Makefile, src/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/UnzipDirectoryChildren.cs
Make build more verbose, should detailed information be needed and make sure it doesn't break if target files exist when unzipping SDK/NDK/etc
=> Build stuff

src/Mono.Android/metadata, src/Mono.Android/methodmap.csv
These fixes are to eliminate API diff, namely eliminating removal of types, methods and fields after merging N API.
=> Fix API "breakage" that N support has brought in

build-tools/mono-runtimes/mono-runtimes.targets
Those were added as part of the netstandard effort.
=> Add new assemblies to mono-runtimes.targets

Configuration.Override.props.in, Configuration.props, README.md, src/Xamarin.Android.Build.Tasks/Mono.Android/ActivityAttribute.Partial.cs, src/Xamarin.Android.Build.Tasks/Mono.Android/ApplicationAttribute.Partial.cs, src/Xamarin.Android.Build.Tasks/Mono.Android/BroadcastReceiverAttribute.Partial.cs
DO NOT MERGE THIS without merging https://github.com/xamarin/java.interop/pull/56
(But note that the PR also depends on THIS PR itself! So you cannot skip this PR!)
This also depends on https://github.com/xamarin/xamarin-android/pull/127
=> Add new manifest attributes for Android N API.

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/ApplyPreserveAttribute.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/PreserveRuntimeSerialization.cs
- this fixes #36697, #36710
- it preserves stuff marked by DataContract and DataMember
attributes, which might be linked away otherwise, because
serialization code uses a lot of reflection (see bellow)
- it is based on xamarin-macios linker code from MobileMarkStep and
ApplyPreserveAttribute
- this commit fixes the bugs mentioned above. it has shortcoming
though, because it doesn't preserve fields, events and custom
attributes on properties. I plan to fix that by unifying
MonodroidMarkStep with macios's MobileMarkStep code
- this is how the reflection is used (backtraces from #36697, where
properties methods were missing in KeyValue`2 type)
get_Key backtrace:
08-10 18:54:40.576 19435 19456 I mono-stdout: KeyValue Key get
08-10 18:54:40.576 19435 19456 I mono-stdout:   at …
=> [linker] preserve more parts for the serialization

src/Xamarin.Android.Build.Tasks/Mono.Android/LayoutAttribute.Partial.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.NamingCustomAttributes/Android.App/LayoutAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Xamarin.Android.NamingCustomAttributes.projitems
"With Android N, the <layout> manifest element supports several attributes that affect how an activity behaves in multi-window mode:"
https://developer.android.com/preview/features/multi-window.html
=> Add LayoutAttribute and support MSBuild type for Android N.

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Commit a8f7db05 [broke the *Release* build][0]:
Mono.Android/LayoutAttribute.Partial.cs(24,6): error CS1593: Delegate `System.Action<Android.App.LayoutAttribute,object>' does not take `1' arguments
Mono.Android/LayoutAttribute.Partial.cs(25,6): error CS1593: Delegate `System.Func<Android.App.LayoutAttribute,string>' does not take `2' arguments
Mono.Android/LayoutAttribute.Partial.cs(29,6): error CS1593: Delegate `System.Action<Android.App.LayoutAttribute,object>' does not take `1' arguments
Mono.Android/LayoutAttribute.Partial.cs(30,6): error CS1593: Delegate `System.Func<Android.App.LayoutAttribute,string>' does not take `2' arguments
Mono.Android/LayoutAttribute.Partial.cs(34,6): error CS1593: Delegate `System.Action<Android.App.LayoutAttribute,object>' does not take `1' arguments …
=> [Xamarin.Android.Build.Tasks] Define `ANDROID_24` in Release builds

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets
=> [msbuild] switch the default binding jar parser to class-parse.

build-tools/mono-runtimes/mono-runtimes.props
commit b4b21d081b03318a07e3ae2220b365b79e1fcec8
Author: Martin Baulig <martin.baulig@xamarin.com>
Date:   Fri Sep 30 11:46:46 2016 +0200
[BTLS]: Add the native BTLS sources.
(cherry picked from commit c950be01aca0ecce9b5f68b9f4430e99ecc51037)
=> Bump Mono to build with the native BTLS sources

src/Mono.Android/metadata
Our internal build should switch more to this OSS repo and this file
has to give more love on the other land...
=> [Mono.Android] simplify merge.SourceFile matching and fix internal builds.

src/Mono.Android/Android.Runtime/JNIEnv.cs
Previously we would simply call `Dispose` on each object surfaced to the runtime before shutdown so that no finalizer code could be run into a dead appdomain.
Unfortunately, because `Dispose` naturally calls `Dispose(bool)` before doing any low-level cleanup, user code can potentially throw exceptions which prevent the operation from happening correcly and (currently) triggers a process crash because of the unhandled exception.
This is the case when in the context of the Xamarin.Forms previewer where XF objects usually implement their own Dispose mechanism. Due to the "flat" nature of our cleanup loop, it may happen that we call `Dispose` on a XF object that in its own `Dispose(bool)` implementation also tries to invoke `Dispose` on an underlying object. The issue is that we may have …
=> [Mono.Android] Add a manual dispose fallback path when calling Dispose on a surfaced object fails

Configuration.props, build-tools/android-toolchain/android-toolchain.projitems, build-tools/scripts/BuildEverything.mk
Install API-25 `android.jar`, Build API-25/v7.1 `Mono.Android.dll`.
=> [build] Install API-25 android.jar, Build API-25 bindings

src/Xamarin.Android.Build.Utilities/AndroidVersion.cs
Increments the MaxApiLevel value, and adds a new entry to KnownVersions for API level 25.
=> Add API level 25 to known versions

src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs
The recent commit 7d8bb92b reworked the Aot task to run the cross
compilers in parallel. However this commit did NOT take into account
that the MSBuild Logger does not like being used from other threads.
So from the command line we end up with exceptions being raised (occasionally)
from the Logger. I suspect within VS that patch would have caused a
complete IDE lockup. This is because VS does not like it when you
Log messages/errors from a thread other than the UI thread.
This commit reworks the Aot Task to derive from the AsyncTask. This
task implements a number of helper methods which resolve the
Logger/UI Thread issues.
=> [Xamarin.Android.Build.Tasks] Fix the Aot Task to work correctly on background threads.

src/monodroid/jni/monodroid-networkinfo.c
Mono parses `/etc/resolv.conf` on Unix systems in order to retrieve the list of
DNS server IP addresses and return it from the
`IPInterfaceProperties.DnsServers` property.
On Android, however, `resolv.conf` doesn't exist and in consequence the DNS
server list is never populated. Instead, on Android we need to read the IPs from
the system properties named `net.dnsX` where X is a number between 1 and 8,
inclusive.
This code implements the XA side of the fix.
Part 1 of fix for https://bugzilla.xamarin.com/show_bug.cgi?id=48016
[Part 2 of the fix](https://github.com/grendello/mono/commit/df4b5520091dd67caaee722c58ae8caf089a1d51) (I will open a PR with Mono as soon as this PR is merged)
=> Query Android for DNS server addresses

src/Mono.Android/Android.App/SyncContext.cs
Under designer context, a main looper is created and destroyed for each render. This means that an asynchronous operation that tries to marshal back to the main thread after it has finished executing will never behave properly as it may happen while in a limbo state where no current looper is present.
The result is that Android views that are coded like this:
```csharp
async void Initialize ()
{
Text = await GetLabelAsync ();
}
async Task<string> GetLabelAsync ()
{
await Task.Delay (5);
return "Foo";
}
```
Will fail because upon calling `Android.App.SyncContext.Post` the main looper will be gone causing an NRE at runtime. This has the consequence of killing the designer rendering process seemingly randomly after a layout is rendered.
There is no proper way to fix this on our side, it's …
=> [Mono.Android] Add null check to avoid crash in Android's SynchronizationContext in the designer

src/Xamarin.Android.Build.Tasks/Resources/StubApplication.java
Android N seems to have changed ResourceManager internals so that now
there is ResourcesImpl class that is to handle several resource accesses.
That unfortunately impacts our fast deployment implementation, which
works like InstantRun and faces the same kind of problems; it needs to
access nonpublic framework internals.
To catch up and workaround the issue, now access to those fields are
two folds for AssetManager and optional for resources.
Resource access on Android N may need further fixes, but so far it
does not crash at startup anymore.
=> [msbuild] fix StubApplication access to private fields.

src/Xamarin.Android.NUnitLite/Gui/Instrumentations/TestSuiteInstrumentation.cs
=> [nunit] make sure the test results path exist

src/Mono.Android/Mono.Android.csproj, src/Xamarin.Android.NUnitLite/Xamarin.Android.NUnitLite.csproj
- added NET_2_0 to the Mono.Android.dll compilation
- removed SILVERLIGHT from NUnitLite compilation in Release
configuration
=> [build] modify defines to be API compatible with monodroid

src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs
AndroidHttpHandler invokes the Java HTTP client to do its actual work and the
Java code must not run on the main thread lest it throws an exception. In most
cases the handler does the right job, the exception being a handful of
HttpClientConnection.Disconnect calls invoked directly in the handler code as
well as from a cancellation token callback.
This commit makes sure we don't run any of the Java code on the main thread by
wrapping the calls in a task.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=51774
=> Ensure no Java network code runs on the main thread

src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocumentElement.cs
This is to pull in cecil/d0cb2b78.
=> Bump to Java.Interop/b55fa216

build-tools/scripts/BuildEverything.mk
- do not hardcode building Debug and Release configurations
everytime
=> [build] build only specified configurations

Configuration.props, build-tools/scripts/BuildEverything.mk, build-tools/scripts/JavaCallableWrappers.targets, src/Mono.Android/Mono.Android.csproj, src/Mono.Android/Mono.Android.targets, src/OpenTK-1.0/OpenTK.csproj
- generate, build and add Java callable wrapper(s) for OpenTK and
merge them into mono.android.jar
=> [opentk build] update mono.android.jar with jcw for OpenTK

src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs
Currently when automatic redirection is disabled and a request is made that
receives a redirect code in response we ignore the content and the headers. This
is incorrect as such a response is a valid one and the client might want to
handle redirection on their own, using the information contained in response
headers.
This commit makes sure that all the headers, as well as cookies, are present in
the response message returned to the caller.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=50587
=> Grab response content on redirects with AllowAutoRedirect == false

build-tools/api-xml-adjuster/.gitignore, build-tools/api-xml-adjuster/Makefile, build-tools/api-xml-adjuster/README.md, build-tools/api-xml-adjuster/api-xml-adjuster.csproj
And add brief README.md for public repo.
And fix intermediary directory for csproj.
=> import Mono.Android api-*.xml.in generator makefile from monodroid

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/SystemUnzip.cs
It's a time of transition: Before 76be1fb1, we built with mono 4.8 and
generated `.mdb` files for debug symbols. With 76be1fb1, we build with
mono 4.9 and generate Portable `.pdb` files for debug symbols.
If you always build from a clean slate, as Jenkins does, this is fine.
If you *don't* build from a "clean" slate, you might discover that
you're re-building `build-tools/mono-runtimes` (!):
Target _BuildUnlessCached needs to be built as input file '.../xamarin-android/external/mono/autogen.sh' is newer than output file '../../bin/Debug//lib/mandroid/mono-symbolicate.exe.mdb'
...
Target _BuildRuntimes needs to be built as input file 'obj/Debug//host-Darwin/.stamp' is newer than output file 'obj/Debug//x86/mono/btls/build-shared/libmono-btls-shared.so'
For example, when building …
=> [xa-prep-tasks] Delete vestigial debug symbol files

build-tools/bundle/bundle-path.targets, build-tools/mono-runtimes/mono-runtimes.targets
- so that we don't have to build it in the monodroid
=> [mono-runtimes] add mkbundle.exe to the bundle

build-tools/xa-prep-tasks/xa-prep-tasks.targets
Write out Xamarin.Android Version information into the files:
* `bin/$(Configuration)/Version`: The major.minor.build value for
Xamarin.Android, which is the `$(ProductVersion)` value.
* `bin/$(Configuration)/Version.commit`: The branch+commit that the
product was built from.
* `bin/$(Configuration)/Version.rev`: The revision value; the number
of commits since `$(ProductVersion)` changed.
=> [xa-prep-tasks] Create Version, Version.commit, Version.rev

src/Xamarin.Android.NUnitLite/Gui/Instrumentations/TestSuiteInstrumentation.cs
This was part of https://github.com/xamarin/monodroid/pull/524 but apparently got lost in the move to the open repo.
=> [tests] Output number of run tests in TestSuiteInstrumentation

.gitmodules, build-tools/enumification-helpers/methodmap.ext.csv, src/Mono.Android/methodmap.csv
Fix NotificationVisibility enumification.
Bump to xamarin-android-api-compatibility/d15-4/64714d84.
=> [Mono.Android] Fix NotificationVisibility enumification.

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs
Make sure the methods required by the debugger are not linked out. Fixes #59516.
Note that this commit doesn't fix the assert reported in #59015 on
Android as it happens with linker turned off as well. So that will
need another fix.
=> [linker] port #59015 fix to XA

.gitmodules
Context: https://bugzilla.xamarin.com/show_bug.cgi?id=59281
Context: https://bugzilla.xamarin.com/show_bug.cgi?id=59364
Context: https://bugzilla.xamarin.com/show_bug.cgi?id=59832
=> Bump to mono/dev15-5-2017-06/fbc487ff

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs
It fixes issues seen in Bcl_Tests in Release configuration, like this failure:
INSTRUMENTATION_RESULT: failure: MonoTests.System.Data.SqlClient.SqlParameterTest.SqlTypes_SqlXml=System.TypeInitializationException : The type initializer for 'System.Data.SqlTypes.SqlXml' threw an exception.
----> System.NullReferenceException : Object reference not set to an instance of an object
at MonoTests.System.Data.SqlClient.SqlParameterTest.SqlTypes_SqlXml () [0x0000f] in <d3fe7682843340618220fc60464eade1>:0
at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] …
=> [linker] backport a linker fix from macios

src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs
In order to speed up the processing of resources we should
make use of the R.txt files which are generally included with
.aar files and our components.
One advantage with this is we get the actual resource id which
is used by android. But it also means that when we do find an
R.txt file we can skip the processing of ALL resources in that
underlying `res` folder. Note this will only apply to the
ManagedResourceParser.
=> [Xamarin.Android.Build.Tasks] Use R.txt for Managed Resource Parser

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-pr-builder/2221/testReport/
This fixes two failing tests, which I tested under MSBuild and XBuild:
- `BuildWithExternalJavaLibrary` - fixed path to
`android-support-multidex.jar` under xbuild
- `CheckLibraryImportsUpgrade` - with the re-save logic added, the
`__library_projects__` directory is deleted on a second build. I think
this is a good interaction, perhaps the project wasn’t re-saving on
MacOS either.
=> [tests] fix Xamarin.Android.Build.Tests

build-tools/bundle/bundle-path.targets, build-tools/mono-runtimes/mono-runtimes.targets
Also added bundle version property, to avoid setting it in multiple
places.
https://github.com/xamarin/xamarin-android/issues/1093
=> [bundle] Add linkeranalyzer.exe to the bundle

src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/1151
Each Activity must have a default constructor or it won't be possible to
instantiate it from the android manifest. Should the constructor be missing we
currently report the fact in a way that doesn't tell the developer where the
error occured. This is not very helpful.
This commit adds code to add the location of the offending source code, if
available, as well as changes the way we report the error - we no longer throw
an exception but instead define a new error code, XA4213, and report it using
the standard MSBuild logger.
=> Better report on location of an Activity without default constructor

src/Xamarin.Android.Build.Tasks/Tasks/Desugar.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
as per https://github.com/xamarin/xamarin-android/issues/1133.
=> [msbuild] Add --min-sdk-version argument to desugar tool 

tests/BCL-Tests/Xamarin.Android.Bcl-Tests/nunit-excluded-tests.txt
And enable the SaveTest again for Release configuration.
=> Bump mono to fix #1186

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, tools/scripts/illinkanalyzer
It executes our copy of linker analyzer tool, which is included in the
runtime bundle.
=> [scripts] Add illinkanalyzer script

build-tools/bundle/bundle-path.targets, build-tools/mono-runtimes/mono-runtimes.projitems, build-tools/mono-runtimes/mono-runtimes.targets
The aot profiler will be used to generate aot profiles for "profiled" AOT builds. Note that we don't have an infrastructure for "profiled" AOT builds yet.
I plan to test the "profiled" AOT to have an idea what apk sizes and startup times to expect.
=> [bundle] Include aot profiler in the bundle

Configuration.props, build-tools/android-toolchain/android-toolchain.projitems, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
If it builds then this should fix https://github.com/xamarin/xamarin-android/issues/1266
=> bump android SDK components for Android 8.1.

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Xamarin.Android.Windows.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/1286
=> Cherry-pick fix for #1286

src/Mono.Android/Test/Properties/AndroidManifest.xml, tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Properties/AndroidManifest.xml, tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Properties/AndroidManifest.xml, tests/locales/Xamarin.Android.Locale-Tests/Properties/AndroidManifest.xml
NDK r16 supports a minimum platform version of 14.
=> [tests] Bump minSdkVersion to 14

src/Mono.Android/Test/Xamarin.Android.Net/AndroidClientHandlerTests.cs, src/Mono.Android/Test/Xamarin.Android.Net/HttpClientIntegrationTests.cs
The formatting was totally messy, make it conform to the XA coding style
=> Reformat AndroidClientHandler test sources [whitespace only commit]

tools/xabuild/XABuild.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1497421&tab=ms.vss-test-web.test-result-details
The fix in #1411 was not quite good enough. It works "most of the time",
but I found a couple instances where a random test failed on VSTS due to
this issue. I could also test this scenario by clearing the symlinks and
`.__sys_links.txt` and running the `BuildTest.RunXABuildInParallel`
test. This test would pass most times, but you could see something odd by
looking at the contents of `.__sys_links.txt`, it would have duplicate
symlink names listed.
So I took another approach:
1. Before checking for the existance of the symlinks, hold the
`.__sys_links.txt` file open
2. Check for each missing symlink, create it if needed
2. Write to `.__sys_links.txt` after each check is …
=> [xabuild.exe] better fix for multi-process file access

src/Mono.Android/Android.Runtime/ResourceIdManager.cs
There were quite a few LINQ expressions in here, that could be rewritten
to simple `foreach` loops. The new code should have fewer allocations.
I also updated the usage of `MethodInfo.Invoke` to use `CreateDelegate`
instead, as it is an order of magnitude faster to call the method in
this way.
Lastly, I added a null check to the return value of `GetMethod`, because
it is *technically* possible for a class to exist with the
`ResourceDesignerAttribute` but be missing an `UpdateIdValues` method.
These changes should give us a *very slight* performance improvement to
startup.
=> [Mono.Android] remove LINQ usage in ResourceIdManager

build-tools/android-toolchain/android-toolchain.csproj, build-tools/android-toolchain/android-toolchain.projitems, build-tools/android-toolchain/android-toolchain.targets, build-tools/scripts/PrepareImageDependencies.targets, src/mono-runtimes/mono-runtimes.projitems, src/mono-runtimes/mono-runtimes.props, src/mono-runtimes/mono-runtimes.targets
https://github.com/mono/mono/issues/6889
=> [mono-sdks] Use for mxe-Win32, mxe-Win64, llvmwin32, llvmwin64 and android toolchain

src/Mono.Android/Android.Runtime/AndroidRuntime.cs, src/Mono.Android/Android.Runtime/JNIEnv.cs
The new code uses `JniTypeManager`'s `RegisterNativeMembers` method to
register native marshaling methods. The type manager itself uses the
register method generated by *jnimarshalmethod-gen* tool or method(s)
of the given type, which have
`JniAddNativeMethodRegistrationAttribute`.
When no such register method exists (`registered` = *false*), we
fallback to the original (old) code.
Example register method generated by the *jnimarshalmethod-gen* tool:
```
[JniAddNativeMethodRegistration]
public static void __RegisterNativeMembers (JniNativeMethodRegistrationArguments args)
{
args.AddRegistrations (new JniNativeMethodRegistration[] {
new JniNativeMethodRegistration ("n_onCreate", "(Landroid/os/Bundle;)V", new Action<IntPtr, IntPtr, IntPtr> …
```
=> [Android.Runtime] Use JniTypeManager to register natives

src/mono-runtimes/mono-runtimes.projitems, src/mono-runtimes/mono-runtimes.targets
Will hopefully allow LLVM to be configured on Linux...
=> [mono-sdks] Pass the Host{Cc,Cxx}{32,64} parameters (Take 2!)

Documentation/guides/LayoutCodeBehind.md
Update to contain more examples.
=> [docs] Update the LayoutCodeBehind documentation

Documentation/guides/messages/xa0000.md, Documentation/guides/messages/xa0030.md, Documentation/guides/messages/xa0031.md, Documentation/guides/messages/xa0032.md, Documentation/guides/messages/xa0033.md, Documentation/guides/messages/xa0034.md, Documentation/guides/messages/xa5205.md, src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs
Add Warning codes and docs for ResolveSdksTask.
=> [Xamarin.Android.Build.Tasks] ResolveSdksTask Warning Codes

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
Context https://github.com/xamarin/xamarin-android/issues/1670
=> Dont use the Managed Parser on Mac

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildItem.cs
Context: http://build.devdiv.io/1749980
On VSTS, the `BindingBuildTest.BindingCheckHiddenFiles` test is
failing due to two tests trying to download the same file to a
temporary location on disk at the same time:
EXEC : 1) error : Xamarin.Android.Build.Tests.BindingBuildTest.BindingCheckHiddenFiles(False) [D:\a\1\s\Xamarin.Android.sln]
System.IO.IOException : The process cannot access the file 'C:\Users\VssAdministrator\AppData\Local\Xamarin.ProjectTools\mylibrary.aar' because it is being used by another process.
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, …
=> [tests] fix concurrency issue with temporary downloaded files

Documentation/building/unix-instructions.md, Documentation/building/windows-instructions.md, Makefile, build-tools/scripts/RunTests.targets
Add the ability to list the unit tests via `make` or `msbuild`.
Added docs on how to run single tests.
=> [build] Add `list-nunit-tests` and docs

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
When running tests in Visual Studio's test runner UI (Windows and
macOS), a test failure causes an unpleasant experience...
Since the entire MSBuild diagnostic log is contained in
`FailedBuildException`, the UI will hang anywhere from 30 seconds to 1
minute while it tries to render the exception details in the IDE.
The solution here is to:
- Detect if the unit test is running inside an IDE
- Don't include the build log in the exception details in this case
On Windows, we can detect the test running by the process name, which
is either `testhost.x86` or `testhost.x64`.
On macOS, we can detect VS for Mac by looking for the
`MONO_GAC_PREFIX` environment variable, which points to
`/Applications/Visual Studio.app/Contents/Resources` by default.
If neither of these cases are met, such as …
=> [Xamarin.Android.Build.Tests] prevent build logs locking up IDEs

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/DownloadUri.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/1810
We can implement `ICancelableTask` in order to make `DownloadUri`
cancellable. `CancellationTokenSource` and `async/await` make this
really simple to implement, as we mostly just need to use the
appropriate cancellable overloads of async methods.
So now if you Ctrl+C during the build, on a line such as:
Downloading `https://xamjenkinsartifact.azureedge.net/xamarin-android/xamarin-android/bin/Debug/bundle-v21-h747933dd-Debug-Darwin-libzip=b95cf3f,llvm=bdb3a11,mono=f3235f3.zip`
It will cancel immediately with the failure:
"xamarin-android\Xamarin.Android.sln" (Prepare target) (1) ->
"xamarin-android\build-tools\download-bundle\download-bundle.csproj" (default target) (4) ->
(_DownloadBundle target) ->
warning MSB4018: The …
=> [xa-prep-tasks] DownloadUri is now cancellable

Documentation/guides/messages/adb0000.md, Documentation/guides/messages/adb0010.md, Documentation/guides/messages/adb0020.md, Documentation/guides/messages/adb0030.md, Documentation/guides/messages/adb0040.md, Documentation/guides/messages/adb0050.md, Documentation/guides/messages/adb0060.md
Context: http://work.devdiv.io/641042
Context: https://github.com/xamarin/monodroid/pull/804
Documented the current set of error codes we emit for ADB.
=> [docs] ADB error codes

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Extensions.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs
Linker wasn't preserving jni marshal methods for all the marked
methods. As an example, `IUncaughtExceptionHandlerInvoker` type lost
its `__<$>_jni_marshal_methods` nested type during linking as we
didn't find registration attribute on `UncaughtException` method.
That led to falling back to the old registration code with a lot of
reflection usage.
=> [linker] Preserve the jni marshal methods for all marked methods

src/Mono.Android/Android.Runtime/AndroidRuntime.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs
Fixes https://github.com/xamarin/xamarin-android/issues/1898
Measured results for XA template start-up (x86 emulator):
| RegisterNativeMembers | Before | After | After with new marshal methods |
|-----------------------|-------:|------:|-------------------------------:|
| Debug                 |  169ms |  33ms |                            N/A |
| Release               |   56ms |  18ms |                            8ms |
For more comparison, RegisterNativeMembers in the 15.8/Release takes
27ms.
The `JniTypeManager:TryRegisterNativeMembers` was quite slow, it used
reflection to find the registration method at runtime.
The new implementation finds the method during build in the Linker and
emits code to prefill a dictionary and to call the registration
methods at runtime.
That removes most of …
=> [Mono.Android] Faster native members registration

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/UnzipDirectoryChildren.cs
The lines are all messed up because the underlying unzip command uses 2 steps to print a line: first the line content, then the '\n'. This can race across processes and makes the output quite hard to read.
This fixes that by making sure we print the whole "line+'\n'" at the same time. This doesn't completely reduce the chance of broken line, but it greatly reduces it anyway.
=> [Xamarin.Android.Tools.BootstrapTasks] Make output of UnzipDirectoryChildren less messy

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ResolveSdksTaskTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
Add a helper method to detect the Ndk Directory.
=> [Xamarin.Android.Build.Tasks] Create a Faux ndk directory.

src/Mono.Android/Test/Xamarin.Android.Net/AndroidClientHandlerTests.cs
We often see networ test "failures" caused by unreachability of one of the
servers those tests use. This creates false negatives since this is not really
the test failing but rather the environment not being correct and preventing the
test from performing its actual task.
This commit catches the `WebException` thrown in connection failed cases and
merely ignores the test instead of failing it. Full exception message and stack
trace is printed as part of the ignore message.
=> [Tests] Make network tests a bit more resilient

src/Mono.Android/Test/Xamarin.Android.Net/AndroidClientHandlerTests.cs
The previous
commit (https://github.com/xamarin/xamarin-android/commit/608d950a703ddb527258565c2a0705aa37f71789)
solved only part of the issue with network tests which fail on connection to a
test server. Not only one test was left without any code to catch failed
connection attempts, all the other tests failed to catch a connection issue in
situations when the Java backend tries to connect to the server only after the
managed code attempts to wait on or obtain the result of the request from the
asynchronous task running the request.
This commit *should* solve the remaining problems.
=> [Tests] More resilient network tests, take 2

src/mono-runtimes/mono-runtimes.targets
Supports https://github.com/mono/mono/issues/10768
=> Adds facades which might override default nuget version to framework list

Documentation/guides/BuildProcess.md
Added AndroidGenerateJniMarshalMethodsAdditionalArguments description
to the build process page.
=> [Documentation] Document recently added property

Configuration.props, Makefile, build-tools/dependencies/dependencies.projitems
hopefully helps to identify the msbuild hang with mono
Context: https://github.com/mono/mono/pull/11706 & https://github.com/xamarin/xamarin-android/pull/2357
/cc @luhenry
=> [do-not-merge] use a 5.16 debug build

src/monodroid/CMakeLists.txt, src/monodroid/jni/logger.c, src/monodroid/jni/logger.h, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/util.h, src/monodroid/jni/xamarin_getifaddrs.cc
Second part of implementation of
https://github.com/xamarin/java.interop/issues/397
=> [monodroid] Move XA specific logger code back from JI

src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs
Fixes: http://feedback.devdiv.io/346386
It was reported that cancelling a build while AOT was running, would
not cancel until AOT finished. Testing in VS Windows 15.9, I could
reproduce this behavior.
Reviewing the `<Aot/>` MSBuild task, it had use of a
`CancellationTokenSource` that killed the AOT processes if cancelled.
However, this did not work as intended, since the
`CancellationTokenSource` is a local variable and the `Cancel` method
can't call it.
When MSBuild tasks are cancelled, if they implement `ICancelableTask`,
the `Cancel` method will be called. `AsyncTask` has a proper
implementation of this, as well as a `Token` property for use with the
TPL. I removed the `CancellationTokenSource` from `<Aot/>`, in favor
of what is already implemented in `AsyncTask`.
I suspect that …
=> [Xamarin.Android.Build.Tasks] fix <Aot/> cancellation

src/Mono.Android/Mono.Android.targets
Changes: https://github.com/xamarin/java.interop/compare/706e4cc...b57d770
[Java.Interop] Target .NET Standard 2.0
[jcwgen] add public method for GetDestinationPath
=> Bump to xamarin/java.interop/master@b57d770

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs
@grendello noticed his machine had leftover files in `$tmp` such as:
$ unzip -l tmpfef1f4c.tmp
Archive:  tmpfef1f4c.tmp
Length      Date    Time    Name
---------  ---------- -----   ----
528  1980-01-01 01:00   AndroidManifest.xml
388  1980-01-01 01:00   res/anim/abc_fade_in.xml
388  1980-01-01 01:00   res/anim/abc_fade_out.xml
852  1980-01-01 01:00   res/anim/abc_grow_fade_in_from_bottom.xml
508  1980-01-01 01:00   res/anim/abc_popup_enter.xml
These seemed suspicious -- as if they came from something in
Xamarin.Android's MSBuild tasks.
After reviewing more logs, we found they were coming from
`<Aapt2Link/>`:
Task "Aapt2Link"
Executing link --manifest Xamarin.Forms-Performance-Integration/Droid/obj/Debug/lp/19/jl/res/../manifest/AndroidManifest.xml --java obj/Debug/android/src -R …
=> [Xamarin.Android.Build.Tasks] <Aapt2Link/> could leave behind temp files

Makefile
Context: https://github.com/xamarin/xamarin-android/issues/2562
Downstream in monodroid, we got a failure such as:
msbuild /p:Configuration=Release /p:AutoProvision=True /p:AutoProvisionUsesSudo=True /p:IgnoreMaxMonoVersion=False /p:XARepositoryName=monodroid /p:XAVersionCommitCount=3 /p:ProductVersion=9.2.99 /p:XAVersionHash=48c518f4d /p:XAVersionBranch=HEAD /v:d /t:Restore Java.Interop.sln
...
external/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop.csproj : error MSB4244: The SDK resolver assembly "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/SdkResolvers/Microsoft.Build.NuGetSdkResolver/..\..\Microsoft.Build.NuGetSdkResolver.dll" could not be loaded. Invalid Image
My guess here (similar to #2562), is that we need to upgrade Mono …
=> [build] dependencies.csproj before NuGet restore

Novell/MonoDroid.FSharp.targets, Novell/Novell.MonoDroid.CSharp.targets, Novell/Novell.MonoDroid.Common.targets
Commit 55ba7474 seems to have added the Novell
targets back into the repo. We need to remove
them again.
=> [Novell] Remove Novell/*.targets

build-tools/automation/build.groovy
Extracted common code into a helper function `stageWithTimeout()`, making the build script easier to read (suppress whitespace changes if you're looking at the diff).
=> Improve Jenkins pipeline build.groovy

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs
Context: http://build.devdiv.io/2415088
In fe0ae91fd, we moved the Android designer's MSBuild targets into
this repository.
There is one test that has been randomly failing:
DesignerTests.SetupDependenciesForDesigner
It was using the same temp directory name as
`CustomDesignerTargetSetupDependenciesForDesigner`, so the two tests
were stepping on each other.
After looking at it, the `SetupDependenciesForDesigner` just seemed
duplicative. We only had it because the designer targets weren't
present in this repo. I removed this test.
I also cleaned up the usage of:
parameters: new [] { "DesignTimeBuild=True", "AndroidUseManagedDesignTimeResourceGenerator=False" })
All designer calls need these, so I declared the `string[]` as a
static variable.
=> [tests] cleanup DesignerTests a bit

Xamarin.Android.sln, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, tools/jit-times/MethodInfo.cs, tools/jit-times/Program.cs, tools/jit-times/Properties/AssemblyInfo.cs, tools/jit-times/README.md, tools/jit-times/Timestamp.cs, tools/jit-times/jit-times.csproj, tools/jit-times/packages.config, tools/scripts/jit-times
Original project: https://github.com/radekdoulik/jit-times/
Also add jit-times script to ease the use of it
=> [tools] Add jit-times tool

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
This reverts commit 0c7d8fd4425c24bf9d073936d621dd12464ee7a0.
=> Revert "[Xamarin.Android.Build.Tasks] AndroidUseAapt2 defaults to False

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/GitBranch.cs
Our current branch name identification logic does not work well when
building in CI, and seemingly always returns `HEAD` for builds
occurring on Jenkins.
In an attempt to fix this, we'll now use @kzu's
[git branch name identification logic][0], which involves attempting
to read the branch name from `$(XamarinAndroidSourcePath)/.git/HEAD`
before invoking (as a fallback):
git name-rev --name-only --exclude=tags/* HEAD
This "try `.git/HEAD` then `git name-rev`" approach allows us to get
useful branch names even in a "detached HEAD" state, which is typical
for our CI builds on Jenkins.
Some examples of output differences; compare the previous command:
git rev-parse --abbrev-ref HEAD
* Local branch: `gitbranch-detached`
* Merge commit: `HEAD`
* Detached HEAD: `HEAD`
* Submodule: `HEAD`
to the …
=> [prep-tasks] Fix git branch name identification

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
Context: http://build.devdiv.io/2558223
We have had a couple cases where our tests timed out:
RunNUnitTests:
packages\NUnit.ConsoleRunner.3.9.0\tools\nunit3-console.exe --trace=Verbose E:\A\_work\1366\s\build-tools\scripts\..\..\bin\TestRelease\Xamarin.Android.Build.Tests.dll  --labels=all --result="TestResult-Xamarin.Android.Build.Tests.xml;format=nunit2" --output="bin\TestRelease\TestOutput-Xamarin.Android.Build.Tests.txt"
...
Attempting to cancel the build...
...
[error]The task has timed out.
Looking at the NUnit log:
InternalTrace: Initializing at level Debug
09:39:55.704 Debug [ 5] DefaultTestAssemblyBuilder: Loading E:\A\_work\1366\s\bin\TestRelease\Xamarin.Android.Build.Tests.dll in AppDomain domain-
09:39:55.712 Debug [ 5] DefaultTestAssemblyBuilder: Examining assembly for test …
=> [tests] potential fix for hang in MSBuild tests on Windows

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/ProcessLogcatTiming.cs
Add special-case handled measurement of activity displayed message
from Android Activity manager.
We have special case code for that, because our normal message
measurements come from the app process, while the activity manager is
a separate process and thus would not be matched by our timing
definitions, which use the PID to pre-filter the matches.
The activity manager adds message to the log when activity is
displayed. We hope that this corelates with actual time the activity
is displayed on screen and thus is interesting time to measure.
The activity messages look like this:
04-05 15:50:00.421  1201  1239 I ActivityManager: Displayed com.google.android.deskclock/com.android.deskclock.alarms.AlarmActivity: +136ms
04-05 16:00:01.157  1201  1239 I ActivityManager: Displayed …
=> [tests] Measure activity displayed time

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/CheckoutExternalGitDependency.cs
I don't use SSH on Windows, and so the current behavior wasn't working
for me. I was getting errors such as:
Cloning into 'C:\src\xamarin-android\\external\monodroid'...
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Errors
C:\src\xamarin-android\build-tools\xa-prep-tasks\external-git-dependencies.targets(17,5): error MSB6006: "git.EXE" exited with code 128. [C:\src\xamarin-android\build-tools\xa-prep-tasks\xa-prep-tasks.csproj]
C:\src\xamarin-android\build-tools\xa-prep-tasks\external-git-dependencies.targets(17,5): error MSB6003: The specified task executable "git.EXE" could not be run. System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
at …
=> [xa-prep-tasks] support https for git clone

Documentation/workflow/UsingYourBuild.md
The path of generated xabuild was wrong.
=> Fixing xabuild path on UsingYourBuild.md

build-tools/automation/build.linux.groovy
It's 100G, vs 30G for /. Should run out of disk less.
=> Install Android stuff to /mnt not /home

build-tools/automation/build.linux.groovy
=> Add packages newly required

build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/mono-runtimes/mono-runtimes.targets
Extracted from https://github.com/xamarin/xamarin-android/pull/3039
=> [mono-runtimes] Use pdb2mdb from bundle

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, src/Mono.Android/Profiles/api-29.params.txt
Add Android API-Q preview 3 binding 
- Updated Toolchain to download new version
- Updated api-29.params.txt file with preview 3 content
=> Switch to API Q preview 3.

.external
Changes: https://github.com/xamarin/monodroid/compare/a4a3a8d720e4aa5b50ea4c2ffd704754421bfbfc...76146a95c8816a8be8f730a0bf63030f76c85e26
$ git diff --shortstat a4a3a8d..76146a95
2 files changed, 2 insertions(+), 2 deletions(-)
Changes: https://github.com/xamarin/android-sdk-installer/compare/d551a34bac028e30272d2dc2009fb6117c390395...4c4daa52814587b6f28eb634847d05102dafc8df
Changes: https://github.com/xamarin/androidtools/compare/ffda2bb7aa2a4f62bab85800064d5bcaf4804012...ffda2bb7aa2a4f62bab85800064d5bcaf4804012
Fixes: http://work.devdiv.io/615336
Fixes: http://work.devdiv.io/915731
=> Bump to xamarin/monodroid/master@76146a95

build-tools/xaprepare/xaprepare/Steps/Step_Android_SDK_NDK.cs
Sometimes packages may get corrupted on disk in which case we should delete them
from the cache directory and re-download them. The verification step should be
done before installation starts, because otherwise an installation failure
exception will be thrown and the entire preparation process will be aborted.
Additionally, if unpacking of a component fails delete the cached archive as
well.
=> Verify each Android SDK package before attempting to install

.external
Changes: http://github.com/xamarin/monodroid/compare/f849c5e...bc0323d
=> Bump to xamarin/monodroid/master@bc0323d

build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/ConfigAndData/Runtimes.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
This reverts commit e1762ea45a972f28bfbeccd804a788a627216927.
WIP
=> Reintroduce Using pdb2mdb from archive

src/Mono.Android/enumflags
bitwise-OR ed values are transferred.
=> Android.Views.Accessibility.Action is a flagged enum

Documentation/release-notes/master.md
The idea for this new `Documentation/release-notes/master.md` file is
that each time a new user-facing bug fix or feature is merged to
`master`, the author(s) of the change will add a corresponding draft
release note to this file.  The note can be added as part of the source
code pull request itself, or it can be added in a separate follow-up
pull request shortly afterward.
If the note for a new feature uses images, the images can be added to
`Documentation/release-notes/images/`.
Authors of new fixes and improvements don't need to do anything special
if their changes get cherry-picked from `master` to a release branch.
The team members who handle final release notes preparation and
publication will copy or move notes as needed from `master.md` to
earlier releases for changes that get …
=> [docs] Add template file for draft release notes

Documentation/building/unix/instructions.md, Documentation/building/windows/instructions.md
My talk at Xamarin Developer Summit 2019 should be a good resource for anyone trying to build Xamarin.Android.
=> [docs] link to "Building Xamarin.Android from Source"

build-tools/xaprepare/xaprepare/Application/Abi.cs, build-tools/xaprepare/xaprepare/Application/LlvmRuntime.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Runtimes.cs
Fixes: https://github.com/mono/mono/issues/15261
Fixes: https://github.com/mono/mono/issues/15262
Fixes: https://github.com/mono/mono/issues/15263
Fixes: https://github.com/mono/mono/issues/15307
Fixes: https://github.com/mono/mono/issues/15751
Fixes: https://github.com/mono/mono/issues/15825
Fixes: https://github.com/mono/mono/issues/15878
Fixes: https://github.com/mono/mono/issues/15887
[w32socket] Translate ELOOP and ENAMETOOLONG
[corlib] Ignore TimeZoneTest.TestCtors on Android GMT
=> Bump to mono/mono/2019-06@893099f2

build-tools/automation/azure-pipelines.yaml
Plus bump up the timeout. Please cherry-pick with a33ac7008df68643d3c25e05955052ee0dc9ed09.
=> Enable Jar signing

.external
Changes: https://github.com/mono/mono/compare/6434153d8b7d20b96e510e43031c5968d4042dda...2c3aeaf3780de7392a0d3cbe4dcf86846eb4dffa
Context: https://github.com/mono/mono/issues/16623
Upstream-Fixes: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/967582
Upstream-Fixes: https://github.com/mono/mono/issues/16034
Upstream-Fixes: https://github.com/mono/mono/issues/16122
Upstream-Fixes: https://github.com/mono/mono/issues/16486
=> Bump to mono/mono/2019-06@2c3aeaf3

.external
Changes: https://github.com/xamarin/monodroid/commit/3ed4b1921a43a6bf5718e82c923040e2512dd8cf
Fix for the random XA5300 error!
=> Bump to xamarin/monodroid/master@3ed4b192

.external, Configuration.props, build-tools/automation/build.groovy
Changes: http://github.com/mono/mono/compare/2c3aeaf3780de7392a0d3cbe4dcf86846eb4dffa...29b1ac19c961b959a09097dbc0fe4cd567cc5298
$ git diff --shortstat 2c3aeaf3..29b1ac19
1528 files changed, 45421 insertions(+), 21967 deletions(-)
Changes: https://github.com/mono/api-doc-tools/compare/d03e819838c6241f92f90655cb448cc47c9e8791...5da8127af9e68c9d58a90aa9de21f57491d81261
$ git diff --shortstat d03e8198..5da8127a
1001 files changed, 86168 insertions(+), 11863 deletions(-)
Changes: https://github.com/mono/api-snapshot/compare/e09042dad3a4cd2e96e790adadd355b0e0c9772d...1ca8e82f51c5f988027e80b59aa59f7748fd0448
$ git diff --shortstat e09042da..1ca8e82f
28 files changed, 612 insertions(+), 217 deletions(-)
Changes: https://github.com/mono/cecil/compare/a6c8f5e1070d25c38cbfaa415d6f6853e5236687...cb6c …
=> Bump to mono/mono/2019-08@29b1ac19 (#3449)

build-tools/automation/azure-pipelines.yaml, src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3651
Also print the response file content to the log for easier
troubleshooting of the AOT
=> [Aot task] Add quotes around the lib paths

.external
Changes: https://github.com/mono/mono/compare/bfbf823ca1129dbfd1ba5b7c066676bf185ed922...6d40f13121e42e41a50b9f2c5eb84983552f0d50
Context: https://github.com/mono/mono/issues/15646
Context: https://github.com/mono/mono/issues/16689
Context: https://github.com/mono/mono/issues/16759
Context: https://github.com/mono/mono/issues/16824
Context: https://github.com/mono/mono/issues/16918
Context: https://github.com/mono/mono/issues/16974
Improve exception filtering within the debugger.
=> Bump to mono/mono/2019-08@6d40f131

build-tools/create-vsix/symbols/ExternalWhiteList.csv, build-tools/create-vsix/symbols/SymbolArchiveWhiteList.csv
Reflects the latest VS changes in http://pr.devdiv.io/205653.
=> [create-vsix] Update whitelist files

Documentation/guides/BuildProcess.md
Fixes #3637
Add documents for `JarsignerTimestampAuthorityUrl` and
`JarsignerTimestampAuthorityCertificateAlias`.
=> [Documentation] Add docs for JarsignerTimestampAuthorityUrl

.github/ISSUE_TEMPLATE/01-building-an-application.md, .github/ISSUE_TEMPLATE/02-running-an-application.md, .github/ISSUE_TEMPLATE/03-ide.md, .github/ISSUE_TEMPLATE/04-mono-android-api.md, .github/ISSUE_TEMPLATE/05-binding-a-java-library.md, .github/ISSUE_TEMPLATE/06-suggestion.md, .github/ISSUE_TEMPLATE/07-other.md
=> [GitHub] Create issue templates to better guide our users filing issues.

.external
Context: https://github.com/xamarin/monodroid/pull/1039
Changes: https://github.com/xamarin/monodroid/compare/ab054acc...dceaee4e
=> Bump monodroid

.external
Changes: https://github.com/xamarin/monodroid/compare/dceaee4ed2a49a81c86bc52b47f07faaf7e4fc13...7f40abfa6f55a801619973af0cb875bf5a58c0c9
Context: https://dev.azure.com/DevDiv/DevDiv/_workitems/edit/998574
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/673872
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/984374
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/994489
Bumps to xamarin/android-sdk-installer/master@ac5a99e1
* Changes: https://github.com/xamarin/android-sdk-installer/compare/b5dfa804522bc6a89a6871519dcb55a5369f1a7e...ac5a99e11840211e05146fe3216c44cfaae317bf
Bumps to xamarin/androidtools/master@efd27324
* Changes: https://github.com/xamarin/androidtools/compare/20ee1ae7f5b8b8891490ec4c63cf0e3d78855ddf...66796669f48f394d1dc56f4045 …
=> Bump to xamarin/monodroid/master@7f40abfa

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
=> Print assembly which was not properly resolved

.external
Changes: https://github.com/xamarin/monodroid/compare/7f40abfa...d23d0864
* Fixes for netstandard projects
* Improvement to deploy times when no device attached
=> Bump to xamarin/monodroid@d23d086

.external
Changes: https://github.com/xamarin/monodroid/compare/533c34ee...1b907d68
Fixes and improvements for Fast Deployment.
=> Bump to xamarin/monodroid/master@1b907d68

Documentation/release-notes/3899.md
Context: https://github.com/xamarin/xamarin-android/pull/3899
This is a first example of a new thing I'm trying to help the team add release notes along the way for all PRs that change user-facing behavior. There isn't any terribly special reason I picked this item as the first example. It was just an item where I saw a notification when the PR was merged, so it reminded me that I could add a release note.
=> [docs] Add release note for PR 3899

Documentation/guides/profiling.md
I thought this was some useful information we didn't have on here.
=> [docs] documented how to use simpleperf for profiling native code

build-tools/debian-metadata/rules
=> Add some moduleref excludes

Documentation/guides/BuildProcess.md, Documentation/release-notes/3964.md, build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Tasks/GetAndroidActivityName.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Application.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/MSBuildDeviceIntegration/Tests/AotProfileTests.cs
Cherry pick the required commits from master and fix small `.csproj` conflict.
=> Backport new AOT profiling targets

src/Xamarin.Android.Build.Tasks/Tasks/RemoveDirFixed.cs
We got report of a failure such as:
XARDF7004: System.ArgumentException: Illegal characters in path.
at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
at Xamarin.Android.Tasks.RemoveDirFixed.RunTask()
at Xamarin.Android.Tasks.AndroidTask.Execute()
XARDF7000: System.ArgumentException: Illegal characters in path.
at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess …
=> [Xamarin.Android.Build.Tasks] improve <RemoveDirFixed/> behavior

Documentation/guides/profiling.md
Describe the simplyfied usage with the new targets.
=> [Documentation] Update the AOT profiling part

.external
Changes: https://github.com/xamarin/monodroid/compare/017b3618bd33689f766e82b5fd640360e4c19919...01a4e0a0c436bf1b0b62acf870cc06e67e62034c
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1033784
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1035905
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/946984
Context: https://github.com/icsharpcode/SharpZipLib/issues/356
* xamarin/monodroid@01a4e0a0c: Bump to xamarin/androidtools/master@2ffbfcb7 (#1074)
* xamarin/monodroid@987ce4d1b: Remove external/debugger-libs (#1072)
* xamarin/monodroid@7ded15051: Bump to mono/debugger-libs/master@5e5b5efb (#1071)
* xamarin/monodroid@072746460: Bump to xamarin/android-sdk-installer/master@c694d0da (#1070)
=> Bump to xamarin/monodroid/master@01a4e0a0

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/MonoAndroidHelperTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
Fixes: http://work.azdo.io/774576
In reviewing `Path.GetTemp*` usage, I found the
`MonoAndroidHelper.CleanBOM` method could leave behind temp files if
an exception is thrown. It did not use a `try-finally` block.
I took the time to refactor the method and add a general test for it.
The other places I reviewed seem to be OK. They have `File.Delete`
calls in a `try-finally` block. Some are at the MSBuild task level.
=> [Xamarin.Android.Build.Tasks] CleanBOM could leave behind a temp file

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/CheckForInvalidResourceFileNames.cs, src/Xamarin.Android.Build.Tasks/Tasks/CheckProjectItems.cs, src/Xamarin.Android.Build.Tasks/Tasks/CompileToDalvik.cs
=> [Xamarin.Android.Build.Tasks] Make APT0002, APT0003, XA0100, & XA4305 localizable

build-tools/Xamarin.Android.Tools.BootstrapTasks/result-packaging.targets, build-tools/scripts/TestApks.targets, tools/apkdiff/ApkDescription.cs, tools/apkdiff/Program.cs, tools/apkdiff/README.md
And thus fix the CI build as well
=> [apkdiff] Make it work with AAB packages

.gitmodules
Security fixes:
[CVE-2019-16168](https://nvd.nist.gov/vuln/detail/CVE-2019-16168) *M*
Vulnerability levels:
*L* low
*M* medium
*H* high
*C* critical
=> Update sqlite to 3.31.1

Documentation/building/windows/instructions.md
This change appear after discussion with @jonpryor in #4275
=> Update instructions for building tests

Documentation/building/unix/dependencies.md
* document necessary C++ compiler versions
* mention OpenJDK
* add the .NET SDK (#4111)
=> Update documentation of build dependencies for Linux

Documentation/release-notes/4350.md
Changes: https://github.com/xamarin/Java.Interop/compare/cdf840f7f746b691db930aa2631fd410aaef215d...b33d183deef0bb07272b30c58714ec8262551244
Context: https://github.com/xamarin/Java.Interop/issues/509
* xamarin/Java.Interop@b33d183: [Java.Interop] JniTypeManager optimizations  (#582)
* xamarin/Java.Interop@28b1fc9: [generator] Support using DIM to nest interface types. (#589)
=> Bump to xamarin/Java.Interop/master@b33d183d

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/GitDiff.cs
Overlooked in commit 2cfce14b/PR #4362.
Doh!
=> [xa-prep-tasks] Add <GitDiff/> Task

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunParallelCmds.cs, src/sqlite-xamarin/sqlite-xamarin.targets
Lets build all ABI's in parallel
before: Time Elapsed 00:00:24.63
after:  Time Elapsed 00:00:10.37
CI builds
mac before: 28:45 (https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3549400)
mac after:  27:14 (https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3549412)
win before: 10:56 (https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3549400)
win after:   8:44 (https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3549412)
=> [build] Build sqlite-xamarin in parallel

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunParallelCmds.cs, src/monodroid/monodroid.targets
Before: Time Elapsed 00:01:35.92
After:  Time Elapsed 00:00:20.50
=> [build] Configure in parallel

src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
Context: https://github.com/xamarin/monodroid/wiki/Localization
=> LOC CHECKIN | xamarin/xamarin-android master | 20200316

src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
Context: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1083016
=> [l10n] Add description comment for XA2002 strings

.external
Changes: https://github.com/mono/mono/compare/beccf5ba4386148534467bff03fabe92da6d9705...fda73998f929f9af2020e8e125afd15c7d504c0c
* mono/mono@fda73998: Adding static to ss_req_acquire and ss_req_count (#19391)
=> Bump to mono/mono/2020-02@fda73998

.external
Changes: https://github.com/xamarin/monodroid/compare/34f5275d1db891e25af17d743b425cc318e6e7df...846697287fb32c38b54ddd2fe21964b9159b2750
* xamarin/monodroid@846697287: Bump to xamarin/androidtools/master@8a2cadb5 (#1079)
* xamarin/monodroid@9d045f82f: Bump to xamarin/android-sdk-installer/master@33a209cc (#1078)
=> Bump to xamarin/monodroid/master@84669728

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CheckApiCompatibility.cs
I noticed this target runs on builds with no changes *twice*:
Building target "_CheckApiCompatibility" completely.
Input files: ..\..\tests\api-compatibility\acceptable-breakages-v10.0.99.txt;..\..\tests\api-compatibility\acceptable-breakages-v10.0.txt;..\..\tests\api-compatibility\acceptable-breakages-v4.4.87.txt;..\..\tests\api-compatibility\acceptable-breakages-v5.0.txt;..\..\tests\api-compatibility\acceptable-breakages-v5.1.txt;..\..\tests\api-compatibility\acceptable-breakages-v6.0.txt;..\..\tests\api-compatibility\acceptable-breakages-v7.0.txt;..\..\tests\api-compatibility\acceptable-breakages-v7.1.txt;..\..\tests\api-compatibility\acceptable-breakages-v8.0.txt;..\..\tests\api-compatibility\acceptable-breakages-v9.0.txt;..\..\tests\api-compatibility\acceptable-breakages-vReference.tx …
=> [BootstrapTasks] fix incremental _CheckApiCompatibility

src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
Corresponding d16-6 backport: https://github.com/xamarin/xamarin-android/pull/4622
=> LOC CHECKIN | xamarin/xamarin-android master | 20200424

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/KeyToolTests.cs
Context #4036
Add unit tests to make sure we can use a strong password with the keytool and signing tools.
=> [Xamarin.Android.Build.Tests] Add string password keystore tests

Configuration.props, Documentation/release-notes/4668.md
Context: https://github.com/google/bundletool/releases/tag/0.14.0
=> [bundletool] bump to 0.14.0

.gitmodules
Context: https://sqlite.org/releaselog/3_32_0.html
Context: https://sqlite.org/releaselog/3_32_1.html
Security fixes:
* [CVE-2020-13434](https://nvd.nist.gov/vuln/detail/CVE-2020-13434)
* [CVE-2020-11655](https://nvd.nist.gov/vuln/detail/CVE-2020-11655)
(HIGH vulnerability level)
=> Bump to sqlite 3.32.1

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/Linux.Debian.cs, build-tools/xaprepare/xaprepare/OperatingSystems/Linux.cs
Xamarin.Android supports detecting a handful of Linux distributions
directly (Ubuntu, Linux Mint, Debian and Arch) but the support can be
improved so that derivatives of those distributions can be detected
properly without having direct support for them.  To do it, this commit
adds support to detect derivatives of the above 4 distributions by way
of looking at the `/etc/os-release` file which contains all the
information we need.
=> [xaprepare] Improve Linux OS detection

build-tools/xaprepare/xaprepare/Application/Program.FedoraLinux.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/Linux.Fedora.cs, build-tools/xaprepare/xaprepare/OperatingSystems/Linux.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj
=> Add support for building on Fedora

src/java-runtime/java/mono/android/MonoPackageManager.java
Fixes: https://github.com/xamarin/xamarin-android/issues/4772
Fixes: https://github.com/xamarin/xamarin-android/issues/4852
Fixes apply to the the **Release** builds on Android 5.x devices.
Android 5.x devices have a bug in their 64-bit dynamic linker which
prevents it from correctly resolving shared library dependencies when a
library required by the one currently being loaded is not found in the
same directory.  The problem is that the Android dynamic linker on those
devices fails to properly interpret the internal library name (so-called
`SONAME`, contained in the `DT_SONAME` field in the ELF executable
header) when checking whether the library is already loaded in the
process memory.  Failing that check, the loader proceeds to look for the
library **file** on the disk/storage medium …
=> [runtime] Preload `libmono-native.so` before initializing XA

Configuration.props, build-tools/xaprepare/xaprepare/Application/KnownProperties.cs, build-tools/xaprepare/xaprepare/Application/Properties.Defaults.cs.in, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, build-tools/xaprepare/xaprepare/xaprepare.targets
System images:
* x86-29: bumped to release 7
Tools:
* platform-tools: bumped to v30.0.2
=> [build] Bump several Android SDK components

.external
Changes: https://github.com/xamarin/monodroid/compare/fb5542fa...6e43a20e
* [tools/msbuild] handle multiple abi's in ro.product.cpu.abilist64
* [build] restore API 19 & 20
* Bump to xamarin/android-sdk-installer/master@23fc8d8
* Bump to xamarin/androidtools/master@3f51412d
* Bump to xamarin/xamarin-android/master@8576118a
=> Bump to xamarin/monodroid/master@6e43a20e

src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj
`netcoreapp3.0` is EOL.  Update to current LTS version.
=> [ILLink] Update to netcoreapp3.1.

src/Xamarin.Android.Build.Tasks/Tasks/Generator.cs
Fixes #4956
We added support for using a response file for generator.exein
xamarin/java.interop#665
This commit updates the BindingGenerator Task to use a response
file rather than passing all the argumets on the command line.
=> [Xamarin.Android.Build.Tasks] Add ResponseFile support for Generator Task

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
The `_CheckForObsoleteAssemblies` MSBuild target checks for OpenTK 0.9 and emits a
warning. OpenTK 0.9 was deprecated in Xamarin.Android 9.3 and removed
completely in Xamarin.Android 9.4.
We no longer need a warning at all here, you will hit this warning
*first*:
warning MSB3245: Could not resolve this reference. Could not locate the assembly "OpenTK". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
Removing the target completely, so:
1. We don't have to localize the message.
2. We won't create a ~26K character MSBuild property on every build.
In a sample app, it created a `$(_ObsoleteAssemblies)` MSBuild
property with this value:
C:\src\net5-samples\packages\microsoft.netcore.app.runtime.android-x86\5.0.0-rc.1.204 …
=> [Xamarin.Android.Build.Tasks] remove _CheckForObsoleteAssemblies

.external
Context: https://github.com/xamarin/androidtools/pull/243
Changes: https://github.com/xamarin/monodroid/compare/b12a3e8d...92b9cce8
* xamarin/monodroid@92b9cce8d: Bump to xamarin/androidtools/master@30a4cf7b (#1110)
* xamarin/monodroid@b229b8cdb: [tools/msbuild] initial localization setup (#1109)
=> Bump to xamarin/monodroid/master@92b9cce8

src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
=> LOC CHECKIN | xamarin/xamarin-android d16-8 | 20200828 (#5065)

src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
Context: https://github.com/xamarin/monodroid/wiki/Localization
=> LOC CHECKIN | xamarin/xamarin-android master | 20200828

src/Xamarin.Android.Tools.JavadocImporter/Xamarin.Android.Tools.JavadocImporter.csproj
Changes: https://github.com/xamarin/java.interop/compare/afbc5b3223d2445784f1de721347dbe248db9e71...ac914ce362c478e937f2c77f57b6bab2fbfd7bd6
=> Bump to xamarin/Java.Interop/master@ac914ce3

.external
Changes: https://github.com/xamarin/monodroid/compare/d37b5aaa...a3bc1886
=> Bump to xamarin/monodroid@a3bc1886

.external
Changes: https://github.com/xamarin/monodroid/compare/a9ae74d474583211c153b2b868417383afd4cb3a...1562e30689e60b884a0b229a233bb6d7bf230a08
* xamarin/monodroid@1562e306: Bump to xamarin/android-sdk-installer/main@c41bc805 (#1114)
=> Bump to xamarin/monodroid/master@1562e306

src/proguard/proguard.targets
Changes: https://github.com/Guardsquare/proguard/compare/ebe9000c9baa36a53dc63902b96956c9525ab052...84e8560d325d80beec8f6d239af52a1095010010
=> Bump to Guardsquare/proguard/master@84e8560d [v7.0.0]

.gitmodules
Changes: https://github.com/xamarin/xamarin-android-tools/compare/1878e43695698ee39901e2f86d37f55e40751001...ab650f59d0e1fafbf4e09a46e6486898328904df
* xamarin/xamarin-android-tools@ab650f5: [Xamarin.Android.Tools.AndroidSdk] Update SDK component for API-30
=> Bump to xamarin/xamarin-android-tools/main@ab650f59

build-tools/xaprepare/xaprepare/Application/Utilities.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4156676&view=logs&j=996c69ec-9601-56aa-a920-9140ba1f716a&t=32be717a-abee-54ef-d1a3-effe9a871c31&l=116
We still occasionally get failures on CI such as:
Downloading NuGet
Step Xamarin.Android.Prepare.Step_DownloadNuGet failed: An error occurred while sending the request.
System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_DownloadNuGet failed: An error occurred while sending the request. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 152.199.4.184:443
at …
=> [xaprepare] add more retry logic

.external
Changes: http://github.com/xamarin/monodroid/compare/767f647...04b0423
=> Bump to xamarin/monodroid@04b0423

Documentation/README.md
=> [documentation] fix broken link to build-process.md.

Documentation/guides/building-apps/build-properties.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Support dependencies dump for ILLink with existing
`LinkerDumpDependencies` property.
=> [illink] Support `LinkerDumpDependencies`

build-tools/automation/CredScanSuppressions.json, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/use-dot-net.yaml, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/MacOS.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsMapsApplicationProject.cs
"Environmental changes" broke the d16-8 build, with fixes on master.
CP the fixes so d16-8 can build on CI.
=> Fix d16-8 Build

Documentation/release-notes/5428.md, build-tools/xaprepare/xaprepare/Steps/Step_DetermineAzurePipelinesTestJobs.cs
Changes: https://github.com/xamarin/sqlite/compare/1a3276b8853d695c96c9c5be3d4ff752e67a1d6f...cfe06e05270fb3de3e37f961cfe46c687c07929f
Context: https://sqlite.org/releaselog/3_32_2.html
=> Bump to xamarin/sqlite/3.32.2@cfe06e05

tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
As we are adding `[Serializable]` attribute to `Java.Lang.Object` now,
test the binary serialization too.
=> [tests] Test binary serialization

build-tools/unix-distribution-setup/unix-distribution-setup.csproj
unix-distribution-setup migration DONE
=> migration-sdk-style-prjs-unix-distribution-setup

build-tools/create-pkg/create-pkg.csproj
=> migration-sdk-style-prjsv build-tools\create-pkg

build-tools/xaprepare/xaprepare/Application/Utilities.cs, build-tools/xaprepare/xaprepare/Steps/Step_BuildMonoRuntimes.Unix.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallMonoRuntimes.cs, build-tools/xaprepare/xaprepare/ToolRunners/MSBuildRunner.cs
/restore added to MSBuildRunner
=> migration-sdk-style-prjs build-tools\xaprepare

build-tools/conjure-xamarin-android-cecil/conjure-xamarin-android-cecil.csproj
conjure-xamarin-android-cecil migrated
=> migration-sdk-style-prjs build-tools\conjure-xamarin-android-cecil

.external, Configuration.props, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Changes https://github.com/xamarin/monodroid/compare/ad19471b8...b355593a
=> Bump Monodroid to Bring in FastDev Fix

src/Xamarin.Android.Build.Tasks/Tasks/AndroidCreateDebugKey.cs
Context: 1ec865d0
Context: https://github.com/dotnet/msbuild/blob/74cbf25b3543a5c8c886a5a6659316f18dc49b8a/src/Utilities/ToolTask.cs#L370-L394
1ec865d0 attempted to fix an infrequent failure such as:
Task "AndroidCreateDebugKey" (TaskId:407)
Task Parameter:StorePass=android (TaskId:407)
Task Parameter:ToolPath=C:\Users\AzDevOps\android-toolchain\jdk-11\bin (TaskId:407)
Task Parameter:KeyAlias=androiddebugkey (TaskId:407)
Task Parameter:Validity=10950 (TaskId:407)
Task Parameter:KeyAlgorithm=RSA (TaskId:407)
Task Parameter:StoreType=pkcs12 (TaskId:407)
Task Parameter:KeyPass=android (TaskId:407)
Task Parameter:Command=-genkeypair (TaskId:407)
Task Parameter:KeyStore=C:\Users\AzDevOps\AppData\Local\Xamarin\Mono for Android\debug.keystore (TaskId:407)
KeyTool : -genkeypair (TaskId:407) …
=> [Xamarin.Android.Build.Tasks] warn exit code for "alias already exists"

Configuration.props
Changes: https://github.com/dotnet/installer/compare/f4682754...b8a03527
=> Bump to .NET 6.0.100-preview.1.21103.13

.external
Changes: https://github.com/xamarin/monodroid/compare/7da768cf9ddbd137bbce5326dab79b139bcc59e0...55477f7307df2b8823e86567daba1f7e58ca33cd
* xamarin/monodroid@55477f730: [ci] Update packageSources in NuGet.config (#1163)
=> Bump to xamarin/monodroid/main@55477f73

Directory.Build.props, build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/xaprepare.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
Changes https://github.com/xamarin/LibZipSharp/compare/1.0.20...1.0.22
=> Bump LibZipSharp to 1.0.22

.external
Changes: https://github.com/xamarin/monodroid/compare/55477f73...2e93b630
* [tools/msbuild] Add `File.Exists()` checks for Fast Deployment
* [ci] Run additional tests on macOS
* [tools/msbuild] `<GetPrimaryCpuAbi/>` sets `$(RuntimeIdentifier)`
=> Bump to xamarin/monodroid/main@2e93b630

build-tools/automation/azure-pipelines.yaml
Related work item: VS #[1282920](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1282920)
Enable signing of jar files that are included in the vsix
=> [build] Enable JAR signing

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets
Move all the feature switches default settings to one place.
=> [net6] Consolidate feature switches defaults

Documentation/building/windows/instructions.md, Documentation/guides/building-apps/build-properties.md, Documentation/guides/messages/xa1005.md, build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/use-dot-net.yaml, build-tools/scripts/get-git-branch.sh
The `master` branch has been renamed `main`.
Update everything that needs updating so that CI behaves properly.
=> [ci] s/master/main/g!

.external
Context: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1290661/
Context: https://github.com/xamarin/xamarin-android/issues/5710
Changes: https://github.com/xamarin/monodroid/compare/5918966a3354d9dcffa3ac3fadd1329356bea737...b2a750a2bd9f25e4f16592168dd919bf36930de4
* xamarin/monodroid@b2a750a2b: Bump to xamarin/androidtools/d16-9@91ca8a80 (#1179)
* xamarin/monodroid@73e652c36: [tools/msbuild] Add File.Exists checks for Fast Deployment (#1166)
=> Bump to xamarin/monodroid/d16-9@b2a750a2

.external
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1290584
Fixes: https://github.com/xamarin/xamarin-android/issues/5710
Changes: https://github.com/xamarin/monodroid/compare/75cf1a237380e95f684438b782e3829efc5109c6...3a05726b80e390dc9dddf39784338f8789e50a7f
* xamarin/monodroid@3a05726b8: [Xamarin.Android.Build.Tasks] Fix the MAX_COMMAND adb Error. (#1182)
* xamarin/monodroid@83de4b43c: [Xamarin.Android.Build.Tasks] Support FastDev for System Apps (#1177)
* xamarin/monodroid@02f19e057: Bump to xamarin/android-sdk-installer@6bf8527 (#1176)
=> Bump to xamarin/monodroid/main@3a05726b

.external, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/InlineData.cs, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1301607
Add a unit test which tests ALL the languages we can to make sure we can Fast Deploy.
=> [MSBuildDeviceIntegration] Add Xamarin.Android unit test which uses ALL available Languages.

.vscode/launch.json, .vscode/tasks.json, samples/HelloWorld/HelloLibrary/HelloLibrary.DotNet.csproj, samples/HelloWorld/HelloWorld.DotNet.csproj, samples/NuGet.config
The new tasks will allow developers to debug the HelloWorld sample
in VSCode using the build tree.
=> [samples] Add Task to debug Samples in VSCode.

Documentation/guides/HowToBranch.md
Writing this down, so I won't forget. I forgot step no. 6 last time.
=> [docs] document how to branch for .NET releases

Documentation/workflow/DevelopmentTips.md
Fixes: https://github.com/xamarin/xamarin-android/issues/6165
=> [docs] add examples of enabling runtime logging

Configuration.props, build-tools/check-boot-times/Program.cs
=> Bump to cmdline-tools 5.0.

.external
Changes: https://github.com/xamarin/monodroid/compare/9b3a37af...4e8702a8
* Delete submodule at external/nrefactory
* Changes: https://github.com/xamarin/androidtools/compare/0549680...7035610
* Changes: https://github.com/xamarin/android-sdk-installer/compare/98fa41b...1a9d910
=> Bump to xamarin/monodroid/main@4e8702a8

src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
Changes: https://github.com/xamarin/xamarin-android-tools/compare/a5194e93498e7f12225d87e2811415a45f742116...0a229578ea0a2dbacffbc4d1ffc48c04bc46625a
* xamarin/xamarin-android-tools@0a22957: [Xamarin.Android.Tools.AndroidSdk] Parse Properties after header (#143)
* xamarin/xamarin-android-tools@dac3a47: [Xamarin.Android.Tools.AndroidSdk] Add API-31 to KnownVersions (#141)
* xamarin/xamarin-android-tools@fc976d8: [Xamarin.Android.Tools.AndroidSdk] Add JdkInfo.GetSupportedJdkInfos() (#142)
* xamarin/xamarin-android-tools@34e98e2: [build] Allow Assembly "vendorization" (#136)
* xamarin/xamarin-android-tools@061bcc2: [build] Import "parent directory.override.targets" (#135)
=> Bump to xamarin/xamarin-android-tools/main@0a229578

tests/Mono.Android-Tests/Mono.Data.Sqlite/SqliteTests.cs
Changes: https://sqlite.org/releaselog/3_37_0.html
=> Bump SQLite to 3.37.0

README.md
- Add `aka.ms` links for `d16-11` and `d17-0`
- Update OSS links to `main` branch
- Remove dead `d15*` links, as `jenkins.mono-project.com` is gone
- Update Feedback links to current preferred venues
=> [readme] Add new download links and remove obsolete information.

src/Mono.Android/Android.Runtime/JavaList.cs, src/Mono.Android/Java.Interop/JavaConvert.cs, tests/Mono.Android-Tests/Java.Interop/JavaListTest.cs, tests/Mono.Android-Tests/Mono.Android-Test.Shared.projitems
Related to 4e0f36b5, I found usage of `JNIEnv` in the .NET Podcast
startup, such as:
5.17ms Mono.Android!Android.Content.PM.ShortcutManager.SetDynamicShortcuts(System.Collections.Generic.IList`1<Android.Content.PM.ShortcutInfo>)
1.22ms Mono.Android!Android.Runtime.JavaList<T_REF>..ctor
1.22ms Mono.Android!Android.Runtime.JNIEnv.FinishCreateInstance
1.22ms Mono.Android!Android.Runtime.JNIEnv.InvokeConstructor
1.22ms Mono.Android!Android.Runtime.JNIEnv.CallNonvirtualVoidMethod
This ports the manual bindings for `JavaList` and `JavaList<T>` to use
`JniEnvironment` instead of `JNIEnv`.
I also added new tests for the `JavaList` types.
Other changes & problems fixed:
1. `JavaList.SubList()` had the wrong signature and didn't work. `(II;)`
needed the `;` removed.
2. The `JavaConvert.TypeMapping` …
=> [Mono.Android] remove JavaList's JNIEnv.Call*Method() usage

.external
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1490514
Changes: https://github.com/xamarin/monodroid/compare/5e2b25ea1f299213f4b176f417dd26231c897eda...b5c07f8a785a776bc22786802f4221c583211ded
* xamarin/monodroid@b5c07f8a7: Bump to xamarin/androidtools/main@c1900f11 (#1242)
* xamarin/monodroid@b59064f75: Bump to xamarin/android-sdk-installer/main@893c5560 (#1243)
=> Bump to xamarin/monodroid/main@b5c07f8a

build-tools/automation/yaml-templates/commercial-build.yaml, build-tools/xaprepare/.gitignore, build-tools/xaprepare/xaprepare/Application/AndroidToolchainComponent.cs, build-tools/xaprepare/xaprepare/Application/Context.cs, build-tools/xaprepare/xaprepare/Application/EssentialTools.MacOS.cs, build-tools/xaprepare/xaprepare/Application/HomebrewProgram.MacOS.cs, build-tools/xaprepare/xaprepare/Application/IBuildInventoryItem.cs, build-tools/xaprepare/xaprepare/Application/MonoPkgProgram.MacOS.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, build-tools/xaprepare/xaprepare/Steps/Step_Android_SDK_NDK.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallAdoptOpenJDK.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs
Context: Section 4.e.i.D of https://eng.ms/docs/initiatives/executive-order/executive-order-requirements/executiveorderoncybersecurity/buildinfraops#build-system-security-requirements
Context: https://microsoft.sharepoint.com/:x:/r/teams/1ES2/_layouts/15/doc2.aspx?sourcedoc=%7B97E1B064-A768-4B0F-BEB5-4BF21577F3D6%7D&file=9d770e15-6208-4284-b347-b2762803623b.xlsx
Adds support to xaprepare to generate a buildtoolsinventory.csv file
which contains information about various build tools we depend on.
Items currently included are dotnet, Android SDK and NDK packages,
Open JDK, Mono MDK, and various Homebrew tools:
BuildToolName,BuildToolVersion
AdoptOpenJDK,1.8.0.282
android-ndk-r24,24.0.8215888
android-sdk-android-15_r05,15.5
android-sdk-android-16_r05,16.5
android-sdk-android-17_r03,17.3 …
=> [build] Enable creation of build tools inventory csv

Directory.Build.props
We've branched 6.0.3xx-rc2:
* https://github.com/xamarin/xamarin-android/commits/release/6.0.3xx-rc2
Update xamarin-android/release/6.0.3xx to 32.0.300-rc.3.
=> Update $(AndroidPackVersionSuffix) to rc.3

.external, Documentation/guides/building-apps/build-properties.md, Documentation/guides/building-apps/build-targets.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/Legacy/ResolveAndroidTooling.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs
Changes: http://github.com/xamarin/monodroid/compare/e451ea986b27cdfb965df07c1f2ea74fa14f33c2...f4240bc3c3d331db47c9ee944b4388e0e9af4076
* xamarin/monodroid@f4240bc3c: Bump to xamarin/android-sdk-installer@68939f22 (#1247)
* xamarin/monodroid@f84615dae: Bump to xamarin/android-sdk-installer/main@69fa0dca (#1245)
* xamarin/monodroid@8589f37fa: [ci] Import variables.yaml from xamarin-android (#1246)
=> Bump to xamarin/monodroid/main@f4240bc3

README.md
Adds https://aka.ms/xamarin-android-commercial-d17-2-windows link to README.md.
=> Add 17.2 link to README.

.github/ISSUE_TEMPLATE/config.yml
It looks like a few of our links to other MS sites are no longer valid.  Update to working links.
=> Update GitHub Issues list URLs

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fix typo introduced in f6f11a5a79.
=> [Xamarin.Android.Build.Tasks] Fix accidental $($(…)) usage

Localize/loc/cs/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_8f6a1daa-4188-4542-8be4-a0783e263c8d_20220726002001749 to main with localized lcls
=> LEGO: Pull request from juno/hb_8f6a1daa-4188-4542-8be4-a0783e263c8d_20220726002001749 to main

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20220729170242753 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20220729170242753 to main

Localize/loc/cs/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20220730103515484 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20220730103515484 to main

.external
http://github.com/xamarin/monodroid/compare/1e6734feac26a86541232c5073ace2fe9dee7569...210073e19b9aa339d2099260e724c1f60df6fd70
* xamarin/monodroid@210073e19: Bump to xamarin/android-sdk-installer@d6a84ec6 (#1263)
* xamarin/monodroid@a23be453c: [Localization] Import translated resx files (#1259)
* xamarin/monodroid@3eb472f87: LEGO: Merge pull request 1262
* xamarin/monodroid@d7e36612f: LEGO: Merge pull request 1261
* xamarin/monodroid@f86fb73cd: LEGO: Merge pull request 1260
* xamarin/monodroid@1e9e65080: [Localization] Add OneLocBuild job (#1257)
=> Bump to xamarin/monodroid@210073e1

.vscode/tasks.json
Also upgrade the tasks to emit build logs just incase something doesn't work.
=> Update the VSCode Task to use net7.0-android

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 11410: Build ID 6664168

.github/dependabot.yml
Submodules that frequently change have been added to the dependabot.yml file to opt in to automatic updates.
=> [dependabot] Automatically update a few submodules

Configuration.props
Changes: https://github.com/xamarin/xamarin-android/compare/d6224ca...af4a25d
=> Bump to 32.0.476 .NET 6 Android packages

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20220929104537923 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20220929104537923 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 11410: Build ID 6759133

Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20220930103353448 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20220930103353448 to main

Documentation/previous-releases.md, README.md
Add links to XA 13.1 release installers.
=> [readme] Links for d17.4 release.

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20221124114634905 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20221124114634905 to main

Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20221125115016707 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20221125115016707 to main

tools/assembly-store-reader/AssemblyStoreReader.cs
Seems like a copy-paste error.
=> fix: AssemblyStoreReader is32Bit flag

Makefile
Local experiment shows a ~21% speed-up thanks to this.
=> [build] Try building in parallel on Unix

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 11410: Build ID 7029692

.github/CODEOWNERS
Assign @grendello as the code owner of more areas
=> [GH] More updates to CODEOWNERS

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 11410: Build ID 7155122

.external
Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1714340
Fixes: https://developercommunity.visualstudio.com/t/Unable-to-debug-XamarinAndroid-system-a/10247269
Changes:  https://github.com/xamarin/monodroid/compare/2b9c9d01820c8df4541157f6b6116852eba73350...50faac94c6a0c27864564829ac83f3988c82f8ef
* xamarin/monodroid@50faac94c: [tools/msbuild] Review RegisterTaskObject() use (xamarin/monodroid#1281)
* xamarin/monodroid@83e997ab5: Bump to xamarin/androidtools/main@f11d1635 (xamarin/monodroid#1286)
* xamarin/monodroid@db636fc7a: [tools/msbuild] Fix System App detection (xamarin/monodroid#1284)
=> Bump to xamarin/monodroid/main@50faac94

.external
Changes: https://github.com/xamarin/monodroid/compare/8f925e3...9454bde
* [tools/msbuild] Fix System App detection
* [tools/msbuild] Deploy *resources.dll from PackageReference
I branched monodroid at the appopriate commit at:
https://github.com/xamarin/monodroid/tree/release/7.0.1xx
=> Bump to xamarin/monodroid/release/7.0.1xx@9454bde

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230128113641291 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230128113641291 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 7255366

Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230131113616874 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230131113616874 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 7269834

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230223114738787 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230223114738787 to main

Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230224114109122 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230224114109122 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 7384592

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 7401514

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230302114017804 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230302114017804 to main

Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230303113708367 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230303113708367 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 7420791

Configuration.props
Changes: https://github.com/xamarin/xamarin-android-tools/compare/9f02d77692bca8c6585941de03750d5eaaca5c5a...ca1552d5b40d3fb9cbeff6148f662c67068d6d9f
* xamarin/xamarin-android-tools@ca1552d: [Xamarin.Android.Tools.AndroidSdk] Update platform-tools for API-T (xamarin/xamarin-android-tools#203)
=> Bump to xamarin/xamarin-android-tools/d17-5@ca1552d5

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 7820837

.external, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs
Changes: https://github.com/xamarin/monodroid/compare/9454bde50...d3008fd4
* [tools/msbuild] Add RunActivity.Server property
* [tools/msbuild] pass -S for am start commands
* [tools/msbuild] InstallAndroidDependencies installs JDK
* [Xamarin.Android.Build.Tasks] Use new '$(_ZipFlushFilesLimit)' property
=> Bump to xamarin/monodroid/release/7.0.2xx@d3008fd4

src/monodroid/jni/monodroid-glue.cc
Backport of: https://github.com/xamarin/xamarin-android/pull/7916
=> [release/7.0.2xx] [debugger] Pass retry timeout to runtime

Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230526103652787 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230526103652787 to main

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230527104818757 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230527104818757 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 7834780

Directory.Build.props, build-tools/debian-metadata/rules, build-tools/installers/create-installers.targets
Changes
* Add Version to Native Library https://github.com/xamarin/LibZipSharp/commit/45f4c1d9f9114605a7b58f66747492b41442769d
* Add net7.0 assembly to package https://github.com/xamarin/LibZipSharp/commit/a3958a6d2ebd6a566a76cb6dd30893fa976305d6
* Keep netcoreapp3.1 https://github.com/xamarin/LibZipSharp/commit/1a0f3420781c636dd7d4865fdbd45cd345f26fd9
=> Bump LibZipSharp to 3.0.0

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 7859909

Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230603104041477 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230603104041477 to main

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230604103820527 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230604103820527 to main

Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230605103623713 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230605103623713 to main

Localize/loc/es/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230611105931413 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230611105931413 to main

Localize/loc/cs/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230612104017875 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230612104017875 to main

.external
Changes: https://github.com/xamarin/monodroid/compare/dbc9c67e7bd45744e5174dd7e94e5b642418bef9...a524859192e6eca6cea45313e5f95b8d04a698bf
=> Bump to xamarin/monodroid@a5248591

Makefile, build-tools/scripts/UpdateApkSizeReference.ps1, build.cmd
This makes it possible to build locally with `make prepare all`
=> Remove more xabuild

.external
Changes: https://github.com/xamarin/monodroid/compare/a5248591...057b17fe
=> Bump monodroid to 057b17fe

.external
Changes: https://github.com/xamarin/monodroid/compare/6e57bd3e...e823fae7
=> [release/8.0.1xx-rc1] Bump to xamarin/monodroid/release/8.0.1xx-rc1@e823fae7

Configuration.props, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
For classic Xamarin.Android projects.
This will be in draft to be sure the test works (expected to fail). Then I will cherry-pick the required fixes here.
=> [d17-5] [tests] verify we can build/run on API 34

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230917103506268 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230917103506268 to main

Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230918103523603 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230918103523603 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8414944

Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230920103540639 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20230920103540639 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8427506

build-tools/automation/yaml-templates/commercial-build.yaml
Xcode 14 has not yet been rolled out to all the PR builders.
=> [ci] Only use Xcode 14 on CI builds

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231025103548087 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231025103548087 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8597526

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8697404

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231118113920940 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231118113920940 to main

Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231119113542045 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231119113542045 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8720715

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8752727

Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231202113557349 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231202113557349 to main

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231203113633797 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231203113633797 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8766658

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8778584

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231208113733084 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231208113733084 to main

Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231212113525142 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20231212113525142 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8805099

.external
Changes: https://github.com/xamarin/monodroid/compare/44b5ccb0ae4a7316e93040289832c74230b5217f...66a65e3b3e5fa4314d8e8d4f1b8ad578a4a56ab0
=> Bump to xamarin/monodroid@66a65e3b3e

src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.cs.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.de.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.en.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.es.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.fr.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.it.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.ja.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.ko.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.pl.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.pt-BR.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.ru.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.tr.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.zh-Hans.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.zh-Hant.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.cs.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.de.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.en.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.es.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.fr.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.it.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.ja.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.ko.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.pl.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.pt-BR.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.ru.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.tr.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.zh-Hans.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.zh-Hant.json
Context: 97819d81b3f08d2e3dc5359d250634c49f0b0783
These files are modified on each build, with new content referring 
to the changes in 97819d81.
Commit the files since the new content must be translated.
=> Update a number of l18n files

Localize/loc/cs/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/cs/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl, Localize/loc/de/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/de/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl, Localize/loc/es/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/es/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl, Localize/loc/fr/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/fr/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl, Localize/loc/it/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/it/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl, Localize/loc/ja/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/ja/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl, Localize/loc/ko/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/ko/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl, Localize/loc/pl/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/pl/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl, Localize/loc/pt-BR/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/pt-BR/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl, Localize/loc/ru/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/ru/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl, Localize/loc/tr/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/tr/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hans/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hans/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hant/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hant/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240117010121446 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240117010121446 to main

src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.cs.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.de.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.es.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.fr.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.it.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.ja.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.ko.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.pl.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.pt-BR.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.ru.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.tr.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.zh-Hans.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.zh-Hant.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.cs.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.de.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.es.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.fr.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.it.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.ja.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.ko.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.pl.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.pt-BR.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.ru.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.tr.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.zh-Hans.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.zh-Hant.json
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8930705

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8944839

Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240120113707988 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240120113707988 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8952275

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8968258

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
Backporting:
* eda5449e4eb7a637ca3caa3b87022bfa671156f8
* d688f1bbad805e20a921b29a48fdb00fee1df97f
* 73c31353e8775ae9bae8b75a20f2e0c7b6d964d5
* 2b2c6ebb5e0d39b7841d8197ce6621dae08b1ead
* e67afc7d7ae848da6b33026b80973d30713b98ad
=> [release/8.0.1xx] localization changes for `XA1039`

src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.cs.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.de.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.es.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.fr.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.it.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.ja.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.ko.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.pl.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.pt-BR.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.ru.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.tr.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.zh-Hans.json, src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.zh-Hant.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.cs.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.de.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.es.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.fr.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.it.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.ja.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.ko.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.pl.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.pt-BR.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.ru.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.tr.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.zh-Hans.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.zh-Hant.json
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 9248556

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 9255165

Localize/loc/de/src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.json.lcl, Localize/loc/de/src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.json.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240320104722611 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240320104722611 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 9323313

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/GeneratePackageManagerJavaTests.cs
Context https://github.com/xamarin/xamarin-android/issues/8849
Add a unit test to make sure we update the environment.xxx.ll files when they are updated.
=> Add a unit test to check environment processing

.external
Changes: https://github.com/xamarin/monodroid/compare/fefc158ef36d056249e8775df4e5d409a70119e2...a5742221b314864636f4356173a2535a539c7b2c
Changes: https://github.com/xamarin/android-sdk-installer/compare/852ad3f83e314b68a4ed10ed928aa9b5bc14bfb7...425a83f9973be530d51edc06779109bc41ecf9e8
Changes: https://github.com/xamarin/androidtools/compare/683b844213c3918322ec089db3109c487b6648db...2d02a3402d177a23b74aeee9ec8cf65eb5193fe4
Changes: https://github.com/xamarin/xamarin-android-tools/compare/37d79c9dcdf738a181084b0b5890877128d75f1e...1ea4e35eaf3fe09b9ca8adf0a29b4d9988146338
=> Bump to xamarin/monodroid@a5742221b3

Localize/loc/cs/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240427103719562 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240427103719562 to main

src/Microsoft.Android.Sdk.ILLink/Properties/Resources.cs.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.de.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.es.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.fr.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.it.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.ja.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.ko.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.pl.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.pt-BR.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.ru.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.tr.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.zh-Hans.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.zh-Hant.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 9494187

Localize/loc/es/src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.json.lcl, Localize/loc/es/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/es/src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.json.lcl, Localize/loc/es/src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.json.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.json.lcl, Localize/loc/ja/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/ja/src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.json.lcl, Localize/loc/ja/src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.json.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.json.lcl, Localize/loc/ko/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/ko/src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.json.lcl, Localize/loc/ko/src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.json.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.json.lcl, Localize/loc/pt-BR/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/pt-BR/src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.json.lcl, Localize/loc/pt-BR/src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.json.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.json.lcl, Localize/loc/ru/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/ru/src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.json.lcl, Localize/loc/ru/src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.json.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hant/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hant/src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hant/src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240516103742977 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240516103742977 to main

Localize/loc/cs/src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.json.lcl, Localize/loc/cs/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/cs/src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.json.lcl, Localize/loc/cs/src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.json.lcl, Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.json.lcl, Localize/loc/de/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/de/src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.json.lcl, Localize/loc/de/src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.json.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.json.lcl, Localize/loc/fr/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/fr/src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.json.lcl, Localize/loc/fr/src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.json.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.json.lcl, Localize/loc/it/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/it/src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.json.lcl, Localize/loc/it/src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.json.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.json.lcl, Localize/loc/pl/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/pl/src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.json.lcl, Localize/loc/pl/src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.json.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hans/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hans/src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hans/src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240517104313369 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240517104313369 to main

src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.es.json, src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.ko.json, src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.pt-BR.json, src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.ru.json, src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.zh-Hant.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.es.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.ko.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.pt-BR.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.ru.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.zh-Hant.json, src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.es.json, src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.ko.json, src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.pt-BR.json, src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.ru.json, src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.zh-Hant.json, src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.es.json, src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.ko.json, src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.pt-BR.json, src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.ru.json, src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.zh-Hant.json, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 9593316

src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.de.json, src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.fr.json, src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.it.json, src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.pl.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.cs.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.de.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.fr.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.it.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.pl.json, src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.de.json, src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.fr.json, src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.it.json, src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.pl.json, src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.de.json, src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.fr.json, src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.it.json, src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.pl.json, src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.zh-Hans.json, src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 9599478

Localize/loc/tr/src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.json.lcl, Localize/loc/tr/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/tr/src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.json.lcl, Localize/loc/tr/src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.json.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240521103943124 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240521103943124 to main

Localize/loc/cs/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/fr/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/ja/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/ru/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hans/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240611104402682 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240611104402682 to main

src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.cs.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.de.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.es.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.fr.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.it.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.ja.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.ko.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.pl.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.pt-BR.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.ru.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.tr.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.zh-Hans.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.zh-Hant.json
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 9686669

Localize/loc/de/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/es/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/it/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/ko/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/pl/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/pt-BR/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/tr/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl, Localize/loc/zh-Hant/src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.json.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240613104420668 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240613104420668 to main

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240724105712737 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240724105712737 to main

Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240725104602226 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240725104602226 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 9938419

src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Utilities/ELFHelper.cs
Also update `src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs`
=> Fix `LogCodedWarning` usage

src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 9945550

Directory.Build.props
Update some outdated NuGet packages to the latest versions.
- `ELFSharp`: `2.13.1` -> `2.17.3`
- `K4os.Compression.LZ4`: `1.1.11` -> `1.3.6`
- `mdoc`: `5.9.2.4` -> `5.9.3`
=> Update some NuGet packages to latest versions.

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10081733

.external
Changes: https://github.com/dotnet/android-tools/compare/7ec795c003fba5ac0ad7463223a88ce5949092e0...657574378a64b2eb8ba301d502d16451904015dc
Changes: https://github.com/xamarin/monodroid/compare/12b1ae70cb082f467bc9a52c8c22e4492537e550...8bd4bae7e2961200dc342abf02b654efaf1d45d0
=> Bump to dotnet/android-tools@657574378a6 and xamarin/monodroid@8bd4bae7

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240826103643499 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240826103643499 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10113262

Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240827103730610 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240827103730610 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10122036

NuGet.config, eng/Version.Details.xml, eng/Versions.props
Reverts https://github.com/dotnet/android/commit/732db0cb733c016cbeca6cda1d1d0689458f896a
Reverts https://github.com/dotnet/android/commit/e03901403be04e8c426e60e54119f3b06012dafe
=> Bump to dotnet/runtime@2d5c0b72 8.0.8

NuGet.config, eng/Version.Details.xml, eng/Versions.props
https://github.com/dotnet/android/compare/b0fd0113c829edd9bd1bc7d742255a237ff19f69...68175bbe5a39140c642dab294cf184ecf72eece0
* Bump to dotnet/runtime@2d5c0b72 8.0.8
=> Bump to 34.0.138 of the .NET 8 Android workload

.external, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Context: https://github.com/dotnet/android/issues/8662
Context: https://github.com/xamarin/monodroid/pull/1537
=> [tests] add test for `$(AdbTargetArchitecture)`

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10277845

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240926103551494 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20240926103551494 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10293307

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10311359

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241002103533710 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241002103533710 to main

.external
[Bump from monodroid@a0cbe139...monodroid@ed75630c](https://github.com/xamarin/monodroid/compare/8a0cbe1392bf88cb3f46710057e224e902b6bf55...ed75630ca3612bab7a6a06a912fe8a8e9e180fe2)
Brings in
- https://github.com/xamarin/monodroid/pull/1522
- https://github.com/xamarin/monodroid/pull/1547
=> Bump monodroid to ed75630ca3612bab7a6a06a912fe8a8e9e180fe2

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10324496

Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241003103754143 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241003103754143 to main

.external
Bump to monodroid@87e386cba1210b95f432836da9cb964f385b6506
=> Bump monodroid to bring in Fast Dev Changes

src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10331149

Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241009014035977 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241009014035977 to main

Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241010103812401 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241010103812401 to main

Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241011103758546 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241011103758546 to main

Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241012103909504 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241012103909504 to main

Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241013103809414 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241013103809414 to main

Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241009103803783 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241009103803783 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10389509

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10397720

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241017104006414 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241017104006414 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10412692

src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10418524

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidGradleModule.cs, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
Adds a test which will install and run a AndroidGradleProject style
binding project.
=> [tests] Add AndroidGradleProject deploy test

.external
Changes:
https://github.com/xamarin/monodroid/compare/62976287a5392ccc17ffff10bcafdc3cecedc89b...6b27528406d556322328d1dae19a384fff074f66
=> Bump to xamarin/monodroid@6b275284

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
Changes: https://github.com/android/ndk/wiki/Changelog-r27#r27c
There are no changes which affect us directly.
=> Bump NDK to r27c

.external
Changes: https://devdiv.visualstudio.com/DevDiv/_git/android-platform-support/branchCompare?baseVersion=GCcdef164e7eef35128f74fa1f3ecbd7a878953a43&targetVersion=GCc22e86517918f75cdf147b12252361d90c6577bd
=> Bump to DevDiv/android-platform-support@c22e8651

build-tools/automation/onelocbuild.yaml
A new version of the OneLocBuild task is now available which includes various SFI related fixes.
=> [ci] Upgrade OneLocBuild to version 3

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10625915

src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10653360

.external
Changes: https://devdiv.visualstudio.com/DevDiv/_git/android-platform-support/branchCompare?baseVersion=GCdf3620a12d632d018211985921374a88303ce4cd&targetVersion=GCb23656d43004f26487ef0d03df8885a4a438167d
* Merged PR 599381: Merged PR 597295: [ci] Extend official 1ES pipeline template
* Merged PR 599380: Merged PR 598732: Update Android Manifest to version 17.13
* Merged PR 599378: Merged PR 597291: Fixes Network available check
* Merged PR 599376: Merged PR 596914: Work around unknown SSL certificate revocation status errors
* Merged PR 599375: Merged PR 596029: Relax license check verification on Google license storage
=> Bump to DevDiv/android-platform-support@b23656d4

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20250110113533143 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20250110113533143 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10814362

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2284231
Changes: https://github.com/NuGet/NuGet.Client/compare/324d7272b8526a3826ef1f12fa6fc3a362b5bb79...aa7eb9987d28e7169cfabfa484f2fdd22d2b91d2
% git diff --shortstat 324d7272...aa7eb998
1057 files changed, 38053 insertions(+), 16423 deletions(-)
=> Bump to NuGet/NuGet.Client/release-6.12.x@aa7eb998

.external
Changes: https://github.com/dotnet/android-tools/compare/f742b1555fc78b6a7c105e38dd3efe3bea6ab138...ab657dfcebf2d80e422c25e91dd389ec4f2aa1bc
Changes: https://devdiv.visualstudio.com/DevDiv/_git/android-platform-support/branchCompare?baseVersion=GCb23656d43004f26487ef0d03df8885a4a438167d&targetVersion=GC08bbd9d3b401589cfe8ac5416abfbe36bf0289ac
* Merged PR 603944: [release/9.0.1xx] Bump to dotnet/android-tools@ab657dfc
=> [release/9.0.1xx] Bump to android-platform-support@08bbd9d3

.gitmodules
Updates the lz4 submodule to use the newly created dotnet fork.
=> Update lz4 submodule to https://github.com/dotnet/lz4

.gitmodules
Changes: https://github.com/dotnet/java-interop/compare/d62008d1ad7f469f801c7c00613f3a9fc94648a1...2a7183a1c0d0f072b90fa836dd39d015d7a8c78d
* dotnet/java-interop@2a7183a1: [Java.Interop] CreatePeer() must satisfy targetType (dotnet/java-interop#1308)
Context: https://github.com/dotnet/android/pull/9747
=> Bump to dotnet/java-interop/main@2a7183a1

Documentation/docs-mobile/messages/apt2000.md, Documentation/docs-mobile/messages/index.md
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2381866
Add a page for APT2000. Add some example messages and some hints on what to do when you see one of these messages.
=> Add Page for APT2000 errors/warnings

src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigCLR.cs, src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGeneratorCLR.cs, src/Xamarin.Android.Build.Tasks/Utilities/RuntimePropertiesParser.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingReleaseNativeAssemblyGeneratorCLR.cs, src/java-runtime/java-runtime.targets, src/java-runtime/java/mono/android/clr/MonoPackageManager.java
A few more modifications brought over from #9572 to make that PR smaller
=> A handful more changes from #9572

.github/copilot-instructions.md
Copilot has a habit of making changes you didn't ask for. So add some instructions to make it only do changes if asked.
=> Update copilot instructions.

.external
Changes: https://devdiv.visualstudio.com/DevDiv/_git/android-platform-support/branchCompare?baseVersion=GC03686c7f519923da5fd2e461a26890c2a229bdfe&targetVersion=GC77445b27f654230a2dfb1af8326a6e1e0bb1f64a
* Merged PR 613751: [Xamarin.Installer.Build.Tasks] Install JDK 17.0.14
* Merged PR 613510: [CodeQL] Suppress SM02196 - Weak cryptography
=> Bump to android-platform-support@77445b27

.external, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
Changes: https://devdiv.visualstudio.com/DevDiv/_git/android-platform-support/branchCompare?baseVersion=GC08bbd9d3b401589cfe8ac5416abfbe36bf0289ac&targetVersion=GC2f5580c6e6121c5253098829b05a72ba36ae4da1
* Merged PR 613753: [Xamarin.Installer.Build.Tasks] Install JDK 17.0.14
Updates build and test jobs to prefer JDK 17.0.14 over 17.0.12.
=> [release/9.0.1xx] Bump to android-platform-support@2f5580c6

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 11130701

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/GitBranch.cs
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20250306114517244 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20250306114517244 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 11148115

NuGet.config, eng/Version.Details.xml, eng/Versions.props
Changes: https://github.com/dotnet/android/compare/fea9dcd5824c760485e39138b38999c303da8b56...82d8938cf80f6d5fa6c28529ddfbdb753d805ab4
=> Update .NET 8 Android workload version to 34.0.154

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 11527204

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20250505103215321 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20250505103215321 to main

Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20250506103213127 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20250506103213127 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 11539811

src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 11548797

src/Xamarin.Android.Build.Tasks/Tasks/BuildAppBundle.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateNativeApplicationConfigSources.cs, src/Xamarin.Android.Build.Tasks/Utilities/ACWMapGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/Aapt2Daemon.cs, src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs, src/Xamarin.Android.Build.Tasks/Utilities/AssemblyCompression.cs, src/Xamarin.Android.Build.Tasks/Utilities/BundleConfigSplitConfigsChecker.cs, src/Xamarin.Android.Build.Tasks/Utilities/FileUtil.cs, src/Xamarin.Android.Build.Tasks/Utilities/JCWGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/JsonExtensions.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/FunctionAttributes.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrModule.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrVariable.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/NativeAssemblerAttribute.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/StringHolder.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Utilities/NativeLinker.cs, src/Xamarin.Android.Build.Tasks/Utilities/NdkTools/NdkTools.cs, src/Xamarin.Android.Build.Tasks/Utilities/NdkTools/NdkVersion.cs, src/Xamarin.Android.Build.Tasks/Utilities/ResourceDesignerImportGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/ResourceParser.cs, src/Xamarin.Android.Build.Tasks/Utilities/SatelliteAssembly.cs, src/Xamarin.Android.Build.Tasks/Utilities/ZipArchiveEx.cs
Enable NRT for some "utility" classes in `Xamarin.Android.Build.Tasks` that only needed trivial changes.
The conventions established in https://github.com/dotnet/android/pull/10099 were used.
=> [XABT] Enable NRT for some utility classes.

.github/ISSUE_TEMPLATE/01-building-an-application.yml, .github/ISSUE_TEMPLATE/02-running-an-application.yml, .github/ISSUE_TEMPLATE/03-mono-android-api.yml, .github/ISSUE_TEMPLATE/04-binding-a-java-library.yml, .github/ISSUE_TEMPLATE/05-other.yml
Instead of assignees, we're going to simply "watch" the entire repo going forward.
=> [github] cleanup issue template

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 11944384

Localize/loc/cs/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/de/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/es/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/fr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/it/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ja/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ko/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pl/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/pt-BR/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/ru/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/tr/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hans/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl, Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20250715103211176 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20250715103211176 to main

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 11966987

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
Context: https://learn.microsoft.com/en-us/java/openjdk/download#openjdk-2108-lts--see-previous-releases
=> [build] build with Open JDK 21.0.8

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/commercial-build.yaml, build-tools/automation/yaml-templates/install-microbuild-tooling.yaml
This will supposedly resolve our signing issues, so I removed this value and copied the condition in each location.
=> [ci] remove `$(MicroBuildSignType)` variable
