dotnet/android

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/FrameworkPath.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj, tools/xabuild/XABuildPaths.cs
We were using the Microsoft.NET.SDK from the
`/usr/local/share/dotnet` path for our unit
tests. However this does not seem to be installed
on our CI system. Instead we should be using the
on which is shipped with mono itself.
=> [Xamarin.Android.Build.Tests] use mono DotNet SDK install

src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs, src/Xamarin.Android.Build.Tasks/Tasks/MakeBundleNativeCodeExternal.cs, src/Xamarin.Android.Build.Tasks/Tasks/NdkUtils.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/NdkUtilTests.cs
Fixes the test failures introduced in: https://github.com/xamarin/xamarin-android/pull/2709
I initially authored the changes in [#2709][0] against a `master` commit
that was a few before the [switch to Android NDK r19][1].  When I
locally merged the changes onto the tip of `master`, I didn't notice
that the `MakeBundleNativeCodeExternal` and `Aot` tasks were now calling
the new method `NdkUtil.Init()` before `NdkUtil.ValidateNdkPlatform()`.
And unfortunately since there was some urgency to get the corresponding
backport ready for the `d16-0` branch, I didn't get a chance to re-build
and re-test locally against the tip of `master`.  Long story short, to
support the new order of method calls, the NDK existence check now needs
to happen at the time of the call to `GetNdkToolchainRelease()` …
=> [Xamarin.Android.Build.Tasks] Correct Android NDK existence check

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/FilesTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.Shared.projitems, src/Xamarin.Android.Build.Tasks/Utilities/Files.cs
Fixes: http://work.devdiv.io/760829
I've recently discovered a scenario that requires a `Rebuild` to fix...
1. File -> New Xamarin.Forms Project in IDE
2. Do *not* build! Note that the IDE will do a build for Intellisense:
design-time build in VS Windows and `UpdateAndroidResources` in VS
Mac
3. Update NuGet packages (they are `<PackageReference/>`)
4. Build
You will likely hit `APT0000` errors and/or Java compilation errors:
/Users/builder/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.10/bin/javac -J-Dfile.encoding=UTF8 -d obj/Release/android/bin/classes -classpath /Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v8.1/mono.android.jar:obj/Release/lp/0/jl/formsviewgroup.jar:obj/Release/lp/10/jl/bin/classes.jar:obj/Release/lp/11/jl/bin/classes.jar:obj/R …
=> [Xamarin.Android.Build.Tasks] #deletebinobj and ResolveLibraryProjectImports

src/mono-runtimes/mono-runtimes.targets
This is based on https://github.com/xamarin/xamarin-android/pull/2658#issuecomment-458784895, amended for some intricacies of libmono-native building.
This produced fully jumbled output such as (while in `bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/lib`):
```
➜  file host-Darwin/libmono-native.dylib
host-Darwin/libmono-native.dylib: ELF 32-bit LSB pie executable Intel 80386, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, with debug_info, not stripped
➜  file armeabi-v7a/libmono-native.so
armeabi-v7a/libmono-native.so: Mach-O 64-bit dynamically linked shared library x86_64
```
while at the same time (in `external/mono/sdks/out`):
```
➜  file android-host-Darwin-release/lib/libmono-native-unified.dylib …
```
=> [mono-2018-10] Bundle libmono-native

build-tools/cmake/xa_macros.cmake, src/Mono.Android/Test/Mono.Android-Test.Shared.projitems, src/Mono.Android/Test/Mono.Android-Tests.csproj, src/Mono.Android/Test/Mono.Data.Sqlite/SqliteTests.cs, src/sqlite-xamarin/CMakeLists.txt, tests/Runtime-MultiDex/Mono.Android-TestsMultiDex.csproj, tests/Runtime-MultiDex/Resources/Resource.designer.cs
After commit
https://github.com/xamarin/xamarin-android/commit/52190d70725c0973f8dacb250cf904c70d7e1539
all the native libraries we build that use cmake were built with the
`-fvisibility=hide` compiler flag which hides all the symbols defined by the
library unless told otherwise on per-symbol basis. This is not desired for our
build of sqlite since, obviously, its functions have to be visible in order for
`Mono.Data.Sqlite` to be able to p/invoke them, otherwise we end up in a
situation when we have the following errors on the runtime:
02-06 16:47:05.746 I/MonoDroid( 2613): UNHANDLED EXCEPTION:
02-06 16:47:05.791 I/MonoDroid( 2613): System.TypeInitializationException: The type initializer for 'Mono.Data.Sqlite.UnsafeNativeMethods' threw an exception. ---> …
=> [sqlite] Unhide symbols in the native library

src/Mono.Android/Test/Resources/layout/Main.axml, tests/Runtime-MultiDex/Mono.Android-TestsMultiDex.csproj, tests/Runtime-MultiDex/Resources/Resource.designer.cs, tests/Runtime-MultiDex/Resources/layout/Main.axml
Currently when running the Mono.Android-Test app
we get the following error
Java.Lang.RuntimeException: Binary XML file line #1: You must supply a layout_width attribute.
This is because the `ScrollView` now needs to have
the `layout` properties for `width` and `height`.
Filling those in we then get
Scrollview can host only one direct child
So we then need to add a `LinearLayout` to the `ScrollView`
so that it removes that error as well.
=> [Tests] Fix Layout so the test app actually runs

build-tools/scripts/Packaging.mk
Downstream in monodroid, we need to specify an additional directory to include when running:
make package-test-errors
`$(XA_TEST_ERRORS_EXTRA)` can be set to include additional files.
=> [build] add $(XA_TEST_ERRORS_EXTRA)

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
Commit https://github.com/xamarin/xamarin-android/commit/578e781ba added support
for using the `msbuild.rsp` response file when running tests in order to work
around issues with diacritic characters on the command line. The commit assumed
that the response file will be picked up automatically if it's found in
the *project root directory*, however this is not the case as the response file
is [documented][0] to exist in the same directory as `msbuild.exe` and thus some
tests (EmbededDSOs, CodeBehind) were failing to build since important properties
required for them to work were only in the response file and not specified on
the command line passed to `msbuild.exe`.
We missed the issue because Jenkins gave us a false-positive green build for
those changes where in reality the tests did [not …
=> [tests] Fix msbuild response file usage

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
Downstream in monodroid, we have a test failure:
18:56:55   1) Failed : Xamarin.Android.Build.Tests.PackagingTest.NetStandardReferenceTest
18:56:55   Microsoft.NET.Sdk not found.
18:56:55   at Xamarin.Android.Build.Tests.PackagingTest.NetStandardReferenceTest ()
We likely introduced this in ef7a38d, but there isn't enough logging
to see what went wrong. When I logged into the build machine the
directory we are looking for looked correct.
I changed `PackagingTest` to log the directory it used, and added a
`Console.WriteLine` call in `Builder.cs`.
=> [tests] more logging around MicrosoftNetSdkDirectory

.gitmodules
Upstream changes:
SQLite Release 3.27.1 On 2019-02-08
Fix a bug in the query optimizer: an adverse interaction between the OR
optimization and the optimization that tries to use values read directly
from an expression index instead of recomputing the expression. Ticket
4e8e4857d32d401f
Changes carried forward from version 3.27.0 (2019-02-07):
* Added the VACUUM INTO command
* Issue an SQLITE_WARNING message on the error log if a double-quoted string
literal is used.
* The sqlite3_normalized_sql() interface works on any prepared statement
created using sqlite3_prepare_v2() or sqlite3_prepare_v3(). It is no longer
necessary to use sqlite3_prepare_v3() with SQLITE_PREPARE_NORMALIZE in order
to use sqlite3_normalized_sql().
* Added the remove_diacritics=2 option to FTS3 and FTS5.
* Added the …
=> Bump SQLite to v3.27.1

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
Downstream in monodroid, we are still seeing a failure in
`NetStandardReferenceTest`:
Using $(FrameworkSDKRoot): /Library/Frameworks/Mono.framework/Versions/5.18.0/lib/mono/
[TESTLOG] Test NetStandardReferenceTest Complete
...
Microsoft.NET.Sdk not found:
But if I test on my machine `$(FrameworkSDKRoot)` is:
/Library/Frameworks/Mono.framework/Versions/5.18.0/lib/mono/msbuild/
Both the build machine and mine have the same version of Mono.
I think we should just make sure the path we are using includes
`/msbuild/` and append the directory if needed.
Other change:
* On Windows, it was always logging `Using $(FrameworkSDKRoot): `. So
let's not log that if it is blank.
=> [Xamarin.ProjectTools] check for /msbuild/ in $(FrameworkSdkRoot)

src/Xamarin.Android.Build.Tasks/Resources/proguard_xamarin.cfg, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Utilities/DexUtils.cs
Context: https://www.guardsquare.com/en/products/proguard/manual/usage#keepoptionmodifiers
Context: https://www.guardsquare.com/en/products/proguard/manual/examples
Fixes: https://github.com/xamarin/xamarin-android/issues/2684
Using R8 on a pre-Android 8.0 device was crashing with:
E/mono    (16220): Unhandled Exception:
E/mono    (16220): Java.Lang.LinkageError: no non-static method "Landroid/runtime/UncaughtExceptionHandler;.<init>()V"
E/mono    (16220):   at Java.Interop.JniEnvironment+InstanceMethods.GetMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <7d7bcc9ee9cc460db8abcdb9a9622733>:0
E/mono    (16220):   at Java.Interop.JniType.GetConstructor (System.String signature) [0x0000c] in <7d7bcc9ee9cc460db8abcdb9a9622733>:0
E/mono …
=> [Xamarin.Android.Build.Tasks] fix proguard rules for R8 compatibility

Configuration.props
The latest commercial Xamarin.Android preview release coming from d16-0
is now versioned 9.2.0. A $(ProductVersion) bump is now required so that
newer versions of the Xamarin.Android .vsix installer can be installed
on top of the latest Visual Studio 2019 Previews.
=> Bump $(ProductVersion) to 9.2.99

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RenameTestCases.cs, build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/ErrorResultsHelper.cs, build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/ProcessPlotInput.cs, build-tools/xa-prep-tasks/xa-prep-tasks.csproj
It is usually hard to notice the problem, when logcat processing fails
because of the logcat file missing. Thus it will make it easier to
find, when we create `TestResults` file with an error, similar to
`RenameTestCases` task.
=> [tests] Create test results, when processing logcat output fails

tests/Runtime-MultiDex/Mono.Android-TestsMultiDex.projitems
We see these errors in our jenkins builds:
/Users/builder/jenkins/workspace/xamarin-android-pr-builder-release/xamarin-android/build-tools/scripts/TestApks.targets(217,5): error : Input file 'logcat-Release-Aot-Mono.Android_TestsMultiDex.txt' doesn't exist. [/Users/builder/jenkins/workspace/xamarin-android-pr-builder-release/xamarin-android/tests/RunApkTests.targets]
Build continuing because "ContinueOnError" on the task "ProcessLogcatTiming" is set to "ErrorAndContinue".
Turns out, that the reason for that is, that the
`Mono.Android_TestsMultiDex` test is not run, because no
`RunInstrumentationTests` nor `RunUITests` is used as their condition
clauses are resolved as **false**.
This is fixed by adding `TestApkInstrumentation` (and
`TestApkPermission` plus `TestApkPermission`) item …
=> [tests] Make the Mono.Android_TestsMultiDex run

Documentation/guides/BuildProcess.md, Documentation/guides/messages/README.md, Documentation/guides/messages/xa1006.md, Documentation/guides/messages/xa1007.md, Documentation/guides/messages/xa1008.md, Novell/MonoDroid.FSharp.targets, Novell/Novell.MonoDroid.CSharp.targets, Novell/Novell.MonoDroid.Common.targets, src/Xamarin.Android.Build.Tasks/Tasks/CheckGoogleSdkRequirements.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/CheckGoogleSdkRequirementsTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context https://github.com/xamarin/xamarin-android/issues/1768
Google has the following guidance for these three values:
> minSdkVersion (lowest possible) <= targetSdkVersion == compileSdkVersion (latest SDK)
This commit adds a new Task `CheckGoogleSdkRequirements` which is responsible for checking
these values. It will be enabled by default but the task can be disabled via the
`AndroidEnableGooglePlayStoreChecks` property.
=> Provide warnings around compileSdkVersion(TargetFrameworkVersion), targetSdkVersion, and minSdkVersion

src/monodroid/jni/dylib-mono.cc, src/monodroid/jni/dylib-mono.h, src/monodroid/jni/monodroid-glue.cc
Refactor the events code a bit to avoid duplication
Note: I didn't see any failed events in the log. I hoped it might shed
light on parts like this one:
JIT method  begin: (wrapper managed-to-native) Android.Runtime.Logger:__android_log_print (Android.Runtime.LogLevel,string,string,string,intptr) elapsed: 0s:139::103087
JIT method   done: Android.Runtime.Logger:__android_log_print (Android.Runtime.LogLevel,string,string,string,intptr) elapsed: 0s:139::226837
JIT method   done: (wrapper managed-to-native) Android.Runtime.Logger:__android_log_print (Android.Runtime.LogLevel,string,string,string,intptr) elapsed: 0s:139::232723
JIT method   done: Android.Runtime.Logger:__android_log_print (Android.Runtime.LogLevel,string,string,string,intptr) elapsed: 0s:139::238712
I think it is still useful …
=> [monodroid] Hookup the jit_failed event as well

Documentation/building/windows/instructions.md
* Fixed a broken link (since we split up docs)
* Added a section on alternatives to the developer command prompt
=> [docs] expand Building on Windows instructions

Configuration.props
Context: http://dl-ssl.google.com/android/repository/repository2-1.xml
Mainly doing this to make sure the following changes are sound:
* e84e502
* 7b16dd5
Details I'm seeing from the manifest:
Generated from:ab bid:5264690 branch:aosp-emu-3.0-release
Built on: Mon Jan 28 16:33:00 2019.
=> [build] bump the emulator to 5264690

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BuildHelper.cs
We have a problem in our tests when the build passes,
but the unit test fails. In this case the `ProjectBuilder`
is auto cleaning up the failed test build directory along
with ALL the logs.
So Lets NOT clean up by default. This does not mean that
we will leave files on disk for passed tests since the
`BaseTest.CleanupTest` [1] method is an nunit `TearDown` method.
So it runs at the end of the test and will clean up the
directory if the test passed.
[1] https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs#L376
=> [Xamarin.Android.Build.Tests] Dont auto clean up tests.

src/mono-runtimes/mono-runtimes.projitems, src/mono-runtimes/mono-runtimes.targets
32-bit Windows DLLs cannot be stripped (`strip` from mxe fails when attempting
to do that). This commit adds a metadata item to the `_MonoRuntime` items which
tells the build whether it's ok to strip the DLL for particular instance of
the runtime build.
=> Don't strip some Windows DLLs

src/r8/build.gradle
Context: https://mvnrepository.com/artifact/com.android.tools/r8/1.3.52
Context: https://r8.googlesource.com/r8/+/refs/tags/1.3.52/build.gradle#52
Update r8 to the latest stable release on Maven.
There is also now some dependencies on packages at:
https://kotlin.bintray.com/kotlinx
I updated the `repositories` defined in `build.gradle` to match what r8's source code has.
=> [r8] bump to 1.3.52

build-tools/automation/build.groovy
Related to PR #2743.  Prior to the Xamarin.Android (release) build moving from a freestyle to a pipeline build, the publish location included both the job name (xamarin-android) *and* the checkout directory name (xamarin-android) in the publish url path such as the following - note the redundant xamarin-android names (JOB_NAME/DIR_NAME) at the end:
http://xamjenkinsartifact.blob.core.windows.net/mono-jenkins-eval/xamarin-android/xamarin-android
After moving to the pipeline build based on the build.groovy jenkinsfile, the publish location changed to the following:
http://xamjenkinsartifact.blob.core.windows.net/mono-jenkins-eval/xamarin-android
This breaks anyone or any system that is looking for published packages in the original location.
The problem was introduced when the publish …
=> Fix pipeline build publish location

src/Xamarin.Android.Build.Tasks/Xamarin.Android.FSharp.targets
Context: https://devblogs.microsoft.com/dotnet/announcing-f-4-5/
Since VS 15.8 on Windows, F# 4.5 is now installed along with Visual
Studio to support side-by-side installations. Previously F# was
installed in a system-wide location specified by `%FSHARPINSTALLDIR%`:
C:\Program Files (x86)\Microsoft SDKs\F#\10.1\Framework\v4.0\
The new locations are, for example:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\FSharp
I have also seen a few instances where our F#-related MSBuild tests
failed on Windows, failing to import `Microsoft.FSharp.targets`:
bin\TestRelease\temp\BuildBasicApplicationFSharp\UnnamedProject.fsproj error MSB4057: …
=> [Xamarin.Android.Build.Tasks] support F# 4.5 Windows path

build-tools/scripts/RunTests.targets
For PR builds we build i `Release` mode but we
dont build the cross compiler tooling. As a result
our `RunApkTests` will fail when try try to use
`AotAssemblies` or `BundleAssemblies`.
So we should check that the tooling exists before
we try to use it.
=> [scripts] Check if the CrossCompiler is available.

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
Context https://devdiv.visualstudio.com/DevDiv/_workitems/edit/679400
When we try to resolve the `runtime` assembly we may well
get a `_._` instead of the filename. This usually means
that the assembly will be provided by the framework. When
this happens we get the following error
Error: Exception while loading assemblies: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA0009: Error while loading assembly: /Users/tamasszadvari/.nuget/packages/system.runtime.loader/4.3.0/lib/MonoAndroid10/_._
So we should really be ignoring this particular senario.
=> [Xamarin.Android.Build.Tasks] Check for `_._` in the Nuget path.

src/Xamarin.Android.Build.Tasks/Tasks/CollectNonEmptyDirectories.cs
Some of the designer tests upstream are producing
errors such as
The "CollectNonEmptyDirectories" task failed unexpectedly.
error MSB4018: System.IO.DirectoryNotFoundException: Could not find `res`
We should not be crashing out of the directory does
not exist. We should just skip it since this task is
called `CollectNonEmptyDirectories`, and not existing
means its empty.
=> [Xamarin.Android.Build.Tasks] Handle bad `res` data.

src/Xamarin.Android.Build.Tasks/Tasks/CompileToDalvik.cs, src/Xamarin.Android.Build.Tasks/Tasks/D8.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Downstream in monodroid, we need to dex java libraries independently
for "Enhanced Fast Deployment". This means that in some cases, we
don't need to dex `classes.zip`.
So a few changes were needed:
* `<D8/>` should not have the `ClassesZip` property marked as
`[Required]`.
* `<CompileToDalvik/>` should take `ClassesZip` as an input and use it
if not blank. This is better than using:
`Path.Combine (ClassesOutputDirectory, "..", "classes.zip")`
=> [Xamarin.Android.Build.Tasks] make classes.zip optional for dexing

Documentation/guides/messages/README.md, Documentation/guides/messages/xa0113.md, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ResolveSdksTaskTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
When you compile a library you might not want to target the latest SDK, as it could hose users targeting lower-end api-levels. However you currently get a warning that really only applies to applications, and not class libraries.
This PR skips the API Level check when the target isn't an application.
Also there were two near-identical warnings on the same check, so I consolidated those into a single warning (it looks like this was historical as updates vs new apps were on different timelines)
@jonathanpeppers
=> Avoid play store warnings when building libraries

build-tools/mingw-dependencies/mingw-dependencies.projitems
When Windows cross-build targets are enabled, Xamarin.Android builds a set of
Windows libraries our runtime is dependent on. Libraries are configured with
cmake and built with ninja. However, the exact location of the ninja binary was
not specified when configuring the libraries for build and, thus, the build may
fail if there's no `ninja` available in the host machine's PATH.
Pass to cmake full path to the Android SDK's ninja to make sure cmake finds the
binary.
=> [build] Use specific ninja binary for mingw cross-builds

src/libzip-windows/libzip-windows.projitems, src/libzip/libzip.projitems
Commit f44de8e987a6fc5e80c24308dd51b7a674940773 made a change to build Windows
libraries with a specific `ninja` binary. However, it seems that there are more
places where this ninja treatment is necessary.
This commit applies the treatment to both host and Windows `libzip` builds.
=> [build] Use specific ninja binary for libzip builds

Makefile, build-tools/automation/build.groovy, build-tools/scripts/Packaging.mk, build-tools/scripts/RunTests.targets, build-tools/scripts/msbuild.mk
There was some unexpected and unforeseen fallout from commit 241d9416:
`make package-build-status` is only run once.
This doesn't *sound* problematic -- hence the oversight -- but the
`msbuild*.binlog` files that the `xa-build-status*.zip` file contained
prior to commit 241d9416 contained *unit test execution logs*, e.g.
`msbuild-*-Target-RunApkTests.binlog`	which contains on-device
execution of the `.apk` unit tests.
However, these files don't exist until *after* the unit tests are run.
Meanwhile, `make package-build-status` is executed *before* unit tests
are run, and thus the resulting `xa-build-status*.zip` file no longer
contains unit test information!
(This makes it rather difficult to actually review anything about unit
test execution!)
The fix?  Update the `$(MSBUILD_BINLOG)` Make …
=> [build] Upload unit test results

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
In preparation for branching for d16-1, we need `$(AndroidUseAapt2)`
to be disabled by default.
We currently have aapt2 disabled on d16-0: ac1b29e8
I am hoping a one-line change is all we need here, since master also
has: 61716bb3
=> [Xamarin.Android.Build.Tasks] AndroidUseAapt2 defaults to False

src/Mono.Android/Android.Runtime/JNIEnv.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/2679
Context: https://github.com/xamarin/xamarin-android/pull/2753
If `System.Security.Cryptography.X509Certificates.X509Certificate`
(from `mscorlib.dll`) is used *before*
`System.Security.Cryptography.X509Certificates.X509Certificate2`
(from `System.dll`), then a `PlatformNotSupportedException` is thrown:
System.PlatformNotSupportedException: Cannot get `ISystemDependencyProvider`.
at Mono.DependencyInjector.get_SystemProvider ()
at System.Security.Cryptography.X509Certificates.X509Helper.get_CertificateProvider ()
at System.Security.Cryptography.X509Certificates.X509Helper.Import (System.Byte[] rawData)
at System.Security.Cryptography.X509Certificates.X509Certificate..ctor (System.Byte[] data)
at App7.MainActivity.OnCreate …
=> [Mono.Android] Call SystemDependencyProvider.Initialize()

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ConvertResourcesCasesTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs
Fixes #2769
Our `ConverResourcesCases` task was NOT processing
`mipmap` xml items. The RegEx needed to be updated
to include `mipmap` items so that we can lowercase
the items within those files.
Also added a unit test.
=> [Xamarin.Android.Build.Tasks] Fix issue with Adaptive Icons

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
APK building process includes a step to put native libraries (Mono runtime,
Xamarin.Android runtime etc) into the archive. This is done by including known
`*.so` files from the per-architecture library directories in the
Xamarin.Android source tree or from a location on the end user's computer.
Unfortunately, currently this process uses a glob pattern to find the required
libraries which may include Linux host libraries with those names, thus
producing the following error when attempting to build any application which
needs to embed SQLite, libMonoPosixHelper or (in the `mono-2018-10` branch)
libmono-native DSOs:
Adding native library: bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/lib/arm64-v8a/libmono-profiler-log.so (APK path: lib/arm64-v8a/libmono-profiler-log.so) (TaskId:320) …
=> Don't include host *.so libraries in the APK

Documentation/guides/BuildProcess.md
* Bring in the typo corrections from the current version of the
document on:
https://docs.microsoft.com/xamarin/android/deploy-test/building-apps/build-process
* Correct spelling and formatting of the newly added items.
* Remove trailing whitespace and adjust all the list items to use the
same indentation levels.
* Alphabetize the various items.  I double-checked the new order in
each section by `grep`ing to get the first line of each list item or
header element, removing the list and header markers, and then
`diff`ing with the output of `sort`.  All the sections now match the
`sort` order.
After these changes, `BuildProcess.md` will be ready to copy into the
MicrosoftDocs/xamarin-docs repository to update the document on
docs.microsoft.com.
=> [docs] Prepare BuildProcess for sync to docs.microsoft.com

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/xamarin-android/commit/eca09c89db42c6dbd5cd2f57c6da2196d86ff761#diff-db39bf07b89b50eaab8ab2001546310cR459
In eca09c8, I fixed cases where our MSBuild targets were running every
time. We missed some breakage happening in the designer:
1. NuGet restore on a new project
2. Designer calls `SetupDependenciesForDesigner`
3. Designer calls `GetExtraLibraryLocationsForDesigner`
`GetExtraLibraryLocationsForDesigner` was not returning all the paths
required, since `_BuildAdditionalResourcesCache` was skipped on step
no. 2!
To fix this:
* Moved the `Condition` from the target to the `<Touch/>` call.
* This should allow the target to build incrementally, but still
prevent downloads on DTBs.
I also updated a few tests around this scenario.
=> [Xamarin.Android.Build.Tasks] fix designer breakage around _BuildAdditionalResourcesCache

build-tools/automation/build.groovy, build-tools/scripts/Packaging.mk, tests/api-compatibility/api-compatibility.mk
The `make run-api-compatibility-tests` target may create a set of HTML
files within `bin/Build$(Configuration)/compatibility`, which would
create an **API Compatibility Checks** "side-bar" for *freestyle*
builds, reporting any API breakage.
This functionality is lost with the new Pipeline builds.
Add a `publishHTML` invocation to `build.groovy` so that API brekage
can be nicely reported when it occurs.
Additionally, update `tests/api-compatibility` so that the test
results are placed into the `bin/Test$(Configuration)` directory, not
`bin/Build$(Configuration)`, and update `make package-test-results` to
include the API compatibility results.
=> [build] Publish API Compatibility Checks

src/Xamarin.Android.Build.Tasks/Tasks/ConvertCustomView.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ZipArchiveExTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes #2501 
There is a problem with our `aapt2` support where
custom views do not have their namespaces replaced
with the `{md5}` hash which is generated by
`GenerateJavaStubs`.
This is due to the order in which we need to do certain
operations. For `aapt2` we need to run `aapt2 compile` to
generate the `flata` archives, these are then passed to
`aapt2 link` to generate the `packaged_resources` archive.
The idea was to get the `compile` step done early in
the build so we could reuse the `flata` archives.
We have to do this for generating the `Resources.desinger.cs`.
The problem is `GenerateJavaStubs` does not run until AFTER
`CoreCompile` at this point the `flata` archives are already
in place. As a result they do not include the fixed up
custom views. So to work around this issue we …
=> [Xamarin.Android.Build.Tasks] Support CustomViews with Aapt2

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
The designer's integration tests have been failing on master, due to:
* The `GetExtraLibraryLocationsForDesigner` MSBuild target returns
`ExtraJarLocation` and `ExtraResourceLocation` target outputs.
* `ExtraJarLocation` was blank in the tests?
Investigating further, the cache file this target reads from,
`obj\Debug\designtime\libraryprojectsimports.cache`, seemed to be
*wrong*:
<Paths><Jars />...</Paths>
The `*.jar` files existed in `obj\Debug\lp`, but this cache file was
incorrect?
In 98d881b, I reworked `<ResolveLibraryProjectImports/>` so that we
could avoid #deletebinobj problems with file timestamps by using
hashes instead.
The `_ResolveLibraryProjectImports` target and
`<ResolveLibraryProjectImports/>` task have some optimizations for
incremental builds:
* The …
=> [Xamarin.Android.Build.Tasks] fix incremental ResolveLibraryProjectImports

Documentation/guides/MSBuildBestPractices.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/jonathanpeppers/MSBuildIncrementalClean
Through research into MSBuild, there are two problem we generally want
to fix:
* We have targets we want to run *before* `IncrementalClean`. Our
current implementation uses a private MSBuild target to achieve
this.
* We have use of `BeforeTargets` and `AfterTargets`, which causes some
problems.
One problem we have, is that usage of `AfterTargets` causes C#
compiler errors to produce extra (and confusing errors):
MainActivity.cs(9,7): error CS0246: The type or namespace name 'ClassLibrary1' could not be found (are you missing a using directive or an assembly reference?)
Would also trigger this:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2160,5): …
=> [Xamarin.Android.Build.Tasks] remove usage of Before/AfterTargets

build-tools/automation/build.groovy
With the xamarin-android build being applied to PR builds, it is critical that the build be made more resilient to connectivity glitches.  There is one such case where the build failed during the checkout stage due to known network issues.  There is a good chance in that that the checkout stage would have succeeded if given another chance.  
Added retry capability to the build.groovy pipeline script, which includes a wait between retries. The wait increases exponentially on each retry.  Retries have been enabled for stages that depend on connectivity for checkout and publishing of results.  These stages are good candidates for retry as they will most likely fail due to connectivity issues as opposed to an issue within the code being built.
Build failure as inspiration for this PR: …
=> Pipeline build: Retries for better network resiliency

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: http://work.devdiv.io/813889
In VS for Mac 2019 Preview, a specific scenario is broken:
1. Download the repro (the creatively-named, perhaps legendary?
`App72.sln`)
2. Delete the `bin` and `obj` directories
3. Open a new VS for Mac instance. (`Automatic NuGet restore` should
be off)
4. Open the solution, wait for any build progress to complete such as
`Updating resources...`, etc.
5. Restore NuGet packages via `Project->Restore NuGet Packages`
6. Open `MainPage.xaml`: designer displays a gray rectangle that says
"AndroidFormsPreviewerRenderer"
Doing a full Build solves the problem, but this is the whole point of
the "build-less" designer/previewer feature in Dev16.
Behind the scenes, the failure is the `SetupDependenciesForDesigner`
MSBuild target. Opening the designer's log file, …
=> [Xamarin.Android.Build.Tasks] fix for "build-less" designer

build-tools/automation/build.groovy, src/mono-runtimes/mono-runtimes.targets
Context: https://github.com/xamarin/xamarin-android/pull/2790
Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-pr-builder-release/1001/
Mono bumps are expected to be time consuming.  They can also be
expected to produce *lots* of build log output.
What's unexpected is the *vast size* of the build logs: a "normal" PR
build log is usually ~20-30MB in size.  Add in a complete mono bump,
and the build log becomes 1.4GB.
Take a page out of commit 987a05fa8: the Console log has "normal"
verbosity, and `.binlog` files are produced which contain "diagnostic"
level output.  Why does the Console log for mono bumps need to be so
ginormous?
The answer is, they don't.
Update the `<Exec/>` tasks within `mono-runtimes.targets` so that
`StandardOutputImportance="Low"` is …
=> [mono-runtimes] `make` output is of Low importance

tools/jit-times/jit-times.csproj
`jit-times.csproj` had a couple issues that caused it to not build on
Windows:
* `Configuration.props` was imported *after* the `Debug` configuration
settings, so `$(XAInstallPrefix)` wasn't declared.
* The reference to `Mono.Options.dll` should actually point to the
`packages` directory at the root of this repo.
=> [build] fixes for jit-times.csproj

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks.csproj, build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/GitCommitInfo.cs, build-tools/xa-prep-tasks/xa-prep-tasks.csproj
When building `Xamarin.Android.sln` (even with no changes),
`<GitCommitInfo/>` runs 15 times, which takes about 6 seconds on my
machine.
Reviewing the input values to `<GitCommitInfo/>`, 2/3 of the calls
seem to be duplicate. This is a classic example where
`RegisterTaskObject` can help.
I cached the `CommitInfo` output property using the important inputs
as a key to `RegisterTaskObject`:
* `WorkingDirectory`
* `XASourceDirectory`
* `SubmoduleName`
* `GitRemoteName`
I used the simple syntax for creating a C# tuple as the lookup key. I
had to update the TFV of two projects to v4.7 to use the simplified
tuple syntax. I prefer this over `Tuple<string,string,string,string>`.
This saves ~4 seconds on incremental builds of `Xamarin.Android.sln`.
=> [build] use RegisterTaskObject in <GitCommitInfo/>

build-tools/dependencies/dependencies.projitems, build-tools/mingw-dependencies/mingw-dependencies.projitems, build-tools/mingw-dependencies/mingw-dependencies.targets, src/libzip-windows/libzip-windows.projitems, src/libzip/libzip.projitems, src/libzip/libzip.targets
Commit a014bd30 reverted e84e502e in hope that we will be able to properly
bootstrap from a squeeky clean system, but that hope was failed because I missed
the fact that `mingw-dependencies` and `libzip` as well as `libzip-windows`
projects, all built during the `android-toolchain` phase used the `cmake` and
`ninja` programs provided with the Android SDK. Well, that couldn't work :P
This commit makes the above projects build with the system `cmake` and `ninja`
binaries and adds both of them to list of macOS dependencies.
If this works fine we will be able to restore e84e502e
=> [build] Use system cmake and ninja to build mingw deps and libzip

src/proguard/proguard.targets, src/r8/r8.targets
If you build `Xamarin.Android.sln`, a lot of stuff happens even if
there are no changes...
Our build doesn't follow our own "MSBuild Best Practices", and we have
a few MSBuild targets that always run.
The main problem here was that we were invoking `gradlew` every time,
and it takes quite a while to startup when using the `--no-daemon`
switch.
I added proper `Inputs` and `Outputs` for the `_BuildR8` MSBuild
target, as well as a `<Touch/>` call.
These changes saved 6 seconds(!!!) on incremental builds of
`Xamarin.Android.sln`.
This project was invoking `<Ant/>` and copying files every time.
I cleaned this project up a bit by creating an `@(_Outputs)` item
group to be used throughout. Adding `Inputs` and `Outputs` to
`_BuildProGuard` and a `<Touch/>` call fixed the incremental build.
The …
=> [build] improve XA's build for proguard & r8

Xamarin.Android.sln, build-tools/automation/build.groovy, build-tools/create-pkg/create-pkg.csproj, build-tools/create-pkg/create-pkg.targets, build-tools/create-pkg/distribution.xml.in, build-tools/create-pkg/scripts/preinstall, build-tools/create-vsix/create-vsix.csproj, build-tools/create-vsix/create-vsix.targets, build-tools/create-vsix/source.extension.vsixmanifest, build-tools/installers/create-installers.targets, build-tools/scripts/Packaging.mk
Introduces a new `create-pkg` project next to `create-vsix` to be used
in a similar way to create a macOS installer for xamarin-android. The
`build-tools/installers/create-installers.targets` file has also been
added to keep track of all of the content we require in both our macOS
and Windows installers. These shared items, properties, and targets are
used by both installer projects to ensure uniformity between the two
installers we produce.
The `ConstructInstallerItems` target determines the majority of the files
which should end up in the installer. Behavior will vary depending on the
existance of certain files or the values of certain msbuild properties.
This was done intentionally to be able to support creating installers for
PR builds, open source packages, and commercial packages. …
=> [installers] Share installer payload generation logic

Configuration.props, build-tools/scripts/Ndk.targets
`cmake` 3.10 is the current version of the tool in the Android SDK,
an update from the much older 3.6. This update brings it closer to
the host `cmake` versions (currently mostly 3.12.*)
Bump NDK to release [19b][0] (a.k.a. 19.1), with the following changes:
* [Issue 855][1]: ndk-build automatically disables multithreaded
linking for LLD on Windows, where it may hang. It is not
possible for the NDK to detect this situation for CMake,
so CMake users and custom build systems must pass
`-Wl,--no-threads` when linking with LLD on Windows.
* [Issue 849][2]: Fixed unused command line argument warning when
using standalone toolchains to compile C code.
* [Issue 890][3]: Fixed CMAKE_FIND_ROOT_PATH. CMake projects will
no longer search the host's sysroot for headers and libraries.
* [Issue …
=> [build] Bump cmake to 3.10 and the NDK to 19b

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsAndroidApplicationProject.cs
I updated usage of Xamarin.Forms to the current 3.6 stable, which has
a few benefits:
* 3.6 includes the patch where Xamarin.Forms is shipping portable
`.pdb` files now. This prevents some of the pdb2mdb errors we see
with our tests running in parallel.
* 3.6 does not require you to list a bunch of support libraries as
`<PackageReference/>` for things to build. The transitive
dependencies work, and the support library 28.x is pulled in
automatically.
Unfortunately, I also discovered a bug when doing this...
The `CompileBeforeUpgradingNuGet` test was hitting a compiler error:
CompileToDalvik:
...
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/annotation/AnimRes;
...
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has …
=> [Xamarin.Android.Build.Tasks] #deletebinobj bug with stale jars

build-tools/installers/create-installers.targets
Context: http://build.devdiv.io/2492963
e83ba0d made quite a few changes to consolidate our installers, yay!
But we started getting a build failure on Azure DevOps:
CreateVsixContainer:
Creating VSIX Container...
Creating the package with the following compression level. "Normal".
E:\A\_work\484\s\packages\Microsoft.VSSDK.BuildTools.15.0.26201\tools\VSSDK\Microsoft.VsSDK.targets(590,5): error VSSDK1025: Could not add the file "E:\A\_work\484\s\\bin\Release\\lib\xamarin.android\xbuild\Xamarin\Android\Java.Runtime.Environment.dll.config" to the zip package "bin\Release\Xamarin.Android.Sdk-OSS-9.2.99.66_HEAD_b77c037.vsix". Could not find file 'E:\A\_work\484\s\bin\Release\lib\xamarin.android\xbuild\Xamarin\Android\Java.Runtime.Environment.dll.config'. …
=> [create-vsix] fix for building the VSIX on Windows

Configuration.props, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: http://work.devdiv.io/788593
Google Play has some new policies coming soon:
Starting August 1, 2019: Google Play Store will require apps to
support 64-bit architectures.
The current recommendation from Google is to provide 64-bit versions
in addition to 32-bit versions of the application.
Starting August 1, 2021: Google Play Store will stop serving apps
without 64-bit versions on 64-bit capable devices.
To prepare for this, we are changing defaults in Xamarin.Android:
<AndroidSupportedAbis Condition=" '$(AndroidSupportedAbis)' == '' ">armeabi-v7a;arm64-v8a</AndroidSupportedAbis>
We may change this at a later date, but this adds `arm64-v8a` to the
list of default architectures.
Additionally, I had to add change `Configuration.props`, so XA's build
will build `arm64-v8a` by default: …
=> [Xamarin.Android.Build.Tasks] include arm64-v8a by default

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Downstream in monodroid, we are having an evaluation ordering problem
with our MSBuild targets. We were intending to append a target to
`$(_ResolveMonoAndroidSdksDependsOn)`, but in fact the opposite is
happening:
Property reassignment: $(_ResolveMonoAndroidSdksDependsOn)="
GetReferenceAssemblyPaths;
" (previous value: "
;_SetupInstantRun
") at Xamarin.Android.Common.targets (868,2)
xamarin-android is overwriting what monodroid has for the value!
The problem was our ordering of `<Import/>`
<Import Project="Xamarin.Android.Common.Debugging.props" />
...
<_ResolveMonoAndroidSdksDependsOn>
GetReferenceAssemblyPaths;
</_ResolveMonoAndroidSdksDependsOn>
...
<Import Project="Xamarin.Android.Common.Debugging.targets" />
The `.props` file was setting an initial value for …
=> [Xamarin.Android.Build.Tasks] prepend to $(_ResolveMonoAndroidSdksDependsOn)

build-tools/installers/create-installers.targets
Context: http://build.devdiv.io/2499023
An integration build for the designer discovered we forgot this file in 4ccbeb7.
=> [installers] add Xamarin.Android.Aapt2.targets

build-tools/debian-metadata/rules
The Linux build [is busted][0]:
dh_clideps -X/usr/lib/xamarin.android/xbuild-frameworks/ \
...
Unhandled Exception:
IKVM.Reflection.BadImageFormatException: Exception of type 'IKVM.Reflection.BadImageFormatException' was thrown.
at IKVM.Reflection.Reader.PEReader.RvaToFileOffset (System.UInt32 rva) [0x00070] in <f3855a9b922743e79049757cdcdbb705>:0
at IKVM.Reflection.Reader.ModuleReader.Read (System.IO.Stream stream, System.Boolean mapped) [0x0004c] in <f3855a9b922743e79049757cdcdbb705>:0
at IKVM.Reflection.Reader.ModuleReader..ctor (IKVM.Reflection.Reader.AssemblyReader assembly, IKVM.Reflection.Universe universe, System.IO.Stream stream, System.String location, System.Boolean mapped) [0x0005b] in <f3855a9b922743e79049757cdcdbb705>:0
at IKVM.Reflection.Universe.OpenRawModule …
=> [linux] Fix the build, by ignoring libwinpthread-1.dll dependency

build-tools/installers/create-installers.targets
As far as I can tell we're not building this file for Windows. If we do need to do so, we could include the Windows build + installer update in this PR or in a future PR.
=> [installers] Add missing 'libmono-native' file

Configuration.props
Downstream in monodroid, we are getting a build error such as:
OpenTK-0.9.JCW.csproj: error : /Users/builder/jenkins/workspace/monodroid-pr/monodroid/src/OpenGLES/OpenTK-0.9.JCW.csproj:
/Users/builder/jenkins/workspace/monodroid-pr/monodroid/external/xamarin-android/Configuration.props: Project file could not be imported, it was being imported by /Users/builder/jenkins/workspace/monodroid-pr/monodroid/src/OpenGLES/OpenTK-0.9.JCW.csproj: Microsoft.Build.Utilities.ToolLocationHelper
OpenTK-0.9.JCW.csproj: Microsoft.Build.BuildEngine.InvalidProjectFileException: /Users/builder/jenkins/workspace/monodroid-pr/monodroid/src/OpenGLES/OpenTK-0.9.JCW.csproj: /Users/builder/jenkins/workspace/monodroid-pr/monodroid/external/xamarin-android/Configuration.props: Project file could not be imported, it …
=> [build] evaluate GetPathToStandardLibraries only when TFV is missing

build-tools/create-pkg/create-pkg.targets, build-tools/create-vsix/create-vsix.targets, build-tools/installers/create-installers.targets
The `ThirdPartyNotices.txt` file is a comprehensive listing of all 3rd
party code which is included in a Xamarin.Android distribution; see
also commit 2bd13c4a.
Commit 2bd13c4a also added `ThirdPartyNotices.txt` to the `.vsix`
installer, allowing it to be read *without* needing to install the
`.vsix` file on Windows; simply `unzip`ing the `.vsix` would allow it
to be viewed.
Unfortunately, we forgot to add `ThirdPartyNotices.txt` to the macOS
installer, and thus e83ba0dd likewise doesn't install it.
Update `build-tools/create-pkg` so that `ThirdPartyNotices.txt` is
installed on macOS into the path:
/Library/Frameworks/Xamarin.Android.framework/Versions/Current/ThirdPartyNotices.txt
=> [create-pkg] Install `ThirdPartyNotices.txt` on macOS

external/sqlite.tpnitems
The `xamarin/sqlite` repo contains two related-yet-distinct sets of
source code:
1. The SQLite source code, in which the authors have disclaimed
copyright, dedicating it to the public domain, and
2. Google's additions for use on Android, which is licensed under the
Apache-2.0 license.
We've been omitting (2) in favor of (1), which isn't quite right.
Update `sqlite.tpnitems` so that *both* sources are listed.  This will
cause `sqlite/sqlite` to be listed, along with it's disclaimer of
copyright, alongside `xamarin/sqlite` with the Apache 2.0 license.
=> [sqlite-xamarin] Update ThirdPartyNotice information

Documentation/guides/messages/README.md, Documentation/guides/messages/xa1009.md, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
We want to remove OpenTK 0.9.3 in the next major
release of Xamarin.Android. This commit adds a
warning so that users will have a chance to
update their projects.
=> [Xamarin.Android.Build.Tasks] Obsolete OpenTK 0.9.3

build-tools/installers/create-installers.targets
Looks like an oversight, we need this binary on all platforms.
=> [installers] Include the jit-times.exe on all platforms

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Continuing the effort to remove `BeforeTargets` and `AfterTargets`, I
am now making changes in monodroid.
One such case is an MSBuild target that needs to run *after*
`_CompileDex`, which is using `AfterTargets` right now.
We already have `$(_AfterCompileDex)`, but it is not specified in
xamarin-android everywhere it needs to be. Anywhere that `_CompileDex`
is listed as a `DependsOnTargets`, we need to list
`$(_AfterCompileDex)` as well.
This change should allow me to finish up the changes in monodroid.
=> [Xamarin.Android.Build.Tasks] fix missing $(_AfterCompileDex)

src/Xamarin.Android.Build.Tasks/Generator/Generator.cs, src/Xamarin.Android.Build.Tasks/Resources/MonoRuntimeProvider.Bundled.java, src/Xamarin.Android.Build.Tasks/Resources/MonoRuntimeProvider.Shared.java, src/Xamarin.Android.Build.Tasks/Tasks/CopyResource.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Context: https://github.com/xamarin/java.interop/pull/422
Context: https://github.com/xamarin/xamarin-android/pull/2841
Bump to xamarin/java.interop/master@7c7eae3a
Changes: https://github.com/xamarin/java.interop/compare/f84c236e...7c7eae3a
In an effort to consolidate our Java source code, there are a couple
files that should be moved into xamarin-android:
* `MonoRuntimeProvider.Bundled.java`
* `MonoRuntimeProvider.Shared.java`
This gives us more flexibility in Xamarin.Android to change these
files, in cases such as:
* Is the shared runtime used?
* Is it a specific API level?
* Could we call into some pre-compiled code instead?
I moved the files, and left them as-is.
The only other changes are due to
`Java.Interop.Tools.JavaCallableWrappers.csproj` no longer containing
resources:
* The …
=> [Xamarin.Android.Build.Tasks] bring in MonoRuntimeProvider

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RenameTestCases.cs, build-tools/scripts/Packaging.mk, build-tools/scripts/TestApks.targets
Context: https://jenkins.mono-project.com/job/xamarin-android-pr-pipeline-release/231/testReport/Xamarin.Android.Bcl_Tests/xunit/Possible_Crash___Release/
Sometimes an on-device test crashes, but the `adb logcat` output is
*not* included into the NUnit error report that `<RenameTestCases/>`
generates.  This is annoying, as it requires that we download the
`xa-test-results*.zip` file to obtain the actual `adb logcat` output,
which is time-consuming and not entirely obvious.
Additionally, I don't understand *why* the `adb logcat` output isn't
being included; the test execution log states:
Task "RunInstrumentationTests"
...
Task Parameter:NUnit2TestResultsFile=…/xamarin-android/tests/../bin/TestRelease/TestResult-Xamarin.Android.Bcl_Tests.xunit.xml
...
Executing: …
=> [tests] Rework logcat-*.txt handling

build-tools/scripts/Ndk.targets
Upstream [changes][0]:
* [Issue 912][1]: Prevent the CMake toolchain file from clobbering a user
specified `CMAKE_FIND_ROOT_PATH`.
* [Issue 920][2]: Fix clang wrapper scripts on Windows.
[0]: https://github.com/android-ndk/ndk/wiki/Changelog-r19#r19c
[1]: https://github.com/android-ndk/ndk/issues/912
[2]: https://github.com/android-ndk/ndk/issues/920
=> Bump NDK to r19c

Documentation/workflow/HowToAddNewApiLevel.md, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
Fixes #2433
We should be using the latest versions of the android tooling
if possible. If we can we should try to match the major version
with the max API level we support. In this case we are on Android
P, API Level 28. So we should be using the 28.x.x versions of
the tooling.
Since not all of the tools have a 28.x.x version, in those cases
we should just use the very latest.
=> [Xamarin.Android.Build.Tools] Bump android Tools versions.

src/monodroid/jni/android-system.h
Recent changes to the installer have broken the Android designer's
integration tests.
`libmonodroid.so` is failing to startup with:
[monodroid] Setting up for DSO lookup in app data directories
[monodroid] Creating public update directory: `/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo8EG0J.tmp/.__override__`
[monodroid] Trying to get property debug.mono.gc.4c07178b
[monodroid] Trying to get property from /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo8EG0J.tmp/.__override__/debug.mono.gc
[monodroid] Trying to get property debug.mono.env.4c07178b
[monodroid] Trying to get property from /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo8EG0J.tmp/.__override__/debug.mono.env
[monodroid] Using override path: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpo8EG0J.tmp/.__ov …
=> [monodroid] fix path to macOS libmonosgen-2.0.dylib

build-tools/scripts/dependencies/debian-common.sh, build-tools/scripts/dependencies/linux-prepare-Debian.sh, build-tools/scripts/dependencies/ubuntu-common.sh
We're trying to upgrade our Linux build bots to a newer version of Debian in
hopes to fix a problem with cross-building LLVM for Windows with MinGW. However,
Debian/testing (codename buster) does not install `libncurses5` by default,
instead it comes with `libncurses6` which makes the preparation phase of the
build fail.
This commit adds a check for Debian version and adjusts the package list
accordingly.
=> [Linux build] Debian/testing has libncurses6 instead of libncurses5

build-tools/installers/create-installers.targets
Our installers are currently missing `v9.0`:
$ zipinfo ~/Downloads/Xamarin.Android.Sdk-OSS-9.2.99.95_master_58137da.vsix | grep Mono.Android.dll
-rw----     0.0 fat 17827328 b- defN 19-Mar-22 15:14 $ReferenceAssemblies/Microsoft/Framework/MonoAndroid/v4.4/Mono.Android.dll
-rw----     0.0 fat 17888256 b- defN 19-Mar-22 15:15 $ReferenceAssemblies/Microsoft/Framework/MonoAndroid/v4.4.87/Mono.Android.dll
-rw----     0.0 fat 19628544 b- defN 19-Mar-22 15:15 $ReferenceAssemblies/Microsoft/Framework/MonoAndroid/v5.0/Mono.Android.dll
-rw----     0.0 fat 19720704 b- defN 19-Mar-22 15:15 $ReferenceAssemblies/Microsoft/Framework/MonoAndroid/v5.1/Mono.Android.dll
-rw----     0.0 fat 20758528 b- defN 19-Mar-22 15:15 $ReferenceAssemblies/Microsoft/Framework/MonoAndroid/v6.0/Mono.Android.dll
-rw---- …
=> [installers] use @(AndroidApiInfo) for frameworks list

src/java-runtime/java-runtime.targets, src/java-runtime/java/mono/android/MonoPackageManager.java, src/java-runtime/java/mono/android/MonoPackageManager_Resources.java
Commit xxxx added the new java_runtime.jar and
java_runtime_fastdev.jar files. The idea is the
java_runtime.jar was the release version of the
runtime. It should NOT contain files such as
mono/android/ResourcePatcher.class
mono/android/Seppuku.class
mono/android/MonkeyPatcher.class
These are for fast dev only.
However we were including these files!!
This was because of a couple of problems.
1) The `RemoveItems` property of `_RuntimeOutput` was being
treated like an ItemGroup when it is infact a property.
So we need to semi-colon seperate the items to make sure
they are ALL removed rather then it just being the last one
listed.
2) Because the `Inputs` was changed to `@(_RuntimeOutput)`
it means the target will run only ONCE. As a result both the
`release.txt` and `fastdev.txt` files …
=> [java-runtime] Remove debug files from java_runtime.jar

Documentation/guides/BuildProcess.md
Apply the link updates and formatting changes from the matching page on
docs.microsoft.com:
https://docs.microsoft.com/xamarin/android/deploy-test/building-apps/build-process
=> [docs] Sync BuildProcess from docs.microsoft.com

src/Xamarin.Android.NamingCustomAttributes/Android.App/ActivityAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Android.App/ApplicationAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Android.App/InstrumentationAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Android.App/ServiceAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Android.Content/BroadcastReceiverAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Android.Content/ContentProviderAttribute.cs
The code completion experience can be improved if the editor knew
which string properties typically come from resources so a completion
suggestion can be provided that is filtered to the type of resource
the property should be pointing to (i.e. `@(string)` vs `@(drawable)`).
Fixes https://github.com/xamarin/xamarin-android/issues/2862
=> Annotate attributes with resource category hint for the IDE

src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs, src/java-runtime/java/mono/android/MonoPackageManager_Resources.java
In commit 75023bd2 we noticed an issue the
value of `MonoPackageManager_Resouces.ApiPackageName` was
`""` even after it was replaced at built time with a new
`.class` file which contained an actual value.
The fix in that PR was to make the temp file in java-runtime
have a value of `null` rather than `""`. This made thing work
but we didn't know WHY.
After some more investigation it turns out that the value
was being inlined by the java compiler.
public static java.lang.String getApiPackageName();
descriptor: ()Ljava/lang/String;
Code:
0: ldc           #48                 // String
2: areturn
The code above is pointing to a string in the Constants table.
What we were expecting was that the statick method would be
called in the file generated by the build system. Making
the temp file have a …
=> [java-runtime] Remove final from MonoPackageManager_Resources

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsAndroidApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsMapsApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/MainActivity.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/MainPageMaps.xaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj
Context: https://github.com/xamarin/xamarin-android/issues/2836#issuecomment-476347029
We have noticed apps using Xamarin.Forms.Maps might be close to
hitting the dex limit for fields.
An example from @PureWeen:
1>  trouble writing output: Too many field references to fit in one dex file: 70468; max is 65536.
We think the way Xamarin.Android invokes `aapt` (or `aapt2`) might be
creating `R.java` files with more fields than are needed.
Step 1 is to add a test project that uses Xamarin.Forms.Maps: we did
not have one.
=> [tests] add a test using Xamarin.Forms.Maps

build-tools/scripts/dependencies/debian-common.sh, build-tools/scripts/dependencies/linux-prepare-Debian.sh, build-tools/scripts/dependencies/ubuntu-common.sh
Instead of relying on a specific soversion of libncurses, depend on its
development package which will always install the current, and expected,
version.
[Kudos to][0] @laarmen for the suggestion :)
[0]: https://github.com/laarmen
=> [build] Use `libncurses-dev` on Debian + friends

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
Context: http://build.devdiv.io/2527883
Our integration build for the Xamarin designer has caught a bug in the
following situation:
* macOS-only (Windows is OK)
* `$(AndroidUseAapt2)` is `False`
* Using `Xamarin.Android.Support.CustomTabs` version 23.x
I was able to reproduce the problem by changing the
`BuildTest.ResourceExtraction` test.
The error message is:
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1765,2):
error APT0000: resource directory '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ADT-0/RT-MyDriving-1/MyDriving.Android/obj/Debug/resourcecache/3288F845948C6081AB114E82B328E204/res' does not exist
The reason this fails is that this particular library does not have a
`res` directory:
$ ls -l …
=> [Xamarin.Android.Build.Tasks] fix for <Aapt/>

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Compile.cs
Context: https://github.com/xamarin/xamarin-android/pull/2881
Context: http://build.devdiv.io/2531303
I have noticed a random failure in our MSBuild tests such as:
E:\A\_work\1214\s\bin\Release\lib\xamarin.android\xbuild\Xamarin\Android\Xamarin.Android.Aapt2.targets(84,3): One or more errors occurred.
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait()
at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
at …
=> [Xamarin.Android.Build.Tasks] lock needed in <Aapt2Compile/>

src/mono-runtimes/mono-runtimes.targets
Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/406/
Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/407/
Commit 333b98b3 inadvertently broke all subsequent commits:
xamarin-android/tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.targets(15,5):
error MSB3030: Could not copy the file "../../../bin/Release/bcl-tests/es-ES/monodroid_corlib_test.resources.dll" because it was not found.
Note, however, that commit 333b98b3 *itself* [built][0].
What went wrong is that the `_InstallRuntimes` target within
`src/mono-runtimes/mono-runtimes.targets` wouldn't consistently copy
the unit test satellite assemblies from the mono archive into the
build tree, nor -- more importantly! -- include the satellite …
=> [create-bundle] Include satellite assemblies

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
Currently all of our unit tests assume that we
are testing against an x86 device. This commit
adds code to get the abi of the attached device
to that it is available for the unit tests.
Currently there are no tests in this repo which
will use this. However we do have a plan to move
all our tests here and there are a few fastdev
tests which weill make use of this.
=> [Xamarin.Android.Build.Tests] Add code to get the device abi

build-tools/installers/create-installers.targets
Commit f80a641c broke the installers, as it added a dependency on
`Xamarin.Build.AsyncTask.dll` to `Xamarin.Android.Build.Tasks.dll`,
but forgot to install `Xamarin.Build.AsyncTask.dll` to the installer.
The result is that the installation is unusable:
error MSB4062: The "Xamarin.Android.Tasks.ResolveSdks" task could not be loaded from the assembly …/Xamarin/Android/Xamarin.Android.Build.Tasks.dll. Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
error MSB4062: Could not load file or assembly 'Xamarin.Build.AsyncTask, Version=0.3.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Add `Xamarin.Build.AsyncTask.dll` to the installation.
=> [installer] Install `Xamarin.Build.AsyncTask.dll`

build-tools/scripts/RunTests.targets
The
https://github.com/xamarin/xamarin-android/commit/e22345162a25a7aa9d1ca35c590253d5462e9660
made the AOT tests conditional. Unfortunately it contained a typo in
the path, which prevented the AOT runs, because the condition was
always resolved as False.
=> [tests] Fix a typo which supressed the AOT test runs

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RenameTestCases.cs, build-tools/scripts/TestApks.targets
After adding more logging in
https://github.com/xamarin/xamarin-android/commit/a6eb47aea, it turned
out that the path to the logcat file is wrong. Note the directory of
the logcat in the following log message:
Could not find file `/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-release/xamarin-android/build-tools/scripts/../../bin/TestRelease-Profiled-Aot/logcat-Release-Profiled-Aot-Mono.Android_Tests.txt`.  Will not be including `adb logcat` output.
The `bin/TestRelease-Profiled-Aot/` part should be `bin/TestRelease/`
instead.
This patch changes it so, that we pass `Configuration` and
`TestsFlavor` separately to the task and the logcat path should now be
correct.
=> [tests] Add TestsFlavor parameter to RenameTestCases task

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.OSS.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/CopyResourceTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
We want to move all of our unit tests into one place.
This means that tests now need to know if they are
running against a Open Source build or a Commercial
build.
We detect that by looking for the
`Xamarin.Android.Common.Debugging.targets` in the
Android MSBuild directory.
We also change over the TestCaseSource in the
`BuildTest.OSS.cs` to be methods rather than
properties. This is so we can (in the future)
dynamically update the items to test both the
Open Source and Commercial build behavour.
There are differences between the two builds
(like fastdev) so the test cases are not always
the same.
We also updated ALL the `TestCaseSource` attributes
to name use of `nameof` rather than strings.
=> [Xamarin.Android.Build.Tests] Add framework for Commercial Builds

src/monodroid/jni/monodroid-glue.cc
Also fix the other profilers extension setting, where we were 1
character short when parameters were specified.
=> [monodroid] Use aotprofile extension for default AOT profile

src/Xamarin.Android.Build.Tasks/Tasks/DetermineJavaLibrariesToCompile.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/Files.cs
We have found an issue with our fastdev support when
it comes across a `.jar` file which does NOT contain
any `.class` files.
As part of our fastdev system we convert all the
`.jar` files we need to `.dex` files so they
can be fast deployed.
If we come across a `.jar` file which does not
contain any `.class` files `dx` exists with the
following error
no classes!
This causes the build to fail. So what we need to do
is check that a `.jar` has `.class` files in it.
This commit also reworks some code to not use Linq
in favour of a standard foreach loop.
=> [Xamarin.Android.Build.Tasks] Check a jar has .class files in it.

Documentation/guides/messages/xa0000.md, src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Compile.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs, src/Xamarin.Android.Build.Tasks/Tasks/CalculateLayoutCodeBehind.cs, src/Xamarin.Android.Build.Tasks/Tasks/Crunch.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateLayoutBindings.cs, src/Xamarin.Android.Build.Tasks/Utilities/AsyncTaskExtensions.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Unhandled exceptions from a `Parallel.ForEach` log an exception in
MSBuild such as:
E:\A\_work\1214\s\bin\Release\lib\xamarin.android\xbuild\Xamarin\Android\Xamarin.Android.Aapt2.targets(84,3): One or more errors occurred.
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait()
at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] array, ParallelOptions parallelOptions, …
=> [Xamarin.Android.Build.Tasks] helpers for AsyncTask + TPL

src/mono-runtimes/mono-runtimes.projitems
Mono Android build still creates a standalone NDK toolchain as part of its
provisioning step and places it in `~/android-toolchain/toolchains` and its
subdirectories. Xamarin.Android then uses this location to find the `strip`
utility which we call after the build is done. However, when Mono archives are
used and the Mono build does *not* take place, the standalone toolchain is never
created (as Xamarin.Android itself doesn't use it) and thus we fail to find the
required `strip` binaries and the build fails
This commit fixes the problem by always using strip from the prebuilt toolchains
as shipped with the NDK.
=> Use correct `strip` path when building with mono archives

Makefile, NuGet.config, build-tools/scripts/PrepareWindows.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
Context: https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior
Context: http://build.devdiv.io/2500191
Context: https://github.com/xamarin/xamarin-android/pull/2859#issuecomment-476691256
We are randomly getting failures during Windows builds such as:
NuGet.targets(114,5): Unable to load the service index for source https://someurl.visualstudio.com/_packaging/Dev/nuget/v3/index.json.
Response status code does not indicate success: 401 (Unauthorized).
It appears that some of our build machines on Azure DevOps have a
global (or user-level) `NuGet.Config` file that points to a NuGet feed
we don't have access to.
The way we can workaround this, is to provide our own `NuGet.config`
file that *only* uses the official nuget.org feed.
* We can put a top-level …
=> [build] use a repository-wide NuGet.config

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs
Context: http://build.devdiv.io/2547670
Context: https://github.com/xamarin/xamarin-android/pull/2911#issuecomment-478739173
We have been occasionally hitting this on CI:
Xamarin.Android.Aapt2.targets(146,3): Value cannot be null.
Parameter name: path
at System.IO.File.Delete(String path)
at Xamarin.Android.Tasks.Aapt2Link.DoExecute()
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.Execute() [E:\A\_work\1214\s\bin\TestRelease\temp\CompileBeforeUpgradingNuGet\UnnamedProject.csproj]
What I think is happening:
* We call `tempFiles.Add()` during a `Parallel.ForEach`. Bad...
* Instead of an exception happening during `Add()`, a `null` is
somehow added to the underlying array--which is corrupted.
Instead I think we should add locking around all usage of this …
=> [Xamarin.Android.Build.Tasks] random error in <Aapt2Link/>

tools/vswhere/MSBuildLocator.cs
Context: http://build.devdiv.io/2547192
Context: https://stackoverflow.com/questions/990562/win32exception-the-directory-name-is-invalid
We seem to have hit an odd failure during the MSBuild tests:
Unhandled Exception: System.ComponentModel.Win32Exception: The directory name is invalid
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at Xamarin.Android.Tools.VSWhere.MSBuildLocator.Exec(String fileName, String args) in E:\A\_work\1404\s\tools\vswhere\MSBuildLocator.cs:line 55
at Xamarin.Android.Tools.VSWhere.MSBuildLocator.QueryLatest() in E:\A\_work\1404\s\tools\vswhere\MSBuildLocator.cs:line 28
at Xamarin.Android.Build.XABuildPaths..ctor() in …
=> [vswhere] set WorkingDirectory

Documentation/guides/MSBuildBestPractices.md
I wanted to document how to use `RegisterTaskObject`, since it has
been quite helpful for us to improve incremental build performance.
I also recently figured out the undocumented `%MSBUILDNOINPROCNODE%`,
which I thought would be helpful for my future self to refer back to.
=> [docs] MSBuild best-practices for in-memory caching

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
When adb fails it is difficult to understand thats going on especially from IDE where an user usually observes only error messages, something like: 
```
MyAndroidProject
...\Xamarin\Android\Xamarin.Android.Common.targets(3281,3): error MSB3073: 
The command ""C:\Program Files (x86)\Android\android-sdk\platform-tools\\adb" -s emulator-5554 install -r "bin\Debug\com.companyname.MyAndroidProject-Signed.apk"" exited with code 1.
```
It is better to have an error message like
```
MyAndroidProject
...\Xamarin\Android\Xamarin.Android.Common.targets(3285,9): error : 
The command ""C:\Program Files (x86)\Android\android-sdk\platform-tools\\adb" -s emulator-5554 install -r "bin\Debug\com.companyname.MyAndroidProject-Signed.apk"" exitied with code 1: 
adb: failed to install …
```
=> Deploy target

build-tools/scripts/RunTests.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/MakeBundleNativeCodeExternalTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/packages.config, tests/CodeBehind/UnitTests/CodeBehindUnitTests.csproj, tests/CodeBehind/UnitTests/packages.config, tests/CodeBehind/UnitTests/run.sh, tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/BuildTests.cs, tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/Xamarin.Android.MakeBundle-UnitTests.csproj, tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/packages.config, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/BuildTests.cs, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/EmbeddedDSO-UnitTests.csproj, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/packages.config, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/run.sh
A couple of things needed to change during this upgrade. 
The code `Properties` Dictionary is now readonly in `3.11.0` so the following code no longer works.
```
TestContext.CurrentContext.Test.Properties ["Output"]
```
So we have to remove it in favour of maintaining a local dictionary of test directories which we can use the clean up once a test passes.
=> [Tests] Upgrade all the tests to the latest stable NUnit.

build-tools/automation/build.linux.groovy
**Symptom**
groovy.lang.MissingPropertyException: No such property: prLabels for class: groovy.lang.Binding
**Analysis**
This issue was not discovered in Linux pipeline CI build workflows since the PR logic was not exercised in that case.  This issue has come to light with Linux PR pipeline build workflows being switched on.
**Resolution**
Define missing global prLabels variable required by the hasPrLabel utility function
**Example of affected build**
https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux-pr-pipeline/18/
=> [build, linux] Fix for Linux pipeline PR build break

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CreateAndroidEmulator.cs, build-tools/scripts/TestApks.targets
We have more and more tests running on the emulator
now. Sometimes we run out of space to run the tests.
This PR increases the disk space.
We also handle a problem with the `CreateAndroidEmulator`
error processing.  `advmanager` was returning the following
warning.
Warning: cvc-pattern-valid: Value '' is not facet-valid with respect to pattern '[a-zA-Z0-9_-]+' for type 'idType'.
org.xml.sax.SAXParseException; lineNumber: 134; columnNumber: 341; cvc-pattern-valid: Value '' is not facet-valid with respect to pattern '[a-zA-Z0-9_-]+' for type 'idType'.
at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
Only the first line was …
=> [build-tools] Increase the emulator disk space.

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks.csproj, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CreateFrameworkList.cs, src/mono-runtimes/mono-runtimes.targets
Fixes: TODO
Context: commit d4fb5e5bd6721f0fe7f1e95648342d9004474014
There was some unfortunate fallout from d4fb5e5b, in which
`FrameworkList.xml` was updated to contain `<File/>` entries for
`System.Buffers.dll` and `System.Memory.dll`: it changed the
`FrameworkList.xml` semantics from "include all the files in this
directory" to "include *only* the specified `<File/>`s."
This in turn means that when editing the Assembly References within
Visual Studio for Mac, the *only* BCL assemblies shown are for
`System.Buffers.dll` and `System.Memory.dll`!
Oops. :-(
Furthermore, there are (at present) *185* files which need to be
listed, between the "real" assemblies and the Facade assemblies.
This is *not* a list I want to manually maintain or otherwise keep up
to date.
Add a new …
=> [mono-runtimes] Fully populate RedistList\FrameworkList.xml

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks.csproj, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CreateFrameworkList.cs, src/mono-runtimes/mono-runtimes.targets
Fixes: https://developercommunity.visualstudio.com/content/problem/514955/lost-net-assemblies-after-vs-update.html
Fixes: https://github.com/mono/monodevelop/issues/5190
Context: commit d4fb5e5bd6721f0fe7f1e95648342d9004474014
There was some unfortunate fallout from d4fb5e5b, in which
`FrameworkList.xml` was updated to contain `<File/>` entries for
`System.Buffers.dll` and `System.Memory.dll`: it changed the
`FrameworkList.xml` semantics from "include all the files in this
directory" to "include *only* the specified `<File/>`s."
This in turn means that when editing the Assembly References within
Visual Studio for Mac, the *only* BCL assemblies shown are for
`System.Buffers.dll` and `System.Memory.dll`!
Oops. :-(
Furthermore, there are (at present) *185* files which need to be
listed, …
=> [mono-runtimes] Fully populate RedistList\FrameworkList.xml (#2928)

build-tools/scripts/mingw-64.cmake.in, src/monodroid/CMakeLists.txt
Context: 24934c0617683349510b1f3ca2d0c06f42e9c850
MinGW builds of shared libraries may (depending on what the source
code uses) link against `libgcc` in a few variations.  The default
work mode is to use the shared library but since it's specific to
gcc/MinGW, it will not be found on the target system and the library
will fail to load.
There are two solutions for this:
* Distribute all the referenced DLLs
* Link them in statically
This commit takes the second approach, implemented in the way that
will affect all the libraries we build for Windows.
=> [mingw] Make sure all 64-bit Windows libraries use static libgcc

src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Utilities/MetadataExtensions.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
We have a couple MSBuild targets that need to only operate on
`MonoAndroid` assemblies:
* `_BuildAdditionalResourcesCache` is the precursor to
Xamarin.Build.Download
* `_ResolveLibraryProjectImports` unzips
`__AndroidLibrariesProjects__.zip`, .jar/.aar files, etc.
Both of these targets all looking at *all* assemblies, so we could
make a new item group `@(_MonoAndroidReferencePath)` and use this
instead. This would both allow the tasks inside these targets to
operate on less assemblies. It would also allow them to skip for
changes in NetStandard projects.
I added a new `<FilterAssemblies/>` MSBuild task to filter based on
the presence of this attribute in an assembly:
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute ("MonoAndroid,Version=v8.1")]
MSBuild/Roslyn populate this …
=> [Xamarin.Android.Build.Tasks] filter @(ReferencePath) for MonoAndroid assemblies

src/Xamarin.Android.Build.Tasks/Tasks/GetImportedLibraries.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
I noticed a target running on an incremental build with only a XAML
code change:
116 ms  _BuildLibraryImportsCache                  1 calls
This was using VS 2019 GA, just a blank Xamarin.Forms app.
Reviewing `<GetImportedLibraries/>` it had some general perf
improvements that could be done:
* It called `Directory.EnumerateFiles` three times...
* It used a bunch of LINQ where a `foreach` would do.
Additionally, I saw some improvements I could do at the MSBuild target
level:
<Target Name="_BuildLibraryImportsCache"
Inputs="$(MSBuildProjectFullPath);@(_ReferencePath);@(_ReferenceDependencyPaths);$(_AndroidBuildPropertiesCache);$(_AndroidLibraryProjectImportsCache)"
Outputs="$(_AndroidLibraryImportsCache).stamp">
This target operates on the output of `_ResolveLibraryProjectImports`,
but it …
=> [Xamarin.Android.Build.Tasks] <GetImportedLibraries/> perf improvements

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Looking at the build output of a simple app:
> ls .\samples\HelloWorld\bin\Debug\*.pdb
Length Name
------ ----
1024 HelloLibrary.pdb
1304 HelloWorld.pdb
13943324 Mono.Android.pdb
153048 Mono.Security.pdb
1545052 mscorlib.pdb
106160 System.ComponentModel.Composition.pdb
393532 System.Core.pdb
43076 System.Net.Http.pdb
795468 System.pdb
325732 System.Runtime.Serialization.pdb
77008 System.ServiceModel.Internals.pdb
917588 System.Xml.pdb
There are *not* accompanying `.dll` files for many of these symbols.
Some of these symbols are also quite big!
I don't think we need to be copying these files to `$(OutputPath)` at
all; it doesn't make sense if their accompanying assembly isn't there!
If we remove the `<CopyIfChanged/>` calls in our targets, MSBuild will
handle copying the appropriate symbol …
=> [Xamarin.Android.Build.Tasks] don't copy pdb/mdb to $(OutputPath)

tests/Runtime-AppBundle/Mono.Android-TestsAppBundle.targets, tests/Runtime-MultiDex/Mono.Android-TestsMultiDex.targets
Context: https://jenkins.mono-project.com/job/xamarin-android-pr-pipeline-release/505/
If `Mono.Android-Tests.csproj` fails to build, you get further errors down the line, such as:
BuildNativeLibs:
"/Users/builder/android-toolchain/ndk/ndk-build"
/Users/builder/android-toolchain/ndk/build/core/build-local.mk:151: *** Android NDK: Aborting    .  Stop.
Android NDK: Could not find application project directory !
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
make[1]: Entering directory `/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-release/xamarin-android/tests/Runtime-MultiDex'
make[1]: Leaving directory `/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-release/xamarin-android/tests/Runtime-MultiDex' …
=> [tests] fix BuildNativeLibs for MultiDex/AppBundle tests

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/xamarin-android/commit/4f088670f2418d6291bd6d4b41fea0dd722081fb
After 4f08867 was merged, I did some testing and found two targets
running always:
* `_Sign`
* `_BuildApkEmbed`
These targets `Inputs` and/or `Outputs` were expecting APK files that
will never exist if you have `$(AndroidPackageFormat)` set to `aab`.
They would basically run every time on a build with no changes.
I adjusted the `Inputs` and `Outputs` of these targets, so they look
for different files based on `$(AndroidPackageFormat)`.
I also added a new test to verify that AAB files are signed & that
targets properly skip on a build with no changes.
=> [Xamarin.Android.Build.Tasks] _Sign target should be incremental for aab

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs
Wanted to clean up a few things here:
* `#if SEPARATE_CRUNCH` seems pretty old, and not needed. I haven't
found it actually *defined* anywhere.
* Removed unused using statements
I wanted to clean this up a bit, the diff will be smaller if I move
this task to use System.Reflection.Metadata in place of Mono.Cecil in
the future.
=> [Xamarin.Android.Build.Tasks] <ResolveLibraryProjectImports/> unused code

build-tools/cmake/xa_macros.cmake
For some reason the Windows cross-build on macOS using MinGW leaves behind a lot
of temporary LTO (Link-Time Optimization) files, the result of passing the
`-flto` flag to the compilers. The temporary files (`*.ltrans*`), around 280 of
them, are then included in our vsix packages, increasing their size while being
completely useless for the end user.
This commit fixes the issue by turning off LTO for MinGW targets. The
optimization is not really useful there and such fix is faster than tracking why
MinGW on macOS (installed from Homebrew) is behaving the way it is.
=> [build] Make MinGW build on mac generate less noise

src/Mono.Android/Test/System.Net/SslTest.cs, src/Mono.Android/Test/Xamarin.Android.Net/AndroidClientHandlerTests.cs
Context: 608d950a703ddb527258565c2a0705aa37f71789
Context: 34dfc6d71d590183f0077b69bbd61964f8879b97
SslTests notoriously fail for reasons not related to the subject of the test,
thus creating false negatives when our bots flag the related builds/PRs as red
while the failure can/should be ignored.
Wrap the tests in code which ignores the most common failures we can safely
ignore.
=> [tests] More network resilience for tests

Documentation/guides/BuildProcess.md, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
MSBuild naming convention is for item groups to be *singular*, not
plural, names.  For example, `@(Compile)`, `@(Reference)`, etc.
Rename `@(AndroidAotProfiles)` to `@(AndroidAotProfile)` to be
consistent with this convention.
=> [Xamarin.Android.Build.Tasks] De-pluralize @(AndroidAotProfile)

src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/FilterAssembliesTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://www.nuget.org/packages/Refractored.Controls.CircleImageView/
Context: https://github.com/Azure-Samples/MyDriving
Context: https://github.com/xamarin/xamarin-android/pull/2934
The MyDriving sample app currently fails to build on master with:
Resources/layout/fragment_profile.axml(2): error APT0000: attribute civ_border_width (aka com.microsoft.mydriving:civ_border_width) not found.
The failure happens with both `aapt` and `aapt2`.
This layout is using a custom view such as:
<?xml version="1.0" encoding="utf-8"?>
<ScrollView
xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:local="http://schemas.android.com/apk/res-auto">
...
<refractored.controls.CircleImageView local:civ_border_width="0dp" />
...
</ScrollView>
This comes from the …
=> [Xamarin.Android.Build.Tasks] <FilterAssemblies/> support missing TFI

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs
If you have `$(AndroidUseAapt2)` set to `True` (which is also the
default on master), the `<ResolveAndroidTooling/>` tooling task seems
to take longer:
aapt2:
83 ms  ResolveAndroidTooling                      2 calls
aapt:
4 ms  ResolveAndroidTooling                      2 calls
I figured out this was due to how we shell out to `aapt2 version` to
check the version of `aapt2`.
We should use `RegisterTaskObject` and cache the result of this call!
* I used a key that contains the path to `aapt2`, so if someone changes the
`aapt2` used, it should call `aapt2 version` again.
* I don't think we actually need to invalidate the cached value on
anything else because we are shipping `aapt2` now.
But what if there is a Xamarin.Android update?
If you install a new VSIX, VS on Windows makes you …
=> [Xamarin.Android.Build.Tasks] cache aapt2 version in AppDomain

Configuration.props
Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/451/testReport/junit/Mono/Android_TestsMultiDex/Possible_Crash___Release/
Context: https://developer.android.com/studio/releases/platform-tools
We have been seeing `adb` crash during our APK tests:
Task "RunInstrumentationTests" (TaskId:274)
...
Executing: /Users/builder/android-toolchain/sdk/platform-tools/adb -s emulator-5570  logcat -v threadtime -d (TaskId:274)
appending stdout to file: /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/build-tools/scripts/../../bin/TestRelease/logcat-Release-Bundle-Mono.Android_TestsMultiDex.txt (TaskId:274)
/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/build-tools/scripts/TestApks.targets(226,5): warning : * daemon not running; …
=> [android-toolchain] update to 28.0.2 platform-tools

Configuration.props, build-tools/api-xml-adjuster/api-xml-adjuster.targets, build-tools/scripts/RunTests.targets, src/Mono.Android/Mono.Android.targets
Currently we don't do that which causes the local/host stack traces not to have
source location information. Pass `--debug` to mono via `$(ManagedRuntime)`
which is used whenever we need to launch a managed program.
=> Pass `--debug` to Mono when running tests etc

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Commit 121b81aa added the new `runtime_java.jar`.
What it did not take into account was what happens
when a user upgrades but does not do a clean build.
What happens is we have old redundant files left
in the `$(IntermediateOutputPath)android\src` and
`$(IntermediateOutputPath)android\bin\classes`.
This then causes errors such as
error: duplicate class: mono.MonoPackageManager_Resources
when compiling the java code.
So what we need to do is clean up after ourselves. We do
this by checking to see if the following file exists
$(MonoAndroidIntermediate)android\src\mono\app\ApplicationRegistration.java
If that file is there, then we need to clean up all the
other known files. We can not do a clean all the time since
we still generate `MonoPackageManager_Resources`. The
contents have changed …
=> [Xamarin.Android.Build.Tasks] Clean up redundant files.

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetStandard.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetXamarinProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/SolutionBuilder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
I went through the `_GenerateJavaStubs` MSBuild target and the
`<GenerateJavaStubs/>` MSBuild task. There was an "easy" win to
improve incremental build performance. I also made a few other general
improvements to `<GenerateJavaStubs/>`.
`_GenerateJavaStubs` has `Inputs` of:
Inputs="$(MSBuildAllProjects);@(_ResolvedAssemblies);$(_AndroidManifestAbs);$(_AndroidBuildPropertiesCache);@(_AndroidResourceDest)"
Lets say a NetStandard assembly changes, such as a XAML change in a
Xamarin.Forms app. In this case `_GenerateJavaStubs` does not actually
need to run again.
We can use `@(_ResolvedUserMonoAndroidAssemblies)` as an input instead
of `@(_ResolvedAssemblies)`.
This is the biggest win--to skip this target completely.
`ManifestDocument` had the concept of a "whitelist" assembly, which …
=> [Xamarin.Android.Build.Tasks] <GenerateJavaStubs/> improvements

tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.targets
so that their references can be resolved
Otherwise, any referenced assemblies that are only used by the xunit testsuites
will not be included in the APK.
---
I'm not sure if this is the best way - with this the XUnit test assemblies all end up inside the APK in the `assemblies/` folder (the same way that all the NUnit test assemblies already do) - which means they're duplicated in the `Xamarin.Android.BCL_Test.apk` - they're included once more in the `bcl-tests.zip` that's embedded as a resource in the `assemblies/Xamarin.Android.Bcl_Tests.dll` inside the APK.
But I've been told that that's a know issue that will be dealt with separately.
=> [mono-2019-02][Xamarin.Android.BCL_Tests] Copy xunit tests to IntermediateOutputPath

src/Xamarin.Android.Build.Tasks/Resources/MonoRuntimeProvider.Shared.20.java, src/Xamarin.Android.Build.Tasks/Resources/MonoRuntimeProvider.Shared.java
Context: https://github.com/xamarin/xamarin-android/commit/4f088670f2418d6291bd6d4b41fea0dd722081fb
Since 4f08867, I noticed a problem with apps crashing on startup with
Fast Deployment:
monodroid: Creating public update directory: `/data/user/0/com.xamarin.android.helloworld/files/.__override__`
monodroid: Using override path: /data/user/0/com.xamarin.android.helloworld/files/.__override__
monodroid: Using override path: /storage/emulated/0/Android/data/com.xamarin.android.helloworld/files/.__override__
monodroid: Using runtime path: /data/app/com.xamarin.android.helloworld-qnOclHxAJS4ueK0I4iLQCQ==/lib/x86
monodroid: checking directory: `/data/user/0/com.xamarin.android.helloworld/files/.__override__/lib`
monodroid: directory does not exist: …
=> [Xamarin.Android.Build.Tasks] fix for shared runtime

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/BundleToolTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/2969
If you tried to use our new Android App Bundle feature with an app
using Google Play Services, you would get an error such as:
[BT Module files can be only in pre-defined directories, but found 'protobuf.meta'.
Looking at `obj\Release\android\bin\base.zip`, it indeed had a file
named `protobuf.meta` in the root of the zip file.
In 4f08867, I missed a case where `<BuildApk/>` puts arbitrary files
from `.jar` files into `.apk` or `.aab` archives. For this to work
with app bundles, files like this need to go into a `/root/`
directory. I have a `RootPath` property to handle this, which I forgot
to use in this case.
I updated `BundleToolTests` so that we use a
`XamarinFormsMapsApplicationProject` that contains Google Play
Services. …
=> [Xamarin.Android.Build.Tasks] fix arbitrary files in App Bundles

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs
Context: http://build.devdiv.io/2593085
Context: https://github.com/xamarin/xamarin-android/commit/c9c1f8ad1922fc7aad517689f5dff3d1214a0ea5
The Android designer's integration tests found another problem:
Xamarin.Android.Common.targets(1326,2): warning MSB4018: The "GenerateResourceDesigner" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\myuser\AppData\Local\Xamarin\Xamarin.Android.Support.CustomTabs\23.1.1.0\embedded\res'.
at System.IO.FileSystemEnumerableIterator`1.CommonInit()
at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean …
=> [Xamarin.Android.Build.Tasks] fix for ManagedResourceParser

build-tools/scripts/RunTests.targets, tests/RunApkTests.targets
We currently invoke `RunApkTests` 3 times with
different parameters. As a result that also
runs the `NUnitDeviceTests` 3 times!!
This commit reworks the RunTest.targets and
the RunApkTests.targets so they only run
once.
=> [tests] Dont run the NunitDeviceTests all the time.

tests/RunApkTests.targets
Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/470/testReport/
A "funny" thing happened with the Jenkins build for commit decfbccf:
~all of the on-device `.apk` tests failed, which is *not* something
which happened for PR #2718, e.g. the [last PR build][0] only had a
failure in `CheckTimeZoneInfoIsCorrect("Pacific/Pitcairn")`, because
the emulator exited (crashed?), which we deemed as unrelated.
146,363 tests ran in that PR build.
Compare to the master build, which had 3,884 tests (!).
Thus, a question: *what happened*?!
Some further investigation showed that things were even *more*
confusing: the `msbuild-20190417T122656-Target-RunApkTests.binlog`
file showed that the test results were successfully grabbed!
Task "RunInstrumentationTests"
...
Executing: …
=> [tests] Don't rename test cases from RunNUnitDeviceTests

src/mono-runtimes/mono-runtimes.targets
We had a weird bunch of test failures on one
of the PR's which bump mono. Many of the
MSBuild tests were failing becuase targets
were running when they shouldn't. Looking
at the logs we saw
Input file "/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-release/xamarin-android/bin/Release/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v1.0/Facades/Microsoft.Win32.Primitives.dll" is newer than output file "obj/Debug/UnnamedProject.dll".
When ment the `Microsoft.Win32.Primitives.dll` assembly
somehow was `newer` than a file we just build...
Further investigation into the mono bundle resulted in
unzip -l android-release-Darwin-cf880be66a2d1cc8ca34e345114a7f420b7b86ea.zip | grep Microsoft.Win32
4608  04-17-2019 08:54   android-bcl/monodroid/Facades/Microsoft.Win32.Primitives.dll …
=> [mono-runtimes] Fix the timestamps on the mono bundle.

Configuration.props
This version supports running in headless mode which may be useful for our CI
servers when running unit tests.
=> Update emulator to version 28.0.25

build-tools/automation/build.groovy, tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs
There is a direct call to `<CompileToDalvik/>` when using
`AndroidFastDeploymentType` = `Assemblies:Dexes`.
We need to add a few tests here to verify that this code path still
works when using `$(AndroidDexTool)` = `d8`.
I also did some minor cleanup in these tests, such as:
* Instead of checking if the `classes.dex` < 30K, I actually checked
for a class that should be missing and one that should exist.
* Use the `TestName` property.
* Use of `CreateApkBuilder (..., false, false)` can just omit the two
`false, false` parameters, as that is the default now.
The actual changes for d8 + enhanced fastdev will be in monodroid.
=> [tests] check d8 works with "Enhanced Fast Deployment"

src/Xamarin.Android.Build.Tasks/Tasks/CompileNativeAssembly.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/NativeAssemblyDataStream.cs
Any Xamarin.Android app was generating build output such as:
_CompileNativeAssemblySources:
[aarch64-linux-android-as.EXE stderr] typemap.mj.inc: Assembler messages:
[aarch64-linux-android-as.EXE stderr] typemap.mj.inc:60201: Warning: end of file not at end of a line; newline inserted
[arm-linux-androideabi-as.EXE stderr] typemap.mj.inc: Assembler messages:
[arm-linux-androideabi-as.EXE stderr] typemap.mj.inc:60201: Warning: end of file not at end of a line; newline inserted
The fix was we just needed to call `StreamWriter.WriteLine()` once at
the end of the file. I added an `NativeAssemblyDataStream.EndOfFile()`
method to call for this instead of `Flush()`.
I also updated log messages in `<CompileNativeAssembly/>` to be more
precise:
* stdout should probably use `LogDebugMessage` for …
=> [Xamarin.Android.Build.Tasks] fix warnings from <CompileNativeAssembly/>

src/Xamarin.Android.Build.Tasks/Resources/proguard_xamarin.cfg, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
I recently was doing some testing, and was using the Xamarin.Forms
Shell template from Visual Studio 2019. I also added
Xamarin.Forms.Maps and enabled multi-dex + r8.
Unfortunately, the app crashed on start with:
java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication"
Using `dexdump`, the class was indeed missing from `classes.dex`.
It feels like this should "just work"?
From some conversation on Slack, @JonDouglas tried in Android Studio;
it was adding this proguard rule automatically:
-keep class android.support.multidex.MultiDexApplication { <init>(); }
I think we can just add this rule to `proguard_xamarin.cfg` *always*
to fix this problem. I tested non-multidex apps, and no new warnings
are popping up or anything. Xamarin.Android apps with …
=> [Xamarin.Android.Build.Tasks] proguard/r8 + multidex missing rule

build-tools/scripts/dependencies/debian-common.sh, build-tools/scripts/dependencies/linux-prepare-Ubuntu.sh
Ubuntu 19 removed OpenJDK 8 and thus we can no longer depend on distro packages
to install it. OpenJDK 8 is a requirement for Android development but, alas,
there's no replacement in the Ubuntu 19 (or Debian 10+) repositories for this
version. At some point we will start provisioning our own version of OpenJDK 8
but, for now, user needs to install OpenJDK 8 on their own. A recommended
alternative is https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html
Remove dependency on openjdk-8-jdk and change `libzip4` dependency to
`libzip-dev` in order to install the latest version of libzip.
=> [build] Adjust dependencies for Ubuntu 19

build-tools/scripts/RunTests.targets
So that it is rebuilt, before running it, with AOT enabled. That
explains the unexpected test times measurements, where there wasn't
much difference between AOT and non-AOT measurements.
Example unexpected measurements (the lines are split for better
readability):
last-Release,JNI.init-Release,init-Release,OnCreateBegin-Release,OnCreateEnd-Release,OnStartBegin-Release,OnStartEnd-Release,OnResumeBegin-Release,OnResumeEnd-Release,ActivityDisplayed-Release
last-Release-Aot,JNI.init-Release-Aot,init-Release-Aot,OnCreateBegin-Release-Aot,OnCreateEnd-Release-Aot,OnStartBegin-Release-Aot,OnStartEnd-Release-Aot,OnResumeBegin-Release-Aot,OnResumeEnd-Release-Aot,ActivityDisplayed-Release-Aot
last-Release-Profiled-Aot,JNI.init-Release-Profiled-Aot,init-Release-Profiled-Aot,OnCreateBegin-Release-Profi …
=> [tests] Add XF test to _ApkTestProjectAot

build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Forgot to list the `startup-xf.aotprofile` file in few places to make
it part of the installation
=> [Xamarin.Android.Build.Tasks] Fix startup-xf.aotprofile installation

build-tools/scripts/RunTests.targets
When fixing the AOT measurements
(https://github.com/xamarin/xamarin-android/pull/3017), I didn't
notice we have similar issue with the Bundle flavor.
We can either not run XF in Bundle flavor or rebuild it before
run. The XF apps are very common, so I think it makes sense to keep running
the test and thus we need to add it to the `_ApkTestProjectBundle` item
group so that it is rebuild before running.
=> [tests] Add XF test to _ApkTestProjectBundle

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs
We made a change where `SignAndroidPackage` no longer
automatically calls `Build`. This was done to help
speed up the IDE and to save it having to call `Build`
all over again. There was an assumption in the `Install`
tests where we assumed `Build` was being called. As a
result a bunch of tests failed with our favourite
`LinkAssemblies` error.
error MSB4018: System.IO.FileNotFoundException: Could not load assembly 'UnnamedProject, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
So lets call `Build` before we do any of the Installation
tests.
Next up it seems that Nunit resolves all the test cases
BEFORE the `[OnTimeSetup]` runs. As a result the value
for `CommercialBuildAvailable` was always `false`.
So lets calculate that in a …
=> [MSBuildDeviceIntegration] Fix the Install/InstantRun tests.

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Utilities/XDocumentExtensions.cs
One of the hard things to do when diagnosing issues
is figuring out where a certain file came from.
Because of the path and command line limits on
Windows we have to use shortened paths by default.
So we have paths such as
obj/Debug/lp/32/res
obj/Debug/lp/42/classes.jar
obj/Debug/lp/55/assets
While this is great for path lengths, it does not
tell use which nuget or Library project those
items came from. There is a map file which does
hold the mapping information, however it is not
a straight forward process to look at that file and
then work out the path to the assembly or `.aar`.
So what this PR does is add a new piece of metadata
to each item specifying the `OriginalFile` which
the item came from. This will either be a full path
to an Assembly, for items which are extracted from
an …
=> [Xamarin.Android.Build.Tasks] Add metadata to library imports

src/Xamarin.Android.Build.Tasks/Tasks/LinkApplicationSharedLibraries.cs, src/Xamarin.Android.Build.Tasks/Tasks/NdkUtils.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
The code mistakenly used the `ld` linker from Android NDK while it should have
used one from the Android *SDK*'s build-tools.
=> Don't use NDK linker to link libxamarin-app.so

src/mono-runtimes/mono-runtimes.targets
Context: http://build.devdiv.io/2621129
We have been seeing failures like this on Windows:
src\mono-runtimes\mono-runtimes.targets(323,5): Error MSB4018: The "SystemUnzip" task failed unexpectedly.
System.AggregateException: One or more errors occurred. --->
System.IO.FileNotFoundException: Could not find file 'C:\Users\dlab14\android-archives\android-release-Windows-e66c76674243826a8d127f0261f0fb64f8d59757.zip'.
Which is odd, because we should not be downloading the mono archive on
Windows at all. When a bundle produced by xamarin-android builds
exists, this step should be skipped.
The culprit was:
Building target "_BuildUnlessCached" completely.
Output file "C:\src\xamarin-android\bin\Debug\lib\xamarin.android\\..\..\bcl-tests\BinarySerializationOverVersionsTest.pdb" does not exist. …
=> [mono-runtimes] missing pdbs for bcl-tests

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tasks/ConvertResourcesCases.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateManagedAidlProxies.cs, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Tasks/GetAdditionalResourcesFromAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.SkipCases.projitems
Context #2895 
As part of the AndroidX migration system we need to
be able to skip over the older support library
assemblies for certain build steps.
The following metadata is supported on the `ReferencePath`
and `ReferenceDependencyPaths` ItemGroups.
AndroidSkipAddToPackage
AndroidSkipResourceProcessing
AndroidSkipJavaStubGeneration
AndroidSkipResourceExtraction
`AndroidSkipResourceProcessing` is the renamed
`SkipAndroidResourceProcessing` metadata item.
This is used to skip case conversion on those
resources.
`AndroidSkipResourceExtraction` will stop the
resources in that library being extracted into
the `IntermediateOutputPath`.
`AndroidSkipJavaStubGeneration` when `true` this
item will stop java code being generated for the
library in quetion.
`AndroidSkipAddToPackage` is used by …
=> [Xamarin.Android.Build.Tasks] Support Filtering Assemblies

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/BundleToolTests.cs
If run against an x86 emulator, these tests were failing with:
[BT : 0.8.0] error : The app doesn't support ABI architectures of the device. Device ABIs: [x86], app ABIs: [armeabi-v7a, arm64-v8a].
I missed this originally, because I was using a device.
In `Release` mode, we don't get x86 by default, so I added:
var abis = new string [] { "armeabi-v7a", "arm64-v8a", "x86" };
project.SetProperty (KnownProperties.AndroidSupportedAbis, string.Join (";", abis));
Most of our MSBuild tests that deploy are doing this. I also added to
our list of assertions to check for x86 so files.
Another problem I found was that this directory was not getting
deleted after successful test runs:
bin\TestDebug\temp\BundleToolTests
I changed the behavior of this test to default to using
`cleanupOnDispose: true`, …
=> [tests] fixes for App Bundle tests

src/mono-runtimes/mono-runtimes.targets
After 89be639 was merged, I was still hitting the original problem of
not being able to build on Windows. This time a different file was the
cuplrit:
Building target "_BuildUnlessCached" completely.
Output file "C:\src\xamarin-android\bin\Debug\lib\xamarin.android\\..\..\bcl-tests\System.Reflection.TestModule.pdb" does not exist.
This file did not exist in Xamarin.Android's bundle or the mono
archive, so we need to exclude it from `Outputs` of
`_BuildUnlessCached`.
To fix this, I added the file to `@(_BclExcludeDebugSymbols)` and
reworked line 77 to use this item group.
I then used a "weird trick" to hardcode the latest `(_VersionHash)`,
so the Xamarin.Android bundle wasn't invalidated for me locally:
diff --git a/build-tools/create-bundle/bundle-path.targets …
=> [mono-runtimes] exclude a missing pdb file

src/monodroid/config.xml
One of the designer unit tests is failing on Mac with:
[2019-04-25 21:52:55.8] INFO: : Unhandled Exception:
[2019-04-25 21:52:55.8] INFO: : System.TypeInitializationException: The type initializer for 'System.Console' threw an exception. ---> System.DllNotFoundException: libmono-native.so
[2019-04-25 21:52:55.8] INFO: :   at (wrapper managed-to-native) Interop+Sys.Stat(byte&,Interop/Sys/FileStatus&)
[2019-04-25 21:52:55.8] INFO: :   at Interop+Sys.Stat (System.ReadOnlySpan`1[T] path, Interop+Sys+FileStatus& output) [0x00028] in <ca2a591e441f458bb6bef167b4521022>:0
[2019-04-25 21:52:55.8] INFO: :   at System.IO.FileSystem.FileExists (System.ReadOnlySpan`1[T] fullPath, System.Int32 fileType, Interop+ErrorInfo& errorInfo) [0x00007] in <ca2a591e441f458bb6bef167b4521022>:0
[2019-04-25 …
=> [monodroid] Change the libmono-native dllmap target on osx

Makefile
Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/491
Context: https://github.com/xamarin/xamarin-android/pull/3032#issuecomment-487174225
A "funny" thing has happened with the mono/2019-02 bump: it has
apparently [broken API compatibility][0], which was not detected or
reported in the last [mono/2019-02 PR build][1].
What went wrong is that the `make run-all-tests` step was failing,
reporting an error, but because of how `make run-all-tests` was
structured, when the `RunAllTests` MSBuild target failed,
*no further tests were run*.
Further tests such as the API compatibility tests!
Fix the `make run-all-tests` target so that even if the `RunAllTests`
MSBuild target fails, we *continue executing tests* so that the
`make run-api-compatibility-tests` target …
=> [tests] Consistently run `run-api-compatibility-tests`

tools/xabuild/XABuildPaths.cs
Newer MSBuild versions are moving to use the `Current` directory instaed of a
versioned one (e.g. `14.0`, `15.0`) to keep its binaries, targets etc. Without
pointing to that directory in a symlink from
`bin/$(Configuration)/lib/xamarin.android/xbuild` the build will fail on Unix
with an error similar to:
bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Aapt2.targets(31,3): error MSB3191: Unable to create directory "/Debug/". Access to the path '/Debug/' is denied.
Adjust XABuildPaths.cs to first look for the `Current` directory and only then
for the old `15.0` one.
=> [build] Create symlink to MSBuild's `Current` "version" directory

Documentation/guides/messages/xa0115.md
Of course, it took until after <https://github.com/xamarin/xamarin-android/pull/2967> was merged for me to be able to see that I had left a typo in the page.
=> [docs] Correct a typo in XA0115 documentation page

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Utilities/MetadataResolver.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3045
In VS 2019 16.1 Preview, a project using `Microsoft.Extensions.Http`
fails to build with:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2146,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'System.Runtime.dll'
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference)
at …
=> [Xamarin.Android.Build.Tasks] <ResolveAssemblies/> and ref assemblies

tests/RunApkTests.targets
When running `RunNUnitDeviceTests` manually you get
and error such as
error MSB4036: The "SetEnvironmentVariable" task was not found.
This is because we are missing the `UsingTask` to bring
in this custom task. This is an issue only when running
`RunNUnitDeviceTests` manually. It does not happen when
running as part of `make run-apk-tests`.
=> [tests] Fix Build error when running 'RunNUnitDeviceTests'

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileExpected.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs, src/Xamarin.Android.Build.Tasks/Utilities/ResourceIdentifier.cs, src/Xamarin.Android.Build.Tasks/Utilities/ResourceParser.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Fixes #3007
Xamarin.Forms introduced some new `android:id` values in the
`Xamarin.Forms.Platform.Android` assembly [1]. These include
a period `.` in the identifier, such as
android:id="@+id/bottomtab.tabbar"
android:id="@+id/toolbar.one"
When processing these with `aapt` or `aapt2` these identifiers
are "fixed up" to be valid java identifiers. The same is
NOT true for the `ManagedResourceParser`. As a result
the very first design time build will fail with the following
error.
obj\Debug\81\designtime\Resource.designer.cs(5048,21,5048,30): error CS0145: A const field requires a value to be provided
obj\Debug\81\designtime\Resource.designer.cs(5048,30,5048,31): error CS1003: Syntax error, ','
obj\Debug\81\designtime\Resource.designer.cs(5048,31,5048,38): error CS1002: ; expected
This is …
=> [Xamarin.Android.Build.Tasks] Invalid Resources generated for DesignTime

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RenameTestCases.cs, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunInstrumentationTests.cs
adb sometimes crashes during test instrumentation. When it happens,
one needs to download the binlogs to confirm it.
With this change is should be reported in the test results and also
mentioned in the log.
The adb crash in binlogs looks like:
Executing: /Users/builder/android-toolchain/sdk/platform-tools/adb -s emulator-5570  shell am instrument  -e "loglevel Verbose" -w "Mono.Android_TestsMultiDex/xamarin.android.runtimetests.TestInstrumentation" (TaskId:274)
Executing: /Users/builder/android-toolchain/sdk/platform-tools/adb -s emulator-5570  logcat -v threadtime -d (TaskId:274)
appending stdout to file: /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/build-tools/scripts/../../bin/TestRelease/logcat-Release-Bundle-Mono.Android_TestsMultiDex.txt (TaskId:274) …
=> [tests] Detect adb crash during instrumentation

Makefile, build-tools/scripts/RunTests.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/RunApkTests.targets
We want to run 2 apk tests, locale and XF, non-parallel. So that the
performance measurements for these tests make more sense and are
comparable between test flavors and also between builds.
The splitting is implemented by introducing new
`RunPerformanceApkTests` target and pre-filtering `TestApk`,
`TestApkInstrumentation` and `TestApkPermission` item groups for this
target and also for `RunApkTests` target.
=> [tests] Split APK tests into parallel and non-parallel runs

build-tools/scripts/TestApks.targets
Recently some/many of the tests run out of memory on Jenkins. So lets
try to increase the emulator memory size to see whether it will help.
The emulator is created for every build on CI, like this:
Using "CreateAndroidEmulator" task from assembly "/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/build-tools/scripts/../../bin/BuildRelease/Xamarin.Android.Tools.BootstrapTasks.dll".
Task "CreateAndroidEmulator" (TaskId:110)
Task Parameter:AndroidAbi=x86 (TaskId:110)
Task Parameter:AndroidSdkHome=/Users/builder/android-toolchain/sdk (TaskId:110)
Task Parameter:SdkVersion=28 (TaskId:110)
Task Parameter:ImageName=XamarinAndroidTestRunner (TaskId:110)
Task Parameter:ToolExe=avdmanager (TaskId:110)
Task Parameter:ToolPath=/Users/builder/android-toolchain/sdk/tools/bin (TaskId:110) …
=> [tests] Increase the emulator RAM size to 3GB

src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileExpected.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs, src/Xamarin.Android.Build.Tasks/Utilities/ResourceIdentifier.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes #3049
This commit also reworks the id generation of the
`ManagedResourceParser` to try replicate the
ids which `aapt2` produces. As a result if the managed
parser generates the code from the `R.txt` file or
directly from the resources, the resulting designer.cs
file will be identical most of the time. There does seem
to be an odd ordering issue where the R.txt file does
not seem to order the items by name as the Id's are 
sometimes switched.
=> [Xamarin.Android.Build.Tasks] first styleable resource id is always incorrect

src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs
Fixes https://github.com/xamarin/xamarin-android/issues/3058
I added comments inline for clarification.
According to https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#openConnection() passing Proxy.NoProxy tells the URL class to not use a proxy, regardless of system settings. Leaving the parameter out makes sure that system settings are used.
=> Do not pass Proxy.NoProxy so that the system proxy settings are respected

Configuration.props
Context: https://github.com/xamarin/xamarin-android/commit/09c390fc97c972a0767d9219ee4715a34b497458
This is the latest stable version of the emulator and it brings the headless
version we hope to use for our tests.
=> Update Android emulator version to 29.0.8

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RenameTestCases.cs, build-tools/scripts/TestApks.targets, tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.projitems
Until now, the logcat filenames were created per TestApk item. BCL
tests share the TestApk item and are differentiated by
TestApkInstrumentation item.
We would like to have logcat files for both.
Also do not process timing for these as it would complicate the
processing (we iterate over _AllArchives and not
TestApkInstrumentation item group). We don't use the BCL timing for
plots, so we will not miss these.
Hopefully this change will help diagnose the BCL tests on Jenkins,
which might be crashing currently and we didn't have the logcat output
in the test results archive.
It might be just another adb crash, but having the logcat output might
shed some light.
[2019-05-05T16:46:27.721Z]   [TESTLOG] Test ResolveSdkTiming Complete
[2019-05-05T16:46:27.721Z]   [TESTLOG] Test ResolveSdkTiming …
=> [tests] Collect separate logcat files for xunit and nunit BCL tests

src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs
We noticed some odd behavior from MSBuild such as:
ReferenceDependencyPaths
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\netstandard.dll
HintPath = ..\..\..\packages\Newtonsoft.Json.11.0.2\lib\netstandard2.0\Newtonsoft.Json.dll
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Runtime.Serialization.dll
HintPath = ..\..\..\packages\Xamarin.Forms.3.1.0.583944\lib\MonoAndroid10\Xamarin.Forms.Platform.Android.dll
`%(HintPath)` is leftover metadata from the `@(ReferencePath)` item
group, so it points to the original assembly???
We currently use `%(HintPath)` in two places, but it seems like we
don't need to use …
=> [Xamarin.Android.Build.Tasks] do not use %(HintPath)

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileExpected.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs
You can have versioned resources in android. As a
result you can have duplicate resource entries.
In the case of styleable items we were trying to
use a dictionary to keep track of the items which
we need to generate id's for. However because we
where comming across duplicate resource entires
we were crashing with a
System.ArgumentException: An item with the same key has already been added.
This was because we had already created that `CodeMemberField`
and added it to the dictionary. What we need to do is skip over
items which have already been added.
Another problem with this was the order in which we
generated the styleable items. Adding the new `MultiSelectListPreference`
item caused the `ManagedResourceParser` to produce
different results. It turns out that android does some
sorting …
=> [Xamarin.Android.Build.Tasks] Handle duplicate Resources for Resource.Designer.cs

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
Fixes #3081
When running an app using the shared runtime we get
the following
Unhandled Exception : System.ArgumentException: Handle must be valid.
This was tracked down to the information in the `typemap.mj.inc`
file. Here are the file sizes for that file, one with the shared
runtime enabled, one without
ls -la typemap.mj.inc    <- shared runtime
-rw-r--r--  1 d  staff  462  9 May 09:42 typemap.mj.inc
ls -la obj/Debug/android/typemap.mj.inc   <- not shared runtime
-rw-r--r--  1 d  staff  8982060  9 May 09:43 obj/Debug/android/typemap.mj.inc
As you can see, the shared runtime file is missing a huge
amount of data. In the past when we generated the old typemap
files we only needed to generate the mapping for the types
in the user assemblies. This is because when using the
shared runtime,it …
=> [Xamarin.Android.Build.Tasks] Debug Shared Runtime deployment attempts are crashing on startup

build-tools/scripts/RunTests.targets, tests/RunApkTests.targets
Commit
https://github.com/xamarin/xamarin-android/commit/74cf0ec949783f2b70b9541a24ebea304dc9e6eb
started running the locale test non-parallel to have *sane* time
measurements.
It will be nice to have the AOT and profiled AOT times for locale test
as well.
=> [tests] Run locale test with AOT enabled too

Documentation/building/configuration.md, build-tools/scripts/Windows-Configuration.OperatingSystem.props.in
Allow `$(JavaSdkDirectory)` to be specified within
`Configuration.Override.props` to control the JDK location.
=> [build] Allow Windows to override `$(JavaSdkDirectory)`

src/java-runtime/java-runtime.targets
For some unknown reason, the JDK environment on @jonpryor's Windows
machine is "wonky," in that the `src\java-runtimes` directory fails
to build because the Android SDK `dx` command fails to execute
because `dx` cannot find Java:
> cd src\java-runtimes
> msbuild
...
ERROR: No suitable Java found. In order to properly use the Android Developer
Tools, you need a suitable version of Java JDK installed on your system.
We recommend that you install the JDK version of JavaSE, available here:
http://www.oracle.com/technetwork/java/javase/downloads
If you already have Java installed, you can define the JAVA_HOME environment
variable in Control Panel / System / Avanced System Settings to point to the
JDK folder.
You can find the complete Android SDK requirements here: …
=> [java-runtimes] Set `%JAVA_HOME%`

README.md
Starting with Xamarin.Android 9.2, public download links for commercial
builds are only available for versions that are published in Visual
Studio.  So the new entries in this commit for Xamarin.Android 9.2 link
directly to the latest released packages for Xamarin.Android 9.2.  These
are the same locations that Visual Studio and Visual Studio for Mac use
to download Xamarin.Android 9.2.
Also, remove the commercial Xamarin.Android master download location.
Because public download links for commercial builds are now only
available for versions that are published in Visual Studio, up-to-date
commercial builds of the `master` branch are not currently available.
For now, only the open source builds of the `master` branch are
available.
=> [docs] Add Commercial Xamarin.Android 9.2 download location

build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/mono-runtimes/mono-runtimes.targets
Add build-time support for *Windows* [mono archives][0].
Context: [xamarin-android/d16-2-with-mono-2018-10-via-6e8a50ea][1]
Context: https://github.com/mono/mono/pull/14307
Context: https://github.com/mono/mono/issues/14333
Fixes: https://github.com/mono/mono/issues/13150
Fixes: https://github.com/mono/mono/issues/14223
Fixes: https://github.com/mono/mono/issues/14247
Fixes: https://github.com/mono/mono/issues/14290
The [Xamarin.Android Designer][2] is an interesting beast: it runs a
Xamarin.Android-like Java stack on desktop macOS and Windows.  A Java
process is created, and that Java process loads:
* *Desktop* Mono via `libmonosgen-2.0.dylib` (macOS)` or
`libmonosgen-2.0.dll` (Windows).`
* The Xamarin.Android runtime via `libmono-android.debug.dylib`
(macOS) or …
=> Bump to mono/mono@1ce13bb

src/Xamarin.Android.Build.Tasks/Tasks/ConvertCustomView.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/microsoft/SmartHotel360-Mobile
In 84daf03, we had to do a workaround to support custom views when
aapt2 is enabled. We had to run a second `aapt2 compile` command for
any layouts with custom views.
In testing our build performance, I noticed a slow MSBuild task when
building SmartHotel360 after a XAML change:
Task Aapt2Compile 19.959s
It makes sense that `_GenerateJavaStubs` ran in this case. This
project does not set `$(ProduceReferenceAssembly)`, which is likely
the current norm for our users.
I think we can do two things to improve this:
1. Run `aapt2 compile` on only the resource directories needed, it
looks like we are running against all of them.
2. Setup a new target, `_ConvertCustomView`, that will be skipped in
cases of small code changes.
If I look at …
=> [Xamarin.Android.Build.Tasks] improve aapt2 incremental builds

tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs, tests/RunApkTests.targets
There were a couple of problems with the
device tests. Firstly we were exporting
the `USE_MSBUILD` property this was causing
the old `__NonExistentFile__` file build
issue which causes `CoreCompile` to always
run.
The second was we were looking for `MonoRuntimeProvider`
in the `classes.dex` file in the apk. However with the
new enhanced fast deployment we no longer include that
file. So we need to check it does NOT exist, bit
check that `MonoPackageManager` is included instead.
=> [tests] Fix the MSBuild device tests

src/mono-runtimes/mono-runtimes.targets
Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/528/
Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/528/Azure/processDownloadRequest/xamarin-android/xamarin-android/xa-build-status-v9.4.99.31_Darwin-x86_64_master_8b24a5ee-Release.zip
Commit d5e002e1 inadvertently broke the `_BuildUnlessCached` target.
The result is longer build times, as every time `src/mono-runtimes` is
is built because of a `@(ProjectReference)`, it rebuilds:
Target "_BuildUnlessCached: (TargetId:1281)" in file "…/xamarin-android/src/mono-runtimes/mono-runtimes.targets" from project "…/xamarin-android/src/mono-runtimes/mono-runtimes.csproj" (target "Build" depends on it):
Building target "_BuildUnlessCached" completely.
Output file …
=> [mono-runtimes] Fix _BuildUnlessCached

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsAndroidApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsMapsApplicationProject.cs
Context: https://github.com/xamarin/Xamarin.Forms/issues/6250
Xamarin.Forms 4.0.0.425677 just went stable.
I've seen an issue with r8 that happens with XF 4.0 and *not* 3.6, so
I thought it would be worth upgrading our MSBuild tests to see if any
tests fail.
=> [tests] update to Xamarin.Forms 4.0.0

.external
Changes: https://github.com/xamarin/monodroid/compare/48faeb611654670518b26ae279f9eb8509f685c3...1c7dc0b742b0dd49b93189730a14eb61dc1e89a5
Allow additional extension of build process `PropertyGroup` elements.
=> Bump to xamarin/monodroid/d16-2@1c7dc0b7

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Utilities/Files.cs
Context: https://github.com/xamarin/xamarin-android/blob/373c6ed08bef01274bd4abfe330d50327052e067/src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs#L195
Context: https://github.com/xamarin/xamarin-android/blob/373c6ed08bef01274bd4abfe330d50327052e067/src/Xamarin.Android.Build.Tasks/Utilities/Files.cs#L271
Testing locally, code changes were not making it onto my device...
Reviewing the build logs:
1. `_CopyPackage` was skipped
2. `CopyIfZipChanged` was returning `false`
3. The `CRC` values of each item in the APK was reporting `0`???
I decided to nuke my build tree with `git clean -dxf` and rebuild.
Then it worked fine... I must have had an outdated `libzip.dll` that
was broken?
This makes me nervous, but there is something to improve here.
There was not really sufficient logging for me to …
=> [Xamarin.Android.Build.Tasks] more logging in <BuildApk/>

Documentation/guides/BuildProcess.md, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Designer.targets, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
As part of the AndroidX migration the Component team
need to hook into our build process. They have
currently been doing that via `BeforeTargets/AfterTargets`.
We have been trying to reduce our use of those methods
within the Xamarin.Android product since commit 3942496.
This PR adds a few internal extension points which can be used
by the components team. Namely
$(_BeforeLinkAssemblies);
$(_AfterGenerateAndroidResourceDir);
$(_BeforeCompileDex);
These can be used by adding a new property group via
<_BeforeCompileDex>
$(_BeforeCompileDex);
_Foo;
</_BeforeCompileDex>
</PropertyGRoup>
We have also added a couple of public extension points
$(BeforeGenerateAndroidManifest);
$(AfterGenerateAndroidManifest);
The main purpose os these is two fold. First for the
component team, …
=> [Xamarin.Android.Build.Tasks] Add some extension points for the Components Team

Documentation/guides/messages/xa4306.md, src/Xamarin.Android.Build.Tasks/Tasks/D8.cs, src/Xamarin.Android.Build.Tasks/Tasks/R8.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/r8/build.gradle
Context: https://mvnrepository.com/artifact/com.android.tools/r8/1.4.93
Context: https://r8.googlesource.com/r8/+/refs/tags/1.4.93/
Updating to the latest R8, we hit a problem...
In R8 1.4.93, they appear to have removed support for custom
`multidex.keep` files when `minSdkVersion` >= 21. R8 decides on its
own if multidex is needed, and splits up dex files appropriately.
The new error message was added here:
https://r8.googlesource.com/r8/+/0e5c4339df0207a0e38f11438db84b29f328f777%5E%21/
Since `r8.jar` will now abort with an error if you specify
`multidex.keep` files and `minSdkVersion` >= 21. I feel all we can do
in this case is add a new warning if developers specify
`@(MultiDexMainDexList)` with R8--then allow R8 to calculate multidex
on its own.
We looked a bit, and did not find much …
=> [r8] update to 1.4.93

Documentation/guides/BuildProcess.md, src/Xamarin.Android.Build.Tasks/Tasks/AndroidSignPackage.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
@redth and I recently went through the process of submitting a
Xamarin.Android App Bundle to Google Play. He had an existing app,
while I tested the SmartHotel360 app.
Unfortunately, Google Play did not accept the bundle at first:
"The Android App Bundle was not signed."
But it *was* signed?
Looking at the build log, the build was running:
jarsigner.exe
-keystore foo.keystore
-storepass foo
-keypass foo
-digestalg SHA1
-sigalg md5withRSA
-signedjar bin\Release\com.foo.smarthotel-Signed.aab
obj\Release\90\android\bin\com.foo.smarthotel.aab
For Android App Bundles, Google Play seems to no longer allow md5 or
SHA1 in favor of SHA-256.
For App Bundles to be accepted by Google Play, we had to run
`jarsigner` manually with:
jarsigner.exe
-keystore foo.keystore
-storepass foo
-keypass foo …
=> [Xamarin.Android.Build.Tasks] App Bundles & Google Play

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/monodroid/jni/embedded-assemblies.cc, src/monodroid/jni/embedded-assemblies.h
Context: https://github.com/xamarin/xamarin-android/commit/7ac95e733c6065dae0c65cad217ab8214fd72247
Context: https://github.com/xamarin/xamarin-android/commit/decfbccf#diff-fcb50a6533eb26323059bc5c8bda1dd7L384
This reverts 7ac95e7 and reverts a small portion of decfbcc.
Unfortunately with 16.2/master we have a ~2.75 second regression with
incremental build performance.
An example using a "Hello World" Xamarin.Forms app, which came from
the File->New Project template in Visual Studio 2019 16.0:
9.2.3-0
829 ms  GenerateJavaStubs                          1 calls
9.4.0-17
3703 ms  GenerateJavaStubs                          1 calls
This was `Debug` / fast dev build after a XAML change.
The slowdown is due to changes in 7ac95e7, which fixed a crash on
startup when the Mono shared runtime is …
=> [monodroid] support typemaps from shared runtime again

src/mono-runtimes/mono-runtimes.targets, tests/api-compatibility/api-compatibility.mk
@jonpryor I also have another patch that keeps those binaries at `bin/Build$(CONFIGURATION)/` , but has a new target since it can't re-use `MonoUtility`. I hope this is okay as it is simpler.
=> [mono-runtimes] Use mono-api-html/info from bundle

build-tools/installers/create-installers.targets, src/mono-runtimes/mono-runtimes.targets
Context: https://github.com/xamarin/xamarin-android/commit/055dabe34e1897305be178a260faee3815e3e908
Context: http://build.devdiv.io/2725037
Windows builds seem to be failing with:
"tests\Runtime-MultiDex\Mono.Android-TestsMultiDex.csproj" (default target) (38) ->
(_ConvertPdbFiles target) ->
Xamarin.Android.Common.targets(2060,2): warning : Could not load file or assembly 'Mono.CompilerServices.SymbolWriter, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified. [E:\A\_work\2218\s\tests\Runtime-MultiDex\Mono.Android-TestsMultiDex.csproj]
Xamarin.Android.Common.targets(2060,2): warning :    at Pdb2Mdb.Converter.Convert(String filename) [E:\A\_work\2218\s\tests\Runtime-MultiDex\Mono.Android-TestsMultiDex.cspro …
=> [mono-runtimes] include Mono.CompilerServices.SymbolWriter

build-tools/automation/azure-pipelines.yaml
We're hitting a couple of git related issues on certain machines, most
commonly around submodule updating on Windows. Rather than relying on an
msbuild setup task to do this, we should override the default pipeline
source checkout behavior. We'll now fetch a clean tree and recursively
clone all relevant submodules for each build stage.
=> [build] Override default yaml checkout behavior

Documentation/guides/messages/README.md
Context: https://github.com/xamarin/xamarin-android/pull/3087
As an additional step toward preparing the message docs to be synced to
docs.microsoft.com, remove the two dead links in the README page for the
message codes.  These links can be added back if dedicated pages are
written for these message codes in the future.
=> [docs] Remove links for message codes that don't yet have pages

build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/mono-runtimes/mono-runtimes.targets
This reverts commit 055dabe34e1897305be178a260faee3815e3e908.
Additional context: f62b794e3a3d8542d43729256b5853736ac0825c
This change produced a breakage when building Xamarin.Android-Tests.sln
on Windows. This breakage[0] was missed for two reasons.
1. We only recently introduced the ability to automatically test mono
related changes on Windows in f9f5b6cd120484b13df74e94638e07411d8693fa.
2. This new Windows build encountered some issues related to submodule
updating when it was first introduced, which was fixed by 2f163049936eb7f95bbbdff184a8e2d128010744.
```
[0] 2019-06-01T04:11:42.7706017Z "E:\A\_work\2165\s\Xamarin.Android-Tests.sln" (default target) (1) ->
2019-06-01T04:11:42.7706304Z "E:\A\_work\2165\s\tests\Runtime-MultiDex\Mono.Android-TestsMultiDex.csproj" (default target) (38) …
```
=> Revert "[mono-runtimes] Use pdb2mdb from archive (#3147)"

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RenameTestCases.cs, build-tools/scripts/TestApks.targets
In recent builds we don't get the logcat output in the error results
test file as we want. It happens because we have the `logcatPath`
wrong.
Like here: https://jenkins.mono-project.com/job/xamarin-android-pr-pipeline-release/1124/testReport/junit/Xamarin.Android.Bcl_Tests/xunit/Possible_Crash___Release/
Checking the build logs, I found:
Looking for `adb logcat` output in the file: /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-release/xamarin-android/build-tools/scripts/../../bin/TestRelease/logcat-Release-Xamarin.Android.Bcl_Tests.xunit.xunit.txt (TaskId:65)
Could not find file `/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-release/xamarin-android/build-tools/scripts/../../bin/TestRelease/logcat-Release-Xamarin.Android.Bcl_Tests.xunit.xunit.txt`.  Will not …
=> [tests] Revert part of 63bef5811

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunInstrumentationTests.cs, build-tools/create-bundle/create-bundle.csproj, build-tools/create-pkg/create-pkg.csproj, build-tools/create-pkg/create-pkg.targets, build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Tools.JavadocImporter/DocumentElement.cs, src/bundletool/bundletool.targets, tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj
Removed an extra `<Import/>`:
src\bundletool\bundletool.targets(2,3): warning MSB4011:
"Configuration.props" cannot be imported again. It was already imported at "src\bundletool\bundletool.csproj (11,3)".
This is  most likely a build authoring error. This subsequent import will be ignored.
Removed an unused field `TextWriter logcatWriter;`:
"build-tools\Xamarin.Android.Tools.BootstrapTasks\Xamarin.Android.Tools.BootstrapTasks.csproj" (default target) (5:2) ->
Xamarin.Android.Tools.BootstrapTasks\RunInstrumentationTests.cs(45,27): warning CS0169: The field 'RunInstrumentationTests.logcatWriter' is never used
Use `<ReferenceOutputAssembly>False</ReferenceOutputAssembly>`:
"src\Xamarin.Android.Build.Tasks\Xamarin.Android.Build.Tasks.csproj" (default target) (28) -> …
=> [build] fixed a pile of warnings

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/3169
Context: https://github.com/zijianhuang/xamarinforms4bugs/tree/ResourcesInLib
We discovered a solution that crashes on startup when it is built with
`$(AndroidUseAapt2)=True`:
Java.Lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/appcompat/R$drawable; ---> Java.Lang.ClassNotFoundException: Didn't find class "android.support.v7.appcompat.R$drawable" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.companyname.Demo2.Android-PozTNMz4ZBMXaHx-doetdQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.Demo2.Android-PozTNMz4ZBMXaHx-doetdQ==/lib/arm64, /data/app/com.companyname.Demo2.Android-PozTNMz4ZBMXaHx-doetdQ==/base.apk!/lib/arm64-v8a, …
=> [Xamarin.Android.Build.Tasks] <Aapt2Link/> don't check for compiled.flata

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/Which.cs
On Windows, I noticed our build generates some odd file extensions:
> ls .\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\ | Select-String EXE
-a----        5/23/2019   2:17 PM        1422848 aarch64-linux-android-as.EXE
-a----        5/23/2019   2:17 PM        1354752 arm-linux-androideabi-as.EXE
-a----        5/23/2019   2:16 PM        1793024 i686-linux-android-as.EXE
-a----        5/23/2019   2:17 PM        1792000 x86_64-linux-android-as.EXE
Going through our build that produces these files:
<Which
HostOS="$(HostOS)"
HostOSName="$(HostOsName)"
Program="$(AndroidNdkFullPath)/toolchains/%(_ToolchainPrefix.Identity)-4.9/prebuilt/$(_PrebuiltToolchainDir)/bin/%(_ToolchainPrefix.ToolPrefix)-as"
Required="True">
<Output TaskParameter="Location" …
=> [xa-prep-tasks] <Which/> can try lowercase extensions

build-tools/installers/create-installers.targets, src/aapt2/aapt2.targets
In the current version of aapt2 we use we are seeing
the following error on Windows
error APT0000: failed parsing overlays.
Oddly it works on MacOS. Bumping to version
3.4.1-5326820 seems to fix the issue.
=> [aapt2] Bump Aapt2 version to 3.4.1-5326820

build-tools/scripts/Configuration.Java.Interop.Override.props, src/monodroid/CMakeLists.txt, src/monodroid/jni/debug.cc, src/monodroid/jni/embedded-assemblies.cc, src/monodroid/jni/logger.cc, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/new_delete.cc, src/monodroid/jni/timezones.cc, src/monodroid/jni/util.cc, src/monodroid/jni/util.h, src/monodroid/jni/xamarin_getifaddrs.cc
Changes:
[Java.Interop] JniMethodInfo.ToString() shouldn't throw (#425)
[java-interop] Migrate to C++ (#427)
Fix build with newer cecil (from overriden source path) (#428)
=> Bump java-interop for fixed cecil build

.external
Provides a fix for commercial .vsix installers being flagged as experimental.
=> Bump external monodroid reference

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
I was actively looking for #deletebinobj bugs, and tried a scenario:
* Create the Master/Detail template from VS 2017 15.9
* Build with 2017 15.9
* Build with 2019 16.2/master
Unfortunately this found a bug:
Task CompileToDalvik
...
Xamarin.Android.Common.targets(2805,3): java.lang.IllegalArgumentException: already added :  Lmono/android/Seppuku;
`Seppuku.java` was another file we missed when creating the
`_CleanupOldStaticResources` target.
I plan to make a new type of test for this scenario, but for now I
updated the `RemoveOldMonoPackageManager` to reproduce this issue.
This fix we can hopefully backport to 16.2.
=> [Xamarin.Android.Build.Tasks] #deletebinobj going from 15.9 to master

build-tools/automation/azure-pipelines.yaml, build-tools/xaprepare/xaprepare/Application/Context.cs, build-tools/xaprepare/xaprepare/Application/Utilities.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs, build-tools/xaprepare/xaprepare/Main.cs, build-tools/xaprepare/xaprepare/Steps/Step_PrepareBundle.cs
Without the trailing `/` in the base URL the last part (the configuration) of
the URL was dropped from the final URL thus pointing to a resource that doesn't
exist.
=> Fix Xamarin.Android bundle URL

build-tools/xaprepare/xaprepare/Application/Utilities.Unix.cs, build-tools/xaprepare/xaprepare/Application/Utilities.Windows.cs, build-tools/xaprepare/xaprepare/Application/Utilities.cs
Current versions of Mono 6 have a bug which makes them throw an `IOException`
whenever an attempt is made to move a file that is a dangling symlink, on Unix
operating systems:
Mono archive already downloaded and valid
Archive path: android-archives/android-debug-Darwin-ddef564e344e1e287d6e7755d633d54aa6344985.7z
[7zip] extracting archive
[7zip] log file: bin/BuildDebug/prepare-20190610T143559.7zip-extract.android-debug-Darwin-ddef564e344e1e287d6e7755d633d54aa6344985.7z.log
Elapsed: 00:00:41.0868232
Step Xamarin.Android.Prepare.Step_BuildMonoRuntimes failed: Could not find file 'external/mono/sdks/out.tmp/android-host-mxe-Win32-debug/bin/mono'.
System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_BuildMonoRuntimes failed: Could not find file …
=> Fix `File.Move` with dangling symlinks

build-tools/automation/azure-pipelines.yaml, build-tools/scripts/PrepareWindows.targets
Instead of running `xaprepare.exe` directly during our build, we
should instead use the `/t:Prepare` target.
This is what developers will use to build Xamarin.Android on Windows,
so this will help us ensure the `Prepare` target continues to work.
=> [build] use Prepare target for AzDO

Configuration.props, build-tools/xaprepare/xaprepare/OperatingSystems/Linux.cs, build-tools/xaprepare/xaprepare/OperatingSystems/MacOS.cs, build-tools/xaprepare/xaprepare/OperatingSystems/OS.cs, build-tools/xaprepare/xaprepare/OperatingSystems/Windows.cs, build-tools/xaprepare/xaprepare/Resources/Configuration.OperatingSystem.props.in, build-tools/xaprepare/xaprepare/Steps/Step_GenerateFiles.cs
`ant` is installed using the package managers on `macOS` and `Linux` and by
downloading its zip distribution archive on Windows. All of those systems
install the utility in a different location (`macOS` in homebrew prefix -
usually `/usr/local`, Linux in `/usr` and Windows in `~/android-toolchain/ant`)
and so it is necessary to point our MSBuild tasks to the correct location.
Make the `AntDirectory` MSBuild property overridable and assign it the default,
detected, location in `Configuration.OperatingSystem.props`
=> [xaprepare] Detect `ant` installation directory

build-tools/automation/build.groovy
Context: https://jenkins.internalx.com/view/Xamarin.Android/job/xamarin-android-commercial/127/execution/node/153/log/
On latest master, the new `.7z` bundle is giving a 404:
Bundle URL: https://xamjenkinsartifact.azureedge.net/mono-jenkins/xamarin-android-debug/xamarin-android/bin/Debug/bundle-v21-h9f52cd0-Debug-Darwin-libzip=b95cf3f,mono=c6edaa6.7z
Step Xamarin.Android.Prepare.Step_PrepareBundle failed
When I look at the build log from Jenkins:
11:47:21  + cp 'bin/Release/bundle-*.zip' /Users/builder/jenkins/workspace/xamarin-android-commercial/package
11:47:21  cp: bin/Release/bundle-*.zip: No such file or directory
11:47:22  sh: line 1: 29879 Terminated: 15          sleep 3
It looks like we are still expecting `.zip` here.
I changed our groovy script to use `-*`, so that both …
=> [build] support .7z extension for xa bundle

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
In testing our AndroidX migration, we found a situation where some of
Xamarin.Android's MSBuild targets would always run:
Building target "_ConvertLibraryResourcesCases" completely.
Input file "obj\Debug\90\lp\44.stamp" does not exist.
...
Building target "_UpdateAndroidResgen" completely.
Input file "obj\Debug\90\lp\44.stamp" does not exist.
...
Building target "_CreateBaseApk" completely.
Input file "obj\Debug\90\lp\44.stamp" does not exist.
This seemed to occur in the case of the AndroidX NuGet package using
an AAR file. Digging further, it seemed we were using the incorrect
path for the `N.stamp` file in the `<ResolveLibraryProjectImports/>`
MSBuild task. It was using `aarFile.ItemSpec` instead of
`aarIdentityName`, which would be the integer-based ID.
It seems this bug has been here …
=> [Xamarin.Android.Build.Tasks] correct name for AAR stamp files

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Tasks/MakeBundleNativeCodeExternal.cs, src/Xamarin.Android.Build.Tasks/Tasks/PrepareAbiItems.cs, src/Xamarin.Android.Build.Tasks/Tasks/SplitProperty.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/MakeBundleNativeCodeExternalTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/3175
In 6ce33aa5, we broke support for `,` and `%3b` as delimiters for
`$(AndroidSupportedAbis)`. We did not have a test checking for these
cases.
Reviewing the code, we had repetition like this throughout our
codebase:
var abis = SupportedAbis.Split (new char[] { ',', ';' }, StringSplitOptions.RemoveEmptyEntries);
Instead what we should do, is provide a single task that converts the
abis to an MSBuild item group to be used throughout:
<SplitProperty Value="$(AndroidSupportedAbis)">
<Output TaskParameter="Output" ItemName="_BuildTargetAbis"/>
</SplitProperty>
Then we can consume the `@(_BuildTargetAbis)` item group in a simpler
way from inside MSBuild tasks:
[Required]
public string [] SupportedAbis { get; set; }
MSBuild can handle …
=> [Xamarin.Android.Build.Tasks] properly support abi delimiters

.editorconfig
Include `indent_size = 8` to fix indenting of code blocks.
Scope tab settings to managed code so we don't mistakenly apply them to C++ or other stuff.
=> Tweak .editorconfig to include indent_size and scope changes to managed code files

build-tools/scripts/RunTests.targets, build-tools/xaprepare/xaprepare/Scenarios/Scenario_Standard.Windows.cs, build-tools/xaprepare/xaprepare/Steps/Step_CopyLibZip.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj, tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/Xamarin.Android.MakeBundle-UnitTests.csproj, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/EmbeddedDSO-UnitTests.csproj
Changes: https://github.com/grendello/LibZipSharp/compare/da94d3d...71f4a94
I hit an error during a local build on Windows:
"src\aapt2\aapt2.csproj" (default target) (26:2) ->
(_DownloadAapt2 target) ->
src\aapt2\aapt2.targets(49,5): error MSB4018: The "UnzipDirectoryChildren" task failed unexpectedly.
src\aapt2\aapt2.targets(49,5): error MSB4018: System.AggregateException: One or more errors occurred.
---> System.DllNotFoundException: Unable to load DLL 'libzip.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
The culprit appeared to be `bin\BuildDebug\libzip.dll` having a
dependency on `zlib.dll`. But we don't even ship `zlib.dll`?
Further investigation, we found `libZipSharp` was using some outdated
NuGet packages for these native libraries on Windows. …
=> Bump to grendello/LibZipSharp/master@71f4a94

build-tools/automation/build.groovy
Context: https://github.com/xamarin/xamarin-android/commit/6f238a2b98a4e03b9f8f7a9b84e865c1b515d036
Commit 6f238a2b fixed the xaprepare bootstrapping logic to be able to
download and consume a bundle which was previously built and published
to azure storage. It also exposed a "bug" in xaprepare: when a prebuilt
bundle was downloaded and used, it would no longer also be copied to the
output directory where it would have otherwise been built. Azure Pipeline
and internal Jenkins builds which use a prebuilt bundle broke as a result,
as they attempt to upload a bundle from bin/$Configuration. The Azure
Pipeline breakage was fixed in commit 6f238a2b because subsequent jobs
rely on the bundle being uploaded again. There are no downstream
consumers of the bundle uploaded by internal Jenkins, so …
=> [build] Don't publish bundle on internal Jenkins

.external, build-tools/installers/create-installers.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/3197
`xbuild-frameworks\MonoAndroid\v9.0\Mono.Android.xml` was missing from
our VSIX installer. This file is only needed on Windows.
Looking at the code:
<_FrameworkFilesWin Include="$(FrameworkSrcDir)\v8.1\Mono.Android.xml" />
<_FrameworkFilesWin Include="$(FrameworkSrcDir)\$(AndroidLatestFrameworkVersion)\Mono.Android.xml" />
`$(AndroidLatestFrameworkVersion)` changed to `v9.0.99`, which caused
this issue.
Looking further, there was some more things that could be cleaned up:
* A few files were listed using `$(FirstInstallerFrameworkVersion)`,
such as `$(FrameworkSrcDir)\$(FirstInstallerFrameworkVersion)\*`.
These were duplicate from what the `ConstructInstallerItems` target
was looking up.
* We should make a …
=> [installer] restore missing XML documentation files

build-tools/debian-metadata/rules
Debian packaging process doesn't work well with native PE executables, trying to
process them with `ikdasm` in order to extract dependencies of the executable.
To make builds possible, remove all the Windows GNU Assemblier (`*-as.exe`)
executables, as well as any instances of `libzip.dll`, before packaging.
=> Fix debian build

src/monodroid/jni/dylib-mono.cc, src/monodroid/jni/dylib-mono.h, src/monodroid/jni/monodroid-glue.cc
Do not load that symbol anymore. Also replace the
`DylibMono::profiler_install_thread` method with the callback methods
and use these directly.
Left the
monodroid_mono_profiler_install_thread_fptr mono_profiler_install_thread;
in DylibMono struct to preserve the binary compatability (preserve
struct order). This will vanish once we get rid of the whole
DylibMono.
=> [monodroid] Get rid of mono_profiler_install_thread

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/xamarin-android/commit/901dba8cf03e65789f160927e8576c77924b13ff
Context: https://github.com/xamarin/xamarin-android/commit/decfbccf3e99449c9a8d6afef113c9339f1bc85b
In decfbcc, we broke support for `,` and `%3b` as delimiters for
`$(AndroidSupportedAbis)`. We did not have a test checking for these
cases.
I fixed this in 901dba8c, but the diff was too large to be deemed
"safe" for 16.2 at this point in time.
A one-line patch to fix the issue is this MSBuild incantation:
<_XARuntimeArchitecture Include="$([MSBuild]::Unescape($(_BuildTargetAbis.Replace(',', ';'))))"/>
We replace the `,` with `;` -- which gets escaped to `%3b`. The
`[MSBuild]::Unescape` call converts `%3b` back to `;`.
This also supports `%3b`.
=> [Xamarin.Android.Build.Tasks] fix for abi delimiters

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/xamarin-android/pull/3205
Context: https://github.com/microsoft/azure-pipelines-agent/issues/2301
We've been occasionally encountering a Windows build failure that we
believe to be caused by having an unclean checkout on certain machines.
Previously, we had attempted to recursively clean our source checkout
through the Azure Pipeline checkout task options. However upon further
investigation, it appears that a 'git clean -ffdx' only occurs at the
root level of our repository, and the root level of every submodule. The
clean parameter associated with the checkout task does not recurse into
submodules of submodules. To address this, we'll attempt to clean out
our workspace entirely before each build. This may add a bit of time to
our checkout step, but it …
=> [build] Clean Azure Pipeline workspaces

tests/BCL-Tests/Xamarin.Android.Bcl-Tests/nunit-excluded-tests.txt, tests/BCL-Tests/Xamarin.Android.Bcl-Tests/xunit-excluded-tests.txt, tests/TestRunner.xUnit/XUnitTestRunner.cs
Exclude two categories of tests:
1. `Mono.Unix.Native.SocketTest` tests, which started failing in
commit ce4eeb4f with the bump to mono/mono/2019-02@c6edaa62:
Before (passes): https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/560/testReport/(root)/SocketTest/
After (fails): https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/561/testReport/(root)/SocketTest/
2. Some tests which the Xamarin.iOS team flagged as a frequent cause
of `OutOfMemoryException`-related errors.
In order to better support (2), update `XUnitTestRunner.IsIncluded()`
to support "class-based" test exclusions.  Similar to 333b98b3 and the
"Unit test exclusion" section, extend `XUnitFilterType.TypeName`
checking so that if a test name starts with an excluded name followed
by a …
=> [tests] Exclude additional tests

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes #3123
Commit 373c6ed0 added a new `_ConvertCustomView` target to
handle the conversion of custom view to the md5 hash versions.
While it worked *most* of the time, there was a very specific
area where it was not fixing up the custom views.
This problem only occurs when a library project code is updated.
When happens next is when the main app builds the library
resources are then re-extracted to the
`$(IntermediateOutputPath)lp\XX\ji\res` directory. The
`ConvertResorucesCases` task is then run to fixup those `res`
files with the correct casing. After than `GenerateJavaStubs`
is then also run, this is because the library project was
updated.
However at this point the wheels fall of the wagon because
`_ConvertCustomViews` does NOT run. this is because it
is only using the following …
=> [Xamarin.Android.Build.Tasks] Thrown an exception while enabling "AndroidUseAapt2" in application.

build-tools/installers/create-installers.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/3234
We had trouble creating the required java types, because
`java-interop.jar` was missing.
Thus we endup with:
Error: jnimarshalmethod-gen: Unable to create Java VM
System.TypeInitializationException: The type initializer for 'Types' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object
at Java.Interop.JniEnvironment+Types.FindClass (System.String classname) [0x000b2] in <3d0cf794364146b58e1c173deac04834>:0
at Java.Interop.JniType..ctor (System.String classname) [0x00006] in <3d0cf794364146b58e1c173deac04834>:0
at Java.Interop.JniEnvironment+Types..cctor () [0x000d2] in <3d0cf794364146b58e1c173deac04834>:0
--- End of inner exception stack trace ---
at …
=> [jnimarshalmethod-gen] Include java-interop.jar in the installation

build-tools/automation/build.groovy
We're encountering a failure when attemping to copy the 'xa-build-status'
zip to it's publish destination. For debugging purposes, we'll check the
content of this folder before attempting to copy anything.
=> [build] Check build dir for results before copy

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/Adb.cs, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RenameTestCases.cs, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunInstrumentationTests.cs, build-tools/Xamarin.Android.Tools.BootstrapTasks/result-packaging.targets, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/apk-instrumentation.yaml, build-tools/automation/yaml-templates/run-installer.yaml, build-tools/scripts/Jar.targets, build-tools/scripts/TestApks.targets, build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/ProcessLogcatTiming.cs, src/Mono.Android/Test/Mono.Android-Tests.targets, tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding/Xamarin.Android.LibraryProjectZip-LibBinding.targets, tests/Xamarin.Forms-Performance-Integration/Droid/Xamarin.Forms.Performance.Integration.Droid.targets
Adds a `Test` stage to azure-pipelines.yaml. At present, this stage only
contains one test job, which builds and runs the following emulator tests:
Mono.Android_Tests
Mono.Android-Tests (AOT + LLVM)
Mono.Android-Tests (Profiled AOT)
Mono.Android-Tests (Bundle)
Mono.Android_TestsAppBundle
Mono.Android_TestsMultiDex
Xamarin.Android.JcwGen_Tests
Xamarin.Android.Locale_Tests
Xamarin.Android.Locale-Tests (AOT)
Xamarin.Android.Locale-Tests (Profiled AOT)
Xamarin.Android.EmbeddedDSO_Test
Xamarin.Forms.Performance.Integration.Droid 
Xamarin.Forms.Performance.Integration.Droid (AOT)
Xamarin.Forms.Performance.Integration.Droid (Profiled AOT)
Xamarin.Forms.Performance.Integration.Droid (Bundle)
Performance reporting has not been considered as part of this PR. Execution of the 
BCL Test suite will …
=> Add APK test job to azure-pipelines.yaml

build-tools/automation/build.groovy
Context: https://github.com/xamarin/xamarin-android/commit/d9348ebfe58a41c8bb340a3984c62e1a4f90d9c3
We were encountering an issue when trying to upload our build results
file on internal Jenkins, which appears to have been caused by the fact
that we were appending an extra 'xamarin-android' to the result path we
were trying to copy from. Strangely, this upload failure seemed to only
happen intermittently, but I'm not sure how (if?) it ever worked.
The fix is to remove the extra 'xamarin-android' value from the expected
build result path, as we're already executing these commands from the
'xamarin-android' directory.
=> [build] Fix internal Jenkins build status reporting

build-tools/remap-assembly-ref/remap-assembly-ref.sln, build-tools/xaprepare/xaprepare/Steps/Step_PrepareLocal.cs
We've seen the following build error when `remap-assembly-ref` is built
from within `xaprepare` by passing its project file to msbuild:
(ValidateSolutionConfiguration target) ->
/Users/vsts/agent/2.153.2/work/1/s/external/mono/external/cecil/Mono.Cecil.sln.metaproj :
error MSB4126: The specified solution configuration "net_4_0_Debug|Any CPU" is invalid.
Please specify a valid solution configuration using the Configuration and Platform properties
(e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those
properties blank to use the default solution configuration.
[/Users/vsts/agent/2.153.2/work/1/s/external/mono/external/cecil/Mono.Cecil.sln]
The reason is that the `$(Configuration)` property, even though set on the msbuild
command line, is reset somewhere …
=> Add a solution file for remap-assembly-ref

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/Aapt2Tests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
Commit 4ccbeb74 added support for downloading `aapt2`
from maven. One thing we missed was updating the
unit tests for `aapt2` to use this rather than the
one in `build-tools`.
This commit updates those tests to use the In-Tree
version of `aapt2` rather than the one in `build-tools`.
It also fixed one of the tests as the new `aapt2` is
now raising two errors rather than just one.
=> [Xamarin.Android.Build.Tests] Update Aapt2 tests to use the XA version.

build-tools/Xamarin.Android.Tools.BootstrapTasks/result-packaging.targets
Context: https://jenkins.mono-project.com/job/xamarin-android-pr-pipeline-release/1336/Azure/
Context: https://github.com/xamarin/xamarin-android/commit/caa3aa47c7a9e86bacc0052c37660b8819d904c9
On a PR build, I saw a case where the EmbeddedDSO tests failed, but we
don't have any build logs.
In caa3aa4, I updated `$(OutputPath)` for this test project, which
meant the `@(_TestResultFiles)` item group would not find the logs:
<_TestResultFiles Include="$(XamarinAndroidSourcePath)bin\Test$(Configuration)\EmbeddedDSO\EmbeddedDSO.build\**\*" />
I think we should just recursively find all `.binlog` and `.log` files
within `bin\Test$(Configuration)`, in case any of these paths change
in the future.
=> [BootstrapTasks] find .binlog and .log recursively

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ResourceDesignerImportGenerator.cs
Fixes: http://feedback.devdiv.io/606610
Fixes: https://github.com/xamarin/xamarin-android/issues/1988
The latest version of Xamarin.Forms causes warnings such as:
warning XA0106: Skipping UnnamedProject.Resource.Drawable.avd_hide_password_1. Please check that your Nuget Package versions are compatible.
warning XA0106: Skipping UnnamedProject.Resource.Drawable.avd_hide_password_2. Please check that your Nuget Package versions are compatible.
warning XA0106: Skipping UnnamedProject.Resource.Drawable.avd_hide_password_3. Please check that your Nuget Package versions are compatible.
warning XA0106: Skipping UnnamedProject.Resource.Drawable.avd_show_password_1. Please check that your Nuget Package versions are compatible.
warning XA0106: Skipping …
=> [Xamarin.Android.Build.Tasks] downgrade XA0106 to a message

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs, build-tools/xaprepare/xaprepare/Steps/MonoRuntimesHelpers.cs, build-tools/xaprepare/xaprepare/Steps/Step_BuildMonoRuntimes.Unix.cs, build-tools/xaprepare/xaprepare/Steps/Step_PrepareBundle.cs
It may happen that some files which are supposed to be in the bundle are
missing. In such case we need to re-download or re-install the bundle to fix the
issue. This commit makes sure it happens.
Additionally, since all the bundle items are specified in `Runtimes.cs`, the
file must be used when calculating the bundle "version" hash or we might face
the issue when the list of expected bundle items (in `Runtimes.cs`) doesn't
agree with what's in the currently selected bundle - because the hash didn't
change even though we added/removed bundle items in `Runtimes.cs`
=> Always check if we have every bundle item installed

Documentation/guides/messages/xa0113.md, Documentation/guides/messages/xa0114.md, Documentation/guides/messages/xa4214.md
Context: https://github.com/xamarin/xamarin-android/issues/1988
Also replace the `/nowarn` command line switch with its alias
`/warnasmessage` to help emphasize the distinction between this command
line switch and the *unrelated* `$(NoWarn)` MSBuild property.
I have verified that both the `/warnasmessage` command line switch and
the `$(MSBuildWarningsAsMessages)` MSBuild property successfully
suppress `XAnnnn` warnings such as `XA4214`.
The reason behind these changes is that I learned that the `/nowarn`
command line switch for MSBuild does *not* correspond to the `$(NoWarn)`
MSBuild property.  In fact, the `$(NoWarn)` property is not used at all
by the MSBuild logger itself.  It is instead passed into the [`<Csc/>`
task in C# projects][0], the [`<Vbc/>` task in Visual Basic
projects][1], …
=> [docs] Correct NoWarn property to MSBuildWarningsAsMessages

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DeleteBinObjTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.Shared.projitems, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ExistingProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj
I setup a new #deletebinobj "regression protection" test:
* Created the Master/Detail Xamarin.Forms template from Visual Studio
2017 15.9
* Built it with 15.9, `Debug` and `Release`
* Zipped it up, and uploaded to Azure
I created 2 zips: Windows & Darwin. I also added a "revision" in the
URL, for changing the zip over time. It will get cached on a CDN, so
the URL needs to change sometimes.
Next I created an `ExistingProject` type in `Xamarin.ProjectTools`, so
I could unzip these files and build them.
To fix other weirdness with NuGet when passing `bin` and `obj` from
one machine to another, I had to:
* Explicitly run `Restore`
* Set `RestoreNoCache=True`, or Mac would fail to `Restore`
I plan to make further changes to `DeleteBinObjTest.cs` in other PRs.
It should start apps and connect …
=>  [Xamarin.Android.Build.Tasks] #deletebinobj "regression protection"

build-tools/xaprepare/xaprepare/Application/Context.Linux.cs, build-tools/xaprepare/xaprepare/Application/Context.MacOS.cs, build-tools/xaprepare/xaprepare/Application/Context.Windows.cs, build-tools/xaprepare/xaprepare/Application/Context.cs, build-tools/xaprepare/xaprepare/Application/MonoCrossRuntime.Windows.cs, build-tools/xaprepare/xaprepare/Application/MonoCrossRuntime.cs, build-tools/xaprepare/xaprepare/Application/Runtime.cs, build-tools/xaprepare/xaprepare/Application/Utilities.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Runtimes.Windows.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Runtimes.cs, build-tools/xaprepare/xaprepare/Steps/Step_BuildMonoRuntimes.Unix.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallAnt.Windows.cs, build-tools/xaprepare/xaprepare/Steps/Step_PrepareBundle.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj
Don't include designer certain files in BuildItems on Windows
Windows, as a host OS, does NOT currently install any BCL files - it takes
everything from the bundle produced on macOS. However, the code to populate
designer BCL file sets also ran on Windows thus producing this, false negative,
error:
bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\Windows\bcl\I18N.dll missing, skipping the rest of bundle item file scan
Some bundle files are missing, download/rebuild/reinstall forced
Step Xamarin.Android.Prepare.Step_PrepareBundle failed
System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_PrepareBundle failed
Fix the issue by not populating the designer BCL files on Windows.
Another issue is Windows trying to include **host** versions of the
cross-compilers in the bundle …
=> Windows build fixes

.external
Changes: https://github.com/xamarin/monodroid/compare/76146a9...f849c5e
This includes changes in monodroid for `@(_BuildTargetAbis)` and 901dba8c.
=> Bump to xamarin/monodroid/master@f849c5e

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/yaml-templates/pull/9
Context: https://dev.azure.com/devdiv/DevDiv/_build?definitionId=9949
Context: https://dev.azure.com/devdiv/DevDiv/_build?definitionId=10046
Context: https://dev.azure.com/devdiv/DevDiv/_taskgroup/58981fdc-2ed9-4cfb-8201-d66a88ed8233
Context: https://dev.azure.com/devdiv/DevDiv/_taskgroup/75c23aa6-db40-44d0-b0e7-65e99f7251c3
Imports template yaml files which contain build and test steps for the
Android Designer.
=> [build] Add Android Designer tests to azure-pipelines.yaml

build-tools/xaprepare/xaprepare/Scenarios/Scenario_AndroidToolchain.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_Standard.cs
I tried building Xamarin.Android on a clean Windows machine:
From: Xamarin.Android.Prepare.Step_Android_SDK_NDK.AcceptLicenses at C:\src\xamarin-android\build-tools\xaprepare\xaprepare\Steps\Step_Android_SDK_NDK.cs(98,4)
EXEC JAVA_HOME is set to an invalid directory: C:\Users\jopepper\android-toolchain\jdk
C:\src\xamarin-android\build-tools\scripts\PrepareWindows.targets(26,5): error MSB3073: The command "C:\src\xamarin-android\build-tools\scripts\..\xaprepare\xaprepare\bin\Debug\xaprepare.exe --no-emoji --run-mode=CI -a " exited with code -1.
Looking at my filesystem, the `jdk` directory did not exist.
It looks like we just need to reorder the steps so that the JDK is
installed before the Android SDK. I was able to fully run `xaprepare`
after that.
I guess things are working on other …
=> [xaprepare] install JDK before Android SDK/NDK

build-tools/automation/azure-pipelines.yaml, build-tools/scripts/PrepareWindows.targets
Sometimes 'xaprepare.exe' will fail before all of the build status
packaging dependencies are built. We can fix some of these cases by
ensuring that we always call the build target before calling any status
packaging targets.
=> [build] Always build result package dependencies

README.md
Also, remove the old Xamarin.Android 7.x download locations for
tidiness.
=> [docs] Add OSS Xamarin.Android master download location

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Commit 901dba8 made some changes to the way
`_DefineBuildTargetAbis` works. However there
was a slight problem with the implemetation.
In our commercial debug system we will automatically
add the abi of the target device to the `_BuildTargetAbis`
ItemGroup. This happens quite early on in the build process.
However the end result of this is that we have duplicate
items in the `_BuildTargetAbis` ItemGroup.
This then causes problems when we try to build the
`libxamarin-app.so`. Because it uses that ItemGroup to
drive the creation and inclusion of files on disk. If
we have duplicates in the ItemGroup we end up with
duplicates in the file list passed to the native linker.
i686-linux-android-ld --unresolved-symbols=ignore-in-shared-libs \
--export-dynamic -soname libxamarin-app.so -z relro \
-z …
=> [Xamarin.Android.Build.Tasks] Fix InstantRun Building

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
[02c07ed6][0] introduced a refinement on `<ConvertResourcesCases/>` to
allow it to skip certain "well-known" assemblies that don't need
processing.  It used an MSBuild item group to define the list of
well-known assemblies.  Each item in the group was a name of a
well-known assembly, without any file extension.
02c07ed6 also included an automated test that checked the build output
for each of the well-known assemblies that should be skipped when
building a test project.  But one of the variable names in the test code
was unintentionally switched around, so the test was actually skipping
over that check for the expected assemblies.
Later, [b255da27][1] adapted the assembly skipping mechanism slightly to
use custom metadata to define the list of well-known assemblies.  This
was a step …
=> [Xamarin.Android.Build.Tasks] Restore ConvertResourcesCases skipping

build-tools/xaprepare/xaprepare/Steps/Step_Android_SDK_NDK.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2794198
Context: https://github.com/xamarin/xamarin-android/commit/75e053e5eff431093c7e00d94962fcd13683be5c
I've seen a rare failure[0] in our Windows Azure Devops builds which
looks like it could have been introduced when we bumped the version of
build-tools that we provision from 28.0.3 to 29.0.0.
Rather than bumping the buildToolsVersion in the CodeGen-Binding suite,
we should be able to fix this by updating `xaprepare` to always execute
the Android SDK license acceptance step. This step would previously be
skipped if all SDK items were provisioned. Since it executes quickly, we
might as well run it everytime in case we somehow fall out of sync or
license files are otherwise deleted. This should allow gradle …
=> [xaprepare] Always accept Android SDK licenses

Makefile, build-tools/automation/azure-pipelines.yaml, build-tools/automation/build.groovy, build-tools/scripts/BuildEverything.mk
Context: https://jenkins.mono-project.com/job/xamarin-android-pr-pipeline-release/1448/#showFailuresLink
Context: https://github.com/xamarin/xamarin-android/commit/9302d514a1437e5d1977da06dfbbe4e7054f33d5
Context: https://github.com/xamarin/xamarin-android/commit/f9f5b6cd120484b13df74e94638e07411d8693fa
The primary intent of these changes is to fix the `EmbeddedDSOUnitTests`
failures we are encountering with Jenkins PR builds. However, this has
presented an opportunity to also clean up some xaprepare changes 
which are no longer needed.
We built a lot of hacks into our make file when initially working on the
xaprepare tool, as the windows and mac azure pipeline builds could not
be modified at the time. We now have these builds defined in yaml, and
as such we should be able to simplify the …
=> [build] Simplify CI make and xaprepare invocations

.gitmodules
Context: https://sqlite.org/releaselog/3_27_2.html
Context: https://sqlite.org/releaselog/3_28_0.html
Security updates:    
- [CVE-2019-9936][0]: fix a buffer overread that could occur when running fts5
prefix queries inside a transaction
- [CVE-2019-9937][1]: fix an fts5 problem with interleaving reads and writes
in a single transaction
- [CVE-2019-8457][2]: heap out-of-bound read
[0]: https://www.cvedetails.com/cve/CVE-2019-9936/
[1]: https://www.cvedetails.com/cve/CVE-2019-9937/
[2]: https://www.cvedetails.com/cve/CVE-2019-8457/
=> Update to SQLite 3.28.0

build-tools/scripts/JavaCallableWrappers.targets
Continuing to build  on a fresh Windows machine after b98175c1, I hit
a new issue:
build-tools\scripts\JavaCallableWrappers.targets(50,5): error MSB3073:
The command ""C:\Users\myuser\android-toolchain\sdk\build-tools\29.0.0\dx" --dex --no-strict --output="C:\src\xamarin-android\bin\Debug\lib\xamarin.android\xbuild-frameworks\MonoAndroid\v9.0\mono.android.dex" "C:\src\xamarin-android\bin\Debug\lib\xamarin.android\xbuild-frameworks\MonoAndroid\v9.0\mono.android.jar"" exited with code -1.
EXEC No suitable Java found. In order to properly use the Android Developer
Tools, you need a suitable version of Java JDK installed on your system.
We recommend that you install the JDK version of JavaSE, available here:
http://www.oracle.com/technetwork/java/javase/downloads
If you already have Java …
=> [Mono.Android] set JAVA_HOME when running dx

build-tools/automation/build.groovy, build-tools/scripts/BuildEverything.mk
Context: https://github.com/xamarin/xamarin-android/commit/a61fd98c3e1fb707329a83243d7088e7bf9ec955
Reverts: https://github.com/xamarin/xamarin-android/commit/1e4d167ac45002adaf0711db99b9e68acaf087a6
Fixes the PR build installer creation breakage[0] caused by 1e4d167 by
reverting it. Also fixes local `make jenkins` build failures, as the
recent changes in a61fd98c overlooked local build behavior. A 'full'
build was only being configured correctly when running from CI, and this
has been fixed by ensuring the `PREPARE_CI` make variable is set when
running `make jenkins` locally.
[0]
11:03:56  "/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-release/xamarin-android/build-tools/create-pkg/create-pkg.csproj" (CreatePkg target) (1) ->
11:03:56  (_CopyFilesToPayloadDir target) -> …
=> [build] Fix PR installer creation, and 'make jenkins'

build-tools/automation/azure-pipelines.yaml
We use the `name` property to set our build "number" value in azure
pipelines. This is currently a bit noisy, so I've trimmed it to use the
short branch name variable. We'll lose PR number in the build number
for PR builds as a result, but it's still easily identifiable in the UI.
old: refs_heads_master-b9c3d9a98f20ac34f49c23effc542f0ab8473bd6-1
new: master-b9c3d9a98f20ac34f49c23effc542f0ab8473bd6-1
old: refs_pull_3279_merge-d83366ad6c9ae17a4f4d5c250f1fd81b455ac436-2
new: merge-d83366ad6c9ae17a4f4d5c250f1fd81b455ac436-2
=> [build] Simplify Azure Pipeline build names

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/yaml-templates/pull/11
Context: https://github.com/xamarin/xamarin-android/blob/afb351205999c3c7ea9754c57f9c6467688e881b/build-tools/automation/build.groovy#L209
Context: https://github.com/xamarin/xamarin-android/blob/afb351205999c3c7ea9754c57f9c6467688e881b/build-tools/automation/build.groovy#L287
Imports existing installer signing logic from build.groovy so that we
can conditionally sign .pkg and .vsix installers for public releases.
=> [build] Add signing to azure-pipelines.yaml

.external
Changes: https://github.com/xamarin/monodroid/commit/52c7914d440e1bd57b28ae91a5bb7ac99c163659
We need the monodroid-side changes for `@(_BuildTargetAbis)`.
=> Bump to xamarin/monodroid/d16-3@52c7914

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileWithLibraryReferenceExpected.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidLibraryProject.cs, src/Xamarin.Android.Build.Tasks/Utilities/ResourceIdentifier.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3250
Partially reverts [af61ecda][0].
It turns out that the System.CodeDom APIs take care of adding `@` as
needed on keywords when outputting C# source code.  Behind the scenes at
run time, the name of the field doesn't actually have the `@` prefix
(e.g., `nameof (@fixed)` returns `"fixed"`).  So the code in af61ecda
that added an `@` prefix unintentionally led to incorrect `false` return
values from `resourceFields.Contains()` in
`ResourceDesignerImportGenerator.CreateImportFor()`.
Revert the part of af61ecda that was adding an `@` prefix.  This goes
back to letting System.CodeDom take care of adding the `@` as needed and
restores the previous correct behavior of `resourceFields.Contains()`.
Before this change, the new updated …
=> [Xamarin.Android.Build.Tasks] Revert special handling of keywords in Android resource names

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs
Context: https://github.com/android-ndk/ndk/wiki/Changelog-r20
Context: https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html
Google released NDK r20 recently with the following changes:
- Updated Clang to r346389c.
- Updated libc++ to r350972.
- Add Android Q Beta 1 APIs:
- MIDI (<amidi/AMidi.h>).
- Binder.
- Extensions to several APIs from previous releases
Also, this release brings [LLD][0], the new (fast!) linker from the LLVM project
which will become the default and only linker in the NDK in the future, so soon
we will need to start testing our software with it.
[0]: https://lld.llvm.org/
=> Update NDK to r20

.gitmodules
`LibZipSharp` repository was moved from its previous location to
`xamarin/LibZipSharp`, update the submodule to point to the new location.
=> Update LibZipSharp submodule to point to Xamarin

src/Mono.Android/map.csv
Fixes https://github.com/xamarin/xamarin-android/issues/3180.
Diff against `Mono.Android.dll`:
```
diff --git a/mono.android-android-28/mcw/Android.Views.MetaKeyStates.cs b/mono.android-android-28/mcw/Android.Views.MetaKeyStates.cs
index ee50c45..df2bfa9 100644
--- a/mono.android-android-28/mcw/Android.Views.MetaKeyStates.cs
+++ b/mono.android-android-28/mcw/Android.Views.MetaKeyStates.cs
@@ -28,6 +28,8 @@ namespace Android.Views {
MetaOn = 65536,
[global::Android.Runtime.IntDefinition (null, JniField = "android/view/KeyEvent.META_META_RIGHT_ON")]
MetaRightOn = 262144,
+    [global::Android.Runtime.IntDefinition (null, JniField = "")]
+    None = 0,
[global::Android.Runtime.IntDefinition (null, JniField = "android/view/KeyEvent.META_NUM_LOCK_ON")]
NumLockOn = 2097152, …
```
=> [Mono.Android] Add MetaKeyStates.None. [#3180]

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ExistingProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
Context: https://github.com/xamarin/xamarin-android/commit/c00095b6e560077bfb94185b6e0b9a36996d3b8b
Context: https://github.com/xamarin/monodroid/pull/1007
We have been getting the following error on monodroid builds:
/Users/builder/jenkins/workspace/monodroid-pr/monodroid/external/xamarin-android/bin/Release/bin/xabuild /Users/builder/jenkins/workspace/monodroid-pr/monodroid/external/xamarin-android/bin/TestRelease/temp/HelloFormsFalse/HelloForms.sln /t:Restore /noconsolelogger "/flp1:LogFile=/Users/builder/jenkins/workspace/monodroid-pr/monodroid/external/xamarin-android/bin/TestRelease/temp/HelloFormsFalse/build.log;Encoding=UTF-8;Verbosity=diagnostic" @"/Users/builder/jenkins/workspace/monodroid-pr/monodroid/external/xamarin-android/bin/TestRelease/temp/HelloFormsFalse/project.rsp" …
=> [tests] fix for ExistingProject

src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
One of the problems we have with the `ManagedResourceParser` is
that it uses the `R.txt` to generate the `Resource.Designer.cs`
file. The issue there is that if the user modifies a layout file
(say adds or changes and id) that will NOT be picked up until
the next build. This is because the `R.txt` file is generated
by `aapt/aapt2` and those tools are not called for DesignTime
Builds.
So what we need to do is pass in the `$(_AndroidResFlagFile)`
into the `GenerateResourceDesigner`. This will allow us to
do a last modified date time check against the `R.txt` file.
If the `$(_AndroidResFlagFile)` is newer then we should NOT
use the `R.txt` and parse the layout files to pick up changes.
=> [Xamarin.Android.Build.Tasks] Fix up DesignTime build Resource.Designer.cs

build-tools/xaprepare/xaprepare/Application/ProcessRunner.cs, build-tools/xaprepare/xaprepare/ToolRunners/NuGetRunner.cs, build-tools/xaprepare/xaprepare/ToolRunners/ToolRunner.cs
`NuGetRunner` doesn't properly specify full path to the nuget binary we download
as part of the prepare run and, thus, it depends on any random version of the
utility in the user's `$PATH` (if at all) which may lead to random errors
depending on the nuget version. Fix the issue by passing the full path to the
downloaded binary.
Additionally, fix `ToolRunner` to properly add arguments when managed
runtime (`mono`) is used on Unix. Until now any initial arguments were passed
to **mono** in such case, instead of to the managed executable. Doh.
=> [xaprepare] Use NuGet binary we download

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
The `<ResolveLibraryProjectImports/>` task has some logic that needs
to look at the item metadata of each `@(Reference)`:
* `%(AndroidSkipResourceExtraction)` to skip unzipping anything
* `%(AndroidSkipResourceProcessing)` to skip `<ConvertResourcesCases/>`
To make matters weird, we had some LINQ:
foreach (var assemblyPath in Assemblies
.Select (a => a.ItemSpec)
.Distinct ()) {
And we would basically lose the metadata information...
To handle this problem, we had two `HashSet`'s we used to lookup the
values:
assembliesToSkipCaseFixup = new HashSet<string> (StringComparer.OrdinalIgnoreCase);
assembliestoSkipExtraction = new HashSet<string> (StringComparer.OrdinalIgnoreCase);
bool metaDataValue;
foreach (var asm in Assemblies) {
if (bool.TryParse (asm.GetMetadata …
=> [Xamarin.Android.Build.Tasks] remove Distinct() from <ResolveLibraryProjectImports/>

src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
We will redistribute `as`, `ld` and `strip` tools and point AOT compiler to
these.
For AOT/llvm we still depend on NDK.
=> [aot] Make it possible to use AOT compiler without NDK

build-tools/xaprepare/xaprepare/Application/Utilities.Unix.cs, build-tools/xaprepare/xaprepare/Application/Utilities.Windows.cs
Console will throw an exception when the cursor coordinates are out of range,
but we don't want to check whether left/top are less than the buffer
width/height, respectively, because that might throw as well, so we just catch
the possible exception.
On Unix it may happen when the windows were just being re-created (e.g. when
switching between monitors) and there's no reason to stop the app because of
this so just log the exception and move on.
=> [xaprepare] Don't throw when console cursor coords are incorrect

Configuration.props, build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/bundletool/bundletool.targets
Context: https://github.com/google/bundletool/releases/tag/0.10.0
Context: https://mvnrepository.com/artifact/com.android.tools.build/bundletool
`bundletool` has had a few releases lately, we should update the
version we are shipping with Xamarin.Android.
I also noticed we were shipping:
bundletool-all-0.8.0-jar
I think we could just use `bundletool.jar`. It would be useful to have
a static filename as versions change release to release. This matches
up with other things we ship, such as `r8.jar`.
You can query the version of `bundletool` with:
$ java -jar bundletool.jar version
0.10.0
So we don't need to encode the version in the filename.
=> [bundletool] bump to 0.10.0

src/Mono.Android/Test/Mono.Android-Test.Library/Mono.Android-Test.Library.csproj
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2819142
Context: https://github.com/xamarin/xamarin-android/commit/e9561076a8e8761002931b886991eb1616561864
When this additional test library was added in e956107 it did not import
our Configuration.props file which contains default paths to the Android
tooling that we provision. This recently caused a breakage when bumping
the TargetFrameworkVersion of this project to v10.0 and building against
a system install of XA, as the Android SDK path which was automatically
resolved did not contain an android-29/android.jar. Importing the
Configuration.props file should fix this build failure.
=> Import Configuration.props in Mono.Android-Test.Library

src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs
`AndroidClientHandler` has no way of accessing the `HttpClient.Timeout` property
in order to set the timeout value of *two* native http client
properties (connect and read timeouts) and so it uses two custom properties to
provide these values. So far, the values were set to 100s for the read timeout
and 120s for the connect timeout, which seemed to be a reasonable value for
their purposes. However, if a developer sets `HttpClient.Timeout` to a
value *larger* than our defaults, `AndroidClientHandler` values "win" and the
connection/read time out earlier. The workaround is to set "our" timeouts along
with the `HttpClient` one, but if the developer cannot do it, for any kind of
reasons (i.e. to avoid platform-specific code) then they are faced with an
annoying situation.
The real fix would …
=> Increase AndroidClientHandler timeouts

src/Xamarin.Android.Build.Tasks/Tasks/CheckForInvalidResourceFileNames.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
Some of our customers are generating `Resource` files
which have invalid file names (as far as aapt/aapt2 is
concerned). They use the `LogicalName` meta data to
provide the "Real" name that the build process should
use.
However when using `aapt2` our `CheckForInvalidResourceFileNames`
task was NOT using the `LogicalName` metadata. It was
just using the filename. This breaks their projects with
an
APT0000: Invalid file name: It must contain only [^a-zA-Z0-9_.-]+
or
APT0000: Invalid file name: It must contain only [^a-zA-Z0-9_.]+
We should really support this scenario since we allow the
use of `LogicalName` for resource files anyway.
This commit fixes that issue and adds a unit test.
=> [Xamarin.Andorid.Build.Tasks] Check if LogicalName is valid before check Resource File.

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/3314
Create a new Xamarin.Forms project using aapt2, you will encounter a
crash on startup for API 19 devices:
android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f080058
at android.content.res.Resources.loadDrawable(Resources.java:2096)
at android.content.res.Resources.getDrawable(Resources.java:700)
at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:360)
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:198)
at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawa …
=> [Xamarin.Android.Build.Tasks] fix for aapt2 and $(AndroidResgenArgs)

.external, Configuration.props, Makefile, build-tools/automation/azure-pipelines.yaml, build-tools/scripts/BuildEverything.mk, build-tools/xaprepare/xaprepare/Application/GeneratedMakeRulesFile.cs
Context: https://github.com/xamarin/monodroid/pull/1010
Partially reworks the inverted build so that variables imported from
'rules.mk' can be accessed externally. 
Improves commercial build support for new Android API levels.
Improves provisioning performance when building and testing on the
Azure Pipeline macOS hosted agent pools. We'll now use the Android
SDK components which are pre-installed on those machines, as most of
what we need is already present and this location should be less prone
to being cleaned up.
=> [build] Pass variables to monodroid and improve toolchain caching

build-tools/automation/azure-pipelines.yaml
Migrates this test stage off of on-prem hardware to the hosted VS 2019
Windows machines. The issues which previously required us to temporarily
use on-prem hardware should now be resolved.
=> [test] Use VS 2019 for Windows Designer tests

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Compile.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
Fixes #3083
`aapt2` can be inconsistent regarding its exit code and
writing errors to stderr. It turns out that there are
cases where only WARNINGS are written to stderr. In this
case the exit code is 0. However we can not rely on the
exit code only, since there have been cases where
the exit code is 0 but we have errors on stderr.
So what we need to do is parse the stderr output and look
for those `tags` which we know represent warnings. This is
so we can correctly classify those errors/warnings to make
sure we correctly report the issues.
=> [Xamarin.Android.Build.Tasks] Apk per ABI fails with TargetFrameworkVersion v7.1 and lower when Aapt2 is enabled

build-tools/create-pkg/create-pkg.targets
Context: https://github.com/xamarin/xamarin-macios/issues/6504
Context: https://github.com/xamarin/vsmac-xamarin-extensions/pull/245
This should allow our .pkg installer to execute on macOS Catalina.
=> [installer] Remove symlinks created in /Developer

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
We can get into a situation where we dont
support a new api level, BUT our tooling
installed it in the `platforms` folder of
the SDK.
This means we get the following warning
warning XA0102:  Not targeting the latest versions of Android; compatibility modes apply. Consider testing and updating this version. Consult the android.os.Build.VERSION_CODES javadoc for details. [OldTargetApi]
What we need to do in the test is ignore this
warning, IF we are in that particular situation.
=> [Xamarin.Android.Build.Tests] Fix Lint Warnings

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3336
@brendanzagaeski found a really weird bug:
1. Build a project with aapt2 with an invalid XML file.
2. Remove the file from the project, build again.
3. Add the file back, build a third time.
On step 3 & beyond, no build error is given--meaning *something* must
be out of date.
I was able to reproduce the problem in a test, and saw it only occurs
with aapt2.
The `_CompileResources` MSBuild target was skipped:
Skipping target "_CompileResources" because all output files are up-to-date with respect to the input files.
Input files: Resources\values\ids.xml;Resources\drawable-hdpi\Icon.png;Resources\drawable-mdpi\Icon.png;Resources\drawable-xhdpi\Icon.png;Resources\drawable-xxhdpi\Icon.png;Resources\drawable-xxxhdpi\Icon.png;Resources …
=> [Xamarin.Android.Build.Tasks] fix Inputs for aapt2

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets
Context #1240
As part of the build process MSBuild generates an
`AssemblyAttribute.cs` class, such as
MonoAndroid,Version=v9.0.AssemblyAttributes.cs
This is the file which adds the `TargetFrameworkAttribute`
to the assembly. While investigating #1240 I noticed that
`_GenerateJavaStubs` was ALWAYS running, even on
incremental builds with no changes. Digging into the build
logs, `CoreCompile` was running because it thought one
of the binding project assemblies was newer..?
Digging in a bit more and I found this in the Binding Library
build output on the `CoreCompile` target.
Input file "/var/folders/n_/vt_nzq1n04schx5yy2jgcgcw0000gn/T/MonoAndroid,Version=v9.0.AssemblyAttributes.cs" is newer than output file "obj/Release/Xamarin.Android.McwGen-Tests.pdb".
It turns out our binding targets …
=> [Xamarin.Android.Build.Tasks] Dont use a temp location for AssemblyAttribute.cs

src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/FilterAssembliesTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/3343
Context: https://github.com/xamarin/XamarinComponents/blob/54646f5c0bef9c618c700628bd1167768d7c9b4f/Android/Guava/source/Guava.ListenableFuture/Guava.ListenableFuture.csproj
We introduced a performance improvement in 5ec3e3ab that "classifies"
assemblies as Xamarin.Android assemblies or not. This allows us to
skip processing of NetStandard/BCL assemblies throughout the build.
Unfortunately, this Guava.ListenableFuture assembly is odd:
* No `[assembly: TargetFramework]` attribute at all
* No reference to `Mono.Android.dll`
The only "marker" is that it has a `.jar` file as an
`EmbeddedResource`, which is put there by `<EmbeddedJar/>`. Its
weirdness is related to it not having any C# code, and using SDK-style
projects.
The fix …
=> [Xamarin.Android.Build.Tasks] <FilterAssemblies/> should look for .jar files

src/Mono.Android/Test/Resources/layout/Main.axml, src/Mono.Android/Test/Xamarin.Android.RuntimeTests/MainActivity.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MarkJavaObjects.cs, tests/Runtime-MultiDex/Resources/layout/Main.axml
Fixes https://github.com/xamarin/xamarin-android/issues/3263
Looks like
https://github.com/xamarin/xamarin-android/commit/5b945abb2e1f0fe1a9ab6589993c970869c4a752
introduced a new regression, where in some cases we were not marking
the *Invoker type anymore, as [this line](https://github.com/xamarin/xamarin-android/commit/5b945abb2e1f0fe1a9ab6589993c970869c4a752#diff-144727b152107ec306fbe284bd5902e3L60)
is gone.
This is fixed by marking the *Invoker types in MarkJavaObjects step.
=> [linker] Make sure we mark *Invoker types

src/Xamarin.Android.Build.Tasks/Tasks/R8.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3370
Context: https://github.com/xamarin/xamarin-android/pull/3121
In 34ee4735, I introduced an incorrect warning if:
* `android:minSdkVersion` >= 21
* `$(AndroidEnableMultiDex)` is `True`
* `$(AndroidDexTool)` is `d8`
We need to check if any `@(MultiDexMainDexList)` files were present
before issuing the warning. r8 no longer supports custom
`multidex.keep` files in some cases, so this is what the `<R8/>`
MSBuild task is actually meant to warn about.
I also improved the warning message a bit.
=> [Xamarin.Android.Build.Tasks] fix false warning from r8

build-tools/conjure-xamarin-android-cecil/conjure-xamarin-android-cecil.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
Context: http://build.azdo.io/2882865
Context: https://github.com/jbevain/cecil/blob/ab5075b3a885ffd5bee5d347b79ce71aabeb32d1/Mono.Cecil.Cil/Symbols.cs#L957-L978
Two tests on Windows have been failing on master since 0c9f83b7:
Xamarin.Android.Build.Tests.BuildTest.BuildHasNoWarnings
Should have zero MSBuild warnings.
Expected: True
But was: False
The actual warning is:
(_GenerateJavaStubs target) ->
warning : Failed to read 'obj\Debug\android\assets\HelloWorld.dll' with debugging symbols. Retrying to load it without it. Error detail s are logged below. [C:\src\xamarin-android\samples\HelloWorld\HelloWorld.csproj]
warning : Mono.Cecil.Cil.SymbolsNotFoundException: No symbol found for file: obj\Debug\android\assets\HelloWorld.dll [C:\src\xamarin-an …
=> [xaprepare] correct strong name for Xamarin.Android.Cecil.*

src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
Fixes: http://work.azdo.io/917139
Context: https://github.com/NuGet/Home/wiki/NuGetizer-Core-Features
The NuGetizer 3000, was failing on Xamarin.Android 9.4 with:
The "FilterAssemblies" task was not given a value for the required parameter "DesignTimeBuild".
This tool runs a `GetPackageContents` MSBuild target that is defined
here:
https://github.com/NuGet/NuGet.Build.Packaging/blob/dev/src/Build/NuGet.Build.Packaging.Tasks/NuGet.Build.Packaging.targets#L201
Since this isn't a `Build` or a `Compile`, neither of these targets
will run:
* `_SetupDesignTimeBuildForBuild`
* `_SetupDesignTimeBuildForCompile`
I don't think we can make the `_AddAndroidCustomMetaData` MSBuild
target (that runs `<FilterAssemblies/>`) depend on either of these.
The simple fix is to just remove `[Required]` from the …
=> [Xamarin.Android.Build.Tasks] fix the NuGetizer 3000

Documentation/guides/app-bundles.md, Documentation/guides/extract-native-libraries.md, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/EnvironmentHelper.cs, src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/NativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/java-runtime/java/mono/android/MonoPackageManager.java, src/java-runtime/java/mono/android/Runtime.java, src/monodroid/jni/android-system.h, src/monodroid/jni/application_dso_stub.cc, src/monodroid/jni/mono_android_Runtime.h, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/xamarin-app.h, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/BuildTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3298
Context: https://github.com/xamarin/xamarin-android/issues/3298#issuecomment-509022428
We have discovered through our current preview of Android App Bundles
in 16.2: the state of `android:extractNativeLibs` with app bundles can
change on a per-device basis.
The comment from `bundletool`'s source code:
// If persistent app is not installable on external storage, only the split APKs targeting
// devices above Android M should be uncompressed. If the persistent app is installable on
// external storage only split APKs targeting device above Android P should be uncompressed (as
// uncompressed native libraries crashes with ASEC external storage and support for ASEC
// external storage is removed in Android P). Instant apps always …
=> Remove __XA_DSO_IN_APK in favor of runtime checks

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
Context: https://jenkins.mono-project.com/job/xamarin-android-pr-pipeline-release/1744/testReport/Xamarin.Android.Build.Tests.IncrementalBuildTest/InvalidAndroidResource/_True____Release/
`IncrementalBuildTest.InvalidAndroidResource` is sometimes failing on
Jenkins with:
Build should have succeeded.
Expected: True
If we set `ThrowOnBuildFailure` back to `True` before this assertion,
we will get a proper build log in the error message.
=> [tests] improve InvalidAndroidResource failure

.gitignore, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/Tasks/CopyIfChanged.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/CopyIfChangedTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
[Xamarin.Android.Build.Tasks] <CopyIfChanged/> should check size
Fixes: https://github.com/xamarin/xamarin-android/issues/2584
Building a project with two different `$(TargetFrameworkVersion)`:
msbuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.4
msbuild /t:Configuration=Release /p:TargetFrameworkVersion=v9.0
Results in a build error:
error MSB4018: The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void BatchStepSensor.BatchStepSensorFragment::OnSaveInstanceState(Android.OS.Bundle)' in assembly: 'BatchStepSensor.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.OS.BaseBundle::PutInt(System.String,System.Int32)
at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
at …
=> [Xamarin.Android.Build.Tasks] <CopyIfChanged/> should check size

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/3322
Enabling code analysis via `<RunCodeAnalysis>true</RunCodeAnalysis>`
results in a build error for `Release` configurations:
error MSB4018: The "LinkAssemblies" task failed unexpectedly.
error MSB4018: System.IO.FileNotFoundException: Could not load assembly 'DroidButton, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
error MSB4018: File name: 'DroidButton.dll'
error MSB4018:   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference, Mono.Cecil.ReaderParameters parameters) [0x00125] in <bf8d1485bd8b4cc8b07ee73dc73c2c6c>:0
error MSB4018:   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (System.String …
=> [Xamarin.Android.Build.Tasks] _LinkAssemblies ordering for code analysis

src/Xamarin.Android.Build.Tasks/Mono.Android/ApplicationAttribute.Partial.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3276
Context: https://developer.android.com/training/articles/security-config
A custom `Android.App.Application` subclass with the attribute:
[Application(NetworkSecurityConfig = "@xml/network_security_config")]
Causes the `<GenerateJavaStubs/>` MSBuild task to throw:
The "GenerateJavaStubs" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: fullName
at Mono.Cecil.AssemblyNameReference.Parse(String fullName)
at Xamarin.Android.Manifest.ManifestDocumentElement.ResolveType(String type, ICustomAttributeProvider provider, IAssemblyResolver resolver)
at Xamarin.Android.Manifest.ManifestDocumentElement1.<>c.<.cctor>b__25_12(Object value, ICustomAttributeProvider p, IAssemblyResolver r, Int32 v) …
=> [Xamarin.Android.Build.Tasks] support Application.NetworkSecurityConfig

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/XABuildPaths.cs
We are currently always running the tests in the
`bin\TestRelease\temp` directory. However it seems our
build system is restoring Nuget packages into
`bin\Test$(Configuration)\temp\packages`
As a reuslt for certain tests the Hint paths are no
longer valid and that causes the test to fail.
This commit changes the path to make use of the
`$(Configuration)` so we end up using the correct
output path for the tests.
=> [Xamarin.Android.Build.Tests] Run tests in the right directory.

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Import.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
Context: http://build.azdo.io/2910500
The `CustomDesignerTargetSetupDependenciesForDesigner` test has been
failing randomly with:
_UpdateAndroidResgen should have been skipped.
Expected: True
But was: False
When I look at the log, following the targets, the culprit seems to
be `_CompileResources`:
Building target "_CompileResources" completely.
Input file "/Users/vsts/agent/2.155.1/work/1/s/bin/TestRelease/temp/SetupDependenciesForDesigner/UnnamedProject/foo.targets" is newer than output file "obj/Debug/flata/_CompileResources.stamp".
This test uses a `foo.targets` to customize the MSBuild logic:
Imports = {
new Import ("foo.targets") {
TextContent = ...
},
When reviewing the source code in Xamarin.ProjectTools, it appears
that we were always saving any `<Import/>` elements -- because …
=> [Xamarin.ProjectTools] use Timestamp for <Import/>

Documentation/guides/BuildProcess.md
Context: https://gitter.im/xamarin/xamarin-android?at=5cd5928f0824230a77105cd5
Update the descriptions of `AndroidHttpClientHandlerType` and
`AndroidTlsProvider` in the BuildProcess guide to make it easier to tell
which values are the defaults and which property values correspond to
which names in the Visual Studio project property pages.
=> [docs] Clarify AndroidHttpClientHandlerType and AndroidTlsProvider defaults

src/Xamarin.Android.Build.Tasks/Tasks/GetAdditionalResourcesFromAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ResolveMonoAndroidSdksTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/xamarin-android/pull/3402
When reviewing #3402, we found two things that seem wrong™:
* A case where `AndroidNdkDirectory` in the
`<GetAdditionalResourcesFromAssemblies/>` MSBuild task, was
`[Required]`. How did that ever work?
* In cases where `$(AndroidNdkDirectory)` is blank, it appears to get
set to `\`. Ok that's how it worked...
The first fix was to just remove `[Required]`, I did not find any
other places this was incorrect. I also had to adjust
`<GetAdditionalResourcesFromAssemblies/>` to account for the value
being blank.
Then I revisited the pattern we have in the `_ResolveMonoAndroidSdks`
MSBuild target:
<CreateProperty Value="$(AppSettingsDirectory)">
<Output TaskParameter="Value" PropertyName="_AppSettingsDirectory"/>
</CreateProperty> …
=> [Xamarin.Android.Build.Tasks] fix for empty $(AndroidNdkDirectory)

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs, tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs
Context: http://build.azdo.io/2917852
We have seen a couple of intermittent issues in some deployment tests on
Azure Pipelines. I suspect these are emulator performance related, but
such failures are difficult to diagnose without logcat output.
MSBuild tests which assert on logcat output have been updated to ensure
that they write the output to a file. This file will automatically be
appended to the test result xml on failure for all tests which inherit
from `BaseTest`.
I've also bumped the default logcat monitoring timeout to 15 seconds to
allow us to be more lenient around slower startup times for emulators
running on Azure hosted pools.
=> [tests] Capture logcat output for all deploy tests

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
Taken from #1939.
Today when we are compiling a class deriving from `Java.Lang.Object` that implements an interface and we see a method that exists on the interface that isn't implemented on the class we inject an override method that throws an `AbstractMethodError` exception.
With Default Interface Members, we need to ignore members that are implemented on the interface and not generate an override.  This is done by restricting our generation to `abstract` methods.
Original context here: https://github.com/xamarin/xamarin-android/commit/f96fcf93e157472072576bcc0a8698302899e8cf
=> [Tuner] Don't generate AbstractMethodErrors for default interface methods

build-tools/xaprepare/xaprepare/OperatingSystems/Windows.cs
Before this change, setting a custom value for
`$(AndroidToolchainDirectory)` in a `Configuration.Override.props` file
without explicitly setting a corresponding value for
`$(JavaSdkDirectory)` would result in an error when running the
`Prepare` target on Windows:
TODO: Modify ProcessRunner to allow standard input writing and switch to it here
From: Xamarin.Android.Prepare.Step_Android_SDK_NDK.AcceptLicenses at C:\Source\xamarin-android\build-tools\xaprepare\xaprepare\Steps\Step_Android_SDK_NDK.cs(103,4)
EXEC : error : JAVA_HOME is set to an invalid directory: C:\Users\Windows User\android-toolchain\jdk
This is somewhat unexpected because `xaprepare` does successfully
install the JDK into the `$(AndroidToolchainDirectory)\jdk` directory
before this step.
To make this scenario a little …
=> [xaprepare] Use AndroidToolchainDirectory for default JavaHome

build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/Steps/Step_Get_Windows_Binutils.Unix.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs, src/Xamarin.Android.Build.Tasks/Tasks/CompileNativeAssembly.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
Context: http://build.azdo.io/2915201
Several of the AOT-related MSBuild tests are failing on Windows with:
[aot-compiler stderr] AOT of image C:\src\xamarin-android\bin\TestDebug\temp\BuildAotApplication_armeabi-v7a_False_True\obj\Release\android\assets\UnnamedProject.dll failed.
[aot-compiler stdout] Mono Ahead of Time compiler - compiling assembly C:\src\xamarin-android\bin\TestDebug\temp\BuildAotApplication_armeabi-v7a_False_True\obj\Release\android\assets\UnnamedProject.dll
[aot-compiler stdout] AOTID 748C00A1-04B7-4B7C-9935-5C7AB69FC5C9
[aot-compiler stdout] Compiled: 17/17
[aot-compiler stdout] Executing the native assembler: "C:\src\XAMARI~1\bin\Debug\lib\XAMARI~1.AND\xbuild\Xamarin\Android\arm-linux-androideabi-as"   -mfpu=vfp3 -o …
=> [Xamarin.Android.Build.Tasks] ndk binutils in subdirectory

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
Context: http://build.azdo.io/2915638
The `IncrementalBuildTest.InvalidAndroidResource` test has been
failing randomly with:
Resources/values/ids.xml(2): error APT0000: <item> must have a 'type' attribute.
Resources/values/ids.xml : error APT0000: file failed to compile.
This test has a few steps:
1. Build a project with the above error -- ignore the error
2. Remove the offending file, build again
3. Add the offending file back -- ignore the error
It looks like on step No. 2 that the `.csproj` file for some reason is
not having a timestamp that would trigger this target:
Target Name=_GenerateAndroidResourceDir Project=UnnamedProject.csproj
Skipping target "_GenerateAndroidResourceDir" because all output files are up-to-date with respect to the input files.
Normally, this target runs …
=> [tests] SetLastWriteTimeUtc in InvalidAndroidResource test

src/r8/build.gradle
Context: https://discuss.gradle.org/t/duplicated-classes-output-jar-with-gradle/17301/2
Context: https://docs.gradle.org/current/javadoc/org/gradle/api/file/DuplicatesStrategy.html
Some internal Microsoft tooling was giving us a failure about `r8.jar`:
jarsigner: unable to sign jar: java.util.zip.ZipException: duplicate entry: module-info.class
Indeed there were duplicates:
7z l .\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\r8.jar | Select-String module-info.class
2018-08-05 07:07:30 .....          275          171  module-info.class
2018-08-05 07:07:40 .....          269          166  module-info.class
2018-08-05 07:07:24 .....          192          140  module-info.class
2018-08-05 07:07:18 .....          192          143  module-info.class
It looks like all we need is a …
=> [r8] prevent duplicate files in the output jar

build-tools/automation/azure-pipelines.yaml, build-tools/scripts/TestApks.targets, build-tools/xaprepare/xaprepare/ConfigAndData/Runtimes.cs, tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.csproj, tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.projitems, tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.targets, tests/TestRunner.Core/TestInstrumentation.cs, tests/TestRunner.Core/TestRunner.cs, tests/TestRunner.NUnit/NUnitTestInstrumentation.cs, tests/TestRunner.xUnit/XUnitTestInstrumentation.cs, tests/TestRunner.xUnit/XUnitTestRunner.cs
Adds a new job to build and run the BCL Test Suite on an emulator.
=> [tests/ci] Add BCL Test job to Azure pipelines

build-tools/automation/CredScanSuppressions.json, build-tools/automation/azure-pipelines.yaml
Context: https://secdevtools.azurewebsites.net/
Context: https://github.com/xamarin/yaml-templates/pull/23
Adds a job which will run static analysis tools and report any issues or
warnings found as a build artifact titled 'CodeAnalysisLogs'. Currently
only the 'CredScan' tool is supported.
=> [ci] Add Code Analysis Job to azure-pipelines.yaml

build-tools/xaprepare/xaprepare/Steps/Step_GenerateFiles.cs
Commit c37c40c did not apply cleanly, it looks like a removal was missed
due to conflict.
=> [build] Fix the xaprepare build

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/SystemUnzip.cs, build-tools/xaprepare/xaprepare/Application/Utilities.cs, src/Xamarin.Android.Build.Tasks/Tasks/ConvertCustomView.cs, src/Xamarin.Android.Build.Tasks/Tasks/Crunch.cs, src/Xamarin.Android.Build.Tasks/Tasks/MergeResources.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/CopyIfChangedTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/FilesTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/Files.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, tools/msbuild-fuzzer/Program.cs
A simple C# code change could break our build:
class Foo : Java.Lang.Object { }
Changed to:
class fOO : Java.Lang.Object { }
`javac` will fail on Windows (and likely macOS if you have a case
insensitive file system) with:
obj\Debug\android\src\md54a1bd985b0effc3cb8b7fa6ec8bb4028\Foo.java(4,8):  error: class fOO is public, should be declared in a file named fOO.java
public class fOO
The only way to get the project working again is to do a `Clean` or
`Rebuild`.
This C# snippet illustrates the issue further:
File.WriteAllText("Foo.txt", "Foo");
File.WriteAllText("fOO.txt", "fOO");
foreach (var file in Directory.GetFiles (".", "*.txt"))
{
Console.WriteLine(file + " -> " + File.ReadAllText (file));
}
The output is:
.\Foo.txt -> fOO
The only solution is to put a `File.Delete()` prior to the …
=> [Xamarin.Android.Build.Tasks] fixes for case-insensitive FS

Documentation/guides/messages/javac0000.md, src/Xamarin.Android.Build.Tasks/Tasks/JavaToolTask.cs, src/Xamarin.Android.Build.Tasks/Tasks/Javac.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
For tracking "deletebinobj" progress, we wanted to make sure we have
proper error codes for any failure that would be symptomatic of a
"deletebinobj" problem.
`javac` failing is one place that developers can't easily cause a
build failure without using `AndroidJavaSource`. If we get a
`JAVAC0000`, likely something went wrong with the Xamarin.Android
build system.
I also fixed up the test that was checking these error messages: it
was using `StringAssertEx.Contains` that calls `Assert.Pass`: some of
the assertions at the end of the test were skipped.
=> [Xamarin.Android.Build.Tasks] JAVAC0000 error code

build-tools/create-pkg/create-pkg.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/3457
Context: https://github.com/xamarin/xamarin-android/commit/e83ba0ddc159d15abcfac1a5a4bce5a53e165d3f
During the installer rework in e83ba0d, some symlinks which we thought
were no longer needed were removed. It turns out AppCenter (and perhaps
others) were relying on these symlinks in order to facilitate swapping
between multiple versions of Xamarin.Android installed side by side.
These changes bring back 'unofficial' support for this Side by Side
installation scenario by restoring legacy symlink behavior.
=> [create-pkg] Restore partial Side by Side support

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3373
A certain situation was causing `armeabi` to be treated as a valid ABI
for native libraries:
* Using a NuGet package that includes an `armeabi` .so file.
* Some directory has a name of a *valid* abi, such as
`$(IntermediateOutputPath)` set to `obj\Debug\x86`.
`MonoAndroidHelper.GetNativeLibraryAbi` was looking at all directory
names -- and so if `x86` was in the path at all, `armeabi/libfoo.so`
will be used throughout the build.
I reworked `GetNativeLibraryAbi` so that it only looks at the topmost
directory that contains the `.so` file. I also added a test for this
scenario.
=> [Xamarin.Android.Build.Tasks] fix a case where armeabi is picked up

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
We have duplicate test for `CheckTargetFrameworkVersion`.
One which only tests a `Release` build and one which
tests both `Release` and `Debug`.
This commit removes the one that only tests the `Release`
build since it is redundant.
=> [Xamarin.Android.Build.Tests] Remove Duplicate Test

Documentation/guides/messages/README.md, Documentation/guides/messages/xa0003.md, Documentation/guides/messages/xa0004.md, src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/Aapt2Tests.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
Fixes #2023
The `versionCode` in the android manifest should be
an `int` value. It should fall within the range of
`0` to `2100000000`.
This commit adds some checks which will emit MSBuild errors
if we encounter an invalid `versionCode`. It also
adds some unit tests to test for decimal values and
the boundary conditions.
=> [Xamarin.Android.Build.Tasks] Validate the `android:versionCode`

build-tools/xaprepare/xaprepare/Application/Utilities.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3439
Set the web request timeout to 60 minutes. It should make failures similar to
the one above less probable.
=> [xaprepare] Use longer web request timeouts for downloads

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/mac/setup-test-environment.yaml, build-tools/automation/yaml-templates/run-installer.yaml, build-tools/automation/yaml-templates/upload-results.yaml
Adds a template to be used for publishing build status and test result
zip file artifacts to reduce code duplication.
Moves artifact downloading to run-installer.yaml
=> [ci] Reduce YAML code duplication

src/Mono.Android/Android.Media/AudioRecord.cs, src/Mono.Android/Android.Media/AudioTrack.cs, src/Mono.Android/Mono.Android.csproj, src/Mono.Android/metadata
Starting on Api 29, Changing metadata to not remove AudioRecord interfaces anymore
Adding RoutingChangedEventArgs class back to AudioRecord and AudioTrack via partial class
Issue: https://github.com/xamarin/xamarin-android/issues/3313
=> Changing metadata to not remove AudioRecord interfaces

tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.projitems
Restores the instrumentation timeout for the NUnit set of BCL tests to
60 minutes, which was the previous timeout value prior to commit 3d9b154.
=> [tests] Bump NUnit BCL Test timeout to 1 hour

build-tools/automation/azure-pipelines.yaml, build-tools/create-pkg/create-pkg.targets, build-tools/create-pkg/runtime-entitlements.plist, build-tools/create-pkg/scripts/postinstall, build-tools/installers/create-installers.targets
Context: https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution
Context: https://github.com/android-ndk/ndk/issues/1060
Starting in macOS Catalina, our .pkg files will need to Notarized to
ensure that a Gatekeeper dialog is not displayed when we first attempt
to install them.
Notarization has the following requirements:
* All executables being distributed must be code-signed.
* A secure timestamp must be added to the code-signing signature.
* All relevant executables must have the Hardened Runtime enabled.
* All relevant executables must be built against macOS 10.9 or later.
To meet these requirements, code-signing and runtime Hardening have now
been enabled for all relevant installer files that we're building or
extracting from the mono archive. New …
=> [build] Add code-signing required for Notarization

Documentation/guides/messages/xa5301.md, src/Xamarin.Android.Build.Tasks/Generator/Generator.cs, src/Xamarin.Android.Build.Tasks/Tasks/RemoveDirFixed.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/MaxPathTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/RemoveDirTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/FilesTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.Shared.projitems, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, src/Xamarin.Android.Build.Tasks/Utilities/Files.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/2848
Context: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation
Context: https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/
A #deletebinobj problem has surfaced related to `MAX_PATH`. We have a
discrepancy of path length between:
* `obj\Debug\android\src` - where we generate `.java` source code
* `obj\Debug\android\bin\classes` - `javac` compiles `.class` files
If you have a project on the edge, where `android\src` does *not* have
a long path, but `android\bin\classes` *does*, we get the issue here:
error MSB3231: Unable to remove directory "obj\Debug\90\android\bin\classes".
Could not find a part of the path …
=> [Xamarin.Android.Build.Tasks] improve MAX_PATH errors

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Linux.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.MacOS.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Unix.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Windows.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
Context: https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/change-log.html#changes-2019-07-16
New upstream release fixes a number of security issues:
* [CVE-2019-7317](https://www.cvedetails.com/cve/CVE-2019-7317)
* [CVE-2019-2842](https://www.cvedetails.com/cve/CVE-2019-2842)
* [CVE-2019-2766](https://www.cvedetails.com/cve/CVE-2019-2766)
* [CVE-2019-2816](https://www.cvedetails.com/cve/CVE-2019-2816)
* [CVE-2019-2745](https://www.cvedetails.com/cve/CVE-2019-2745)
* [CVE-2019-2786](https://www.cvedetails.com/cve/CVE-2019-2786)
* [CVE-2019-2762](https://www.cvedetails.com/cve/CVE-2019-2762)
* [CVE-2019-2769](https://www.cvedetails.com/cve/CVE-2019-2769)
Windows bumps to a different version of Corretto because of trivial and cosmetic
changes that were specific only to Windows OS.
=> [xaprepare] Bump OpenJDK Corretto version

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/3494
In VS 2019 16.2 on Windows, I was able to reproduce a #deletebinobj
bug:
1. Create a new Xamarin.Android app
2. Open a layout file
3. Quickly type one letter and hit Ctrl+B
For me it took a couple tries sometimes, but I could eventually get an
error such as:
Aapt2Link
Assembly = C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Build.Tasks.dll
...
Executing link --manifest C:\Users\jopepper\AppData\Local\Temp\aihofny3.f3q\manifest\AndroidManifest.xml --java C:\Users\jopepper\AppData\Local\Temp\aihofny3.f3q --custom-package com.companyname.app10 -R C:\Users\jopepper\source\repos\App10\App10\obj\Debug\90\flata\\compiled.flata --auto-add-overlay -I "C:\Program Files …
=> [Xamarin.Android.Build.Tasks] fix #deletebinobj bug with designer

Documentation/guides/messages/xa5302.md, src/Xamarin.Android.Build.Tasks/Tasks/WriteLockFile.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/xamarin-android/issues/3494#issuecomment-521256360
In the past, we have seen some cases where the IDE can run MSBuild on
the same project in parallel. This causes inexplicable failures
throughout Xamarin.Android's MSBuild targets.
If we generate a build warning indicating this is happening, we can
have insight release over release if this happens in the wild. We will
also have a visible warning recorded in customer build logs.
Basically, we should:
* Write a zero-byte "lock file" at the beginning of a build
* Warn if this file already exists
* Delete the file at the end of the current build
* Even if the build failed, was cancelled, etc.
This is simple and should work cross-platform, where a named `Mutex`
would only work on Windows.
To achieve this we …
=> [Xamarin.Android.Build.Tasks] XA5302 warning for parallel builds

build-tools/automation/azure-pipelines.yaml, build-tools/xaprepare/xaprepare/OperatingSystems/OS.cs, build-tools/xaprepare/xaprepare/OperatingSystems/Unix.cs, build-tools/xaprepare/xaprepare/OperatingSystems/Windows.cs, build-tools/xaprepare/xaprepare/Steps/Step_GenerateFiles.cs
We currently use this script to install the JDK and select a specific
version of Xcode, however these dependencies should no longer be needed.
We are already installing the Corretto JDK as part of xaprepare, and we
should no longer have a dependency on Xcode 9.2.
As of commit 08e0ccb4 `$(AndroidToolchainDirectory)` is set to
`$(HOME)/Library/Android` when executing on macOS Azure Pipelines hosts.
The `$(JAVA_HOME)` variable set during our core macOS build has been
updated to point to this path which will contain the Corretto JDK.
=> [ci] Remove monodroid provisionator script

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2942448&view=ms.vss-test-web.build-test-results-tab&runId=7928872&resultId=100035&paneView=debug
We have a specific test that times a design-time build and asserts
that it took less than a period of time.
It appears that in once instance the test taking too long, the
`Restore` target is what took a long time:
10765 ms  Restore                                    1 calls
We should explicitly NuGet restore *first*, and not include that in
the timing.
I think this will also allow us to just check that things are under
10s and not check `IsRunningOnHostedAzureAgent`.
=> [tests] AndroidUpdateResourcesTest timing should exclude Restore

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Designer.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs
Context: https://github.com/xamarin/xamarin-android/pull/3418
In the case of AndroidX, the Android designer was not getting returned
certain `.jar` files from the `GetExtraLibraryLocationsForDesigner`
MSBuild target.
This target has an output item group of `ExtraJarLocation`, such as:
<ExtraJarLocation Include="@(_AdditionalJavaLibraryReferences)">
<Source>AssemblyCache</Source>
</ExtraJarLocation>
<ExtraJarLocation Include="@(_LibraryJars)">
<Source>LibraryImport</Source>
</ExtraJarLocation>
It turns out that any instances of `@(AndroidJavaLibrary)` were not
accounted for.
`<ReadLibraryProjectImportsCache/>` only returns jar files that were
extracted in `_ResolveLibraryProjectImports`, such as:
* `.jar` files from `__AndroidLibraryProjects__.zip`
* `.jar` files that are …
=> [Xamarin.Android.Build.Tasks] designer targets missing @(AndroidJavaLibrary)

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/MacOS.cs
When running `make prepare` with `AutoProvision` set to true, the script installs mingw 6.0.0_2. When it detects that mingw is not installed, it will install version 6.0.0_2 and continue. The next time, it will detect 6.0.0_2 and complain about the version, unable to proceed.
=> Fix mingw dependency version constraint

Xamarin.Android.sln, build-tools/jnienv-gen/Generator.cs
Changes: https://github.com/xamarin/Java.Interop/compare/be581591d0a995c740600be3ceefd0c3351dd0dd...2abfc1e06a641a095acebe518f8f684efb36b3f1
Context: https://github.com/xamarin/java.interop/pull/459
Updates `generator` so that all bound Java interfaces also implement
`IJavaPeerable` in addition to `IJavaObject`, for eventual future
C#8 Default Interface Member support.
[generator] Remove extraneous slash when creating .projitems.
[generator] Always use XAPeerMembers for XAJavaInterop1
Drop dependency on DylibMono when building for Xamarin.Android
[jnienv-gen] fix p/invoke usage for .NET framework
Add `jnimarshalmethod-gen.exe -r ASSEMBLY` option.
=> Bump to xamarin/Java.Interop/master@2abfc1e0

build-tools/cmake/xa_macros.cmake, src/monodroid/CMakeLists.txt, src/monodroid/jni/android-system.cc, src/monodroid/jni/android-system.h, src/monodroid/jni/debug.cc, src/monodroid/jni/debug.h, src/monodroid/jni/embedded-assemblies.cc, src/monodroid/jni/host-config.h.in, src/monodroid/jni/jni-wrappers.h, src/monodroid/jni/logger.cc, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/monodroid-networkinfo.cc, src/monodroid/jni/new_delete.cc, src/monodroid/jni/osbridge.cc, src/monodroid/jni/util.cc, src/monodroid/jni/util.h, src/monodroid/jni/xamarin_getifaddrs.cc, src/monodroid/monodroid.props, src/monodroid/monodroid.targets
This commit adds a number of measures to try to detect potential issues in the
native C++ code in Xamarin.Android.
Firstly, it passes a number of warning flags to the C++ compiler to enable
diagnostics disabled by default related to type conversion (signed vs unsigned
integers), sign and unsigned types comparison, use of potentially uninitialized
variables, use of deprecated APIs. These flags are enabled ONLY for our code in
`src/monodroid` since we can't do much about e.g. sqlite code and enabling them
for 3rd party code would merely result in useless noise during the build which
could hide issues in our code.
Secondly, it adds an MSBuild target named `RunStaticAnalysis` in `src/monodroid`
to run the `clang-check` utility which analyzes source code for each target we
build and saves the …
=> Fix issues found by static analysis + compiler warnings

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/TestEnvironment.cs
The hosted pools we're using on Azure Pipelines no longer appear to have
'hosted' in the name. Updates the running on hosted check to look for
the new hosted pool agent naming schema, and adds a new variable check
to help make this more robust. Predefined Azure Pipeline variables can be
found here: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables
=> [tests/ci] Fix Azure Pipeline hosted detection

src/Xamarin.Android.Build.Tasks/Tasks/ConvertCustomView.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ConvertResourcesCasesTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3477
An issue was reported of an error such as:
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2315,3): error MSB4018: The "ConvertCustomView" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object
at Xamarin.Android.Tasks.ConvertCustomView+<>c__DisplayClass20_1.<Execute>b__0 (System.Diagnostics.TraceLevel level, System.String message) [0x0005b] in <35be9ecd0f44486bbcde5cb44c4d94c6>:0
at Xamarin.Android.Tasks.ConvertCustomView.TryFixCustomView (System.Xml.Linq.XElement elem, System.Collections.Generic.Dictionary`2[TKey,TValue] acwMap, System.Action`2[T1,T2] logMessage) [0x0006f] in <35be9ecd0f44486bbcde5cb44c4d94c6>:0
at …
=> [Xamarin.Android.Build.Tasks] fix NRE in <ConvertCustomView/>

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Extensions.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MarkJavaObjects.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs
Improves fix of https://github.com/xamarin/xamarin-android/issues/3263
The
https://github.com/xamarin/xamarin-android/commit/4d8c28f624b50a86b564b0bc6bdefb85ea822b69
fix increased the apk size more than needed. It marked all the
*Invoker types, beause MarkJavaObjects substep iterates over all
Java.Object derived types, before all the linking.
Turned out that the original regression came from the linker
itself. The new linker optimization was introduced in
https://github.com/mono/linker/commit/13ea1582e518f5f64cb93057aca962983e58e337
and so the ITextWatcher interface was not marked anymore.
Before the new optimization, the linker preserved these
ifaces (like `ITextWatcher`) when marking the types based on them
(like `AbsListView` or `ITextWatcherImplementor` in this case). That also …
=> [linker] Improve *Invoker types linking

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Linker.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/OutputStepWithTimestamps.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
I've removed various MSBuild targets that copy assemblies into the
`obj\Debug\linksrc` directory, and instead just use
`@(ResolvedUserAssemblies)` or `@(ResolvedAssemblies)` directly
Things seem to *work*, I can build and deploy `samples\HelloWorld` and
the Xamarin.Forms app in this repo. Let's see what breaks?
The size of `tests\Xamarin.Forms-Performance-Integration\Droid\obj\`
is improved dramatically:
Before:
184.27 MB
After:
111.74 MB
~73MB savings.
These MSBuild tasks were completely removed:
3 ms  _CopyMdbFiles                              1 calls
43 ms  _CopyPdbFiles                              1 calls
127 ms  _CopyIntermediateAssemblies                1 calls
On a slower machine with Windows Defender enabled, these targets are
taking:
6 ms  _CopyMdbFiles …
=> [Xamarin.Android.Build.Tasks] remove the linksrc directory

Before.Xamarin.Android.sln.targets, build-tools/scripts/ImportExportDocs.targets
Add a few helper MSBuild targets to facilitate copying documents in the
xamarin-android repository to and from the corresponding files in the
MicrosoftDocs/xamarin-docs and MicrosoftDocs/xamarin-engineering-docs-pr
repositories.
For example, to update content from xamarin-android into a local
checkout of the xamarin-docs repository, run a command like:
msbuild -t:ExportXamarinDocs -p:XamarinDocsPath=/path/to/xamarin-docs/ Xamarin.Android.sln
The `ExportXamarinDocs` target currently only copies the
`Documentation/guides/BuildProcess.md` guide.
Similarly, to update content from the xamarin-android into a local
checkout of the xamarin-engineering-docs-pr repository, run a command
like:
msbuild -t:ExportXamarinEngineeringDocs -p:XamarinEngineeringDocsPath=/path/to/xamarin-engineering-docs-pr/ …
=> [docs] Add doc import and export MSBuild targets

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/xamarin-android/commit/cca5b65c338c8685e0c52070f2cf5f89e337515a
Context: https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution/customizing_the_notarization_workflow#3087734
Starting in macOS Catalina, our `.pkg` files will need to Notarized
to ensure that a Gatekeeper dialog is not displayed by the installer.
Our `.pkg` files are able to be Notarized as of commit cca5b65, so we
can now add a step for Notarization and Stapling to our non PR builds.
=> Add notarization to the Xamarin Android pipeline (#3536)

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/AndroidResourceTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/969915
Certain android resource items can make use of the following
namespace
xmlns:app=""http://schemas.android.com/apk/res-auto""
this provides additional extension attributes which need
to be fixed up. Some examples are `actionLayout`, `rectLayout`
and `roundLayout`. The values for these attributes should
be lowercased as they refer to a `@layout` item.
It seems however that this list is always expanding. A new
item `headerLayout` seems to have appeared. Rather than handcoding
each of these items, the code here changes to check for `Layout`
in the attrbiute and will then lowercase the value. This should
protect us from future "additions", and help our customers since
they won't have to work around casing problems for …
=> [Xamarin.Android.Build.Task] Handle res-auto headerLayout

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Extensions.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs
Check whether the interface type is based on `IJavaObject` or
`IJavaPeerable` when deciding if the iface should be marked without
further linker analysis.
@jonp suggested that idea during review of
https://github.com/xamarin/xamarin-android/pull/3525
I have tried the change with Topeka sample to make sure we don't break
the java ifaces linking again. The size stays the same. The set of
interfaces for which we return *true* in
`ShouldMarkInterfaceImplementation` is the same with the exception of
`IJavaObject` and `IJavaPeerable`. These would be preserved anyway.
=> [linker] Simplify java ifaces detection

build-tools/automation/azure-pipelines.yaml
Context: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#dependencies
We shouldn't run the vsix sign job if any failures occurred in the build
before it. We also shouldn't run notarization and upload to storage steps
if any failures occur in our build.
=> [ci] Fix vsix sign job and other conditions

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Designer.targets, src/Xamarin.Android.Build.Tasks/Tasks/Javac.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
I was reviewing MSBuild logs inside the IDE when using the Android
designer and noticed something odd:
Building target "_CompileToDalvikWithDx" completely.
Input file "obj\Debug\android\bin\classes.zip" is newer than output file "obj\Debug\stamp\_CompileToDalvik.stamp".
It appears that editing an Android layout was causing
`_CompileToDalvikWithDx` to run again?
Then I looked at the build log from `SetupDependenciesForDesigner`:
Building target "SetupDependenciesForDesigner" completely.
Output file "obj\Debug\android\bin\classes\mono\MonoPackageManager.class" does not exist.
Ok, we no longer generate `MonoPackageManager.class`. It is included
as part of `java-runtime.jar`.
Looking closer, the `Inputs` and `Outputs` did not seem right for
`SetupDependenciesForDesigner`: …
=> [Xamarin.Android.Build.Tasks] improve incremental builds + designer

src/Mono.Android/Android.Runtime/OutputStreamInvoker.cs
From #3498:
When writing to Google Drive using `Application.Context.ContentResolver.OpenOutputStream` the content is not actually written.  This method returns an `Android.Runtime.OutputStreamInvoker` that wraps the `Java.IO.OutputStream`.  However the Invoker does not override `Close ()` so the base stream does not get closed.
This does not seem to be an issue when writing a file locally but causes 0 bytes to get written to Google Drive.  (Likely due to buffering.)
The `KitKat` project in `monodroid-samples` can be used as a repro:
https://github.com/xamarin/monodroid-samples/tree/master/KitKat
* Run project
* Click Storage Access Framework
* Click Create new document
* Choose Google Drive as the target
* Hit Save
Without this change the file contains 0 bytes.  With this change the file …
=> [Mono.Android] Close BaseOutputStream when OutputStreamInvoker.Close is called

Makefile, build-tools/automation/build.groovy, tests/RunApkTests.targets
As we slowly migrate to Azure DevOps, there are some duplicate phases
we are running on Jenkins that mostly produce noise, such as:
* MSBuild Tests - we commonly get failures related to NuGet
* BCL Tests - enough said...
* Networking-related issues on APK-based tests
For now we could replace the call:
make run-all-tests
To run a subset:
make run-performance-tests
This will keep the existing plots we have working. OSS contributors
will still have access to builds, etc.
=> [Jenkins] remove some duplicate test phases

Documentation/guides/BuildProcess.md, src/Xamarin.Android.Build.Tasks/Tasks/AndroidApkSigner.cs, src/Xamarin.Android.Build.Tasks/Tasks/AndroidSignPackage.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Fixes #3513
Both `jarsigner` and `apksigner` provide a way to use both
files and environment variables for the store and key passwords.
For `jarsigner` you have to suffix the parameter switch with either
`:env` or `:file` to use those options. For `apksigner` you have
to prefix the value with either `:env`, `:file` or `:pass`.
We currently only support raw passwords.
This commit adds support for using both `env:` and `file:` for
signing. When providing values for the MSBuild properties
such as `AndroidSigningStorePass` and `AndroidSigningKeyPass` all
they need to do is prefix the value with `env:` or `file:` to
use the alternative parameters.
/p:AndroidSigningKeyPass=env:MyPasswordEnvVar
/p:AndroidSigningKeyPass=file:PathToPasswordFile
This will stop passwords appearing in build logs etc.
=> [Xamarin.Android.Build.Tasks] Add EnvVar and File support for Signing APKs

build-tools/automation/build.linux.groovy, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/Linux.DebianCommon.cs
On ubuntu 18.04 (LTS) we are unable to install/find libncurses-dev, instead it uses libncurses5-dev
=> Update Linux.DebianCommon.cs to look for libncurses5-dev 

build-tools/automation/azure-pipelines.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/MaxPathTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/RemoveDirTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/FilesTests.cs
Context: http://build.azdo.io/2971289
Our `MaxPathTests` seem to be failing on a specific build machine:
`DDMBLDW137`. I suspect this machine has long paths enabled.
I added a check that attempts to write a long path, and if it succeeds
we can `Assert.Ignore` these tests appropriately.
=> [tests] add checks if long paths supported

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.DefaultOutputPaths.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/MSBuildSdkExtrasTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.Shared.projitems, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/MSBuildSdkExtrasProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidLibraryProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetStandard.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj, tools/xabuild/XABuild.cs, tools/xabuild/XABuildPaths.cs
Context: https://github.com/onovotny/MSBuildSdkExtras
Context: https://www.nuget.org/packages/MSBuild.Sdk.Extras/
Today, you can create an SDK-style project such as:
<Project Sdk="Microsoft.NET.Sdk">
<TargetFramework>netstandard2.0</TargetFramework>
</Project>
If you want to "multi-target", you can take advantage of
MSBuild.Sdk.Extras, such as:
<Project Sdk="MSBuild.Sdk.Extras/2.0.41">
<TargetFrameworks>netstandard2.0;MonoAndroid90</TargetFrameworks>
</Project>
This imports `Xamarin.Android.CSharp.targets` on top of the SDK-style
MSBuild targets. `MSBuild.Sdk.Extras` is a community-led project.
During a build both will be produced:
* `bin\Debug\netstandard2.0\foo.dll`
* `bin\Debug\monoandroid90\90\foo.dll` - *NOTE* this …
=> [Xamarin.Android.Build.Tasks] tests for MSBuild.Sdk.Extras

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
When testing performance, I found an issue with `_GenerateJavaStubs`:
1. Change `MainActivity.cs` in an Android app project and hit F5.
2. The `Build` runs `_GenerateJavaStubs`
3. The `Install` runs `_GenerateJavaStubs`
4. Any subsequent build (even with no changes) will run
`_GenerateJavaStubs`...
The log reads:
Building target "_GenerateJavaStubs" completely.
Input file "obj\Debug\90\android\assets\App14.dll" is newer than output file "obj\Debug\90\android\typemap.jm.arm64-v8a.s".
In 74cf0ec9, we modified the `Outputs` to be:
Outputs="$(_AndroidStampDirectory)_GenerateJavaStubs.stamp;@(_TypeMapAssemblySource)"
This would be OK, except in some cases we don't update this file:
MonoAndroidHelper.CopyIfStreamChanged (ms, asmFileName);
If `_GenerateJavaStubs` runs, but the typemap doesn't …
=> [Xamarin.Android.Build.Tasks] fix incremental builds w/ native assembler

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/mac/setup-test-environment.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, src/java-runtime/java-runtime.targets
We've been encountering a handful of issues recently with the Windows
machine pool we're using for building and testing. There have been quite
a few failures caused by files being locked, or dependencies being out
of date or missing. Moving to the VSEng VS2019 Windows pool will
hopefully resolve some of these issues.
Unfortunately the size of our build dependencies presents an issue when
attempting to use the Microsoft hosted Windows VS2019 agents, as our Win
job ultimately runs out of space when executing on those VMS. Using the
VSEng VS2019 pool will allow us to migrate to VS2019 while avoiding disk
space limitations.
As of commit 8cdda11, `$(JavaSdkDirectory)` will have a default value
of the path to the Corretto JDK we install on both Windows and macOS.
We should try to use this JDK …
=> [ci] Move Windows build and test to VS2019

build-tools/xaprepare/xaprepare/Application/Context.cs, build-tools/xaprepare/xaprepare/Application/KnownProperties.cs, build-tools/xaprepare/xaprepare/Application/MonoPkgProgram.MacOS.cs, build-tools/xaprepare/xaprepare/Application/Properties.Defaults.cs.in, build-tools/xaprepare/xaprepare/Main.cs
The xamarin-android build prefers that the system mono be the same
version as the bundled mono.  As `.external` is currently referencing
the mono/2019-06 branch, this suggests use of system mono 6.4.0.
Meanwhile, the current *stable* version of Xamarin.Android --
Xamarin.Android 9.4.0 (d16-2) at the time of this writing -- is using
mono/2019-02 (mono 6.0.0).
Consequently, if a stable version of mono is installed, the
xamarin-android repo cannot be built unless system mono is updated:
$ make prepare
...
Checking Mono                                        [WRONG VERSION 6.0.0.311]
Error: Some programs are missing or have invalid versions, but automatic provisioning is disabled
Error: Failed to initialize OS support
make: *** [prepare] Error 1
Add an `xaprepare.exe …
=> [xaprepare] Add `xaprepare.exe --ignore-min-mono-version=true`

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
Context: http://build.azdo.io/2989026
We have seen test failures such as:
Xamarin.Android.Build.Tests.IncrementalBuildTest.ConvertCustomView(True)
Xamarin.Android.Build.Tests.IncrementalBuildTest.ConvertCustomView(False)
They both get a build error such as:
/Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/NuGet.targets(121,5):
error : The file '/Users/vsts/.nuget/packages/netstandard.library/2.0.3/.nupkg.metadata' already exists.
I think this a general bug when using `/t:Restore` or `/restore` with
an SDK-style project on Mac in parallel. I saw a similar issue when
writing the `MSBuildSdkExtrasTests`.
For now `[NonParallelizable]` should solve the issue.
=> [tests] add [NonParallelizable] to ConvertCustomView

Documentation/guides/BuildProcess.md, src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs, src/Xamarin.Android.Build.Tasks/Tasks/CompileNativeAssembly.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkApplicationSharedLibraries.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/3564
Adds an overridable `$(AndroidBinUtilsDirectory)` property which is used
to specify the directory that contains `as`, `ld`, and `strip` tools.
The default value for this property is the installation path of our
distribution of these tools, `$(MonoAndroidBinDirectory)\ndk\`.
Fixes #3564 by ensuring that we use the 64bit version of `ld` that we're
distributing, rather than the 32bit version found in the Android SDK.
Bad:
Task Parameter:AndroidSdkBuildToolsPath=/Users/user/Library/Developer/Xamarin/android-sdk-macosx/build-tools/28.0.3/
[Native Linker] /Users/user/Library/Developer/Xamarin/android-sdk-macosx/build-tools/28.0.3/aarch64-linux-android-ld --unresolved-symbols=ignore-in-shared-libs --export-dynamic -soname …
=> [XA.Build.Tasks] Add AndroidBinUtilsDirectory prop

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Our AOT system has issues when a user uses
non ASCII characters and spaces on Windows.
We use `GetShortPath` to get the old DOS
8.3 short names of paths to get around
paths having spaces and unicode characters.
However on the latest versions of windows
`GetShortPath` seems to be supported only
on the main system drive (C:). Many of our
developers and CI will be building on other
drives. So we really need to support paths
with spaces and unicode.
This commit reworks the way we provide the
`--aot` pargument to the cross compilers so
that it actually works in those senarios.
The first thing was how the arguments were
parsed. `mono` uses the build in system
command line parser `GetCommandLineW` to parse
arguments. Given the following `--aot` argument …
=> [Xamarin.Android.Build.Tasks] Response file support for AOT

src/monodroid/jni/android-system.cc, src/monodroid/jni/basic-android-system.cc, src/monodroid/jni/debug-app-helper.cc, src/monodroid/jni/debug.hh, src/monodroid/jni/embedded-assemblies.cc, src/monodroid/jni/embedded-assemblies.hh, src/monodroid/jni/jni-wrappers.hh, src/monodroid/jni/logger.cc, src/monodroid/jni/monodroid-glue-internal.hh, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/osbridge.hh, src/monodroid/jni/util.cc, src/monodroid/jni/util.hh
A small cleanup which deals with a handful of remaining warnings after enable
more extensive diagnostics in our compilers.
Deal with `read(2)` definition differences between Android+Unix compilers and
MinGW (on *nix the third argument, `count`, is defined to be of type `size_t`
while on MinGW it's `unsigned int` which caused an integer conversion warning
when building for Windows)
Take advantage of the C++17 `if constexpr ()` construct (works similar to the
preprocessor `#if{n}def` but is part of the language standard and is type-safe)
as well as the more compact (and less of an eyesore) namespace declaration,
instead of:
```cpp
namespace xamarin { namespace android { namespace internal
```
we can now use
```cpp
namespace xamarin::android::internal
```
C++17 allows one to declare and …
=> More C++ warnings cleanup + C++17 changes

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes https://github.com/xamarin/xamarin-android/issues/3547
When building in release mode if the user has `AndroidKeyStore` set
we should not try to create the debug.keystore. This is causing
problems on CI systems since sometimes the CI job is running
as a `system` account. Mostly around writting to the system
profile directory `C:\Windows\system32\config\systemprofile\AppData`.
=> [Xamarin.Android.Build.Tasks] Dont create debug.keystore if we don't need to.

.external
Changes: https://github.com/xamarin/monodroid/compare/60d4bd47cd90744535d7040a4726241a6b04a467...6f1e0752acdd8ffd250793b84a9c8bc99fa642c8
$ git diff --shortstat 60d4bd47..6f1e0752
3 files changed, 9 insertions(+), 2 deletions(-)
Changes: https://github.com/xamarin/androidtools/compare/8bda6e8184999c85100f710b37452c45f925d6d7...47d0bcb5df91b8f29c1ff36675b481e1b543f1de
Fixes the random XA5300 error seen on our CI builds!
=> Bump to xamarin/monodroid/d16-4@6f1e0752

Documentation/guides/MSBuildBestPractices.md, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildOutput.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
If I time an incremental build of a "Hello World" Xamarin.Forms app,
one of the last remaining areas to improve is:
340 ms  LinkAssemblies                             1 calls
In this build, I made a one-line change in a XAML file in a
NetStandard project with the optimal settings such as
`$(ProduceReferenceAssembly)`.
On a slower PC I have with Windows defender enabled, this step can
take even longer:
767 ms  LinkAssemblies                             1 calls
Part of the reason for the time taken is the linker needs to load
*every* assembly, even if not every assembly is actually changed or
saved.
A `Debug` build (or `$(AndroidLinkMode)` = `None`) only needs to run a
single linker step:
var pipeline = new Pipeline ();
if (options.LinkNone) {
pipeline.AppendStep (new FixAbstractMethodsStep …
=> [Xamarin.Android.Build.Tasks] fully incremental linker for Debug builds

Documentation/README.md, Documentation/guides/profiling.md
I recently found the Xamarin Profiler / GUI wasn't really suitable for
profiling Xamarin.Android startup on devices.
This is basically a brain dump of every way I have found to get
different timing information.
It should be useful in timing such things as Xamarin.Forms startup,
etc.
=> [docs] document different ways to profile startup

build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/Aapt2Tests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Commit 4ccbeb74 began the process of splitting up the
`aapt2` calls into its own targets. This will help
make the product easier to maintain since the Targets
are in their own .target files.
This commit builds on that and moves the old `aapt` calls
into their own targets. We also split out the remaining
`aapt2` based calls from `_CreateBaseApk` and `_UpdateAndroidResgen`
into the `Xamarin.Android.Aapt2.targets`.
Turns out `CallTarget` does NOT include any locally
created Properties or ItemGroups so we need to
split those out into new `_Prepare*` targets to
make sure they are defined before we call the
various `CallTarget`s. For more info on the MSbuild issue
see https://github.com/Microsoft/msbuild/issues/1006
=> [Xamarin.Android.Build.Tasks] Split out Aapt into its own Targets

src/Xamarin.Android.Build.Tasks/Tasks/PrepareWearApplicationFiles.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/WearTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.Shared.projitems, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidWearApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetXamarinProject.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/3562
Our QA tests caught a regression where building a Xamarin.Android app
that includes an embedded Android Wear app would always rebuild.
This brought up a few things:
1. We have a `XamarinAndroidWearApplicationProject` class, but no
tests using it?
2. What does our MSBuild targets even do for Wear projects?
In adding some tests, I had to fix a few other things:
* We should use the 1.0.0 Xamarin.Android.Wearable NuGet instead of
`preview7`.
* `Xamarin.ProjectTools` was generating `csproj` files of an encoding
that did not match:
```
Xamarin.Android.Common.targets(423,2): error MSB4018: The "ParseAndroidWearProjectAndManifest" task failed unexpectedly.
System.Xml.XmlException: There is no Unicode byte order mark. Cannot switch to …
```
=> [Xamarin.Android.Build.Tasks] fix Android Wear incremental builds

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
Error messages taken from https://gist.github.com/grendello/72c1ce5f6e8cdd3aefd393b983576d9a.
Created by grepping the `aapt` source for `error`.
=> [Xamarin.Android.Build.Tasks] Parse AAPT errors so every build error isn't APT0000

Documentation/release-notes/master.md, src/Xamarin.Android.Build.Tasks/Tasks/Generator.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets, tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/DimBindingTests.cs, tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Properties/AndroidManifest.xml, tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj, tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/Xamarin.Android.McwGen-Tests.csproj, tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/java/com/xamarin/android/DefaultMethodsInterface.java, tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/java/com/xamarin/android/EmptyOverrideClass.java, tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/java/com/xamarin/android/ImplementedChainOverrideClass.java, tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/java/com/xamarin/android/ImplementedOverrideClass.java, tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/java/com/xamarin/android/StaticMethodsInterface.java
Adds MSBuild support for DIM to Android Bindings projects.
To enable, add the following to a binding project:
```
<LangVersion>preview</LangVersion>
<_EnableInterfaceMembers>True</_EnableInterfaceMembers>
```
=> [Xamarin.Android.Build.Tasks] Add MSBuild support for DIM.

Documentation/guides/MSBuildBestPractices.md, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
In 5320c25a, I implemented a way for `_LinkAssembliesNoShrink` to
build partially.
However, I found a bug when testing out the new feature on a project
with existing `bin` and `obj` directories:
* `build.props` was updated because `$(XamarinAndroidVersion)` changed
* `_LinkAssembliesNoShrink` ran, but many of the files were not
actually copied, such as `FormsViewGroup.dll` from the Xamarin.Forms
NuGet package.
* Any subsequent build would always run `_LinkAssembliesNoShrink`
fully! Because `FormsViewGroup.dll` would eternally have an older
timestamp than `build.props`.
I was able to reproduce the problem with a new test.
The fix is to set the timestamp on copied assemblies, even if they
weren't actually copied. This way the `Inputs` and `Outputs` of
`_LinkAssembliesNoShrink` will always …
=> [Xamarin.Android.BuildTasks] fix for _LinkAssembliesNoShrink

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs, src/Xamarin.Android.Build.Tasks/Tasks/CheckForInvalidResourceFileNames.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
Context: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/735263
Context: https://android.googlesource.com/platform/frameworks/base/+/563abce4ed0a0d9f08f8839a8f15b548b3dcd4d1/tools/aapt
Context: https://gist.github.com/grendello/72c1ce5f6e8cdd3aefd393b983576d9a
Errors and warning *codes* for errors and warnings reported
*within Visual Studio* from developers participating in the
[Visual Studio Customer Experience Improvement Program][0] are
reported "telemetry" events, but *only* the error and warning codes
are reported.  The warning and error message contents are not sent.
Unfortunately all `aapt2`-related errors are reported as APT0000,
which reduces the utility of telemetry, making it more difficult to
better understand where our build system could be improved. …
=> [Xamarin.Android.Build.Tasks] Improve AAPT2 error granularity

src/Xamarin.Android.Build.Tasks/Tasks/BuildAppBundle.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/BundleToolTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3596
Context: https://github.com/google/bundletool/blob/2e9ac4e628a690c0fce402548fe90c747c86533c/src/main/proto/config.proto#L22-L25
We got report of `.resx` files not working with Android App Bundles.
Sure enough, when I tried the sample:
https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/usingresxlocalization/
I was not seeing Spanish localization when running the app...
So I pulled the app bundle from the device:
>  adb shell pm list packages -f | Select-String UsingResxLocalization.Android
package:/data/app/UsingResxLocalization.Android-VGGyQ6woBTkNUy4HJ8WqmQ==/base.apk=UsingResxLocalization.Android
> adb pull /data/app/UsingResxLocalization.Android-VGGyQ6woBTkNUy4HJ8WqmQ==/base.apk …
=> [Xamarin.Android.Build.Tasks] fix resx files for aabs

build-tools/automation/build.groovy
Commit ed597fba modified `build.groovy` so that `make run-all-tests`
was no longer executed, instead running `make run-performance-tests`.
Unfortunately, one set of tests which *only* runs on Jenkins was
overlooked: API compatibility tests (cffc6996)!
Update `build.groovy` so that `make run-api-compatibility-tests` is
always executed, so that we have *some* mechanism of tracking API
breakage over time.
TODO: Migrate API compatibility tests to Azure DevOps.
=> [Jenkins] Run API compatibility tests

src/Xamarin.Android.Build.Tasks/Tasks/BuildAppBundle.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/BundleToolTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3598
By default, Android leaves "already compressed" files such as
`*.wav` uncompressed in APKs.
This behavior is implemented in `aapt` & `aapt2`:
* `aapt`: https://github.com/aosp-mirror/platform_frameworks_base/blob/036ea39d96babb6c8a20464319903aea130e1a5f/tools/aapt/Package.cpp#L30-L37
* `aapt2`: https://github.com/aosp-mirror/platform_frameworks_base/blob/e80b45506501815061b079dcb10bf87443bd385d/tools/aapt2/cmd/Link.cpp#L2339-L2343
`bundletool` has a similar list of file extensions:
https://github.com/google/bundletool/blob/5ac94cb61e949f135c50f6ce52bbb5f00e8e959f/src/main/java/com/android/tools/build/bundletool/io/ApkSerializerHelper.java#L111-L115
However, if you specify `BundleConfig.json` (the `--config` switch), …
=> [Xamarin.Android.Build.Tasks] .aab default uncompressed file extensions

src/Xamarin.Android.Build.Tasks/Tasks/CilStrip.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes https://github.com/xamarin/xamarin-android/issues/1240
The `CilStrp` task was not able to handle being called incrementally. When called a second time the resulting error would be raised.
```
error XA3001: System.IO.IOException: The file '/Users/dean/Projects/Foo5F/Foo/obj/Release/android/assets/non-stripped/Foo.dll' already exists. 
at System.IO.FileSystem.LinkOrCopyFile (System.String sourceFullPath, System.String destFullPath) [0x000b9] in <06589f46f7f64859943a6a461f88c56e>:0
at System.IO.FileSystem.MoveFile (System.String sourceFullPath, System.String destFullPath) [0x0003a] in <06589f46f7f64859943a6a461f88c56e>:0
at System.IO.File.Move (System.String sourceFileName, System.String destFileName) [0x00083] in <06589f46f7f64859943a6a461f88c56e>:0
at …
```
=> [Xamarin.Android.Build.Tasks] Fix issues with re running CilStrip.

build-tools/cmake/xa_macros.cmake, src/java-runtime/java/mono/android/Runtime.java, src/monodroid/CMakeLists.txt, src/monodroid/jni/globals.cc, src/monodroid/jni/globals.hh, src/monodroid/jni/inmemory-assemblies.cc, src/monodroid/jni/inmemory-assemblies.hh, src/monodroid/jni/mono_android_Runtime.h, src/monodroid/jni/monodroid-glue.cc
This PR adds the necessary code and entry-point to be able to supply assembly data directly from memory.
The motivation is to allow the designer more flexibility in how it acquire those assemblies to begin with and avoid a complicated dance of file paths juggling and file copying that are detrimental to performance on Windows and cause file locking problems.
This is achieved by introducing a new class `InMemoryAssemblies` that, much like `EmbeddedAssemblies`, can be queried when a new .dll needs to be loaded to fetch it from a store that's keyed per-assembly name and per-appdomain. If not found in this new store it falls back to the existing logic that can load assemblies directly from disk.
Since we only care about this capability on desktop, the support is only compiled for host …
=> [monodroid] Allow loading assemblies from memory

src/Xamarin.Android.Build.Tasks/Tasks/R8.cs, src/r8/build.gradle
Context: https://mvnrepository.com/artifact/com.android.tools/r8/1.5.68
I updated the list of maven repositories to match r8's source.
One weirdness to note, was there was a 1.5.68 tag missing, so I looked at 1.5.67 instead.
=> Bump to r8 1.5.68

Configuration.props, src/bundletool/bundletool.targets
Context: https://github.com/google/bundletool/releases/tag/0.10.2
Changes: https://github.com/google/bundletool/compare/0.10.0...0.10.2
Bumping `bundletool` as I see some fixes that look important.
I then needed to fix the scenario where the `<DownloadUri/>` task was
skipping the download completely. By keeping the version in the
filename, it will force a download if `$(XABundleToolVersion)`
changes.
I also added `SkipUnchangedFiles=True` to speed up incremental builds
of `Xamarin.Android.sln`.
=> Bump to bundletool 0.10.2

.external
To get `aprofutil` tool. Besides other changes it also contain fix for
AOT/arm32, where method_addresses are in data section to avoid .text
relocations.
Changes: https://github.com/mono/mono/compare/29b1ac19c961b959a09097dbc0fe4cd567cc5298...cecda47c489a990c1554bdef486fa54e97544eea
=> Bump mono to 2019-08@cecda47c489a990c1554bdef486fa54e97544eea

Documentation/guides/messages/README.md, Documentation/guides/messages/xa0119.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
I have found developers using combinations of settings in `Debug` mode
that hurts their build times:
* Linker
* AOT
* ProGuard/R8
Additionally, using Android App Bundles is not a good idea for `Debug`
builds. Although, I have not seen that in the wild yet.
We can give a build warning if one of this configurations is found.
`XA0119` will recommend changing the project configuration and
hopefully guide develoeprs to change their settings.
=> [Xamarin.Android.Build.Tasks] warn XA0119 for non-ideal configurations

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Utilities/MetadataExtensions.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
I wrote the code for this a long time ago, but never opened a PR
because when timing the difference, I was seeing *no* improvement.
I even wrote a benchmark, that did clearly show an improvement:
https://github.com/jonathanpeppers/Benchmarks/blob/38ffb60421604b15eef38170ad9b12a2049ac3f1/Benchmarks/Cecil.cs
Method |      Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
----------- |----------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
SRM |  8.669 ms | 0.0385 ms | 0.0322 ms |   1000.0000 |    671.8750 |    656.2500 |             5.51 MB |
Mono.Cecil | 24.006 ms | 0.1879 ms | 0.1758 ms |   1906.2500 |   1718.7500 |    781.2500 |            39.95 MB |
Then last week I saw this line in the diff:
var …
=> [Xamarin.Android.Build.Tasks] use System.Reflection.Metadata for ResolveLibraryProjectImports

.external
Changes: https://github.com/mono/mono/compare/cecda47c489a990c1554bdef486fa54e97544eea...7ec17ba1be9bd08d9d991d10414df2b78710bc18
Fixes: https://github.com/xamarin/xamarin-android/issues/3619
Adds `aprofutil.exe` to the mono archive for Xamarin.Android use.
Fix leaks when handling a few metadata attributes.
Fix infrequent hangs in test-runner.
[threads] do not convert NULL thread name.
=> Bump to mono/mono/2019-08@7ec17ba1

tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3062430&view=logs&s=859b8d9a-8fd6-5a5c-6f5e-f84f1990894e&j=4348ab7c-72f0-52b0-44fd-6f17a16a558f
We had a test hang for the MSBuild device tests.
Reviewing the `while` loop in `ApplicationRunsWithDebuggerAndBreaks`:
TimeSpan timeout = TimeSpan.FromSeconds (60);
while (session.IsConnected && breakcountHitCount < 3) {
Thread.Sleep (10);
timeout = timeout.Subtract (TimeSpan.FromMilliseconds (10));
}
This would be an infinite loop if the test failed. I think it was
intended to check:
while (session.IsConnected && breakcountHitCount < 4 && timeout >= TimeSpan.Zero) {
...
=> [tests] fix DebuggingTest hang on failure

Documentation/guides/profiling.md, build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/ConfigAndData/Runtimes.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, tools/scripts/aprofutil
Let the xaprep know about the `aprofutil` and `Mono.Profiler.Log`
assembly.
Add documentation about *Profiling the AOT*.
Add script to call the aprofutil on MacOS.
=> [aprofutil] Add the aprofutil to the installation

Documentation/guides/MSBuildBestPractices.md, src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Compile.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tasks/AndroidTask.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs, src/Xamarin.Android.Build.Tasks/Tasks/CalculateLayoutCodeBehind.cs, src/Xamarin.Android.Build.Tasks/Tasks/CompileNativeAssembly.cs, src/Xamarin.Android.Build.Tasks/Tasks/Crunch.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateLayoutBindings.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateLibraryResources.cs, src/Xamarin.Android.Build.Tasks/Tasks/GetAdditionalResourcesFromAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkApplicationSharedLibraries.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs, src/Xamarin.Android.Build.Tasks/Utilities/AsyncTaskExtensions.cs
Right now there is a lot of boilerplate when using `AsyncTask`:
public override bool RunTask ()
{
Yield ();
try {
var task = this.RunTask (DoExecute);
task.ContinueWith (Complete);
base.RunTask ();
} finally {
Reacquire ();
}
return !Log.HasLoggedErrors;
}
We don't want to remember all that... or have to consistently get it
right.
Then if you want to use `Parallel.ForEach` it gets even more complex:
this.RunTask (
() => this.ParallelForEach (SomeArray, DoExecute)
).ContinueWith (Complete);
In d4c8f077, we created a base `AndroidAsyncTask` for error handling.
Let's put this weird `Yield-try-finally-Reacquire` logic in there,
too!
So instead, you would override:
public override System.Threading.Tasks.Task RunTaskAsync ()
This method is:
* Already on a background thread.
* You can use …
=> [Xamarin.Android.Build.Tasks] async helpers in AndroidAsyncTask

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/xamarin-android/pull/3607
Adds a new job to the Azure Pipelines 'Test' stage which downloads,
installs, and runs API compatibility checks against the .pkg installer
produced by the macOS build job.
=> [ci] Add API Compatibility job to Azure Pipelines

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/mac/setup-test-environment.yaml, build-tools/automation/yaml-templates/run-installer.yaml, build-tools/automation/yaml-templates/run-integrated-regression-tests.yaml, build-tools/automation/yaml-templates/run-nunit-tests.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_release?_a=releases&view=mine&definitionId=476
Adds two new "integrated regression test" jobs to Azure Pipelines to run
additional external tests which were previously only ran and reviewed in
an ad-hoc manner.
Permission issues with PR builds from forks are currently preventing us
from running these jobs against such builds, so we'll only run against
manually triggered or regular CI builds instead.
=> [ci] Add integrated regression test jobs

Documentation/guides/messages/xa0121.md, src/Mono.Android/Android/IncludeAndroidResourcesFromAttribute.cs, src/Mono.Android/Android/NativeLibraryReferenceAttribute.cs, src/Mono.Android/Android/ReferenceFilesAttribute.cs, src/Mono.Android/Java.Interop/JavaLibraryReferenceAttribute.cs, src/Xamarin.Android.Build.Tasks/Tasks/GetAdditionalResourcesFromAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
The `<GetAdditionalResourcesFromAssemblies/>` MSBuild task is the
precursor to Xamarin.Build.Download. It is only used by very old
versions of the Xamarin support library components.
We want to deprecate its behavior in an effort to remove complexity
and improve build performance. We have to scan each assembly for these
assembly-level attributes.
I added a new `XA0121` warning if a library is encountered during a
build that uses these attributes:
* `IncludeAndroidResourcesFromAttribute`
* `NativeLibraryReferenceAttribute`
* `JavaLibraryReferenceAttribute`
I added `[Obsolete]` on these as well.
=> [Xamarin.Android.Build.Tasks] deprecate <GetAdditionalResourcesFromAssemblies/>

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs
Currently the TimeZone unit tests do NOT restore
the device TimeZone back to its initial state.
This could effect other tests if they are expected
to run in a particular TimeZone. So we should restore
the state as much as possible.
Also the TimeZone tests REQUIRE the use of
adb shell su root xxxx
in order to set the TimeZone. This will not work on
any device which has not been rooted. Fortunately we
can check the `ro.debuggable` to see if the device
can run the above command. If it cannot then we should
ignore the test with a suitable message.
Also fixes an issue where if you use the `ADB_TARGET` environment
variable it was ignored when running `RunAdbCommand`.
=> [tests/MSbuildDeviceIntegration] Improve TimeZone Tests

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/3635
Running a `Clean`, would leave the app bundle in the `bin` directory:
> msbuild Foo.Android.csproj /p:Configuration=Release /p:AndroidPackageFormat=aab /t:SignAndroidPackage
> msbuild Foo.Android.csproj /p:Configuration=Release /p:AndroidPackageFormat=aab /t:Clean
> ls -n bin\Release
com.mycompany.foo-Signed.aab
The `_CollectMonoAndroidOutputs` MSBuild target has a series of
`<CreateItem/>` calls that add apk-related files to `@(FileWrites)`.
We need to do the same for all app-bundle-related files.
=> [Xamarin.Android.Build.Tasks] Clean did not delete App Bundles

build-tools/xaprepare/xaprepare/Steps/Step_PrepareExternal.Unix.cs
A co-worker who only had AdoptOpenJDK 13 installed was not able to run
`make prepare`:
Project "…/xamarin-android/external/Java.Interop/build-tools/scripts/jdk.targets" on node 1 (GetPreferredJdkRoot target(s)).
…/xamarin-android/external/Java.Interop/build-tools/scripts/jdk.targets(5,5): warning : Not a valid JDK directory: `/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk/Contents/Home`; via locator: `/usr/libexec/java_home -X`
…/git/xamarin-android/external/Java.Interop/build-tools/scripts/jdk.targets(5,5): error : Could not determine JAVA_HOME location. Please set JdksRoot or export the JAVA_HOME environment variable.
Done Building Project "…/xamarin-android/external/Java.Interop/build-tools/scripts/jdk.targets" (GetPreferredJdkRoot target(s)) -- FAILED.
Build FAILED.
`make …
=> [xaprepare] Java.Interop should use Corretto

build-tools/automation/azure-pipelines.yaml
Migrates our macOS build jobs to the macOS 10.14 Mojave pool which is
more performant for certain build types. Also moves all host name variables
into 'azure-pipelines.yaml' so it's easier to test and swap to different machine
pools. Looking at performance across a few jobs, the Mojave pool appears to
be better for all of our jobs which don't use an emulator. Unfortunately,
emulator performance appears to be worse on this pool however.
|        Job        | HighSierra | Mojave         |
|-----------------|------------|----------------|
| Prepare           | ~18m       | ~13m       |
| Build             | ~75m       | ~55m        |
| Test Apks         | ~48m       | ~50m           |
| Test BCL          | ~90m       | ~113m          |
| Test MSBuild      | ~128m      | ~118m          |
| …
=> [ci] Move Azure Pipeline mac jobs to Mojave

.external
Changes: https://github.com/mono/mono/compare/7ec17ba1be9bd08d9d991d10414df2b78710bc18...bfbf823ca1129dbfd1ba5b7c066676bf185ed922
Context: https://github.com/mono/mono/issues/16709
Context: https://github.com/xamarin/xamarin-macios/issues/7005
Disables `ppdb` data decompression.
Add missing membars when initializing rgctx entries
Remove the mac32 build
Adds .NET 4.8 reference assemblies
=> Bump to mono/mono/2019-08@bfbf823c

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/MonoAndroidHelperTests.cs
Context: https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=3077728&view=ms.vss-test-web.test-result-details
We had a random test failure, such as:
Xamarin.Android.Build.Tests.MonoAndroidHelperTests.CopyIfBytesChanged_Readonly
System.UnauthorizedAccessException : Access to the path 'C:\Users\dlab14\AppData\Local\Temp\CopyIfBytesChanged_Readonly' is denied.
TearDown : System.UnauthorizedAccessException : Access to the path 'C:\Users\dlab14\AppData\Local\Temp\CopyIfBytesChanged_Readonly' is denied.
Stack trace
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String …
=> [tests] fix for MonoAndroidHelperTests

tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
Context https://github.com/xamarin/xamarin-android/issues/2730
This commit adds a unit test to make sure that we can debug custom applications. 
It did expose a slight issue with our enhanced fast deployment. One of the requirements for custom applications working is that the java classes for the custom app MUST be in the `classes.dex` file in the apk. As a result when using enhanced fast deployment, we can't load the application because not even the MultiDexLoader has been loaded. So for that to work will need to somehow figure out how to pick out just the custom app dependencies and put them into the apk. 
All other development modes work fine, so we should add the tests anyway. We can updated the tests later once the enhanced fast deployment issue has been fixed.
=> Add Unit test for Custom Application

build-tools/Xamarin.Android.Tools.BootstrapTasks/result-packaging.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs
Context: https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=3075928&view=ms.vss-test-web.test-result-details
I was originally using this in #3649, but it seemed better to do this
in a separate PR.
If a `DeviceTest` fails, it can take a screenshot, add an attachment
to the failed test, and archive it as an artifact. This will help
troubleshoot if things like a button press fails, and if we add more
tests like this down the road.
=> [tests] DeviceTest captures & records screenshots

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/PreserveHttpAndroidClientHandler.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3626
https://github.com/mono/mono/commit/6034bc00c432356a31208136b871ed152eb3f8d3
https://github.com/mono/mono/commit/2d6f02a83c5715b41364fe450f3bf4391c64c37b
introduced new `HttpClient.CreateDefaultHandler()` method, which
replaces the `HttpClient.GetDefaultHandler()` method.
Our XA linker logic was detecting `AndroidClientHandler` usage by
checking the `GetDefaultHandler` method and so it doesn't work
anymore.
Added a new test to avoid similar regression in the future.
=> [linker] Update PreserveHttpAndroidClientHandler substep

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-installer.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/TestEnvironment.cs
We'd like to run most if not all of our tests against a complete .vsix
or .pkg installer in order to better replicate our users development
environments. All of our 'Test' jobs on Azure Pipelines are currently
configured to test against our installers, however these jobs are only
running on macOS environments.
Adds one new jobs to run the msbuild tests which don't require an
emulator on a Windows test environment against our .vsix installer.
=> [ci] Add Windows MSBuild test job

.external
Context: https://github.com/mono/mono/commit/7ae0f38fd7ee4409b3cc717e33315188b603bb31
Mono had a small regression where it started to ignore the runtime version
passed to it during initialization (`mobile` in our case) which resulted in the
runtime repeatedly remapping assemblies from the "mobile" version `2.0.5.0` to
the "default" version `4.0.0.0`. That, in turn, caused our assembly preload hook
to be repeatedly called in order to load the same assemblies over and over
again. Bump Mono to fix the issue.
Changes:
* d8441deead6 [crashing] Remove Mono signal handlers when starting to handle a crash (#17078)
* 7ae0f38fd7e [runtime] Respect runtime_version in mono_init_internal (#17086)
* 61ca7fe3a46 [sdks] Bump min iOS version to 7.0. (#17070)
=> Bump Mono to fix remapping assembly versions on run time

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
Context: https://www.nuget.org/packages/Xamarin.AndroidX.Migration
Xamarin.AndroidX.Migration has a lot of integration into the
Xamarin.Android MSBuild targets. We should include a test for
AndroidX, so we have better coverage of our MSBuild extension points.
We don't want to break it!
=> [tests] add an MSBuild test for AndroidX migration

src/Xamarin.Android.Build.Tasks/Tasks/AndroidSignPackage.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
`jarsigner` always prints a message such as:
Warning: The signer's certificate is self-signed.
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2049-06-13) or after any future revocation date.
You will see this if `$(AndroidApkSigner)` is `False` or
`$(AndroidPackageFormat)` is `aab`.
This is basically just noise, `jarsigner` always complains when
signing APKs with a self-signed keystore file.
We should downgrade these specific `Warning:` messages from
`jarsigner` to just a regular MSBuild message.
I found the source code for `jarsigner` here:
* `Resources.java`: http://hg.openjdk.java.net/jdk8u/jdk8u-dev/jdk/file/0fc878b99541/src/share/classes/sun/security/tools/ …
=> [Xamarin.Android.Build.Tasks] downgrade jarsigner warnings to messages

.external, Documentation/release-notes/master.md
Changes: https://github.com/xamarin/monodroid/compare/623845d44abe5eb7a76d9a63d48b30a27ac1bac2...8cd2639e7c396f4e5ee8816dccdb2db5fe523023
$ git diff --shortstat 623845d4..8cd2639e
13 files changed, 178 insertions(+), 38 deletions(-)
Bring in changes to the commercial `InstallPackageAssemblies` task to
cache the `AndroidDeploySession` in MSBuild's AppDomain for reuse across
repeated fast deployments.
=> Bump to xamarin/monodroid/master@8cd2639e

.external
Some time around mono 4.9 (0ddcf96), the C# compiler started
emitting Portable PDB (`.pdb`) files instead of `*.mdb` files.
However, the shared runtime was not updated to include `.pdb` files.
It was still only including `*.mdb` files.
Consequently, the shared runtime hasn't included debug symbols in *ages*.
Update the `tools/RuntimeService` so that `.pdb` files are included
in the shared runtime, so that stack traces when `debug.mono.debug`=1
are more useful.
=> [RuntimeService] Include .pdb files in the Shared Runtime

build-tools/Xamarin.Android.Tools.BootstrapTasks/result-packaging.targets, tests/CodeBehind/UnitTests/BuildTests.cs, tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-Tests/Xamarin.Android.MakeBundle-Tests.csproj, tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/BuildTests.cs, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/BuildTests.cs, tests/EmbeddedDSOs/EmbeddedDSO/EmbeddedDSO.csproj
There have been some cases where we wanted to get the entire project
directory from the CI system after a test run has completed.
We can zip up all of:
bin\Test$(Configuration)\temp\**\*
However, there are a few MSBuild-related tests that don't drop their
files in this directory:
* `CodeBehind`
* `CodeGen-MkBundle`
* `EmbeddedDSOs`
I changed these tests to output to `temp`. This should be OK even if
there is a naming collision, since they don't run at the same time as
the other MSBuild tests.
=> [tests] include all of bin/Test$(Configuration)/temp in xa-tests-results.zip

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Utilities/ZipArchiveEx.cs
Context: https://github.com/xamarin/xamarin-android/pull/3695
Context: https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=3095849&view=ms.vss-test-web.test-result-details
We have been hitting a random MSBuild test failure on macOS:
Unable to open 'obj/Debug/android/bin/UnnamedProject.UnnamedProject.apk' as zip archive
This appears to be coming from `zipalign` directly. In #3695 I was
able to get the APK file in question.
Using 7-zip on Windows, it reports the file is invalid:
> 7z t "C:\Users\jopepper\Downloads\CheckResourceDesignerIsCreatedFalseCSharp\obj\Debug\android\bin\UnnamedProject.UnnamedProject.apk" …
=> [Xamarin.Android.Build.Tasks] dispose GetManifestResourceStream

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
We have a few tests that make use of `FileCompare`, which
unfortunately does not report what actually differed.
I think we should make this method `AssertFileContentsMatch` instead,
and add both files as test attachments in cases of failure. This way
we can inspect both files and see what went wrong. Our test code will
also be a little simpler.
Additionally, I found the actual difference in the two files is CRLF
vs LF. I accidentally lost the following line in 88a1d6cd:
https://github.com/xamarin/xamarin-android/commit/88a1d6cd88e68bda208a6eb05d99d802c7800d2e#diff-f2ab112c825cdebe3019eecdbed39cb5L397
I partially reverted 88a1d6cd to use the helper method
`ReadAllBytesIgnoringLineEndings`, but used CRC64 instead of MD5.
=> [tests] FileCompare -> AssertFileContentsMatch

.external, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks.csproj, build-tools/Xamarin.Android.Tools.BootstrapTasks/packages.config, build-tools/xaprepare/xaprepare/ThirdPartyNotices/LibZipSharp.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/packages.config, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/packages.config, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/packages.config, src/Xamarin.Android.Tools.JavadocImporter/Xamarin.Android.Tools.JavadocImporter.csproj, src/Xamarin.Android.Tools.JavadocImporter/packages.config, tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/Xamarin.Android.MakeBundle-UnitTests.csproj, tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/packages.config, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/EmbeddedDSO-UnitTests.csproj, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/packages.config, tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj, tests/MSBuildDeviceIntegration/packages.config
We need to start shipping pdb files with our installer. This is so we can get better stack traces if we get errors. LibZipSharp 1.0.2 which we were using did not contain any pdb files. This PR bumps LibZipSharp to 1.0.5 which does include the pdb files.
=> Bump LibZipSharp to 1.0.5 to include pdb files

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
Fixes https://github.com/xamarin/xamarin-android/issues/3675
We were NOT passing `AndroidStoreUncompressedFileExtensions` to the `Aapt2Link` task 🤦‍♂. 
So any file listed would still be stored compressed. I think we got away with this for the most part because certain files (like assemblies) are added by us manually later. However if users want certain `Asset` files to be uncompressed this will cause them issues.
So lets use this setting for `Aapt2Link` and update the test which checks for compressed files to test `aapt` and `aapt2`.
=> Fix Uncompressed files for Aapt2

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs, src/monodroid/jni/monodroid-glue.cc, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
We hit a problem where the text for the log message
for the debugger was changed. It went from
monodroid-debug: Trying to initialize the debugger with options:
to
monodroid-debug: mono_runtime_init: Trying to initialize the debugger with options:
Which stopped our unit test matching the line.
So lets make this use just the text
Trying to initialize the debugger with options:
and make sure we comment the line to if it changes people
also go an update the unit test.
=> [MSBuildDeviceIntegration] Harden checks for the debugger.

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs, src/Xamarin.Android.Build.Tasks/Tasks/AndroidToolTask.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/Aapt2Tests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/AndroidRegExTests.cs, src/aapt2/aapt2.targets
Source https://mvnrepository.com/artifact/com.android.tools.build/aapt2/3.5.0-5435860
This PR updates the `aapt2` tool we ship to the latest stable version. It also adds some additional message processing. The line [1] is a warning, and it is being picked up as an error by out Task. This is because it is not following the same pattern as other warnings. 
```
// aapt2 W 09-17 18:15:27 98796 12879433 ApkAssets.cpp:138] resources.arsc in APK 'android.jar' is compressed.
```
So in this case we need to look for the `aapt2 W ` and tag such lines as warnings not errors.
[1] https://github.com/aosp-mirror/platform_frameworks_base/blob/master/libs/androidfw/ApkAssets.cpp#L137
=> [aapt2] Bump Aapt2 to Version 3.5.0-5435860

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Properties/AndroidManifest.xml
This is an effort to improve build performance going forward.
Context: https://dev.azure.com/DevDiv/DevDiv/_build/results?buildId=3087283&view=ms.vss-test-web.test-result-details
I was getting:
Java.Lang.AbstractMethodError : abstract method "int com.xamarin.android.DefaultMethodsInterface.foo()"
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualIntMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <eea339da6b5e4d4bb255bfef95601890>:0
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in …
=> [Xamarin.Android.Build.Tasks] use d8 by default

ThirdPartyNotices.txt, build-tools/xaprepare/xaprepare/ThirdPartyNotices/Xamarin.Android.Build.Tasks.cs, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/PackagingUtilsTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.Shared.projitems, src/Xamarin.Android.Build.Tasks/Utilities/PackagingUtils.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Fixes: https://github.com/xamarin/xamarin-android/issues/3348
Usage of a Kotlin library in a Xamarin.Android application could fail
with:
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.sample.xamarinsampleapp, PID: 20262
[AndroidRuntime] java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
Reviewing the results of an APK from Android Studio, these files were
missing in the equivalent Xamarin.Android apk:
META-INF/services/kotlinx.coroutines.internal.MainDispatcherFactory
META-INF/services/kotlinx.coroutines.CoroutineExceptionHandler
I was able to piece together what the behavior is from Google's
Android Gradle plugin.
The top level gradle task: …
=> [Xamarin.Android.Build.Tasks] support for META-INF/services inclusion in APKs

tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Context #3727
Somehow sometimes the code we have does NOT detect
that the user uninstalled the app. As a result the
`_Upload` target does not run. This commit just adds
some additional checks to the unit test to make sure we
skip that target when we should, and run it when we need to.
Hopefully this might help us detect if and when this problem 
happens on our build system.
=> [Xamarin.Android.Build.Test] Check _Upload is skipped.

build-tools/automation/azure-pipelines.yaml
Creates two new jobs within a new 'Finalize Installer' stage. The first
job notarizes and staples the .pkg installer, uploads the .pkg, .vsix,
and updateinfo files to the storage mirror, and posts a GitHub status
containing storage mirror links for these artifacts. The second queues
and waits for a .vsix signing job which runs on Jenkins. These two jobs
run sequentially after the mac build is completed, and the new stage
runs in parallel with the existing test stage.
Our finalized installers will receive a final validation pass via the
"insertion PRs" into VS and VS Mac. They will no longer be used by any
existing test job in this YAML pipeline. Only unsigned installers will
be tested by the YAML pipeline.
=> [azure-pipelines] Add Installer Finalization stage

src/r8/build.gradle
If you run:
> java -jar .\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\r8.jar
Error: Could not find or load main class com.android.tools.r8.SwissArmyKnife
Whoops! In a85dd5b5 I bumped r8 to 1.5.68, which no longer contains
`SwissArmyKnife` anymore, but forgot to fix this setting.
This is not a problem for Xamarin.Android because it invokes this
command instead:
> java -classpath .\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\r8.jar com.android.tools.r8.R8
But it would be good to fix this anyway.
=> [r8] fix Main-Class setting in manifest

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
We don't export the BUILD_HOST environment variable
anymore. As a result we don't clear out the global
Xamarin cache for extracted zip files.
So lets change this code to use the `TestEnvironment.IsRunningOnCI`
so we can correctly detect when we are running
on CI.
=> [Xamarin.Android.Build.Tests] Clean cache on CI

src/monodroid/jni/osbridge.cc
Context: https://github.com/xamarin/xamarin-android/issues/3706
After enabling GREF logging to investigate a potential leak, my brain
got very confused while reading the GREF counts:
+g+ grefc 1 gwrefc 0 obj-handle 0x2586/G -> new-handle 0x25b6/G from thread '(null)'(1)
+g+ grefc 2 gwrefc 0 obj-handle 0x199/L -> new-handle 0x25c6/G from thread '(null)'(1)
-g- grefc 2 gwrefc 0 handle 0x25c6/G from thread '(null)'(1)
+g+ grefc 2 gwrefc 0 obj-handle 0x191/L -> new-handle 0x25ca/G from thread '(null)'(1)
In particular, note lines 2-3, in which `+g+`, `-g-`, and `+g+` all
show the same GREF count: 2.
Say what?  How can we start at 2, see `-g-`, and still be at 2?
`logcat-parse` also doesn't like this state of affairs:
$ mono /Library/Frameworks/Xamarin.Android.framework/Versions/Current//lib/xa …
=> [monodroid] Use __sync_sub_and_fetch for -g-

Documentation/guides/BuildProcess.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BuildHelper.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownProperties.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Add `AndroidUseDefaultAotProfile`. It can be used to suppress usage of
the default AOT profiles.
Add `AndroidAotProfiles` property to specify AOT profiles from command
line.
=> [profiled aot] Added 2 new properties for our targets

src/Xamarin.Android.Build.Tasks/Tasks/GetAdditionalResourcesFromAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/GetAdditionalResourcesFromAssembliesTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
Context: https://dev.azure.com/devdiv/DevDiv/_releaseProgress?releaseId=469145&_a=release-environment-extension&environmentId=2323128&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&runId=8876788&resultId=100476&paneView=debug
Context: https://github.com/xamarin/xamarin-android/commit/88a1d6cd88e68bda208a6eb05d99d802c7800d2e
Adds missing braces to a using statement to fix the following
`ObjectDisposedException`:
C:\Program Files (x86)\Microsoft Visual Studio\2019\IntPreview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(535,3): warning XA0121: Assembly 'Xamarin.Android.Support.Compat.dll' is using a deprecated attribute '[assembly: Java.Interop.JavaLibraryReferenceAttribute]'. Use a newer version of this NuGet package or notify the library author. …
=> [XA.Build.Tasks] Fix file hashing using statement

src/monodroid/jni/debug-app-helper.cc
Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/989404
Context: https://developercommunity.visualstudio.com/content/problem/749635/xamarin-stop-on-load.html
Xamarin.Android runtime used the `RTLD_NODELETE` flag with `dlopen(3)` in order
to make subsequent opens of the same shared library slightly faster (the flag
causes `dlclose(3)` not to remove the mapped DSO from memory and not to
reinitialize its static variables etc on the subsequent call to `dlopen`). The
flag is defined in the NDK without any API level (platform) version restrictions
but, apparently, it fails to work on some API 22 Samsung devices with the
following error:
F/debug-app-helper( 9171): Failed to dlopen Mono runtime from /data/data/com.companyname.xamarinlearning/files/.__override__/links/libmonosgen-2.0.so: …
=> Don't use RTLD_NODELETE flag with dlopen

src/monodroid/CMakeLists.txt, src/monodroid/jni/basic-utilities.hh, src/monodroid/jni/cpp-util.hh, src/monodroid/jni/debug.cc, src/monodroid/jni/debug.hh, src/monodroid/jni/embedded-assemblies.cc, src/monodroid/jni/embedded-assemblies.hh, src/monodroid/jni/external-api.cc, src/monodroid/jni/globals.cc, src/monodroid/jni/globals.hh, src/monodroid/jni/logger.cc, src/monodroid/jni/mkbundle-api.h, src/monodroid/jni/monodroid-glue-internal.hh, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/monodroid-glue.hh, src/monodroid/jni/monodroid-networkinfo.cc, src/monodroid/jni/timezones.cc, src/monodroid/jni/util.cc, src/monodroid/jni/util.hh, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs, tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs
monodroid-glue is one of the last pieces of our native code that, so far, hasn't
been converted to "proper" C++ by putting the data and functions in a class,
while migrating some of them to more appropriate classes.
This commit implements just that:
* move all the data members to a new `MonodroidRuntime` class
* move a number of profiler and debugging functions to the `Debug` class
* move most `MONO_API` functions to a separate file
Additionally, bits and pieces of code are modified to make them more C++ than
C (including some Windows-specific code to work around the ancient mingw version
we used at some point).
The simple pointer guard class is extended to work with C-allocated
pointers (the class still needs some work to make it more generally useful, but
that's beyond the scope of this …
=> [C++ification] Convert monodroid-glue to a class

tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs
The `DeploymentTest` unit tests build the test application
during `[Setup]` of the unit test class. As a result if
we do not have any Devices attached we never create the
`proj` or `builder` classes.
So what happens is we get a test failure due to a Null
Reference exception when the test shuts down.
We should handle that senario and make sure we do not
throw errors when we shut down the unit tests.
=> [MSBuildDeviceIntegration] Add null checks to [Teardown]

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
We have a race condition. If the `BuildLibraryWhichUsesResources`
tests run at the same time it causes the following
type of errors.
error APT2260: resource style/Platform.V11.AppCompat.Light (aka UnnamedProject.UnnamedProject:style/Platform.V11.AppCompat.Light) not found.
error APT2062: failed linking references.
This seems to be because both tests try to extract files
into the same global cache directory. What ends up happening
is we end up with an empty directory and no files.
This is because of the `GetAdditionalResourcesFromAssemblies`
task, which we are deprecating anyway.
So lets not run these in parellel, so they do not trip over
each other.
=> [Xamarin.Android.Build.Tests] Done run BuildLibraryWhichUsesResources in parallel.

tests/MSBuildDeviceIntegration/Tests/BugzillaTests.cs
Context: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3107238&view=ms.vss-test-web.test-result-details
Context: https://bugzilla.xamarin.com/show_bug.cgi?id=29730
This test has been failing with some frequency since it was imported in
the new Integrated Regression test Azure Pipeline jobs. After some
investigation, it appears that the failure is due to test environment
limitations. Some of the Android devices attached to the machine pools
being used for this test job have a lock screen enabled, and in some
cases this is preventing `ViewTreeObserver` events from executing.
Fixes the intermittent failure by moving this test into the
`MSBuildDeviceIntegration` suite which runs on an x86 emulator in CI.
This emulator is never locked and should always display activites for …
=> [tests] Import regression test for bug 29730

tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Commit 5745b601 added a new unit test `TestAndroidStoreKey`.
However this test needs to have a device present in order
to run correctly. The test did not include the standard
`HasDevices` check at the start of the test. As a result
the test will fail if we don't have a device. We should
Ignore this test if we do not have a device like we do
on other tests in this project.
=> [tests/MSBuildDeviceIntegation] Fix TestAndroidStoreKey to check for Device.

.external
Changes: http://github.com/xamarin/monodroid/compare/28ffbd3...e803e0d
Fixes: xamarin/xamarin-android#3091
Fixes: https://developercommunity.visualstudio.com/content/problem/576975/android-debugging-always-reinstalls-shared-runtime.html
=> Bump to xamarin/monodroid@e803e0d

Documentation/guides/messages/README.md, Documentation/guides/messages/xa4307.md, src/Xamarin.Android.Build.Tasks/Tasks/Proguard.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Fixes #3571
Currently if `proguard` encounters a problem with the format
of a config file our users get this unhelpful message
error MSB6006: "java.exe" exited with code 1.
They have to look though the logs to pick our the actual
error. Most of the reports we have seen are a result of the
file being saved with a Byte Order Mark (BOM). In this case
`proguard` throws a `proguard.ParseException`. This commit
catches this particular issue and makes sure the actual
error message is raised rather than the generic java one.
This also adds a unit test.
=> [Xamarin.Android.Build.Tasks] Catch Proguard config format errors. 

build-tools/timing/timing.targets
This is helpful when analyzing logcats from CI or debugging the code
that processes the logcat timing.
=> [logcat timing] Make it possible to use local logcat file as input

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs
We were not catching the message `unexpected element <activity> found in <manifest>` that users are reporting after switching to `aapt2`.  Add that as well as a fallback for any other unexpected element messages.
=> [Xamarin.Android.Build.Tasks] Add some new AAPT2 coded errors

build-tools/automation/azure-pipelines.yaml
Context: https://build.azdo.io/3140335
Fix the hard coded user path by setting JAVA_HOME in a script that uses
a VSO logging command[0]. This works around the inability to use system
variable values when setting other variables from YAML.
This ensures that the JDK we provision[1], and attempt to use, stay in sync.
[0] https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands
[1] https://github.com/xamarin/xamarin-android/blob/73547b144c4022713dc6d50907bc4184a003acad/Configuration.props#L63
=> [ci] Do not hard code agent user name

tests/Xamarin.Forms-Performance-Integration/Droid/Xamarin.Forms.Performance.Integration.Droid.csproj, tests/Xamarin.Forms-Performance-Integration/run-perf-test.sh
The script runs our XF integration test on the connected device 10 times for
each of the following configurations:
* 32-bit build, assembly preload enabled
* 32-bit build, assembly preload disabled
* 64-bit build, assembly preload enabled
* 64-bit build, assembly preload disabled
At the end the script generates two files:
* performance-report.csv
Contains average times in nanoseconds
* performance-table.md
Contains a Markdown table with average times in milliseconds, useful for
inclusion in commit messages
The script requires manual intervention to start the application on device.
=> Add a script to run XF performance test on connected device

src/monodroid/CMakeLists.txt, src/monodroid/jni/android-system.cc, src/monodroid/jni/android-system.hh, src/monodroid/jni/basic-android-system.cc, src/monodroid/jni/basic-android-system.hh, src/monodroid/jni/basic-utilities.cc, src/monodroid/jni/basic-utilities.hh, src/monodroid/jni/debug-app-helper.cc, src/monodroid/jni/debug.cc, src/monodroid/jni/debug.hh, src/monodroid/jni/embedded-assemblies-zip.cc, src/monodroid/jni/embedded-assemblies.cc, src/monodroid/jni/embedded-assemblies.hh, src/monodroid/jni/external-api.cc, src/monodroid/jni/globals.hh, src/monodroid/jni/inmemory-assemblies.cc, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/util.cc, src/monodroid/jni/util.hh
Next commit in the series of making our native code use "proper" C++ constructs,
take advantage of the language's features etc. Changes:
* Fix more compilation warnings arising from differences between platforms
* Compare pointers against `nullptr` instead of the traditional `!p` C-style check
* Use the `simple_pointer_guard` class in more places
* Use references to pointers instead of pointers to pointers in a handful of
places to decrease the number of null checks
* Switch nested namespace declarations to C++17 style
* Make `Util::ends_with` slightly faster when used with literal strings,
taking advantage of C++ templates
* Move variable declarations closer to places where they are actually used
* Move a number of extern "C" functions to `external-api.cc`
=> [C++ification] Continue converting code to "proper" C++

src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
A few places during a Xamarin.Android build, we have the following
pattern:
if (DesignTimeBuild && !File.Exists (assemblyPath)) {
Log.LogDebugMessage ($"Skipping non-existent dependency '{assemblyPath}' during a design-time build.");
continue;
}
In the case of a `<ProjectReference/>` not building, there starts to
be a problem here.
What happens during a regular build, is we end up throwing a
`FileNotFoundException` in `<FilterAssemblies/>`.
If we remove the `if (DesignTimeBuild)` check, we would instead see
the behavior you would get for a .NET Console app referencing a .NET
Framework library project:
(ResolveProjectReferences target) ->
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1875,5):
warning : The …
=> [Xamarin.Android.Build.Tasks] <FilterAssemblies/> shouldn't throw FNFE

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/994496
When we call `GetAndroidDependencies` we expect to get
a list of TaskItems back describing the tooling the
project needs.
However if certain parts of the Android SDK have NOT
been installed we get errors such as
XA5205: Cannot find aapt.exe. Please install the Android SDK Build-tools package with the C:\Program Files (x86)\Android\android-sdk\tools\android.bat program.
This is because `ResolveAndroidTooling` throws an error. This
is expected behaviour when building an app. However when calling
`GetAndroidDependencies` we dont want it to throw. So lets
add a property which will control the `ContinueOnError` property
of the task. Doing a normal build the error will be reported.
However when calling via the …
=> [Xamarin.Android.Build.Tasks] AutoSDK doesn't install Tools or Build Tools

build-tools/automation/azure-pipelines.yaml
Commit d202ef4 broke some [downstream validation][0] which ensured our .pkg
file was properly notarized. These changes temporarily reintroduce a
build artifact which contains our notarized .pkg, so that it can be used
by this validation release defintion. 
A script has also been added to run the `xcrun stapler validate` command
against our finished `.pkg` file to validate the "notarize and staple" step.
This command will exit with code 65 and cause the notarization job to fail
if a successful notarization ticket has not been stapled to the `.pkg` file.
[0]: https://dev.azure.com/devdiv/DevDiv/_release?_a=releases&view=mine&definitionId=1977
=> [ci] Upload Notarized .pkg for validation

src/Xamarin.Android.Build.Tasks/Tasks/R8.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3751
When enabling multi-dex, but *not* code shrinking, such as:
<AndroidDexTool>d8</AndroidDexTool>
<AndroidLinkTool></AndroidLinkTool>
<AndroidEnableMultiDex>True</AndroidEnableMultiDex>
In this configuration, we run r8 instead of d8, because it fully
supports multi-dex. r8 automatically calculates what needs to go in
the main dex file, which d8 doesn't do.
We pass these flags to r8 in this mode:
--no-tree-shaking --no-minification
However, I noticed a few problems in the dex file I analyzed with:
dexdump -d obj\Debug\android\bin\classes.dex > classes.txt
* The dex code appears to be optimized. The code within methods is
shortened/scrambled.
* Annotations are missing???
`dexdump` does not appear to list annotations, but I could …
=> [Xamarin.Android.Build.Tasks] r8 should not optimize for multi-dex only

.external, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Utilities/NativeAssemblyDataStream.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingNativeAssemblyGenerator.cs
This is a first step to use the `typemap.mj` and `typemap.jm` files
for Fast Deployment. We will eventually generate these files on a
per-assembly basis, but can get some small perf improvements for
`Debug` builds:
* When `$(EmbedAssembliesIntoApk)` is `True` use the native assembly
in `typemap.*.inc` and the current behavior.
* When `$(EmbedAssembliesIntoApk)` is `False` don't generate any
`typemap.*.inc` files at all, but still use the native assembly for
environment variables.
* We have to still generate `typemap.*.s` files with empty values.
Before:
```as
jm_typemap_header:
/* version */
.long	1
/* entry-count */
.long	1324
/* entry-length */
.long	262
/* value-offset */
.long	117
.size	jm_typemap_header, 16
/* Mapping data */
.type	jm_typemap, %object
.global	jm_typemap
jm_typemap: …
```
=> [Xamarin.Android.Build.Tasks] use typemaps when EmbedAssembliesIntoApk=False

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3779
Using @brendanzagaeski's repro, I saw a possible #deletebinobj issue
when using aapt2:
* Build with a resource error, get an `APT2XXX` error code.
* Future builds give no error???
Once in this state, you could be using a malformed APK until you
modify a `@(AndroidResource)` -- or fix the problem?
The cause appears to be that `aapt2` is actually generating output in
`obj\Debug\bin\android\packaged_resources` even though it emits an
error?
I think we should:
* Do *not* copy `packaged_resources.bk` if `aapt2` failed.
* Delete `packaged_resources` on `aapt2` failures.
=> [Xamarin.Android.Build.Tasks] aapt2 failure causes targets to skip

src/Xamarin.Android.Build.Tasks/Tasks/AndroidZipAlign.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ZipAlignTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
The standard behaviour of the `ToolTask` is to write
any `stderr` output out as a message. It then logs
a generic "Tool existed with exitcode X" error. This
is not great as the end user then has to dig through
the logs to find the actual problem.
The `ToolTask` does have a property `LogStandardErrorAsError`
which defaults to `false`. When set to `true` any `stderr`
output will be logged as an error. However there is no way
in the `ToolTask` to provide an `ErrorCode` for those errors.
You just get a blank `ErrorCode`. So while that might seem
like a good solution, its not what we are after.
So in this case we want an `ANDZA0000` errode code. Looking
at the source code for `ToolTask` [1] the best way to do
this is to intercept the message logging in the
`LogEventsFromTextOutput`. …
=> [Xamarin.Android.Build.Tasks] Produce a better ZipAlign Error.

src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android.Runtime/TimingLogger.cs, src/Mono.Android/Mono.Android.csproj, src/monodroid/jni/android-system.cc, src/monodroid/jni/debug.cc, src/monodroid/jni/external-api.cc, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/osbridge.cc, src/monodroid/jni/util.cc, src/monodroid/jni/util.hh, tests/Xamarin.Forms-Performance-Integration/Droid/MainActivity.cs
This commit introduces a new public class, `Android.Runtime.Timing` which can be
used by the managed code to efficiently and accurately (to the nanosecond level)
measure code performance. At the moment the class is used only by our
Xamarin.Forms integration test.
Additionally, this commit removes support for namespaced system properties (that
is properties suffixed by the package name) which were added for the benefit of
the IDEs but never seen any use. Namespaced properties require two system
property retrieval calls and so they cost extra time (not much, around 25k
nanoseconds but taken together they can contribute to >1ms of startup time with
no real purpose).
=> A handful of timing changes

src/monodroid/CMakeLists.txt, src/monodroid/jni/osbridge.cc
Fixes: https://github.com/xamarin/xamarin-android/issues/3802
Most Linux distributions don't have a wrapper for the `gettid` syscall in the
standard C library. It appears that distributions with newer glibc define it in
`unistd_ext.h` header included by `unistd.h`. Add a symbol check to avoid build
errors on those distributions which do define `gettid` in the system headers.
=> Try to detect the `gettid` function on Linux hosts

.external
Changes: https://github.com/mono/mono/compare/01dbbb746f4174130ef1226e4a9683f2f9a70f9d...ef75d4bef7509b23103fffa2acca039e9acbb157
Fixes an issue within `Socket.BeginConnect()` returning too early when
the callback wasn't provided.
=> Bump to mono/mono/2019-08@ef75d4be

build-tools/installers/create-installers.targets
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3169241&_a=summary
Symbol check is erroring due to a missing Xamarin.Android.NUnitLite.pdb.
I am not sure why this was not previously reported, however we should
be able to appease symbol check by including this file in the installer.
=> [Installer] Add Xamarin.Android.NUnitLite.pdb

.external
Changes: https://github.com/mono/mono/compare/df5e13f95df7a2d11d86904e74b1bd8950c9d43b...baa12e5d2405fc81195817638983ba7d6d8330f2
* mono/mono@baa12e5d: [profiler] Fix coverage profiler on macos (#17422)
* mono/mono@ef75d4be: [2019-08] BeginConnect complete to early when not using callback. (#17416)
* mono/mono@01dbbb74: [2019-08] Enable GSS on Linux (#17410)
* mono/mono@51a3dc37: Fix SafeHandle marshalling in ref/in/out parameters (#17330)
* mono/mono@3eb5f34f: [GTK] Bump bockbuild for GtkViewport autoscrolling patch. (#17321)
* mono/mono@b601371d: Update MERP event type to MonoAppCrash
* mono/mono@6184ff00: [2019-08][ci] Use Xcode11.1 and 11.2beta2 for XI/XM Mono SDK builds (#17324)
* mono/mono@8969f2cc: [2019-08] [merp] Include any managed methods in the 'unmanaged_frames portion …
=> Bump to mono/mono/2019-98@baa12e5d

build-tools/automation/azure-pipelines.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3177751
Context: https://github.com/xamarin/designer/pull/2269
Custom control designer tests have recently started failing against
xamarin-android/d16-4 due to changes in designer/master. We should ensure
that our release branches are tracking the correct test sources, as
breaking changes can be expected when testing older release branches
against ongoing changes in master.
=> [tests] Use d16-4 designer source on d16-4

src/Mono.Android/Test/System/AppDomainTest.cs
Context: https://github.com/xamarin/xamarin-android/issues/1536
Context: https://dev.azure.com/devdiv/DevDiv/_releaseProgress?_a=release-environment-extension&releaseId=484122&environmentId=2423388&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab
Introduces a new test category which can be used to ignore unit tests
that aren't compatible with Hybrid AOT.
=> [tests] Introduce 'HybridAotNotWorking' category

build-tools/xaprepare/xaprepare/Application/Utilities.cs, build-tools/xaprepare/xaprepare/Steps/Step_Android_SDK_NDK.cs, build-tools/xaprepare/xaprepare/Steps/Step_DownloadMonoArchive.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallCorrettoOpenJDK.cs, build-tools/xaprepare/xaprepare/Steps/Step_PrepareBundle.cs, build-tools/xaprepare/xaprepare/ToolRunners/SevenZipRunner.cs
In order to make builds faster, we're going to remove downloaded archive
verification step. The way the verification works is basically unpack the
archive without writing its contents to disk, merely calculating the checksum.
In effect, the time it takes to verify is just slightly less than it takes to
actually unpack the archive. Removing the verification step appears to give us
~6 minutes back on Azure builds for the **prepare** target and just above 1 minute 
for the **prepare -> bundle** stage.
=> Disable archive verification in xaprepare

.external
Changes: https://github.com/mono/mono/compare/baa12e5d2405fc81195817638983ba7d6d8330f2...8946e49a974ea8b75fe5b8b7e93ffd4571521a85
Context: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1005448
Context: https://github.com/mono/mono/issues/17084
* mono/mono@8946e49a: (origin/2019-08) Added SR.missing from original backport
* mono/mono@5c784c97: Bump to mono/corefx@fb41040
* mono/mono@fdb70490: Revert "[2019-08] rollback msbuild/roslyn updates for a preview" (#17543)
* mono/mono@92a17792: [2019-08] [debugger] Changing how debugger handles exception ... (#17524)
* mono/mono@1b2e536b: [2019-08] rollback msbuild/roslyn updates for a preview
* mono/mono@ec4ef9bc: Bump roslyn-binaries to get roslyn 3.4.0-beta3-19521-01
* mono/mono@cc8deca9: Bump msbuild to pick up sdks+roslyn updates
* …
=> Bump to mono/mono/2019-08@8946e49a

build-tools/cmake/xa_macros.cmake, src/monodroid/CMakeLists.txt
GNU assembler (`as`) shipped with MinGW 6.0.0-3 on Ubuntu 19.10 (but possibly
other Linux distributions as well) does not recognize the `--noexecstack`
parameter we've been using so far. However, it (and all other versions) is fine
with the `-noexecstack` form. Use the single dash form in all cases.
=> Fix build failure with some versions of GNU assembler

tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs, tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs
The `TargetsSkipped` had some code which was using the `b.RunningMSBuild` code. This is weird since we ALWAYS use MSBuild now. This test was also randomly failing because the target was being skipped when it was expected to run (according to the test). However this looks like a bug in the test itself which was trying to verify old behaviour which has since changed. 
So we need to update the test to verify the correct behaviour. In this case the `CoreCompile` target SHOULD be skipped. 
This PR is also addressing an issue where the deployment tests were leaving directories in place even though the test passed. This was due to the directory checks NOT including the required `Root` path information.
=> Fix weird `TargetsSkipped` test failure. 

Documentation/guides/messages/xa2001.md, src/Xamarin.Android.Build.Tasks/Tasks/AndroidUpdateResDir.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/AndroidComputeResPathsTests.cs
I found a performance problem in a project containing:
<AndroidResource Include="Resources\layout\noexist.xml" />
What happens in this case, is on every build you get:
Building target "_CompileResources" completely.
Input file "Resources\layout\noexist.xml" does not exist.
Building target "_UpdateAndroidResgen" completely.
Input file "Resources\layout\noexist.xml" does not exist.
Effectively, even builds with no changes will always run expensive
`aapt` calls...
But we should just emit an error here! That would match more in-line
with what the `<Csc/>` MSBuild task gives for missing C# files.
An example of a non-existent C# file:
CSC : error CS2001: Source file 'C:\src\xamarin-android\samples\HelloWorld\noexist.cs' could not be found.
Giving a similar `XA2001` error …
=> [Xamarin.Android.Build.Tasks] non-existent @(AndroidResource) files should error

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/Tasks/CollectNonEmptyDirectories.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsMapsApplicationProject.cs
Context: https://github.com/xamarin/GooglePlayServicesComponents/pull/271
In an application with Google Play Services, a json configuration file
is used, such as:
<GoogleServicesJson Include="google-services.json" />
There are MSBuild targets in the NuGet package that process this file,
and add to the `@(LibraryResourceDirectories)` item group:
https://github.com/xamarin/GooglePlayServicesComponents/blob/fc057c754e04d3e719d8c111d03d60eb2467b9ce/source/com.google.android.gms/play-services-basement/merge.targets#L44-L80
Unfortunately, this causes MSBuild targets to run every time if
`$(AndroidUseAapt2)` is `True`:
Building target "_ConvertLibraryResourcesCases" completely.
Input file "obj\Debug.stamp" does not exist.
Such a project will run `aapt2` every time, even with no changes.
The …
=> [Xamarin.Android.Build.Tasks] fix aapt2 incremental build for GPS

Documentation/guides/BuildProcess.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/MaxPathTests.cs
Changes: https://github.com/xamarin/java.interop/compare/73096d9...baf43b0
Bumping for removal of `PackageNamingPolicy.LowercaseMD5`.
Other changes:
* In `MaxPathTests` we improved `MAX_PATH` the limit by 6 characters
for "Hello World". Xamarin.Forms projects did not have an
improvement, however; a non-Java stub file is hitting the limit.
* Other tests using `PackageNamingPolicy.LowercaseMD5`, I switched to
use `PackageNamingPolicy.Lowercase` instead.
=> Bump to xamarin/java.interop/master@baf43b0

Documentation/guides/MSBuildBestPractices.md
It's not really clear cut that you shouldn't, and also there's `MSBuildLastTaskResult` 
which can help in the mentioned scenarios too.
=> De-emphasize the guideline against Before/After targets

build-tools/Xamarin.Android.Tools.BootstrapTasks/result-packaging.targets
Context: https://build.azdo.io/3197067
We noticed we were missing `.binlog` files produced by the step:
https://github.com/xamarin/xamarin-android/blob/7c7177f7563d43e2a533768c054bf5663ba131c1/build-tools/automation/yaml-templates/apk-instrumentation.yaml#L18
In 936459c00, I accidentally broke this. We need to include any `*log`
files in the top `TestRelease` directory, not just the ones inside
`TestRelease/temp`.
=> [build] include *log files from the Test$(Configuration) directory

build-tools/Xamarin.Android.Tools.BootstrapTasks/result-packaging.targets, build-tools/automation/azure-pipelines.yaml, tests/CodeBehind/UnitTests/BuildTests.cs, tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/BuildTests.cs, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/BuildTests.cs
Context: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3196159&view=artifacts
I recently noticed the `win-build-test-results` artifact that we were
uploading was enormous, even when all tests had passed. This was due to
the fact that we weren't cleaning up after successful tests from the
`CodeBehind`, `CodeGen-MkBundle`, and `EmbeddedDSOs` suites. I've also
updated our `result-packaging` globbing to exclude NuGet packages from
our test result zips to further reduce unnecessary uploading.
This also identified an issue in our test execution. The three suites
mentioned above are not running in any test stages against an installer.
To address this our build pipeline has been updated to ensure these
assemblies are built and uploaded during the `Mac Build` job, and then
downloadedd …
=> [tests] Build, run, and clean up missing test suites

build-tools/Xamarin.Android.Tools.BootstrapTasks/result-packaging.targets
Expanding upon 4d2ac4ae, we should archive `.apk` files as well.
This will be useful for the current mono/2019-10 bump.
=> [build] include *.apk files from the bin\Test$(Configuration) directory

src/OpenTK-1.0/OpenTK.csproj, src/Xamarin.Android.NUnitLite/Xamarin.Android.NUnitLite.csproj
Shush 60 useless warnings about invalid or missing XML docs in 3rd party
projects we use. Go down to 937 from 997.
=> Make build quieter by 60 warnings.

build-tools/automation/azure-pipelines.yaml, tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs, tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
A new set of tests to catch regressions in build performance. They
would likely catch a bug where we accidentally caused MSBuild targets
to run when they shouldn't.
In a previous build, these tests passed while using `[Repeat(10)]`:
https://build.azdo.io/3193441
Hopefully, this means they will be stable (not flaky) going forward.
Cases we are now testing:
- Build with no changes
- Build with C# change
- Build with AndroidResource change
- Build with Android designer change (call designer's MSBuild targets)
- Build with XAML change & *no* reference assemblies
- Build with XAML change & reference assemblies
- Build with new `Java.Lang.Object`
- Build with `csproj` change
- Install with C# change
- Install with XAML change & reference assemblies
These run on on the MSBuild Device tests on …
=> [tests] MSBuild performance regression tests

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-installer.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3206030&view=logs&j=035e6729-702a-53d4-bea9-761745a9f552&t=a8982860-1b1b-5e3d-f0c9-54fa4d7fb67c&l=160
I had a PR build, where it appeared the MSBuild tests on Windows did
not have my changes.
Then I noticed on the provisioning step:
Visual Studio extension Xamarin.Android.Sdk 10.2.99.6: already provisioned
We should use the `-f` option when provisioning Xamarin.Android, as a
build machine could have the same version number installed from a
different PR.
We should *not* use the `-f` option when running the provisioning for
the Designer & Regression tests, since they provision things other
than Xamarin.Android. The Designer & Regression tests *do* call
`run-installer.yaml` to provision Xamarin.Android, however.
=> [build] use -f for all provisioning commands

build-tools/cmake/xa_macros.cmake, src/monodroid/jni/android-system.cc, src/monodroid/jni/embedded-assemblies-zip.cc, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/timing.hh
Desktop compilers mis-detect memory allocation size in our bundled property
code if fortified version of `strncpy` is used (even though the size
calculation is correct). Use `memcpy` instead.
LTO doesn't appear to be ready for use just yet. It gives warnings similar to
these:
jni-wrappers.hh(143,41): warning GD616DC71: argument 1 value ‘18446744073709551615’ exceeds maximum object size 9223372036854775807
util.cc(75,8): warning GA5933D32: ‘MEM[(struct timing_point *)&partial_time].ns’ may be used uninitialized in this function [-Wmaybe-uninitialized]
Which, even though well-intentioned (and, technically, correct) are irrelevant
in our case and the compiler+linker diagnostics fail to understand the intention
and usage of the code.
Additionally, fix a few instances where type conversion is …
=> [C++ification] Take care of a few warnings and don't use LTO

.external
Changes: https://github.com/mono/mono/compare/8946e49a974ea8b75fe5b8b7e93ffd4571521a85...e1ef774391da2b84d003431e8871b0bacbd25cb3
Context: https://github.com/mono/mono/issues/17133
* mono/mono@e1ef774391d: [2019-08] Bump CoreFX to pickup corefx PR #367 to fix #17133. (#17622)
* mono/mono@6d1f88e0ad2: Bump msbuild to get SDK updates from https://github.com/mono/msbuild/pull/150
* mono/mono@a3f3bfc4c3d: Bump nuget to the latest suggested version
* mono/mono@9bd3079f1ca: [2019-08] bump msbuild with more p2 packages
* mono/mono@6ac1ff75a27: [dim][regression] Explicit interface override (#17583) (#17627)
* mono/mono@a119807a015: [acceptance-tests] Bump mono/roslyn to get build fix
* mono/mono@d234d34b700: [2019-08][merp] Install sigterm handler in EnableMicrosoftTelemetry
* …
=> Bump to mono/mono/2019-08@e1ef7743

build-tools/automation/azure-pipelines.yaml
We have a very weird issue when running MSBuild
Unit tests on Mojave. For some reason which is
still unknown to us, libzip creates a corrupt
zip file. This then causes a `zipalign` error
later in the build process. This only seems to
happen on Mojave in Azure. It does not appear
to happen locally.
So this PR switches the MSBuild tests back to using
the `$(HostedMac)` pool. This should give us greener
builds while we try to figure out what the issue is.
=> [build-tools] Dont use Mojave for Unit Tests

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/3804
Reviewing our App Bundle implementation, there were two things missing:
* An unsigned app bundle in `$(OutputPath)`. This is useful when
calling the `PackageForAndroid` target, and signing is done manually
some point later.
* No support for `$(MonoSymbolArchive)=True` to generate the `.mSYM`
symbols.
The only changes needed to make these work, was to refactor the
`_CopyPackage` MSBuild target so it knows about App Bundles.
I also created an `$(_MSYMDirectory)` property, to simplify usage of:
`$(OutDir)$(_AndroidPackage).$(AndroidPackageFormat).mSYM`
I updated some tests in `PackagingTest.cs`, to verify the `.mSYM`
directory for both `.apk`'s and `.aab`'s.
=> [Xamarin.Android.Build.Tasks] App Bundle support for PackageForAndroid

src/r8/.gitignore
When I open xamarin-android in VS Code, the Java plugin creates directories where it finds gradle projects. Since r8 uses gradle, we should add to its `.gitignore`.
=> [r8] update .gitignore

build-tools/Xamarin.Android.Tools.BootstrapTasks/result-packaging.targets, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/apk-instrumentation.yaml
In 22de1178, it did not actually archive *all* `.apk` files.
Throughout our build pipeline, we build projects with different
MSBuild properties as input such as `/p:AotAssemblies=True`. This
causes the `.apk` files to be overwritten, and we lose them...
Instead, we should copy each APK to a directory inside
`$(Build.ArtifactStagingDirectory)` with a path identifying.
And so I propose modifying the template such as:
- template: yaml-templates/apk-instrumentation.yaml
parameters:
configuration: $(ApkTestConfiguration)
testName: Mono.Android_Tests-Aot
project: src/Mono.Android/Test/Mono.Android-Tests.csproj
testResultsFiles: TestResult-Mono.Android_Tests-$(ApkTestConfiguration)-Aot.xml
extraBuildArgs: /p:AotAssemblies=True /p:EnableLlvm=True
artifactName: Mono.Android_Tests-Signed.apk …
=> [build] archive APKs/AABs in yaml

tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
Context: https://build.azdo.io/3218699
Context: https://build.azdo.io/3219042
Raising some of the expected times, as we have seen some random
failures that do not appear to be performance regressions.
The assertion failures were:
Build_No_Changes: Exceeded expected time of 3250ms, actual 3270ms
Build_AndroidResource_Change: Exceeded expected time of 4750ms, actual 4770ms
Build_XAML_Change(True,False): Exceeded expected time of 6250ms, actual 6270ms
Build_XAML_Change(False,False): Exceeded expected time of 9500ms, actual 9560ms
=> [tests] MSBuild performance raise expected times by 100ms

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Designer.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs
I was doing some review of the MSBuild targets that run when you save
an axml file. The first thing I found was:
Building target "_GeneratePackageManagerJavaForDesigner" completely.
Output file "obj\Debug\100\android\src\mono\MonoPackageManager.java" does not exist.
This MSBuild target was running every time that
`SetupDependenciesForDesigner` runs.
We no longer generate `MonoPackageManager.java` at all, so instead:
* Look for `MonoPackageManager_Resources.java`, which actually exists.
* Use `$(_AcwMapFile)` instead of the typemaps, since the designer
actually uses that file. In some cases the typemaps aren't generated
either.
These changes improve `SetupDependenciesForDesigner` by about 500ms on
a small app.
=> [Xamarin.Android.Build.Tasks] fix _GeneratePackageManagerJavaForDesigner

src/monodroid/CMakeLists.txt
`libxamarin-debug-app-helper.so` is a shared library used only for Debug
Xamarin.Android applications to set up the debugging environment, amongst others
to copy the fast-deployed shared libraries from the override directories to an
internal location where we're allowed to use `dlopen` to load the DSOs.
The library used to be built twice (like our runtime), but unlike the runtime it
was copied to the same location and, with Release being built second, the
release version replaced the debug one resulting in a library that does not
include the necessary code to set up the scenario described above.
Fix the issue by building the library only in Debug configuration.
=> Build only Debug configuration of libxamarin-debug-app-helper.so

src/monodroid/jni/basic-android-system.cc
Context: https://github.com/xamarin/xamarin-android/pull/3759
Context: https://github.com/xamarin/xamarin-android/commit/6d857597187e42d0e7190dfdb61d259e4bac409a#diff-e99739c16155208685952aa52870d4cdL33-L39
When switching from C-style `xcalloc` to C++-style `new` I failed to use the
proper type to allocate array which holds directories where Android placed the
APK files of the application. This mistake manifested itself only when using
AppBundles, which is where we allocate more than one entry of the array. The
resulting error was the following runtime exception:
11-04 12:27:55.722  3339  3339 E mono    : Unhandled Exception:
11-04 12:27:55.722  3339  3339 E mono    : System.DllNotFoundException: __Internal assembly:<unknown assembly> type:<unknown type> member:(null)
11-04 12:27:55.722 …
=> Allocate directory array with correct type

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Context: https://developer.android.com/studio/build/shrink-code#configuration-files
Fixes: http://work.azdo.io/825420
Fixes: https://github.com/xamarin/xamarin-android/issues/3636
Let's say you used the following code fragment in an Android layout:
<android.support.v7.widget.Toolbar />
Currently, you would need to add a ProGuard rule regardless if you
were using ProGuard or R8.
Fortunately, `aapt2` has a command-line switch:
> aapt2 link -h
...
--proguard arg    Output file for generated Proguard rules.
According to the Google docs for R8:
AAPT2 generates keep rules based on references to classes in your
app’s manifest, layouts, and other app resources. For example, AAPT2
includes a keep rule for each Activity that you register in your app’s
manifest as an entry point.
I added a new …
=> [Xamarin.Android.Build.Tasks] use aapt2 option to generate proguard rules

build-tools/manifest-attribute-codegen/manifest-definition.xml, src/Xamarin.Android.Build.Tasks/Mono.Android/ServiceAttribute.Partial.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocumentElement.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.NamingCustomAttributes/Android.App/ServiceAttribute.cs
Our tools currently do not automatically add new manifest properties.
Manually adding ForegroundServiceType property to ServiceAttribute class
Tracking issue: https://github.com/xamarin/xamarin-android/issues/3712
=> Fix: ServiceAttribute is missing foregroundServiceType

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
I spent a little time looking at build logs of design-time builds
inside VS Windows. To trigger these, I was editing an `.axml` file and
saving it.
I found some perf issues...
The first thing I noticed was that `_ResolveLibraryProjectImports`
runs on every DTB:
Building target "_ResolveLibraryProjectImports" completely.
Input file "obj\Debug\100\designtime\build.props" is newer than output file "obj\Debug\100\stamp\_ResolveLibraryProjectImports.stamp".
Then I looked at how `build.props` was actually changing between
different targets such as:
* `UpdateGeneratedFiles` - the general DTB target
* `SetupDependenciesForDesigner` - the Android designer runs this
target
Comparing the files, I saw this difference:
```diff
- AndroidSdkPath = C:\Program Files (x86)\Android\android-sdk
+ …
```
=> [Xamarin.Android.Build.Tasks] DTBs and _ResolveLibraryProjectImports

Documentation/guides/BuildProcess.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/MaxPathTests.cs
Backport of 27ec4988
Test changes for removal of `PackageNamingPolicy.LowercaseMD5`.
* In `MaxPathTests` we improved `MAX_PATH` the limit by 6 characters
for "Hello World". Xamarin.Forms projects did not have an
improvement, however; a non-Java stub file is hitting the limit.
* Other tests using `PackageNamingPolicy.LowercaseMD5`, I switched to
use `PackageNamingPolicy.Lowercase` instead.
=> Backport of 27ec4988

build-tools/automation/azure-pipelines.yaml
The `VSEng-MicroBuildVS2019` pool is currently overloaded, so a new
`VSEng-Xamarin-Android` Windows machine pool has been set up for us to
migrate to. The configurations of these machines should be identical as
far as we're concerned. This pool currently has 5 agents configured,
however we should be able to increase capacity as needed.
=> [CI] Move Azure Pipelines Windows jobs to new pool

Documentation/guides/BuildProcess.md, build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Tasks/GetAndroidActivityName.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Application.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Add new `Run` target to start the app activity on the device/emulator
Add new `GetAndroidActivityName` task to retrieve the activity name
from the manifest file
Add new `Xamarin.Android.Application.targets` file for application
specific targets and import it conditionaly into the
`Xamarin.Android.Common.targets`.
=> [Xamarin.Android.Build.Tasks] Add Run target

.external, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks.csproj, build-tools/Xamarin.Android.Tools.BootstrapTasks/packages.config, build-tools/xaprepare/xaprepare/ThirdPartyNotices/LibZipSharp.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/packages.config, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/packages.config, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/packages.config, src/Xamarin.Android.Tools.JavadocImporter/Xamarin.Android.Tools.JavadocImporter.csproj, src/Xamarin.Android.Tools.JavadocImporter/packages.config, tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/Xamarin.Android.MakeBundle-UnitTests.csproj, tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/packages.config, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/EmbeddedDSO-UnitTests.csproj, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/packages.config, tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj, tests/MSBuildDeviceIntegration/packages.config
Fixes an issue where the Linux native binaries were inverted i.e 32bit in x64 and 64bit in x86.
=> Bump LibZipSharp to 1.0.6

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildOutput.cs
This commit adds some helper methods which will pull
out Task and Target timings from the PerformanceSummary
of a build log.
It also picks up the data from `adb logcat` which tells
us how long it took for the app to start.
These methods will be used in future tests.
=> [Xamarin.Android.Build.Tests] Add some additional helper methods.

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Designer.targets, src/Xamarin.Android.Build.Tasks/Tasks/DetermineJavaLibrariesToCompile.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Expanding upon 1a61fa81, I found some more MSBuild item groups that we
could remove all usage of:
* `@(_AdditionalJavaLibraryReferences)`
* `@(_AdditonalAndroidResourceCachePaths)`
The `<GetAdditionalResourcesFromAssemblies/>` used to populate these
item groups, but it is now removed.
We can remove any MSBuild logic using these item groups.
=> [Xamarin.Android.Build.Tasks] more deprecated code removal

Documentation/building/windows/dependencies.md
Looks like the development tools are now called SDK in the installer.
Also remove the mention of Oracle JDK as it is not needed anymore.
Update also the .NET Core versions as I  don't see .NET Core 2.0 SDK
in the VS2019 installer anymore.
=> [Documentation] Update Windows build deps

src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs, src/Xamarin.Android.Build.Tasks/Utilities/ResourceDesignerImportGenerator.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
I noticed the `<GenerateResourceDesigner/>` MSBuild task had a couple
things we could change to speed it up:
* Use System.Reflection.Metadata instead of Mono.Cecil
* Only look at "MonoAndroid" assemblies, so we don't have to load the
BCL or NetStandard assemblies.
* Remove System.Linq usage in favor of `foreach`
The SRM port was straightforward, as the code only needs to look at
type and field names.
I could also simply use `@(_MonoAndroidReferencePath)` over
`@(_ReferencePath)`.
However, I had to split up `@(_MonoAndroidReferencePath)` and include
`@(_ReferenceDependencyPaths)` in a new item group:
`@(_MonoAndroidReferenceDependencyPaths)`.
Otherwise, this test case failed:
App -> LibraryA -> LibraryB
The app's `Resource.designer.cs` was attempting to set values in
LibraryB, even though …
=> [Xamarin.Android.Build.Tasks] use SRM for <GenerateResourceDesigner/>

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Designer.targets, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
When editing `AndroidResource` files and saving in the IDE, I noticed
that `_GenerateJavaStubs` always runs.
It doesn't seem like we actually need to do that?
The value for `Inputs` makes sense when you look at how the task is
called:
<Target Name="_GenerateJavaStubs"
Inputs="$(MSBuildAllProjects);@(_ResolvedUserMonoAndroidAssemblies);$(_AndroidManifestAbs);$(_AndroidBuildPropertiesCache);@(_AndroidResourceDest)">
<GenerateJavaStubs
...
ResourceDirectory="$(MonoAndroidResDirIntermediate)"
/>
</Target>
But looking closer, the `ResourceDirectory` is not even used by
`<GenerateJavaStubs/>`. It seems like we can just remove the
`@(_AndroidResourceDest)` item group from the list of `Inputs`.
Testing an `AndroidResource`-change in the Toggl app: …
=> [Xamarin.Android.Build.Tasks] AndroidResource changes do not affect _GenerateJavaStubs

Documentation/guides/BuildProcess.md, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Application.targets
Add new target to stop the app package on the device/emulator.
Add documentation for the new target
This is one of the steps needed for [recording AOT profiles][1]. It is
also useful for scripts to measure the app performance on a
device or an emulator.
[1]: https://github.com/xamarin/xamarin-android/issues/3792
=> [Xamarin.Android.Build.Tasks] Add StopAndroidPackage target

Configuration.props
Recently I run into missing AOT cross compilers after successful
build.
Turned out the prepare step (`make prepare`) uses
`$(AndroidSupportedTargetAotAbis` value and it wasn't set on my
system.
Not sure why it was working before for me (maybe I had
`Configuration.Override.props` in place?), but now when the AOT is
non-enterprise feature, we should set that.
This is how part of my prepare step looked like:
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Configured targets
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Enabled Mono Android runtime ABIs:
* armeabi-v7a
* arm64-v8a
* x86
Enabled Mono host runtimes:
* Darwin
Enabled Mono cross compilers:
NONE
Enabled LLVM cross compilers:
NONE
=> Set the default $(AndroidSupportedTargetAotAbis) value

Documentation/guides/BuildProcess.md, Documentation/release-notes/3935.md, src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
The `ExtraAotOptions` parameter of Aot task was not used in our
targets. It was also added with comma as separator, which doesn't make
sense.
Make it possible to set by `$(AndroidExtraAotOptions)` property.
With these changes it can be used for example to get more information
from the mono aot compiler by adding `--verbose` option.
Like:
xabuild /t:Clean\;SignAndroidPackage /p:Configuration=Release /v:diag /p:AndroidExtraAotOptions=--verbose /p:AndroidEnableProfiledAot=true my.csproj
where the output contains:
[AOT] MONO_PATH="/Users/rodo/Projects/xatemplateaot/xatemplateaot/obj/Release/android/assets/shrunk" MONO_ENV_OPTIONS="" /Users/rodo/git/xa-master/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Darwin/cross-x86 --response=obj/Release/aot/x86/System.dll/response.txt …
=> [aot] Make ExtraAotOptions parameter useful

src/monodroid/jni/debug.cc
This adds a useful timing message for Debug builds:
11-20 16:05:55.683 10984 10984 I monodroid-timing: start_debugging_and_profiling; elapsed: 2s:0::94210
If it really takes 2 seconds like this, it should be easier for us to spot going forward.
=> [monodroid] add timing message for the debugger

src/monodroid/jni/android-system.cc
Context: https://github.com/xamarin/xamarin-android/pull/3940#issuecomment-556147250
The check for unknown AOT mode was inverted. Fix by using the correct,
inequality, operator.
=> Fix invalid AOT mode reporting code

src/monodroid/jni/debug.cc, src/monodroid/jni/debug.hh
In a Debug build of `samples/HelloWorld`, startup was taking way longer
than a Release build:
Debug build:
ActivityTaskManager: Displayed com.xamarin.android.helloworld/example.MainActivity: +2s689ms
Release build:
ActivityTaskManager: Displayed com.xamarin.android.helloworld/example.MainActivity: +678ms
In this case I was launching the app with no debugger attached. Why is
it *so* much slower?
Reading through `debug.cc` and the `start_connection` method, the
return values and comments did not quite match up--or make sense.
It seemed that even though `conn_port` is 0, it was trying to connect
the debugger? I believe this check needed to actually return 2:
if (!conn_port)
return 0;
I changed this line, and reworked things to use an `enum` instead of
an `int`. Everything seems clearer now. …
=> [monodroid] don't start the debugger if not configured

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/apk-instrumentation.yaml, src/monodroid/jni/basic-utilities.cc, src/monodroid/jni/debug-app-helper.cc
Override directories must be set up both in the debug app helper and the
monodroid runtime as both of them are loaded separately and they do not depend
on each other. This fixes loading of the side loaded shared libraries from the
internal location where they are copied from the override directories.
=> Fix fastdev library side loading

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
In bf4c3781, we added a warning to detect parallel builds on the same
Xamarin.Android project. This was meant to be a feature for finding
bugs in the IDEs.
However, there appears to be a case this is causing a lot of noise in
Visual Studio for Windows:
1. The user hits F5 / or the play button
2. The IDE runs a build and gets a status back it was successful.
3. The IDE runs the `Install` target.
On step 3, we are randomly getting the warning?
Xamarin.Android.Common.targets(404,3): warning XA5302: Two processes may be building this project at once. Lock file exists at path: obj\Debug\90\.__lock
It appears that VS is getting a result that the build is finished, but
MSBuild has not cleaned up all `RegisterTaskObject`'s with a `Build`
lifetime: …
=> [Xamarin.Android.Build.Tasks] skip _WriteLockFile by default

src/monodroid/jni/debug.cc
In a26e0dbf, I fixed a 2 second delay on startup, which was somewhat
perplexing... It helped by 2 seconds regardless if a debugger was
present or not.
It turned out that a `""` returned from `monodroid_get_system_property`
was the actual root cause of the issue. Luckily, this issue was only
present on d16-5 and master.
We think checking the return value of `monodroid_get_system_property`
is most appropriate. I changed this call to look the same as the rest
of the calls in `monodroid`.
=> [monodroid] check return value of monodroid_get_system_property

build-tools/debian-metadata/rules
Ought to resolve `dpkg-shlibdeps: error: cannot find library libcrypto.so.1.1 needed by debian/xamarin.android-oss/usr/lib/xamarin.android/xbuild/Xamarin/Android/libzip.so (ELF format: 'elf32-i386' abi: '0101000300000000'; RPATH: '')`
=> Delete 32-bit libzip.so, as the package is pure x64 only.

src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/monodroid/jni/monodroid-glue.cc
I was profiling an app's startup in `Debug` mode, and I saw it
printing a lot of stuff:
11-22 15:01:30.994  5616  5616 I monodroid-assembly: Trying to load shared library '/data/user/0/com.xamarin.android.helloworld/files/.__override__/libaot-HelloWorld.dll.so'
11-22 15:01:30.994  5616  5616 I monodroid-assembly: Shared library '/data/user/0/com.xamarin.android.helloworld/files/.__override__/libaot-HelloWorld.dll.so' not found
11-22 15:01:30.994  5616  5616 I monodroid-assembly: Trying to load shared library '/storage/emulated/0/Android/data/com.xamarin.android.helloworld/files/.__override__/libaot-HelloWorld.dll.so'
11-22 15:01:30.994  5616  5616 I monodroid-assembly: Shared library '/storage/emulated/0/Android/data/com.xamarin.android.helloworld/files/.__override__/libaot-HelloWorld.dll. …
=> [monodroid] set MONO_AOT_MODE_NONE when AOT is off

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
In the case where `$(AndroidLinkMode)` is not `None`, we run a
`<RemoveRegisterAttribute/>` to remove all `[Register]` attributes
from `Mono.Android.dll`. This is a step to save on APK size.
However, we found that the AOT compiler is seeing *two*
`Mono.Android.dll` files:
* obj\Debug\android\assets\Mono.Android.dll
* obj\Debug\android\assets\shrunk\Mono.Android.dll
@vargaz pointed out that this is bad, some of the AOT images will be
linked against the wrong one and fail to load at runtime. We could
possibly be silently falling back to the JIT...
I first attempted to just remove the `shrunk` directory and write
`Mono.Android.dll` *in place*. This idea didn't pan out:
https://github.com/xamarin/xamarin-android/pull/3925#issuecomment-557566329
That idea broke incremental builds... So the …
=> [Xamarin.Android.Build.Tasks] copy all assembles to android/assets/shrunk

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Context: https://build.azdo.io/3267504
We have seen a random failure such as:
/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/NuGet.targets(123,5): error : Could not find file '/Users/runner/.nuget/packages/xamarin.android.support.constraint.layout.solver/1.0.2.2/63mg83ek.7t8'.
Normally, we just add `[NonParallelizable]` to workaround problems
like this.
=> [tests] add [NonParallelizable] to CheckLintErrorsAndWarnings

build-tools/automation/azure-pipelines.yaml
* xamarin/java.interop@dec2e39: Convert Test projects to SDK style projects. (#517)
* xamarin/java.interop@439bd83: [XA.Tools.Bytecode] Add Kotlin support to our binding process. (#505)
* xamarin/java.interop@5fa8c18: [Java.Interop] Replace Gendarme with Roslyn FxCop Analyzers (#523)
* xamarin/java.interop@7558ca1: Bump to mono/cecil/master@a6a7f5c0 (#524)
=> Bump to xamarin/java.interop@dec2e390

tools/xabuild/SymbolicLink.cs, tools/xabuild/XABuild.cs, tools/xabuild/XABuildPaths.cs
Context: https://github.com/xamarin/xamarin-android/pull/3393/files
Builds for PR #3393 were failing on Windows because
`Microsoft.Portable.CSharp.targets` couldn't be found:
> bin\Debug\bin\xabuild /bl Xamarin.Android-Tests.sln
...
...\xamarin-android\external\Java.Interop\lib\mono.linq.expressions\Mono.Linq.Expressions.csproj(108,3):
error MSB4019: The imported project "...\xamarin-android\bin\Debug\lib\xamarin.android\xbuild\Microsoft\Portable\v4.0\Microsoft.Portable.CSharp.targets"
was not found. Confirm that the path in the <Import> declaration is
correct, and that the file exists on disk.
Turns Out that there are *multiple* `Microsoft` directories of
consequence, and we need *all* of them to build, including:
* `%ProgramFiles(x86)%\Microsoft Visual Studio\2019\*\MSBuild\Microsoft`
* …
=> [xabuild] Find Microsoft.Portable.CSharp.targets

src/monodroid/jni/embedded-assemblies-zip.cc, src/monodroid/jni/embedded-assemblies.cc, src/monodroid/jni/embedded-assemblies.hh, src/monodroid/jni/monodroid-glue.cc
I was noticing a lot of logging like this:
11-25 13:14:59.430 13111 13111 I monodroid-assembly: open_from_update_dir: trying to open assembly: /data/user/0/com.xamarin.android.helloworld/files/.__override__/mscorlib.dll
11-25 13:14:59.431 13111 13111 I monodroid-assembly: open_from_update_dir: trying to open assembly: /storage/emulated/0/Android/data/com.xamarin.android.helloworld/files/.__override__/mscorlib.dll
11-25 13:14:59.431 13111 13111 I monodroid-assembly: open_from_update_dir: trying to open assembly: /data/user/0/com.xamarin.android.helloworld/files/.__override__/mscorlib.dll.dll
11-25 13:14:59.431 13111 13111 I monodroid-assembly: open_from_update_dir: trying to open assembly: /storage/emulated/0/Android/data/com.xamarin.android.helloworld/files/.__override__/mscorlib.dll.dll …
=> [monodroid] don't probe for .exe files

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-nunit-tests.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3260689&view=logs&j=035e6729-702a-53d4-bea9-761745a9f552&t=282d23f1-1559-55a2-a4d2-5ec0512e57b5&l=3323
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3263297&view=logs&j=cac0e8d3-0ef5-5d2b-b57e-e8fde7204df3&t=e6feceab-89bf-416f-a5f8-0254f16ee003&l=10
We've been seeing cases where if tests timeout on Windows, then
processes remain running.
This causes various problems, such as:
1) Zipping the build artifacts fails with file-sharing issues:
```
build-tools\Xamarin.Android.Tools.BootstrapTasks\result-packaging.targets(72,5): Error MSB3027:
Could not copy "E:\A\_work\3\s\bin\TestRelease\temp\BuildProguard Enabled Project(1)Falsedx\obj\Debug\android\bin\classes\mono\android\support\v4\view\accessibili …
```
=> [build] kill processes after test run

Documentation/release-notes/3958.md
Missing docs for: https://github.com/xamarin/xamarin-android/pull/3958
=> [docs] release notes for PR 3958

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/designer/pull/2217
The designer repo has recently been updated to require authentication to
a couple of private NuGet feeds, and as a result our designer checks
have been failing during NuGet restore attempts.
We can fix this by passing auth tokens to provisionator so that they can
later be accessed during NuGet operations via the `Azure Artifacts
Credential Provider`. More information about this credential provider
can be found below:
https://github.com/microsoft/artifacts-credprovider#unattended-build-agents
https://github.com/xamarin/provisionator/commit/ed77b56d8ff4b8416248fb3c8cf6751be5809053
The variables referenced in these YAML changes come from a variable
group that has been added to our build pipelines: …
=> [ci] Set NuGet feed secrets for designer test jobs

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/clean.yaml, build-tools/automation/yaml-templates/kill-processes.yaml, build-tools/automation/yaml-templates/run-nunit-tests.yaml
Context: https://build.azdo.io/3281436
Expanding upon e608464d, let's disable the clean behavior provided by
Azure DevOps and clean ourselves. We have an opportunity to kill
processes this way.
Otherwise, we seem to be hitting this on every build now:
##[error]The process cannot access the file 'F:\A\xamarin-v000001-1\_work\2\s' because it is being used by another process.
I am also interested in what `Get-Process` will print here.
=> [build] clean directories ourselves on AzDO

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs, tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs
Context http://work.azdo.io//1009593
Both aapt and aapt2 will use overlay semantics when deciding
which final resource to use. The order in which the resources
are passed to the tooling is important.
For `aapt` the it used the FIRST item it came across, this is
why we always passed the Application resource directory in first.
For `aapt2` the LAST item is used... this is why we always pass
the Application resoruce directory last.
However we still use the same ordering for the references as
we do for `aapt`. As a result if you have duplicate resources
in two library projects `aapt` and `aapt2` will use different
files.
This PR reverses the order of the libraries we use for `aapt2`.
This ensures that the behaviour we see in `aapt2` is consistent
with `aapt`.
Future work we need to find a way …
=> [Xamarin.Android.Build.Tasks] Fix Library Resource ordering.

Documentation/guides/BuildProcess.md, src/Xamarin.Android.Build.Tasks/Tasks/AndroidCreateDebugKey.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/KeyToolTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
We have recently started to see the following error
```
rror ANDKT0000: keytool error: java.lang.Exception: Key pair not generated, alias <androiddebugkey> already exists
```
Looking at the logs, we see the following warning issued further up.
```
message ANDKT0000: androiddebugkey, Nov 25, 2019, PrivateKeyEntry, [/Users/runner/runners/2.160.1/work/1/s/bin/TestRelease/temp/CodeBehind/SuccessfulBuildFew/Release/CommonSampleLibrary/CommonSampleLibrary.csproj] (TaskId:476)
message ANDKT0000: Certificate fingerprint (SHA1): 8F:DE:A1:AF:26:8B:E7:02:4D:D0:57:86:F4:81:4F:B7:4A:80:60:AA [/Users/runner/runners/2.160.1/work/1/s/bin/TestRelease/temp/CodeBehind/SuccessfulBuildFew/Release/CommonSampleLibrary/CommonSampleLibrary.csproj] (TaskId:476)
message ANDKT0000: Warning: The JKS keystore uses a …
```
=> [Xamarin.Android.Build.Tasks] Use PKCS12 Key Store format

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Linux.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.MacOS.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Unix.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Windows.cs
Context: https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/change-log.html
Context: https://bugs.openjdk.java.net/browse/JDK-8152856
Context: https://bugs.openjdk.java.net/browse/JDK-8062808
Changes:
* 8.232.09.1 (Critical patch update)
* Update Corretto to 8.232.09.1, all platforms: update Corretto 8 patch set to 8.232.09.1. Update the security baseline to OpenJDK 8u232.
* Explicitly convert _lh_array_tag_type_value from unsigned to int, macOS: this is caused by the backport of JDK-8152856. It caused _lh_array_tag_obj_value being implicitly converted to unsigned int during the compilation.
* Turn on the -Wreturn-type warning, all platforms: this is a backport of JDK-8062808, which help catching missing return statements earlier in the development cycle.
* CVEs fixed:
* …
=> Update Amazon Corretto OpenJDK

src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ResourceDesignerImportGenerator.cs
Fixes #3808
Project Refernces can include [Aliases](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.projectreference.aliases?view=roslyn-dotnet).
```
<ProjectReference Include="..\LibraryA\LibraryA.csproj">
<Project>{A31DB667-7565-4C13-99CD-82064660960F}</Project>
<Name>LibraryA</Name>
<Aliases>LibA</Aliases>
</ProjectReference>
```
When using these users can no longer use the `global` keyword
to reference the types. So
```
global::LibraryA.Foo.Bar;
```
will become
```
LibA.LibraryA.Foo.Bar;
```
and an `extern alias LibA;` will need to be added at the very
top of the `.cs` file.
When doing this for a Xamarin.Android project we get the
following build error from the `Resource.designer.cs` file.
```
error CS0400: The type or namespace name 'LibraryA' could not be found in …
```
=> [Xamarin.Android.Build.Tasks] Handle Reference Aliases

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.D8.targets
Context: https://docs.microsoft.com/visualstudio/msbuild/createitem-task
CreateItem task
This task is deprecated. Starting with .NET Framework 3.5, item groups may be placed within Target elements.
The `<CreateItem/>` MSBuild task is deprecated, this removes all usage
of it in xamarin-android's targets we ship. I tried to make changes to
simplify `Condition`, and hopefully no actual behavior will be changed
here.
There may also be some light performance impact, in a build with no
changes in `samples\HelloWorld`:
20 ms  CreateItem                                39 calls
Time Elapsed 00:00:01.16
Now there are 0 calls. I suspect some of this time is merely moved
elsewhere, however...
MSBuild likely has some performance improvements to using
`<ItemGroup/>` over `<CreateItem/>`. I was also …
=> [Xamarin.Android.Build.Tasks] remove usage of <CreateItem/>

.external
Changes: https://github.com/mono/mono/compare/e1ef774391da2b84d003431e8871b0bacbd25cb3...bef1e6335812d32f8eab648c0228fc624b9f8357
Context: https://github.com/mono/mono/issues/17924
Context: https://github.com/mono/mono/issues/17931
* mono/mono@bef1e633581: [interp] track valuetype stack for CEE_RET too (#17998)
* mono/mono@56325f4097f: [arm] if mtriple is provided, do not set -march
* mono/mono@c4a1b40fbda: [2019-08] [runtime] Treat calling a non-virtual method through… (#17961)
* mono/mono@0c9250280da: [2019-08] bump msbuild+roslyn to track mono-2019-08 (#17954)
* mono/mono@14aac0c541c: Bump msbuild to track mono-2019-08 (#17854)
* mono/mono@a77128ca793: [merp] Remove extraneous waitpid invocation (#17762)
* mono/mono@296a9afdb24: [MacSDK] Bump xamarin-gtk-theme.py to latest revision …
=> Bump to mono/mono/2019-08@bef1e633

Documentation/guides/messages/xa2000.md, Documentation/release-notes/3974.md, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
Context:
https://github.com/xamarin/xamarin-android/issues/3912
https://github.com/xamarin/xamarin-android/issues/3845
Issue warning when non-product/non-SDK assembly uses
`System.AppDomain::CreateDomain` as app domains will be removed in
.NET5
The check is added to `FixAbstractMethodsStep`, so this way it is done
in both configurations, `Debug` and `Release`.
Add tests for both configurations.
=> Warn about AppDomain.CreateDomain usage

src/Mono.Android/Test/Mono.Android-Test.Shared.projitems, src/Mono.Android/Test/System.Drawing/TypeConverterTest.cs
Regression test for https://github.com/xamarin/xamarin-android/issues/3726
I originally planned to add this in Mono but it turns out it's more complicated there since we don't have a way to test this in our Android setup, so I decided to put it here :)
=> Add simple Drawing TypeConverter tests

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-nunit-tests.yaml
We've encountered numerous timeouts in our Windows build job when
executing the `RunNUnitTests` msbuild target. This timeout can result in
various file locking issues, as well as poor partial test result
reporting. To help address these two problems, we'll change the order of
test execution so that our short running test suites execute and publish
test results first. We'll also use the `run-nunit-tests` YAML template
to run the xamarin-android test suites. This template will run each test
assembly in separate powershell invocations as opposed to a batched
MSBuild target, which may result in fewer hangs. Finally, an unused
(and undefined) parameter has been removed from the `run-nunit-tests`
template.
=> [ci] Run Windows build tree tests with powershell

build-tools/xaprepare/xaprepare/Application/Context.cs, build-tools/xaprepare/xaprepare/Application/MonoRuntimesHelpers.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs, build-tools/xaprepare/xaprepare/Main.cs, build-tools/xaprepare/xaprepare/Steps/Step_DownloadMonoArchive.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallMonoRuntimes.cs, build-tools/xaprepare/xaprepare/ThirdPartyNotices/mono.cs
This change to `xaprepare` allows us to use a custom build of mono
along with a local xamarin-android build.
This adds a new switch to xaprepare, such as:
xaprepare --mono-archive-url=https://xamjenkinsartifact.azureedge.net/mono-jenkins/xamarin-android-test/android-release-Darwin-9bd1b2e065d8b1a8cfd21c8dc1821c89ad921eec.7z
This is a build of mono I built and uploaded using these instructions
on macOS:
https://github.com/mono/mono/blob/a2f9fb77a3704049ffe5de32362029ece154ee4c/sdks/README.md
With mono/master or 2019-12, I was hitting:
Step Xamarin.Android.Prepare.Step_ThirdPartyNotices failed:
License file external\mono\sdks\out\android-tpn\external\llvm\LICENSE.TXT does not exist
I made it probe for two different paths for `llvm` as the path has
changed: …
=> [xaprepare] add option for custom mono archive URL

src/monodroid/jni/debug.cc, src/monodroid/jni/debug.hh, src/monodroid/jni/logger.cc, src/monodroid/jni/monodroid-glue.cc
XA runtime supports setting the Mono debugger log level by setting the
`loglevel` option of the Mono runtime's `--debugger-agent` paremeter via the
`debug.mono.extra` system property (set by the IDEs). However, it turns out that
the IDEs (via AndroidTools) always set the log level to `0`. Fixing the issue
would require updates to AndroidTools and then IDEs, however.
To allow setting the debugger level without having to wait for the next IDE
release, this commit adds a new option to the `debug.mono.log` system property:
debugger-log-level=LEVEL
where `LEVEL` is a positive 32-bit signed integer or 0. This option will take
precedence when the level is set both in `debug.mono.extra` and `debug.mono.log`
system properties.
=> Add new `debugger-log-level` option to `debug.mono.log`

Documentation/guides/BuildProcess.md, Documentation/release-notes/3964.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Application.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/MSBuildDeviceIntegration/Tests/AotProfileTests.cs
Implements https://github.com/xamarin/xamarin-android/issues/3792
Add 2 targets to start and finish the profiling. The start target also
builds the project with embedded aot profiler and sets its
options. The finish one collects data from the device/emulator and
writes them to custom.aprof file with aprofutil tool.
Add documentation.
Add test.
Add `AndroidEmbedProfilers` to cached properties, to trigger
rebuild when changed.
Originally I wanted to have also single step process target, which
would use `duration=n` option of the aot profiler. After discussion with
@dellis1972, it looks like it might not be usable for IDEs as it might block
the UI thread. So I didn't implement that one.
Instead I might do it differently by introducing new task to watch for
activity displayed message in the …
=> Add new targets for AOT profiling

src/Xamarin.Android.Build.Tasks/Tasks/BuildAppBundle.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
AppBundles can support multiple modules. This PR adds
the ability to specify additional modules to the
`bundle-tool`. These options might be used in the
future to help support Dynamic features.
=> [Xamarin.Android.Build.Tasks] Add Ability to include additional Modules

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetStandard.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
Fixes #3920
In the bug report we had a situation we had not come across before. The assembly 
in the `ref` folder of the Nuget did NOT have the `ReferenceAssembly`Attribute on it.
As a result we never switched it out for the `monodroid90` one during build time. 
It turns out that having the `ReferenceAssembly` Attribute is not always going to 
identify a `ReferenceAssembly` from Nuget. We should also be looking at the path
the file is in. In this case reference assemblies are always in a path with `ref` in it. 
So lets look for that as well as the attribute. 
This PR also adds a unit test to make sure we do the right thing in this situation.
=> [Xamarin.Android.Build.Tasks] Handle Ref Assemblies from Nuget

src/manifestmerger/.gitignore
I was seeing files in my working tree after a build, I reused the `.gitignore` that `r8` is using.
=> [manifestmerger] needs a .gitignore file

build-tools/xaprepare/xaprepare/Application/Context.cs, build-tools/xaprepare/xaprepare/Steps/Step_PrepareExternal.cs
We currently only support restore for a single solution (Xamarin.Android.sln), those changes enable we support restore for multiple solutions.
=> Enabling restore for multiple solutions.

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
Context: https://github.com/android/ndk/wiki/Changelog-r20#r20b
This is a minor update to the previous version. Changes:
* Fix for CVE-2019-2212, out of bounds buffer read in std::random (https://bugs.chromium.org/p/chromium/issues/detail?id=994957)
* Updated Clang to r346389c
* Updated libc++ to r350972
* Add Android Q Beta 1 APIs
* MIDI (<amidi/AMidi.h>)
* Binder
* Extensions to several APIs from previous releases
=> Update NDK to the latest version (20b)

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/MacOS.cs
#3375 removed libzip in favor of a nuget dependency
If I understand correctly, this no longer is required by the build tools (although I'm still trying to get to build locally)
=> Remove libzip from build tools

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes #3996
Commit 008ba98 did not go far enough. Both `ValidateJavaVersion` and `ResolveSdks` also needed the same `ContinueOnError` setting. While the commit did allow users to install components which were missing, it did NOT allow users to install the entire SDK. This is because even when calling's the `InstallAndroidDependencies` target the build would still fail with 
```
error XA5300: The Android SDK Directory could not be found. Please set via /p:AndroidSdkDirectory.
```
What we need to do in this case was include the `ContinueOnError` property on `ValidateJavaVersion` and `ResolveSdks`. This allows the build to continue and call the targets to install the required sdk. This is very handy for CI environments as it means we can install the Android SDK from scratch on a clean …
=> Allow installing the SDK if one doesn't exist

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
Fixes #3962
Commit d20a991 fixed up an issue where `aapt2` was always compressing
items even if they were defined in `AndroidStoreUncompressedFileExtensions`.
However users are not always including a period in the values they
place in that ItemGroup. In the Linked issue the user was using
`tflite` rather than `.tflite` which `aapt2` is expecrting.
So lets check to see if we have a `.` prefix and if not add one.
=> [Xamarin.Android.Build.Tasks] Fix up AndroidStoreUncompressedFileExtensions.

src/Xamarin.Android.Build.Tasks/Tasks/D8.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3622
Context: https://r8.googlesource.com/r8/
Just building a Xamairn.Forms template with multi-dex enabled produces
the warning:
R8 : warning : Resource 'META-INF/MANIFEST.MF' already exists.
There are also other reports of:
R8 : warning : Resource 'META-INF/MSFTSIG.SF' already exists.
R8 : warning : Resource 'META-INF/MSFTSIG.RSA' already exists.
Reviewing r8's source code, I see no way to prevent it from emitting
these messages.
For now, it seems simple enough to add a `Regex` for this message and
downgrade it to a regular MSBuild message.
I added a test for this scenario as well, however I was also getting
this message from r8:
Warning: The rule `-keep public class * extends java.lang.annotation.Annotation { *; }` uses extends …
=> [Xamarin.Android.Build.Tasks] r8 duplicate resource warnings -> messages

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
In a26e0dbf and 5bfe44e9 we found a performance regression with
startup in Debug builds.
To better catch this in the future, I updated `DebuggingTest`.
If it takes longer than 1 second for the app to start and debugger
connect, the test will fail now.
This worked on my PC with a HAXM emulator, we will see if this number
is too optimistic for our CI servers.
=> [test] add an assertion checking Debug startup time

Xamarin.Android.sln, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.Windows.projitems, tools/xabuild/packages.config, tools/xabuild/xabuild.csproj
Removes the `create-bundle.csproj` reference from `Xamarin.Android.sln`.
Removes an empty `packages.config` file from `xabuild`.
Removes the empty and unused `Xamarin.ProjectTools.Windows.projitems`.
=> [build] Remove empty files and references

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.Shared.projitems
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3307232&view=ms.vss-test-web.test-result-details
We noticed a failure in the `DuplicateReferences` test, which appeared
to be caused by an incorrect Android SDK path being used. MSBuild tests
which build a project will look for the Android SDK in the following
paths:
1) Value of `$(ANDROID_SDK_PATH)` if set.
2) The `HKEY_CURRENT_USER\\SOFTWARE\\Novell\\Mono for Android` registry key.
3) The path we install build tooling into: `%USERPROFILE%\android-toolchain\sdk`.
In the case of the `DuplicateReferences` test failure,
`$(ANDROID_SDK_PATH)` was set to an unexpected value:
ANDROID_SDK_PATH = F:\A\xamarin-v000006-1\_work\2\s\bin\TestRelease\temp\InstallAndroidDependenciesTest\android-sdk
Presumably this failure occurred …
=> [tests] Use non-parallel fixture for InstallAndroidDependencies

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
This warning message actually prints:
XA0110: Disabling true as it is not supported by `aapt2`. If you wish to use true please set True to false.
In the long term, I think we should remove `$(AndroidExplicitCrunch)`.
I have found some bugs using it that cause targets to re-run on
incremental builds. It is also not supported when using `aapt2`.
It's worth fixing the warning message for now, though.
=> [Xamarin.Android.Build.Tasks] fix $(AndroidExplicitCrunch) warning

tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs, tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
Context: https://github.com/xamarin/xamarin-android/pull/4003#issuecomment-563274531
Since 2c6f5cd1, I believe we are hitting a performance regression in
the `Build_JLO_Change` test:
Building target "_ManifestMerger" completely.
Input file "obj/Debug/AndroidManifest.xml" is newer than output file "obj/Debug/android/AndroidManifest.xml".
Fortunately, I think we just need to change the test. The test itself
alters `AndroidManifest.xml` when the activity's name is changed:
```diff
-<activity android:name=".MainActivity">
+<activity android:name=".MainActivity2">
```
I added a new test that specifically times a `AndroidManifest.xml`
change vs a `Java.Lang.Object` subclass change.
=> [tests] improve performance test for JLO change

src/Mono.Android/Android/IncludeAndroidResourcesFromAttribute.cs, src/Mono.Android/Android/NativeLibraryReferenceAttribute.cs, src/Mono.Android/Android/ReferenceFilesAttribute.cs, src/Mono.Android/Java.Interop/JavaLibraryReferenceAttribute.cs
Context: https://github.com/xamarin/xamarin-android/commit/1a61fa811e370b68b38a7f318b7d4059dc70779e
The corresponding [backported commit][0] has not yet been published in a preview version, so there's an opportunity to make this tiny little change from "not" to "no" before the wording appears in a published build.
This is just a tiny wording item I noticed by chance while learning more about how the API compatibility check was working on my other PR. Hopefully these errors should be fairly uncommon for users anyway, but it looked like it might have been unintentional to say "not" rather than "no," so I thought it might be handy to switch that while we had a chance. No worries if not though.
[0]: https://github.com/xamarin/xamarin-android/commit/63a69872f3f9ae7e9ae43c7b23c4ce2d0b31715d
=> [Mono.Android] Adjust wording

tools/xabuild/XABuild.cs, tools/xabuild/XABuildPaths.cs
The .NET Framework directories installed by "recent" versions of mono on
macOS have been updated to redirect to a new TargetFrameworkDirectory.
I believe these directories used to contain reference assemblies, but
at present they only contain a `RedistList/FrameworkList.xml` with the
following content:
/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/xbuild-frameworks/.NETFramework/v4.7.2/RedistList/FrameworkList.xml
<FileList  Name=".NET Framework 4.7.2" TargetFrameworkDirectory="..\..\..\..\4.7.2-api">
</FileList>
The .NET Framework assemblies are now installed into `$(Version)-api`
folders such as:
/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.7.2-api
This causes an issue with xabuild. The `GetReferenceAssemblyPaths` task
fails to follow this relative path …
=> [xabuild] Create symlinks to .NET Framework redirects

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CheckApiCompatibility.cs
Small code improvement to provide more info in case of exception when reading breakages content.
We hit an exception on: https://jenkins.mono-project.com/job/xamarin-android-linux-pr-pipeline-debug/585/console
And it seems the exception happened when trying to read: https://github.com/xamarin/xamarin-android/blob/07e7477126fdc3eb68cca38347d1b8698d334874/tests/api-compatibility/acceptable-breakages-v7.0.txt#L1
Code expects to read `Compat issues with assembly` but it seems it is reading something else.
Changing the code to output what it is reading and also short-circuiting code in case an error has happened.
Build log:
```
[2019-12-11T15:42:23.286Z]   CheckApiCompatibility for ApiLevel: v7.0
[2019-12-11T15:42:23.325Z]   CompatApi command: …
```
=> CheckApiCompat - Small code improvement

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/xamarin-android/commit/9eb4b7f16785902c8942c7f9c88b31cd48a2b9aa
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3316261&view=logs
In some cases our `Xamarin.Android.Build.Tests.dll` execution slows down
dramatically on Windows[0]. We'll attempt to address this by reducing the
amount of work we do in parallel. Our Windows agents seemingly
[have 8 cores available][1], and NUnit-Console will attempt to use all
cores when running tests in parallel by default. Setting the `--workers`
argument to 4 should cut our parallelization in half, and potentially
prevent the machine from running out of resources.
Commit 9eb4b7f16 introduced these changes, but only for the
`Windows Build and Test` job. I believe this should also be added to the …
=> [ci] Limit parallel scope for Windows tests

build-tools/automation/azure-pipelines.yaml
Attempts to clone the `designer` source branch that has the same name
as the target branch of the PR being built, or the branch of the commit
being built if we aren't building a PR.
=> Dynamically determine designer source branch

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
By checking whether the assembly has a type reference to
`Java.Lang.Object` first. `ModuleDefinition::HasTypeReference` call is
relatively fast in cecil and by using it we save a lot of further
processing.
Measurements of the `_LinkAssembliesNoShrink` target (XA template,
rebuild after touching MainActivity.cs, 5 runs average):
Before: 160ms
After:   52ms
=> [FixAbstractMethodsStep] Speedup the step

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/PackagingUtilsTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/PackagingUtils.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/3993
After 16.4 shipped, we started getting reports that App Bundle signing
was broken. Google Play was not accepting the file:
You uploaded an APK or Android App Bundle with invalid or missing signing information for some of its files.
You need to create a valid signed APK or Android App Bundle.
Both @pjcollins and myself tested this, but it worked for us?
Finally we discovered the issue only occurred when multi-dex was
enabled! I was able to reproduce the issue and do a diff of the file
contents of good and bad `.aab` files.
These two files were present in the broken App Bundle:
+1969-12-31 18:00:00 .....         1480          716  base\root\META-INF\MSFTSIG.SF
+1969-12-31 18:00:00 .....         8546         5469 …
=> [Xamarin.Android.Build.Tasks] fix signing for App Bundles with multi-dex

.external
Changes: https://github.com/xamarin/monodroid/compare/1b907d680cc6561dcfaddc6f997d2f6ff5456644...2efbdd3e04710a7887c3da676b275d425e167a43
[tools/msbuild] another fix to <GetPrimaryCpuAbi/> (#1056)
[ci] Build with on-prem hardware (#1054)
[build] Convert build task and test projects to short-form style (#1048)
=> Bump to xamarin/monodroid@2efbdd3e

build-tools/automation/azure-pipelines.yaml
Context: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3331623
Upon investigation of a recent `Build Results - macOS` build artifact
from our Azure build pipeline, I noticed that we are now uploading a
duplicate Xamarin.Android.Sdk*.nupkg on every build. This is because
the [template for result publishing][0] uploads everything found in
`$(Build.ArtifactStagingDirectory)`. We should use a unique path when
packaging and uploading this .nupkg file to avoid duplication.
[0]: https://github.com/xamarin/xamarin-android/blob/c9ed134e5d3eb94f6c09a9e3067f5c60c4a32833/build-tools/automation/yaml-templates/upload-results.yaml#L18
=> [ci] Package and upload .nupkg in unique location

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/xamarin-android/pull/4052#issuecomment-567576834
Our `Windows Build and Test` job runs on the same set of VMs that we use
for testing and in some cases this can cause issues. Most recently, I
noticed a failure when attempting to restore NuGet packages for
`Xamarin.Android-Tests.sln`, because the Xamarin.Android version on disk
is used when calculating the NuGet dependecy graph for Android projects.
We should attempt to downgrade XA to the version that shipped with the
instance of VS that we are building with before building on Windows.
=> [ci] Downgrade XA before Windows build

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/RemoveAttributes.cs
Implements https://github.com/xamarin/xamarin-android/issues/3911
Context: https://github.com/dotnet/roslyn/blob/7bc44488c661fd6bbb6c53f39512a6fe0cc5ef84/docs/features/nullable-metadata.md
C#8 non-null reference uses custom attributes to let compiler know
more information related to non-null reference.
These shouldn't be needed when running on device, as the C# language
feature doesn't require modifications to the runtime. Thus it should
be safe to remove them.
=> [linker] Remove C#8 Nullable attributes

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj
I noticed I could no longer use the NUnit test runner in VS Windows.
In dc49cf92, we removed the `NUnit3TestAdapter` which has no other function than to make the IDE "work".
I tried using this extension instead:
https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter
However, it seems the NuGet package is the only thing that solves the issue for me.
=> [tests] bring back NUnit3TestAdapter

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs
We should return `false` when the iface was already marked, to avoid
unnecessary processing, which can cause infinite loop in the linker.
Fixes https://github.com/xamarin/xamarin-android/issues/3852
What was happening: we were returning `true` from
`ShouldMarkInterfaceImplementation` for ifaces of types that
implements `IJavaObject` or `IJavaPeerable`. In case of #3852, 3 of
these had also `System.Runtime.CompilerServices.NullableAttribute`
custom attributes. That led to enqueuing the custom attribute
constructor every pass through the primary queue in the linker and so
the queue was never emptied and that resulted in an infinite loop.
IMO linker should check for iface being already marked outside of
`ShouldMarkInterfaceImplementation`. I will add PR to the linker for
that, meanwhile we …
=> [linker] Update ShouldMarkInterfaceImplementation logic

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-integrated-regression-tests.yaml, build-tools/automation/yaml-templates/upload-results.yaml
Context: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops
Context: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3360513
Some of our build and test jobs started failing recently due to what
appear to be authorization issues when attepting to clone private
sources:
stderr | remote: Repository not found.
In order to avoid this, we'll try to move away from using custom scripts
and tokens for source checkout and instead use the new "multi-repo"
checkout feature in Azure Pipelines that @akoeplinger suggested.
=> [ci] Use multi-repo checkout feature

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-integrated-regression-tests.yaml, build-tools/automation/yaml-templates/upload-results.yaml
Context: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops
Context: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3360513
Recently (on or around 2020-Jan-03), our build and test jobs started
failing to build due to what appear to be authorization issues when
attempting to clone private sources:
Updating external repositories
* monodroid
-> cloning from xamarin/monodroid
stderr | Cloning into 'monodroid'...
stderr | remote: Repository not found.
stderr | fatal: repository 'https://github.com:/xamarin/monodroid/' not found
We don't know what *caused* this, but we do know of a "workaround":
AzDO recently added the ability to check out multiple repositories
within a pipeline.
Move away from using custom scripts and tokens for …
=> [ci] Use multi-repo checkout feature (#4085)

README.md
Add Commercial Xamarin.Android 10.2 Windows download location to the
README.
Update OSS master version number to 10.2.99.
Remove old Commercial Xamarin.Android 8.x versions from the README.
=> [docs] Add Commercial Xamarin.Android 10.2 Windows download location

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/xamarin-android/commit/ed29bf1d47661e9df8458b5be074ed0369752b0b
Context: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3363837
Our notarization job has been failing since adding multi-repo
checkout steps to our YAML pipeline:
/Users/builder/azdo/_work/_temp/edb4cc03-b677-49a2-8db9-524d03404164.sh: line 1: cd: /Users/builder/azdo/_work/1/s/release-scripts/release-scripts: No such file or directory
Upon further investigation, it seems that our working directory was set
to a value that was unexpected:
##[debug]  Working directory: '/Users/builder/azdo/_work/1/s/release-scripts'
The behavior of `$(System.DefaultWorkingDirectory)` changes based on the
number of checkout steps used in a single job, and whether or not those
steps specify a custom …
=> [ci] Fix multi-repo checkout notarization breakage

.external
Changes: https://github.com/mono/mono/compare/d56a0e72c21d8e58566b9cb46c151ce86a5d4f1f...99e3aed6ec366383372f75af07994162f247d9ff
Context: https://github.com/mono/mono/issues/16513
Context: https://github.com/mono/mono/issues/17916
Context: https://github.com/msys2/MINGW-packages/issues/5803
* mono/mono@99e3aed6ec3: Socket.BeginMConnect() should not attempt connections on unsupported address families. (#18321)
* mono/mono@5f0704ce372: [eglib] Don't define _FORTIFY_SOURCE on Cygwin builds (#18312)
* mono/mono@dc5902c243e: [domain] Don't add NULL runtime to runtimes list (#18265)
* mono/mono@bfcac9bd309: Bump corefx to get test fix
=> Bump to mono/mono/2019-10@99e3aed6

tests/MSBuildDeviceIntegration/Tests/AotProfileTests.cs
Use random port number to lower probability of choosing an already
used port number.
=> [tests] Use random port between 9000 and 9999 for AOT profiling

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/xamarin-android/pull/4089
Context: https://github.com/xamarin/xamarin-android/commit/ed29bf1d47661e9df8458b5be074ed0369752b0b
In commit ed29bf1d we migrated to a new Azure Pipelines feature that
allows us to clone external sources. This caused an issue with our
inverted build, as it introduced a nested xamarin-android checkout which
was previously ignored. When attempting to apply ed29bf1d to d16-4, our
build failed due to an attempt to restore NuGet packages which are only
present (with a proper feed configuration) in xamarin-android/master:
2020-01-07T00:20:53.8724800Z Restore failed in 483.85 ms for /Users/runner/runners/2.162.0/work/1/s/xamarin-android/external/monodroid/external/xamarin-android/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.T …
=> [ci] Remove nested xamarin-android submodule

Documentation/release-notes/4058.md, src/monodroid/jni/monodroid-glue.cc, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
Fixes: https://developercommunity.visualstudio.com/content/problem/788217/xamarin-android-resource-ids-mismatch-1.html
In a project where:
* The `MainLauncher` activity is in a class library
* This activity uses a value from `Resource.designer.cs`
You get a crash such as:
UNHANDLED EXCEPTION:
Android.Content.Res.Resources+NotFoundException: Resource ID #0x7f09001c
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <e7e2d009b69d4e5f9a00e6ee600b8a8e>:0
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, …
=> [monodroid] ensure main app assembly is loaded

build-tools/automation/azure-pipelines.yaml
Commit a092dca1 had a typo: the
`tests/Runtime-MultiDex/Mono.Android-TestsMultiDex.csproj` project
creates a file named `Mono.Android_TestsMultiDex-Signed.apk`, based
on the `/manifest/@package` value within
`tests/Runtime-MultiDex/Properties/AndroidManifest.xml`.
Unfortunately, a092dca1 was uploading `Mono.Android_Tests-Signed.apk`,
which happened to be build output from the preceding
`tests/Runtime-AppBundle` build.
As such, we weren't actually uploading the `.apk` produced by the
multidex build *at all*.
Fix the `artifactName` value so that the correct `.apk` is uploaded.
=> [ci] Upload Mono.Android-TestsMultiDex-Signed.apk for MultiDex output

build-tools/automation/azure-pipelines.yaml
Ensure we checkout our sources into `$(System.DefaultWorkingDirectory)`
before attempting to download any artifacts into it, or modify it in
any other way.
=> [ci] Checkout notarization scripts first

.external
Changes: https://github.com/mono/mono/compare/bef1e6335812d32f8eab648c0228fc624b9f8357...e3084ececececf33f634329612451d31a2c28802
Context: https://github.com/mono/mono/issues/17926
* mono/mono@e3084ececec: [debugger] skip suspend for unattached threads (#18138)
* mono/mono@da5b1c675d9: [2019-08] Enable GSS on android (#18116)
=> Bump to mono/mono/2019-08@e3084ece

build-tools/xaprepare/xaprepare/Application/VersionFetchers.cs, build-tools/xaprepare/xaprepare/ToolRunners/SevenZipRunner.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/4082
Context: https://www.7-zip.org/history.txt
`xaprepare` uses the `-bs[o|e|p][0|1|2]` 7z/7za switches to make
absolutely sure output produced by 7zip goes where we want it to.
However, these switches were added only in version 15.05 of 7zip and
thus on operating systems with older versions of the utility `make
prepare` would fail to unpack any archives. Since these switches are
not **critical** to our operation we can accommodate the older 7z
releases by making the switches optional.
=> [xaprepare] Detect if 7z supports output stream switches

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/xamarin-android/commit/ed29bf1d47661e9df8458b5be074ed0369752b0b
The notarization job is also responsible for posting artifact metadata
to GitHub as a commit status. Commit ed29bf1d broke this, as it changed
the source checkout behavior for this job.
We report artifact metadata to GitHub with the [Artifacts tool][0], and
this tool must be ran inside the source directory that it is going to
create a GitHub commit status for. As of commit ed29bf1d, we started
executing this tool within a release-scripts checkout rather than a
xamarin-android checkout.
Our .vsix signing job relies on the GitHub commit status created by
the Artifacts tool to determine which file to sign. Since artifact
metadata reporting was broken, our .vsix signing job was failing to
fetch …
=> [ci] Report artifact status to the correct repo

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes #2413
We should calculate the values for `_ManagedUpdateAndroidResgenInputs`
in a target rather than at evaluation time. This is so
we can pick up the correct `_AndroidBuildPropertiesCache`.
=> [Xamarin.Android.Build.Tasks] MSBuild target does not properly build incrementally

src/Xamarin.Android.Build.Tasks/Utilities/UnhandledExceptionLogger.cs
When logging unhandled exceptions in our MSBuild tasks, a missing `else` is causing each error to get logged twice, once with the coded error and once with the generic error.
Example:
```
XARDF7004: System.ArgumentException: Illegal characters in path.
at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
at Xamarin.Android.Tasks.RemoveDirFixed.RunTask()
at Xamarin.Android.Tasks.AndroidTask.Execute()
XARDF7000: System.ArgumentException: Illegal characters in path.
at …
```
=> [Xamarin.Android.Build.Tasks] Don't log unhandled exceptions twice.

src/Xamarin.Android.Build.Tasks/Tasks/GenerateLibraryResources.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/GenerateLibraryResourcesTests.cs
Fixes: https://developercommunity.visualstudio.com/content/problem/845345/cant-build-xamarin-for-android-project.html
We have been getting reports of an unhandled exception during builds
such as:
Unhandled exception: System.IO.IOException: Sharing violation on path /Users/runner/runners/2.160.1/work/1/s/Droid/obj/Release/android/src/com/google/android/gms/base/R.java
at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <ba70b91736bd40cb990a357097dba9c3>:0
at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, …
=> [Xamarin.Android.Build.Tasks] collision in <GenerateLibraryResources/>

src/Xamarin.Android.Sdk/targets/Xamarin.Android.Sdk.DefaultItems.props
Follows the pattern at https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props#L36
=> Honor the .NET SDK EnableDefaultItems property when including default items

build-tools/automation/build.groovy
The https://github.com/xamarin/xamarin-android/pull/3594 started using
different filenames, so we need to update Jenkins configuration.
=> [test sizes] Update the sizes data filename

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
Context: https://build.azdo.io/3380356
We have seen an error on PR builds such as:
(_ResolveAssemblies target) ->
Xamarin.Android.Common.targets(1702,2): error : Could not load file or assembly 'NuGet.Common, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
Xamarin.Android.Common.targets(1702,2): error :   at Xamarin.Android.Tasks.ResolveAssemblies.RunTaskAsync () [0x00006] in <b7f246e55e6448348b8bc9a1e37cc64b>:0
Xamarin.Android.Common.targets(1702,2): error :   at Xamarin.Android.Tasks.AndroidAsyncTask.<RunTask>b__4_0 () [0x00000] in <b7f246e55e6448348b8bc9a1e37cc64b>:0
Xamarin.Android.Common.targets(1702,2): error :   at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <97b502f2cbfa41d493563be777ffb43e>:0 …
=> [build] fix ILRepacker target's inputs

.external
Changes: https://github.com/xamarin/monodroid/compare/2efbdd3e...0f6725ed
Fixes: https://developercommunity.visualstudio.com/content/problem/858509/adb0030-monoandroidtoolsrequiresuninstallexception-2.html
Bump to xamarin/androidtools/master@d221090
[tools/msbuild] prevent InstallPackageAssemblies from reporting two errors
=> Bump to xamarin/monodroid/master@0f6725ed

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/Linux.DebianCommon.cs
We no longer need the package as `libzip` comes from a nuget now.
=> [xaprepare] drop dependency on libzip-dev on Linunx

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3387160&view=ms.vss-test-web.build-test-results-tab&runId=10630574&resultId=100273&paneView=debug
Maven now requires https in order to download files.  This PR changes `http://central.maven.org/...` to `https://repo1.maven.org/...`.
=> [Xamarin.Android.Build.Tasks] Maven now requires packages to be downloaded over https.

tools/xabuild/XABuild.cs
After a recent update of msbuild on Linux I started to see the following
error when attempting to build our tests (with `make all-tests`):
"Xamarin.Android-Tests.sln" (default target) (1) ->
"tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/Xamarin.Android.MakeBundle-UnitTests.csproj" (default target) (21) ->
BuildTests.cs(150,22): error CS0012: The type 'ValueType' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/Xamarin.Android.MakeBundle-UnitTests.csproj]
Which, after investigation by Jo Shields, turned out to be caused by
`xabuild` not creating a bunch of symlinks to Mono API façades (the
`*-api` …
=> [build] fix xabuild on Linux

src/Mono.Android/Android.Graphics/Color.cs
it enables:
Color c = -65536; //Red
Simple conversion and intuitive since Color can be assigned to int parameter/field, vice versa shall be available.
=> Implicit operator for Color to to enable int assignment

.vscode/launch.json, .vscode/settings.json, Configuration.props, NuGet.config, build-tools/automation/yaml-templates/run-nunit-tests.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/xaprepare/xaprepare/OperatingSystems/Windows.cs, build-tools/xaprepare/xaprepare/ThirdPartyNotices/LibZipSharp.cs, build-tools/xaprepare/xaprepare/ThirdPartyNotices/libzip.cs, src/Mono.Android/Mono.Android.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs, tests/CodeBehind/UnitTests/run.sh, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/run.sh
`PackageReference` packages install/restore into a default global folder
of `%userprofile%\.nuget\packages (Windows)` or
`~/.nuget/packages (Mac/Linux)`.
In order to avoid bloating the home directories on our machines used
locally and in CI, we'll reconfigure the `globalPackagesFolder` path to
point to a `packages` folder nested under `xamarin-android`.
This also allows us to continue to use "known" paths to certain tools
that are used by our tests, such as `nunit3-console.exe`.
Each test in `Xamarin.Android.Build.Tests` copies and uses the
`NuGet.config` file from the xamarin-android repo root. Now that a
`globalPackagesFolder` value is specified in that file, the NuGet restore
behavior for all tests has changed, and some test changes were needed.
A new `globalPackagesFolder` default has …
=> [build] Use an in tree `globalPackagesFolder`

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidProfile.cs
Context: https://github.com/xamarin/xamarin-android/issues/4141
Context: https://github.com/xamarin/xamarin-android/commit/130905e1612f1c3f41b6b233056cae2753270630
The `Java.Interop.GenericMarshaler` namespace was put in separate
assembly in Java.Interop repo.
Lets make linker be aware of it, so that it can be linked in
LinkSdkOnly mode.
=> [linker] Add Java.Interop.GenericMarshaler to Sdk assemblies

Configuration.props, build-tools/scripts/MSBuildReferences.projitems, build-tools/xaprepare/xaprepare/ThirdPartyNotices/LibZipSharp.cs, build-tools/xaprepare/xaprepare/ThirdPartyNotices/libzip.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj, src/Xamarin.Android.Tools.JavadocImporter/Xamarin.Android.Tools.JavadocImporter.csproj
Fixes #4100
The version of libzip.so we shipped for linux in
1.0.6 had a dependency on libcrypto.so.1.1. Some
linux based systems only ship with libcrypto.so.1.0.
As a result Xamarin.Android would not build and we give
the following error.
error MSB4018: System.DllNotFoundException: lib64/libzip.so assembly
Verison 1.0.7 if Xamarin.LibZipSharp fixes this issue by
statically linking libcrypto (and other dependencies) into the
dynamic library. This should allow Xamarin.Android to build and
run on those systems which does not include libcrypto or have
an older version.
This PR reworks the source a bit so we define the LibZipSharp version in ONE place.
Both the all the csproj and targets files include `Configuration.props` in them. So it 
makes sense to place the version there as an MSBuild …
=> [Build] Bump Xamarin.LibZipSharp to 1.0.7

.external
Changes: https://github.com/xamarin/monodroid/compare/2c9ce23d...dab75e88
Fixes: https://work.azdo.io/1041849
Fixes: https://developercommunity.visualstudio.com/content/problem/858509/adb0030-monoandroidtoolsrequiresuninstallexception-2.html
Bump to xamarin/androidtools/d16-5@62844ab
Bump to xamarin/android-sdk-installer/d16-5@5adcbfa
[tools/msbuild] prevent InstallPackageAssemblies from reporting two errors
=> Bump to xamarin/monodroid/d16-5@dab75e88

Documentation/building/unix/instructions.md, Documentation/building/windows/instructions.md
Since the prepare external dependencies step is only for proprietary
dependencies, update the wording of the build instructions to let
community contributors know that they should skip it.
`make prepare-external-dependencies` uses the
`PrepareExternalGitDependencies` step in `xaprepare`, which currently
only prepares the monodroid external dependency.
The Mono dependency listed in `.external` is prepared via a separate
`DownloadMonoArchive` step in `xaprepare`.  That step is part of `make
prepare` and does not require running `make
prepare-external-dependencies`.
=> [docs] Add intended audience for prepare-external-dependencies

src/monodroid/CMakeLists.txt, src/monodroid/jni/android-system.cc, src/monodroid/jni/android-system.hh, src/monodroid/jni/basic-android-system.cc, src/monodroid/jni/basic-android-system.hh, src/monodroid/jni/basic-utilities.cc, src/monodroid/jni/basic-utilities.hh, src/monodroid/jni/cpp-util.hh, src/monodroid/jni/cpu-arch-detect.cc, src/monodroid/jni/debug-app-helper.cc, src/monodroid/jni/embedded-assemblies-zip.cc, src/monodroid/jni/external-api.cc, src/monodroid/jni/jni-wrappers.hh, src/monodroid/jni/monodroid-glue-internal.hh, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/timezones.cc, src/monodroid/jni/xamarin_getifaddrs.cc
Add a number of warnings to the array of arguments passed to the C++
compilers in order to detect suboptimal or incorrect code:
* `-Wduplicated-branches`
Detect conditional branches which yield identical code.
* `-Wduplicated-cond`
Detect duplicated conditions in the if-else-then statements
* `-Werror=return-type`
Make `-Wreturn-type` an error. Prevents compiling code with
functions which require a return value but do not return from all
code paths.
* `-Wextra`
A bunch of "extra" warnings (too many to list here) which should
help make the code cleaner and more correct
* `-Wmisleading-indentation`
Warn about code which has indentation that can mislead the developer
into thinking that a statement following the `if` statement is part
of the statement's `true` block while in reality it isn't. …
=> C++ code cleanup based on extra warnings

.vscode/tasks.json
When trying to run the 'Run Xamarin.Android Build Tasks Unit Tests'
command in VSCode we get the following error now
error MSB4057: The target "RunNUnitTests" does not exist in the project.
This is because the `RunTest.targets` file is now only imported
when you run against the `Xamarin.Android.sln`. So we need
to update this command to use the correct command line.
=> [vscode] Fix the command used to run the NUnit Tests

src/Mono.Android/Android.Runtime/AndroidRuntime.cs
Bump to xamarin/java.interop/master@621e297
Changes: https://github.com/xamarin/java.interop/compare/4565369...621e297
When profiling with `adb setprop debug.mono.profile log:alloc`, I
noticed the following allocations:
84840        505      168 Java.Interop.JniRuntime.JniTypeManager.<CreateGetTypeSignaturesEnumerator>d__11
24096        502       48 Android.Runtime.AndroidTypeManager.<GetSimpleReferences>d__1
This was using the Xamarin.Forms integration project in xamarin-android:
https://github.com/xamarin/xamarin-android/tree/master/tests/Xamarin.Forms-Performance-Integration
100K of memory allocations are a bit much, so seemed like it might help
to reduce these.
I made a version of both `JniTypeManager.CreateTypeSignatures` and …
=> [Mono.Android] remove IEnumerable iterators called at startup

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/XamarinAndroidXMigration
Fixes: https://github.com/xamarin/xamarin-android/issues/4068
Developers have been reporting an error when using AndroidX.Migration:
The "CopyGeneratedJavaResourceClasses" task was not given a value for the required parameter "SourceTopDirectory".
It is reported another build fixes the issue, and it "randomly"
happens on incremental builds.
The error seems to indicate either `$(AaptTemporaryDirectory)` or
`$(ResgenTemporaryDirectory)` are blank? But it only happens when
using the AndroidX.Migration NuGet package.
From a user's build log:
Skipping target "_PrepareCreateBaseApk" because all output files are up-to-date with respect to the input files.
Which would indicate in the case of AndroidX.Migration:
* `_PrepareCreateBaseApk` …
=> [Xamarin.Android.Build.Tasks] reorder two targets to fix AndroidX.Migration

tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Context: https://github.com/xamarin/androidtools/pull/207
This adds the missing test from androidtools#207.
=> [tests] add a /t:Install test when keystore changes

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-integrated-regression-tests.yaml
Breaks up the `Integrated Regression` tests to run across 3 nodes, reducing the time taken to run from `~150 minutes` to `3 x ~50 minutes`.
Moves the `Integrated Regression` tests to a separate Stage to improve readability.  This also allows us to move the `condition` to the Stage level instead of each Job.
=> [CI] Run integrated regression tests in parallel

build-tools/scripts/MSBuildReferences.projitems
Commit dc49cf92 switched over our build system to use the MSBuild Nuget Packages. 
However when we use that and run the Unit Tests from within VSForMac they all fail with a
`PlatformNotSupported` exception. This is despite the fact that we never actually copy the files over to the output path, but use the Framework ones. 
It turns out the MSBuild Nuget File are loaded by the IDE and the NUnit Test Addin so it tries to use those when running the tests. This then results in the error. This issue does not occur on the command line or in VSCode since they do not load the MSBuild Nuget assemblies into the process.
=> Use the Framework MSBuild on Mac/Linux

Documentation/building/unix/dependencies.md, build-tools/xaprepare/xaprepare/OperatingSystems/Unix.cs
Context: https://github.com/xamarin/xamarin-android/issues/4155
Computers running older versions of Unix/Linux operating systems may
have default C/C++ compilers which are too old to build Xamarin.Android.
However, it is possible that other versions of the compilers are
available on those machines which can be sufficiently new to build our
native code. In order to make building on those hosts easier, this
commit adds code to detect the desired compiler by looking at the `CC`
and `CXX` variables in the `xaprepare` environment.
Both variables should be set to the desired compiler name when invoking
`make` to prepare XA build:
CC=gcc-7 CXX=g++-7 make prepare
=> [build] Use the CC and CXX envvars to detect compilers on Unix

src/Xamarin.Android.Build.Tasks/Tasks/BuildApkSet.cs, src/Xamarin.Android.Build.Tasks/Tasks/BuildAppBundle.cs, src/Xamarin.Android.Build.Tasks/Tasks/BundleTool.cs, src/Xamarin.Android.Build.Tasks/Tasks/BundleToolAdbTask.cs, src/Xamarin.Android.Build.Tasks/Tasks/InstallApkSet.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/BundleToolTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://developercommunity.visualstudio.com/content/problem/854863/unable-to-deploy-to-physical-device-when-emulator.html
Fixes: http://work.azdo.io/1056857
We got some reports that our App Bundle MSBuild tasks fail when you
have multiple devices/emulators connected to adb.
We were not using the `$(AdbTarget)` MSBuild property at all, which is
actually a slightly different parameter for `bundletool`:
--device-id: (Optional) Device serial name. If absent, this uses the
ANDROID_SERIAL environment variable. Either this flag or the environment
variable is required when more than one device or emulator is connected.
Used only if connected-device flag is set.
It appears that only a value such as `-s emulator-5554` would work for
the `--device-id` switch. To make things compatible, I …
=> [Xamarin.Android.Build.Tasks] App Bundle support for $(AdbTarget)

.external
Changes: https://github.com/xamarin/monodroid/compare/0f6725edfa09559afad58233d43f385122e31e8d...b2841feb5a69f9ccd3c480a9341fcb1da62af552
Context: https://build.azdo.io/3395342
* xamarin/monodroid@b2841feb5: Bump to xamarin/android-sdk-installer/master@78c3d16 (#1065)
* xamarin/monodroid@3c8601c55: [tools/msbuild] ported <GetPrimaryCpuAbi/> to AndroidAsyncTask (#1067)
* xamarin/monodroid@ad8d0f348: Support for new typemaps (#1061)
=> Bump to xamarin/monodroid/master@b2841feb

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileExpected.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileWithElevenStyleableAttributesExpected.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileWithLibraryReferenceExpected.cs, src/Xamarin.Android.Build.Tasks/Utilities/JavaResourceParser.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs
Fixes http://work.azdo.io/1057222
We had the global:: namespace prefix on ALL namespaces
in the Resource.Designer.cs file EXCEPT GeneratedCodeAttribute :facepalm.
So users can get errors like
The type or namespace name 'CodeDom' does not exist in the namespace Foo.Bar.System
If they use `System` in their defualt namespace for the project.
This commit adds it, so users who use `System` in their
assembly namespaces will not be hit by this in the future.
=> [Xamarin.Android.Build.Task] use global:: for GeneratedCodeAttribute

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-timezoneinfo-tests.yaml, tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs
This PR is intended to give us greater control over when we run our extended regression test suite and to parallelize TimeZoneInfo tests.
Creates a new `RunAllTests` variable that defaults to `false`.  This variable is used as a `condition` to trigger running our extended regression test suite.
This variable is set to `true` in the following ways:
* The `master` pipeline sets the value to `true` so all commits to `master` run the full suite.
* The value is set to true for a PR build if:
* The branch name contains `mono-`
* The branch is not a fork
* This allows our Mono bump branches PRs (which take the form of `mono-2019-12`) to run the full suite, as there is a much higher chance of breakage for these commits.
* If you are queuing a new run from the UI, clicking the `Variables` option …
=> [CI] Run TimeZoneInfo tests in parallel.

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs, src/Xamarin.Android.Build.Tasks/Tasks/CilStrip.cs, src/Xamarin.Android.Build.Tasks/Tasks/CompileNativeAssembly.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkApplicationSharedLibraries.cs
Split up the different uses of XA3001 by giving each error condition its
own code.  This makes it possible to gather telemetry for each condition
separately, and it also makes it easier for users to search for the
particular code they are seeing.
Move XA3001 and the other new error codes to the `.resx` file so that
they are localizable.
Remove the `try-catch` from `CilStrip.RunTask()` because after
[d4c8f077][1], the `AndroidTask` base class now provides that
functionality.
[1]: https://github.com/xamarin/xamarin-android/commit/d4c8f077faefdfc6174355848a9d8c74ecaa8f56
=> [Xamarin.Android.Build.Tasks] Split up XA3001 errors and move them into .resx file

src/Xamarin.Android.Build.Tasks/Resources/proguard_xamarin.cfg, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/4110
A crash was reported when using either Proguard/R8:
java.lang.RuntimeException: Unable to get provider mono.MonoRuntimeProvider_1: java.lang.ClassNotFoundException: Didn't find class "mono.MonoRuntimeProvider_1" on path: DexPathList[[zip file "/data/app/myApp-61Sw26LCrQQYfOvCs2GsDw==/base.apk"],nativeLibraryDirectories=[/data/app/myapp-61Sw26LCrQQYfOvCs2GsDw==/lib/arm64, /data/app/myapp-61Sw26LCrQQYfOvCs2GsDw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
at android.app.ActivityThread.installProvider(ActivityThread.java:7152)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:6630)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6525)
at …
=> [Xamarin.Android.Build.Tasks] default proguard rules for BroadcastReceiver

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CheckApiCompatibility.cs
We have hit some mono crashes happening when we run the apicompat tool.
Before we were unable to diagnose why the tool was failing, but now we can detect if a crash happened and retry.
Also improving some of the error message outputs.
=> Improving ApiCompat tool 5859b11

src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/packages.config, src/Xamarin.Android.Tools.Aidl/Xamarin.Android.Tools.Aidl.csproj, src/Xamarin.Android.Tools.Aidl/packages.config
CP https://github.com/xamarin/xamarin-android/pull/4119 to `d16-5`.
=> [Mono.Android] Add unsigned NewArray overloads.

Documentation/release-notes/4168.md, build-tools/create-vsix/symbols/ExternalWhiteList.csv, build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/ThirdPartyNotices/Xamarin.Android.Build.Tasks.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.FSharp.targets
Context: https://github.com/xamarin/xamarin-android/pull/238
Context: https://github.com/xamarin/xamarin-android/pull/4132
Removes the use of F# CodeDOM for generating the resource
designer file for F#.
Instead, a type provider
is used at compile time (both xbuild and the IDE) that compiles the
C# code using CSharpCodeProvider and makes the types available to
the consuming F# project. The type provider is available as a NuGet
package and is included in the Android templates.
This is similar to #159, but uses an F# type provider to compile the C# instead of an msbuild task. The advantage of this method is that intellisense works in the IDE without having to change the IDE code.
=> [F#] Use C# Resource.designer.cs file for F#

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/xamarin-android/pull/4171
When working on PR #4171, I was hitting an NRE on this line:
marshalTypes.Add (GetType ("Mono.Android", "Java.Interop.TypeManager/JavaTypeManager/__<$>_jni_marshal_methods"));
Somehow `Mono.Android.dll` was missing?
Java.Interop.TypeManager/JavaTypeManager/__<$>_jni_marshal_methods
After more investigation, I came upon this `<ItemGroup>` that seemed
wrong:
<ItemGroup Condition=" '$(AndroidGenerateJniMarshalMethods)' == 'True' ">
<_JniAssembliesToLink Include="@(ResolvedAssemblies->'$(_JniMarshalMethodsOutputDir)%(Filename)%(Extension)')" />
<_AssembliesToLink Condition="Exists(%(Identity))" Include="@(_JniAssembliesToLink)" />
<_AssembliesToLink Condition="!Exists(@(JniAssembliesToLink))" Include="@(ResolvedAssemblies)" /> …
=> [Xamarin.Android.Build.Tasks] fixes for jnimarshalmethod-gen

Documentation/guides/messages/xa2000.md, Documentation/release-notes/appdomain-warning-2.md, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
Putting up this PR just in case any of these changes might be handy. Feel free to take any, all, or none of them.
* * *
Remove the extra `Warning: ` prefix to match up with warnings from the
other MSBuild tasks.
Switch to the C# `AppDomain.CreateDomain()` syntax instead of the CIL
`AppDomain::CreateDomain` syntax.
Adjust the second sentence of the warning to align with the information
from the [System.AppDomain API documentation][0] about how there is only
one `AppDomain` in .NET Core.
Tidy up a few other little items in the docs page.
[0]: https://docs.microsoft.com/dotnet/api/system.appdomain?view=netcore-3.1
=> [linker][docs] Adjust AppDomain.CreateDomain warning wording

Documentation/release-notes/4011.md, build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
Context: https://www.blog.google/products/android/evolving-android-brand/
Starting with Android 10, Google is no longer adding nicknames to the
Android releases.
=> [xaprepare] Update Android 10 name

.external
Changes: https://github.com/mono/mono/compare/1182f8cbf5b4f11e3f6ca0dfa97fbdb14041dbb7...1cca0cfebfcbd019c6f2bdd3e5b99f769f1e2e0c
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1048838
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1050615
* mono/mono@1cca0cfebfc: Bump bockbuild for Pango patch
* mono/mono@b216675706a: configure.ac: remove AC_SEARCH_LIBS for libintl (#18596)
* mono/mono@c0a5db5f829: [2019-10] Bump msbuild to track mono-2019-10 (#18576)
* mono/mono@9ce68dc791c: [2019-10] [debugger] Native thread not executing managed code considered as terminated  (#18503)
* mono/mono@ea94456156c: [interp] context can be uninitialized for get_resume_state callback (#18536)
=> Bump to mono/mono/2019-10@1cca0cfe

Documentation/guides/BuildProcess.md, Documentation/release-notes/4046.md, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Support has been added for lint configuration files for android layouts in the designer code base.
This adds build action support for the new "AndroidRuleSet" item.
https://github.com/xamarin/designer/blob/8b01a63b3ecd494d65001cf1f74239a7db2a3db9/Xamarin.Designer.Android/Xamarin.AndroidDesigner/MSBuildConstants.cs#L52
https://github.com/xamarin/designer/pull/2709
=> Build Action support for designer's AndroidRuleSet

build-tools/scripts/MSBuildReferences.projitems, src/Xamarin.Android.Build.Tasks/Properties/AssemblyInfo.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
Updates `Xamarin.Android.Build.Tasks.csproj` to a short-form style
project which targets `netstandard2.0` to help ensure future compliance
with the dotnet version of MSBuild.
A few PackageReference related changes were needed to work with our
existing installer packaging logic, as NuGet assets are no longer copied
to the OutputDirectory by default for short-form style projects. To work
around this, we're setting `CopyLocalLockFileAssemblies` to true to copy
over all relevant NuGet package content. This property doesn't work for
debug symbols and certain NuGet folder hierarchies however. The new
`_CopyExtraPackageContent` target has been added to copy over these
unexpected files. This target relies on the `GeneratePathProperty`
metadata that is set on the `PackageReference` element. …
=> [Xamarin.Android.Build.Tasks] Target netstandard2.0

Documentation/guides/messages/xa1005.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/AndroidUpdateResDir.cs, src/Xamarin.Android.Build.Tasks/Tasks/CalculateLayoutCodeBehind.cs
Other changes:
Add a couple words to one of the XA1005 messages so it reads more like a
full sentence.  Hopefully that will be helpful for the translation team.
=> [Xamarin.Android.Build.Tasks] Move XA1005 and XA2001 message text into .resx file

Configuration.props, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ZipArchiveExTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs, src/Xamarin.Android.Build.Tasks/Utilities/ZipArchiveEx.cs, tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
The `BuildApk` task currently does not work incrementally.
When it is called it throws away the previously built apk
in favour of using the `base` on that `aapt/aapt2` just built.
With incremental builds it is highly likely that only a
few files have actually changed so we are wasting a ton of time.
During my tests on a simple app `BuildApk` generally takes
about 4 seconds to run. This is the same for both clean
and incremental builds.
With these changes, this time could now go down to 600 ms
for an incremental build. Which is a decent improvement.
The new system does not throw away all the work done in
the previous build. Instead it uses the previous output
apk as a base on which to produce the new one.
The output from `aapt/aapt2` is instead `merged` into the
current apk. We do this by …
=> [Xamarin.Android.Build.Tasks] Allow BuildApk to run incrementally.

build-tools/scripts/TimingDefinitions.txt, tests/Xamarin.Forms-Performance-Integration/Droid/timing-definitions.txt
Context: https://github.com/xamarin/xamarin-android/commit/e887eff9811b630fcbe35479d426013ae2acb024
The above mentioned commit changed the timing messages. As our timing
measurements use regex patterns to detect the appropriate lines, we
need to update the patterns to match the relevant lines again.
That should fix the missing measurements in
https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/plot/Tests%20times
=> [timing] Update timing definition files

.external, src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tasks/AndroidTask.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs, src/Xamarin.Android.Build.Tasks/Tasks/CalculateLayoutCodeBehind.cs, src/Xamarin.Android.Build.Tasks/Tasks/CheckGoogleSdkRequirements.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateLayoutBindings.cs, src/Xamarin.Android.Build.Tasks/Tasks/ManifestMerger.cs, src/Xamarin.Android.Build.Tasks/Tasks/NdkUtils.cs, src/Xamarin.Android.Build.Tasks/Tasks/NdkUtilsOld.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs, src/Xamarin.Android.Build.Tasks/Utilities/UnhandledExceptionLogger.cs
Changes: https://github.com/xamarin/monodroid/compare/78d56588...017b3618
Bump to xamarin/monodroid/master@017b3618
We have had a continuing concern of accidentally calling
`AsyncTask.Log` from a background thread. If done so, this can cause a
hang inside Visual Studio on Windows.
I finally had the idea of creating a build error if we inadvertently
do this:
[Obsolete("You should not use the 'Log' property directly for AsyncTask. Use the 'Log*' methods instead.", error: true)]
public new TaskLoggingHelper Log { get; }
This uncovered 26 build errors! Some were actually on the main thread
and completely OK, but several were not OK.
In most of the places, I could simply change `Log.LogDebugMessage` to
`LogDebugMessage`.
However a few of the more troublesome places:
* `ManifestDocument` …
=> [Xamarin.Android.Build.Tasks] fix potential AsyncTask.Log calls

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
Context: https://github.com/mono/mono/commit/a3c25e7b4f86b1bb202f80aa260942c6ccfc3a31
Commit 959ef4ba updated xamarin-android to start using mono/2019-12,
which added an `[Obsolete]` on `AppDomain.CreateDomain()` in
mono/mono@a3c25e7b so that a CS0618 would be emitted whenever the
`AppDomain.CreateDomain()` method was used.
This CS0618 is *not* duplicative of the existing XA2000 warning added
in bbbe2ed3, as the CS0618 will only be emitted when compiling source
code, while the XA2000 can be emitted when referencing an existing
(already compiled) assembly which uses `AppDomain.CreateDomain()`.
That said, the introduction of the `[Obsolete]` caused the
`LinkerTestsWarnAboutAppDomains()` test to start failing, as *two*
warnings were now being emitted by the test, not the expected one.
Update …
=> [Xamarin.Android.Build.Tests] Fix AppDomain warning asserts

Xamarin.Android.sln
Changes: https://github.com/xamarin/xamarin-android-tools/compare/9f4ed4b9c3d2993b69ff16ed0513c5574f561ff1...bfb66f38b77421ac373c06a5f8407e1f9c793cc8
* xamarin/xamarin-android-tools@bfb66f3: Update to sdk-style csproj and netstandard2.0. (#78)
=> Bump to xamarin/xamarin-android-tools/master@bfb66f38

.external
Changes: https://github.com/mono/mono/compare/2edccc52a78d90fea7bcbd37844164663e712397...8b72dbb708681fbde7f0da13fe76d128d62f8686
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1048838
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1050615
Context: https://github.com/mono/mono/issues/18614
* mono/mono@8b72dbb7086: [corlib] Split corlib xunit tests even more for iOS (#18620)
* mono/mono@1e2d68b92c9: Bump bockbuild for Pango patch
* mono/mono@e55302cb080: configure.ac: remove AC_SEARCH_LIBS for libintl (#18595)
* mono/mono@ef8188a08d9: [runtime] Disable lldb backtrace display on osx, it hangs on attaching in lldb. (#18591)
* mono/mono@01be275ad70: [2019-12] Bump msbuild to track mono-2019-10 (#18577)
* mono/mono@f9e5a6d2b2a: [jit] Compute has_references …
=> Bump to mono/mono/2019-12@8b72dbb7

Documentation/guides/messages/README.md, Documentation/guides/messages/xa1006.md, Documentation/guides/messages/xa1008.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/CheckGoogleSdkRequirements.cs
Move the text for the XA1006, XA1007, and XA1008 messages into the
`.resx` file.
Other changes:
Remove "you" and "your" from the messages.
Clarify that the number shown for `$(TargetFrameworkVersion)` is the
corresponding Android API level, not the `$(TargetFrameworkVersion)`
itself.
Make the messages for XA1006 and XA1008 more similar to each other.
=> [Xamarin.Android.Build.Tasks] Move XA1006, XA1007, XA1008 message text into .resx file

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/xamarin-android/pull/4187
We have been able to repro a hang when using ReSharper +
Xamarin.Android with this stack trace:
Xamarin.Build.AsyncTask.dll!Xamarin.Build.AsyncTask.WaitForCompletion() Line 285
Xamarin.Build.AsyncTask.dll!Xamarin.Build.AsyncTask.Execute() Line 226
Xamarin.Android.Build.Tasks.dll!Xamarin.Android.Tasks.AndroidAsyncTask.RunTask()
Xamarin.Android.Build.Tasks.dll!Xamarin.Android.Tasks.AndroidAsyncTask.Execute()
This is happening inside the `<CalculateLayoutCodeBehind/>` MSBuild
task.
Using ReSharper's special "new class" dialog, a design-time build
causes the UI to lock up in VS.
PR #4187 does not fully solve the problem, however the problem *does*
go away if I make `_FindLayoutsToBind` conditional.
`_FindLayoutsToBind` can be …
=> [Xamarin.Android.Build.Tasks] skip _FindLayoutsToBind when feature is unused

.vscode/launch.json, .vscode/tasks.json, Xamarin.Android.sln, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks.csproj, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunAndroidEmulatorCheckBootTimes.cs, build-tools/automation/azure-pipelines.yaml, build-tools/check-boot-times/Program.cs, build-tools/check-boot-times/Properties/AssemblyInfo.cs, build-tools/check-boot-times/check-boot-times.csproj, build-tools/scripts/TestApks.targets
This is a PerfTest tool to be used by the Hyper-V team to be able to compare performance improvement progress.
Example of a run:
```
Testing emulator startup times for 1 execution(s). This may take several minutes.
Acceleration type: 0, WHPX (10.0.19041) is installed and usable.
Android emulator version 29.3.5.0 (build_id 6120838) (CL:N/A)
XamarinPerfTest Average Cold Boot Time for 1 run(s) out of 1 request(s): 34642 ms
XamarinPerfTest Average Hot Boot Time for 1 run(s) out of 1 request(s): 4224 ms
XamarinPerfTestPixelWithSkin Average Cold Boot Time for 1 run(s) out of 1 request(s): 159600 ms
XamarinPerfTestPixelWithSkin Average Hot Boot Time for 1 run(s) out of 1 request(s): 2695 ms
Testing emulator startup times for 1 execution(s). This may take several minutes.
Acceleration type: 0, …
```
=> Android PerfTest tool

.external, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs, tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs, tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs
Changes: https://github.com/xamarin/monodroid/compare/ed9e9e8c...61e5c49f
Bump to xamarin/androidtools/d16-4@765e1cb
Changes: https://github.com/xamarin/androidtools/compare/d400e59...765e1cb
Fixes: https://developercommunity.visualstudio.com/content/problem/858509/adb0030-monoandroidtoolsrequiresuninstallexception-2.html
Fixes: https://work.azdo.io/1041849
[Xamarin.AndroidTools] fix error handling around PushAndInstallPackage
=> Bump to xamarin/monodroid/d16-4@61e5c49f

Configuration.props, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
Context: https://github.com/xamarin/xamarin-android/commit/c5231075e11176db03c338ec370bf18b3e70a8b2
Context: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1032105
As described in [c5231075][0], we should be using the latest versions of
the Android tooling if possible, matching the major version with the max
API level we support.  Xamarin.Android now supports Android 10 (API
level 29), so we should be using the 29.x.x versions of the tooling.
Update `$(AndroidSdkBuildToolsVersion)` to 29.0.2.
Update `$(AndroidSdkPlatformToolsVersion)` to 29.0.5.
[0]: https://github.com/xamarin/xamarin-android/commit/c5231075e11176db03c338ec370bf18b3e70a8b2
=> [Xamarin.Android.Build.Tools] Bump Android tools versions

src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Move the text for the XA4301 and XA0107 messages into the `.resx` file.
Other changes:
Standardize the capitalization of "APK" and "ABI" in the messages.
Replace an exclamation point with a period in one of the XA0107 messages
to make the message a little gentler.
Replace a comma with a period in one of the XA4301 messages.
=> [Xamarin.Android.Build.Tasks] Move XA4301 and XA0107 message text into .resx file

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Linux.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.MacOS.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Windows.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
Context: https://github.com/corretto/corretto-8/blob/develop/CHANGELOG.md#corretto-version-8232092
Context: https://github.com/corretto/corretto-8/blob/develop/CHANGELOG.md#corretto-version-8242071
Context: https://github.com/corretto/corretto-8/blob/develop/CHANGELOG.md#corretto-version-8242081
Security vulnerability severity levels:
* **L** low
* **M** medium
* **H** high
Update includes the following security fixes:
* [CVE-2020-2604 Serialization](https://nvd.nist.gov/vuln/detail/CVE-2020-2604) (**H**)
* [CVE-2020-2601 Security](https://nvd.nist.gov/vuln/detail/CVE-2020-2601) (**M**)
* [CVE-2020-2655 JSSE](https://nvd.nist.gov/vuln/detail/CVE-2020-2655) (**M**)
* [CVE-2020-2593 Networking](https://nvd.nist.gov/vuln/detail/CVE-2020-2593) (**M**)
* [CVE-2020-2654 …
=> [build] Update Corretto OpenJDK to v8.242.08.1

Configuration.props, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
We have been seeing the following errors on
PRs.
error : Method not found: void System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
error :   at NuGet.ProjectModel.LockFileUtilities.GetLockFile (System.String lockFilePath, NuGet.Common.ILogger logger)
This seems to be comming from the Nuget API packages. So
Lets try upgrading them to the latest version to see if
this fixes the issue.
=> Upgrade Nuget API Packages to 5.4.0

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
I found that we were invoking the `<ResolveAssemblyReference/>`
MSBuild task directly:
<ResolveAssemblyReference ...>
<Output TaskParameter="SatelliteFiles" ItemName="_AndroidResolvedSatellitePaths"/>
</ResolveAssemblyReference>
What is weird about this, is that `<ResolveAssemblyReference/>` is
called twice during any Xamarin.Android build.
But the first call from MSBuild itself returns the exact same
assemblies we need here:
Task ResolveAssemblyReference
...
OutputItems
...
ReferenceSatellitePaths
C:\src\weird-solutions\ClassLibrary1\bin\Debug\es\ClassLibrary3.resources.dll
In this example I added a `Strings.resx` and `Strings.es.resx`. The
satellite assembly contains the spanish translation.
It looks to me we can just remove our call to the
`<ResolveAssemblyReference/>` task, and use …
=> [Xamarin.Android.Build.Tasks] don't call <ResolveAssemblyReference/> directly

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
I noticed that VS Windows was showing the `Tests` directory in
`Xamarin.Android.Build.Tasks.csproj` as if many of the files were
included in the project.
In the IDE, I chose "Exclude From Project" in the context menu and it
removed additional files in the `Tests` directory by adding wildcards.
I suspect we might have been including some extraneous
`@(EmbeddedResource)` files in `Xamarin.Android.Build.Tasks.dll`.
=> [Xamarin.Android.Build.Tasks] further exclude Tests\**

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
Context: https://github.com/android/ndk/wiki/Changelog-r21#changelog
Context: https://github.com/android/ndk/wiki/Changelog-r21#known-issues
Summary of changes:
* 32-bit Windows is no longer supported.
* Updated Clang and LLD to r365631
* Updated libc++ to r369764
* Updated glibc to 2.17
* Updated gdb to 8.3
* ndk-build and the CMake toolchain file now enable _FORTIFY_SOURCE by default
* Fixed hiding of unwinder symbols in outputs of ndk-build and CMake
=> [build] Update NDK to r21.0.6113669

build-tools/xaprepare/xaprepare/Steps/Step_DownloadMonoArchive.cs
Context: `master` build failure:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3446638&view=logs&j=96fd57f5-f69e-53c7-3d47-f67e6cf9b93e&t=65256bb7-a34c-5353-bc4d-c02ee25dc133
```
[00:03:37.9358067] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[00:03:37.9358099] Downloading Mono archive
[00:03:37.9358128] =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[00:03:37.9358158] 
[00:03:37.9378132] Checking if all runtime files are present
[00:03:37.9393392] BCL file Mono.Btls.Interface.dll will NOT be included in the installed Designer BCL files (DesignerWindows)
[00:03:37.9418091] File '/Users/builder/azdo/_work/63/s/xamarin-android/bin/Release/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v1.0/I18N.dll' or symbols …
```
=> [xaprepare] If Mono archive extraction fails delete Mono archive.

src/Mono.Android/Android.Runtime/InputStreamInvoker.cs, src/Mono.Android/Test/Android.Runtime/InputStreamInvokerTest.cs, src/Mono.Android/Test/Mono.Android-Test.Shared.projitems
Hi Xamarin Team,
`InputStreamInvoker` lack of seeking support seems like a oversight to me: 
When working with files across apps, `ContentResolver.openInputStream()` returns `ParcelFileDescriptor.AutoCloseInputStream` which is wrapped to `InputStreamInvoker`.
Requiring to copy this stream to a `MemoryStream` just to get seeking support is **bad** for the **memory usage** of any android app, but especially for older and entry level devices.  
This pull request implements seeking for all `FileInputStream` subclasses using `FileChannel` while keeping the old behaviour for other types of streams.
Review Notes:
* Given that `FileChannel` is connected to the `FileInputStream`, it seems good to me to `null` it before closing the stream.
* The channel doesn't required an explicit closed:  
> …
=> InputStreamInvoker: Seeking for FileInputStreams using FileChannels

Xamarin.Android.sln, build-tools/Xamarin.Android.Tools.BootstrapTasks/result-packaging.targets, build-tools/installers/create-installers.targets, build-tools/scripts/TestApks.targets, build-tools/xaprepare/xaprepare/Steps/Step_PrepareLocal.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, tools/apkdiff/ApkDescription.cs, tools/apkdiff/Program.cs, tools/apkdiff/Properties/AssemblyInfo.cs, tools/apkdiff/README.md, tools/apkdiff/apkdiff.csproj, tools/apkdiff/apkdiff.targets, tools/apkdiff/packages.config, tools/scripts/apkdiff
Context: https://github.com/xamarin/xamarin-android/projects/14
Context: https://github.com/xamarin/xamarin-android/issues/4191
And use it to produce `.apkdesc` files. These files will be later used
instead of the size reference files we have now. They contain more
detailed size information and also improve the readability compared to
the `.csv` files.
The `.apkdesc` files look like:
{
"Comment": "HEAD/master: cdc04224edcb876ae6607693ea4011fee8c76893",
"PackageSize": 75817581,
"Entries": {
"AndroidManifest.xml": {
"Size": 5428
},
"res/drawable/android_button.xml": {
"Size": 588
},
...
}
=> Add apkdiff tool

Documentation/guides/messages/README.md, Documentation/guides/messages/xa1002.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/ConvertCustomView.cs, src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs
Move the XA1001 and XA1002 message text into the `.resx` file so that
they are ready for localization.
Other changes:
Remove "we" from the XA1002 message, and change "casing" to
"capitalization" to reduce potential ambiguity for the l10n team.
=> [Xamarin.Android.Build.Tasks] Make XA1001 and XA1002 localizable

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/NdkUtils.cs, src/Xamarin.Android.Build.Tasks/Tasks/NdkUtilsOld.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/MakeBundleNativeCodeExternalTests.cs
Give the XA5101 errors in `NdkUtil` their own new error codes so they
can be distinguished from the `NdkUtilOld` errors in telemetry.
Move the message text for XA5101 and the other new error codes into the
`.resx` file so that they are ready for localization.
=> [Xamarin.Android.Build.Tasks] Split up XA5101 errors and make them localizable

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
When building the SmartHotel360 app, I found that
`<ResolveAssemblies/>` was loading the NuGet `ProjectAssetFile` /
`LockFile` even though it was not used by the task at all. Putting a
`Stopwatch` around the code, I also found it to be somewhat expensive.
I reworked the code to use a `Lazy<T>` for accessing the `LockFile`.
This way it is not actually loaded until it is needed.
I also found several `LogDebugMessage` calls that seemed to be too
much... The `<ResolveAssemblies/>` was emitting hundreds of lines of
logging in the SmartHotel360 app.
I removed two messages such as:
LogDebugMessage ($"Adding {resolved_assembly} to topAssemblyReferences");
...
LogDebugMessage ("{0}={1}", assemblyName, apiLevel);
The `[Input]` and `[Output]` values for the task and the remaining log
message should …
=> [Xamarin.Android.Build.Tasks] perf improvements for <ResolveAssemblies/>

src/sqlite-xamarin/CMakeLists.txt
Fixes: https://github.com/xamarin/xamarin-android/issues/4244
Turns out our `Release` build failed to strip the `sqlite3` shared
library (it was built with `-g`) and so it ended up packaged with all
the debug symbols included, thus unnecessarily growing the size of APKs
we produce.
Pass `-s` to the compiler during `Release` builds so that only the
dynamic symbols are present in the resulting shared library and no debug
symbols are present.
This decreases the shared library around 5 times.
=> [build] Strip sqlite DSO on Release builds

CODEOWNERS
Set @brendanzagaeski and @jonpryor as owners on the draft release notes
directory, the error and warning docs directory, and the
`Resources.resx` file and `xlf/` directory for error and warning
strings.
=> [GitHub] Update CODEOWNERS

Documentation/guides/messages/README.md, Documentation/guides/messages/xa1005.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
Context: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1064104
Remove the uses of "naive", "fixup", and "above" to make the XA1005
warning messages easier to translate to other languages.
=> [Xamarin.Android.Build.Tasks] Adjust XA1005 wording for localization

Documentation/guides/messages/xa0122.md, src/Mono.Android/Java.Interop/DoNotPackageAttribute.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
The `<ResolveAssemblies/>` MSBuild task currently looks for an
attribute in every assembly:
[assembly: Java.Interop.DoNotPackage ("foo.jar")]
`foo.jar` would be used at compile time for java code, but not
included in the final Android app. This seems like the wrong way to go
about things, you can simply add to the `@(AndroidExternalJavaLibrary)`
item group for the same behavior.
I also found very little usage of this on Github:
https://github.com/search?l=C%23&p=1&q=%5Bassembly%3A+DoNotPackage&type=Code
Most of the projects using this are unsupported libraries from the
Xamarin Component store.
If we plan to completely remove `<ResolveAssemblies/>` this is a piece
we will have to deprecate for a period of time first.
=> [Xamarin.Android.Build.Tasks] deprecate [assembly: DoNotPackage]

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/ProcessApkSizes.cs
Our apk size regression testing was using absolute value of the size
difference, which doesn't make much sense in case we reduce the size.
Do not error out, only warn when it happens, so that we keep the
reference actual.
=> [tests] Do not error when we shrink apk size

build-tools/xaprepare/xaprepare/Steps/Step_Android_SDK_NDK.cs
On a "clean" macOS 10.15 Catalina machine -- "clean" such that there
is no JDK installed -- running `make prepare` will cause a macOS GUI
dialog to appear, requesting that a JDK be installed:
$ make prepare PREPARE_ARGS="--ignore-min-mono-version=true"
...
• Checking cmake-3.10.2-darwin-x86_64
installed
TODO: Modify ProcessRunner to allow standard input writing and switch to it here
From: Xamarin.Android.Prepare.Step_Android_SDK_NDK.AcceptLicenses at /Volumes/Xamarin-Work/xamarin-android/build-tools/xaprepare/xaprepare/Steps/	Step_Android_SDK_NDK.cs(103,4)
No Java runtime present, requesting install.
...
The GUI dialog says:
> To use the “java” command-line tool you need to install a JDK.
>
> Click “More Info…” to visit the Java Developer Kit download website.
>
> …
=> [xaprepare] Always set JAVA_HOME for sdkmanager

src/monodroid/jni/application_dso_stub.cc
Older compilers don't support C++ designated initializers for
non-trivial types:
../../../jni/application_dso_stub.cc:26:1: sorry, unimplemented: non-trivial designated initializers not supported
Don't use them.
=> [build] Unbreak native code builds with older compilers

src/Xamarin.Android.Build.Tasks/Tasks/MonoSymbolicate.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/2654
If you build a Xamarin.Forms template in `Release` with
`MonoSymbolArchive=True`, you get many warnings such as:
Warning: Directory obj\Release\android\assets contains Xamarin.Android.Arch.Core.Common.dll but no debug symbols file was found.
Warning: Directory obj\Release\android\assets contains Xamarin.Android.Arch.Core.Runtime.dll but no debug symbols file was found.
Warning: Directory obj\Release\android\assets contains Xamarin.Android.Arch.Lifecycle.Common.dll but no debug symbols file was found.
Warning: Directory obj\Release\android\assets contains Xamarin.Android.Arch.Lifecycle.LiveData.Core.dll but no debug symbols file was found.
Warning: Directory obj\Release\android\assets contains …
=> [Xamarin.Android.Build.Tasks] mono-symbolicate warnings are messages

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/MacOS.cs
The release updates GCC version to 9.2, brings compatibility updates with
Windows headers and adds `__FORTIFY_SOURCE` support.
=> [build] Update MinGW on Mac to v7.0.0

Documentation/guides/messages/README.md, Documentation/guides/messages/xa4305.md, Documentation/guides/messages/xa4309.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/CompileToDalvik.cs, src/Xamarin.Android.Build.Tasks/Tasks/CreateMultiDexMainDexClassList.cs, src/Xamarin.Android.Build.Tasks/Tasks/R8.cs
[3757be20][0] moved the XA4305 messages for `<CompileToDalvik/>` into
the `.resx` file, but it overlooked the uses of XA4305 in
`<CreateMultiDexMainDexClassList/>` and `<R8/>`.
The original uses of XA4305 in `<CreateMultiDexMainDexClassList/>` and
`<R8/>` were a little confusing because the `@(MultiDexMainDexList)`
MSBuild item corresponds to the `CustomMainDexListFiles` property in the
tasks, not the `MultiDexMainDexListFile` property.
To reduce the potential for confusion between `@(MultiDexMainDexList)`
and `MultiDexMainDexListFile` and to separate them in telemetry, give
the warning message related to `@(MultiDexMainDexList)` its own new
XA4309 warning code, reword …
=> [Xamarin.Android.Build.Tasks] Update multidex warnings & make localizable

build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, tools/apkdiff/apkdiff.csproj, tools/scripts/apkdiff
We were clashing with `Xamarin.Android.Build.Tasks` project assemblies in
`lib/xamarin.android/xbuild/Xamarin/Android/`, so put it in `lib/xamarin.android/xbuild/Xamarin/Android/apkdiff/` instead.
There were 2 issues:
* the `Xamarin.Android.Build.Tasks` project requires `netstandard2.0` version of
`libZipSharp.dll`. Sometimes the `apkdiff` is built after
`Xamarin.Android.Build.Tasks` and thus we end up with `net45` version,
which causes errors like this one:
C:\A\xamarin-v00000K-1\_work\1\s\packages\xamarin.android.sdk\0.0.1\tools\Xamarin.Android.Common.targets(785,2): error MSB4062: The "Xamarin.Android.Tasks.ResolveSdks" task could not be loaded from the assembly C:\A\xamarin-v00000K-1\_work\1\s\packages\xamarin.android.sdk\0.0.1\tools\Xamarin.Android.Build.Tasks.dll. Could not load …
=> [apkdiff] Put apkdiff tool in separate output directory

build-tools/automation/CredScanSuppressions.json, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-timezoneinfo-tests.yaml, build-tools/automation/yaml-templates/upload-results.yaml
Fixes: https://github.com/xamarin/xamarin-android/issues/4241
Context: https://github.com/xamarin/yaml-templates/commit/fc7eb6822ea92ee000258b6fff71e80b8d1022f5, https://github.com/xamarin/yaml-templates/commit/af29b0c60164f883bc597544a178fa6cd53eae9e
Bumps our static analysis template to a new version that will allow us
to specify the version of the `credscan` tool to use. This template will
use `V2` by default, but can be overridden as needed:
```yaml
- template: security\xa-static-analysis\v2.yml@yaml
parameters:
credScanSuppressionsFile: $(System.DefaultWorkingDirectory)\build-tools\automation\CredScanSuppressions.json
toolMajorVersion: V1
```
Artifact publishing and downloading tasks have also been bumped to their
latest versions.
=> [ci] Bump credscan and artifact task versions

build-tools/create-vsix/create-vsix.csproj, build-tools/create-vsix/symbols/ExternalWhiteList.csv, build-tools/installers/create-installers.targets, build-tools/scripts/MSBuildReferences.projitems, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, src/Xamarin.Android.Tools.JavadocImporter/Xamarin.Android.Tools.JavadocImporter.csproj
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3468220&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=da4239c9-cabf-50a7-e7ce-52be5c6d9883
A recent PR updating the Xamarin.Android version in Visual Studio
reported a new failure in SymbolCheck. The two files which were reported
to be missing symbols are:
$msbuild\xamarin\android\mono.posix.netstandard.dll
xamarin.android.sdk.dll
Some thorough sleuthing by @jonpryor indicated that we likely don't need
to be redistributing `Mono.Posix.NETStandard.dll` in our installers at
all. Various unecessary package references have been removed, and the
set of files required by our installers has been updated to reflect this
discovery. This removal should also appease the Symbol Check process.
We aren't sure why Symbol Check …
=> [installers] Remove Mono.Posix.NETStandard and add missing symbols

Configuration.props, Documentation/building/configuration.md, Documentation/workflow/HowToBumpMono.md, build-tools/xaprepare/xaprepare/Application/KnownProperties.cs, build-tools/xaprepare/xaprepare/Application/Properties.Defaults.cs.in, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.MacOS.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/MacOS.cs, build-tools/xaprepare/xaprepare/Steps/Step_PrepareImageDependencies.MacOS.cs, build-tools/xaprepare/xaprepare/xaprepare.targets
We have a bit of a disconnect with respect to our dependency on Mono
across different tools. `xaprepare` has some Mono version information
embedded in it, and we duplicate some of this information in
`Configuration.props`. Furthermore, we don't do an adequate job of
enforcing a version ceiling in our Azure Pipelines builds.
For additional context, see https://github.com/xamarin/xamarin-android/pull/4219
for all of the places that require updating when we bump the version of
Mono that we depend on.
In order to improve this story, `xaprepare` has been updated to gather
all Mono dependency information from `Configuration.props`, and no
longer specifies any version information of its own. We will also now
roll back the installation of Mono on CI builds if the installed version
exceeds the max …
=> [build] Consolidate Mono dependency information

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/RemoveAttributes.cs
Context: https://github.com/xamarin/xamarin-android/issues/4231
The size increase comes from added attributes and attribute types. The related
`apkdiff` output:
+        3584 assemblies/Java.Interop.dll
...
+             Type Microsoft.CodeAnalysis.EmbeddedAttribute
+             Type System.Runtime.CompilerServices.NullableAttribute
+             Type System.Diagnostics.CodeAnalysis.AllowNullAttribute
+             Type System.Diagnostics.CodeAnalysis.MaybeNullAttribute
+             Type System.Diagnostics.CodeAnalysis.NotNullAttribute
+             Type System.Diagnostics.CodeAnalysis.NotNullWhenAttribute
+             Type System.Diagnostics.CodeAnalysis.NotNullIfNotNullAttribute
...
Comparison of #4279 and master build (d543a8ac5ed65bcb1cc5d1d65cca1ba3344a62ed):
```
mono apkdiff.exe …
```
=> [linker] Remove more non-nullable related attributes

Documentation/guides/messages/xa5205.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/Lint.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs
Move the message strings for XA5205 and several of the message strings
for XA5300 into the `.resx` file so that they are localizable.
`ResolveJdkJvmPath.cs` contains a few other uses of XA5300 that have
been left unchanged for now so that they can be considered separately.
Other changes:
Adjust the capitalization of "Build-Tools" to match the capitalization
from the Android repository manifest.
Remove the Android SDK directory message from the XA5205 documentation
because that message is currently associated with XA5300 instead.
=> [Xamarin.Android.Build.Tasks] Make XA5205 and some of XA5300 localizable

.external, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs, tests/BCL-Tests/Xamarin.Android.Bcl-Tests/nunit-excluded-tests.txt
Changes: https://github.com/mono/mono/compare/1cca0cfebfcbd019c6f2bdd3e5b99f769f1e2e0c...c0c5c78e2bdbdbf7a70ae10b0a698708f1f2edbe
For mainly these two:
https://github.com/mono/mono/pull/18764
https://github.com/mono/mono/pull/18832
To let users to set custom httphandler to legacy `MonoWebRequestHandler`
```xml
<AndroidHttpClientHandlerType>System.Net.Http.MonoWebRequestHandler, System.Net.Http</AndroidHttpClientHandlerType>
```
For NTLM scenarios (see https://github.com/mono/mono/pull/18764 for more details)
=> Bump to mono/mono/2019-10@c0c5c7

Documentation/release-notes/4260.md, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
I was using the Mono profiler for our build, and I noticed:
180765632    2142803       84 System.String
53218472 bytes from:
MonoDroid.Tuner.FixAbstractMethodsStep:FixAbstractMethods (Mono.Cecil.AssemblyDefinition)
MonoDroid.Tuner.FixAbstractMethodsStep:FixAbstractMethodsUnconditional (Mono.Cecil.AssemblyDefinition)
MonoDroid.Tuner.FixAbstractMethodsStep:FixAbstractMethods (Mono.Cecil.TypeDefinition)
MonoDroid.Tuner.FixAbstractMethodsStep:HaveSameSignature (Mono.Cecil.TypeReference,Mono.Cecil.MethodDefinition,Mono.Cecil.MethodDefinition)
(wrapper managed-to-native) string:FastAllocateString (int)
~53MB of string from this one method is a lot!
I found that one of these `string.Format` calls are running for almost
every method on every …
=> [linker] remove unneeded string.Format calls

build-tools/automation/azure-pipelines.yaml
In #4161 we created a new YAML variable called `IsMonoBranch` that checks if the branch name contains `mono-` so we could determine if it's a mono integration branch.  If it is, we would like to run the full regression test suite on it at the PR stage and not wait until the branch is merged.  This is because a Mono build is riskier and has a higher chance of breaking stuff.
However, the way this was implemented: `contains(variables['Build.SourceBranchName'], 'mono-')` only works for manually run builds (which is how I tested it and confirmed that it works).  If the build is kicked off automatically from the PR, `Build.SourceBranchName` is overwritten with the value `"merge"` (https://github.com/microsoft/azure-pipelines-tasks/issues/8793).  Thus we have not been running these suites on …
=> [CI] Ensure Mono integration branch PRs run the full regression suite.

build-tools/xaprepare/xaprepare/Application/HomebrewProgram.MacOS.cs, build-tools/xaprepare/xaprepare/Application/Program.cs, build-tools/xaprepare/xaprepare/OperatingSystems/OS.cs, build-tools/xaprepare/xaprepare/ToolRunners/BrewRunner.MacOS.cs
Brew allows installation of several versions of a single software package on the system,
even though only one of them can be "linked" into the installation prefix and directly
accessible to the user. This is generally fine, unless the version currently linked does not
work with the version of macOS running on the machine or is otherwise broken.
In our case, some CI bots managed to install two versions of mingw - the old v6.0.0 and the
new v7.0.0 with the former being the default or with the package not linked at all, and the
confusion leading to errors similar to the one below:
20:24:43  [CMake] running
20:24:43  [CMake] log file: bin/BuildRelease/prepare-20200220T152055.cmake.dlfcn-win32-mxe-Win32-configure.log
20:24:43  Running: /usr/local/bin/cmake "-GNinja" …
=> [build macOS] Properly handle multiple versions of installed software

.external, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs, tests/BCL-Tests/Xamarin.Android.Bcl-Tests/nunit-excluded-tests.txt
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1070776/
Context: https://github.com/mono/mono/pull/18764
Context: https://github.com/mono/mono/pull/18832
Changes: https://github.com/mono/mono/compare/8b72dbb708681fbde7f0da13fe76d128d62f8686...cec38fcfc83c25901a4301383ce4ee12ebebe315
* mono/mono@cec38fcfc83: Bump bockbuild to bring in Gtk# regression fix (#18911)
* mono/mono@0761b0ee554: [2019-12] Make MonoWebRequestHandler linker friendly (#18833)
* mono/mono@0c45a74a967: Move HttpClientHandlerTests.Android.cs to nunit (#18889)
* mono/mono@d5f5f3762fc: [2019-12] Bump msbuild to track mono-2019-10 (#18862)
* mono/mono@f1bdf8a93de: Move offsets-tool into mono/tools (#18830)
* mono/mono@3fdc3c84b28: [2019-12] Bump msbuild to track mono-2019-10 (#18792)
* …
=> Bump to mono/mono/2019-12@cec38f (#4287)

src/Xamarin.Android.Build.Tasks/Utilities/NativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingNativeAssemblyGenerator.cs
Using the Mono profiler, I saw:
28784408     432288       66 System.String
...
2353592 bytes from:
Xamarin.Android.Tasks.TypeMappingNativeAssemblyGenerator:WriteJavaMap (System.IO.StreamWriter,string)
Xamarin.Android.Tasks.TypeMappingNativeAssemblyGenerator:WriteJavaMapEntry (System.IO.StreamWriter,Xamarin.Android.Tasks.TypeMapGenerator/TypeMapEntry,int)
Xamarin.Android.Tasks.NativeAssemblyGenerator:WriteCommentLine (System.IO.StreamWriter,string,bool)
Xamarin.Android.Tasks.NativeAssemblyGenerator:WriteComment (System.IO.StreamWriter,string,bool)
(wrapper alloc) object:ProfilerAllocString (intptr,int)
(wrapper managed-to-native) object:__icall_wrapper_mono_profiler_raise_gc_allocation (object)
1239424 bytes from: …
=> [Xamarin.Android.Build.Tasks] less string alloc in native assembly generation

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Now that [03743f32][0] has switched the
`Xamarin.Android.Build.Tasks.csproj` file to the short-form project
style, some item metadata needs to be added explicitly to
`Resources.resx` and `Resources.Designer.cs` to tell Visual Studio to
generate `Resources.Designer.cs` from `Resources.resx` as expected.  The
short-form project style does add the files automatically to the
appropriate `@(EmbeddedResource)` and `@(Compile)` item lists via the
default wildcard includes, but it doesn't add this metadata.
The new items are almost the same as in [0342fe56][1], but they use the
`Update` attribute instead of the `Include` attribute because now the
items are already included via the wildcard includes.
[0]: https://github.com/xamarin/xamarin-android/commit/03743f32aec3b02edc280886061b12e0dde0bd1c …
=> [Xamarin.Android.Build.Tasks] Re-enable Resources.Designer.cs generation

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
I was profiling builds with the Mono profiler and noticed:
Method call summary
Total(ms) Self(ms)      Calls Method name
70862       97      89713 Java.Interop.Tools.Cecil.DirectoryAssemblyResolver:Resolve (Mono.Cecil.AssemblyNameReference,Mono.Cecil.ReaderParameters)
Almost 90K calls? What is that coming from???
61422 calls from:
Java.Interop.Tools.Cecil.TypeDefinitionRocks/<GetTypeAndBaseTypes>d__1:MoveNext ()
Java.Interop.Tools.Cecil.TypeDefinitionRocks:GetBaseType (Mono.Cecil.TypeDefinition)
Mono.Cecil.TypeReference:Resolve ()
Mono.Cecil.ModuleDefinition:Resolve (Mono.Cecil.TypeReference)
Mono.Cecil.MetadataResolver:Resolve (Mono.Cecil.TypeReference)
Java.Interop.Tools.Cecil.DirectoryAssemblyResolver:Resolve (Mono.Cecil.AssemblyNameReference)
Ok, this jogged my memory. …
=> [Xamarin.Android.Build.Tasks] use Java.Interop's TypeDefinitionCache

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/JavaToolTask.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tasks/Lint.cs
Move the message strings for XA0108, XA2006, & XA5213 into the `.resx`
file so that they are localizable.
=> [Xamarin.Android.Build.Tasks] Make XA0108, XA2006, & XA5213 localizable

build-tools/xaprepare/xaprepare/Application/HomebrewProgram.MacOS.cs, build-tools/xaprepare/xaprepare/ToolRunners/BrewRunner.MacOS.cs
Turns out we can sometimes have a situation when a homebrew package is
installed but it's not linked into a directory that's found in the
user's `PATH` environment variable.
Remedy the situation by unconditionally linking all the packages we
depend on.
=> [xaprepare] Further steps to fix brew

src/Xamarin.Android.Build.Tasks/Tasks/CreateManagedLibraryResourceArchive.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildAssetsTest.cs
Fixes: https://developercommunity.visualstudio.com/content/problem/917114/xamarinandroidtask-createmanagedlibraryresourcearc.html
Fixes: https://feedback.devdiv.io/917114
Creating an `@(AndroidAsset)` with a full path pointing outside your
project in a Xamarin.Android class library:
<AndroidAsset Include="C:\path\to\foo.txt" LogicalName="Assets\foo.txt" />
Results in:
(_CreateManagedLibraryResourceArchive target) ->
error MSB4018: The "CreateManagedLibraryResourceArchive" task failed unexpectedly.
error MSB4018: System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
error MSB4018: Parameter name: startIndex
error MSB4018: at System.String.Substring(Int32 startIndex, Int32 length)
error MSB4018: at System.String.Substring(Int32 startIndex)
error MSB4018: at …
=> [Xamarin.Android.Build.Tasks] fix AndroidAsset with full path

src/Mono.Android/Android.Graphics/Color.cs
Unfortunately we detected that change 1d5ed48 causes cyclic dependency issues.
Xamarin forms have the follow usage that exposes the issue:
SetScrimColor(isShowingSplit ? Color.Transparent.ToAndroid() : (int)DefaultScrimColor);
the example above is unable to determine the correct usage, because now ToAndroid() returns Color, while DefaultScrimColor returns int.
The initial thoughts of having this extra operator was very good, but unfortunately we will not be able to keep at this time due to the reasons mentioned above.
=> Reverting "[Mono.Android] Add implicit int -> Color operator (#4120)"

Documentation/building/configuration.md, src/Mono.Android/Mono.Android.targets
The API compatibility check runs after Mono.Android and friends are
built and on my machine it takes over 1.5 minutes to run:
107208 ms  CheckApiCompatibility                      1 calls
Provide a way to optionally disable the check: set the
`DisableApiCompatibilityCheck` property to `True`.
By default the check is enabled.
=> [build] Optionally disable API compatibility check
