Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/MakeBundleNativeCodeExternal.cs, src/Xamarin.Android.Build.Tasks/Tasks/NdkUtils.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/MakeBundleNativeCodeExternalTests.cs
Move the message strings for XA5102, XA5103, & XA5201 into the `.resx`
file so that they are localizable.
Other changes:
Reword "resulted in an error" to "exited with an error".
Renumber the conflicting XA5102 and XA5103 codes that I accidentally
added in 8acd915e.
Add the comment about the term "assembly" from XA5102 to the comments
for XA3004 as well because that message involves the same other meaning
of "assembly".
=> [Xamarin.Android.Build.Tasks] Make XA5102, XA5103, & XA5201 localizable

Documentation/guides/profiling.md
I had Windows-style directory separators, which doesn't appear to work in Github.
It worked in VS Code on Windows, so I didn't notice it there.
=> [docs] fix broken image link in profiling.md

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/Proguard.cs, src/Xamarin.Android.Build.Tasks/Tasks/R8.cs, src/Xamarin.Android.Build.Tasks/Tasks/ReadAndroidManifest.cs
Move the message strings for XA4218, XA4304, & XA4307 into the `.resx`
file so that they are localizable.
Other changes:
Standardize the capitalization of "ProGuard" in the messages.
=> [Xamarin.Android.Build.Tasks] XA4218, XA4304, & XA4307 l10n support

build-tools/automation/azure-pipelines.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DeferredBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EnvironmentContentTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/Aapt2Tests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/WearTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Introduces a new `SmokeTests` category to `Xamarin.Android.Build.Tests`
as part of a broader effort to help split up our test execution and
improve turnaround times for our Azure Pipelines builds. My selection
of tests to add to this category was somewhat arbitrary, but it includes
a handful of build, rebuild, and incremental build scenarios, as well as
multiple project configurations (including AOT and Bundle Assemblies),
and native/java build actions.
We've also been seeing a somewhat rare case where the VS instance on our
Windows machines becomes unlaunchable and the `MSBuild` task falls back
to a very old version, breaking the build. I've attempted to fix this by
updating our script that reverts the version of XA installed with VS to
first try to resume a partial visual studio …
=> [Xamarin.Android.Build.Tests] Add SmokeTests category

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Extensions.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Linker.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
Context: https://github.com/xamarin/java.interop/commit/b81cfbb9ab8efa647a3bfcc2b2b97a5f1b1fa71e
Similar to aff3b52e, we can use `TypeDefinitionCache` in a few places
in the linker. My approach was to make each linker step require a
`TypeDefinitionCache` for its constructor as needed. This made a
single `TypeDefinitionCache` used throughout a linker `Pipeline`. The
`<LinkAssembliesNoShrink/>` MSBuild task could also control the
lifetime of the `TypeDefinitionCache`.
The results of building the Xamarin.Forms integration project on
Windows:
Before:
706 ms  LinkAssembliesNoShrink                     1 calls
After:
695 ms  LinkAssembliesNoShrink                     1 calls
On macOS / mono:
Before:
1248 ms  LinkAssembliesNoShrink                     1 calls
After:
1228 ms …
=> [linker] use Java.Interop's TypeDefinitionCache

tools/xabuild/SymbolicLink.cs
For some reasons `Path.GetFullPath (path)` and `GetRealPath (path)` has values which was different case and it reports `bin\Debug\lib\xamarin.android\xbuild\Microsoft` as symlink.
Example difference in cases:
```
d:\xamarin-android\bin\Debug\lib\xamarin.android\xbuild\Microsoft <-> D:\xamarin-android\bin\Debug\lib\xamarin.android\xbuild\Microsoft
```
Fix #4306
=> Properly compare paths

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs, src/Xamarin.Android.Build.Tasks/Utilities/AsyncTaskExtensions.cs
Move the message strings for XA0000, XA0001, XA0104, XA0111, XA0112,
XA0113, & XA0117 into the `.resx` file so that they are localizable.
Other changes:
Make "SHOULD NOT BE REACHED" lowercase to simplify translation since
some languages do not use all caps for emphasis.
Replace "Sequence Point mode" with the literal name of the associated
MSBuild property `$(AndroidSequencePointsMode)` so it doesn't need to be
translated.
=> [Xamarin.Android.Build.Tasks] ResolveAndroidTooling l10n support

.gitignore
We generate 3 `.targets` files in the `Novell` directory when building XA.  These files should not be committed to source control.
- Novell/MonoDroid.FSharp.targets
- Novell/Novell.MonoDroid.Common.targets
- Novell/Novell.MonoDroid.CSharp.targets
=> [gitignore] Ignore generated Novell .targets.

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/CompileNativeAssembly.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkApplicationSharedLibraries.cs, src/Xamarin.Android.Build.Tasks/Tasks/NdkUtilsOld.cs
Move the message strings for XA3004 & XA3005 into the `.resx` file so
that they are localizable.
Other changes:
Renumber the conflicting XA3004 & XA3005 codes that I accidentally added
in 1524e6e2.
=> [Xamarin.Android.Build.Tasks] XA3004 & XA3005 l10n support

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/apk-instrumentation.yaml, build-tools/automation/yaml-templates/fail-on-issue.yaml, build-tools/automation/yaml-templates/run-integrated-regression-tests.yaml, build-tools/automation/yaml-templates/run-nunit-tests.yaml, build-tools/automation/yaml-templates/run-timezoneinfo-tests.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3482854&view=logs&j=8a30e15e-2b03-5f17-c7f5-98058d3d9cd8&t=47d4d312-ac98-567e-7ba2-f57378c80633
Replaces `succeededOrFailed()` conditions with `continueOnError: true`
to ensure that steps that should be treated as fatal stop execution of
a job. Previously, all test steps would run regardless of the success of
a prior step, even if that step was necessary (e.g. building a test
suite before running it). A job should continue if any step with the new
`continueOnError: true` parameter fails, and we should now abort earlier
when a step without this parameter errors out.
A new template has been added to ensure jobs which encounter issues
in tests are still flagged as failed (rather than `SucceededWithIssues`).
Finally, I've …
=> [ci] Improve test execution conditions

.external
Changes: https://github.com/mono/mono/compare/fc145be98c719a15ed7182506185e84851803e1d...b33fa1d00ed3b3c16c9abf8c623bb089c6ddc669
Context: https://github.com/mono/mono/issues/17140
Context: https://github.com/mono/mono/issues/18796
Context: https://github.com/mono/mono/issues/18941
* mono/mono@b33fa1d00ed: Backport 2020-02 enable embedded ppdb. (#19050)
* mono/mono@8a687a40444: Bump bockbuild for Pango nil check fix
* mono/mono@44703b3eccd: [merp] Produce hashes for unmanaged thread stacks also (#18964)
* mono/mono@0ac7105eddd: [merp] Increase buffer size for state dump (#18839)
* mono/mono@147ecc0ac36: [2019-12] Bump msbuild to track mono-2019-10 (#18986)
* mono/mono@e7b4669bc9a: Added some parenthesis and a cast to control order of operations. (#18984)
Allows mono to use embedded …
=> Bump to mono/mono/2019-12@b33fa1d0

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
Move the message strings for XA0105, XA0118, & XA2002 into the `.resx`
file so that they are localizable.
Other changes:
Reword the XA0105 message to avoid "you" and "your".
Replace "target" with "`target` in lock file" so that "`target`" can be
left unlocalized.
=> [Xamarin.Android.Build.Tasks] ResolveAssemblies l10n support

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/MemoryStreamPoolTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/MonoAndroidHelperTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/MemoryStreamPool.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs
Expanding upon 87ee20c5, there are two places in
`<GenerateJavaStubs/>` that was using a `new MemoryStream` and
`BinaryWriter`. This adds a new `CreateBinaryWriter()` method with the
same behavior as the `CreateStreamWriter()` method.
This should reduce the allocations of two large `byte[]` /
`MemoryStream` instances each time `<GenerateJavaStubs/>` runs.
Results:
Before:
157629088      37858     4163 System.Byte[]
77760        972       80 System.IO.MemoryStream
After:
157608824      37856     4163 System.Byte[]
77600        970       80 System.IO.MemoryStream
~20,104 bytes saved. I can't really tell a difference performance-wise.
It is probably worth doing this, just to standardize `MemoryStream` use.
I also removed some unused …
=> [Xamarin.Android.Build.Tasks] BinaryWriter support for MemoryStreamPool

build-tools/xaprepare/xaprepare/Application/Context.cs, build-tools/xaprepare/xaprepare/Application/Scenario.cs, build-tools/xaprepare/xaprepare/OperatingSystems/OS.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_PrepareExternal.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_Required.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_Standard.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_ThirdPartyNotices.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_UpdateMono.Unix.cs
When updating Mono from an older version (e.g. 6.6) `xaprepare` can
crash as soon as the Mono package is installed with exceptions similar
to the ones below:
System.InvalidOperationException: Failed to obtain version information from the cc compiler
at Xamarin.Android.Prepare.Unix.DetectCompilers () [0x00344] in build-tools/xaprepare/xaprepare/OperatingSystems/Unix.cs:102
at Xamarin.Android.Prepare.OS.ConfigureEnvironment () [0x00096] in build-tools/xaprepare/xaprepare/OperatingSystems/OS.cs:371
at Xamarin.Android.Prepare.OS.Init () [0x000e6] in build-tools/xaprepare/xaprepare/OperatingSystems/OS.cs:254
at Xamarin.Android.Prepare.Context.Init (System.String scenarioName) [0x0026c] in build-tools/xaprepare/xaprepare/Application/Context.cs:761
at Xamarin.Android.Prepare.App.Run …
=> [xaprepare] Do less when updating Mono

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tasks/WriteLockFile.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
Move the message strings for XA1000, XA4303, XA5207, & XA5302 into the
`.resx` file so that they are localizable.
=> [Xamarin.Android.Build.Tasks] XA1000, XA4303, XA5207, & XA5302 l10n support

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/ValidateJavaVersion.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ValidateJavaVersionTests.cs
Move the message strings for XA0030, XA0031, XA0032, XA0033, & XA0034
into the `.resx` file so that they are localizable.
Other changes:
Use the literal name `$(TargetFrameworkVersion)` so that it doesn't need
to be localized.
Standardize the name "Android SDK Build-Tools" to match XA5205.
Replace a usage of "it" in the message for XA0033 to reduce potential
ambiguity for the l10n team.
=> [Xamarin.Android.Build.Tasks] ValidateJavaVersion l10n support

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3520928&view=ms.vss-test-web.build-test-results-tab&runId=11613622&resultId=100500&paneView=debug
Xamarin.Android.Build.Task tests which attempt to look up the path to
aapt/aapt2 recently started failing on the Azure Pipelines hosted macOS
machine pool [0]. I suspect this is caused by a preview version of tools
ending up on the machine. I think we can be a bit more lenient when
locating the latest version of build-tools by instead using a string
comparison. This will also allow the relevant tests to use a preview
version of build-tools if they exist. Additional logging has also been
added to confirm this hypothesis.
[0]:
System.FormatException : Input string was not in a correct format.
at …
=> [tests] Be more flexible when parsing build-tools versions

Documentation/release-notes/4308.md, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Invoking keytool takes about 200ms (my machine, best case, likely mostly due to java startup). Peppers and I were looking for ways to speed up Apply Changes builds and Android builds in general. For Apply Changes, removing the call to keytool (or caching its result if it's needed) was next on my optimization list.
It looks like the KeyTool invocation isn't needed at all.
Here's the commit which added it, 5 years ago: https://github.com/xamarin/monodroid/commit/fe94c0a88ca68e78a639d0032fb59dd91409e9ca
The comment there says "emit the SHA1 during the _Sign target to make it easier for people to publish to google play".
But note that:
- KeyTool is only run when the AndroidKeyStore isn't supplied, so it's only run when using the default debug keystore, not when the user supplies one
- I don't …
=> Remove KeyTool from signing

src/Mono.Android/Android.Telephony.Mbms/IGroupCallCallback.cs, src/Mono.Android/Mono.Android.csproj, src/Mono.Android/Mono.Android.targets, src/Mono.Android/metadata, tests/api-compatibility/acceptable-breakages-v10.0.99.txt
Context: https://github.com/xamarin/java.interop/issues/509
Using the new features provided by C#8 to provide bindings that mirror the original Java `android.jar` more closely.
Enable `--lang-features=default-interface-methods` to start generating `default` methods on all interfaces in `Mono.Android.dll` API-30+.
=> [Mono.Android] Generate default interface members for API-30+.

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/Linux.Ubuntu.cs
Ubuntu 20.04 (focal fossa) no longer includes the `libx32ncurses6-dev`
package. Don't try to install when running on Ubuntu version 20 or
higher.
=> [xaprepare] Update dependencies on Ubuntu 20.04

build-tools/installers/create-installers.targets, build-tools/scripts/redirect-BCL.xml.in
Context: 1d053ec45b416c2ad1d8e2b702ab201b595f7975
Commit 1d053ec4 added the classlib docs and doc redirect files for
`Mono.Android.dll` and `OpenTK-1.0.dll` to the OSS installers, but it
unintentionally overlooked the doc redirect files for the BCL
assemblies.
Those redirect files don't require anything from monodroid, so it makes
sense to generate them as part of the xamarin-android build and include
them into the Windows OSS installers.
Other changes:
Remove the unneeded doc redirect files for the `Mono.*` assemblies.
.NET Framework does not have documentation for those assemblies, so the
redirect files aren't useful.
Include `Xamarin.Android.NUnitLite.xml` into the Windows OSS installers.
`Xamarin.Android.NUnitLite.csproj` already generated that file during
OSS builds, but the file was …
=> [build] Add BCL doc redirects to OSS installers

Configuration.props, Documentation/release-notes/4320.md, build-tools/check-boot-times/check-boot-times.csproj, build-tools/installers/create-installers.targets, build-tools/scripts/MSBuildReferences.projitems
Context: https://github.com/xamarin/LibZipSharp/pull/50
When profiling xamarin-android builds with the Mono profiler, I noticed
`libZipSharp` is one of the biggest allocators of `byte[]`:
251089192      57759     4347 System.Byte[]
94852584 bytes from:
Xamarin.Tools.Zip.ZipArchive:Close ()
(wrapper managed-to-native) Xamarin.Tools.Zip.Native:zip_close (intptr)
(wrapper native-to-managed) Xamarin.Tools.Zip.ZipArchive:stream_callback (intptr,intptr,ulong,Xamarin.Tools.Zip.SourceCommand)
Xamarin.Tools.Zip.ZipArchive:stream_callback (intptr,intptr,ulong,Xamarin.Tools.Zip.SourceCommand)
(wrapper alloc) object:ProfilerAllocVector (intptr,intptr)
(wrapper managed-to-native) object:__icall_wrapper_mono_gc_alloc_vector (intptr,intptr,intptr) …
=> Bump to libZipSharp 1.0.10

src/Mono.Android/Mono.Android.targets, src/Mono.Android/metadata
Context: https://github.com/xamarin/java.interop/issues/509
Beginning with C#8, interfaces may now contain nested types.  This allows us to better match the `android.jar` we are binding.  However, we cannot nest any types prior to API-30, as that would result in a breaking API change.
This PR:
- Enables the `generator` flag: `--lang-features=nested-interface-types`, which will nest all types on interfaces using C#8.
- Adds `metadata` that looks for all `@merge.SourceFile` prior to API-30 and adds the `unnest=true` attribute to those types.  This attribute tells `generator` to treat them as legacy "unnested" types for backwards compatibility.
API diff between `master` `API-30` and this PR: https://gist.github.com/jpobst/a23ecebbed0837a1abfe7c6cbd7ecf1e
=> [Mono.Android] Allow interfaces to contain nested types starting with API-30

build-tools/automation/azure-pipelines.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3531536&view=logs&jobId=bfe1c8f0-0562-5169-4501-8cf84831035d&j=bfe1c8f0-0562-5169-4501-8cf84831035d&t=8d0f59aa-88c2-53a6-661f-85ce58936952
Context: https://github.com/xamarin/xamarin-android/commit/ed29bf1d47661e9df8458b5be074ed0369752b0b
Designer test jobs have been failing when attempting to checkout a
different source branch after cloning the repo. It seems that the value
of `$(System.DefaultWorkingDirectory)` has changed recently. The value
of this this variable will apparently change depending on the number of
checkout steps in a given job, and whether or not those checkout steps
use a custom path.
=> [ci] Fix path to designer checkout

Documentation/guides/messages/README.md, Documentation/guides/messages/xa4310.md, Documentation/release-notes/xa4310.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/AndroidApkSigner.cs, src/Xamarin.Android.Build.Tasks/Tasks/AndroidSignPackage.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Context: User comments on https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1073446
A user noticed that the error messages from `<AndroidSignPackage/>` and
`<AndroidApkSigner/>` did not provide much information when
`$(AndroidKeyStore)` was `true` and `$(AndroidSigningKeyStore)` was set
to a file that did not exist.
For `$(AndroidPackageFormat)`=`aab`, `<AndroidSignPackage/>` produced
the error:
error MSB6006: "jarsigner.exe" exited with code 1
For `$(AndroidPackageFormat)`=`apk`, `<AndroidApkSigner/>` produced
the error:
error MSB6006: "java.exe" exited with code 2
To improve this, add a new XA4310 error with a more descriptive message.
=> [Xamarin.Android.Build.Tasks] Add XA4310 for keystore not found

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunParallelCmds.cs, build-tools/api-xml-adjuster/api-xml-adjuster.targets
Improve the build speed by running the class-parse and api-xml-adjuster tools in parallel.
Measured times:
Original:
Project Performance Summary:
60265 ms  C:\Users\rodo\git\xamarin-android\build-tools\api-xml-adjuster\api-xml-adjuster.csproj   1 calls
60265 ms  _AdjustApiXml                              1 calls
Target Performance Summary:
20 ms  _DefineApiFiles                            1 calls
26117 ms  _AdjustApiXml                             16 calls
34116 ms  _ClassParse                               16 calls
Task Performance Summary:
3 ms  MakeDir                                   16 calls
5 ms  CreateItem                                16 calls
60221 ms  Exec                                      32 calls
New:
Project Performance Summary:
5673 ms …
=> [build] Run class-parse and api-xml-adjuster in parallel

src/Xamarin.Android.Build.Tasks/Tasks/AndroidApkSigner.cs, src/Xamarin.Android.Build.Tasks/Tasks/AndroidSignPackage.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
In 160f1c6c, I overlooked the fact that `<ToolTask/>` doesn't
automatically skip running the tool if `GenerateCommandLineCommands()`
returns `string.Empty`.  This meant that `jarsigner.exe` and
`apksigner.jar` were still running when the keystore was not found,
resulting noisy additional build output lines and warnings.
To solve this, move the XA4310 `KeyStore` validation check to the
`ValidateParameters()` override that runs before
`GenerateCommandLineCommands()`.
Other changes:
Remove unused string interpolation in the test.
=> [Xamarin.Android.Build.Tasks] Avoid running tool after XA4310

.external, Documentation/release-notes/4351.md
Context: https://github.com/xamarin/monodroid/pull/1076
Removes the duplicate docs reference and doc generation
from the inverted build system.
=> [build] Remove doc generation duplication

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/AndroidResourceTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs
Fixes http://work.azdo.io/1042658
Commit a6387737 made the assumption that ALL `*Layout` view
extension values needed to be lowercased. This is not always
the case. In the Issue listed above the user defined custom
enumeration values which were CamelCase. These were not lowercased
by our build process. So when we lowercased the value in the
layout we got the following build error
Error		‘fixedsize’ is incompatible with attribute ChildLayout (attr) enum [Auto=0, FixedHeight=2, FixedSize=3, FixedWidth=1, MaxHeightAlignBottom=16, MaxHeightCenter=32, MaxWidthAlignRight=4, MaxWidthCenter=8]
To work around this issue this PR logs all of the `attr` values it
comes across during the conversion of the casing. If the value
for the view extension exists in that list it will not be lowercased. …
=> [Xamarin.Android.Build.Tasks] Dont always lowercase "*Layout" element values

src/Xamarin.Android.Sdk/targets/Xamarin.Android.Sdk.Common.targets
Visual Studio uses CPS to load SDK-style projects. In CPS, most things are keyed-off so-called capabilities[0] which replace other methods that were used previously like project type GUIDs.
While capabilities can be defined in the IDE, they make most sense to be directly expressed in the targets themselves where CPS will pick them up automatically.
[0]  https://github.com/microsoft/VSProjectSystem/blob/master/doc/overview/about_project_capabilities.md
=> [.NET 5] Start adding some project capabilities

src/Mono.Android/Mono.Android.targets
Context: https://github.com/xamarin/java.interop/issues/509
Beginning with C#8, interfaces may now contain constants.  This allows us to better match the `android.jar` we are binding. 
This PR:
- Enables the `generator` flag: `--lang-features=interface-constants`, which will generates constants on interfaces using C#8.
- This does not remove any previously created constants.  We will need to `[Obsolete]` them in a future PR.
API diff between `master` `API-30` and this PR: https://gist.github.com/jpobst/31c692a67a7f0389895b59cca92480ff
=> [Mono.Android] Enable constants on interfaces.

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/xamarin-android/pull/4360
I fear that #4360 is causing a real problem from the designer unit
tests. However, I need the `.binlog` files to understand what is
happening.
We currently do not have these as artifacts, so this will add them.
=> [build] include designer binlog files from tests

Configuration.props
This is the macOS system mono which corresponds with
commit mono/mono/2020-02@d90665a4.
=> [build] Use system mono 6.12.0.43

build-tools/automation/yaml-templates/upload-results.yaml
Today we cannot successfully rerun failed jobs on our CI because the new runs fail with "duplicate artifact name" when uploading the logs, even if everything else was successful.
This PR uses the AzDO variable `System.JobAttempt` to append a unique run number to the artifact name, allowing the upload to succeed.  Note that the run number is only added for retries, the original run does not change.
Example:
* First run: `Build Results - Windows`
* Second run: `Build Results - Windows (Attempt 2)`
* Third run: `Build Results - Windows (Attempt 3)`
=> [CI] Add job attempt to artifact name to prevent duplicates.

Documentation/release-notes/4385.md, src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/FilesTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/Files.cs
Context: https://github.com/xamarin/AndroidX/issues/73
Context: https://developer.android.com/studio/projects/android-library.html#aar-contents
Context: https://groups.google.com/forum/#!topic/lint-dev/BM8q5EQ3POE
With the latest AndroidX bindings, we were encountering a build error
from r8 such as:
You have Jar libraries, 
lint.jar, 
lint.jar, 
lint.jar, 
that have the identical name with inconsistent file contents. 
Please make sure to remove any conflicting libraries in EmbeddedJar, InputJar and AndroidJavaLibrary. 
The following `.aar` contains a  `lint.jar`:
https://maven.google.com/androidx/fragment/fragment/1.2.2/fragment-1.2.2.aar
Apparently there is a feature for implementing your own custom `lint`
rules. These are placed in `lint.jar` and Android Studio runs them as
needed. …
=> [Xamarin.Android.Build.Tasks] only extract specific .jar files from .aar

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/GetMonoPlatformJar.cs, src/Xamarin.Android.Build.Tasks/Tasks/PrepareWearApplicationFiles.cs
Move the message strings for XA0002 & XA5211 into the `.resx` file so
that they are localizable.
Other changes:
Update `<GetMonoPlatformJar/>` to call `LogCodedError()` with the XA0002
code number.  XA0002 was already listed in
`Documentation/guides/messages/README.md`, but it wasn't yet used in
`<GetMonoPlatformJar/>` itself.
=> [Xamarin.Android.Build.Tasks] XA0002 & XA5211 l10n support

Documentation/guides/BuildProcess.md, Documentation/guides/messages/README.md, Documentation/guides/messages/xa1010.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tasks/ManifestMerger.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
Add a warning code XA1010 to the existing warning about invalid values
of `$(AndroidManifestPlaceholders)`, and move the message string into
the `.resx` file so that it is localizable.
Other changes:
Correct the warning to say `AndroidManifestPlaceholders` instead of
`AndroidApplicationPlaceholders`.
Correct the warning to show the list of key-value pairs from the
property instead of `System.String[]`.
Add an entry for `$(AndroidManifestPlaceholders)` in `BuildProcess.md`.
=> [Xamarin.Andrdoid.Build.Tasks] Add XA1010 code for invalid placeholders

Makefile, build-tools/xaprepare/xaprepare/Steps/Step_GenerateFiles.Unix.cs
When the tree is configured with `make CONFIGURATION=Release`, every
subsequent `make` invocation will require `CONFIGURATION=Release` to be
present on the command line or otherwise the build tree will be messed
up and will require a re-run of `make prepare`.
Prevent the above from happening by storing the configuration in a
`bin/configuration.mk` file which is included by the `Makefile` as the
very first thing.
=> [build] Preserve CONFIGURATION for subsequent make invocations

src/Mono.Android/Android.Runtime/AndroidRuntime.cs, tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/ExceptionTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/4394
When using a preview drop of the .NET 5 BCL with a Xamarin.Forms app,
app startup crashes within
`AndroidTypeManager.RegisterNativeMembers()` becuase we attempt to use
`Delegate.CreateDelegate()` on a generic type definition, a
`typeof(VisualElementRenderer<>)`.
.NET Core and .NET Framework doesn't like this; mono does, which is
why it hasn't been a problem before.
We attempt to register the generic type definition for
`VisualElementRenderer<T>` because that's what the Java Callable
Wrapper does!  Given C#:
// C#
partial class FormsViewGroup : Android.Views.ViewGroup {
}
partial class VisualElementRenderer<T> : FormsViewGroup {
}
partial class PageRenderer : VisualElementRenderer<Page> {
}
the Java Callable Wrappers will …
=> [Mono.Android] Delegate.CreateDelegate & generic type definitions

build-tools/automation/azure-pipelines.yaml
The [2020-02 Mono bump](https://github.com/xamarin/xamarin-android/pull/4219) enabled `msbuild /m` for parallel builds in our CI for Windows.  However we have not audited our `Xamarin.Android.sln` to ensure build dependencies are correctly set.  Something(s) in there are not correct and this causes a race condition where builds sometimes fail because expected files do no exist yet.
Often this looks like this:
```
Error MSB3644: The reference assemblies for MonoAndroid,Version=v10.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
```
This disables parallel builds until a future audit is completed.
=> [ci] Don't build XA.sln in parallel on Windows, as it sometimes fails.

build-tools/automation/yaml-templates/upload-results.yaml
In https://github.com/xamarin/xamarin-android/pull/4373 we append the job run number to the log artifact's name to create a unique name so the upload succeeds.  However the script does not have `condition: always()` set so it isn't being run if a previous step failed.
=> [ci] Always set artifact run number, even if previous steps failed.

src/monodroid/jni/monodroid-glue.cc
Context: https://xamarinhq.slack.com/archives/CFB4MC864/p1584020384371400
Logging of which Java types we're registering native methods for was
removed in af02a65a.
Reintroduce a similar form of logging so that we can determine which
type is causing `Delegate.CreateDelegate()` to throw from
`AndroidTypeManager.RegisterNativeMembers()`.
The new log messages will only be printed when `timing` logging is
enabled:
$ adb shell setprop debug.mono.log timing
For example:
Registering native methods for managed type `Xamarin.Forms.Platform.Android.PlatformRenderer, Xamarin.Forms.Platform.Android, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null`
Finished registering native methods for managed type `Xamarin.Forms.Platform.Android.PlatformRenderer, Xamarin.Forms.Platform.Android, …
=> [Mono.Android] Add logging around RegisterNativeMembers()

Documentation/release-notes/4395.md, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/Tasks/ConvertResourcesCases.cs, src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs
I noticed that we were still using temporary files for
`AndroidResource.UpdateXmlResource`. I reworked this to use
`MemoryStreamPool.CreateStreamWriter` and generate the file in-memory.
We also had the code:
if (srcmodifiedDate <= lastUpdate) {
Log.LogDebugMessage ("  Skipping: {0}  {1} <= {2}", file, srcmodifiedDate, lastUpdate);
continue;
}
Log.LogDebugMessage ("  Processing: {0}   {1} > {2}", file, srcmodifiedDate, lastUpdate);
I removed the "Skipping" log message, because we have found that
MSBuild log messages can hurt performance. In this case, it could
potentially log a lot of files, and it will help incremental builds to
only log files that changed.
Building the Toggl app on Windows:
https://github.com/jonathanpeppers/mobileapp/tree/peppers-fixes
Originally from: …
=> [Xamarin.Android.Build.Tasks] don't use temp files in <ConvertResourcesCases/>

README.md
Add Commercial Xamarin.Android 10.3 Windows download location to the
README.
Update OSS master version number to 10.3.99.
=> [docs] Add Commercial Xamarin.Android 10.3 Windows download location

src/Xamarin.Android.Build.Tasks/Tasks/KeyTool.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidProject.cs, tests/CodeBehind/BuildTests/CodeBehindBuildTests.csproj
When running unit tests we occasionally see a random
`ANDKT0000` build error. We suspect this happens when
two tests try to create the same `debug.keystore` in
the same locaiton.
To work around this issue all projects should use override
the `_ApkDebugKeyStore` property to make sure the file
is created in the project directory. This should stop
parallel tests creating the same file at the same time.
=> [Xamarin.Android.Build.Tests] Move debug.keystore into Project Tree

src/monodroid/CMakeLists.txt, src/monodroid/monodroid.targets
This file was only used for dependencies and wasn't imported until
second build. The dependencies already contain the source files.
It was causing problems in parallel configure builds as the cmake
processes were writting to the file simultaneously.
=> [build] Do not generate and use sources.projitems

src/sqlite-xamarin/CMakeLists.txt, src/sqlite-xamarin/sqlite-xamarin.csproj, src/sqlite-xamarin/sqlite-xamarin.targets
Similar reasons as https://github.com/xamarin/xamarin-android/pull/4417
Also fix `OutputPath` and typo in dependencies to avoid unnecessary
rebuilds
=> [build] Do not generate and use source.proitems file

src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ResourceDesignerImportGenerator.cs
Fixes #4409
Our inital commit (d18c824c) to support Aliases did not take
into account the fact your can add more than one.
This commit handles the comma delimited `Aliases` metadata
so that the generated Resource.designer.cs file compiles.
=> [Xamarin.Android.Build.Tasks] Add Support fo Comma delimited Aliases

build-tools/api-merge/ApiDescription.cs, build-tools/api-merge/api-merge.cs, build-tools/api-merge/api-merge.csproj, build-tools/api-merge/merge-configuration.xml, src/Mono.Android/Mono.Android.targets
When we run `make jenkins`, we run `api-merge.exe` N times, where N is the number of Android Platform Levels (currently 12).  Each successive run has to merge all previous levels and then the new level.  
That is, our runs look like this:
- 10 + 15 + 16 + 17 +18 + 19 -> 19
- 10 + 15 + 16 + 17 +18 + 19 + 20 -> 20
- 10 + 15 + 16 + 17 +18 + 19 + 20 + 21 -> 21
- etc.
Instead, we can do a single pass where we do all the merging once, outputting the `api.xml` files in between the merges as needed.
- Merge 10 + 15 + 16 + 17 + 18 + 19
- Write 19
- Merge 20
- Write 20
- etc.
This shaves about 4 minutes off of `make jenkins`:
```
Before: 25:35
After: 21:44
```
Note:
This may not be the best place to insert this process. Should we instead do it somewhere earlier in the `make jenkins` chain, and then …
=> [api-merge] Generate all api's in single pass.

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs, tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
Context: https://github.com/xamarin/xamarin-android/pull/4381
In 18957918, we made the `debug.keystore` reside in each test app
instead of system-wide. This was to improve random parallel build
failures.
Unfortunately, this file is getting cleaned in various incremental
build tests.
One such is a performance test where this target runs:
_CreateAndroidDebugSigningKey (1.102s)
This appears to be happening on any incremental `SignAndroidPackage`
call in our tests.
I'm updating the file cleaning logic in Xamarin.ProjectTools to skip
over `debug.keystore` files.
After fixing this, I found we can lower the times by ~500ms for the
performance tests that install APKs. There is still a buffer:
=> Xamarin.Android.Build.Tests.PerformanceTest.Install_CSharp_Change
[TESTLOG] Test InstallCSharpChange …
=> [tests] fix deletion of debug.keystore

build-tools/api-merge/ApiDescription.cs, build-tools/api-merge/api-merge.cs
I was curious whether loading all the XML docs in parallel could
exercise a SSD a bit and gain some time.
MSBuild.exe /t:_GenerateApiDescription .\Mono.Android.csproj
Before: Time Elapsed 00:00:20.47
After:  Time Elapsed 00:00:17.67
Let see whether CI bots will like that.
CI mac:
Before:     45084 ms  _GenerateApiDescription                    1 calls
After:      40289 ms  _GenerateApiDescription                    1 calls
CI win:
Before:     32441 ms  _GenerateApiDescription                    1 calls
After:      26871 ms  _GenerateApiDescription                    1 calls
So even CI builds benefit from this change :-)
=> [api-merge] Preload XDocuments in parallel

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs, tests/MSBuildDeviceIntegration/Tests/AotProfileTests.cs
The app for the AotProfileTest was crashing on
startup with
Could not create log profiler server socket: Operation not permitted
This was because the `INTERNET` permission was not being
included in the manifst. This PR adds that permission.
Why this was working in the first place is a question that
is still unanswered.
=> [MSBuildDeviceIntegration] Fix AotProfileTest

build-tools/automation/yaml-templates/fail-on-issue.yaml, build-tools/automation/yaml-templates/run-nunit-tests.yaml
Because we use PowerShell to run our tests instead of the VSTask AzDO task each failed test suite generates 2 unhelpful error messages in the UI:
This PR changes the test suite failure message to be `Test suite had X failure(s)` and removes any message from the `fail if any issues occurred` step while still marking the build as Failed.
After:
=> [ci] Use a nicer error message when test failures occur.

src/Mono.Android/Mono.Android.csproj
I recently hit the following test failure
CheckTimestamps:
obj/Release/android/assets/it-IT/Mono.Android.resources.dll` is older than `20/03/2020 11:43:38`, with a timestamp of `20/03/2020 11:04:48`!
Which was completely weird. Partly because the project was not
building any localised assets. But mostly because it was
for `Mono.Android`.
It turns out the move to SDK style projects was accidently
including ALL the `.cs` files from the `Test` folder as
well as the normal code.
This exaplins why we are now generating this file and including
it in our build system.
So lets Remove all the `Test` files from the project.
=> [Mono.Android] Dont include Test code in Mono.Android.dll

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://build.azdo.io/3575078
Context: https://build.azdo.io/3574952
Our CI builds have been hitting random failures such as:
(_UpdateAndroidResgen target) ->
error XARDF7024: System.IO.IOException: The directory is not empty.
error XARDF7024:
error XARDF7024:    at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
error XARDF7024:    at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
error XARDF7024:    at Xamarin.Android.Tasks.RemoveDirFixed.RunTask()
Or in another target:
(_CreateBaseApk target) ->
error XARDF7024: System.IO.IOException: The directory is not empty.
error XARDF7024:
error XARDF7024:    at …
=> [Xamarin.Android.Build.Tasks] only warn about failed deletion of temp dirs

Documentation/release-notes/4414.md, build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.D8.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.DX.targets, tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs
Context: https://android-developers.googleblog.com/2020/02/the-path-to-dx-deprecation.html
As part of consolidation, cleanup, and the fact DX is about to be
unsupported:
* Move calls to DX and the `<CompileToDalvik/>` MSBuild task to a new
`Xamarin.Android.DX.targets` file.
* This includes usage of ProGuard.
* Remove support for using ProGuard in combination with d8. r8 should
just be used in this case.
Additionally, I cleaned up some logic in `Xamarin.Android.D8.targets`.
Resetting properties causes some unnecessary logging in MSBuild.
=> [Xamarin.Android.Build.Tasks] move DX into its own MSBuild targets file

.vscode/settings.json, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Compile.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tasks/AndroidComputeResPaths.cs, src/Xamarin.Android.Build.Tasks/Tasks/CollectNonEmptyDirectories.cs, src/Xamarin.Android.Build.Tasks/Tasks/ConvertCustomView.cs, src/Xamarin.Android.Build.Tasks/Tasks/CopyIfChanged.cs, src/Xamarin.Android.Build.Tasks/Tasks/PrepareWearApplicationFiles.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/Aapt2Tests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/CopyIfChangedTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/MockBuildEngine.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Utilities/Aapt2Daemon.cs, src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs, src/Xamarin.Android.Build.Tasks/Utilities/Files.cs, src/Xamarin.Android.Build.Tasks/Utilities/OutputLine.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/aapt2/aapt2.targets, tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs, tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
The `aapt2 compile` command runs in two modes. The one we
currently use is the `archive` mode. We calling `aapt2 compile`
with the `--dir` argument you end up generating one `flata`
archive for all the files. The side effect of this is that even
if you only change one file, it will need to regenerate the
entire `flata` archive.
But it has a second mode. Rather than using `--dir` you just send
in a single file. This then writes a single `.flat` file to the
output directory. While this does mean you have to call `aapt2 compile`
for EVERY file, it does mean we can leverage MSbuilds support for
partial targets. This means MSbuild will detect ONLY the files which
changed and allow us to call `aapt2 compile` with just THOSE files.
While this may impact on initial build times, the goal is to …
=> [Xamarin.Android.Build.Tasks] Run `aapt2 compile` incrementally.

build-tools/create-packs/Packager.csproj, src/Xamarin.Android.Sdk/Xamarin.Android.Sdk.Lite.proj
I found with ae136f0f, was that I was getting the following issue on
Windows:
"C:\src\xamarin-android\src\Xamarin.Android.Sdk\Xamarin.Android.Sdk.Lite.proj" (Pack target) (1) ->
Xamarin.Android.Sdk\Xamarin.Android.Sdk.Lite.proj(5,9): error MSB4184:
The expression "[System.IO.File]::ReadAllText(..\..\bin\Debug\Version)" cannot be evaluated. Could not find file 'C:\bin\Debug\Version'.
It seems the property:
<PackageVersion Condition="Exists('..\..\bin\$(Configuration)\Version')">$([System.IO.File]::ReadAllText('..\..\bin\$(Configuration)\Version'))</PackageVersion>
Somehow the evaluation of `Exists` and `ReadAllText` are doing
different things? Weird.
I refactored things to use `$(MSBuildThisFileDirectory)` and
intermediate properties for the file paths.
After that... I found that the value …
=> [Xamarin.Android.Sdk] fixes for $(PackageVersion)

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3576092&view=logs&jobId=8556562a-ae5f-5bd1-7c4d-bf1af4b6f1e1&j=58fa601a-973f-52de-d6ce-8b812c2da347&t=1e1c7f4c-cb47-45a2-8ea1-a12add99e69f
We've been seeing some test jobs failing due to an error when building
`Xamarin.Android.Tools.BootstrapTasks.csproj`. After reviewing the build
log, it seems that we may be missing a required submodule:
warning : The referenced project '../../external/xamarin-android-tools/src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj' does not exist.
Attempt to fix this build failure by always recursively checking out
xamarin-android for test jobs which require it.
Some `workspace: clean: all` additions have also been made for
consistency across jobs.
=> [CI] Ensure test sources are recursively cloned

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
Context: https://build.azdo.io/3576318
This partially reverts:
* 18957918
* b6eba4ea
Some tests that deploy to an emulator with fast deployment were
failing with:
[MESSAGE] jarsigner error: java.lang.RuntimeException:
keystore load: /Users/runner/.local/share/Xamarin/Mono for Android/debug.keystore (No such file or directory)
This is because `_CreateAndroidDebugSigningKey` created a
`debug.keystore` local to the project, and the system-wide one doesn't
exist. `androidtools` apparently will *only* use the system-wide key,
and fails if it does not exist.
18957918 was a little heavy-handed, it was aiming to just fix
`CodeBehindBuildTests.csproj`. I reverted the global change to set
`$(_ApkDebugKeyStore)` in all tests, to just set it in
`CodeBehindBuildTests.csproj`.
We also don't need the …
=> [tests] rework how debug.keystore is used in tests

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CheckApiCompatibility.cs
ApiCompat logic is not ready to handle netcoreapp3.1 folder structure.
We should disabl it for now and reenable once the logic is added.
=> Quick fix to disable apicompat check against netcoreapp target

build-tools/cmake/xa_macros.cmake, src/monodroid/CMakeLists.txt
We always build both release and debug binaries but the purpose of the
Debug build is not to be debuggable/unoptimized/etc in the native sense
but rather to contain code specific to and required by the managed Debug
builds.
So far, the Debug native builds have been built without any
optimizations thus making our Debug apps slower than they really need to
be. This commit changes the compiler optimization to `-O2` for the Debug
build, putting it on par with the Release builds, as far as optimization
is concerned.
This should make our Debug apps a bit faster.
The changes aren't dramatic, but there's a slight improvement:
= Before
Date (UTC): **3/25/2020 8:23:52 AM**
App configuration: **Debug**
Xamarin.Android
- Version: **10.3.99-129**
- Branch: **master**
- Commit: …
=> [build] Don't build "real" debug DSOs

build-tools/automation/yaml-templates/clean.yaml
Context: https://build.azdo.io/3582251
Some builds have been failing with:
git : fatal: not a git repository (or any of the parent directories): .git
I think we can set `$ErrorActionPreference` to ignore this failure. It
is probably happening for new build machines. The subsequent
`Checkout` step should create the git repository.
=> [build] fix failure with "manual clean" step

Documentation/release-notes/4360.md, build-tools/automation/azure-pipelines.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs, tests/MSBuildDeviceIntegration/Tests/DeleteBinObjTest.cs
I found a crash at runtime, if you:
1. Build / Run a project with 16.4
2. Build / Run the same project with 16.6
The stack trace is:
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "jm_typemap" referenced by "/data/app/com.companyname.app59-bgIEcmaPpoMxpR948Wo8ZA==/lib/x86/libmonodroid.so"...
at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
at java.lang.System.loadLibrary(System.java:1667)
at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:80)
at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:48)
at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
at …
=> [Xamarin.Android.Build.Tasks] clean $(IntermediateOutputPath) if build.props changes

tools/xabuild/XABuildPaths.cs
Context: https://github.com/xamarin/xamarin-android/pull/4467
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3590265&view=logs&j=96fd57f5-f69e-53c7-3d47-f67e6cf9b93e&t=7b19ceb3-907a-5a0d-b8ed-87e3f7335a58
When trying to integration test xamarin/Java.Interop#614, the
`make all-tests` job fails:
/usr/local/share/dotnet/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5):
error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.1.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.1.
[/Users/builder/azdo/_work/2/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop.csproj]
Particularly odd about this is that we have an explicit job to …
=> [xabuild] Probe DOTNET_ROOT for .NET sdks

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Context: https://build.azdo.io/3589171
Context: https://mvnrepository.com/artifact/com.soundcloud.android/android-crop/1.0.1
We've seen `AarContentExtraction` fail such as:
```
System.Net.WebException : Error: SecureChannelFailure (Remote prematurely closed connection.)
----> System.IO.IOException : Remote prematurely closed connection.
at System.Net.WebConnection.CreateStream (System.Net.WebOperation operation, System.Boolean reused, System.Threading.CancellationToken cancellationToken) [0x0021a] in <25c939f74d6540b5ab92a1c4b8117ce9>:0
at System.Net.WebConnection.InitConnection (System.Net.WebOperation operation, System.Threading.CancellationToken cancellationToken) [0x00141] in <25c939f74d6540b5ab92a1c4b8117ce9>:0
at System.Net.WebOperation.Run () [0x0009a] in …
```
=> [tests] update URL for AarContentExtraction

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidCommonProject.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3592451&view=ms.vss-test-web.build-test-results-tab
We've been having lots of `FSharp.Core`-related tests fail of late,
e.g. from `BuildTest.BuildBasicApplicationFSharp()`:
> Restoring packages for MonoAndroid,Version=v10.0... (TaskId:37)
>   …
>   GET https://api.nuget.org/v3-flatcontainer/fsharp.core/4.0.0.1/fsharp.core.4.0.0.1.nupkg (TaskId:37)
>   OK https://api.nuget.org/v3-flatcontainer/fsharp.core/4.0.0.1/fsharp.core.4.0.0.1.nupkg 64ms (TaskId:37)
> …
> FSC : error FS0229: Error opening binary file 'C:\A\vs2019xam000009-1\_work\1\s\packages\fsharp.core\4.0.0.1\lib\portable-net45+monoandroid10+monotouch10+xamarinios10\FSharp.Core.dll': Cannot read or write file
> FSC : error FS3160: Problem reading assembly …
=> Bump to FSharp.Core 4.7.1

.external
Changes: https://github.com/mono/mono/compare/a7e29665d246d359a778bf4d692b4cb5fd2f3548...beccf5ba4386148534467bff03fabe92da6d9705
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999375/
Context: https://github.com/mono/mono/issues/18715
Context: https://github.com/mono/mono/issues/18917
Context: https://github.com/mono/mono/issues/19005
* mono/mono@beccf5ba438: [2020-02] Use GArray instead of GList when getting custom attributes from an image (#19102)
* mono/mono@5bea89d861f: [llvm] Disable running the llvm verifier by default, it was enabled by mistake, and it takes a long time. (#19332)
* mono/mono@4b0424cd688: [2020- 02][debugger] Implementing step through multithreaded code. (#19343)
* mono/mono@2444b38b3c5: [2020-02] [dim] Class overriding interface method that was …
=> Bump to mono/mono/2020-02@beccf5ba

src/Mono.Android/metadata
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3594952&view=results
Cherry-picking PR #4468 to d16-6 resulted in a build break:
error : CompatApi command: /Users/builder/azdo/_work/92/s/xamarin-android/packages/microsoft.dotnet.apicompat/5.0.0-beta.20162.4/tools/net472/Microsoft.DotNet.ApiCompat.exe "/Users/builder/azdo/_work/92/s/xamarin-android/bin/Release/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v10.0/ApiCompatTemp" -i "/Users/builder/azdo/_work/92/s/xamarin-android/bin/Release/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v10.0.99/ApiCompatTemp" --allow-default-interface-methods --exclude-attributes ../../tests/api-compatibility/api-compat-exclude-attributes.txt
error : CheckApiCompatibility found nonacceptable Api breakages for ApiLevel: v10.0.99. …
=> [Mono.Android] Don't property-ify `Connection.setVideoState()`

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
Context: https://github.com/xamarin/xamarin-android/commit/295aff28371fc9f3cbe1e1f937eb7fa6634ad670
Do not store location of the bin directory and the netcore bin directory
in the same variable as the first property to be accessed will make "the
other" path to never be used which may lead to hard to detect issues.
=> [xaprepare] Use separate backing field for NetCoreBinDir

src/Xamarin.Android.Build.Tasks/Tasks/GetJavaPlatformJar.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ResolveSdksTaskTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
One of our QA tests was failing when using
`TargetFrameworkVersion=v10.0.99`:
C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25\bin\javac.exe -J-Dfile.encoding=UTF8 obj\Release\10099\android\src\mono\MonoRuntimeProvider.java:25: error: cannot find symbol (TaskId:163)
String[] splitApks = applicationInfo.splitPublicSourceDirs; (TaskId:163)
^ (TaskId:163)
symbol:   variable splitPublicSourceDirs (TaskId:163)
location: variable applicationInfo of type ApplicationInfo (TaskId:163)
Note: obj\Release\10099\android\src\crc64e49dab49335e9709\ButtonActivity.java uses unchecked or unsafe operations. (TaskId:163)
Note: Recompile with -Xlint:unchecked for details. (TaskId:163)
`splitPublicSourceDirs` is available starting with API 21, what is
going on?
Task "GetJavaPlatformJar" (TaskId:17) …
=> [Xamarin.Android.Build.Tasks] fix for API R and <GetJavaPlatformJar/>

Xamarin.Android-Tests.sln
The VSMac was complaining loading the XF test subproject:
Error while trying to load the project 'tests/Xamarin.Forms-Performance-Integration/Xamarin.Forms.Performance.Integration.csproj': Project Xamarin.Forms.Performance.Integration is being loaded as a Shared Assets project but has a different file extension. Please check the project type GUID in the solution file is correct.
The GUID used means: Visual C#: {FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}
https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/adding-items-to-the-add-new-item-dialog-boxes?view=vs-2019
=> [tests] Let Xamarin.Android-Tests.sln load in VSMac without errors

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs
Currently, the on-device MSBuild integration tests (and possibly others)
fail to properly record the full logcat buffer of the test run because
they run `adb logcat`, wait 5 seconds and kill the process. This results
in most log (if not all) files to be cut short (the sizes I saw were
between 20 and 80k) and thus not contain the useful information like the
process crash. The crash information is found towards the end of the
logcat, with the amount of text that is produced now that is at around
400k.
logcat supports the `-d` option which makes the command dump the buffer
to output and exit, thus removing the need to monitor and kill the
command after a timeout is reached.
This commit adds the `-d` argument and also reverts the 5s timeout to
the standard timeout for all adb commands in the …
=> [tests] Use `adb logcat -d` to dump logcat buffer

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Designer.targets, src/Xamarin.Android.Build.Tasks/Tasks/JavaCompileToolTask.cs, src/Xamarin.Android.Build.Tasks/Tasks/Javac.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.PCLSupport.targets
The `TargetFrameworkDirectory` property is no longer set by the .NET
Core build system.  Removing seemingly dead references to this property
will help simplify the places where we need to override this value in
.NET 5.
I could not find any references of `_XAInboxNETStandardFolders` in any
relevant [GitHub sources][0], so I've removed that ItemGroup declaration
entirely.
`Javac` (and its parents) also don't seem to make use of this property
as far as I can tell, so those references have been removed.
[0]: https://github.com/search?q=_XAInboxNETStandardFolders&type=Code
=> [Xamarin.Android.Build.Tasks] Remove TargetFrameworkDirectory usage

build-tools/xaprepare/xaprepare/xaprepare.csproj
The property:
```
<DocumentationFile>bin\Debug\xaprepare.xml</DocumentationFile>
```
causes several warnings to be generated like:
```
Application\KnownConditions.cs(3,14): warning CS1591: Missing XML comment for publicly visible type or member 'KnownConditions' [C:\A\vs2019xam000000-1\_work\1\s\build-tools\xaprepare\xaprepare\xaprepare.csproj]
Application\RefreshableComponent.cs(5,14): warning CS1591: Missing XML comment for publicly visible type or member 'RefreshableComponent' [C:\A\vs2019xam000000-1\_work\1\s\build-tools\xaprepare\xaprepare\xaprepare.csproj]
Application\RefreshableComponent.cs(7,3): warning CS1591: Missing XML comment for publicly visible type or member 'RefreshableComponent.None' [C:\A\vs2019xam000000-1\_work\1\s\build-tools\xaprepare\xaprepare\xaprepare.csproj] …
```
=> [xaprepare] Disable unused XML documentation

Documentation/guides/messages/README.md, Documentation/guides/messages/apt0001.md, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs
Move the message strings for APT0001 & XA0002 into the `.resx` file so
that they are localizable.
Other changes:
Adjust the wording of the message for APT0001 so that it covers not only
the scenario where an `aapt` option is used with `aapt2` but also the
scenario where one of the provided `aapt2` command line arguments
contains a typo.
=> [Xamarin.Android.Build.Tasks] APT0001 & XA2000 l10n support

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks.csproj, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CheckApiCompatibility.cs, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CodeGenDiff.cs, src/Mono.Android/Mono.Android.targets, src/Mono.Android/metadata, tests/api-compatibility/api-compatibility.targets
Fixing the issue were ApiCompat is not reporting errors on master. That issue caused that some breakages got passed on master. see https://github.com/xamarin/xamarin-android/pull/4485
Enabling netcoreapp3.1 assemblies to also be part of apicompat checks. it will check only against reference.
Updating the arcade package reference to use version 20181.7
The new version allows to provide a baseline file with validations to make sure baseline content has no unused/garbage on it.
The new ApiCompat capability allows us to do a major cleanup on CheckApiCompatibility task.
Also the new version allows to specify assemblies instead of folders, so now we don't need to move files around anymore to run it. Another good cleanup
Removing the previous way of diff'ing assemblies with GenApi using gitdiff, …
=> ApiCompat enhancements

Documentation/building/windows/instructions.md, build-tools/automation/azure-pipelines.yaml, build-tools/scripts/PrepareWindows.targets
On macOS,  you can generally build with just:
make prepare all
On Windows:
msbuild Xamarin.Android.sln /t:Prepare
msbuild Xamarin.Android.sln
In 295aff28, we introduced some changes that now require a change to
the second step:
msbuild Xamarin.Android.sln /restore
I think we can add a call at the end of `/t:Prepare`:
<MSBuild Projects="$(_TopDir)\Xamarin.Android.sln" Targets="Restore" />
This way you don't have to remember the `/restore` switch.
Lastly, I updated the Windows `Build and Smoke Test` phase on Azure
DevOps, so it will build on Windows without `/restore`.
=> [build] /restore no longer needed on Windows

Documentation/guides/DotNet5.md, build-tools/automation/azure-pipelines.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetStandard.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Tooling.targets, src/Xamarin.Android.Sdk/targets/Xamarin.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Sdk/targets/Xamarin.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Sdk/targets/Xamarin.Android.Sdk.DefaultItems.props, src/Xamarin.Android.Sdk/targets/Xamarin.Android.Sdk.Lite.props, src/Xamarin.Android.Sdk/targets/Xamarin.Android.Sdk.props, src/Xamarin.Android.Sdk/targets/Xamarin.Android.Sdk.targets
There are currently two "verbs" we are aiming to get working in
Xamarin.Android:
dotnet build
dotnet publish
Currently in .NET Core (aka .NET 5), `dotnet publish` is where all the
work to produce a self-contained "app" happens:
* The linker via the `<IlLink/>` MSBuild task
* .NET Core's version of AOT, named "ReadyToRun"
https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#readytorun-images
This means Xamarin.Android would run the following during `dotnet
build`:
* Run `aapt` to generate `Resource.designer.cs` and potentially emit
build errors for issues in `@(AndroidResource)` files.
* Compile C# code
Almost everything else happens during `donet publish`:
* Generate java stubs, `AndroidManifest.xml`, etc. This must happen
after the linker.
* Compile java code via …
=> [.NET 5] initial implementation of "dotnet publish"

src/Mono.Android/Mono.Android.csproj
Since e2854ee7, `Mono.Android.csproj` has multi-targeting:
<TargetFrameworks>monoandroid10;netcoreapp3.1</TargetFrameworks>
I've been getting a weird issue with the unit test runner in VS
Windows.
If I run, `Xamarin.Android.Build.Tests.BuildTest.BuildBasicApplication`,
I get a popup that the build failed. It prompts to continue yes/no, and
the test continues to run regardless of the answer!
If I enable the build logging in the IDE using:
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools
I see a build of `Xamarin.Android.Build.Tasks.csproj` fails with:
Mono.Android.csproj error MSB4057: The target "GetTargetPath" does not exist in the project.
Yet the next build for `Xamarin.Android.Build.Tests.csproj` succeeds.
Everything works fine …
=> [Mono.Android] workaround for VS Windows test runner

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunParallelCmds.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3598843&view=logs&j=cac0e8d3-0ef5-5d2b-b57e-e8fde7204df3&s=14c5bb15-e916-5bc3-7b8f-0ac5dbe45c97&t=d0eaacf3-179f-5217-7519-cd03bc45e5e4&l=10948
We had a build fail that said:
Process 'msbuild.exe' exited with code '1'.
And yet:
0 Error(s)
The only to figure out the true error is to do something like:
$ msbuild foo.binlog /v:diag | grep FAILED
This shows that `<RunParallelCmds/>` failed, but didn't log any
errors. This means `Execute()` returned `false`.
It looks like the real error is:
Non-zero exit code: 1  Error output: ...
I changed it to call `LogError` instead of `LogMessage`, so it will be
easier to track down failures.
=> [build] <RunParallelCmds/> should call LogError

.external
Changes: https://github.com/mono/mono/compare/fda73998f929f9af2020e8e125afd15c7d504c0c...ecde08600b274d782bdd89f3ef7dd41849e40ddf
Context: https://github.com/mono/mono/issues/18127
Context: https://github.com/mono/mono/issues/19377
Context: https://github.com/xamarin/xamarin-android/pull/4487
* mono/mono@ecde08600b2: [runtime] Allocate the memory for gshared gparams from image sets. (#19361) (#19419)
* mono/mono@8fb93012925: [meta] Add mono_type_get_name_full to public API (#19415)
* mono/mono@7bfb441fb4c: Fix Windows .msi build using newer xar
* mono/mono@e77cea19105: Fix Windows .msi build with recent cygwin updates
=> Bump to mono/mono/2020-02@ecde0860

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3609773&view=logs&j=96fd57f5-f69e-53c7-3d47-f67e6cf9b93e&t=65256bb7-a34c-5353-bc4d-c02ee25dc133
Some builds have been failing with the following error:
BuildJniEnvironment_g_cs:
dotnet "/Users/builder/azdo/_work/211/s/xamarin-android/external/Java.Interop/bin/BuildRelease-netcoreapp3.1/jnienv-gen.dll" Java.Interop/JniEnvironment.g.cs obj/Release/netcoreapp3.1//jni.c
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.2' was not found.
- The following frameworks were found:
2.1.12 at [/Users/builder/azdo/_work/_tool/dotnet/shared/Microsoft.NETCore.App]
3.1.0 at [/Users/builder/azdo/_work/_tool/dotnet/shared/Microsoft.NETCore.App]
5.0.0-preview.1.20120.5 at …
=> [ci] Prefer a stable .NET Core version

Documentation/release-notes/4487.md, src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Test/Java.Interop/JnienvTest.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tasks/PrepareAbiItems.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ARMNativeAssemblerTargetProvider.cs, src/Xamarin.Android.Build.Tasks/Utilities/NativeAssemblerTargetProvider.cs, src/Xamarin.Android.Build.Tasks/Utilities/NativeTypeMappingData.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingDebugNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingReleaseNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/X86NativeAssemblerTargetProvider.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/monodroid/CMakeLists.txt, src/monodroid/jni/application_dso_stub.cc, src/monodroid/jni/embedded-assemblies.cc, src/monodroid/jni/embedded-assemblies.hh, src/monodroid/jni/external-api.cc, src/monodroid/jni/monodroid-glue-internal.hh, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/xamarin-app.hh, tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs, tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
Fixes: https://github.com/xamarin/xamarin-android/issues/4415
Context: https://github.com/xamarin/xamarin-android/commit/ce2bc689a19cb45f7d7bfdd371c16c54b018a020
This commit partially reverts ce2bc689a19cb45f7d7bfdd371c16c54b018a020
in the sense that it restores the use of type names for Java-to-Managed
and Managed-to-Java type lookups for **Debug** builds only.
The reason for the change is that in order for the MVID and type token
based lookups to work we need two things:
- for the MVID to remain unchanged in each mapped assembly
- for the type token to remain unchanged in each mapped assembly
However, in incremental builds neither of the above requirements is
met **unless** the application is fully rebuilt and, thus, the typemaps
are regenerated from scratch, which obviously doesn't sit …
=> Return of the Strings

src/Xamarin.Android.Build.Tasks/Tasks/AndroidApkSigner.cs
Thanks to b28a93ad223f3610067aef63c427afb17a23e7d7, the error check in
`AndroidApkSigner.RunTask()` is no longer needed.  Before that commit,
`RunTask()` was validating the path of `apksigner` or `apksigner.bat`.
But now that `AndroidApkSigner` inherits from `JavaToolTask`, the check
is just revalidating the path of `java`.
One option would be to update the check to validate the path of
`apksigner.jar` instead, but that isn't needed because
`<ResolveAndroidTooling/>` already validates that path.  So the check
can just be removed.
=> [Xamarin.Android.Build.Tasks] Remove unused error from AndroidApkSigner

Documentation/workflow/Localization.md, src/Xamarin.Android.Build.Tasks/Tasks/AndroidError.cs, src/Xamarin.Android.Build.Tasks/Tasks/AndroidWarning.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
The built-in `<Error/>` and `<Warning/>` tasks from MSBuild do not
provide a way to look up string resources, so they don't allow logging
localizable warnings and errors from MSBuild targets.
Add custom `<AndroidError/>` and `<AndroidWarning/>` tasks to handle
this scenario.
This approach is inspired by the [`<NETSdkError/>`][0] and
[`<NETSdkWarning/>`][1] tasks in dotnet/sdk.
[0]: https://github.com/dotnet/sdk/blob/56a9d827c8408f98ab27caceae2c8e1936281401/src/Tasks/Common/NETSdkError.cs
[1]: https://github.com/dotnet/sdk/blob/56a9d827c8408f98ab27caceae2c8e1936281401/src/Tasks/Common/NETSdkWarning.cs
=> [Xamarin.Android.Build.Tasks] Add localizable message tasks

Documentation/release-notes/4505.md, src/Xamarin.Android.Build.Tasks/Tasks/CompileToDalvik.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.D8.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.DX.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/4478
Fixes: https://github.com/xamarin/xamarin-android/issues/4486
We with the release of VS for Mac 8.5 going stable have been getting
some reports of:
error ADB0010:  Deployment failed
Mono.AndroidTools.InstallFailedException: Failure [INSTALL_FAILED_INVALID_APK: Package couldn't be installed in /data/app/com.contoso.androidapp1-RTZZFPyLkRI7Bk7VDgGkDg==: Package /data/app/com.contoso.androidapp1-RTZZFPyLkRI7Bk7VDgGkDg==/base.apk code is missing]
at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess (System.String output, System.String packageName) [0x00159] in <65710797f19f43cc9d8f9e05353b9615>:0
at Mono.AndroidTools.AndroidDevice+<>c__DisplayClass95_0.<InstallPackage>b__0 (System.Threading.Tasks.Task`1[TResult] t) …
=> [Xamarin.Android.Build.Tasks] trailing / causes missing classes.dex

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
Context: https://build.azdo.io/3615798
Context: https://build.azdo.io/3615816
This test commonly fails with:
NuGet.targets(124,5): error : Could not find file '/Users/runner/runners/2.165.2/work/1/s/packages/xamarin.forms/2.3.4.231/ltlis65w.fez'.
0 Warning(s)
1 Error(s)
Looking at the other tests that use
`KnownPackages.XamarinForms_2_3_4_231`, they already have
`[NonParallelizable]`.
I think we should do the same for this test.
=> [tests] CheckAapt2WarningsDoNotGenerateErrors non-parallelizable

Documentation/guides/BuildProcess.md, Documentation/release-notes/4509.md, src/Xamarin.Android.Build.Tasks/Tasks/R8.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.D8.targets
Context: https://www.guardsquare.com/products/proguard/manual/usage
Fixes: https://feedback.devdiv.io/959121
Fixes: https://feedback.devdiv.io/960245
Fixes: https://github.com/xamarin/xamarin-android/issues/4457
A common problem Xamarin.Android developers are running into is `r8`
failing with:
Warning: Missing class: org.apache.http.client.methods.HttpEntityEnclosingRequestBase
Error: Compilation can't be completed because some library classes are missing.
The simplest way to hit this is:
* Use Google Play Services
* Use multi-dex
In this case, we are only using `r8` for multi-dex support and *not*
code shrinking. Developers aren't setting proguard rules at all in
this scenario.
The correct fix is to do this in `AndroidManifest.xml`:
<uses-library android:name="org.apache.http.legacy" …
=> [Xamarin.Android.Build.Tasks] -ignorewarnings option to make r8 less strict

tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
Context: https://build.azdo.io/3616517
Context: https://github.com/xamarin/xamarin-android/pull/4487
7117414c raised the acceptable build times for three tests:
* `Build_From_Clean_DontIncludeRestore`
* `Build_AndroidManifest_Change`
* `Build_JLO_Change`
Unfortunately, we didn't increase the times enough. I raised them a
bit more, so they should pass more reliably.
In a future PR, we could consider using the ABI of the connected
emulator/device to only build & generate an APK for that specific
device. I could see this improving the regressed timings here, as the
`_GenerateJavaStubs` and native assembly compilation are taking
additional time per-ABI.
=> [tests] raise acceptable timings for performance tests

src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
Backport of: https://github.com/xamarin/xamarin-android/pull/4532
This backport excludes the changes related to XA0031 because those are
for 231bf2a4381af4996c795e27fa65b15d63e3fc0b, which is only present on
master.
=> LOC CHECKIN | xamarin/xamarin-android d16-6 | 20200406

build-tools/Xamarin.Android.App/Xamarin.Android.App.Ref.proj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Tooling.targets, src/Xamarin.Android.Sdk/Xamarin.Android.Sdk.proj, src/Xamarin.Android.Sdk/targets/Xamarin.Android.Sdk.Lite.props, src/Xamarin.Android.Sdk/targets/Xamarin.Android.Sdk.props
In .NET 5, all framework assemblies will be resolved from various
targeting and runtime packs.  Now that commit a5369517 has landed, we
should no longer be bundling these in the SDK.
All `MonoAndroid/v*` content has been removed. Additionally, the
host-specific BCL and runtime bits that were included have been
removed. `jnimarshamethod-gen` has been removed for now, as
it relies on this host BCL.
Updates the `Xamarin.Android.App.Ref` targeting pack to include both
`mono.android.jar` and `mono.android.dex`.  The `GetMonoPlatformJar`
task has been updated to resolve these items from the targeting pack
when using the .NET 5 Android SDK.
`Xamarin.Android.Tooling.targets` has been updated to conditionally
reference `$(_JavaInteropReferences)`, as these will be implicitly
referenced through …
=> [.NET 5] Remove framework assemblies from Xamarin.Android.Sdk

src/Xamarin.Android.Sdk/Xamarin.Android.Sdk.proj
Commit ebd8586b contained a bad rebase, and as a result there were a
couple of SDK content changes that did not make it as described in
those changes. This PR fixes the lines which were previously missed when
rebasing https://github.com/xamarin/xamarin-android/pull/4501.
=> [.NET 5] Fix Xamarin.Android.Sdk content

src/Mono.Android/Test/Java.Interop/JnienvTest.cs, src/monodroid/jni/embedded-assemblies.cc
Context: 7117414ca27d88a71b4a272705a0207f772423bd
7117414ca27d88a71b4a272705a0207f772423bd introduced native code which queries
the Mono runtime to obtain an instance of `MonoClass` for a given
`MonoReflectionType` as well as the `MonoImage` associated with the
class.  However, it appears that in certain cases the class pointer
stored `MonoReflectionType` doesn't lead us to getting a valid
`MonoImage` instance, causing a segfault similar to:
04-08 15:52:55.015 19030 19030 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3000021 in tid 19030 (s.swipeviewdemo), pid 19030 (s.swipeviewdemo)
04-08 15:52:55.037 19061 19061 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
04-08 15:52:55.037  1834  1834 I /system/bin/tombstoned: received …
=> [runtime] Fix segfault when accessing MonoImage in certain cases

Documentation/guides/messages/README.md, Documentation/guides/messages/xa1011.md, Documentation/release-notes/4414.md, Documentation/release-notes/xa1011.md, Documentation/workflow/Localization.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: 5563a79cbb6931818b06ddfb0c83d6957e3df480
Somewhat related: https://github.com/xamarin/xamarin-android/pull/4509#issuecomment-608640547
Rather than automatically changing `$(AndroidLinkTool)` from `proguard`
to `r8` when `$(AndroidDexTool)`=`d8`, provide an error that instructs
project authors to update the property themselves.
The motivation for this approach is that we have seen some cases where
changing from ProGuard to R8 can change behavior.  Forcing project
authors to change `$(AndroidLinkTool)` themselves will help let them
know that they should pay attention for any potential changes to Java
code shrinking behavior after the change.
=> [Xamarin.Android.Build.Tasks] Add XA1011 error for D8 with ProGuard

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/4439
If you build a project with `AndroidDexTool=invalid`, you end up with
an APK file that is missing a `classes.dex`. We don't emit an error,
and you won't actually know anything is wrong until going to install
the APK.
If someone did this on accident, I think we can just default
`AndroidDexTool=d8` *unless* it is set to `dx`.
I updated a test for this.
=> [Xamarin.Android.Build.Tasks] fixup invalid $(AndroidDexTool)

tools/apkdiff/ApkDescription.cs, tools/apkdiff/AssemblyDiff.cs, tools/apkdiff/EntryDiff.cs, tools/apkdiff/ISizeProvider.cs, tools/apkdiff/Program.cs, tools/apkdiff/SharedLibraryDiff.cs, tools/apkdiff/apkdiff.csproj
Besides the other changes we want the regression testing.
Example output:
apkdiff.exe --test-apk-size-regression=51200 --test-assembly-size-regression=51200 Xamarin.Forms_Performance_Integration-Signed-Release.apkdesc bin\TestDebug\Xamarin.Forms_Performance_Integration-Signed.apk
+  26,749,952 assemblies/Mono.Android.dll
Error: apkdiff: Assembly 'assemblies/Mono.Android.dll' size increase 26,749,952 is 26,698,752 bytes more than the threshold 51,200.
+  14,655,424 assemblies/Mono.Android.pdb *2
+   2,423,388 lib/x86/libmonosgen-2.0.so
+   2,413,568 assemblies/mscorlib.dll
Error: apkdiff: Assembly 'assemblies/mscorlib.dll' size increase 2,413,568 is 2,362,368 bytes more than the threshold 51,200.
+   2,025,076 classes.dex
+ …
=> Merge apkdiff from upstream

Documentation/release-notes/r8-multidex-config.md, src/Xamarin.Android.Build.Tasks/Tasks/R8.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/xamarin-android/issues/4369#issuecomment-610553571
Context: https://developercommunity.visualstudio.com/content/problem/979562/r8-warning-missing-class-javalangclassvalue.html
Context: https://github.com/xamarin/AndroidX/issues/74
Currently, Xamarin.Android always uses `com.android.tools.r8.R8` to
generate DEX files if `$(AndroidDexTool)`=`d8` and
`$(AndroidEnableMultiDex)`=`True`, even if `$(AndroidLinkTool)`=``.
This causes some tricky behavior because, unlike DX and
`com.android.tools.r8.D8`, R8 always performs dependency checks,
including [warning about missing Java classes][0].  As a consequence,
switching from `$(AndroidDexTool)`=`dx` to `$(AndroidDexTool)`=`d8`
while `$(AndroidEnableMultiDex)`=`True` can introduce new build
warnings, somewhat …
=> [Xamarin.Android.Build.Tasks] Use @(ProguardConfiguration) for R8 multidex

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/ParseAndroidWearProjectAndManifest.cs, src/Xamarin.Android.Build.Tasks/Tasks/PrepareWearApplicationFiles.cs
Add codes to the existing warnings and errors in the Wear application
tasks, and move the message strings into the `.resx` file so that they
are localizable.
Other changes:
Remove "you" from one of the messages.
=> [Xamarin.Android.Build.Tasks] Wear application tasks l10n support

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
Context: 0103d4fc07f1764eba11a9d0cbc2daed2c5368bd
Add codes to the remaining errors in `<ResolveAssemblies/>` that did not
yet have codes, and move the message strings into the `.resx` file so
that they are localizable.
=> [Xamarin.Android.Build.Tasks] ResolveAssemblies l10n support part 2

build-tools/installers/create-installers.targets
Using `AndroidUseSharedRuntime=True` doesn't work in .NET 5 yet, and
it is still up in the air if we will support it.
For now, we can remove these from `Xamarin.Android.Sdk.nupkg` to save
on file size. This save ~164MB of file size on disk when the NuGet
package is extracted.
=> [.NET 5] exclude shared runtime APKs from Xamarin.Android.Sdk

src/Mono.Android/Mono.Android.csproj
I noticed that `GenerateJavaCallableWrappers` was building completely on
every incremental build for me locally:
Target "GenerateJavaCallableWrappers: (TargetId:1260)" in file "C:\Source\xamarin-android\build-tools\scripts\JavaCallableWrappers.targets" from project "C:\Source\xamarin-android\src\Mono.Android\Mono.Android.csproj" (target "Build" depends on it):
Building target "GenerateJavaCallableWrappers" completely.
Input file "C:\Source\xamarin-android\Mono.Android.dll" does not exist.
The issue was that the refactoring to short-form project style in commit
a6e5d10a by chance moved the assignment of
`$(JavaCallableWrapperAbsAssembly)` to happen before the assignment of
`$(OutputPath)`, meaning that `$(JavaCallableWrapperAbsAssembly)` no
longer contained the correct path to the …
=> [build] [Mono.Android] Assign $(JavaCallableWrapperAbsAssembly) after $(OutputPath)

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/CheckDuplicateJavaLibraries.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/CheckDuplicateJavaLibrariesTests.cs
Add a code to the existing error in `<CheckDuplicateJavaLibraries/>`,
and move the message string into the `.resx` file so that it is
localizable.
Other changes:
Remove "you" from the message.
=> [Xamarin.Android.Build.Tasks] CheckDuplicateJavaLibraries l10n support

README.md
When the xamarin-macios team recently added a downloads section to their
README, they noticed that users were by default picking the first link,
so they decided to switch the order to sort from newest to oldest.
Update the commercial download locations in the xamarin-android README
to use newest-to-oldest order like the xamarin-macios README.
Leave the OSS master download as the last entry because that link is
expected to be used less frequently than the links for the commercial
versions.
=> [docs] Put newest download locations first in README

Documentation/release-notes/4509.md
Restructure the R8 `-ignorewarnings` release note to provide details
about two examples of common warnings and errors that users have seen
when using R8 for multidex.
Remove the description about "just warnings" when using `dx` because in
my local testing, using DX for multidex did not produce any related
warnings, at least not for these two common known scenarios.
=> [docs] Update release note for R8 -ignorewarnings

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/GetJavaPlatformJar.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Add XA1018 and XA4228 codes for existing build messages, and move the
message strings into the `.resx` file so that they are localizable.
Other changes:
Use the XPath selector `//activity-alias/@android:targetActivity` in the
message for XA4228 to minimize ambiguity and make the message easier to
translate.
=> [Xamarin.Android.Build.Tasks] Add XA1018 & XA4228 for l10n

.external
Changes: https://github.com/xamarin/monodroid/compare/846697287fb32c38b54ddd2fe21964b9159b2750...16cb1cb1ac7c472207023953b7bb3970f7c9aa54
* xamarin/monodroid@16cb1cb1a: Bump to xamarin/androidtools/master@068e4f5 (#1084)
* xamarin/monodroid@8f61f0cae: Bump to xamarin/android-sdk-installer/master@d9276b4 (#1085)
* xamarin/monodroid@bec720cd0: Bump to xamarin/jar2xml/master@4125da65 (#1083)
* xamarin/monodroid@a49e901d6: [tools/msbuild] update <BuildApk/> task inputs (#1082)
* xamarin/monodroid@b9f16c002: Bump to xamarin/androidtools/master@5412dc8 (#1081)
* xamarin/monodroid@673a74961: [.NET 5] fix for ALC isolation between assemblies (#1080)
=> Bump to xamarin/monodroid/master@16cb1cb1

src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
Context: 231bf2a4381af4996c795e27fa65b15d63e3fc0b
The generated comment in the `Resources.Designer.cs` file was not yet
updated to account for the changes from commit 231bf2a4, and the comment
in the `.resx` file was using a `&quot;` character entity reference that
Visual Studio was replacing with `"` any time it saved the file.
Add those automatic changes now so there won't be any need to worry
about them getting included unintentionally as part of some unrelated
future change to the `.resx` file.
=> [Xamarin.Android.Build.Tasks] Tidy generated l10n resource files

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/CreateLibraryResourceArchive.cs, src/Xamarin.Android.Build.Tasks/Tasks/Lint.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
Add XA0123 and XA1019 codes for existing build messages, and move the
message strings into the `.resx` file so that they are localizable.
Other changes:
Change the wording of the message for XA1019 to make it more
descriptive.  The new wording makes it easier to see that the message is
only relevant for an older style of Android library projects created via
`android create lib-project`.
=> [Xamarin.Android.Build.Tasks] Add XA0123 & XA1019 for l10n

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/MacOS.cs
New MinGW version is out (7.0.0_2) and it appears that some bots are sad
they don't have it:
Full Homebrew executable path value: /usr/local/bin/brew
Running: /usr/local/bin/brew "tap" "xamarin/xamarin-android-windeps"
Running: /usr/local/bin/brew "install" "xamarin/xamarin-android-windeps/mingw-zlib"
stderr | Error: You must `brew unpin mingw-w64` as installing xamarin/xamarin-android-windeps/mingw-zlib requires the latest version of pinned dependencies
| ==> Installing mingw-zlib from xamarin/xamarin-android-windeps
Error: Installation of xamarin/xamarin-android-windeps/mingw-zlib failed
Please them by updating to the latest version.
=> [macos] Bump MinGW version

src/Xamarin.Android.Build.Tasks/Tasks/RuntimeIdentifierToAbi.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Sdk/targets/Xamarin.Android.Sdk.Tooling.targets
Context: https://docs.microsoft.com/dotnet/core/rid-catalog
.NET Core has a concept of `$(RuntimeIdentifier)` (or RID), which
means you would `publish` an `arm64-v8a` build for Android via:
dotnet publish foo.csproj --runtime-identifier android-arm64 --self-contained
To make this work with our existing MSBuild targets we will need to
map RIDs to `$(AndroidSupportedAbis)`. I made a helper method that
looks for the second `-arm64` portion of the RID.
There is still work ongoing to support multiple RIDs in a single build
in .NET 5. We will need to rework things when this is available.
I updated the .NET 5 MSBuild tests to validate multiple RIDs.
=> [.NET 5] map $(RuntimeIdentifier) to $(AndroidSupportedAbis)

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs, src/Xamarin.Android.Sdk/targets/Xamarin.Android.Sdk.props
Currently with a .NET 5 build you have to do:
dotnet publish foo.csproj --self-contained
Or:
dotnet publish foo.csproj -p:SelfContained=true
On Android platforms, it doesn't make sense to have a
non-self-contained app. That would mean there is a system-wide .NET 5
installation, which is not going to happen on Android.
In .NET 5 running on Windows/MacOS, this means the application relies
on the BCL living in a system-wide directory somewhere.
To simplify the command-line arguments we should default
`$(SelfContained)` to `true` when it is an Android application.
=> [.NET 5] default to --self-contained=true

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/ApkDiffCheckRegression.cs, build-tools/scripts/TestApks.targets, tools/apkdiff/ApkDescription.cs, tools/apkdiff/AssemblyDiff.cs, tools/apkdiff/DexDiff.cs, tools/apkdiff/EntryDiff.cs, tools/apkdiff/Program.cs, tools/apkdiff/README.md
Add the configuration and the flavor to the filename, save them to `$(OutputPath)` .
This way we can just copy the files when we need update reference apkdesc's.
Also merge apkdiff changes from upstream
* radekdoulik/apkdiff@cb0083b: Fix indentation, put the XA link  on separate line
* radekdoulik/apkdiff@092e40a: Added links to the upstream repo and XA location
* radekdoulik/apkdiff@cdb7593: Added DEX comparison example
* radekdoulik/apkdiff@17f242b: Update usage info in README.md
* radekdoulik/apkdiff@1dbdb00: Added options to specify path of saved description
* radekdoulik/apkdiff@e6390f6: Initial DEX comparison
* radekdoulik/apkdiff@7c8d5d8: Dispose PEReaders
Mostly to have the options to save descriptions to specified path. Also
contains the DEX files comparison.
=> Save apkdesc files to output path

build-tools/automation/azure-pipelines.yaml, build-tools/plots-to-appinsights/Program.cs
Removed the following plots as it appears the CSV file is no longer produced for these
- Runtime test sizes
- Xamarin.Forms app
Fixed a bug where the error for a missing CSV file isn't being sent to AppInsights by adding a call to Flush().
=> Add Locale to AppInsights plot tracking

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Some of our tests are failing on CI with:
dotnet\sdk\5.0.100-preview.2.20176.6\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(329,5):
error NETSDK1082: There was no runtime pack for Microsoft.NETCore.App available for the specified RuntimeIdentifier 'android.21-x86'.
These tests work fine if you install a master build of .NET 5. We will
need a build of .NET 5 Preview 4 for these tests to work.
Let's ignore them for now, so our CI will be more greenish.
=> [tests] ignore .NET 5 tests for x86/x64

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Tooling.targets, src/Xamarin.Android.Build.Tasks/Tasks/CheckGoogleSdkRequirements.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
In our current .NET 5 builds, you always hit:
warning XA1008: The TargetFrameworkVersion (Android API level 21) is lower than the targetSdkVersion (29).
Please increase the `$(TargetFrameworkVersion)` or decrease the `android:targetSdkVersion` in the `AndroidManifest.xml` so that the API levels match.
It is giving a warning for Google Play, because
`$(TargetFrameworkVersion)` is equal to 5.0.
To fix this, I modified the `<CheckGoogleSdkRequirements/>` MSBuild
task so that `TargetFrameworkVersion` is optional. For .NET 5 builds,
we can pass in `$(_AndroidApiLevel)` instead.
This way we will still get some important warnings for .NET 5 such as
`targetSdkVersion` or `minSdkVersion` that need to be changed in the
`AndroidManifest.xml` file.
I also fixed up `LastBuildOutput`, we needed the …
=> [.NET 5] fix warning for $(TFV) of 5.0

Documentation/guides/messages/README.md, Documentation/guides/messages/xa4231.md, Documentation/guides/messages/xa4232.md, Documentation/release-notes/4577.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets
Both `<AndroidClassParser>jar2xml</AndroidClassParser>` and `<AndroidCodegenTarget>XamarinAndroid</AndroidCodegenTarget>` were replaced 5+ years ago by `class-parse` and `XAJavaInterop1` respectively.
We already are not adding new features to them, like DIM, NRT, and Kotlin improvements, so projects using them are not benefiting from our improvements.
We would also like to some day stop maintaining these configurations.  As such, add warnings to Bindings project builds if these configurations are still used:
```
XA4231: The Android class parser value 'jar2xml' is deprecated and will be removed in 
a future version of Xamarin.Android. Update the project properties to use 'class-parse'.
```
```
XA4232: The Android code generation target 'XamarinAndroid' is deprecated and will 
be removed in …
```
=> [Bindings.targets] Warn about deprecated jar2xml and XamarinAndroid values.

build-tools/xaprepare/xaprepare/Application/EssentialTools.MacOS.cs, build-tools/xaprepare/xaprepare/Application/EssentialTools.cs, build-tools/xaprepare/xaprepare/ToolRunners/PkgutilRunner.MacOS.cs
`xaprepare` defines a set of binaries/programs which are deemed
essential and, thus, it enforces their presence before the scenario
runs.  However, there can be scenarios (e.g. `UpdateMono`) which
disallow installation of any programs and should any of the essential
programs be missing, we'd see a failure similar to:
Required program '7za' could not be found
System.InvalidOperationException: Required program '7za' could not be found
at Xamarin.Android.Prepare.OS.Which (System.String programPath, System.Boolean required)
at Xamarin.Android.Prepare.EssentialTools.Init (Xamarin.Android.Prepare.Context context)
at Xamarin.Android.Prepare.Context+<Init>d__201.MoveNext ()
--- End of stack trace from previous location where exception was thrown ---
at …
=> [xaprepare] Don't require binaries when unable to install them

src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs
Context: 60363ef45cd6994a322adac1b73d4271b0658c1e
This commit is, in a way, a follow-up to 60363ef4 in that it causes less
Java exceptions to "leak" to applications which use code shared between
platforms that might not be able to check for Java exception types
directly (because they don't link against `Mono.Android.dll`).  However,
instead of making the behavior optional, as implemented in 60363ef4,
this commit unconditionally wraps `Java.IO.Exception` and some of its
derivatives in the standard .NET `WebException`.  This makes the handler
to behave in a manner that's closer to how other `HttpClient` custom
handlers behave.
=> [AndroidClientHandler] Wrap Java exceptions in .NET ones

Documentation/guides/DotNet5.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.props, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Xamarin.Android.Sdk.Lite.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownProperties.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinPCLProject.cs
In .NET 5, Xamarin.iOS is already using `<OutputType>Exe<OutputType>`
to distinguish an iOS application vs an iOS class library.
Xamarin.Android, however, is checking the existence of
`Properties/AndroidManifest.xml`.
This brings up some issues:
* When using a multi-targeted project in .NET, we should be using the
same convention to distinguish library vs applications on both iOS
and Android.
* Xamarin.iOS apps have a `static void Main` method. `OutputType=Exe`
makes sense, as it tells Roslyn to expect a `Main` method.
To consolidate this, I propose:
* Use `$(OutputType)` of `Exe` to set `$(AndroidApplication)` to
`true`. No longer look for `AndroidManifest.xml` for this default.
* Immediately set `$(OutputType)` to `Library`, since we *never* want a
`Main` method on Android.
To make this …
=> [.NET 5] use $(OutputType) Exe for application vs library

Makefile, build-tools/automation/azure-pipelines.yaml
In the process of creating a new Mac OSS PR workflow, I encountered an issue where the build would consistently break when executing the `prepare-update-mono` target.  The break occurred on the following command on _a newly reimaged agent (bot)_:
```bash
pgrep -lfi VBCSCompiler.exe
```
The command returns 0 if the managed compiler server `VBCSCompiler.exe` is running; otherwise, it returns 1 if the process is not running.  When executing the build pipeline on the newly re-imaged machine, the process is not running, the `pgrep` command returns 1 and the build fails with the following error: 
```
pgrep -lfi VBCSCompiler.exe
make: *** [prepare-update-mono] Error 1
```
Turns out that on established build machines in the pool, `VBCSCompiler.exe` is consistently found to be running at this …
=> Fix build break on newly reimaged bot

tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Aot.apkdesc, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Bundle.apkdesc, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Profiled-Aot.apkdesc, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release.apkdesc, tools/apkdiff/ApkDescription.cs
This will allow cleaner patches to `.apkdesc` files.
The current `.apkdesc` files are updated to contain the sorted entries.
=> [apkdiff] Use sorted dictionary for .apkdesc

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs, tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs
Currently with .NET 5, you can build, deploy, and run an app with:
dotnet publish foo.csproj -t:Install -t:StartAndroidActivity
This doesn't match the behavior of other platforms that use `dotnet
run` to launch.
Unfortunately `dotnet run` won't work in its current state:
Unable to run your project.
Ensure you have a runnable project type and ensure 'dotnet run' supports this project.
A runnable project should target a runnable TFM (for instance, netcoreapp2.0) and have OutputType 'Exe'.
The current OutputType is 'Library'.
But we can supply a `Run` target to start Android applications:
https://github.com/dotnet/sdk/blob/645919b8e850771a73f2f7a31b97038d6bdf1092/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L755-L758
This at least allows this command to work:
dotnet …
=> [.NET 5] add a `Run` MSBuild target

.external
Changes: https://github.com/mono/mono/compare/58b04da0d7c746c1a45eee1a14db1f50653e545f...051408e0befb4f8da7c3072702e24ebe7bbbcf9d
* mono/mono@051408e0bef: Bump CoreFX to pickup https://github.com/mono/corefx/pull/398. (#19566)
=> Bump to mono/mono/2020-02@051408e0

Documentation/guides/DotNet5.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.props, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
Commit 60363ef4 added support for the `$(AndroidBoundExceptionType)`
MSBuild property, which controls whether or not Java exception types
are wrapped in appropriate .NET exception types from ".NET methods"
such as `IList.Add()` via `Android.Runtime.JavaList`/etc.
By default `$(AndroidBoundExceptionType)`=Java, meaning "don't wrap",
and `System` can be used to enable exception wrapping.
Commit 60363ef4 mentioned:
> [When .NET 5 is released with Xamarin.Android support][1], the
> default value will be `System`.
Do it!  Within .NET 5, `$(AndroidBoundExceptionType)`=System,
by default.
=> [.NET 5] $(AndroidBoundExceptionType)=System

build-tools/automation/azure-pipelines.yaml, build-tools/installers/create-installers.targets, build-tools/scripts/TestApks.targets
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1109699
Context: https://xamarinhq.slack.com/archives/C03CEGRUW/p1587737392083500
Remove `apkdiff` (2e28f2ea) from the macOS `.pkg` and Windows `.vsix`
installers.  After internal discussion, we felt that it didn't make
sense to include `apkdiff` within the Xamarin.Android installers, and
it would instead make more sense to package it for use with
`dotnet tool`.  See also:
* [`dotnet tool install` documentation][0]
* [Tutorial: Install and use a .NET Core global tool using the .NET Core CLI][1]
[0]: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install
[1]: https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-use
=> [apkdiff] Remove apkdiff from installers

Documentation/guides/messages/README.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/CheckDuplicateJavaLibraries.cs, src/Xamarin.Android.Build.Tasks/Tasks/GetJavaPlatformJar.cs, src/Xamarin.Android.Build.Tasks/Tasks/ParseAndroidWearProjectAndManifest.cs, src/Xamarin.Android.Build.Tasks/Tasks/PrepareWearApplicationFiles.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/CheckDuplicateJavaLibrariesTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Add all of the latest `.xlf` file changes from the 20200424 localization drop except for the changes related to XA0031 because those are for https://github.com/xamarin/xamarin-android/commit/231bf2a4381af4996c795e27fa65b15d63e3fc0b, which is only present on master.
Cherry-pick all of the corresponding `.resx` file changes from master.
This leaves two `.resx` file changes on master that are not yet cherry-picked because they do not yet have any corresponding translations in the `.xlf` files: 3fee2438 and ef12d24e.
=> LOC CHECKIN | xamarin/xamarin-android d16-6 | 20200424

build-tools/xaprepare/xaprepare/Steps/Step_PrepareLocal.cs, tests/Xamarin.Forms-Performance-Integration/Droid/Xamarin.Forms.Performance.Integration.Droid.csproj, tests/Xamarin.Forms-Performance-Integration/Xamarin.Forms.Performance.Integration.csproj, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Aot.apkdesc, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Bundle.apkdesc, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Profiled-Aot.apkdesc, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release.apkdesc
To have XF test with up to date Xamarin.Forms package.
Also update reference `.apkdesc` files.
Use older XF for *Bundle* flavor, as it hits the known issue https://github.com/xamarin/AndroidX/issues/64#issuecomment-606645412. The conditional `PackageReference` to older XF might be removed, once this issue is fixed.
=> [XF test] Update nuget packages

build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/apk-instrumentation.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml
Context: https://github.com/MicrosoftDocs/azure-devops-docs/issues/3265
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3679916&view=logs&j=8556562a-ae5f-5bd1-7c4d-bf1af4b6f1e1&t=5076e147-fc66-561e-6c69-3aa777afefc5
We sometimes observe experiencing "weird issue" on AzDO CI in which
the **Test** > **APK Instrumentation** step fails:
…/external/Java.Interop/src/Java.Interop/Java.Interop.targets(37,5): error MSB3073: The command """ -source 1.6 -target 1.6 -bootclasspath "" -d "obj/Release/ji-classes" java/com/xamarin/java_interop/internal/JavaProxyObject.java java/com/xamarin/java_interop/internal/JavaProxyThrowable.java java/com/xamarin/java_interop/GCUserPeerable.java java/com/xamarin/java_interop/ManagedPeer.java" exited with code 127.
The cause of the issue is …
=> [CI] Avoid use of `script: |` blocks

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ResolveSdksTaskTests.cs
Hanging test prints:
[TESTLOG] Test CheckClassIsReplacedWithMd5 Outcome=Passed
This started happening since 835c59bc, but I don't see how the commit
would cause it.
Working build (https://build.azdo.io/3669040) prints this after
`CheckClassIsReplacedWithMd5`:
=> Xamarin.Android.Build.Tests.ResolveSdksTaskTests.LatestTFV_OldTargetSdkVersion
After adding logging, etc. I couldn't figure out if this was a bug in
NUnit or our tests. Adding `[NonParallelizable]` for the entire
`ResolveSdksTaskTests` class seems to solve the hang, so I think we
should just go with this for now.
=> [tests] mark hanging test [NonParallelizable]

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets
Implements https://work.azdo.io/1112733 as a workaround for the conflicts between 
the built-in launchsettings.json-based .NET Core debugger and our Mono debugger.
=> Remove the LaunchProfiles capability for the CPS integration

Documentation/release-notes/4589.md, src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs
Context: https://github.com/xamarin/xamarin-android/issues/4550
It is possible that, in certain situations, a cancellation request
arriving from code external to `AndroidClientHandler` will not be
satisfied while starting the task to acquire connection status, because
the cancellation request appears after handler already established
connection to the remote host but before the request status is obtained.
Failure to check that the cancellation was requested may result in the
status retrieval task starting only to run into the issue that the
`AndroidClientHandler` object itself is already disposed (since the
cancellation request has been applied) and throw the
`ObjectDisposedException` instead of cancelling the status request
quietly.  Note that this is likely happen only in situations …
=> [AndroidClientHandler] Observe cancellation requests more

build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.DesignTime.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.EmbeddedResource.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
For .NET 5, I am looking into getting binding projects working.
There may not need to be a concept of a "binding project" *at all*, if
we can get the item groups to work in a regular .NET 5 Android
application or library.
My first thought was to just try something like this in
`Microsoft.Android.Sdk.targets`:
<Import Project="$(MSBuildThisFileDirectory)..\tools\Xamarin.Android.Bindings.targets" />
<Import Project="$(MSBuildThisFileDirectory)..\tools\Xamarin.Android.Common.targets" />
However, there is a lot of duplicate MSBuild targets in
`Xamarin.Android.Bindings.targets`. There are targets with the same
name that do slightly different things.
To try to consolidate this, I've created two new files:
* `Xamarin.Android.DesignTime.targets` - for design-time build things
* …
=> [Xamarin.Android.Build.Tasks] refactor common logic for binding projects

build-tools/xaprepare/xaprepare/Application/EssentialTools.cs, build-tools/xaprepare/xaprepare/Application/KnownConditions.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_Required.cs
Context: a5748347da50ea002ea7288821c8813fb82be4fa
a5748347 made `xaprepare` ignore "essential" tools if they are missing
from the system, so that certain scenarios (currently `UpdateMono`) can
complete their task even without the essentials being
installed (provided the scenario doesn't actually need the tool, of
course).  However, what was missing is the part to actually install the
tools, since they're not going to magically appear on the host we're
currently running on.  This, however, requires a task that can both
ignore missing essential tools *and* install them (the idea behind
essential tools is that the scenarios may blindly assume the tools
exist, thus making the code simpler).  One such task is the `Required`
scenario which ensures that all necessary bits are there.  However, …
=> [xaprepare] Install essential utilities in the `Required` scenario

Documentation/guides/DotNet5.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
Currently, we are producing `.apk` files with .NET 5 with:
dotnet publish foo.csproj
The problem with this is that `dotnet build` needs to produce
something that is "runnable". `dotnet build` is the developer loop,
while `dotnet publish` is something you run for a release.
Ideally, to produce an `.apk` you would instead do:
dotnet build foo.csproj
`dotnet publish` would be used for distribution to Google Play. Our
first implementation would likely support re-signing the app and
copying the output to a local `publish` directory.
For now, I've removed our usage of `$(_CorePublishTargets)` and moved
these targets to `$(BuildDependsOn)`. The benefit here, is we are no
longer using any private MSBuild properties for .NET 5.
I updated our tests in these areas. I dropped the tests running …
=> [Microsoft.Android.Sdk] change dotnet publish/build behavior

Configuration.props, Directory.Build.props, Documentation/guides/DotNet5.md, build-tools/automation/azure-pipelines.yaml, build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/Microsoft.Android.Sdk.proj, build-tools/create-packs/Xamarin.Android.Sdk.Lite.proj, build-tools/scripts/XAVersionInfo.targets, build-tools/xa-prep-tasks/xa-prep-tasks.targets, src/Mono.Android/Mono.Android.targets, src/Xamarin.Android.Build.Tasks/Tests/Directory.Build.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Updates the version for all .nupkg files we are generating for .NET 5 to
follow the dotnet [SDK versioning scheme][0].  For more information, see
Documentation/guides/DotNet5.md.
Versioning for release candidates has not yet been automated.  This
commit only introduces the following two package version types:
* 10.0.100-ci.branchname.commitdistance+sha.1b2c3d4e
* 10.0.100-ci.pr.gh1234.commitdistance+sha.1b2c3d4f
Version file generation has been updated to generate new files for our
nupkgs.  Mono.Android assembly info generation has also been updated to
include different version information depending on $(TargetFramework).
[0]: https://github.com/dotnet/designs/blob/master/accepted/2018/sdk-version-scheme.md
=> [.NET 5] Update NuGet package version scheme

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.TestCaseSource.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Since a6489813, we have a few MSBuild tests failing related to
multi-dex.
`BuildApplicationRequiresMultiDex("d8")` - for now I've just ignored
this test when running with `AndroidDexTool=d8`. It appears when API
21 is the minimum, `d8` is able to setup multi-dex automatically and
the build won't fail. I will need to revisit this in the future to
decide what Xamarin.Android should do about multi-dex going forward.
`BuildHasNoWarnings(False,True,True,"apk")` - one case we were
asserting there was 1 warning. Now there are 0 warnings.
`BuildMultiDexApplication(False,"v7.1")` - this test needed to be
parameterized for `AndroidDexTool` of `dx` and `d8`. I also generally
cleaned it up, removing `useJackAndJill` and simplifying assertions.
=> [tests] cleanup and fix failing MSBuild tests

build-tools/installers/create-installers.targets
Context: 42822e0488185cdf4bca7c0bd05b21ad03dfbd7e
42822e04 installed interpreter versions of the Mono runtime into our
build tree but did not add code to package them.  This commit adds the
necessary entries to include the interpreter runtime in .pkg and .vsix
installer packages.
=> [packaging] Package interpreter-enabled versions of the Mono runtime

Documentation/release-notes/bump-ji-56955d9ad3.md
Changes: https://github.com/xamarin/Java.Interop/compare/ce8dc4001bd7b5ab84c42b9b27711755f051cd2d...377c4c7ab50d1f25082c7079214b8075eb25de35
Fixes: https://github.com/xamarin/java.interop/issues/631
* xamarin/Java.Interop@377c4c7: Bump to xamarin/xamarin-android-tools/master@f5fcb9fd (#637)
* xamarin/Java.Interop@857b9a9: [Java.Interop.Export] Begin supporting methods with 14+ params (#635)
* xamarin/Java.Interop@9876e31: [Java.Interop.BootstrapTasks] Convert to SDK style project (#609)
* xamarin/Java.Interop@cbb50af: [generator-Tests] Use Roslyn for .NET Core Support (#638)
* xamarin/Java.Interop@56955d9: [generator] Use custom delegates instead of Func/Action. (#632)
* xamarin/Java.Interop@0a77166: [Java.Interop.sln] Commit updated automatically generated guids. (#634)
=> Bump to xamarin/Java.Interop/master@377c4c7a

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/automation/yaml-templates/use-dot-net.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs
Context: https://github.com/xamarin/net5-samples/blob/7607d1cde77f0bef676cb7e1a4290e3150501c56/azure-pipelines.yml
Context: https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer
Currently, on CI we've been doing:
- task: UseDotNet@2
inputs:
version: 5.0.100-preview.1.20155.7
This `UseDotNet` Azure DevOps task works for any public release of
.NET 5 found here:
https://dotnet.microsoft.com/download/dotnet/5.0
However, we need .NET 5 Preview 4, which is not on this public
downloads page yet...
Luckily, we can use these install scripts *instead*:
https://docs.microsoft.com/dotnet/core/tools/dotnet-install-script
The main drawback is the powershell script *only* works on Windows, so
we have to conditionally use bash on macOS.
This allows us to download any …
=> [build] install .NET 5 preview 4 nightly build

Documentation/release-notes/4640.md
Changes: https://github.com/xamarin/xamarin-android-tools/compare/12f52acd4407323b2e1b48ca56bab80ffd97b31e...f5fcb9fd1583ebe928734e8525303a0dbe93c79c
* xamarin/xamarin-android-tools@f5fcb9f: [Xamarin.Android.Tools.AndroidSdk] Add support for cmdline-tools (#83)
* xamarin/xamarin-android-tools@f473ff9: [AndroidSdkWindows] Guard against exception checking registry (#79)
* xamarin/xamarin-android-tools@36d7fee: JetBrains OpenJDK 11 detection (#82)
=> Bump to xamarin/xamarin-android-tools/master@f5fcb9fd

src/Mono.Android/Test/Android.OS/BundleTest.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingDebugNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingReleaseNativeAssemblyGenerator.cs, src/monodroid/jni/embedded-assemblies.cc, tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/BindingTests.cs, tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/Timing.cs, tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/java/com/xamarin/android/Timing.java
Fixes: https://github.com/xamarin/xamarin-android/issues/4596
Fixes: https://github.com/xamarin/xamarin-android/issues/4660
Context: https://github.com/xamarin/monodroid/commit/192b1f1b71c98650d04bf0a4e52ee337a054ff4c
Context: https://github.com/xamarin/java.interop/blob/fc18c54b2ccf14f444fadac0a1e7e81f837cc470/src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs#L149-L186
Context: https://github.com/xamarin/java.interop/blob/010161d1ef6625b762429334f02e7b15e1f7caae/src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs#L155
~~ Debug Mode ~~
In some environments, `BundleTest.TestBundleIntegerArrayList2()` fails
when  using the commercial shared runtime:
Test …
=> [typemaps] Handle Java to managed type maps properly

src/monodroid/jni/embedded-assemblies.cc
Fixes: https://github.com/xamarin/xamarin-android/issues/4596
Context: a017561b1e44c51a9af79fae0baaa50fe01c4123
Context: https://gist.github.com/pjcollins/87762e81f1f3c7e8b821356e4612eecf
A missing parameter in a call to `log_debug` added in a017561b may lead
to a segfault when `assembly` log category and `debug` log level are
enabled:
F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3 in tid 922 (DrawableTinting), pid 922 (DrawableTinting)
I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
I /system/bin/tombstoned: received crash request for pid 922
I crash_dump64: performing dump of process 922 (target tid = 922)
F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
F DEBUG   : Build fingerprint: …
=> [typemaps] Fix a log statement which may lead to segfault when used

Documentation/release-notes/4653.md, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, src/Mono.Android/Mono.Android.slnf, src/Mono.Android/metadata
Bumps our API-R preview from DP2 to DP4.  This only required one `metadata` to make a method match its base visibility.
Note this does not include additional enumification.  The current plan is to have enumification complete for 16.7 (10.4) P3.
=> [Mono.Android] API-R Developer Preview 4.

build-tools/create-packs/Microsoft.Android.Sdk.proj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NuGet.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Tasks/FixupNuGetReferences.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsXASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetStandard.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/AndroidX/Tabbar.xml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/AndroidX/Toolbar.xml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj, tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs
Context: https://github.com/xamarin/net5-samples/blob/d525d8a2d60700f52f86372c47e83d646d800aa4/Directory.Android.targets
Currently, .NET 5 will not restore *existing* Xamarin.Android NuGet
packages. It does not know to map `netcoreapp5.0` to
`MonoAndroid10.0`, `MonoAndroid9` etc.
We'll need to work around this until this lands:
* https://github.com/NuGet/NuGet.Client/pull/3339
To get a Xamarin.Forms project building & running *at all* in
`xamarin/net5-samples`, I had to:
1. Change `$(AssetTargetFallback)`
2. Write an MSBuild target to replace any instances of
`netstandard2.0\Xamarin.Forms.Platform.dll` with
`MonoAndroid10.0\Xamarin.Forms.Platform.dll`.
3. Add additional platform-specific assemblies in
`$(PkgXamarin_Forms)\lib\MonoAndroid10.0\`
There are still some issues with this:
1. You …
=> [.NET 5] NuGet workarounds for Xamarin.Forms projects

Documentation/release-notes/4670.md, src/r8/build.gradle
Context: https://r8.googlesource.com/r8/+/refs/tags/1.6.82/
Context: https://mvnrepository.com/artifact/com.android.tools/r8/1.6.82
=> Bump to r8 1.6.82

.gitmodules, Documentation/release-notes/4683.md, build-tools/automation/CredScanSuppressions.json, build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/ThirdPartyNotices/proguard.cs, src/proguard/proguard.targets
Changes: https://github.com/Guardsquare/proguard/compare/9d4660e5...ebe9000c
This updates our submodule from:
https://github.com/xamarin/proguard
To the official ProGuard source on Github:
https://github.com/Guardsquare/proguard/
To build only `proguard.jar` and no other optional components, I was
able to build `:core` and copy `core.jar` to the proper location.
I also added `ignore = dirty` setting, since we lost control of the
`.gitignore` setup in the `external/proguard` git submodule. Otherwise
we will always show changes to `external/proguard` after a build.
=> [ProGuard] bump to 6.2.2 and use Github source

.external
Changes: https://github.com/xamarin/monodroid/compare/9242fa4fe5df2413faf12689c522825404b90755...e50ff9a43a56293cb3c9112344f250eebc002ec8
* xamarin/monodroid@e50ff9a43: Bump to xamarin/androidtools/master@ff35fa96 (#1092)
* xamarin/monodroid@3d4f171a0: Bump to xamarin/xamarin-android/master@a01756 (#1087)
* xamarin/monodroid@5560daf55: [tools/RuntimeService] base versionCode off xamarin-android (#1088)
=> Bump to xamarin/monodroid/master@e50ff9a4

Documentation/release-notes/fix-4675.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: f0b1e8a53054c5620b256b7f5613ef5b3610146c
Fixes: https://github.com/xamarin/xamarin-android/issues/4675
Thanks to commit f0b1e8a5, Xamarin.Android 10.0 and higher no longer
require the NDK when `$(AotAssemblies)`=`true` or
`$(AndroidEnableProfiledAot)`=`true`.  The NDK is now only required when
`$(EnableLLVM)`=`true` or when `$(BundleAssemblies)`=`true`.
Update `GetAndroidDependencies` to account for this new behavior.  This
allows users who have `$(AotAssemblies)`=`true` or
`$(AndroidEnableProfiledAot)`=`true` to build successfully from within
Visual Studio without being forced to install the NDK.  Previously, this
scenario was blocked by an error:
The project AndroidApp1 is missing Android SDKs required for building. Double-click on this message and follow the prompts to install …
=> [Xamarin.Android.Build.Tasks] Update NDK dependency check

src/monodroid/CMakeLists.txt
The `CMAKE_LIBRARY_OUTPUT_DIRECTORY` value was same for Debug and
Release build types (which is not the same as Configuration, we build
both types in each configuration). And because we configure these
in parallel, it might result in concurent file writes.
I think this is causing these errors on build bots:
error : CMake Error at C:/Users/dlab14/android-toolchain/sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CheckCXXSourceCompiles.cmake:91 (file): [C:\A\vs2019xam00000E-1\_work\2\s\src\monodroid\monodroid.csproj]
error :   file failed to open for writing (Permission denied): [C:\A\vs2019xam00000E-1\_work\2\s\src\monodroid\monodroid.csproj]
error :     C:/A/vs2019xam00000E-1/_work/2/s/src/monodroid/obj/Release/x86_64-Release/CMakeFiles/CMakeTmp/src.cxx …
=> [monodroid] Set cmake path to include build type

build-tools/automation/azure-pipelines-oss.yaml, build-tools/create-pkg/create-pkg.targets, build-tools/debian-metadata/rules
Context: https://dev.azure.com/xamarin/public/_build/results?buildId=18233&view=results
Our OSS Linux builds have been failing because they are running out of
disk space.  I've set up a new [virtual machine scale set agent pool][0]
to try to use for our Ubuntu builds.  These VMs are configured with more
disk space than the ~10 GB allowed by the hosted agents.
The virtual machine scale set resource can be found in the azure portal
here:
https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/64e11c84-c922-4ffd-bea9-67ab39354edd/resourceGroups/XAMARIN-PUBLIC-PIPELINES/providers/Microsoft.Compute/virtualMachineScaleSets/android-public-ubuntu-vmss/overview
[0]: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops
=> [CI/OSS] Use new Ubuntu VM scale set agents

Documentation/release-notes/4654.md, Documentation/release-notes/r8-multidex-config.md, src/Xamarin.Android.Build.Tasks/Tasks/R8.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.D8.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.DX.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.EmbeddedResource.targets
Context: https://developer.android.com/studio/build/multidex#mdex-gradle
When `android:minSdkVersion` is 21 or higher, d8 can automatically
support multi-dex. It will merely generate multiple `classes.dex`
files as needed, and we won't have a need for an
`$(AndroidEnableMultiDex)` MSBuild property.
Changes when `$(AndroidDexTool)` is set to `d8`:
* We no longer use `android-support-multidex.jar`.
* We no longer use `android.support.multidex.MultiDexApplication`.
* `$(AndroidEnableMultiDex)` is not used for anything.
These changes are not made when `AndroidDexTool=dx`
This makes the `<R8/>` MSBuild task much simpler, as many of the
incoming values are no longer needed. `<R8/>` will now only be needed
when `AndroidLinkTool=r8` and developers are opting into code
shrinking.
=> [Xamarin.Android.Build.Tasks] simplify d8/r8 multi-dex support

Documentation/guides/DotNet5.md, build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/create-packs/Microsoft.Android.Ref.proj, build-tools/create-packs/Microsoft.Android.Runtime.proj, build-tools/create-packs/Microsoft.Android.Sdk.proj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Tooling.targets
The latest .NET 5 previews now have support for a $(TargetFramework) of
`net5.0`, which allows us to replace our usage of `netcoreapp5.0` with
`net5.0`.
The .NET 5 version of `_ResolveSdks` has also been updated to avoid
usage of the projects $(TargetFramework) value when setting the path
to `Mono.Android.dll`.  This fixes an issue that was occurring when
using the latest .NET 5 nightly preview, which was the result of Android
projects using targeting packs with different $(TargetFramework) values.
/Users/peter/.nuget/packages/microsoft.android.sdk/10.0.100-ci.net5-fix-tf.22/tools/Xamarin.Android.Tooling.targets(61,5): error XARSD7004: System.ArgumentException: `/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0-preview.6.20264.1/ref/netcoreapp5.0` must be a directory! …
=> [.NET 5] Update TargetFramework to net5.0

Documentation/guides/messages/xa0113.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/Legacy/ResolveAndroidTooling.cs
Context: https://support.google.com/googleplay/android-developer/answer/113469#targetsdk
As of August 1, 2019, Google Play requires API level 28. The `XA0113` warning was checking for API 26, so it needed to be updated.
The `XA0117` warning also needs to be updated as API 21 is Xamarin.Android's new supported minimum API level.
=> [Xamarin.Android.Build.Tasks] update API level warning messages

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Context: https://github.com/xamarin/xamarin-android/pull/4356
In order to build preview bindings on Windows, we set the following properties in `Configuration.props`:
```
<AndroidLatestStableApiLevel Condition="'$(AndroidLatestStableApiLevel)' == ''">30</AndroidLatestStableApiLevel>
<AndroidLatestStablePlatformId Condition="'$(AndroidLatestStablePlatformId)' == ''">R</AndroidLatestStablePlatformId>
<AndroidLatestStableFrameworkVersion Condition="'$(AndroidLatestStableFrameworkVersion)'==''">v10.0.99</AndroidLatestStableFrameworkVersion>
```
This writes the generated files to `src\Mono.Android\obj\$(Configuration)\monoandroid10\android-R\mcw`, however `Xamarin.Android.Build.Tasks.csproj` is looking in `src\Mono.Android\obj\$(Configuration)\monoandroid10\android-30\mcw`, because it is using …
=> [XA.Build.Tasks] Use 'android-R' instead of 'android-30' to properly find preview bindings.

Documentation/release-notes/4554.md, src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ResourceDesignerImportGenerator.cs
Fixes #4542
Our previous fix d18c824c did not take into account that users might
need to add `global` to their list of aliases in the `ProjectReferece`
MetaData. This then causes the following error
Error CS1681: You cannot redefine the global extern alias (CS1681)
So to fix this we need to ignore the `global` entry if one is present.
=> [Xamarin.Android.Build.Tasks] Ignore `global` Alias when emitting code.

src/Xamarin.Android.Build.Tasks/Tasks/ManifestMerger.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
Fixes #4662
The `manifestmerger.jar` did not work in the way we expeected.
Its primary purpose is to allow users to remove/modify manifest
items from `LIBRARY` projects. What it doesn't do it process
items in the main manifest itself.
As part of our build system we sometimes auto generate manifest
items based on C# attributes within a referenced assembly. A good
example of this is the `ZXing.Net.Mobile` packages. This will
inplicitly add a `uses-permission` element for `android.permission.CAMERA`.
In #4662 the user expectation was that if they add the `tools:node="remove"`
to the `uses-permission` element in their own manifest, this would stop
the permission from being added. Unfortunately this did NOT happen.
The `manifestmerger.jar` completely ignored this entry and it ended up
in the …
=> [Xamarin.Android.Build.Tasks] Honour Manifest `tools:node="remove"` items.

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs, tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
Context: https://build.azdo.io/3744248
Some of the MSBuild performance timings have started failing.
It seems like it is a change on the build machines, as I've not seen
anything in the logs pointing out a regression. I merely bumped a few
of the times here.
I also fixed the failure related to missing test attachments:
TearDown : System.IO.FileNotFoundException : Test attachment file path could not be found.
If one of the files was missing in `DeviceTest.cs`, then it would fail
getting any subsequent attachments due to the thrown exception.
=> [tests] fix PerformanceTest

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.CSharp.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.FSharp.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.VisualBasic.targets
Context: a64898132e746d4425d54cfc4c52f6fc7892ef9c
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3745247&view=logs&j=43d78dc4-ec1e-5245-95fd-87585dd83b08&t=6c172c00-c01b-5149-b118-044152099deb
Ever since a6489813, API-21 has been the minimum supported API-level
for applications, which in turn means that the minimum
`$(TargetFrameworkVersion)` value is v5.0.
What happens if an `.csproj` file doesn't explicitly provide a
`$(TargetFrameworkVersion)` value?  Then the project "inherits" the
default value specified in e.g. `Xamarin.Android.CSharp.targets`:
<TargetFrameworkVersion Condition="'$(TargetFrameworkVersion)' == ''">v4.4</TargetFrameworkVersion>
v4.4 is API-19, which is less than v5.0/API-21.
Which …
=> [Xamarin.Android.Build.Tasks]

build-tools/installers/create-installers.targets
Running this command on macOS was failing for me:
$ msbuild /t:CreateAllPacks build-tools/create-packs/Microsoft.Android.Sdk.proj
With:
build-tools/installers/create-installers.targets(72,5): error MSB3073:
The command "mono "bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/mdoc.exe" --debug assemble -o "bin/Debug/lib/monodoc/MonoAndroid-lib" "external/android-api-docs/docs/Mono.Android/en/\" "external/android-api-docs/docs/OpenTK-1.0/en/\" "external/android-api-docs/docs/Xamarin.Android.NUnitLite/en/\"" exited with code 1. [build-tools/create-packs/Microsoft.Android.Sdk.proj] [build-tools/create-packs/Microsoft.Android.Sdk.proj]
build-tools/create-packs/Directory.Build.targets(61,5): error MSB3073:
The command "dotnet pack -p:Configuration=Debug …
=> [build] fix /t:CreateAllPacks on macOS Catalina

.gitmodules, Documentation/building/configuration.md, Documentation/release-notes/4686.md, build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/ThirdPartyNotices/K4os.Compression.LZ4.cs, build-tools/xaprepare/xaprepare/ThirdPartyNotices/lz4.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateCompressedAssembliesNativeSourceFiles.cs, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Tasks/PrepareAbiItems.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ARMNativeAssemblerTargetProvider.cs, src/Xamarin.Android.Build.Tasks/Utilities/AssemblyCompression.cs, src/Xamarin.Android.Build.Tasks/Utilities/CompressedAssembliesNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/CompressedAssemblyInfo.cs, src/Xamarin.Android.Build.Tasks/Utilities/NativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/X86NativeAssemblerTargetProvider.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/monodroid/CMakeLists.txt, src/monodroid/jni/application_dso_stub.cc, src/monodroid/jni/basic-utilities.hh, src/monodroid/jni/embedded-assemblies.cc, src/monodroid/jni/embedded-assemblies.hh, src/monodroid/jni/xamarin-app.hh, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Bundle.apkdesc
Currently, `Xamarin.Android` supports managed assembly compression in
the APK archive if application is bundled (with Mono's `mkbundle`) into
a native shared library.  Managed assemblies are compressed using gzip
compression and placed in an array inside the data section of the shared
library.  However, support for `mkbundle` is possibly going to be
removed and we realized it is a feature some developers appreciate since
the produced APKs are smaller and the impact on startup time isn't big
enough to worry.
This commit aims to be a replacement for `mkbundle` with a handful of
improvements thrown in.  First of all, the compression is performed
using the [managed implementation][0] of the excellent [LZ4][1]
algorithm.  This gives us a decent compression ratio and a much faster …
=> Add support for compressed assemblies in APK

src/monodroid/jni/embedded-assemblies.cc
Fixes: https://github.com/xamarin/xamarin-android/issues/4727
Context: https://developercommunity.visualstudio.com/content/problem/1021788/javainterop-assembly-not-found-for-xamarin-android.html
Turn some warnings about typemap not finding entries to info-level
messages, not visible by default.
=> Less assembly logging

Documentation/guides/DotNet5.md, build-tools/automation/yaml-templates/run-msbuild-mac-tests.yaml, build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.props, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.TestCaseSource.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidBindingProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidLibraryProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsXASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetStandard.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetXamarinProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/IShortFormProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Utilities/ProjectExtensions.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Utilities/XmlUtils.cs, tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs
As we transition to One .NET, we need a way to run our existing
MSBuild tests with `dotnet build` instead of `msbuild`.
To do this:
* Add a new `dotnet` category, on a subset of tests. Eventually, we
may be able to run all tests, but not quite yet.
* Add a `--params dotnet=true` parameter to the `nunit3-console`
invocation.
* `Xamarin.ProjectTools` does not have a reference to NUnit, so create
a `Builder.UseDotNet` static property that is set in `BaseTest`.
* `Builder.UseDotNet` is used throughout `Xamarin.ProjectTools` to
change the contents of generated projects.
For now, this enables 35 passing tests. We will fix issues and enable
more of them moving forward.
Workarounds:
* We have to set `$(XamarinAndroidSupportSkipVerifyVersions)` for
existing support libraries to be used.
* We have …
=> [tests] One .NET MSBuild test infrastructure

Documentation/release-notes/4724.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/BundleToolTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/InlineData.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/4664
Fixes: https://feedback.devdiv.io/1030901
It turns out that building *inside* Visual Studio is causing `.resx`
files to stop working. Satellite assemblies are missing from the APK
and/or were not deployed with Fast Deployment.
In 65a917a9, I removed a direct call to `<ResolveAssemblyReference/>`
for performance reasons. This appears to have caused this problem.
This is due to:
https://github.com/microsoft/msbuild/blob/dc485bce3427e9d2b020ce61c2400e7b5a76062c/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2101
https://github.com/microsoft/msbuild/blob/dc485bce3427e9d2b020ce61c2400e7b5a76062c/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2059
`<ResolveAssemblyReference/>` by default only finds satellite
assemblies when …
=> [Xamarin.Android.Build.Tasks] fix .resx files for IDE builds

Documentation/release-notes/4724.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/BundleToolTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/InlineData.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/4664
Fixes: https://feedback.devdiv.io/1030901
It turns out that building *inside* Visual Studio is causing `.resx`
files to stop working.  Satellite assemblies are missing from the
`.apk` and/or were not deployed with Fast Deployment.
In 65a917a9, I removed a direct call to `<ResolveAssemblyReference/>`
for performance reasons. This appears to have caused this problem.
This is due to:
* https://github.com/microsoft/msbuild/blob/dc485bce3427e9d2b020ce61c2400e7b5a76062c/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2101
* https://github.com/microsoft/msbuild/blob/dc485bce3427e9d2b020ce61c2400e7b5a76062c/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2059
`<ResolveAssemblyReference/>` by default only finds satellite …
=> [d16-6] [Xamarin.Android.Build.Tasks] fix .resx files for IDE builds

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Utilities/XDocumentExtensions.cs
Fixes: https://feedback.devdiv.io/955972
Android layout files with utf8 characters and custom views fail to
build with:
error APT2258: not well-formed (invalid token).
In be47b3ec, I inadvertently changed the `<ConvertCustomView/>`
MSBuild task to save changes using `Encoding.Default`.
`XDocumentExtensions.SaveIfChanged` should just use
`MonoAndroidHelper.UTF8withoutBOM` by default.
The other places that use this method, will not be affected by using
UTF-8 without a BOM. I also fixed two other places in the build that
use `Encoding.Default`.
I updated two tests to reproduce this issue.
=> [Xamarin.Android.Build.Tasks] fix for utf8 chars and custom views

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
TimeZone tests fail to build with `/restore`:
NuGet.targets(124,5): The local source '/Users/runner/runners/2.168.2/work/1/s/bin/BuildRelease/nupkgs' doesn't exist.
In 10d814f2, I added support for running our MSBuild test suite under
.NET 5. This inadvertently added the local source to the
`NuGet.config` for the TimeZone tests.
To fix this, I made the change so the `NuGet.config` will only contain
the extra sources if:
* `XASdkProject` is used.
* `Builder.UseDotNet` is set via `nunit3-console --params dotnet=true`.
=> [tests] fix failing NuGet restore on TimeZone tests

Documentation/release-notes/4724.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/BundleToolTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/InlineData.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/4664
Fixes: https://feedback.devdiv.io/1030901
It turns out that building *inside* Visual Studio is causing `.resx`
files to stop working.  Satellite assemblies are missing from the
`.apk` and/or were not deployed with Fast Deployment.
In 65a917a9, I removed a direct call to `<ResolveAssemblyReference/>`
for performance reasons. This appears to have caused this problem.
This is due to:
* https://github.com/microsoft/msbuild/blob/dc485bce3427e9d2b020ce61c2400e7b5a76062c/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2101
* https://github.com/microsoft/msbuild/blob/dc485bce3427e9d2b020ce61c2400e7b5a76062c/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2059
`<ResolveAssemblyReference/>` by default only finds satellite …
=> [d16-7] [Xamarin.Android.Build.Tasks] fix .resx files for IDE builds

build-tools/installers/create-installers.targets, build-tools/scripts/MSBuildReferences.projitems, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
When running `InstallAndroidDependenciesTest` locally it fails with the following error.
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
File name: 'Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
at Xamarin.Installer.AndroidSDK.Manager.Helper.Unzip (System.String baseDirectory, System.String archivePath, System.String fileOwnerName, Xamarin.Installer.Common.InstallationProgressEventArgs+InstallationProgressActionDelegate progressCallback) [0x002d9] in <4587721623424dba847f5b558050d27a>:0 
at Xamarin.Installer.AndroidSDK.Common.BasePackage.InstallArchive (System.String …
```
=> Include Mono.Posix.NETStandard as it is required by LibZipsharp and SDK Manager

Documentation/guides/messages/README.md, Documentation/guides/messages/xa1023.md, Documentation/release-notes/dx-deprecation.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://android-developers.googleblog.com/2020/02/the-path-to-dx-deprecation.html
On February 1, 2021 DX will be removed from the Android SDK and
Android Studio. We should start emitting a warning in Xamarin.Android
*now*, so that developers can migrate to D8.
=> [Xamarin.Android.Build.Tasks] warning message that DX is deprecated

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Application.targets
Fixes https://github.com/xamarin/xamarin-android/issues/4152
And don't use `-f` option when calling `aprofutil` as the adb might not
be in the `PATH`
=> Set the adb port forwarding

build-tools/automation/azure-pipelines-oss.yaml, build-tools/create-packs/Microsoft.Android.Sdk.proj, build-tools/installers/create-installers.targets
`Mono.Terminal` has a timestamp:
$ ls -l ./Debug/lib/xamarin.android/xbuild/Xamarin/Android/Mono.Terminal.dll
-rwxr--r-- 1 grendel grendel 20480 Jan  1  1980 ./Debug/lib/xamarin.android/xbuild/Xamarin/Android/Mono.Terminal.dll
That causes the failure:
"build-tools/create-packs/Microsoft.Android.Sdk.proj" (CreateAllPacks target) (1) ->
/usr/share/dotnet/sdk/3.1.300/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error : The DateTimeOffset specified cannot be converted into a Zip file timestamp. (Parameter 'value')
`Mono.Terminal` is only used by `logcat-parse`, so we should exclude
this file for .NET 5 packages. `logcat-parse` is already excluded.
There is also some incorrect casing that causes:
(CreateAllPacks target) -> …
=> [build] fixes for .nupkg's on Linux

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
The Builder.BuildInternal function has been updated to print the build
tool being used and the arguments being passed to it.  Some additional
cleanup has been made around legacy code which previously would allow
`xbuild` to be used as a build tool on macOS.
Sample "before" output:
=> Xamarin.Android.Build.Tests.BuildTest.DuplicateManagedNames
[TESTLOG] Test DuplicateManagedNames Starting
Using msbuild
Using msbuild
Using msbuild
Using msbuild
Found Time Elapsed 00:00:11.4900000
Sample "after" output:
=> Xamarin.Android.Build.Tests.IncrementalBuildTest.ConvertCustomView(False)
[TESTLOG] Test ConvertCustomViewFalse Starting
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe C:\A\vs2019xam00000N-1\_work\2\s\bin\TestRelease\temp\ConvertCustomViewFals …
=> [Xamarin.Android.Build.Tests] Print build tool and args

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
This test is failing with:
1) Failed : Xamarin.Android.Build.Tests.IncrementalBuildTest.BuildIncrementalAot("arm64-v8a","Hybrid",False,True)
`_BuildApkEmbed` should be skipped on second build!
Expected: True
at Xamarin.Android.Build.Tests.IncrementalBuildTest.BuildIncrementalAot
This is triggered due to the `<CilStrip/>` MSBuild task:
https://github.com/xamarin/xamarin-android/blob/0022554468a0d0ded26c7fd119a555cddd5525ff/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L2253-L2259
It modifies the assemblies in-place. This causes the generated native
assembly code to change, and so you see things like:
Input file "obj/Release/android/typemaps.armeabi-v7a.o" is newer than output file "obj/Release/app_shared_libraries/armeabi-v7a/libxamarin-app.so".
So then the …
=> [tests] ignore incremental Hybrid AOT test

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
Context: https://github.com/android/ndk/wiki/Changelog-r21#r21c
Changes:
* [Issue 1060][0]: A macOS app bundle that is signed and notarized is now
available for download from our wiki and our website. Note that
because only bundles may use RPATHs and pass notarization, the
traditional NDK package for macOS *cannot be notarized. The SDK will
continue to use the traditional package as the app bundle requires
layout changes that would make it incompatible with Android Studio.
The NDK is not quarantined when it is downloaded via the SDK manager,
so is curently allowed by Gatekeeper. The SDK manager is currently the
most reliable way to get the NDK for macOS.
* [Issue 1207][1]: Fix fatal error in clang when building with -O2 on arm64.
* [Issue 1239][2]: Fix network drive issues for clang.
* …
=> Bump NDK to r21c

build-tools/scripts/MSBuildReferences.projitems, tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs, tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
Context: https://msbuildlog.com
Context: https://github.com/microsoft/msbuild/blob/ba9a1d64a7abf15a8505827c00413156a3eb7f62/src/Build/Logging/BinaryLogger/BuildEventArgsReader.cs
I've noticed that we have been including some MSBuild overhead in our
timings in `PerformanceTest`. If you use the MSBuild binlog viewer,
you can see the "project build time" can be *seconds* shorter than the
overall build time. This extra time is spent for MSBuild startup,
shutdown, and writing log files, etc. We can exclude this time for
these tests.
We can get this number by parsing the `.binlog` file directly, using a
`BuildEventArgsReader` MSBuild API. I just had to update our
`<PackageReference/>` to `Microsoft.Build.*` to a newer version.
Keeping a `Stack` of "project started" event, you can sum them as …
=> [tests] improve PerformanceTest accuracy

build-tools/automation/yaml-templates/run-integrated-regression-tests.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3765530&view=logs&jobId=1cfdb47b-00d6-51ee-9189-006d3307b76f
Our Windows regression test jobs have been failing for a number of weeks
due to a timeout during provisioning.  After getting access to one of
these machines, I noticed that 'VSIXInstaller.exe' processes were being
kept open even after invocations of the tool completed succesfully.
I was able to avoid this issue by deleting the Visual Studio `Installer`
directory that was left behind, and running a stable VS Installer to
replace the old installer with a stable version.  It seems that an early
16.7 preview version of VSIXInstaller.exe was problematic, and the
latest public preview and stable installers do not have this issue.
=> [CI] Delete VS installer before provisioning VS

src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs
I discovered the `Profile.IsSdkAssembly()` and
`Profile.IsProductAssembly()` checks only work against assembly names:
https://github.com/xamarin/xamarin-android/blob/a134aa72df62d7d1bfb4da52b5c642dbfe4d0490/src/Xamarin.Android.Build.Tasks/Linker/Mobile.Tuner/MobileProfile.cs#L12-L197
So we were actually checking for obsolete `AppDomain` usage in the BCL,
`Mono.Android.dll`, `Java.Interop.dll`, etc.
I fixed these checks by using `Path.GetFileNameWithoutExtension()`.
Now these assemblies shouldn't even be loaded with Mono.Cecil at all.
Before:
2596 ms  LinkAssembliesNoShrink                     1 calls
After:
1849 ms  LinkAssembliesNoShrink                     1 calls
Saved ~750ms.
This was running an initial build of the Xamarin.Forms integration
project on macOS. There will likely be not …
=> [Xamarin.Android.Build.Tasks] fix IsSdkAssembly() checks in LinkAssembliesNoShrink

Configuration.props
Context: https://github.com/xamarin/xamarin-android-tools/pull/85
Partially reverts commit 5ad666d5a591a0a18ab6645664a3a0a0e17ca7d6.
Commit 5ad666d5 bumped the Android SDK Build-tools version that
`xaprepare` installs to be 30.0.0-rc4, which is problematic becuase it
contains an `apksigner.jar` which requires JDK11, support for which
has not yet been merged (see PR #4567).
In retrospect, bumping the `$(XABuildToolsVersion)` value was a
Bad Idea™.  It was the `DexUtils.cs` change that we wanted.
Revert the `$(XABuildToolsVersion)` bump, and thus once again provision
Android SDK Build-tools 29.0.2.
=> Bump to Android SDK Build-tools 29.0.2

src/Xamarin.Android.Build.Tasks/Utilities/Aapt2Daemon.cs
Context https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1130414
For some unknown reason the setting of `Console.InputEncoding`
on a customers machine is throwing an IOException. This then
causes Visual Studio to completely crash.
```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
at System.IO.__Error.WinIOError(Int32, System.String)
at System.IO.__Error.WinIOError()
at System.Console.set_InputEncoding(System.Text.Encoding)
at Xamarin.Android.Tasks.Aapt2Daemon.Aapt2DaemonStart()
at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at …
```
=> [Xamarin.Android.Build.Tasks] Catch Exception when setting Console.InputEncoding

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Context: https://build.azdo.io/3775041
We've been seeing the F# tests fail with errors such as:
NuGet.targets(124,5): error : Could not find file "/Users/runner/.local/share/NuGet/v3-cache/1ca707a4d90792ce8e42453d4e350886a0fdaa4d$ps:_api.nuget.org_v3_index.json/nupkg_fsharp.core.4.7.1.dat"
These are likely due to `FSharp.Core` being restored in parallel.
I added `[NonParallelizable]` to the F# tests, which has fixed this
problem for certain tests in the past.
I also cleaned up the `BuildBasicApplicationFSharp` test to use a
parameter for `Debug` vs `Release`.
=> [tests] mark F# tests NonParallelizable

Configuration.props
Context: https://androidstudio.googleblog.com/
Context: https://androidstudio.googleblog.com/2020/03/emulator-3006-canary-windows-performance.html
Context: https://androidstudio.googleblog.com/2020/04/emulator-3007-canary.html
Context: https://androidstudio.googleblog.com/2020/04/emulator-3008-canary.html
Context: https://androidstudio.googleblog.com/2020/04/emulator-3009-canary.html
Context: https://androidstudio.googleblog.com/2020/05/emulator-30012-canary-psa-if-emulator.html
Changes (cumulative, since 30.0.5):
* Upgraded protobuf verison to 3.11.4
* Added experimental car data replay feature for when running
Android Auto Embedded system images to the car data page in
the extended controls.
* Fixed kernel version parsing issue when running aarch64 guest kernels
* Vulkan
* Worked around …
=> Bump Android Emulator to v30.0.12

.external
Changes: https://github.com/xamarin/monodroid/compare/8d51d0af0572db1583a8ab5ec095bec3046ae476...0d0e4527f142e73bdff9fa1b63349bb0a1631900
Context: 5bba16ec4e72365a77e0996fd0ea4a4769ad9f9a
* xamarin/monodroid@0d0e4527f: Bump to xamarin/androidtools/d16-7@315b97be (#1096)
=> Bump to xamarin/monodroid/d16-7@0d0e4527

Configuration.props, build-tools/check-boot-times/Program.cs, build-tools/scripts/TestApks.targets, build-tools/xaprepare/xaprepare/Application/KnownProperties.cs, build-tools/xaprepare/xaprepare/Application/Properties.Defaults.cs.in, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.Linux.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.MacOS.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.Windows.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, build-tools/xaprepare/xaprepare/Steps/Step_Android_SDK_NDK.cs, build-tools/xaprepare/xaprepare/xaprepare.targets
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3711144&view=logs&jobId=4348ab7c-72f0-52b0-44fd-6f17a16a558f&j=8556562a-ae5f-5bd1-7c4d-bf1af4b6f1e1&t=9f016295-34d3-5b55-55cb-51df877e2cc6
Usage of `avdmanager` fails under JDK 11:
TestApks.targets(45,5): error : Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
TestApks.targets(45,5): error : 	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
TestApks.targets(45,5): error : 	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
TestApks.targets(45,5): error : 	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81) …
=> [ci] Use commandlinetools' avdmanager

Configuration.props, build-tools/scripts/Jar.targets, build-tools/scripts/JavaCallableWrappers.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in, src/java-runtime/java-runtime.targets, src/manifestmerger/build.gradle, src/manifestmerger/manifestmerger.targets, src/r8/build.gradle, src/r8/r8.targets
In order to support using JDK 11 to build Xamarin.Android, we need to
consistently use `javac -source 1.8 -target 1.8` ~everywhere, because
we also require `javac --boot-class-path`, and JDK11 doesn't support
`javac --boot-class-path` unless targeting < JDK 1.9:
% javac --boot-class-path ~/android-toolchain/sdk/platforms/android-29/android.jar Example.java
error: option --boot-class-path not allowed with target 11
The `<Javac/>` task use `javac --boot-class-path` to compile Java
code, so that Android's `android.jar` provides everything:
Task "Javac" (TaskId:154)
Task Parameter:JavaPlatformJarPath=/Users/runner/Library/Android/sdk/platforms/android-29/android.jar
Task Parameter:ClassesOutputDirectory=obj/Release/android/bin/class …
=> [build] JavacSourceVersion JavacTargetVersion Harmonization

build-tools/scripts/Paths.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
This makes the behavior match what we are doing for the
`$(AndroidSdkDirectory)` and `$(AndroidNdkDirectory)` properties.
Additionally, if `$(JavaSdkDirectory)` isn't set, try to use the
`JI_JAVA_HOME` and `JAVA_HOME` environment variables, to allow paths
to be reasonably overridden for test purposes.
=> [tests] set /p:JavaSdkDirectory for MSBuild tests

build-tools/scripts/JavaCallableWrappers.targets, src/Mono.Android/Mono.Android.csproj, src/OpenTK-1.0/OpenTK.csproj, src/java-runtime/java-runtime.csproj, src/java-runtime/java-runtime.targets, src/manifestmerger/manifestmerger.csproj
`dx` doesn't like OpenJDK 11 on Windows:
"C:\Users\dlab14\android-toolchain\sdk\build-tools\29.0.2\dx" --dex --no-strict --output="C:\A\vs2019xam00000H-1\_work\2\s\bin\Release\lib\xamarin.android\xbuild\Xamarin\Android\java_runtime.dex" "C:\A\vs2019xam00000H-1\_work\2\s\bin\Release\lib\xamarin.android\xbuild\Xamarin\Android\java_runtime.jar"
##[debug]Processed: ##vso[task.logdetail id=dffb25d4-cb0b-4e58-94d2-4b9a4f215bed;parentid=;name=EXEC;type=Build;starttime=2020-04-19T01:21:10.0332656Z;state=InProgress;]
##[error]EXEC(0,0): Error : No suitable Java found. In order to properly use the Android Developer
##[debug]Processed: ##vso[task.logissue type=Error;sourcepath=EXEC;linenumber=0;columnnumber=0;code=;]No suitable Java found. In order to properly use the Android Developer …
=> [java-runtime, build] Use r8.jar instead of dx

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
Context: https://build.azdo.io/3786371
We've been somewhat plagued by errors on Windows CI like:
TearDown : System.IO.IOException : The directory is not empty.
at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
at Xamarin.Android.Build.Tests.BaseTest.CleanupTest() in /Users/builder/azdo/_work/3/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs:line 445
The test *passed*, it just encountered an `IOException` attempting to
cleanup a temporary directory.
Let's catch `IOException` here and log the error instead. If this
occurs, we …
=> [tests] don't fail MSBuild tests if CleanupTest hits IOException

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Tooling.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.props, src/Xamarin.Android.Build.Tasks/Tasks/CalculateProjectDependencies.cs, src/Xamarin.Android.Build.Tasks/Tasks/Lint.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Tooling.targets
The Android SDK `lint` utility is now in *two* Android SDK packages:
the `tools` package, and the `cmdline-tools` package, e.g. as of commit
d99facb1, *both* of these exist on e.g. macOS:
* `$HOME/android-toolchain/sdk/tools/bin/lint`
* `$HOME/android-toolchain/sdk/cmdline-tools/1.0/bin/lint`
There are two important differences of interest:
1. `tools/bin/lint` will not run on OpenJDK 11.
2. `cmdline-tools/1.0/bin/lint` has a *lower version* than
`tools/bin/lint`.  *Much* lower:
% ~/android-toolchain/sdk/tools/bin/lint --version
lint: version 26.1.1
% ~/android-toolchain/sdk/cmdline-tools/1.0/bin/lint --version
lint: version 3.6.0
(1) means that we can't use the previous `lint` in an OpenJDK11 world,
and thus we should migrate …
=> [Xamarin.Android.Build.Tasks] Support cmdline-tools

src/Xamarin.Android.Build.Tasks/Tasks/CreateMultiDexMainDexClassList.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3729696&view=ms.vss-test-web.build-test-results-tab&runId=13228096&resultId=100066&paneView=attachments
`<CreateMultiDexMainDexClassList/>` fails under JDK11:
$ /Users/runner/Library/Android/jdk/bin/java \
-Djava.ext.dirs=/Users/runner/Library/Android/sdk/build-tools/29.0.2/lib \
com.android.multidex.MainDexListBuilder …
-Djava.ext.dirs=/Users/runner/Library/Android/sdk/build-tools/29.0.2/lib is not supported.  Use -classpath instead.
CREATEMULTIDEXMAINDEXCLASSLIST : error : Could not create the Java Virtual Machine.
CREATEMULTIDEXMAINDEXCLASSLIST : error : A fatal exception has occurred. Program will exit.
The command exited with code 1.
Under JDK11, `java` …
=> [Xamarin.Android.Build.Tasks] <CreateMultiDexMainDexClassList/> & JDK11

src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs, tests/CodeBehind/UnitTests/BuildTests.cs
The following import does not work when the tests run:
<Import
Condition="Exists('..\..\..\Configuration.props')"
Project="..\..\..\Configuration.props"
/>
`CodeBehindBuildTests.csproj` is copied to a directory, where it would
need to use this path:
..\..\..\..\..\..\..\Configuration.props
But the first path is correct, for when the project is built in-place
in `Xamarin.Android-Tests.sln`.
This path is getting too long... I think it is simpler to set
`$(TargetFrameworkVersion)` in the test, as we can use
`builder.LatestTargetFrameworkVersion ()`.
=> [tests] CodeBehindTests explicitly set $(TFV)

Documentation/guides/messages/README.md, Documentation/guides/messages/xa1011.md, Documentation/release-notes/reword-xa1011.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
Context: https://developercommunity.visualstudio.com/content/problem/1043110/xamarin-%E9%A1%B9%E7%9B%AE%E5%9C%A8vs165%E7%89%88%E6%9C%AC%E7%BC%96%E8%AF%91%E6%AD%A3%E5%B8%B8%E5%8D%87%E7%BA%A7%E5%88%B0vs166%E6%97%A0%E6%B3%95%E7%BC%96%E8%AF%91%E8%BF%90%E8%A1%8C.html
Seeing the localized version of the message for XA1011 in context from a
real user's build made @brendanzagaeski realize that the original
wording he wrote for that message was problematic.
One issue was that messages for Xamarin.Android build errors are not
currently accompanied by their numbered error codes when they appear in
the Error List in Visual Studio.  This means that users who see a
localized translation for a message will likely search online using the
localized text instead of the numbered code and will have a more …
=> [Xamarin.Android.Build.Tasks] Improve XA1011 error wording

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.D8.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.DX.targets
We have split up `$(AndroidDexTool)` implementations into:
* Xamarin.Android.D8.targets
* Xamarin.Android.DX.targets
We should move the `<UsingTask/>` declarations to these files as well.
There was also reference to a `Xamarin.Android.Tasks.Dx` task that
doesn't exist; I removed it.
=> [Xamarin.Android.Build.Tasks] move <UsingTask/> to where tasks are used

build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/net6-samples/pull/20
`xamarin-android` has been building / testing against .NET 5 Preview 6.
`libmono.a` was renamed to `libmonosgen-2.0.a` recently.
`xamarin-macios` depends on this name, and so `xamarin-macios`
requires .NET 5 Preview 7 now.
Update to `xamarin-android` to use .NET 5 Preview 7, so we can keep
both repos in sync.
=> [build] bump to .NET 5.0.100-preview.7.20307.3

Documentation/guides/DotNet5.md, build-tools/create-packs/Xamarin.Android.Sdk.Lite.proj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultItems.props, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultItems.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.props, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Xamarin.Android.Sdk.Lite.props, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Xamarin.Android.Sdk.Lite.targets
Context: https://github.com/xamarin/xamarin-macios/pull/8752
Reduces the amount of SDK / Target Framework Profile specific properties
which control default item inclusion behavior.  For now, we will only
have one property, $(EnableDefaultAndroidItems), which controls default
inclusion for all Android specific file types.
Default Android item inclusion behavior has been moved from a .props
to a .targets file for better consistency with xamarin-macios SDKs, and to
allow usage of the default value of `$(EnableDefaultItems)` which is set in
Microsoft.NET.Sdk.DefaultItems.targets.
$(DisableImplicitAndroidFrameworkReference) has also been removed as it
was only used by our "Lite" SDK, and we can explicitly remove the
Microsoft.Android @(FrameworkReference) from that SDK instead.
Finally, The …
=> [dotnet] Consolidate default item properties

Documentation/release-notes/4790.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/4790
If you change `$(AndroidSupportedAbis)` in the IDE and perform an
incremental build, you can hit:
[i686-linux-android-as.EXE stderr] Assembler messages:
[i686-linux-android-as.EXE stderr] Error: can't open typemaps.x86.s for reading: No such file or directory
Xamarin.Android.Common.targets(2245,3): error XA3006: Could not compile native assembly file: typemaps.x86.s
I was able to reproduce the issue in a test by using the `.csproj`:
<AndroidSupportedAbis>armeabi-v7a</AndroidSupportedAbis>
Then command-line pass a different ABI, such as:
-p:AndroidSupportedAbis=x86
`$(AndroidSupportedAbis)` needs to be listed in `build.props`, so that
changes to this value will trigger all MSBuild targets to run again.
In particular …
=> [Xamarin.Android.Build.Tasks] add $(AndroidSupportedAbis) to build.props

Documentation/guides/DotNet5.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Publish.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
Currently `dotnet publish` is incomplete; it uses the built-in behavior
in dotnet/sdk that copies all the managed assemblies to a `publish`
directory. Ideally an `.apk` or `.aab` should be the output instead?
For example:
> dotnet publish foo.android.csproj
This should copy any `.apk` files to `$(PublishDir)` and nothing else.
To achieve this, we need to declare our own minimal `Publish` target
that depends on:
Build;
PrepareForPublish;
CopyFilesToPublishDirectory;
We don't want *our* `Publish` target to run things like `ILLink`, AOT,
etc. because our `Build` target will be in charge of running those
build steps.
The current implementation in `Microsoft.Android.Sdk.Publish.targets`
is based on the `_CopyResolvedFilesToPublishPreserveNewest` target in
dotnet/sdk: …
=> [One .NET] updated implementation for 'dotnet publish'

tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
Context: https://build.azdo.io/3804575
Context: https://build.azdo.io/3804792
In 1f0e632b, I raised the times for a few tests, but I think we need
to raise them more:
Build_CSProj_Change
Exceeded expected time of 10200ms, actual 10293.371ms
Exceeded expected time of 10200ms, actual 10224.05ms
Build_From_Clean_DontIncludeRestore
Exceeded expected time of 10500ms, actual 10512.716ms
Build_JLO_Change
Exceeded expected time of 9600ms, actual 9780.282ms
Build_AndroidResource_Change
Exceeded expected time of 3000ms, actual 3004.573ms
Build_No_Changes
Exceeded expected time of 2000ms, actual 2004.638ms
I also suspect that the newer `aapt2` version bumped in cbdb5d15 could
be slightly slower, and that is why these have started failing. We
happened to get lucky (unlucky?) and #4794 was green.
If …
=> [tests] raise PerformanceTest times again

Documentation/guides/DotNet5.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Application.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
We currently have a `Run` target for .NET 6 projects:
<Target Name="Run" DependsOnTargets="Install;StartAndroidActivity" />
But the following command does not work:
> dotnet run --project HelloAndroid.csproj
It fails with:
Unable to run your project.
Ensure you have a runnable project type and ensure 'dotnet run' supports this project.
A runnable project should target a runnable TFM (for instance, net5.0) and have OutputType 'Exe'.
The current OutputType is 'Library'.
This occurs if `$(RunCommand)` is empty after MSBuild evaluation:
https://github.com/dotnet/sdk/blob/70cee0d6d445e332d3f926a66e7f4334cdca87e3/src/Cli/dotnet/commands/dotnet-run/RunCommand.cs#L203-L206
We can get our `Run` target hooked up to `dotnet run` by setting:
<RunCommand>dotnet</RunCommand>
<RunArguments>build …
=> [One .NET] initial implementation of 'dotnet run'

Documentation/release-notes/4805.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/4805
Context: https://github.com/xamarin/xamarin-android/issues/4664
There are still reports of `.resx` files not working inside IDEs...
65a917a9 was the original cause of this problem.
Unfortunately, the original problem in #4664 still occurs if the
`.resx` files are in the Xamarin.Android application project. The
original fix in d298fdaa, only solved the problem for missing
satellite assemblies in referenced projects.
Two missing targets need to run for `SignAndroidPackage` in IDE builds:
PrepareResources;
CreateSatelliteAssemblies;
These targets fill out the
`@(IntermediateSatelliteAssembliesWithTargetPath)` item group, that
contains all satellite assemblies for the current project.
In IDE builds, this item group was empty and …
=> [Xamarin.Android.Build.Tasks] fix IDE builds missing satellite assemblies in apps

Documentation/release-notes/incremental-linkdescription.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://developercommunity.visualstudio.com/content/problem/1061307/changes-not-applied-on-build-after-linker-configur.html
Changes to a `@(LinkDescription)` file did not trigger the
`_LinkAssembliesShrink` MSBuild target to run again.
The only way to see changes from this file was to `Rebuild` every time.
:eyes:
Adding a test for this scenario is also nice, as it didn't seem like
we had an MSBuild test verifying that `@(LinkDescription)` works in
general.
=> [Xamarin.Android.Build.Tasks] @(LinkDescription) should be in Inputs for the linker

Documentation/release-notes/4823.md
Changes: https://github.com/xamarin/java.interop/compare/76d1ac70ec740e1118678525b2e07f53ef53b622...1f3388af4897e6d8aca0e41c86ff02fa0ef4e67e
* xamarin/Java.Interop@1f3388a: [generator] Use proper syntax for nested classes for DIM invokers (#662)
* xamarin/Java.Interop@5e23163: [generator] Support XML defined enums with no JNI info (#659)
* xamarin/Java.Interop@5c4581d: [generator] Don't invalidate interface if static method is invalidated (#660)
* xamarin/Java.Interop@9687bb5: Bump to xamarin/xamarin-android-tools/d16-7@017078f2 (#658)
* xamarin/Java.Interop@abfade5: [Java.Interop] Fix C# warnings (#652)
* xamarin/Java.Interop@fb6d5f9: [Java.Interop.Tools.Generator] Specify $(OutputPath) (#650)
* xamarin/Java.Interop@a3f148c: [Xamarin.Android.Tools.Bytecode] Support @JvmOverloads (#651)
=> Bump to xamarin/Java.Interop/d16-7@1f3388af

Documentation/release-notes/4823.md, build-tools/installers/create-installers.targets
Changes: https://github.com/xamarin/Java.Interop/compare/b00e644e0d701114a6a1325c0b2ffe7a431e3d48...1de5501b2d49df3d8d3b187df026d611996a67da
* xamarin/Java.Interop@1de5501: [CI] Add an "macOS .NET Core" build (#655)
* xamarin/Java.Interop@9a56465: [generator] Use proper syntax for nested classes for DIM invokers (#662)
* xamarin/Java.Interop@267c3f3: [generator] Support XML defined enums with no JNI info (#659)
* xamarin/Java.Interop@5dcf896: [generator] Don't invalidate interface if static method is invalidated (#660)
* xamarin/Java.Interop@1b59dcc: [java-interop] Update to SDK style project (#657)
* xamarin/Java.Interop@b136ac9: [param-name-importer] Bump to Microsoft.Xml.SgmlReader 1.8.16 (#656)
* xamarin/Java.Interop@eb39a3a: Bump to xamarin/xamarin-android-tools/master@3974fc38 …
=> Bump to xamarin/Java.Interop/master@1de5501b

src/Xamarin.Android.Build.Tasks/Resources/NOTICE.txt, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/BundleToolTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Aot.apkdesc, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Bundle.apkdesc, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Profiled-Aot.apkdesc, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release.apkdesc
Context: https://github.com/xamarin/xamarin-macios/issues/8849
Context: https://github.com/xamarin/xamarin-macios/pull/8857
Long ago it was decided that all created `.apk` and `.aab` packages
should contain a `NOTICE` file, which stated:
> Xamarin built applications contain open source software.
> For detailed attribution and licensing notices, please visit:
>
> 	http://xamarin.com/mobile-licensing
In the meantime, the world has moved on, and the above URL has
bitrotten, and is thus meaningless.
Additionally, we have gotten updated guidance that we don't need to
emit such a file anymore.
Instead of fixing the above URL, remove the `NOTICE` file.
This will be less work for everyone. 😏
If one *really* wants to know what 3rd party open-source software is
being redistributed, please see the …
=> [Xamarin.Android.Build.Tasks] Don't create NOTICE in App packages

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallJetBrainsOpenJDK.cs
Now that we install JetBrains OpenJDK in two, versioned, directories, it
makes sense to get rid of the old Corretto directory if found so that
we're sure we always use one of the JetBrains OpenJDK versions.
=> [xaprepare] Nuke $(AndroidToolchainDirectory)/jdk if found

.external, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateCompressedAssembliesNativeSourceFiles.cs, src/Xamarin.Android.Build.Tasks/Utilities/CompressedAssemblyInfo.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: d236af54538ef1fe62d0125798cdde78e46dcd8e
d236af54 introduced assembly compression and one part of the process is
to gather information about the size of all the assemblies to be
packaged with the application, in order to generate native assembly code
which pre-allocates memory for them.  To do that, the native runtime must
be sure that the the assembly being currently decompressed will fit in
the pre-allocated memory area and thus it stores the original file size
both in the compressed assembly header and in the generated native
assembler source (compiled into `libxamarin-app.so`).  If the sizes
mismatch, we will see an error in the logcat similar to:
F/monodroid-assembly(11348): Compressed assembly 'mscorlib.dll' is larger than when the application was built (expected at most …
=> [compression] Store assembly information with unique key

src/monodroid/jni/embedded-assemblies.cc
Fixes: https://github.com/xamarin/xamarin-android/issues/4791
Make a couple of messages related to MVID use `log_info` instead of
`log_warn` so that they are not shown by default (even though they are
useful for diagnostic purposes)
=> [runtime] Downgrade some typemap message severity

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml
There have been a few issues involving Android builds on Windows involving problems with the VS installation or an incorrect (older) version of MSBuild being invoked. This build step provides visibility into the VS and MSBuild installations installed on the windows build agent. It utilizes `vswhere` as a means to enumerate and obtain the VS installations on the agent. Additionally, the template being called leverages code from the MSBuild task to locate the version of MSBuild that will be used.
=> [build, win] Display (log) VS and MSBuild installation details for win_build_test stage

Configuration.props, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.csproj, tests/EmbeddedDSOs/EmbeddedDSO/EmbeddedDSO.csproj
Fix "in-tree" usage of `$(AdbToolPath)` for projects which import
`Configuration.props`, e.g.
> cd samples/HelloWorld
> msbuild /t:Install
> msbuild /t:StartAndroidActivity
…
StartAndroidActivity:
PackageName: com.xamarin.android.helloworld
"…/android-toolchain/sdk/platform-toolsadb"  shell am start -n "com.xamarin.android.helloworld/example.MainActivity"
/var/folders/j4/t8z2dw2d7pndmvwcxz71njf40000gn/T/tmp04a537baf06445baa371ef57689ad833.exec.cmd: line 2: …/android-toolchain/sdk/platform-toolsadb: No such file or directory
…/Xamarin.Android.Application.targets(27,5): error MSB3073: The command ""…/android-toolchain/sdk/platform-toolsadb"  shell am start -n "com.xamarin.android.helloworld/example.MainActivity"" exited with code 127.
Done Building Project …
=> [build] Fix local $(AdbToolPath)

src/Mono.Android/Android.Runtime/AndroidEnvironment.cs, src/Mono.Android/Android.Runtime/JNIEnv.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/4632
The `UNHANDLED EXCEPTION` message was printed from
`AndroidEnvironment.UnhandledException()`, which is invoked during
exception propagation, at each Managed::Java VM boundary.
It need not be from an *actual* unhandled exception!
Consequently, if there is a Managed :: Java :: Managed stack frame,
and *either* the 1st Managed or the Java frames catch the exception
thrown from the 2nd Managed frame -- meaning the exception is in fact
handled! -- we would still "spam" `adb logcat` with
`UNHANDLED EXCEPTION` messages, because at the "scope" in which it's
emitted, it can't know whether or not it's *actually* unhandled.
To avoid spamming `adb logcat` with unecessary noise, move the
`UNHANDLED EXCEPTION` log message into …
=> [Mono.Android] Only log *actual* unhandled exceptions

src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/4809
Context: 7117414ca27d88a71b4a272705a0207f772423bd
Context: a017561b1e44c51a9af79fae0baaa50fe01c4123
Part of the a017561b commit dealt with mappings from certain Java types
which point to the same Managed type by making sure that they all refer
to the same type definition and managed type name.  However, in doing so
it failed to synchronize the property which indicates that we are
dealing with an interface or generic type, in which case such a type
should be ignored by the type mapping code in the runtime.
In this particular case, the issue was with the `ArrayAdapter` type
which has both a generic and non-generic definitions and it so happens
that the *first* type in `Mono.Android` assembly is the generic one,
thus it, and its …
=> [typemap] Handle duplicates of generic types properly

build-tools/automation/azure-pipelines.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3827329&view=logs&j=051336c7-58fc-58df-2c99-9295b706a641&t=20716647-8442-5250-dfa5-2cf363e96f19
The designer tests have been failing to build with:
Xamarin.Designer.iOS/external/ios-sim-sharp/MonoTouch.Hosting/MonoTouch.Hosting.csproj(163,5): error MSB3073:
The command "unset XCODE_DEVELOPER_DIR_PATH && xcodebuild -workspace libspawnapp.xcworkspace -scheme libspawnapp -configuration Debug -destination 'generic/platform=iOS Simulator' -derivedDataPath ." exited with code 65.
We think this could be fixed by using the agent pool running macOS
10.14.
=> [build] run designer tests on $(HostedMacMojave)

Documentation/release-notes/4818.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/4818
Use of Hybrid AOT currently results in assemblies that have not been
CIL-stripped.
In 77ab2404, a change was made to fix how `Mono.Android.dll` was
treated during AOT. `Mono.Android.dll` used to be the only assembly
copied to the `shrunk` directory, and we had two copies of the this
assembly passed to the AOT compiler. This change unintentionally made
`<CilStrip/>` strip the wrong set of assemblies...
The initial fix would be:
<CilStrip
...
-   ResolvedAssemblies="@(_ResolvedAssemblies)">
+   ResolvedAssemblies="@(_ShrunkAssemblies)">
Unfortunately, this causes a crash:
06-11 16:19:08.557 E/AndroidRuntime(18806): java.lang.UnsatisfiedLinkError: No implementation found for void …
=> [Xamarin.Android.Build.Tasks] fix <CilStrip/> for Hybrid AOT

Documentation/release-notes/api30-queries.md, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs, src/manifestmerger/build.gradle
Context: https://developer.android.com/preview/privacy/package-visibility#package-name
If using Fast Deployment with an API 30 device or emulator and
`targetSdkVersion="30"`, the app will crash on startup with:
06-18 09:40:54.530   557   853 I AppsFilter: interaction: PackageSetting{f346c3d com.companyname.app72/10152} -> PackageSetting{67adc32 Mono.Android.Platform.ApiLevel_30/10151} BLOCKED
...
06-18 09:40:54.531  8624  8624 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider mono.MonoRuntimeProvider: java.lang.RuntimeException: Unable to find application Mono.Android.Platform.ApiLevel_30!
06-18 09:40:54.531  8624  8624 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:7135)
06-18 09:40:54.531  8624  8624 E AndroidRuntime: …
=> [Xamarin.Android.Build.Tasks] add //manifest/queries for API 30

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
Context: https://github.com/xamarin/monodroid/pull/1101
Context: https://build.azdo.io/3823945
The monodroid build is failing with:
create-pkg.targets(34,5): error MSB3030: Could not copy the file "/Users/builder/azdo/_work/2/s/external/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/System.Collections.Immutable.dll" because it was not found.
0 Warning(s)
1 Error(s)
We added this file to `create-installers.targets` in 2f677ef, because
it is needed for the new "delta install" support.
However, there is an issue depending on the ordering of how things are
built. If `Xamarin.Android.Build.Tasks.csproj` is built *last*, it
will `ILMerge `this assembly and delete it.
Let's not delete the ILMerge'd assemblies. This may solve the problem.
=> [Xamarin.Android.Build.Tasks] don't delete ILMerge'd assemblies

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/xamarin-android/pull/4635
In https://github.com/xamarin/xamarin-android/pull/4635 we changed our `push nupkgs` step to fire on every build where `Build.Reason != PullRequest`, however this causes problems when doing manual builds run the AzDO UI, because the `Build.Reason` is `Manual`.  This causes the step to run, and running it more than once fails the build with:
```
Response status code does not indicate success: 409 (Conflict - The feed already contains 
'Microsoft.Android.Ref 10.0.100-ci.qa-test.113+sha.003be50'.
```
There is no way to opt out of this behavior because `Build.Reason` is OR'd with `variables['PushXAPackages']`, so setting `PushXAPackages` to `false` is ignored.
This PR changes the behavior to rely solely on …
=> [CI] Only push NET5 pkgs when PushXAPackages is true.

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/AssertionExtensions.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownTargets.cs
When running under .NET 5+, the `ILLink` MSBuild target runs the
linker. A lot of our MSBuild tests check for the
`_LinkAssembliesShrink` target, and so they currently fail.
To fix this, and improve things:
* Add a `KnownTargets` class similar to the `KnownProperties` class we
already have.
* Add a property that conditionally returns `ILLink` or
`_LinkAssembliesShrink`.
* Add an `AssertionExtensions` class to check if targets are skipped
or not with less code.
* Cleanup any tests using `_LinkAssembliesShrink` to use the new
helpers.
Any tests I changed were added to the `dotnet` category.
=> [tests] fixes for ILLink vs _LinkAssembliesShrink

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Context: https://build.azdo.io/3834197
Frequently, the `MSBuild - Mac 1` test phase hangs and just times out.
A log was showing:
Task "R8" (TaskId:191)
...
processing ClassesZip, JavaLibrariesToEmbed... (TaskId:191)
/Users/runner/Library/Android/jdk-11/bin/java -Xmx64m -classpath /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/r8.jar com.android.tools.r8.R8 --debug --min-api 16 --output obj/Debug/android/bin/ --lib /Users/runner/Library/Android/sdk/platforms/android-30/android.jar obj/Debug/android/bin/classes.zip /Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v11.0/mono.android.jar /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/java_runtime_fastdev.jar …
=> [tests] remove XA5213IsRaisedWhenOutOfMemoryErrorIsThrown

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
We have enabled nullable reference types (NRT) for `Mono.Android.dll`, and `Xamarin.Android.Build.Tasks.dll` imports several source files from MA like `IntentFilterAttribute.cs`.
Because `Xamarin.Android.Build.Tasks.csproj` does not enable NRT this results in 100+ warnings like:
```
src\Mono.Android\Android.App\IntentFilterAttribute.cs(28,16): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
```
The easiest fix is to simply ignore this warning until XABT enables NRT.
=> [Xamarin.Android.Build.Tasks] Ignore CS8632 warning about using NRT annotations without enabling NRT.

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
Context: https://github.com/android/ndk/wiki/Changelog-r21#r21d
Changes:
* Added APIs for Android 11:
* New [ImageDecoder][0] API.
* New [Thermal][1] API.
* Updated [AAudio][2] APIs.
* Updated [Bitmap][3] APIs.
* Updated [Camera][4] APIs.
* Updated [Choreographer][5] APIs.
* Updated [Native Window][6] APIs.
* Updated [NdkBinder][7] APIs.
* Updated [NeuralNetworks][8] APIs.
* OpenSLES is deprecated in favor of [AAudio][2]. Developers should use [Oboe][9] to automatically select the best available API.
[0]: https://developer.android.com/ndk/reference/group/image-decoder
[1]: https://developer.android.com/ndk/reference/group/thermal
[2]: https://developer.android.com/ndk/reference/group/audio
[3]: https://developer.android.com/ndk/reference/group/bitmap
[4]: …
=> Bump Android NDK to r21d

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Linker.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownTargets.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidBindingProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidCommonProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsAndroidApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsXASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetXamarinProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
When running `dotnet build` and setting `IsRelease=true` in our
MSBuild tests, the current MSBuild tests generate `.csproj` files such
as:
<Project Sdk="Microsoft.Android.Sdk">
<Configuration>Release</Configuration>
The problem with this is how the ordering of imports work in SDK-style
projects:
1. Any `Directory.Build.props` are imported.
2. The SDK targets are imported, such as:
https://github.com/dotnet/sdk/blob/b7c7f33aa44b23dc1f984a9a1162ee2d57439897/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props#L39-L45
3. The `.csproj` is imported.
The result, is even though `Configuration=Release` in this project,
some defaults are set such as `Optimize=False` and `DebugSymbols=True`.
This works for legacy projects because
`Xamarin.Android.CSharp.targets` is …
=> [Xamarin.ProjectTools] use Directory.Build.props for $(Configuration)

Documentation/release-notes/Issue4804.md, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/JarContentBuilder.cs
Fixes https://github.com/xamarin/xamarin-android/issues/4804
We were overwriting the AndroidManifest.xml file in the apk with
ones from Support Libraries. This manifests itself with the following error
```
Failed to parse APK info: failed to parse AndroidManifest.xml, error: %!s()
deploy failed, error: failed to get apk infos, output: W/ResourceType( 5266): Bad XML block: 
```
This commit fixes this issue by ignoring files from .jar files
which already exist in the apk. This stops things from being
overwritten. A test has also been added.
=> [Xamarin.Android.Build.Tasks] Wrong AndroidManifest.xml packaged to the APK while using binding library

tests/BCL-Tests/Xamarin.Android.Bcl-Tests/nunit-excluded-tests.txt
`Android 11` / `API 30` made the `memfd_create(2)` Linux-specific API
fail whenever the `MFD_CLOEXEC | MFD_ALLOW_SEALING` combination of flags
is passed to it:
Xamarin.Android.Bcl_Tests, MonoTests.Mono.Unix.Native.MemfdTest.TestMemfd / Release
System.ArgumentOutOfRangeException : Current platform doesn't support this value.
Parameter name: value
Actual value was MFD_CLOEXEC, MFD_ALLOW_SEALING.
Disable the test altogether, since this API isn't used by
`Xamarin.Android` and any applications using it will/should check the
`errno` variable for the `ENOSYS` value to see if the API is supported
or not.  This will unblock us, allowing update of our Android emulator
system image to API 30.
=> [tests] Disable a Mono.Posix test

src/Mono.Android/Test/System.Net/NetworkInterfaces.cs
Context: https://developer.android.com/preview/behavior-changes-11#netlink-mac
Context: https://developer.android.com/reference/java/net/NetworkInterface#getNetworkInterfaces()
If an application targets `Android 11`/`API 30` (and newer) then the
number of reported interfaces as well as the amount of information about
them change to include less detail.
First of all, only interfaces with associated IP addresses will be
reported by both the `NetworkInterface` Java API and the `getifaddrs(3)`
native libc API:
* Application targetting API 28 on API 30 device:
* name: wlan0; type: Ethernet
* name: dummy0; type: Ethernet
* name: lo; type: Loopback
* name: hwsim0; type: Unknown
* name: ip6tnl0; type: Tunnel
* name: sit0; type: Tunnel
* name: ip6_vti0; type: Tunnel
* name: ip_vti0; type: Tunnel
* …
=> [tests] Fix network interface tests for Android 30

.external, .vscode/launch.json, .vscode/settings.json, Configuration.props, build-tools/automation/azure-pipelines.yaml, build-tools/scripts/NUnitReferences.projitems, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, tests/CodeBehind/UnitTests/CodeBehindUnitTests.csproj, tests/CodeBehind/UnitTests/run.sh, tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/Xamarin.Android.MakeBundle-UnitTests.csproj, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/EmbeddedDSO-UnitTests.csproj, tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/run.sh, tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj
Update to:
* NUnit 3.12.0
* NUnit.ConsoleRunner 3.11.1
* NUnit3TestAdapter 3.16.1
These are all different numbers, but these are the latest stable
versions on nuget.org.
I also went ahead and consolidated all NUnit `@(PackageReference)` to
a `NUnitReferences.projitems` file. This way we can list the versions
for all NUnit packages in one MSBuild file.
NUnit.ConsoleRunner was still listed in a few other files we will have
to manually update.
Bump to xamarin/monodroid/master@82bea9c6
Changes: https://github.com/xamarin/monodroid/compare/6e43a20e...82bea9c6
=> [tests] update and consolidate NUnit packages

Documentation/release-notes/xa0119-aab-err.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://developercommunity.visualstudio.com/content/problem/1076396/fatal-signal-11-sigsegv-code-1-segv-maperr-fault-a.html
Context: https://github.com/xamarin/xamarin-android/issues/4071#issuecomment-625589592
Context: https://forums.xamarin.com/discussion/comment/414288/#Comment_414288
A few reports have come in from users about the crashes that happen when
`$(AndroidPackageFormat)`=`aab` in the Debug configuration.
There was already a build warning for this scenario, but since it is
known that this scenario currently produces a crash, change that warning
to an error to improve the visibility of the known limitation and save
users time.
Example of the current crash:
D Mono    : DllImport attempting to load: '__Internal'.
D Mono    : DllImport error loading library '__Internal': …
=> [Xamarin.Android.Build.Tasks] Make XA0119 an error for App Bundles in Debug

src/Mono.Android/Android.Runtime/JNINativeWrapper.cs, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets, tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs
If you tried to debug an app with:
dotnet build HelloAndroid/HelloAndroid.csproj -t:Install,_Run -p:AndroidAttachDebugger=true
The presence of `$(AndroidAttachDebugger)` causes a crash on startup:
06-24 11:57:42.538 14948 14948 E mono    : Unhandled Exception:
06-24 11:57:42.538 14948 14948 E mono    : System.ArgumentNullException: Value cannot be null. (Parameter 'meth')
06-24 11:57:42.538 14948 14948 E mono    :    at System.Reflection.Emit.ILGenerator.Emit(OpCode opcode, MethodInfo meth)
06-24 11:57:42.538 14948 14948 E mono    :    at Android.Runtime.JNINativeWrapper.CreateDelegate(Delegate dlg)
06-24 11:57:42.538 14948 14948 E mono    :    at Android.App.Activity.GetOnCreate_Landroid_os_Bundle_Handler()
06-24 11:57:42.538 14948 14948 E mono    :    at …
=> [One .NET] fix debugging

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Application.targets, tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs
Context: https://github.com/xamarin/monodroid/blob/6e43a20ebaa2cd59532e130ef64585c5829e3373/tools/msbuild/Xamarin.Android.Common.Debugging.targets#L510-L528
In the commercial Xamarin.Android project, there is a `_Run` MSBuild
target that launches apps as well as configures debugging.
We should conditionally use this target for the public `Run` target in
.NET 5+, so you could attach a debugging session via:
> dotnet build HelloAndroid/HelloAndroid.csproj -t:Run -p:AndroidAttachDebugger=true
Unfortunately, you can't add additional MSBuild properties to `dotnet
run`, so this command would not work:
> dotnet run --project HelloAndroid/HelloAndroid.csproj -p:AndroidAttachDebugger=true
MSBUILD : error MSB1008: Only one project can be specified.
Switch: AndroidAttachDebugger=true
For switch …
=> [One .NET] add debugging support for Run target

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.props, src/Xamarin.Android.Build.Tasks/Tasks/Legacy/ValidateJavaVersion.cs, src/Xamarin.Android.Build.Tasks/Tasks/ValidateJavaVersion.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
Fixes: https://github.com/xamarin/xamarin-android/issues/4853
Context: https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime
Using JDK 11.0.7, builds currently fail with:
error XA0030: Building with JDK version `11.0.7` is not supported. Please install JDK version `11.0.4`. See https://aka.ms/xamarin/jdk9-errors
We could set `$(LatestSupportedJavaVersion)` to `11.0.7` to allow this
version to work, but it is not future-proof.
So if we used `11.0.99`, this would allow Xamarin.Android to continue
to work with minor JDK bumps if 11.0.8 happened to come out tomorrow.
Unfortunately, this makes the error message bad:
error XA0030: Building with JDK version `14.0.0` is not supported. Please install JDK version `11.0.99`.
I updated the `<ValidateJavaVersion/>` MSBuild task, so that only …
=> [Xamarin.Android.Build.Tasks] support JDK 11.0.7

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ConvertResourcesCasesTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ZipArchiveExTests.cs
Context: https://build.azdo.io/3845868
Some tests have been randomly failing such as:
SkipExistingFile_TimeStamp
TearDown : System.IO.IOException : The directory is not empty
--TearDown
at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
at Xamarin.Android.Build.Tests.ZipArchiveExTests.TearDown() in /Users/builder/azdo/_work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ZipArchiveExTests.cs:line 40
Or another example:
Xamarin.Android.Build.Tests.ConvertResourcesCasesTests.CheckCla …
=> [tests] ignore IOException in some MSBuild tests

src/Mono.Android/Android.Runtime/JNIEnv.cs
Context: https://github.com/dotnet/runtime/issues/38465
Both of these methods are missing in .NET 5+:
* `System.Diagnostics.Debugger.Mono_UnhandledException`
* `AppDomain.CurrentDomain.DoUnhandledException`
The code path that runs during an unhandled exception relies on these
methods. Currently, an unhandled exception will throw several additional
exceptions we should fix:
Unable to initialize UncaughtExceptionHandler. Nested exception caught: System.ArgumentNullException: Value cannot be null. (Parameter 'method')
at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
at System.Delegate.CreateDelegate(Type type, MethodInfo method, Boolean throwOnBindFailure)
at System.Delegate.CreateDelegate(Type type, …
=> [One .NET] fix code path for unhandled exceptions

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Linker.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
When using r8 or ProGuard in .NET 5, `proguard_project_references.cfg`
or `$(_ProguardProjectConfiguration)` was not being generated. It
turns out that the `$(_ProguardProjectConfiguration)` MSBuild property
was completely blank.
`$(_ProguardProjectConfiguration)` is used when deciding if
r8/ProGuard need to run such as:
https://github.com/xamarin/xamarin-android/blob/a944a8923c0f5e782af308525a3e99ebc2470fe8/src/Xamarin.Android.Build.Tasks/Xamarin.Android.D8.targets#L28
The way the inner/outer builds work in .NET 5+, we need to set
`$(_ProguardProjectConfiguration)` from the outer build and pass it
through to the inner build running the `ILLink` MSBuild target.
After this fix, I could enable the `BuildProguardEnabledProject` test
under .NET 5. The only thing to note is that the …
=> [Microsoft.Android.Sdk] fixes for ILLink and @(ProguardConfiguration)

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.props, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EnvironmentContentTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Utilities/ProjectExtensions.cs
I noticed that if you define `<AndroidLinkMode>Full</AndroidLinkMode>`
in a `.csproj` file, the `ILLink` MSBuild target did not run.
It turns out that we were setting `$(PublishTrimmed)` by default too
early. If set in `Microsoft.Android.Sdk.props`, this is evaluated
before the user's `.csproj` file. If we set this in
`Microsoft.Android.Sdk.targets`, then we can rely on values set in the
`.csproj` file.
I found a test that was failing due to this issue and added it to the
`dotnet` category. I made a couple other changes to the test so it
passed under .NET 5+:
* Test against `FormsViewGroup.dll` instead of a support library, so
the test still passes if using AndroidX libraries.
* Use `$(RuntimeIdentifiers)` over `$(AndroidSupportedAbis)`. I added
a new helper method for multiple RIDs.
=> [Microsoft.Android.Sdk] set $(PublishTrimmed) after .csproj evaluated

build-tools/automation/PoliCheckExclusions.xml, build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/yaml-templates/pull/42
PoliCheck has been added to our code analysis job.  Initial results from
running this tool reported 27 failures, which are all present in
external sources and have been added to an exclusion list.
All code anaylsis steps and reporting for the xamarin-android pipeline
previously lived in yet another template (xa-static-analysis/v2.yml),
but the content of that file is no longer well suited for a template.
Rather than creating another version of this template in the
yaml-templates repo, the core logic has been moved here.
=> Run policheck as part of code analysis job

build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
In order to ensure that both xamarin.android and the sdk installer
use the same version number we are now using the `Xamarin.Android.Tools.Versions.props`
file. This file is maintained in the xamarin-android-tools repo and
will be imported via `external/xamarin-android-tools`. The file
is imported in `Xamarin.Android.Common.props`.
=> [Xamarin.Android.Build.Tools] Import the new Xamarin.Android.Tools.Versions.props file.

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
Running under .NET 5+, the `AndroidResourceChange` test would always
fail with:
The target _ResolveLibraryProjectImports should have been skipped.
It turns out our test infrastructure was deleting `NuGet.config` on
incremental builds. This triggers the `Restore` target to do its work
again on every build changing `$(ProjectAssetsFile)`. This is an input
of `_ResolveLibraryProjectImports`:
<Target Name="_ResolveLibraryProjectImports"
Inputs="$(ProjectAssetsFile)...
We shouldn't ever delete `NuGet.config` files during MSBuild tests.
This allowed the test to pass, and we can now run it under `dotnet`.
The same was happening for `build.log`, `msbuild.binlog`, and
`process.log`, so I thought it would be good to skip deletion of
`.log` or `.binlog` files.
I also cleaned up the test a little to …
=> [tests] don't delete NuGet.config files during MSBuild tests

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EnvironmentContentTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Utilities/ProjectExtensions.cs
Context: https://github.com/xamarin/xamarin-android/blob/792d61d116cc0293bd457d1c418d1972829ec226/Documentation/guides/MSBuildBestPractices.md#filewrites-and-incrementalclean
Running under `dotnet`, a test is failing with:
GenerateJavaStubsAndAssembly(True)
android\environment.armeabi-v7a.o is not in FileWrites!
Expected: some item equal to "C:\A_work\1\s\bin\TestRelease\temp\GenerateJavaStubsAndAssemblyTrue\obj\Release\android\environment.armeabi-v7a.o"
When I authored `Microsoft.Android.Sdk.BuildOrder.targets`, I didn't
bring over the workaround to make `IncrementalClean` and `FileWrites`
work appropriately:
<CoreBuildDependsOn>
$([MSBuild]::Unescape($(CoreBuildDependsOn.Replace('IncrementalClean;', '$(_BeforeIncrementalClean);IncrementalClean;'))))
</CoreBuildDependsOn>
It appears this …
=> [One .NET] fixes for IncrementalClean and FileWrites

build-tools/xaprepare/xaprepare/ThirdPartyNotices/dlfcn.cs, build-tools/xaprepare/xaprepare/ThirdPartyNotices/witwall_mman.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj
`external/dlfcn-win32` and `external/mman-win32` were added in
commit d8fdbcfc, but we accidentally overlooked that the content of
these submodules was included into built binary artifacts, and
redistributed via our installers.'
Consequently, these resources *should* have been listed in the
generated `ThirdPartyNotices.txt` which is included in the installers,
but they were not.
Add appropriate `ThirdPartyNotices.txt` entries for
[dlfcn-win32/dlfcn-win32][0] and [witwall/mman-win32][1].
[0]: https://github.com/dlfcn-win32/dlfcn-win32
[1]: https://github.com/witwall/mman-win32
=> [xaprepare] Emit ThirdPartyNotices entries for mman, dlfcn

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
The `XA0119` test was failing under a `dotnet` context:
(_BuildApkEmbed target) ->
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\A\_work\1\s\bin\TestRelease\temp\XA0119\obj\Debug\linked\shrunk\UnnamedProject.dll'.
at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at Xamarin.Android.Tasks.MonoAndroidHelper.IsReferenceAssembly(String assembly)
at Xamarin.Android.Tasks.BuildApk.AddAssemblies(ZipArchiveEx apk, Boolean debug, Boolean compress, IDictionary`2 compressedAssembliesInfo)
at …
=> [Microsoft.Android.Sdk] fix $(AndroidUseSharedRuntime) w/ linker

Documentation/guides/DotNet5.md, Documentation/guides/messages/README.md, Documentation/guides/messages/xa4312.md, Documentation/release-notes/wear.md, build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Wear.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/WearTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidWearApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
Context: https://developer.android.com/training/wearables/apps/standalone-apps
Going forward in .NET 5+, we will be dropping support for embedding
Android Wear applications inside a "main" application.
From a `Foo.Android.csproj` you can:
<ProjectReference Include="..\Foo.Wear\Foo.Wear.csproj">
<Name>Wearable</Name>
<IsAppExtension>True</IsAppExtension>
<ReferenceOutputAssembly>False</ReferenceOutputAssembly>
</ProjectReference>
This would embed `com.foo.wear.apk` *inside* `com.foo.android.apk` in
`Resources/raw`.
We are removing this functionality, because it is not widely used. You
can distribute Android Wear as standalone applications since Android
Wear 2.0, so this should be the option going forward. I added a new
`XA4312` warning to be emitted for projects using this feature.
I moved …
=> [Xamarin.Android.Build.Tasks] deprecate %(ProjectReference.IsAppExtension)

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EnvironmentContentTests.cs
These tests relied on the default value for the
`$(AndroidHttpClientHandlerType)` and `$(AndroidEnableSGenConcurrent)`
MSBuild properties.
The default values change in .NET 5+, so I think these tests can just
set these MSBuild properties explicitly instead of relying on the
default value at all.
I also found the `CheckMonoDebugIsAddedToEnvironment` test worked, so
I added it to the `dotnet` category.
I also did some general test cleanup.
=> [tests] fixes for EnvironmentContentTests under dotnet

Directory.Build.props, Documentation/README.md, Documentation/guides/OneDotNet.md, Documentation/guides/messages/README.md, Documentation/guides/messages/xa1024.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
Running under .NET 5+, the `BuildBasicApplicationCheckConfigFiles`
test fails with:
UnnamedProject.dll.config was must be copied to Intermediate directory
Expected: True
But was: False
After review, it doesn't seem like Xamarin.Android needs to support
`.dll.config` files in .NET 5+ at all.
1. `<dllmap>` is not supported. It was a feature of Mono.
2. `appSettings` only work via a compat NuGet package:
```xml
<PackageReference Include="System.Configuration.ConfigurationManager" Version="4.7.0" />
```
This NuGet package does not work in the current Xamarin.Android
(throws `PlatformNotSupportedException`), and there is no other
mechanism to support `appSettings`.
Any MSBuild targets related to `.config` files have been moved to
`Xamarin.Android.Legacy.targets`.
I added `XA1024` to warn going …
=> [One .NET] exclude MSBuild targets for .dll.config files

build-tools/automation/azure-pipelines.yaml
Context: https://www.1eswiki.com/wiki/AntiMalware_Scan_Build_Task
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1139581
Adds the Anti-Malware Scan build task to our code analysis job.  This
tool uses Windows Defender to scan the specified folder for malware,
and will ensure that we don't check any offending binaries into source
control.
=> [ci] Add Anti-Malware Scan to code analysis job

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/clean.yaml, build-tools/automation/yaml-templates/kill-processes.yaml, build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml
A new [Virtual machine scale set][0] has been created for our Windows
build and test jobs.  This new pool should improve Windows queue times,
as it will automatically scale up and down based on demand.  The agent
pool is currently configured to scale between 3-12 machines.  This range
is set in the [agent pool settings][1] and can easily be changed to meet
future changes in demand.
The new agent pool will also give us greater control over the VMs and
machine images used for build and test.  This pool can be configured to
have every job spin up a fresh VM, and will generally shut down older
instances and create fresh ones as it scales with demand.  This
functionality should help alleviate some of the issues we've seen on our
static machine pool related to file permissions and Visual Studio …
=> [ci] Use new scaling VM pool for Windows build and test jobs

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EnvironmentContentTests.cs
Context: https://build.azdo.io/3890818
This test seems to be consistently failing on macOS with:
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(124,5): error :
Could not find file '/Users/runner/work/1/s/packages/xamarin.android.support.transition/28.0.0.1/nvzgjsmt.a6m'.
We've generally just added `[NonParallelizable]` for tests hitting
this in the past to work around it.
=> [tests] BuildApplicationWithMonoEnvironment is [NonParallelizable]

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/apk-instrumentation.yaml, build-tools/automation/yaml-templates/run-timezoneinfo-tests.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3893162&view=logs&j=cac0e8d3-0ef5-5d2b-b57e-e8fde7204df3&t=ecb52562-b867-5d86-aae7-56a38766a1ce&l=170
The Java.Interop test step has recently started failing on our Windows
builds due to a strange error which seems to indicate that there is an
extra new line character in an invalid location.  I believe that this
has to do with the `>` character we're using to allow for blocks of
strings in various places.  Updating this to `>-` should hopefully trim
any trailing new lines that aren't intended according to this resource
for YAML multi-line string syntax https://yaml-multiline.info/.
=> [ci] Trim new line from multi-line MSBuild arguments

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/AssemblyCompression.cs
Context: d236af54538ef1fe62d0125798cdde78e46dcd8e
Commit d236af54 introduced assembly compression for `Release` builds
with compression output placed in the same directory where the original
assembly resides.  This works well if the linker is enabled for the
project, because all the assemblies are copied to the `obj/` directory,
but if the linker is disabled, some assemblies will be read from their
original path, possibly a system location which is NOT writable by
non-root/non-admin processes.
This commit moves the compressed output location to a subdirectory of
the `obj/` directory for all the input assemblies.
=> [build] Fix compression of assemblies in unwritable directories

Documentation/guides/OneDotNet.md, Documentation/guides/messages/xa1023.md, build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://android-developers.googleblog.com/2020/02/the-path-to-dx-deprecation.html
On February 1, 2021 DX will be removed from the Android SDK. It is
very possible this will happen before .NET 6 ships. There are also
currently a few MSBuild tests that fail when using DX.
* Drop support for DX in .NET 5+. Emit `XA1023` as an *error*.
* Don't even include `Xamarin.Android.DX.targets` in .NET 5+ packages.
* Add several tests to the `dotnet` category.
* Any tests using `AndroidDexTool=dx` will be ignored.
I left the `PackagingTest.CheckClassesDexIsIncluded` test so that it
verifies you get an `XA1023` build error when using DX with .NET 5+.
Other changes:
* There were some related warning messages that I moved to the
`_CheckNonIdealConfigurations` MSBuild target. These seem like they …
=> [One .NET] drop support for DX

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Design-time builds were not working as expected under a `dotnet`
context, mostly due to differences in build ordering.
`dotnet` design-time builds would fail with:
Xamarin.Android.Common.targets(577,2): Could not locate MonoAndroid SDK.
Reviewing the `_ResolveMonoAndroidSdks` MSBuild target, it depends on
values that the `_ResolveSdks` provides.
After updating `$(_ResolveMonoAndroidSdksDependsOn)` to include
`_ResolveSdks`, I hit:
Xamarin.Android.Common.targets(716,2): error MSB4044: The "GetAndroidDefineConstants" task was not given a value for the required parameter "AndroidApiLevel".
`$(_AndroidApiLevel)` was blank, which is provided by the
`_ResolveAndroidTooling` target.
After updating `$(_ResolveMonoAndroidSdksDependsOn)` again, I hit:
CSC error CS2001: Source file …
=> [One .NET] fix design-time builds

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Tasks/CalculateProjectDependencies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
In a .NET 5+ project, the `GetAndroidDependencies` MSBuild target
would use `$(TargetFrameworkVersion)` (which is 5.0) and always report
that API 21 needs to be installed.
The `<CalculateProjectDependencies/>` MSBuild task should use
`$(_AndroidApiLevel)` if set, and fallback to using
`$(TargetFrameworkVersion)`.
Under .NET 5+, `$(_AndroidApiLevel)` will be set via different targets
running in `$(GetAndroidDependenciesDependsOn)`. `$(_AndroidApiLevel)`
will be blank in legacy projects.
I updated a test so it now passes under a `dotnet` context.
=> [One .NET] fix the GetAndroidDependencies MSBuild target

Before.Xamarin.Android.sln.targets, Documentation/building/unix/instructions.md, Documentation/building/windows/instructions.md, Makefile, build-tools/scripts/DotNet.targets
When working on .NET 6, I use the following powershell function for my
"developer loop":
function pack-xa-nugets([string] $configuration = 'Debug')
{
& msbuild $xa\build-tools\xa-prep-tasks\xa-prep-tasks.csproj
& msbuild $xa\Xamarin.Android.sln -p:DisableApiCompatibilityCheck=true
& msbuild /t:CreateAllPacks build-tools/create-packs/Microsoft.Android.Sdk.proj
Remove-Item -r $xa\packages\microsoft.android.* -ErrorAction SilentlyContinue
}
The steps here are:
1. Build `xa-prep-tasks.csproj` so the `_CreateVersion` MSBuild target
can run and update git versioning information:
https://github.com/xamarin/xamarin-android/blob/9c880983914e2dbc3f384dea16b5351696732682/build-tools/xa-prep-tasks/xa-prep-tasks.targets#L4
2. Build `Xamarin.Android.sln`.
3. Run `CreateAllPacks`, to create all the …
=> [build] PackDotNet target to simplify .NET 6 development

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
The `AndroidXMigration` test was failing under a `dotnet` context:
error NU1605: Detected package downgrade: Xamarin.AndroidX.Lifecycle.LiveData from 2.1.0 to 2.1.0-rc1. Reference the package directly from the project to select a different version.
UnnamedProject -> Xamarin.Forms 4.5.0.617 -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.1.0)
UnnamedProject -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.1.0-rc1)
error NU1605: Detected package downgrade: Xamarin.Google.Android.Material from 1.0.0 to 1.0.0-rc1. Reference the package directly from the project to select a different version.
UnnamedProject -> Xamarin.Forms 4.5.0.617 -> Xamarin.Google.Android.Material (>= 1.0.0)
UnnamedProject -> Xamarin.Google.Android.Material (>= 1.0.0-rc1)
error NU1605: Detected package downgrade: …
=> [tests] bump to stable AndroidX packages

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Utilities/XmlUtils.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
The `AndroidUpdateResourcesTest.CheckFilesAreRemoved` test was failing
with:
Resources\values\Theme.xml error XA2001: Source file 'Resources\values\Theme.xml' could not be found.
When looking through logs, I noticed lots of differences in build
ordering from legacy projects.
1. `$(BuildDependsOn)` ordering - In legacy projects
`ImplicitlyExpandDesignTimeFacades` is listed last, while it was in
the middle for .NET 5+ projects.
This was caused by the ordering of `<Import/>`.
`Microsoft.Android.Sdk.BuildOrder.targets` needs to be imported before
`Xamarin.Android.Common.targets`.
2. `$(BuildDependsOn)` also listed these targets in legacy projects:
_CheckTargetFramework;
_RemoveLegacyDesigner;
`_CheckTargetFramework` is not needed, but it needs to be moved to
`Xamarin.Android.Legacy.targets`. …
=> [One .NET] fix build ordering & BuildItem.Deleted

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EnvironmentContentTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, tests/MSBuildDeviceIntegration/Tests/AotProfileTests.cs, tests/MSBuildDeviceIntegration/Tests/BugzillaTests.cs, tests/MSBuildDeviceIntegration/Tests/BundleToolTests.cs, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs, tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs, tests/MSBuildDeviceIntegration/Tests/MonoAndroidExportTest.cs
Using `ProjectExtensions.SetAndroidSupportedAbis()` sets either
`$(RuntimeIdentifiers)` or `$(AndroidSupportedAbis)` when appropriate.
Most tests should not do something like this going forward:
proj.SetProperty (KnownProperties.AndroidSupportedAbis, string.Join (";", supportedAbis));
And instead, simply do this:
proj.SetAndroidSupportedAbis (supportedAbis);
This fixes many tests under the `dotnet` context, but I just enabled a
couple for now.
=> [tests] standardize on SetAndroidSupportedAbis in MSBuild tests

build-tools/Xamarin.Android.Tools.BootstrapTasks/result-packaging.targets, build-tools/automation/azure-pipelines.yaml, build-tools/xaprepare/xaprepare/Scenarios/Scenario_Standard.cs, build-tools/xaprepare/xaprepare/Steps/Step_GenerateCGManifest.cs, build-tools/xaprepare/xaprepare/ToolRunners/GitRunner.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1139601
Fixes: https://dev.azure.com/devdiv/DevDiv/_componentGovernance/112013/alert/3185600?typeId=1016455
Context: https://docs.opensource.microsoft.com/tools/cg/cgmanifest.html
Context: https://github.com/xamarin/xamarin-macios/commit/32c4999822da706e0d374c253b76a293ba80cd8a
For a variety of "sanity and security" reasons, we need to better
integrate with "Component Governance", which "detects open source [used]
and alerts you to whether it has security vulnerabilities…".
Much of Component Governance is automagic, scanning the source tree
before and after the build occurs -- meaning it can scan NuGet
dependencies & such which are "in tree" after `make prepare` -- but it
can't have "insight" into the *meaning* of certain …
=> [xaprepare] CGManifest.json generation

build-tools/xaprepare/xaprepare/Application/ProcessRunner.cs, build-tools/xaprepare/xaprepare/Application/ProcessStandardStreamWrapper.cs, build-tools/xaprepare/xaprepare/Application/Program.DebianLinux.cs, build-tools/xaprepare/xaprepare/ToolRunners/GitRunner.cs
`git` outputs its progress messages to the standard error stream which
`xaprepare` intercepts and prints on screen in red and in the following
format:
stderr | Cloning into 'monodroid'...
stderr | remote: Enumerating objects: 58, done
stderr | Receiving objects:   0% (1/79000)
stderr | Receiving objects:   1% (790/79000)
stderr | Submodule 'external/Java.Interop' (https://github.com/xamarin/java.interop.git) registered for path 'external/Java.Interop'
stderr | Submodule 'external/android-api-docs' (https://github.com/xamarin/android-api-docs) registered for path 'external/android-api-docs'
This may be confused for an actual error even though it is most
certainly a harmless progress output.  This commit adds code to
intercept the know progress messages and redirect them to standard
output …
=> [xaprepare] Redirect some git messages from stderr to stdout

.editorconfig
For contributors using Visual Studio Code with the EditorConfig
extension, manual edits to `.resx` files would cause trailing spaces to
be trimmed from all lines of the files on each file save.  This
conflicted with edits made using the Visual Studio `.resx` resource
editor because in that editor, each file save creates a new file that
includes trailing spaces in the explanatory `Microsoft ResX Schema` XML
comment.
Adjust the `.editorconfig` file to disable automatic trimming of
trailing spaces from `.resx` files.  Contributors will now need to trim
trailing spaces by hand for any changed lines and avoid changing
trailing spaces for any other lines.
=> [.editorconfig] Do not trim trailing spaces in .resx files

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs
The `@(ResolvedSymbols)` and `@(_ResolvedSymbols)` MSBuild item group
are currently populated in `Xamarin.Android.Legacy.targets`.
Since a) nothing used these item groups and b) no test failed, I
didn't implement these item groups for .NET 5+.
After reviewing some of the existing code:
* https://github.com/xamarin/monodroid/blob/3d84feddd5517b2ca2322ddc68eef454c60fa9ca/tools/msbuild/Tasks/InstallPackageAssemblies.cs#L191-L194
* https://github.com/xamarin/xamarin-android/blob/0907f09f9c2073522adb66d717c2726be3712208/src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs#L342-L353
It seems like we *should* actually use these item groups, instead of
relying on `File.Exists()` checks. Additionally, the new fast
deployment system is using item groups.
I was able to look for `.pdb` files within …
=> [One .NET] populate @(ResolvedSymbols)

build-tools/scripts/cmake-common.props, src/monodroid/CMakeLists.txt, src/monodroid/jni/cppcompat.hh, src/monodroid/jni/new_delete.cc
Fixes: https://github.com/xamarin/xamarin-android/issues/4949
Context: https://github.com/xamarin/xamarin-android/pull/4952
Context: https://github.com/android/ndk/issues/744
Xamarin.Android uses the "system" version of the C++ standard
library (which is, in reality, a very basic stub containing only weak
definitions of the `new` and `delete` operator functions) in order to
avoid possible conflicts with Xamarin.Android applications which could
make use of their own version of the C++ standard library. The conflict
would arise from the fact that the `libc++` library shipped with the
current versions of Android NDK is built in a way that would expose a
large number of its symbols which would conflict with any other `libc++`
used by the application.
Additionally, linking `libc++` into …
=> [runtime] Use the "none" option for C++'s standard library

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Designer.targets, src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs
All of the `DesignerTests` were failing under a `dotnet` context...
The first issue is that the main app assembly might not exist during
the `SetupDependenciesForDesigner` MSBuild target. This target can run
before a build has been run at all.
So I brought the same `File.Exists()` check over from the
`<FilterAssemblies/>` MSBuild target to the `<ProcessAssemblies/>`
MSBuild target:
https://github.com/xamarin/xamarin-android/blob/0907f09f9c2073522adb66d717c2726be3712208/src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs#L38-L41
This allows `SetupDependenciesForDesigner` to complete successfully.
Secondly, some of the `AndroidX` libraries pull in this setting:
<AndroidManifestMerger Condition=" '$(AndroidManifestMerger)' == '' …
=> [One .NET] fix designer MSBuild targets/tests

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
The `CheckMetadataSkipItemsAreProcessedCorrectly` test was failing
under a `dotnet` context due to item metadata missing, such as:
<AndroidSkipAddToPackage>True</AndroidSkipAddToPackage>
<AndroidSkipJavaStubGeneration>True</AndroidSkipJavaStubGeneration>
<AndroidSkipResourceExtraction>True</AndroidSkipResourceExtraction>
These metadata support AndroidX.Migration, and they are completely
missing from the item groups generated in
`Microsoft.Android.Sdk.AssemblyResolution.targets`.
After the `<ProcessAssemblies/>` MSBuild task is called, we should
call `<AppendCustomMetadataToItemGroup/>` to populate the missing
metadata.
The `CheckMetadataSkipItemsAreProcessedCorrectly` test now passes.
=> [Microsoft.Android.Sdk] fix %(AndroidSkip*) item metadata

.external, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs
Context: xamarin/android-sdk-installer#450
Changes: https://github.com/xamarin/android-sdk-installer/compare/c6c12db0...2b4d1a6
Changes: https://github.com/xamarin/monodroid/compare/5784a746...b12a3e8d
A fix for the `<InstallAndroidDependencies/>` target has been brought in
via the `android-sdk-installer` bump in xamarin/monodroid@b12a3e8.
The `<InstallAndroidDependencies/>` test previously had issues due to
clean up logic in the test framework that partially deleted the newly
provisioned Android SDK on a subsequent build.  I believe that we've
been seeing successful results for this test because the subsequent
build in the test would fall back to a different Android SDK that was
already on disk.  The test has been improved by asserting that the newly
installed Android SDK is used during …
=> [Xamarin.Android.Build.Tasks] Fix <InstallAndroidDependencies/>

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/Aapt2Tests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ResolveSdksTaskTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsAndroidApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsMapsApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsXASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/AndroidManifest.xml, tests/MSBuildDeviceIntegration/Tests/BugzillaTests.cs, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs, tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs
Context: https://github.com/xamarin/net6-samples/commit/571e1c0f94737271c2ea43b25ad3e2b508e72b5f
Xamarin.Forms 4.7.x is required to solve a crash on startup in .NET 5+.
We should bump to Xamarin.Forms 4.7 in our MSBuild tests. This requires
some additional AndroidX packages to be bumped.
However, after doing this I got build warnings such as:
warning XA1006: Android API level 30 is higher than the targetSdkVersion (28). Please increase the `android:targetSdkVersion` in the `AndroidManifest.xml` so that the API levels match.
The project has a `AndroidManifest.xml` with an empty `<uses-sdk/>`
element, but `obj\Debug\android\AndroidManifest.xml` has 28 listed.
The projects that the MSBuild tests generate have an empty
`<uses-sdk/>` by default.
So where does `targetSdkVersion="28"` come from? …
=> [tests] emit <uses-sdk/> & use Xamarin.Forms 4.7

Documentation/release-notes/4975.md, src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
In a customer's build log, a large solution build with no changes had:
1956 ms  FilterAssemblies                          18 calls
The `<FilterAssemblies/>` MSBuild task runs on every build for class
libraries and application projects. It looks at assemblies to classify
them as a "MonoAndroid" assembly.
Since we are already using System.Reflection.Metadata to open each
assembly, we can use each assembly's MVID and `RegisterTaskObject` to
skip future calls to the same assembly. This will be helpful in
incremental builds in the IDE, as well as, large solutions that
encounter the same assemblies throughout a build.
Using the in-memory cache, we don't need to check any file timestamps.
Unique MVIDs will yield the same result for the `<FilterAssemblies/>`
task -- regardless if the assembly was …
=> [Xamarin.Android.Build.Tasks] <FilterAssemblies/> in-memory cache

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Context: https://build.azdo.io/3947655
Since 396aca1c switched the
`Xamarin.Android.Build.Tests.BuildTest.BuildLibraryWhichUsesResources`
test to use AndroidX, it has been randomly failing with:
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(124,5): error : Could not find file '/Users/runner/work/1/s/packages/xamarin.androidx.migration/1.0.0.1/c0hredtr.mkk'.
I think this is happening because the test is parameterized and
AndroidX has a large dependency tree.
`[NonParallelizable]` should solve the issue.
=> [tests] BuildLibraryWhichUsesResources should be NonParallelizable

Documentation/release-notes/4982.md, src/Xamarin.Android.Build.Tasks/Tasks/CreateLibraryResourceArchive.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/Files.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/4565
Context: https://github.com/xamarin/xamarin-android/issues/4565#issuecomment-668341395
In f230b87c, I fixed `lint.jar` from being included in apps from the
`@(AndroidAarLibrary)` item group. Unfortunately, this did not fix the
scenario for `@(LibraryProjectZip)` in binding projects!
I moved the `skipCallback` used in the
`<ResolveLibraryProjectImports/>` to a common place in the `Files`
class so it can also be used by the `<CreateLibraryResourceArchive/>`
MSBuild task.  We need to use this for `.aar` files *only*, because
`.zip` files could be *any* format.
I brought over Brendan's test that reproduces the bug as well.
=> [Xamarin.Android.Build.Tasks] fix for lint.jar and @(LibraryProjectZip)

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-msbuild-mac-tests.yaml, build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/CodeBehindTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EmbeddedDSOTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EnvironmentContentTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/MSBuildSdkExtrasTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/MakeBundleTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs
This will enable all MSBuild tests in
`Xamarin.Android.Build.Tests.dll` except for the new categories:
`DotNetIgnore`, `AOT`, `FSharp`, `LibraryProjectZip`, `MkBundle`,
`MonoSymbolicate`, `PackagesConfig`, and `StaticProject`.
Reasoning:
* `AOT` - need Mono AOT support in .NET 5.
* `FSharp` - [Xamarin.Android.FSharp.ResourceProvider][0] support
needed on .NET 5.
* `LibraryProjectZip` - will need future support in Xamarin.Android.
* `MkBundle` - may not ever come to .NET 5.
* `MonoSymbolicate` - need symbolication support in .NET 5.
* `PackagesConfig` - n/a for .NET 5.
* `StaticProject` a few tests that were migrated to
`Xamarin.Android.Build.Tests` in d447aa66 are ignored for now.
This also reworks our build pipeline to run the MSBuild tests across 12
CI machines:
* Windows - Node 1 - …
=> [build] enable One .NET MSBuild tests

README.md
Add Commercial Xamarin.Android 11.1 download locations to `README.md`.
Update the Commercial Xamarin.Android 10.4 download locations to show
the final version number 11.0.
Update the OSS master version number to 11.1.99, and update the download
location for it to the Azure Pipelines build instead of the old disabled
Jenkins job.  Currently the Azure Pipeline build only produces NuGet
packages and `.deb` installer packages, so at the moment, the artifacts
are not easy to consume on systems other than Ubuntu.
=> [docs] Add Commercial Xamarin.Android 11.1 download locations

Documentation/release-notes/transitive-refasm.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
Fixes: https://developercommunity.visualstudio.com/content/problem/1086457/index.html
Context: 8f2ae24813ec3cdab56f688c4c3b611a33759333
Context: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/938468
If a Xamarin.Android app referenced a .NET Standard library that had
`$(ProduceReferenceAssembly)`=`true`, and that library in turn
referenced a second .NET Standard library, then changes to the second
library would not be deployed during incremental deployments in Visual
Studio unless the app project also directly referenced the second
library.
For additional context, note that as discussed in internal work item
938468, if a .NET Framework console application references a .NET
Standard library that has `$(ProduceReferenceAssembly)`=`true`, then
changes to the library are similarly …
=> [Xamarin.Android.Build.Tasks] Deploy changes to transitive reference assembly dependencies

Documentation/guides/MSBuildBestPractices.md, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Documentation.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Wear.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.EmbeddedResource.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.PCLSupport.targets
Context: https://github.com/dotnet/msbuild/pull/5553
Context: https://github.com/dotnet/msbuild/issues/5315
I have seen some comically long log messages such as:
Task "GetDependsOnNETStandard" skipped, due to false condition; ('$(_HasReferenceToSystemRuntime)' != 'true' and '$(_IsXBuild)' != 'true' and '$(DependsOnNETStandard)' == '' and '@(_XACandidateNETStandardReferences)' != '') was evaluated as ('true' != 'true' and 'true' != 'true' and '' == '' and 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0-rc.1.20371.13\ref\net5.0\Microsoft.CSharp.dll;C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0-rc.1.20371.13\ref\net5.0\Microsoft.VisualBasic.Core.dll;C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0-rc.1.20371.13\ref\net5.0\Microsoft.VisualBasic.dll;C …
=> [Xamarin.Android.Build.Tasks] fix enormous string expansion

src/java-runtime/java/mono/android/DebugRuntime.java, src/java-runtime/java/mono/android/MonoPackageManager.java, src/java-runtime/java/mono/android/Runtime.java, src/monodroid/jni/basic-android-system.cc, src/monodroid/jni/basic-android-system.hh, src/monodroid/jni/debug-app-helper.cc, src/monodroid/jni/debug-app-helper.hh, src/monodroid/jni/mono_android_Runtime.h, src/monodroid/jni/monodroid-glue-internal.hh, src/monodroid/jni/monodroid-glue.cc, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/4983
Context: https://developer.android.com/reference/android/content/pm/ApplicationInfo.html#FLAG_EXTRACT_NATIVE_LIBS
Xamarin.Android has supported the [extractNativeLibs][0]
attribute (introduced by Android API 23) on the `<application>` element
in AndroidManifest.xml since 95ca1025f0b7e678055ea922a4091b8b9710b18f,
with a single significant modification in
feb9ea2a53034b73d5bd62ed3caea4e8f658d1e5 after we discovered that
Android build system can set the flag when constructing the APK after we
are done packaging.
feb9ea2a5 introduced a runtime check to see whether the
`FLAG_EXTRACT_NATIVE_LIBS` is *not* set, which meant that the native
libraries are to stay in the APK file and we need to set up our DSO
search paths to point to the …
=> Work around Android 9+ bug with extractNativeLibs flag

Configuration.props, build-tools/debian-metadata/rules, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
Fixes the issue with a native crash on windows. 
The actual patch for libzip can be found at [https://github.com/nih-at/libzip/pull/202](https://github.com/nih-at/libzip/pull/202).
However LibZipSharp is currently applying that patch manually via [https://github.com/xamarin/LibZipSharp/pull/67](https://github.com/xamarin/LibZipSharp/pull/67) to fix the issue in v1.7.3 of libzip. This is because the fix might not land for a while.
=> [LibZipSharp] Bump to Version 1.0.20

build-tools/scripts/MSBuildReferences.projitems, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/App.config, tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj, tools/xabuild/App.config, tools/xabuild/xabuild.csproj
Fixes: https://github.com/xamarin/xamarin-android/issues/4872
Context: https://docs.microsoft.com/dotnet/framework/configure-apps/redirect-assembly-versions
On Windows, since installing VS 16.7 `xabuild` fails on any project with:
error XACML7028: System.IO.FileNotFoundException: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
error XACML7028: File name: 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
error XACML7028:    at Xamarin.Tools.Zip.ZipArchive.stream_callback(IntPtr state, IntPtr data, UInt64 len, SourceCommand cmd)
error XACML7028:    at Xamarin.Tools.Zip.Native.zip_source_function(IntPtr source, …
=> [xabuild] fixes for MSBuild 16.7.x

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/Aapt2Tests.cs
Context: https://build.azdo.io/3974634
Several of the `Aapt2DaemonInstances` tests can fail with:
Expected 6 but was 3
Expected: 6
But was:  3
It seems like this is happening randomly, and we think the reason is
that some macOS CI machines only have 4 processors/cores.
To solve this:
* I moved the `Environment.ProcessorCount` call to a `virtual`
property.
* The test overrides the value to 8, so the test will pass on any
machine.
I verified that if you change the value to 4, the test fails in the
same way we are seeing on CI.
=> [tests] fix Aapt2DaemonInstances on 4 core machines

Documentation/release-notes/5001.md, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ZipArchiveExTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/ZipArchiveEx.cs
Fixes: https://feedback.devdiv.io/1144021
Fixes: https://github.com/xamarin/xamarin-android/issues/4990
If you deploy an app with `android:extractNativeLibs="true"` (most of
the time the default when omitted).
Then change it to `android:extractNativeLibs="false"` and deploy again
you get a deploy error:
ADB0010: Mono.AndroidTools.InstallFailedException: Failure [INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]
Looking at the resulting `.apk` file, the native libraries are
compressed when they shouldn't be. A `Rebuild` solves the issue.
In 1c4727cb, the changes to the `<BuildApk/>` for better incremental
build performance did not take into account what happens if the
compression mode changes for zip entries.
There are two cases:
1. We are copying entries produced by …
=> [Xamarin.Android.Build.Tasks] <BuildApk/> should check compression

build-tools/scripts/RunTests.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AidlTest.cs, src/Xamarin.Android.Tools.Aidl/CSharpCodeGenerator.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/1597
`Xamarin.Android.Tools.Aidl.CSharpCodeGenerator` didn't properly
support unmarshaling the `Map` type, e.g. given a `Test.aidl` file
with the Build action `@(AndroidInterfaceDescription)`:
import java.util;
interface Test {
void arrayList(inout List list);
void map(inout Map m);
}
the build would fail with:
obj/Debug/aidl/Test.cs(57,17): error CS7036: There is no argument given that corresponds to the required formal parameter 'loader' of 'Parcel.ReadHashMap(ClassLoader)'
obj/Debug/aidl/Test.cs(98,21): error CS7036: There is no argument given that corresponds to the required formal parameter 'outVal' of 'Parcel.ReadList(IList, ClassLoader)'
obj/Debug/aidl/Test.cs(118,18): error CS7036: There is no argument given that corresponds …
=> [Xamarin.Android.Tools.Aidl] Fix `Map` marshaling

Documentation/release-notes/cpp-aab.md, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Microsoft.Cpp.Android.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/4998
Context: https://github.com/luminixinc/XamarinAndroidNativeDebugTest
The above C++ project fails to build when using
`$(AndroidPackageFormat)` = `aab` with:
Files under lib/ must have .so extension, found 'lib/x86/gdbserver'.
Reviewing `Microsoft.Cpp.Android.targets`, it adds `gdbserver` to the
`@(AndroidNativeLibrary)` item group.
`bundletool` fails on any non-`.so` files added to the `lib` directory:
https://github.com/google/bundletool/blob/ae0fc0162fd80d92ef8f4ef4527c066f0106942f/src/main/java/com/android/tools/build/bundletool/validation/BundleFilesValidator.java#L97-L103
This should probably only be done for debug builds. We should only
include this file when `$(AndroidIncludeDebugSymbols)` is `true`
and …
=> [Microsoft.Cpp.Android] fix for app bundles and C++ projects

src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Some of the warning messages in the `_CheckNonIdealConfigurations`
MSBuild target were written before we had localization support in
Xamarin.Android.Build.Tasks.
This brings the messages over to `Resources.resx`, so we can get them
localized.
=> [Xamarin.Android.Build.Tasks] localization for _CheckNonIdealConfigurations

build-tools/xaprepare/xaprepare/Application/DownloadStatus.cs, build-tools/xaprepare/xaprepare/Application/Utilities.cs
Context: https://build.azdo.io/3979030
Sometimes I've seen random network failures on CI such as:
Download progress: 80.87% (2.29 GB at 1.91 GB/s)
Download progress: 80.87% (2.29 GB at 16 KB/s)
Step Xamarin.Android.Prepare.Step_Android_SDK_NDK failed: Failed to download https://dl.google.com/android/repository/android-2.3.3_r02.zip: Remote prematurely closed connection.
System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_Android_SDK_NDK failed: Failed to download https://dl.google.com/android/repository/android-2.3.3_r02.zip: Remote prematurely closed connection. ---> System.InvalidOperationException: Failed to download
at Mono.Net.Security.AsyncProtocolRequest.ProcessOperation (System.Threading.CancellationToken cancellationToken) [0x000e3] in …
=> [xaprepare] add retry logic for downloading files

.vscode/launch.json, .vscode/settings.json, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-msbuild-mac-tests.yaml, build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml, build-tools/automation/yaml-templates/run-nunit-tests.yaml, build-tools/create-vsix/symbols/ExternalWhiteList.csv, build-tools/installers/create-installers.targets, build-tools/scripts/RunTests.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ResolveSdksTaskTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidCommonProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, src/Xamarin.Android.Tools.Aidl/Xamarin.Android.Tools.Aidl.csproj
There are various tests in `Xamarin.Android.Build.Tests` that execute
MSBuild tasks directly. This means the changes in #4820 are not quite
complete. We need to actually *run* the tests under .NET Core to see
if these tests would pass under a One .NET context.
The solution (you would think), would be to make the test assembly
`netstandard2.0` so you could run either:
> nunit3-console Xamarin.Android.Build.Tests.dll
> dotnet test Xamarin.Android.Build.Tests.dll
`nunit3-console` would execute the tests under .NET framework/Mono and
`dotnet test` would run under .NET Core or .NET 5+.
Unfortunately, `nunit3-console` can't run tests from a
`netstandard2.0` library!
So we multi-target:
<TargetFrameworks>net472;net5.0</TargetFrameworks>
Unfortunately, the `net5.0` causes MSBuild to fail with:
> …
=> [tests, build] multi-target Xamarin.Android.Build.Tests

src/Mono.Android/Android.Runtime/AndroidRuntime.cs, src/Mono.Android/Test/Java.Lang/ObjectTest.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/4989
What happens if you dispose an instance *while disposing the instance*?
// C#
public class MyDisposableObject : Java.Lang.Object {
bool _isDisposed;
protected override void Dispose (bool disposing)
{
if (_isDisposed) {
return;
}
_isDisposed = true;
if (this.Handle != IntPtr.Zero)
this.Dispose ();
base.Dispose (disposing);
}
}
// …
void MyTestMethod ()
{
var value = new MyDisposableObject ();
value.Dispose ();
value.Dispose ();
}
Here, `MyDisposableObject.Dispose(bool)` calls `Object.Dispose()`
when `Object.Handle` is valid.  This "feels" admittedly unusual, but
`IDisposable.Dispose()` is *supposed to be* Idempotent: it can be
called multiple times with no ill effects.  Shouldn't this be the same?
Unfortunately, it *isn't* the …
=> Bump to xamarin/Java.Interop/master@007b35b

tools/setup-windows/setup-windows.csproj
`setup-windows.exe` was being output to:
xamarin-android\tools\setup-windows\bin\Debug\bin\setup-windows.exe
This caused a little trouble because `setup-windows.exe` currently only
creates the correct symlinks if it is run from:
xamarin-android\bin\Debug\bin\setup-windows.exe
The trouble was that `Configuration.props` was being imported after the
use of `$(XamarinAndroidSourcePath)`, so `$(XamarinAndroidSourcePath)`
was empty when it was used.
To fix that, move the `Configuration.props` import before the use of
`$(XamarinAndroidSourcePath)`.
=> [setup-windows] Import Configuration.props earlier

Documentation/release-notes/extractNativeLibs.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/4986
Context: https://github.com/xamarin/xamarin-android/commit/86737ca159d851f2743c01ffdf66428df07082b5
Context: https://android.googlesource.com/platform/tools/base/+/fd2ac00ab76dfdececce5a25cb7ad23b2b6f5d29%5E%21
When we bumped `manifest-merger` from 26.5.0 to 27.0.0, it started
emitting this in `AndroidManifest.xml` when `minSdkVersion` is 23 or
higher:
<application android:extractNativeLibs="false">
When *omitted* this value defaults to `true`, meaning that native
libraries are compressed in `.apk` files and extracted to disk on
installation.
When `extractNativeLibs` is `false`, native libraries are
*uncompressed* in `.apk` files and loaded directly from the `.apk`.
This saves on install size at the cost of larger `.apk` size. …
=> [Xamarin.Android.Build.Task] emit android:extractNativeLibs="true" by default

build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/Application/MonoRuntime.cs, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
To save on distribution size, Xamarin.Android hasn't been shipping the
unstripped Mono native libraries for quite a while now.  However, that
causes stack traces, when the native side crashes, quite tedious to read
since they usually provide liitle to no information about the exact
location of the crash since the binaries have no non-public symbol
information.
This commit introduces several changes in this area:
* We now package the .d.so versions (full debug info) of the DSOs
* The .d.so versions are packaged into Debug APKs if
the **unsupported** `$(_AndroidDebugNativeLibraries)` is set to
`True` (it defauls to `False`)
* The .so libraries which so far have been stripped of all the
symbols, are now stripped of just the full debug information leaving
the local/hidden symbol table in the …
=> [runtime] package and use unstripped DSOs

Documentation/release-notes/class-libraries-aab.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/5024
Building a class library with `$(AndroidPackageFormat)` set to `aab`
fails with:
error XA0119: Using the shared runtime and Android App Bundles at the same time is not currently supported.
Use the shared runtime for Debug configurations and Android App Bundles for Release configurations.
In 5d8bc5c1, we upgraded this message from a warning to an error.
Unfortunately, this error is being emitted for class libraries as
well as apps!
You could easily hit the issue running MSBuild command-line:
msbuild Foo.Android.csproj -p:Configuration=Release -p:AndroidPackageFormat=aab
If `Foo.Android.csproj` referenced a Xamarin.Android class library, it
would have the global `$(AndroidPackageFormat)` property set. Class
libraries also appear …
=> [Xamarin.Android.Build.Tasks] _CheckNonIdealConfigurations only runs for apps

build-tools/automation/azure-pipelines.yaml
The default yaml-templates branch is now `main`, we should track this
going forward.
=> [ci] Use main branch of yaml-templates

Documentation/release-notes/class-libraries-aab.md, Documentation/release-notes/extractNativeLibs.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
These are 5 commits that had conflicts:
* https://github.com/xamarin/xamarin-android/commit/9db3ecbb32baedd528d21a303a080f1b8c904128
* https://github.com/xamarin/xamarin-android/commit/4931eb4451ca88fdfac8dc19795d18b242a54ae9
* https://github.com/xamarin/xamarin-android/commit/1403eec765b14aafc64f97d619d5a143df4cb261
* https://github.com/xamarin/xamarin-android/commit/d94ebbd564b3517618c7d3f7cd027fbeb3824b61
* https://github.com/xamarin/xamarin-android/commit/baa8adad35a2f27dcd57d504013c01ad83577674
One test was modified since the `XamarinAndroidApplicationProject.MinSdkVersion` property is missing.
I used this instead:
```diff
-proj.MinSdkVersion = "23";
+proj.AndroidManifest = proj.AndroidManifest.Replace ("<uses-sdk />", "<uses-sdk android:minSdkVersion=\"23\" />");
```
=> d16-8 backport for for Preview 3

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
This was failing with:
Xamarin.Android.Common.targets(2107,3): error XABBA7024: Xamarin.Tools.Zip.ZipIOException: Error occured while reading obj\Debug\android\bin\base.zip
at Xamarin.Tools.Zip.ZipArchive.Open(String path, FileMode mode, String defaultExtractionDir, Boolean strictConsistencyChecks, IPlatformOptions options) in /Users/runner/work/1/s/ZipArchive.cs:line 273
at Xamarin.Android.Tasks.ZipArchiveEx..ctor(String archive, FileMode filemode)
at Xamarin.Android.Tasks.BuildApk.ExecuteWithAbi(String[] supportedAbis, String apkInputPath, String apkOutputPath, Boolean debug, Boolean compress, IDictionary`2 compressedAssembliesInfo)
at Xamarin.Android.Tasks.BuildApk.RunTask()
at Xamarin.Android.Tasks.AndroidTask.Execute()
But this shouldn't run at all for a class library?
The test was …
=> [tests] fix ClassLibraryHasNoWarnings test

Documentation/release-notes/5038.md, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/Tasks/CollectNonEmptyDirectories.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/Aapt2Tests.cs
Context https://github.com/Redth/ResizetizerNT/issues/23
The `CollectNonEmptyDirectories` task is responsible for
creating a cache file `files.cache`. This file contains
a list of all the resource files for that particular
directory.
We hit a problem when using `ResizetizerNT` and a
`google-services.json` file where the `files.cache` for
one would be overwritten by the other.  This is because of
a simple assuption within the Task itself. That if the
"directory" was not in the Intermediate `lp` directory
(for libraries) then we could just create the `files.cache`
file in the parent directory. This woud be the root of
the `IntermediateOutputPath`.
The problem with `ResizetizerNT` and `google-services.json` is that
they are BOTH outside of the `lp` directory. They also only create
a …
=> [Xamarin.Android.Build.Tasks] Fix CollectNonEmptyDirectories to handle file collisions.

.gitmodules, Documentation/release-notes/5032.md, Xamarin.Android.sln, build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/ThirdPartyNotices/apksigner.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Tooling.targets, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ResolveSdksTaskTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets, src/apksigner/.gitignore, src/apksigner/apksigner.csproj, src/apksigner/build.gradle
The Android SDK Build-tools 30.x currently requires JDK 11
in order to use `apksigner.jar`:
Task "AndroidApkSigner"
Task Parameter:ApkSignerJar=C:\Users\dlab14\android-toolchain\sdk\build-tools\30.0.0-rc4\lib\apksigner.jar
…
Task Parameter:ToolPath=C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25\bin
Task Parameter:ManifestFile=obj\Release\android\AndroidManifest.xml
C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25\bin\java.exe -jar C:\Users\dlab14\android-toolchain\sdk\build-tools\30.0.0-rc4\lib\apksigner.jar sign --ks "C:\Users\dlab14\AppData\Local\Xamarin\Mono for Android\debug.keystore" --ks-pass pass:android --ks-key-alias androiddebugkey --key-pass pass:android --min-sdk-version 21 --max-sdk-version 29 …
=> [Xamarin.Android.Build.Tasks] redistribute apksigner.jar

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/publish-artifact.yaml, build-tools/automation/yaml-templates/upload-results.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4000236&view=logs&j=db00894d-3ef4-5d97-073c-254fbd613a41&t=2d91500b-42fa-5f4d-9c78-a0a207f1288c&l=2042
A re-run of the designer tests will fail with:
##[error]Artifact Test Results - Designer - macOS already exists for build 4000236.
All of our other calls to `PublishPipelineArtifact` go through the
steps in `upload-results.yaml`. I moved the logic that sets
`$(UploadAttemptSuffix)` so that it can be used by the designer tests
as well.
=> [build] add attempt # for designer tests

src/Mono.Android/Android.Runtime/Extensions.cs, src/Mono.Android/Java.Interop/JavaObjectExtensions.cs
Assuming `JavaCast<TResult>` never returns null except when its input is null, this annotation conveys the idea so C# realizes that given a non-null input, a non-null output will come out, thereby avoiding compiler warnings in calling code caused by the addition of the less precise nullable annotations added earlier.
=> Fix nullable annotation on JavaCast

.gitmodules, Documentation/release-notes/5032.md, Xamarin.Android.sln, build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/ThirdPartyNotices/apksigner.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Tooling.targets, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ResolveSdksTaskTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets, src/apksigner/.gitignore, src/apksigner/apksigner.csproj, src/apksigner/build.gradle
Fixes? https://work.azdo.io/1148474
Fixes? https://developercommunity.visualstudio.com/content/problem/1086793/我用xamarin-开发android-后进行打包发布apk但升级后打包报密码错误.html
Context: 380e95e340168f68b1ae3eb43e0a71b05bc6d80b
Context: https://issuetracker.google.com/issues/150189789
Context: https://github.com/xamarin/androidtools/commit/0031300d95cdeeaa5b64cb1287ea0b4a4586e1a9
Context: https://github.com/xamarin/androidtools/commit/3f51412d5f213c0267fc597623f3430437d6452e
Visual Studio has a [Xamarin Android SDK Manager][0], which allows
installing and updating the various Android SDK packages.
Historically, two "repositories" were available: the Microsoft
repository, and the Google repository.  The Microsoft repository was
curated, containing only "known good" package versions, while the
Google …
=> [Xamarin.Android.Build.Tasks] redistribute apksigner.jar (#5032)

build-tools/automation/yaml-templates/upload-results.yaml
I accidentally put the extra label twice in 5bcd2d9d:
Test Results - MSBuild - Mac-2 - Legacy (Attempt 2) (Attempt 2)
This was because `publish-artifact.yaml` has:
- task: PublishPipelineArtifact@1
displayName: ${{ parameters.displayName }}
inputs:
artifactName: ${{ parameters.artifactName }} $(UploadAttemptSuffix)
targetPath: ${{ parameters.targetPath }}
condition: ${{ parameters.condition }}
*and* `upload-results.yaml` has:
- template: publish-artifact.yaml
parameters:
displayName: upload build and test results
artifactName: ${{ parameters.artifactName }} $(UploadAttemptSuffix)
We need to remove `$(UploadAttemptSuffix)` from `upload-results.yaml`.
=> [build] fix '(Attempt N)' listed twice on artifacts

Documentation/release-notes/csharp-8.md, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.CSharp.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/5049
Context: https://github.com/dotnet/roslyn/commit/12f1b8f6c17c0bcd271525b5f4db0f621944c49d#diff-125e2d8c52dd9033f9b248f79f78c3f8
Context: https://github.com/dotnet/roslyn/pull/44911#discussion_r477418327
The `BuildTest.CSharp8Features` test was failing for me locally where
I have Visual Studio 2019 16.7.2 installed:
Foo.cs(1,23): error CS8370: Feature 'using declarations' is not available in C# 7.3. Please use language version 8.0 or greater.
After review, it appears that a change in Roslyn's MSBuild targets
removed `$(MaxSupportedLangVersion)` and made the property private:
`$(_MaxSupportedLangVersion)`.
After some discussion around C# 9.0:
* It is unknown if C# 9.0 will be supported by mono/mono/2020-02. Some
features like …
=> [Xamarin.Android.Build.Tasks] fix C# 8.0 support by default

Documentation/release-notes/5051.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://developercommunity.visualstudio.com/content/problem/1157593/apk-is-not-rebuild-when-androidasset-changes.html
Fixes: https://feedback.devdiv.io/1157593
An incremental build after `@(AndroidAsset)` file changes did not
actually make it to the `.apk` file.
I could reproduce this easily in a sample app doing something like:
using (var reader = new StreamReader (Assets.Open ("foo.txt"))) {
var textView = FindViewById<TextView> (Resource.Id.textView1);
textView.Text = reader.ReadToEnd ();
}
Edits to `foo.txt` would not show on screen, unless I did a `Rebuild`
or edited an `@(AndroidResource)` file!
Reviewing the inputs to the `_CreateBaseApk` MSBuild target:
<_CreateBaseApkInputs>
$(MSBuildAllProjects)
;$(IntermediateOutputPath)android\AndroidManifest.xml …
=> [Xamarin.Android.Build.Tasks] AndroidAsset changes should update .apk

build-tools/create-packs/Microsoft.Android.Runtime.proj
`libsqlite3_xamarin.so` is needed for `Mono.Data.Sqlite.dll`, which
does not currently exist in a One .NET world.
`libsqlite3_xamarin.so` is currently included in the
`Microsoft.Android.Runtime` pack:
runtimes\android.21-arm\lib\net5.0\Java.Interop.dll
runtimes\android.21-arm\lib\net5.0\Mono.Android.dll
runtimes\android.21-arm\lib\net5.0\Mono.Android.Export.dll
runtimes\android.21-arm\native\libmono-android.debug.so
runtimes\android.21-arm\native\libmono-android.release.so
runtimes\android.21-arm\native\libxa-internal-api.so
runtimes\android.21-arm\native\libsqlite3_xamarin.so
runtimes\android.21-arm\native\libxamarin-debug-app-helper.so
The way things are currently working, every native library in this
package is added to every app.
This library adds ~641KB per architecture:
Size …
=> [One .NET] remove libsqlite3_xamarin.so from Microsoft.Android.Runtime

src/apksigner/apksigner.csproj
In c50df1c5, I made a small mistake in building `apksigner`.
Locally, I noticed my machine is in a state where `apksigner` is built
on any incremental build:
Input file "apksigner.csproj" is newer than output file "build\libs\apksigner.jar".
Exec
...
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
BUILD SUCCESSFUL in 3s
3 actionable tasks: 3 up-to-date
To fix this, we need a `<Touch/>` MSBuild task call to ensure the
timestamp on `apksigner.jar` is updated even if gradle doesn't do any
work.
Now things are working properly:
Skipping target "_BuildGradle" because all output files are up-to-date with respect to the input files.
Input files: apksigner.csproj;build.gradle
Output files: build\libs\apksigner.jar
This saves …
=> [build] fix incremental build for apksigner.jar

Configuration.props, build-tools/xaprepare/xaprepare/Application/KnownProperties.cs, build-tools/xaprepare/xaprepare/Application/Properties.Defaults.cs.in, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, build-tools/xaprepare/xaprepare/xaprepare.targets
Now that we have:
* c50df1c5
* xamarin/androidtools/master@30a4cf7b
We should be able to bump to `build-tools` 30.x and everything work.
One issue, is I had to use the same functionality for a hash in the URL as mentioned in 044bbe5a.
=> Bump to build-tools 30.0.2

Configuration.props, src/apksigner/apksigner.csproj, src/manifestmerger/manifestmerger.targets, src/proguard/proguard.targets, src/r8/r8.targets
Since c50df1c5, building apps with JDK 1.8 fails with:
~/android-toolchain/jdk-1.8/bin/java -jar ./xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/apksigner.jar sign --ks "~/.local/share/Xamarin/Mono for Android/debug.keystore" --ks-pass pass:android --ks-key-alias androiddebugke
y --key-pass pass:android --min-sdk-version 28 --max-sdk-version 29  ./xamarin/XAPerfTest/bin/Debug/com.xamarin.xaperftest-Signed.apk  (TaskId:206)
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer; (TaskId:206)
at com.android.apksig.internal.util.FileChannelDataSource.copyTo(FileChannelDataSource.java:154) (TaskId:206)
at com.android.apksig.internal.util.FileChannelDataSource.getByteBuffer(FileChannelDataSource.java:164) (TaskId:206)
at …
=> [build] all desktop Java code should be built with JDK 1.8

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/CompressedAssemblyInfo.cs, src/Xamarin.Android.Build.Tasks/Utilities/MSBuildExtensions.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
Context: https://github.com/xamarin/xamarin-android/pull/5040
In trying to enable our F# MSBuild tests, one fails with:
GenerateCompressedAssembliesNativeSourceFiles
Xamarin.Android.Common.targets(1933,3): error XAGCANSF7004: System.ArgumentException: An item with the same key has already been added. Key: [FSharp.Core.resources.dll, Xamarin.Android.Tasks.CompressedAssemblyInfo]
at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)
at Xamarin.Android.Tasks.GenerateCompressedAssembliesNativeSourceFiles.GenerateCompressedAssemblySources()
at Xamarin.Android.Tasks.GenerateCompressedAssembliesNativeSourceFiles.RunTask()
at Xamarin.Android.Tasks.AndroidTask.Execute()
Looking at some of the item groups …
=> [One .NET] fixes for satellite assemblies

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/monodroid/jni/embedded-assemblies.cc, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/xa-internal-api.cc
Context: https://github.com/xamarin/java.interop/pull/703
This commit fixes a handful of warnings reported by GCC and clang when
building for different platforms.
monodroid-glue.cc:1609:8: warning: declaration shadows a static data member of 'xamarin::android::internal::MonodroidRuntime' [-Wshadow]
void *api_dso_handle = nullptr;
^
monodroid-glue.cc:102:25: note: previous declaration is here
void *MonodroidRuntime::api_dso_handle = nullptr;
Fix by renaming the local variable.  No functionality changes result
from this fix.
MinGW builds report:
xa-internal-api.cc: In member function ‘virtual mono_bool xamarin::android::internal::MonoAndroidInternalCalls_Impl::monodroid_get_network_interface_up_state(const char*, mono_bool*)’:
xa-internal-api.cc:24:86: warning: unused parameter ‘ifname’ …
=> [C++] fix a handful of compiler warnings

build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/provisioning/xcode.csx
Context: https://github.com/xamarin/xamarin-android/issues/4907
A new script has been added to manage the Xcode version that we build
against on macOS.  Our three macOS build pools all appear to be using
Mojave agents, and as a result Xcode 11.3.1 will be used.  This script
will support a future migration to Catalina and will use the latest
Xcode currently available (11.6) when building on that macOS version.
=> [ci] Install and build with Xcode 11

build-tools/automation/azure-pipelines.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidCommonProject.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/Xamarin.Android.FSharp.ResourceProvider/pull/6
Xamarin.Android.FSharp.ResourceProvider 1.0.1 is now built for
`netstandard2.0` and published to an internal feed.
We should be able to enable F# tests under a `dotnet` context now.
The `_RemoveLegacyDesigner` MSBuild target was running, when it
shouldn't be for F# projects and adding a `Resource.designer.cs`
`@(Compile)` item. I needed to add a `$(Language)` check.
One workaround is for:
https://github.com/dotnet/sdk/issues/12954
We need to set `$(ProduceReferenceAssembly)` to `false` for .NET 5 F#
projects at the moment.
=> [tests] enable One .NET tests for F#

Documentation/release-notes/reword-xa5300-1.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
Context: https://github.com/xamarin/androidtools/pull/241
Update the XA5300 messages about SDK locations to sync with the new
wording from the corresponding androidtools string resources in
xamarin/androidtools#241 that mention some Visual Studio settings to check to
help resolve the errors.
=> [Xamarin.Android.Build.Tasks] Mention VS settings for XA5300

Documentation/release-notes/5071.md, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs, src/Xamarin.Android.Build.Tasks/Tasks/AndroidComputeResPaths.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/Aapt2Daemon.cs
Context: https://developercommunity.visualstudio.com/content/problem/1141659/android-build-process-never-stops.html
Context: https://feedback.devdiv.io/1141659
If you add the following file to a project:
<AndroidResource Include="Resources\drawable\.DS_Store" />
It can just be an empty file.
The `<Aapt2Compile/>` MSBuild task will block indefinitely with:
Executing compile -o C:\src\xamarin-android\samples\HelloWorld\obj\Debug\110\flat\ C:\src\xamarin-android\samples\HelloWorld\obj\Debug\110\res\drawable\.ds_store
In VS for Mac, the "stop" button will not stop the build either.
Clicking this button has no effect. At the command-line, Ctrl+C works
properly.
The above `aapt2 compile` command does not error and does not output
any files.
At first I found this code:
const char * const …
=> [Xamarin.Android.Build.Tasks] fix for `aapt compile` and .DS_Store

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultItems.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Context: https://github.com/xamarin/xamarin-android/pull/5071
In writing the fix for #5071, I noticed that our default wildcards for
.NET 6 projects bring in `.DS_Store` files for `@(AndroidAsset)` files
or `Resources\raw` files. I also noticed we bring in sub-directories
for `Resources`, but these are also invalid.
I fixed up all the wildcards, adding appropriate `Include` and
`Exclude`. At first I thought we should use `$(DefaultItemExcludes)`
and `$(DefaultExcludesInProjectFolder)`:
https://github.com/dotnet/sdk/blob/c7ac111a2438fc488229eed6f48a9d5298904bd2/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L22-L42
But they won't work due to the way `Exclude` works.
If you have:
<AndroidAsset Include="Assets\**\*" Exclude="**\.*\**" />
The `Exclude` …
=> [One .NET] improve default item groups

build-tools/xaprepare/xaprepare/Application/Program.ArchLinux.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/Linux.Arch.cs
This pull request adds support for pacman, the Arch Linux package manager.
It also implements the InitOS function in ConfigAndData/Dependencies/Linux.Arch.cs
=> [xaprepare] Implement support for ArchLinux pacman

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml, build-tools/automation/yaml-templates/run-nunit-tests.yaml
Context: https://stackoverflow.com/a/57999644
Our nunit3-console commands pass:
--workers=4
This helped to reduce test parallelism, which could slow the CI
machines to a crawl.
We aren't passing the same switch to instances where we run `dotnet
test`. We can do this by adding `-- NUnit.NumberOfTestWorkers=4` at
the end of the `dotnet test` command.
You can see this applied from the `dotnet test` log:
> dotnet test .\bin\TestDebug\netcoreapp3.1\Xamarin.Android.Build.Tests.dll --logger trx --filter "Name~BuildBasicApplication" --results-directory . --diag log.txt -- NUnit.NumberOfTestWorkers=4
From `log.txt`:
TpTrace Information: 0 : 13252, 1, 2020/09/03, 11:10:20.363, 3521331719316, vstest.console.dll, TestRunRequest.ExecuteAsync: Starting run with settings:TestRunCriteria: …
=> [build] dotnet test should set NUnit.NumberOfTestWorkers

build-tools/proprietary/proprietary.csproj, build-tools/proprietary/proprietary.targets, global.json, src/aapt2/aapt2.csproj, src/aapt2/aapt2.targets, src/apksigner/apksigner.csproj, src/bundletool/bundletool.csproj, src/bundletool/bundletool.targets, src/java-runtime/java-runtime.csproj, src/java-runtime/java-runtime.targets, src/manifestmerger/manifestmerger.csproj, src/manifestmerger/manifestmerger.targets, src/monodroid/monodroid.csproj, src/monodroid/monodroid.targets, src/proguard/proguard.csproj, src/proguard/proguard.targets, src/r8/r8.csproj, src/r8/r8.props, src/r8/r8.targets, src/sqlite-xamarin/sqlite-xamarin.csproj, src/sqlite-xamarin/sqlite-xamarin.targets
Context: https://github.com/xamarin/xamarin-android/pull/5064
Xamarin.Android has many "projects" that are `.csproj`, but do not actually compile a managed assembly.  Instead, the `Build` and `Clean` targets are overridden to perform other tasks, like compile Java.  When using a `Directory.Build.props` file to add a NuGet to all projects, these projects failed to build due to a NuGet error.
Nowadays there is a better solution for these types of projects that produces more correct projects with fewer side-effects: https://github.com/microsoft/MSBuildSdks/tree/master/src/NoTargets.
This commit converts these projects to SDK-style projects based on `Microsoft.Build.NoTargets`.
Additionally, we add the `Microsoft.Build.NoTargets` version to a `global.json` so the version is consistent among …
=> [csproj] Convert non-managed projects to SDK-style "Microsoft.Build.NoTargets" projects.

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-integrated-regression-tests.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
Context: https://github.com/xamarin/QualityAssurance/pull/3644
CI and Xamarin.Android.Build.Tests have been updated to reflect the
second round of regression test auditing.  All QA regression tests have
been merged into two total jobs, one per operating system type.
The following regression test categories have been removed, see
https://github.com/xamarin/QualityAssurance/pull/3644 for more info:
* Proguard - Deprecated tool.
* Multidex - Deprecated tool.
* ExplicitCrunch - Obsolete build option.
* TargetFrameworkTests - Missing coverage partially migrated to BuildBasicApplication and LibraryReferenceWithHigherTFVShouldDisplayWarning.
* ResourceCacheTests - Category was previously removed.
* PropertyCacheTests - Missing coverage partially migrated to BuildPropsBreaksConvertResourcesCases. …
=> [Xamarin.Android.Build.Tests] Import regression tests from job 2

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/5043
Instead of replacing `.s` with `.o` in the entire string, thus risking
breaking the path to the file, replace just the extension.
Co-authored by: @jonathanpeppers
=> Replace just the assembly source file extension

tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs, tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs, tests/MSBuildDeviceIntegration/Tests/MonoAndroidExportTest.cs, tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs, tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
Context: https://docs.nunit.org/articles/nunit/writing-tests/attributes/retry.html
Frequently, the `PerformanceTest` fails by just missing the time limit
by a couple ms:
Exceeded expected time of 4000ms, actual 4011.701ms
Downloading the log, there usually isn't performance regression. CI
machines' performance just seems to fluctuate.
I think we should add a `[Retry(2)]` to every `PerformanceTest` and
see if this helps.
In reading about `RetryAttribute`, I found:
> The argument you specify is the total number of attempts and *not*
> the number of retries after an initial failure. So `[Retry(1)]` does
> nothing and should not be used.
We have `[Retry(1)]` throughout our codebase a lot -- which does
nothing. I removed these for now, as I don't think they actually need
to become …
=> [tests] add/remove NUnit RetryAttribute

build-tools/create-packs/Microsoft.Android.Ref.proj, build-tools/create-packs/Microsoft.Android.Runtime.proj, build-tools/create-packs/Microsoft.Android.Sdk.proj, build-tools/create-packs/Xamarin.Android.Sdk.Lite.proj, build-tools/create-packs/global.json, global.json
Let's remove `build-tools/create-packs/global.json` and have a single
`global.json` file in the root. This allows us to remove the version
number for `Sdk="Microsoft.Build.NoTargets"` in several files.
We weren't able to do this in 079197ac because of the extra
`global.json` file that took precendence over the one in the root.
=> [build] consolidate global.json for Microsoft.Build.NoTargets

build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/automation/yaml-templates/use-dot-net.yaml
Context: https://docs.microsoft.com/dotnet/core/tools/dotnet-install-script
The `use-dot-net.yaml` template is leaving behind old installations of
.NET 5:
$ dotnet --list-sdks
3.1.201 [/Users/builder/.dotnet/sdk]
5.0.100-preview.6.20265.2 [/Users/builder/.dotnet/sdk]
5.0.100-preview.7.20307.3 [/Users/builder/.dotnet/sdk]
5.0.100-rc.1.20365.11 [/Users/builder/.dotnet/sdk]
5.0.100-rc.1.20411.10 [/Users/builder/.dotnet/sdk]
5.0.100-rc.1.20414.5 [/Users/builder/.dotnet/sdk]
5.0.100-rc.1.20426.3 [/Users/builder/.dotnet/sdk]
5.0.100-rc.2.20458.11 [/Users/builder/.dotnet/sdk]
We are currently using `dotnet-install.sh` or `dotnet-install.ps1` to
install nightly builds of .NET 5. These scripts basically download a
`.zip` file and extract them.
I added a new `remove_dotnet` parameter to delete the …
=> [build] clean up past .NET 5 installations

.gitignore, Configuration.props, Documentation/guides/OneDotNet.md, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/GenerateSupportedPlatforms.cs, build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml, src/Xamarin.Android.Build.Tasks/.gitignore, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetXamarinProject.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, tests/CodeBehind/BuildTests/CodeBehindBuildTestsDotNet.csproj, tests/CodeBehind/CommonSampleLibrary/CommonSampleLibraryDotNet.csproj
After bumping to .NET 5.0.100-rc.2.20458.11, we can now use:
<TargetFramework>net5.0-android</TargetFramework>
On the first try, this failed with:
error NETSDK1139: The target platform identifier android was not recognized.
Our SDK needs to specify:
<TargetPlatformSupported Condition=" '$(TargetPlatformIdentifier)' == 'Android' ">true</TargetPlatformSupported>
After doing this, everything seemed to work as before.
I updated tests so they will use `net5.0-android` going forward.
A second part of this change is the need to fill out
`$(TargetPlatformVersion)`, `@(AndroidSdkSupportedTargetPlatform)`,
and `@(SdkSupportedTargetPlatform)` similar to:
https://github.com/dotnet/sdk/blob/c43785736edc8d4bc927df3b557c1609d028cd93/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.WindowsSdkSupp …
=> [Microsoft.Android.Sdk] use net5.0-android $(TargetFramework)

Documentation/guides/BuildProcess.md
Merge `BuildProcess.md` with the content from the matching page on
docs.microsoft.com:
https://docs.microsoft.com/xamarin/android/deploy-test/building-apps/build-process
Changes: https://github.com/MicrosoftDocs/xamarin-docs/commits/93e6358aac2ade44e8b800f066405b8bc8df2510/docs/android/deploy-test/building-apps/build-process.md
* MicrosoftDocs/xamarin-docs@93e6358a: Bookmark fixes
* 6 insertions(+), 6 deletions(-)
* MicrosoftDocs/xamarin-docs@a3e6e567: [android] Correct AndroidBundleConfigurationFile release info
* 1 insertion(+), 1 deletion(-)
From MicrosoftDocs/xamarin-docs@93e6358a, standardize the anchors like
`<a name="Build_Actions" />` to `<a name="Build_Actions"></a>`.
From MicrosoftDocs/xamarin-docs@a3e6e567, correct the "Added in"
sentence to Xamarin.Android 10.3 for …
=> [docs] Merge BuildProcess.md from MicrosoftDocs/xamarin-docs@93e6358a

src/Mono.Android/metadata
When binding API-30, we disabled a few overloads of `java.util.Map.of (...)` that took more than 14 parameters, as we could not support them with C# `Action`/`Func` constructs.
With https://github.com/xamarin/java.interop/pull/632, we now support any number of parameters, so these methods can be enabled.
=> [Mono.Android] Enable Map.Of methods that have more than 14 parameters.

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs, tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
We currently copy all the assets for all Library Projects
into one main directory. This can slow down build times
if the assets are large. So what we should do is use those
assets in place.
This will also allow us to consume .nuget assets in place as
well sometime in the future.
=> [Xamarin.Android.Build.Tasks] Dont copy assets for Library Projects.

.external, Documentation/release-notes/5112.md
Fixes: https://github.com/xamarin/xamarin-android/issues/4996
Changes: https://github.com/xamarin/monodroid/compare/92b9cce8dacad8b7ce48ddbcf9e5247598cd2ccd...a9ae74d474583211c153b2b868417383afd4cb3a
* xamarin/monodroid@a9ae74d47: Bump to xamarin/android-sdk-installer/master@1928338b (#1113)
* xamarin/monodroid@4afc0d960: [RuntimeService] Update Shared runtime to use `getExternalFilesDir` (#1111)
=> Bump to xamarin/monodroid/master@a9ae74d4

Documentation/release-notes/5113.md, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Compile.cs, src/Xamarin.Android.Build.Tasks/Tasks/AndroidComputeResPaths.cs, src/Xamarin.Android.Build.Tasks/Tasks/CollectNonEmptyDirectories.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
Fixes: https://developercommunity.visualstudio.com/content/problem/1141659/android-build-process-never-stops.html
Context: https://www.nuget.org/packages/Xamarin.PdfView.Android/
In addition to:
<AndroidResource Include="Resources\values\.gitignore" />
The Xamarin.PdfView.Android NuGet package causes the `<Aapt2Compile/>`
MSBuild task to hang indefinitely. This is a package last updated
11/26/2015 that has a very weird file layout:
Xamarin.PdfView.Android.1.0.4.nupkg
lib\PdfViewBinding.dll
__AndroidLibraryProjects__.zip
library_project_imports\res\.gitignore
The `res` directory is otherwise empty!
The `<CollectNonEmptyDirectories/>` MSBuild task returned:
_LibraryResourceFiles
obj\Debug\lp\0\jl\res\.gitignore
FilesCache = obj\Debug\lp\0\jl\res\..\files.cache
Hash = obj\Debug\lp\0.stamp …
=> [Xamarin.Android.Build.Tasks] .gitignore files in __AndroidLibraryProjects__.zip

build-tools/create-packs/Microsoft.Android.Sdk.proj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
Context: https://github.com/dotnet/installer/blob/97f447f228824c0217d2c8b845b003118673ff22/src/redist/targets/GenerateBundledVersions.targets#L208-L218
Context: https://docs.microsoft.com/dotnet/core/deploying/trimming-options
Right now we are modifying the `@(ResolvedFileToPublish)` item group
and setting `%(IsTrimmable)` for `Mono.Android.dll`,
`Mono.Android.Export.dll`, and `Java.Interop.dll`. Instead we can set
this metadata on `@(KnownFrameworkReference)`, which is the way that
`Microsoft.NETCore.App` is setup. This way these assembly references
will be "trimmable" by default.
We should also rename `Microsoft.Android.Sdk.Linker.targets` to
`Microsoft.Android.ILLink.targets` to better match the naming in .NET 5.
=> [linker] set %(IsTrimmable) for @(KnownFrameworkReference)

Documentation/release-notes/5107.md, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
@mattleibow was hitting an error building a `.sln` file with `/m` on
Windows:
obj\Release\100\android\manifest\AndroidManifest.xml(7,0): error APT2260: resource mipmap/ic_launcher (aka com.companyname.skiasharpsample:mipmap/ic_launcher) not found.
obj\Release\100\android\manifest\AndroidManifest.xml(7,0): error APT2260: resource string/app_name (aka com.companyname.skiasharpsample:string/app_name) not found.
obj\Release\100\android\manifest\AndroidManifest.xml(7,0): error APT2260: resource mipmap/ic_launcher_round (aka com.companyname.skiasharpsample:mipmap/ic_launcher_round) not found.
obj\Release\100\android\manifest\AndroidManifest.xml(9,0): error APT2260: resource style/MainTheme.Splash (aka com.companyname.skiasharpsample:style/MainTheme.Splash) not found. …
=> [Xamarin.Android.Build.Tasks] audit WorkingDirectory usage in <Aapt2Link/>

build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/Microsoft.Android.Ref.proj, src/Mono.Android.Export/Mono.Android.Export.csproj, src/Mono.Android/Mono.Android.csproj
The `Microsoft.Android.Ref.nupkg` file is meant to only contain
reference assemblies, and we are currently shipping the *real* assembly.
The actual runtime assembly is found in the runtime pack for each RID:
* `Microsoft.Android.Runtime.android.21-arm.nupkg`
* `Microsoft.Android.Runtime.android.21-arm64.nupkg`
* `Microsoft.Android.Runtime.android.21-x86.nupkg`
* `Microsoft.Android.Runtime.android.21-x64.nupkg`
To fix this, we need to set `$(ProduceReferenceAssembly)` for each
assembly we distribute in `Microsoft.Android.Ref`.
The MSBuild targets in dotnet/sdk already handle passing the correct
reference assembly to the `<Csc/>` MSBuild task, and passing us the
runtime assembly to place in `.apk` files.
I also cleaned up `Mono.Android.Export.csproj` so we don't need to
clear …
=> [Microsoft.Android.Ref] use reference assembly for Mono.Android.dll

src/Mono.Android/metadata
Context: https://github.com/xamarin/xamarin-android/issues/5027
Context: https://github.com/xamarin/java.interop/issues/699
There is an issue with implementing `Android.Database.ICursor` in API-30+.  A default method [`setnotificationUris (ContentResolver, List<Uri>)`](https://developer.android.com/reference/android/database/Cursor#setNotificationUris(android.content.ContentResolver,%20java.util.List%3Candroid.net.Uri%3E)) was added in API-29.  If a user tries to bind a Java class that implements `ICursor`, we generate invalid C# code when we generate the interface invoker method:
```
var uris = (global::System.Collections.Generic.IList`1)global::Java.Lang.Object.GetObject<global::System.Collections.Generic.IList`1> (native_uris, JniHandleOwnership.DoNotTransfer);
```
The `generator` fix …
=> [Mono.Android] Remove default method ICursor.SetNotificationUris that causes binding error.

src/Mono.Android/Android.Runtime/AndroidEnvironment.cs, src/Mono.Android/Android.Runtime/AndroidRuntime.cs, src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android.Runtime/Logger.cs, src/Mono.Android/Java.Interop/Runtime.cs, src/Mono.Android/Java.Interop/TypeManager.cs, src/monodroid/jni/monodroid-glue-internal.hh, src/monodroid/jni/monodroid-glue.cc, tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs
Context: https://github.com/xamarin/xamarin-android/pull/4914
Context: https://github.com/xamarin/xamarin-android/commit/d583b7c215fe9be2f732b4a52423be0aea7f0809
The .NET5 version of the Mono runtime "hijacked" `__Internal` for its
own purposes and the change causes us trouble when trying to resolve
p/invokes from our managed code to our runtime.  Instead we now use
`xa-internal-api` (added in d583b7c2) to specify the p/invoke library
name.
=> Stop using `__Internal` in our p/invoke calls

build-tools/automation/yaml-templates/use-dot-net.yaml
Context: https://build.azdo.io/4072655
Context: https://docs.microsoft.com/powershell/module/microsoft.powershell.management/remove-item
I saw the build error:
Remove-Item : Cannot find path 'C:\Program Files\dotnet\' because it does not exist.
I probably caused this by canceling a build. Whoops. I think we need a
`Test-Path` check to only delete if the file exists:
if ("${{ parameters.remove_dotnet }}" -eq $true -And (Test-Path $DotNetRoot)) {
Remove-Item -Recurse $DotNetRoot -Verbose
}
`Remove-Item` does not appear to have an option to prevent failure if
the path does not exist.
The macOS side seems like it would already work if the directory did
not exist:
rm -rfv $DOTNET_ROOT
=> [build] check if $DotNetRoot exists before deletion

Documentation/proposals/OneDotNetEmbeddedResources.md
Context: https://github.com/xamarin/xamarin-android/issues/2441
See `OneDotNetEmbeddedResources.md` for the new spec for
`@(AndroidLibrary)` and removal of `EmbeddedResource` usage in
Xamarin.Android class libraries.
Future proposals can be commited to `Documentation/proposals`. When
implemented, the proposal can be reworked and moved to
`Documentation/guides` if it is still useful
Easiest to read [here](https://github.com/jonathanpeppers/xamarin-android/blob/spec-embeddedresource/Documentation/proposals/OneDotNetEmbeddedResources.md).
=> [spec] for @(AndroidLibrary) and avoiding EmbeddedResource

build-tools/create-packs/Xamarin.Android.Sdk.Lite.proj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultItems.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.props, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.props, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Xamarin.Android.Sdk.Lite.props, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
We were setting several MSBuild property defaults in
`Microsoft.Android.Sdk.props`. The problem with this, is that it
doesn't enable the properties to be overridden in a .csproj file at
all.
The import ordering should be:
1. `Microsoft.Android.Sdk.props` - only contains properties that
cannot be overridden, or properties that the `.csproj` might need
to rely on.
2. The `.csproj` file
3. `Microsoft.Android.Sdk.targets`
a. `Microsoft.Android.Sdk.DefaultProperties.props`
b. `Microsoft.NET.Sdk/Sdk.targets`
4. Any other `.targets` files where we have functionality split up.
I took the opportunity to reorganize/cleanup a few other things:
* `@(ProjectCapability)` should go in
`Microsoft.Android.Sdk.DefaultItems.targets`.
* Lots of usage of `$(MSBuildThisFileDirectory)` that wasn't needed.
* …
=> [One .NET] fix <Import/> ordering

src/Microsoft.Android.Sdk.ILLink/ApplyPreserveAttributeBase.cs, src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj, src/Microsoft.Android.Sdk.ILLink/SetupStep.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/ApplyPreserveAttribute.cs
The ApplyPreserveAttribute susbtep  was not (yet?) upstreamed, so
make it build and add it to the pipeline and run it before other
substeps to not break ac5269d54e518d9db6dac31e49de26c8b288662c fix.
=> [net5/illink] Add ApplyPreserveAttribute substep

Documentation/release-notes/5107.md, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
@mattleibow was hitting an error building a `.sln` file using
`msbuild /m` on Windows:
> msbuild /m …
obj\Release\100\android\manifest\AndroidManifest.xml(7,0): error APT2260: resource mipmap/ic_launcher (aka com.companyname.skiasharpsample:mipmap/ic_launcher) not found.
obj\Release\100\android\manifest\AndroidManifest.xml(7,0): error APT2260: resource string/app_name (aka com.companyname.skiasharpsample:string/app_name) not found.
obj\Release\100\android\manifest\AndroidManifest.xml(7,0): error APT2260: resource mipmap/ic_launcher_round (aka com.companyname.skiasharpsample:mipmap/ic_launcher_round) not found.
obj\Release\100\android\manifest\AndroidManifest.xml(9,0): error APT2260: resource style/MainTheme.Splash (aka com.companyname.skiasharpsample:style/MainTheme.Splash) not found. …
=> [Xamarin.Android.Build.Tasks] audit WorkingDirectory usage in <Aapt2Link/> (#5107)

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs
Fixes https://work.azdo.io/1216790
We had this very weird situation where the `Aapt2Compile` step
would hang indefinately. This did not happen on every machine,
just on a particular customer's setup.
It turns out that `Environment.ProcessorCount` was returning 1.
This would cause the following code to return a value of 0.
Math.Min(Environment.ProcessorCount -1, DefaultMaxAapt2Daemons);
We did not have any protection in place to guard against getting
a 0 from this code. As a result we tried to spawn 0 instances of
aapt2. This would result in the `Aapt2Compile` task to wait for
jobs that were never going to be completed.
=> [Xamarin.Android.Build.Tasks] Guard against only having 1 processor.

Documentation/release-notes/5139.md
Fixes: https://github.com/xamarin/java.interop/issues/682
Fixes: https://github.com/xamarin/java.interop/issues/717
Context: https://github.com/xamarin/java.interop/issues/719
Changes: https://github.com/xamarin/java.interop/compare/a807961666bc48b81d46aa16bc02baf9bf05bd45...79d95334219690fc51c30baeccaf702542afeba1
* xamarin/java.interop@79d95334: [generator] Use GC.KeepAlive for reference type method parameters. (#722)
* xamarin/java.interop@1a19ec04: [Xamarin.Android.Tools.Bytecode] Hide Kotlin nested types inside (#723)
* xamarin/java.interop@24a9abdb: [Xamarin.Android.Tools.ApiXmlAdjuster] Find app.android.IntentService (#718)
=> Bump to xamarin/Java.Interop/d16-8@79d95334

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
The `BaseTest.RunProcess` is redirecting the standard and error output,
so that it can be captured. It didn't work, because it was not using the
output related events and so if there was enough output, we got dead
lock and timeout as a result.
Context: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.standarderror
Example behaviour before the fix - notice the timeout:
RunProcess: C:\Users\rodo\android-toolchain\sdk\platform-tools\adb.exe  logcat -d > "C:\Users\rodo\git\xa-master\bin\TestDebug\temp\otNetInstallAndRunTrueFalse\logcat-failed.log"
RunProcess timed out: C:\Users\rodo\android-toolchain\sdk\platform-tools\adb.exe  logcat -d > "C:\Users\rodo\git\xa-master\bin\TestDbug\temp\DotNetInstallAndRunTrueFalse\logcat-failed.log"
=> [tests] Fix process output collection

Documentation/release-notes/androidresgenextraargs.md, src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs
Context: https://github.com/xamarin/xamarin-android/pull/5131
Context: https://github.com/xamarin/monodroid/commit/90c791f89ea065680fafd3ab8301142fb4a9ff18
In #5131, I need to modify `obj\$(Configuration)\lp\map.cache` so the
full file name is listed for each row. I was hitting a collision for
similarly named files such as `Foo.dll` and `Foo.aar`. This led me to
fix all callers of `AssemblyIdentifyMap`, such as
`Aapt.ExpandString()` and `Aapt2Link.ExpandString()`.
Reading `ExpandString()`, it supports some very weird syntax, which
would be something like:
<AndroidResgenExtraArgs>-I ${library.imports:foo.jar}</AndroidResgenExtraArgs>
Looking at xamarin/monodroid/master@90c791f8, this was a feature added
for the Amazon Fire Phone in ~Oct 2014. Amazon placed
`AndroidResource` files inside a …
=> [Xamarin.Android.Build.Tasks] remove ${library.imports:} syntax for $(AndroidResgenExtraArgs)

Documentation/guides/OneDotNet.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.props, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EnvironmentContentTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
Context: https://docs.microsoft.com/dotnet/core/deploying/trimming-options
This sets up sensible defaults for the linker while supporting the
legacy `$(AndroidLinkMode)` MSBuild property.
For `Release` builds by default:
* `PublishTrimmed=true`
* `TrimMode=link`
I documented these settings in `OneDotNet.md`.
This may cause some tests to fail because we are using `TrimMode=Link`, we'll see what happens.
/cc @rolfbjarne
=> [One .NET ] consolidate linker MSBuild properties

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs
The `RunAdbCommand` is not running a shell, so we cannot use output
redirection like:
RunAdbCommand ($"logcat -d > \"{deviceLog}\"");
So instead just write the output to the file ourselves.
Before the output of the command was:
Invalid filter expression 'C:\...\bin\TestDebug\temp\DotNetInstallAndRunTrueFalse\logcat-failed.log'
Usage: logcat [options] [filterspecs]
options include:
-s              Set default filter to silent. Equivalent to filterspec '*:S'
-f <file>, --file=<file>               Log to file. Default is stdout
-r <kbytes>, --rotate-kbytes=<kbytes>
Rotate log every kbytes. Requires -f option
...
So we didn't get the logcat output we wanted.
=> [tests] Fix logcat output saving

src/monodroid/jni/android-system.cc, src/monodroid/jni/android-system.hh, src/monodroid/jni/basic-android-system.hh, src/monodroid/jni/basic-utilities.cc, src/monodroid/jni/basic-utilities.hh, src/monodroid/jni/embedded-assemblies-zip.cc, src/monodroid/jni/embedded-assemblies.cc, src/monodroid/jni/embedded-assemblies.hh, src/monodroid/jni/helpers.hh, src/monodroid/jni/jni-wrappers.hh, src/monodroid/jni/monodroid-glue-internal.hh, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/platform-compat.hh, src/monodroid/jni/strings.hh
This commit introduces a couple of top-level classes to work with
strings allocated either on stack or from the heap, which are always
released when leaving the scope.  The classes allocate string buffer on
stack if the size doesn't exceed a certain maximum value (provided as a
template parameter) or, if the space needed is more than size of the
on-stack buffer, allocate memory from heap as necessary.  If we choose
the stack allocation size correctly, this has the advantage of being
very quick since no calls are necessary for (de)allocation of memory -
it's either part of the function prolog/epilog where appropriate stack
for local variables space is reserved, or part of a scope setup which
operation also isn't expensive.
Two introduced classes are `static_local_string` and …
=> [runtime] Introduce simple local/stack string classes

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.props, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidCommonProject.cs
I noticed build output for `HelloAndroid.csproj` emits a collection of
junk files & directories that we do not need:
> ls -r -n .\HelloAndroid\bin\Debug\net5.0-android\
android.21-arm64
android.21-x86
ref
com.microsoft.net5.helloandroid-Signed.apk
com.microsoft.net5.helloandroid.apk
HelloAndroid.deps.json
HelloAndroid.dll
HelloAndroid.pdb
android.21-arm64\publish
android.21-arm64\ref
android.21-x86\publish
android.21-x86\ref
ref\HelloAndroid.dll
First issue to fix, is we shouldn't set `$(ProduceReferenceAssembly)`
for application projects. Applications shouldn't reference other
applications, so there isn't a need for `$(ProduceReferenceAssembly)`
to be `true` by default.
Xamarin.Android class libraries can have continue to set
`ProduceReferenceAssembly=true` by default as provided by the …
=> [One .NET] cleanup build output

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Bump XliffTasks to the latest version referenced by
dotnet/arcade/master@1b5940fd.
This will help prevent version conflicts for the NuGet package in case
any of xamarin-android's submodules update their XliffTasks references
to this newer version.
Changes: https://github.com/dotnet/xliff-tasks/compare/fdf42c08a386935000f64b1e0fd7d73fa9c961d5...975065e08307a459dc2649b1c852f5c4cafd2f91
=> [build] Bump XliffTasks version

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/CodeBehindTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EmbeddedDSOTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EnvironmentContentTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/MakeBundleTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BuildHelper.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Context: https://build.azdo.io/4092693
The `SolutionBuildSeveralProjects` test has been failing with a really
short build log:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1333,2): error MSB3374: The last access/last write time on file "C:\a\1\s\bin\TestRelease\temp\SolutionBuildSeveralProjects\Lib9\bin\Debug\Lib9.dll.mdb" cannot be set. The process cannot access the file 'C:\a\1\s\bin\TestRelease\temp\SolutionBuildSeveralProjects\Lib9\bin\Debug\Lib9.dll.mdb' because it is being used by another process. [C:\a\1\s\bin\TestRelease\temp\SolutionBuildSeveralProjects\App1\App1.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe …
=> [tests] cleanup Verbosity in MSBuild tests

build-tools/automation/CredScanSuppressions.json, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsMapsApplicationProject.cs
Context: https://build.azdo.io/4095069
I started seeing two CredScan failures on PRs today. The first:
external\android-api-docs\docs\Mono.Android\en\Javax.Crypto\ISecretKey.xml(2,): error : SecretinFile : {{Searcher}}CSCAN-GENERAL0060
{{Code}}See ISecretKey.xml line 2 for the code resulting in match
{{Info}}Found General Password.
{{Suggest}}Validate file contains secrets, remove, roll credential, and use approved store. For additional information on secret remediation see https://aka.ms/credscan
We had similar suppressions for other files, so I added an exception
for this one in `CredScanSuppressions.json`.
The second:
src\Xamarin.Android.Build.Tasks\Tests\Xamarin.ProjectTools\Android\XamarinFormsMapsApplicationProject.cs(65,): error : SecretinFile : {{Searcher}}CSCAN-GOOG0010 …
=> [CredScan] fix credential scanner failures

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
Context: https://developercommunity.visualstudio.com/content/problem/1073405/index.html
Context: https://github.com/mono/monodevelop/blob/fb12ccb7f4245eca20803661deaa37ead0ec35af/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectFile.cs#L336-L337
In Visual Studio for Mac, `Xamarin.Android.Build.Tasks.csproj` was not
loading due to:
Error while trying to load the project '/Users/macuser/Projects/xamarin-android/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj': Invalid value for Link property
The problem was that the `%(Link)` metadata for some of the files in the
project started with `..\`, which Visual Studio for Mac currently
rejects.  For comparison, Visual Studio on Windows accepts `%(Link)`
metadata starting with `..\` but hides the files from the Solution …
=> [build] Add VSMac workaround for %(Link) metadata

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://build.azdo.io/4092693
The `SolutionBuildSeveralProjects` is failing on CI occasionally with:
Xamarin.Android.Common.targets(1333,2): error MSB3374: The last access/last write time on file "C:\a\1\s\bin\TestRelease\temp\SolutionBuildSeveralProjects\Lib9\bin\Debug\Lib9.dll.mdb" cannot be set. The process cannot access the file 'C:\a\1\s\bin\TestRelease\temp\SolutionBuildSeveralProjects\Lib9\bin\Debug\Lib9.dll.mdb' because it is being used by another process.
Or another example hit 2 errors:
Xamarin.Android.Common.targets(1333,2): error MSB3375: The file "C:\a\1\s\bin\TestRelease\temp\SolutionBuildSeveralProjects\Lib4\bin\Debug\Lib4.dll.mdb" does not exist.
Xamarin.Android.Common.targets(1333,2): error MSB3374: The last access/last write time on file …
=> [Xamarin.Android.Build.Tasks] fix -m:4 collision in _ConvertPdbFiles

src/Mono.Android/metadata
Context: https://github.com/xamarin/java.interop/issues/699
In https://github.com/xamarin/xamarin-android/pull/5124 we removed `Cursor.setNotificationUris (...)` because it causes binding problems when it is overridden.  `Cursor.getNotificationUris ()` was not removed because it was believed that the issue was confined to parameters, however it affects return values as well.
Remove default interface method `Cursor.getNotificationUris ()` until `generator` can be properly fixed.
=> [Mono.Android] Remove problematic default interface method Cursor.getNotificationUris.

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs, tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs
To make sure we don't get activity displayed message from previous run.
`WaitForActivityToStart` doesn't know the `PID`, so it can match the
previous run.
I was curious why CI test run doesn't show the crash I see when running
manualy on hardware device. Let see whether it will catch it with this
change.
Update: it works and the tests fails now as it should. Opened issue
https://github.com/xamarin/xamarin-android/issues/5166,
which should be fixed by
https://github.com/xamarin/xamarin-android/pull/5145
=> [tests] Clear adb log after running the test

Configuration.props, Documentation/release-notes/bundletool-1.2.0.md
Context: https://github.com/google/bundletool/releases/tag/1.2.0
Changes (from release notes)
0.15.0
* Support output-zip option for bundletool extract-apks command that
allows to output requested apks into zip archive.
* Forbid application downgrades in bundletool install-multiple-apks.
1.0.0
* Merge unconditional install-time modules into base module by
default.
* Add --overwrite (overwriteOutput) option to BuildBundleCommand.
1.1.0
* ADB support for install-multi-apks
* Verbose log for build-apks
* Fix Wear APK path resolution
1.2.0
* Support options to generate system APKs with uncompressed native
libraries and uncompressed dex.
=> Bump to bundletool 1.2.0

.external
Changes: https://github.com/xamarin/monodroid/compare/1562e30689e60b884a0b229a233bb6d7bf230a08...1ac5333ec5e90b4e1fb9b324714811effdede37f
* xamarin/monodroid@1ac5333ec: Bump to xamarin/android-sdk-installer/main@30bf71f1 (#1116)
=> Bump to xamarin/monodroid/master@1562e306

Documentation/release-notes/r8-2.1.67.md, src/r8/build.gradle
Context: https://mvnrepository.com/artifact/com.android.tools/r8/2.1.67
Context: https://r8.googlesource.com/r8/+/cc1556056e7317b5b4350c6d92800895e9115550
Google appears to have made several releases to r8 in the past few months; we should update.
=> Bump to r8 2.1.67

build-tools/automation/azure-pipelines.yaml
A new git repository has been created for the Android designer and other
related sources, and the old `designer` repo has been deprecated.  Our
YAML pipeline has been updated to track this new repo so that we will
continue to run integration tests against the latest designer sources.
=> [ci] Use new UITools repo for designer testing

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/GenerateSupportedPlatforms.cs, build-tools/automation/azure-pipelines.yaml
Context: https://github.com/dotnet/sdk/commit/37d5ade0f863258a78313b8421eae0eb02d25c69
Using the latest .NET 5 rc 2 build fails with:
Microsoft.NET.TargetFrameworkInference.targets(213,5): error NETSDK1140: 30 is not a valid TargetPlatformVersion for android. Valid versions include:
Microsoft.NET.TargetFrameworkInference.targets(213,5): error NETSDK1140: None
`@(SdkSupportedTargetPlatform)` was renamed to
`@(SdkSupportedTargetPlatformVersion)`. We should fix this and bump to
a later build of .NET 5.0 rc2 to account for this change.
We should also rename `@(AndroidSdkSupportedTargetPlatform)` to
`@(AndroidSdkSupportedTargetPlatformVersion)` to match
`@(WindowsSdkSupportedTargetPlatformVersion)`.
/cc @rolfbjarne I don't know if you have run into this for iOS yet.
=> Bump to .NET 5.0.100-rc.2.20480.7

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
Context: https://build.azdo.io/4092693
The `LibraryProjectTargetsDoNotBreak` test is occasionally failing on
macOS with:
_CreateAar should not be skipped on second build!
Expected: False
But was:  True
I can't reproduce this locally, even with `[Repeat (10)]`.
I think what is happening is the `Touch()` calls only have a 1 second
resolution as mentioned by the comments in `XamarinProject`:
// LastWriteTime is inaccurate without milliseconds, but neither mono FileSystemInfo nor UnixFileSystemInfo (in Mono.Posix)
// handles this precisely. And that causes comparison problem.
// To avoid this issue, we compare time after removing milliseconds field here.
Adding a `System.Threading.Thread.Sleep(1000)` to see if this helps.
I don't think we can do something like `DateTime.UtcNow.AddSeconds(1)`, …
=> [tests] add delay for LibraryProjectTargetsDoNotBreak

build-tools/automation/azure-pipelines-oss.yaml
Our OSS builds have been producing .pkg and .vsix installer files,
however we seem to have neglected an attempt to upload these artifacts.
The OSS YAML pipeline has been updated to upload these artifacts for
external consumption as needed.
=> [ci] Copy and publish OSS installer artifacts

src/Microsoft.Android.Sdk.ILLink/PreserveRegistrations.cs, src/Microsoft.Android.Sdk.ILLink/SetupStep.cs
Fix: https://github.com/xamarin/xamarin-android/issues/5156
Create new substep to preserve parts needed for JNI types registration
in `Android.Runtime.AndroidTypeManager.RegisterNativeMembers`. These
are preserved by `MonodroidMarkStep` in the XA linker. We cannot derive
from ILLink's MarkStep in NET5 as the API is not and will not be public.
Thus we need to preserve the API in the new separate substep
`PreserveRegistrations`.
Note: temporarily we need to use reflection to be able to call
`void AnnotationStore::AddPreservedMethod (MethodDefinition key, MethodDefinition method)`
method. This can be removed once we have Microsoft.NET.ILLink containing
https://github.com/mono/linker/commit/e6dadc995a834603e1178f9a1918f0ae38056b29
Example of additions in `Android.App.Activity` type
in …
=> [illink] Preserve API needed for registration

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-timezoneinfo-tests.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/xaprepare/xaprepare/Application/AndroidToolchainComponent.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_AndroidTestDependencies.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_EmulatorTestDependencies.cs, build-tools/xaprepare/xaprepare/Steps/Step_Android_SDK_NDK.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallJetBrainsOpenJDK.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj
The `AndroidToolchain` scenario previously used for installing Android
test dependencies has been replaced by two new scenarios responsible
for less work overall.  The `AndroidTestDependencies` scenario is
responsible for installing both JDKs, as well as the core Android SDK
components required for all test jobs.  The `EmulatorTestDependencies`
scenario is responsible for installing the Android SDK `emulator` tool,
as well as the `x86_64` system image that is used for emulator tests.
The majority of test jobs now skip the download of roughly 2 GB of
components.  The unused `x86` emulator system image has been removed,
and the `x86_64` system image, emulator, docs, and m2repository
components should not be needed for tests that don't require a device.
Jobs requiring emulator components …
=> [ci] Improve test dependency installation times

build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml
Related to VS #[1225839](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1225839)
As part of the GitHub Single Sign-On (SSO) effort, GitHub service accounts (i.e., any GitHub account not linked with an individual Microsoft account) will be denied GitHub org (Microsoft, Xamarin) access rights. The Xamarin.Android pipelines currently make use of a GitHub token tied to the Xamarin org (e.g., a Microsoft org).  That token is passed to Provisionator.  This change involves replacing that token with a GitHub token tied to a GitHub service account that does not have access to any Microsoft GitHub org (Microsoft or Xamarin).
=> Utilize GitHub token in compliance with GitHub service account restrictions

src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs
Add the automatic changes that Visual Studio makes when saving the
resource files so there won't be any need to worry about them getting
included unintentionally as part of an unrelated future change to the
`.resx` file.
=> [l10n] Tidy generated resource files

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/Tasks/ConvertResourcesCases.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/AndroidResourceTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ConvertResourcesCasesTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs
The `<ConvertResourcesCases/>` loads the `acw-map.txt` file and passes
the dictionary throughout several methods in `AndroidResource`.
However, this dictionary is completely unused throughout?
Since 1886e6f1, the logic using `acw-map.txt` was moved to the
`<ConvertCustomView/>` MSBuild task. We no longer need to use this
file in the `<ConvertResourcesCases/>` task.
At the time `<ConvertResourcesCases/>` runs (before `Build`),
`acw-map.txt` does not even exist. It is created by the
`<GenerateJavaStubs/>` MSBuild task, that runs after `Build`.
I was working on a performance improvement, where I was attempting to
use `acw-map.txt` -- unfortunately an empty dictionary.
To eliminate confusion and clean things up, I removed all usage of
`acw-map.txt` in the `<ConvertResourcesCases/>` MSBuild …
=> [Xamarin.Android.Build.Tasks] remove acw-map.txt usage in <ConvertResourcesCases/>

Documentation/release-notes/5188.md, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Designer.targets, src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Compile.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs, src/Xamarin.Android.Build.Tasks/Tasks/AndroidComputeResPaths.cs, src/Xamarin.Android.Build.Tasks/Tasks/ConvertCustomView.cs, src/Xamarin.Android.Build.Tasks/Tasks/ConvertResourcesCases.cs, src/Xamarin.Android.Build.Tasks/Tasks/Lint.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/Aapt2Tests.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Reviewing a customer's large solution, `$(_AndroidResourceNameCaseMap)`
contains a ~20,000 character string that is logged and parsed multiple
times throughout the build.
Improvements:
* The `<AndroidComputeResPaths/>` MSBuild task can create a
`Dictionary<string,string>` directly and store it via
`RegisterTaskObject`. No need to create a giant string at all.
* `<AndroidComputeResPaths/>` shouldn't log all the output values, as
it adds hundreds of log messages per `LogDebugTaskItems()` call in
this customer's project. The surrounding log has enough context, so
these messages are not needed.
* `MonoAndroidHelper.LoadResourceCaseMap` should only be called when
the value is actually needed. This is normally for error messages.
* `MonoAndroidHelper.LoadResourceCaseMap` can call …
=> [Xamarin.Android.Build.Tasks] remove $(_AndroidResourceNameCaseMap) for performance

.editorconfig, Documentation/guides/building-apps/build-properties.md, build-tools/Xamarin.Android.Tools.BootstrapTasks/result-packaging.targets, build-tools/cmake/xa_macros.cmake, build-tools/installers/create-installers.targets, build-tools/wrap.sh/asan.sh, build-tools/wrap.sh/ubsan.sh, build-tools/xaprepare/xaprepare/Resources/Configuration.OperatingSystem.props.in, build-tools/xaprepare/xaprepare/Steps/Step_GenerateFiles.cs, src/Mono.Android/Test/Mono.Android-Tests.csproj, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tasks/NdkUtils.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingReleaseNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/monodroid/CMakeLists.txt, src/monodroid/jni/android-system.cc, src/monodroid/jni/basic-utilities.cc, src/monodroid/jni/embedded-assemblies-zip.cc, src/monodroid/jni/embedded-assemblies.cc, src/monodroid/jni/globals.hh, src/monodroid/jni/monodroid-glue.cc, src/monodroid/monodroid.targets, src/sqlite-xamarin/CMakeLists.txt, tests/Xamarin.Forms-Performance-Integration/Droid/Xamarin.Forms.Performance.Integration.Droid.csproj
We now support the [`clang-tidy`][0] static analysis of the C++ code
and the [`ASAN`][1] and [`UBSAN`][2] clang sanitizers on the runtime to find issues
that cannot be detected by static analysis. All of the tools are shipped
with the Android NDK which currently ships the clang 9 toolchain.
All of the tools require separate builds of the native code.
`clang-tidy` builds the entire codebase to generate an AST and then
analyze it, reporting possible errors but it does not output any
binaries.
The two runtime sanitizers, however, instrument the generated code in
numerous ways thus making it much (up to 3x) slower to execute.
Therefore, we now build our native code 4 additional times - for each
sanitizer in both `Debug` and `Release` modes. The output binaries have
the …
=> [C++] Add support for native code static checkers and sanitizers

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/MacOS.cs
Context: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4145754&view=results
All of our macOS test jobs are currently blocked during environment
provisioning due to the following error:
```
stderr | Error: Calling Installation of mingw-w64 from a GitHub commit URL is disabled! Use 'brew extract mingw-w64' to stable tap on GitHub instead.
Failed to install some required programs.
System.InvalidOperationException: Failed to install some required programs.
at Xamarin.Android.Prepare.OS.EnsureDependencies () [0x0050e] in <6cf28c0130c14a06a5b36a148f5fad5c>:0 
at Xamarin.Android.Prepare.OS.Init () [0x0008b] in <6cf28c0130c14a06a5b36a148f5fad5c>:0 
at Xamarin.Android.Prepare.Context.Init (System.String scenarioName) [0x001dc] in <6cf28c0130c14a06a5b36a148f5fad5c>:0 
at …
```
=> [xaprepare] Remove mingw installation formula

src/Mono.Android/Android.Runtime/CharSequence.cs, src/Mono.Android/Android.Runtime/InputStreamAdapter.cs, src/Mono.Android/Android.Runtime/InputStreamInvoker.cs, src/Mono.Android/Android.Runtime/JavaArray.cs, src/Mono.Android/Android.Runtime/JavaCollection.cs, src/Mono.Android/Android.Runtime/JavaDictionary.cs, src/Mono.Android/Android.Runtime/JavaList.cs, src/Mono.Android/Android.Runtime/JavaSet.cs, src/Mono.Android/Android.Runtime/OutputStreamAdapter.cs, src/Mono.Android/Android.Runtime/OutputStreamInvoker.cs, tests/api-compatibility/api-compat-exclude-attributes.txt
As part of https://github.com/xamarin/xamarin-android/issues/5197 I am
reviewing usage of `PreserveAttribute`.
The ones removed here are not needed as their declaring types are
already preserved by `Mono.Android.xml` preserve list.
Also remove `Android.Runtime.PreserveAttribute` from API compatibility
checks as these are removed by the linker anyway.
=> Remove [Preserve] attributes where not needed

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsMapsApplicationProject.cs
* Bump to Xamarin.GooglePlayServices 117.x.
Running under a `dotnet` context, a MSBuild tests using Google Play
Services would fail because of a `<ProcessGoogleServicesJson/>`
MSBuild task. The assembly was built for .NET framework, and so it
fails when running with `dotnet build`. We can update to
Xamarin.GooglePlayServices 117.x, because it is a netstandard2.0
assembly now.
I did some other general cleanup here:
* Setup `XamarinFormsMapsApplicationProject` so it will bring in the
newest Xamarin.GooglePlayServices.
* Removed old Xamarin.GooglePlayServices packages from `KnownPackages`.
* Updated tests to use `XamarinFormsMapsApplicationProject` instead of
the various GooglePlayServices packages directly.
* Removed the relevant `[Category ("DotNetIgnore")]`.
I also completely removed …
=> [tests] use latest Xamarin.GooglePlayServices in tests

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Context: https://github.com/xamarin/xamarin-android/issues/5214
Build simple XA and XA/Forms apps in tests with current and NET5/6 XA.
Do not remove the temporary projects, so that it is possible to compare
the apks after tests run.
The apps are built with single arm64 ABI, in Release configuration.
The test can be run like this.
current XA:
msbuild Xamarin.Android.sln /t:RunNunitTests /p:TEST="Xamarin.Android.Build.Tests.BuildTest.BuildReleaseArm64"
NET5/6:
dotnet test -v diag --filter BuildTest.BuildReleaseArm64 .\bin\TestDebug\netcoreapp3.1\Xamarin.Android.Build.Tests.dll
=> [tests] Add test for apk size comparison

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/xaprepare/xaprepare/Scenarios/Scenario_AndroidTestDependencies.cs
The setup-test-environment.yaml template has been updated to reduce the
amount of dependency installation that happens by default for all test
jobs.  The majority of these jobs do not need all dependencies defined
by xaprepare, and we can save time provisioning by skipping these steps.
=> [CI] Skip required program installation for most test jobs

src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj, src/Microsoft.Android.Sdk.ILLink/RemoveAttributesBase.cs, src/Microsoft.Android.Sdk.ILLink/SetupStep.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/RemoveAttributes.cs
Implements: https://github.com/xamarin/xamarin-android/issues/5216
Removes redundant attributes like NRT related attributes.
Savings in `BuildReleaseArm64` test apks, plain and forms,
[apkdiff](https://github.com/radekdoulik/apkdiff) output:
Summary:
+           0 Dalvik executables 0.00% (of 317,096)
-      36,440 Assemblies -1.37% (of 2,657,134)
+           0 Shared libraries 0.00% (of 3,972,224)
-      36,452 Package size difference -0.81% (of 4,504,749)
Summary:
+           0 Dalvik executables 0.00% (of 3,491,180)
-      89,015 Assemblies -1.17% (of 7,636,539)
+           0 Shared libraries 0.00% (of 4,227,272)
-      89,010 Package size difference -0.78% (of 11,476,109)
=> [illink] Add RemoveAttributes substep

Documentation/release-notes/5221.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/MonoAndroidHelperTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/Files.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5218
Builds could fail on a Windows network share with:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'XYZ'
at System.IO.File.InternalDelete(String path, Boolean checkHost)
at System.IO.File.Delete(String path)
at Xamarin.Android.Tools.Files.CopyIfStreamChanged(Stream stream, String destination)
at Xamarin.Android.Tools.Files.ExtractAll(ZipArchive zip, String destination, Action`2 progressCallback, Func`2 modifyCallback, Func`2 deleteCallback, Func`2 skipCallback)
at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(IDictionary`2 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, …
=> [Xamarin.Android.Build.Tasks] fix DirectoryNotFoundException for builds on network shares

.vscode/extensions.json, .vscode/launch.json, .vscode/tasks.json
When building in vscode it was hardcoded to build in
`Debug`. This is a problem is you have to build in
`Release` since you can't use the ide.
This commit adds the ability to choose the configuration
when you launch the task. It will default to `Debug`.
=> [.vscode] Update tasks to use Configuration.

build-tools/installers/create-installers.targets
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1230070
Changes: https://github.com/xamarin/Java.Interop/compare/b991bb869c022616f53e4c3a324a01d77e6e4a2b...da74abd24d95ce6c3511467e3cd481680d888230
* xamarin/Java.Interop@da74abd2: Bump to mono/LineEditor/v5.4.1@3fa0c2eb (#740)
* xamarin/Java.Interop@5fe912ad: Bump to xamarin/xamarin-android-tools/main@26d65d9 (#741)
* xamarin/Java.Interop@9c73dbff: [generator] Output correct formatting for binding warnings (#737)
Update `create-installers.targets` so that `LineEditor.pdb` is
included in the macOS `.pkg` and Windows `.vsix` installers.
=> Bump to xamarin/Java.Interop/master@da74abd2

build-tools/automation/azure-pipelines.yaml, build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/Microsoft.Android.Ref.proj, build-tools/create-packs/Microsoft.Android.Runtime.proj, build-tools/create-packs/Microsoft.Android.Sdk.proj, build-tools/create-packs/Microsoft.NET.Workload.Android.proj
Context: https://docs.microsoft.com/nuget/reference/msbuild-targets
The various `.nupkg` files we ship for .NET 6 need to include a
`LICENSE` file:
* Create a new `$(NuGetLicense)` property that can be set at the
command-line. This allows us to use a proprietary license file when
needed.
* Set `$(PackageLicenseFile)` to the result of
`System.IO.Path.GetFileName($(NuGetLicense))`.
* Put the license file in the root of the NuGet package.
* Pass the license file from xamarin/monodroid via
`/p:PackageLicenseFile` in `azure-pipelines.yaml`.
=> [build] add missing LICENSE files for .NET 6 packages

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
[XamarinFormsAndroidApplicationProject](https://github.com/xamarin/xamarin-android/blob/91498d558e9443f5d4f854b58d64149d9c7c898e/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsAndroidApplicationProject.cs#L43-L48)
uses different XF versions for current and dotnet build.
As we want to have the apks as close as possible to compare the apk
sizes, let use the same version for this test.
=> [tests] Use same XF version to compare apk sizes

Documentation/release-notes/5234.md, src/Xamarin.Android.Build.Tasks/Tasks/Legacy/ValidateJavaVersion.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5234
I was building a project and hit:
```
error XA0032: Java SDK 11.0 or above is required when using Android SDK Build-Tools 30.0.2.
```
This is actually not true anymore since we got c50df1c5 and other
changes in to redistribute `apksigner.jar`. Let's drop this check, and
just require JDK 1.8.
I'm not actually sure how others haven't run into this?
=> [Xamarin.Android.Build.Tasks] do not require JDK 11 for build-tools 30

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AndroidLibraries.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Context: https://github.com/dotnet/sdk/issues/14042#issuecomment-716868311
We had been using an unfortunate hack to get the proper directory for
placing `.aar` files in NuGet packages:
<None Include="$(_AarOutputPath)" Pack="true" PackagePath="lib\$(TargetFramework)$(TargetPlatformVersion).0" />
Not only was the `.0` weird, but it would also produce the wrong
result if the `$(TargetFramework)` was `net5.0-android30`:
lib\net5.0-android3030.0
Using an example from the NuGet team, we can run a run a target by
setting `$(TargetsForTfmSpecificContentInPackage)`:
<TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_IncludeAarInNuGetPackage</TargetsForTfmSpecificContentInPackage>
Then we can run the `<GetNuGetShortFolderName/>` …
=> [One .NET] place .aar files in NuGet packages properly

Configuration.props, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/ConvertToRichText.cs, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/GenerateWixFile.cs, build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-installer.yaml, build-tools/create-dotnet-msi/Microsoft.NET.Workload.Android.wix.in, build-tools/create-dotnet-msi/create-dotnet-msi.csproj, build-tools/create-dotnet-pkg/create-dotnet-pkg.csproj, build-tools/create-dotnet-pkg/distribution.xml.in, build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/Microsoft.Android.Ref.proj, build-tools/create-packs/Microsoft.Android.Runtime.proj, build-tools/create-packs/Microsoft.Android.Sdk.proj, build-tools/create-packs/Microsoft.NET.Workload.Android.proj, build-tools/scripts/DotNet.targets, build-tools/scripts/Packaging.mk, build-tools/scripts/XAVersionInfo.targets
For .NET 6 Preview 1, we will need to provide our own installers for
the Android workload. This will also unblock the Xamarin.Forms / MAUI
team as they build on top of the iOS and Android workloads for .NET 6.
We will eventually do some kind of "insertion" process to provide our
`.nupkg` files to the dotnet/installer repo, so these installers will
go away completely at some point.
For now, this creates two new installers:
* Microsoft.Android.Workload.msi - installs to `C:\Program Files\dotnet\`
* Microsoft.Android.Workload.pkg - installs to `/usr/local/share/dotnet/`
Both installers have the following file structure underneath the root
directory:
* sdk\5.0.100-rtm.20509.5\EnableWorkloadResolver.sentinel
* sdk-manifests\5.0.100\Microsoft.Android.Workload\**
* packs\Microsoft.Android.Ref\** …
=> [One .NET] temporary Windows & macOS installers for .NET 6

src/Mono.Android/Android.Runtime/JNIEnv.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/4655
The following test is failing under .NET 5+ because
`SynchronizationContext.Current` returns `null`:
[Test]
public void SynchronizationContext_Is_ThreadingSynchronizationContextCurrent ()
{
bool same = false;
Application.SynchronizationContext.Send (_ => {
var c = System.Threading.SynchronizationContext.Current;
same = object.ReferenceEquals (c, Application.SynchronizationContext);
}, null);
Assert.IsTrue (same);
}
Following how this works in current Xamarin.Android / Mono:
* https://github.com/mono/mono/blob/169a842f4e913608b17a1e5f38bcb635063b8dc8/mcs/class/referencesource/mscorlib/system/threading/synchronizationcontext.cs#L297
* https://github.com/mono/mono/blob/d6f0c25d34da7512639346828ef368ff65a25003/mcs/class/corlib/Syste …
=> [One .NET] call SynchronizationContext.SetSynchronizationContext() on startup

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Deploying a project that uses two `$(RuntimeIdentifiers)` will fail on
our new fast deploy system with:
Xamarin.Android.Common.Debugging.targets(589,5): Access to the path 'obj/Debug/net5.0-android/android/assets/' is denied.
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at Xamarin.Android.Tasks.FastDeploy.DeployFileWithFastDevTool(ITaskItem file, String toolPath, String overridePath, Byte[] buffer, Byte[] compressed, LZ4Level lz4level) in /Users/builder/azdo/_work/18/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 579
at Xamarin.Android.Tasks.FastDeploy.DeployFastDevFiles(String …
=> [One .NET] fix duplicate .pdb files for multiple RIDs

Documentation/guides/OneDotNetEmbeddedResources.md, src/Xamarin.Android.Build.Tasks/Tasks/CreateAar.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
The following situation was broken in .NET 6 after the new `.aar` file
implementation in fcd7cf8:
* A class library includes `Resources\layout\Foo.axml` with an
uppercase name.
* An application references the library and uses the
`Resource.designer.cs` definition of `Resource.Layout.Foo`.
* `Resource.Layout.Foo` will have the incorrect integer value and
crash at runtime!
Reviewing the `Resource.designer.cs` file of the library:
// aapt resource value: 0x7F030000
public static int Foo = 2130903040;
Compared to the app:
// aapt resource value: 0x7F030000
public const int Foo = 2130903040;
// aapt resource value: 0x7F030001
public const int foo = 2130903041;
The reason this works in "legacy" Xamarin.Android is the
`__res_name_case_map.txt` file that is generated in …
=> [One .NET] <CreateAar/> should generate resource case map

.external
Changes: https://github.com/xamarin/monodroid/compare/04b0423e...0eef8891
Includes three fixes for the new Fast Deployment system:
* Improved no device error messages for FastDeploy
* Terminate running app on FastDeploy
* workaround <FastDeploy/> hang in .NET 5
=> Bump to xamarin/monodroid/master@0eef8891

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Many of our existing MSBuild tests set
`$(AppendRuntimeIdentifierToOutputPath)` to false so that the build
output has the same directory structure for "legacy" Xamarin.Android
as for .NET 6.
This causes a problem with the `ILLink` MSBuild target with multiple
`$(RuntimeIdentifiers)`, as linked .NET assemblies are output to:
obj\Debug\android.21-arm64\linked\Foo.dll
obj\Debug\android.21-x86\linked\Foo.dll
`AppendRuntimeIdentifierToOutputPath=false` cause both files to be
written to:
obj\Debug\linked\Foo.dll
obj\Debug\linked\Foo.dll
And so the last `$(RuntimeIdentifier)` wins, overwriting the linker
output of any previous RIDs. This would cause runtime crashes for some
ABIs, as `System.Private.CoreLib.dll` is different per architecture.
To fix this, we can always force …
=> [One .NET] fix linker output if $(AppendRuntimeIdentifierToOutputPath) is false

build-tools/create-dotnet-pkg/create-dotnet-pkg.csproj, build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/Microsoft.Android.Ref.proj, build-tools/create-packs/Microsoft.Android.Runtime.proj, build-tools/create-packs/Microsoft.Android.Sdk.proj, build-tools/create-packs/Microsoft.NET.Workload.Android.proj, build-tools/installers/create-installers.targets, build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/ReplaceFileContents.cs, src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj, src/Xamarin.Android.Build.Tasks/Microsoft.NET.Workload.Android/WorkloadManifest.in.json, src/Xamarin.Android.Build.Tasks/Microsoft.NET.Workload.Android/WorkloadManifest.targets
The Microsoft.Android.Sdk pack has been broken up into three Host OS
packs.  Depending on the operating system used during the build, one or
more of the following packs will now be created:
* Microsoft.Android.Sdk.linux-x64
* Microsoft.Android.Sdk.osx-x64
* Microsoft.Android.Sdk.windows-x64
This is still mostly missing Linux support, which can be addressed in
a future PR that adds a linux build job to our commercial pipeline.
I've moved around a few ItemGroups that were used to determine
what ends up in our ref and runtime packs.  These were previously
declared in a shared targets file as the assembly content did not differ
between the ref and runtime packs, but now that we are producing
reference assemblies for certain projects we can move the item
declarations into the project files …
=> [One .NET] Create Host OS specific SDK packs

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/xamarin-android/commit/68be8d810e3f87865d88467ae593048297bf3e60
We can produce public facing download links for our installers by adding
`/public/` to our blob storage upload path.
=> [ci] Produce installers with public download links

src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs
In .NET 6, I noticed many of the `PerformanceTest` tests are about
150ms-300ms slower than in "legacy" Xamarin.Android.
`PerformanceTest.Build_No_Changes` spends a lot of
time in the `<FilterAssemblies/>` MSBuild task:
FilterAssemblies = 220 ms
This was running on our CI on macOS.
For a "Hello World" app, this task had an input of 155 assemblies.
`Mono.Android.Export.dll` was the only assembly added to
`@(_MonoAndroidReferencePath)`, but it doesn't actually need to be.
Reviewing build logs, I saw the following metadata:
C:\Users\myuser\android-toolchain\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0-rtm.20508.7\ref\net5.0\mscorlib.dll
FrameworkReferenceName = Microsoft.NETCore.App
FrameworkReferenceVersion = 5.0.0-rtm.20508.7
Every assembly that came from a `@(FrameworkReference)` has this …
=> [One .NET] <FilterAssemblies/> can skip over @(FrameworkReference)

Documentation/building/unix/instructions.md, Documentation/building/windows/instructions.md
Our instructions for working with .NET 6 are a bit out of date. The
old instructions were describing how to use the `.nupkg` files
directly as an MSBuild SDK. I updated the instructions for .NET
"workloads".
=> [docs] update instructions for using .NET 6 builds

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownProperties.cs, tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5274
In 51fb93e1, I had logic checking for `$(AndroidLinkMode)` and
`$(AndroidIncludeDebugSymbols)` in two places:
* The `<ProcessAssemblies/>` MSBuild task, which eventually populates
a `@(_ShrunkAssemblies)` item group.
* The `_PrepareAssemblies` MSBuild target, which fills out various
item groups such as `@(_ShrunkFrameworkAssemblies)` and
`@(_ShrunkUserAssemblies)`.
The logic did not match exactly, and so building a `Release` app with
`AndroidLinkMode=None` would result in all of these item groups being
empty.
I switched to checking `$(PublishTrimmed)` as it is the only property
that needs to be checked here:
* if `$(PublishTrimmed)` is `true`, `ILLink` runs and we need to use
the assemblies that the `_RemoveRegisterAttribute` …
=> [One .NET] fix Release builds with AndroidLinkMode=None

tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/DimBindingTests.cs, tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/java/com/xamarin/android/DefaultMethodsInterface.java
Context: https://github.com/xamarin/xamarin-android/issues/5251
Context: https://github.com/xamarin/java.interop/pull/745
https://github.com/xamarin/java.interop/compare/c3c35753b6e1b9e8e682adf37fc9d9e531114cf7...99897b24eada3b68fa1eedae41efd15fbf128ae1
Adds a test for `static` methods on an interface that is implemented by a class.  Our existing `static` test was an interface that only contained `static` members, and thus we did not try to implement the interface.  Implementing the interface exposed a JCW error.
=>  Bump to xamarin/java.interop@99897b2 

src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5263
In .NET 6, we currently run the `ILLink` MSBuild target for each
`$(RuntimeIdentifier)`, as the Mono runtime packs have some .NET
assemblies that differ per architecture.
To make this happen, the `<ProcessAssemblies/>` MSBuild task works
with input such as:
* `android.21-arm\linked\Foo.dll`
* `android.21-x86\linked\Foo.dll`
* `android.21-arm\linked\System.Private.CoreLib.dll`
* `android.21-x86\linked\System.Private.CoreLib.dll`
And "merges" this to what we need in the output of the `.apk`:
* `assemblies\Foo.dll`
* `assemblies\armeabi-v7a\System.Private.CoreLib.dll`
* `assemblies\x86\System.Private.CoreLib.dll`
`Foo.dll` is identical for all architectures, so we only need to use a
single copy of it.
A bug in our implementation …
=> [One .NET] better logic for deduplication of architecture-specific assemblies

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets
Context: https://github.com/xamarin/xamarin-android/issues/5271
Temporarily set trim mode of support assemblies to `link`.
apk size comparison of XF BuildReleaseArm64True test after the change, current monodroid vs net5:
```
Summary:
+          29 Other entries 0.00% (of 750,919)
-         116 Dalvik executables -0.00% (of 3,455,436)
+   1,604,215 Assemblies 33.66% (of 4,765,637)
-   6,488,608 Shared libraries -61.38% (of 10,570,992)
-     394,325 Package size difference -3.73% (of 10,572,124)
```
apk size comparison of XF BuildReleaseArm64True test before and after the change (net5):
```
Summary:
-         184 Other entries -0.02% (of 751,132)
-      35,860 Dalvik executables -1.03% (of 3,491,180)
-   1,179,296 Assemblies -15.62% (of 7,549,148)
-     144,888 Shared libraries -3.43% (of …
```
=> [illink] Set TrimMode of support assemblies

Configuration.props, Documentation/guides/OneDotNet.md, NuGet.config, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/GenerateWixFile.cs, build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/Microsoft.Android.Ref.proj, build-tools/create-packs/Microsoft.Android.Runtime.proj, build-tools/create-packs/Microsoft.Android.Sdk.proj, build-tools/create-packs/Microsoft.NET.Workload.Android.proj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.After.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Microsoft.NET.Workload.Android/WorkloadManifest.in.json, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetXamarinProject.cs, tests/CodeBehind/BuildTests/CodeBehindBuildTestsDotNet.csproj, tests/CodeBehind/CommonSampleLibrary/CommonSampleLibraryDotNet.csproj
Changes: https://github.com/dotnet/installer/compare/53e0c8c7...efac3f25
This version of .NET 6 includes support for
`$(AfterMicrosoftNETSdkTargets)`, and so we now have a slightly
different import ordering:
1. `AutoImport.props`
2. The user's `.csproj` file
3. Some early parts of `Microsoft.NET.Sdk` / `Sdk.targets`
4. `Microsoft.Android.Sdk.targets`
5. The rest of `Microsoft.NET.Sdk` / `Sdk.targets`
6. `Microsoft.Android.Sdk.After.targets`
Anything that needs to happen *after* the `Microsoft.NET.Sdk` targets
can go in `After.targets`.
This allows us to set up some defaults that we lost in 91498d55 when
implementing Android as a .NET "workload":
* `$(GenerateDependencyFile)` defaults to `false`
* `$(ProduceReferenceAssembly)` defaults to `false` for application
projects.
Using …
=> Bump to .NET 6.0.100-alpha.1.20562.2

src/Microsoft.Android.Sdk.ILLink/SetupStep.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5287
Turns out we were building the step, but not adding it to the linker
steps pipeline.
With the step added to the pipeline, the right resources are removed
again. The [apkdiff](https://github.com/radekdoulik/apkdiff) output
comparing the apks before and after the change:
+       7,732 assemblies/Xamarin.Forms.Platform.Android.dll
+             Resource __AndroidLibraryProjects__.zip
+       2,013 assemblies/FormsViewGroup.dll
+             Resource formsviewgroup.jar
+         192 assemblies/Xamarin.Forms.Platform.dll
+             Resource __AndroidLibraryProjects__.zip
...
Summary:
+           0 Other entries 0.00% (of 751,132)
+           0 Dalvik executables 0.00% (of …
=> [illink] Add StripEmbeddedLibraries step

build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/automation/yaml-templates/use-dot-net.yaml
Context: https://github.com/xamarin/xamarin-android/pull/5293
Context: https://github.com/xamarin/xamarin-android/blob/f5680e783fe45d4f536f8199372ff504ebfdc393/build-tools/automation/yaml-templates/use-dot-net.yaml
PR #5293 introduced an incompatibility with xabuild, and it appears to
be causing issues with other stable builds.  The [UseDotNet][1] task has
a caching feature to improve "installation" times for certain versions,
however this can cause issues for our non-hosted build machines.
/Users/builder/azdo/_work/_tool/dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(54,5): error MSB4186: Invalid static method invocation syntax: "[MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')". Method …
=> [ci] Restore custom use-dot-net task

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets
Use the user custom linker files with ILLink on .NET5/6.
Fixes: https://github.com/xamarin/xamarin-android/issues/5288
It should fix `CustomLinkDescriptionPreserve` test as well.
Context: https://github.com/xamarin/xamarin-android/pull/5035#discussion_r522201211
=> [illink] Use @(LinkDescription) items

build-tools/automation/azure-pipelines.yaml
Context: https://dev.azure.com/devdiv/DevDiv/_releaseProgress?_a=release-environment-logs&releaseId=877224&environmentId=4657763
A recent VS Mac insertion attempt failed due to the fact that we were
no longer publishing information from an `updateinfo` file required by
that tooling.  This was accidentially removed in 68be8d81 via the
addition of the `patterns` filter on the [installer artifact download
task][1].  This addition prevented the `updateinfo` file from being
downloaded and processed during the notarize + sign job, which left a
couple of key fields in our installers `artifact.json` empty:
"tag": "",
"productId": "",
"releaseId": "",
We can fix this by making sure the `updateinfo` file is downloaded and
sitting side by side the `.pkg` file when the build-tasks [artifacts][2]
tool …
=> [ci] Include updateinfo in artifacts.json

build-tools/cmake/xa_macros.cmake
The ARM64 build of our native runtime code fails with the following
message when Xcode with Apple silicon support is installed:
ld : warning : ignoring file libmonosgen-2.0.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
"_mono_add_internal_call", referenced from:
...
ld: symbol(s) not found for architecture arm64
clang : error : linker command failed with exit code 1 (use -v to see invocation)
This is caused by the fact that the Mono archive we use does not
contain Mono binaries which include both the `x86_64` and the
`arm64` architectures.
Add a check on `libmonosgen-2.0.dylib` to see if it's a fat binary
with both required architectures and disable ARM64 if not, even if
the Xcode toolchain supports Apple …
=> [macOS] More checks for Apple silicon support

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunAndroidEmulatorCheckBootTimes.cs, build-tools/automation/azure-pipelines.yaml
Context: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4231349&view=logs&j=cd6eb242-2e57-569b-620a-eaaded8e9a51&t=e2ddc662-66d6-5931-5787-f44b56aa5ee1
The "Run check-boot-times" step has been failing intermittently on CI.
After reviewing the logs, it appears that the issue is due to a process
timeout:
2020-11-16T22:55:32.7941780Z CheckBootTimes:
2020-11-16T22:55:32.7942560Z   Task RunAndroidEmulatorCheckBootTimes
2020-11-16T22:55:32.7944830Z        CheckBootTimesPath: /Users/runner/work/1/s/build-tools/scripts/../../bin/BuildRelease/check-boot-times.exe
2020-11-16T22:55:32.7945930Z        DeviceName: XamarinAndroidTestRunner64
2020-11-16T22:55:32.7947410Z   CheckBootTimesPath:  /Users/runner/work/1/s/bin/BuildRelease/check-boot-times.exe
2020-11-16T22:55:33.0955770Z …
=> [ci] Bump check-boot-times timeout, exclude from smoke tests

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4233431&view=ms.vss-test-web.build-test-results-tab&runId=17100812&resultId=100181&paneView=debug
The `Desugar` tests started failing with:
System.Net.WebException : The remote server returned an error: (401) Unauthorized
at System.Net.HttpWebRequest.GetResponse()
at System.Net.WebClient.GetWebResponse(WebRequest request)
at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
at System.Net.WebClient.DownloadFile(Uri address, String fileName)
at System.Net.WebClient.DownloadFile(String address, String fileName)
at Xamarin.ProjectTools.DownloadedCache.GetAsFile(String url) in /Users/builder/azdo/_work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DownloadedCach …
=> [tests] update URL for twitter-core-3.3.0.aar

build-tools/automation/azure-pipelines.yaml
Fixes commit 9429b54c which attempted to use a Configuration
related variable name that didn't exist in the context of the new
job responsible for running check-boot-times.
=> [ci] Fix check-boot-times configuration name

build-tools/automation/azure-pipelines.yaml
Commit b864f93d appears to have broken the GitHub status for the .NET 6
installers.  These changes resulted in us attempting to use the same
blob storage location for both legacy and .NET 6 installers, and the
step which ran last (often legacy, as signing takes a while) would write
over the previous status.  Adding `net6` to the .NET 6 installer blob
storage path should fix this.
=> [ci] Use unique storage URLs for installers

Documentation/guides/building-apps/build-properties.md, Documentation/release-notes/5304.md, src/Xamarin.Android.Build.Tasks/Resources/proguard_xamarin.cfg, src/Xamarin.Android.Build.Tasks/Tasks/Proguard.cs, src/Xamarin.Android.Build.Tasks/Tasks/R8.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.D8.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.DX.targets
Fixes #5186
When uploading a package to the Google Play Store users are seeing
the following warning.
This App Bundle contains Java/Kotlin code, which might be obfuscated.
To fix this users need to provide a `mapping.txt` file which contains
the Java class mappings from their plain versions to the ones which
are obfuscated. By default we do not obfuscate the java code but the
warning still shows.
To fix this issue we have a new property `$(AndroidProguardMappingFile)`
which defaults to `$(OutputPath)mapping.txt`. This file will be produced
as part of the build process. In order for this mapping file to be
generated the following lines needed to be added to the `proguard_xamarin.cfg`
file.
-keepattributes SourceFile
-keepattributes LineNumberTable
=> [Xamarin.Android.Build.Tasks] Add support for Proguard `mapping.txt` file

build-tools/xaprepare/xaprepare/Application/HomebrewProgram.MacOS.cs
The latest version of homebrew introduced a breaking change in the
way it handles certain combinations of its command-line arguments.
Namely, what affects us, is the combination `--versions -1` to
limit the number of package's versions to a single line. Right
now it is not allowed and causes the following failure:
Error: Invalid usage: Options --versions and -1 are mutually exclusive.
[MISSING]
Checking automake                                   Usage: brew list, ls [options] [formula|cask]
Instead of passing `-1`, do the processing ourselves.
=> [xaprepare] Fix for newer homebrew on macOs

Documentation/building/unix/instructions.md, Documentation/building/windows/instructions.md, Documentation/guides/OneDotNet.md, Documentation/guides/messages/README.md, Documentation/guides/messages/xa0036.md, Documentation/guides/messages/xa1023.md, Documentation/guides/messages/xa1024.md, Documentation/guides/messages/xa1026.md, Documentation/guides/messages/xa2000.md, build-tools/create-packs/Directory.Build.targets, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
Since 6f761ea8 gets us on a build of .NET 6, we can update all
user-facing messaging to say .NET 6 instead of .NET 5.
* Documentation around building `xamarin-android`
* Error/warning messages
I also updated a few things other things that should say .NET 6:
* `NuGet.config` sources in MSBuild tests
* `@(FrameworkListRootAttributes)` for our .NET 6 packages
I did not update various code comments, as most of them say .NET 5+
and are not user-facing.
Other changes in `OneDotNet.md`:
* Started a new `Runtime behavior` section with a link to
`String.IndexOf()` behavior.
* Link to `net6-samples` as the source for .NET 6 example projects and
installation instructions.
=> [One .NET] update user-facing messages from .NET 5 to .NET 6

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, tests/Mono.Android-Tests/Directory.Build.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/5299
When setting up `Mono.Android.NET-Tests`, we had to workaround an
error with duplicate `@(Content)` files:
error NETSDK1148: Found multiple publish output files with the same relative path: external\Java.Interop\bin\Release\java-interop.jar, \external\Java.Interop\bin\Release-netcoreapp3.1\java-interop.jar.
Android doesn't support the `@(Content)` build action *at all*, and we
emit a `XA0101` warning if it is used. We even have a test for this.
However, it appears that any `@(Content)` from `@(ProjectReference)`
items are currently brought over in .NET 6, as they get added to the
`@(ResolvedFileToPublish)` item group by the dotnet/sdk.
Luckily there appears to be a `$(_GetChildProjectCopyToPublishDirectoryItems)`
MSBuild …
=> [One .NET] ignore @(Content) from @(ProjectReference)

Documentation/release-notes/5304.md, src/Xamarin.Android.Build.Tasks/Resources/proguard_xamarin.cfg, src/Xamarin.Android.Build.Tasks/Tasks/Proguard.cs, src/Xamarin.Android.Build.Tasks/Tasks/R8.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/xamarin-android/pull/5304
The Proguard mapping.txt PR was not quite ready for prime time and has
seemingly caused some new proguard test failures and an .apk size
regression in our Xamarin.Forms baseline.  Let's disable this by default
for now until we can fix these issues.
=> [Xamarin.Android.Build.Tasks] Make Proguard mapping.txt opt-in

.vscode/settings.json, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-msbuild-device-tests.yaml, build-tools/automation/yaml-templates/run-timezoneinfo-tests.yaml, build-tools/scripts/NUnitReferences.projitems, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj, tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.targets, tests/MSBuildDeviceIntegration/Resources/LinkDescTest/MainActivityReplacement.cs, tests/MSBuildDeviceIntegration/Tests/AotProfileTests.cs, tests/MSBuildDeviceIntegration/Tests/BundleToolTests.cs, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs, tests/MSBuildDeviceIntegration/Tests/DeleteBinObjTest.cs, tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs, tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs, tests/MSBuildDeviceIntegration/Tests/MonoAndroidExportTest.cs, tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs, tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs, tests/RunApkTests.targets
This builds `MSBuildDeviceIntegration.csproj` for `netcoreapp3.1`, and
adds a new test job for the `MSBuild Emulator Tests` stage.
I added `[Category]` as needed for tests when running under a `dotnet`
context.
Other fixes:
* `PerformanceTest` now builds all projects for a single ABI. This
reduces the time spent in `<ProcessAssemblies/>`. I also added a
500ms buffer for a `dotnet` context and an additional 500ms if the
test would now sign the `.apk` during `dotnet build`.
* If `AutomaticNuGetRestore` is `false`, `dotnet build` needs to pass
`--no-restore`. This improves `PerformanceTest` times.
* `BundleToolTests` needed many file paths updated.
* Ensure that `AssertDexToolSupported (dexTool)` is called to ignore
tests using an `$(AndroidDexTool)` of `dx`.
* The MSBuild tests using …
=> [tests] multi-target MSBuildDeviceIntegration

build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/automation/yaml-templates/update-vs.yaml, build-tools/automation/yaml-templates/use-dot-net.yaml, build-tools/provisioning/vs2019.csx, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, tools/xabuild/XABuildPaths.cs
All build and test jobs have been updated to install both .NET Core
3.1.201 and .NET 5.0.100.  Eventually, we should be able to remove the
3.1.201 installation after we migrate everything targeting .NET Core to
.NET 5.  Windows jobs will now update the Visual Studio 2019 instance
on disk to the latest available stable version. The base image has been
updated to speed up update performance.  See below for more info:
https://github.com/xamarin/monodroid/wiki/Azure-Pipelines-and-DevOps#windows-scale-set-agent-pool-management
There are currently multiple issues with .NET 5 and `xabuild`.  First
off, the system Mono that we are using contains a version of MSBuild
that is not compatible with .NET 5 targets, which attempt to use a
static property method that does not exist in Mono's MSBuild: …
=> [ci] Install .NET 5 stable and stable VS

src/Xamarin.Android.NamingCustomAttributes/Java.Interop/ExportAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Java.Interop/ExportFieldAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/System.Diagnostics.CodeAnalysis/DynamicDependencyAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/System.Diagnostics.CodeAnalysis/DynamicallyAccessedMemberTypes.cs, src/Xamarin.Android.NamingCustomAttributes/Xamarin.Android.NamingCustomAttributes.projitems
... when Export or ExportField attributes are used.
Should fix: https://github.com/xamarin/xamarin-android/issues/5265
The dynamic dependency attribute code comes from dotnet/runtime repo.
Once we switch to VS 16.8, we can use the `net5.0` TFM and start using these
attributes from NET5.
=> [illink] Preserve DynamicCallbackCodeGenerator

Documentation/release-notes/5314.md, src/Xamarin.Android.Build.Tasks/Tasks/ManifestMerger.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
When testing a .NET 6 project using AndroidX and
`$(AndroidManifestMerger)` = `manifestmerger.jar`, I noticed:
1. I edited the `.csproj` file and did various incremental builds.
2. During `dotnet build`, the `_ManifestMerger` MSBuild target was
always running--even if there were no changes.
I was able to reproduce the issue in a test, even in "legacy"
Xamarin.Android:
Building target "_ManifestMerger" completely.
Input file "obj\Debug\AndroidManifest.xml" is newer than output file "obj\Debug\android\AndroidManifest.xml".
What appears to be happening is:
1. The `Inputs` to `_ManifestMerger` changed.
2. The `Outputs` had identical contents and so
`MonoAndroidHelper.CopyIfStreamChanged()` did not actually write a
file.
At this point you are stuck in a place where the `Inputs` will be …
=> [Xamarin.Android.Build.Tasks] fix incremental _ManifestMerger target

src/Microsoft.Android.Sdk.ILLink/PreserveJavaInterfaces.cs, src/Microsoft.Android.Sdk.ILLink/SetupStep.cs
When comparing monodroid and net5 apks of `BuildReleaseArm64True` test
I noticed some of the methods and related fields were missing.
Create `PreserveJavaInterfaces` substep to add more preservation,
similar as we do in `MonodroidMarkStep.DoAdditionalTypeProcessing`.
Example additional preserved API in `Android.App.Activity` and summary
of additions to `Mono.Android.dll`:
Type Android.App.Activity
+             Field static System.Delegate cb_onProvideKeyboardShortcuts_Ljava_util_List_Landroid_view_Menu_I
+             Method static System.Delegate GetOnProvideKeyboardShortcuts_Ljava_util_List_Landroid_view_Menu_IHandler ()
+             Method static void n_OnProvideKeyboardShortcuts_Ljava_util_List_Landroid_view_Menu_I (IntPtr, IntPtr, IntPtr, IntPtr, int)
+             Method public …
=> [illink] Preserve Java interface methods

Documentation/guides/building-apps/build-items.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes #5312
The manifest merger tool supports providing additional AndroidManifest.xml
files which will `overlay` on top of the final file. This commit adds a
new Build Action `AndroidManifestOverlay` which can be used to provide
these files to the manifest merger.
Users can now use these overlay files to alter the manifest during
build time. This can be for adding new permissions or even removing
ones that are not needed. It will also allow for different manifest
files to be generated for debug/release configurations. This can be
done by conditionally including `overlay` files depending on the
`$(Configuration)`.
```
<ItemGroup>
<AndroidManifestOverlay Include="DebugPermissions.xml" Condition=" '$(Configuration)' == 'Debug' " />
</ItemGroup>
```
=> [Xamarin.Android.Build.Tasks] Add Support for AndroidManifest.xml overlays

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
Set all current feature switches, but `InvariantGlobalization`, to
defaults which trim the features.
Context: https://github.com/dotnet/runtime/blob/master/docs/workflow/trimming/feature-switches.md
Difference in assembly size of XA BuildReleaseArm64False test before/after:
Summary:
-     417,632 Assemblies -15.98% (of 2,613,075)
=> [illink] Set runtime libraries feature switches defaults

src/Microsoft.Android.Sdk.ILLink/PreserveLists/Mono.Android.xml
Fixes: https://github.com/xamarin/xamarin-android/issues/5339
Instead preserve just the known API accessed by reflection.
=> [illink] Do not preserve all in J.I namespace

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
The feature was added in https://github.com/xamarin/xamarin-android/commit/286a0aa3b5a4a01b5f51bcf65a5b21c3bb0265f4
=> [illink] Enable @LinkDescription test on DotNet

src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
Fixes #5334
We are still adding the `android.permission.READ_EXTERNAL_STORAGE` permission
when we don't embed assemblies into the apk. Since 71dc7185 we no longer need
this permission since we fast deploy to the applications internal directory.
=> [Xamarin.Android.Build.Tasks] Do not add READ_EXTERNAL_STORAGE permission

Documentation/guides/MSBuildBestPractices.md, Documentation/release-notes/5283.md, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.ClassParse.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.JarToXml.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Designer.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.DesignTime.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
I noticed that changing the selected device or emulator in Visual
Studio 2019 16.8 on Windows was causing many MSBuild targets to run
again in the IDE. The time taken was similar to a `Rebuild`!
Looking closer, I noticed:
Building target "_CompileJava" completely.
Input file "App42.csproj.user" is newer than output file "obj\Debug\_javac.stamp".
`.csproj.user` is where the IDE stores the selected device or
emulator. The contents of the file:
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<SelectedDevice>pixel_2_pie_9_0_-_api_28</SelectedDevice>
<DefaultDevice>pixel_2_pie_9_0_-_api_28</DefaultDevice>
</Project>
The reason this triggers many targets is the file is actually …
=> [Xamarin.Android.Build.Tasks] ignore .csproj.user file in $(MSBuildAllProjects)

src/Xamarin.Android.Build.Tasks/Tasks/BuildBaseAppBundle.cs
When building an app bundle incrementally we get the following crash
error XABBA7000: Xamarin.Tools.Zip.ZipException: Invalid argument [/Users/dean/Projects/MonoGameAndroidAds/MonoGameAndroidAds.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2079,3): error XABBA7000:   at Xamarin.Tools.Zip.ZipArchive.ReadEntry (System.UInt64 index, System.Boolean throwIfDeleted) [0x00047] in <88e5f87310fc4b0cbcadde89bab7fe3c>:0  [/Users/dean/Projects/MonoGameAndroidAds/MonoGameAndroidAds.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2079,3): error XABBA7000:   at Xamarin.Tools.Zip.ZipArchive.ReadEntry (System.UInt64 index) [0x00000] in <88e5f87310fc4b0cbcadde89bab7fe3c>:0 …
=> [Xamarin.Android.Build.Tasks] Fix crash in BuildBaseAppBundle

Documentation/guides/messages/README.md, Documentation/guides/messages/xa0113.md, Documentation/release-notes/google-play-29.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf, src/Xamarin.Android.Build.Tasks/Tasks/Legacy/ResolveAndroidTooling.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/4977
Context: https://support.google.com/googleplay/android-developer/answer/9859152?visit_id=637424522037563363-1219346479&rd=1#targetsdk
We currently warn if `$(TargetFrameworkVersion)` is less than 28:
Google Play requires that new applications and updates must use a TargetFrameworkVersion of v9.0 (API level 28) or above.
Since November 2, 2020, Google Play requires API 29, so we need to
update this warning.
=> [Xamarin.Android.Build.Tasks] bump XA0113 warning to 29

Documentation/guides/OneDotNet.md, Documentation/guides/OneDotNetEmbeddedResources.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AndroidLibraries.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
When implementing #5348, I noticed that we could add a wildcard to
make Java bindings simpler:
<TransformFile Include="Transforms\**\*.xml" />
This way you can just put `.xml` files in the `Transforms` folder so
they will be picked up automatically.
We also need to include some additional wildcards:
<AndroidLibrary       Include="**\*.jar" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
<AndroidLibrary       Include="**\*.aar" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
<AndroidNativeLibrary Include="**\*.so"  Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)" />
To make sure we exclude folders like `bin` and `obj`, we can rely on
`$(DefaultItemExcludes)` and `$(DefaultExcludesInProjectFolder)` as
the dotnet/sdk does: …
=> [One .NET] improve default MSBuild item groups

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
https://github.com/xamarin/xamarin-android/commit/881edb3e64b21f65c82809f19307ea6ca5be9abc
improved the linking and now
the `System.Runtime.Serialization.Formatters` is linked away.
=> [tests] Update CheckIncludedAssemblies tests

tests/MSBuildDeviceIntegration/Resources/LinkDescTest/MainActivityReplacement.cs, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5319
This test was originally failing in 6e3e3831 with:
android.runtime.JavaProxyThrowable: System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception.
---> System.DllNotFoundException: e_sqlite3
at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
at …
=> [tests] enable sqlite-net-pcl test in .NET 6

src/Microsoft.Android.Sdk.ILLink/PreserveLists/Mono.Android.xml
Part of https://github.com/xamarin/xamarin-android/issues/5167
The type is not accessed through reflection.
It is preserved by the linker when needed like:
illinkanalyzer -r Android.Runtime.Extensions linker-dependencies.xml.gz
...
--- Method:TResult Android.Runtime.Extensions::JavaCast(Android.Runtime.IJavaObject) dependencies ---
Dependency #1
Method:TResult Android.Runtime.Extensions::JavaCast(Android.Runtime.IJavaObject)
| MethodSpec:TResult Android.Runtime.Extensions::JavaCast<T>(Android.Runtime.IJavaObject) [1 deps]
| Method:T Android.App.Activity::FindViewById(System.Int32) [1 deps]
| MethodSpec:!!0 Android.App.Activity::FindViewById<Android.Widget.Button>(System.Int32) [1 deps]
| Method:System.Void UnnamedProject.MainActivity::OnCreate(Android.OS.Bundle) [2 deps]
| …
=> [illink] Do not preserve A.R.Extensions

build-tools/automation/azure-pipelines.yaml
Recently some CI builds are ending early, because Homebrew is failing
like this:
Installing automake
...
stderr | Error: Not a directory @ dir_s_rmdir - /usr/local/Cellar/openssl
| Removing: /usr/local/Cellar/openssl/1.0.2t... (1,787 files, 12MB)
Error: Installation of automake failed
=> [build] Fix Homebrew/openssl

build-tools/automation/azure-pipelines.yaml
As part of the transition off Jenkins-based operations, transition to using the Azure DevOps-based signing pipeline. The Azure DevOps solution is functionally equivalent to the Jenkins-based solution.
This change queues the signing job here:
https://dev.azure.com/devdiv/DevDiv/_build?definitionId=13878
Because the PR build does not include signing, a special manual build was launched (and passed) as follows:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4275293&view=results
Which in turn launched the following Azure DevOps signing job
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4275526&view=results
=> [build] Replace Jenkins-based signing step with Azure DevOps step

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/01-building-an-application.md, .github/ISSUE_TEMPLATE/02-running-an-application.md, .github/ISSUE_TEMPLATE/04-mono-android-api.md, .github/ISSUE_TEMPLATE/05-binding-a-java-library.md, .github/ISSUE_TEMPLATE/07-other.md
Fixes: https://github.com/xamarin/xamarin-android/issues/5389
The instructions did not specify how to do an equivalent of:
$ adb logcat -d | pbcopy
On Windows, it can be:
> adb logcat -d | clip
=> [issues] fix instructions for 'adb logcat -d' on Windows

Documentation/release-notes/5375.md, src/Xamarin.Android.NamingCustomAttributes/Android.App/ActivityAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Android.App/ApplicationAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Android.App/InstrumentationAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Android.App/ServiceAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Android.Content/BroadcastReceiverAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Android.Content/ContentProviderAttribute.cs, tests/api-compatibility/acceptable-breakages-vReference.txt
This reverts commit d548ec9ca5746e7ef2f4bd5f0ea11bd58b09ae3b.
Decoration of `ApplicationAttribute.Label` with:
[System.ComponentModel.Category ("@string")]
public string?                Label                   {get; set;}
Allowed an experimental feature in Visual Studio to offer `@string`
`AndroidResource` completion when changing the `Label` property in C#.
Unfortunately, the presence of this attribute causes the linker to
preserve various dependencies of `System.ComponentModel` in .NET 6.
It appears that this completion feature never shipped in the IDE, so
we can completely remove this. If we ever want to bring the feature
back, we should create a new `internal` attribute to be used instead.
Results of this change:
> apkdiff before.apk after.apk
Size difference in bytes ([*1] apk1 only, …
=> Revert "[Mono.Android] Add [Category] for IDE completion of string props

src/Mono.Android/metadata, src/Mono.Android/methodmap.csv
Fixes: #5368 
The class [`AccessibilityNodeInfo`](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo) has the following methods:
```
// Added in API-14, deprecated in API-21
public void addAction (int action)
// Added in API-21
public void addAction (AccessibilityNodeInfo.AccessibilityAction action)
```
We are converting the `int action` to an enum using `methodmap.csv`:
```
0, android.view.accessibility, AccessibilityNodeInfo, addAction, action, Android.Views.Accessibility.Action
```
However this mechanism does not specify parameter types, so both methods are getting their parameter enum-ified:
```
public void AddAction (Android.Views.Accessibility.Action action)
public void AddAction (Android.Views.Accessibility.Action action)
```
This isn't …
=> [Mono.Android] Bind AccessibilityNodeInfo.AddAction (AccessibilityAction action)

src/Microsoft.Android.Sdk.ILLink/PreserveLists/Mono.Android.xml
Part of https://github.com/xamarin/xamarin-android/issues/5167
Removed API from `BuildReleaseArm64False` test (ignore the SIGERR's in place of return types):
Type Android.Runtime.AndroidEnvironment
-             Field public static string AndroidLogAppName
-             Field static Javax.Net.Ssl.IX509TrustManager sslTrustManager
-             Field static Java.Security.KeyStore certStore
-             Method static SIGERR SetupTrustManager ()
-             Method static SIGERR SetupCertStore ()
-             Method public static SIGERR add_UnhandledExceptionRaiser (System.EventHandler`1<Android.Runtime.RaiseThrowableEventArgs>)
-             Method public static SIGERR remove_UnhandledExceptionRaiser (System.EventHandler`1<Android.Runtime.RaiseThrowableEventArgs>)
-             Method …
=> [illink] Do not preserve A.R.AndroidEnvironment

Documentation/guides/OneDotNetEmbeddedResources.md, Documentation/guides/building-apps/build-items.md, Documentation/release-notes/5372.md, build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.AvailableItems.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AndroidLibraries.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidItem.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/5357
The new `@(AndroidLibrary)` item group can now be used in "legacy"
Xamarin.Android:
<AndroidLibrary Include="foo.jar" />
<AndroidLibrary Include="bar.aar" />
* Application and class library projects:
* `foo.jar` maps to `AndroidJavaLibrary`
* `bar.aar` maps to `AndroidAarLibrary`
* Java binding projects:
* `foo.jar` maps to `EmbeddedJar`
* `foo.jar` maps to `EmbeddedReferenceJar` if `Bind="false"` metadata is added
* `bar.aar` maps to `LibraryProjectZip`
* Additionally:
* `@(AndroidNativeLibrary)` now will be used for native libraries.
You can use `@(AndroidNativeLibrary)` instead of
`@(EmbeddedNativeLibrary)`.
All `@(AvailableItemNames)` are now defined in a single
`Xamarin.Android.AndroidItems.targets` that is imported by all …
=> [Xamarin.Android.Build.Tasks] @(AndroidLibrary) for all project types

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets
Context: https://github.com/dotnet/msbuild/pull/5499
In .NET 6, we can rely on `$(IncrementalCleanDependsOn)`. This means
we can remove the expression:
<CoreBuildDependsOn>
$([MSBuild]::Unescape($(CoreBuildDependsOn.Replace('IncrementalClean;', '$(_BeforeIncrementalClean);IncrementalClean;'))))
</CoreBuildDependsOn>
And simply use `$(IncrementalCleanDependsOn)` instead of
`$(_BeforeIncrementalClean)`.
I also found a block of targets defined with:
<PropertyGroup Condition=" '$(_ComputeFilesToPublishForRuntimeIdentifiers)' != 'true' ">
But this file is no longer imported at all:
<Import Project="Microsoft.Android.Sdk.BuildOrder.targets" Condition=" '$(_ComputeFilesToPublishForRuntimeIdentifiers)' != 'true' " />
So we can delete the `Condition` now.
=> [One .NET] cleanup BuildOrder.targets

.external, Documentation/guides/building-apps/build-properties.md, Documentation/release-notes/5311.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs, tests/MSBuildDeviceIntegration/Tests/BundleToolTests.cs, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
This commit adds support for running multi user tests on device.
It makes use of various adb commands to create test users and
remove them.
`shell pm create-user --guest {name}` will create a guest user of a
specific name.
`shell pm remove-user --guest {userId}` will remove a userId.
The userId can be retrieved via `shell pm list users`. This command
will return results as follows
Users:
UserInfo{0:Owner:c13} running
UserInfo{10:guest1:414}
We can then use a RegEx to pull out the required `userId` for a specific
user.
Finally `shell am switch-user {userId}` can be used to switch between
users on the device.
Emulators seem to create the main user with the name "Owner" so that should
be the default name we use for the main user. In the unit tests if we
cannot find a user named "Owner" when …
=> [Xamarin.Andrid.Build.Tests] Add MultiUser unit tests

build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/Steps/Step_DetermineAzurePipelinesTestJobs.cs
We don't need to package `Xamarin.Android.Legacy.targets`, as well as
the following `.targets` that are imported at the bottom of "legacy"
`.csproj` files:
* `Xamarin.Android.Bindings.targets`
* `Xamarin.Android.CSharp.targets`
* `Xamarin.Android.FSharp.targets`
* `Xamarin.Android.VisualBasic.targets`
Let's go ahead and exclude all of these files to be sure that
everything continues to work.
=> [One .NET] exclude "legacy" MSBuild targets from .NET 6 packages

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
Two more assemblies are linked away, that is probably result of multiple
linker related fixes going in together yesterday.
=> [illink] Update CheckIncludedAssemblies test

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
In `PerformanceTest`, I've been seeing the
`_ComputeResolvedCopyLocalPublishAssets` MSBuild target from the
dotnet/sdk take time on our CI on macOS:
_ComputeResolvedCopyLocalPublishAssets 183ms
This is in a build with no changes, and the target doesn't actually do
anything besides emit an `<ItemGroup/>`:
https://github.com/dotnet/sdk/blob/955c0fc7b06e2fa34bacd076ed39f61e4fb61716/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L708-L726
In application projects, we should be able to set
`$(PublishReferencesDocumentationFiles)` to `false`, so this target
will skip most of its work.
I have not found any proper documentation for
`$(PublishReferencesDocumentationFiles)`, but I believe the intention
is that `.xml` documentation files are copied to the build output from …
=> [One .NET] apps default $(PublishReferencesDocumentationFiles) to false

build-tools/automation/azure-pipelines.yaml
Follow up change to https://github.com/xamarin/xamarin-android/pull/5370
Provides useful information regarding the build who's calling the signing job.  When the build definition name and build number is passed, the signing job will set the build number to reflect the calling build.  This makes it much more convenient to immediately tell which build launched the signing job without having to dig into the logs.  It also leads to better information in our telemetry regarding the calling build.
Note: This change has also been applied to the d16-8 PR
=> [build] Pass more information regarding the build to the signing job

src/Microsoft.Android.Sdk.ILLink/PreserveLists/Mono.Android.xml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
Context: https://github.com/xamarin/xamarin-android/issues/5167
Instead preserve just methods accessed
from [native code](https://github.com/xamarin/xamarin-android/blob/master/src/monodroid/jni/monodroid-glue.cc).
=> [illink] Do not preserve whole JNIEnv class

.external
Changes: https://github.com/mono/mono/compare/ac596375c762c6b8dbe3c802f0ce626004eab51c...4fdfb5b1fd5a40a7e77342bb5146b7adee5e1322
* mono/mono@4fdfb5b1fd5: Bump bockbuild for gtk+ patch
* mono/mono@6f6c3286b66: [runtime] Avoid checking for hardened runtime on ios, its not needed, and it causes alerts because of PROT_WRITE|PROT_EXEC. (#20623)
* mono/mono@124f1157141: Fix iOS sdks build on Xcode 12 (#20574)
* mono/mono@dfbfe5eed19: [2020-02] Build makefile to support Mac Catalyst (#20566)
=> Bump to mono/mono/2020-02@4fdfb5b1

src/Microsoft.Android.Sdk.ILLink/PreserveLists/Mono.Android.xml, src/Mono.Android/Android.Runtime/JavaObject.cs
Context: https://github.com/xamarin/xamarin-android/issues/5167
Also remove `JavaObject.Clone ()` method, which should not be
needed.
This `Clone ()` method was pulling in a lot of API, through `ICloneable` iface.
When removed, it saves more than 900kbytes of compressed assembly size.
Summary:
-     942,460 Assemblies -43.72% (of 2,155,792)
-     947,763 Package size difference -10.50% (of 9,024,291)
Interestingly, it was pulling it in through the serialization code preserved
by the old `ApplyPreserveAttributeStep`. After https://github.com/xamarin/xamarin-android/commit/89edafcb17c61572f5ffaf1ae2a3bb7609979ae2
was merged, the difference is much smaller.
Summary:
-       3,382 Assemblies -0.36% (of 934,139)
-       4,096 Package size difference -0.05% (of 7,797,203)
In the end we are now …
=> [illink] Do not preserve whole JavaObject

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/release-scripts/blob/ce33e71cfe75f4ad098aa5f66c475e60582ccafb/notarize.ps1
We have received a request to migrate away from our Xamarin Notarization
logic and instead use a new ESRP Notarization script.  To do this we
need to first install the required MicroBuild plugin, and then call the
new `notarize.ps1` script.
=> [CI] Migrate to ESRP macOS notarization

build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5402
Some .NET 6 binding projects are failing with:
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Java.Interop.Tools.Generator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Java.Interop.Tools.Generator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Java.Interop.Tools.Generator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
File name: 'Java.Interop.Tools.Generator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
at MonoDroid.Generation.EnumMappings.ParseFieldMappings(TextReade …
=> [One .NET] include Java.Interop.Tools.Generator.dll in installer

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4291650&view=ms.vss-test-web.build-test-results-tab&runId=17600706&resultId=100198&paneView=attachments
We have occasionally seen failures under `dotnet build` such as:
Project should have built.
Expected: True
But then the diagnostic MSBuild log says:
Build succeeded.
0 Warning(s)
0 Error(s)
Looking at the logic in `Builder.BuildInternal()`, it seems like this
means the `ExitCode` was non-zero. There was no `Build Timed Out!` log
message either.
We should log the exit code, which might help diagnose the issue.
=> [Xamarin.ProjectTools] log ExitCode when MSBuild exits

Documentation/release-notes/aapt2-4.1.1.md, src/aapt2/aapt2.targets
Context: https://mvnrepository.com/artifact/com.android.tools.build/aapt2/4.1.1-6503028
Context: https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/tools/aapt2/
The result of `aapt2 version` changed:
```diff
-Android Asset Packaging Tool (aapt) 2.19-6051327
+Android Asset Packaging Tool (aapt) 2.19-6503028
```
The best release note I could find are:
https://android.googlesource.com/platform/frameworks/base/+/master/tools/aapt2/readme.md
However, I don't see how any of these map to the versions on Maven:
```diff
-compile group: 'com.android.tools.build', name: 'aapt2', version: '4.0.0-6051327', ext: 'pom'
+compile group: 'com.android.tools.build', name: 'aapt2', version: '4.1.1-6503028', ext: 'pom'
```
=> Bump to aapt2 4.1.1-6503028

.external
Context: https://github.com/dotnet/runtime/pull/35008#issuecomment-657402155
Context: https://github.com/mono/mono/issues/15418
Context: https://github.com/mono/mono/issues/16763
Context: https://github.com/mono/mono/issues/20490
Context: https://github.com/mono/mono/issues/20533
Context: https://github.com/xamarin/xamarin-macios/issues/9949
Changes: https://github.com/mono/mono/compare/be2226b5a1c57df065efc4c1cf008d581e5cec7d...5e9cb6d1c1de430965312927d5aed7fcb27bfa73
* mono/mono@5e9cb6d1c1d: Use explicit arithmetic checks in the amd64 watchOS simulator. (#20647)
* mono/mono@4fdfb5b1fd5: Bump bockbuild for gtk+ patch
* mono/mono@6f6c3286b66: [runtime] Avoid checking for hardened runtime on ios, its not needed, and it causes alerts because of PROT_WRITE|PROT_EXEC. (#20623)
* …
=> Bump to mono/mono/2020-02@5e9cb6d1

.gitmodules
Bump from lz4 v1.9.2 to v1.9.3.
Changes: https://github.com/lz4/lz4/compare/fdf2ef5809ca875c454510610764d9125ef2ebbd...d44371841a2f1728a3f36839fd4b7e872d0927d3
% git diff --shortstat fdf2ef58...d4437184
94 files changed, 2917 insertions(+), 1377 deletions(-)
Note: lz4/lz4 has no `master` branch.  Release tags are for commits
on the `release` branch.  Update `.gitmodules` accordingly.
=> Bump to lz4/lz4/release@d4437184 [v1.9.3]

.gitmodules
Changes: https://github.com/alitrack/mman-win32/compare/dbba5db192a4826c67ef03d68513c005ed689e8c...2d1c576e62b99e85d99407e1a88794c6e44c3310
* alitrack/mman-win32@2d1c576: Merge pull request #12 from constantined/patch-1
* alitrack/mman-win32@fd14269: Merge pull request #16 from ZachCook/patch-1
* alitrack/mman-win32@6556d4f: Support MAP_FIXED using MapViewOfFileEx
* alitrack/mman-win32@9f115ad: Merge pull request #15 from roydmerkel/master
* alitrack/mman-win32@3874169: Added --bindir install option to configure so we can specify the bindir parameter.
* alitrack/mman-win32@c6cc38f: Define bindir, libdir and incdir after custom PREFIX was set
An unexpected oddity: we previously used witwall/mman-win32, but
<https://github.com/witwall/mman-win32> is now an HTTP 301 (redirect)
to …
=> Bump to alitrack/mman-win32/master@2d1c576e

Configuration.props, Documentation/release-notes/manifestmerger-27.1.1.md, src/manifestmerger/build.gradle, src/manifestmerger/manifestmerger.csproj
Context: https://mvnrepository.com/artifact/com.android.tools.build/manifest-merger/27.1.1
Context: https://android.googlesource.com/platform/tools/base/+/master/build-system/manifest-merger
Other changes:
* `manifestmerger.csproj` does not need to reference `r8.csproj`.
* I removed `$(XAManifestMergerToolVersion)` as it was completely unused.
=> Bump to manifest-merger 27.1.1

Documentation/release-notes/r8-2.1.75.md, src/r8/build.gradle
Context: https://r8.googlesource.com/r8/+/refs/tags/2.1.75/
Context: https://mvnrepository.com/artifact/com.android.tools/r8/2.1.75
Bump r8 from 2.1.67 to 2.1.75.
=> Bump to r8 2.1.75

build-tools/xaprepare/xaprepare/Steps/Step_DetermineAzurePipelinesTestJobs.cs
Bump from ProGuard v7.0.0 to v7.0.1.
Changes: https://github.com/Guardsquare/proguard/compare/84e8560d325d80beec8f6d239af52a1095010010...912d149394fc96072905735649327d4101980832
* Guardsquare/proguard@912d1493: Bump to version 7.0.1
* Guardsquare/proguard@6a56cc22: Merge pull request #93 from Guardsquare/mrjameshamilton-patch-1
* Guardsquare/proguard@cecb95f8: Add release note for Kotlin 1.4 metadata fix
* Guardsquare/proguard@cbbecd81: Merge remote-tracking branch 'github/master'
* Guardsquare/proguard@46b7300d: Backport DGD-2494
* Guardsquare/proguard@679425e5: Add Gradle Kotlin DSL example
* Guardsquare/proguard@8532cfa2: Highlight README code snippets.
* Guardsquare/proguard@c70af673: Add 'getting help' section to README with community link.
* Guardsquare/proguard@d0e82308: Cleaned up …
=> Bump to Guardsquare/proguard/master@912d1493 [v7.0.1]

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4304485&view=ms.vss-test-web.build-test-results-tab&runId=17685428&resultId=100245&paneView=debug
Similar to what we saw in c7f1ccb8, the `DotNetLibraryAarChanges` test
can fail with:
res/raw/bar.txt should contain baz
String lengths are both 3. Strings differ at index 2.
Expected: "baz"
But was:  "bar"
Reviewing the build log, the `_GenerateAndroidResourceDir` and
`_CreateAar` MSBuild targets are skipped:
Skipping target "_GenerateAndroidResourceDir" because all output files are up-to-date with respect to the input files.
Input files: /Users/runner/work/1/s/bin/TestRelease/temp/DotNetLibraryAarChanges/obj/UnnamedProject.csproj.nuget.g.props;/Users/runner/Library/Android/dotnet/sdk/6.0.100-alpha.1.20562.2/NuGet.targets; …
=> [tests] add delay to DotNetLibraryAarChanges

Configuration.props, Documentation/release-notes/bundletool-1.4.0.md, build-tools/xaprepare/xaprepare/Steps/Step_DetermineAzurePipelinesTestJobs.cs
Context: https://github.com/google/bundletool/releases/tag/1.2.0
Changes: https://github.com/google/bundletool/compare/1.2.0...1.4.0
1.3.0
* Support generating and embedding source stamps in APKs generated
from Android App Bundles.
* `output-format` option for `build-apks` command that allows to
choose output format for generated APKs: APK Set archive or
directory.
* `include-metadata` option for `extract-apks` command that allows to
produce `metadata.json` file which contains information about
extracted APKs: module name and delivery type of the APK.
1.4.0
* Introduced DexMergingStrategy option in BundleConfig that allows to
skip dex merging for multidex applications with minSdk below 21.
* Conditional install-time modules can now depend on other
install-time modules.
Other changes:
* …
=> Bump to google/bundletool/1.4.0@f5c6dc66

build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
We are currently importing/using `Xamarin.Android.PCLSupport.targets`,
which does not appear to be needed at all in .NET 6.
Even if I add a PCL such as PCLStorage:
<PackageReference Include="PCLStorage" Version="1.0.2" />
The `ImplicitlyExpandDesignTimeFacades` target doesn't do any actual work:
Task "GetDependsOnNETStandard" skipped, due to false condition; ('$(_HasReferenceToSystemRuntime)' != 'true' and '$(_IsXBuild)' != 'true' and '$(DependsOnNETStandard)' == '' and '@(_XACandidateNETStandardReferences->Count())' != '0') was evaluated as ('true' != 'true' and 'true' != 'true' and '' == '' and '156' != '0').
Task "Message" skipped, due to false condition; ('%(ReferencePath.ResolvedFrom)' == 'ImplicitlyExpandDesignTimeFacades') was evaluated as ('{RawFileName}' == …
=> [One .NET] exclude Xamarin.Android.PCLSupport.targets

build-tools/automation/azure-pipelines.yaml
The homebrew/openssl related workaround/fix started failing recently with:
Error: No available formula or cask with the name "openssl@1.0.2t".
When running:
brew uninstall openssl@1.0.2t && rm -rf /usr/local/etc/openssl && rm -rf /usr/local/etc/openssl@1.1
@pjcollins thinks the original issue was fixed meanwhile, so we can remove it,
instead of fixing it by forcing the uninstall.
=> Remove brew/openssl workaround

src/monodroid/monodroid.targets
On macOS, I noticed this happening on every build:
$ msbuild src/monodroid -clp:performancesummary
...
2934 ms  _BuildHostRuntimes
41768 ms  _BuildAndroidRuntimes
The original cause was:
Building target "_BuildAndroidRuntimes" completely.
Output file "obj/Debug//armeabi-v7a-Debug/libxamarin-app.so" does not exist.
I updated the `Outputs` to use the correct file path:
```diff
-@(AndroidSupportedTargetJitAbi->'$(IntermediateOutputPath)\%(Identity)-Debug\libxamarin-app.so');
-@(AndroidSupportedTargetJitAbi->'$(IntermediateOutputPath)\%(Identity)-Release\libxamarin-app.so')
+@(AndroidSupportedTargetJitAbi->'$(OutputPath)\%(Identity)\Debug\libxamarin-app.so');
+@(AndroidSupportedTargetJitAbi->'$(OutputPath)\%(Identity)\Release\libxamarin-app.so')
```
Next, I was still hitting the problem, but …
=> [build] fix Inputs/Outputs for monodroid.csproj

Documentation/proposals/OneDotNetSingleProject.md
One theme for Xamarin in .NET 6 is to simplify the cross-platform
experience between iOS and Android. We would like to provide
cross-platform alternatives to `AndroidManifest.xml` and `Info.plist`.
The eventual goal would be to remove the need for these files for
simple apps and project templates. Developers would only need to
create them when a less widely used feature is needed. We would need
to create item templates for `AndroidManifest.xml` and `Info.plist`
when (and if) they are removed from project templates.
The concepts for a Xamarin "single project" go much beyond this. This
document is a starting point for what needs to go in the .NET Android
and Apple SDKs, while much of the remaining features would be in the
Xamarin.Forms/MAUI MSBuild targets.
This is a spec for the first …
=> [One .NET] proposal for "Single Project"

Documentation/release-notes/5431.md, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.ClassParse.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets, src/Xamarin.Android.Build.Tasks/Tasks/Generator.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
Apparently when we did NRT `generator` support for binding projects we did not actually update our MSBuild tasks to give `generator` the "enable NRT" flag.  Whoops.
The way this should work is if the binding project is using at least `<LangVersion>8</LangVersion>` and contains `<Nullable>enable</Nullable>`, this should trigger `generator` to generate binding code with nullable annotations.
The flag needed to pass to `generator` to trigger this is `--lang-features=nullable-reference-types`.
=> [Xamarin.Android.Build.Tasks] Enable NRT for bindings projects.

Documentation/release-notes/5266.md, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tasks/Javac.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ZipArchiveExTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/ZipArchiveEx.cs
While investigating another bug, I found that the code to look up
an existing entry in the zip was not working at all.
The problem was the filename we were looking up included a `/` at
the start of the path. The zip entires in the zip do not include a
`/` at the start. So the code was never finding a match. As a result
we were always trying to add a file rather than skipping those which
were up to date.
In addition I found that we do not always need to create entires in
the zip for directories. So when we create the `classes.zip` in the
`Javac` task we dont need to create directory entires. So we should
have a property to allow us to skip directories.
Also we should have the ability to turn the auto flush on/off.
There seems to be a small performance boost with these changes.
Old
```
749 …
```
=> [Xamarin.Android.Build.Tasks] Fix up ZipArchiveEx to handle updates.

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/5280
A test has been randomly failing with:
CSC : error CS2012: Cannot open 'C:\a\1\s\bin\TestRelease\temp\SolutionBuildSeveralProjects\Lib6\obj\Debug\Lib6.dll' for writing -- 'The process cannot access the file 'C:\a\1\s\bin\TestRelease\temp\SolutionBuildSeveralProjects\Lib6\obj\Debug\Lib6.dll' because it is being used by another process.'
I could reproduce this by putting `[Repeat(10)]` on the test. We
shouldn't commit this change, since the test took 5+ minutes.
The problem happens when:
* Build a `.sln` with two Android head projects that reference library
projects.
* Use `-m:4` to build with multiple MSBuild nodes.
* One of the head projects is running `<Csc/>` of a referenced project
at the same time …
=> [One .NET] fix parallel .sln builds

Documentation/guides/building-apps/build-properties.md, Documentation/release-notes/5278.md, src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/AddKeepAlivesStep.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Extensions.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Linker.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/LinkerOptions.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.CSharp.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
Context: https://github.com/xamarin/java.interop/issues/719
Modify "old" bindings, so that they hold the object reference
long enough to avoid above issue.
It is implemented as linker step, which looks for offended methods
and injects call to `System.GC.KeepAlive` to prevent premature
collection.
The injection can be disabled with `AndroidAddKeepAlives` property
set to false.
The property's default value depends on `AndroidIncludeDebugSymbols`
property and is thus true for release builds and false for debug.
The impact on release build of XA forms template (flyout variety) is
cca 137ms on my machine.
Disabled:
12079 ms  LinkAssemblies                             1 calls
Enabled:
12216 ms  LinkAssemblies                             1 calls
Example updated method body:
```
try { …
```
=> [linker] Add AddKeepAlivesStep

src/Mono.Android/Android.Runtime/AndroidRuntime.cs
Context: https://github.com/xamarin/xamarin-android/issues/5442
Apk size of BuildReleaseArm64False/net6 comparison:
apkdiff --bs -e dll$ before.apk after.apk
+         274 assemblies/Mono.Android.dll
Type Android.Runtime.AndroidTypeManager
-          42 Method System.Collections.Generic.IEnumerable`1<System.Type> GetTypesForSimpleReference (string)
-          33 Method public void RegisterNativeMembers (Java.Interop.JniType, System.Type, string)
+             Method System.Collections.Generic.IEnumerable`1<System.Type> <>n__0 (string)
-             Type <>c__DisplayClass11_0
-             Type <>c__DisplayClass11_1
+             Type <GetTypesForSimpleReference>d__2
-          67 assemblies/System.Private.CoreLib.dll
Type …
=> [Mono.Android] Remove more LINQ usage

src/Microsoft.Android.Sdk.ILLink/PreserveLists/Mono.Android.xml
Context: https://github.com/xamarin/xamarin-android/issues/5206
Context: https://github.com/xamarin/xamarin-android/issues/5167
They are only accessed through `CallbackCode` class in M.A.Export with
reflection code, which ILLink is able to detect.
This change reduces the apk size in common situation, when M.A.Export is
not used.
apk size comparison, BuildReleaseArm64False test:
> apkdiff -f -e dll$ before.apk after.apk
-          80 assemblies/System.Console.dll
-         129 assemblies/Java.Interop.dll
-       1,237 assemblies/System.Private.CoreLib.dll
-       6,093 assemblies/Mono.Android.dll
Summary:
-       7,539 Assemblies -1.01% (of 749,078)
=> [illink] Do not preserve IO stream adapter/invoker

src/Mono.Android/Mono.Android.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Tools.JavadocImporter/Xamarin.Android.Tools.JavadocImporter.csproj
Context: https://github.com/xamarin/xamarin-android/issues/5451
apk size comparison, BuildReleaseArm64False test:
> apkdiff -e dll$ before.apk after.apk
-         123 assemblies/Mono.Android.dll
-             Type Java.Interop.Tools.JavaCallableWrappers.Crc64
Type Java.Interop.Tools.TypeNameMappings.JavaNativeTypeManager
-             Method static string ToHash (string, System.Security.Cryptography.HashAlgorithm)
+             Method static string ToCrc64 (string)
+             Type Java.Interop.Tools.JavaCallableWrappers.Crc64Helper
-       2,975 assemblies/System.Security.Cryptography.Primitives.dll *1
Summary:
-       3,098 Assemblies -0.41% (of 749,039)
=> [illink] Use Crc64Helper class

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5437
In testing was I thought might be broken in #5437, everything seemed
to work fine! It will be good to include `.resx` files in a NET 6
test, however.
=> [tests] added .resx localization to .NET 6 test

Documentation/release-notes/5457.md, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
Fixes #5424
There is a bug in BuildApk where the Stream being passed to LibZipSharp
is NOT being disposed of. This is probably the cause of the classes.jar
file being left open.
=> [Xamarin.Android.Build.Tasks] Something leaves classes.jar files open until MSBuild exits

build-tools/installers/create-installers.targets
Context: https://github.com/xamarin/xamarin-android/pull/4690
As of Fast Deployment v2.0 we are no longer using the Shared Runtime
packages to fast deploy certain files.  It should be safe to remove
these from our installers at this time.
=> [Installers] Remove Shared Runtime .apks

build-tools/create-dotnet-pkg/create-dotnet-pkg.csproj, build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/Microsoft.Android.Sdk.BundleTool.proj, build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk.BundleTool/Sdk/Sdk.targets, src/Xamarin.Android.Build.Tasks/Microsoft.NET.Workload.Android/WorkloadManifest.in.json, src/Xamarin.Android.Build.Tasks/Microsoft.NET.Workload.Android/WorkloadManifest.targets
Context: https://github.com/xamarin/xamarin-android/issues/5438
This only implements half of #5438.
`bundletool.jar` is quite large:
24755974 bundletool.jar
Since this isn't needed for every build, only when
`$(AndroidPackageFormat)` is `aab`, we can put `bundletool.jar` in its
own "workload" pack.
The way this works is for `WorkloadManifest.targets` to define an
optional Sdk import:
<Import Project="Sdk.targets" Sdk="Microsoft.Android.Sdk.BundleTool"
Condition=" '$(AndroidPackageFormat)' == 'aab' " />
If the SDK is missing, for a build using `AndroidPackageFormat=aab`
you get the error:
Microsoft.NET.Workload.Android\WorkloadManifest.targets(4,33): error MSB4236: The SDK 'Microsoft.Android.Sdk.BundleTool' specified could not be found.
Our .NET 6 installers will include …
=> [One .NET] put bundletool.jar in separate workload pack

build-tools/xaprepare/xaprepare/Application/Context.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/Linux.Ubuntu.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/4929
Some releases of Ubuntu use only a single digit for their version, which
the `Version` class is not able to parse properly.  Add a special case
to handle it.
Additionally, don't hardcode `Ubuntu` into error message, use the
actual (derived) distro name instead.
=> [Linux] Properly parse single-digit Ubuntu version

src/Microsoft.Android.Sdk.ILLink/PreserveLists/Mono.Android.xml, src/Mono.Android/ILLink/ILLink.LinkAttributes.xml
Context: https://github.com/xamarin/xamarin-android/issues/5167
The attribute itself doesn't need to be preserved.
I didn't find any usage of the attribute instances during runtime, so
this change removes them during linking.
apk size comparison, BuildReleaseArm64False test:
> apkdiff -f -e dll$ before.apk after.apk
-          39 assemblies/Mono.Android.dll
+         132 Resource Android.ILLink.ILLink.LinkAttributes.xml
-             Type Android.Runtime.GeneratedEnumAttribute
Summary:
-          39 Assemblies -0.01% (of 749,078)
Note that the attribute instances removal doesn't work yet, we need
net6 illink for that.
=> [illink] Do not preserve GeneratedEnumAttribute

src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj, src/Microsoft.Android.Sdk.ILLink/SetupStep.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/AddKeepAlivesStep.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Extensions.cs, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
Context: https://github.com/xamarin/xamarin-android/issues/5427
Make the step build, add it to the illink custom step and let the test
run on net6.
=> [illink] Add AddKeepAlivesStep

src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingDebugNativeAssemblyGenerator.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5409
Context: a017561b1e44c51a9af79fae0baaa50fe01c4123
Context: bb55bb064b967adf8ca975928736346694dceb02
This is another commit in the series of properly handling the N:1 type
mapping from Java to Managed types.
a017561b implemented most of the handling properly, bb55bb064 fixed it
up for generic types but neither of the two commits accounted for the
situation when a Managed type map is requested that points back to a
duplicate Java type.  In fact, such Managed types were removed from the
typemap unless they were the type pointed to from the Java duplicate.
This meant that, effectively, all the `*Invoker` classes were not part
of the mapping, leading to this error for Debug builds:
app_process32: ---- DEBUG ASSERTION FAILED ---- …
=> [typemap] Handle managed -> Java duplicate mapping correctly

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.ClassParse.targets, tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/BindingTests.cs
Fixes: https://github.com/xamarin/java.interop/issues/767
Changes: https://github.com/xamarin/java.interop/compare/7574f166008bb45c0df97315aae7907ac25f8602...fdc200cca5676660dd8f732f4d7eef7716daa3df
* xamarin/java.interop@fdc200cc: [Xamarin.Android.Tools.Bytecode] Relax _ApiXml check (#772)
* xamarin/java.interop@f1b93653: [generator] Change generated code to not emit CA1305 warning. (#771)
* xamarin/java.interop@2244407d: [generator] Ensure DIM from assembly refs are correctly marked (#770)
* xamarin/java.interop@da73d6a5: [Java.Interop] Prevent premature collection w/ JniInstance* (#768)
Commit a7413a23 added support for invoking `java-source-utils.jar`
on `@(JavaSourceJar)` to extract Javadoc comments and translate them
into C# XML Documentation Comments.
What this can *also* do is …
=> Bump to xamarin/Java.Interop/master@fdc200cc

.gitmodules
Context: https://sqlite.org/releaselog/3_32_3.html
Context: https://sqlite.org/releaselog/3_33_0.html
Context: https://sqlite.org/releaselog/3_34_0.html
Changes: https://github.com/xamarin/sqlite/compare/3.32.2..3.34.0
=> Bump to xamarin/sqlite/3.34.0@c9eba82c

tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Context https://github.com/xamarin/monodroid/issues/1123
There seems to be a bug in the new fast deployment system
where if the dll was modified BUT had exactly the same size
as the existing dll on the device it would not be uploade.
This commit adds a test to make sure this does work as
expected.
=> [tests/MSBuildDeviceIntegration] Add test for dll's which have the same size.

Documentation/guides/building-apps/build-properties.md, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
Rename the `$(_AndroidUseInterpreter)` MSBuild property (42822e04)
to `$(AndroidUseInterpreter)`.
The property remains experimental.
=> [Xamarin.Android.Build.Tasks] Make $(AndroidUseInterpreter) public

build-tools/installers/create-installers.targets
Recent changes to monodroid and xamarin-android-tools have improved our
build task localization story, however it seems that these new files
never made it into our installers.
=> [Installers] Add missing localized assemblies

build-tools/create-packs/Microsoft.Android.Sdk.proj, build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Context: https://github.com/jonathanpeppers/foo/blob/Microsoft.NET.Sdk/foo.csproj
I've been experimenting with trying to multi-target "legacy"
Xamarin.Android and .NET 6 with:
<Project Sdk="Microsoft.NET.Sdk">
<TargetFrameworks>monoandroid11.0;net6.0-android</TargetFrameworks>
</Project>
I got this to work fairly well on Windows with some hacks, but it
completely fails on macOS:
error XACML7000: System.DllNotFoundException: Unable to load shared library 'MonoPosixHelper' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libMonoPosixHelper, 1): image not found
error XACML7000:    at Mono.Unix.Native.Syscall.lstat(String file_name, Stat& buf)
error XACML7000:    at …
=> [installer] extra copy of libMonoPosixHelper.dylib for libZipSharp.dll

src/Mono.Android/Java.Lang/Object.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/MainActivity.cs, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs, tests/api-compatibility/acceptable-breakages-vReference.txt
Context: https://github.com/xamarin/xamarin-android/issues/5454
The use of `DataContract` attribute on  `Java.Lang.Object` class pulls
in `System.Runtime.Serialization.Primitives` assembly.
We still need to make the `Java.Lang.Object` class serializable, so that
inherited types can be serialized. Otherwise that would lead to
`System.Runtime.Serialization.InvalidDataContractException` during
runtime.
Instead of decorating `Java.Lang.Object` with `DataContract` attribute,
use `Serializable` attribute on class and `NonSerialized` attribute on fields.
This might seem contraproductive, to use multiple attribute instances
instead of one. In real it is not and leads to size saving and getting rid
of `System.Runtime.Serialization.Primitives` assembly reference
in linked apps. Because the …
=> [illink] Redo Java.Lang.Object serialization

Documentation/release-notes/5477.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
@PureWeen ran into an error building this project in Xamarin.Forms:
https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Stubs/Xamarin.Forms.Platform.Android/Xamarin.Forms.Platform.Android%20(Forwarders).csproj
Xamarin.Android.Legacy.targets(467,5): error MSB3375: The file "obj\Debug\monoandroid10.0\__AndroidLibraryProjects__.zip" does not exist.
I could reproduce with VS 2019 16.9, but not 16.8.
The file did not actually exist?
> ls 'C:\src\Xamarin.Forms\Stubs\Xamarin.Forms.Platform.Android\obj\Debug\monoandroid10.0\__AndroidLibraryProjects__.zip'
ls : Cannot find path 'C:\src\Xamarin.Forms\Stubs\Xamarin.Forms.Platform.Android\obj\Debug\monoandroid10.0\__AndroidLibraryProjects__.zip' because it does not exist.
If you have a class library with 0 `@(AndroidResource)` files and use
AndroidX, …
=> [Xamarin.Android.Build.Tasks] fix build error for class library

Configuration.props, Directory.Build.props, build-tools/scripts/RoslynAnalyzers.projitems
If I open our `.sln` files in VS Windows, I start getting errors about
projects in `external/nrefactory` and `external/debugger-libs`:
"Xamarin.Android.sln" (default target) (1) ->
"tests\MSBuildDeviceIntegration\MSBuildDeviceIntegration.csproj" (default target) (53) ->
"tests\MSBuildDeviceIntegration\MSBuildDeviceIntegration.csproj" (Build target) (53:2) ->
"external\debugger-libs\Mono.Debugging.Soft\Mono.Debugging.Soft.csproj" (default target) (54:2) ->
"external\debugger-libs\Mono.Debugging\Mono.Debugging.csproj" (default target) (56:3) ->
"external\nrefactory\ICSharpCode.NRefactory\ICSharpCode.NRefactory.csproj" (default target) (57:3) ->
external\nrefactory\ICSharpCode.NRefactory\Documentation\XmlDocumentationProvider.cs(122,38): error CA3075: XmlTextReader …
=> [build] disable analyzers in IDE

build-tools/xaprepare/xaprepare/Application/Utilities.cs
Try to prevent download failures in CI downloads by increasing the
initial download timeout time from the current 250ms to 30s.  `xaprepare`
attempts the download up to 5 times, each time increasing timeout twofold.
Starting with 30s will, hopefully, decrease the number of timed out
downloads.
=> [xaprepare] Increase initial network download timeout to 30s

Documentation/guides/MSBuildBestPractices.md, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateCompressedAssembliesNativeSourceFiles.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveJdkJvmPath.cs, src/Xamarin.Android.Build.Tasks/Tasks/ValidateJavaVersion.cs, src/Xamarin.Android.Build.Tasks/Tasks/WriteLockFile.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/Aapt2Tests.cs, src/Xamarin.Android.Build.Tasks/Utilities/Aapt2Daemon.cs, src/Xamarin.Android.Build.Tasks/Utilities/MSBuildExtensions.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
Context: https://github.com/jonathanpeppers/Xamarin.Legacy.Sdk
When working on an experiment that enables multi-targeting such as:
<Project Sdk="Xamarin.Legacy.Sdk">
<TargetFrameworks>monoandroid11.0;net6.0-android</TargetFrameworks>
</Project>
I got the build error:
Xamarin.Android.Aapt2.targets(123,3): error MSB4018: The "Aapt2Compile" task failed unexpectedly.
System.InvalidCastException: [A]Xamarin.Android.Tasks.Aapt2Daemon cannot be cast to [B]Xamarin.Android.Tasks.Aapt2Daemon. Type A originates from 'Xamarin.Android.Build.Tasks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Build.Tasks.dll'. Type B …
=> [Xamarin.Android.Build.Tasks] cast with `as` for GetRegisteredTaskObject

build-tools/automation/azure-pipelines.yaml
Should fix this error during CI build:
"/Users/runner/work/1/s/build-tools/remap-assembly-ref/remap-assembly-ref.csproj" (default target) (1) ->
(ResolvePackageAssets target) ->
/Users/runner/.dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1004: Assets file '/Users/runner/work/1/s/build-tools/remap-assembly-ref/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/Users/runner/work/1/s/build-tools/remap-assembly-ref/remap-assembly-ref.csproj]
=> [tests] Add /restore to build remap-assembly-ref

Configuration.props, build-tools/remap-assembly-ref/remap-assembly-ref.csproj, build-tools/xaprepare/xaprepare/Steps/Step_DetermineAzurePipelinesTestJobs.cs
BCL Test phases are failing with:
remap-assembly-ref.cs(3,12): error CS0234: The type or namespace name 'Cecil' does not exist in the namespace 'Mono' (are you missing an assembly reference?)
The problem being `Mono.Cecil.dll` does not actually exist:
warning MSB3245: Could not resolve this reference. Could not locate the assembly "Mono.Cecil". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
This appears to have started failing since 49e570d8.
19c3b731 fixed the issue with needing `/restore`, but this is the next
issue...
Reviewing a build log from before 49e570d8, it *only* worked because
the build was pulling `Mono.Cecil.dll` from Mono's GAC:
Task ResolveAssemblyReference
Reference found at search path location …
=> [remap-assembly-ref] use Mono.Cecil from NuGet

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.AvailableItems.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
I was testing the new `@(AndroidLibrary)` item group, and noticed some
logic was backwards:
<EmbeddedJar          Include="@(AndroidLibrary)" Condition=" '%(AndroidLibrary.Extension)' == '.jar' and '%(AndroidLibrary.Bind)' != 'true' " />
<EmbeddedReferenceJar Include="@(AndroidLibrary)" Condition=" '%(AndroidLibrary.Extension)' == '.jar' and '%(AndroidLibrary.Bind)' == 'true' " />
`@(EmbeddedJar)` should be used when `%(Bind)` is `true`! Because it
is using `@(EmbeddedReferenceJar)` instead, we are not currently
generating C# bindings by default.
We had a test for this item group, but it didn't actually check the
output assembly has a C# class from the `@(AndroidLibrary)`.
I updated the test and fixed the logic here.
=> [Xamarin.Android.Build.Tasks] fix @(AndroidLibrary) in legacy Xamarin.Android

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/MacOS.cs
We've been seeing the attempts to install the recipe time out on our CI
servers:
Error: Process '/usr/local/bin/brew "install" "xamarin/xamarin-android-windeps/mingw-zlib"' timed out after 00:30:00
Error: Installation of xamarin/xamarin-android-windeps/mingw-zlib failed
Since the recipe existed only for the benefit of cross-building Mono for
Windows on macOS using mingw and we no longer do that, we can remove the
recipe.
=> [xaprepare] remove dependency on the windep homebrew recipe on mac

Configuration.props, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets
Changes: https://github.com/dotnet/installer/compare/efac3f25...47153b5f
We are hitting a problem inside Visual Studio, where our .NET 6
projects aren't able to build:
NETSDK1147: The following workload packs were not installed: Microsoft.Android.Sdk
`dotnet build` worked fine, but not inside the IDE. Updating .NET 6
solved this issue.
We haven't updated our build of .NET 6 since ~Nov 13, let's update!
=> Bump to .NET 6.0.100-alpha.1.21064.27

src/Xamarin.Android.Build.Tasks/Tasks/AndroidDotnetToolTask.cs
Context: https://github.com/xamarin/Xamarin.Legacy.Sdk
When building this project under `dotnet build`:
<Project Sdk="Xamarin.Legacy.Sdk">
<TargetFrameworks>monoandroid11.0;net6.0-android</TargetFrameworks>
</Project>
We are in a situation where `AndroidDotnetToolTask` will attempt to
run `generator.exe` for a "legacy" Xamarin.Android binding project.
This works on Windows, because you can just run `generator.exe`.
On Mac, however, we need to run `mono generator.exe`. If the runtime
is Mono, this happens implicitly:
https://github.com/mono/mono/blob/2020-02/mono/metadata/w32process-unix.c#L1745
https://github.com/mono/mono/blob/2020-02/mono/metadata/w32process-unix.c#L1236-L1363
But if the runtime is .NET 6, you get the error: …
=> [Xamarin.Android.Build.Tasks] run 'mono generator.exe' in some cases

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/StartAndroidEmulator.cs, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-msbuild-device-tests.yaml, build-tools/automation/yaml-templates/run-msbuild-mac-tests.yaml, build-tools/automation/yaml-templates/run-timezoneinfo-tests.yaml, build-tools/automation/yaml-templates/use-dot-net.yaml
All test jobs that were running on a macOS [Microsoft-hosted agent][1]
have been updated to use the 10.15 Catalina VM Image.  The majority of
these jobs were still running on High Sierra, and we have hit a number
of issues there recently when trying to install various brew tools.
Retry attempts have also been added to the `use-dot-net.yaml` template
to try to make dotnet SDK installation attempts more robust.
An initial attempt to use this image saw a few emulator jobs fail with:
/Users/runner/work/1/s/build-tools/scripts/TestApks.targets(57,5): Emulator failed to start: eglMakeCurrent failed in binding subwindow! [/Users/runner/work/1/s/tests/Mono.Android-Tests/Mono.Android-Tests.csproj]
The `StartAndroidEmulator` task has been updated to ignore this
output as it doesn't appear to be …
=> [ci] Migrate macOS test jobs to 10.15 Catalina

.external
Changes: http://github.com/xamarin/monodroid/compare/27736a7ffc48d606ab45598f761e873f8572f46a...ad19471b8478f9f8028c9a3517ad3ca7bca5fb4a
* [tools/msbuild] remove MSBuild targets related to the Xamarin Inspector
* [tools/msbuild] improve XA0010 error message
* [tools/msbuild] <FastDeploy/> Length cannot be less than zero
* Bump to xamarin/xamarin-analysis@9524531
* [tools/msbuild] FastDeploy is not ignoring warnings in output
=> Bump to xamarin/monodroid@ad19471

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunAndroidEmulatorCheckBootTimes.cs, build-tools/check-boot-times/Program.cs, build-tools/check-boot-times/check-boot-times.csproj
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4396987&view=logs&jobId=4ae5d5b0-7ab6-5bea-80fd-0525fc475851&j=4ae5d5b0-7ab6-5bea-80fd-0525fc475851&t=8f6971e6-2797-5530-8020-c2758d44f276
The `check-boot-times` tool has been failing intermittently across a
handful of CI runs.  I noticed that the tool will hang and eventually
fail with a process timeout when attempting to boot an emulator that is
already running.  In order to prevent this, the tool will now attempt to
close all emulators that are running before all "cold" or "hot" boot
attempts.  Additional output verbosity has also been enabled to help
with any future troubleshooting.
=> [check-build-times] Always close all running emulators

build-tools/automation/azure-pipelines.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4410378&view=logs&j=57fca568-3a80-5708-ac58-2fae4dd254ef&t=3f8f3a6c-0017-59f5-c4e0-9209d885e02d&l=134
We're running into issues installing the Microbuild Signing tools when
running PR builds from a fork.  To fix this, we'll only attempt to
install and use the signing tooling when attempting to "Real" sign.
=> [ci] Don't test sign PR builds

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/AndroidX/pull/247
When porting AndroidX to .NET 6, I noticed something odd... I was
getting `.aar` files in the build output that appeared to contain the
contents of `android-support-multidex.jar`.
Then I noticed:
https://github.com/xamarin/AndroidX/blob/16b02ae51980f7bab7be395d44f9998eea9bf32f/source/AndroidXProject.cshtml#L18
The AndroidX binding projects are setting `$(AndroidEnableMultiDex)`?
This is surely not intentional to be set in a class library, but this
causes `_AddMultiDexDependencyJars` to run:
<Target Name="_AddMultiDexDependencyJars">
<ItemGroup Condition=" '$(AndroidEnableMultiDex)' == 'True' AND '$(AndroidMultiDexSupportJar)' == '' ">
<AndroidJavaLibrary Include="$(MonoAndroidToolsDirectory)\android-support-multidex.jar" /> …
=> [Xamarin.Android.Build.Tasks] _AddMultiDexDependencyJars only runs for apps

build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs
We've been running into an issue when attempting to pack our .nupkg
files:
CreateAllPacks:
Directory "/Users/builder/azdo/_work/1/s/xamarin-android/bin/BuildRelease/nupkgs" doesn't exist. Skipping.
/Users/builder/Library/Android/dotnet/dotnet pack -p:Configuration=Release -p:NuGetLicense=/Users/builder/azdo/_work/1/s/xamarin-android/external/monodroid/tools/scripts/License.txt -p:AndroidRID=android.21-arm -p:AndroidABI=armeabi-v7a "/Users/builder/azdo/_work/1/s/xamarin-android/build-tools/create-packs/Microsoft.Android.Runtime.proj"
Found .NET SDK, but did not find dotnet.dll at [/Users/builder/Library/Android/dotnet/sdk/6.0.100-alpha.1.21064.27/dotnet.dll]
We should try to test the `dotnet` tool in this preview installation
location before using it, and reinstall the entire SDK if it …
=> [build] Attempt to fix broken dotnet preview installations

build-tools/automation/yaml-templates/run-nunit-tests.yaml, build-tools/scripts/nunit3-console.cmd
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4414611&view=logs&j=674b6335-1d71-5535-2f20-11f5708a0b9d&t=358dacbe-f0d4-5f52-9155-e5dfefeddb0c&l=67
Our Windows NUnit tests do not appear to be running at all:
Microsoft Windows [Version 10.0.17763.1282]
(c) 2018 Microsoft Corporation. All rights reserved.
C:\a\2\s>
It just seems to launch a `cmd` prompt and continue on?
I could reproduce this locally, which I could fix by using `cmd /c`:
https://docs.microsoft.com/windows-server/administration/windows-commands/cmd
Then I hit the next problem:
> & cmd /c 'C:\src\xamarin-android\build-tools/scripts/nunit3-console.cmd' bin\TestDebug\net472\Xamarin.Android.Build.Tests.dll --test foo
The system cannot find the path specified.
Reviewing `nunit3-console.cmd`, it seems to …
=> [build-tools/scripts] fixes for nunit3-console.cmd

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/WaitForAndroidEmulator.cs, build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/apk-instrumentation.yaml, build-tools/automation/yaml-templates/commercial-build.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/scripts/TestApks.targets, build-tools/xaprepare/xaprepare/Steps/Step_DetermineAzurePipelinesTestJobs.cs, tests/TestRunner.Core/TestInstrumentation.cs
Context: https://github.com/xamarin/xamarin-android/pull/5098
A new `azure-pipelines-nightly.yaml` build pipeline file has been added
to run our longer running build and test tasks that we don't want to run
against every commit or PR build.  This new pipeline is scheduled to run
every day at 3:00am UTC.  The pipeline will only run if there have been
source code changes since the last successful scheduled run.  For more
information see the [scheduled triggers documentation][1].
This new nightly pipeline starts with a commercial build on macOS, which
provides an opportunity to run time consuming Roslyn analyzers.  Other
code analysis steps can be added to this nightly build in the future.
After the build completes, the artifacts that are produced will be used
by new supplemental test jobs. …
=> [ci] Add nightly build and test pipeline

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/AddKeepAlivesStep.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
Context: https://github.com/xamarin/xamarin-android/issues/5562
Add `AddKeepAlivesStep` class to `LinkAssembliesNoShrink` task. This class overrides linker's `AddKeepAlivesStep` and provides corlib assembly without accessing linker context. It also provides logging for the step.
Test more scenarios with `AndroidAddKeepAlives`. Two of these scenarios led to a crash in the linker step before the fix - `Debug` configuration with `AndroidAddKeepAlives` enabled and `Release` configuration with linker mode set to `None`.
=> Fix LinkAssembliesNoShrink/AndroidAddKeepAlives crash (d16-9)

tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Context: https://github.com/xamarin/monodroid/pull/1156
This adds a class library project to `LocalizedAssemblies_ShouldBeFastDeployed`
that contains satellite assemblies.
The test now verifies that `es/Localization.resources.dll` is deployed.
=> [tests] add test for monodroid#1156

src/Xamarin.Android.Build.Tasks/Tasks/AndroidCreateDebugKey.cs, src/Xamarin.Android.Build.Tasks/Tasks/KeyTool.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4418226&view=ms.vss-test-web.build-test-results-tab&runId=18501656&resultId=100103&paneView=debug
Our .NET 6 MSBuild tests have a common failure on Windows & Mac:
Task "AndroidCreateDebugKey" (TaskId:407)
Task Parameter:StorePass=android (TaskId:407)
Task Parameter:ToolPath=C:\Users\AzDevOps\android-toolchain\jdk-11\bin (TaskId:407)
Task Parameter:KeyAlias=androiddebugkey (TaskId:407)
Task Parameter:Validity=10950 (TaskId:407)
Task Parameter:KeyAlgorithm=RSA (TaskId:407)
Task Parameter:StoreType=pkcs12 (TaskId:407)
Task Parameter:KeyPass=android (TaskId:407)
Task Parameter:Command=-genkeypair (TaskId:407)
Task Parameter:KeyStore=C:\Users\AzDevOps\AppData\Local\Xamarin\Mono for Android\debug.keystore (TaskId:407) …
=> [Xamarin.Android.Build.Tasks] warn for "alias already exists"

src/Mono.Android/Android.Runtime/AndroidRuntime.cs, src/Mono.Android/Android.Runtime/ConstructorBuilder.cs, src/Mono.Android/Java.Interop/TypeManager.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
Implement `JniValueManager.ActivatePeer` method
in `AndroidValueManager`.
Context: https://github.com/xamarin/xamarin-android/pull/5400
This allows us to remove SLE dependency and save cca 15% of assembly
size for XA simple Hello world app.
Size difference of `BuildReleaseArm64False` on net6:
+          96 assemblies/Mono.Android.dll
-         331 assemblies/System.Collections.Concurrent.dll
-         907 assemblies/Java.Interop.dll
-       1,003 assemblies/System.Linq.dll
-       3,856 assemblies/System.ObjectModel.dll *1
-       4,496 assemblies/System.Collections.dll *1
-       7,824 assemblies/System.Private.CoreLib.dll
-     115,284 assemblies/System.Linq.Expressions.dll *1
Summary:
-     133,605 Assemblies -15.33% (of …
=> [Mono.Android] Implement JniValueManager.ActivatePeer

.external
Changes: https://github.com/xamarin/monodroid/compare/bafd1393...aae6670c
* [ci] Bump relevant branches to use `main`, not `master`
* [tools/msbuild] fix when java_runtime_fastdev.jar is used
=> Bump to xamarin/monodroid/main@aae6670c

Documentation/guides/OneDotNet.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs
Related: https://github.com/xamarin/xamarin-android/issues/5436
In "legacy" Xamarin.Android, we have the following behavior:
1. The `Build` target does not produce an `.apk` or sign it.
2. Only `SignAndroidPackage` (or `Install`) would do this.
So if you hit F6, Ctrl+B, Command+B, etc. in Visual Studio, you don't
have to wait on a valid `.apk` file to be produced to get build
results. This is useful for incremental build performance -- and
developers' habit of hitting build all the time.
`dotnet build` has different behavior, because it should inherently
produce something that is runnable. `dotnet build` currently produces
an `.apk` file and signs it.
To match "legacy" Xamarin.Android's behavior in IDEs we could do
something different while in Visual Studio when …
=> [One .NET] no longer produce .apk for IDE builds

Documentation/building/unix/dependencies.md, build-tools/xaprepare/xaprepare/Application/GeneratedMakeRulesFile.cs, build-tools/xaprepare/xaprepare/OperatingSystems/MacOS.cs, build-tools/xaprepare/xaprepare/OperatingSystems/OS.cs, build-tools/xaprepare/xaprepare/ToolRunners/BrewRunner.MacOS.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5518
Context: https://github.com/xamarin/xamarin-android/projects/16
[Apple announced new Mac hardware][0], which use an [M1 CPU][1], which
is an arm64-compatible ABI, *not* intel based.  Legacy software built
for intel CPUs will still run via the [Rosetta][3] translation
environment.
Because of Rosetta, existing Xamarin.Android binaries will work as-is
on Mac hardware with M1 CPUs.
However, what if you want to *build* the xamarin-android repo on an
M1 CPU?
Previously, that would fail:
% make prepare PREPARE_AUTOPROVISION=true
…
Error: Could not find Homebrew on this system, please install it from https://brew.sh/
Unfortunately, [Homebrew][4] won't install by default:
% /bin/bash -c "$(curl -fsSL …
=> [build] Apple Silicon M1 build support

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4422361&view=ms.vss-test-web.build-test-results-tab&runId=18547936&resultId=100086&paneView=debug
We had an MSBuild test failing under .NET 6:
MSBuildDeviceIntegration On Device - macOS - One .NET > SwitchConfigurationsShouldRedeploy
fastdev directory should NOT exist for Release builds.
Expected string length 0 but was 4970. Strings differ at index 0.
Expected: <string.Empty>
But was:  "Java.Interop.dll\nMicrosoft.CSharp.dll\nMicrosoft.VisualBasic.C..."
This was because a supposed `Release` build was skipping the `_Upload`
target completely:
Skipping target "_Upload" because all output files are up-to-date with respect to the input files.
Input files: bin\Debug\UnnamedProject.UnnamedProject-Signed.apk...
It appears …
=> [Xamarin.ProjectTools] fix toggling XamarinProject.IsRelease

src/Xamarin.Android.Build.Tasks/Tasks/AndroidSignPackage.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
Fixes: #5553
Package signing attempts that do not use `apksigner.jar` can fail if the
provided `$(AndroidSigningKeyAlias)` has a space in it:
_Sign:
/Users/peter/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25/bin/jarsigner -keystore "test file.keystore" -storepass "test pass" -keypass "test pass" -digestalg SHA-256 -sigalg SHA256withRSA -signedjar bin/Release/mono.samples.button-Signed-Unaligned.apk /Users/peter/source/monodroid-samples/Button/obj/Release/android/bin/mono.samples.button.apk test alias
Only one alias can be specified
Please type jarsigner -help for usage
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2244,2): error MSB6006: "jarsigner" exited with code 1. …
=> [Xamarin.Android.Build.Tasks] Allow whitespace chars in $(AndroidSigningKeyAlias)

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/AddKeepAlivesStep.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
Context: https://github.com/xamarin/xamarin-android/issues/5562
Add `AddKeepAlivesStep` class to `LinkAssembliesNoShrink` task. This class overrides linker's `AddKeepAlivesStep` and provides corlib assembly without accessing linker context. It also provides logging for the step.
Test more scenarios with `AndroidAddKeepAlives`. Two of these scenarios led to a crash in the linker step before the fix - `Debug` configuration with `AndroidAddKeepAlives` enabled and `Release` configuration with linker mode set to `None`.
=> Fix LinkAssembliesNoShrink/AndroidAddKeepAlives crash

Configuration.props, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets
Changes: https://github.com/dotnet/installer/compare/47153b5f...f4682754
After updating, `Release` builds were failing with:
Fatal error in IL Linker
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\src\xamarin-android\bin\TestDebug\temp\DotNetBuildandroid.21-armTrue\UnnamedProject'.
File name: 'C:\src\xamarin-android\bin\TestDebug\temp\DotNetBuildandroid.21-armTrue\UnnamedProject'
at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, …
=> Bump to .NET 6.0.100-preview.1.21081.5

src/monodroid/jni/debug-app-helper.cc
When using `$(EmbedAssembliesIntoApk)=false` and
`/application/@extractNativeLibs="false"`, apps crash on startup with:
D debug-app-helper: Checking if libmonodroid was unpacked to /data/app/~~5pGpNKwo58itttVZIz8-GA==/UnnamedProject.UnnamedProject-Lh_MOHcs1J3EajxFou0uBg==/lib/arm64/libmonodroid.so
D debug-app-helper: /data/app/~~5pGpNKwo58itttVZIz8-GA==/UnnamedProject.UnnamedProject-Lh_MOHcs1J3EajxFou0uBg==/lib/arm64/libmonodroid.so not found, assuming application/android:extractNativeLibs == false
I debug-app-helper: Setting up for DSO lookup directly in the APK
D debug-app-helper: Added APK DSO lookup location: /data/app/~~5pGpNKwo58itttVZIz8-GA==/UnnamedProject.UnnamedProject-Lh_MOHcs1J3EajxFou0uBg==/base.apk!/lib/arm64-v8a
W debug-app-helper: Using runtime path: …
=> [monodroid] fix for Fast Dev & extractNativeLibs="false"

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets
Context: https://github.com/xamarin/xamarin-macios/pull/10552
After bumping .NET 6 in 240a3e1c, I found the
`CustomLinkDescriptionPreserve(Full)` test fails:
Linker test app did not run successfully.
Expected: True
This fails because we are producing an `.apk` file where the
`MainActivity` is completely linked away.
It seems that removing `@(TrimmerRootAssembly)` completely in 240a3e1c
only worked if `AndroidLinkMode` was `SdkOnly` and not `Full`.
I brought over the change that worked for Xamarin.iOS to fix this
issue.
=> [illink] fix for .NET 6 & AndroidLinkMode=Full

build-tools/automation/azure-pipelines.yaml, build-tools/xaprepare/xaprepare/Application/Context.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/MacOS.cs, build-tools/xaprepare/xaprepare/Main.cs
On CI the `APK instrumentation - MacOS` job is often failing with:
Error: Installation of mingw-w64 failed
The `mingw-w64` should not be needed for that job, so add a new option
for `xaprepare` to disable that installation.
=> [CI] Do not install mingw for APK instrumentation

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-msbuild-mac-tests.yaml, build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleLegacy.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsLegacy.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj
Context: https://github.com/xamarin/xamarin-android/issues/5441
Test legacy/dotnet simple/xforms Release builds apk sizes against
reference apkdesc files.
=> [tests] Let BuildReleaseArm64 test apk size

build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml
Context: https://github.com/xamarin/xamarin-android/pull/5589
We are working on upgrading our macOS build machines to macOS Catalina,
and in certain cases we'd like to continue to use an existing agent pool
rather than creating and authorizing a new one.  In those cases, the
existing pool will be updated to contain both Mojave and Catalina
machines.  We can make sure to always pick a Mojave machine by setting
a demand for the relevant system [capability][0] that any given
[machine may have][1].
[0]: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#capabilities
[1]: https://devdiv.visualstudio.com/DevDiv/_settings/agentqueues?agentId=688191&queueId=2206&view=capabilities
=> [ci] Set demand for macOS Mojave build machines

Xamarin.Android.sln, tools/decompress-assemblies/decompress-assemblies.csproj, tools/decompress-assemblies/main.cs, tools/scripts/decompress-assemblies
The utility is named `decompress-assemblies` and takes as its
parameters a list of files to decompress.  The files might be either
`.apk` archives or `.dll` files.
I case of `.apk`, managed assemblies stored in the `assemblies/`
directory inside the APK will be read and decompressed.
The uncompressed result is stored in the current directory with the
original assembly name modified to contain the `uncompressed-` prefix,
in order to prevent accidental overwriting of assemblies found in the
current directory.
=> [tools] Add a tool to decompress XA-compressed assemblies

Xamarin.Android-Tests.sln, Xamarin.Android.Build.Tasks.sln, Xamarin.Android.sln
Our solution files no longer match what VS2019 generates when it saves the file.  Although either version of the solution files work, they cause the local tree to be dirty, and can obscure actual intended changes to the solution file.
This commit loads the solution files in VS2019 16.8 and saves them.
The main changes are project types changing from `FAE04EC0-301F-11D3-BF4B-00C04F79EFBC` to `9A19103F-16F7-4668-BE54-9A1E7A4F7556`.  The former is the project type for long form C# projects and the latter is the project type for SDK style projects.
There are also some additional items VS wants to specify regarding Shared Projects.
=> [build] Sync solution files with what VS2019 16.8 generates.

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Context: https://github.com/xamarin/Xamarin.Legacy.Sdk
Xamarin.Legacy.Sdk is a way for .NET 6 projects to target older target
frameworks such as `monoandroid11.0`:
<Project Sdk="Xamarin.Legacy.Sdk">
<TargetFrameworks>monoandroid11.0;net6.0-android</TargetFrameworks>
</Project>
This adds a test that creates a `.nupkg` file verifying that
assemblies for both .NET 6 and "legacy" Xamarin.Android can be
produced.
=> [tests] add MSBuild test for Xamarin.Legacy.Sdk

build-tools/automation/azure-pipelines.yaml, build-tools/scripts/TestApks.targets, tests/Mono.Android-Tests/Runtime-AppBundle/Mono.Android-TestsAppBundle.csproj, tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj, tests/Mono.Android-Tests/Runtime-MultiDex/Mono.Android-TestsMultiDex.csproj
The AppBundle, MultiDex, and .NET 6 variants of Mono.Android-Tests will
now write their timing data to the same .csv file that is used for all
other Mono.Android-Tests variants.  This will allow us to compare
timing data from any Mono.Android-Tests run in the same chart.
See the [App Insights wiki][0] for more information on how we visualize
the startup timing that is being sent to App Insights.
[0]: https://github.com/xamarin/monodroid/wiki/Azure-Pipelines-and-DevOps#startup-timing-visualizations-using-app-insights
=> [ci] Add more Mono.Android-Tests data to App Insights

tools/decompress-assemblies/decompress-assemblies.csproj
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4445246&view=logs&j=cac0e8d3-0ef5-5d2b-b57e-e8fde7204df3&t=31862389-0152-5a37-13be-1c23abc1cf4f&l=18
Context: https://weblog.west-wind.com/posts/2019/Apr/30/NET-Core-30-SDK-Projects-Controlling-Output-Folders-and-Content
The `Windows Build & Smoke Test` phase is currently failing with:
bin\Release\bin\xabuild.exe Xamarin.Android-Tests.sln /restore /p:Configuration=Release /bl:C:\a\1\s\bin\TestRelease\msbuild-build-tests.binlog
...
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
C:\a\1\s\bin\Release\bin\bin\Release\bin\xabuild.exe /bl:C:\a\1\s\bin\TestRelease\msbuild-build-tests.binlog /p:Configuration=Release /restore …
=> [xabuild] fix dependencies from decompress-assemblies

build-tools/create-vsix/create-vsix.csproj, build-tools/create-vsix/create-vsix.targets
Notes:
* We have to import `Microsoft.NET.Sdk` manually at the top and
bottom, because `$(BuildDependsOn)` needs to be overridden *after*
`Sdk.targets`.
* `@(Compile)` and `@(None)` are auto-imported, remove them.
* `@(EmbeddedResource)` is auto-imported, use `Update` instead of
`Include`.
=> [create-vsix] convert to short-form MSBuild project

Configuration.props, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/StartAndroidEmulator.cs, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-timezoneinfo-tests.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs, tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs
The Timezone tests have been very unreliable recently. We speculate that this is down to the emulator not
running as fast as it used to on the CI system.
This PR attempts to make these tests more reliable. 
Firstly we will make use of the `NonParallelizable` attribute to ensure that the tests run in sequence. This 
is to stop them tripping over each other when setting the timezone. Next up we will add a `Retry` attribute
to at least re run a test once if it fails. This might help if the emulator is running slowly. 
Next we introduce the following code both before and after the test.
```
RunAdbCommand ($"shell am force-stop --user all {proj.PackageName}");
RunAdbCommand ($"shell am kill --user all {proj.PackageName}");
```
These commands will force the application to stop, and face any …
=> Make TimeZone tests more reliable.

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets
This allows for unnecessary code to be trimmed by default in an app. See https://github.com/dotnet/runtime/pull/47999.
=> Default InvariantGlobalization in Xamarin Android

.gitmodules
In order to target .NET 5/6 we need to build with `dotnet build`, which requires SDK style projects.
One set of `csproj` files that need to be updated is NRefactory.  The unit tests in Xamarin.Android use these assemblies along with the Mono debugging assemblies to ensure that changes do not break the ability to debug XA applications.
The "official" NRefactory repository that we currently use has been archived.  However, there already exists a Xamarin fork that the VSMac team uses.  The relevant project files we need in that repo have been converted to SDK style, so we simply need to point our git submodule to that fork.
=> [NRefactory] Switch to Xamarin fork that contains SDK style csproj.

build-tools/scripts/MonoAndroidFramework.props, build-tools/scripts/MonoAndroidFramework.targets, src/OpenTK-1.0/OpenTK.csproj, src/System.EnterpriseServices/System.EnterpriseServices.csproj, src/Xamarin.Android.NUnitLite/Xamarin.Android.NUnitLite.NET.csproj, src/Xamarin.Android.NUnitLite/Xamarin.Android.NUnitLite.csproj
In order to build the following projects:
* OpenTK.csproj
* System.EnterpriseServices.csproj
* Xamarin.Android.NUnitLite.csproj
These need to be `MonoAndroid` assemblies that import
`Xamarin.Android.CSharp.targets`. They are *not* built by `xabuild`.
At first you would think you could just do:
<Project Sdk="Microsoft.NET.Sdk">
<Import Project="$(OutputPath)\..\..\..\xbuild\Xamarin\Android\Xamarin.Android.CSharp.targets" />
</Project>
This yields a warning such as:
Xamarin.Android.CSharp.targets(50,5): warning MSB4011: "Microsoft.CSharp.targets" cannot be imported again.
It was already imported at "C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets (37,3)".
This is most likely a build authoring error. This subsequent import will be ignored.
We can change this to: …
=> [build] MonoAndroidFramework.props/targets for short-form MSBuild projects

NuGet.config, build-tools/automation/azure-pipelines.yaml
Context: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610
Context: https://azure.microsoft.com/en-us/resources/3-ways-to-mitigate-risk-using-private-package-feeds/
Context: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/12676/ncident-help-for-Substitution-attack-risk-from-multiple-package-feeds
Changes: https://github.com/xamarin/Java.Interop/compare/ee7b6bbe382bf408cc1a991e6149819889ad8c6c...b46598a254c20060b107312564e0ec0aee9e33d6
* xamarin/Java.Interop@b46598a2: Bump to xamarin/xamarin-android-tools/main@479931ce; packageSources (#796)
There is a Package Substitution Attack inherent in NuGet, whereby
if multiple package sources provide packages with the same name,
it is *indeterminate* which package source will provide the package.
For example, consider …
=> Bump to xamarin/Java.Interop/main@b46598a2; packageSources

build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-timezoneinfo-tests.yaml, build-tools/xaprepare/xaprepare/Steps/Step_DetermineAzurePipelinesTestJobs.cs
The broad set of TimeZoneInfo deployment tests don't need to be running
against every commit and PR build.  They should be moved to the Nightly
build and test pipeline that was introduced in commit 916d24b.  This 
will reduce PR build execution times and the overall machine time cost
of PR/CI builds.
=> [ci] Move TimeZoneInfo tests to Nightly pipeline

build-tools/automation/yaml-templates/commercial-build.yaml
Context: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=4463506&view=logs&j=96fd57f5-f69e-53c7-3d47-f67e6cf9b93e&t=65256bb7-a34c-5353-bc4d-c02ee25dc133&l=17445
Xamarin.Android pipeline builds have been failing during android-sdk-installer
NuGet restore attempts.  I am not yet sure why PR builds haven't been failing
in the same way, but this should hopefully fix the issue.
=> [ci] Use NugetAuthenicate for commercial builds

src/Mono.Android/Mono.Android.csproj
Context: https://github.com/mono/linker/blob/main/docs/data-formats.md#custom-attributes-annotations-format
Change the logical name of attributes embedded resource to
`ILLink.LinkAttributes.xml` instead of current
`Android.ILLink.ILLink.LinkAttributes.xml`
=> [illink] Set LinkAttributes logical name

src/Mono.Android/ILLink/ILLink.Substitutions.xml, src/Mono.Android/Java.Interop/TypeManager.cs, src/Mono.Android/Mono.Android.csproj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
Context: https://github.com/xamarin/xamarin-android/issues/5515
Context: https://github.com/dotnet/runtime/blob/master/docs/workflow/trimming/feature-switches.md#adding-new-feature-switch
Add new feature switch `XATypeRegistrationFallback` for type
registrations fallback. The switch default value is `false` for linked
net6 apps.
We can remove the fallback by the linker, because all the java to
managed type names lookup is now handled by typemap, so we should not
need this fallback anymore - at least not on device.
On desktop we still need it for Designer, which uses unlinked
assemblies and thus the fallback still works.
Also add lazy initialization of `packageLookup` field. That allows
linker to link the field away. That also improves startup performance,
as we don't create the dictionary …
=> [illink] Type registrations fallback switch

Documentation/guides/OneDotNet.md, Documentation/guides/messages/xa0035.md, Documentation/guides/messages/xa0036.md, build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/Microsoft.Android.Runtime.proj, build-tools/create-packs/Microsoft.Android.Sdk.proj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Utilities/ProjectExtensions.cs
When looking at the .NET runtime packs for iOS/Android:
Microsoft.Android.Runtime.android.21-arm
Microsoft.Android.Runtime.android.21-arm64
Microsoft.Android.Runtime.android.21-x86
Microsoft.Android.Runtime.android.21-x64
Microsoft.iOS.Runtime.ios-arm
Microsoft.iOS.Runtime.ios-arm64
Microsoft.iOS.Runtime.ios-x86
Microsoft.iOS.Runtime.ios-x64
Microsoft.NETCore.App.Runtime.android-arm
Microsoft.NETCore.App.Runtime.android-arm64
Microsoft.NETCore.App.Runtime.android-x86
Microsoft.NETCore.App.Runtime.android-x64
Microsoft.NETCore.App.Runtime.ios-arm
Microsoft.NETCore.App.Runtime.ios-arm64
Microsoft.NETCore.App.Runtime.ios-x86
Microsoft.NETCore.App.Runtime.ios-x64
It seems like we should not be putting the `.21` in the names of our
Android runtime packs.
In fact, this command does not work …
=> [One .NET] drop the .21 from android RIDs

src/monodroid/jni/monodroid-glue.cc
Context: https://github.com/xamarin/xamarin-android/issues/5619
It appears that Xamarin.Android application uploaded to Google Console
internal Test Track can fail the pre-launch test because the
`MonodroidRuntime::get_java_class_name_for_TypeManager` method, can
sometimes get a `nullptr` Java class name from JNI:
Build fingerprint: 'google/blueline/blueline:9/PQ3A.190801.002/5670241:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
pid: 15773, tid: 15773, name: com.Myapp  >>> com.Myapp<<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
x0  0000000000000000  x1  0000000000000000  x2  0000000000000000  x3  00000000000000e1
x4  0000000000000000  x5  0000000000000305  x6  0000000000000006  x7  0000000000000010
x8  0101010101010101  x9 …
=> [monodroid] Prevent a segfault when Java class name is unavailable

build-tools/create-packs/Directory.Build.props
Context: https://docs.microsoft.com/en-us/nuget/create-packages/set-package-type
Context: https://github.com/dotnet/runtime/blob/86d5d16d31ee46d619b4d9af510f307ed7da4846/src/installer/tests/Microsoft.DotNet.CoreSetup.Packaging.Tests/NuGetArtifactTester.cs#L142-L149
This is the pattern to follow for a package that is part of .NET that
people should not install directly. It prevents you from being able to
use `@(PackageReference)` for our packages -- which would not work
anyway.
If I review `Microsoft.NetCore.App.Runtime.android-arm.nuspec`, this
is how `$(PackageType)` is expressed within the `.nupkg` file:
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/10/nuspec.xsd">
<metadata>
<packageTypes>
<packageType name="DotnetPlatform" /> …
=> [One .NET] set $(PackageType) of DotnetPlatform

Directory.Build.props, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, tools/decompress-assemblies/decompress-assemblies.csproj, tools/xabuild/xabuild.csproj
I keep getting this error in VS Windows:
Detected package downgrade: System.Collections.Immutable from 1.7.1 to 1.7.0. Reference the package directly from the project to select a different version.
Xamarin.Android.Build.Tasks -> Microsoft.Android.Build.BaseTasks -> System.Collections.Immutable (>= 1.7.1)
Xamarin.Android.Build.Tasks -> System.Collections.Immutable (>= 1.7.0)
But command-line it seems to work fine?
It does seem like this package is behind compared to one used in
`xamarin-android-tools`, so let's just update it.
I also went ahead and created `$(SystemCollectionsImmutableVersion)`
in `Directory.Build.props` as this NuGet package is used in a few
places.
=> [Xamarin.Android.Build.Tasks] bump to System.Collections.Immutable 1.7.1

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AndroidLibraries.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Context: https://github.com/xamarin/Xamarin.Forms/tree/main-handler/src/Platform.Renderers/src/Xamarin.Forms.Platform.Android/Resources/anim
When porting some projects to .NET in Xamarin.Forms/MAUI, given a file
name such as:
Resources/anim/EnterFromRight.xml
The `Resource.designer.cs` file contained:
public static int enterfromright = 2130771997;
However, in "legacy" Xamarin.Android the casing was preserved:
public static int EnterFromRight = 2130771969;
I was able to reproduce this in `XASdkTests`. The problem was the new
`_ResolveAars` MSBuild target that resolves `.aar` files from
dependencies was not running in class libraries, only application
projects. My original thinking was that class libraries don't need
`@(AndroidAarLibrary)` defined, but they *do* for
`Resource.designer.cs` …
=> [One .NET] fix support for uppercase file names in class libraries

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
In https://github.com/dotnet/runtime/pull/47083, we are introducing the UseNativeHttpHandler feature switch.  This change sets the default to true for Android projects.
=> Set UseNativeHttpHandler project default

Xamarin.Android.sln
Allow VSWin to update the project type GUIDs in `Xamarin.Android.sln` from `FAE04EC0-301F-11D3-BF4B-00C04F79EFBC` (long form) to `9A19103F-16F7-4668-BE54-9A1E7A4F7556` (SDK-style).
These were the final projects that needed to be migrated to SDK-style, so this should be the final churn on the `.sln`.
=> [Xamarin.Android.sln] Update project type GUIDs for final SDK-style migrations.

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NuGet.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Context: https://github.com/dotnet/designs/blob/38bffe6c03a149c80f1c3b22787f33c794e71c76/accepted/2021/net6.0-tfms/net6.0-tfms.md
We don't have a complete implementation for .NET 6 & NuGet yet, so for
for things to work *at all* we have `Microsoft.Android.Sdk.NuGet.targets`
that contains workarounds that enable:
* Given some NuGet package, `Foo.nupkg`
* Try `lib/net6.0-android/Foo.dll`
* Try `lib/monoandroid10.0/Foo.dll`, other `$(TFV)` etc.
We can now test the above scenario with AndroidX NuGet packages:
* https://github.com/xamarin/AndroidX/pull/247
* https://pkgs.dev.azure.com/azure-public/vside/_packaging/xamarin-impl/nuget/v3/index.json
* `<PackageReference Include="Xamarin.AndroidX.AppCompat" Version = "1.2.0.7-net6preview01" />`
Unfortunately, consuming `Xamarin.AndroidX.AppCompat` …
=> [One .NET] update $(PackageTargetFallback) for NuGet packages

src/Mono.Android/Mono.Android.csproj
In https://github.com/xamarin/xamarin-android/pull/5253 we added support for generating XML documentation for `Mono.Android.dll` from Java source .jars.  However it adds a considerable amount of warnings to the build (40K+).
Add these 2 warning types to `<NoWarn>`.
```
C:\a\1\s\src\Mono.Android\obj\Release\monoandroid10\android-30\mcw\Android.Accounts.AccountManager.cs(2029,45): warning CS1658: Identifier expected. See also error CS1001. [C:\a\1\s\src\Mono.Android\Mono.Android.csproj]
C:\a\1\s\src\Mono.Android\obj\Release\monoandroid10\android-30\mcw\Android.Telephony.TelephonyManager.cs(207,21): warning CS1584: XML comment has syntactically incorrect cref attribute '#ACTION_SHOW_VOICEMAIL_NOTIFICATION' [C:\a\1\s\src\Mono.Android\Mono.Android.csproj]
```
Note XML Documentation is not …
=> [Mono.Android] Ignore some documentation warnings.

build-tools/enumification-helpers/methodmap.ext.csv, src/Mono.Android/methodmap.csv
The Android API methods:
```
Android.App.Service.GetForegroundServiceType ()
Android.App.Service.StartForeground (int, Android.App.Notification, Android.App.ForegroundService)
```
do not appear in `Mono.Android.dll` due to these warnings:
```
warning BG8700: Unknown return type 'Android.App.ForegroundService' for member 'Android.App.Service.GetForegroundServiceType ()'.
warning BG8800: Unknown parameter type 'Android.App.ForegroundService' for member 'Android.App.Service.StartForeground (int, Android.App.Notification, Android.App.ForegroundService)'.
```
This is because the return/parameter enum is mapped as `Android.App.ForegroundService` which does not exist.  Instead it should be `Android.Content.PM.ForegroundService`.
Update the mapping so these methods will get bound.
=> [Mono.Android] Fix incorrect mapping of Android.Content.PM.ForegroundService.

Configuration.props, src/Microsoft.Android.Sdk.ILLink/SetupStep.cs, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleLegacy.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsLegacy.apkdesc, tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj
Bump `DotNetPreview` version to `6.0.100-preview.1.21109.8`
Add linker reflection based workaround, till
the [new API](https://github.com/mono/linker/pull/1774) is ready to use.
It forces the `ILLink` to process all the referenced assemblies in our steps,
without it, no assemblies are processed before `MarkStep`.
Updated apk size reference files. The NET6 linker has more optimizations
enabled, assembly sizes decreased about 0.5% and native shared libraries
are smaller as well - about 0.7%.
Comparison of `BuildReleaseArm64` apk test sizes before/after
```
Simple XA NET6
Summary:
+           0 Other entries 0.00% (of 52,514)
+           0 Dalvik executables 0.00% (of 316,876)
-       3,237 Assemblies -0.47% (of 690,451)
-      34,992 Shared libraries -0.67% (of 5,202,312)
-       7,680 …
```
=> [net6] Bump DotNetPreview version to 6.0.100-preview.1.21109.8

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/AssertionExtensions.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildOutput.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
Context: https://github.com/xamarin/Xamarin.Forms/tree/main-handler
I noticed that when building Maui, `CoreCompile` seems to be running
on every build no matter what:
Building target "CoreCompile" completely.
Input file "obj\Debug\net6.0-android\Core-net6.csproj.CoreCompileInputs.cache" is newer than output file "bin\Debug\net6.0-android\Microsoft.Maui.xml".
I could reproduce this in a test:
* Build `AppA` & `LibraryB`
* Build `AppA` & `LibraryB` again, `LibraryB` will run `CoreCompile`
*every* time.
There is a `_GenerateCompileDependencyCache` target that basically does:
<Hash ItemsToHash="@(CoreCompileCache)">
<Output TaskParameter="HashResult" PropertyName="CoreCompileDependencyHash" />
</Hash>
<WriteLinesToFile
Lines="$(CoreCompileDependencyHash)" …
=> [One .NET] fix for incremental CoreCompile

Documentation/guides/building-apps/build-properties.md, src/Microsoft.Android.Sdk.ILLink/SetupStep.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/AndroidLinkConfiguration.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Extensions.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/GetAssembliesStep.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Linker.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/LinkerOptions.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/RemoveResourceDesignerStep.cs, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
The idea is to remove the `Resource` class NestedTypes from the final
linked assemblies in release mode. We do this by examining all the
locations where the fields are used and replacing those IL calls with a
call which specifies the actual resource id directly. This will remove
the need to call `global::Android.Runtime.ResourceIdManager.UpdateIdValues();`
completely. It will also allow us to completely remove the `Resource`
class sub classes. Due to an odd linker failure we cannot completely
remove the `Resource` class itself. However it will be completely empty.
As mentioned the call to `UpdateIdValues` will no  longer be required.
This should reduce startup time slightly. One thing to note is this will
only be true for Release apps when enabled. Debug apps will still
call …
=> [Xamarin.Android.Build.Tasks] Link Resource Nested Types from assemblies

build-tools/automation/azure-pipelines.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
Fixes? https://github.com/xamarin/xamarin-android/issues/5674
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4513530&view=ms.vss-test-web.build-test-results-tab&runId=19361000&resultId=100033&paneView=debug
Occasionally, we are seeing a test failure:
BuildReleaseArm64(True)
System.ComponentModel.Win32Exception : The system cannot find the file specified
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at Xamarin.Android.Build.Tests.BaseTest.RunProcessWithExitCode(String exe, String args) in C:\a\1\s\src\Xamarin.Android.Build.Tasks\Tests\Xamarin.Android.Build.Tests\Utilities\BaseTest.cs:line 287
at Xamarin.Android.Build.Tests.BaseTest.RunApkDiffCommand(String args) in C:\a\1\s\src\Xamarin.Android.Build.Tasks\Tests\Xamarin.Android.Build …
=> [ci] fixes for apkdiff and Dotnet Build phase

build-tools/automation/azure-pipelines.yaml
.NET 5.0.3 was released today, and now our CI `Dotnet Build and Smoke Test - Prepare Solution` breaks with:
```
"C:\Program Files\dotnet\dotnet.exe" build C:\a\1\s\Xamarin.Android.sln "-dl:CentralLogger,\"C:\a\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.181.0\dotnet-build-helpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll\"*ForwardingLogger,\"C:\a\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.181.0\dotnet-build-helpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll\"" -c Release -target:Prepare -m:1 -p:AutoProvision=true -bl:C:\a\1\s\bin\BuildRelease\dotnet-build-prepare.binlog
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.3' was not found.
- The following …
```
=> Update DotNet5Version to 5.0.3

build-tools/scripts/nunit3-console.cmd
Fixes: https://github.com/xamarin/xamarin-android/issues/5674
Context: https://www.tutorialspoint.com/batch_script/batch_script_variables.htm
Context: https://github.com/xamarin/xamarin-android/issues/5674#issuecomment-789012754
We noticed test failures on Windows do not fail the build:
Test Run Summary
Overall result: Failed
Test Count: 65, Passed: 63, Failed: 2, Warnings: 0, Inconclusive: 0, Skipped: 0
Failed Tests - Failures: 2, Errors: 0, Invalid: 0
Start time: 2021-03-02 12:33:22Z
End time: 2021-03-02 13:13:27Z
Duration: 2404.467 seconds
Results (nunit3) saved as TestResult-SmokeMSBuildTests-WinBuildTree-Release.xml
##[debug]$LASTEXITCODE: 0
##[debug]Exit code: 0
Reviewing `nunit3-console.cmd` it calls `set` at the end of the script
so it doesn't modify global variables:
set …
=> [nunit3-console.cmd] fix exit codes

src/Xamarin.Android.Build.Tasks/Tasks/FixupNuGetReferences.cs
I was attempting to build a project using some brand new Maui NuGet
packages and hit errors such as:
The type or namespace name 'MauiAppCompatActivity' could not be found
The type or namespace name 'MauiApplication<>' could not be found
These types are in:
%userprofile%\.nuget\packages\microsoft.maui.core\6.0.100-preview.2.179\lib\net6.0-android30.0\Microsoft.Maui.dll
Unfortunately, the build actually used the `netstandard2.1` assembly:
%userprofile%\.nuget\packages\microsoft.maui.core\6.0.100-preview.2.179\lib\netstandard2.1\Microsoft.Maui.dll
Our temporary `<FixNuGetReferences/>` MSBuild task should be the thing
that selects the correct assembly--but it didn't. When we have full
NuGet `$(TFM)` support, we won't need this task at all.
After reviewing the code, I think we need to check …
=> [One .NET] <FixNuGetReferences/> should also work for netstandard2.1

src/monodroid/jni/android-system.cc, src/monodroid/jni/android-system.hh, src/monodroid/jni/monodroid-glue.cc
This depends on a fix to mono/mono#18893 (make interp only mode distinct from `MONO_AOT_MODE_LAST`) which was done in mono/mono#20159 but only for .NET 6, not previous Mono releases.
Fixes https://github.com/xamarin/xamarin-android/issues/5633
=> [monodroid] Use MONO_AOT_MODE_INTERP_ONLY when available

Configuration.props, src/Microsoft.Android.Sdk.ILLink/PreserveLists/System.Private.CoreLib.xml, src/monodroid/jni/embedded-assemblies-zip.cc, src/monodroid/jni/mkbundle-api.h, src/monodroid/jni/monodroid-glue.cc, tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs
Bump net6 preview2 version, be in sync with iOS https://github.com/xamarin/xamarin-macios/blob/871e7b1cd0ca0e8434e94c8eedb168f33d5da2e8/Make.config#L500
Bump runtime pack version.
Added `System.Private.CoreLib.xml` as workaround for the crash in `GlobalizationNative_GetSortHandle`.
Context: https://github.com/dotnet/runtime/issues/49073
Stop using `mono_register_config_for_assembly` and `mono_config_parse_memory` functions,
they are gone from net6 runtime.
`BuildReleaseArm64` test, net6 apk size difference before/after
Simple XA:
```
Summary:
+           0 Other entries 0.00% (of 58,410)
+           0 Dalvik executables 0.00% (of 316,728)
-       7,699 Assemblies -1.10% (of 696,896)
-      41,704 Shared libraries -0.80% (of 5,196,608)
-      14,848 Uncompressed assemblies -1.09% (of …
```
=> Bump to net6 preview2 (6.0.100-preview.2.21114.3)

.external, Directory.Build.props, build-tools/installers/create-installers.targets
Changes Changes: https://github.com/xamarin/libzipsharp/compare/1.0.22...1.0.24
needs
=> Bump LibZipSharp to 1.0.24

tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Context: https://github.com/xamarin/xamarin-android/commit/0cd890bdf7fb0255f11d8c14e3de69c9e2691117
0cd890bd was committed despite one test,
`Xamarin.Android.Build.Tests.InstallTests.InstallWithoutSharedRuntime`,
failing. The test was failing because it didn't take into account that
the newly added native runtime builds stored their output in a directory
suffixed with `-net6` and it assumed that ABI name (e.g. `armeabi-v7a`)
was identical to directory name, thus failing to find the correct
runtime when running tests under NET6
Fix the issue by properly appending the `-net6` suffix when looking for
a matching runtime name while executing the test for NET6
=> [net6] Fix the `InstallWithoutSharedRuntime` test

Documentation/project-docs/ApkSizeRegressionChecks.md, build-tools/scripts/UpdateApkSizeReference.ps1, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleLegacy.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsLegacy.apkdesc
To make us have the reference files up-to-date.
Use new apkdiff's `--descrease-is-regression` option is used.
Added documentation, explain how to obtain the reference files. Also added
new simple powershell script to update the reference files locally.
Lower the thresholds to catch smaller regressions.
Also mention the need of Release XA builds. Context: https://github.com/xamarin/xamarin-android/issues/5675
=> Make apk size decrease regression as well

Configuration.props, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
Changes: https://github.com/dotnet/installer/compare/1868e585...e858d570
Context: https://github.com/xamarin/xamarin-macios/pull/10788
Also used the runtime pack version from:
> cat ~\android-toolchain\dotnet\sdk\6.0.100-preview.2.21153.28\dotnet.runtimeconfig.json
{
"runtimeOptions": {
"tfm": "net6.0",
"framework": {
"name": "Microsoft.NETCore.App",
"version": "6.0.0-preview.2.21123.7"
}
}
}
`BuildReleaseArm64` test, net6 apk size difference before/after
Simple XA:
```
Summary:
+           0 Other entries 0.00% (of 58,410)
+           0 Dalvik executables 0.00% (of 316,728)
-       1,038 Assemblies -0.15% (of 689,197)
-      12,824 Shared libraries -0.25% (of 5,154,904)
-       8,192 Package size difference -0.28% (of 2,910,062)
```
XF/XA:
```
Summary:
+           0 Other entries 0.00% …
```
=> Bump to .NET 6.0.100-preview.2.21153.28

Documentation/guides/building-apps/build-items.md, Documentation/guides/building-apps/build-process.md, Documentation/guides/building-apps/build-properties.md, Documentation/guides/building-apps/build-targets.md
Context: d8dea85c25f341224d6ef268fbf82620d9603b52
Context: https://github.com/MicrosoftDocs/xamarin-docs-pr/pull/2310
Context: https://github.com/MicrosoftDocs/xamarin-docs-pr/pull/2319
Commit MicrosoftDocs/xamarin-docs-pr#2310 was created by running:
msbuild /t:ExportXamarinDocs /p:XamarinDocsPath=/path/to/xamarin-docs/ Xamarin.Android.sln
This export was then edited to remove references to features to be
introduced in Xamarin.Android 11.3, *and* copy-edited to appease
[the all-mighty grammar gods][0].
Import the copy-edited text, and preserve the new Xamarin.Android 11.3
features:
msbuild /t:ImportXamarinDocs /p:XamarinDocsPath=/path/to/xamarin-docs/ Xamarin.Android.sln
[0]: https://github.com/Microsoft/vscode-docs-authoring
=> [docs] Synchronize with MicrosoftDocs/xamarin-docs

src/monodroid/CMakeLists.txt, src/monodroid/jni/build-info.hh, src/monodroid/jni/logger.cc, src/monodroid/jni/logger.hh, src/monodroid/jni/mono-log-adapter.cc, src/monodroid/jni/monodroid-glue-internal.hh, src/monodroid/jni/monodroid-glue.cc, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Bundle.apkdesc
Mono produces a lot of messages at various levels of severity which, if
enabled, can quickly fill the logcat buffer also contributing to a
higher signal-to-noise ratio for those users who don't need the
messages.  In order to put the amount of logging under control, this
commit implements logging handlers which take over the logging
responsibility from Mono and put it on Xamarin.Android.  Three log
handlers are registered:
* Mono tracing+logging
* `stdout`
* `stderr`
At the same time, the `debug.mono.log` system property gains two new
options, `mono_log_mask` and `mono_log_level`.  Both of them require a
value (described below), following the equals sign.
`mono_log_mask` corresponds to the `MONO_LOG_MASK` environment
variable (described in detail in the `mono(1)` manpage) and it accepts a …
=> [monodroid] Handle Mono log messages in XA runtime

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
A default value for `$(AndroidCommandLineToolsVersion)` is set in
xamarin/xamarin-android-tools, and we shouldn't override that value.
The default value of `11.0.99` for `$(LatestSupportedJavaVersion)` is
set in Xamarin.Android.Common.props.  The additional declaration in this
file is redundant.
=> [net6] Remove duplicate property defaults

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Context: https://github.com/xamarin/XamarinComponents/tree/master/Android/Guava/source/Guava
Looking at some of the patterns in the XamarinComponents repo, many of
the bindings commonly have a single `Transforms.xml` in the root of
the project. I think this pattern makes complete sense, so let's add
this to `AutoImport.props` by default.
I updated a test for this scenario, the test relies on the
`@(TransformFile)` wildcards working.
=> [One .NET] AutoImport.props should include Transforms.xml

Configuration.props, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
Changes: https://github.com/dotnet/installer/compare/e858d570...1a9103db
Also used the runtime pack version from:
> cat ~\android-toolchain\dotnet\sdk\6.0.100-preview.2.21155.3\dotnet.runtimeconfig.json
{
"runtimeOptions": {
"tfm": "net6.0",
"framework": {
"name": "Microsoft.NETCore.App",
"version": "6.0.0-preview.2.21154.6"
}
}
}
`BuildReleaseArm64` test, net6 apk size difference before/after
Simple XA:
```
Summary:
+           0 Other entries 0.00% (of 58,410)
+           0 Dalvik executables 0.00% (of 316,728)
+          81 Assemblies 0.01% (of 688,072)
-         144 Shared libraries -0.00% (of 5,147,624)
+           0 Uncompressed assemblies 0.00% (of 1,345,024)
+           0 Package size difference 0.00% (of 2,905,966)
```
XF/XA:
```
Summary:
+           0 Other entries 0.00% (of …
```
=> Bump to .NET 6.0.100-preview.2.21155.3

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/run-msbuild-device-tests.yaml, build-tools/automation/yaml-templates/run-msbuild-mac-tests.yaml, build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/TestEnvironment.cs
The legacy MSBuild test jobs have been updated to use JDK 1.8 in order
to retain some JDK 1.8 test coverage.  JDK 1.8 is still installed by VS
and VS Mac, and it is likely what the vast majority of our customers
use today.
The Xamarin.ProjectTools.Builder and Xamarin.ProjectTools.DotNetCLI
classes are used for all Xamarin.Android.Build tests that need to invoke
msbuild or dotnet build.  Both of these wrapper classes will append
`/p:JavaSdkDirectory=$PATH` to all msbuild/dotnet build invocations, and
they use the same logic from Xamarin.ProjectTools.AndroidSdkResolver to
look up the JDK path.  See 16e971f29fc39639a9a245811e10bf9fd3c5047e for
more details.
This look up first checks to see if `$(JavaSdkDirectory)` is set in
Configuration.OperatingSystem.props.  This file is generated by an …
=> [ci] Use JDK 1.8 for legacy MSBuild test jobs

tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj, tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs
Context: https://github.com/dotnet/msbuild/issues/6225
Context: https://www.nuget.org/packages/MSBuild.StructuredLogger/
In .NET 6 Preview 2, the `.binlog` file format version increased. This
means we can no longer use the latest MSBuild NuGet packages to parse
these files. 16.9.0 isn't recent enough:
https://www.nuget.org/packages/Microsoft.Build/16.9.0
Instead, we can use the MSBuild.StructuredLogger package used by the
[MSBuild binlog viewer](https://msbuildlog.com), as it is able to read the new
`.binlog` format. It also is quite a bit less code to do what we need.
Going forward, this package should be the best for parsing `.binlog`
files when using .NET 6 Preview builds.
=> [tests] reenable .NET 6 build performance tests

Documentation/guides/building-apps/build-items.md, Documentation/guides/building-apps/build-properties.md, Documentation/release-notes/5327.md, src/Xamarin.Android.Build.Tasks/Tasks/BuildApkSet.cs, src/Xamarin.Android.Build.Tasks/Tasks/InstallApkSet.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context #4810
When using app bundles users install the application from an `apkset`.
At this time this only contains the base application. However we might
in the future support dynamic features in some fashion. In this case
developers should be able to pick which features they want installed.
This commit adds an `AndroidInstallModules` ItemGroup which will allow
developers to specify which modules to install. By default it will be
empty. This means all modules which are to be installed on first install
will be installed. So there is no change in the current behavior.
This commit also adds support for passing additional arguments to 
`bundle tool` via the new `AndroidBundleToolExtraArgs` property.
=> [Xamarin.Android.Build.Tasks] Allow users to specify modules for apk sets.

src/Mono.Android/Android.Runtime/AndroidEnvironment.cs, src/Mono.Android/Android.Runtime/Logger.cs, src/Mono.Android/ILLink/ILLink.Substitutions.xml, src/Mono.Android/Java.Interop/TypeManager.cs, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
Context: https://github.com/xamarin/xamarin-android/issues/5622
Do not fallback to `System.Console.WriteLine` in our logger on devices.
We still need that for designer. That saves another 2.83% of assembly
size in simple XA `BuildReleaseArm64` test app.
Lets use the type registration fallback feature switch to hide
the fallback and rename it to `VSAndroidDesigner` as both
of these fallbacks are only used by the designer. Also move
it to `AndroidEnvironment` class.
Update the `CheckIncludedAssemblies` test, we just got rid of another
assembly :-)
Size savings, simple XA/net6 `BuildReleaseArm64` test:
Summary:
-         202 Other entries -0.35% (of 58,410)
+           0 Dalvik executables 0.00% (of 316,728)
-      19,471 Assemblies -2.83% (of 688,072)
-          64 Shared libraries -0.00% …
=> [illink] Do not fallback to S.Console in Logger

Documentation/project-docs/ApkSizeRegressionChecks.md, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/ApkDiffCheckRegression.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Aot.apkdesc, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Profiled-Aot.apkdesc, tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release.apkdesc, tests/apk-sizes-reference/com.companyname.vsandroidapp-Signed-Release.apkdesc
Add more detail about apk size regression testing.
Add `--descrease-is-regression` to `apkdiff` arguments for APK
instrumentation tests.
Add link to `ApkSizeRegressionChecks.md` document to the failed check
messages.
Updated the reference files. The change with `--descrease-is-regression` did
kick in and we need to refresh the reference files, because we have smaller
apks compared to the last time we updated these.
=> [doc] More info about size regression checks

src/Xamarin.Android.Build.Tasks/Microsoft.NET.Workload.Android/WorkloadManifest.in.json
I got report of M1 Macs failing to build .NET 6 Android projects:
Microsoft.NET.Sdk.ImportWorkloads.targets(24,5): error NETSDK1147: The following workload packs were not installed: Microsoft.Android.Sdk
Looking at our `WorkloadManifest.json`, we did not define an
`alias-to` for M1 Macs. Manually editing `WorkloadManifest.json`
solved the problem for them.
This gets us closer to M1 working.
There is now a new failure we can address next:
Xamarin.Android.EmbeddedResource.targets(36,5): error XARLP7000: System.DllNotFoundException: Unable to load shared library 'libzip' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibzip, 1): image not found
at Xamarin.Tools.Zip.Native.zip_open(IntPtr path, …
=> [One .NET] allow M1 macs to find the Android workload

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
The `MissingOrgApacheHttpClient` test seems to fail on a regular basis.
This is probably down to networking issues, so we should retry this
test a few times just in case.
=> [Xamarin.Android.Build.Tests] Retry MissingOrgApacheHttpClient.

build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/azure-pipelines.yaml
As part of some Azure subscription clean up efforts I've created a new
Windows virtual machine scale set in our new
[Xamarin - SDK Engineering][0] Azure subscription.  This VMSS uses the
same base image as our existing Windows Build and Test pool and should
behave in the same way.
[0]: https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/cd4829e2-e38b-43d2-8316-2f2009f36f97/resourceGroups/DEVDIV-VM-SCALE-SETS/providers/Microsoft.Compute/virtualMachineScaleSets/xawin2019-vmss/overview
=> [ci] Migrate Windows build and test to new VMSS

Configuration.props, src/Microsoft.Android.Sdk.ILLink/PreserveLists/System.Private.CoreLib.xml, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidCommonProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidWearApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsAndroidApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsXASdkProject.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc, tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs, tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj
At first, Android "Hello World" fails with:
> dotnet build -c Release
ILLink : error IL1009: Assembly 'System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' reference 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' could not be resolved
Dropping the `--skip-unresolved false` switch passed to ILLink solves
this issue. This was a recommendation from Sven Boemer on the .NET team.
A nice, side-effect, is we no longer need workarounds like this any
longer:
<ItemGroup Condition=" '$(Configuration)' == 'Release' ">
<PackageReference Include="System.CodeDom" Version="6.0.0-*" />
<PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0-*" />
<PackageReference …
=> Bump to .NET 6.0.100-preview.3.21161.23

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ProjectCapabilities.targets
- this property will be defined on single projects to use launch profiles capability required on VisualStudio
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1291512
When a single-project is loaded on VisualStudio, to enable the switch between target frameworks the LaunchProfiles capability need to be enabled. 
By default, it is enabled but this capability is removed by our SDKs because the HEAD projects (Android and iOS) does not use this IDE feature to display devices on the start button.
The _KeepLaunchProfiles property avoids that removal in order to have LaunchProfiles enabled on VisualStudio.
MAUI targets adds _KeepLaunchProfiles with the value true to enable it for single-project.
=> Avoids to remove the launch profiles capability when the _KeepLaunchProfiles property is true

Documentation/building/unix/instructions.md, Documentation/building/windows/instructions.md, build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/commercial-build.yaml, build-tools/create-packs/Directory.Build.props, build-tools/create-packs/Directory.Build.targets, src/Microsoft.Android.Templates/Microsoft.Android.Templates.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs, tests/Mono.Android-Tests/Directory.Build.targets
The `installers`, `nupkg`, `nupkg-linux`, and `net6-pkg` Azure Pipelines
Artifacts have been renamed to better indicate their signing statuses.
The first three artifacts have been renamed to `installers-unsigned`,
`nuget-unsigned`, and `nuget-linux-unsigned` respectively.  The
`net6-pkg` artifact will be uploaded as `net6-pkg-unsigned` or
`net6-pkg-signed` depending on whether or not real signing occurred
before upload.
Additionally, the MicroBuild tooling installation/uninstallation has
been removed from the commercial-build.yaml template. While the existing
condition will prevent these tasks from running, the fact that they
exist at all in the nightly YAML is [halting the job][0].  We don't want
to grant this permission on this pipeline, and we can fix it by moving
the MicroBuild tasks …
=> [build/ci] Rename installer and nuget artifacts

Configuration.props, NuGet.config, build-tools/create-dotnet-msi/create-dotnet-msi.csproj, build-tools/create-dotnet-pkg/create-dotnet-pkg.csproj, build-tools/create-packs/Directory.Build.targets, build-tools/xaprepare/xaprepare/Application/Context.cs, build-tools/xaprepare/xaprepare/Application/KnownProperties.cs, build-tools/xaprepare/xaprepare/Application/Properties.Defaults.cs.in, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs, build-tools/xaprepare/xaprepare/package-download.proj, build-tools/xaprepare/xaprepare/xaprepare.csproj, build-tools/xaprepare/xaprepare/xaprepare.targets, eng/README.md, eng/Version.Details.xml, eng/Versions.props, global.json, src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
Context: https://github.com/dotnet/arcade/blob/ea609b8e036359934332480de9336d98fcbb3f91/Documentation/Darc.md
The dotnet core engineering group has some dependency management tooling
(known as `darc`) that we'd like to adopt.  Integrating this tooling in
to the build system will make it easier to stay up to date with the
latest .NET 6 SDK changes.
Many dotnet repos use a [publishing workflow][0] that will push build
artifact data to a central location known as the "Build Asset Registry".
This data includes a "[Channel][1]" association, which is the key to
dependency updating.  Local updates and automatic update "Subscriptions"
compare the version files in a given repo against the product versions
avalable in the channel that you are interested in.
We hope to be able to publish Xamarin SDK …
=> [build] Use arcade dependency management tooling

Xamarin.Android.sln, build-tools/provisioning/vs2019.csx, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, src/monodroid/CMakeLists.txt
Fixes: https://github.com/xamarin/java.interop/issues/790
Changes: https://github.com/xamarin/java.interop/compare/bba1f077ae9886cdcc3e35fee35386937ce885dc...3824b974dada6f302ed5f7b7f97ffbd08990a82a
* xamarin/java.interop@3824b974: [java-interop] Windows build system support (#816)
* xamarin/java.interop@94c0c709: Bump to xamarin/xamarin-android-tools/main@554d45a (#813)
* xamarin/java.interop@5c756b14: [Java.Interop-PerformanceTests] Support .NET Core 3.1 (#808)
* xamarin/java.interop@daec07b6: [build] Fix various warnings (#812)
* xamarin/java.interop@678c4bd2: [class-parse, generator] Allow showing Kotlin internals via metadata (#793)
* xamarin/java.interop@cd4c8f80: [jnienv-gen] Generate a header file for the native functions (#809)
* xamarin/java.interop@69767c1a: …
=> Bump to xamarin/Java.Interop/main@3824b974

build-tools/automation/azure-pipelines-nightly.yaml
In commit 952e67be nightly build script was missing a `/` in one of the templates
this was causing
```
/build-tools/automation/azure-pipelines-nightly.yaml:
Could not find /build-tools/automation/yaml-templatesupload-results.yaml
in repository self hosted on https://github.com/ using commit
952e67be871b517208aa62ad6ae6679043669d8f.
GitHub reported the error, "Not Found"
```
=> [automation] Fix typo in commit 952e67be

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tasks/BuildBaseAppBundle.cs
Fixes https://work.azdo.io/1288593
This is a weird bug which I cannot reproduce locally. However reading
the code this code path is possible.
When trying to do incremental builds when using the `AndroidPackageFormat`
`aab` we get the following error
[BT : 1.4.0] error : Module 'base' is missing mandatory file 'manifest/AndroidManifest.xml'.
The problem is the base.zip doesn't have ANY AndroidManifest.xml in it...
But why?
Well what seems to happen is in this case the input file `packaged_resources`
and the output `base.zip` are unchanged. `packaged_resources` has
an `AndroidManifest.xml` file and `base.zip` has a `manifest/AndroidManifest.xml`
file. Because it was renamed from `AndroidManifest.xml` to `manifest/AndroidManifest.xml`
on a previous build. This is so that our `base.zip` …
=> [Xamarin.Android.Build.Tasks] Xamarin.Android deployment fails unless project is cleaned first

.gitmodules
Context: https://sqlite.org/releaselog/3_35_0.html
Context: https://github.com/xamarin/sqlite/compare/3.34.1..3.35.0
The most important upstream changes are:
* Fix a potential NULL pointer dereference when processing a
syntactically incorrect SELECT statement with a correlated WHERE
clause and a "HAVING 0" clause. (Also fixed in the 3.34.1 patch
release.)
* Fix a bug in the IN-operator optimization of version 3.33.0 that
can cause an incorrect answer.
* Fix incorrect answers from the LIKE operator if the pattern ends
with "%" and there is an "ESCAPE '_'" clause.
=> Bump to xamarin/sqlite/3.35.0@e399aec07

Documentation/building/unix/instructions.md, Documentation/building/windows/instructions.md, build-tools/automation/azure-pipelines.yaml, build-tools/create-dotnet-pkg/create-dotnet-pkg.csproj, build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/Microsoft.Android.Sdk.proj, src/Xamarin.Android.Build.Tasks/Microsoft.NET.Workload.Android/WorkloadManifest.in.json
When reviewing our `WorkloadManifest.json`, we realized that 32-bit
Windows was not listed.
However, 32-bit Windows should already work because:
* We ship 32 & 64-bit `libzip.dll`
* `aapt2.exe` is 32-bit
`Microsoft.Android.Sdk` needs to support both 32 & 64-bit, because you
can run `MSBuild.exe` in either:
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe"
By default MSBuild is 32-bit on Windows, as well as inside Visual Studio.
After reviewing the names of packages, using RIDs does not really make
sense. The `osx-x64` and `win-x64` packages are actually Mac & Windows
packages, regardless of the architecture.
Let's rename the packages to …
=> [One .NET] rename to Microsoft.Android.Sdk.$(HostOS)

.gitmodules
Context: https://sqlite.org/releaselog/3_35_1.html
Context: https://sqlite.org/releaselog/3_35_2.html
The most important upstream changes are:
* Fix a [bug][0] in the new DROP COLUMN feature when used on columns that
are indexed and that are quoted in the index definition.
* Fix a problem in the appendvfs.c extension that was introduced into
version 3.35.0.
[0]: https://www.sqlite.org/src/info/1c24a659e6d7f3a1
=> Bump to xamarin/sqlite/3.35.2@afa0437d

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Tooling.targets
In .NET 6, we set a `$(_XATargetFrameworkDirectories)` MSBuild
property to be used throughout the legacy MSBuild targets:
_XATargetFrameworkDirectories =
...\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-preview.2.21154.6\ref\net6.0\
...\dotnet\packs\Microsoft.Android.Ref\11.0.200-ci.main.148\ref\net6.0\
However, when testing a new workload for .NET Maui we hit the error:
error XARSD7004: System.ArgumentException: `...\dotnet\packs\Microsoft.Maui.Controls.Ref\0.0.1-alpha1\ref\net6.0` must be a directory! (Parameter 'frameworkDirectories')
error XARSD7004:    at Xamarin.Android.Tools.AndroidVersions..ctor(IEnumerable`1 frameworkDirectories) in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Xamarin.Android.Tools.AndroidSdk/AndroidVersions.cs:line 30
error …
=> [Xamarin.Android.Build.Tasks] fix for .NET 6 targeting pack locations

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5751
After bumping to .NET 6 Preview 3, we get hundreds of ILLINK warnings.
This is because of:
https://github.com/dotnet/sdk/pull/16327
We need to default `$(SuppressTrimAnalysisWarnings)` to ignore these
warnings for now.
We should continue to use `TrimMode=link`, as that is the behavior
Xamarin developers get today.
=> [One .NET] default $(SuppressTrimAnalysisWarnings) to true

build-tools/check-boot-times/Program.cs, build-tools/scripts/TestApks.targets, build-tools/xaprepare/xaprepare/Steps/Step_Android_SDK_NDK.cs, src/Xamarin.Android.Build.Tasks/Tasks/CalculateProjectDependencies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/GetDependenciesTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://developer.android.com/studio/releases/sdk-tools
The Android SDK Tools package has been deprecated since 2017 and is
no longer receiving updates.
Remove all usage of the Android SDK Tools package.
=> Remove support for the Android SDK Tools Package

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/GitBranch.cs
I noticed the version from our builds on `main` has an odd version
number:
Microsoft.NET.Workload.Android.11.0.200-ci.171cccd1fa1486df9ced3a5eb34001b9ac65d4b0.186.nupkg
When I look at logs, it seems like this command:
> git name-rev --name-only --exclude=tags/* HEAD
171cccd1fa1486df9ced3a5eb34001b9ac65d4b0
But locally, I get:
> git name-rev --name-only --exclude=tags/* HEAD
main
When I look at the logs for checkout, it seems like Azure DevOps has
fundamentally changed how it checks out a branch?
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4596532&view=logs&j=96fd57f5-f69e-53c7-3d47-f67e6cf9b93e&t=0d8be578-6249-5b90-d8fc-9284fb350946&l=1097
From https://github.com/xamarin/xamarin-android
* [new ref]           171cccd1fa1486df9ced3a5eb34001b9ac65d4b0 -> …
=> [xa-prep-tasks] use AzDO env var for branch detection

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Linux.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.MacOS.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Unix.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Windows.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_AndroidTestDependencies.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_Standard.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallJetBrainsOpenJDK.Linux.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallJetBrainsOpenJDK.MacOS.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallJetBrainsOpenJDK.Windows.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallJetBrainsOpenJDK.cs, src/Xamarin.Android.Build.Tasks/Tasks/AndroidSignPackage.cs
Context: https://aka.ms/getopenjdk
Context: https://devblogs.microsoft.com/java/tag/openjdk/
Begin provisioning and using Microsoft OpenJDK 11 for
integration test purposes.
=> [xaprepare] Provision Microsoft OpenJDK 11

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Disable the current default behavior of Xamarin.Android runtime to
preload all the assemblies shipped in the apk on application startup.
This behavior has been the default in order to support older versions of
`Xamarin.Forms`, sacrificing startup performance.
=> Disable assembly preload by default

build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml
Context: https://github.com/dotnet/maui/issues/598
In a252b1a6, we bumped to a .NET 6 Preview 4 (main) build.
I created a release branch for preview 3:
https://github.com/xamarin/xamarin-android/tree/6.0.1xx-preview3
Let's setup CI triggers for the new .NET 6 branch names.
=> [azdo] add triggers for .NET 6 release branches

tests/Mono.Android-Tests/Android.Runtime/XmlReaderPullParserTest.cs, tests/Mono.Android-Tests/Android.Runtime/XmlReaderResourceParserTest.cs, tests/Mono.Android-Tests/Java.Interop/JnienvTest.cs, tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj, tests/Mono.Android-Tests/System.Drawing/TypeConverterTest.cs, tests/Mono.Android-Tests/System.Net/SslTest.cs, tests/Mono.Android-Tests/System.Net/WebSocketTests.cs, tests/Mono.Android-Tests/System/TimeZoneTest.cs, tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidClientHandlerTests.cs
A few tests which were previously failing have been fixed and can now
be enabled.  Additionally, now that dotnet/runtime has removed the
incomplete OpenSSL support on Android, we can enable more tests
that used various System.Security.Cryptography APIs directly or
indirectly.
There are still some SSL related test failures that are being ignored
that are generally being tracked in https://github.com/dotnet/runtime/issues/45741.
=> [Mono.Android-Tests] Update ignored .NET 6 tests

build-tools/automation/azure-pipelines-oss.yaml
Context: https://dev.azure.com/xamarin/public/_build/results?buildId=38123&view=logs&j=1bd95447-8107-5fbe-3014-ec4d4db1e5a6&t=7df6c319-0f16-56cb-dcf7-1be9457aaeed
Our open source Linux builds have been failing when attempting to build
Java.Interop, as the version of CMake on the Ubuntu 18.04 VM image is
too old.  We can fix this issue by using https://apt.kitware.com/, which
currently provides a CMake version of 3.20.0.
=> [ci] Bump CMake version used for OSS Linux builds

build-tools/xaprepare/xaprepare/Steps/Step_InstallJetBrainsOpenJDK.Windows.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4605864&view=logs&jobId=fb3518d4-6415-56d8-56e7-3e01113bd696&j=fb3518d4-6415-56d8-56e7-3e01113bd696&t=cdc044ef-b869-5235-56df-ac4b6018a01e
Context: https://discord.com/channels/732297728826277939/732297837953679412/826969920184778782
Context: https://github.com/xamarin/xamarin-android/commit/60b54d5ae8f63b9dce0ea7e7db2e9a3b09e041fd#diff-57d44829988dde5ea93a4c3f65fa77d5b04bd82c1ac87c4b300c0316f94f85a3L20
After 60b54d5a was merged, occasionally we would see the
**Legacy Tests** > **MSBuild Legacy - Windows** jobs fail in the
`nuget restore Xamarin.Android-Tests.sln` task:
##[error]The nuget command failed with exit code(1) and error(C:\Program Files (x86)\Microsoft Visual …
=> [xaprepare] Fix JetBrains JDK 1.8 provisioning on Windows

build-tools/automation/azure-pipelines.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4613841&view=logs&jobId=94c79d37-c271-5f89-fbfd-be54dda94a90&j=8100f0f7-e86c-5b6e-6a78-6808e1478ee9&t=7439ba00-eeea-57fd-ba83-c762626e636b
Context: https://github.com/microsoft/azure-pipelines-tasks/issues/14668
Commercial Linux builds are consistently failing against pull requests
initiated from a fork.  There is some issue related to accessing the
`xamarin-xvs` artifact feed on these machines in this case.  We should
disable these builds for now until we can fix the problem.
=> [ci] Skip Linux stage when building PRs from forks

build-tools/create-packs/Directory.Build.props, src/Microsoft.Android.Templates/Microsoft.Android.Templates.csproj
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4614104&view=logs&j=96fd57f5-f69e-53c7-3d47-f67e6cf9b93e&t=9492f091-fb29-57d7-1f68-ecbf86da9c24
After bumping msbuild on macOS we ran into an issue when packing our
workload .nupkg files:
/Users/builder/.dotnet/sdk/5.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 6.0.  Either target .NET Core 5.0 or lower, or use a version of the .NET SDK that supports .NET Core 6.0. [/Users/builder/azdo/_work/1/s/xamarin-android/build-tools/create-packs/Microsoft.Android.Sdk.proj]
The target framework used by the projects that create our workload packs
should not matter.  Updating them to netstandard2.0 should …
=> [build] Use netstandard2.0 for all workload packs

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks.csproj, eng/Version.Details.xml, eng/Versions.props
Adds the Microsoft.DotNet.ApiCompat package to our dotnet dependency
management files so that it can be automatically updated as needed
in the future.  This package version can also be used for
Microsoft.DotNet.GenAPI, as both nugets are produced by the same build.
=> [build] Add Microsoft.DotNet.ApiCompat dependency

build-tools/automation/azure-pipelines.yaml
I was checking a different pipelines settings and stumbled on a new
PR build setting:
Make fork builds have the same permissions as regular builds
I've enabled this and it seems to have fixed our Azure artifact auth
issues on Linux.
=> [ci] Enable Linux stage for PR builds from forks

build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/commercial-build.yaml, build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/Microsoft.Android.Sdk.proj, build-tools/scripts/Packaging.mk, build-tools/scripts/msbuild.mk, src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj
I've been encountering various issues when building and packing .NET 6
content with `dotnet build`.
Using an older version of `dotnet` with `<Exec/>` tasks that invoke a
newer version of `dotnet` seems to be problematic:
(CreateAllPacks target) -> 
/Users/builder/.dotnet/sdk/5.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(241,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly. [/Users/builder/azdo/_work/2/s/xamarin-android/build-tools/create-packs/Microsoft.Android.Runtime.proj] [/Users/builder/azdo/_work/2/s/xamarin-android/build-tools/create-packs/Microsoft.Android.Sdk.proj]
/Users/builder/.dotnet/sdk/5.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(241,5): error MSB4018: …
=> [ci] Build and pack updates, bump to .NET 5.0.201

build-tools/automation/yaml-templates/setup-test-environment.yaml
This should allow us to get `.binlog` files for diagnosing when things
go wrong. `nuget restore -Verbosity detailed` is not as detailed as we
would like.
Use `$(RestoreConfigFile)`, which maps to the `-ConfigFile` switch for
NuGet:
https://docs.microsoft.com/nuget/reference/msbuild-targets
We no longer need to run the `NuGetToolInstaller` yaml task either.
=> [azdo] restore with MSBuild instead of NuGet

build-tools/xaprepare/xaprepare/Steps/Step_DetermineAzurePipelinesTestJobs.cs
Context: https://github.com/xamarin/xamarin-android/pull/5830
We'd like to have our PR builds and tests run automatically against
dependency bump PRs created by the dotnet Maestro bot.  To do this, I've
overridden the CI triggers in the Xamarin.Android-PR pipeline to include
branches that begin with `darc-*`.
These branches will now trigger a build automatically, but it will be
building an individual commit and not a merge commit.  The xaprepare
tool has been updated to enable all test jobs in these cases.
=> [ci] Enable CI for Maestro bot PRs

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
This reverts commit d13d0f972a4eb663251b2a6b5a934c59a6789db1.
I also updated a test that was triggering an issue with
`$(AndroidEnablePreloadAssemblies)`. It was originally crashing with:
Java.Lang.RuntimeException: Unable to start activity ComponentInfo{com.xamarin.classlibrarymainlauncherruns/com.xamarin.classlibrarymainlauncherruns.MainActivity}: android.view.InflateException: Binary XML file line #1 in com.xamarin.classlibrarymainlauncherruns:layout/foo: Binary XML file line #1: You must supply a layout_width attribute.
---> Android.Views.InflateException: Binary XML file line #1 in com.xamarin.classlibrarymainlauncherruns:layout/foo: Binary XML file line #1: You must supply a layout_width attribute.
---> Java.Lang.UnsupportedOperationException: Binary XML file line #1: You must …
=> Revert "[One .NET] $(AndroidEnablePreloadAssemblies)=False by default"

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/GenerateSupportedPlatforms.cs, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NuGet.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/AssertionExtensions.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5819
A project using Maui and `TargetFramework=net6.0-android` can hit the
warning:
warning CA1416: This call site is reachable on all platforms. 'Class1' is only supported on: 'android' 30.0 and later.
I found the project had:
TargetPlatformVersion = 30
Projects that emit no warnings have `TargetPlatformVersion = 30.0`.
Update the `<GenerateSupportedPlatforms/>` MSBuild task to always
append `.0`:
version.ApiLevel.ToString ("0.0", CultureInfo.InvariantCulture)
This solves the warning, but we still get an error in other projects
in the solution:
error CS1061: 'Class1<TVirtualView, TNativeView>' does not contain a definition for 'Context' and no accessible extension method 'Context' accepting a first argument of type …
=> [One .NET] fix $(PackageTargetFallback) and $(TargetPlatformVersion)

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/create-packs/Directory.Build.props, build-tools/create-packs/Directory.Build.targets, eng/README.md, eng/Version.Details.xml, eng/Versions.props, global.json
The `dotnet_create_msi` job has been updated to publish information
about Android .NET 6 .nupkg files to the dotnet Maestro server.
With this data being published, the `darc` tool can now be used to
manage an Android .NET 6 product dependency:
darc add-dependency -n Microsoft.Android.Sdk.Windows -t product -r https://github.com/xamarin/xamarin-android -v 1.2.3
darc update-dependencies --channel "General Testing Internal"
Looking up latest build of https://github.com/xamarin/xamarin-android on General Testing Internal   
Updating 'Microsoft.Android.Sdk.Windows': '1.2.3' => '11.0.200-ci.publish-bar-manifest.197' (from build 'publish-bar-manifest-41c7adffb2669c313e96607f98f8ab05c820e56f-1' of 'https://github.com/xamarin/xamarin-android')
For dependency updating to work, we must configure …
=> [ci] Upload build asset data to darc/maestro

build-tools/automation/azure-pipelines.yaml
Commit 12edc2c5 introduced a feature that seems to only be available
in newer versions of MSBuild:
<Import Project="Sdk.props" Sdk="Microsoft.DotNet.SharedFramework.Sdk" Version="$(MicrosoftDotNetBuildTasksFeedPackageVersion)" />
This caused an issue during the `dotnet_create_pkg` job on our
Xamarin.Android pipeline, which uses a different machine pool than
Xamarin.Android-PR:
/Users/builder/azdo/_work/2/s/xamarin-android/build-tools/create-packs/Directory.Build.targets(11,3): error : Version 5.0.201 of the .NET Core SDK requires at least version 16.8.0 of MSBuild. The current available version of MSBuild is 16.6.0.52201. Change the .NET Core SDK specified in global.json to an older version that requires the MSBuild version currently available. …
=> [ci] Use dotnet to create workload .pkg

src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BuildHelper.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsAndroidApplicationProject.cs, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1300734
Break points are currently not working for .NET 6 projects inside
`<ProjectReference/>` from the main Android application. It turns out
that `@(ResolvePublishList)` does not contain `.pdb` files for
referenced projects?
I could reproduce this in our existing
`ApplicationRunsWithDebuggerAndBreaks` test. I added a class library
and an additional break point to make sure the break point works.
To actually solve the issue, I added a `File.Exists()` check to look
for `.pdb` files on disk and add them -- as there appears to be no way
to find the files from MSBuild item groups from the dotnet/sdk.
I also added an assertion that the `.pdb` files are deployed.
I added `[DebuggerHidden]` to a couple assertion helper methods, too. …
=> [One .NET] include .pdb files from <ProjectReference/>

build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/Microsoft.NET.Workload.Android.proj
Context: https://github.com/dotnet/designs/pull/188/files#diff-8fcaa29d8e6f00b34b3cb1830d93f33e75f04424780a66a3c658c7021048e74fR125
The future `dotnet workload install` commands will be expecting that
the `.nupkg` for a workload will contain:
* `data/WorkloadManifest.json`
* `data/WorkloadManifest.targets`
This was done so that we don't interfere with NuGet's spec for layout
of a `.nupkg` file. You are allowed to put whatever you like in a
`/data/` folder.
The layout on disk in `C:\Program Files\dotnet`, etc. is unchanged, so
we don't need any changes to our installers, etc.
Future changes in other repos:
* Will need to update xamarin-macios:
https://github.com/xamarin/xamarin-macios/tree/main/dotnet/package
* Will need to update where dotnet/maui provisions workloads: …
=> [One .NET] move WorkloadManifest.* files to /data/ folder

build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/azure-pipelines-oss.yaml, build-tools/automation/azure-pipelines.yaml
Context: https://github.com/dotnet/maui/issues/598#issuecomment-820609077
In 8ca43359, I messed up, and we used the wrong branch name
`6.0.1xx-preview3`, which should have been prefixed with `release/`.
Replace 8ca43359, in favor of `release/*`, so we can follow .NET 6
branch naming such as `release/6.0.1xx-preview4`.
=> [azdo] fix release branch triggers

src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/monovm-properties.hh
Putting it in a separate class allows for nicer compile-time checking
for array overflow without the need to pollute code in
`monodroid-glue.cc`.
=> Move `monovm_initalize` property handling to a separate class

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/monodroid/jni/build-info.hh
Context: https://github.com/xamarin/java.interop/commit/ebd7d76161ac60ce7ad3bfee87789f08a333ae78
Context: https://github.com/xamarin/java.interop/commit/f9faaaba0ca2f3721ea1de33fd793edeae059474
With `Java.Interop` Java type scanner now including Java interfaces in
the returned set of types, we need to ignore interfaces when generating
JCWs.
=> Ignore interfaces when generating JavaCallableWrappers

build-tools/automation/azure-pipelines-nightly.yaml
The nightly TimeZone and System App tests are failing with:
error XA0030: Building with JDK version `14.0.2` is not supported. Please install JDK version `11.0`.
See https://aka.ms/xamarin/jdk9-errors
Earlier in the log:
JI_JAVA_HOME = /Users/runner/Library/Android/
...
warning XA5300: An exception occurred while validating the Java SDK installation in '/Users/runner/Library/Android/' that was found while searching the paths from '$JI_JAVA_HOME'.
Ensure that the Android section of the Visual Studio options has a valid Java SDK directory configured.
To use a custom SDK path for a command line build, set the 'JavaSdkDirectory' MSBuild property to the custom path.
Exception: Could not find required file `jar` within `/Users/runner/Library/Android/`; is this a valid JDK?
Parameter name: …
=> [build] fix nightly CI builds

build-tools/xaprepare/xaprepare/ToolRunners/GitRunner.BlamePorcelainEntry.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5867
Note: I cannot reproduce it locally, `git blame -p` output doesn't have
any `boundary` headers here
Be more flexible when parsing `git blame -p` output by accepting headers
without values.
=> [xaprepare] Don't throw when reading git blame headers without value

.external, Documentation/release-notes/5860.md
Changes: https://github.com/xamarin/monodroid/compare/ff633623e2c5793e765b7e498c7ea3f9dd7cbe88...76c04cd15eca7afc269a6d26296e9d2db6f79be2
* xamarin/monodroid@76c04cd15 [tools/msbuild] [MSB3680] The source file "obj/Debug/androidx/jl/classes.dex" does not exist (#1197)
* xamarin/monodroid@ed584c775 [tools/msbuild] Improve FastDeploy error messages (#1190)
* xamarin/monodroid@74294dca0 Bump to xamarin/androidtools/main@47ec118f (#1195)
=> Bump to xamarin/monodroid/main@76c04cd1

build-tools/xaprepare/xaprepare/ToolRunners/GitRunner.BlamePorcelainEntry.cs
Context: https://github.com/xamarin/xamarin-android/issues/5867
Context: 40fdecbd5d4877a0ac28045ecd6832604970ecc3
Assign new array to the old one so that IndexOutOfRangeException
isn't thrown later on in the code.
=> [xaprepare] Add a missing line to fix for issue 5867

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4690182&view=ms.vss-test-web.build-test-results-tab
The `BuildTest.Desugar()` test is failing on CI with:
System.Net.WebException : The remote server returned an error: (403) Forbidden.
Even using the latest URLs here, the download gives me a login prompt
in the browser:
https://mvnrepository.com/artifact/com.twitter.sdk.android/twitter-core/3.3.0
https://repo.spring.io/libs-release/com/twitter/sdk/android/twitter-core/3.3.0/twitter-core-3.3.0.aar
I just removed the usage of this `.aar` file in the `Desugar()` test,
since there seem to be sufficient `.aar` files used in the test.
I also updated a few other URLs that were using `bintray.com`, because
they may eventually stop working.
=> [tests] stop using bintray URLs

.gitmodules, Directory.Build.props
(Commercial) Xamarin.Android v11.3 is being tracked in the
[xamarin-android/d16-10][0] branch, which was branched from
commit eac74ebb.
Bump `$(ProductVersion)` to 11.3.99 to track development progress of
the *next* version of Xamarin.Android.
Additionally, bump various submodules to their "main" equivalents
to mirror the d16-10 branch commit 496a43a5, and update `.gitmodules`
so that the correct branch name is used:
Changes: https://github.com/mono/debugger-libs/compare/8bf09ce96132b74e416ed9a9c332b6e7b6de1234...08268b730a73cca0e3b3ac9c703f0b773a3be25b
* mono/debugger-libs@08268b7: Add Module.ApplyChanges (#342)
* mono/debugger-libs@1b5a55a: Fix assembly version after converting projects to SDK style
Changes: https://github.com/mono/opentk/compare/933939da123a3fe4a040d57a589b43af99175037. …
=> Bump $(ProductVersion) to 11.3.99
