src/Xamarin.Android.Build.Tasks/Tasks/ProcessNativeLibraries.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc

Fixes: https://github.com/xamarin/xamarin-android/issues/5855
Currently, in .NET 6, any `.so` file in our runtime pack is included
in apps by default. This is the nature of how native libraries coming
from NuGet packages work. They just get added based on the file path
and `$(RuntimeIdentifier)` of the project.
We already have a special case for `libmono-android.release.so` and
`libmono-android.debug.so` that uses `$(AndroidIncludeDebugSymbols)`
as a way to know which native library is needed.
We can do the same thing here and exclude
`libxamarin-debug-app-helper.so`, which should only be included in
`Debug` builds.
This saves ~37K for all Release apps:
-37,104 lib/arm64-v8a/libxamarin-debug-app-helper.so *1

[One .NET] exclude libxamarin-debug-app-helper.so from Release builds

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets

Context: https://github.com/xamarin/xamarin-android/issues/5856
In .NET 6 Preview 4, we can adjust some of our defaults for ILLink:
This can be completely removed, it is the default now:
<TrimMode Condition=" '$(PublishTrimmed)' == 'true' and '$(TrimMode)' == '' ">link</TrimMode>
There is a new feature that has the same behavior as
`AndroidLinkMode=full`:
<TrimmerDefaultAction Condition=" '$(TrimmerDefaultAction)' == '' and '$(AndroidLinkMode)' == 'Full' ">link</TrimmerDefaultAction>
This allows us to remove where we were manually setting
`%(TrimMode)=link` on the `@(ResolvedFileToPublish)` item group.
In a future PR, we should add an additional default to emit warning
for `TrimmerDefaultAction=link` or `AndroidLinkMode=Full`:
<SuppressTrimAnalysisWarnings Condition=" …

[One .NET] clean up default ILLink MSBuild properties

---

Configuration.props
Xamarin.Android.sln
build-tools/automation/azure-pipelines-oss.yaml
build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/setup-test-environment.yaml
build-tools/create-packs/Directory.Build.targets

The desktop mono version has been bumped to include a major MSBuild
update from 16.6 to 16.9.  This MSBuild version supports net5.0, and
as such it allows us to add `Microsoft.Android.Sdk.ILLink` to the
`Xamarin.Android.sln` build.

Update desktop Mono to 6.12.0.137 and MSBuild 16.9

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/install-apkdiff.yaml
build-tools/automation/yaml-templates/run-msbuild-mac-tests.yaml
build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml
build-tools/automation/yaml-templates/setup-test-environment.yaml
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Context: https://github.com/radekdoulik/apkdiff/pull/2
New percentage changed based checks have been added to apkdiff to allow
for greater flexibility when determining whether or not a size change
is problematic.  The .NET 6 .apk content and size checks have been
updated to use percentage based comparisons, and as a result have been
made more lenient.  This should reduce the amount of times we need to
manually update .apkdesc files.  These checks can be tightened as we get
closer to a stable release.

[One .NET] Make apk size checks more lenient

---

src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

When testing .NET 6 in the latest Internal Preview builds of Visual
Studio, we are now in a place where the Android designer is working
and rendering layouts.
Unfortunately if you add a new `android:id="@+id/foo"`, Intellisense
does not update to show that `Resource.Id.foo` is available.
After enabling build logging with `Project System Tools`:
https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools
I found the following is happening:
* I hit Ctrl+S to save the `.xml` file
* `UpdateGeneratedFiles` runs, which updates
`obj/Debug/*/designtime/Resource.designer.cs`. This runs in a
design-time context where we use the `ManagedResourceParser`, it
uses an `R.txt` if found on disk. In this case, it is an old `R.txt`
from a previous build.
* …

[Xamarin.Android.Build.Tasks] Build should update designtime/Resource.designer.cs

---

build-tools/create-packs/Directory.Build.targets

Context: https://github.com/dotnet/sdk/issues/16946
Copy our template workload pack to a lowercase destination so that it
can be detected and used when building and testing on Linux.

[build] Copy templates to lowercase path on Linux

---

src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs

Context: https://github.com/xamarin/xamarin-android/issues/5838
Setting `$(AndroidEnablePreloadAssemblies)`=False, which disables
assembly preloading (see af02a65a), could result in a crash when:
1. The launched `Activity` isn't located within the "main App
assembly", the assembly built as part of the `App.apk` build, and
2. The launched `Activity` uses Android Resource IDs, and
3. Those Android Resource IDs differ between the Library project
build and the Application project build (usually the case).
This setup is exemplified by the
`DebuggingTest.ClassLibraryMainLauncherRuns()` unit test.
Our current Resource architecture assumes/ensures that there is
Only One™ `Resource` type mentioned by an assembly-level
`ResourceDesignerAttribute` custom attribute, with …

[monodroid] `AndroidEnablePreloadAssemblies` causes runtime crash.

---

build-tools/create-packs/Microsoft.Android.Sdk.proj
src/Mono.Android.Export/Properties/AssemblyInfo.cs
src/Mono.Android/Properties/AssemblyInfo.cs.in

Fixes: https://github.com/xamarin/xamarin-android/issues/5638
Going forward in .NET 6, we shouldn't use the `%(IsTrimmable)`
metadata anymore, but use the following C# attribute in each assembly
instead:
[assembly: AssemblyMetadata ("IsTrimmable", "True")]
Similar changes on the iOS side here:
https://github.com/xamarin/xamarin-macios/commit/289053b1e3bdf3b8c3cc3839384811f6018bba48
Bump to xamarin/java.interop/main@df4c5e7c
Changes: https://github.com/xamarin/java.interop/compare/f9faaaba...df4c5e7c
This adds `AssemblyMetadataAttribute` for `Java.Interop.dll`.

[One .NET] use AssemblyMetadataAttribute for IsTrimmable

---

src/Mono.Android/metadata

Fixes #5868.
These interfaces contain constants that we are pointing users to now that we can support them via DIM.  However in Java they are `protected` interfaces in `sealed` classes.  C# prevents users from accessing `protected` types inside a `sealed` type, so users can't actually use these members.
This commit uses `metadata` to make these interfaces `public` so their members can be used.
```
Android.Provider.CalendarContract/IAttendeesColumns
Android.Provider.CalendarContract/ICalendarAlertsColumns
Android.Provider.CalendarContract/ICalendarCacheColumns
Android.Provider.CalendarContract/ICalendarColumns
Android.Provider.CalendarContract/ICalendarSyncColumns
Android.Provider.CalendarContract/IColorsColumns
Android.Provider.CalendarContract/IEventDaysColumns …
```

[Mono.Android] Make protected constants interfaces public.

---

build-tools/automation/yaml-templates/install-apkdiff.yaml

We've been running into issues trying to install an older version of
apkdiff on various machines after bumping the version in a PR.  Avoid
this by always attempting to uninstall apkdiff first.  The uninstall
exit code is ignored as uninstall attempts will error if the tool is not
already installed.

[ci] Uninstall apkdiff before installation

---

build-tools/automation/azure-pipelines.yaml

CI error:
```
The pipeline is not valid. Could not get the latest source version for repository xamarin/xamarin-forms-samples 
hosted on https://github.com/ using ref refs/heads/master. GitHub reported the error, "No commit found for 
SHA: refs/heads/master"
```

[ci] Remove obsolete QA repos.

---

.github/ISSUE_TEMPLATE/04-binding-a-java-library.md

* Point to Binding Troubleshooting Guide
* Add hints to include `.jar`/`.aar`/diagnostic log.

[GitHub] Update the 'Binding Issue' template to better guide the user.

---

build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4728381&view=ms.vss-test-web.build-test-results-tab&runId=21435278&resultId=100052&paneView=attachments
CI on some of our release branches is failing with errors such as:
UnnamedProject.csproj: warning MSB4242: The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed to run. An item with the same key has already been added. Key: microsoft-android-sdk-full
Microsoft.NET.Sdk.ImportWorkloads.props(14,3): warning MSB4242: The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed to run. An item with the same key has already been added. Key: microsoft-android-sdk-full
Microsoft.NET.Sdk.ImportWorkloads.props(14,38): error MSB4236: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified …

[xaprepare] better cleanup past .NET 6 installs

---

src/java-runtime/java/mono/android/MonoPackageManager.java

Work around for https://github.com/dotnet/runtime/issues/51274 which
will be removed before NET6 release.

Preload System.Security.Cryptography.Native.OpenSsl on startup

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/5838
Context: e0da1f152de84c4cc39983f2fda775ec98c08250
Partially reverts 522d7fb61f3669d85d077ba4f2889dbe8c9c8ac3 which
reverted d13d0f972a4eb663251b2a6b5a934c59a6789db1
The [`$(AndroidEnablePreloadAssemblies)`][0] property controls
whether or not *all* `.dll` files contained within a `.apk` are
loaded during process startup.  *Not* doing so reduces process
startup times, which is desirable, but this also caused certain
Xamarin.Forms apps to fail to run as they previously had, as
not loading all assemblies during startup broke their
Dependency Injection infrastructure.
For .NET 6, we feel we have *some* "wiggle-room" to change default
semantics, so for .NET 6 projects set the default value of
`$(AndroidEnablePreloadAssemblies)` to …

[One .NET] $(AndroidEnablePreloadAssemblies)=False by default (#5790)

---

build-tools/automation/yaml-templates/setup-test-environment.yaml
build-tools/create-packs/Microsoft.Android.Ref.proj
build-tools/xaprepare/xaprepare/Resources/JdkInfo.Windows.props.in
build-tools/xaprepare/xaprepare/Steps/Step_GenerateFiles.Windows.cs
build-tools/xaprepare/xaprepare/Steps/Step_PrepareExternalJavaInterop.Unix.cs
src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj
tools/xabuild/XABuild.cs

Changes: https://github.com/xamarin/java.interop/compare/df4c5e7c...4d0cba64
Other changes are required here to enable Java.Interop to target `net6.0`.

Bump to xamarin/java.interop/main@4d0cba64

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/GenerateWixFile.cs
build-tools/create-dotnet-msi/create-dotnet-msi.csproj
build-tools/create-dotnet-pkg/create-dotnet-pkg.csproj
build-tools/create-packs/Directory.Build.targets

This feature flag is now on by default in .NET 6.0.100-preview.4.21253.14 and higher.
We should stop generating `EnableWorkloadResolver.sentinel`, as it strongly ties our installers to a specific version of the .NET SDK.

[One .NET] remove EnableWorkloadResolver.sentinel

---

Directory.Build.props
Documentation/guides/OneDotNet.md

Our current versions for .NET 6 packages are:
11.0.200-preview.4.XXX
Where `XXX` is the git "commit distance".
This is the only place Android 11 remains, as we have been using the
Android API level for all other versions in .NET 6.
We should instead use a version number, such as:
30.0.100-preview.4.XXX
This will likely make things less confusing, so this can match the
Android TFM as well:
net6.0-android30

[One .NET] version .NET 6 packages with Android API level

---

Configuration.props
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CreateAndroidEmulator.cs
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/StartAndroidEmulator.cs
build-tools/scripts/TestApks.targets
src/Xamarin.Android.Build.Tasks/Tasks/Lint.cs

Context: https://dl-ssl.google.com/android/repository/repository2-1.xml
We were seeing some lint-related MSBuild tests fail with:
Lint
Parameters
ToolPath = /Users/runner/Library/Android/sdk/cmdline-tools/latest/bin
...
LintVersion: 4.2.0
Environment Variables passed to tool:
JAVA_HOME=/Users/runner/Library/Android/jdk-11/
...
Errors
obj/Debug/android/AndroidManifest.xml(12,89): error XA0103:  MainActivity must extend android.app.Activity [Instantiatable] [/Users/runner/work/1/s/bin/TestRelease/temp/CheckLintConfigMerging/UnnamedProject.csproj]
obj/Debug/android/AndroidManifest.xml(18,28): error XA0103:  MonoRuntimeProvider must extend android.content.ContentProvider [Instantiatable] [/Users/runner/work/1/s/bin/TestRelease/temp/CheckLintConfigMerging/UnnamedProject.csproj]
2 errors, 3 …

Bump to cmdline-tools 4.0, fix lint errors

---

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs

Context: fc3f02826077dde0caf78e86080261669a0ba44e
Change the repository to `https://github.com/xamarin/xamarin-android-binutils`
and "reset" the version back to 2.36.1-XA.1 (since this is the first
release from that repository)
There are otherwise no functional changes in this build of
binutils

[xaprepare] Update GNU Binutils version and URL

---

src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/monovm-properties.hh

Context: 0cd890bdf7fb0255f11d8c14e3de69c9e2691117
0cd890bd added code to initialize NET6 MonoVM using its new
`monovm_initialize` API which accepts a number of key-value string
properties, parsed by the runtime in order to configure various areas of
the VM.  One of these properties is `PINVOKE_OVERRIDE`, a new way to
resolve p/invoke calls which, at the time of 0cd890bd, required
converting pointer to a callback function to a string, which would then
be parsed by `monovm_initialize` back into a pointer.
This commit removes the need for parsing by using new MonoVM
initialization function, `monovm_initialize_preparsed`, which takes a
typesafe struct of runtime initialization arguments, including a "real"
pointer to the `PINVOKE_OVERRIDE` callback function.
The new initialization routine …

[monodroid] MonoVM initialization without pointer parsing

---

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs
src/Mono.Android/metadata

Context: https://developer.android.com/about/versions/12/overview
Context: https://android-developers.googleblog.com/search/label/Android12
Android 12 [Beta 1 has been released][0].
* [API diff vs. Developer Preview 3][1]
* [API diff vs. API-30][2]
Google's documented [timeline for Android 12][3] is unchanged
vs. commit 11c30ac:
* May: Beta 1
* June-July: Beta 2, Beta 3
* August: Beta 4
This contains the final APIs and official SDK.
[0]: https://android-developers.googleblog.com/search/label/Android12
[1]: https://developer.android.com/sdk/api_diff/s-beta1-incr/changes
[2]: https://developer.android.com/sdk/api_diff/s-beta1/changes
[3]: https://developer.android.com/about/versions/12/overview#timeline

[Mono.Android] Bind API-S Beta 1.

---

Configuration.props
Documentation/release-notes/5888.md
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/UnzipDirectoryChildren.cs
build-tools/xaprepare/xaprepare/Application/Context.cs
build-tools/xaprepare/xaprepare/Application/KnownProperties.cs
build-tools/xaprepare/xaprepare/Application/Properties.Defaults.cs.in
build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
build-tools/xaprepare/xaprepare/Scenarios/Scenario_Standard.cs
build-tools/xaprepare/xaprepare/Steps/Step_Get_Android_BuildTools.cs
build-tools/xaprepare/xaprepare/xaprepare.targets
src/aapt2/aapt2.targets

Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1288832
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1287930
Commit c9e2d754 had to revert the version of `aapt2` we were shipping
due to issues with older PC's. Specifically a certain type of AMD
processor the AMD Phenom II. That commit simply reverted back to the last
known working version.
This made us think about if getting `aapt2` from maven was the best
idea. We are not 100% sure if the builds on maven even match those
being shipped in the google sdk. So the idea now is to use the one that
google ships with its sdk. However since we will control which version
of the build tools we want to ship we will not be relying on the one
from the users SDK folder. This will make sure we always ship a known …

[aapt2] Use the aapt2 from `build-tools_r$(XABuildToolsVersion)-{os}.zip`

---

build-tools/xaprepare/xaprepare/Application/Context.cs
build-tools/xaprepare/xaprepare/Application/KnownProperties.cs
build-tools/xaprepare/xaprepare/Application/Properties.Defaults.cs.in
build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs
build-tools/xaprepare/xaprepare/package-download.proj
build-tools/xaprepare/xaprepare/xaprepare.targets
eng/Version.Details.xml
eng/Versions.props

Context: https://github.com/dotnet/installer/blob/f442964a34125c76240b1bf2d2c53fdb00d53e41/eng/Version.Details.xml#L20-L23
We can start tracking dotnet/runtime as a "coherent dependency" of
dotnet/installer. This is a bit simpler than manually parsing:
dotnet\sdk\*\Microsoft.NETCoreSdk.BundledVersions.props
The benefit of doing this, is when maestro comes along to bump
dotnet/installer, we'll get a diff for dotnet/runtime as well.
We can also start using the `$(MicrosoftNETCoreAppRefPackageVersion)`
MSBuild property throughout our build as needed. We'll need to do this
if we want to provision `Microsoft.NET.Workload.Mono.ToolChain` to a
specific version.
An example if we updated things *now*:
> darc update-dependencies --channel ".NET 6"
Looking up latest build of …

[build] add dotnet/runtime dependency through dotnet/installer

---

build-tools/create-packs/Directory.Build.props
build-tools/create-packs/Directory.Build.targets
build-tools/create-packs/License.targets
src/Microsoft.Android.Templates/Microsoft.Android.Templates.csproj

Microsoft has rules for submitting signed NuGet packages with the
namespace `Microsoft.*` under the Microsoft + Xamarin organizations.
Some of these rules include:
* Package must be signed.
* Must include a license.
* `$(Authors)` should be `Microsoft`
* `$(PackageProjectUrl)` can't be blank.
* `$(Copyright)` must *exactly* say `© Microsoft Corporation. All rights reserved.`
If any of these are wrong, you'll get errors during `nuget push` such as:
Response status code does not indicate success:
400 (The package is not compliant with metadata requirements for Microsoft packages on NuGet.org.
Go to https://aka.ms/Microsoft-NuGet-Compliance for more information.
Policy violations: The package metadata is missing required ProjectUrl.).
We used a script to fix up these values and resign for …

[build] set proper settings for NuGet.org

---

Documentation/release-notes/5945.md

Fixes: https://github.com/xamarin/java.interop/issues/835
Fixes: https://github.com/xamarin/xamarin-android/issues/5921
Context: https://github.com/xamarin/xamarin-android/issues/5894
Changes: http://github.com/xamarin/Java.Interop/compare/12e670a8560f69581d3a3adf0a9d91e8ce8c9afa...2573dc8c84fd4eb68e75bcae73912c26f4942356
* xamarin/Java.Interop@2573dc8c: [Java.Interop.Tools.*] IMetadataResolver not TypeDefinitionCache (#842)
* xamarin/Java.Interop@412e974b: Revert "[generator] Disable [SupportedOSPlatform] until .NET 5/6. (#781)" (#841)
* xamarin/Java.Interop@23baf0bc: [Java.Interop] Fix NRT warnings introduced by targeting 'net6.0' (#840)
* xamarin/Java.Interop@131c1496: [generator] Fix NRE from return type not consistently set (#834)
* xamarin/Java.Interop@100fffc1: [generator] Ensure …

Bump to xamarin/Java.Interop/main@2573dc8c

---

.vscode/tasks.json
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CreateAndroidEmulator.cs
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunAndroidEmulatorCheckBootTimes.cs
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/StartAndroidEmulator.cs
build-tools/check-boot-times/Program.cs
build-tools/scripts/TestApks.targets
samples/.gitignore
samples/NuGet.config
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/5944
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4791430&view=logs&jobId=9e58dffc-b78a-5028-45f4-4d99f4c2da6c
The TestBinaryDeserialization test has been disabled for .NET 6 as it
is no longer supported due to security reasons.
The "Run check-boot-times" test has seemingly been failing since commit
92efdccb6, which introduced a new version of avdmanager and changed the
path where our AVD files are stored.  The corresponding task and tool
have been fixed to know about this new AVD home location.  The create
and start Android emulator tasks have also been updated for uniformity.
All of these tasks now set [`$(ANDROID_PREFS_ROOT)`][0] rather than the
now deprecated `$(ANDROID_SDK_HOME)` variable.
I have also …

[ci] Fix smoke and emulator test issues

---

src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.targets

Context: https://github.com/dotnet/sdk/pull/16208/files
Context: https://gist.github.com/sfoslund/12e1daff114bccc8a29ebb441bc461a5#detecting-installed-platforms
Fixes: https://github.com/xamarin/xamarin-android/issues/5941
The VS ProjectSystem needs a way to know during MSBuild evaluation
which platforms are supported by a workload.
If we add the item group:
<SdkSupportedTargetPlatformIdentifier Include="android" DisplayName="Android" />
This enables the IDE to know that Android is supported.
I will make a future change in xamarin/xamarin-macios for this.

[One .NET] add @(SdkSupportedTargetPlatformIdentifier)

---

build-tools/automation/yaml-templates/install-microbuild-tooling.yaml

Context:  https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4803805&view=logs&j=3ce66085-846b-53dd-5323-3e00eb12b9a6&t=c7de918a-2762-5750-800e-a440a28cd7e6
We've been seeing some .NET 6 .msi signing attempts fail when installing
the MicroBuild signing tooling with the following:
##[error]The path 'Microsoft.NuGet.CredentialProvider.zip' either does not exist or is not a valid file system path.
Installing the NuGet credential provider will hopefully address this.

[ci] Install credential provider when signing

---

src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Context: https://github.com/dotnet/maui/pull/603
When building the .NET MAUI workload, I found the following scenario
was broken:
* `Microsoft.Maui.dll` uses `Microsoft.Maui.Resource.Layout.navigationlayout`
in order to use an Android layout.
* A sample app's `Resource.designer.cs` did not contain a line such as:
```csharp
global::Microsoft.Maui.Resource.Layout.navigationlayout = global::MyMauiSampleApp.Resource.Layout.navigationlayout
```
This resulted in a crash at runtime such as:
UNHANDLED EXCEPTION:
Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
--- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
android.runtime.JavaProxyThrowable: System.InvalidCastException: Unable to convert instance of type …

[One .NET] improve detection of "Android" assemblies

---

build-tools/xaprepare/xaprepare/Application/KnownProperties.cs
build-tools/xaprepare/xaprepare/Application/Properties.Defaults.cs.in
build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs
build-tools/xaprepare/xaprepare/package-download.proj
build-tools/xaprepare/xaprepare/xaprepare.targets
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json

Context: https://github.com/dotnet/runtime/blob/d43e88620fe574045f026a4ebce50f7a8541347a/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.json.in
In order to start using packs from the `microsoft-net-runtime-android`
workload, we need to:
1. Add `Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.100` to
`package-download.proj`.
2. Copy `WorkloadManifest.*` files from:
```
Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.100/data/
```
To:
~/android-toolchain/dotnet/sdk-manifests/6.0.100/Microsoft.NET.Workload.Mono.ToolChain/
So we get the latest `WorkloadManifest.json` based on the version
defined in `$(MicrosoftNETCoreAppRefPackageVersion)`.
3. `xaprepare` should run:
```
~/android-toolchain/dotnet/dotnet workload install microsoft-net-runtime-android …
```

[One .NET] extend the microsoft-net-runtime-android workload

---

.external

Changes: https://github.com/mono/mono/compare/b4a385816ed4f1398d0184c38f19f560e868fd80...c633fe923832f0c3db3c4e6aa98e5592bf5a06e7
* mono/mono@c633fe92383: [MSBuild] Update to vs16.10 branch (#21073)
* mono/mono@a01309d1041: sdks: Use https for xamjenkinsartifacts llvm archive download
* mono/mono@6e079842a65: sdks: Disable parallelism for mxe llvmwin64 build
* mono/mono@28a101a8ab5: [2020-02] Fix leak in assembly-specific dllmap lookups (#21053)
* mono/mono@0449008883d: [MonoIO] Wrap calls to open() in EINTR handling (#21042)
* mono/mono@51d876a041e: [2020-02][System.Native] Handle ReadDir EINTR (#21029)
* mono/mono@581e5827f46: Bump corefx for credscan fixes (#21018)
* mono/mono@c90ec48f596: [arm64] Fix wrong marshalling in gsharedvt transition (#21006)

Bump to mono/mono/2020-02@c633fe92

---

tests/MSBuildDeviceIntegration/AssemblyInfo.cs
tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
tests/MSBuildDeviceIntegration/Tests/DeleteBinObjTest.cs
tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs
tests/MSBuildDeviceIntegration/Tests/MonoAndroidExportTest.cs
tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs
tests/MSBuildDeviceIntegration/Tests/SystemApplicationTests.cs
tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs

We occasionally hit test failures in the
`InstallAndRunTests.InterpreterEnabled` test. Running the test locally
by itself seems to work fine.
Then I noticed the class was decorated with the `[SingleThreaded]`
attribute and not `[NonParallelizable]`. `[SingleThreaded]`'s summary
says:
> Marks a test fixture as requiring all child tests to be run on the
> same thread as the OneTimeSetUp and OneTimeTearDown. A flag in the
> NUnit.Framework.Internal.TestExecutionContext is set forcing all
> child tests to be run sequentially on the current thread. Any
> NUnit.Framework.ParallelScope setting is ignored.
How is this test class not failing *more* often than it is? I found
that we set an assembly-level attribute in `DeploymentTest.cs`:
[assembly: NonParallelizable]
But from the description of …

[tests] remove SingleThreadedAttribute

---

build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4825895&view=logs&j=afc75dd9-ea98-591e-f4f4-0b6212ccdfde&t=a18fc855-de22-5374-28de-d604f6803bd2&s=af72edbe-9d58-52b1-91f1-857d7e391cf0
In 0150bbbc, I missed that the designer tests phases fail with:
Workload installation failed: One or more errors occurred. (microsoft.net.runtime.runtimeconfigparser.task::6.0.0-preview.6.21274.1 is not found in NuGet feeds https://api.nuget.org/v3/index.json",)
I believe the command isn't finding the `NuGet.config` file in the
root of the xamarin-android repo, and so we're missing this source:
<add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />
We need to set the `WorkingDirectory` of the process, so it finds the
appropriate …

[xaprepare] pass WorkingDirectory to dotnet workload install

---

src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs

Fixes #5964
In commit accc846e we missed a few paths which might need to be quoted in order to handle
spaces in the paths. As a result users are seeing errors like the one below.
```
2021-05-28T22:15:09.3191452Z   [aot-compiler stdout] Executing the native linker: "C:\Program Files (x86)\Android\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.EXE" -Bsymbolic -shared -o obj\Release\110\aot\armeabi-v7a\libaot-Xamarin.AndroidX.CardView.dll.so.tmp "obj\Release\110\aot\armeabi-v7a\Xamarin.AndroidX.CardView.dll\temp-llvm.o" obj\Release\110\aot\armeabi-v7a\Xamarin.AndroidX.CardView.dll\temp.s.o -LC:\Program Files (x86)\Android\android-sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\lib\gcc\arm-linux-androideabi\4.9.x -LC:\Program Files …
```

[Xamarin.Android.Build.Tasks] Quote Aot Paths (again)

---

build-tools/automation/azure-pipelines.yaml

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4831106&view=logs&j=5ded96ba-e325-5baf-fde0-f1868aa3be52&t=cfd7d899-a506-54ab-8689-bd03e4a79419&l=14
Test phases on our .NET 6 Preview 5 release branch can fail with:
cp: bin/TestRelease/net6-android/Mono.Android.NET_Tests-Signed.apk: No such file or directory
Partially backports da536fcf.
Fix `azure-pipelines.yaml` so that if (when) the
`Mono.Android.NET_Tests` unit tests fail, the corresponding `.apk`
or `.aab` file is uploaded for our later investigation; see also
commit af7f7f5, which contained a "typo" such that .NET 6 packages
*weren't* uploaded on unit test failure, as they used the wrong
target framework identifier in the path.

[build] fix typo in paths of test .apk files

---

src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

In .NET 6 if you run:
dotnet build HelloAndroid -t:SignAndroidPackage -p:BuildingInsideVisualStudio=true
You'll hit the error:
Microsoft.Android.Sdk.AssemblyResolution.targets(136,5): error MSB4096:
The item "obj\Debug\net6.0-android\UnnamedProject.pdb" in item list "ResolvedSymbols" does not define a value for metadata "DestinationSubPath".  In order to use this metadata, either qualify it by specifying %(ResolvedSymbols.DestinationSubPath), or ensure that all items in this list define a value for this metadata.
I could reproduce this problem in a test.
This file doesn't actually exist, as you can see in the log:
Skipping non-existent dependency 'obj\Debug\net6.0-android\UnnamedProject.dll'.
In this scenario, we're using an optimization when building inside the
IDE. In this case:
* IDE …

[One .NET] fix for non-existent .dll/.pdb files

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

We currently emit a warning when `$(UseInterpreter)` is true:
warning XA0119: Using fast deployment and AOT at the same time is not recommended. Use fast deployment for Debug configurations and AOT for Release configurations. [C:\src\xamarin-android\bin\TestDebug\temp\DotNetBuildXamarinFormsTrue\UnnamedProject.csproj]
It turns out that we were setting `$(AotAssemblies)` to true when the
interpreter was used.
Since `$(UseInterpreter)` on Android is meant for Debug & "Hot Reload"
scenarios, we definitely don't want this setting to enable AOT!
Luckily enabling AOT doesn't do anything yet in .NET 6, because it is
not implemented yet. I also suspect enabling the interpreter is not
used much (if at all) in "legacy" Xamarin.Android.
I updated a .NET 6 test so it sets `$(UseInterpreter)` and …

[Xamarin.Android.Build.Tasks] fix warning with $(UseInterpreter)

---

build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs

Currently, `make prepare` fails on Linux with:
System.Exception: Duplicate workload manifest microsoft.net.workload.mono.toolchain
at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.RefreshWorkloadManifests() in Microsoft.DotNet.TemplateLocator.dll:token 0x600006c+0x6c
at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver..ctor(IWorkloadManifestProvider manifestProvider, String[] dotnetRootPaths, String[] currentRuntimeIdentifiers) in Microsoft.DotNet.TemplateLocator.dll:token 0x600006b+0x31
at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion) in Microsoft.DotNet.TemplateLocator.dll:token 0x6000068+0x8a
at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand.. …

[xaprepare] fix workload install on Linux

---

src/Mono.Android.Export/Mono.Android.Export.csproj
src/Mono.Android/Mono.Android.csproj
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/5943
Context: https://github.com/dotnet/sdk/blob/c1b8e80be1f7cca767ed9f3c90a45d6830b166a0/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets#L92-L96
By default, we need to enable ILLink's "single file" analyzers for
Android app projects. We should also do this for `Mono.Android.csproj`
and `Mono.Android.Export.csproj`.
After enabling this analyzer, no warnings appeared. But I do see the
appropriate analyzers setup in projects now:
Analyzer
~\android-toolchain\dotnet\sdk\6.0.100-preview.6.21280.2\Sdks\Microsoft.NET.Sdk\targets\..\analyzers\ILLink.CodeFixProvider.dll
IsImplicitlyDefined = true
~\android-toolchain\dotnet\sdk\6.0.100-preview.6.21280.2\Sdks\Microsoft.NET.Sdk\targets\..\analyzers\ILLink.RoslynA …

[One .NET] set $(EnableSingleFileAnalyzer) by default

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/GenerateUnixFilePermissions.cs
build-tools/create-packs/Microsoft.Android.Sdk.proj
build-tools/installers/create-installers.targets

Context: https://github.com/dotnet/sdk/issues/16894
There is currently a workaround in place, so that executables inside a
.NET workload have the right permissions:
https://github.com/dotnet/sdk/pull/17299/files
A new `data/UnixFilePermissions.xml` file will be required to define
permissions such as:
<FileList>
<File Path="tools/Darwin/aapt2" Permission="755" />
</FileList>
I am putting this in place before the changes to `dotnet workload
install` actually land.
We also found these files should be *removed* from our .NET workload
packs:
* `aprofutil`
* `mono`
* `mono-symbolicate`

[One .NET] define UnixFilePermissions.xml

---

.external
Directory.Build.props
build-tools/create-packs/SignList.xml
build-tools/debian-metadata/rules
build-tools/installers/create-installers.targets
build-tools/xaprepare/xaprepare/xaprepare.csproj
src/Xamarin.Android.Build.Tasks/Resources/Mono.Unix.dll.config
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs

`Xamarin.Android` uses the Mono's Mono.Posix assembly on Unix machines
to perform tasks not possible with BCL classes, provided so far by the
`Mono.Posix.NETStandard` nuget.  Unfortunately, that nuget doesn't work
with `dotnet` and so the `Mono.Posix` code has recently been extracted
from the Mono repository and placed in its own, from which the new
`Mono.Unix` nuget is built and published.
This commit switches to `Mono.Unix` in Xamarin.Android and also updates
a number of submodules which likewise migrated from
`Mono.Posix.NETStandard` to `Mono.Unix`
Additionally, LibZipSharp is updated as well, since it now uses
`Mono.Unix`
`Mono.Unix` no longer uses the older `libMonoPosixHelper` dynamic
library, replaced by a new `libMono.Unix` one.  This change, however,
broke a number of tests since …

Switch to the new Mono.Unix nuget

---

.external
.gitmodules
Configuration.props
Directory.Build.props
build-tools/automation/azure-pipelines.yaml

Xamarin.Android v11.4.0 will be shipped as part of
Visual Studio 2019 16.11 Preview 3 and subsequent releases.
Changes: https://github.com/xamarin/monodroid/compare/76c04cd15eca7afc269a6d26296e9d2db6f79be2...fab2d0b3e5205cb97d03e7a33a367245dbd211aa
* xamarin/monodroid@fab2d0b3e: Branching for d16-11. (#1209)

Branching for d16-11; Bump $(ProductVersion) to 11.4.0

---

Configuration.props

Context: https://github.com/xamarin/xamarin-android/pull/6014
We are occasionally seeing test failures with many forms of:
Could not load file or assembly 'Microsoft.NET.StringTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
This seems to be caused by Mono 6.12.0.145 installed on some of the
build machines.
We can undo this change when #6014 goes in.

[build] temporarily require Mono 6.12.0.137

---

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs

Context: https://developer.android.com/about/versions/12/overview
Context: https://android-developers.googleblog.com/search/label/Android12
Android 12 [Beta 2 has been released][0].
* [API diff vs. Beta 1][1]
* [API diff vs. API-30][2]
Google's documented [timeline for Android 12][3] is unchanged
vs. commit 11c30ac:
* May: Beta 1
* June-July: Beta 2, Beta 3
* August: Beta 4
This contains the final APIs and official SDK.
[0]: https://android-developers.googleblog.com/2021/06/android-12-beta-2-update.html
[1]: https://developer.android.com/sdk/api_diff/s-beta2-incr/changes
[2]: https://developer.android.com/sdk/api_diff/s-beta2/changes
[3]: https://developer.android.com/about/versions/12/overview#timeline

[Mono.Android] Bind API-S Beta 2.

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.After.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.RuntimeConfig.targets
src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/EnvironmentHelper.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGenerator.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
src/monodroid/jni/application_dso_stub.cc
src/monodroid/jni/embedded-assemblies-zip.cc
src/monodroid/jni/embedded-assemblies.hh
src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/shared-constants.hh
src/monodroid/jni/xamarin-app.hh
tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj
tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/System/AppContextTests.cs
tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/runtimeconfig.template.json

WIP, I implemented the MSBuild side partially.

[One .NET] *.runtimeconfig.json support

---

build-tools/create-packs/Directory.Build.targets

We are seeing test failures on Linux such as:
warning MSB4242: The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed to run. Duplicate workload manifest microsoft.net.sdk.android
error MSB4236: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found.
In recent .NET 6 Preview builds, workloads use all lowercase directory
names. We need to update several paths in our .NET 6 build targets, so
lowercase folder names are used.

[build] use lowercase .NET 6 workload folder names

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.After.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NuGet.targets
src/Xamarin.Android.Build.Tasks/Tasks/FixupNuGetReferences.cs

Context: https://github.com/dotnet/maui/pull/1322#issuecomment-861603825
This conditionally reverts commit ca51adbc.
There is a change in NuGet that is currently needed by the .NET 6
Android workload:
https://github.com/NuGet/NuGet.Client/commit/10274281c37e9dd3626938757f7e947d649b821b
This change is not present in VS 16.10 or VS 16.11:
https://github.com/dotnet/msbuild/blob/vs16.11/eng/Version.Details.xml
If we want Visual Studio 2019 on Windows to continue working for .NET
6 projects, then we can't actually remove our NuGet workarounds.
I put the workarounds back, but then are now conditionally imported:
<Import Project="Microsoft.Android.Sdk.NuGet.targets" Condition=" '$(MSBuildRuntimeType)' == 'Full' and '$(MSBuildVersion)' &lt; '17.0' " />
So if you use `dotnet build` or Visual …

Revert "[One .NET] remove NuGet workarounds"

---

Documentation/release-notes/5951.md
src/Xamarin.Android.Build.Tasks/Tasks/GetAndroidPackageName.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #5951
Related: commit b423ff6.
Our current `AndroidManifestPlaceholders` implementation would allow users
to change any part of the manifest with the exception of the `package`
element on the `manifest` itself. What was actually happening was the
`package` was being changed but it was happening after  the
`GetAndroidPackageName` had already been called. So the internal MSBuild
property `$(_AndroidPackage)` did not reflect the desired value.
So lets update `GetAndroidPackageName` to use the `AndroidManifestPlaceholders`.
Note: This will only effect the `$(_AndroidPackage)` value when the
manifest is being used. If the user is using the `GenerateApplicationManifest`
option, the `$(_AndroidPackage)` will be controlled from the `$(ApplicationId)`
MSBuild property.

[Xamarin.Android.Build.Tasks] Allow package to be defined with AndroidManifestPlaceholders

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets

Xamarin.Android.NUnitLite has been deprecated. So lets add a Warning
like we did for OpenTK to give users a heads up.

[Xamarin.Android.Build.Tasks] Add Warning for NUnitLite

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets

Context: https://github.com/dotnet/designs/blob/1a79ddc4dc8df38f645d2b5517cdfa330747511e/accepted/2020/net5/net5.md#valid-platforms
Context: https://github.com/xamarin/xamarin-macios/commit/e35bb9c47913fc8ef6c23a89a73e219f75daa448
The spec for `$(TargetPlatformIdentifier)` mentions that each workload
should normalize the casing.
xamarin-macios already does this for `iOS`, `macOS`, `tvOS`, etc. We
should normalize to `Android`.
The place I set this is only imported by `WorkloadManifest.targets`
when MSBuild's case insensitive string comparison matches:
<Import Project="Sdk.targets" Sdk="Microsoft.Android.Sdk"
Condition=" '$(TargetPlatformIdentifier)' == 'android' " />
So we can simply set this early on in our .NET 6 `.targets`:
<TargetPlatformIdentifier>Android</TargetPlatformIdentifier>

[One .NET] normalize case for $(TargetPlatformIdentifier)

---

tests/Mono.Android-Tests/System.Net/WebSocketTests.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/5801
Web sockets appear to be working in .NET 6 Preview 5 and higher. I
think we can simply enable these tests now.

[One .NET] enable WebSocketTests

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/6016
Context: https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/MauiApp1/Android/AndroidEnvironment.txt
Currently, the the .NET MAUI project template includes a
`@(AndroidEnvironment)` file for "Hot Reload" scenarios. Let's setup
this value by default so it will not be needed.

[One .NET] set env var automatically for $(UseInterpreter)

---

src/Xamarin.Android.Build.Tasks/Tasks/GenerateCompressedAssembliesNativeSourceFiles.cs

Context: https://dev.azure.com/xamarin/public/_build/results?buildId=41853&view=logs&j=9cf5f8f4-c6e1-5b84-8b95-5f96f5b2da57&t=837f1816-7880-57fc-23bc-a709d74f8097&l=22687
dotnet/maui is hitting a build error, such as:
error XAGCANSF7004: System.ArgumentException: An entry with the same key already exists.
error XAGCANSF7004:    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
error XAGCANSF7004:    at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
error XAGCANSF7004:    at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)
error XAGCANSF7004:    at Xamarin.Android.Tasks.GenerateCompressedAssembliesNativeSourceFiles.GenerateCompressedAssemblySources()
error XAGCANSF7004:    at …

[Xamarin.Android.Build.Tasks] fix ArgumentException in GenerateCompressedAssembliesNativeSourceFiles

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets

Rework of commit 064babf6 to raise an error under .net 6 if the user tries to
use OpenTK or NUnitLite. We can do this by using the `AndroidError`
task to raise the error. Under legacy projects we use the `ContinueOnError`
Task property to control if the output is a warning or not. Under .net 6
it will be an error, under legacy it will be a warning.
Update the existing unit test to handle the new errors/warnings and
let it run under .net 6.

[Xamarin.Android.Build.Tasks] Add OpenTK/NUnitLite Error for .net 6

---

Documentation/guides/tracing.md
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Tasks/ProcessNativeLibraries.cs
src/monodroid/jni/monodroid-glue.cc

`EventPipe` is a dotnet mechanism to implement profiling/tracing of
.NET5+ applications.  It replaces the Mono logging profiler which no
longer works.
This commit adds support of packaging the Mono components required for
EventPipe to work in the application APK as well as runtime support for
initializing and enabling the profiler.
Profiler is enabled by setting the `debug.mono.profile` Android system
property to the appropriate value (e.g. `127.0.0.1:9000,suspend`) which
is then exported by the XA runtime as an environment
variable (`DOTNET_DiagnosticPorts`) which, in turn, is read by the
EventPipe component in order to start profiling.
Details of the process are documented in the
`Documentation/guides/tracing.md` file.

Add EventPipe tracing support

---

build-tools/automation/azure-pipelines.yaml

Since 5da92bd we are seeing the on device tests fail with the following error.
error JAVAC0000: java.lang.AssertionError: annotationType() :  unrecognized Attribute name MODULE (class com.sun.tools.javac.util.SharedNameTable$NameImpl)
This suggests that AP 31 requires JDK 11 in order to compile.
So lets bump the version which we use for the on device tests for now,
until we can figure out what do actually do.

try to use jdk 11 for device tests

---

build-tools/automation/azure-pipelines.yaml

We've been having an issue with Android Designer test dependency
provisioning on macOS:
Xamarin.Provisioning.ProvisioningException: Failed to provision /Applications/Xcode_12.5.0.app
---> Xamarin.Provisioning.ProvisioningException: This Xcode version requires macOS ≥ 11.0 (currently running on 10.15.7)
We should be able to remedy this by moving to the same macOS Big Sur
pool that the Designer build is using.
The Windows tests have also been failing for a while, and this problem
is [not unique to our pipeline][0].  We should disable these tests for
now until the issue is addressed.
[0]: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4894821&view=logs&jobId=2f037848-d60e-57a4-8d19-387778a8302c&j=2f037848-d60e-57a4-8d19-387778a8302c&t=fbc84e65-28e6-5146-ccec-20ffda77f75c

[ci] Use macOS 11 for Android Designer tests

---

Directory.Build.props

Context: https://github.com/xamarin/LibZipSharp/commit/fcb9323d9d95b06051f67d8d73ba371a4029722d
Context: https://libzip.org/news/release-1.8.0.html
2.0.0-alpha7 changes:
* bump libzip version to 1.8.0
* add support for ZSTD compression
* properly hide all the native library symbols except for the libzip ones

Bump LibZipSharp to 2.0.0-alpha7

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs

If you run the `DotNetNew` tests by themselves, they fail because a
`NuGet.config` file is not generated that contains:
<add key="testsource1" value="C:\src\xamarin-android\bin\BuildDebug\nuget-unsigned" />
...and so it isn't able to locate any of the
`Microsoft.Android.Runtime.*` packs without this.
We have two `CreateDotNetBuilder()` methods in this test, and they now
generate the `NuGet.config` file in the same way.
I also fixed a place that `Directory.CreateDirectory()` was needed.

[tests] fix for DotNetNew tests

---

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
src/Xamarin.Android.Build.Tasks/Tasks/ReadAndroidManifest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.DX.targets
tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs

Fixes #5925
Context https://developer.android.com/topic/security/dex
Android 10 introduced a new attribute for the application element in the
AndroidManifest.xml, `android:useEmbeddedDex`. This allows the .dex files
to be run directly from the apk, rather than unpacked. This new attribute
does require that the .dex files be STORED in the apk rather than
COMPRESSED. Otherwise you get the following error
Failure [INSTALL_FAILED_INVALID_APK: Some dex are not uncompressed and aligned correctly
So lets update BuildApk to use the `GetCompressionMethod` method to figure
out if we need to compress the .dex files. We can then update the `ReadAndroidManifest`
task to check for the new attribute and update the `AndroidStoreUncompressedFileExtensions`
ItemGroup accordingly.
Also added unit tests.

[Xamarin.Android.Build.Tasks] Add support for `android:useEmbeddedDex`

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Context: https://github.com/dotnet/maui/pull/1309#issuecomment-866364091
dotnet/maui projects are failing to build after adding new ASP.NET
assemblies for BlazorWebView:
error XABLD7024: System.IO.IOException: The process cannot access the file 'D:\a\1\s\src\Controls\samples\Controls.Sample.SingleProject\obj\Release\net6.0-android\android\lz4\System.Runtime.CompilerServices.Unsafe.dll.lz4' because it is being used by another process. [D:\a\1\s\src\Controls\samples\Controls.Sample.SingleProject\Maui.Controls.Sample.SingleProject.csproj]
error XABLD7024:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [D:\a\1\s\src\Controls\samples\Controls.Sample.SingleProject\Maui.Controls.Sample.SingleProject.csproj]
error XABLD7024:    at System.IO.FileStream.Init(String path, …

[One .NET] fixes for System.* PackageReference

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.AvailableItems.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Fixes: https://github.com/dotnet/maui/issues/1475
A .NET 6 application project was failing to include C# bindings for
`.aar` files, but `.jar` files were working.
The workaround was to include:
<LibraryProjectZip Include="myjavalibrary.aar" />
We had a test that checked this behavior for `.jar` files, but not
`.aar` files.
After reproducing the behavior in a test, I found the
`_CategorizeAndroidLibraries` MSBuild target did not automatically
setup the `@(LibraryProjectZip)` item group in .NET 6 application
projects. `@(AndroidAarLibrary)` *was* being setup, which explained
why the Java code made it to `classes.dex`, but C# bindings were
missing.
Updated the `_CategorizeAndroidLibraries` MSBuild target for this case.

[One .NET] enable C# bindings for @(AndroidLibrary)

---

src/Mono.Android/Android/LinkerSafeAttribute.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/5639
Context: https://github.com/mono/linker/blob/84338086c5f36f4847b85242b1c8c2d3ea7177ac/docs/design/trimmed-assemblies.md#assemblymetadataistrimmable-true
The `Android.LinkerSafeAttribute` custom attribute is beening
replaced by the [`System.Reflection.AssemblyMetadataAttribute`][0]
custom attribute, with a `Key` of `"IsTrimmable"` and a
`Value` of `"True"`:
// Old-and-busted
[assembly: Android.LinkerSafe]
// New hotness:
[assembly: global::System.Reflection.AssemblyMetadata("IsTrimmable", "True")]
`AssemblyMetadataAttribute` is more portable, part of
.NET Standard 1.0 and above, with linker support in .NET 5+.
It should thus be preferred over `Android.LinkerSafeAttribute`.
[0]: …

[Mono.Android] Obsolete [LinkerSafe]

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-msbuild-device-tests.yaml
build-tools/automation/yaml-templates/run-msbuild-mac-tests.yaml
build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml
build-tools/scripts/NUnitReferences.projitems
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj

Updates `Xamarin.Android.Build.Tests` and `MSBuildDeviceIntegration` tests
to cross target against `net6.0` instead of `netcoreapp3.1`.

[build] Update MSBuild tests to target net6.0

---

README.md

Links currently point to `xamarin.android-11.3.0.4`.

[readme] Add 16.10 download links.

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets

The default value for release app will be false, so debugger will not be available.
The default value for release app will be true, so debugger will be available.
Related to https://github.com/dotnet/runtime/pull/54887

[debugger] Componentize the debugger, only link debugger when it's a debug app.

---

src/monodroid/jni/embedded-assemblies.cc
src/monodroid/jni/embedded-assemblies.hh
src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/util.cc
src/monodroid/jni/util.hh

Context: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=net-5.0
dotnet 6 removes support for AppDomains (technically, there still exists
a single AppDomain, but creation of new ones is no longer possible),
replacing them (in a way) with AssemblyLoadContext, which enables scoped
loading of managed assemblies.
Part of the change is the new set of MonoVM functions we need to call in
order to load an assembly into either the default AssemblyLoadContext
(early in the startup process) or into the application-created context
later on during application run time.  MonoVM also adds new preload
hooks which work with the `ALC` instead of the older AppDomains.
This commit adds support for `ALC` preload callbacks and the new
assembly load functions.

[NET6] Enable support for AssemblyLoadContext

---

src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/CheckPackageManagerAssemblyOrder.java
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/GeneratePackageManagerJavaTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj

Context:
* https://discord.com/channels/732297728826277939/732297965019988138/859449393472471082
* ...through...
* https://discord.com/channels/732297728826277939/732297965019988138/859454102999400488
The ordering of `MonoPackageManager_Resources.Assemblies` is very important to process startup, e.g. see 9c043786, wherein we decide that we *must* preload the *first* assembly listed within `MonoPackageManager_Resources.Assemblies`, as that's The One that has the correct resource IDs.
The problem is threefold:
1. The order of `@(_ResolvedUserAssemblies)` is poorly defined/undefined.
2. `@(_ResolvedUserAssemblies)` contains *paths* which includes directory names.
3. The observed ordering of `@(_ResolvedUserAssemblies)` *differs* between "legacy" MSBuild and `dotnet build`.
See also: …

[Xamarin.Android.Build.Tasks] Fix Assembly Ordering in PackageManager

---

src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/osbridge.cc
src/monodroid/jni/osbridge.hh
src/monodroid/jni/shared-constants.hh
src/monodroid/jni/timezones.cc
src/monodroid/jni/util.cc
src/monodroid/jni/util.hh

NET6+ no longer supports multiple AppDomains, there's always only a
single "root" AppDomain.  This allows us to drop bits of code which deal
with obtaining and setting the current AppDomain in various context.
This commit removes almost all uses of AppDomains from the native
Xamarin.Android runtime.  Unfortunately, it requires sometimes messy use
of the C++ preprocessor, but wherever it is possible and not overly
ugly, I try to separate the NET6 and "legacy" code completely, for
easier and less noisy future removal of the latter.

[NET6] Remove as much AppDomain use as possible

---

build-tools/automation/azure-pipelines.yaml
build-tools/create-packs/Directory.Build.targets
build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json

Context: https://github.com/dotnet/maui/tree/ef4518bf502ffa6760625c4cb53fa0cb015bc6d1/src/Workload#net-maui-workload-ids
Right now to install the Android workload you would run:
dotnet workload install microsoft-android-sdk-full
Let's shorten this to be:
dotnet workload install android
We can also create a new workload that extends `android`, and includes
AOT support:
dotnet workload install android-aot
To test this behavior on our CI, I reworked the `ExtractWorkloadPacks`
to run `dotnet workload install` commands. This should give us more
confidence that our workload can be installed -- and our MSBuild tests
will consume the installed workload.
Other changes:
* Added our `Microsoft.Android.Runtime.*` packs to the
`WorkloadManifest.json`. This was mostly omitted by mistake;
however, …

[One .NET] dotnet workload install android or android-aot

---

.external
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Emulator.csproj
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
tests/MSBuildDeviceIntegration/Tests/BundleToolTests.cs

We have seen in the past issues where the emulator seems to disappear during Unit testing. 
I don't have access to the error message which we got since those old builds have since been removed. 
Our existing setup checked that we had a running emulator when the test fixture was started. So this check
only happened once. If anything happens to the emulator after that check the unit tests would still think
that is was running. Also there is no recovery mechanism. All the code to start the emulator is handled by 
the pipelines build scripts and the `AcquireAndroidTarget`. 
So we need to rethink this a bit. The pipelines will still call `AcquireAndroidTarget` to start up the emulator 
before all the tests. But we need to introduce some additional checks to make sure the emulator is …

Try to detect when the emulator is not working

---

build-tools/automation/azure-pipelines.yaml

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4954055&view=logs&j=a62e275d-46d5-5c3b-5a47-c4e00ae7427d&s=998e29ca-850b-59f2-4134-6ed1d0ce6c3a
I've seen our .NET 6 installer jobs time out after 60 minutes a couple
of times recently, we should be able to avoid this by increasing the
default timeout value.

[ci] Increase job timeouts for .NET 6 installers

---

src/monodroid/jni/osbridge.cc

Context: https://code.google.com/p/android/issues/detail?id=63929
Context: https://android-review.googlesource.com/c/platform/art/+/73142
ART issue this code worked around was fixed in December 2019 and
released in one of the Android 4.4 (KitKat, API 19) updates, most likely
4.4.3 on June 2, 2014.
Additionally the `persist.sys.dalvik.vm.lib` system property doesn't
appear to be present any longer on newer Android versions.
Remove the dead code.

Remove dead code

---

.vscode/extensions.json
.vscode/settings.json
.vscode/tasks.json
Documentation/guides/vscode-support.md
Xamarin.Android.code-workspace
build-tools/scripts/vswhere.cmd
build.cmd
build.sh

Update the extensions list to use the correct id for the vscode csharp extension.
Remove the `nxunitExplorer.nunit` setting as it was causing the unit tests not to load.
This is because the extension is expecting a CIL image, but we were passing a batch
file. As a result none of the unit tests would load in the IDE.
Add some documentation around using VSCode to run the unit tests and debug the 
sample apps. This includes a link to a patched version of the `testrun.exe` which the 
`nxunit.explorer` extension uses. There is a bug in the extension where tests will 
parameters will NOT run or debug. The link patched version of the files is included 
in the docs. A PR to the upstream extension has also been sent.
Added the `dotnet-adapter` extension which lets us run the tests under a `dotnet` …

Update VSCode Support

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml

Context: https://www.1eswiki.com/wiki/1ES_hosted_AzureDevOps_Agents
We've been tasked with migrating away from our scale set agent pools to
a new 1ES service.  There are a couple of benefits to using 1ES agent
pools.  We should now be able to use customizable versions of the
[Microsoft-hosted agent images][0] which come preloaded with some of our
dependencies.  These images are also updated regularly which should
hopefully reduce maintenance costs.  Overall, the process for creating,
updating, and rolling out image changes to our scale set agent pools
should now be dramatically simplified over [the existing workflow][1].
Visual Studio update steps have been removed as these images should stay
up to date with the latest stable VS, similar to the Microsoft-hosted
images.
The new Azure …

[ci] Use new 1ES Hosted win2019 Pool

---

build-tools/create-packs/Directory.Build.targets

When working on .NET 6, I've occasionally hit the build error:
Microsoft.NET.TargetFrameworkInference.targets(109,5): error NETSDK1139: The target platform identifier android was not recognized.
After looking at the contents of `dotnet\packs`, I
have an empty folder such as:
~\android-toolchain\dotnet\packs\Microsoft.Android.Sdk.Windows\30.0.100-ci.main.76\
Yet the workload said it actually installed the pack:
Writing workload pack installation record for Microsoft.Android.Sdk version 30.0.100-ci.main.76...
I think the `dotnet workload` command must skip over folders if the
folder *exists*. It does not actually validate if content is missing.
To make matters worse, our logic would not actually delete folders
when using this wildcard:
<_PackFilesToDelete …

[build] use explicit folder names in DeleteExtractedWorkloadPacks

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Context: https://blog.gradle.org/jcenter-shutdown
Context: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
JCenter is shutting down. It is no longer browsable as of May 1, and artifacts hosted on JCenter repository will be read-only accessible indefinitely.
Stop using JCenter, and instead use Maven Central.
NOTE: unable to find url replacements:
* jetbrains runtime jbrsdk
* twitter-core
```
./build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs:35:			// https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbrsdk-8u202-linux-x64-b1483.37.tar.gz
./build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs:36:			// https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbrsdk-8u202-osx-x64-b1483.37.tar.gz …
```

jfrog/bintray removals/replacements

---

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/GitBranch.cs

According to the [Pipelines predefined variables doc][0], the
`$(BUILD_SOURCEBRANCHNAME)` variable will only contain the last path
segment in the branch name value.  This is the example they provide:
For example, in `refs/heads/main` this value is `main`. In
`refs/heads/feature/tools` this value is `tools`.
CI builds for branches containing `/` would produce .NET 6 packs and
manifests with incomplete branch information, which can be fixed by
using (and trimming) the `$(BUILD_SOURCEBRANCH)` variable instead.
Possible values for `$(BUILD_SOURCEBRANCH)`:
* Git repo branch: refs/heads/main
* Git repo pull request: refs/pull/1/merge
[0]: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services

[build] Update Pipelines var used for branch name

---

src/Mono.Android/Android.Runtime/AndroidRuntime.cs
src/monodroid/jni/internal-pinvoke-api.cc
src/monodroid/jni/osbridge.hh
src/monodroid/jni/pinvoke-override-api.cc
src/monodroid/jni/xa-internal-api-impl.hh
src/monodroid/jni/xa-internal-api.cc
src/monodroid/jni/xa-internal-api.hh

Context: https://github.com/xamarin/monodroid/commit/cb49134f6126f56ab9eec6efd52d85b45694dfe4
Context: https://github.com/xamarin/java.interop/blob/4a02bc3291ccf81e82379a426a731716a31741f8/src/Java.Interop/Java.Interop/JniRuntime.JniObjectReferenceManager.cs#L156-L157
The `JniRuntime.JniObjectReferenceManager.WeakGlobalReferenceCount`
property is supposed to return the number of JNI Weak Global References
which have been created by Xamarin.Android.
Unfortunately, `AndroidObjectReferenceManager.WeakGlobalReferenceCount`
always returned -1, which had the nasty side effect of breaking
`JniObjectReferenceManager.CreateWeakGlobalReference()`, which
*asserts* that `WeakGlobalReferenceCount` is not negative.
The result is that the [`JavaObjectTest.UnregisterFromRuntime()`][0]
unit test *always …

[Mono.Android] Fix WeakGlobalReferenceCount

---

Documentation/guides/OneDotNet.md
Documentation/guides/OneDotNetBindingProjects.md
Documentation/guides/building-apps/build-properties.md
src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Tasks/Generator.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets

Fixes: #4657.
With .NET 6 we want to turn on the following binding project enhancements added with C# 8 by default:
- Interface constants
- Interface static methods
- Interface default methods
- Interface nested types
However, each of these features previously had a workaround that we performed so the code could be used by .NET.  This means that users who are updating their existing bindings may find API breaks as we now use the new method instead of the workaround.  Thus each of these needs a way for the user to opt out of the new behavior to preserve API compatibility.
- **`<AndroidBoundInterfacesContainConstants>`** - Controls whether constants on interfaces will be supported, or the old workaround of creating a `IMyInterfaceConsts` class will be used.
- …

[Xamarin.Android.Build.Tasks] Set .NET6 defaults for bindings projects.

---

Documentation/workflow/DevelopmentTips.md

This gives a few examples on how to test a specific dotnet/runtime build in a .NET 6 Android application.

[docs] add some tips for .NET 6 Mono runtime packs

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets

Fixes #6091
The code was executing the call to `lipo` to create the universal
binary. But then overwriting it with the 64 bit version later.
We should only do the Copy if we are not on MacOS.

[Xamarin.Android.Build.Tasks] .NET 6 builds fail on Apple M1

---

Directory.Build.props
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
tests/Xamarin.Forms-Performance-Integration/Droid/Xamarin.Forms.Performance.Integration.Droid.csproj
tests/Xamarin.Forms-Performance-Integration/Xamarin.Forms.Performance.Integration.csproj

Changes: https://github.com/JamesNK/Newtonsoft.Json/compare/12.0.3...13.0.1
* JamesNK/Newtonsoft.Json@ae9fe44e: Remove compiler package and update sourcelink (#2498)
* JamesNK/Newtonsoft.Json@8ef66218: Remove prerelease for 13.0.1
* JamesNK/Newtonsoft.Json@11331f50: Update SDK to 5.0.200 (#2495)
* JamesNK/Newtonsoft.Json@c7e8abc0: Update to 13.0.1-beta2
* JamesNK/Newtonsoft.Json@1745d7c1: Fix JTokenWriter when writing comment to an object (#2493)
* JamesNK/Newtonsoft.Json@583eb120: Fix missing error when deserializing JToken with a contract type mismatch (#2494)
* JamesNK/Newtonsoft.Json@b6dc05be: Change MaxDepth default to 64 (#2473)
* JamesNK/Newtonsoft.Json@15525f1c: Fix JsonWriter.WriteToken to allow null with string token (#2472)
* JamesNK/Newtonsoft.Json@926d2f0f: Enable embed …

Bump to JamesNK/Newtonsoft.Json@ae9fe44e [13.0.1]

---

build-tools/automation/azure-pipelines-oss.yaml
build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/setup-ubuntu.yaml
build-tools/debian-metadata/rules

Context: https://www.1eswiki.com/wiki/1ES_hosted_AzureDevOps_Agents
We've been tasked with migrating away from our scale set agent pools to
a new 1ES service.  There are a couple of benefits to using 1ES agent
pools.  We should now be able to use customizable versions of the
[Microsoft-hosted agent images][0] which come preloaded with some of our
dependencies.  These images are also updated regularly which should
hopefully reduce maintenance costs.  Overall, the process for creating,
updating, and rolling out image changes to our scale set agent pools
should now be dramatically simplified over [the existing workflow][1].
Our internal and OSS Linux builds will now use the same Ubuntu 20.04
base image, so setup tasks can be shared.  A couple of workarounds
have been added to avoid some open …

[ci] Use new 1ES Hosted Ubuntu Pools

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/delete-platform-31.yaml
build-tools/automation/yaml-templates/setup-test-environment.yaml

Context: https://github.com/xamarin/xamarin-android/pull/6089
We currently have lots of test failures due to the warning:
warning XA1008: The TargetFrameworkVersion (Android API level 30) is lower than the targetSdkVersion (31). Please increase the `$(TargetFrameworkVersion)` or decrease the `android:targetSdkVersion` in the `AndroidManifest.xml` so that the API levels match.
Looking at `Properties\AndroidManifest.xml`, Xamarin.ProjectTools
generated:
<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="31" />
This appears to be due to the `GetMaxInstalledPlatform()` method:
https://github.com/xamarin/xamarin-android/blob/1b71da0cd3a44861b006ac41c77a24eedf066281/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs#L121-L138
I think what …

[build] delete platform-31 folder on test jobs

---

build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs

I'm seeing failures on CI such as:
C:\a\_work\2\s\build-tools\xaprepare\xaprepare\package-download.proj : warning MSB4242: The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed to run. Inconsistency in workload manifest 'microsoft.net.workload.mono.toolchain': missing dependency 'Microsoft.NET.Workload.Emscripten'
C:\Users\cloudtest\android-toolchain\dotnet\sdk\6.0.100-preview.7.21369.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,3): warning MSB4242: The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed to run. Inconsistency in workload manifest 'microsoft.net.workload.mono.toolchain': missing dependency 'Microsoft.NET.Workload.Emscripten'
C:\Users\cloudtest\android-toolchain\dotnet\sdk\6.0.100-preview.7.21369.2\Sdks\Microsoft.N …

[xaprepare] always delete ~/android-toolchain/dotnet

---

src/Mono.Android.Export/CallbackCode.cs

For awhile, we've been observing ILLink warnings:
ILLink warning IL2036: Java.Interop.DynamicInvokeTypeInfo.ToNative(CodeExpression): Unresolved type 'Android.Runtime.JavaArray' in DynamicDependencyAttribute
The cause is a "typo" in commit 15269f6f, which added the
`[DynamicDependency]` custom attributes to
`DynamicInvokeTypeInfo.ToNative()`: commit 15269f6f specified the
non-generic type `Android.Runtime.JavaArray`, which does not exist.
Fix the `[DynamicDependency]` custom attribute value to instead
mention ``Android.Runtime.JavaArray`1``, the type `JavaArray<T>`.
This should fix the IL2036 warning.

[Mono.Android.Export] Fix DynamicDependency to JavaArray

---

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs

Changes: https://sourceware.org/pipermail/binutils/2021-July/117384.html
Upstream release message mentions numerous bug fixes, however doesn't
list them.  List of bugs in SourceWare bugzilla tagged with the 2.37
version:
https://sourceware.org/bugzilla/buglist.cgi?bug_status=RESOLVED&component=binutils&component=gas&component=ld&product=binutils&query_format=advanced&resolution=FIXED&version=2.37

Bump to Binutils v2.37

---

src/Mono.Android/Android.Runtime/JNIEnv.cs
src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
tests/MSBuildDeviceIntegration/Tests/UncaughtExceptionTests.cs

Context: https://github.com/dotnet/runtime/pull/55904#discussion_r672577807
Context: https://github.com/xamarin/xamarin-android/pull/4927#issuecomment-875864999
Context: https://github.com/xamarin/xamarin-android/pull/4927#issuecomment-875876255
Xamarin.Android has been using the `AppDomain.DoUnhandledException` API
since the dawn of time to propagate uncaught Java exceptions to the
managed world.  However, said API (and AppDomains) are gone from the
NET6 MonoVM runtime and we need to switch to something else - the
`mono_unhandled_exception` native API.
This commit introduces an internal call,
`JNIEnv.monodroid_unhandled_exception`, which is used instead of the
older mechanism when targetting NET6 and which calls the native API
mentioned above.
Add a device integration test which makes …

Use `mono_unhandled_exception` for NET6

---

build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs

Context: https://github.com/xamarin/xamarin-android/pull/6112#pullrequestreview-712229556
The .NET Preview 7 bump is failing with:
Running: /Users/builder/Library/Android/dotnet/dotnet "workload" "install" "microsoft-net-runtime-android" "--skip-manifest-update" "--verbosity" "diag"
stderr | Workload with id microsoft-net-runtime-android is not recognized.
However, it was a bug in the `dotnet workload install` command that we
were even able to install this workload in the first place! The
concept behind "abstract" workloads is they are not user visible in
any way. They're meant to be an implementation detail.
In 0150bbbc, I setup `xaprepare` to install
`microsoft-net-runtime-android`, but we don't actually even need to do
this. We can simply update the `sdk-manifest` for this pack, so the …

[xaprepare] don't install microsoft-net-runtime-android workload

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs

Context: https://github.com/xamarin/xamarin-android/pull/6112
The .NET 6 Preview 7 bump had a test failure:
CleanBasicBindingLibrary("class-parse")
obj/Release should have no directories.
Expected: <empty>
But was:  < "/Users/runner/work/1/s/bin/TestRelease/temp/CleanBasicBindingLibraryclass-parse/obj/Release/refint" >
`refint` is a new directory, see:
* https://github.com/dotnet/sdk/pull/19114/commits/e424c0eae2dcbdb71ff60014c6bdad82ddb3175d
* https://github.com/dotnet/msbuild/blob/9e576281e638d60701ca34411e2483bed01e35c7/src/Tasks/Microsoft.Common.CurrentVersion.targets#L397
Clean doesn't actually delete directories, no need to test for this.
The test already is checking if any files exist, and that should be
sufficient.

[tests] we don't need to check if Clean deletes directories

---

src/Mono.Android/Android.Runtime/JNIEnv.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.cs
src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc

Waiting this to be merged https://github.com/dotnet/runtime/pull/56071

[debugger] Calling embedded api and avoid changing System.Diagnostics.Debugger class.

---

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/MacOS.cs

Homebrew allows pinning of a package to a specific version of it, but
the solution is far from perfect for us.  The problem is that if you
updated your mingw version to any version other than we require,
`xaprepare` will detect it and will try to install version of the
package that we need, but if it's older than the current version, we'll
get the latest version installed anyway since there's no direct way of
specifying a package/formula version.
Instead of trying o work around the issue, let's always install the
latest version of mingw (currently 9.0.0).

[macOS] Do not pin mingw version

---

src/Mono.Android/Android.Runtime/PreserveAttribute.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/5664
The .NET 5+ replacement for [`Android.Runtime.PreserveAttribute`][0]
is [`System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute`][1].
One "discrepancy" is that the relationship is "backwards":
`[Preserve]` is an *assertion* that the member is required, and that
the member should be preserved by the linker.
`DynamicDependencyAttribute` is an indicator: *if* the member with
`[DynamicDependency]` is preserved, then the members referenced by
`[DynamicDependency]` will be preserved.
Consider commit 15269f6f: in a `[Preserve]` world, we had:
// `Mono.Android.dll`
[Preserve(AllMembers=true)] partial class JavaCollection {
public static IntPtr ToLocalJniHandle (ICollection? items) {…}
}
[Preserve(AllMembers=true)] partial class …

[Mono.Android] Obsolete [Preserve]

---

.external

Fixes: https://github.com/xamarin/xamarin-android/issues/6113
Changes: https://github.com/xamarin/monodroid/compare/33e542fac95f1ac4e56d3965d2f336a1d6a5f98e...ab6c39ee5f5762c2e21b0628af6b0fa1c8256498
* xamarin/monodroid@ab6c39ee5: [tools/fastdev] use strtoull to parse 64 bit argument. (#1217)
* xamarin/monodroid@aa75b5b89: [tools/msbuild] Cache the ToolsAbi value for the device. (#1216)
* xamarin/monodroid@d4a8977cb: [tools/msbuild] add missing RuntimeConfigBinFilePath value (#1213)

Bump to xamarin/monodroid/main@ab6c39ee

---

Documentation/guides/OneDotNet.md
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/GenerateSupportedPlatforms.cs
build-tools/automation/azure-pipelines.yaml
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.After.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Aot.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs
src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
src/Xamarin.Android.Build.Tasks/Tasks/CilStrip.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetAotArguments.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
tests/MSBuildDeviceIntegration/Tests/AotProfileTests.cs
tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj

Fixes: https://github.com/xamarin/xamarin-android/issues/6052
Helpful reading:
* https://github.com/dotnet/runtime/blob/15dec9a2aa5a4236d6ba70de2e9c146867b9d2e0/src/tasks/AotCompilerTask/MonoAOTCompiler.cs
* https://github.com/dotnet/runtime/blob/15dec9a2aa5a4236d6ba70de2e9c146867b9d2e0/src/mono/netcore/nuget/Microsoft.NET.Runtime.MonoAOTCompiler.Task/README.md
To make this work, I moved the existing `<Aot/>` MSBuild task calls to
a new `_AndroidAot` MSBuild target in `Xamarin.Android.Legacy.targets`.
In the .NET 6 targets, there is a *different* `_AndroidAot` MSBuild
target that runs the new `<MonoAOTCompiler/>` MSBuild task. The
`_AndroidAot` target runs per `$(RuntimeIdentifier)` after the linker
completes. Native libraries are added to the
`@(ResolvedFileToPublish)` item group to be …

[One .NET] AOT support

---

build-tools/automation/azure-pipelines.yaml

With `dotnet workload install` and the soon to come Visual Studio based
acqusition paths, we should no longer need the .pkg and .msi installers
for our .NET 6 content.  Signing and notarization for these installers
takes a decent amount of time in our official build pipeline.  We can
save some turnaround time by removing these jobs as they should no
longer be needed.  The source used to create these installers is not
being removed in case it's ever needed in the future.

[CI] Remove temporary .NET 6 installer jobs

---

Documentation/release-notes/6084.md
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Tooling.targets
src/Xamarin.Android.Build.Tasks/Tasks/Legacy/ValidateJavaVersion.cs
src/Xamarin.Android.Build.Tasks/Tasks/ValidateJavaVersion.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/CodeBehindTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ResolveSdksTaskTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs

API 31 builds fail when using JDK 1.8 with:
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1728,3):
error JAVAC0000: java.lang.AssertionError: annotationType() : unrecognized Attribute name MODULE (class com.sun.tools.javac.util.SharedNameTable$NameImpl)
To solve this issue, we must require JDK 11 for API 31.
There are two code paths here for "legacy" Xamarin.Android and .NET 6.
Legacy is straightforward, as we already had a pattern for this.
In .NET 6, I checked the `$(TargetPlatformVersion)` property for now
and require JDK 11 in that case. When API 31 is stable, we can
probably remove this code and just set this value by default:
<MinimumSupportedJavaVersion Condition=" '$(MinimumSupportedJavaVersion)' == '' …

[Xamarin.Android.Build.Tasks] require JDK 11 for API 31

---

src/Microsoft.Android.Templates/android-bindinglib/.template.config/template.json
src/Microsoft.Android.Templates/android-bindinglib/AndroidBinding1.csproj
src/Microsoft.Android.Templates/android/.template.config/template.json
src/Microsoft.Android.Templates/android/AndroidApp1.csproj
src/Microsoft.Android.Templates/android/AndroidManifest.xml
src/Microsoft.Android.Templates/androidlib/.template.config/template.json
src/Microsoft.Android.Templates/androidlib/AndroidLib1.csproj
src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Designer.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs
src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs
src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownProperties.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://github.com/xamarin/xamarin-android/issues/6107#issuecomment-884391615
In .NET 6, we are wanting `AndroidManifest.xml` in project templates
to no longer contain:
<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="30" />
This is because we can define these values such as:
<TargetFramework>net6.0-android30</TargetFramework>
<SupportedPlatformOSVersion>21.0</SupportedPlatformOSVersion>
There is not really a reason to put this information in two places.
`$(SupportedPlatformOSVersion)` is also required for enabling C#
compiler warnings such as:
MainActivity.cs(28,4): warning CA1416: This call site is reachable on: 'Android' 21.0 and later. 'View.AccessibilityTraversalAfter.get' is only supported on: 'android' 22.0 and later.
This is an example of calling an API from …

[One .NET] implement $(SupportedPlatformOSVersion) for minSdkVersion

---

Documentation/release-notes/r8-2.2.64.md
src/r8/build.gradle

Context: https://r8.googlesource.com/r8/+/refs/tags/2.2.64
Context: https://mvnrepository.com/artifact/com.android.tools/r8/2.2.64
Bump from r8 2.1.75 to 2.2.64.

Bump to r8 2.2.64

---

build-tools/automation/azure-pipelines.yaml

Commit 810c9170 was not tested well enough, and attempting to push pack
info to Maestro has been failing:
C:\a\1\s\build-tools\create-packs\Directory.Build.targets(150,5): error : No packages to create manifest from. [C:\a\1\s\build-tools\create-packs\Microsoft.Android.Sdk.proj]
Fix this by correctly setting the `$(OutputPath)` for this target to
find the signed .nupkg files that were previously downloaded.

[CI] Fix maestro manifest file generation

---

build-tools/create-packs/Directory.Build.targets

Use the new `--source` parameter when calling `dotnet workload
install`. This was not working previously, and the only option was to
generate a `NuGet.config` in the current working directory.

[build] use 'dotnet workload install --source'

---

build-tools/create-packs/Microsoft.Android.Ref.proj
src/Mono.Android/Mono.Android.csproj

Right now in .NET 6, you don't get any `<summary>` documentation on
Android APIs.
This adds files like `Mono.Android.xml` and `Java.Interop.xml` to the
Microsoft.Android.Ref pack to solve this issue.
I also fixed a place in `Mono.Android.csproj` that used `net6.0`, so
this will continue to work in a future .NET 7.

[One .NET] add missing API documentation

---

build-tools/automation/azure-pipelines.yaml
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Aot.targets
src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetAotArguments.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs

Fixed some issues that allows `$(EnableLLVM)` to work:
* `$(_LLVMPath)` needs to point to Mono's AOT pack that contains `opt`
and `llc`.
* We need to fill out `ld-name` and `ld-flags`.
* `ld-flags` needs some special workarounds in order for them to be
passed in correctly on .NET 6.
* Use space as a delimiter
* Escape spaces in paths
* Added `temp-path` parameter. This prevents the warning on Windows:
```
'rm' is not recognized as an internal or external command
```
I enabled tests around .NET 6 and LLVM.
All tests:
1. Were running on a [Google Pixel 5][0], and
2. Enabled two architectures, arm64 and x86, and
3. **AOT time** was average of 10 runs with `-c Release
-p:RunAOTCompilation=true`, with the `Activity: Displayed` time
4. **AOT+LLVM time** was average of 10 runs with `-c Release …

[One .NET] support $(EnableLLVM) with AOT

---

tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj
tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs

Some of our `PerformanceTest`'s are currently ignored due to:
Ignored : Xamarin.Android.Build.Tests.PerformanceTest.Build_No_Changes
Test requires an updated MSBuild.StructuredLogger
We ignored these tests in 304e6989. This was failing due to changes in
the `.binlog` file format.
I think we can remove this with the latest MSBuild.StructuredLogger.

Bump to MSbuild.StructuredLogger 2.1.500

---

build-tools/automation/azure-pipelines.yaml
build-tools/create-packs/vs-workload.in.props

Context: https://github.com/xamarin/yaml-templates/pull/124
VS PR produced: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/343772
The VS Insertion stage will now automatically open a PR against VS main
once approved.  The primary limitation with the current workflow is that
there is no good way to automatically create a PR against a branch other
than VS main.  This can be addressed at a later date, as we can still do
manual insertions into release branches during QB mode as needed

[ci] Opt in to auto .NET 6 VS pr creation

---

src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/EnvironmentHelper.cs
src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGenerator.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
src/monodroid/CMakeLists.txt
src/monodroid/jni/android-system.cc
src/monodroid/jni/application_dso_stub.cc
src/monodroid/jni/basic-android-system.cc
src/monodroid/jni/basic-utilities.cc
src/monodroid/jni/basic-utilities.hh
src/monodroid/jni/cpp-util.hh
src/monodroid/jni/cxx-abi/terminate.cc
src/monodroid/jni/cxx-abi/vector.cc
src/monodroid/jni/debug.cc
src/monodroid/jni/embedded-assemblies-zip.cc
src/monodroid/jni/embedded-assemblies.cc
src/monodroid/jni/embedded-assemblies.hh
src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/new_delete.cc
src/monodroid/jni/pinvoke-override-api.cc
src/monodroid/jni/strings.hh
src/monodroid/jni/xamarin-app.hh

C++ features:
* Use C++20 concepts to make compile-time correctness verification
stronger
* Use `std::vector` for dynamic heap buffers
* Use `std::array` for static stack buffers
* Use `std::unique_ptr` instead of the home-grown equivalent (also for
C-allocated memory)
* Use C++20 structure designators
Optimizations:
* Add string routines (`ends_with` and `find_last`) optimized for the
stack string types (derived from `string_base`)
* Count assemblies at the build time and pre-allocate enough memory (in
the form of `std::vector` instance) to store information about the
bundled assemblies, thus avoiding 2 allocations per assembly (one
`realloc` and one `malloc`) making the bundled assemblies loading
algorithm closer to O(1) instead of the previous O(n*2)
* Use character arrays instead of …

Use more standard C++ features + performance improvements

---

Configuration.props
Documentation/workflow/DevelopmentTips.md
build-tools/scripts/DotNet.targets
build-tools/scripts/maui.proj

We need a way for testing to install builds of .NET MAUI alongside a
local build of the Android workload.
This creates a new target such as:
msbuild Xamarin.Android.sln -t:InstallMaui -p:MauiVersion=6.0.100-rc.1.1351
You will need to lookup the version of the
`Microsoft.NET.Sdk.Maui.Manifest-6.0.100` package you want on [Azure
DevOps][0] or nuget.org.
[0]: https://dev.azure.com/azure-public/vside/_packaging?_a=package&feed=xamarin-impl%40Local&package=Microsoft.NET.Sdk.Maui.Manifest-6.0.100&protocolType=NuGet&version=6.0.100-rc.1.1351%2Bsha.3fbb791e7-azdo.5078933

[build-tools] setup a way to install .NET MAUI

---

src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/6140
`XA_TLS_PROVIDER` environment variable was used to set the TLS provider
for HttpClient in "legacy" Xamarin.Android.  NET6 and newer no longer
use that variable, so we can stop exporting it.

[NET6] Don't export the XA_TLS_PROVIDER envvar

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/6185
Context: https://github.com/dotnet/runtime/issues/56990
We should *only* default `UseSystemResourceKeys` to `true` if the
linker is enabled, so users get nice exception messages while
debugging.
If a user desires, they could retain long exception messages in
release builds by setting the value in the `.csproj`:
<UseSystemResourceKeys>false</UseSystemResourceKeys>

[One .NET] UseSystemResourceKeys=true only when linking

---

Directory.Build.props
Documentation/guides/HowToBranch.md
build-tools/scripts/XAVersionInfo.targets

Context: https://semvercompare.azurewebsites.net/?version=30.0.100-preview.7.110&version=30.0.100-ci.main.111
We have an issue currently where our version number on `main` is lower
than `preview.7`:
30.0.100-ci.main.111 < 30.0.100-preview.7.110
With this setup, `dotnet workload install` cannot possibly update to
`ci.main` versions (it always grabs latest) -- unless we somehow
constructed a NuGet feed without `preview.7` builds.
The only way for people to use `ci.main` builds at present is with
`maui-check --main`, because it uses
`dotnet workload update --from-rollback-file` to manually specify
versions. We want `maui-check` to be *optional* if possible.
The solution for `ci.main` versions is:
* Switch `xamarin-android/main` to `rc.1` *now*.
* When we branch for `rc.1`, we update `main` …

[One .NET] use rc.1 version number for main

---

tests/Mono.Android-Tests/System.Net/WebSocketTests.cs

The `echo.websocket.org` server used by the tests appears to no
longer be available.
Disable the tests for now until we figure out what service we
can use to replace `echo.websocket.org`

[Tests] Disable Mono.Android WebSocket tests

---

src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/EnvironmentHelper.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsLegacy.apkdesc
src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGenerator.cs
src/Xamarin.Android.Build.Tasks/Utilities/NativeAssemblyGenerator.cs
src/monodroid/jni/application_dso_stub.cc
src/monodroid/jni/cpp-util.hh
src/monodroid/jni/embedded-assemblies-zip.cc
src/monodroid/jni/embedded-assemblies.cc
src/monodroid/jni/embedded-assemblies.hh
src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/pinvoke-override-api.cc
src/monodroid/jni/strings.hh
src/monodroid/jni/util.cc
src/monodroid/jni/util.hh
src/monodroid/jni/xamarin-app.hh

Bundled assemblies are now stored on run time in an array pre-allocated
during build. This allows us to avoid any memory allocation during
startup. At the same time, a provision is made for adding more
assemblies than those counted and placed in the .apk during the build.
This may come handy when Xamarin.Android supports split
applications (with components placed in different APKs) and also as a
simple fail-safe feature should the build miscalculate something.
Debug information for assemblies is no longer registered when reading
the APK, but rather whenever an assembly load is requested by Mono.
Neither the assemblies nor their debug information are mmapped when
reading the APK anymore. This is done lazily when assembly load is
requested by Mono. Mapping of files after the startup phase …

Tune bundled assemblies

---

src/monodroid/jni/application_dso_stub.cc
src/monodroid/jni/embedded-assemblies.cc
src/monodroid/jni/embedded-assemblies.hh

Context: https://github.com/xamarin/xamarin-android/commit/69289d7811068aa56b39c58e99c69291b4e92259
69289d78 introduced the use of POSIX semaphore API to protect assembly
mmap code from race conditions.   However, it turns out that macOS
implementation of the semaphore is deprecated and always returns an
error, which in turn makes the Xamarin.Android runtime to [abort][0]
the application:
[2021-08-18 23:45:32.5] Renderer (error) >> ../../../jni/embedded-assemblies.hh:89 (prepare_for_multiple_threads): Failed to initialize assembly mapping semaphore. Function not implemented
[2021-08-18 23:45:32.5] Renderer >>
[2021-08-18 23:45:32.5] Renderer >> =================================================================
[2021-08-18 23:45:32.5] Renderer >> 	Native Crash Reporting
[2021-08-18 …

[mac] Fix failing Designer test

---

Directory.Build.props

Context: https://github.com/xamarin/xamarin-android/tree/release/6.0.1xx-rc1
We branched for .NET 6 `rc.1`, so we need to change main to `rc.2` now.

Bump version to 30.0.100-rc.2

---

Configuration.props
Documentation/workflow/DevelopmentTips.md
build-tools/automation/azure-pipelines.yaml
build-tools/create-packs/Directory.Build.targets
tests/Mono.Android-Tests/Directory.Build.targets

We now have the ability to push to the `dotnet6` feed that contains
the rest of the .NET 6 SDK Workload packages.  Begin pushing packages
to the `dotnet6` feed.
This should help simplify workload acquisition.
The `.nupkg` files containing the `.msi` installers used for
Visual Studio insertions will also now be pushed to this feed.

[ci] Push .NET 6 packages to dnceng dotnet6 feed

---

build-tools/scripts/XAVersionInfo.targets

I noticed our `release/6.0.1xx-rc1` branch was producing packs with a
strange version string:
30.0.100-ci.release-6-0-1xx-rc1.14
The regex performed on `$(_AndroidPackBranch)` strips all `/` characters
from the branch name, causing the release branch condition specified in
`$(_AndroidPackBranch.StartsWith('release/'))` to never be true.
Fix this condition by using the unaltered `$(XAVersionBranch)` property
value.

[build] Fix release branch package versions

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs

Context: https://github.com/dotnet/sdk/issues/19891
If you `dotnet new android` and `dotnet build` it without a
`NuGet.config` you hit:
error NU1102: Unable to find package Microsoft.AspNetCore.App.Runtime.linux-arm64 with version (= 6.0.0-rc.1.21417.2)
I found I could workaround the problem by removing `linux-*` packages
at a certain point during the build:
<Target Name="_RemoveLinuxFrameworkReferences"
AfterTargets="ProcessFrameworkReferences">
<ItemGroup>
<_ProblematicRIDs Include="linux-arm;linux-arm64;linux-x86;linux-x64" />
<PackageDownload Remove="Microsoft.AspNetCore.App.Runtime.%(_ProblematicRIDs.Identity)" />
<PackageDownload Remove="Microsoft.NETCore.App.Host.%(_ProblematicRIDs.Identity)" />
</ItemGroup>
</Target>
With this target in place, I can build projects without a …

[One .NET] exclude Microsoft.AspNetCore.App.Runtime.linux-* packages

---

build-tools/automation/yaml-templates/run-msbuild-device-tests.yaml
build-tools/create-packs/Microsoft.Android.Runtime.proj
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs

Adds the .pdb files associated with our framework assemblies to the .NET
runtime packs.  This will allow them to be fast deployed or included in
an .aab/.apk for Debug builds.  A couple of symbol related tests have
been updated to also check for Mono.Android.pdb.
I also noticed that the `SmokeTest` category was not running for the
`net6.0` MSBuildDeviceIntegration tests, as the emulator smoke test job
only runs against the `net472` test assembly.  This currently doesn't
matter as all `net6.0` smoke tests are ignored through other category
attributes, but this fix should be needed in the future.

[One .NET] Include symbol files in runtime packs

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs

Context: https://aster.cloud/2021/02/23/lets-be-explicit-about-our-intent-filters/
Fixes: https://github.com/xamarin/xamarin-android/issues/6196
> An important change is coming to Android 12 that improves both app
> and platform security. This change affects all apps that target
> Android 12.
>
> Activities, services, and broadcast receivers with declared
> intent-filters now must explicitly declare whether they should be
> exported or not.
For example:
<activity android:icon="@mipmap/icon" android:label="HelloWorld" android:name="example.MainActivity">
<intent-filter>
<action android:name="android.intent.action.MAIN" />
<category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
</activity>
Should become:
<activity android:exported="true" android:icon="@mipmap/icon" …

[Xamarin.Android.Build.Tasks] emit exported="true" for MainLauncher activities

---

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/Linux.Debian.cs
build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/Linux.Ubuntu.cs
build-tools/xaprepare/xaprepare/OperatingSystems/Linux.cs

The current Debian unstable distribution (codenamed "bookworm") no
longer contains any release version information in the `/etc/os-release`
file (the `VERSION` and `VERSION_ID` and `VERSION_CODENAME` fields were
removed) causing `xaprepare` to fail when running on this version of
Debian.
Fix the Debian/unstable version detection by looking for known release
codenames and faking the version number.

[Linux] Properly detect Debian bookworm/sid

---

src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
src/Xamarin.Android.Build.Tasks/Tasks/ValidateJavaVersion.cs

Testing latest xamarin-android/main, I got the error:
error XA0031: Java SDK 11.0 or above is required when using `<Project Sdk="Xamarin.Android.Sdk">`.
This seems out of date, we should just say `.NET 6 or higher` instead. I made a new resource key for this.

[Xamarin.Android.Build.Tasks] fix XA0031 message

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets

Since e7228252, API 31 is stable -- this requires JDK 11.
Unfortunately, if you build an app right now you hit:
> dotnet new android ; dotnet build
...
error XA0031: Java SDK 11.0 or above is required when using .NET 6 or higher.
You can fix the problem with:
dotnet build -p:MinimumSupportedJavaVersion=11.0.0
Let's make `$(MinimumSupportedJavaVersion)` default to `11.0` going
forward in .NET 6.

[One .NET] bump $(MinimumSupportedJavaVersion) to 11.0

---

Documentation/guides/OneDotNetBindingProjects.md
Documentation/guides/building-apps/build-properties.md
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
tests/CodeBehind/BuildTests/CodeBehindBuildTests.NET.csproj
tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj

Fixes: https://github.com/xamarin/xamarin-android/issues/6198
When migrating Xamarin.Android binding projects to .NET 6, one
difference is that `Resource.designer.cs` will be generated by .NET 6
class libraries.
There is not currently a way to turn this off, if you pass:
dotnet build -p:AndroidUseIntermediateDesignerFile=false
Then `Resources\Resource.designer.cs` will be generated instead. There
is no way to prevent this behavior, because `$(AndroidResgenFile)`
defaults to this value.
To solve cases where you *don't* want `Resource.designer.cs` at all:
1. Remove the `$(AndroidResgenFile)` default value.
2. Add a new `$(AndroidGenerateResourceDesigner)` MSBuild property,
that seems like it will be a better name for .NET 6.
3. `$(AndroidUseIntermediateDesignerFile)` is based on …

[One .NET] add $(AndroidGenerateResourceDesigner) property

---

src/Microsoft.Android.Templates/android-activity/Activity1.cs
src/Microsoft.Android.Templates/android-bindinglib/AndroidBinding1.csproj
src/Microsoft.Android.Templates/android/AndroidApp1.csproj
src/Microsoft.Android.Templates/android/MainActivity.cs
src/Microsoft.Android.Templates/androidlib/AndroidLib1.csproj
src/Microsoft.Android.Templates/androidlib/Class1.cs
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownProperties.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XASdkProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidLibraryProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsAndroidApplicationProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsXASdkProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/DotNet/MainActivity.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs

Context: https://github.com/dotnet/sdk/issues/19521
Fixes: https://github.com/xamarin/xamarin-android/issues/6075
Fixes: https://github.com/xamarin/xamarin-android/issues/6076
We need to make two sets of changes for C# 10:
1. Support "global usings". Our .NET 6 templates should have no
`using` statements at the top of `.cs` files.
2. Use `$(Nullable)` `enable` by default in project templates.
To test this, our .NET 6 MSBuild tests use `Nullable=enable` and
`ImplicitUsings=enable` by default and do not include `using`
statements in `.cs` files.
I've made a new `MainActivity.cs` for our .NET 6 MSBuild tests. The
"legacy" Xamarin.Android tests will use the original file.
Our default `global using` are:
```csharp
global using global::Android.App;
global using global::Android.Widget;
global …
```

[One .NET] support latest C# 10 language features

---

Documentation/guides/building-apps/build-properties.md
build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/apk-instrumentation.yaml
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.targets
src/Xamarin.Android.Build.Tasks/Tasks/AndroidApkSigner.cs
src/Xamarin.Android.Build.Tasks/Tasks/AndroidSignPackage.cs
src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
src/Xamarin.Android.Build.Tasks/Tasks/BuildApkSet.cs
src/Xamarin.Android.Build.Tasks/Tasks/Unzip.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildAssetsTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/CodeBehindTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EnvironmentContentTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.csproj
tests/MSBuildDeviceIntegration/Tests/BundleToolTests.cs
tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs

Fixes #6059
Users will probably want to target more than one App Store. Google is now requiring the `aab` format for 
Google Play Store uploads. Unfortunately this package format is not compatible with other stores. 
Users can build their app twice producing an `aab` for one build and `apk` for another, but we should
try to make this a bit easier. 
`bundle-tool` has the ability to create a universal apk from the `aab` file. So lets make use of that to 
generate one along side the `aab`. We are introducing a new property `AndroidPackageFormats`.
Under .net 6 this will have a value of `aab;apk` by default for Release builds, for Legacy it will be 
empty. 
If `AndroidPackageFormats` is specified and `AndroidPackageFormat` is empty we will use the 
values in `AndroidPackageFormats` to …

[One .NET] select defaults for App Bundles

---

build-tools/xaprepare/xaprepare/Steps/Step_DetermineAzurePipelinesTestJobs.cs
src/Microsoft.Android.Sdk.ILLink/PreserveLists/System.Private.CoreLib.xml

The linked runtime issue is fixed:
https://github.com/dotnet/runtime/issues/49073
We should be able to remove this now.

[Microsoft.Android.Sdk.ILLink] delete System.Private.CoreLib.xml

---

Documentation/guides/building-apps/build-properties.md
build-tools/installers/create-installers.targets
build-tools/xaprepare/xaprepare/Application/BuildInfo.cs
build-tools/xaprepare/xaprepare/Application/MonoJitRuntime.cs
build-tools/xaprepare/xaprepare/Application/Utilities.cs
build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs
build-tools/xaprepare/xaprepare/Steps/Step_Android_SDK_NDK.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetAotArguments.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/NdkUtilTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleLegacy.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsLegacy.apkdesc
src/Xamarin.Android.Build.Tasks/Utilities/NdkTools/NdkTools.cs
src/Xamarin.Android.Build.Tasks/Utilities/NdkTools/WithClang.cs
src/Xamarin.Android.Build.Tasks/Utilities/NdkTools/WithClangNoBinutils.cs
src/monodroid/CMakeLists.txt
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Aot.apkdesc
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Bundle.apkdesc
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release.apkdesc
tests/apk-sizes-reference/com.companyname.vsandroidapp-Signed-Release.apkdesc

Context: https://github.com/android/ndk/wiki/Changelog-r23#changelog
The most important changes for Xamarin.Android:
NDK r23 removes GNU Binutils and so we need to switch to using our
bundled copy of them.
Upstream changes:
* Includes Android 12 APIs.
* Updated LLVM to clang-r416183b, based on LLVM 12 development.
* [Issue 1047]: Fixes crash when using ASan with the CFI unwinder.
* [Issue 1096]: Includes support for [Polly]. Enable by adding `-mllvm -polly`
to your cflags.
* [Issue 1230]: LLVM's libunwind is now used instead of libgcc for all
architectures rather than just 32-bit Arm.
* [Issue 1231]: LLVM's libclang_rt.builtins is now used instead of libgcc.
* [Issue 1406]: Fixes crash with Neon intrinsic.
* Vulkan validation layer source and binaries are no longer shipped in the NDK.
The …

Add support for NDK r23.

---

src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf

Context: https://aka.ms/vs2019-and-jdk-11
Context: https://github.com/xamarin/xamarin-android/wiki/JDK-11-Warning
The XA0031 error will be generated when
`$(TargetFrameworkVersion)`=v12.0 and JDK 1.8 is detected, as JDK-11
is required for API-31; see also 8140991e, 26770284.
The problem is the XA0031 error message:
error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v12.0.
The error message implies that error can be fixed by installing JDK-11.
Which is correct: the XA0031 error *can* be fixed by installing JDK-11.
The problem is that *once JDK-11 is installed*, the Android Designer
breaks, as the Android Designer, as shipped in Visual Studio 16.11 and
Visual Studio for Mac 8.10, only works with JDK 1.8.
This can easily result in a scenario where a …

[Xamarin.Android.Build.Tasks] Improve XA0031 error

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ValidateJavaVersionTests.cs

Commit 658db25e inadvertently broke the
`ValidateJavaVersionTests.TargetFramework8_1_Requires_1_8_0()`
and `ValidateJavaVersionTests.BuildTools27_Requires_1_8_0()` tests,
by updating the XA0031 error message text.  Because these tests use
string.operator==() to compare the string contents, updating the
XA0031 message text broke the tests.
(This also means that the tests will fail if/when localizations are
ever actually used… 🤔)
Update these tests to instead use `string.StartsWith()`, as the *end*
of the XA0031 message was changed, not the beginning.

[tests] Fix TargetFramework8_1_Requires_1_8_0

---

src/monodroid/CMakeLists.txt

There are (at least?) two ways to resolve WinAPI references:
* by using the "legacy" library names, or
* by using the UWP library names.
Consider [`FlushViewOfFile()`][0]: the "legacy" library is
`kernel32.dll`, while the UWP library is
[`api-ms-win-core-memory-l1-1-2.dll`][1].
I don't know why one style should be preferred over the other.
Regardless, commit 6be4bdbcfd introduced use of `-lmincore`, which
uses the UWP library name style.
*This works*, and *has* worked since 2019.
However, certain internal tools don't "know about" the UWP names,
resulting in spurious "warnings" about having "calls to potentially
undocumented Windows functions".
Appease the tools by using `-lkernel32` and not `-lmincore`.
[0]: https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-flushvie …

[monodroid] Use -lkernel32, not -lmincore

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Resources/ApacheHttpClient.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/ResourceData.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj

Context: https://github.com/xamarin/xamarin-android/pull/6263#issuecomment-912671300
We have a "flaky" test:
Xamarin.Android.Build.Tests.BuildTest.MissingOrgApacheHttpClient("dx")
Xamarin.ProjectTools.FailedBuildException : Build failure:
...
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5):
error : Could not find file '/Users/runner/.nuget/packages/xamarin.googleplayservices.tasks/117.0.0/bsd2z4yg.43k'.
[/Users/runner/work/1/s/bin/TestRelease/temp/MissingOrgApacheHttpClientdx/UnnamedProject.csproj]
We have a `[Retry(5)]` on this, which doesn't seem to help.
To simplify what this is testing, we don't actually need to bring in
Google Play Services & Xamarin.Build.Download.
I could create an `ApacheHttpClient.cs` file that uses the …

[tests] simpler test case for org.apache.http.legacy

---

src-ThirdParty/System.Runtime.CompilerServices/UnconditionalSuppressMessageAttribute.cs

We have a copy of a few .NET 5.0 linker-related attributes for
`monoandroid10` and `netstandard2.0` usage of `Mono.Android.dll`.
In 8eb10dd4, I added a new one, but forgot to make it `internal` like
the rest. This could be problematic, as we don't want to expose it as
a public API.

[Mono.Android] make UnconditionalSuppressMessageAttribute internal

---

Documentation/guides/building-apps/build-properties.md

`class-parse` should not say it is experimental. Updated some of the wording around .NET 6.

[docs] update $(AndroidClassParser) and `class-parse` documentation

---

build-tools/automation/azure-pipelines.yaml

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5180358&view=logs&j=5b07041f-3ad2-50e1-dcc0-0b413b70a215&t=aaad43f1-f8e0-5332-447f-d87e37c943fe&l=125
Context: https://github.com/xamarin/yaml-templates/pull/135
Context: https://github.com/xamarin/yaml-templates/pull/134
The `Convert NuGet to MSI` job has been failing consistently since we
updated to a version of dotnet/arcade that introduced some changes to
run in parallel.  I've added a parameter to opt-out of parallelization
until those issues can be fixed.
Additionally, our .NET 6 packs will now be pushed to a public xamarin
`net6-maui-shipping` feed during the `VS Insertion` stage.

[ci] Don't convert nuget to msi in parallel

---

src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json

Context: https://github.com/dotnet/designs/blob/main/accepted/2020/workloads/workload-manifest.md#workload-definitions
Context: https://github.com/dotnet/runtime/blob/c21a701f59557aa55add95ea4b44f56d6dac46d6/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.json.in#L27
We should align our workloads with the list of supported platforms of the `microsoft-net-runtime-android` workload in dotnet/runtime.

[One .NET] specify platforms for android and android-aot workloads

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.AvailableItems.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Context: https://discord.com/channels/732297728826277939/732297837953679412/885897167900934175
Adding a single `.jar` file to a .NET 6 application project does not
produce bindings:
1. The file is added to `@(AndroidLibrary)` and
`@(AndroidJavaLibrary)` item groups, but not `@(EmbeddedJar)` or
`@(InputJar)`.
2. Any MSBuild targets related to C# binding generation are skipped.
I could reproduce this issue in a new test.
To solve the issue, we can add `.jar` files to `@(InputJar)` for all
.NET 6 application projects in the `_CategorizeAndroidLibraries`
MSBuild target.

[One .NET] fix binding generation for .jar in application projects

---

Documentation/guides/OneDotNetSingleProject.md
src/Microsoft.Android.Templates/android/AndroidApp1.csproj
src/Microsoft.Android.Templates/android/AndroidManifest.xml
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/SingleProjectTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://github.com/dotnet/maui/issues/1662
We previously were mapping new MSBuild properties to values in
`AndroidManifest.xml`:
* `$(AndroidVersionCode)` -> `android:versionCode`
* `$(ApplicationVersion)` -> `android:versionName`
To be more consistent with other platforms, we're reworking this to be:
* `$(ApplicationVersion)` -> `android:versionCode`
* `$(ApplicationDisplayVersion)` -> `android:versionName`
If we force `$(ApplicationVersion)` to be an integer, you can use the
same values on all platforms dotnet/maui supports. We no longer need
an Android-specific `$(AndroidVersionCode)`.
We also need to consider the `$(Version)` property that influences
`$(AssemblyVersion)`, `$(FileVersion)`, and `$(InformationalVersion)`.
We can simply set `$(Version)` when …

[One .NET] rework $(ApplicationVersion) and $(ApplicationDisplayVersion)

---

build-tools/automation/azure-pipelines.yaml

Context: https://github.com/xamarin/yaml-templates/blob/18d9a2207276165a259da3681cb13250dc2f4d0a/vs-insertion/stage/v1.yml#L62-L84
Based on our existing manual approval for VS insertions, let's add an additional manual approval step to push packages to NuGet.org.
On .NET 6 release days, we will be able to go to a particular build and approve it. This should push packages to NuGet.org.
The steps for pushing and approval need to be in different jobs, due to:
'wait_for_nuget_approval' is a server job, but contains task 'DownloadPipelineArtifact' which can only run on agents.
'wait_for_nuget_approval' is a server job, but contains task 'NuGetCommand' which can only run on agents.

[build] add manual approval to push to NuGet.org

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/6280
.NET 6 projects have the following issue:
1. Build a .NET 6 project with a `.jar` to create a C# binding.
2. Delete the `.jar` completely & build again.
3. The C# types remain in the assembly!
We have the following expression to decide when C#-binding related
targets should be completely skipped:
Condition=" '$(UsingAndroidNETSdk)' != 'true' Or '@(InputJar->Count())' != '0' Or '@(EmbeddedJar->Count())' != '0' Or '@(LibraryProjectZip->Count())' != '0' "
This allows the targets to run for "legacy" Xamarin.Android binding
projects, and .NET 6 project when certain item groups are non-empty.
We were missing this condition on the `AddBindingsToCompile` MSBuild
target!
<Target Name="AddBindingsToCompile" …

[One .NET] conditionally add `generated\*\*.cs` to @(Compile)

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

The [Android SDK Tools package][0] is deprecated, replaced by the
[Android SDK cmdline-tools package][1]:
> This SDK Tools package is deprecated and no longer receiving
> updates. Instead, please use the new command-line tools package.
The Android SDK Tools package hasn't seen an update since 2017-Sep.
We do have support for the cmdline-tools package, e.g. 92efdccb,
but the *default* `$(LintToolPath)` value was still using the
Android SDK Tools package, because:
1. The [default `$(AndroidCommandLineToolsVersion)` value][2] is
`2.1`, which isn't installed anywhere (current "latest" is 5.0).
2. The `<ResolveAndroidTooling/>` task would only check
`$(AndroidSdkDirectory)\cmdline-tools\$(AndroidCommandLineToolsVersion)`;
if that didn't exist, it would eventually try the Tools dir.
The …

[Xamarin.Android.Build.Tasks] Fix default $(LintToolPath)

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/6284
Building an Android application with:
[Activity(
MainLauncher = true,
Exported = true,
//...
Fails with:
Xamarin.Android.Common.targets(1424,3): error XAGJS7009: System.InvalidOperationException: Duplicate attribute.
at System.Xml.Linq.XElement.AddAttributeSkipNotify(XAttribute a)
at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
at System.Xml.Linq.XContainer.Add(Object content)
at Xamarin.Android.Tasks.ManifestDocument.AddLauncherIntentElements(XElement activity)
at Xamarin.Android.Tasks.ManifestDocument.<>c__DisplayClass99_0.<ActivityFromTypeDefinition>b__1(ActivityAttribute aa, XElement element)
at Xamarin.Android.Tasks.ManifestDocument.ToElement[TAttribute](TypeDefinition type, String name, Func`2 parser, …

[Xamarin.Android.Build.Tasks] don't add exported="true" if already present

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/FilterAssembliesTests.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5202425&view=ms.vss-test-web.build-test-results-tab&runId=25843494&resultId=100119&paneView=debug
I saw the test failure:
System.Threading.Tasks.TaskCanceledException : A task was canceled.
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Xamarin.Android.Build.Tests.FilterAssembliesTests.<DownloadFromNuGet>d__4.MoveNext() in /Users/builder/azdo/_work/2/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/FilterAssembliesTests.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
at …

[tests] remove HttpClient code in FilterAssembliesTests

---

src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf

`XA0031` doesn't include a download link. Let's make the error message more helpful.

[Xamarin.Android.Build.Tasks] include openjdk link in error messages

---

src/Mono.Android/Android.Runtime/ResourceIdManager.cs
src/Mono.Android/Java.Interop/JavaObjectExtensions.cs
src/Mono.Android/Java.Interop/TypeManager.cs
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MarkJavaObjects.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Context: https://github.com/xamarin/xamarin-android/issues/5652
There are two remaining linker warnings when building with:
> dotnet build -c Release -p:SuppressTrimAnalysisWarnings=false
...
src\Mono.Android\Android.Runtime\ResourceIdManager.cs(37,6): warning IL2026: Android.Runtime.ResourceIdManager.GetResourceTypeFromAssembly(Assembly): Using method 'System.Reflection.Assembly.GetType(String)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed.
src\Mono.Android\Java.Interop\JavaObjectExtensions.cs(136,4): warning IL2026: Java.Interop.JavaObjectExtensions.GetHelperType(Type,String): Using method 'System.Reflection.Assembly.GetType(String)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when …

[One .NET] fix more Mono.Android.dll linker warnings

---

Directory.Build.props

Context: https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/
Context: https://semvercompare.azurewebsites.net/?version=31.0.101-preview.9.1&version=31.0.100-rc.1.12
.NET MAUI (and underlying optional .NET workloads) will be in a
"preview" status until Q2 2022.
Going forward in xamarin-android/main, our version number will be
`31.0.101-preview.9.*`.
We need to bump to 101, so the version number will be higher than the
currently released `31.0.100-rc.1.12`.

[One .NET] use preview.9 version number

---

src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs
tests/Mono.Android-Tests/Java.Interop-Tests/Java.Interop-Tests.NET.csproj
tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj
tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidClientHandlerTests.cs

Context: https://github.com/dotnet/runtime/commit/01c4028969fafb927762477d6991c483f3b3cc5c
I found usage of the `ServerCertificateCustomValidationCallback`
property triggered ILLink warnings:
warning IL2037: System.Net.Http.HttpClientHandler.GetServerCertificateCustomValidationCallback(): No members were resolved for 'get_ServerCertificateCustomValidationCallback'.
This would also fail at runtime.
Going forward:
* Add a test that sets `ServerCertificateCustomValidationCallback`.
* Add `IL2037` to `$(WarningsAsErrors)`
I also found a bug in `Java.Interop-Tests.NET.csproj`, it fails to
build for me:
external\Java.Interop\tests\Java.Interop-Tests\obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.cs(4,12): error CS0579: Duplicate …

[Mono.Android] add missing property in AndroidMessageHandler

---

build-tools/automation/azure-pipelines-nightly.yaml

Context: https://docs.microsoft.com/azure/devops/pipelines/yaml-schema
Our nightly build is currently building all `release/*` branches.
Let's update this to ignore past preview branches.
Let's also update the VS branches this runs against.

[build] update nightly CI triggers

---

Configuration.props

Context: https://github.com/xamarin/xamarin-android/pull/6300
Context: https://github.com/xamarin/java.interop/issues/883
Changes: http://github.com/xamarin/xamarin-android-tools/compare/9b658b29bd41157151f5515619d0d90dc062563d...a5194e93498e7f12225d87e2811415a45f742116
* xamarin/xamarin-android-tools@a5194e9: [Xamarin.Android.Tools.AndroidSdk] Downgrade build-tools to API-30
* xamarin/xamarin-android-tools@440e6be: [Xamarin.Android.Tools.AndroidSdk] Update SDK component for API-31 (#134)
Note: while this xamarin-android-tools bump updates the Android SDK
[Platform Tools][0] version to 31.0.3, we are *not* updating
`$(XAPlatformToolsVersion)` to 31.0.3.  As such, there will be a
mismatch between what we build xamarin-android against, vs. the
default suggested platform-tools package …

Bump to xamarin/xamarin-android-tools/main@a5194e93

---

.external

Changes: https://github.com/xamarin/monodroid/compare/0156d4e51523aba1c11babd2612328e9ce2525e6...07a99d799289e90870243312ffd16f9e3187ec52
* xamarin/monodroid@07a99d799: Bump to xamarin/androidtools/main@05496806 (#1227)

Bump to xamarin/monodroid/main@07a99d79

---

Directory.Build.props

Context: https://github.com/xamarin/xamarin-android/blob/d61aae7f120f9c39c2186908fb3cd791b3bde871/Documentation/guides/HowToBranch.md
Context: https://github.com/xamarin/xamarin-android/pull/6312
Context: https://github.com/xamarin/xamarin-android/tree/release/6.0.1xx-preview9
I branched because we saw "rtm" builds coming from dotnet/installer
this morning.
Going forward, our version number will be slightly confusing:
1. .NET 6 RC2 == 31.0.101.preview.9
2. .NET 6 RTM == 31.0.101.preview.10

[build] bump xamarin-android/main to preview.10

---

Documentation/guides/HowToBranch.md
build-tools/automation/azure-pipelines-nightly.yaml

`release/6.0.1xx-rc2` is going to be named `release/6.0.1xx-preview9`
for the dotnet/maui, xamarin-android, and xamarin-macios repos. I
renamed the branch in xamarin-android.
We need to update the nightly CI triggers. I added this to the
`HowToBranch.md` doc as well.

[build] update nightly CI triggers, again

---

src/Xamarin.Android.Build.Tasks/Tasks/GetAndroidPackageName.cs
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/6302
If you try to use both `$(ApplicationId)` and `@package` in
`AndroidManifest.xml` at the same time, you hit errors during
deployment:
Xamarin.Android.Common.Debugging.targets(611,5): error XA0132: The package was not installed. Please check you do not have it installed under any other user.
If the package does show up on the device, try manually uninstalling it then try again.
You should be able to uninstall the app via the Settings app on the device.
From the spec, the `AndroidManifest.xml` is *supposed* to be preferred.
I found the `<GetAndroidPackageName/>` MSBuild task is accidentally
preferring the `$(ApplicationId)` MSBuild property. I reordered the
logic and only use the property when no value is found in the …

[One .NET] fix $(ApplicationId) and //manifest@package at the same time

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs

When we have unit tests running in parallel we sometimes get issues
where the method `GetMaxInstalledPlatform` returns a lower API level
than the max installed. This is because multiple tests are calling
the method at the same time. As a result they overwrite each other
as they are both scanning the directories. The results in some tests
getting a lower API level than expected becuase the `maxInstalled`
field has a value.

[Xamarin.Android.Build.Tests] Fix GetMaxInstalledPlatform threading.

---

build-tools/create-vsix/create-vsix.csproj
build-tools/create-vsix/create-vsix.targets
build-tools/create-vsix/source.extension.vsixmanifest

Context: https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022#extensions-without-running-code
Our .vsix installer can't be installed "on top" of VS2022.  This is
something we'll want to continue to support for testing purposes, and
for our OSS installer.  Adding an `amd64` installation target and
updating VS SDK and Tools package reference versions should fix this.
The workaround from commit 4799ea2 has been removed as it no
longer appears to be needed.

[build] Add standalone VS2022 support to vsix

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs

Context: https://github.com/xamarin/xamarin-android/issues/6308
Context: https://github.com/xamarin/monodroid/commit/2e93b630e47701dae56f426fe5934846d571832b
When a device or emulator is selected during a build with Fast
Deployment enabled, a single `$(RuntimeIdentifier)` is selected. This
gives us a reasonable speedup for the build.
One place we can do more is the `<ProcessAssemblies/>` MSBuild task.
Add a "fast path", where we don't need to read the MVIDs from every
assembly. We can simply loop over the assemblies and set required item
metadata.
I also made various changes to refactor the `<ProcessAssemblies/>` so
there is more shared helper methods within the task, etc.
An incremental build of a `dotnet new android` project with no changes:
Two RIDs:
81 ms  ProcessAssemblies …

[One .NET] add a single-RID "fast path" for <ProcessAssemblies/>

---

build-tools/automation/azure-pipelines-oss.yaml
build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/commercial-build.yaml
build-tools/xaprepare/xaprepare/Steps/Step_PrepareExternalJavaInterop.Unix.cs

Context: https://twitter.com/KirillOsenkov/status/1440192351528374279
Our verbose logging is getting a little out of control.  The `make jenkins` log is ~870 MB and can no longer be viewed in the AzDO UI.
Remove `V=1` from our invocations, which removes `/v:diag`.
Timings aren't stable across build agents so numbers aren't very accurate, but there are definitely improvements:
- Log file of `make jenkins` went from 870 MB to 32 MB
- Build time of `make jenkins` went from 42:49 to 34:43
Full logs are still available in the `.binlog`'s we already produce and place in artifacts.

[ci] Make logging less verbose

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets

Context: https://docs.microsoft.com/visualstudio/msbuild/msbuild-task
During .NET 6 builds, we run a portion of the build in an `<MSBuild/>`
task nested build per-`$(RuntimeIdentifier)`.
The work in the nested build is done in separate directories for each
RID, so we should be able to do the work in parallel for:
* `ILLink`
* AOT compilation
We have to use the `%(AdditionalProperties)` item metadata for the
list of projects (which is the same project) passed to the
`<MSBuild/>` task.
One point of concern is if you have a property at the end of
`%(AdditionalProperties)`:
_OuterIntermediateOutputPath=$(IntermediateOutputPath);
The `;` will be included in the path if this is the last property!
I reworked the `$(_AdditionalProperties)` so there will not be any
trailing `;` that could cause …

[One .NET] run per-RID builds in parallel

---

Documentation/guides/messages/xa0031.md

Two things fixed here:
1. XA0031 can also happen if no JDK was installed at all (while the previous text only mentioned differing or incompatible versions, as if Windows included a JDK by default?).
2. When the user gets this error for the first time, it's not clear if he has to download the Java SDK manually herself from the Oracle website or not. A Visual Studio user might think that this can be done under the hood by Visual Studio (in the same way that Android SDKs are downloaded and installed automatically within Visual Studio), but it is not the case for the Java SDK so it's better to mention the Oracle website here as a hint.

Clarify XA0031

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

We set `Builder.UseDotNet` for `Xamarin.Android.Build.Tests` tests in a static `SetUp ()` constructor in an NUnit `[SetUpFixture]`.  However this is not getting set before it is consumed by NUnit for test parameters.
For example:
```
// BuildTest.cs
public void BuildBasicApplication ([ValueSource (nameof (SupportedTargetFrameworks))] string tfv, [Values (true, false)] bool isRelease)
```
is being evaluated as `UseDotNet=false`, and thus running this test on all TFV's for .NET 6, when it should only be run for the latest TFV.
By changing `Builder.UseDotNet` to an evaluated property-getter, we can ensure that it is always correct for running on .NET 5+.
The net result of this change is that the `MSBuild - One .NET - Node-1` test suites run 24 fewer tests for both Windows and Mac.

[Xamarin.Android.Build.Tests] Ensure UseDotNet is set before NUnit evaluates test parameters.

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-msbuild-mac-tests.yaml
build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AidlTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildAssetsTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DeferredBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/GenerateLibraryResourcesTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/GeneratePackageManagerJavaTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/GetDependenciesTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/KeyToolTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/MakeBundleNativeCodeExternalTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/NdkUtilTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/RemoveDirTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ResolveMonoAndroidSdksTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ResolveSdksTaskTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ValidateJavaVersionTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

In order to have sub-2 hour builds, we should endeavor to keep the `Mac Build` stage under an hour, and each individual Test job under an hour.
The Mac MSBuild tests take considerably longer than the Windows tests, breaking the 1 hour limit:
This is because they run on the public `Azure Pipelines` Mac images, which are slower than our private Android-specific Windows agents.  The good news is that there are an ~infinite number of them, which means we can simply split our tests across more agents.
However, our Android-specific Windows agents **are** limited in number, so we do not want to split the tests any further for them.  By doubling our Mac agents from 3 to 6, we can simplify the logic to keep Windows at 3 nodes.  Each Windows node runs 2 categories:
- Windows Node 1 runs `[Category …

[ci] Run Mac MSBuild tests on 6 nodes instead of 3.

---

build-tools/automation/azure-pipelines.yaml

Context: https://eng.ms/docs/cloud-ai-platform/developer-services/one-engineering-system-1es/1es-docs/1es-hosted-azure-devops-pools/1es-hosted-azuredevops-agents
We've been tasked with migrating away from all scale set agent pools
to a new 1ES service.  The `VSEngSS-MicroBuild2019` pools are being
retired and replaced by `VSEngSS-MicroBuild2019-1ES`.

[ci] Use 1ES MicroBuild pool

---

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs
src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

We found an incremental build in a `dotnet new android` app with C#
code changes has this duration:
100 ms  LinkAssembliesNoShrink                     1 calls
It turns out we don't actually need to run `<LinkAssembliesNoShrink/>`
against the "main" assembly in .NET 6. After passing in
`$(TargetName)` and simply copying the file, this time improved to:
9 ms  LinkAssembliesNoShrink                     1 calls
This change should improve incremental C# changes by ~91ms in `dotnet
new android` projects.
In "legacy" Xamarin.Android, it still seems possible for an
application project to reference a class library with a higher
`$(TargetFrameworkVersion)`. So we cannot apply this optimization for
Xamarin.Android.

[Xamarin.Android.Build.Tasks] <LinkAssembliesNoShrink/> can skip the main assembly

---

Configuration.props
Documentation/release-notes/bundletool-1.8.1.md

Context: https://github.com/google/bundletool/releases/tag/1.8.1
Changes: https://github.com/google/bundletool/compare/1.4.0...1.8.1
Fixes: https://github.com/xamarin/xamarin-android/issues/6354
`dotnet build -c Release -t:Install` fails on an API-31 emulator with:
[BT : 1.4.0] error : Error retrieving device density. Please try again.
Updating `bundletool` with the fix:
Android12 emulator fails due to 'Error retrieving device density'
https://github.com/google/bundletool/issues/241

Bump to google/bundletool/main@5ba6c05

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AndroidLibraries.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs

Building a `dotnet new maui` app, I noticed a lot of time spent in
`<ConvertResourcesCases/>`:
1346 ms ConvertResourcesCases
Reviewing the build logs, I found `%(AndroidSkipResourceProcessing)`
was set to `false` for all AndroidX `.aar` files. This should not be
the case, because we don't need to fix up casing in these libraries.
After review, I found a bug in the `_ResolveAars` MSBuild target:
<AndroidAarLibrary Include="@(_AarFromLibraries)" Exclude="@(AndroidAarLibrary)" Pack="false" />
<AndroidAarLibrary Update="@(_AarFromLibraries)" AndroidSkipResourceProcessing="false" />
The second update was setting `%(AndroidSkipResourceProcessing)` on
libraries it shouldn't have.
I collapsed these two item groups into a single `Include` and this
fixes the issue.
I could reproduce the problem by …

[One .NET] fix for %(AndroidSkipResourceProcessing)

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-msbuild-device-tests.yaml
tests/MSBuildDeviceIntegration/Tests/AotProfileTests.cs
tests/MSBuildDeviceIntegration/Tests/BundleToolTests.cs
tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
tests/MSBuildDeviceIntegration/Tests/DeleteBinObjTest.cs
tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs
tests/MSBuildDeviceIntegration/Tests/MonoAndroidExportTest.cs
tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs
tests/MSBuildDeviceIntegration/Tests/SystemApplicationTests.cs
tests/MSBuildDeviceIntegration/Tests/UncaughtExceptionTests.cs
tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs

Much like the `MSBuild` tests used to, the `MSBuild with Emulator` tests can take multiple hours.  
Like we did for `MSBuild` tests, the solution is to parallelize them across multiple build agents.  This PR splits each test suite across 3 nodes using the same `[Category ("Node-X")]` hack, bringing the total wall-time of running each suite under an hour.

[ci] Split MSBuildDeviceIntegration tests across multiple build agents.

---

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/6215
Context: https://android-developers.googleblog.com/2021/10/android-12-is-live-in-aosp.html
Google has marked `android-31` "final", and has provided the `sources-31_r01.zip` file that we need to build our updated API documentation from.  Update `xaprepare` to provision this new documentation info for us.

[Mono.Android] Use android-31 sources for generating docs.

---

build-tools/automation/azure-pipelines.yaml

In https://github.com/xamarin/xamarin-android/pull/6369 we removed .NET Core 3.1 from our CI.  However, it is still needed by the `pkg` notarization step, which only runs on `main`/`release` branches so it didn't show as a failure on the initial PR.
Add .NET Core 3.1 back for this CI job only.

[ci] PKG notarization still needs .NET Core 3.1.

---

build-tools/scripts/RoslynAnalyzers.projitems

The nightly pipeline is failing with:
```
/Users/builder/azdo/_work/4/s/xamarin-android/build-tools/scripts/RoslynAnalyzers.projitems(3,14): error MSB4113: Specified condition " $(XAShouldAnalyzeAssembly) " evaluates to "" instead of a boolean. [/Users/builder/azdo/_work/4/s/xamarin-android
```
We should update this comparison to a string compare so that it still works if `$(XAShouldAnalyzeAssembly)` doesn't get set at all.

[ci] Fix nightly ci by comparing 'XAShouldAnalyzeAssembly' as string instead of bool

---

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/SingleProjectTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/6384
Fixes: https://github.com/dotnet/sdk/issues/21614
In .NET 6, you can't currently put `versionCode` in
`AndroidManifest.xml`, as it is always overwritten by a default:
<ApplicationVersion Condition=" '$(ApplicationVersion)' == '' ">1</ApplicationVersion>
We should actually check if the value is present in
`AndroidManifest.xml` and only set if blank.
The other new MSBuild properties don't appear to suffer from this
problem:
* `$(ApplicationId)`
* `$(ApplicationTitle)`
* `$(ApplicationDisplayVersion)`
This is because we don't default these properties to a value when they
are blank.
I added a new test for this scenario.

[One .NET] prefer /manifest/@android:versionCode

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs

Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1334066
In traditional Xamarin.Android, a File -> New binding project emits
the warning:
BINDINGSGENERATOR warning BG8601: No '<package>' elements found.
This happens until you add a Java library to actually bind.
The warning doesn't happen in .NET 6 due to the `Condition`:
<Target Name="_SetAndroidGenerateManagedBindings"
Condition=" '$(UsingAndroidNETSdk)' != 'true' Or '@(InputJar->Count())' != '0' Or '@(EmbeddedJar->Count())' != '0' Or '@(LibraryProjectZip->Count())' != '0' ">
<_AndroidGenerateManagedBindings>true</_AndroidGenerateManagedBindings>
</Target>
The `$(UsingAndroidNETSdk)` check makes the value always true in
traditional Xamarin.Android. I think we can just remove this check, as …

[Xamarin.Android.Build.Tasks] skip C# binding-related targets

---

build-tools/installers/create-installers.targets
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Extensions.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj

Commit 3e6a6232d904acfc95017eeae58408787b0f8dc9
Context: https://discord.com/channels/732297728826277939/732297837953679412/898675755779768330
An unfortunate unexpected breakage occurred due to commit 3e6a6232:
the version of `Java.Interop.dll` changed -- which we *should* have
expected but completely overlooked & forgot -- which in turn meant
that *everything* which depends upon it -- which is everything --
started breaking due to the version change, e.g.
error CS1705: Assembly 'Microsoft.Maui' with identity 'Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
uses 'Java.Interop, Version=0.1.6.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
which has a higher version than referenced assembly
'Java.Interop' with identity 'Java.Interop, Version=0.1.2.0, …

[Xamarin.Android.Build.Tasks] Remove Java.Interop.dll reference.

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets

Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1413756
Fixes: https://github.com/xamarin/xamarin-android/issues/6353
The API 31 emulator no longer has 32-bit images and the x86_64 image
has dropped support for 32-bit architectures:
> adb shell getprop | grep cpu
[ro.product.cpu.abi]: [x86_64]
[ro.product.cpu.abilist]: [x86_64,arm64-v8a]
[ro.product.cpu.abilist32]: []
[ro.product.cpu.abilist64]: [x86_64,arm64-v8a]
Compared to an API 30 x86_64 emulator:
> adb shell getprop | grep cpu
[ro.product.cpu.abi]: [x86_64]
[ro.product.cpu.abilist]: [x86_64,x86,arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [x86,armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [x86_64,arm64-v8a]
The problem is our default RIDs are:
<RuntimeIdentifiers Condition=" '$(RuntimeIdentifier)' == …

[One .NET] specify all RIDs by default

---

build-tools/automation/azure-pipelines.yaml

The binlogs and extra test artifacts produced by the designer test jobs
will now only be uploaded when a task in the job fails.

[ci] Only upload designer test logs on failure

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props

Context: https://github.com/dotnet/maui/pull/3018#pullrequestreview-792369556
In order for the .NET MAUI workload to properly implement implicit
global usings:
1. The .NET MAUI workload will add many `@(Using)` entries that
conflict with each platform's APIs.
2. We need *something* to identify `@(Using)` is for a specific
platform, so we can use a new `%(Platform)` metadata for this.
3. Late in .NET MAUI's MSBuild targets, we can do:
```xml
<ItemGroup Condition=" '$(UseMaui)' == 'true' and ('$(ImplicitUsings)' == 'true' or '$(ImplicitUsings)' == 'enable') ">
<Using Remove="@(Using->HasMetadata('Platform'))" />
</ItemGroup>
```
In .NET 7, we might have a nicer design around this, but for now this
is the plan for .NET 6.

[One .NET] add %(Platform) to any global @(Using)

---

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs

Changes: https://github.com/android/ndk/wiki/Changelog-r23#r23b
The most important changes for us:
* Bumped compiler toolchain to LLVM 12
* Uses universal binaries on M1 Macs
* Assorted cmake fixes

Bump to NDK r23b

---

build-tools/xaprepare/xaprepare/xaprepare.csproj

Context: https://github.com/xamarin/xamarin-android/pull/4294
We enabled NRT warnings for `xaprepare` in https://github.com/xamarin/xamarin-android/pull/4294, however we never fixed the warnings and they pollute our build logs.
By switching to `<Nullable>annotations</Nullable>` we can continue to use NRT syntax to annotate our code, but warnings will not be produced when null safety cannot be proven by the compiler.
Reduces warnings building `xaprepare` from 169 to 21.

[xaprepare] Suppress NRT warnings.

---

Documentation/guides/HowToBranch.md
build-tools/automation/azure-pipelines-nightly.yaml

We noticed the Xamarin.Android nightly job is running against old
branches like:
* `release/6.0.1xx-preview3`
* `release/6.0.1xx-preview4`
* `release/6.0.1xx-preview5`
* `release/6.0.1xx-preview6`
* `release/6.0.1xx-preview7`
xamarin-android/main does *not* have a schedule setup for these
branches... Meaning, we would have to go update the trigger on each
branch?
Instead, let's define the schedule in Azure DevOps UI. I've updated
`HowToBranch.md` with the new instructions.
I removed the schedule from `azure-pipelines-nightly.yaml`. After this
is merged, we may have to cherry-pick the schedule removal to each
branch. After this is merged, we'll find out.

[ci] override schedule for Xamarin.Android nightly

---

Makefile

We've seen a couple of PR builds fail recently with the following:
"/Users/builder/azdo/_work/2/s/xamarin-android/build-tools/xaprepare/xaprepare/xaprepare.csproj" (Build target) (2:3) ->
(GetReferenceAssemblyPaths target) ->
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1232,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/Users/builder/azdo/_work/2/s/xamarin-android/build-tools/xaprepare/xaprepare/xaprepare.csproj]
This appears to only be happening when the Mono installation on disk is
too old to support .NET 6.  We can fix this by using `dotnet` to update …

[build] Use `dotnet run` to update Mono

---

src/monodroid/jni/basic-utilities.cc
src/monodroid/jni/basic-utilities.hh
src/monodroid/jni/cpp-util.hh
src/monodroid/jni/logger.cc
src/monodroid/jni/strings.hh
src/monodroid/jni/xxhash.hh

* Rewrite `BasicUtilities::monodroid_strsplit`
Instead of reallocating the vector on each new token, pre-calculate
the number of tokens and allocate enough memory for the entire
vector at once.
* Rewrite `init_logging_categories`
Eliminate memory allocation by not using `monodroid_strsplit`,
instead do all the processing using on-stack strings and their
tokenizer.  Also, replace the `CATEGORY` preprocessor macro with a
template function.

A handful of tiny improvements for the native runtime

---

Documentation/guides/messages/il6200.md
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs
src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs

Context: https://github.com/dotnet/linker/issues/2333
In testing 10b97206, I found that the XA2000 warning didn't actually
appear when consuming a class library with `AppDomain` usage in .NET 6.
After some discussion on dotnet/linker#2333, the only way to log a
warning from a custom trimmer step is:
Context.LogMessage (MessageContainer.CreateCustomWarningMessage (Context, msg, 6200, new MessageOrigin (), WarnVersion.ILLink5))
Where the code must be 6001 or higher, and it will automatically be
prefixed with `IL`. I mapped `XA2000`, to `IL6200`, to just have the
number *similar*? We can chooose something else, let me know.
Once the warning was working, I got *many* warnings for the same
assembly. It turns out we were emitting it in .NET 6 for every type!
protected void ProcessType …

[illink] fix XA2000 warning, again

---

build-tools/automation/yaml-templates/variables.yaml

Bumps the system .NET 6 install from RC 2 to the official stable build.

[ci] Build with stable .NET 6 release

---

src/Mono.Android/Mono.Android.targets

A `frameworks.xml` file will now be passed to `mdoc.exe` when updating
external API docs.  This file contains the metadata required to find
and update or create [FrameworksIndex files][0].
The version of `Mono.Android.dll` used to generate docs will no longer
be passed to `mdoc.exe`.  Instead, it will be copied to the relative
`%(Source)` directory described in `frameworks.xml` to be resolved
automatically.
The `mdoc` package version has also been fixed, and we'll now use
`5.8.0` instead of `5.0.0.25`.
Includes the following Java.Interop update:
https://github.com/xamarin/java.interop/compare/dcdcce13220d98a848ae3d3598b9b87b22a62c84...087684a70bb71a84c0afb7423c27b50bafb74fb2
[0]: https://github.com/xamarin/android-api-docs/tree/cd414a93057b6f61afcdd3db6ff44391fb166246/docs/Mono.Android/en/ …

[Mono.Android] Pass frameworks.xml file to mdoc

---

src/Mono.Android/Mono.Android.targets

The `--lang` parameter will now be passed to `mdoc.exe` when updating
external API docs.  This should fix a `<TypeSignature />` ordering
issue.  If this parameter is not specified, some `F#` doc entries will
end up being listed before `C#` entries when updating existing docs that
contain `F#` data.

[Mono.Android] Update F# API docs

---

src/Mono.Android/metadata

In https://github.com/xamarin/xamarin-android/pull/6452  we did not add the required per-API-level `metadata` that enables the `ApiSince` (and thus `[SupportedOSPlatform]`) annotations.  This means that these APIs show as being available on all API levels.
Adding the required `metadata` produces the expected annotations:
```csharp
// Metadata.xml XPath method reference: path="/api/package[@name='android.app']/class[@name='WallpaperInfo']/method[@name='shouldUseDefaultDeviceStateChangeTransition' and count(parameter)=0]"
[global::System.Runtime.Versioning.SupportedOSPlatformAttribute ("android32.0")]
[Register ("shouldUseDefaultDeviceStateChangeTransition", "()Z", "", ApiSince = 32)]
public unsafe bool ShouldUseDefaultDeviceStateChangeTransition ()
{
const string __id = …
```

[Mono.Android] Enable api-since metadata for API-32.

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Aot.targets
src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetAotArguments.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetAotAssemblies.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Profiled-Aot.apkdesc

When using the built-in profiles for Profiled AOT, one drawback is the
user's code isn't AOT'd. We only AOT types that are called in the BCL,
`Java.Interop.dll`, `Mono.Android.dll`, etc.
To make this better, we can full AOT the "main" assembly. Most code in
users' main assembly would likely get called on startup. This should
have a minor impact to `.apk` size, but gain us a better startup boost
by default.
When testing, I can see more methods AOT'd:
11-11 09:01:01.441 16386 16386 D Mono    : AOT: FOUND method foo.MainActivity:OnCreate (Android.OS.Bundle) [0x7c050e8e20f0 - 0x7c050e8e213b 0x7c050e8e2673]
A `dotnet new android` app, built with:
> dotnet build -c Release -p:AndroidEnableProfiledAot=true -p:RunAOTCompilation=true -r android-arm64 -p:AndroidPackageFormat=apk
File size:
> …

[Xamarin.Android.Build.Tasks] Profiled AOT can Full AOT the main assembly

---

Makefile
build-tools/automation/yaml-templates/install-apkdiff.yaml
build-tools/scripts/msbuild.mk
build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/MacOS.cs
build-tools/xaprepare/xaprepare/Scenarios/Scenario_CopyExtraResultFilesForCI.cs
build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs

The prepare related make targets have been updated to use `dotnet` over
`msbuild` or `mono`.
Includes an `apkdiff` bump to allow the tool to run against newer
versions of .NET, which will allow us to stop provisioning the .NET core
3.1 runtime.
Homebrew provisioning of `git` has been updated as installing
from a URL is no longer supported.
A small fix has been made in xaprepare to prevent log files from being
named renamed to `package-results-*` when running a different scenario.

[build] Use dotnet build for make prepare

---

build-tools/xaprepare/xaprepare/Application/Context.cs

37dbc459 made `xaprepare` build and run using dotnet which
caused `xaprepare` to misdetect whether the current terminal
supports Unicode and, thus, not use emoji.  This cannot be! :D
The problem lies in the fact that dotnet sets `Console.OutputEncoding`
to an internal class wrapping `System.Encoding` and our check for
the known Unicode encoding types fails.  Before looking at the type
of `OutputEncoding`, check whether the encoding name contains the
word "Unicode".  This fixes the check on dotnet.

[xaprepare] Fix Unicode detection when running on dotnet

---

src/monodroid/jni/logger.cc

917e1a94 rewrote the `init_logging_categories` function which parses the
`debug.mono.log` system property to eliminate memory allocation and
perform the parsing faster.  However, the conversion failed to set the
`LOG_TIMING` category when the `timing=bare` is used, which results in
the timing information not showing in the logs.
Fix the mistake by setting `LOG_TIMING` where appropriate.

Fix the `timing=bare` logging category

---

Documentation/README.md
Documentation/workflow/DevelopmentTips.md
Documentation/workflow/SystemProperties.md
src/monodroid/jni/debug-constants.cc
src/monodroid/jni/debug.hh
src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/strings.hh

From the `how did I miss it?!` department.
The main purpose of this commit is to fix parsing of the `mono_log_mask`
component of the `debug.mono.log` property.  The component is set to a
list of Mono logging categories (e.g. `asm`, `gc` or `dll`) which, so
far, were supposed to be a comma-separated list.  However...
`debug.mono.log` **itself** uses commas to separate components, so using
the following:
```shell
$ adb shell setprop debug.mono.log mono_log_mask=asm,gc,dll
```
would **not** set the `MONO_LOG_MASK` environment variable to the
expected value of `asm,gc,dll` but instead it would end up being just
`asm`, as the other values would be considered to be `debug.mono.log`
components instead.  To fix this, this commit changes the
`mono_log_mask` separator to `:`, so the above command …

Fix `mono_log_mask` parsing and add property docs

---

src/Microsoft.Android.Templates/android-activity/Activity1.cs
src/Microsoft.Android.Templates/android/MainActivity.cs
src/Microsoft.Android.Templates/androidlib/Class1.cs

Context: https://docs.microsoft.com/dotnet/csharp/whats-new/csharp-10#file-scoped-namespace-declaration
In 7fb7c814, I implemented most C# 10 features in templates, but I forgot about file scoped namespaces.
To match the other .NET 6 templates, we should have:
namespace AndroidApp1;
And remove one level of indentation from these files.

[One .NET] use file scoped namespaces in templates

---

src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/EnvironmentHelper.cs
src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGenerator.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
src/monodroid/jni/application_dso_stub.cc
src/monodroid/jni/cpp-util.hh
src/monodroid/jni/embedded-assemblies-zip.cc
src/monodroid/jni/embedded-assemblies.cc
src/monodroid/jni/generate-pinvoke-tables.cc
src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/startup-aware-lock.hh
src/monodroid/jni/xamarin-app.hh
src/monodroid/jni/xxhash.hh

Whenever a NET6 Xamarin.Android app starts, MonoVM will probe for a
number of Mono components:
11-16 14:23:24.805 10791 10791 I monodroid-assembly: Trying to load shared library '/data/app/~~5lwn5C40pkRva2-L4kilZA==/com.microsoft.net6.helloandroid-MrYUTOqX7yZPkmtLOPnuuw==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libmono-component-debugger.so'
11-16 14:23:24.806 10791 10791 I monodroid-assembly: Failed to load shared library '/data/app/~~5lwn5C40pkRva2-L4kilZA==/com.microsoft.net6.helloandroid-MrYUTOqX7yZPkmtLOPnuuw==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libmono-component-debugger.so'.
dlopen failed: library "/data/app/~~5lwn5C40pkRva2-L4kilZA==/com.microsoft.net6.helloandroid-MrYUTOqX7yZPkmtLOPnuuw==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libmono-component-debugger.so" not found …

[net6] Don't blindly load Mono components

---

src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs

Recently we've seen a lot of failures on the macOS build bots caused by
the inability to find `uname(1)`, resulting in the following exception
being thrown:
Xamarin.Android.Tooling.targets(64,5): error XARSD7000: System.ComponentModel.Win32Exception (0x80004005): ApplicationName='uname', CommandLine='-s', CurrentDirectory='', Native error= Cannot find the specified file
Xamarin.Android.Tooling.targets(64,5): error XARSD7000:   at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x0029f] in <ab9a187a50e54f8cb6a2692756ca03ac>:0
Xamarin.Android.Tooling.targets(64,5): error XARSD7000:   at System.Diagnostics.Process.Start () [0x0003a] in <ab9a187a50e54f8cb6a2692756ca03ac>:0
Xamarin.Android.Tooling.targets(64,5): error XARSD7000:   at (wrapper …

[Tests] Fix `uname` usage on macOS

---

Directory.Build.props
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/ApkDiffCheckRegression.cs
build-tools/create-packs/SignList.xml
build-tools/installers/create-installers.targets
build-tools/xaprepare/xaprepare/Steps/Step_CopyExtraResultFilesForCI.cs
build-tools/xaprepare/xaprepare/ThirdPartyNotices/ELFSharp.cs
src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
src/Xamarin.Android.Build.Tasks/Utilities/ELFHelper.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Profiled-Aot.apkdesc
tools/tmt/tmt.csproj

Fixes: https://github.com/xamarin/xamarin-android/issues/3932
Profiled AOT tends to produce a number of "empty" .so shared libraries
because the profile names only a handful of types from a handful of
assemblies and the AOT compiler in Mono currently doesn't support not
outputting the .so in such cases.
This has the unfortunate effect that an application may have a large
number of such empty .so libraries and each of them will have to be
opened and loaded before Mono can determine that there's no code in them
and the JIT has to compile the requested types and methods.  Loading
every .so takes a non-zero amount of time, especially if the shared
libraries aren't unpacked to the filesystem.  I've seen times between 10
and 30ms to load a single shared library, which can add up to a …

Don't package empty AOT-d DSOs

---

src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/ArchiveAssemblyHelper.cs
src/monodroid/jni/embedded-assemblies.cc
tools/assembly-store-reader/Program.cs

Fixes: https://developercommunity.visualstudio.com/t/Xamarin-Forms-Android-App-crashes-on-sta/1578587
Context: c9270261
c9270261 added support for assembly stores which, in turn, depend on
knowing the exact number of assemblies packaged in the APK in order to
properly perform binary search on the tables of assembly name hashes.
This information is recorded by the `GeneratePackageManagerJava` task
in the `libxamarin-app.so` library on the build time and then used by
the assembly store code on the run time.
The code responsible for counting failed to skip assemblies which had
the `AndroidSkipAddToPackage` metadata, in our case the old Android
Support Library ones, replaced by AndroidX, with the metadata set on the
old assemblies by the AndroidX migration code.
Properly ignore skipped …

Don't count assemblies to be skipped when packaging

---

src/monodroid/jni/monodroid-glue.cc

When the `monodroid_dlopen` is called by Mono, we search for libraries
in a handful of known locations (either app private library directory or
the base.apk archive, possibly override directories for Debug builds)
but if these fail to find the library, we give up and return `NULL`.
For that reason, a p/invoke into e.g. `libEGL.so` will "fail" in that we
will report the library as not found (since it's a system library, not
one private to the app) but the p/invoke may still work since a system
library may already be loaded, so `dlsym` will work despite the load
"failure".
Fix this by calling `AndroidSystem::load_dso` if we fail to locate the
shared library in the app directories, passing it the name sent to us by
Mono.

Fix `monodroid_dlopen` to load arbitrary DSOs

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs

We are seeing a Component Governance error for `System.Net.WebSockets.Client`.
This is because one of our tests uses `Microsoft.Azure.EventHubs`. This
is pulling in an old version of `System.Net.WebSockets.Client`.
So we need to upgrade the NuGet to make sure we pull in the newer version.
Interestingly, with the newer version we no longer get the expected
failure when using `PackageReference`. This is probably due to them fixing
the NuGet. So we have to update the test to reflect that change.

[Xamarin.Android.Build.Tests] Update Microsoft_Azure_EventHubs

---

src/monodroid/jni/monodroid-glue.cc

Context: 3329243f734a28dfc4b86951f5329833f3703971
3329243f failed to apply the same fix to the "legacy" Xamarin.Android, fix
the omission.

[monodroid] Fix `monodroid_dlopen()` to load arbitrary DSOs for legacy code

---

Directory.Build.props

Context: https://github.com/xamarin/xamarin-android/blob/b04b9fda5c34b9edec10bc6fd65dd5b67fe8d52a/Documentation/guides/HowToBranch.md
Context: https://github.com/xamarin/xamarin-android/tree/release/6.0.1xx-preview11
We branched `xamarin-android` along with `xamarin-macios`. This will
reflect the next release of .NET MAUI Preview 11. xamarin-android/main
should become Preview 12.

$(AndroidPackVersionSuffix)=preview.12; net6 is 31.0.101.preview.12

---

src/Xamarin.Android.Build.Tasks/Tasks/JarToXml.cs

Context: https://bugzilla.xamarin.com/show_bug.cgi?id=21096 [a 404 :-(]
Context: http://github.com/xamarin/monodroid/commit/df479c296720ee8fd2f19b12d2ff58d2b7474141
Context: https://github.com/xamarin/xamarin-android/issues/6524
(Behold the perils of *not* copying "important contextual bug info"
into commit messages, and the original bug was "private", and now
nobody can access the bug…)
Way back in 2014, we updated `<JarToXml/>` to *disable* use of the
[new type checker with StackMapTable attributes][0]:
java -XX:-UseSplitVerifier -jar /path/to/jar2xml.jar …
This was presumably to work around a bug with [asm][1], which was
probably fixed by [bumping to asm 5.0.3][2].
Unfortunately, using `-XX:-UseSplitVerifier` *fails* on JDK-11:
% path/to/jdk-11/java -XX:-UseSplitVerifier -jar …

[Xamarin.Android.Build.Tasks] Don't use -XX:-UseSplitVerifier

---

Configuration.props
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/GenerateSupportedPlatforms.cs
build-tools/create-packs/Directory.Build.targets
build-tools/create-packs/Microsoft.Android.Ref.proj
build-tools/create-packs/Microsoft.Android.Runtime.proj
build-tools/create-packs/Microsoft.Android.Sdk.proj
build-tools/scripts/DotNet.targets
src/Mono.Android.Export/Mono.Android.Export.csproj
src/Mono.Android/Mono.Android.csproj
src/Mono.Android/Mono.Android.targets
src/Mono.Android/Properties/AssemblyInfo.cs.in
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Tooling.targets
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json
src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Tooling.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/6176
Fixes: https://github.com/xamarin/xamarin-android/issues/6501
After some discussion with Daniel Plaisted, we think the best approach
for setting up API 31 packs is to have multiple packs:
* `Microsoft.Android.31.Ref`
* `Microsoft.Android.31.Runtime.[RID]`
* `Microsoft.Android.32.Ref`
* `Microsoft.Android.32.Runtime.[RID]`
We can check `$(TargetPlatformVersion)` to decide which pack to
list in `@(KnownFrameworkReference)` during builds.
These will all be versioned to match all other Android workload packs.
We'll continue to use `**FromWorkload**` to define their versions in
MSBuild.
I created a `android-32` workload, that installs additional API 32
packs. However, this workload doesn't necessarily need to exist as
targeting and …

[One .NET] add "preview" packs for API 32

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs

Context: https://github.com/jonathanpeppers/android-pipe/blob/c313259b782bff40204e1a1ca988659dc7d3180b/csharp/Benchmark.csproj#L25
When using BenchmarkDotNet in a .NET 6 Android app for the first time,
I hit this build error:
Microsoft.Android.Sdk.AssemblyResolution.targets(106,5): error XAPRAS7009: System.InvalidOperationException: PE image does not have metadata.
at System.Reflection.PortableExecutable.PEReader.GetMetadataBlock()
at System.Reflection.PortableExecutable.PEReader.GetMetadata()
at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader, MetadataReaderOptions options, MetadataStringDecoder utf8Decoder)
at System.Reflection.Metadata.PEReaderExtensions.GetMetadataReader(PEReader peReader)
at …

[One .NET] exclude .dll/.pdb files from @(None) or @(Content)

---

build-tools/create-packs/Microsoft.Android.Ref.proj
build-tools/create-packs/Microsoft.Android.Runtime.proj
build-tools/create-packs/Microsoft.Android.Sdk.proj
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json

When doing a Visual Studio insertion, we hit a build errors complaining
some packs don't have owners.
The rules matched patterns like:
Microsoft.Android.Ref*
Microsoft.Android.Runtime*
Microsoft.Android.Sdk*
We decided to rename the packs to match the above patterns, as we
didn't like the names anyway:
* Microsoft.Android.31.Ref -> Microsoft.Android.Ref.31
* Microsoft.Android.31.Runtime.[RID] -> Microsoft.Android.Ref.31.[RID]
* Microsoft.Android.32.Ref -> Microsoft.Android.Ref.32
* Microsoft.Android.32.Runtime.[RID] -> Microsoft.Android.Ref.32.[RID]
I think the `[RID]` should still remain last, as that tends to be the
pattern with RID-specific packages like:
* https://www.nuget.org/packages/Microsoft.NETCore.App.Runtime.win-x64/
* …

[One .NET] rename Microsoft.Android.31.Ref -> Microsoft.Android.Ref.31

---

Documentation/workflow/SystemProperties.md
src/monodroid/jni/logger.cc
src/monodroid/jni/monodroid-glue.hh
src/monodroid/jni/osbridge.cc
src/monodroid/jni/osbridge.hh

Context: https://bugzilla.xamarin.com/25/25443/bug.html#c23
Context: https://github.com/xamarin/monodroid/commit/bf9dc9ee270002ab02f6339640ad80f1b0bdf7c1
Once upon a time, JNI Global Reference (GREF) and
JNI Local Reference (LREF) logging was written only to `adb logcat`.
This worked, until it didn't work; around Android 5.0,
[`__android_log_print()`][0] appeared to become "less reliable", and
`adb logcat` would no longer "reliably" contain all GREF messages.
We "fixed" this in xamarin/monodroid@bf9dc9ee (2015-Feb-6) by writing
GREF messages to `grefs.txt`.
While this improved reliability, there was a "usability" cost:
`grefs.txt` can only be accessed if the app is ["debuggable"][1],
which isn't necessarily easy (requires rebuilding from source), and
hinders diagnosis and review.
Add new …

[monodroid] Add new `gref+`, `lref+` log options

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs

Context: https://github.com/dotnet/runtime/issues/57800
dotnet/runtime#57800 is fixed.

[tests] enable NoSymbolsArgShouldReduceAppSize test

---

src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs
src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetAotArguments.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetAotAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tasks/MakeBundleNativeCodeExternal.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/NdkUtilTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/JarContentBuilder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
src/Xamarin.Android.Build.Tasks/Utilities/NdkTools/NdkTools.cs
src/Xamarin.Android.Build.Tasks/Utilities/NdkTools/NdkVersion.cs
src/Xamarin.Android.Build.Tasks/Utilities/NdkTools/NullNdkTools.cs

It is possible for us to not require the Android NDK to be installed,
but we have checks in place that would emit errors, such as:
error XA5104: Could not locate the Android NDK. Please make sure the Android NDK is installed in the Android SDK Manager, or if using a custom NDK path, please ensure the $(AndroidNdkDirectory) MSBuild property is set to the custom path.
To make it possible to build with AOT without the NDK:
1. Make a `NullNdkTools` class to use when an NDK is not found.
2. Make the NDK only actually required when `$(EnableLLVM)` is `true`.
3. Update our MSBuild tests so they leave `$(AndroidNdkDirectory)`
blank.
After these changes, I'm able to build full and profiled AOT applications without
an Android NDK installed.
After this is merged, we might be able to make `Release` …

[Xamarin.Android.Build.Tasks] make $(AndroidNdkDirectory) optional

---

eng/Version.Details.xml
eng/Versions.props

Changes: https://github.com/dotnet/runtime/compare/4822e3c3aa77eb82b2fb33c9321f923cf11ddde6...3992fc3841133e15ad322842d35adb8c249a824f
We are in a situation where:
1. .NET MAUI is still in preview.
2. We need dotnet/runtime fixes for MAUI, but we don't necessarily
want all fixes going into .NET 6 service releases.
Since we are relying on optional workload packs from dotnet/runtime
anyway, we can simply use "different" builds.
An initial set of builds is coming from the ".NET 6 MAUI" channel on
Maestro. To update, we will need to drop the `CoherentParentDependency`
for dotnet/runtime.
After this change goes in, I can configure a subscription to update
daily/weekly, or whichever we decide is best.

[build] use dotnet/runtime packs from the ".NET 6 MAUI" channel

---

.github/ISSUE_TEMPLATE/01-building-an-application.yml
.github/ISSUE_TEMPLATE/02-running-an-application.yml
.github/ISSUE_TEMPLATE/03-mono-android-api.yml
.github/ISSUE_TEMPLATE/04-binding-a-java-library.yml
.github/ISSUE_TEMPLATE/05-other.yml

In our new YML issue templates, we use checkboxes for users to choose if their issues applies to Classic XA, .NET XA, or both.
However, these checkboxes are converted to "issue tasks" and show up as "1 of 2 tasks". ([example])(https://github.com/xamarin/xamarin-android/issues/6545)
This feedback has been filed to [GitHub](https://github.com/github/feedback/discussions/5238).
For now, switch to a dropdown that allows multiple selections.

[GitHub] Don't use checkboxes in issue templates.

---

build-tools/create-packs/Directory.Build.targets
build-tools/scripts/DotNet.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs

Context: https://docs.microsoft.com/dotnet/core/install/windows#download-and-manually-install
I have VS main installed, and my system has:
> dotnet --version
6.0.200-preview.21573.3
And so any built-in `~\android-toolchain\dotnet\dotnet.exe` commands
would actually run my system `dotnet` because it is newer than the
version our build provisions. In this case, my `C:\Program
Files\dotnet\dotnet.exe` was attempting to install my local build.
We can use `$DOTNET_MULTILEVEL_LOOKUP` to force
`~\android-toolchain\dotnet\dotnet.exe` to be always used. I couldn't
find many docs on this, but it is used in various dotnet repos, such as:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/dotnet.cmd#L16-L17
I also fixed the wildcard match for `@(_PreviewPacks)`, which …

[build] set $DOTNET_MULTILEVEL_LOOKUP to 0

---

Documentation/guides/messages/README.md
Documentation/guides/messages/xa0113.md
src/Xamarin.Android.Build.Tasks/Tasks/Legacy/ResolveAndroidTooling.cs

Context: https://support.google.com/googleplay/android-developer/answer/9859152?#targetsdk
We currently warn if `$(TargetFrameworkVersion)` is less than 29:
Google Play requires that new applications and updates must use a TargetFrameworkVersion of v10.0 (API level 29) or above.
Since November 1, 2021, Google Play requires API 30, so we need to
update this warning.

[Xamarin.Android.Build.Tasks] Bump XA0113 warning to 30.

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml
build-tools/automation/yaml-templates/variables.yaml
tools/xabuild/XABuildPaths.cs

Context: https://aka.ms/1eshostedpools
I've created a new Windows VS 2022 pool to use for Windows build and
test jobs.  The azure resource for this pool can be [found here][0].
The base image of this pool is the Microsoft-hosted [windows-2022][1]
image, and our machines will stay in sync with any updates that happen
to that hosted pool moving foward.
[0]: https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/cd4829e2-e38b-43d2-8316-2f2009f36f97/resourceGroups/devdiv-vm-scale-sets/providers/Microsoft.CloudTest/hostedpools/android-win-2022/overview
[1]: https://github.com/actions/virtual-environments/blob/ddaeaaa8fba88b009ab140001e63ee317dae52db/images/win/Windows2022-Readme.md

[ci] Move to 1ES Windows VS 2022 pool

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs

This reverts commit 5dcf2945e4cd7da50c5c8f76608e0d0266022b09.
Context: https://github.com/xamarin/xamarin-android/issues/6520
Context: https://github.com/xamarin/xamarin-android/pull/6560
Context: 5dcf2945e4cd7da50c5c8f76608e0d0266022b09
Context: c96d9f496675d177687273fb20bc65f6e5dc73cd
There was a "curious" interaction between 5dcf2945 (PR #6544) and
commit c96d9f49 (PR #6539): they both had green PRs, but each of
their PR build ran without the other existing.  Once both were merged,
all subsequent commits, and PRs based on c96d9f49, had a unit test
failure in `NoSymbolsArgShouldReduceAppSize`:
Task "MonoAOTCompiler" requested 6 cores, acquired 6 cores, and now holds 6 cores total.
[System.Private.CoreLib.dll] Running: C:\Users\cloudtest\android-toolchain\dotnet\packs\Microsoft.NETCore.Ap …

Revert "[tests] enable NoSymbolsArgShouldReduceAppSize test (#6544)"

---

Documentation/guides/messages/xa0119.md
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Aot.targets
src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Building a .NET 6 `Release` app with `UseInterpreter=true` and
`RunAOTCompilation=true` would fail with:
Microsoft.Android.Sdk.Aot.targets(71,5): Unknown Mode value: Interpreter. 'Mode' must be one of: Normal,JustInterp,Full,FullInterp,Hybrid,LLVMOnly,LLVMOnlyInterp
Reviewing the code:
https://github.com/dotnet/runtime/blob/60edc0bdafce1849fec19e3ec4f766074de50fc3/src/tasks/AotCompilerTask/MonoAOTCompiler.cs#L1064-L1073
There does not appear to be a mode of `Normal` + `Interp`. So let's
just make AOT take precendence over `$(UseInterpreter)`. On Android
`$(UseInterpreter)` is a Debug-mode setting for Hot Reload.
Building a .NET 6 `Debug` app `RunAOTCompilation=true` would fail with:
Microsoft.Android.Sdk.Aot.targets(49,5): error MSB4044: The "GetAotAssemblies" task was not given a value …

[One .NET] fix AOT builds with different settings

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc

to produce smaller output
_AggressiveAttributeTrimming - mostly attributes remove by current XA
NullabilityInfoContextSupport - saves a lot by trimming all C# compiler generated nullable information
BuiltInComInteropSupport - no COM support on Android

Enable more 6.0 feature switches

---

build-tools/create-packs/Microsoft.Android.Sdk.proj
src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.ClassParse.targets
src/Xamarin.Android.Build.Tasks/Tasks/ClassParse.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj

Context: https://github.com/xamarin/java.interop/pull/499
There are potentially some conflicts with using `Xamarin.Android.Tools.Bytecode` directly in the MSBuild process, as it now imports `protobuf-net` which is a commonly used library.
To ensure it isn't running in-process, switch our targets to shell out to `class-parse[.exe/.dll]`.
Additionally add `class-parse.dll`, etc. to the .NET 6 install pack.  We are already shipping `class-parse.exe`, etc. in the Classic installer even though it wasn't used, so no additional installer changes are needed there.
As expected, moving this out-of-process is slightly slower, but still acceptable.
```
Before
292 ms  ClassParse                                 1 calls
After
425 ms  ClassParse                                 1 calls
```
Additionally …

[Xamarin.Android.Build.Tasks] Use class-parse.exe out of MSBuild process

---

.external

Context: https://github.com/dotnet/runtime/issues/58394
Context: https://github.com/mono/mono/issues/12098
Context: https://github.com/mono/mono/issues/17113
Context: https://github.com/mono/mono/issues/19433
Context: https://github.com/mono/mono/issues/20417
Context: https://github.com/mono/mono/issues/21206
Changes: https://github.com/mono/mono/compare/c633fe923832f0c3db3c4e6aa98e5592bf5a06e7...b8d7525156acaecf311ba468147caa74d8c190f6
* mono/mono@b8d7525156a: [2020-02] [cominterop] Add coop handle enter/return on native CCW methods  (#21366)
* mono/mono@2ca650f1f62: [2020-02] Adds full path to libcairo for correct assembly directory resolution in monterey (#21351)
* mono/mono@e750cb3ee50: [aot] Prepend the assembly name to the names of gsharedvt wrappers to avoid duplicate symbol errors …

Bump to mono/mono/2020-02@b8d75251

---

build-tools/scripts/XABuildConfig.cs.in
build-tools/xaprepare/xaprepare/Application/KnownProperties.cs
build-tools/xaprepare/xaprepare/Application/Properties.Defaults.cs.in
build-tools/xaprepare/xaprepare/Steps/Step_GenerateFiles.cs
build-tools/xaprepare/xaprepare/xaprepare.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj

Context: https://github.com/xamarin/xamarin-android/commit/21751b5bc4292be4b23dd58577cb6cf9f01d82bb
Android API 32 is [now "final"][0], and is causing test failures on hosted
Azure Pipelines agents:
"/Users/runner/work/1/a/TestRelease/12-15_16.53.22/temp/XA4310apk/UnnamedProject.csproj" (Build;SignAndroidPackage target) (1:7) ->
(_CheckGoogleSdkRequirements target) -> 
/Users/runner/Library/Android/dotnet/packs/Microsoft.Android.Sdk.Darwin/31.0.101-preview.12.144/targets/Microsoft.Android.Sdk.Tooling.targets(68,5): warning XA1008: The TargetFrameworkVersion (Android API level 31) is lower than the targetSdkVersion (32). Please increase the `$(TargetFrameworkVersion)` or decrease the `android:targetSdkVersion` in the `AndroidManifest.xml` so that the API levels match. …

[tests] Ignore unstable API levels when creating test projects

---

.external

Changes: https://github.com/xamarin/monodroid/compare/06ff96ddccf7d702ed413b85728459b639d5f1a3...5b0fab478fa4682034dbbc0cce06748c7dc51474
* xamarin/monodroid@5b0fab478: Bump to xamarin/androidtools/main@772d2f0b (#1234)
* xamarin/monodroid@16f8f7ea2: Bump xamarin-android (#1233)

Bump to xamarin/monodroid/main@5b0fab47

---

src/Xamarin.Android.Build.Tasks/Tasks/ValidateJavaVersion.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ValidateJavaVersionTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs

Context: https://en.wikipedia.org/wiki/Log4Shell
Context: https://nvd.nist.gov/vuln/detail/CVE-2021-45046
Context: https://twitter.com/hacks4pancakes/status/1470926736095391744
Context: https://twitter.com/Laughing_Mantis/status/1470412026119798786
Around 2021-Dec-10, the "Log4Shell" exploit became widely known.
For a brief moment (the weekend?), it appeared that the exploit could
be prevented -- or at least *minimized* -- by disabling certain JVM
features, a'la:
export JAVA_TOOL_OPTIONS='-Dcom.sun.jndi.ldap.object.trustURLCodebase=false -Dcom.sun.jndi.rmi.object.trustURLCodebase=false -Dcom.sun.jndi.cosnaming.object.trustURLCodebase=false -Dlog4j2.formatMsgNoLookups=true'
export _JAVA_OPTIONS="$JAVA_TOOL_OPTIONS"
Turns out™, this mitigation [doesn't actually work][0], but it was …

[Xamarin.Andorid.Build.Tasks] Improve javac version parsing

---

build-tools/automation/yaml-templates/variables.yaml

Now that macOS 12 Monterey is publicly available, it seems like a good
time to upgrade our macOS test machines to last years macOS 11 Big Sur
release.

[CI] Run macOS test jobs on macOS 11

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs

I was looking at a build log and noticed:
Mono: AOT: FOUND method System.Threading.Thread:GetCurrentCultureNoAppX () [0x1120b7eb0 - 0x1120b7f82 0x1124d0e98]
Mono: AOT: FOUND method System.Globalization.CultureInfo:get_UserDefaultCulture () [0x1123d0750 - 0x1123d0772 0x1124e2be7]
Mono: AOT: FOUND method System.Globalization.CultureInfo:ConstructCurrentCulture () [0x1123ca740 - 0x1123ca88c 0x1124e286c]
Mono: AOT NOT FOUND: (wrapper managed-to-native) System.Globalization.CultureInfo:get_current_locale_name ().
It seems like if Mono is set to log all of this information, it would
slow down our CI times?
I found an instance we set `MONO_LOG_LEVEL=debug` for MSBuild tests,
added in:
https://github.com/xamarin/xamarin-android/commit/b8c30f9e5329bfb4f1bf7ac3ade4131ffd067654
It was probably just …

[tests] remove $MONO_LOG_LEVEL debug

---

Documentation/release-notes/README.md
Xamarin.Android.sln
tools/relnote-gen/App.cs
tools/relnote-gen/CommitInfo.cs
tools/relnote-gen/README.md
tools/relnote-gen/relnote-gen.csproj

Context: ae6c42745038b22d525c6c5378e7b643ca99c25f
Context: https://docs.microsoft.com/xamarin/android/release-notes/12/12.1
Add a utility to *assist* with writing release notes:
git log -p --cherry-pick --right-only 46e867efc69ac5b62881277e2580d1b6e0347b52...d7ce643351b248777a50ea63b3b13b54d95aa6c5 \
| dotnet run --project tools/relnote-gen
`tools/relnote-gen` parses the `git log -p` output, looking for:
* The `commit COMMIT` header
* The commit message "summary", which optionally contains a
"component" (b9ba3763) and PR number
* The commit message text, which may contain `Fixes: ` URLs
* Release notes (via `git log -p`; any additions to the
`Documentation/release-notes` directory)
All commits with the same component are coalesced, and
Markdown-formatted text is written containing:
* The …

[relnote-gen] Add Release Notes Generator Helper

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/setup-test-environment.yaml

We have a private mirror, for servicing security fixes, or testing
builds of .NET with security fixes.
By default, the private mirror, `xamarin-android-private` is checking
out into:
Finishing: Checkout xamarin/xamarin-android-private@main to s/xamarin-android-private
Which causes the build to fail on a later step:
Could not find a part of the path '/Users/builder/azdo/_work/7/s/xamarin-android/build-tools/provisioning/xcode.csx'
Specify the path when checking out `self` to solve this issue.

[build] specify path for self checkouts

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsMapsApplicationProject.cs

We recently discovered the following doesn't work in .NET 6:
* `dotnet new android`
* Add `<PackageReference Include="Xamarin.Google.MLKit.BarcodeScanning" Version="116.1.2.2" />`
`dotnet build` fails with many `javac` errors:
obj\Debug\net6.0-android\android\src\crc6434af9c19aa01b597\GoogleApiClientConnectionCallbacksImpl.java(8,52): error JAVAC0000:  error: package com.google.android.gms.common.api.GoogleApiClient does not exist
`Xamarin.Build.Download` didn't actually download the Java libraries.
If you make this change to Xamarin.Build.Download locally, it solves
the issue:
https://github.com/xamarin/XamarinComponents/commit/faf04b389ea3e1b9a57d9f9bd5ba57f0ad2f87fa
We never shipped this fix!
This is resolved now with [Xamarin.Build.Download 0.11.0][0]. So
adding this to the original …

[tests] update to latest GPS packages

---

build-tools/automation/azure-pipelines.yaml

As our main pipeline continues to grow and become more complex we need
to scroll further to see all of our stages and jobs.  The Code Analysis
stage has been moved to the end of the pipeline file to improve the
visibility of stages that fail more often.

[ci] Move Code Analysis stage to end of pipeline

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.RuntimeConfig.targets
src/java-runtime/java/mono/android/MonoPackageManager.java
src/monodroid/CMakeLists.txt
src/monodroid/jni/basic-android-system.cc
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/monovm-properties.cc
src/monodroid/jni/monovm-properties.hh
src/monodroid/jni/shared-constants.hh

Fixes: https://github.com/xamarin/xamarin-android/issues/6190
NET6+ BCL needs two `AppContext` properties to be defined and passed to
the runtime on initialization:
* `RUNTIME_IDENTIFIER` which contains the RID
* `APP_CONTEXT_BASE_DIRECTORY` which points to the app's "home"
directory
Initialize and pass these properties to `monovm_initialize_preparsed`.

[NET6] Pass required properties to MonoVM

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-installer.yaml
build-tools/automation/yaml-templates/setup-test-environment.yaml
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/TestEnvironment.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/5701
Adds a Linux test stage to exercise the `Microsoft.Android.Sdk.Linux`
.nupkg produced by the Linux build.  This stage contains one job that
runs the `SmokeTests` category of our MSBuild tests.
A couple of updates have been made to `Xamarin.ProjectTools` to support
test environments that do not have a system-wide installation of classic
Xamarin.Android.  This effort was focused on getting the `SmokeTests`
category to run, however more test harness changes will be needed in 
in this area in the future.

[ci] Move Linux tests to separate stage

---

Directory.Build.props

Context: http://aka.ms/maui-schedule
Update our version number to 31.0.200 to match the 6.0.200 .NET SDK.
We branched xamarin-android/release/6.0.2xx-preview12, to reflect the
next release of .NET MAUI Preview 12.
xamarin-android/main becomes Preview 13.

$(AndroidPackVersionSuffix)=preview.13; net6 is 31.0.200.preview.13

---

build-tools/automation/azure-pipelines.yaml

The `MSBuild` based Windows job has been removed in favor of the
`dotnet build` job.  This should reduce the overall load on our custom
Windows agent pool.
The `net472` version of `Xamarin.Android.Build.Tests` will now run as
part of this single Windows job.  This will ensure that classic tests
that run against a local build tree continue to work.

[ci] Consolidate Windows Build and Test jobs

---

build-tools/scripts/msbuild.mk

Commit bb4e4a63 seemingly broke our nightly build, as the extra MSBuild
properties set in the `$MSBUILD_ARGS` make variable were no longer used
in `dotnet build` invocations.  Fix this by appending `$MSBUILD_ARGS` to
all `DOTNET_BINLOG` make function calls.

[ci] Fix extra build args in nightly build

---

eng/Versions.props

Previously in 63a9aca4, we bumped from:
6.0.100-rtm.21552.8 to 6.0.101-servicing.21562.12
And our existing logic that computes `$(DotNetPreviewVersionBand)`
came up with:
<DotNetPreviewVersionBand>6.0.101</DotNetPreviewVersionBand>
While we need the version band to actually read 6.0.100!
At the time we just hardcoded 6.0.100, let's change the logic to
instead match:
^\d+\.\d+\.\d
Then appending '00' results in a correct version band.
I tested with this project:
<Project>
<MicrosoftDotnetSdkInternalPackageVersion>6.0.201-preview.22055.18</MicrosoftDotnetSdkInternalPackageVersion>
<DotNetPreviewVersionBand>$([System.Text.RegularExpressions.Regex]::Match($(MicrosoftDotnetSdkInternalPackageVersion), `^\d+\.\d+\.\d`))00</DotNetPreviewVersionBand>
<Target …

[build] fix logic to compute .NET version band

---

Documentation/release-notes/r8-2.2.64.md
Documentation/release-notes/r8-3.0.73.md
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
src/r8/build.gradle

Context: https://r8.googlesource.com/r8/+/refs/tags/3.0.73
Context: https://mvnrepository.com/artifact/com.android.tools/r8/3.0.73
Bump from r8 2.2.64 to 3.0.73.

Bump to r8 3.0.73

---

.github/dependabot.yml

Context: https://docs.github.com/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/
Context: https://docs.github.com/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
To help us keep r8 and manifest-merger updated, we can configure
Github's dependabot to send us PRs weekly.
It appears we have to merge this file and "see if it works"?
I did this in another repo for NuGet packages here:
https://github.com/jonathanpeppers/boots/commit/b5f191d1fc1ccd7a024472245f6fb89ac77210e0
And the file seems to be what configures everything.

Enable github dependabot for gradle files

---

.github/dependabot.yml

Context: https://github.com/xamarin/xamarin-android/network/updates/253221292
Dependabot failed with:
Dependabot couldn't find a build.gradle(.kts)?.
Dependabot requires a build.gradle(.kts)? to evaluate your Java
dependencies. It had expected to find one at the path:
/build.gradle(.kts)?.
If this isn't a Java project, you may wish to disable updates for
it in the .github/dependabot.yml config file in this repo.
I believe the only options here are `package-ecosystem`, `directory`,
and `schedule`. So I think we can configure two directories for r8 and
manifestmerger.
Unfortunately, it seems like we have to test this in the default
branch. When I tried another branch I see the message:
Cannot configure Dependabot.
To configure Dependabot, you must use this repository’s default branch.

[github] configure dependabot for two directories

---

Documentation/building/windows/instructions.md

It seems to be necessary to restore the packages before the first build of `xabuild.csproj` on Windows.

Add missing restore instruction for building xabuild.csproj

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Documentation.targets
src/Xamarin.Android.Build.Tasks/Tasks/UnzipToFolder.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

MSBuild ships with an Unzip task already. This task has a different
API to our one. So we would rename the Task so that is does not clash
with the existing task.

[Xamarin.Android.Build.Tasks] Rename Unzip to UnzipToFolder

---

Makefile

Running `make pack-dotnet` on Unix may fail with a combination of
the following errors:
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj(4,47): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Microsoft.Android.Build.BaseTasks.csproj(4,47): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Microsoft.Android.Build.BaseTasks.csproj(4,47): error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Microsoft.Android.Build.BaseTasks.csproj(4,47): error MSB4236: The SDK …

Run the `pack-dotnet` make target in single-threaded mode

---

tests/msbuild-times-reference/MSBuildDeviceIntegration.csv

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5619146&view=ms.vss-test-web.build-test-results-tab&runId=31222446&resultId=100025&paneView=debug
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5619146&view=ms.vss-test-web.build-test-results-tab&runId=31217648&resultId=100025&paneView=debug
Since ~Jan 4 (that is far as history goes back), we've noticed these
tests failing sometimes:
* `Build_Designer_Change`
* `Build_AndroidManifest_Change`
Reviewing the `.binlog` files, I don't see a regression in *our*
MSBuild tasks. So I suspect that maybe it is due to some change in the
.NET SDK, MSBuild, or CI machines?
On thing of suspect is how long project evaluation is taking: 447ms
Either way, I think we should just increase the times on these two …

[tests] update MSBuildDeviceIntegration.csv

---

build-tools/installers/sign-pkg-content.proj
src/manifestmerger/build.gradle

Our .pkg notarization step has been failing since bumping manifestmerger
to 30.0.4.  After further investigation, this appears to be due to some
new macOS binaries:
"issues": [
{
"severity": "error",
"code": null,
"path": "xamarin.android.pkg Contents/Payload/Library/Frameworks/Xamarin.Android.framework/Versions/12.2.99.37/lib/xamarin.android/xbuild/Xamarin/Android/manifestmerger.jar/com/sun/jna/darwin/libjnidispatch.jnilib",
"message": "The binary is not signed.",
"docUrl": null,
"architecture": "i386"
}
]
Rather than trying to sign/harden these files ourselves, we should be
able to remove them from manifestmerger.jar to fix this.

[build] Remove jna content from manifestmerger.jar

---

build-tools/installers/sign-pkg-content.proj
src/bundletool/bundletool.targets

We've been removing the aapt2 executables included in bundletool.jar
during our CI builds on macOS only.  This is being done to simplify the
work needed for installer signing and notarization.  We should move this
logic to the project that builds bundletool.jar to establish consistent
behavior across build environments.

[build] Remove aapt2 from bundletool during build

---

build-tools/automation/azure-pipelines.yaml

This brings over more changes from `xamarin-android-private`.
With these changes, the private fork should be able to build `main` and push builds to an internal feed.
I also set `$(TeamName)`, which isn't used here -- but will be needed when consuming internal .NET builds on the private fork.

[build] .yaml changes for private fork & NuGet feeds

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Tooling.targets

I've noticed the following sometimes happens when a new .NET MAUI
project is created in VS 2022 on Windows:
dotnet\sdk\6.0.200-preview.22055.18\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5):
error NETSDK1004: Assets file 'obj\project.assets.json' not found.
Run a NuGet package restore to generate this file.
I seem to only get this for MAUI projects and only *sometimes*.
`dotnet new android` projects seem to always work fine.
When this error occurs, I think the dropdown fails to load the device
list. What you end up with is the play button that just says
`> Android Emulator`. After some amount of "fiddling", you can get the
IDE to load the device list.
What I think is happening is:
1. NuGet restore takes longer in MAUI projects than `dotnet new …

[One .NET] fix GetAndroidDependencies target with --no-restore

---

build-tools/create-packs/Directory.Build.targets
build-tools/create-packs/Microsoft.Android.Sdk.proj
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json

After 6eb11f15 went in, I realized an issue when using `net6.0-android31`:
1. You get API 31 by default. We bring in these packs from NuGet.org
with the version 31.0.101-preview.11.117:
Microsoft.Android.Ref.31
Microsoft.Android.Runtime.31.[rid]
2. So now you can't get the latest changes for `libmonodroid.so`, for
example? You'd have to opt-in via `net6.0-android32`.
Thinking about it more, we should only need to use the API 31 "ref" or
"targeting" pack. The "runtime" pack can just use the latest from the
workload.
To fix this:
1. Create new `$(_AndroidTargetingPackId)` and
`$(_AndroidTargetingPackVersion)` properties to use independently
of the runtime pack version.
2. Remove `Microsoft.Android.Runtime.31.[rid]` packs from the workload.
3. Remove the `android-32` workload, as it should …

[One .NET] use API 31 "ref" pack with 32 "runtime" pack

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs

Context: https://sqlite.org/releaselog/3_37_2.html
Context: https://sqlite.org/src/info/73c2b50211d3ae26
Context: https://sqlite.org/src/info/5232c9777fe4fb13
Changes:
* Fix a bug introduced in version 3.35.0 (2021-03-12) that can cause database
corruption if a SAVEPOINT is rolled back while in PRAGMA temp_store=MEMORY
mode, and other changes are made, and then the outer transaction commits.
* Fix a long-standing problem with ON DELETE CASCADE and ON UPDATE CASCADE
in which a cache of the bytecode used to implement the cascading change
was not being reset following a local DDL change.

Bump SQLite to v3.37.2

---

Documentation/guides/tracing.md

I simplified some of the steps, and included instructions for installing `dotnet-dsrouter`.
These instructions should be a little simpler to follow, for both Windows & Unix-like OS users.
/cc @eerhardt

[docs] improve the `dotnet trace` instructions

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
tests/MSBuildDeviceIntegration/Tests/InstallTests.cs

Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1447873
The following breaks in both Xamarin.Android & .NET 6:
1. Deploy a build with `AndroidPackageFormat=aab` to a device
2. Switch the dropdown in the IDE, deploy to an emulator
Fails with:
HelloWorld.csproj  → Install
Target _DeployAppBundle
Task InstallApkSet
Error [BT Missing APKs for [ABI] dimensions in the module 'base' for the provided device.
I could reproduce this in a test with a blank `$(AdbTarget)`, then set
`$(AdbTarget)` to the connected device. This should simulate what
happens in the IDE when you switch devices.
What happens is this `Condition`:
Condition="!Exists('$(_ApkSetIntermediate)')"
Just skips if the file exists!
To solve the issue:
1. Move the `<BuildApkSet/>` task to a new `_BuildApkSet` target.
2. …

[Xamarin.Android.Build.Tasks] fix .aab deploying to different ABIs

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/variables.yaml

Updates our Microsoft hosted and VSEng scale set Windows pools to the
latest and greatest images.  The designer integration test job has been
disabled on Windows for some time, and it will continue to use the
`windows-2019` pool until it is re-enabled.

[ci] Use Windows 2022 agent pools

---

Directory.Build.props

Changes
- Use a different license tag for nuget generation 
- Fix corrupt data when Deleting entries from zip files.
https://github.com/xamarin/LibZipSharp/compare/2.0.0...2.0.2

Bump LibZipSharp to 2.0.2

---

Documentation/guides/building-apps/build-items.md
Documentation/guides/building-apps/build-properties.md
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Publish.targets
src/Xamarin.Android.Build.Tasks/Tasks/BuildAppBundle.cs
src/Xamarin.Android.Build.Tasks/Tasks/Proguard.cs
src/Xamarin.Android.Build.Tasks/Tasks/R8.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Aot.apkdesc
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Bundle.apkdesc
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Profiled-Aot.apkdesc
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release.apkdesc
tests/apk-sizes-reference/com.companyname.vsandroidapp-Signed-Release.apkdesc

Fixes: #5378
Context: 2dab2bc
When uploading an `.apk` or `.aab` file which contains native
libraries such as AOT'd .NET assemblies to the Google Play store,
the Google Play Console reports the following warning:
> This App Bundle contains native code, and you've not uploaded
> debug symbols.  We recommend that you upload a symbol file to make
> your crashes and ANRs easier to analyse and debug.
Commit 2dab2bc addresses a similar warning regarding obfuscated
Java/Kotlin code.
Improve support for this scenario by adding a new
`$(AndroidCreateProguardMappingFile)` MSBuild property which controls
the creation of the ProGuard mapping file.
When True (the default when r8 is used), a ProGuard mapping file will
be created and added to `.apk`/`.aab` build outputs.  This increases
the size of …

[Xamarin.Android.Build.Tasks] Add Support for bundletool meta-data

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Tooling.targets

Context: https://github.com/dotnet/sdk/issues/23562
This reverts commit a21d1a7d.
When installing from Visual Studio, builds can hit the error:
error XA0002: Could not find mono.android.jar
Running `dotnet workload install maui` over top, solves the issue!
Since, `%(TargetingPack.PackageDirectory)` appears to be blank when
installed from Visual Studio, I think we just have to revert this
change.

Revert "[One .NET] fix GetAndroidDependencies target with --no-restore"

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs

Context: https://github.com/xamarin/QualityAssurance/tree/master/Manual/CrossPlatformDebugging
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1430409
Fixes: https://github.com/xamarin/xamarin-android/issues/6480
A `CrossPlatformDebugging` sample project in the QA repo fails to
debug with:
System.InvalidProgramException
Message=Invalid IL code in Mono.SystemDependencyProvider:Initialize (): IL_002e: endfinally
The problem goes away if you do one of:
* Turn *on* Fast Deployment
* Add `<AndroidUseAssemblyStore>false</AndroidUseAssemblyStore>`
* Change `$(DebugType)` to `portable`. (the project has `full`)
The problem appears to be:
1. `$(AndroidUseAssemblyStore)` defaults to `true` when you turn Fast
Deployment *off*.
2. Assembly stores appear to have some issue when …

[Xamarin.Android.Build.Tasks] default $(AndroidUseAssemblyStore) to false for debug builds

---

Directory.Build.props

Context: http://aka.ms/maui-schedule
We branched xamarin-android/release/6.0.2xx-preview13, to reflect the
next release of .NET MAUI Preview 13.
xamarin-android/main becomes Preview 14.

$(AndroidPackVersionSuffix)=preview.14; net6 is 31.0.200.preview.14

---

src/Mono.Android/Android.Runtime/AndroidRuntime.cs

Context: https://github.com/dotnet/maui/issues/4262
`dotnet new maui-blazor` crashes at runtime, if you do:
dotnet build -t:Run -c Release
You can turn *off* the linker to solve this issue:
dotnet build -t:Run -c Release -p:AndroidLinkMode=None
(or `PublishTrimmed=false`)
The app crashes in way that you get a native crash:
backtrace:
#00 pc 000000000065d8fc  /apex/com.android.art/lib64/libart.so (void art::StackVisitor::WalkStack<(art::StackVisitor::CountTransitions)0>(bool)+156) (BuildId: 7fbaf2a1a3317bd634b00eb90e32291e)
#01 pc 000000000069b25d  /apex/com.android.art/lib64/libart.so (art::Thread::GetCurrentMethod(unsigned int*, bool, bool) const+157) (BuildId: 7fbaf2a1a3317bd634b00eb90e32291e)
#02 pc 0000000000430fed  /apex/com.android.art/lib64/libart.so …

[Mono.Android] handle exceptions in RegisterNativeMembers

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/apk-instrumentation.yaml
build-tools/scripts/TestApks.targets
tests/Mono.Android-Tests/System.Net/SslTest.cs
tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidClientHandlerTests.cs

Drops the dependency we have on the `tls-test*.internalx.com` VMs.
Tests that attempted to run against a particular TLS version have been
removed, others have been updated to use httpbingo.org
A small `TestApks.targets` change has also been added to simplify local
test execution.

[Mono.Android-Tests] Stop using tls-test.internalx.com

---

Directory.Build.props
src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs

We are seeing the following error on some builds
`error XABBA7000: Xamarin.Tools.Zip.ZipException: Zip archive inconsistent: entry 0: invalid WinZip AES extra field `
Verison 2.0.2 of LibZipSharp was supposed to fix this, but it had a [bug](https://github.com/xamarin/LibZipSharp/pull/104). 
Which would cause corruption in the zip file itself. 
This bug was fixed in 2.0.3 of LibZipSharp. So lets bump to that.

Bump LibZipSharp to 2.0.3

---

src/Microsoft.Android.Sdk.ILLink/PreserveLists/Mono.Android.xml
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc

Fixes: https://github.com/dotnet/maui/issues/2246
Fixes: https://github.com/dotnet/maui/issues/4262
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1447865
Revert "[One .NET] Do not preserve IO stream adapter/invoker (#5449)"
This reverts commit 051cad7.
`dotnet new maui-blazor` crashes in Release mode with:
Android.Runtime.JavaProxyThrowable: Exception_WasThrown, Android.Runtime.JavaProxyThrowable
--- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
android.runtime.JavaProxyThrowable: System.ArgumentException: Arg_DlgtTargMeth
at System.Delegate.CreateDelegate(Type , Type , String , Boolean , Boolean )
at System.Delegate.CreateDelegate(Type , Type , String )
at Android.Runtime.AndroidTypeManager.RegisterNativeMembers(JniType , Type , String )
--- End of …

[Microsoft.Android.Sdk.IlLink] preserve methods in Android.Runtime classes

---

build-tools/automation/yaml-templates/apk-instrumentation.yaml
build-tools/automation/yaml-templates/upload-results.yaml
build-tools/scripts/TestApks.targets
build-tools/xaprepare/xaprepare/Steps/Step_CopyExtraResultFilesForCI.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs

Fixes .apk/.aab file uploads when an apk test configuration fails.
The filters for log file uploading have also been improved to avoid a
situaton where we attempt to upload a file with the same name twice:
Copying file '/Users/runner/work/1/s/xamarin-android/bin/TestRelease/logcat-Release-full.log' to '/Users/runner/work/1/a/TestRelease/logcat-Release-full.log' (overwrite destination: False)
Copying file '/Users/runner/work/1/s/xamarin-android/bin/TestRelease/logcat-ReleaseAab-Mono.Android.NET_Tests.txt' to '/Users/runner/work/1/a/TestRelease/logcat-ReleaseAab-Mono.Android.NET_Tests.txt' (overwrite destination: False)
...
Copying file '/Users/runner/work/1/s/xamarin-android/bin/TestRelease/logcat-Release-full.log' to '/Users/runner/work/1/a/TestRelease/logcat-Release-full.log' (overwrite …

[ci] Improve test failure content uploads

---

src/Mono.Android/Android.Runtime/JNIEnv.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.g.tt
src/Mono.Android/Java.Interop/TypeManager.cs
src/Mono.Android/Mono.Android.csproj
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleLegacy.apkdesc

`dotnet new android` calls `JNINativeWrapper.CreateDelegate()` twice,
while `dotnet new maui` ends up calling it 58 times during startup.
This code path calls System.Reflection.Emit to generate a
`System.Delegate` at runtime to be invoked. After some thought, it is
possible to "hard code" common delegate types and avoid SRE:
private static Delegate CreateBuiltInDelegate (Delegate dlg, Type delegateType)
{
switch (delegateType.Name) {
case nameof (_JniMarshal_PP_V): {
_JniMarshal_PP_V callback = (_JniMarshal_PP_V) Delegate.CreateDelegate (typeof (_JniMarshal_PP_V), dlg.Target, dlg.Method);
_JniMarshal_PP_V result = (jnienv, klazz) => {
JNIEnv.WaitForBridgeProcessing ();
try {
callback (jnienv, klazz);
} catch (Exception e) {
bool filter = Debugger.IsAttached || !JNIEnv.PropagateExceptions; …

[Mono.Android] avoid System.Reflection.Emit usage for common calls

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc

Some combination of merging:
* 32cff438
* f61cd81c
We missed an update to this file, as `Mono.Android.dll`'s size
increased beyond the threshold:
stdErr: Error: apkdiff: File 'assemblies/Mono.Android.dll' has changed by 4,468 bytes (5.10 %). This exceeds the threshold of 5.00 %.
Error: apkdiff: Size regression occured, 1 check(s) failed.

[tests] update BuildReleaseArm64SimpleDotNet.apkdesc

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Aot.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs

Fixes: https://github.com/dotnet/runtime/issues/64269
An F# test was failing in AOT builds with:
Microsoft.Android.Sdk.Aot.targets(74,5): Precompiling failed for C:\src\xamarin-android\bin\TestDebug\temp\BuildBasicApplicationFSharpTrue\obj\Release\android-arm\aot-in\FSharp.Core.resources.dll.
AOT of image obj\Release\android-arm\aot-in\FSharp.Core.resources.dll failed.
Mono Ahead of Time compiler - compiling assembly C:\src\xamarin-android\bin\TestDebug\temp\BuildBasicApplicationFSharpTrue\obj\Release\android-arm\aot-in\FSharp.Core.resources.dll
AOTID 302CA46D-4000-DCAD-1A9F-642D849470DE
Using profile data file 'C:\Program Files\dotnet\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-ci.dotnet-release-aot-by-default.36\targets\dotnet.aotprofile'
Added 0 methods from profile.
Compiled: …

[One .NET] don't pass satellite assemblies to the AOT compiler

---

build-tools/automation/azure-pipelines.yaml
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Aot.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs
src/monodroid/jni/monodroid-glue.cc
tests/MSBuildDeviceIntegration/Tests/AotProfileTests.cs

I found when I went to update the AOT profile in .NET MAUI:
https://github.com/jonathanpeppers/android-profiled-aot
https://github.com/dotnet/maui/pull/4355
The profiler crashed with:
01-27 11:10:16.119 28922 28922 W monodroid: Creating public update directory: `/data/user/0/com.androidaot.MauiApp1/files/.__override__`
...
01-27 11:10:16.119 28922 28922 W monodroid: Initializing profiler with options: aot:port=9999output=/data/user/0/com.androidaot.MauiApp1/files/.__override__/profile.aotprofile
01-27 11:10:16.119 28922 28922 W monodroid: Looking for profiler init symbol 'mono_profiler_init_aot'? 0x7325b6355c
01-27 11:10:16.119 28922 28922 E mono-prof: Could not create AOT profiler output file 'output.aotprofile': Read-only file system
But the directory was writeable?
adb shell run-as …

[One .NET] fix libmono-profiler-aot.so recording

---

Documentation/guides/OneDotNet.md
build-tools/create-packs/Directory.Build.targets
build-tools/create-packs/vs-workload.in.props
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
tests/MSBuildDeviceIntegration/Tests/BundleToolTests.cs
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs

To improve startup performance for `Release` builds:
1. Default `$(RunAOTCompilation)` to `true`
2. Default `$(AndroidEnableProfiledAot)` to `true`.
Going forward, you would have to explicitly turn these off if you want
them to be off.
We also can drop the `android-aot` workload, and just include the
dotnet/runtime packs in the `android` workload:
https://github.com/dotnet/runtime/blob/c7adf5598f27e59644030ddae4e382cbda74e41e/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.json.in#L29-L40
These packs are already inserted into Visual Studio, so we can rely on
them.
Since the new project options screen evaluates MSBuild, we don't
appear to need to do anything on the UI side:

[One .NET] default to Profiled AOT for Release builds

---

Documentation/guides/messages/xa4233.md
src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets
src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
src/Xamarin.Android.Build.Tasks/Tasks/Generator.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/BindingTests.cs
tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/Xamarin.Android.McwGen-Tests.csproj
tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/java/com/xamarin/example/NamespaceTransform.java

Context: https://github.com/xamarin/java.interop/issues/727
Add an MSBuild equivalent to the `<ns-replace>` metadata feature added in https://github.com/xamarin/java.interop/issues/727.
This takes namespace transforms like:
```xml
<ItemGroup>
<AndroidNamespaceReplacement Include='Androidx' Replacement='AndroidX' />
<AndroidNamespaceReplacement Include='Com' Replacement='' />
<AndroidNamespaceReplacement Include='Com.Google.' Replacement='Google' />
</ItemGroup>
```
And places them into a generated `msbuild-metadata.xml` file that is passed to `generator`:
```xml
<metadata>
<ns-replace source='Androidx' replacement='AndroidX' />
<ns-replace source='Com' replacement='' />
<ns-replace source='Com.Google.' replacement='Google' />
</metadata>
```
Today, this only supports `<ns-replace>` …

[Xamarin.Android.Build.Tasks] Add support for '<AndroidNamespaceReplacement>'.

---

src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

In testing Profiled AOT, I found a problem in "classic"
Xamarin.Android that was working in .NET 6:
1. Build & run a Release build using AOT
2. Enable AOT-related logging via:
adb shell setprop debug.mono.log=all,mono_log_level=debug,mono_log_mask=aot
Notice we are missing messages that AOT is being used! I was not able
to find messages like `libaot-` or `AOT: FOUND method`.
c227042b worked appropriately for .NET 6, because the build ordering is:
1. linker
2. AOT
3. `<GeneratePackageManagerJava/>`
The problem in "classic" Xamarin.Android, is the ordering is
different:
1. linker
2. `<GeneratePackageManagerJava/>`
3. AOT
And so the list of native libraries would not contain any
`libaot-*.dll.so` files.
The difference of ordering, is due to how .NET 6 runs an "inner" build
per …

[Xamarin.Android.Build.Tasks] add libaot-*.dll.so files to dso_cache

---

eng/Version.Details.xml
eng/Versions.props
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets

* Bump to .NET 6.0.200-rtm.22078.8
Changes: https://github.com/dotnet/installer/compare/52d6372...e950d07
Changes: https://github.com/dotnet/linker/compare/d0662ed...70dc7f6
Updates:
* Microsoft.Dotnet.Sdk.Internal: from 6.0.200-rtm.22074.2 to 6.0.200-rtm.22078.8
* Microsoft.NET.ILLink.Tasks: from 6.0.100-1.21519.4 to 6.0.200-1.22069.1
* Downgrade ILLink to 6.0.100
Downgrade the linker reference to use a 6.0.100 version, otherwise we might
end up building Microsoft.Android.Sdk.IlLink.dll with a reference to illink.dll v6.0.200, and
then (trying to) execute on illink.dll v6.0.100, which fails with the
following unhelpful error:
> error ILLink : error IL1027: Custom step 'Xamarin.SetupStep' could not be found
This occurs because illink.dll v6.0.100 fails to load our custom step assembly …

[release/6.0.2xx-preview13] backport latest .NET SDK

---

src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.g.tt
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc

In porting System.Reflection.Emit code in 32cff438, I was considering
our use of `Delegate.CreateDelegate()`. This appears to take up
~2.83ms, when using `dotnet trace` to profile. Can we just cast
instead?
"generator" from xamarin/java.interop generates `internal` delegates
for each Java binding assembly:
_JniMarshal_PP_V
A direct cast wouldn't work, if for example,
`Xamarin.AndroidX.AppCompat.dll` had its own `_JniMarshal_PP_V`, we
can't cast to the one in `Mono.Android.dll`.
To solve this problem we can use `Unsafe.As<T>()` instead:
https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.unsafe.as?view=net-6.0
Testing a `dotnet new maui` app on a Pixel 5, a `Release` build
without AOT:
Before:
02-04 16:03:18.603  1867  2226 I ActivityTaskManager: Displayed …

[Mono.Android] use Unsafe.As<T>() over Delegate.CreateDelegate()

---

build-tools/automation/azure-pipelines.yaml

Context: https://github.com/xamarin/sdk-insertions/blob/1ecc4ae21866d152a9e37465d422de97a8ac1019/templates/common/upload-vs-insertion-artifacts.yml
GitHub commit statuses will also be created for the .NET artifacts,
which will be used by a new VS insertion release pipeline.

[ci] Push .NET artifacts to blob storage

---

.external

Context: https://github.com/xamarin/xamarin-android/pull/6683#issuecomment-1026157337
Changes: https://github.com/mono/mono/compare/a5d1934898bfdf06662cee5799782b09ce8afe5a...148f536b0b463a111a021b960ee3aeaed0cf203b
* mono/mono@148f536b0b4 [2020-02] [AOT] Use .short directive instead of .hword (#21419)
* mono/mono@a6f3e8f179a Avoid an assert in ves_icall_RuntimeFieldInfo_SetValueInternal (#21420)
* mono/mono@3c4f3de377d Add correct InetAccess category to HttpClientTest.Proxy_Disabled test and disable Ping tests
* mono/mono@9f35bf1b807 Add missing handle function enter/return macros (#21407)
* mono/mono@45efaa3b6f9 [interp] Remove hack for nint/nfloat (#21395)

Bump to mono/mono/2020-02@148f536b

---

.external

Fixes: https://devdiv.visualstudio.com/DevDiv/_componentGovernance/112013/alert/6473253?typeId=6317040
Changes: http://github.com/xamarin/monodroid/compare/5b0fab478fa4682034dbbc0cce06748c7dc51474...91b4ef9fcfad5906b0699865afb3e46c383a5710
* xamarin/monodroid@91b4ef9fc: Bump to xamarin/android-sdk-installer/main@58485dee (#1236)

Bump to xamarin/monodroid/main@91b4ef9f

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets

This is no longer needed since https://github.com/dotnet/runtime/pull/53453 fixed the issue this was working around.
Bringing back the original optimization in https://github.com/xamarin/xamarin-android/pull/5605.

Remove InvariantGlobalization workaround

---

src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.g.tt

One performance issue with the existing code:
_JniMarshal_PP_V callback = Unsafe.As<_JniMarshal_PP_V> (dlg);
_JniMarshal_PP_V result = (jnienv, klazz) => {
JNIEnv.WaitForBridgeProcessing ();
try {
callback (jnienv, klazz);
} catch (Exception e) when (_unhandled_exception (e)) {
AndroidEnvironment.UnhandledException (e);
}
};
return result;
In this example, `callback` is "captured", and an intermediate class
is generated to store this data such as
`Android.Runtime.JNINativeWrapper/<>c__DisplayClass5_15`.
A way to do this is:
return new _JniMarshal_PP_V (Unsafe.As<_JniMarshal_PP_V> (dlg).Wrap_JniMarshal_PP_V);
Where `Wrap_JniMarshal_PP_V` is an extension method:
internal static void Wrap_JniMarshal_PP_V (this _JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
{ …

[Mono.Android] avoid capturing variables in JNINativeWrapper

---

src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.g.tt

Context: https://github.com/microsoft/dotnet-podcasts
Running the MAUI podcast sample, shows several `_JniMarshal_`
delegates we could list:
Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PP_I': Int32 n_GetItemCount(IntPtr, IntPtr)
Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PP_I': Int32 n_GetOpacity(IntPtr, IntPtr)
Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PP_Z': Boolean n_CanScrollVertically(IntPtr, IntPtr)
Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PPI_L': IntPtr n_CreateFragment_I(IntPtr, IntPtr, Int32)
Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PPI_I': Int32 n_GetItemViewType_I(IntPtr, IntPtr, Int32)
Falling back to System.Reflection.Emit for delegate …

[Mono.Android] add a few more _JniMarshal_ built-in delegates

---

build-tools/automation/azure-pipelines.yaml
build-tools/create-packs/Directory.Build.targets

We've seen some failures in recent attempts to push package info to the
Maestro Build Asset Registry.  Fix this by using the correct OutputPath
when running `<PushManifestToBuildAssetRegistry/>`.

[ci] Swap Maestro and artifact status ordering

---

.external
Configuration.props
build-tools/scripts/JavaCallableWrappers.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs
src/java-runtime/java-runtime.targets

Context: https://github.com/actions/virtual-environments/blob/5cdc2e5f50ec21dbac1d3b475ae0fe364f4a2d12/images/linux/Ubuntu2004-Readme.md#environment-variables-3
Context: https://github.com/actions/virtual-environments/blob/5cdc2e5f50ec21dbac1d3b475ae0fe364f4a2d12/images/win/Windows2022-Readme.md#environment-variables-2
Context: https://github.com/actions/virtual-environments/blob/5cdc2e5f50ec21dbac1d3b475ae0fe364f4a2d12/images/macos/macos-11-Readme.md#environment-variables-2
Build and test against Android SDK and NDK paths set by Azure Pipelines
hosted images if those paths exist.

[build] Use Azure Pipelines vars for Android SDK/NDK paths

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/6732
A problem occurs when you do:
> dotnet new android
> dotnet build -c Release -r android-arm64
> dotnet build -c Release -r android-arm64
After the second build with no changes, MSBuild targets run that
shouldn't -- and you end up with an `.apk` that is missing all the
AOT'd assemblies!
What is happening is the `Inputs` to the `_RemoveRegisterAttribute`
have the wrong path of a file:
Input file "obj\Release\net6.0-android\android-arm64\android-arm64\link.flag" does not exist.
Removing `-r android-arm64` from the above commands solve the problem!
The issue here being:
1. We have an "outer" build where normally `$(RuntimeIdentifiers)`
(plural) triggers an "inner" build for each RID.
2. Each inner build runs ILLink & AOT …

[One .NET] fix incremental AOT builds

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/6628
The following will fail:
> dotnet new android
> dotnet build -p:PublishTrimmed=true
with:
error XABLD7023: System.IO.DirectoryNotFoundException: Could not find a part of the path 'obj\Debug\net6.0-android\android-arm\linked\shrunk\UnnamedProject.dll'.
at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
at …

[One .NET] fix PublishTrimmed=true for Debug builds

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/commercial-build.yaml
build-tools/automation/yaml-templates/run-installer.yaml
build-tools/automation/yaml-templates/run-msbuild-device-tests.yaml
build-tools/automation/yaml-templates/run-msbuild-mac-tests.yaml
build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml
build-tools/automation/yaml-templates/setup-test-environment.yaml

Context: https://github.com/xamarin/provisionator/pull/447
Context: https://github.com/xamarin/yaml-templates/pull/172
Context: https://github.com/xamarin/UITools/blob/a59d5dbc9ba48b7ffba40156dba3314d8fb12de3/Designer/build/automation/stages/validate-android-designer.yml#L14
Context: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1469705
The Windows build and test job for the designer has been updated in
xamarin/UITools, and the tests have been re-enabled.  The macOS tests
have also been temporarily disabled.
Update our Designer test jobs to mirror their changes.
A new `provisionatorChannel` parameter has been added which will allow
builds to be manually queued against provisionator PRs for testing
purposes.

[ci] Enable Android Designer tests on Windows

---

build-tools/automation/azure-pipelines-oss.yaml

Fixes our OSS Linux build by ensuring that newer versions of the `g++`
and `gcc` compilers are used when needed.

[ci] Update compiler version variables for OSS Linux build

---

README.md

Add Windows d17.1 aka.ms link.
Remove Mac d17.0 aka.ms link, as there is no stable VSMac 17.0 or 17.1.  The previous link was to a pre-release build that contains the incorrect `0.1.2.0` `Java.Interop.dll`.

[README] Add d17.1 aka.ms link.

---

Directory.Build.props

Context: https://docs.microsoft.com/dotnet/core/compatibility/sdk/6.0/write-reference-assemblies-to-obj
Context: https://github.com/dotnet/msbuild/issues/7355
Context: https://github.com/xamarin/java.interop/pull/949
Using the latest internal builds of Visual Studio, you hit the build
error when building xamarin-android:
error MSB4018: The "CreateFrameworkListFile" task failed unexpectedly. [C:\src\xamarin-android\build-tools\create-packs\Microsoft.Android.Ref.proj] [C:\src\xamarin-android\build-tools\create-packs\Microsoft.Android.Sdk.proj]
error MSB4018: System.IO.FileNotFoundException: Could not find file 'C:\src\xamarin-android\bin\Release\lib\xamarin.android\xbuild-frameworks\Microsoft.Android\net6.0-android32\ref\Mono.Android.dll'.
This was a breaking change in MSBuild:
> ### Old …

[build] set $(ProduceReferenceAssemblyInOutDir)=True

---

build-tools/automation/azure-pipelines.yaml
build-tools/provisioning/xcode.csx

Context: https://eng.ms/docs/initiatives/executive-order/executive-order-requirements/executiveorderoncybersecurity/buildinfraops
Moves our offical macOS build to the `internal-macos-11` build pool as
part of ongoing security and compliance efforts.
The `VSEng-Xamarin-RedmondMac-Android-Untrusted` pool will continue to
be used for PR builds for performance reasons, and it will be updated to
macOS 11 over the next week or two.
We will also now provision and use Xcode 13.2 when running on macOS 11
machines.

[ci] Use `internal-macos-11` for official macOS builds 

---

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/LinkDesignerBase.cs
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/RemoveResourceDesignerStep.cs
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs

The current implementation of the `RemoveResourceDesignerStep` does not
work under .NET 6. This is mostly down to the fact that we didn't
`override` the require methods to make it work in that environment.
This PR also reworks the `RemoveResourceDesignerStep` to split some
of the functionality out into a new base class. This new base class will
be used in the future by the Resource Assembly linker step. Since much of
the code is identical.
Apk size difference in a Basic Android Application. This is a single App Head project with no additional libraries or Nuget references.
```
-         596 assemblies/assemblies.blob
-         760 lib/x86/libaot-DotNet6AndroidBasic.dll.so
-         764 …
```

[Xamarin.Android.Build.Tasks] Enable 'AndroidLinkResources' for .NET 6 Release Applications

---

src/Mono.Android/Android.Runtime/JNIEnv.cs
src/Mono.Android/Java.Interop/TypeManager.cs

Context: https://github.com/microsoft/dotnet-podcasts
In working on #6766 and reviewing `dotnet trace` output, I found time
being spent in `JNIEnv.GetObjectArray()`:
17.09ms Mono.Android!Java.Interop.TypeManager.n_Activate(intptr,intptr,intptr,intptr,intptr,intptr)
...
4.96ms Mono.Android!Android.Runtime.JNIEnv.GetObjectArray
In this case, it is taking an array of parameters and calling a
constructor. A lot of the time we are calling empty constructors!
Reviewing `JNIEnv.GetObjectArray()` we could add a check if the array
is of length 0 and return `Array.Empty<object>()`. I also found one
other place doing `new Type[0]` we can fix while we're at it.
After the change, I instead get:
2.56ms Mono.Android!Android.Runtime.JNIEnv.GetObjectArray
I'm not able to see a noticeable difference in …

[Mono.Android] JNIEnv.GetObjectArray() can use Array.Empty<T>()

---

Configuration.props

Context: https://dl-ssl.google.com/android/repository/repository2-3.xml
Context: https://github.com/xamarin/xamarin-android/pull/6469
Context: https://github.com/xamarin/xamarin-android/pull/6764
Bump `$(XAPlatformToolsVersion)`=32.0.0, which is the current
non-RC `platform-tools` Android SDK package version.
We are already on the latest `build-tools` package version, and on
the latest NDK r23.* version.  (There are NDK r24 and r25 versions,
but we don't support them yet; see also PR #6469, #6764.)

[build] Bump Android tools versions

---

src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/6777
Building a Xamarin.Android application with:
-p:Configuration=Release -p:AndroidEnableProfiledAot=true -p:EnableLLVM=true
Fails with:
[aot-compiler stdout] Executing the native linker: "C:\ProgramData\Microsoft\AndroidNDK\android-ndk-r22b\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-ld.gold" -Bsymbolic -shared -o obj\Release\110\aot\arm64-v8a\libaot-FastExpressionCompiler.dll.so.tmp "obj\Release\110\aot\arm64-v8a\FastExpressionCompiler.dll\temp-llvm.o" obj\Release\110\aot\arm64-v8a\FastExpressionCompiler.dll\temp.s.o "-LC:\ProgramData\Microsoft\AndroidNDK\android-ndk-r22b\toolchains\llvm\prebuilt\windows-x86_64\lib\gcc\aarch64-linux-android\4.9.x" "-LC:\ProgramData\Microsoft\AndroidNDK\android-ndk-r22b\toolc …

[Xamarin.Android.Build.Tasks] fix $(EnableLLVM) + $(AndroidEnableProfiledAot)

---

Configuration.props
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets

Currently, if you build with `net6.0-android` and leave off the
number, it defaults to API 31. Let's bump this to API 32, Android 12L.
I also fixed the `Inputs` of the `_GenerateSupportedPlatforms` target,
so it will rerun when `Configuration.props` changes.
We will likely need to coordinate the API level installed by various
Visual Studio installers.

[One .NET] default $(TargetPlatformVersion) to 32

---

.external

Changes: https://github.com/xamarin/monodroid/compare/2c3e786bb5c9292e0b1fb196cb70148171f5549e...5e2b25ea1f299213f4b176f417dd26231c897eda
* xamarin/monodroid@5e2b25ea1: Bump to xamarin/androidtools/main@01d05424 (#1241)
Changes: https://github.com/xamarin/xamarin-android-tools/compare/bbe85df4251fe6c2ccaa7fc3fd03b28e5649fff0...f0b3abdb7600bc47be8696bab2c170d849283f06
* xamarin/xamarin-android-tools@f0b3abd: Revert "[Xamarin.Android.Tools.AndroidSdk] Update SDK component for API-32 (#156)"
We do not yet have all of our proverbial ducks in a row to bump these
Android SDK versions.  Revert until we're fully ready to bump.

Bump to xamarin-android-tools@f0b3abdb, monodroid@5e2b25ea

---

Configuration.props
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets

This reverts commit 7cc3cbb5e8cf8c6dd8b0d671ce91a1d2a19969a7.
We need to time this better so the IDEs can install API 32 by default
at the same time.
Conflicts:
Configuration.props

Revert "[One .NET] default $(TargetPlatformVersion) to API-32"

---

src/Mono.Android/Mono.Android.csproj
src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs

We noticed that .NET 6 MAUI apps include `OldAndroidSSLSocketFactory` even after being linked.
Since API 21 is the minimum, we can exclude this class from `Mono.Android.dll` in .NET 6.

[Mono.Android] remove OldAndroidSSLSocketFactory usage in .NET 6

---

.vscode/tasks.json
Configuration.props
Directory.Build.props
Documentation/building/unix/instructions.md
Documentation/building/windows/instructions.md
Documentation/workflow/DevelopmentTips.md
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/GenerateWixFile.cs
build-tools/automation/yaml-templates/apk-instrumentation.yaml
build-tools/automation/yaml-templates/run-dotnet-preview.yaml
build-tools/automation/yaml-templates/run-nunit-tests.yaml
build-tools/automation/yaml-templates/setup-test-environment.yaml
build-tools/scripts/Paths.targets
build-tools/scripts/UpdateApkSizeReference.ps1
build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

Moves the "sandbox" installation of `dotnet` that we use for testing
purposes into the repo at bin/$(Configuration)/dotnet.  While this could
lead to increased disk usage across some local build environments it
provides a handful of benefits.
Every time `make prepare` or `-t:Prepare` runs we remove this directory
and start fresh.  Having it in a single "global" location is not too
desirable when working out of multiple checkout locations (fork vs
non-fork for example), or when using multiple build configurations at
the same time.
This sandbox can also now more easily be removed with a `git clean` if
desirable, we had no "automatic" way to remove the ~/android-toolchain
installation location previously.
This move will also make it easier to eventually structure our .NET
build output in a …

Move dotnet sandbox to build output directory

---

build-tools/installers/create-installers.targets
src/Mono.Android/Mono.Android.targets

Partially fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1467817
A warning is printed when building with `-p:MonoSymbolArchive=true`:
Warning: Directory obj\Release\120\android\assets contains Java.Interop.dll but no debug symbols file was found.
It turns out we are missing `Java.Interop.pdb` from our installer?
I went ahead and also added `Mono.Posix.pdb` and
`System.EnterpriseServices.pdb`, since we appear to have these in
build output.

[installer] add missing .pdb files to Xamarin.Android

---

Directory.Build.props
eng/Versions.props

Context: http://aka.ms/maui-schedule
Context: https://github.com/xamarin/xamarin-android/blob/7e8cc34989bfcb5bd58cb857013ba67273c00c79/Documentation/guides/HowToBranch.md
Context: https://github.com/xamarin/xamarin-android/tree/release/6.0.2xx-preview14
We branched xamarin-android/release/6.0.2xx-preview14, to reflect the
next release of .NET MAUI Preview 14. It will remain on the .NET
6.0.200 version band.
xamarin-android/main becomes RC 1. main will also be targeting the
.NET 6.0.300 version band, so we should become 31.0.300.

$(AndroidPackVersionSuffix)=rc.1; net6 is 31.0.300.rc.1

---

build-tools/scripts/DotNet.targets
build-tools/scripts/maui.proj

Using xamarin-android/main, the command to install .NET MAUI fails
with:
> msbuild Xamarin.Android.sln -t:InstallMaui -p:MauiVersion=6.0.200-preview.14.5055
...
error NU1101: Unable to find package Microsoft.NET.Sdk.Maui.Manifest-6.0.300. No packages exist with this id in source(s):...
The problem being is there is not a Microsoft.NET.Sdk.Maui.Manifest
6.0.300 pack yet.
We should instead infer 6.0.200 from `-p:MauiVersion`:
<MauiVersionBand>$([System.Text.RegularExpressions.Regex]::Match($(MauiVersion), `^\d+\.\d+\.\d`))00</MauiVersionBand>
We use a similar regex to infer the .NET SDK version band.
This should work more appropriately going forward.

[build] -t:InstallMaui can infer the version band

---

src/Mono.Android/Android.Runtime/JNIEnv.cs
src/Mono.Android/Java.Lang/Class.cs

Code paths using `JNIEnv.CallStaticObjectMethod` are using the "old"
way of doing Java.Interop. One such case is found when profiling the
.NET Podcast app:
15.09ms Mono.Android!Android.Runtime.JNIEnv.FindClass
6.25ms Mono.Android!Android.Runtime.JNIEnv.CallStaticObjectMethod
This is called in one place by:
6.16ms Mono.Android!Android.Content.Intent..ctor(Android.Content.Context,System.Type)
If we instead define on `Java.Lang.Class`:
internal static JniPeerMembers Members => _members;
We could access `Java.Lang.Class.Members.StaticMethods`, however in
this case we get the method ID from:
internal static unsafe void Initialize (JnienvInitializeArgs* args)
{
// ...
mid_Class_forName = args->Class_forName;
If we use the `IntPtr` here to create:
new JniMethodInfo (args->Class_forName, …

[Mono.Android] JNIEnv.FindClass() can use StaticMethods.CallStaticObjectMethod()

---

src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.g.tt

Profiling `dotnet new maui` is hitting:
39.66ms Mono.Android!Android.Runtime.JNINativeWrapper.CreateDelegate(System.Delegate)
28.35ms System.Private.CorLib!System.Reflection.Emit.DynamicMethod..ctor(...)
Which is due to:
03-08 08:53:30.436 23350 23350 D monodroid-assembly: Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PPLZ_V': Void n_OnFocusChange_Landroid_view_View_Z(IntPtr, IntPtr, IntPtr, Boolean)
It appears new usage of `OnFocusChange()` is prompting us to include
`_JniMarshal_PPLZ_V` in our list of "built-in" delegates.
After this change, we don't hit the SRE code path anymore:
2.80ms Mono.Android!Android.Runtime.JNINativeWrapper.CreateDelegate(System.Delegate)

[Mono.Android] add "built-in" delegate for _JniMarshal_PPLZ_V

---

src/Mono.Android/Android.Runtime/AndroidRuntime.cs
src/Mono.Android/Android.Runtime/JNIEnv.cs

Based on the comments:
https://github.com/xamarin/xamarin-android/pull/6708#discussion_r801077205
Viewing `dotnet trace` output for the .NET Podcast app, we actually see:
122.71ms (0.26%) Mono.Android!Android.Runtime.JNIEnv.RegisterJniNatives(intptr,int,intptr,intptr,int)
5.13ms (0.01%) System.Private.CoreLib!System.String.Ctor(char*,int,int)
Once per type that enters RegisterJniNatives(), we were allocating a
potentially large `System.String` that contains every Java method that a
C# type overrides. If we use `ReadonlySpan<char>`, we can avoid this
allocation for each call.
After this change, instead I see:
1.23ms System.Private.CoreLib!System.String.Ctor(char*,int,int)
This call happens earlier in the method, which it doesn't look like we
can use `ReadonlySpan<char>` for:
string …

[Mono.Android] avoid RegisterJniNatives() string allocation

---

src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.g.tt

Context: https://github.com/dotnet/maui/commit/ceaff6b3a6598c66b7b2c6a9f9fd3404fa17edf5
Since the "Shell" navigation pattern was added to the default `dotnet
new maui` template, we started hitting the System.Reflection.Emit code
path again:
03-09 14:20:35.358 6711 6711 D monodroid-assembly: Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PPLF_V': Void n_OnDrawerSlide_Landroid_view_View_F(IntPtr, IntPtr, IntPtr, Single)
So then I checked the .NET Podcast app:
03-09 14:28:35.675  7278  7278 D monodroid-assembly: Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PPLF_V': Void n_OnDrawerSlide_Landroid_view_View_F(IntPtr, IntPtr, IntPtr, Single)
03-09 14:28:35.811  7278  7278 D monodroid-assembly: Falling back to System.Reflection.Emit for delegate …

[Mono.Android] add more "built-in" delegates for MAUI+Shell

---

src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/pinvoke-override-api.cc
tests/MSBuildDeviceIntegration/Tests/InstallTests.cs

Context: https://github.com/xamarin/xamarin-android/pull/6818
`dotnet/mono` disables gathering of performance counter statistics for
the JIT and, in effect, a largely empty file is generated by the
`mono_counters_dump` runtime function.
Disable support for dumping the counters in .NET6+ builds of the
runtime.

Disable gathering of JIT statistics on .NET6+

---

Documentation/guides/profiling.md

When recording JIT times, we didn't have instructions to set
/manifest/application/@android:debuggable="true". This is a crucial
step for Release builds.
I also noted that `counters.txt` is not useful in .NET 6. It is
mostly empty text such as:
It might be worth removing support for this in .NET 6, but let's just
comment that it isn't useful for now.

[docs] improve instructions for obtaining methods.txt

---

.external

Changes: https://github.com/xamarin/monodroid/compare/b5c07f8a785a776bc22786802f4221c583211ded...e451ea986b27cdfb965df07c1f2ea74fa14f33c2
* xamarin/monodroid@e451ea986: Bump to xamarin/androidtools/main@38f1ce12 (#1244)

Bump to xamarin/monodroid/main@e451ea98

---

Documentation/guides/building-apps/build-properties.md
build-tools/create-packs/SignList.xml
build-tools/installers/create-installers.targets
build-tools/installers/unix-binutils.projitems
build-tools/xaprepare/xaprepare/Application/NDKTool.cs
build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
build-tools/xaprepare/xaprepare/Steps/Step_InstallGNUBinutils.Unix.cs
build-tools/xaprepare/xaprepare/Steps/Step_InstallGNUBinutils.Windows.cs
build-tools/xaprepare/xaprepare/Steps/Step_InstallGNUBinutils.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs
src/Xamarin.Android.Build.Tasks/Tasks/StripNativeLibraries.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Utilities/NativeAssemblyGenerator/NativeAssemblyGenerator.cs
src/Xamarin.Android.Build.Tasks/Utilities/NdkTools/WithClangNoBinutils.cs
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Aot.apkdesc
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Profiled-Aot.apkdesc

Context: https://github.com/xamarin/xamarin-android/issues/6685
Context: fd5f31cc89648957243f31ba8fd7af7fccba11e4
So far, `Xamarin.Android` has been using a GNU Binutils toolchain to compile and link native assembler code we generate
during application build.  Unfortunately, Binutils have a problem with certain filename encodings on Windows and so we
decided to switch to an LLVM-based toolchain which handles such file names without issues.
However, since Mono/dotnet AOT expects a GNU build chain, it was necessary to implement a GNU Assembler (`gas`) wrapper
around the LLVM `llvm-mc` assembler, so that command lines used by the Mono AOT compiler keep working fine.
Since LLVM utilities are multi-target by default and, unlike GNU Binutils, they don't need separate builds of every utility,
we …

Use new LLVM-based Xamarin.Android toolchain

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/6729
Fixes: https://github.com/xamarin/xamarin-android/issues/6841
The `dotnet new maui` template enables:
<UseInterpreter Condition="'$(Configuration)' == 'Debug'">True</UseInterpreter>
This should really just belong in each platform SDK instead of the
template.
Additionally, I found the interpreter improves startup times. For
example Release builds on a Pixel 5 would get:
| Application        | JIT Time(ms) | Interpreter Time(ms) | Profiled AOT Time(ms) |
|------------------- | ------------:| --------------------:| ---------------------:|
| dotnet new android |        244.1 |                210.1 |                 165.5 |
| dotnet new maui    |        887.6 |                717.2 |                 469.9 |
Source: …

[Xamarin.Android.Build.Tasks] default $(UseInterpreter) for Debug mode

---

Documentation/guides/messages/README.md
src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
src/Xamarin.Android.Build.Tasks/Tasks/CheckForInvalidResourceFileNames.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/CheckForInvalidResourceFileNamesTests.cs

Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1333264/
Android Resources MUST start with a Letter or an underscore. They cannot
start with any other character. We should raise a specific error for this
so it is obvious to the user what the issue is.

Raise an error if the Resource starts with an Invalid Character.

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets

Context: https://github.com/dotnet/sdk/issues/19891
In 3f052b5f, I added a workaround to exclude
`Microsoft.AspNetCore.App.Runtime.linux` packages from Android builds.
This was a problem where the `android` RID "inherited" from the
`linux` RID, and so we ended up with unintended packages restored.
This was fixed in https://github.com/dotnet/installer/pull/12702, so
we should remove this workaround.

[Xamarin.Android.Build.Tasks] remove Microsoft.AspNetCore.App.Runtime.linux workaround

---

.vscode/tasks.json
Documentation/building/unix/instructions.md
Documentation/building/windows/instructions.md
dotnet-local.cmd
dotnet-local.sh

Lets add a couple of `dotnet-local` scripts which will allow us to
use the in-tree dotnet install easier. Also update the VSCode tasks
to make use of this new script.

Add `dotnet-local` scripts to make using in tree dotnet easier.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.DesignTime.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets

Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1440274
The design time build was not taking into account the `AndroidGenerateResourceDesigner` property value. 
As a result we would always get a `Resource.designer.cs` file generated in the designtime directory.
So lets turn off the designtime build if that property is set. 
Also note set a defaut for `AndroidGenerateResourceDesigner` in legacy so that it is always `true`. 
This is to get around some issues under legacy where `AndroidGenerateResourceDesigner` was not 
defined. This is because the designtime build tasks and targets are shared between both systems.

DesignTime Builds should honour AndroidGenerateResourceDesigner.

---

src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.Legacy.cs
src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs

AndroidMessageHandler.SetupRequest returns a Task so overrides can be async. The base implementation checks the object hasn't been disposed. However, it is doing this check using Task.Run, which queues a work item to the ThreadPool. This is unnecessary and causes more threads to be spawned than what is needed.
The fix is to just check for disposed synchronously and return a completed Task.
Fix #6854

Remove unnecessary background Task in AndroidMessageHandler

---

src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.g.tt

Context: https://github.com/dotnet/maui/commit/680f1fbbdd9fa8e5e4e3f1614d798213d36eace9
`dotnet new maui` is logging:
03-24 16:21:42.193 16360 16360 D monodroid-assembly: Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PPLLL_V': Void
n_OnComplete_Ljava_lang_Boolean_Landroid_graphics_drawable_Drawable_Ljava_lang_Runnable_(IntPtr, IntPtr, IntPtr, IntPtr, IntPtr)
So we can add a case for `_JniMarshal_PPLLL_V`:
Before:
48.18ms Mono.Android!Android.Runtime.JNINativeWrapper.CreateDelegate(System.Delegate)
After:
3.13ms Mono.Android!Android.Runtime.JNINativeWrapper.CreateDelegate(System.Delegate)
This was `dotnet trace` output running on a Pixel 5.

[Mono.Android] add another "built-in" JNINativeWrapper

---

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetAotArguments.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/MakeBundleTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/NdkUtilTests.cs
tests/Mono.Android-Tests/Properties/AndroidManifest.xml
tests/Mono.Android-Tests/Runtime-AppBundle/Properties/AndroidManifest.xml

Changes: https://github.com/android/ndk/wiki/Changelog-r24#changes
The most interesting changes from Xamarin.Android's point of view:
* GDB has been removed. Use LLDB instead. Note that ndk-gdb uses 
LLDB by default, and Android Studio has only ever supported LLDB.
* Jelly Bean (APIs 16, 17, and 18) is no longer supported. The
minimum OS supported by the NDK is KitKat (API level 19).
* Non-Neon devices are no longer supported. A very small number of
very old devices do not support Neon so most apps will not notice
aside from the performance improvement.
* Additional Apple M1 support: 
* LLVM tools are now universal binaries.

Bump NDK to r24

---

Directory.Build.props

We just branched:
* https://github.com/xamarin/xamarin-android/tree/release/6.0.3xx
* https://github.com/xamarin/xamarin-android/tree/release/6.0.3xx-rc1
xamarin-android/main will be 33.0.100-preview.4
xamarin-android/release/6.0.3xx will be 32.0.300-rc.2
xamarin-android/release/6.0.3xx-rc1 will be 32.0.300-rc.1

$(AndroidPackVersionSuffix)=preview.4; net7 is 33.0.100.preview.4

---

src/Mono.Android/Android.Runtime/JNIEnv.cs
tests/Mono.Android-Tests/Android.Runtime/JnienvArrayMarshaling.cs

Context: https://github.com/dotnet/maui/blob/79f2fef9397bbfe2f6aa1527e40f933712a5d2ad/src/Core/src/Platform/Android/ColorStateListExtensions.cs#L50-L51
When running a `dotnet new maui` app, we noticed the log:
W monodroid: typemap: failed to map managed type to Java type: System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e (Module ID: 8e4cd939-3275-41c4-968d-d5a4376b35f5; Type token: 33554653)
W monodroid-assembly: typemap: called from
W monodroid-assembly: at Android.Runtime.JNIEnv.TypemapManagedToJava(Type )
W monodroid-assembly: at Android.Runtime.JNIEnv.GetJniName(Type )
W monodroid-assembly: at Android.Runtime.JNIEnv.FindClass(Type )
W monodroid-assembly: at Android.Runtime.JNIEnv.NewArray(Array , Type )
W monodroid-assembly: at …

[Mono.Android] improve performance of new Java arrays

---

build-tools/automation/azure-pipelines-release-trigger.yaml
build-tools/automation/azure-pipelines.yaml

Context: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers
A new pipeline has been added to capture build information from the
Xamarin.Android pipeline, which can than be processed by old UI-style
release definitions.
The Xamarin.Android pipeline often has known or acceptable test failures
in the builds that we want to release, and old UI-style release
definitions will not run against partially failed builds.  This new
pipeline avoids that limitation as it will always be green.  The new
pipeline will also publish information about the Xamarin.Android build
that triggered it, which will allow an old UI-style release definition
to download artifacts from the Xamarin.Android build using the
[DownloadPipelineArtifact][1] task.
A [pipeline resource][0] controls …

[ci] Add job to run after Xamarin.Android pipeline

---

build-tools/automation/azure-pipelines.yaml
build-tools/provisioning/xcode.csx

Context: https://eng.ms/docs/initiatives/executive-order/executive-order-requirements/executiveorderoncybersecurity/buildinfraops
Moves our offical macOS build to the `internal-macos-11` build pool
as part of ongoing security and compliance efforts.
The `VSEng-Xamarin-RedmondMac-Android-Untrusted` pool will continue
to be used for PR builds for performance reasons, and it will be
updated to macOS 11 over the next week or two.
We will also now provision and use Xcode 13.2 when running on
macOS 11 machines.

[ci] Use internal-macos-11 for official macOS builds (#6736)

---

dotnet-local.cmd
dotnet-local.sh

The current `docnet-local` scripts relied on being run from the
same directory. This change uses the script location to run the
exists checks and to execute the `dotnet` binary. This way we can
run this from any directory.

Update `dotnet-local` script to work from any directory.

---

build-tools/automation/azure-pipelines-release-trigger.yaml
build-tools/automation/azure-pipelines.yaml

Context: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline?view=azure-pipelines#the-pipeline-resource-metadata-as-predefined-variables
Commit 7982895c added a new pipeline that can be used to trigger release
definitions, however the automatic trigger was not fully testable until
after it was merged.
Update the new pipeline to use the correct variable names that are set
when it is automatically triggered by the Xamarin.Android pipeline.

[ci] Fix variable names for release triggering build

---

Documentation/guides/messages/xa2000.md
src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/6875
The dotnet/runtime team would like to remove the
`MONO_GC_BRIDGE=bridge-implementation=old` backend in .NET 7.
Check for usage of `MONO_GC_BRIDGE=bridge-implementation=old`, and
emit an XA2000 warning if found.

[Xamarin.Android.Build.Tasks] XA2000 for bridge-implementation=old

---

tests/Mono.Android-Tests/System.Net/NetworkInterfaces.cs
tests/Mono.Android-Tests/System.Net/SslTest.cs

Context: https://github.com/dotnet/runtime/issues/35836
These tests were disabled back when some HTTP and SSL-related features weren't working yet in .NET 6.
Let's enable these now, since they appear to pass for me locally.

[tests] enable additional runtime tests for .NET 6

---

build-tools/automation/yaml-templates/setup-test-environment.yaml
src/Mono.Android/Android.Runtime/JNIEnv.cs
src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/EnvironmentHelper.cs
src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfig.cs
src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGenerator.cs
src/monodroid/jni/application_dso_stub.cc
src/monodroid/jni/cpp-util.hh
src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/xamarin-app.hh

With the .NET6 Mono runtime we are able to use the
`[UnmanagedCallersOnly]` attribute to mark certain methods as directly
callable from native code.  This is faster than going through
`mono_runtime_invoke`, as there is nearly no marshaling of parameters
performed.  Since `Android.Runtime.JNIEnv.Initialize` is called only by
our native runtime, we can use this approach here.
Additionally, remove some reflection use by looking up and saving
managed tokens of the `Android.Runtime.JNIEnv` class as well as its two
methods, `Initialize` and `RegisterJniNatives`.  This saves time by
allowing us to not look for the above methoods via their names at
startup.
Time savings aren't spectacular in the overall startup time, but the
"native to managed" phase (essentially a call to `JNIEnv.Initialize`) …

[NET6] Call JNIEnv.Initialize directly, via a function pointer

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml
build-tools/automation/yaml-templates/setup-test-environment.yaml
build-tools/automation/yaml-templates/setup-ubuntu.yaml

Related: https://github.com/xamarin/xamarin-android/pull/6598
Our Windows and Linux pools are "stateful" and are only wiped fresh
every 7 or 3 days respectively.  This allows them to service jobs more
quickly when demand is high.  Now that we are starting to build and test
against .NET 7 previews we should enable .NET SDK clean up, as these
pools will be shared across .NET 6 and .NET 7 branches.

[ci] Remove extra .NET SDKs on Windows and Linux

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs

Temporarily ignore this test to reduce noise on PR builds while it is
being fixed.  The test has seemingly been partially invalidated by
commit 5efda9d69, however it is still passing against Classic
Xamarin.Android on Windows.  More investigation is required as to why
we see different stripping results when using a combination of the `-s`,
`no-write-symbols`, and `nodebug` flags with different toolchains.

[Xamarin.Android.Build.Tests] Ignore NoSymbolsArgShouldReduceAppSize

---

src/Mono.Android/Android.Runtime/JNIEnv.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/EnvironmentHelper.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleLegacy.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsLegacy.apkdesc
src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrGenerator.cs
src/Xamarin.Android.Build.Tasks/Utilities/NativeTypeMappingData.cs
src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs
src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingReleaseNativeAssemblyGenerator.cs
src/monodroid/jni/application_dso_stub.cc
src/monodroid/jni/embedded-assemblies.cc
src/monodroid/jni/embedded-assemblies.hh
src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/platform-compat.hh
src/monodroid/jni/util.hh
src/monodroid/jni/xamarin-app.hh

Up until now, Xamarin.Android used string comparison when finding a
Managed type corresponding to a given Java type.  Even though the
strings were pre-sorted at build time, multiple string comparisons
costed more time than necessary.  To improve comparison speed, this
commit implements lookups based on hash values (using the `xxHash`
algorithm) calculated for all the Java names at build time.  This allows
us to process each Java type once at run time - to generate its hash.
After that, the hash is used to binary search an array of hashes and the
result (if found) is an index into array with the appropriate
Java-to-Managed mapping.
This change also allows us to move Java type names from the mapping
structure (`TypeMapJava`) to a separate array.  We used to keep Java
type name in the …

Speed up java-to-managed typemap lookups

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Some tests are failing on xamarin-android/main, such as:
bin\Release\net6.0-android\com.xamarin.dotnetbuild-Signed.apk should contain assemblies/System.Linq.dll
Expected: True
Trying locally, this fails because:
1. It is a `Debug` build
2. Fast Deployment is off
These only fail on the Windows lane because it doesn't include our
internal bits from xamarin/monodroid. If Fast Deployment was used (as
on other test lanes), then this assertion would get skipped.
To solve this problem, let's just assert against a *different* file.
If `System.Linq.dll` is sometimes arhitecture-specific, let's just
assert `Mono.Android.dll` instead. The tests now pass.

[tests] fix DotNetBuild tests

---

build-tools/create-packs/Directory.Build.targets
build-tools/create-packs/Microsoft.Android.Sdk.proj
build-tools/scripts/DotNet.targets
build-tools/scripts/XABuildConfig.cs.in
build-tools/xaprepare/xaprepare/Application/KnownProperties.cs
build-tools/xaprepare/xaprepare/Application/Properties.Defaults.cs.in
build-tools/xaprepare/xaprepare/Steps/Step_GenerateFiles.cs
build-tools/xaprepare/xaprepare/xaprepare.targets
src/Mono.Android/Mono.Android.csproj
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/in/Microsoft.Android.Sdk.BundledVersions.in.targets
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

The Microsoft.Android `@(KnownFrameworkReference)` will now delcare
targeting and runtime pack metadata that is based on the
`$(TargetPlatformVersion)` of the project file.  The only exception to
this rule is when '$(TargetPlatformVersion)' == '31.0'; in this case the
project will use an API 31 ref pack with API 32 runtime packs.  The
inline `Microsoft.Android.Sdk.BundledVersions.targets` file content
has been moved into a separate file to improve the readability of the
`@(KnownFrameworkReference)` element.
Breakdown of supported `$(TargetFramework)` -> ref/runtime pack used:
| `$(TargetFramework)` | Targeting Pack | Runtime Pack |
| -------------------- | -------------- | ------------ |
| net6.0-android     | Microsoft.Android.Ref.31 | Microsoft.Android.Runtime.32 |
| net6.0-android31.0 …

[One .NET] Fix targeting API 33, build API 31 ref pack

---

src-ThirdParty/System.Diagnostics.CodeAnalysis/DynamicallyAccessedMembersAttribute.cs
src/Mono.Android/Java.Interop/JavaConvert.cs
src/Xamarin.Android.NamingCustomAttributes/Xamarin.Android.NamingCustomAttributes.projitems

Fixes: https://github.com/xamarin/xamarin-android/issues/6895
In some cases an app with a single `HttpClient` request can crash with:
android.runtime.JavaProxyThrowable: System.ArgumentNullException: ArgumentNull_Generic Arg_ParamName_Name, method
at System.Delegate.CreateDelegate(Type , Object , MethodInfo , Boolean , Boolean )
at System.Delegate.CreateDelegate(Type , MethodInfo , Boolean )
at System.Delegate.CreateDelegate(Type , MethodInfo )
at Java.Interop.JavaConvert.GetJniHandleConverterForType(Type )
at Java.Interop.JavaConvert.GetJniHandleConverter(Type )
at Java.Interop.JavaConvert.FromJniHandle[IList`1](IntPtr , JniHandleOwnership , Boolean& )
at Java.Interop.JavaConvert.FromJniHandle[IList`1](IntPtr , JniHandleOwnership )
at Android.Runtime.JavaDictionary`2[[System.String, …

[Mono.Android] preserve public methods for GetJniHandleConverterForType

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/variables.yaml
build-tools/installers/unix-binutils.projitems
build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
build-tools/xaprepare/xaprepare/Steps/Step_InstallGNUBinutils.cs

Changes: (LLVM) https://discourse.llvm.org/t/llvm-14-0-1-release/61700
Updates LLVM version to just-relased version 14.0.1 and now includes
Windows PDB files in the distribution.

Update our LLVM toolchain

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props

Context: https://github.com/xamarin/xamarin-android/pull/6598
It seems like it will still be a bit before we get main on .NET 7
In the meantime, we took many Maestro bumps on the `release/6.0.3xx` branch.
Let's bring all those forward so we have a newer .NET in main.

[main] port dotnet maestro bumps to main

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/commercial-build.yaml
build-tools/create-packs/Microsoft.Android.Sdk.proj
build-tools/create-packs/SignVerifyIgnore.txt
build-tools/installers/sign-content.proj

When looking at the [Xamarin.Android pipeline analytics][0] I noticed
that the Prepare Classic Release stage accounted for a very large
percentage of our overall failures.
To help address this I've moved the vsix signing step into a new job
that runs on a Windows agent, where the signing tasks are hopefully more
resilient.  This seems to have sped up signing performance dramatically
as well, as a step that would take upwards of an hour or more on macOS
now seems to be completing in less than 10 minutes on the Windows
MicroBuild agent pool.
I've also added the `MicroBuildCodesignVerify` task in a couple of
places to validate the signing status of the vsix and msi files we ship.
[0]: https://devdiv.visualstudio.com/DevDiv/_pipeline/analytics/stageawareoutcome?definitionId=11410&contextType=b …

[ci] Sign vsix in separate job, add CodesignVerify task

---

src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.g.tt

Context: https://github.com/dotnet/maui/pull/6133#discussion_r851405705
`dotnet new maui` is logging on startup:
Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PPJ_Z': Boolean n_ContainsItem_J(IntPtr, IntPtr, Int64)
This was probably introduced at:
https://github.com/dotnet/maui/commit/003744a722f3cbbe91284c617a76db1ab7660c51#diff-e8c9ed1d734bd47f7e75df934b4090d131ee6391aeeaa0cb84afb5de18c180f8R71
Then I tried `dotnet new maui-blazor`:
Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PPIL_Z': Boolean n_OnKeyDown_ILandroid_view_KeyEvent_(IntPtr, IntPtr, Int32, IntPtr)
Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PPLL_L': IntPtr n_ShouldInterceptRequest_Landroid_webkit_WebView_Landroid_webkit_WebResourceRequest_(IntPtr, …

[Mono.Android] add JNINativeWrapper "built-in" delegates for RC 2

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetXamarinProject.cs
tests/MSBuildDeviceIntegration/Tests/BundleToolTests.cs

If you do:
dotnet build -c Release -r android-arm64 -p:AndroidLinkTool=r8
You'll get the warning:
warning XA4304: ProGuard configuration file 'obj\Release\android-arm64\android-arm64\proguard\proguard_project_references.cfg' was not found.
That path has two `android-arm64` in it!
Additionally, I found this problem was hidden in our testing
infrastructure because we set `$(AppendRuntimeIdentifierToOutputPath)`
to `false` in several tests... After removing this, I could write a
test that reproduces this issue.
The fix for the issue is that `$(_InnerIntermediateOutputPath)` needs
to check if the outer build has a single `$(RuntimeIdentifier)`. If
so, we don't need to append a RID in that path.

[Xamarin.Android.Build.Tasks] fix --runtime and r8 at the same time

---

build-tools/xaprepare/xaprepare/xaprepare.csproj

Context: https://devdiv.visualstudio.com/DevDiv/_componentGovernance/112013/alert/2548260?typeId=6317076
I noticed that xaprepare was pulling in an out of date version of
`System.Private.Uri` through its `System.Net.Http` PackageReference.
Adding an explicit reference to version 4.3.2 of System.Private.Uri
should fix a few component governance issues.  I also think that the
`Microsoft.NETFramework.ReferenceAssemblies` reference should no longer
be needed now that the project is targeting `net6.0`.

[xaprepare] Add ref to System.Private.Uri 4.3.2

---

src/Xamarin.Android.Build.Tasks/Tasks/JavaToolTask.cs
src/Xamarin.Android.Build.Tasks/Tasks/ManifestMerger.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/6634
Adding a `[Service]` with `[IntentFilter]` requires you to specify
`[Service(Exported=true)]` in API 30. Newer versions of
`manifestmerger.jar` enforce this at build time -- instead of
previously you would only hit the error during `adb install`.
Unfortunately, Xamarin.Android displays the error message poorly:
D : \agent\1\s\src\Essentials\samples\Samples\obj\Debug\net6.0-android\AndroidManifest.xml error :  [D:\agent\1\s\src\Essentials\samples\Samples\Essentials.Sample.csproj]
The error text is literally `D`!
To fix this:
1. Make `JavaToolTask.CodeErrorRegEx` overridable.
2. Provide a `Regex` to match the error messages that
`manifestmerger.jar` gives for `AndroidManifest.xml` files.
We now get appropriate error messages with …

[Xamarin.Android.Build.Tasks] improve <ManifestMerger/> error messages

---

src/Mono.Android.Export/Mono.Android.Export.csproj

The `Microsoft.Android.Ref` and `Microsoft.Android.Runtime` packs always
include the latest stable version:
<_AndroidRuntimePackAssemblies Include="$(XAInstallPrefix)xbuild-frameworks\Microsoft.Android\net6.0-android$(AndroidLatestStableApiLevel)\Mono.Android.Export.dll" />
We shouldn't need to build this more than once.

[build] Only build .NET Mono.Android.Export once

---

Documentation/guides/LayoutCodeBehind.md
Documentation/guides/building-apps/build-items.md
Documentation/guides/building-apps/build-properties.md
src/Xamarin.Android.Build.Tasks/Resources/LayoutBinding.cs
src/Xamarin.Android.Build.Tasks/Tasks/CalculateLayoutCodeBehind.cs
src/Xamarin.Android.Build.Tasks/Tasks/GenerateLayoutBindings.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/CodeBehindTests.cs
tests/CodeBehind/BuildTests/AnotherMainActivity.cs
tests/CodeBehind/BuildTests/CodeBehindBuildTests.NET.csproj
tests/CodeBehind/BuildTests/CodeBehindBuildTests.csproj
tests/CodeBehind/BuildTests/MainActivity.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/6893
Context: 92cd68c7beb3a26dab55957b2e061faf6cdc1d89
Context: https://github.com/xamarin/AndroidX/blob/628cf049e0ef61e140cb17600df16ed801449814/source/AndroidXTargets.cshtml#L36
When:
1. The [`$(AndroidFragmentType)`][0] MSBuild property is set, *and*
2. The [`$(AndroidGenerateLayoutBindings)`][1]=True, *and*
3. There is a Layout XML file which has an `id`, *and*
4. Define `__HAVE_ANDROIDX__` C# symbol.
then [`LayoutBinding.cs`][2] (92cd68c7) fails to compile.
Repro:
1. `dotnet new android`
2. Edit `Resources/layout/activity_main.xml` so that the
`<TextView/>` has `android:id="@+id/text_view"`:
<TextView
android:id="@+id/text_view"
android:layout_width="wrap_content" …

Fix LayoutBinding under AndroidX.

---

build-tools/scripts/PrepareWindows.targets

After merging commit b5ce08d4 we started seeing a new issue during
prepare on Windows:
xaprepare -> C:\a\_work\1\s\build-tools\xaprepare\xaprepare\bin\Release\net6.0\xaprepare.dll
Could not execute because the specified command or file was not found.
Possible reasons for this include:
* You misspelled a built-in dotnet command.
* You intended to execute a .NET program, but dotnet-C:\a\_work\1\s\build-tools\scripts\..\xaprepare\xaprepare\bin\Release\\xaprepare.dll does not exist.
* You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
C:\a\_work\1\s\build-tools\scripts\PrepareWindows.targets(34,5): error MSB3073: The command "dotnet "C:\a\_work\1\s\build-tools\scripts\..\xaprepare\xaprepare\bin\Release\\xaprepare.dll" --no-emoji …

[build] Add Directory.Build.props to PrepareWindows.targets

---

src/Microsoft.Android.Sdk.ILLink/PreserveLists/System.Private.CoreLib.xml

Fixes: https://github.com/xamarin/xamarin-android/issues/6626

Workaround FirstChanceExceptionEventArgs being trimmed

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs

If you attempt to use r8 in a `dotnet new maui` project:
> dotnet new maui
> dotnet build -f net6.0-android -c Release -p:AndroidLinkTool=r8
Running the app crashes with:
java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList...
This is listed in the `AndroidManifest.xml`:
<provider android:name="androidx.startup.InitializationProvider" android:authorities="com.companyname.foo.androidx-startup" android:exported="false" tools:node="merge">
<meta-data android:name="androidx.lifecycle.ProcessLifecycleInitializer" android:value="androidx.startup" />
<meta-data android:name="androidx.emoji2.text.EmojiCompatInitializer" android:value="androidx.startup" />
</provider>
So that brings up the questions:
1. How does this work in Android …

[Xamarin.Android.Build.Tasks] fix r8 and aapt_rules.txt

---

src/Xamarin.Android.Build.Tasks/Tasks/GetAotArguments.cs

Context: https://releases.llvm.org/14.0.0/tools/lld/docs/ReleaseNotes.html#elf-improvements
Context: 16bbf6f0b0cd49f96f73197d28e8faf31aa9e499
After switching to LLVM 14 we noticed that all `arm64` apps which use
AOT, crash with the following assertion from the Mono runtime:
* Assertion at /__w/1/s/src/mono/mono/mini/tramp-arm64.c:53, condition `((ins >> 24) & 0x1f) == 0x10' not met
After investigation, it turns out that one of the LLVM 14 changes for
the `aarch64` architecture in the `lld` linker was an optimization which
modifies generated code in the following fashion (`-` is the "good"
code, `+` is the "bad" one):
-   13a44: 30 01 00 b0          adrp    x16, 0x38000 <.text+0x148>
-   13a48: 10 e2 3e 91          add     x16, x16, #4024         // =4024
+   13a44: 1f 20 03 d5 …

[AOT] Fix for a compatibility issue between AOT and LLVM 14

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/apk-instrumentation.yaml
build-tools/scripts/TestApks.targets
samples/VSAndroidAppProxy.csproj

The test configurations for Mono.Android.NET_Tests have been updated to
reflect recent changes in default settings for Release apps.  The Aab
and Aot configurations don't make much sense anymore, as they are both
enabled by default.  These have been replaced with NoAab and NoAot.  A
default Debug configuration has also been added.  The `<RunTestApp/>`
target will now use the `<Install/>` target from the product to allow
the fast dev path to be exercised here as well.

[ci] Improve Mono.Android.NET_Tests configurations

---

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/MacOS.cs

Our macOS Azure Pipelines agents recently updated their brew install of
git causing version detection and installation to fail:
Installing git
| ==> Downloading https://ghcr.io/v2/homebrew/core/git/manifests/2.36.0
| ==> Downloading https://ghcr.io/v2/homebrew/core/git/blobs/sha256:5739e703f9ad34dba01e343d76f363143f740bf6e05c945c8f19a073546c6ce5
| ==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:5739e703f9ad34dba01e343d76f363143f740bf6e05c945c8f19a073546c6ce5?se=2022-04-22T07%3A30%3A00Z&sig=wRs9k0qfZuGMtVfu4PUL%2FB8VV1fR28Hka%2FyOGMP%2Bqg8%3D&sp=r&spr=https&sr=b&sv=2019-12-12
| ==> Pouring git--2.36.0.big_sur.bottle.tar.gz
| The formula built, but is not symlinked into /usr/local
stderr | Error: The `brew link` step did not complete successfully
| Could …

[xaprepare] Allow using git from $PATH

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/variables.yaml

The $(DotNetStableTargetFramework) and $(DotNetTargetFramework) yaml
variables added in commit b5ce08d4 have been moved into to the variables
template.  This will allow all pipelines to access these variables.

[ci] Move TargetFramework vars to variables.yaml

---

Documentation/guides/building-apps/build-properties.md
src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/EnvironmentHelper.cs
src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfig.cs
src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGenerator.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
src/monodroid/jni/application_dso_stub.cc
src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/xamarin-app.hh

Backports: https://github.com/xamarin/xamarin-android/pull/6940
Fixes: https://github.com/xamarin/xamarin-android/issues/6935
Context: https://github.com/dotnet/runtime/pull/67024
Add support for enabling lazy loading of AOTd assemblies and their
associated shared libraries, when targeting .NET6+.
The feature is enabled by default when AOT is enabled for `Release`
builds and can be disabled by setting the new
`$(AndroidAotEnableLazyLoad)` MSBuild property to `false`.
Performance gains are obvious, but their scale depends on where we look.
Results of running a Hello World MAUI app on Pixel 6 Pro, with:
See PR for full timing details.
With:
* `$(RuntimeIdentifier)`=android-arm64
* `$(AndroidEnablePreloadAssemblies)`=False
* `$(AndroidUseAssemblyStore)`=True, …

Enable lazy loading of AOTd assemblies

---

src/Microsoft.Android.Templates/android/AndroidManifest.xml

Context: https://github.com/dotnet/maui/issues/6576
Context: https://github.com/dotnet/maui/pull/6673
Debug builds on Android automatically add the `INTERNET` permission,
because otherwise debugging wouldn't work! This definitely adds some
confusion if you switch to a `Release` build and start getting
exceptions in your `HttpClient` calls.
We should just add the `INTERNET` premission to the Android templates,
as nearly every modern app will use the internet. Customers can simply
remove the permission if they don't want it.

[templates] add INTERNET permission

---

build-tools/installers/create-installers.targets

The `CreateMultiDexMainDexClassList` and `Proguard` tasks that rely on
`proguard.jar` are only used in classic Xamarin.Android.  We should not
need to ship proguard files in the .NET packs/installers.

[build] Exclude proguard files from .NET packs

---

src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs

When using the `AllowAutoRedirect` feature of `AndroidMessageHandler` to automatically follow 3xx redirects, the cookies that are returned together with the redirection are not processed. If the redirection target requires the cookies returned by the first request, the call will fail.
This change fixes this behavior and always processes the cookies before the redirection takes place. Fixes #3954.

Parse cookies on redirect

---

build-tools/automation/azure-pipelines.yaml
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs

Context: https://github.com/dotnet/runtime/issues/68734
Context: https://github.com/xamarin/XamarinComponents/pull/1368
We have a newer Xamarin.Build.Download package that shouldn't suffer
from the duplicate `ZipArchive.CreateEntry()` issue were are hitting
in .NET 7.
Let's use it, and enable previously failing tests.

[tests] update to Xamarin.Build.Download 0.11.2

---

Directory.Build.props
build-tools/create-packs/Directory.Build.targets
build-tools/scripts/XAVersionInfo.targets

Make our .NET pack versioning stable by updating it to 32.0.301.  The
third number will continue to increase as new commits land in this
branch.  32.0.301.0 will be used for the MSI generation tooling as it
expects a four part version.

[release/6.0.3xx] Bump to 32.0.301

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/in/Microsoft.Android.Sdk.BundledVersions.in.targets

We can't use `TrimEnd` here since it will use the `TrimEnd(char[])` overload so it'd trim **all** `.` and `0` chars from the end, not the whole string `.0`. 
This results in `30.0` being trimmed to just `3` instead of the expected `30`.
See https://github.com/dotnet/sdk/issues/25370 for more details, I first thought it's a dotnet SDK issue but it turned out to be an XA issue.
/cc @pjcollins

Fix TrimEnd for _AndroidTargetingPackId in Microsoft.Android.Sdk.BundledVersions.in.targets

---

Directory.Build.props
build-tools/automation/azure-pipelines.yaml
build-tools/create-packs/Directory.Build.targets

We should now have access to use the `dnceng-dotnet7` connection in DevDiv's AzDO instance.

[build] enable the dotnet7 feed

---

src/monodroid/jni/timing-internal.hh

Context: 1efa0cf46c9079fc06669a4434f597faf47504af
It appears that Apple clang in Xcode 13.2 still has problems
with support for C++20 concepts, resulting in problems building
the recently committed timing code:
timing-internal.hh(433,4): error GD3D6EBB4: no matching function for call to 'calculate_interval'
calculate_interval (event.start, event.end, interval, total_ns);
This could also be fixed by using `std::remove_reference_t`, but
it would make the code unnecessarily less readable.  With Android
being the primary target and compliation for it working properly,
I think it's OK to disable concepts for macOS in this instance.

Disable C++20 concepts when building for macOS

---

src/monodroid/jni/timing-internal.hh

Apple Clang from Xcode 13.2 appears to have a bug which causes it to
fail with the following error when concepts in `timing-internal.hh` are
used:
timing-internal.hh(436,4): error GB0476C6D: no matching function for call to 'calculate_interval' [/Users/peter/source/xamarin-android/src/monodroid/monodroid.csproj]
calculate_interval (event.start, event.end, interval, total_ns);
^~~~~~~~~~~~~~~~~~
timing-internal.hh:264:28: note: candidate template ignored: constraints not satisfied [with P = xamarin::android::internal::TimingEventPoint, I = xamarin::android::internal::TimingInterval]
force_inline static void calculate_interval (P const& start, P const& end, I &result, uint64_t& total_ns) noexcept
^
timing-internal.hh:260:12: note: because 'xamarin::android::internal::TimingEventPoint' does …

[monodroid] Fix compilation with Xcode 13.2

---

Documentation/building/unix/instructions.md
Documentation/building/windows/instructions.md
Makefile
build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml
build-tools/automation/yaml-templates/setup-test-environment.yaml
build-tools/automation/yaml-templates/variables.yaml
build-tools/create-packs/Directory.Build.targets
build-tools/scripts/Packaging.mk
build-tools/scripts/PrepareWindows.targets
build-tools/scripts/msbuild.mk

Removes the need to have a .NET 7 preview installed globally to build.
A .NET 6 install is required to build and run xaprepare, which will
provision a .NET 7 preview build used for further building and testing.
Instructions to build on macOS remain unchanged:
make prepare
make all
or
make jenkins
Instructions to build on Windows have been updated:
dotnet msbuild -t:Prepare Xamarin.Android.sln
dotnet-local.cmd -t:PackDotNet Xamarin.Android.sln
The `dotnet msbuild` command is recommended as it will not attempt a
restore.  This will allow the `Prepare` target to run against a .NET 6
install, even though `Xamarin.Android.sln` contains projects that target
net7.0.  Otherwise, attempts to dotnet build any target belonging to
`Xamarin.Android.sln` with .NET 6 will fail during restore:
Project …

[build] Use local .NET preview to build net7.0

---

build-tools/automation/azure-pipelines.yaml

Mac doesn't use `-m:1` when calling the prepare step, so Windows shouldn't need it either.
It doesn't really save any time, but it will help ensure we don't add something that requires it in the future.

[ci] Remove `-m:1` from Windows `-t:Prepare` step.

---

build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs

Context: https://github.com/dotnet/install-scripts/issues/15
Context: https://dot.net/v1/dotnet-install.sh
Context: https://dot.net/v1/dotnet-install.ps1
We've been installing dotnet versions using the Unix shell and Windows
powershell scripts, which work fine.  However, they do not cache the
downloaded archive and therefore we end up re-downloading the same
archive over and over again on CI servers as well as locally.
Additionally, if one finds themselves without internet connection,
there's no way to install the required version of dotnet.
The installation scripts don't provide a way to cache the payloads and
they appear to be in maintenance mode, so there's rather no chance to
add caching support to them.
Instead of relying on the scripts, we can do the downloading and
installation …

[xaprepare] Download and install dotnet ourselves, with caching

---

Configuration.props
build-tools/create-packs/Directory.Build.targets
build-tools/create-packs/Microsoft.NET.Sdk.Android.proj
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/in/Microsoft.Android.Sdk.BundledVersions.in.targets
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.targets
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/TestEnvironment.cs
tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs

We currently have a hard dependency between:
* `Xamarin.Android.Build.Tasks.dll`
* `libmonodroid.so`
The design for building a `net6.0-android` app with a .NET 7 SDK
results in us using a .NET 7 `Xamarin.Android.Builds.Tasks.dll` and a
.NET 6 `libmonodroid.so`. This crashes with:
05-06 09:32:31.206  8713  8713 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "java_name_width" referenced by "/data/app/~~8CHtXY8wK4g7s9VcOLTQEg==/com.microsoft.net6.helloandroid-cUUhwuQls7TRb6JdBsbPdg==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libmonodroid.so"...
To solve this problem:
* Define `$(AndroidNet6Version)` to specify our .NET 6 GA `32.0.301`
build that is released.
* Add an alias for a `Microsoft.Android.Sdk.$(HostOS).NET6` workload
pack that loads a .NET 6 …

[One .NET] support building net6.0-android apps in .NET 7

---

build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs

We are seeing the Prepare step fail on windows machines on CI. This
is because `dotnet` is interpreting the Errors we are emitting when
downloading the `dotnet` sdk as actual errors. This results in the
`dotnet` process exiting with an ExitCode of -1.
The thing is these are not really errors they are warnings. So lets
just use `LogWarning` instead to get around this issue.

 Fix Windows Build Error on Prepare

---

Directory.Build.props
build-tools/installers/create-installers.targets

Changes: https://github.com/xamarin/xamarin-android-tools/compare/fc3c2ac...20f6112
Changes: https://github.com/xamarin/LibZipSharp/compare/2.0.3...2.0.4
* Add support for writing `android:roundIcon` to Android manifest
* Bump LibZipSharp to 2.0.4
Other changes:
* The paths to `libZipSharpNative.dll` changed to `x86` and `x64`.

Bump to xamarin/xamarin-android-tools/main@20f6112

---

build-tools/installers/create-installers.targets
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json

Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1544836
I'll manually test this when the build is done. It might be worth writing a doc on testing on `win-arm64`.

[One .NET] add win-arm64 support to the workload

---

build-tools/create-packs/Microsoft.NET.Sdk.Android.proj

Downloading our current .NET 7 workloads, extracting them to a folder,
and installing them doesn't work. Trying to update the manifest
results in:
dotnet workload update --source C:\some\local\folder
...
Failed to update the advertising manifest microsoft.net.sdk.android: microsoft.net.sdk.android.manifest-7.0.100-preview.5 is not found in NuGet feeds C:\some\local\folder"..
It appears we also need `-preview.5` in the `$(PackageId)` when using
the `7.0.100-preview.5.22273.1` .NET SDK, for this to work correctly.
We can use `$(DotNetSdkManifestsFolder)` to include the additional
info.
Our build in xamarin-android/main is working, because we copy our
manifests to folders directly.
With this change in place, we get a hilarious file name: …

[workload] manifest should be Microsoft.NET.Sdk.Android.Manifest-7.0.100-preview.5

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Context: https://github.com/xamarin/xamarin-android/pull/6988
One problem we hit when trying to build `net6.0-android` projects from
a .NET 7 SDK & Android workload, was that we ended up importing *two*
`AutoImport.props` files.
These are imported for any pack in `WorkloadManifest.json` declared as
an SDK:
"packs": {
"Microsoft.Android.Sdk": {
"kind": "sdk",
So the way this has to work:
* Any `<ItemGroup>` must be conditioned so that
`$(TargetFrameworkVersion)` matches the .NET SDK version expected.
* Never use an MSBuild property in `AutoImport.props`. Properties are
evaluated in the first pass and `$(TargetFrameworkVersion)` will be
blank...
I removed `$(_DefaultJavaSourceJarPattern)` and just duplicated the
value where it was used.
I used `[MSBuild]::VersionEquals()` for all checks, …

[workload] AutoImport.props supports future .NET versions

---

build-tools/automation/azure-pipelines.yaml

This reverts commit 45997f29c4da1ab0e791f5c0eceb6aff2f2c98e8.
Our build has been broken since commit fd47b027, as the recently updated
MSI tooling throws an error when a workload pack is missing:
nuget-msi-convert\convert-v3\convert.proj(76,5): Error : System.IO.FileNotFoundException: Could not load file or assembly 'D:\a\_work\1\a\nugets\Microsoft.Android.Sdk.Windows.32.0.301.nupkg'. The system cannot find the file specified.
File name: 'D:\a\_work\1\a\nugets\Microsoft.Android.Sdk.Windows.32.0.301.nupkg'
We don't yet have a good solution for how to handle VS insertions for
the .NET 6 SDK packs that our workload now depends on.  Revert the MSI
tooling update to fix the build while this is being investigated.

Revert "[ci] Use nuget-msi-convert/job/v3.yml (#7032)"

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs

Context: 3f052b5f
Context: https://github.com/dotnet/sdk/issues/25679
If you use our .NET 7 workload, and do:
dotnet restore
It fails with:
C:\src\foo\foo.csproj error NU1102: Unable to find package Microsoft.NETCore.App.Host.linux-arm with version (= 7.0.0-preview.5.22271.4)
- Found 88 version(s) in nuget.org [ Nearest version: 7.0.0-preview.4.22229.4 ]
- Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\src\foo\foo.csproj]
C:\src\foo\foo.csproj error NU1102: Unable to find package Microsoft.NETCore.App.Host.linux-arm64 with version (= 7.0.0-preview.5.22271.4)
- Found 88 version(s) in nuget.org [ Nearest version: 7.0.0-preview.4.22229.4 ]
- Found 0 version(s) in Microsoft Visual Studio Offline Packages [C:\src\foo\foo.csproj]
C:\src\foo\foo.csproj …

[One .NET] remove Microsoft.NETCore.App.Host.linux-*

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.AvailableItems.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AndroidLibraries.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/7040
It appears we were missing a test case of:
1. `dotnet new androidlib`
2. Add an `.aar` file
3. `dotnet pack`
4. Assert that `lib\net6.0-android31.0\MyAndroidLibrary.aar` exists in
the `.nupkg` output
We instead end up with "weird" output in the `.nupkg` like:
lib\net6.0-android31.0\MyDotNetAssembly.dll
lib\net6.0-android31.0\MyDotNetAssembly.xml
lib\net6.0-android31.0\MyDotNetAssembly.aar
content\MyAndroidLibrary.aar
contentFiles\any\net6.0-android31.0\MyAndroidLibrary.aar
`MyDotNetAssembly.aar` would contain any `.jar` files or
`AndroidResource` files packed inside. However, *other* `.aar` files
are supposed to sit next to `MyDotNetAssembly.dll`.
It was surprisingly difficult to work alongside NuGet's MSBuild
targets to get …

[One .NET] pack AndroidLibrary .aar files in .nupkg

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.AvailableItems.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AndroidLibraries.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Backporting to `release/6.0.4xx`, there were lots of merge conflicts in the tests.
Fixes: https://github.com/xamarin/xamarin-android/issues/7040
It appears we were missing a test case of:
1. `dotnet new androidlib`
2. Add an `.aar` file
3. `dotnet pack`
4. Assert that `lib\net6.0-android31.0\MyAndroidLibrary.aar` exists in
the `.nupkg` output
We instead end up with "weird" output in the `.nupkg` like:
lib\net6.0-android31.0\MyDotNetAssembly.dll
lib\net6.0-android31.0\MyDotNetAssembly.xml
lib\net6.0-android31.0\MyDotNetAssembly.aar
content\MyAndroidLibrary.aar
contentFiles\any\net6.0-android31.0\MyAndroidLibrary.aar
`MyDotNetAssembly.aar` would contain any `.jar` files or
`AndroidResource` files packed inside. However, *other* `.aar` files
are supposed to sit next to …

[release/6.0.4xx] [One .NET] pack AndroidLibrary .aar files in .nupkg

---

build-tools/automation/yaml-templates/setup-test-environment.yaml

Context: https://github.com/xamarin/xamarin-android/pull/6880
Partially backports 16680700.
Update our `DotNetCoreCLI@2` use in `setup-test-environment.yaml` to
work around a "bizarre" CI error:
"C:\Program Files\dotnet\dotnet.exe" restore
C:\a\_work\1\s\xamarin-android\src\Xamarin.Android.Build.Tasks\Tests\Xamarin.Android.Build.Tests\Xamarin.Android.Build.Tests.csproj
--configfile C:\a\_work\1\Nuget\tempNuGet_5963650.config
--verbosity Detailed
--configfile C:\a\_work\1\s\xamarin-android/NuGet.config
-bl:C:\a\_work\1\s\xamarin-android/bin/TestRelease/restore-Xamarin.Android.Build.Tests.binlog
Option '--configfile' only accepts a single argument but 2 were provided.
It appears that `restoreArguments: --configfile …` can no longer be
used with the [`DotNetCoreCLI@2`][0] task, and instead …

[release/6.0.4xx] fix designer tests

---

tests/MSBuildDeviceIntegration/Resources/LinkDescTest/HttpClientTest.cs
tests/MSBuildDeviceIntegration/Resources/LinkDescTest/MainActivityReplacement.cs

Context: https://github.com/dotnet/runtime/issues/67402
This is a new regression test that should catch a problem like dotnet/runtime#67402 going forward.
This code runs in a class library that gets trimmed. `Mono.Android-Tests` has many tests including usage of `HttpWebRequest`, that I believe avoids the problem.

[tests] add linker test that makes HttpClient request

---

build-tools/installers/create-installers.targets

Installer packaging has been improved to only include `libMono.Unix.so`
on Linux and `libMono.Unix.dylib` on macOS.  The `Mono.Unix.dll.config`
file has also been excluded from the .NET SDK as `<dllmap>` is not
supported there.

[build] Package host specific Mono.Unix library

---

build-tools/create-packs/Directory.Build.targets
build-tools/create-packs/vs-workload.in.props

As part of supporting .NET 6 projects with our .NET 7 workload, we will
want to be able to insert both .NET 6 and .NET 7 workload packs into VS.
Historically, we have replaced the [VS manifest file][0] every time we
update our workload.  For .NET 7 we will likely want two VS manifests
side by side, one which contains our .NET 6 packs and one for .NET 7.
Add a version to the .NET VS manifest file to support this potential
side by side scenario.
[0]: https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/.corext/Configs/dotnet-workloads-components.json&version=GBmain&line=10&lineEnd=11&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

[build] Version .NET VS manifest file

---

Xamarin.Android.sln
build-tools/api-merge/merge-configuration.xml
build-tools/api-xml-adjuster/api-xml-adjuster.csproj
build-tools/create-android-api/create-android-api.csproj
src/Mono.Android/Mono.Android.csproj
src/Mono.Android/Mono.Android.targets

*One* issue with running `dotnet build Xamarin.Android.sln` without `-m:1` is that it attempts to run our Android API extraction process multiple times simultaneously.  This results in file locking issues:
```
C:\code\xamarin-android\src\Mono.Android\Mono.Android.targets(409,5): "C:\code\xamarin-android\src\Mono.Android\..\..\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\class-parse.exe C:\Users\jopobst\android-toolchain\sdk\platforms\android-26\android.jar -platform=26 -parameter-names="C:\code\xamarin-android\src\Mono.Android\..\..\src\Mono.Android\Profiles\api-26.params.txt" -o="C:\code\xamarin-android\src\Mono.Android\..\..\bin\BuildDebug\api\api-26.xml.class-parse"" failed with code: -532462766  Error output: 
Unhandled Exception: System.IO.IOException: The process cannot …
```

[Mono.Android] Move API xml file generation to dedicated project.

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets
src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Javac.targets
src/Xamarin.Android.Build.Tasks/Tasks/JavaSourceUtils.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Resources/JavaSourceTestExtension.java
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Resources/JavaSourceTestInterface.java
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/ResourceData.cs

Import parameter name information when `%(AndroidJavaSource.Bind)`
is True.
This isn't particularly noticeable when `%(AndroidJavaSource.Bind)`
files are classes, but it *is* noticeable for Java *interfaces*, as
e.g. `javac -parameters` *doesn't* retain method parameter names in
interface methods.
The only reliable way to get parameter name information on interfaces
is to parse the `.java` files, i.e. by using `<JavaSourceUtils/>`.
Update the `_CompileBindingJava` target to use `<JavaSourceUtils/>`
to extract parameter names (and Javadoc) from `@(AndroidJavaSource)`
files with `%(AndroidJavaSource.Bind)`=True, and provide this
parameter name information to the `_ExportJarToXml` target, by way of
the internal `@(_JavaSourceJavadocXml)` item group.

[Xamarin.Android.Build.Tasks] @(AndroidJavaSource) & parameter names

---

build-tools/automation/azure-pipelines-nightly.yaml

Commit e52c1315 broke our nightly runs of Mono.Android-Tests as it moved
the Java.Interop prepare step out of xaprepare.  Fix the nightly test
runs by preparing Java.Interop before building Mono.Android-Tests.

[ci] Add JI prepare step to nightly test runs

---

build.cmd

Our 'build.cmd' file was using `msbuild`. We have switched over to
using `dotnet` for most of our CI systems. So we should switch this
over as well.

Update 'build.cmd' to use 'dotnet build'.

---

src/monodroid/jni/mono_android_Runtime.h

Context: e1af9587bb98d4c249bbc392ceccc2b53ffff155
e1af9587 was the first commit in a series to implement marshal
methods.  Part of that were two JNI function declarations declared in
the `src/jni/monodroid/mono_android_Runtime.h` header file that
I thought would be silently ignored.  I missed the fact that the file
is regenerated whenever `monodroid.csproj` is built and so every time
that happens one would find themselves with a modifications that
weren't part of their work.
Remove the declarations to fix the issue.

[monodroid] Remove unused JNI function declarations

---

Configuration.props
Documentation/building/unix/instructions.md
Documentation/building/windows/instructions.md
Makefile
build-tools/automation/azure-pipelines.yaml
build-tools/create-packs/Directory.Build.targets
build-tools/create-packs/Microsoft.Android.Ref.proj
build-tools/create-packs/Microsoft.Android.Runtime.proj
build-tools/create-packs/Microsoft.Android.Sdk.proj
build-tools/create-packs/Microsoft.NET.Sdk.Android.proj
build-tools/installers/create-installers.targets
build-tools/scripts/BuildEverything.mk
build-tools/scripts/DotNet.targets
dotnet-local.cmd
dotnet-local.sh
src/Microsoft.Android.Templates/Directory.Build.targets
src/Mono.Android.Export/Mono.Android.Export.csproj
src/Mono.Android/Mono.Android.csproj
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
src/monodroid/monodroid.targets

Build steps have been updated to circumvent the need to pack and install
.nupkgs to test local build changes against .NET 7 +.
Projects which produce content required for our Ref and Runtime packs
have been updated to copy their outputs to a `packs` directory.  This
directory follows the structure that dotnet workload resolution expects.
The version of these local packs has been simplified compared to CI, it
will not include commit distance or any semver metadata.
A new `ConfigureLocalWorkload` target has been added to run a couple of
extra steps that are required to set up the local workload.  This
includes generating workload manifest, target, and FrameworkList files,
installing mono/runtime dependencies, and creating the templates pack.
A new `BuildDotNet` target has been added …

[build] Copy .NET build output to ref/runtime dirs

---

dotnet-local.sh

Set the `FULLROOT` property to the full version of the path
where the `dotnet-local.sh` script is, not to the current
directory.  This allows invoking the script without having to
cd into the `xamarin-android` repository first.

[build] Fix the `dotnet-local.sh` script path resolution

---

build-tools/xaprepare/xaprepare/Steps/Step_DetermineAzurePipelinesTestJobs.cs

Context: https://github.com/xamarin/xamarin-android/issues/7091
We have a couple of BCL tests that seemingly started to fail after
commit e1af9587 landed.  Unfortunately PR #7004 didn't run the BCL test
stage, which may have caught this issue sooner.  Update the triggers for
the BCL tests to include changes to src/monodroid.

[ci] Run BCL tests on src/monodroid changes

---

src/Mono.Android.Export/Mono.Android.Export.csproj
src/Mono.Android.Export/Properties/AssemblyInfo.cs

Eliminate warnings from `Mono.Android.Export.csproj`.
- Fix 27 warnings of `warning CA1416: This call site is reachable on all platforms.` by specifying that this assembly relies on the `Android21.0` platform because it relies on `Mono.Android.dll`.
- Suppress 9 warnings of `warning CS0649: Field 'CodeTry.condition' is never assigned to, and will always have its default value null` and similar because this is "external" code we have imported from Mono, and I doubt we're going to fix them.

[Mono.Android.Export] Fix build warnings.

---

Directory.Build.props
build-tools/automation/azure-pipelines.yaml
build-tools/create-android-api/create-android-api.csproj
build-tools/scripts/BuildEverything.mk
src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj
src/Mono.Android/Mono.Android.csproj
src/Mono.Android/Mono.Android.targets
src/manifestmerger/manifestmerger.csproj
src/r8/r8.csproj
tools/javadoc2mdoc/javadoc2mdoc.csproj

There are several known issues that cause errors when attempting to `dotnet build Xamarin.Android.sln` without `-m:1`.  With these fixes, the build *seems* to be buildable without `-m:1`.  
Testing conducted is 4 consecutive CI builds without errors.  Note that due to the unpredictability of race-condition errors appearing, this is not a guarantee that all issues are fixed.  We will simply have to run with this and fix any additional errors as they appear.
Fixes:
- Use `create-android-api` to build `JNIEnv.g.cs` only once, since it is not TargetFramework dependent.  Prevents sharing violation when multiple `Mono.Android.csproj` builds attempt to create it simultaneously.
- `System.IO.IOException: The process cannot access the file …

[Xamarin.Android.sln] Fix issues preventing parallel builds.

---

src/monodroid/jni/embedded-assemblies.cc

Fixes: https://github.com/xamarin/xamarin-android/issues/7091
Context: https://github.com/xamarin/xamarin-android/commit/e1af9587bb98d4c249bbc392ceccc2b53ffff155
e1af958 refactored a handful of `MonoImage` loading methods and
during that process, I mistakenly made reference-only assemblies
to be loaded in a "full" way which broke a number of BCL tests.
Fix the issue by making sure reference-only assemblies are really
loaded as such.

Fix loading of refonly assemblies for "classic" apps

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/EnvironmentHelper.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs
src/Xamarin.Android.Build.Tasks/Utilities/NdkTools/WithClangNoBinutils.cs

Context: 70272dbd9600dca4b161ecd2c0251ee68d2c3481
Context: 38b12367f959533ef69fe9858202a3097a4df903
Context: https://github.com/actions/virtual-environments/blob/9cf1ebd754807fba137c8ce9fa2140311609fdd6/images/win/Windows2022-Readme.md
Context: https://github.com/actions/virtual-environments/commit/2950cbfeab88a6a6202fa31d7371e574dbe2dc51
We've had an "inadvertent thinko" for the past couple of months:
in commit 70272dbd we updated the default `$(AndroidNdkDirectory)`
value to be `$(ANDROID_NDK_LATEST_HOME)`, if set.  *At the time*,
we think this was NDK r23.
In commit 38b12367, we updated `xaprepare` to install NDK r24.
The "thinko" is that commit 38b12367 was *irrelevant*, as commit
70272dbd was "in control".  The Windows **Prepare Solution** log
would contain e.g.:
Checking if …

[build] Default to using NDK r23

---

.gitmodules

Changes: https://github.com/xamarin/android-api-docs/compare/a7e914965a0e80c9454149399551d87a18997b2e...5c4bf28f9fa75e9bf96a6f80f879e22f906aaf06
* xamarin/android-api-docs@5c4bf28f: Merge pull request 32 from xamarin/dabritch-config
* xamarin/android-api-docs@4e096ef2: Master becomes main.
* xamarin/android-api-docs@b1743ec3: Update docs using xamarin/java.interop@d3f0c5c

Bump to xamarin/android-api-docs@5c4bf28f

---

.gitmodules
Configuration.props
Documentation/guides/messages/xa1023.md
src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.cs.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.de.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.es.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.fr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.it.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ja.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ko.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pl.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.pt-BR.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.ru.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.tr.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hans.xlf
src/Xamarin.Android.Build.Tasks/Properties/xlf/Resources.zh-Hant.xlf
src/Xamarin.Android.Build.Tasks/Tasks/R8.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
tests/Mono.Android-Tests/Mono.Android-Tests.csproj
tests/Mono.Android-Tests/Runtime-AppBundle/Mono.Android-TestsAppBundle.csproj
tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj
tests/Mono.Android-Tests/Runtime-MultiDex/Mono.Android-TestsMultiDex.csproj
tests/Xamarin.Forms-Performance-Integration/Droid/Xamarin.Forms.Performance.Integration.Droid.csproj

Context: https://github.com/xamarin/xamarin-android-tools/pull/169
Does It Build™?

Try xamarin/xamarin-android-tools#169

---

src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.g.tt

Fixes: https://github.com/xamarin/xamarin-android/issues/7085
Fixes: https://github.com/xamarin/xamarin-android/issues/7102
Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1554705
In a new Xamarin.Android project, if you go to your `OnCreate()`
method and add a `throw new Exception("test")` VS Mac breaks on a
`NullReferenceException` such as:
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
at Android.Runtime.JNINativeWrapper._unhandled_exception (System.Exception e) [0x0000e] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:12
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V (_JniMarshal_PPL_V callback, System.IntPtr jnienv, System.IntPtr …

[Mono.Android] handle NRE in VS Mac when breaking on exceptions

---

src/Xamarin.Android.Build.Tasks/Tasks/ClassParse.cs
src/Xamarin.Android.Build.Tasks/Tasks/Generator.cs

Fixes: https://github.com/dotnet/maui/issues/8049
There was a bug causing response files to not work when trying to bind Java libraries in a path containing a space, since the CLI argument given to `class-parse`/`generator` was not properly quoted.
This has been fixed in PR https://github.com/xamarin/xamarin-android/pull/5926, however this is a .NET 7 only PR.
Pull the fix out of that PR and port it to the `6.0.4xx` branch so it will go into a .NET 6 servicing release.

[XABT] Port class-parse/generator response file space fix from 67ce902c.

---

Makefile
build-tools/automation/azure-pipelines-apidocs.yaml
build-tools/automation/yaml-templates/upload-results.yaml
src/Mono.Android/Mono.Android.targets

The `_UpdateExternalDocumentation` target has been updated to allow API
docs to be updated against any API level.  Latest stable versions will
still be used by default, however the `$(AndroidApiLevel)`,
`$(AndroidPlatformId)`, and `$(AndroidFrameworkVersion)` properties can
now be set if needed.  This will let us update the current API 31 docs
without having to release an API 32 update.
The api docs pipeline has been updated to allow these properties to be
set at queue time, and it will now upload a `.diff` file rather than
the entire docs folder.

[Mono.Android] Generate docs for any API level

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Aot.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Fixes: https://github.com/jonathanpeppers/maui-profiling/issues/16#issuecomment-1158183178
Building a .NET 6 Android application in `Release` mode inside Visual
Studio results in `libaot-*.so` files missing from the `.apk`.
However, it works fine at the command-line! This also appears to not
be an issue in Xamarin.Android. I could reproduce this issue in a test.
Reviewing our MSBuild targets, this happens because the list of files
are returned by the `<MonoAOTCompiler/>` task:
<MonoAOTCompiler ...>
<Output TaskParameter="CompiledAssemblies" ItemName="_AotCompiledAssemblies" />
<Output TaskParameter="FileWrites"         ItemName="FileWrites" />
</MonoAOTCompiler>
The IDE does a `Build`, then `Install` in two steps. `Build` runs the
AOT compiler, but `Install` (runs `SignAndroidPackage`) …

[One .NET] fix missing libaot-* files when building in IDEs

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/CodeBehindTests.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6296209&view=ms.vss-test-web.build-test-results-tab&runId=44135466&resultId=100131&paneView=attachments
It looks like we only uploaded `*.log` as attachments in this test.
Let's expand to `*.*log` and pickup `.binlog` files as well.

[tests] fix missing .binlog attachments from CodeBehindTests

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/CodeBehindTests.cs

The `SuccessfulAndroidXApp` test fails to restore with:
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5):
error : Unable to resolve 'Xamarin.AndroidX.AppCompat (>= 1.4.1.1)' for 'MonoAndroid,Version=v12.0'.
I looked at 1.4.2.1 of the same NuGet, but both versions have
`monoandroid12.0` inside.
I noticed in the `.binlog`:
NuGet Config files used:
/Users/runner/.config/NuGet/NuGet.Config
So this test is using the machine-wide `NuGet.config` instead of the
one in the root of the `xamarin-android` repo. I made a change to use
this one, let's see if that solves anything.

[tests] fix SuccessfulAndroidXApp test

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DebuggingTasksTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/AndroidDotnetToolTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/NdkUtilTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ResolveSdksTaskTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/EnvironmentHelper.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/TestEnvironment.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Utilities/FileSystemUtils.cs
tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs

Adds support to the desktop MSBuild tests to find and use build output
in the `bin/$(Configuration)/lib/packs` folder.  This is an extension
of the changes in commits b1232a2b and c21e78ca which allowed local
builds to skip .nupkg packing and installing.
The `Xamarin.Android.Build.Tests` and `MSBuildDeviceIntegration` test
suites will now attempt to run against local build outputs by default,
and fall back to `dotnet/packs` or a legacy system install location if
a local build does not exist.

[XABT] Support testing with dotnet packs override

---

Configuration.props
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Context: https://github.com/dotnet/maui/releases/tag/6.0.400
Context: https://github.com/xamarin/xamarin-android/pull/7023
MAUI SR 1 shipped along with a new .NET 6 Android workload. We should
be able to use these packs in .NET 7. This would occur when building
`net6.0-android` apps with a .NET 7 SDK.
Since #7023 is in that release, we can:
* Specify the .NET 6 packs as `sdk` where appropriate.
* Condition `AutoImport.props` to apply for .NET 7-only.
* We also need to remove `$(_DefaultJavaSourceJarPattern)` like we did
in .NET 6.

[One .NET] update the .NET 6 packs used in .NET 7

---

src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj

Commit c21e78ca allowed us to use `dotnet` workloads without having
to call `make pack-dotnet`. We overlooked the copying of the ILLink
PreserveLists xml files into the pack build locations though. As a
result when building an app locally we see the following error
```
error XAGPM7009: System.InvalidOperationException: Unable to find the required Android.Runtime.JNIEnv method tokens
```
This is because the required methods are being linked out by the ILLink
process. This commit makes sure we copy over the PreserveLists xml files
into the packs locations.
This was fine on CI because we always call `make pack-dotnet` as part
of the build process.

Fix Local DotNet builds

---

tools/jit-times/Program.cs

We needed to sort methods by name to compare JIT times for .NET 6 vs .NET 7.
I added a feature for this and the long-form of switches.
Help output is now:
> jit-times --help
Usage: jit-times.exe OPTIONS* <methods-file>
Processes JIT methods file from XA app with debug.mono.log=timing enabled
Copyright 2019 Microsoft Corporation
Options:
-h, --help, -?             Show this message and exit
-m, --method=TYPE-REGEX    Process only methods whose names match TYPE-REGEX.
-s, --sort-self-times      Sort by self times. (this is default ordering)
-t, --sort-total-times     Sort by total times.
-n, --sort-methods         Sort by method names.
-u, --unsorted             Show unsorted results.
-v, --verbose              Output information about progress during the run
of the tool

[jit-times] add method name sorting, more switches

---

src/Mono.Android/Mono.Android.csproj
src/apksigner/apksigner.csproj
src/apksigner/apksigner.targets

Context: 944f88a8b6f1c30eaf43f56cfbebf0f8cd7a547f
Commit 944f88a8 enabled parallel builds by removing `dotnet build -m:1`
usage, which allows for faster incremental builds.
One of the problems encountered was around `gradlew` usage: `gradlew`
doesn't support multiple concurrent executions, and will *block*
waiting for other `gradlew` builds to complete, which can result in
timeouts and failed builds.
Commit 944f88a8 fixed this by "serializing" all projects which
involve `gradlew`:
* `r8.csproj` is the "entrypoint"
* `r8.csproj` references `manifestmerger.csproj`
* `manifestmerger.csproj` references `apksigner.csproj`
This arrangement would cause `dotnet build` to sequentially build
`r8.csproj`, `manifestmerger.csproj`, and `apksigner.csproj`, ensuring
that only one `gradlew` command was …

[apksigner] Serialize gradlew: depend on java-source-utils

---

Directory.Build.props

Context: https://github.com/xamarin/xamarin-android/tree/release/7.0.1xx-preview6
Context: https://github.com/xamarin/xamarin-android/pull/7127
We branched for .NET 7 Preview 6, and there is already a Maestro bump for .NET 7 Preview 7.
Let's update xamarin-android/main's version number.

$(AndroidPackVersionSuffix)=preview.7; net7 is 33.0.0.preview.7

---

build-tools/automation/azure-pipelines-apidocs.yaml
src/Mono.Android/Mono.Android.targets

Improve the `UpdateExternalDocumentation` target so that it will run
successfully without having to set extra properties on the command line.
API docs will now be generated against API 31 sources by default.

[Mono.Android] Update default API level for docs

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs

Context: https://github.com/xamarin/xamarin-android/pull/7135#issuecomment-1171544462
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6356930&view=ms.vss-test-web.build-test-results-tab&runId=45761434&resultId=100052&paneView=debug
On a PR, I noticed CheckIncludedAssemblies fail three times in a row with:
/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5):
error : Could not find file '/Users/runner/.nuget/packages/system.runtime.interopservices.windowsruntime/4.0.1/q3bg64o1.8br'.
We've seen this in the past, and adding `[NonParallelizable]` seems to
workaround it.
This is happening on `Legacy` test lanes only, so I think it's fine to
add this for now. It might not be an issue at all in .NET 6+.

[tests] make CheckIncludedAssemblies NonParallelizable

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs

Fixes https://i.azdo.io/1439405
The ManagedResourceParser was not handling the case where we do not
get four items per line. As a result it would crash with the following
error.
```
System.IndexOutOfRangeException: Index was outside of bounds of the array.
as Xamarin.And.Tasks.ManagedResourceParser.ProcessRtxtFile (System.String file)
```
If we do not get the expected four items from the line in the file we
should ignore that line. A unit test has been added to check that the
task does not fail when this happens.

[Xamarin.Android.Build.Tasks] Handle Empty R.txt file.

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.AvailableItems.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Context: https://github.com/xamarin/GooglePlayServicesComponents/issues/652
In .NET 6, `@(AndroidLibrary)` defaults to `%(Pack)` being true, while
`@(LibraryProjectZip)` mistakenly does not. This would be an issue if
you migrated a project using `@(LibraryProjectZip)` and were not
relying on the default wildcards that would use:
<AndroidLibrary Include="**/*.aar" />
Let's set this value by default, to ease migration to .NET 6.
I updated a test for this scenario and fixed some assertions that are
working since 2ca2a103 was merged.

[Xamarin.Android.Build.Tasks] fix @(LibraryProjectZip) and NuGets

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AndroidLibraries.targets
src/Xamarin.Android.Build.Tasks/Tasks/CreateAar.cs
src/Xamarin.Android.Build.Tasks/Tasks/ReadLibraryProjectImportsCache.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.EmbeddedResource.targets

Fixes #3752
Add support for using `proguard.txt` file from `aar` files. 
Also add support for including `proguard.txt` files in our generated `aar` files when we build a Library project
in .net 6. This will merge all `ProguardConfiguration` Items into one `proguard.txt` file and include that in the 
root of the `aar`. 
Update the Unit Tests to include test for this functionality.

[Xamarin.Android.Build.Tasks] Use Proguard config files from .aar files.

---

.gitmodules
src/apksigner/apksigner.csproj

Ever since commit 2197a459, CI builds for the `main` branch have been
incredibly flakey: 918613d0 through 27647d2a all failed to complete
the **Mac** stage -- which *must* pass in order for most unit tests
to run -- then dbadf130 built, then f149c25c failed.
9 commits in the past week have failed to adequately build.
(PR builds, meanwhile, were largely fine.)
Most of these failures are from `make all-tests`:
_ExtractJavadocsFromJavaSourceJars:
/Users/runner/android-toolchain/jdk-11/bin/java -jar /Users/runner/work/1/s/xamarin-android/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/java-source-utils.jar @/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp1cf0947e.tmp 
JAVASOURCEUTILS : warning : Invalid or corrupt jarfile /Users/runner/work/1/s/xamarin-android/bin/Release/lib/xamari …

[apksigner] Remove AdditionalProperties on java-source-utils.csproj

---

build-tools/automation/azure-pipelines.yaml
tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs

When running the `ApplicationRunsWithDebuggerAndBreaks` unit test under
.NEt 6 we see the following test failure.
```
Error Message:
Should have hit 2 breakpoints. Only hit 1
Expected: 2
But was:  1
```
This is because we are using code like this
```
session.Breakpoints = new BreakpointStore {
{ Path.Combine (Root, appBuilder.ProjectDirectory, "MainActivity.cs"),  19 },
}
```
The line number is hard coded. Now under .NET 6 we seem to be getting a
slightly different file compared to running under Legacy. The usings are
missing. As a result the line numbers have changed. It turns out that
line 19 in this `MainActivity.cs` file is a blank line. Not the
`base.OnCreate (bundle);` which we are expecting. So the breakpoint never
hits.
So lets update these tests to `lookup` the line we want to …

[MSBuildDeviceIntegration] Make Debugging Test work under .NET 6+.

---

src/Mono.Android/Android.App/Activity.cs
src/Mono.Android/Android.Views/View.cs

Context: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/view/View.java;l=25322
Context: https://developer.android.com/reference/android/view/View#requireViewById(int)
In porting Xamarin.Android samples to .NET 6, using latest C# 10
features like `Nullable=enable`, you run into a pattern such as:
var foo = FindViewById<TextView>(Resource.Id.foo);
ArgumentNullException.ThrowIfNull(foo);
foo.Text = "bar";
`var` here is a nullable `TextView?`, so you have to null-check. This
is pretty verbose, and actually seems to make NRTs annoying...
API 28 introduced a `requireViewById()`:
https://developer.android.com/reference/android/view/View#requireViewById(int)
Let's introduce a C# version of this, so you can simply do:
TextView foo = …

[Mono.Android] add RequireViewById<T>() for better NRT support

---

build-tools/create-packs/Directory.Build.targets

Workload template packs installed into the `template-packs` folder
should have a lowercased package ID.  This was not accounted for when
updating local build behavior in commit c21e78ca.  Fix the path that we
"install" our template pack into for local builds so that the templates
can be resolved on Linux.

[build] Output templates pack to lowercase path

---

.gitignore
build-tools/scripts/omnisharp.json.in
build-tools/xaprepare/xaprepare/Steps/Step_GenerateFiles.cs

Context: https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options
The generated file should allow any editor using OmniSharp to open
samples, solutions, projects, tests in the XA tree which use .NET7
and get full code completion etc.
Note that the generated file will affect only the Xamarin.Android
repository.  If you want to be able to open projects outside the
Xamarin.Android source tree, the generated file needs to be copied
(or symlinked) to `~/.omnisharp/` or to the root of the project being 
opened.

[xapreapre] Generate omnisharp.json for the current branch

---

Documentation/project-docs/ApkSizeRegressionChecks.md
build-tools/scripts/UpdateApkSizeReference.ps1
build-tools/scripts/UpdateApkSizeReference.sh

Add a shell script for updating these descriptions locally on MacOS/*nix. Since not everyone wants to install PowerShell. 
Update the PowerShell script to use the correct test names, since the Unit tests was moved to a new class.

Update Apk Size descriptions Script

---

build-tools/scripts/DotNet.targets

This addresses several problems with the `InstallMaui` target:
1. There was not a way to override `$(MauiVersionBand)`. You can now
pass this value in such as `-p:MauiVersionBand=7.0.100`.
2. The logic for computing `$(MauiVersionBand)` was wrong:
error NU1101: Unable to find package Microsoft.NET.Sdk.Maui.Manifest-7.0.000.
This should default to `$(DotNetSdkManifestsFolder)` now, which will
work by default when this lands: https://github.com/dotnet/maui/pull/8737
Until dotnet/maui#8737 is merged, `-p:MauiVersionBand=7.0.100` can be
used.
3. The `dotnet6` feed is now required:
```
Workload installation failed: microsoft.maui.sdk::6.0.408 is not found in NuGet feeds https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public …
```

[build-tools] fix InstallMaui target for .NET 7

---

eng/Versions.props

Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1576444
There is a known issue with the VS Mac updater & the 6.0.400 preview
.NET SDK.
The resolution (for now) is to move from:
Microsoft.NET.Sdk.Android.Manifest-6.0.300
To:
Microsoft.NET.Sdk.Android.Manifest-6.0.400
Likely further changes would also be needed in the next VS insertion.

[One .NET] transition to 6.0.400 version band

---

Directory.Build.props

Context: https://github.com/xamarin/xamarin-android/tree/release/7.0.1xx-preview7
Context: https://github.com/xamarin/xamarin-android/pull/7170
We branched for .NET 7 Preview 7, and there is already a Maestro bump
for .NET 7 RC 1.
Let's update xamarin-android/main's version number.

$(AndroidPackVersionSuffix)=rc.1; net7 is 33.0.0.rc.1

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets

Context: https://github.com/dotnet/linker/issues/2563
The dotnet/linker issue is fixed, so we should be able to enable this analyzer again.

[One .NET] default $(EnableSingleFileAnalyzer) to true again

---

Directory.Build.props
build-tools/automation/azure-pipelines-apidocs.yaml
src/Mono.Android/Mono.Android.targets

Updates mdoc to the latest release, and adds a parameter to the apidocs
pipeline to allow any version of mdoc to be used when generating docs.

[Mono.Android] Bump to mdoc 5.8.9.2

---

Localize/LocProject.json
build-tools/automation/azure-pipelines.yaml

A new job has been added to run the `OneLocBuild@2` task on every commit
to main.  This task produces files needed by the localization team.  For
more details on this process, see the [OneLocBuild documentation][0].
Onboarding for this repo is still pending, and a workflow for automatic
"handback" of localized files will need to be established in a future
PR once onboarding is complete.
[0]: https://aka.ms/OneLocBuild

[Localization] Add OneLocBuild job

---

src/Microsoft.Android.Sdk.ILLink/PreserveLists/System.Private.CoreLib.xml

Reverts xamarin/xamarin-android#6953
The fix for this issue is backported to dotnet/runtime 6.0 now so we can revert the workaround.

Revert "Workaround FirstChanceExceptionEventArgs being trimmed"

---

build-tools/automation/azure-pipelines.yaml

These tests fail with:
DotNetStableTargetFramework: /Users/runner/work/_temp/9afef9fa-d376-4c50-9d87-8a9a6a9fee17.ps1:7
Line |
7 |  … elease/MSBuildDeviceIntegration/$(DotNetStableTargetFramework)/MSBuil …
|                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
| The term 'DotNetStableTargetFramework' is not recognized as a
| name of a cmdlet, function, script file, or executable
| program. Check the spelling of the name, or if a path was
| included, verify that the path is correct and try again.
When we backported 0b375fec, it used the `$(DotNetStableTargetFramework)`
variable, which isn't defined on `release/6.0.4xx`.
We can use `net6.0` instead on this branch.

[tests] fix `WearOS On Device - macOS` tests

---

build-tools/automation/azure-pipelines-nightly.yaml
build-tools/automation/azure-pipelines-oss.yaml
build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-msbuild-device-tests.yaml
build-tools/automation/yaml-templates/run-msbuild-mac-tests.yaml
build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml

Certain tools such as [Component Governance][0] only use the Pipeline
name -- as defined somewhere in Azure DevOps -- and the `displayName`
property on the [`job` definition][1].  The `displayName` property on
the containing [`stage`][2] is *not* displayed.
This can result in "wonderful" alerts which state that the affected
pipeline is e.g. "Xamarin.Android (macOS)", which isn't particularly
helpful when there are *three* jobs with a `displayName` of `macOS`:
* `designer_integration_mac`
* `mac_bcl_tests`
* `mac_build_create_installers`
Fully understanding these alerts is irksome.
Improve this situation by introducing "redundancy" into the job
`displayName` values, and updating them to follow a pattern:
1. Host Platform
2. Category
3. (Optional) Description
Each part is separated from the …

[ci] Rename job names

---

src/Microsoft.Android.Templates/android-wear/AndroidApp1.csproj

The `DotNetNew("androidwear")` test is failing with:
(_CheckForUnsupportedNETCoreVersion target) ->
/Users/runner/work/1/s/xamarin-android/bin/Release/dotnet/sdk/6.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(144,5):
error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 6.0 or lower, or use a version of the .NET SDK that supports .NET 7.0.
When I backported 0b375fec, we needed to change the
`$(TargetFramework)` to `net6.0-android`.

[templates] Wear template should be net6.0-android

---

build-tools/create-packs/Directory.Build.targets
build-tools/create-packs/Microsoft.Android.Sdk.proj
build-tools/scripts/DotNet.targets
build-tools/xaprepare/xaprepare/Application/GeneratedMonoAndroidProjitemsFile.cs
build-tools/xaprepare/xaprepare/Scenarios/Scenario_AndroidTestDependencies.cs
build-tools/xaprepare/xaprepare/Steps/Step_BaseGenerateFiles.cs
build-tools/xaprepare/xaprepare/Steps/Step_GenerateFiles.cs
build-tools/xaprepare/xaprepare/Steps/Step_GenerateMonoAndroidProfileItems.cs
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/in/Microsoft.Android.Sdk.BundledVersions.in.targets
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Context: https://github.com/xamarin/xamarin-android/issues/7183
Adding a class like this to a `dotnet new android` project:
class MyThread : Java.Lang.Thread { }
Causes the build to fail with:
obj\Debug\net6.0-android\android\src\crc6474063b540de74d1e\RenderingThread.java(76,3): error JAVAC0000:  error: no suitable constructor found for Thread(ThreadGroup,Runnable,String,long,boolean)
super (p0, p1, p2, p3, p4);
constructor Thread.Thread() is not applicable
(actual and formal argument lists differ in length)
constructor Thread.Thread(Runnable) is not applicable
(actual and formal argument lists differ in length)
constructor Thread.Thread(ThreadGroup,Runnable) is not applicable
(actual and formal argument lists differ in length)
constructor Thread.Thread(String) is not applicable
(actual …

[One .NET] produce 31, 32, 33 packs

---

eng/Versions.props

Continue to append pre-release version information to our manifest pack
name and `sdk-manifests` subfolder name (e.g. 7.0.100-rc.1).  We likely
wont want to drop this pre-release string until we move to `-rtm`
branded builds.

[build] Add `rc.*` to $(DotNetSdkManifestsFolder)

---

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleLegacy.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsLegacy.apkdesc
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Aot.apkdesc
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Bundle.apkdesc
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release-Profiled-Aot.apkdesc
tests/apk-sizes-reference/Xamarin.Forms_Performance_Integration-Signed-Release.apkdesc
tests/apk-sizes-reference/com.companyname.vsandroidapp-Signed-Release.apkdesc

Changes: https://github.com/android/ndk/wiki/Changelog-r25#changes
Bump to the current NDK LTS r25.  There are no changes that are interesting
from the Xamarin.Android point of view.

Bump to NDK r25

---

src/Mono.Android/Android.Graphics/Color.cs
src/Mono.Android/Android.Runtime/AndroidEnvironment.cs
src/Mono.Android/Android.Runtime/AndroidRuntime.cs
src/Mono.Android/Android.Runtime/CharSequence.cs
src/Mono.Android/Android.Runtime/IJavaObjectValueMarshaler.cs
src/Mono.Android/Android.Runtime/JNIEnv.cs
src/Mono.Android/Android.Runtime/JavaArray.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/5442
Remove all `using System.Linq` statements and all use of LINQ
extension methods from `Mono.Android.dll`.
Primary motivation was to reduce `.apk` size (09baa52e), and we don't
want to inadvertently allow LINQ usage back in…

[Mono.Android] Remove System.Linq usage

---

Documentation/guides/building-apps/build-items.md
Documentation/guides/building-apps/build-properties.md
Documentation/guides/building-apps/build-targets.md

Context: https://github.com/MicrosoftDocs/xamarin-docs/commit/fa13cf9e017d9427203f12a0a2cfe7ac7ac106aa
After synchronizing xamarin/xamarin-android docs with
MicrosoftDocs/xamarin-docs, now we synchronize the other way, to
preserve documentation edits.
Note that many of the changes here are to "appease" [Acrolinx][0],
"rewording" the documentation to achieve an Acrolinx score of 80.
Of note:
* "additional" is not liked.
* "which" should always follow a comma; use "that" instead.
* "this" is always potentially ambiguous, and a less ambiguous
phrase should be used instead.
* *Informal* writing is preferred (?!), along with greater use of
contractions.
* The phrase "Defaults to" is bad.
[0]: https://www.acrolinx.com/

[docs] Synchronize with MicrosoftDocs/xamarin-docs (#6886)

---

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs

I noticed there might be a performance regression in .NET 7 when
building a .NET MAUI project, in the `<GenerateJavaStubs/>` MSBuild
task:
.NET 6:  GenerateJavaStubs = 799 ms
xa main: GenerateJavaStubs = 912 ms
When reviewing what PerfView shows, I saw:
54.31ms (5.7%) module java.interop.tools.javacallablewrappers <<java.interop.tools.javacallablewrappers!Java.Interop.Tools.TypeNameMappings.JavaNativeTypeManager.ToJniName(class Mono.Cecil.TypeDefinition)>>
This was the overload that did not take in a `TypeDefinitionCache`. I
found one instance of this in `<GenerateJavaStubs/>`.
This doesn't seem like the .NET 7 regression, because it has always
been this way.
However, it seems to help quite a bit:
GenerateJavaStubs = 825 ms
GenerateJavaStubs = 867 ms
This probably saves around ~50ms in …

[Xamarin.Android.Build.Tasks] use `ToJniName (type, cache)`

---

Configuration.props
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.targets

Context: https://www.nuget.org/packages/Microsoft.NET.Sdk.Android.Manifest-6.0.400/32.0.447
We shipped newer .NET 6 packs, so we can use them in our .NET 7 workload.
We can also remove the workaround for `Microsoft.NETCore.App`, because the .NET 7 SDK now ships dotnet/runtime 6.0.7.

Bump `$(AndroidNet6Version)` to 32.0.447

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-designer-tests.yml

The designer team is no longer using the build and test templates in
[yaml-templates][0], so there is not much value in us maintaining them
externally.
A copy of the test template has been moved into our repo, and the build
and test steps have been updated to reflect the latest changes in the
UITools repo.
[0]: https://github.com/xamarin/yaml-templates/tree/89becd2759512ebd8fe560a53f6916cc684f0b4c/designer

[ci] Add Android Designer test template

---

build-tools/automation/azure-pipelines.yaml
src/Mono.Android/Android.Runtime/JNIEnv.cs
tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj

`dotnet new android` apps would crash on startup when built with
`-c Release -p:EnableLLVM=true`:
07-20 08:55:44.642  2983  2983 F monodroid-assembly: Internal p/invoke symbol 'java-interop @ java_interop_jvm_list' (hash: 0x58c48fc8b89cb484) not found in compile-time map.
...
07-20 08:55:44.834  3004  3004 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
07-20 08:55:44.834  3004  3004 F DEBUG   : Abort message: 'Internal p/invoke symbol 'java-interop @ java_interop_jvm_list' (hash: 0x58c48fc8b89cb484) not found in compile-time map.'
`java_interop_jvm_list` should *never* be called on Android, it is the
result of `new AndroidRuntime()` having not been called yet?
The problem being that the static `Android.App.Application.cctor` was
somehow running *before* …

[Mono.Android] fix crash on startup with EnableLLVM

---

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Linux.cs
build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.MacOS.cs
build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Windows.cs
build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs

Context: https://docs.microsoft.com/java/openjdk/download#openjdk-11016-lts--see-previous-releases
Context: https://adoptium.net/temurin/releases/?version=8
The IDE teams are shipping these updates in Visual Studio shortly.
Update to these builds, so we can test them out.

[build] update to latest JDKs

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/commercial-build.yaml

We've recently seen a handful of build timeouts and/or failures during
signing.  The ESRP signing service seems to be much less performant and
more error prone on macOS.  In these failure cases, rebuild attempts
would also fail when they got to the "upload test assembly" step:
[error]Artifact test-assemblies already exists for build 6522654.
Improve this by uploading test assemblies and build inventory data at
the end of the build, and by increasing the overall timeout of the job.

[ci] Upload test assemblies after signing

---

Documentation/previous-releases.md
README.md

- Add links to XA 13.0 release installers.
- Move previous release downloads to its own page, as it is starting to take over the entire readme.

[README] Add links to XA 13.0 release installers.

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/7249
Context: https://github.com/dotnet/runtime/pull/71203
Context: https://github.com/dotnet/runtime/issues/60639
Context: https://github.com/dotnet/runtime/issues/61685
Mono introduced a new `marshal-ilgen` component in
dotnet/runtime@de32c446 which needs to be used when
*non-blittable type* is required.
`string` marshaling is a form of non-blittable marshaling.
Eventually the idea is that assemblies should migrate to use the
[`DllImport Generator`][0] for non-blittable marshaling purposes,
then [`[assembly:DisableRuntimeMarshallingAttribute]`][1] can be
applied to the assembly, and -- if no assemblies in an Android app
require non-blittable marshaling -- then the `marshal-ilgen`
component can be omitted from the `.apk`, reducing …

[Xamarin.Android.Build.Tasks] Use marshal-ilgen component

---

build-tools/automation/yaml-templates/variables.yaml

Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1585820
Context: https://github.com/xamarin/XamarinVS/pull/13271
Many of our MSBuild tests fail with:
error MSB4018: The "XamarinTelemetry" task failed unexpectedly.
error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
error MSB4018: File name: 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
error MSB4018:    at Microsoft.VisualStudio.Telemetry.TelemetrySessionSettings.GetFaultEventBucketFilterJson(List`1 bucketFilters)
error MSB4018:    at Microsoft.VisualStudio.Telemetry.TelemetrySessionSettings.ToString() …

[build] disable `<XamarinTelemetry/>` task

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs

Context: https://github.com/xamarin/android-sdk-installer/pull/685
Our `InstallAndroidDependenciesTest` started failing with:
Xamarin.Installer.Common.targets(12,3): error : Element 'type-details' with parser TypeDetailsSourceParser has a child element 'extension-level' but this version of the library does not support it (https://dl.google.com/android/repository/repository2-3.xml)
Since the fix is going into main / .NET 7, we think we should just
ignore this test for now in .NET 6.

[tests] ignore InstallAndroidDependenciesTest

---

Directory.Build.props
build-tools/xaprepare/xaprepare/Steps/Step_DetermineAzurePipelinesTestJobs.cs
tools/decompress-assemblies/decompress-assemblies.csproj
tools/xabuild/App.config
tools/xabuild/xabuild.csproj

`xabuild Xamarin.Android-Tests.sln` was failing with:
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
at Microsoft.Build.Shared.FileUtilities.LooksLikeUnixFilePath(String value, String baseDirectory)
at Microsoft.Build.CommandLine.MSBuildApp.GatherCommandLineSwitches(List`1 commandLineArgs, CommandLineSwitches commandLineSwitches, String commandLine)
at …

[xabuild] update binding redirects for MSBuild 17.3

---

build-tools/automation/azure-pipelines.yaml
build-tools/xaprepare/xaprepare/Steps/Step_InstallGNUBinutils.cs

The `windows-toolchain-pdb` artifact has been updated to include a ZIP
containing both PDB and EXE files.  This artifact will now be uploaded
to blob storage and included in the `nuget-artifacts` GitHub status.
These changes will allow the .NET Visual Studio insertion pipeline to
archive the symbols in this zip file, as its symbol archiving step
already [has support for processing ZIP files][0] listed in the
`nuget-artifacts` GitHub status.
[0]: https://github.com/xamarin/sdk-insertions/blob/15cc361f17d8c34f208ab8d8be024ba39307b295/templates/common/archive-symbols.yml#L40-L72

[ci] Add EXE files to windows-toolchain-pdb artifact

---

Directory.Build.props

Context: https://github.com/xamarin/xamarin-android/tree/release/7.0.1xx-rc1
We branched for .NET 7 RC 1. Let's update xamarin-android/main's version number.

$(AndroidPackVersionSuffix)=rc.2; net7 is 33.0.0.rc.2

---

src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.g.tt

Context: https://github.com/dotnet/maui/commit/15df4ed8fc8a8f84b090b1afae08303d847c481f
Fixes: https://github.com/xamarin/xamarin-android/issues/7212
In the app we're recording AOT profiles for .NET MAUI, we added a
`FlyoutPage` and navigated to it. This was good because it added
common scenarios to the profile:
* Navigation from one page to another
* A non-Shell API, `FlyoutPage`
* `FlyoutPage` also implicitly uses `NavigationPage`?
This caused the app to start using System.Reflection.Emit and logging:
```
08-16 09:46:24.687 31517 31517 D monodroid-assembly: Falling back to System.Reflection.Emit for delegate type '_JniMarshal_PPIZI_L': IntPtr n_OnCreateAnimation_IZI(IntPtr, IntPtr, Int32, Boolean, Int32)
```
I added a case for `_JniMarshal_PPIZI_L`, this log message is now gone
when I …

[Mono.Android] add "built-in" delegate for MAUI+non-Shell

---

src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/7088
When the AOT hybrid mode is enabled via the
`<AndroidAotMode>Hybrid</AndroidAotMode>` MSBuild property, we failed to
inform the AOT compiler about its desired mode by omitting the `hybrid`
argument from the list of options passed to the compiler via `--aot`
The same would apply to the full AOT mode.
Add `hybrid` and `full` options to the AOT compiler command line, if
enabled via the `AndroidAotMode` MSBuild property.
Mode is set after processing the `AotAdditionalArguments` MSBuild
property.  The `AndroidAotMode` property should always be the definitive
source of AOT compiler mode, as it specifies the options directly
supported by us.
Note that the AOT compiler doesn't appear to validate options passed to
it too rigorously, so …

[AOT] Pass the `hybrid` option to AOT compiler, if enabled

---

Configuration.props
build-tools/xaprepare/xaprepare/Application/GeneratedFile.cs
build-tools/xaprepare/xaprepare/Application/GeneratedSourceLinkJsonFile.cs
build-tools/xaprepare/xaprepare/Steps/Step_GenerateCGManifest.cs
build-tools/xaprepare/xaprepare/Steps/Step_GenerateFiles.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/2614
Context: https://developercommunity.visualstudio.com/t/JNINativeWrappergcs-file-Not-found/10020777
Context: https://www.nuget.org/packages/sourcelink/
Context: https://github.com/dotnet/designs/blob/main/accepted/2020/diagnostics/source-link.md#source-link-file-specification
Context: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink
Context: https://www.hanselman.com/blog/exploring-net-cores-sourcelink-stepping-into-the-source-code-of-nuget-packages-you-dont-own
[SourceLink][0] is a set of tooling which allows debuggers to obtain
source code, allowing developers to "step into" assemblies for which
they don't have local source code to.
It operates by adding a JSON document to Portable PDB files, which …

[xaprepare] Generate SourceLink.json

---

tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6595850&view=ms.vss-test-web.build-test-results-tab&runId=51752272&resultId=100026&paneView=debug
Frequently `Install_CSharp_Change` fails with:
Exceeded expected time of 4500ms, actual 4671.203ms
Reviewing the `.binlog` the `<FastDeploy/>` task shows up:
Top 10 most expensive tasks
GenerateJavaStubs = 1.304 s
_GenerateJavaStubs = 1.304 s
FastDeploy = 498 ms
_Upload = 498 ms
`<FastDeploy/>` is logging "lots of stuff" due to
`$(_FastDeploymentDiagnosticLogging)`:
FastDeploy
Parameters
DiagnosticLogging = True
...
// Hundreds of lines of:
xamarin.find: Ignoring line 'DEBUG: ./UnnamedProject.dll size:1661286176390 mtime:6144 tv_sec:1661286176 tv_nsec:390000'. Line is incorrectly formatted.
This was added in 7b51fd1b, to …

[tests] disable `$(_FastDeploymentDiagnosticLogging)` in PerformanceTest

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-installer.yaml
build-tools/automation/yaml-templates/run-msbuild-device-tests.yaml
build-tools/automation/yaml-templates/setup-test-environment.yaml

Many of our Windows lanes on `release/6.0.4xx` are failing with:
Xamarin.Provisioning.ProvisioningException: Failed to provision
---> Xamarin.Provisioning.ProvisioningException: Only extension versions greater than that in the instance catalog version (13.0.0.0) can be installed.
This is because the CI machines have VS 17.3 now, and the classic
Xamarin.Android we're building is too old.
For now, let's just disable all these classic tests on this branch. We
can come up with a better idea for this later.

[build] disable classic tests on .NET 6 release branches

---

build-tools/automation/azure-pipelines.yaml
build-tools/create-packs/vs-workload.in.props
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Context: https://github.com/xamarin/yaml-templates/pull/180
Context: https://github.com/xamarin/yaml-templates/pull/195
Context: https://github.com/xamarin/yaml-templates/pull/199
Updates the build to use the latest MSI generation template. The v3
template uses the latest changes from arcade which include a large
refactoring, support for multi-targeting, and support for workload pack
group MSIs.
The build will now produce two different VS Drop artifacts.  The MSI and
VSMAN files generated for SDK packs have been split out into a new
`vsdrop-multitarget-signed` artifact, allowing us to include multiple
versions of the SDK packs in VS.
The `Microsoft.Android.Sdk` pack has been renamed to
`Microsoft.Android.Sdk.net6` to match the pack alias that is referenced
in the .NET 7 manifest.

[ci] Add support to net6.0 for multi-targeting in VS

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-installer.yaml
build-tools/automation/yaml-templates/run-msbuild-device-tests.yaml
build-tools/automation/yaml-templates/variables.yaml

Related: https://github.com/xamarin/xamarin-android/pull/7286
Classic test jobs and VSIX installer provisioning will no longer run on
.NET release branches (branches starting with `release/`).
The MSBuild smoke test jobs have also been updated to run against the
`net6.0` version of the `Xamarin.Android.Build.Tests.dll` and
`MSBuildDeviceIntegration.dll` test assemblies.

[ci] Skip classic tests on .NET release branches

---

Configuration.props
build-tools/automation/azure-pipelines.yaml
build-tools/create-packs/vs-workload.in.props
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs

Context: https://github.com/xamarin/yaml-templates/pull/180
Context: https://github.com/xamarin/yaml-templates/pull/195
Context: https://github.com/xamarin/yaml-templates/pull/199
Updates the build to use the latest MSI generation template. The v3
template uses the latest changes from arcade which include a large
refactoring, support for multi-targeting, and support for workload pack
group MSIs.
The build will now produce two different VS Drop artifacts.  The MSI and
VSMAN files generated for SDK packs have been split out into a new
`vsdrop-multitarget-signed` artifact, allowing us to include multiple
versions of the SDK packs in VS.
The `Microsoft.Android.Sdk` pack has been renamed to
`Microsoft.Android.Sdk.net7` to allow it to be imported by the .NET 8
workload manifest when the time …

[ci] Add support to net7.0 for multi-targeting in VS

---

eng/Version.Details.xml
eng/Versions.props
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc

Context: https://maestro-prod.westus2.cloudapp.azure.com/3077/https:%2F%2Fgithub.com%2Fdotnet%2Fruntime/latest/graph
Changes: https://github.com/dotnet/runtime/compare/430c42acb0eb0481f58d1acb172af346363e2edc...06aceb7015f3bd2ff019ef5920d2354eb2ea2c92
Changes: https://github.com/dotnet/emsdk/compare/321399ab3ab4853fbf861b2eaed2113447a6d7e4...5ef661392ae7b1595b683df83d63e3a0365fc126
To get this bump sooner, I removed:
CoherentParentDependency="Microsoft.Dotnet.Sdk.Internal"
Then locally ran:
darc update-dependencies --id 146680

Bump to dotnet/runtime/release/7.0-rc1@06aceb70

---

.github/fabricbot.json

Today we rely on our templates to apply the `needs-triage` label to new issues.  However, there are several ways issues can be added to our repo that bypasses our templates:
- Using the "blank" template
- Moved from another repository
- Moved from `vsfeedback`
FabricBot can ensure *every* new issue is tagged with `needs-triage`.
Note that the first commit simply allows the FabricBot UI to reformat our existing config file to its desired format.  It does not make any changes.
To see what is actually being added, look at the second commit.

[FabricBot] Apply 'needs-triage' label to new issues.

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Application.targets

Context: https://github.com/dotnet/xamarin/issues/26
The following does not work as expected:
dotnet run -c Release
You end up with a `Debug` app in this case.
The way we implemented `dotnet run` was to make `$(RunCommand)` and
`$(RunArguments)` invoke `dotnet build -t:Run`.
We were losing the `$(Configuration)` value in this example.

[One .NET] fix `dotnet run -c Release`

---

src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs
src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingReleaseNativeAssemblyGenerator.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/7302
Context: https://github.com/xamarin/xamarin-android/commit/7117414ca27d88a71b4a272705a0207f772423bd
When building .NET6 app on .NET7, sometimes the build fails with:
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.451\tools\Xamarin.Android.Common.targets(1438,3): error XAGJS7004: System.ArgumentException: An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at Xamarin.Android.Tasks.TypeMapGenerator.GenerateRelease(Boolean skipJniAddNativeMethodRegistrationAttributeScan, List`1 javaTypes, String outputDirectory, ApplicationConfigTaskState appConfState)
at …

Don't use Dictionary<K,V> to avoid duplicate value exception

---

.github/fabricbot.json

Copy https://github.com/dotnet/runtime automation for `backlog-cleanup-candidate` as `possibly-stale`.
When we place the issue label `possibly-stale` on an issue, it will kick off the following workflow:
- A comment will be added to the issue that states:
```
We suspect this issue is stale and no longer relevant. It will be closed if no further activity occurs within 
14 more days. Any new comment (by anyone, not necessarily the author) will undo this process.
```
- If anyone comments on the issue during this timespan, the `possibly-stale` label will be removed and the `need-attention` label will be applied so we can review the comment.
- If no one comments on the issue during this timespan, the issue will be closed with the comment:
```
This issue will now be closed since it had been …
```

[FabricBot] Add 'possibly-stale' GH label for closing old issues.

---

build-tools/xaprepare/xaprepare/Steps/Step_GenerateCGManifest.cs

Context: https://www.jsonschemavalidator.net/
Context: https://github.com/JamieMagee/verify-cgmanifest
Context: https://json.schemastore.org/component-detection-manifest.json
Context: https://github.com/xamarin/AndroidX/pull/608
There is a [JSON Schema][0] for `CGManifest.json`.
Update `xaprepare` so that `CGManifest.json` conforms to the JSON
schema.  This involves three sets of changes:
* Add a `$schema` property.
* Add a `version` property; I can't find any actual documentation
for this schema, but the [sample manifest][1] uses `"version": 1`,
so use the same version.
* "camelCase" all the JSON property names.  From the
[JamieMagee/verify-cgmanifest README.md][2]:
> Component Detection will accept object properties in PascalCase,
> but JSON schema does not have a case-insensitive mode. …

[xaprepare] CGManifest.json conforms to JSON schema

---

src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs
src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingReleaseNativeAssemblyGenerator.cs

Backport of #7340
(There were some minor merge conflicts)
Fixes: https://github.com/xamarin/xamarin-android/issues/7302
Context: https://github.com/xamarin/xamarin-android/commit/7117414ca27d88a71b4a272705a0207f772423bd
When building .NET6 app on .NET7, sometimes the build fails with:
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.451\tools\Xamarin.Android.Common.targets(1438,3): error XAGJS7004: System.ArgumentException: An item with the same key has already been added.
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at Xamarin.Android.Tasks.TypeMapGenerator.GenerateRelease(Boolean skipJniAddNativeMethodRegistrationAttributeScan, List`1 javaTypes, String …

Don't use Dictionary<K,V> to avoid duplicate value exception (#7340)

---

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs

Changes: https://github.com/android/ndk/wiki/Changelog-r25#r25b
There are no interesting changes in this version, from our point
of view.  Bumping merely to track the current supported version
of the NDK.

Bump NDK to r25b

---

tests/msbuild-times-reference/MSBuildDeviceIntegration.csv

Frequently 3 performance tests fail with times such as:
Build_CSharp_Change
Exceeded expected time of 3850ms, actual 3912.98ms
Build_AndroidManifest_Change
Exceeded expected time of 4250ms, actual 4873.595ms
Install_CSharp_Change
Exceeded expected time of 4500ms, actual 4693.08ms
Let's increase these times to make our CI runs less noisy.
At some point, we could also do some build performance work to get these times lower. Right now these time differences are pretty small, and I believe due to environmental changes in the CI machines, etc.

[tests] update times in MSBuildDeviceIntegration.csv

---

Documentation/building/configuration.md
Documentation/guides/OneDotNet.md
Documentation/guides/building-apps/build-properties.md
Documentation/guides/messages/README.md
Documentation/guides/messages/xa1029.md
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownProperties.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/7297
The way we support `$(AotAssemblies)` requires us to *know* the names
of packs in the Mono workload.
Let's drop support for `$(AotAssemblies)` and use the new
`$(RunAOTCompilation)` property instead. We can begin by emitting a
warning in .NET 7, to potentially remove/error in .NET 8.

[One .NET] add XA1029 for $(AotAssemblies)

---

build-tools/automation/azure-pipelines.yaml
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Aot.targets
src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetAotArguments.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetAotAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/MakeBundleNativeCodeExternalTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Legacy.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Tooling.targets
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
tests/Mono.Android-Tests/Mono.Android-Tests.csproj
tests/Mono.Android-Tests/Runtime-AppBundle/Mono.Android-TestsAppBundle.csproj
tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj
tests/Mono.Android-Tests/Runtime-MultiDex/Mono.Android-TestsMultiDex.csproj
tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidMessageHandlerNegotiateAuthenticationTests.cs
tests/Xamarin.Forms-Performance-Integration/Droid/Xamarin.Forms.Performance.Integration.Droid.csproj
tools/xabuild/XABuild.cs

It appears that an Android NDK installation is no longer needed when
using Aot with LLVM.  Projects which enable Aot and LLVM will no longer
attempt to use the NDK unless it is explicitly requested by setting
`$(AndroidNdkDirectory)` to a valid NDK path in the project file.

[Xamarin.Android.Build.Tasks] Use binutils for Aot and LLVM

---

NuGet.config
build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs
build-tools/xaprepare/xaprepare/package-download.proj
eng/Version.Details.xml
eng/Versions.props
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Aot.targets
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc

Changes: https://github.com/dotnet/installer/compare/330dee39e5e4dcf765f4c41c76b94c8e4497e91c...dd355bb777249689beba30978ac26e15c96da642
Changes: https://github.com/dotnet/linker/compare/313671b195b1b36d56a8888a9a0e12edaac52c57...5f9bfd94d9c687207872ae03f751ea19704381c0
Changes: https://github.com/dotnet/runtime/compare/ef077d0b58ffddcf54fa73bd85dace6b999b8992...6d10e4c8bcd9f96ccd73748ff827561afa09af57
Changes: https://github.com/dotnet/emsdk/compare/216093204c415b6e37dfadfcbcf183881b443636...8d8d2122b16c81df4b158fe43995f958e8fe115e
Updates:
* Microsoft.Dotnet.Sdk.Internal: from 7.0.100-rc.2.22454.1 to 7.0.100-rc.2.22457.6
* Microsoft.NET.ILLink.Tasks: from 7.0.100-1.22423.4 to 7.0.100-1.22452.1
* Microsoft.NETCore.App.Ref: from 7.0.0-rc.1.22422.12 to 7.0.0-rc.2.22451.11
* …

Bump to dotnet/installer/main@dd355bb 7.0.100-rc.2.22457.6

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/7302
Context: https://github.com/dotnet/linker/issues/2203
Context: https://github.com/dotnet/runtime/issues/67660
Context: https://github.com/xamarin/xamarin-android/pull/6598
This partially backports 745214d.
Building a `net6.0-android` app in `Release` mode with .NET 7 can fail with many errors like:
error XA4215: The Java type `androidx.activity.contextaware.OnContextAvailableListener` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
This happens because we end up with multiple assemblies, such as:
obj/Release/net6.0-android/android-arm/linked/Xamarin.AndroidX.Activity.dll
obj/Release/net6.0-android/android-arm64/linked/Xamarin.AndroidX.Activity.dll …

[illink] set `$(TrimmerRemoveSymbols)` by default

---

src/Microsoft.Android.Templates/android-activity/.template.config/ide.host.json
src/Microsoft.Android.Templates/android-layout/.template.config/ide.host.json

Fixes: https://github.com/xamarin/xamarin-android/issues/7315
Fixes: https://github.com/xamarin/xamarin-android/issues/7231
This makes our item templates useable from inside Visual Studio, as it should allow them to show up in a new `Android` category in the "Add New Item" dialog.

[templates] add `ide.host.json` files

---

build-tools/automation/yaml-templates/variables.yaml

Context: https://github.com/dotnet/linker/issues/3012#issuecomment-1239958027
See if disabling the "server GC" in favor of the "workstation GC" helps a failing test.

[tests] export $DOTNET_gcServer as 0

---

samples/HelloWorld/HelloLibrary/HelloLibrary.csproj
samples/HelloWorld/HelloLibrary/LibraryActivity.cs
samples/HelloWorld/HelloLibrary/Resources/values/Attr.xml
samples/HelloWorld/HelloWorld/HelloWorld.csproj
samples/HelloWorld/HelloWorld/Resources/values/Attr.xml
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/LinkDesignerBase.cs
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/RemoveResourceDesignerStep.cs
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs

Fixes https://github.com/xamarin/xamarin-android/issues/7194
Context https://github.com/dotnet/maui/pull/7038
The initial version of `AndroidLinkResources` commited in 9e6ce03c was to broad in its removal of Fields. 
Certain field usage like `Styleable` arrays were not called using the IL`stsfld` op code. As a result they could
not be easily replaced with constant usage. However the linker removed ALL the fields from the `Resource` 
sub classes. This would result in the following error
`System.BadImageFormatException: 'Could not resolve field token 0x0400000b'`.
This was because the `int[]` fields were removed as part of the linking process. 
So to fix this we need to leave the `int[]` fields in the `Resource` subclasses and not remove them. We can 
still remove all the other `int` fields …

AndroidLinkResources and Styleables

---

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MarkJavaObjects.cs
tests/MSBuildDeviceIntegration/Resources/LinkDescTest/MainActivityReplacement.cs
tests/MSBuildDeviceIntegration/Resources/LinkDescTest/MaterialTextChanged.cs
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/7097
Context: https://github.com/xamarin/monodroid/commit/a619cbea33e1b7cd8ffd0352bb37ac551d324f67
Usage of a `Google.Android.Material.TextField.TextInputEditText`:
var filterBox = FindViewById<TextInputEditText>(Resource.Id.filterBox);
filterBox.TextChanged += (s, e) => { };
Crashes at runtime with:
android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not load type '{0}' from assembly '{1}'., Android.Text.ITextWatcherInvoker, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
at System.RuntimeTypeHandle.GetTypeByName(String , Boolean , Boolean , StackCrawlMark& , Boolean )
at System.RuntimeType.GetType(String , Boolean , Boolean , StackCrawlMark& )
at System.Type.GetType(String , Boolean )
at …

[linker] preserve interfaces on Java types

---

Documentation/guides/building-apps/build-items.md
src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #6920
Add a new ItemGroup `AndroidPackagingOptionsExclude` to the common targets. This ItemGroup will contain a set of RegEx compatible patterns which will be used to exclude certain files from the final apk/aab.
The patterns will need to be Url encoded so that MSBuild does not try to interpret them.
The main purpose of this is to allow us to exclude certain Kotlin meta-data files from the final package. These files seem to be excluded by gradle so we should do the same.

[Xamarin.Android.Build.Tasks] Feature for excluding Kotlin-related files from apps

---

.gitignore
build-tools/automation/azure-pipelines.yaml

Fixes a timeout in the `MSBuild+Emulator One .NET` job by ensuring that
the correct test categories are passed to `dotnet test`.  All smoke test
job timeouts have been set to 180 minutes for consistency.  A couple of
gitignore entries have also been updated to ignore the files produced
when running API compatibility checks on Mono.Android.

[ci] Fix test categories for emu smoke tests

---

.external

Changes: https://github.com/xamarin/monodroid/compare/43583d0...135be73
This brings fixes for Fast Deployment.
* [tools/msbuild] use full paths & additional logging
* Bump to xamarin/androidtools@f7e9b92

Bump to xamarin/monodroid/main@135be73

---

src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.Legacy.cs

When using the `AllowAutoRedirect` feature of `AndroidClientHandler` to automatically follow 3xx redirects, the cookies that are returned together with the redirection are not processed. If the redirection target requires the cookies returned by the first request, the call will fail.
With this change the cookies are always processes before the redirection takes place. Fixes #3954.
Please note that this change was already merged for `AndroidMessageHandler` (see #6987), but not for the legacy `AndroidClientHandler`.

Parse cookies on redirect (legacy AndroidClientHandler)

---

.external

Changes: https://github.com/xamarin/monodroid/compare/135be73fdb3aa6ecbc9f9d078097521ab028e620...8f925e3346c8aea63f3481a26c811374915b8d18
* xamarin/monodroid@8f925e334: Bump to xamarin/android-sdk-installer/main@0fb3646a (xamarin/monodroid#1270)
* xamarin/monodroid@51ed9b12d: Bump to xamarin/androidtools/main@c95015cb (xamarin/monodroid#1269)

Bump to xamarin/monodroid/main@8f925e33

---

Directory.Build.props
build-tools/automation/azure-pipelines.yaml

Context: https://github.com/xamarin/xamarin-android/tree/release/7.0.1xx
We branched for .NET 7 into release/7.0.1xx, main is now .NET 8.
Let's update xamarin-android/main's version number to 34.0.0-preview.1.
We should also only push packages from main to the `dotnet8` feed.

$(AndroidPackVersionSuffix)=preview.1; net8 is 34.0.0.preview.1

---

Directory.Build.props

Context: https://github.com/xamarin/xamarin-android/tree/release/7.0.1xx-rc2
We branched for .NET 7 RC 2 into release/7.0.1xx-rc2. release/7.0.1xx is branded rtm.
Let's update xamarin-android/release/7.0.1xx's version number to 33.0.0-rtm.

$(AndroidPackVersionSuffix)=rtm; net7 is 33.0.0.rtm

---

build-tools/automation/azure-pipelines.yaml

Context: 7723f856
The steps that publish our .NET packages to a dotnet feed and to maestro have been disabled.  We should re-enable these steps when main is building and testing against .NET 8, and when we have a service connection set up for the `dotnet8` feed.

[ci] Do not publish .NET 8 packages

---

Documentation/guides/messages/xa1030.md
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/7178
Using this combination:
<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
<RunAOTCompilation>true</RunAOTCompilation>
<PublishTrimmed>false</PublishTrimmed>
Causes apps to crash at runtime with:
07-18 11:39:53.613 20269 20269 D Mono    : AOT: module Microsoft.Maui.dll.so is unusable (GUID of dependent assembly Xamarin.AndroidX.AppCompat doesn't match (expected '1FC81757-8A70-4D56-93E6-8A635E2C23DE', got 'FD3821D1-CBF4-4956-B930-EA2A5379E18D')).
AOT runs right after the `<ILLink/>` MSBuild task, and so the combination currently doesn't work when trimming is disabled.
For now, to solve this let's emit a `XA1030` error and fail the build. This way you at least get a reasonable error at build time …

[One .NET] error with XA1030 for AOT and PublishTrimmed=false

---

Configuration.props
src/java-runtime/java/mono/android/MonoPackageManager.java
src/java-runtime/java/mono/android/Runtime.java
src/monodroid/jni/mono_android_Runtime.h
src/monodroid/jni/monodroid-glue-internal.hh
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/monovm-properties.cc
src/monodroid/jni/monovm-properties.hh

Follows up https://github.com/dotnet/runtime/pull/74459 for https://github.com/dotnet/runtime/issues/71004
On dotnet/runtime, `DateTimeOffset.Now` is now updated to leverage an App Context's property as a fast path result if provided. In order to improve startup performance for applications that rely on DateTimeOffset.Now during startup will need to set `System.TimeZoneInfo.LocalDateTimeOffset` as the appropriate value.
The original issue reported a perf timing of 277ms, and after https://github.com/dotnet/runtime/pull/74459, has an average perf timing of 21.818ms.
---------------------------
Created an Android app
Added `_ = DateTimeOffset.Now;` to OnCreate
The timing of DateTimeOffset.Now with dotnet-trace was 1.18ms + 17.67ms = 18.85ms
----------------------------
This PR does the …

Add local date time offset monovm prop

---

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 11410: Build ID 6747093

---

build-tools/installers/unix-binutils.projitems
build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs

On Windows our distribution package is much bigger than on macOS because the LLVM binaries each include the entire LLVM framework, no shared libraries are used.  For that reason, the distribution size on Windows pushes 100MB.  In order to make the footprint smaller, we now compress the Windows binaries with UPX.

Use LLVM toolchain compressed with UPX

---

eng/Version.Details.xml
eng/Versions.props

Changes: https://github.com/dotnet/runtime/compare/c623d96fe33cc360bd9981c9e6f6a646d7881d9e...550605cc93d9b903c4fbaf8f1f83e387d2f79dbe
Changes: https://github.com/dotnet/emsdk/compare/76e6b338e87093ddc9b3b650f027706aba65d388...6625add9a3eadc2954af0311be35290cfefcddb0
* Bump to Microsoft.NETCore.App.Ref 7.0.0-rc.2.22472.3
* Bump to Microsoft.NET.Workload.Emscripten.*.Manifest-7.0.100 7.0.0-rc.2.22465.1
To update to a newer dotnet/runtime:
1. Remove `CoherentParentDependency="Microsoft.Dotnet.Sdk.Internal"`
2. Find the latest dotnet/runtime build on the `.NET 7 RC 2` channel:
https://maestro-prod.westus2.cloudapp.azure.com/3078/https:%2F%2Fgithub.com%2Fdotnet%2Fruntime/latest/graph
3. Run `darc update-dependencies --id 150400`
After this is merged, I will setup a subscription such as:
darc …

Bump to dotnet/runtime/release/7.0-rc2@550605c 7.0.0-rc.2.22472.3

---

tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj

Context: https://github.com/dotnet/runtime/issues/73304
Context: https://github.com/dotnet/runtime/issues/75155
The issues for these should be fixed in .NET 7 RC 2.

[tests] enable InetAccess, NetworkInterfaces for LLVM tests

---

src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 11410: Build ID 6765281

---

src/Mono.Android/Mono.Android.targets

Updates the `<UpdateExternalDocumentation/>` target to run the mdoc `export-msxdoc` command for validation, and to include new files in the diff that it produces.

[Mono.Android] Improve generated API docs diff

---

src/Xamarin.Android.Build.Tasks/Tasks/GetJavaPlatformJar.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Tooling.targets

Fixes #7405
Raising a XA5207 Error during a design time build is causing some
problems for the auto sdk installer. The design time build is run for
all frameworks. So you end up in a position when you have the Windows
framework selected in the IDE and the auto sdk installer will try to
install an Android framework. Its very confusing for the user.
So lets not raise this Error during a design time build.

Avoid XA5207 for design-time builds 

---

src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs

The ManifestDocument class has a few instances of `ToJniName` that are not using the `cache` overload. Using the `cache` version should be faster, so lets try to use that :).

[Xamarin.Android.Build.Tasks] Fix up `ToJniName` to use cache.

---

src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs

My project uses AndroidMessageHandler.  Currently, idiomatic code like this produces a nullability warning:
```cs
if (handler.RequestNeedsAuthorization)
handler.PreAuthenticationData = handler.RequestedAuthentication[0];
```
This PR adds a [MemberNotNullWhen attribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.membernotnullwhenattribute?view=net-6.0) that allows RequestedAuthentication to be used without a null-check after testing RequestNeedsAuthorization.

Nullability for AndroidMessageHandler.RequestNeedsAuthorization

---

Directory.Build.props
build-tools/create-packs/Directory.Build.targets
build-tools/scripts/XAVersionInfo.targets

Context: https://github.com/xamarin/xamarin-android/commit/4c460a89cb070ee8dfd731842f36bc3dc68dc75c
This brings 4c460a89 to .NET 7, so our versioning will be stable with .NET 7 GA.
We will start out with 33.0.0, and each commit increments by 1.

[release/7.0.1xx] stable 33.0.x branding

---

.github/dependabot.yml

Context: https://github.com/xamarin/xamarin-android/network/updates/488916011
Commit 619420ae attempted to add submodule dependency updating to our dependabot configuration, however it was not configured correctly:
Dependabot couldn't find a .gitmodules.
Dependabot requires a .gitmodules to evaluate your Git dependencies. It had expected to find one at the path: /external/android-api-docs/.gitmodules.
The directory for the `gitsubmodule` dependency has been updated to fix this, and the repos that we may not want automatic updates for have been added to the ignore list.

[dependabot] Fix automatic submodule updates

---

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
src-ThirdParty/NUnitLite/Env.cs
tests/MSBuildDeviceIntegration/Resources/LinkDescTest/Bug35195.cs
tests/Mono.Android-Tests/Mono.Data.Sqlite/SqliteTests.cs

Context: https://github.com/dotnet/runtime/pull/68610
In .NET 8, a test using `SpecialFolder.Personal` failed with:
```
[FAIL] Create table attempt failed!
SQLite.SQLiteException: Could not open database file: /data/user/0/com.xamarin.customlinkdescriptionpreserve/files/Documents/TaskDB.db3 (CannotOpen)
at SQLite.SQLiteConnection..ctor(SQLiteConnectionString )
at SQLite.SQLiteConnectionWithLock..ctor(SQLiteConnectionString )
at SQLite.SQLiteConnectionPool.Entry..ctor(SQLiteConnectionString )
at SQLite.SQLiteConnectionPool.GetConnectionAndTransactionLock(SQLiteConnectionString , Object& )
at SQLite.SQLiteConnectionPool.GetConnection(SQLiteConnectionString )
at SQLite.SQLiteAsyncConnection.GetConnection()
at SQLite.SQLiteAsyncConnection.<>c__DisplayClass33_0`1[[SQLite.CreateTableResult, …
```

Use Environment.SpecialFolder.UserProfile, not SpecialFolder.Personal

---

src/monodroid/jni/monodroid-glue.cc

Context: https://github.com/xamarin/monodroid/commit/d887d87d8f 
Context: https://github.com/llvm/llvm-project/commit/c10ca903243f97cbc8014f20c64f1318a57a2936
Disable loading of `libLLVM.so` on Android API 21 and newer, because the symbol we're looking for is no longer present in the library on those Android versions.
The hack was implemented on April 8, 2014:
Disable LLVM signal handlers. Fixes #18016.
This happens when RenderScript needs to be compiled. See https://bugzilla.xamarin.com/show_bug.cgi?id=18016
This happens only on first run of the app. LLVM is used to compiled the RenderScript scripts. LLVM, been
a nice and smart library installs a ton of signal handlers and don't chain at all, completely breaking us.
This is a hack to set llvm::DisablePrettyStackTrace to true and avoid …

Disable loading of libLLVM at runtime

---

eng/Versions.props

Local builds were failing with:
make prepare all
...
build-tools/create-packs/Directory.Build.targets(280,5): error MSB3073: The command ""…/xamarin-android/bin/Debug/dotnet/dotnet" workload install android-deps --configfile "…/xamarin-android/NuGet.config" --skip-manifest-update --verbosity diag" exited with code 1.
`android-deps` is our workaround for installing the "abstract" Mono workload that we need to build against.
Since we are "inventing" this workload, there is not a way for the .NET workload system to fall back to older version bands.
And so:
bin/Debug/lib/sdk-manifests/8.0.100/android.deps.workload/WorkloadManifest.json
Doesn't work because the version band is *actually* 8.0.100-alpha.1.
Update our logic in `eng/Versions.props` to support `alpha` version bands.

[build] fix 8.0.100-alpha.1 version band

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/FilterAssembliesTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildItem.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DownloadedCache.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Utilities/SevenZipHelper.cs
tests/MSBuildDeviceIntegration/Tests/DeleteBinObjTest.cs

Our `https://xamjenkinsartifact.azureedge.net` site for some of the unit test data seems to have disappeared.
So lets use a github repo to store this data instead. The unit tests can download the raw files directly from github. The repo will be public as well so there won't be any need for authorization.
The new repo can currently be found at https://github.com/dellis1972/xamarin-android-unittest-files.

[Tests] Replace azurestorage with a github repo.

---

build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs

Context: https://github.com/dotnet/runtime/issues/77385
Building `net6.0-android` and `net7.0-android` apps with .NET 8 is failing with:
Microsoft.Android.Sdk.RuntimeConfig.targets(46,5): error MSB4036: The "RuntimeConfigParserTask" task was not found.
Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "/Users/runner/work/1/s/xamarin-android/bin/Release/dotnet/sdk/8.0.100-alpha.1.22553.2" directory.
The problem appears to be due to the import ordering:
8.0.100-alpha.1/microsoft.net.workload.mono.toolchain.net6/WorkloadManifest.targ …

[xaprepare] use 8.0.100 version band for Mono workloads

---

NuGet.config

Without it, it's impossible to install MAUI:
dotnet msbuild Xamarin.Android.sln -t:InstallMaui -p:MauiVersion=7.0.49 -p:MauiVersionBand=7.0.100 -p:Configuration=Release
build-tools/scripts/maui.proj : error NU1101: Unable to find package Microsoft.NET.Sdk.Maui.Manifest-7.0.100.

[NuGet] Add back the `dotnet7` feed

---

Documentation/guides/OneDotNetBindingProjects.md

Context: https://github.com/xamarin/xamarin-android/issues/7527#issuecomment-1303859544
Update docs to give some examples on excluding files that you wouldn't want to bind.

[docs] notes on binding `gradle-wrapper.jar`

---

build-tools/scripts/UpdateApkSizeReference.ps1
build-tools/scripts/UpdateApkSizeReference.sh

The `UpdateApkSizeReference` scripts were using `net6.0` in their paths. This is wrong as we now produce `net7.0` assemblies. So the scripts were failing. So lets update them!

[build-tools] Update UpdateApkSizeReference scripts to use the right path

---

build-tools/automation/azure-pipelines-nightly.yaml
build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/install-microbuild-tooling.yaml
build-tools/automation/yaml-templates/update-vs.yaml

In an attempt to unify the build for all the SDKs we need to rename all the resources to use the same names. This change follows the pattern used by tehe MAUI repo.
Partial fix for https://github.com/xamarin/sdk-insertions/issues/39

[DevOps] Rename the yaml-tempaltes resources to match the MAUI repo.

---

build-tools/scripts/BuildEverything.mk
build-tools/scripts/DotNet.targets

The external builds of monodroid and java.interop prep have been made
more consistent.  They will both use an `<Exec/>` task to build with the
preview dotnet SDK that is installed into `bin/$(Configuration)/dotnet`.

[build] Make external build targets more consistent

---

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs
src/Mono.Android/Mono.Android.targets

Updates the default API level used to generate API docs from 31 to 33.
The install path has been updated to use the default path that the
`sdkmanager` tool uses.

[Mono.Android] Generate API docs for API 33

---

build-tools/automation/azure-pipelines.yaml

Our pipelines should be authorized to push to the dotnet8 feed now. Update our `.yaml` to start doing this.

[build] push nightly builds to dotnet8 feed

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #6924
If the user moves the project to another location on the hard drive the build will fail with errors such as.
```
APT2126	file not found.	Foo.Foo	C:\Foo.Foo\obj\Debug\net6.0-android\lp\122\jl\res\values\attr.xml	1
```
To work around this we should place the `$(MSBuildProjectFullPath)` value in the `_PropertyCacheItems` ItemGroup. This will trigger a Clean if it changes.

[Xamarin.Android.Build.Tasks] run a Clean if the project path changes.

---

src/Xamarin.Android.Build.Tasks/ManifestOverlays/Timing.xml

API 33 requires that publicly accessible receivers need to have `android:exported="true"` added to them in order to them to work.
The Timing.xml overlay did not have this attribute, so lets add it.

[Xamarin.Android.Build.Tasks] Add 'android:exported="true"' to Timing.xml

---

tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidClientHandlerTests.cs

`httpbingo.org` is returning the following error when we try to redirect.
```
Forbidden redirect URL. Be careful with this link.
```
To lets try to use `httpbin.org` directly instead.

[tests] Switch to `httpbin.org`

---

Documentation/guides/messages/xa0134.md

Spelling error

---

build-tools/automation/azure-pipelines-nightly.yaml
tests/Mono.Android-Tests/System.Net/NetworkInterfaces.cs

Fixes #7490
Lets ass API 33 to the nightly build tests. Note the `default` image is not available so we have to use the `google_apis` image instead. 
Also it seems that under API 33 dotnet is unable to get the hardware address of the network adapters. As a result the tests which compare these were failing. So for API 33 we ignore the hardware address check, but still continue to check other aspects of the network adapters.

Add API-33 to the nightly build

---

.external

Changes: http://github.com/xamarin/monodroid/compare/8f925e3346c8aea63f3481a26c811374915b8d18...8c54ea6df5dfdbe4a0db61445e5b7f2faf9810dd
* xamarin/monodroid@8c54ea6df: Bump to xamarin/androidtools/main@df37cc76 (xamarin/monodroid#1275)
* xamarin/monodroid@cd1e08ced: Enable CodeQL on Windows build job (xamarin/monodroid#1274)
* xamarin/monodroid@1ff225b8d: Merge pull request xamarin/monodroid#1271 from xamarin/dev/msylvia/update-provisionator-bootstrap
* xamarin/monodroid@fce261626: Update provisionator bootstrap
* xamarin/monodroid@56cb29f17: Use .NET 7.0.x; Bump to xamarin/xamarin-android/main@ca2c6292 (xamarin/monodroid#1273)
Of particular note is xamarin/monodroid@8c54ea6df, which fixes a `FormatException` from `AndroidDevice.RunShellCommandAsync()`:
System.FormatException: Index (zero …

Bump to xamarin/monodroid/main@8c54ea6d

---

build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs
build-tools/xaprepare/xaprepare/Steps/Step_PrepareExternal.cs

Local builds have been occassionally failing for me:
Determining projects to restore...
C:\Users\Peter\source\xamarin-android\build-tools\xaprepare\xaprepare\package-download.proj : error NU1101: Unable to find package Microsoft.NETCore.App.Runtime.Mono.android-arm. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, darc-pub-dotnet-emsdk-c3fc739, darc-pub-dotnet-runtime-1e1f688, xamarin.android util [C:\Users\Peter\source\xamarin-android\Xamarin.Android.sln]
C:\Users\Peter\source\xamarin-android\build-tools\xaprepare\xaprepare\package-download.proj : error NU1101: Unable to find package Microsoft.NETCore.App.Runtime.Mono.android-arm64. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, darc-pub-dotnet-emsdk-c3fc739, …

[build] Pass NuGet.config when restoring

---

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs

Fixes #7473
With the new build system under `dotnet` we can end up with duplicate assemblies for different `RuntimeIdentifiers`. This can cause the `GenerateJavaStubs` task to mistakenly report duplicate types.
```
warning XA4214: The managed type `Microsoft.UI.Xaml.Controls.AnimatedIcon` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical. [C:\a\1\s\UnoAppAll\UnoAppAll.Mobile\UnoAppAll.Mobile.csproj::TargetFramework=net6.0-android]
error XA4215: The Java type `crc64a5a37c43dff01024.GridViewHeaderItem` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted. [C:\a\1\s\UnoAppAll\UnoAppAll.Mobile\UnoAppAll.Mobile.csproj::Tar …
```

[Xamarin.Android.Build.Tasks] Don't report duplicate type if the AssemblyName  is the same.

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/StartAndroidEmulator.cs
build-tools/automation/azure-pipelines-nightly.yaml
build-tools/automation/yaml-templates/run-localization-tests.yaml
build-tools/automation/yaml-templates/run-msbuild-device-tests.yaml
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/InlineData.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/MainPage.xaml
tests/MSBuildDeviceIntegration/Tests/DeploymentTest.cs
tests/Mono.Android-Tests/Xamarin.Android.Net/HttpClientIntegrationTests.cs

Lets add some unit tests for localization. These need to run on an
emulator like our timezone tests. We should do this on a nightly
test run as they take a long time to run.

[MSBuildDeviceIntegration] Add nightly localization unit tests.

---

src/Mono.Android/Mono.Android.csproj

Building our repo generates around 3400 warnings per single .NET build, similar to:
warning CA1416: This call site is reachable on: 'Android' 21.0 and later. 'Double' is only supported on: .
warning CA1422: This call site is reachable on: 'Android' 21.0 and later. 'Double' is obsoleted on: 'Android' 33.0 and later.
Since printing each message to the console needs to be synchronized, that means the build might be slower than necessary, since we generate over 10k of these messages per CI build.
Disable the warnings by default. They can be enabled by setting the `$(_EnableCodeAnalyzerPlatformWarnings)` MSBuild property to any value.

[build] Hush a couple of code analyzer warnings for Mono.Android

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-installer.yaml
build-tools/automation/yaml-templates/variables.yaml

Extend commit 78224d57 by also disabling clasic installer provisioning and test jobs when building a PR targeting a `release/*` branch.

[ci] Skip classic tests on release branch PRs

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc

Changes: https://github.com/dotnet/runtime/compare/d099f075e45d2aa6007a22b71b45a08758559f80...de84cf9f723f5d4342e95c692d088ed2af63fdbe
Changes: https://github.com/dotnet/emsdk/compare/6b7d1f47eaaa3f64c95e6f825c9e57debd4c0f31...73eb13444bdee019ec91191f96fd866661acbc78
As .NET goes into servicing mode, much of the Maestro code flow goes through internal Azure DevOps repos. In the past, we made a direct subscription to dotnet/runtime as a way to test the latest changes there (which won't even flow to dotnet/installer).
Let's do the same for `release/7.0.1xx` & .NET 7.
Removed from `Microsoft.NETCore.App.Ref`:
CoherentParentDependency="Microsoft.Dotnet.Sdk.Internal"
Then ran:
darc update-dependencies --id 157927
I found this build number via a combination of:
* Maestro site: …

[maestro] consume dotnet/runtime/release/7.0 directly

---

Configuration.props
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetStandard.cs

Changes: https://github.com/xamarin/xamarin-android/compare/9bf238f0f3eb5436cf9f9236327c3315bfc6689e...619ab7a92a09825ecb274bf87d8086d2dbe63aea

Bump to Android 32.0.485 packs for .NET 6

---

src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs

`dotnet-trace` output of a `dotnet new maui` app:
dotnet trace collect --format speedscope -- C:\src\xamarin-android\bin\Release\dotnet\dotnet.exe build -bl --no-restore bar.csproj
Shows an interesting case of `File.Exists()`:
49.88ms xamarin.android.build.tasks!Xamarin.Android.Tasks.FilterAssemblies.RunTask()
8.09ms System.Private.CoreLib.il!System.IO.File.Exists(class System.String)
The common case is the files always exist. The rare case appears to be 783ac9e9, which would be when something like a `<ProjectReference/>` doesn't exist.
Instead of calling `File.Exists()` on every .NET assembly (likely done multiple times in a build), we can handle `FileNotFoundException` and take appropriate action.
This will save ~8ms on *every* build, and we should get the exact same behavior as before. …

[Xamarin.Android.Build.Tasks] avoid `File.Exists()` check

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets
src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs

Fixes #7447
Users are reporting a error with the aapt_rules file generated by aapt2
```
MSBUILD : java.exe error JAVA0000: Error in obj\Release\110\aapt_rules.txt at line 289, column 1: [C:\Jenkins\workspace\Demo\Demo.Android\Demo.Android.csproj]
MSBUILD : java.exe error JAVA0000: Expected char '-' at obj\Release\110\aapt_rules.txt:289:1 [C:\Jenkins\workspace\Demo\Demo.Android\Demo.Android.csproj]
MSBUILD : java.exe error JAVA0000: nit>(...); } [C:\Jenkins\workspace\Demo\Demo.Android\Demo.Android.csproj]
MSBUILD : java.exe error JAVA0000: Compilation failed
```
This only happens when building with `AndroidCreatePackagePerAbi` set to `true`. After looking at the code, it turns out that we call `aapt2 link` multiple times when building per abi. The temp file used for the `aapt2 link` …

[Xamarin.Android.Build.Tasks] Fix aapt_rules.txt corruption

---

.external

Changes: https://github.com/xamarin/monodroid/compare/8c54ea6df5dfdbe4a0db61445e5b7f2faf9810dd...c0c933b7a5286c0babecb165c0676c32f5e44092
* xamarin/monodroid@c0c933b7a: Bump xamarin/android-sdk-installer, xamarin/androidtools (xamarin/monodroid#1280)
* xamarin/monodroid@87aabc519: Bump to xamarin/android-sdk-installer/main@08b836fa (xamarin/monodroid#1278)
* xamarin/monodroid@85f83d02d: Bump to xamarin/androidtools/main@f90c9565 (xamarin/monodroid#1277)

Bump to xamarin/monodroid/main@c0c933b7

---

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx
src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx

Localized file check-in by OneLocBuild Task: Build definition ID 11410: Build ID 7087603

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/App.config
src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrGenerator.cs

Reviewing `dotnet trace` output for a `dotnet new maui` app:
dotnet trace collect --format speedscope -- .\bin\Release\dotnet\dotnet.exe build -bl --no-restore foo.csproj
21% of the time in `<GenerateJavaStubs/>` is spent in:
249.60ms xamarin.android.build.tasks!Xamarin.Android.Tasks.LLVMIR.LlvmIrComposer.Write(value class Xamarin.Android.Tools.Andro...
Drilling down, some of the hot spots are:
68.64ms xamarin.android.build.tasks!Xamarin.Android.Tasks.LLVMIR.LlvmIrGenerator.WriteString(class System.String,class System.St
40.39ms xamarin.android.build.tasks!Xamarin.Android.Tasks.LLVMIR.LlvmIrGenerator.WritePointer(class Xamarin.Android.Tasks.LLVMIR
These seem to be places we create intermediate `string` or `byte[]` objects.
The types of things I solved so far:
* I audited every `$""` to …

[Xamarin.Android.Build.Tasks] perf improvements for LlvmIrGenerator

---

build-tools/automation/azure-pipelines.yaml

In https://github.com/xamarin/UITools/pull/1289, the Designer code was moved from `/Designer` to `/src`.  We need to update the paths in our CI script to reflect this change.

[ci] Fix Designer test paths

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets

Context: https://github.com/dotnet/linker/issues/3165#issuecomment-1358680001
In 2a10e969, I added a workaround for new linker behavior.
It turns out I should have used `All` instead of `Library` for now.
The original issue is still under discussion.

[Xamarin.Android.Build.Tasks] use %(TrimmerRootAssembly.RootMode) All

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/run-msbuild-device-tests.yaml
build-tools/automation/yaml-templates/run-msbuild-mac-tests.yaml
build-tools/automation/yaml-templates/run-msbuild-win-tests.yaml
build-tools/automation/yaml-templates/setup-test-environment.yaml

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7102687&view=logs&j=270ba80a-9de5-5c73-abb9-bb787532a07c&s=25cdcba1-3ecb-5490-0002-daf27c697525&t=306f7057-edf0-58b5-5004-8b3b311950d4&l=449
`provisionator` is a source of random failures like:
[21:41:23 ERR] Error Xamarin.Provisioning.ProvisioningException: Failed to provision C:\a\_work\1\s\xamarin-android\Xamarin.Android.Sdk-13.1.99.88.vsix
In this case, we were downloading a classic Xamarin.Android build for use on a test lane for `One .NET` tests?
To make things better, let's skip this step completely for `One .NET` tests. We shouldn't need to provision classic Xamarin.Android on these test lanes.
This also has the added benefit of faster test runs, just spot-checking the time spent on the above build:
* Saves 1-2 …

[build] skip provisioning of Xamarin.Android on .NET lanes

---

src/Xamarin.Android.Build.Tasks/Tasks/CheckClientHandlerType.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

`dotnet trace` of a `dotnet new maui` project, I noticed this was
happening on *any* build:
65.94ms xamarin.android.build.tasks!Xamarin.Android.Tasks.CheckClientHandlerType.RunTask()
Checking outside of a profiler, a `.binlog` says:
CheckClientHandlerType = 55 ms
This was added in 311b41e8, so it is only in main & .NET 8. Maybe when
we timed this before, it wasn't a MAUI app?
Looking at the stack trace, most of the time is spent loading
assemblies with Mono.Cecil.
Let's add a check at the beginning for the two most common values:
* .NET 6+: `Xamarin.Android.Net.AndroidMessageHandler`
* Classic: `Xamarin.Android.Net.AndroidClientHandler`
And we can return early in these cases.
After these changes, I get:
CheckClientHandlerType = 2 ms
This should save ~53ms on any build w/ common settings …

[Xamarin.Android.Build.Tasks] fast path for `<CheckClientHandlerType/>`

---

src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs

Reviewing `dotnet trace` output for a `dotnet new maui` app:
dotnet trace collect --format speedscope -- .\bin\Release\dotnet\dotnet.exe build -bl --no-restore foo.csproj
8.6% of the time in `<GenerateJavaStubs/>` is spent in:
93.81ms xamarin.android.build.tasks!Xamarin.Android.Tasks.ManifestDocument.Merge(...)
Drilling down further, a lot of time is spent in:
26.91ms java.interop.tools.javacallablewrappers!Java.Interop.Tools.TypeNameMappings.JavaNativeTypeManager.ToJniName(...)
4.03ms java.interop.tools.javacallablewrappers!Java.Interop.Tools.TypeNameMappings.JavaNativeTypeManager.ToCompatJniName(...)
It looks like we call this code for *every* Java.Lang.Object subclass:
var name        = JavaNativeTypeManager.ToJniName (t, cache).Replace ('/', '.');
var compatName  = …

[Xamarin.Android.Build.Tasks] delay ToJniName calls in ManifestDocument

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/dotnet/maui/issues/10154
If you have a solution setup with:
* `ApplicationA` project reference ->
* `LibraryB` reference ->
* `LibraryC`
The app will crash at runtime, due to a missing `LibraryC.dll`.
You can solve the problem by changing `@(Reference)` to a `@(ProjectReference)`. However, it appears the same situation works in a .NET 7 self-contained console app:
dotnet publish --self-contained -r win-x64
...
ls -n .\bin\Debug\net7.0\win-x64\publish\LibraryC.dll
LibraryC.dll
The underlying issue appears to be:
https://github.com/dotnet/msbuild/blob/a2490dd3f78cce4abc8f9e6f1b5268437332818f/src/Tasks/Microsoft.Common.CurrentVersion.targets#L2322
In the console app, `$(BuildingProject)` is `true` and `$(_FindDependencies)` is empty.
In the android app, …

[Xamarin.Android.Build.Tasks] fix cases of missing `@(Reference)`

---

Documentation/guides/building-apps/build-properties.md
src/Xamarin.Android.Build.Tasks/Tasks/D8.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.D8.targets

Fixes: https://github.com/dotnet/maui/issues/10901
Building a .NET MAUI project such as:
dotnet new maui
dotnet build -c Release -f net6.0-android -p:AndroidLinkMode=r8
Results in build warnings from R8 such as:
R8 : warning : Missing class androidx.window.extensions.WindowExtensions
In 92bc7050, we already had attempted to silence warnings from R8 such as:
R8 : warning : Resource 'META-INF/MANIFEST.MF' already exists.
At the time, there was no option to hide warnings, now there is!
--map-diagnostics[:<type>] <from-level> <to-level>
We can pass:
--map-diagnostics warning info
Which can be done in existing apps via:
<AndroidD8ExtraArguments>--map-diagnostics warning info</AndroidD8ExtraArguments>
<AndroidR8ExtraArguments>--map-diagnostics warning info</AndroidR8ExtraArguments>
To solve …

[Xamarin.Android.Build.Tasks] downgrade d8/r8 `warning` messages to `info`

---

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/ActivityAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/ApplicationAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/BroadcastReceiverAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/ContentProviderAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/GrantUriPermissionAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/InstrumentationAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/LayoutAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/MetaDataAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/PermissionAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/PermissionGroupAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/PermissionTreeAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/ServiceAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/SupportsGLTextureAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/UsesConfigurationAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/UsesFeatureAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/UsesLibraryAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/UsesPermissionAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocumentElement.cs

Context: https://github.com/xamarin/java.interop/pull/1069
Any place we had:
TypeDefinitionCache?
IMetadataResolver?
These no longer allow nulls, and so overloads that use `Obsolete` now emit errors instead of warnings:
[Obsolete ("Use the TypeDefinitionCache overload for better performance.", error: true)]
public static MethodDefinition GetBaseDefinition (this MethodDefinition method) => throw new NotSupportedException ();
This results in 3 compiler errors in xamarin-android:
src\Xamarin.Android.Build.Tasks\Mono.Android\ApplicationAttribute.Partial.cs(65,11): error CS0619: 'TypeDefinitionRocks.IsSubclassOf(TypeDefinition, string)' is obsolete: 'Use the TypeDefinitionCache overload for better performance.'
src\Xamarin.Android.Build.Tasks\Mono.Android\ApplicationAttribute.Partial.cs(268,12) …

Address breaking changes in Java.Interop

---

src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs
tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidMessageHandlerTests.cs

Fixes #7650 
We check if the server certificate hostname matches the  request's RequestUri. When the request is redirected to a different host, the verification failed because we tested the next server's hostname against the original request URI. This PR keeps the RequestUri in sync with the redirect status to avoid this problem.

Fix ServerCertificateValidationCallback after redirect

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Resource.Designer.targets
src/Xamarin.Android.Build.Tasks/Tasks/AppendCustomMetadataToItemGroup.cs
src/Xamarin.Android.Build.Tasks/Tasks/CheckForInvalidDesignerConfig.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs

After profiling a build for a `dotnet new maui` app, I noticed:
193.41ms xamarin.android.build.tasks!Xamarin.Android.Tasks.MonoAndroidHelper.HasResourceDesignerAssemblyReference()
Which equates to:
Top 10 most expensive tasks
...
AppendCustomMetadataToItemGroup = 204 ms
In dc3ccf2, we added this check to emit `XA1034` when `$(AndroidUseDesignerAssembly)` is false. And so we don't actually need to validate this value when it is `true` (the default).
I moved the logic from the `<AppendCustomMetadataToItemGroup/>` MSBuild task to a new `<CheckForInvalidDesignerConfig/>` task. In most projects, it will be completely skipped:
Target "_CheckForInvalidDesignerConfig" skipped, due to false condition; ( '$(AndroidUseDesignerAssembly)' != 'True' ) was evaluated as ( 'true' != 'True' ).
After these …

[Xamarin.Android.Build.Tasks] skip XA1034 logic in some cases

---

src/Mono.Android/Android.Hardware.Camera2/CameraAccessException.cs
src/Mono.Android/Android.Media/AudioManager.cs
src/Mono.Android/Mono.Android.csproj
src/Mono.Android/map.csv

Using Android's API-33 `annotations.zip`, some missing and incorrect enum mappings were found.
Enums that were previously left as constants have been enumified and have had the old members added back to the API with manual additions code marked with `[Obsolete]`.
```csv
I,23,android/hardware/camera2/CameraAccessException.MAX_CAMERAS_IN_USE,5,,,,
```
to
```csharp
E,23,android/hardware/camera2/CameraAccessException.MAX_CAMERAS_IN_USE,5,Android.Hardware.Camera2.CameraAccessErrorType,MaxCameraInUse,keep,
[Obsolete ("This constant will be removed in the future version. Use Android.Hardware.Camera2.CameraAccessErrorType enum directly instead of this field.")]
[Register ("MAX_CAMERAS_IN_USE", ApiSince=23)]
public const int MaxCamerasInUse = 5;
```
Other constants were assigned to the wrong …

[Mono.Android] Fix some incorrect enums.

---

src/Mono.Android/Android.Telecom/InCallService.cs
src/Mono.Android/Mono.Android.csproj
src/Mono.Android/methodmap.csv
tests/api-compatibility/acceptable-breakages-vReference-net8.0.txt
tests/api-compatibility/acceptable-breakages-vReference.txt

Fixes #2472 
`Android.Telecom.InCallService.SetAudioRoute (int)` was incorrectly enumified as `Android.Telecom.VideoQuality` instead of `Android.Telecom.CallAudioRoute`.
To fix, we need to change the enum map to generate the correct method:
```csharp
[global::System.Runtime.Versioning.SupportedOSPlatformAttribute ("android23.0")]
[Register ("setAudioRoute", "(I)V", "", ApiSince = 23)]
public unsafe void SetAudioRoute ([global::Android.Runtime.GeneratedEnum] Android.Telecom.CallAudioRoute route)
{ ... }
```
For backwards compatibility, we need to add an `[Obsolete]` overload containing the incorrect enumification:
```csharp
[Obsolete ("Incorrect enum parameter, use the overload that takes a CallAudioRoute paramter instead.")]
[global::System.Runtime.Versioning.SupportedOSPlatformAttribute …
```

[Mono.Android] Fix Android.Telecom.InCallService.SetAudioRoute enumification.

---

build-tools/automation/azure-pipelines.yaml

Context: https://github.com/xamarin/UITools/commit/9559b43b8e897daacb605d2a9ab74427a1541264
A resource used by the Designer tests now requires authentication.

[ci] Pass token when building Designer tests

---

src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceCaseMap.cs

Context: https://github.com/dotnet/maui/pull/12520
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7209613&view=results
dotnet/maui's build fails with:
Task GenerateResourceCaseMap
Parameters
ResourceDirectory = obj/Debug/net8.0-android/res/
OutputFile = obj/Debug/net8.0-android/case_map.txt
AdditionalResourceDirectories
...
Errors
/Users/builder/azdo/_work/2/s/bin/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.0-preview.1.119/tools/Xamarin.Android.Resource.Designer.targets(82,3): error XAGRCM7001: System.NullReferenceException: Object reference not set to an instance of an object.
at Xamarin.Android.Tasks.GenerateResourceCaseMap.RunTask()
at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/s …

[Xamarin.Android.Build.Tasks] fix NRE in `<GenerateResourceCaseMap/>`

---

.github/workflows/sdk-insertion-bump.yml

tldr; The action will send an event to the sdk-insertions repository that will do the correct steps to bump the version of the android project to be used in the unified pipeline.
The idea is as follows:
The action will get the information of an update branch, that is sent to the sdk-insertions repo using a client payload via a repository dispatch (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch). That event with the payload is the parsed by a second action in the sdk-insertions repo and the needed yaml files are updated. This allow to have the unified pipeline build the latest commits of the SDKs without a manual trigger.
More details can be found here: https://github.com/xamarin/sdk-insertions/wiki/Unified-pipeline#github-actions …

[Actions] Add action that will bump the hash used for the unified pipeline.

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

This reverts commit 22f2001.
.NET MAUI is hitting a build failure such as:
Unable to open file 'obj\Release\net8.0-android\android-x64\aot\x86_64\Microsoft.Maui.Controls.resources\temp.s': Permission denied
In 22f2001, we began passing satellite assemblies to the AOT compiler, on accident? I am unsure how a test in xamarin-android didn't catch this, but it may be something that only happens via a `@(ProjectReference)` as occurred in .NET MAUI.
For now, let's revert the change and revisit later.
We should reopen https://github.com/dotnet/maui/issues/10154 after this is merged.

Revert "[Xamarin.Android.Build.Tasks] fix cases of missing `@(Reference)` (#7642)"

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Resource.Designer.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs

Currently setting `AndroidGenerateResourceDesigner` to `false` does NOT stop the new resource designer assembly
from being generated. 
We should change this so that library projects which want to use this setting (as per the docs) to disable
the resoruce designer then it should work.  So if the `AndroidGenerateResourceDesigner` is set to fail we will NOT generate
the intermediate `__Microsoft.Resource.Designer.Assembly.cs` (or .fs) file. But we will still generate the assembly. 
This means the `Resource` class will not be part of the built assembly and will not be available. 
A unit test has been updated to test this change.

[Xamarin.Android.Build.Tasks] Honour the AndroidGenerateResourceDesigner setting

---

Configuration.props

Context: https://www.nuget.org/packages/Microsoft.NET.Sdk.Android.Manifest-7.0.100/33.0.26
33.0.26 is the version of the latest `android` workload in .NET 7.
Bump to this version, so we will rely on those packs in .NET 8. Previously we were using an older build, I noticed the issue when trying to dogfood .NET 8 builds on macOS:
Workload installation failed: microsoft.android.sdk.darwin::33.0.1 is not found in NuGet feeds

[build] bump `$(AndroidNet7Version)`

---

src/monodroid/CMakeLists.txt
src/monodroid/jni/cpp-util.hh
src/monodroid/jni/cxx-abi/terminate.cc
src/monodroid/jni/debug-app-helper.cc
src/monodroid/jni/debug.cc
src/monodroid/jni/embedded-assemblies-zip.cc
src/monodroid/jni/embedded-assemblies.cc
src/monodroid/jni/helpers.cc
src/monodroid/jni/helpers.hh
src/monodroid/jni/mono-log-adapter.cc
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/new_delete.cc
src/monodroid/jni/pinvoke-override-api.cc
src/monodroid/jni/strings.hh
src/monodroid/jni/timezones.cc
src/monodroid/jni/util.cc
src/monodroid/jni/xamarin-android-app-context.cc

`exit()` causes the application to restart, which can be both annoying and 
confusing when the app seemingly shows something (usually a white screen) 
and yet it doesn't work.  The only way to learn what's going on is to look 
at the logcat output to see the error message and a restart.
`abort()`, however, fully terminates the application and also shows a native 
stack trace, which makes it easy to find the cause of the "crash" (the error 
message will be logged typically just before the native stack trace is printed)

Replace all `exit()` calls with `abort()` in native code

---

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs

Changes: https://discourse.llvm.org/t/llvm-15-0-4-released/66337 
Changes: https://discourse.llvm.org/t/llvm-15-0-5-release/66616 
Changes: https://discourse.llvm.org/t/llvm-15-0-6-released/66899 
Changes: https://discourse.llvm.org/t/llvm-15-0-7-release/67638
This might be the last release in the LLVM 15 series.
Additionally, the `ldd` wrapper scripts now pass the `--no-relax` 
argument to the linker.  This argument is required by MonoVM's AOT 
compiler.

Bump LLVM to version 15.0.7

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Since https://github.com/dotnet/runtime/pull/77386 has been merged, .NET will require a certain class from  `libSystem.Security.Cryptography.Native.Android.jar` that will be located in the runtime pack files.
I'm not sure if this is the best way to pull the .jar from the runtimepack so feedback is welcome.

Use .jar files from the .NET runtime pack

---

Configuration.props
build-tools/scripts/TestApks.targets
build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs

Updates xaprepare to install arm64 versions of Android emulator
components on Apple devices that support them.  The `emulator` tool
version has also been bumped from `31.3.1` to `32.1.9`.

[xaprepare] Support arm64 emulator components

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleLegacy.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsLegacy.apkdesc
src/monodroid/jni/embedded-assemblies.cc
src/monodroid/jni/embedded-assemblies.hh

Fixes: https://github.com/xamarin/xamarin-android/issues/7335
Commit d236af54538ef1fe62d0125798cdde78e46dcd8e introduced embedded assembly compression, 
using the lz4 algorithm, which speeds up startup and reduces final package size.
Assemblies are compressed at build time and, at the same time, pre-allocated buffers for
the **decompressed** data are allocated in `libxamarin-app.so`.  The buffers are then passed
to the LZ4 APIs, all threads using the same output buffer.  The assumption was that we can
do fine without locking as even if overlapped decompression happens, the output data will be
the same and so even if two threads do the same thing at the same time, the data will be valid
at all times, so long as at least one thread completes the decompression.  
This assumption proved to be …

Prevent overlapped decompression of embedded assemblies

---

src/Mono.Android/Android.Telecom/InCallService.cs
src/Mono.Android/Android.Views/View.cs
src/Mono.Android/Android.Views/WindowManagerLayoutParams.cs
src/Mono.Android/Mono.Android.csproj
src/Mono.Android/metadata

Fixes https://github.com/xamarin/xamarin-android/issues/4290
The following API were incorrectly enumified as `StatusBarVisibility` instead of `SystemUiFlags`:
- `android.views.View.[get|set]SystemUiVisibility (int)` ([source](https://developer.android.com/reference/android/view/View#setSystemUiVisibility(int)))
- `android.views.WindowManager.LayoutParams.SystemUiVisibility` ([source](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#systemUiVisibility))
As these are properties, we cannot create an overload.  Instead create a new property called `SystemUiFlags` and obsolete the incorrect property.  Additionally, this whole thing was deprecated in API-30, so make sure we reflect that on the new method.  It's still worth fixing this, as people will be using this …

[Mono.Android] Fix WindowManagerLayoutParams.SystemUiVisibility enumification

---

.external

Fixes: https://developercommunity.visualstudio.com/t/Unable-to-debug-XamarinAndroid-system-a/10247269 Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1714340
Changes: https://github.com/xamarin/monodroid/compare/c0c933b7a5286c0babecb165c0676c32f5e44092...9b69cb11ce5dafed7126baafad28ac8dff22a5d2
* xamarin/monodroid@9b69cb11c: [tools/msbuild] Fix System App detection (xamarin/monodroid#1284)

Bump to xamarin/monodroid/d17-5@9b69cb11

---

src/Xamarin.Android.Build.Tasks/Tasks/AndroidAdb.cs
src/Xamarin.Android.Build.Tasks/Tasks/InstallApkSet.cs
src/Xamarin.Android.Build.Tasks/Tasks/JavaToolTask.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
tests/MSBuildDeviceIntegration/Tests/InstallTests.cs

Fixes https://i.azdo.io/1398544
It is quite common for users to switch from Debug to Release mode in
order to test the app. However if the `Release` build is using a custom
signing keystore you will generally see this warning and error.
```
warning MSB6006: "adb" exited with code 1.
[BT : 1.8.1] error : Installation of the app failed.
```
This is not entirely helpful. Since you need to dig into the log to
figure out what the actual issue is.
The warning is produced when we try to run `adb uninstall -k <package>`.
```
adb uninstall -k com.xamarin.foo  (TaskId:361)
The -k option uninstalls the application while retaining the data/cache. (TaskId:361)
At the moment, there is no way to remove the remaining data. (TaskId:361)
You will have to reinstall the application with the same signature, …
```

[Xamarin.Android.Build.Tasks] Fix issue where app will not install

---

Directory.Build.props

Context: https://github.com/xamarin/xamarin-android/tree/release/8.0.1xx-preview1
We branched for .NET 8 preview 1 from 34af985 into `release/8.0.1xx-preview1`.
Update xamarin-android/main's version number to 34.0.0-preview.2 for .NET 8 preview 2.

$(AndroidPackVersionSuffix)=preview.2; net8 is 34.0.0-preview.2

---

build-tools/automation/azure-pipelines-apidocs.yaml

Context: https://github.com/xamarin/java.interop/issues/1071
Adds a step to the API docs build that will fail the job if any
problematic JavadocInfo messages are found in the log.

[ci] Report issues in the API docs build log

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.EmbeddedResource.targets

On occasion we see the following error when building a Maui app.
```
MyMauiApp/Platforms/Android/AndroidManifest.xml : error APT2260: resource style/Maui.SplashTheme
(aka com.companyname.mymauiapp:style/Maui.SplashTheme) not found.
```
Looking in detail at te build log we notice that NONE of the resources in the `$(IntermediateOutputPath)\lp` folder 
are being included in the call to `aapt2`. Looking further we see two very important lines
`Skipping target "_ResolveLibraryProjectImports" because all output files are up-to-date with respect to the input files.`
```
Task "ReadLibraryProjectImportsCache" (TaskId:184)
Task Parameter:CacheFile=obj/Debug/net7.0-android/libraryprojectimports.cache (TaskId:184)
Task ReadLibraryProjectImportsCache (TaskId:184)
CacheFile: …
```

Add `_AndroidLibraryProjectImportsCache` to `FileWrites`

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs

We are seeing the `InstallAndroidDependenciesTest` test fail allot recently.
Looking at the logs we see the following warning.
```
warning : Dependency `platform-tools` should have been installed but could not be resolved. You can attempt to install it with: /Users/dean/Documents/Sandbox/Xamarin/WI1714603/bin/TestRelease/temp/InstallAndroidDependenciesTest/android-sdk/cmdline-tools/7.0/lib/sdkmanager-classpath.jar --install "platform-tools"
```
As a result `platform-tools` is not installed. This causes the `ResolveSdks` task to ignore the test sdk directory because `adb` is missing. So lets update the `AndroidSdkPlatformToolsVersion ` to use one that does work.

Bump 'InstallAndroidDependenciesTest' to use PlatformTools 34.0.0

---

src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj

Context: https://github.com/xamarin/xamarin-macios/pull/17560
Context: https://github.com/dotnet/runtime/issues/82241
On macOS, if you have both .NET 7 and .NET 8 Preview 1 installed, and you do:
* `dotnet new android`
* `dotnet build -c Release`
You get a build error:
Fatal error in IL Linker
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at Microsoft.Android.Sdk.ILLink.PreserveSubStepDispatcher..ctor()
at …

[Microsoft.Android.Sdk.ILLink] target `net7.0` temporarily

---

build-tools/scripts/NUnitReferences.projitems

The tests on the `run MSBuildDeviceIntegration On Device - macOS-1 - One .NET` job are not running due to this error:
```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Exception NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryException,    Exception thrown executing tests in /Users/runner/work/1/s/xamarin-android/bin/TestRelease/MSBuildDeviceIntegration/net7.0/MSBuildDeviceIntegration.dll
Not a TestFixture, SetUpFixture or TestSuite, but ParameterizedFixture
at NUnit.VisualStudio.TestAdapter.NUnitEngine.DiscoveryConverter.ExtractTestFixtures(NUnitDiscoveryCanHaveTestFixture parent, XElement node) in D:\repos\NUnit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitEngine\DiscoveryConverter.cs:line 272
at …
```

[tests] Bump NUnit versions to latest

---

tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs

The following test case is duplicated in `MSBuildDeviceIntegration.XASdkDeployTests (...)`:
```csharp
new object[] {
/* isRelease */      true,
/* xamarinForms */   false,
/* targetFramework*/ "net8.0-android",
},
```
This was likely a c/p error and the correct `targetFramework` is `net7.0-android`.

[MSBuildDeviceIntegration] Fix duplicated test parameter

---

Documentation/guides/messages/README.md
Documentation/guides/messages/apt2264.md
src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs
src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs

Context #7639
If a project has a long path name this can cause `aapt2` to raise a `The system cannot find the file specified` error. 
This is not very helpful since there is no obvious reason to the user as to WHY the build is failing. So we should do better.
So lets catch that specific error message and report a helpful, actionable message instead. In this case we will advise the
user that the path is probably too long and they should consult the documentation on how to resolve it. 
As for resolutions the documentation includes a number of options so it should cover all use cases. Generally these 
are 
1.  Move the project closer to the root of the drive.
2. Enable long path support in windows.
3. Make changes to the `$(BaseIntermediateOutputPath)` MSbuild property to move only the `obj` …

Handle `aapt2` error "The system cannot find the file specified." slightly better

---

src/Xamarin.Android.Build.Tasks/Tasks/ReadAndroidManifest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs

Fixes: https://github.com/dotnet/maui/issues/11345
For context users can mark their package as "testOnly" in the `AndroidManifest.xml`. When they do this `adb` also needs an additonal flag to install the package. 
PR https://github.com/xamarin/monodroid/pull/1279 adds the ability to pass this additional flag to `adb`. 
This PR adds the ability to read the flag from the `AndroidManifest.xml`, so it can be used by other tasks. 
A unit test has also been added to the Device tests to make sure we can install `testOnly` packages.

Add Unit Test for testOnly apps

---

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs

Changes: https://github.com/android/ndk/wiki/Changelog-r25#r25c
Changes potentially useful for us:
- Updated LLVM to clang-r450784d1, based on LLVM 14 development. 
- Issue 1832: Improvements to aarch64 vector code generation.

Bump NDK to r25c

---

.gitmodules
build-tools/scripts/Jar.targets
src/Mono.Android/Android.Runtime/AndroidRuntime.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/ResourceData.cs
tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj
tests/MSBuildDeviceIntegration/Resources/StaticMethodsInterface.java
tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs
tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Remaps.xml

Changes: https://github.com/xamarin/java.interop/compare/9e0a4690adb71c04cd88a5b54bea3c3f8da73cc0...bbaeda6f698369bdd48bfc2dd1a32a41c9d23229
* xamarin/java.interop@bbaeda6f: [Java.Interop] Support Desugar + interface static methods (xamarin/java.interop#1077)
Context: https://github.com/xamarin/java.interop/commit/bbaeda6f698369bdd48bfc2dd1a32a41c9d23229
Context: https://github.com/xamarin/java.interop/commit/1f27ab552d03aeb74cdc6f8985fcffbfdb9a7ddf
Context: f6f11a5a797cd8602854942dccb0f2b1db57c473
[Desugaring][0] is the process of rewriting Java bytecode so that Java 8+ constructs can be used on Android pre-7.0 (API-24), as API-24 is the Android version which added native support for Java 8 features such as [interface default methods][1].
One of the implications of desugaring is that …

Bump to xamarin/Java.Interop/main@bbaeda6f

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleLegacy.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsLegacy.apkdesc
src/monodroid/jni/embedded-assemblies.cc
src/monodroid/jni/embedded-assemblies.hh

Fixes: https://github.com/xamarin/xamarin-android/issues/7335
Context: #7732
Context: d236af54538ef1fe62d0125798cdde78e46dcd8e
Commit d236af54 introduced embedded assembly compression, using LZ4,
which speeds up startup and reduces final package size.
Assemblies are compressed at build time and, at the same time, pre-
allocated buffers for the **decompressed** data are allocated in
`libxamarin-app.so`.  The buffers are then passed to the LZ4 APIs,
all threads using the same output buffer.  The assumption was that we
can do fine without locking as even if overlapped decompression
happens, the output data will be the same and so even if two threads
do the same thing at the same time, the data will be valid at all
times, so long as at least one thread completes the decompression.
This …

[monodroid] Prevent overlapped decompression of embedded assemblies

---

.external
build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/variables.yaml

Update the build and test images for 6.0.4xx to run on macOS Monterey to
allow Big Sur machines to be candidates for OS upgrades.

[ci][6.0.4xx] Build and test on macOS Monterey

---

build-tools/automation/azure-pipelines-nightly.yaml
build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/apk-instrumentation.yaml
build-tools/automation/yaml-templates/build-windows.yaml
build-tools/automation/yaml-templates/run-localization-tests.yaml
build-tools/automation/yaml-templates/run-nunit-tests.yaml
build-tools/automation/yaml-templates/run-timezoneinfo-tests.yaml
build-tools/automation/yaml-templates/variables.yaml

Attempt to improve desktop test execution reliability by running our
test assemblies with a stable version of .NET by default.
The default value of the `useDotNet` yaml template parameters have been
flipped as part of continued efforts to remove classic test runs.
.NET 7.0 SDK provisioning has been updated to install the latest GA
version now that it is stable.

[ci] Run nunit tests with stable .NET version

---

Directory.Build.props

Context: https://github.com/xamarin/xamarin-android/tree/release/8.0.1xx-preview2
We branched for .NET 8 preview 2 from d0701eb into `release/8.0.1xx-preview2`.
Update xamarin-android/main's version number to 34.0.0-preview.3 for .NET 8 preview 3.

$(AndroidPackVersionSuffix)=preview.3; net8 is 34.0.0-preview.3

---

build-tools/create-packs/Directory.Build.targets

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7397299&view=logs&j=28f7b402-0b52-5743-3f46-b0c973acb4f8&t=06392762-0cbe-5837-5fae-a131d329206a&l=81
Context: 978b74f
Many times on release branches, parts of the .NET installer is signed, and we need to allow unsigned workloads to be installed via the `--skip-sign-check` flag:
Rolling back pack Microsoft.Android.Sdk.Windows installation...
Workload installation failed: Failed to validate package signing.
Verifying Microsoft.Android.Sdk.Windows.34.0.0-ci.darc-release-8-0-1xx-preview2-cef50a92-f62d-4147-9b74-08689588cab8.180
This is testing a local build of the `android` workload, so it will not be signed at this stage.
Let's put this change in main, so we don't have to keep doing this release branches.

[build] pass `--skip-sign-check` to `dotnet workload`

---

src/Mono.Android/Android.Runtime/AndroidRuntime.cs

Context: f6f11a5a797cd8602854942dccb0f2b1db57c473
Context: f99fc814b0dcc021a441e70bb5a487b2034f6760
How do we diagnose type & member remapping issues?  If (when) things don't work as anticipated, what do we do?
If a method is remapped *and* the remapped-to method cannot be found, then [Java.Interop will write a message to stderr][0]:
warning: For declared method `java/lang/Object.remappedToToString.()Ljava/lang/String;`, could not find requested method `java/lang/Object.toString.()Ljava/lang/String;`!
which is a scenario we think/assume Shouldn't Happen™.  If it *does* happen, we believe that the above message will be sufficient to fix the problem.
However, in the "happy" path in which the replacement method is found *or* the "less-happy" path in which *nothing happens*, how do we get …

[Mono.Android] Print type & member remapping info

---

src/Mono.Android/Android.Runtime/AndroidRuntime.cs

Context: f6f11a5a797cd8602854942dccb0f2b1db57c473
Context: f99fc814b0dcc021a441e70bb5a487b2034f6760
How do we diagnose type & member remapping issues?  If (when) things don't work as anticipated, what do we do?
If a method is remapped *and* the remapped-to method cannot be found, then [Java.Interop will write a message to stderr][0]:
warning: For declared method `java/lang/Object.remappedToToString.()Ljava/lang/String;`, could not find requested method `java/lang/Object.toString.()Ljava/lang/String;`!
which is a scenario we think/assume Shouldn't Happen™.  If it *does* happen, we believe that the above message will be sufficient to fix the problem.
However, in the "happy" path in which the replacement method is found *or* the "less-happy" path in which *nothing happens*, how do we get …

[Mono.Android] Print type & member remapping info (#7844)

---

build-tools/automation/yaml-templates/build-linux.yaml
build-tools/automation/yaml-templates/commercial-build.yaml

We want to be able to override the values of `$(NuGetArtifactName)` and
`$(LinuxNuGetArtifactName)` in the megapipeline so that artifact names
don't overlap.  We shouldn't use these variables to determine where
local build artifacts are being output to.

[ci] Allow dynamic`$(NuGetArtifactName)` values

---

eng/Version.Details.xml
eng/Versions.props

Maestro is currently failing to open new PRs due to:
> darc update-dependencies --id 169161
Looking up build with BAR id 169161
Updating 'Microsoft.Dotnet.Sdk.Internal': '8.0.100-preview.3.23128.1' => '8.0.100-preview.3.23153.7' (from build '20230303.7' of 'https://github.com/dotnet/installer')
Using 'Strict' coherency mode. If this fails, a second attempt utilizing 'Legacy' Coherency mode will be made.
Coherency updates failed for the following dependencies:
Unable to update System.IO.Hashing to have coherency with Microsoft.Dotnet.Sdk.Internal: https://github.com/dotnet/installer @ 9cf0095d0892d385a7e26772752d75e3bb68d8e4 does not contain dependency System.IO.Hashing
In 5d68699, we added a new dependency of System.IO.Hashing from dotnet/runtime.
But for …

[build] remove darc dependency for System.IO.Hashing

---

tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidMessageHandlerTests.cs

Context: https://github.com/xamarin/xamarin-android/pull/7785
Context: https://github.com/xamarin/xamarin-android/pull/7785/commits/7b2e1728295d476f23d832e48640082c9f424aa0
7b2e1728 added changes to retry the test up to 5 times should
https://httpbin.org fail the request (e.g. because of throttling).
However, I skipped building the changes locally believing that should
anything be wrong, that CI would catch it.  And it did, but the failures
weren't in the `[Tests]` tab but rather in a stage build log: the
`Mono.Android.NET-Tests.csproj` failed to build because the `[Retry]`
attribute is not available in `NUnitLite` which this test suite uses.
Additionally, `Assert.Warn` isn't supported either and the
`DoCompression` method should have been marked `async`.
Murphy must be laughing …

Fix recently added AndroidMessageHandler test

---

build-tools/automation/yaml-templates/build-windows.yaml

Quick and easy win: don't run Classic smoke tests on the Windows Build/Test stage, saving ~22 minutes.

[ci] Don't run classic tests on the Windows build/test stage.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs

Context: bec42eff7e99a6c93eaa7681d50def138bbf9115
Context: 9752257da933b3709c6de420f0139b623f78fd85
Context: …
Context: https://dl-ssl.google.com/android/repository/repository2-3.xml
Whenever Google updates their `repository2-3.xml`, there is a chance that our `AndroidDependenciesTests.InstallAndroidDependenciesTest()` unit test will fail, as `repository2-3.xml` containsn *only one* platform-tools package version, and when that changes, out test breaks.
Tracking down the cause of this breakage is annoying, usually because when this happens we've forgotten that platform-tools package version changes are the primary reason `InstallAndroidDependencies()` fails. 😅
Update `AndroidDependenciesTests.InstallAndroidDependenciesTest()` to set `$(AndroidSdkPlatformToolsVersion)`=34.0.1, fixing the …

[tests] `InstallAndroidDependenciesTest` can use `platform-tools` 34.0.1

---

build-tools/automation/yaml-templates/setup-test-environment.yaml

[Previously](https://github.com/xamarin/xamarin-android/pull/6874), we reduced the number of Android SDK Platforms that needed to be installed on CI test agents to `19,21,26,32,33`.  This can significantly reduce the amount of time needed to `xaprepare` an agent.
With most uses of Classic gone from `main`, retesting this reveals more platforms that can be removed.
Removing `19,21,26,32` saves up to 2 minutes of `xaprepare` time, particularly on Windows.
- Green after removing API 19:
- https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7456544&view=results
- Green after removing API 21:
- https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7456980&view=results
- Green after removing API 26:
- https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7457765&view=re …

[ci] Install fewer Android SDK platforms on test agents.

---

Configuration.props

Context: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/457579
Context: https://github.com/xamarin/xamarin-android/commit/58a54aef5213e50e3e59008e244a64896fe971b6
Bumps the net7.0 package reference to the latest version in VS.

Bump `$(AndroidNet7Version)`

---

.github/ISSUE_TEMPLATE/01-building-an-application.yml
.github/ISSUE_TEMPLATE/02-running-an-application.yml
.github/ISSUE_TEMPLATE/03-mono-android-api.yml
.github/ISSUE_TEMPLATE/04-binding-a-java-library.yml
.github/ISSUE_TEMPLATE/05-other.yml

Our current terminology is to use ".NET Android", not "Android for .NET".
Update our GitHub templates accordingly.

[github] Use ".NET Android", not "Android for .NET"

---

eng/Version.Details.xml
eng/Versions.props

Changes: https://github.com/dotnet/installer/compare/632ddca...cddf8e6
Changes: https://github.com/dotnet/runtime/compare/2bdc3cb...a92ed6e
Changes: https://github.com/dotnet/emsdk/compare/d7ff0aa...4c1f185
This requires a manual intervention because the dependency name changed:
--Microsoft.NET.Workload.Emscripten.Current.Manifest-8.0.100-preview.2
++Microsoft.NET.Workload.Emscripten.Current.Manifest-8.0.100-preview.3
After manually fixing up naming, I ran:
> darc update-dependencies --id 170190
I got the build number from the `.NET 8.0.1xx SDK` channel:
https://maestro-prod.westus2.cloudapp.azure.com/3074/https:%2F%2Fgithub.com%2Fdotnet%2Finstaller/latest/graph
This also partially reverts e7db44e, to use `$(DotNetPreviewVersionBand)` for the Mono and emsdk workload versions.

Bump to dotnet/installer/main@cddf8e6 8.0.100-preview.3.23163.4

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/build-macos.yaml
build-tools/automation/yaml-templates/run-msbuild-tests.yaml
build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml
build-tools/automation/yaml-templates/stage-msbuild-tests.yaml
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DeferredBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DesignerTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EnvironmentContentTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs

Context: https://github.com/xamarin/xamarin-android/pull/7850#discussion_r1130001948
With the re-parallelization of our test suites (https://github.com/xamarin/xamarin-android/pull/7804, https://github.com/xamarin/xamarin-android/pull/7850), combined with the fact that most PR's end up running the full test suite anyways, the separate "Smoke Tests" jobs aren't really saving us much, if any, CI time.  We feel we would be better off using those additional agents to run the full test suite faster.
This PR removes the separate "Smoke Tests" jobs and runs all tests in the same jobs.
Additionally, as the `[Category ("SmokeTests")]` NUnit attribute is now only used by the Windows build stage to run in-tree tests, it has been cut back to the absolute bare minimum, saving ~45 minutes.  Note that …

[ci] Remove separate SmokeTests jobs.

---

src/monodroid/CMakeLists.txt

Context: 0e4c29aabb2af023d3ff66f02d42c2b487575d85
0e4c29aa introduced builds of two library stubs, for libc
and libm libraries, to be used when no NDK is installed.
It appears that it can sometimes cause these link errors:
ld : error : undefined symbol: vtable for __cxxabiv1::__function_type_info [/Users/builder/azdo/_work/3/s/xamarin-android/src/monodroid/monodroid.csproj]
>>> referenced by stub.cc
>>>               CMakeFiles/c.dir/libstub/stub.cc.o:(typeinfo for void ())
>>> the vtable symbol may be undefined because the class is missing its key function (see https://lld.llvm.org/missingkeyfunction)
>clang++ : error : linker command failed with exit code 1 (use -v to see invocation) [/Users/builder/azdo/_work/3/s/xamarin-android/src/monodroid/monodroid.csproj]
The missing symbol …

Attempt to fix a macOS lib{c,m} link error

---

build-tools/create-packs/vs-workload.in.props

Context: https://github.com/xamarin/yaml-templates/pull/251
The VS manifest files generated during MSI conversion will now be split up using the workload pack type rather than a substring match.

[vs-workload] Remove @(MultiTargetPackNames)

---

eng/Version.Details.xml
eng/Versions.props

Context: https://github.com/dotnet/runtime/blob/059898f8c0dbea2c6d0ed2ff30bc1b584af6b439/eng/Version.Details.xml#L88-L92
Context: https://github.com/dotnet/emsdk/pull/308
Changes: https://github.com/dotnet/installer/compare/cddf8e6...c373093
Changes: https://github.com/dotnet/runtime/compare/a92ed6e...2aec381
Changes: https://github.com/dotnet/emsdk/compare/4c1f185...25d9f7a
Maestro was failing to update with:
> darc update-dependencies --id 171040
Looking up build with BAR id 171040
Updating 'Microsoft.Dotnet.Sdk.Internal': '8.0.100-preview.3.23163.4' => '8.0.100-preview.3.23170.5' (from build '20230320.5' of 'https://github.com/dotnet/installer')
Using 'Strict' coherency mode. If this fails, a second attempt utilizing 'Legacy' Coherency mode will be …

Bump to dotnet/installer/main@c373093 8.0.100-preview.3.23170.5

---

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs

Fixes https://github.com/xamarin/xamarin-android/issues/7902
Commit 2726a386 introduced the ability to ignore certain file patterns when adding files to an apk. Unfortunately it had a bug in the code and the test. The code would log a warning that is was ignoring the file, but then add the file anyway. The test was looking for the wrong path in the apk , so it would always pass the test.
This commit fixes both of these issues.

[Xamarin.Android.Build.Tasks] Fix AndroidPackagingOptionsExclude

---

Configuration.props
build-tools/create-packs/Microsoft.NET.Sdk.Android.proj
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json
src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetStandard.cs
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs

Context: https://dotnet.microsoft.com/platform/support/policy/maui
> A major version of .NET MAUI receives support for a minimum of 6
> months after a successor (the next major release) ships. For
> example, .NET MAUI 6.0 will be supported for 6 months after .NET
> MAUI 7.0 ships. Similarly, .NET MAUI 7.0 will receive support for 6
> months after .NET MAUI 8.0 ships.
By the time .NET 8 GA ships, .NET 6 MAUI projects will not be supported.
Remove .NET 6 support from the `android` workload.
I removed `net6.0-android` parameters from various tests, making sure we still have .NET 7 and .NET 8 tests.

[build] remove .NET 6 support

---

src/Mono.Android/Android.Runtime/JNINativeWrapper.cs

Reviewing `dotnet-trace` output, I noticed in a `dotnet new maui` app on a Pixel 5:
6.38ms mono.android!Android.Runtime.JNINativeWrapper.CreateDelegate(System.Delegate)
1.16ms mono.android!Android.Runtime.JNINativeWrapper.get_runtime_types()
We spend ~1ms looking up `AndroidEnvironment.UnhandledException` and `AndroidRuntimeInternal.WaitForBridgeProcessing`.
However, in this app *all* calls go to the "fast path" via `JNINativeWrapper.CreateBuiltInDelegate()`. We don't *need* to look up these methods in this app at all.
Delay the call to `get_runtime_types()` to only when it is needed via the "slow path". Will help us a small amount in .NET 8.

[Mono.Android] delay JNINativeWrapper.get_runtime_types()

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/apk-instrumentation.yaml
build-tools/automation/yaml-templates/setup-test-environment.yaml
build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml
build-tools/automation/yaml-templates/start-stop-emulator.yaml

Optimize overhead for `APK's .NET` ci job:
- Use new `start-stop-emulator.yaml` template to start the emulator before the tests begin.  If the emulator isn't working, then each test step tries to run, waits 10 minutes, and then errors out (see screenshot below).  Instead, let's just error out completely at the beginning if the emulator isn't available.
- Bump emulator timeout to 15 minutes (from 10 minutes).  Using public Mac bots can be slow, maybe giving them a little extra time will result in more successful builds.
- Call `Xamarin.Android.sln -t:PrepareJavaInterop` with ` --no-restore` to prevent it from running restore on the entire solution.
- Don't waste time installing unneeded dependencies:
- Legacy dotnet
- Mono
- NUnit.Console
- Extra Android SDK platforms

[ci] Optimize 'APK's .NET' test job overhead.

---

src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownProperties.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs
src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodsNativeAssemblyGenerator.cs
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs

Fix native code generation when marshal methods are disabled
Disabling marshal method generation turns off a lot of native code
generation in the `MarshalMethodsNativeAssemblyGenerator` class, but the
class is also responsible for outputting correctly sized cache area (an
array of X pointers) to be used by the native runtime to cache pointers
to `MonoImage` instances.
Native runtime trusts the managed runtime to generate correct code and,
thus, does not verify the size of generated array.  This trust,
unfortunately, was broken because with marshal methods disabled, the
native code generator output cache array that was 0 entries in size,
thus leading to segfault when attempting to run the application.
Fix the issue and also parametrize one of the on-device tests to be
built twice, with …

Fix native code generation when marshal methods are disabled

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes https://github.com/dotnet/maui/issues/11139
Users trying to use `maui` and the new `ApplicationVersion` in conjunction with `AndroidCreatePackagePerAbi` find that the version is NOT used in the final set of apks.
This is because when we use `AndroidCreatePackagePerAbi` we are totally ignoring the `ApplicationVersion` number. Instead we pick up the one from the `AndroidManifest.xml` `android:versionCode`. For maui users This is not obvious and is counter intuitive.
So lets use the `ApplicationVersion` when using `AndroidCreatePackagePerAbi`. All the old code will remain in place, if the `ApplicationVersion` is not set we will still fall back to `android:versionCode` and if that is not set default to `1`.

[Xamarin.Android.Build.Tasks] Fix Android Version Code for Release builds

---

build-tools/automation/yaml-templates/build-macos.yaml

The PR build pool demands don't need to be set on the unified pipeline.

[ci] Don't set demands for megapipeline

---

tests/Mono.Android-Tests/System.Net/ProxyTest.cs

Commit 112c832 broke the `QuoteInvalidQuoteUrlsShouldWork`. It is now reporting the following error.
```
System.Net.WebException : net_http_ssl_connection_failed
----> System.Net.Http.HttpRequestException : net_http_ssl_connection_failed
----> System.Security.Authentication.AuthenticationException : net_auth_SSPI
----> Interop+AndroidCrypto+SslException : Exception_WasThrown, Interop+AndroidCrypto+SslException
```
Revert back to use the previous url until we can figure this one out.

[/Mono.Android-Tests] Revert back to example.com

---

src/monodroid/CMakeLists.txt

We are seeing the following build error on Nightly builds.
```
ld : error : undefined symbol: vtable for __cxxabiv1::__function_type_info [/Users/builder/azdo/_work/3/s/xamarin-android/src/monodroid/monodroid.csproj]
clang++ : error : linker command failed with exit code 1 (use -v to see invocation) [/Users/builder/azdo/_work/3/s/xamarin-android/src/monodroid/monodroid.csproj]
ld : error : undefined symbol: vtable for __cxxabiv1::__function_type_info [/Users/builder/azdo/_work/3/s/xamarin-android/src/monodroid/monodroid.csproj]
clang++ : error : linker command failed with exit code 1 (use -v to see invocation) [/Users/builder/azdo/_work/3/s/xamarin-android/src/monodroid/monodroid.csproj]
```
The code changes in the PR will fix this.

[monodroid] Fix `ld` build error on Nightly Builds.

---

Directory.Build.props
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/ArchiveAssemblyHelper.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/MainActivity.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/DotNet/MainActivity.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/MainActivity.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Wear/MainActivity.cs
tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj
tests/MSBuildDeviceIntegration/Tests/LocalizationTests.cs

Tests https://github.com/xamarin/xamarin-android/issues/7622
Localisation assemblies were not being fast deployed. Commit https://github.com/xamarin/monodroid/commit/1f52d5873960cf72685b9b08dbe262fc1ad4ca13
fixed that. However we need to add a unit test to make sure that these files are deployed and 
actually produce the required results. 
So lets use Humanizer to handle the localisation. This PR adds a test which checks that the 
app on the device outputs the expected text which Humanizer is supposed to generate. 
It also updates existing packaging tests to make sure that the required satellite assemblies are
packaged.

Add Nightly Tests for Humanizer 

---

build-tools/automation/yaml-templates/build-windows.yaml
build-tools/automation/yaml-templates/commercial-build.yaml

Now that we no longer run any Classic test suites in `main`, we no longer need to build them with `Xamarin.Android-Tests.sln`.
The .NET test suites that we do use are built in `Xamarin.Android.sln` or built locally on the test agents with the installed XA test packages.
This saves about 7.5 minutes from the Mac Build.

[ci] Stop building classic test suites.

---

src/Microsoft.Android.Sdk.ILLink/PreserveLists/Mono.Android.xml
tests/MSBuildDeviceIntegration/Resources/LinkDescTest/MainActivityReplacement.cs
tests/MSBuildDeviceIntegration/Resources/LinkDescTest/PreserveTest.cs
tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/7953
When a timezone changes in a `Release` app, it can crash with:
[monodroid] Unable to find Android.Runtime.AndroidEnvironment.NotifyTimeZoneChanged()!
In 11f0e1b, we removed the line:
<?xml version="1.0" encoding="utf-8" ?>
<linker>
<assembly fullname="Mono.Android">
--      <type fullname="Android.Runtime.AndroidEnvironment" />
Unfortunately, this method is called from native code, so we need to *always* preserve it.
Added a test for this scenario, we may want to audit all `mono_class_get_method_from_name` calls and add more tests cases.
I also cleaned up the tests a bit with a `getResource()` local function.

[Microsoft.Android.Sdk.ILLink] fix crash when TZ changes

---

build-tools/automation/yaml-templates/apk-instrumentation.yaml
build-tools/automation/yaml-templates/run-dotnet-preview.yaml

The `apk-instrumentation` tests are a good candidate for using `retryCountOnTaskFailure`.  This is because they only take a few minutes to run, and have a low enough flaky rate that it is likely that rerunning the entire test suite will succeed.
As noted in https://github.com/xamarin/java.interop/pull/1095, AzDO's support for this isn't perfect.  The initial failure will still show up in the Error Log, however the task will be green and will not show up as a failed build.
Ironically, you can see it in action on this build because we have an HTTP test that is currently failing with 504.  🤷‍♂️

[ci] Automatically retry failed apk-instrumentation tests.

---

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/ZipArchiveEx.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context https://i.azdo.io/1782014
On Windows customers are seeing the following error
```
Error XABLD7000: Xamarin.Tools.Zip.ZipException: Renaming temporary file failed: Permission denied
at Xamarin.Tools.Zip.ZipArchive.Close() in /Users/runner/work/1/s/LibZipSharp/Xamarin.Tools.Zip/ZipArchive.cs:line 939
```
We have traced this to the use of the `MoveFileExW`/`MoveFileExA` API. When libzip is trying to move its temp file to the final location, Windows is raising this error.
```
Renaming temporary file failed: Permission denied
```
Turning off Anti Virus seems to help, however adding an exclusion does not. This is very confusing. So we are unsure why this error is being raised. The process has the correct permissions and the file being moved is in the same directory, so its not a TEMP …

[Xamarin.Android.Build.Tasks] Bump ZipFlushFilesLimit

---

build-tools/automation/azure-pipelines.yaml

Context: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-security-configuration/azdo-config-remediation/forked-builds#secure-supply-chain-analysis-build-task-enforcement
We have an exception for our pipeline configuration filed in
https://msazure.visualstudio.com/One/_workitems/edit/15310210.

[ci] Suppress fork PR build warnings

---

build-tools/automation/yaml-templates/start-stop-emulator.yaml

Lets add the `xaSourcePath` parameter to some yaml files so that they can be called from `monodroid`.

[automation] Add 'xaSourcePath' to yaml so they can be used from monodroid

---

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs
src/Mono.Android/metadata
src/Mono.Android/methodmap.csv

Context: https://developer.android.com/about/versions/14
Context: https://android-developers.googleblog.com/2023/04/android-14-beta-1.html
Android 14 Developer Preview 1 has been released.  The Android 14
* Feb/Mar: Developer Previews
* April/May: Unstable Betas
* June/July: Stable Betas
* ???: Final
[0]: https://developer.android.com/about/versions/14/overview

[Mono.Android] API-UpsideDownCake Beta 1

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/build-linux.yaml

We should use Microsoft hosted machines for PR builds wherever possible.

[ci] Use hosted Linux build pool for PR builds

---

build-tools/automation/yaml-templates/setup-test-environment.yaml

The `ExtractWorkloadPacks` target used in test environment setup expects
nuget artifacts to be in a `nuget-unsigned` folder, so we should always
download to this folder even if the names of the nuget artifacts differ.

[ci] Always download nupkgs to nuget-unsigned

---

Directory.Build.props

Context: https://github.com/xamarin/xamarin-android/tree/release/8.0.1xx-preview4
We branched for .NET 8 preview 4 from a8de67e into `release/8.0.1xx-preview4`.
Update xamarin-android/main's version number to 34.0.0-preview.5 for .NET 8 preview 5.

$(AndroidPackVersionSuffix)=preview.5; net8 is 34.0.0-preview.5

---

Configuration.props

Changes: https://github.com/xamarin/xamarin-android/compare/33.0.46...837ca0d8
This updates the stable .NET 7 workload that the .NET 8 workload depends on.

Bump to 33.0.56 $(AndroidNet7Version)

---

build-tools/automation/azure-pipelines.yaml

Commit https://github.com/xamarin/xamarin-android/commit/ecb207baf07c1829adbbe41231cc7913097a2c61 broke the `plots-to-appinsights` process that only gets run on `main` (not PR builds).
As we do not believe this data is consumed anymore, we are electing to remove it from CI rather than make the necessary updates to get it working again.
Note there are some alternatives to this data that are used today:
- Unit tests that test build time and use `apidiff` to test apk size
- MAUI maintains a dashboard of similar graphs for their builds, which are our builds.

[ci] Remove plots-to-appinsights.

---

Documentation/guides/OneDotNetBindingProjects.md
Documentation/guides/building-apps/build-properties.md
src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets
src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
src/Xamarin.Android.Build.Tasks/Tasks/Generator.cs

Context: https://github.com/xamarin/java.interop/issues/1081
Context: https://github.com/xamarin/java.interop/pull/1094
Adds support for emitting `[Obsolete]` warnings for API marked with `androidx.annotation.RestrictTo`.  These warnings inform the user that the package owner does not consider an API to be "public".  These warnings have a custom warning code (`XAOBS001`) that can be suppressed if desired.
This is enabled by default with the value `obsolete`, but can be disabled by setting `$(AndroidEnableRestrictToAttributes)` to `disable`.
```xml
<AndroidEnableRestrictToAttributes>disable</AndroidEnableRestrictToAttributes>
```

[Xamarin.Android.Build.Tasks] Add support for 'AndroidEnableRestrictToAttributes'.

---

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs

Google released an `r2` of `platform-33` while we are still using `r1`.  Our CI machines come pre-loaded with `r2`, so this means we have to provision `r1` instead on every run.
- [Windows agent image](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#android)
- [Mac agent image](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#android)
Running `class-parse` against both versions of `android.jar` produce an identical file, so there are no API changes in `r2`.

[Mono.Android] Use 'platform33-r2'.

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/setup-test-environment.yaml
build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml
build-tools/xaprepare/xaprepare/Scenarios/Scenario_AndroidTestDependencies.cs
build-tools/xaprepare/xaprepare/Scenarios/Scenario_EmulatorTestDependencies.cs

For test agents that run emulator tests, we currently run `xaprepare` twice with different scenarios:
- AndroidTestDependencies
- EmulatorTestDependencies
As there is some overhead to running `xaprepare`, we can instead make `EmulatorTestDependencies` depend on the `AndroidTestDependencies` scenario.  Then we only need to run a single `xaprepare` invocation.
These steps vary wildly on each run, but averaging 8 runs seems to save over a minute.
| | `main`, 2 steps total time | PR, 1 step |
|-|-|-|
| MSBuild 1 | 5:50 | 3:52 |
| MSBuild 2 | 2:52 | 2:44 |
| MSBuild 3 | 3:26 | 4:32 |
| MSBuild 4 | 4:18 | 2:44 |
| MSBuild 5 | 3:00 | 2:02 |
| MSBuild 6 | 6:52 | 6:05 |
| MSBuild 7 | 6:41 | 2:48 |
| MSBuild 8 | 7:31 | 4:34 |
| Average | 5:03 | 3:40 |

[xaprepare] Combine 'AndroidTestDependencies' and 'EmulatorTestDependencies' scenarios.

---

build-tools/automation/yaml-templates/install-dotnet-test-slicer.yaml
build-tools/automation/yaml-templates/run-msbuild-tests.yaml
build-tools/automation/yaml-templates/run-sliced-nunit-tests.yaml
build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml
build-tools/automation/yaml-templates/start-stop-emulator.yaml

[Previously](https://github.com/xamarin/xamarin-android/pull/7963), we have used `retryCountOnTaskFailure` to retry some of our flaky test suites.  However this is not a good solution for our MSBuild and emulator tests for 2 reasons:
- Running each suite takes 30-60 minutes, so it would take a long time to retry the entire suite.
- The suites are very flaky, and rerunning the entire suite would likely result in test(s) that were successful on the first run to fail on the second.
We need a solution that only retries the specific test(s) that failed.  Unfortunately nothing like that exists, so we'll once again have to roll our own solution, and we can reuse `dotnet-test-slicer` for this.
This involves some trickery to make everything show up correctly in the AzDO UI:
- Run the initial test …

[ci] Automatically retry failed MSBuild/emulator tests.

---

Configuration.props
build-tools/automation/yaml-templates/variables.yaml
build-tools/scripts/NUnitReferences.projitems
build-tools/scripts/nunit3-console
build-tools/scripts/nunit3-console.cmd

With the new auto-retry for failed emulator tests we are seeing some weird results.
Example:
The first run failed with:
```
Failed DotNetInstallAndRun(True,True,"net8.0-android") [12 m 11 s]
Error Message:
`dotnet run` should succeed
Expected: True
Stack Trace:
at Xamarin.Android.Build.Tests.XASdkDeployTests.DotNetInstallAndRun(Boolean isRelease, Boolean xamarinForms, String targetFramework) in /Users/builder/azdo/_work/1/s/xamarin-android/tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs:line 87
1)    at Xamarin.Android.Build.Tests.XASdkDeployTests.DotNetInstallAndRun(Boolean isRelease, Boolean xamarinForms, String targetFramework) in /Users/builder/azdo/_work/1/s/xamarin-android/tests/MSBuildDeviceIntegration/Tests/XASdkDeployTests.cs:line 87
```
The retry failed …

Bump NUnit versions.

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml

The "stop emulator" step on CI generally takes ~35-40 seconds.
However, our Mac agents are public images that are not reused, so there is no benefit to cleaning up after ourselves.
Create a new parameter called `macTestAgentsUseCleanImages` and don't bother stopping the emulator if it set to true.  (We currently only run emulators on Macs.)

[ci] Don't stop emulator on test agents that won't get reused.

---

build-tools/create-packs/Microsoft.Android.Ref.proj
build-tools/installers/create-installers.targets
build-tools/scripts/JavaCallableWrappers.targets
src/Mono.Android/Mono.Android.csproj
src/Mono.Android/Mono.Android.targets

The `UpdateExternalDocumentation` target has been updated to run against
the .NET version of Mono.Android.dll, as we no longer need to generate
docs and doc redirects for the classic installers.

[Mono.Android] Generate API docs for .NET Android

---

build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml

Update the WearOS Emulator job to use the same enhancements made to the other emulator jobs:
- Do not install unnecessary dependencies
- Auto-retry failed emulator tests

[ci] Simplify WearOS Emulator test job.

---

Documentation/guides/building-apps/build-targets.md
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Application.targets

Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1777086
Context: https://github.com/xamarin/xamarin-android/blob/17c74c5cfcc383464931e6a2f828a689ba998965/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs#L187-L190
If an android app is already running, and you do one of:
dotnet build -t:Run
dotnet build -t:StartAndroidActivity
It doesn't actually close and restart the app.
To do this, we need to pass `-S`:
am start: start an Activity.  Options are:
...
-S: force stop the target app before starting the activity
This appears to work fine going back to API 21, we are already using this flag in unit tests.
Now the `<Exec/>` task prints an extra line:
Stopping: com.companyname.foo
Starting: Intent { …

[Xamarin.Android.Build.Tasks] pass `-S` for `am start` commands

---

src/Mono.Android.Export/Mono.Android.Export.csproj
src/Mono.Android/Mono.Android.csproj
src/Mono.Android/Mono.Android.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj

Remove `monoandroid10` target framework from `Mono.Android.csproj` and `Mono.Android.Export.csproj`.
This enables removing `net472` from Java.Interop: https://github.com/xamarin/java.interop/pull/1099.

[Mono.Android] Remove `monoandroid10` target framework.

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/AssertionExtensions.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.EmbeddedResource.targets

Context: https://github.com/xamarin/AndroidX/pull/729
A customer reported a build error such as:
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.46\targets\Microsoft.Android.Sdk.AndroidLibraries.targets(77,5):
error XACAAR7014: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
at System.Text.StringBuilder.ToString()
at Xamarin.Android.Tasks.CreateAar.RunTask()
at Microsoft.Android.Build.Tasks.AndroidTask.Execute()
Somewhere here:
https://github.com/xamarin/xamarin-android/blob/c31f3eda63a16e412a39fa61eb0f885be3c5f543/src/Xamarin.Android.Build.Tasks/Tasks/CreateAar.cs#L108-L114
The problem appears to be triggered by:
ProguardConfigurationFiles=
~\.nuget\packages\xamarin.androidx.versionedparcelable\1.1.1.15\buildTransitive\net6.0-andro …

[Xamarin.Android.Build.Tasks] skip `proguard.txt` files in class libraries

---

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props

Context: https://aka.ms/maui-support-policy
Context: https://github.com/xamarin/xamarin-android/issues/8003
To be able to emit a new build warning:
dotnet\sdk\6.0.409\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(35,5):
warning NETSDK1138: The workload 'android' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/maui-support-policy for more information about the support policy.
We can emit a new item group, such as:
<ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'android' and $([MSBuild]::VersionEquals($(TargetFrameworkVersion), '6.0')) ">
<EolWorkload Include="android" Url="https://aka.ms/maui-support-policy" />
</ItemGroup>
Changes in the .NET SDK can be found at: …

[Xamarin.Android.Build.Tasks] add metadata about .NET 6 EOL
