Configuration.props
Changes: https://github.com/xamarin/xamarin-android/compare/619ab7a9...25cb50d7
This brings the changes for .NET 6 EOL.
=> Bump .NET 6 to 32.0.509

build-tools/automation/yaml-templates/use-dot-net.yaml
We've recently seen an increase in intermittent issues causing .NET SDK
installation steps to fail in CI.  We should be able to make these
job steps more robust by adding a "task retry".
=> [ci] Retry .NET install attempts

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, src/Mono.Android/Java.Lang.Invoke/MethodType.cs, src/Mono.Android/Java.Lang/Class.cs, src/Mono.Android/Mono.Android.csproj, src/Mono.Android/metadata
Context: https://developer.android.com/about/versions/14
Context: https://android-developers.googleblog.com/2023/05/android-14-beta-2.html
Android 14 Beta 2 has been released.  The Android 14
* Feb/Mar: Developer Previews
* April/May: Unstable Betas
* June/July: Stable Betas
* ???: Final
[0]: https://developer.android.com/about/versions/14/overview
This update added several new interfaces to existing classes in `Java.Lang.*`.  Ensuring our classes implemented these interfaces without changing the existing class methods took some creative solutions.  Each instance should be reasonably documented with inline comments.
=> [Mono.Android] API-UpsideDownCake Beta 2

Documentation/guides/messages/xa5300.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
Improve the XA5300 error messages to be more "actionable" by linking to instructions to install the Android SDK and JDK:
<https://aka.ms/dotnet-android-install-sdk>
=> [Xamarin.Android.Build.Tasks] Update XA5300 text

.external
Fixes: https://github.com/xamarin/xamarin-android/issues/7658
Changes: https://github.com/mono/mono/compare/6dd9def57ce969ca04a0ecd9ef72c0a8f069112d...73df89a73d2aa08155fca01b75f2cc2944bbb7ea
* mono/mono@73df89a73d2: Fix xar url again
* mono/mono@36fd1837d0d: Switch back to original xar version
* mono/mono@5bbc709e5dc: Fix xar download url
* mono/mono@3cb47d8b4dc: [mono] Use `unsigned char` when computing UTF8 string hashes (mono/mono#21633)
* mono/mono@a102a350e53: [2020-02] [mono][loader] Set status on success; avoid mmap on Android (mono/mono#21610)
* mono/mono@74f85c2ac33: Fix url to gtksharp msi
* mono/mono@2f7d584ad2b: Fix build on macOS 13 / Xcode 14 (mono/mono#21597)
* mono/mono@03b09960787: Disable a failing test
=> Bump to mono/mono/2020-02@73df89a7

.external, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs
Adds a test for:
https://github.com/xamarin/monodroid/pull/1309
Bump to xamarin/monodroid/main@dbc9c67e
Changes: https://github.com/xamarin/monodroid/compare/5aed7edd...dbc9c67e
=> [tests] new test for provisioning JDKs

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.ClassParse.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets
There are a few instances where we would like to run a custom/updated `generator` and `class-parse` with an existing .NET install:
- AndroidX/GPS would like newer fixes that may not have been backported to previous target frameworks that are still shipped
- We would like some CI for `generator` itself that runs proposed changes against a large corpus like AndroidX/GPS before being committed to detect possible bugs sooner
- Being able to easily test local `generator` changes against test cases without using `dotnet-local` (especially for running inside VS)
To facilitate this, add the internal MSBuild option `$(_BindingsToolsLocation)` which can be set to a path where a custom/updated `generator`/`class-parse` exist:
```
dotnet build MyBindings.csproj …
```
=> [Xamarin.Android.Build.Tasks] Add $(_BindingsToolsLocation) to allow overriding binding tool binaries.

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/Eol.targets, src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/8003
Add a new `Eol.targets` file to be imported for `net6.0-android` projects. It contains the necessary/minimal settings to emit the build error:
Microsoft.NET.EolTargetFrameworks.targets(35,5): error NETSDK1202:
The workload 'android' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/maui-support-policy for more information about the support policy.
We will probably need the latest .NET SDK to flow to us, in order to write a test. I could only test locally by editing `.targets` files in the .NET SDK.
=> [Xamarin.Android.Build.Tasks] introduce Eol.targets for .NET 6

Directory.Build.props
Context: https://github.com/xamarin/xamarin-android/tree/release/8.0.1xx-preview5
We branched for .NET 8 preview 5 from a2f41716 into `release/8.0.1xx-preview5`.
Update xamarin-android/main's version number to 34.0.0-preview.6 for .NET 8 preview 6.
=> $(AndroidPackVersionSuffix)=preview.6; net8 is 34.0.0-preview.6

Configuration.props
Changes: https://github.com/xamarin/xamarin-android/compare/d96a7a1a...a7e0eff1
These changes are going out in a future servicing release.
=> Bump to 33.0.68 $(AndroidNet7Version)

build-tools/automation/azure-pipelines.yaml
Commit https://github.com/xamarin/xamarin-android/commit/ca5ff9b06b2aab969f837b869883459b944f8e04 migrated our Linux PR build and test jobs to Microsoft
hosted agents.  At the time it seemed that we had trimmed our build
output and provisioning requirements enough to fit within the 10GB disk
space limit of the hosted agents.  However, we've been running into disk
issues recently:
System.IO.IOException: No space left on device : '/home/vsts/agents/3.220.2/_diag/Worker_20230605-125326-utc.log'
A new [`android-devdiv-ubuntu-vmss-pr`][0] scaling pool has been set up
for Linux PR builds and tests, with the same configuration as the
`android-devdiv-ubuntu-vmss` pool used for non PR builds.
[0]: https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/cd4829e2-e38b-43d2-8316 …
=> [ci] Use new 1ES Hosted Linux PR build pool

Configuration.props, build-tools/automation/azure-pipelines-nightly.yaml, build-tools/scripts/RoslynAnalyzers.projitems, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Tools.Aidl/Xamarin.Android.Tools.Aidl.csproj, src/Xamarin.Android.Tools.JavadocImporter/Xamarin.Android.Tools.JavadocImporter.csproj
Commit 04e4bb1e turned `CA1305` into a build error for projects in the
`src` directory, however the .NET analyzers that detect this issue only
run by default on projects targeting .NET 5.0 or later.  Sources that
target `netstandard2.0` (including our build tasks) contain instances of
`CA1305` that should be fixed, but these errors weren't being reported
in our regular builds.
Our nightly build managed to catch _some_ of these issues, as this build
set an MSBuild property that would cause our sources to import the FxCop
NuGet package.
FxCop is deprecated, and it should be replaced by using the first-party
.NET analyzers.  These analyzers can be enabled for projects with older
target frameworks by setting the [`$(EnableNETAnalyzers)`][0] property
to `true`.  This property is now set to …
=> [build] Ignore CA1305 in more projects

build-tools/automation/yaml-templates/run-sliced-nunit-tests.yaml
Context: https://github.com/xamarin/xamarin-android/pull/8021
The previous attempt to fix the `"Unknown abi"` error on retried unit tests was unsuccessful.  Perhaps the issue is our old friend MSBuild node reuse?
Call `dotnet build-server shutdown` before retrying tests.
=> [ci] Shut down dotnet processes before retrying failed unit tests.

Configuration.props
Context: https://github.com/android/ndk/issues/1299
Context: https://developer.android.com/tools/releases/build-tools
Similar to the Android NDK (android/ndk#1299), `aapt2` from the Android SDK build-tools package is also a native binary.
`aapt2` from build-tools_r32 only contains an x64 slice:
% file aapt2
aapt2: Mach-O 64-bit executable x86_64
`aapt2` in build-tools_r33 and build-tools_r34 contains both x64 and arm64 slices:
% file aapt2
aapt2: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
aapt2 (for architecture x86_64):	Mach-O 64-bit executable x86_64
aapt2 (for architecture arm64):	Mach-O 64-bit executable arm64
Update `$(XABuildToolsVersion)`=34, so that we redistribute this newer `aapt2` binary.  This will remove *a* place that …
=> [build] Bump `$(XABuildToolsVersion)`=34

src/Microsoft.Android.Sdk.ILLink/Properties/Resources.cs.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.de.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.es.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.fr.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.it.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.ja.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.ko.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.pl.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.pt-BR.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.ru.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.tr.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.zh-Hans.resx, src/Microsoft.Android.Sdk.ILLink/Properties/Resources.zh-Hant.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 7902488

src/Mono.Android/Android.App/Dialog.cs, src/Mono.Android/Android.App/FragmentManager.cs, src/Mono.Android/Android.Graphics/Color.cs, src/Mono.Android/Android.OS/AsyncTask.cs, src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android.Runtime/JavaCollection.cs, src/Mono.Android/Android.Runtime/JavaDictionary.cs, src/Mono.Android/Android.Runtime/JavaList.cs, src/Mono.Android/Android.Runtime/JavaSet.cs, src/Mono.Android/Android.Runtime/XmlPullParserReader.cs, src/Mono.Android/Android.Runtime/XmlReaderPullParser.cs, src/Mono.Android/Android.Telephony/CellInfo.cs, src/Mono.Android/Android.Views/View.cs, src/Mono.Android/Android.Views/Window.cs, src/Mono.Android/Android.Widget/ArrayAdapter.cs, src/Mono.Android/Java.Interop/JavaConvert.cs, src/Mono.Android/Java.Interop/JavaObjectExtensions.cs, src/Mono.Android/Java.Interop/TypeManager.cs, src/Mono.Android/Java.Lang/Object.cs, src/Mono.Android/System.Drawing/PointConverter.cs, src/Mono.Android/System.Drawing/RectangleConverter.cs, src/Mono.Android/System.Drawing/SizeConverter.cs, src/Mono.Android/System.Drawing/SizeFConverter.cs, src/Mono.Android/System.Linq/Extensions.cs, src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs, src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs, src/Mono.Android/Xamarin.Android.Net/AuthDigestSession.cs, src/Mono.Android/Xamarin.Android.Net/AuthModuleBasic.cs, src/Mono.Android/Xamarin.Android.Net/NegotiateAuthenticationHelper.cs, src/Mono.Android/Xamarin.Android.Net/ServerCertificateCustomValidator.cs
Fix ~67 NRT warnings in hand-written code when binding `Mono.Android`.
=> [Mono.Android] Fix NRT warnings in hand bound code.

src/Mono.Android/Android.Runtime/AndroidRuntime.cs, src/Mono.Android/Java.Interop/JavaObjectExtensions.cs, src/Mono.Android/Java.Interop/TypeManager.cs
Context: https://github.com/xamarin/xamarin-android/issues/5652
Building an app such as:
dotnet build -c Release -p:SuppressTrimAnalysisWarnings=false -p:TrimmerSingleWarn=false
Results in many illink/trimmer warnings:
external\Java.Interop\src\Java.Interop\Java.Interop\JniRuntime.JniMarshalMemberBuilder.cs(57,4): warning IL2072: Java.Interop.JniRuntime.SetMarshalMemberBuilder(JniRuntime.CreationOptions): 'type' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in call to 'System.Activator.CreateInstance(Type)'. The return value of method 'System.Reflection.Assembly.GetType(String)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is …
=> [Mono.Android] suppress/solve more illink warnings

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
I was investigating a failure building Android projects in `Release` mode inside VS Mac:
Task "GenerateJavaStubs"
Failed to read '/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.android-arm/8.0.0-preview.5.23280.8/runtimes/android-arm/lib/net8.0/Microsoft.CSharp.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
System.UnauthorizedAccessException: Access to the path '/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.android-arm/8.0.0-preview.5.23280.8/runtimes/android-arm/lib/net8.0/Microsoft.CSharp.dll' is denied.
---> System.IO.IOException: Permission denied
--- End of inner exception stack trace ---
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
at Interop.CheckIo(Error …
=> [Xamarin.Android.Build.Tasks] <GenerateJavaStubs/> should open readonly in some cases

src/Xamarin.Android.Build.Tasks/Tasks/BuildAppBundle.cs, tests/MSBuildDeviceIntegration/Tests/BundleToolTests.cs, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
Users reported that when they added a custom `uncompressedGlob` entry to the `$(AndroidBundleConfigurationFile)`, it was ignored. This is because the `MergeArrayHandling` option we were using in the `BuildAppBundle` task was set to `MergeArrayHandling.Replace`.
As a result we would just overwrite the user config with our own. We should be using the `MergeArrayHandling.Union` option instead. This with merge the arrays , but will remove duplicates. This should allow users to provide additional `uncompressedGlob` options.
A unit test has been added to test this new behaviour.
=> [Xamarin.Android.Build.Tasks] Allow override of `uncompressedGlob`.

Configuration.props
Context: https://learn.microsoft.com/nuget/reference/cli-reference/cli-ref-environment-variables
I recently paved my Windows PC and set `%NUGET_PACKAGES%` to a Dev Drive at:
D:\.nuget\packages
This caused Xamarin.Android's build to fail with:
Mono.Android.targets(220,5): error : CompatApi command: dotnet "C:\Users\jonat\.nuget\packages/microsoft.dotnet.apicompat/7.0.0-beta.22103.1/tools/net472/..\netcoreapp3.1\Microsoft.DotNet.ApiCompat.dll" "D:\src\xamarin-android\tests\api-compatibility\reference\net8.0\Mono.Android.dll" -i "D:\src\xamarin-android\bin\Debug\lib\xamarin.android\xbuild-frameworks\Microsoft.Android\33" --allow-default-interface-methods --baseline "D:\src\xamarin-android\tests\api-compatibility\acceptable-breakages-vReference-net8.0.txt" --validate-baseline …
=> [build] consider $NUGET_PACKAGES for $(XAPackagesDir)

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Fixes: https://github.com/dotnet/maui/issues/15696
Context: https://github.com/dotnet/sdk/pull/30038
In .NET 8 Preview 5, there are various changes to default values:
* `dotnet publish` is now `Release` by default
* Builds that provide a `$(RuntimeIdentifier)` are no longer "self contained" by default.
The result of this change is the problem:
dotnet publish
Microsoft.NET.RuntimeIdentifierInference.targets(212,5): error NETSDK1191: A runtime identifier for the property 'SelfContained' couldn't be inferred. Specify a rid explicitly.
While these commands all work:
dotnet build
dotnet build -c Release
dotnet publish -c Debug
dotnet publish -r android-arm64
`Debug` configurations work fine, because trimming is not involved. `dotnet build` works fine, because the offending …
=> [One .NET] fix 'dotnet publish' with no arguments

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
Context: https://github.com/xamarin/xamarin-android/pull/8116/commits/95f4b796700b2acaedb9bb58ba24f84b39de8891
When making API 34 the default in .NET 8, some tests tried to build `net7.0-android` projects with an `AndroidManifest.xml` that contains:
<uses-sdk android:targetSdkVersion="34" />
This won't work until we backport API 34 to .NET 7.
In general, you shouldn't use `<uses-sdk/>` in .NET 6+ apps as the following MSBuild properties should be used instead:
<TargetFramework>net7.0-android33</TargetFramework>
<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
Where `33` is implicit if left out.
Let's no longer set `TargetSdkVersion` by default in our MSBuild tests, as this is closer to what customers will do. We also no longer build or test Xamarin.Android in main.
I removed …
=> [tests] don't set `/uses-sdk@android:targetSdkVersion=34` by default

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs, src/Xamarin.Android.Build.Tasks/Utilities/Aapt2Daemon.cs
When cancelling a build on the command line we occasionally see the following exception.
```
Unhandled exception. System.IO.IOException: Broken pipe
---> System.Net.Sockets.SocketException (32): Broken pipe
at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
--- End of inner exception stack trace ---
at System.IO.Pipes.PipeStream.WriteCore(ReadOnlySpan`1 buffer)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.IO.StreamWriter.WriteLine(String value)
at Xamarin.Android.Tasks.Aapt2Daemon.Aapt2DaemonStart()
at System.Threading.Thread.StartHelper.Callback(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at …
```
=> [Xamarin.Android.Build.Tasks] Handle IOException in Aapt2Daemon

Configuration.props, Documentation/release-notes/bundletool-1.8.1.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
Context: https://github.com/google/bundletool/releases/tag/1.15.1
Changes: https://github.com/google/bundletool/compare/1.8.1...1.15.1
We are seeing an error with API 34:
XABBA7024: Xamarin.Tools.Zip.ZipIOException: The file 'obj\Release\android\bin\base.zip' is not a ZIP archive.
We wonder if updating `bundletool` will help. It was last updated in 989dc07b.
=> Bump to google/bundletool/main@f17ce94a

Directory.Build.props
Context: https://github.com/xamarin/xamarin-android/tree/release/8.0.1xx-preview6
We branched for .NET 8 preview 6 from dab495ff into `release/8.0.1xx-preview6`.
Update xamarin-android/main's version number to 34.0.0-preview.7 for .NET 8 preview 7.
=> $(AndroidPackVersionSuffix)=preview.7; net8 is 34.0.0-preview.7

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodsAssemblyRewriter.cs
Context: https://github.com/dotnet/maui/pull/15399#issuecomment-1609576331
During a PR updating AndroidX dependencies in .NET MAUI, we got the error:
Task GenerateJavaStubs
...
System.IO.IOException: The process cannot access the file 'D:\a\_work\1\s\src\Compatibility\ControlGallery\src\Android\obj\Release\net8.0-android\android\assets\Xamarin.AndroidX.CustomView.pdb' because it is being used by another process.
at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
at Xamarin.Android.Tasks.MarshalMethodsAssemblyRewriter.Rewrite(DirectoryAssemblyResolver resolver, List`1 targetAssemblyPaths, Boolean brokenExceptionTransitions)
at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res, Boolean useMarshalMethods)
at …
=> [Xamarin.Android.Build.Tasks] correct paths in MarshalMethodsAssemblyRewriter

build-tools/automation/azure-pipelines-nightly.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/CodeBehindTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EmbeddedDSOTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs, tests/MSBuildDeviceIntegration/Tests/LocalizationTests.cs, tests/MSBuildDeviceIntegration/Tests/TimeZoneInfoTests.cs
Updates the `TimeZoneInfo` and `Localization` test stages to use the
`dotnet-test-slicer` tool used by other MSBuild test runs.
These test jobs have a pretty high frequency of failing and timing out,
and a few changes have been made to try to reduce the points of failure.
SetUp and TearDown functions have been trimmed down and made standard
across the two fixtures.  OneTimeSetup will prepare the device and
install the project, and we will only attempt to attach log files during
TearDown.
The tests will launch the app activity directly with ADB, rather than
using `dotnet build -t:Run` for every iteration.  The tests will attempt
to reinstall the app if it is not present as a fallback.
=> [CI] Use dotnet-test-slicer in nightly tests

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/Linux.Debian.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/Linux.DebianCommon.cs
Current Debian/unstable (otherwise known as `sid`), codename `trixie`, made `libncurses5-dev` a 
transitional package and the package replacing it is `libncurses-dev`
=> [xaprepare] update Debian dependencies for current unstable (trixie)

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/xamarin/xamarin-android/issues/8095
Context: f99fc814b0dcc021a441e70bb5a487b2034f6760
Initialize `$(MonoAndroidAssetsDirIntermediate)` earlier in `Xamarin.Android.Common.targets`, so that the existing `$(_XARemapMembersFilePath)` property (f99fc814) is able to correctly use it.
=> [Xamarin.Android.Build.Tasks] Move MonoAndroidAssetsDirIntermediate

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs
The `InstallAndroidDependenciesTest` test has been failing:
_AndroidSdkDirectory not set to new SDK path /Users/runner/work/1/a/TestRelease/07-11_21.59.53/temp/InstallAndroidDependenciesTest/android-sdk, probably because Google's repository has a newer platform-tools package!  repository2-3.xml contains platform-tools <major>34</major>.<minor>0</minor>.<micro>4</micro>; expected 34.0.3!
Fix this by bumping the platform-tools version that we try to install during this test to 34.0.4.
=> [AndroidDependenciesTests] Use platform-tools 34.0.4

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs
Updates the InstallAndroidDependenciesTest test to run against the self hosted Xamarin manifest, as well as Googles v2 manifest.
For the default case, we shouldn't override any package versions.  The dependency versions we calculate should be present in, and installable from, our manifest.
For the Google manifest case, we should override the platform-tools version.  Their manifest only ever contains one platform-tools version, and it is updated somewhat regularly causing the test to fail every time it changes.
=> [AndroidDependenciesTests] Test both manifest types

build-tools/automation/guardian/PoliCheck.Exclusions.xml, src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android/IncludeAndroidResourcesFromAttribute.cs, src/Mono.Android/Java.Interop/JavaLibraryReferenceAttribute.cs, src/Mono.Android/Java.Interop/JavaTypeParametersAttribute.cs, src/Mono.Android/Mono.Android.csproj, src/Mono.Android/Properties/AssemblyInfo.cs.in, src/Mono.Android/PublicAPI/API-34/PublicAPI.Shipped.txt
Fixes #7421
Enable Microsoft's [PublicApiAnalyzers](https://github.com/dotnet/roslyn-analyzers/tree/main/src/PublicApiAnalyzers) for `Mono.Android.dll`.
We currently have `ApiCompat`, which ensures that we do not break backwards compatibility between Android API levels, but now that we are in the .NET `TargetFramework` world we also need to ensure we do not *add* any new API to a TF once it has shipped.  A `TargetFramework` is essentially a contract that we cannot change.  (Imagine if you had different minor versions of .NET on your local machine and CI machine, what works on one should work on the other.)
Running the `PublicApiAnalyzer` adds about 25 seconds to a local build.  One can use our existing `$(DisableApiCompatibilityCheck)` property we have to also disable them to facilitate …
=> [Mono.Android] Use PublicApiAnalyzers to ensure we do not break API.

build-tools/automation/yaml-templates/upload-results.yaml
Context: https://github.com/xamarin/xamarin-android/pull/8157/commits/f59a3c2e3c1dad24ac9f42696553ced23d992a96
By default, we only store the CI build logs of jobs that fail.  However there are times when we would like to see the build logs for successful jobs.
This adds the ability to specify that a CI run should publish *all* of its build logs.
When running a job from the UI, set the `XA.PublishAllLogs` variable to `true`:
Test CI run:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8067357&view=results
=> [ci] Add variable to request all build logs be published to build artifacts.

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/build-linux.yaml, build-tools/automation/yaml-templates/build-macos.yaml
Context: https://github.com/xamarin/yaml-templates/pull/263
Updates the main SBOM file we produce to include build component info
from both the macOS and Linux builds.  These two builds will now produce
build component SBOMs which are downloaded and referenced in our main
SBOM afer all building and signing is complete.
=> [ci] Include build components in SBOM

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.AvailableItems.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/8190
In a customer sample, they have an `.aar` file they need the Java code from, but do not want a C# binding for it:
<AndroidLibrary Update="FooNonBinding-release.aar" Bind="false" />
`Bind="false"` looks to have the side effect where:
1. It does not get copied to the output directory.
2. The Java types don't make it to the final app.
3. Crash at runtime:
```
java.lang.ClassNotFoundException: Didn't find class "com.example.foononbinding.FooSample" on path
```
A workaround is to add a line such as:
<None Include="FooNonBinding-release.aar" CopyToOutputDirectory="PreserveNewest" />
I could reproduce this issue by updating our existing `DotNetBuildLibrary` test. I could assert the file exists in the output directory, as well as …
=> [Xamarin.Android.Build.Tasks] fix `.aar` files flowing from project references

Documentation/guides/building-apps/build-items.md, Documentation/workflow/commit-messages.md
Applies the term replacements suggested by recently failing policheck source scans.
=> [Documentation] Appease PoliCheck Rule: 79604

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.AvailableItems.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Context: https://github.com/dotnet/maui/pull/16024#issuecomment-1640461682
.NET MAUI's build currently fails with:
Xamarin.Android.Aapt2.targets(123,3): error APT2144: invalid file path 'D:\a\_work\1\s\src\Core\src\obj\Debug\net8.0-android\lp\129.stamp'.
What is very wrong about this, it is trying to `aapt2 compile` a `*.stamp` file:
Executing compile -o /Users/builder/azdo/_work/1/s/src/Core/src/obj/Release/net8.0-android/lp/87/jl/res/../flat/ /Users/builder/azdo/_work/1/s/src/Core/src/obj/Release/net8.0-android/lp/87.stamp
Normally this runs against `*.flat` or `*.flata` files.
This problem was introduced in 26ffd5d7:
1. Library A uses an AndroidX package, the AndroidX `.aar` file is added to `@(AndroidAarLibrary)`. The NuGet package does this in a `.targets` file.
2. With the change in …
=> [Xamarin.Android.Build.Tasks] fix duplicate `.aar` files

Directory.Build.props
Context: https://github.com/xamarin/xamarin-android/tree/release/8.0.1xx-preview7
We branched for .NET 8 preview 7 from 7bf4eddb into `release/8.0.1xx-preview7`.
Update xamarin-android/main's version number to 34.0.0-rc.1 for .NET 8 RC 1.
=> $(AndroidPackVersionSuffix)=rc.1; net8 is 34.0.0-rc.1

build-tools/automation/azure-pipelines.yaml, build-tools/create-packs/vs-workload.in.props
Context: https://github.com/xamarin/yaml-templates/pull/274
Enables side by side workload manifest support when generating workload MSIs.
This should only be enabled for builds shipping with .NET 8 Preview 7 or later.
=> [vs-workload] Set EnableSideBySideManifests=true

build-tools/automation/azure-pipelines.yaml, build-tools/create-packs/Directory.Build.targets, build-tools/scripts/DotNet.targets
Adds a new MAUI test stage and job that will run against PR builds
targeting xamarin-android/main.
The new job will build dotnet/maui against the Android packs produced by
the PR build.  If that is successful, it will install the MAUI packs
into Androids dotnet preview sandbox, and create and build a template.
=> [ci] Add MAUI integration job

.external, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/8028
Fixes: https://github.com/xamarin/xamarin-android/issues/8175
Changes: https://github.com/mono/mono/compare/73df89a73d2aa08155fca01b75f2cc2944bbb7ea...d9a6e8710b37cd7f16cf52eff4f772556e57cc41
* mono/mono@d9a6e8710b3: [libs][TimeZoneInfo] Bound transition time conversion (mono/mono#21686)
* mono/mono@7e58b2a0c54: Install temurin-8-jdk instead of adoptopenjdk
* mono/mono@efee217811d: Update sdks-archive.groovy
* mono/mono@a9de9b041f6: [Mono.Security] Adjust test after EKU fix
* mono/mono@9784c2bc5e4: [libs] Update TimeZoneInfo to read new version of tzdata (mono/mono#21682)
* mono/mono@ba344d3416d: [Mono.Security] Add additional validation to AuthenticodeDeformatter
* mono/mono@f648ec1e0a6: Bump nuget.exe to v6.6.1
=> Bump to mono/mono/2020-02@d9a6e871

build-tools/automation/azure-pipelines-release-trigger.yaml
The "Xamarin.Android Release Definition Trigger" pipeline is used to
create PRs into VS for classic Xamarin.Android, and should not run
against branches that only produce .NET Android artifacts.
=> [ci] Remove .NET branches from classic release trigger

build-tools/automation/azure-pipelines.yaml
Notarization attempts have been failing on d17-5:
dotnet DDSignFiles.dll
You must install or update .NET to run this application.
App: DDSignFiles.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '3.1.0' (x64)
.NET location: /Users/runner/.dotnet/
Attempt to fix this by installing the .NET Core 3.1 runtime on our notarization agents.
=> [ci] Install .NET Core runtime 3.1 for notarization

build-tools/automation/azure-pipelines.yaml, build-tools/scripts/DotNet.targets
The new MAUI build and test job has been failing:
C:\a\_work\2\s\maui\src\DotNet\Dependencies\Workloads.csproj : error NU1102: Unable to find package Microsoft.NET.Sdk.Android.Manifest-8.0.100-preview.7 with version (= 34.0.0-ci.pr.gh8185.402) [C:\a\_work\2\s\maui\src\DotNet\DotNet.csproj]
This is because our main branch has bumped from .NET 8 preview.7 builds to .NET 8 rc.1 builds.  We can fix this by writing our SDK band to the Microsoft.NET.Sdk.Android.Manifest item in the workload restore project.
=> [ci] Fix MAUI integration test job

build-tools/installers/unix-binutils.projitems, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
Context: https://github.com/dotnet/maui/issues/14531
Changes: https://discourse.llvm.org/t/llvm-16-0-0-release/69326
Changes: https://discourse.llvm.org/t/llvm-16-0-1-release/69774
Changes: https://discourse.llvm.org/t/llvm-16-0-2-release/70107
Changes: https://discourse.llvm.org/t/16-0-3-release/70341
Changes: https://discourse.llvm.org/t/16-0-4-release/70692
Changes: https://discourse.llvm.org/t/16-0-5-release/71097
Changes: https://discourse.llvm.org/t/16-0-6-release/71344
This release drops use of the UPX executable compressor, since it appears to be crashing on some Windows machines.
=> Bump to LLVM toolchain based on version 16.0.6

build-tools/scripts/Packaging.mk
Recent `make create-installers` attempts have been failing, seemingly due to recent changes to dotnet host resolution:
Restored /Users/runner/work/1/s/xamarin-android/src/Microsoft.Android.Templates/Microsoft.Android.Templates.csproj (in 257 ms).
1>/Users/runner/work/1/s/xamarin-android/bin/Release/dotnet/sdk/8.0.100-rc.1.23373.1/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : You must install or update .NET to run this application. [/Users/runner/work/1/s/xamarin-android/src/Microsoft.Android.Templates/Microsoft.Android.Templates.csproj] [/Users/runner/work/1/s/xamarin-android/build-tools/create-packs/Microsoft.Android.Sdk.proj]
1>/Users/runner/work/1/s/xamarin-android/bin/Release/dotnet/sdk/8.0.100-rc.1.23373.1/Roslyn/Microsoft.CSharp.Core.targets(80,5): error : …
=> [build] Use .NET preview to create nupkgs

build-tools/automation/yaml-templates/install-apkdiff.yaml, build-tools/automation/yaml-templates/install-dotnet-test-slicer.yaml, build-tools/automation/yaml-templates/run-msbuild-tests.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml, build-tools/automation/yaml-templates/variables.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidSdkResolver.cs
Updates our macOS test jobs to run on the latest hosted macOS images.
The [Ventura images][0] do not contain classic Xamarin or Mono packages,
so these have been added to the test jobs that still require them.
[0]: https://github.com/actions/runner-images/blob/96f1383301c4d6866d3186b31c52c4d84e7b8812/images/macos/macos-13-Readme.md
=> [ci] Target hosted macOS-13 Ventura pool

build-tools/automation/azure-pipelines.yaml
This test job should only run if the initial build was successful.
=> [ci] Fix condition for MAUI integration test job

build-tools/automation/azure-pipelines.yaml
Disables all of the jobs that are unique to .NET Android NuGet package
creation, testing, and signing, as we we do not plan to release new
nuget packages from the `d17-5` branch.
This behavior is controlled by a new pipeline parameter named
`createSignNupkgs` which can be set to `true` if it's ever needed.
=> [ci] Disable .NET jobs by default on d17-5

src/Mono.Android/Android.Content.PM/PackageManager.cs, src/Mono.Android/Mono.Android.csproj
Fixes #7729 
We do not currently enumify `PackageManager.PackageInfoFlags.Of (long)` [(source)](https://developer.android.com/reference/android/content/pm/PackageManager.PackageInfoFlags) because it is a `long` and our tooling is built around enumifying `int` values.
However, it seems to be a relatively used API so we should try to make it nicer.
Create a new `PackageInfoFlagsLong` `long` enum that can be used as a parameter to a new `Of` overload.
=> [Mono.Android] Provide enum overload of `PackageManager.PackageInfoFlags.Of`.

src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs, src/Mono.Android/Android.Runtime/JNINativeWrapper.g.tt
I noticed some methods appear when creating a new `.aotprofile` for .NET MAUI:
void System.Reflection.Emit.RuntimeILGenerator:.ctor (System.Reflection.Module,System.Reflection.Emit.ITokenGenerator,int)
void System.Reflection.Emit.RuntimeILGenerator:BeginCatchBlock (System.Type)
void System.Reflection.Emit.RuntimeILGenerator:Emit (System.Reflection.Emit.OpCode,int)
void System.Reflection.Emit.RuntimeILGenerator:Emit (System.Reflection.Emit.OpCode,System.Reflection.Emit.Label)
void System.Reflection.Emit.RuntimeILGenerator:Emit (System.Reflection.Emit.OpCode,System.Reflection.Emit.LocalBuilder)
void System.Reflection.Emit.RuntimeILGenerator:Emit (System.Reflection.Emit.OpCode,System.Reflection.MethodInfo)
void System.Reflection.Emit.RuntimeILGenerator:Emit (System.Reflection.Emit.OpCode)
We …
=> [Mono.Android] add "built-in" delegate for _JniMarshal_PPII_L

build-tools/automation/yaml-templates/commercial-build.yaml
Today, our CI checks out the private `monodroid` repository in order to build its proprietary code.  Checking this repository out recursively with its submodules can take quite a lot of time.  A large portion of this time is checking out a `xamarin-android` submodule.  However, we do not use this submodule, in fact we immediately delete it to ensure that it does not get used.
Ideally we would not spend the time checking out this submodule just to delete it, however this is trickier than one might expect.
The solution that seems to work is:
- Check out `monodroid` without any submodules
- Use `git config submodule."external/xamarin-android".update none` to tell `git` to ignore the submodule
- Check out `monodroid` with recursive submodules, but `git` will skip XA
This saves about 2-3 …
=> [ci] Don't checkout monodroid's unneeded XA submodule

build-tools/api-merge/merge-configuration.xml, build-tools/create-android-api/create-android-api.csproj
In Classic, we needed to build a `Mono.Android.dll` for every Android API level we supported.  In .NET we only build the latest API level(s).  Thus we do not need to output an `api.xml` for API levels we aren't building.
Save a few build seconds and several hundred megabytes of disk space by not writing unneeded `api.xml` files.
=> [api-merge] We only need to write API-34 api.xml.

build-tools/automation/yaml-templates/run-sliced-nunit-tests.yaml
Changes to the `dotnet-test-slicer` task from commit a4276880 may have
caused it to fail silently if any issues occur.  Updating the task to
fail if anything is written to stderr should fix this.
=> [ci] Report when dotnet-test-slicer fails

build-tools/automation/yaml-templates/stage-msbuild-tests.yaml
Recent MSBuild test updates and removals seem to have sped up the tests
enough that we can split them across fewer agents.
=> [ci] Use fewer agents for macOS MSBuild tests

src/Mono.Android/Android.Content/ContentValues.cs, src/Mono.Android/Android.Content/Context.cs, src/Mono.Android/Android.Media/AudioTrack.cs, src/Mono.Android/Android.OS/AsyncTask.cs, src/Mono.Android/Android.OS/Handler.cs, src/Mono.Android/Android.OS/Vibrator.cs, src/Mono.Android/Android.Runtime/AndroidEnvironment.cs, src/Mono.Android/Android.Runtime/JavaObject.cs, src/Mono.Android/Android.Telecom/InCallService.cs, src/Mono.Android/Android.Telephony/CellInfo.cs, src/Mono.Android/Android.Views/View.cs, src/Mono.Android/Java.Interop/JavaConvert.cs, src/Mono.Android/Java.Interop/TypeManager.cs, src/Mono.Android/Java.Lang/Object.cs, src/Mono.Android/Mono.Android.csproj
Fixes #7590
Fix the remaining `[SupportedOSPlatform]` warnings in manually bound code.  Other issues we were previously seeing appear to have been a bug in earlier .NET 8 previews.
Of particular note, the constructors for `Java.Lang.Boolean`, `Java.Lang.Integer`, etc. have been marked as `Deprecated` in API-33. ([source](https://developer.android.com/reference/java/lang/Integer?hl=en#Integer(int))).
This PR replaces them with the suggested `valueOf` methods.
@jonpryor Please verify this change is acceptable for our use case.
=> [Mono.Android.dll] Fix [SupportedOSPlatform] warnings.

Documentation/building/windows/instructions.md, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/build-windows.yaml, build-tools/scripts/PrepareWindows.targets, build.cmd, dotnet-local.cmd, dotnet-local.sh, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
The recent bump to dotnet broke the dotnet-local scripts. It now seems that the "local" path must be FIRST in the PATH in order to pick up the packs.
Also added a smoke test step to make sure the script works, at least one Mac and Linux.
=> Fix dotnet-local script to work.

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, tests/Mono.Android-Tests/Mono.Android-Test.Shared.projitems, tests/Mono.Android-Tests/System.Text.Json/JsonSerializerTest.cs
Fixes: https://github.com/dotnet/maui/issues/16038
Changes to trimmer defaults in .NET 8 require a new `$(JsonSerializerIsReflectionEnabledByDefault)` MSBuild property to be set by default for project types that use `$(TrimMode)=partial` like when running on mobile (iOS/Android).
I added a very basic System.Text.Json test, which fails with the exception:
System.InvalidOperationException : JsonSerializerIsReflectionDisabled
at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions , Type )
at System.Text.Json.JsonSerializer.Deserialize(String , Type , JsonSerializerOptions )
at System.Text.JsonTests.JsonSerializerTest.Deserialize()
at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, …
=> [Xamarin.Android.Build.Tasks] fix System.Text.Json with default trimmer settings

Configuration.props
Running the `-t:Install` target with a local xamarin-android build on Windows, I got the error:
AndroidAdb
Errors
Xamarin.Android.Common.targets(2641,3): error MSB6004:
The specified task executable location "D:\android-toolchain\sdk\platform-tools\adb" is invalid.
This appears to only happen with a local of xamarin/xamarin-android because it specifies `AdbToolExe=adb` in `Configuration.props`.
It appears that most of our tasks just use the pattern:
protected override string GenerateFullPathToTool ()
{
return Path.Combine (ToolPath, ToolExe);
}
Where if `ToolExe` was completely blank, it would fall back to the value:
protected override string ToolName => OS.IsWindows ? "adb.exe" : "adb";
Searching the web:
https://grep.app/search?current=2&q=ToolExe&words=true&filter[lang][0]=C%23&filter[l …
=> [build] set file extension for common `ToolExe` values

Directory.Build.props
Context: https://github.com/xamarin/xamarin-android/tree/release/8.0.1xx-rc1
We branched for .NET 8 RC 1 from 3cca3d9d into `release/8.0.1xx-rc1`.
Update xamarin-android/main's version number to 34.0.0-rc.2 for .NET 8 RC 2.
=> $(AndroidPackVersionSuffix)=rc.2; net8 is 34.0.0-rc.2

build-tools/manifest-attribute-codegen/manifest-definition.xml, src/Mono.Android/Android.App/IntentFilterAttribute.cs, src/Xamarin.Android.Build.Tasks/Mono.Android/IntentFilterAttribute.Partial.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BuildHelper.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Fixes: #8235
Adds the following properties to `[IntentFilter]` to allow the specified `AndroidManifest.xml` attributes to be generated:
- `DataPathSuffix` -> `pathSuffix`
- `DataPathSuffixes` -> `pathSuffix`
- `DataPathAdvancedPattern` -> `pathAdvancedPattern`
- `DataPathAdvancedPatterns` -> `pathAdvancedPattern`
Note that while we have a script to detect new elements added to `AndroidManifest.xml`, the code must be written manually.  Filed #8272 because we really should automate this code generation.
=> [Mono.Android] Add `pathSuffix` and `pathAdvancedPattern` to `[IntentFilter]`

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/dotnet/arcade/commit/b6e1c2fd5fdada05c64e7f17e2a97fae240f9043
Updates the arcade version to bring in a fix for workload MSI generation
when side by side manifest support is enabled.  This should allow us to
avoid an issue that would occur when trying to insert a new workload
manifest with the same SDK band as the one already in VS.
=> [build] Bump arcade for latest SxS manifest fixes

eng/Version.Details.xml, eng/Versions.props
Changes: https://github.com/dotnet/runtime/compare/e897946596...034d27f4a9
Because the .NET SDK has switched over to internal code flow, we have to subscribe to runtime directly
This initial bump I did manually by removing `CoherentParentDependency`, then I ran the command:
> darc update-dependencies --id 189081
Looking up build with BAR id 189081
Updating 'Microsoft.NETCore.App.Ref': '8.0.0-rc.1.23414.4' => '8.0.0-rc.1.23419.3' (from build '20230819.3' of 'https://github.com/dotnet/runtime')
Using 'Strict' coherency mode. If this fails, a second attempt utilizing 'Legacy' Coherency mode will be made.
Updating 'Microsoft.NET.Workload.Emscripten.Current.Manifest-8.0.100.Transport': '8.0.0-rc.1.23411.2' => '8.0.0-rc.1.23415.5' to ensure coherency with …
=> Bump to dotnet/runtime/release/8.0-rc1@034d27f 8.0.0-rc.1.23419.3

build-tools/scripts/DotNet.targets
The MAUI integration test job has been failing with:
EXEC(0,0): Error : NU3004: The package is not signed.
Our upstream dependencies will not always be signed, and the packages
we are building for testing purposes are not signed.  We can avoid this
error by adding `--skip-sign-check` to the workload install command.
=> [tests] Skip sign check when installing MAUI

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs
We see users reporting the following error on Windows machines.
```
APT2000 The system cannot find the file specified. (2): foo.xml
```
This is odd because what it SHOULD be reporting is an APT2264 error. This provides additional feedback to check for Long File Paths. As a result users do not get the additional info.
It turns out we were trying to match
`The system cannot find the file specified. (2).`
with `The system cannot find the file specified. (2):`. On Windows the error message contains a `:` rather than `.` this stops the code matching and results in the APT2000 error. Lets fix that.
=> [Xamarin.Android.Build.Tasks] Fix APT2264 error on Windows.

src/monodroid/monodroid.targets
Commit 6ba9992 was incomplete, and broke both the nightly build and
clean target.  Fix this by removing or replacing the instances of
`%(AndroidSupportedTargetJitAbi.Identity)` that were missed.
=> [monodroid] Fix the EnableNativeAnalyzers build

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/Eol.targets
Context: https://github.com/xamarin/xamarin-android/pull/8047#issuecomment-1692910565
The current error message:
Microsoft.NET.EolTargetFrameworks.targets(35,5): error NETSDK1202:
The workload 'android' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/maui-support-policy for more information about the support policy.
Doesn't say the problem is .NET 6, it sounds like all versions of the `android` workload are out of support.
To align with the xamarin-macios team, let's change it to be:
The workload 'net6.0-android' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/maui-support-policy for more information about the support policy.
=> [Xamarin.Android.Build.Tasks] improve net6.0 "out of support" message

build-tools/xaprepare/xaprepare/Application/Utilities.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs
CI builds have been failing frequently and quietly:
Downloading dotnet-install...
Error: Installation of dotnet SDK 8.0.100-rc.2.23422.31 failed.
Step Xamarin.Android.Prepare.Step_InstallDotNetPreview failed
System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_InstallDotNetPreview failed
We were returning early when attempts to calculate the size of the
`dotnet-install` script failed, and a cached install script file was not
already on disk.  This has been fixed by ensuring that we still attempt
to download the script if the size calculation fails.
The size check failure has also been fixed by using a get request, and
logging around this prepare step has been improved.
=> [xaprepare] Fix dotnet-install script size check

build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs
Context: https://github.com/xamarin/xamarin-android/pull/8311#discussion_r1310636246
Improves the logging around attempts to download or calculate the size
of the dotnet-install script.  Messages about cached install script use
will be more explicit, and readability of failure cases should also be
improved.
=> [xaprepare] Improve dotnet-install script logging

build-tools/automation/yaml-templates/commercial-build.yaml
This is a backport of #8231, to see if we can fix CI on `d17-5` branch.
I might end up bringing over other changes.
=> [d17-5] [ci] Don't checkout monodroid's unneeded XA submodule

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
Context: https://github.com/xamarin/xamarin-android/pull/8309
Context: https://learn.microsoft.com/java/openjdk/download#openjdk-17
Classic Xamarin.Android apps appear to work with JDK-17, just by doing:
msbuild -r -bl -t:SignAndroidPackage -p:JavaSdkDirectory="C:\Program Files\Microsoft\jdk-17.0.8.101-hotspot" -p:LatestSupportedJavaVersion=17.99
I see log messages calling a JDK 17 `javac` like:
_CompileJava:
C:\Program Files\Microsoft\jdk-17.0.8.101-hotspot\bin\javac.exe -J-Dfile.encoding=UTF8 "@C:\Users\jopepper\AppData\Local\Temp\tmp119C.tmp" -target 1.8 -source 1.8
Update `$(LatestSupportedJavaVersion)` to allow usage of JDK 17.
=> [d17-5] [Xamarin.Android.Build.Tasks] allow JDK 17 usage

build-tools/automation/azure-pipelines-apidocs.yaml, build-tools/automation/yaml-templates/commercial-build.yaml, build-tools/gradle/gradle/wrapper/gradle-wrapper.properties, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallAdoptOpenJDK.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in, src/manifestmerger/build.gradle, src/r8/build.gradle
Context: https://github.com/xamarin/xamarin-android/issues/8304
Context: https://github.com/xamarin/xamarin-android/pull/8029
Context: https://web.archive.org/web/20230507035529/https://developer.android.com/studio/releases/#jdk-17
> Starting from Android Studio Flamingo Canary 3, the Studio IDE is
> bundled with JDK 17.
Context: https://github.com/xamarin/java.interop/pull/1141
> Does It Build™?
Because of xamarin/xamarin-android#8029 we know we *can* use JDK 17.
Because of xamarin/xamarin-android#8304 we know we *should* use JDK 17.
Update `xaprepare` so that Microsoft OpenJDK 17.0.8 is provisioned for the build.  Note: `$(_JavacSourceVersion)` and `$(_JavacTargetVersion)` are *not* changed, so that our built `.jar` tooling can still *run* on JDK-11.
Update to use Gradle 8.1.1.  This is …
=> [build] Use Microsoft OpenJDK 17.0.8

Documentation/guides/messages/README.md, Documentation/guides/messages/apt2264.md, Documentation/guides/messages/apt2265.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
Context https://i.azdo.io/1714603
Context https://issuetracker.google.com/issues/188679588
There is a known issue with `aapt2`, `AndroidAsset` and non-ASCII paths/project names. 
`aapt2` has a bug where it cannot correctly traverse a directory which contains non-ASCII 
characters. We curently have no way to work around this issue. 
So the PR adds some more detail to the specific error message which `aapt2` raises in 
these cases. It suggests the user check their paths to make sure it does not contain 
non-ASCII characters. 
We also add some unit tests to cover this senario.
=> MAUI project with non-ASCII project name cannot release to my Android phone

build-tools/automation/azure-pipelines.yaml
Updates the Linux test job to include everything relevant from
BuildTest, PackagingTest, XASdkTests, and AndroidDependenciesTests.
=> [ci] Run more MSBuild tests on Linux

build-tools/automation/yaml-templates/build-macos.yaml, build-tools/automation/yaml-templates/commercial-build.yaml
A few of the projects in our submodules are configured to sign output
files after build:
https://github.com/xamarin/xamarin-android-tools/blob/fa3711b7ddac7cea6850a9c1c67beda1996aafc0/src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj#L36
https://github.com/xamarin/androidtools/blob/720fd4e7cc2f018c681843210edfc796c97c1dde/Xamarin.AndroidTools/Xamarin.AndroidTools.csproj#L21
We should skip these sign requests during our build as we perform post
build signing for all of our shipping artifacts.
=> [ci] Install signing plugin after building

Configuration.props
Changes: https://github.com/xamarin/xamarin-android/compare/a7e0eff1...6678e021
These changes are going out in a future servicing release.
=> Bump to 33.0.95 `$(AndroidNet7Version)`

build-tools/installers/unix-binutils.projitems, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
Changes: https://releases.llvm.org/17.0.1/docs/ReleaseNotes.html
Changes: https://releases.llvm.org/17.0.1/tools/lld/docs/ReleaseNotes.html
Changes: https://github.com/xamarin/xamarin-android-binutils/commit/83a894fcd5d57e6c53ca3b06c950cde34574b9b7
LLVM 17.0.1 has just been released.  For full set of changes in this release 
please see the links above.  This is the same version of LLVM that is used in 
just-released Android NDK r26.
The changes that are relevant to Xamarin.Android are:
* Typed pointers are no longer supported and the -opaque-pointers
option has been removed. See the opaque pointers documentation for
migration instructions.
* The `nofpclass` attribute was introduced. This allows more
optimizations around special floating point value comparisons.
Additionally, Vlad Braeze …
=> Bump our binary utilities toolchain to LLVM 17.0.1

.external, build-tools/scripts/DotNet.targets
Includes changes for https://github.com/xamarin/monodroid/compare/057b17fe491f51823eb814f0163bb92686e24991...8908d6a1c4fdfa8d3cc391d1d78f23f88a8ce6fb
=> Bump to Include Debugging.Tasks Versioning

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Fixes #8191
The implementation of `AndroidJavaSource` was missing one component. It was missing references to the `classes.jar` files which are extracted to the `$(IntemediateOutputPath)lp` directory. As a result we end up with 
errors such as the following
```
Error	JAVAC0000	 error: package androidx.appcompat.widget does not exist
```
What was missing was a dependency on the `_GetLibraryImports` target. This target will call the chain of 
targets which extracts the dependent `classes.jar` files and populates the `@(Jars)` ItemGroup which is used in the `_CompileBindingJava` target. This should allow users to write simple wrapper methods in Java that wrap more 
complex API.
=> [Xamarin.Android.Build.Tasks] Unable to use import androidx.appcompat.widget.Toolbar into a java file when using AndroidJavaSource

Documentation/guides/building-apps/build-targets.md, Documentation/workflow/DevelopmentTips.md, build-tools/scripts/TestApks.targets, build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/Sleep.cs, build-tools/xa-prep-tasks/xa-prep-tasks.csproj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Application.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
We are frequently faced with the need to look at some detailed
information optionally logged by our runtime (as well as by the MonoVM
runtime in dotnet) and in order to obtain the necessary data, we ask our
users to perform a series of steps on command line.
This is a task we can easily wrap in a nice target, so that instead of
having to type 5 lines of commands the user invokes a single command
which will do the rest for them:
dotnet build -t:RunWithLogging
The above command will set the `debug.mono.log` property to the desired
value, increase logcat buffer, clear the buffer, start the application
waiting for it to be fully started, then pause for 1s and dump the
logcat buffer to a file.
Optionally, the `$(_RunLogVerbose)` property can be set to `true` in
order to log verbose MonoVM data …
=> Add a target to run application with logging

.external, build-tools/installers/create-installers.targets
Related https://github.com/xamarin/monodroid/commit/a2dbe752e40f25b39e22f0fac6b21f7980d73c1d.
Currently we control which files are included from the monodroid Fast Deployment in this repo. 
This can cause problems when we want to add new files (or remove them). Since we would need
to bump each repo multiple times to get everything to work. 
This PR moves that control over to monodroid, so new files can be included in one commit and then
one bump.
=> [installers] Let monodroid control which fast dev files are included in the installer

Directory.Build.props
Context: https://github.com/xamarin/xamarin-android/tree/release/8.0.1xx
We branched for .NET 8 from 791fedb5 into release/8.0.1xx; the main branch is now .NET 9.
Update xamarin-android/main's version number to 34.99.0-preview.1.
=> $(AndroidPackVersionSuffix)=preview.1; net9 is 34.99.0.preview.1

Directory.Build.props, build-tools/create-packs/Directory.Build.targets, build-tools/scripts/XAVersionInfo.targets
Context: https://github.com/xamarin/xamarin-android/commit/e6002f84602ade59eccf95974ca6188875d3a79f
The `release/8.0.1xx` versioning will be stable with .NET 8 GA.
We will start out with 34.0.1, and each commit increments by 1.
We have to reset `$(AndroidPackVersion)` so it will "reset" the commit distance.
=> [release/8.0.1xx] stable 34.0.x branding

build-tools/automation/yaml-templates/install-microbuild-tooling.yaml
Authenticode signing attempts started failing recently with:
ERROR: 'xsign' is misspelled or not recognized by the system.
Updating to Python 3 is the suggested fix for this issue.
=> [ci] Use Python 3 for signing tasks

eng/Version.Details.xml, eng/Versions.props
Changes: https://github.com/dotnet/runtime/compare/287c10d2...974edf97
This is an initial manual bump that removes:
CoherentParentDependency="Microsoft.Dotnet.Sdk.Internal"
Because "code flow" is now being done through internal forks -- we have to bump dotnet/runtime independently via:
> darc update-dependencies --id 193990
Looking up build with BAR id 193990
Updating 'Microsoft.NETCore.App.Ref': '8.0.0-rc.2.23466.4' => '8.0.0-rc.2.23472.10' (from build '20230922.10' of 'https://github.com/dotnet/runtime')
Using 'Strict' coherency mode. If this fails, a second attempt utilizing 'Legacy' Coherency mode will be made.
Updating 'Microsoft.NET.Workload.Emscripten.Current.Manifest-8.0.100.Transport': '8.0.0-rc.2.23463.1' => '8.0.0-rc.2.23471.3' to ensure …
=> Bump to dotnet/runtime/release/8.0@974edf97 8.0.0-rc.2.23472.10

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
Context: https://github.com/xamarin/xamarin-android/pull/8360
MSBuild tests that use `net7.0-android` `TargetFrameworks` can fail on release branches with:
error NU1102: Unable to find package Microsoft.AspNetCore.App.Ref with version (= 7.0.12)
error NU1102:   - Found 1621 version(s) in dotnet7 [ Nearest version: 7.0.0-rtm.22513.3 ]
error NU1102:   - Found 1537 version(s) in dotnet8 [ Nearest version: 8.0.0-alpha.1.22416.11 ]
error NU1102:   - Found 87 version(s) in testsource1 [ Nearest version: 8.0.0-preview.1.23112.2 ]
error NU1102:   - Found 87 version(s) in dotnet-public [ Nearest version: 8.0.0-preview.1.23112.2 ]
error NU1102:   - Found 0 version(s) in darc-pub-dotnet-emsdk-9506882
error NU1102:   - Found 0 version(s) in darc-pub-dotnet-runtime-26e0f82
error …
=> [tests] set `$(DisableTransitiveFrameworkReferenceDownloads)`

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets
Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1837913
Testing on a DevBox with only the .NET 8 RC 1 SDK and `dotnet workload install maui`:
> dotnet new android
> dotnet build -t:InstallAndroidDependencies -p:AndroidSdkDirectory=C:\tools\android-sdk -p:JavaSdkDirectory=C:\tools\jdk -bl
Microsoft.Android.Sdk.Windows\34.0.0-rc.1.432\tools\Xamarin.Android.Common.Debugging.targets(110,2):
error XA5300:  The Android SDK directory could not be found. Check that the Android SDK Manager in Visual Studio shows a valid installation. To use a custom SDK path for a command line build, set the 'AndroidSdkDirectory' MSBuild property to the custom path.
Ok, that's completely broken... So let's try `-c Release`, as this target is related to Fast Deployment: …
=> [Xamarin.Android.Build.Tasks] fix `InstallAndroidDependencies` in .NET 8

build-tools/automation/yaml-templates/setup-ubuntu.yaml
Package update attempts started failing recently on our Linux lane:
Setting up grub-efi-amd64-signed (1.187.6~20.04.1+2.06-2ubuntu14.4) ...
mount: /var/lib/grub/esp: special device /dev/disk/by-id/scsi-14d5346542020202075f68e4df928b946a6a92fab5bc044c1-part15 does not exist.
dpkg: error processing package grub-efi-amd64-signed (--configure):
installed grub-efi-amd64-signed package post-installation script subprocess returned error exit status 32
Our base Linux OS image is updated regularly by 1ES, so we shouldn't
need to update during every CI run.
=> [ci] Skip Linux apt upgrade step

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, src/Mono.Android/Mono.Android.targets
Updates xaprepare to install the `sources-34_r01` Android SDK package,
allowing our API docs generation tasks to use the latest sources.
=> [Mono.Android] Generate API docs for android-34

Documentation/guides/building-apps/build-properties.md, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildWithLibraryTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context https://github.com/xamarin/xamarin-android/issues/8387
The value for `AndroidManifestMerger` should be updated to be `manifestmerger.jar`. This allows users to make use of the new features like `AndroidManifestOverlay` out of the box.
The old system is still available, the users will need to add the following to their csproj.
```
<AndroidManifestMerger>legacy</AndroidManifestMerger>
```
=> [Xamarin.Android.Build.Tasks] Make manifestmerger.jar the default.

Documentation/guides/building-apps/build-properties.md, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Tasks/Generator.cs
Context: https://github.com/xamarin/java.interop/pull/1143
Context: https://github.com/xamarin/java.interop/pull/1130
In https://github.com/xamarin/java.interop/pull/1143, we added the ability to globally opt-out of the new `generator` [feature](https://github.com/xamarin/java.interop/pull/1130) that automatically applies `[Obsolete]` attributes to methods that override `[Obsolete]` methods.  (Preventing a C# compiler warning.)
This adds support for a new `$(AndroidEnableObsoleteOverrideInheritance)` boolean MSBuild property for users to opt-out.  The default is `true`.
=> [Xamarin.Android.Build.Tasks] Add support for $(AndroidEnableObsoleteOverrideInheritance).

eng/Version.Details.xml, eng/Versions.props
Changes: https://github.com/dotnet/runtime/compare/a84f8ffb...b17a34c8
This a manual bump, Maestro can update for us after this is merged.
* Removed `CoherentParentDependency="Microsoft.Dotnet.Sdk.Internal"`
* `darc update-dependencies --id 195870`
Using the build number from:
* https://maestro-prod.westus2.cloudapp.azure.com/3073/https:%2F%2Fgithub.com%2Fdotnet%2Fruntime/latest/graph
=> Bump to dotnet/runtime/release/8.0@b17a34c8 8.0.0-rtm.23506.12

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
Changes: https://github.com/xamarin/java.interop/compare/8e63cc8d...ed63d890
* [generator] restore `[RegisterAttribute]` for *Implementor types
=> Bump to xamarin/java.interop/main@ed63d890

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixLegacyResourceDesignerStep.cs
We have a very odd situation regarding the NuGet `Xamarin.CommunityToolkit.MauiCompat`. 
The NuGet package ships with a file `.net/__res_name_case_map.txt` in the 
`Xamarin.CommunityToolkit.MauiCompat.aar` which contains the 
case map changes for the `AndroidResource` items. The purpose of this file is to allow
the user to use Camel case (or any case) names in C# code, while the android resource
compilation is left as all lowercase. This is because android requires lowercase resource 
items. 
The contents of this file are as follows
```
Resources/Layout/CameraFragment.axml;layout/camerafragment.xml
```
As you can see from this `camerafragment` is remaped to `CameraFragment`. With this 
change we would expect to see code in C# which uses `CameraFragment`. This is true
as per …
=> [Xamarin.Android.Build.Tasks] Try a case insensitive lookup as a backup for Legacy Designer fixup

src/monodroid/jni/android-system.cc, src/monodroid/jni/basic-android-system.cc, src/monodroid/jni/monodroid-glue.cc, src/monodroid/jni/util.cc
We log a number of messages during startup, whether or not logging is
enabled.  However, logcat messages take non-trivial (and not entirely
predictable) amount of time to process, so we should limit their number
by default in order to speed up startup.
Tests show the following improvements resulting from this change:
* Displayed: 6.28% faster
* Native-to-managed transition: 6.11% faster
* Total native init time: 13.95% faster
=> Hush some messages logged by default on startup

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocumentElement.cs
Fixes #8409
There were a number of missing `ForegroundService` types missing in the last few releases. As a result users were not able to make use of them via the `Service` attribute. If they tried it would result in an empty `foregroundService` attribute.
```
<service android:foregroundServiceType="" android:name="crc64cd18cf298594e84d.MyService " />
```
Lets fill in the missing types. We should address this in the future by using some form of code generation as outlined in #8272
=> Fix up ForegroundService.ToString()

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/AddKeepAlivesStep.cs
- The `method.Parameters.Count == 0` check should be faster than LINQ's `Any` call (`CustomAttributes.Any`). So moved it first.
- Moved some variables near their usage, particularly, `GetILProcessor` which may allocate unnecessarily if `GC.KeepAlive(...)` call was already found. It's not a big of problem though as it's not very common.
=> [Refactor] Small refactoring to `AddKeepAlives` method

build-tools/automation/azure-pipelines-apidocs.yaml, src/Mono.Android/Mono.Android.csproj
Updates `$(AndroidJavadocVerbosity)` to `full` to generate additional
API docs content.  A `javadocVerbosity` parameter has been added to the
API docs build pipeline to make it easier to toggle this setting when
queueing a docs build.
The docs build pipeline has been updated to upload the output of the
`Mono.Android` build to make it easier to download and push docs updates
to the [apidrop/binaries][0] repository.
[0]: https://apidrop.visualstudio.com/binaries/_git/binaries#
=> [Mono.Android] Generate API docs with "full" verbosity

Documentation/guides/tracing.md
Context: https://github.com/dotnet/diagnostics/pull/4081
Context: https://github.com/dotnet/diagnostics/pull/4090
Context: https://github.com/dotnet/runtime/pull/88634
Context: https://github.com/dotnet/diagnostics/issues/4337
Using the latest `dotnet-trace` tooling:
> dotnet tool list -g
Package Id                         Version                       Commands
--------------------------------------------------------------------------------------
dotnet-dsrouter                    7.0.447801                    dotnet-dsrouter
dotnet-gcdump                      7.0.447801                    dotnet-gcdump
dotnet-trace                       7.0.447801                    dotnet-trace
There is a simplified way to profile Android apps.
For an Android emulator:
> dotnet-dsrouter android-emu …
=> [docs] .NET 8 simplified `dotnet-trace` instructions

.external
Changes https://github.com/xamarin/monodroid/compare/e57630bd3...47bdaaa9b
https://github.com/xamarin/monodroid/commit/47bdaaa9b Bump to xamarin/androidtools/main@a9168743 (#1379)
https://github.com/xamarin/monodroid/commit/2f07bd4a7 Bump external/android-sdk-installer from `6f38560` to `3880589` (#1378)
https://github.com/xamarin/monodroid/commit/af9de6a1b Bump external/xamarin-android from `c6d5025` to `2b0761b` (#1377)
https://github.com/xamarin/monodroid/commit/05a18eedb [tools/msbuild] Dont raise XA0138 Warning if fast deployment hangs. (#1375)
https://github.com/xamarin/monodroid/commit/8dee1d4c8 Bump external/xamarin-android from `41aaf38` to `c6d5025` (#1374)
https://github.com/xamarin/monodroid/commit/fbb362b85 Bump external/xamarin-android from `547a157` to `41aaf38` (#1372) …
=> Bump monodroid to 2f07bd4a71f2d59d0d86caefedf61b9fd0795699

Documentation/guides/messages/xa1031.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Tasks/CheckClientHandlerType.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/EnvironmentContentTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/CheckClientHandlerTypeTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/xamarin-android/commit/d3e87674187fca4ce136f5c4b460c488044e1bec
Context: https://github.com/xamarin/xamarin-android/commit/311b41e864a0162895d079477cb9398fbec5ca6e
Updates the `CheckClientHandlerType` task to throw an XA1031 error when
`$(AndroidHttpClientHandlerType)` is set to a value that inherits from
`System.Net.Http.HttpClientHandler`.
=> [Build Tasks] Update CheckClientHandlerType errors

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/AddKeepAlivesStep.cs
Adding all types to a list first, then processing that list is not necessary and has unnecessary overhead. The code is now modified to process types directly
=> [Performance] Simplify `AddKeepAlivesStep` to not add all assembly types in a list

build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/DebuggingTasksTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/TestEnvironment.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
The `TestResolveToolsExists` test currently requires a Xamarin.Android
installation on disk to pass.  The test has been fixed by passing the
.NET reference assembly paths to the `ResolveXamarinAndroidTools` task.
The build has also been updated to allow this test to pass against a
local build tree, as it requires product `Version` files in the SDK
output directory.
=> [Tests] Fix TestResolveToolsExists on .NET

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
Changes: https://github.com/android/ndk/wiki/Changelog-r26#r26b
NDK r26 failed to update LLVM to v17.0.1 and instead shipped with 
an earlier beta build of the v17 toolchain.  r26b fixes this mistake 
and updates LLVM to:
* 17.0.2 (based on r487747d)
* https://github.com/llvm/llvm-project/commits/c4c5e79dd4b4c78eee7cffd9b0d7394b5bedcf12
=> Bump NDK to r26b

src/Mono.Android/Mono.Android.targets
The `mdoc export-msxdoc` command that runs at the end of the API docs
build shouldn't overwrite the `Mono.Android.xml` file produced by the
build.
=> [docs] Don't overwrite xml produced by docs build

build-tools/create-packs/License.targets, build-tools/create-packs/Microsoft.Android.Sdk.proj, build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_ThirdPartyNotices.cs, build-tools/xaprepare/xaprepare/Steps/Step_CopyExtraResultFilesForCI.cs, build-tools/xaprepare/xaprepare/Steps/Step_ThirdPartyNotices.cs
Adds the `THIRD-PARTY-NOTICES.TXT` file to all packs that contain a
license file.
=> [build] Include ThirdPartyNotices in workload packs

Configuration.props, build-tools/xaprepare/xaprepare/Application/KnownProperties.cs, build-tools/xaprepare/xaprepare/Application/Properties.Defaults.cs.in, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, build-tools/xaprepare/xaprepare/Steps/Step_Get_Android_BuildTools.cs, build-tools/xaprepare/xaprepare/xaprepare.targets
Context: https://github.com/xamarin/xamarin-android/commit/6eb11f159c692563200ffb88cddc7b69f761cace
We do not need to provision build-tools version 30.0.3 as `dx` is no
longer supported.
=> [build] Do not install build-tools 30.0.3

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
We had a worry that the `_Microsoft.Android.Resource.Designer.dll` was being auto included in NuGet packages. So lets add a test to make sure it is not.
Spoiler... turns out it wasn't :D
=> Add Unit test to make sure Designer Assembly is not packaged.

.external, build-tools/create-packs/Microsoft.Android.Sdk.proj, build-tools/create-packs/SignList.xml, build-tools/installers/create-installers.targets, build-tools/installers/sign-content.proj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
We had already excluded most of the classic-specific and mono bundle components from our .NET NUPKGs, but we were still restributing a few files that should no longer be needed:
* ICSharpCode.SharpZipLib.dll - dependency of Xamarin.Installer.Build.Tasks, moved to monodroid
* Mono.Profiler.Log.dll - dependency of aprofutil.exe
* Mono.CompilerServices.SymbolWriter.dll - dependency of pdb2mdb.exe
* monodoc.dll - dependency of mdoc.exe
=> [build] Remove classic components from NUPKGs

build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml
Our MSBuild Emulator Tests are bumping up against the 90 minute timeout specified by CI, causing legitimate runs to fail.  Bump the timeout to 180 minutes like most of our other CI stages.
=> [ci] Increase MSBuild Emulator Tests timeout.

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/build-linux.yaml, build-tools/automation/yaml-templates/commercial-build.yaml
The Xamarin.Android-PR pipeline has been updated to restrict builds from 
forks, which surfaced a few issues that were missed in commit b1bb67b3.
The Linux build and the repo used to preserve multi-repo checkout
behavior have been updated to fix these issues.
=> [ci] Fix builds from forks

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
Context: https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android/9.5.2-beta
The `Microsoft.Intune.Maui.Essentials.android` makes use of specific MSBuild targets and "remapping" features.
We should add a test verifying that it stays working over time.
=> [tests] add test for Microsoft.Intune

build-tools/automation/yaml-templates/install-microbuild-tooling.yaml
Context: https://github.com/xamarin/xamarin-android/commit/4fffbf686bad5479a8ef7954d7d9d0d68941f034
Authenticode signing attempts recently started failing again due to
issues installing the `xsignextension`.  We believe python 3.12 may have
caused this breakage, so we're pinning to 3.11.x for now.
=> [ci] Use python 3.11.x

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs
Our designer tests were not using ` AndroidSdkResolver.GetMaxInstalledPlatform ()`. As a result if the `android-27` platform was NOT installed the unit tests would fail. Lets update the system to use the helper method to find the latest installed platform and use that.
=> [Tests] Fix Designer Tests to use ` AndroidSdkResolver.GetMaxInstalledPlatform ()`

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
Context: https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android/10.0.0-beta2
A `MicrosoftIntune(false)` test on xamarin-android/main can fail with:
/Users/runner/.nuget/packages/microsoft.intune.maui.essentials.android/10.0.0-beta/build/netstandard2.0/Microsoft.Intune.Maui.Essentials.android.targets(203,9):
error : /Users/runner/work/1/s/bin/Release/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.android-x64/8.0.0-rc.2.23466.4/runtimes/android-x64/native/libSystem.Security.Cryptography.Native.Android.jar doesn't contain /Users/runner/.nuget/packages/ and the mamified library won't be placed in the correct intune directory. This is not expected.
This is potentially fixed in the next release, let's try it.
=> [tests] update Microsoft.Intune.Maui.Essentials.android

tests/MSBuildDeviceIntegration/Tests/AotProfileTests.cs, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs, tests/MSBuildDeviceIntegration/Tests/MonoAndroidExportTest.cs, tests/MSBuildDeviceIntegration/Tests/SystemApplicationTests.cs
MSBuild device tests that specified a subset of supported ABIs can fail
depending on your target device/emulator.  These tests have been updated
to use the default ABI of the attached device, which is determined
during test setup.
Tests which explicitly specify the full set of supported ABIs have been
left unchanged.
=> [tests] Better support running on arm64-v8a devices

Directory.Build.props, src/Mono.Android/Mono.Android.targets
Updates mdoc to version 5.9.2.4, and updates the `_RunMdoc` target to
use the same commands and parameters as the [automated docs build][0].
[0]: https://apidrop.visualstudio.com/Content%20CI/_build?definitionId=5552
=> [Mono.Android] Replicate automated docs build

build-tools/automation/yaml-templates/build-windows.yaml
We are no longer regularly installing arbitrary preview versions of the
classic XA VSIX on our Windows pool.  We can save some windows build
time by not attempting to modify VS.
=> [ci] Do not try to modify classic VSIX install

.gitmodules, src/Xamarin.Android.Build.Tasks/Resources/proguard_xamarin.cfg, src/java-runtime/java-runtime.csproj, tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Remaps.xml, tests/Mono.Android-Tests/proguard.cfg
Changes: https://github.com/xamarin/java.interop/compare/25850ba741b9e3d9dbda353c03b80f7ccb4def42...445ee6cdde696f771bb73c1694adacac56006b78
* xamarin/java.interop@445ee6cd: Rename com.xamarin.java_interop package to net.dot.jni (xamarin/java.interop#1166)
=> Bump to xamarin/Java.Interop/main@445ee6cd

build-tools/automation/azure-pipelines-nightly.yaml
Commit https://github.com/xamarin/xamarin-android/commit/204225b8ca3d94842f82e6fed60d350776191c23 broke the nightly build, as it added a `maui` checkout
to the main build and the maui resource was night defined in the nightly
pipeline.  This checkout was added as a sort of workaround to make sure
we are always checking out at least 2 repos, so that our sources are
placed into consistent locations.
=> [ci] Fix nightly build

.github/ISSUE_TEMPLATE/01-building-an-application.yml, .github/ISSUE_TEMPLATE/02-running-an-application.yml, .github/ISSUE_TEMPLATE/03-mono-android-api.yml, .github/ISSUE_TEMPLATE/04-binding-a-java-library.yml, .github/ISSUE_TEMPLATE/05-other.yml, .github/ISSUE_TEMPLATE/config.yml
Update some placeholder values to reflect more recent versions of our components.
=> [GitHub] Modernization tweaks for GitHub issue templates.

.external, Configuration.props, build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/build-windows.yaml, build-tools/automation/yaml-templates/run-emulator-tests.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/scripts/TestApks.targets
Context: https://github.com/xamarin/xamarin-android-tools/pull/218
Changes:
* xamarin/monodroid@7b6faa349: Bump to xamarin/android-sdk-installer@ac2bd9a, xamarin/androidtools@352675a
* xamarin/monodroid@7a85ac569: [ci] Stop provisioning Xcode on macOS agents
Changes:
* xamarin/xamarin-android-tools@08a6990 Bump android-sdk NDK version to 26.1.10909125
* xamarin/xamarin-android-tools@6ae1f2a Bump android-sdk build-tool version to 34.0.0
* xamarin/xamarin-android-tools@184b6b3 Bump android-sdk cmdline-tools to version 11.0
* xamarin/xamarin-android-tools@1365e33 Bump android-sdk platforms-tools to version 34.0.5
* xamarin/xamarin-android-tools@8d38281 Update the maximum NDK version to 26
Updates our recommended Android SDK component versions to the following:
* build-tools 34.0.0
* …
=> [release/8.0.1xx] Bump Android SDK component versions

src/Microsoft.Android.Templates/android-bindinglib/AndroidBinding1.csproj
Fixes: https://github.com/xamarin/xamarin-android/issues/8411
Context: https://github.com/dotnet/docs-maui/pull/1916
We have a nice docs page that should eliminate some confusion if we linked to it with a comment in the project template.
I considered putting a commented out example of disabling the C# binding (ala `EmbeddedReferenceJar`):
<ItemGroup>
<AndroidLibrary Update="foo.jar" Bind="false">
</ItemGroup
But I think this case is rare, and the docs page should be sufficient.
=> [Microsoft.Android.Templates] docs link in binding project template

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs
Context: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
By using the revisions of Android SDK Platforms already on the MS Hosted CI images we do not need to spend time downloading and installing alternate versions.
Current `main` `xaprepare`:
```
* Checking platform-33_r02
outdated
* Checking platform-34-ext7_r01
outdated
```
This PR `xaprepare`:
```
* Checking platform-33-ext3_r03
installed
* Checking platform-34-ext7_r02
installed
```
Note these "ext" versions seem to be the new "baseline" versions.  That is, there is no longer a "plain" `platform-33` or `platform-34` listed in the Google SDK manifest.
Neither `ApiCompat` nor `PublicApiAnalyzers` were triggered, so we can safely assume the public API has not changed in these new revisions.
=> [xaprepare] Track the versions of Android SDK Levels available on CI agents.

build-tools/cmake/xa_macros.cmake, src/monodroid/CMakeLists.txt
The following compile-time warning options are added:
* -Wformat=2
Enable additional format function warnings. The `2` form of the
option enables more extensive checks in calls to `printf`, `scanf`
etc. These are compile-time only checks, no effect on runtime
performance.
* -Wimplicit-fallthrough
Warn when a switch case falls through. If this is an intended
-action, it can be marked with the `[[fallthrough]]` attribute
* -Wtrampolines
Enable warnings about trampolines that require executable stacks.
The following options which affect the generated code are added:
* -fstack-clash-protection
Enable run-time checks for variable-size stack allocation validity.
This may affect performance if code allocates a lot of memory on the
stack, but since we don't do that, we should be fine.
* …
=> Add a handful of compiler options to harden code

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj
Bump `xamarin-android-tools` from `bde49e6` to `4889bf0`.
With https://github.com/xamarin/xamarin-android-tools/pull/220, we now need to set `$(_IncludeMicrosoftBuildPackage)` for projects that need a `Microsoft.Build` reference.
This bump fixes 226 CI reported warnings (390 -> 164).
=> Bump `xamarin-android-tools` from `bde49e6` to `4889bf0`.

build-tools/automation/azure-pipelines.yaml
Context: https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet9
We need to start pushing xamarin-android/main to the `dotnet9` feed going forward.
Switch to using the `dnceng-dotnet9` credentials, which we'll have to work with someone in release engineering to help setup.
=> [build] push .NET 9 packages using `dnceng-dotnet9`

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetCLI.cs
When running MSBuild tests locally, both of the paths used for:
/p:AndroidSdkDirectory="C:\Some Path\android-sdk\"
/p:JavaSdkDirectory="C:\Some Path\jdk\"
Because the two paths have a trailing `\`, it appears that MSBuild is escaping the `\"` giving an error message that we can't build more than one project! Basically, all command-line parsing is failing!
I am unsure what changed, but making this change locally allows me to run the MSBuild tests again.
=> [tests] trim trailing `\` from AndroidSdkDirectory/JavaSdkDirectory

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/Adb.cs, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CheckAdbTarget.cs
Currently the `start-emulator` tasks emit 4 warnings for each invocation, related to the initial probing it does to see if an emulator is already running.
```
/Users/runner/work/1/s/build-tools/scripts/TestApks.targets(50,5): warning : * daemon not running; starting now at tcp:5037 [/Users/runner/work/1/s/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Emulator.csproj]
/Users/runner/work/1/s/build-tools/scripts/TestApks.targets(50,5): warning : * daemon started successfully [/Users/runner/work/1/s/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Emulator.csproj]
/Users/runner/work/1/s/build-tools/scripts/TestApks.targets(50,5): warning : adb: no devices/emulators found [/Users/runner/work/1/s/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tes …
```
=> [ci] Don't emit warnings for normal `CheckAdbTarget` operations.

src/Mono.Android/Mono.Android.csproj
Context: https://github.com/xamarin/xamarin-android/commit/e2854ee71961d4a9910944e5b2aa7107cdf2349c
Often when compiling XA locally on Windows I get this error:
```
CSC : error CS2012: Cannot open 'c:\code\xamarin-android\external\Java.Interop\tools\generator\obj\Debug-net7.0\generat
or.dll' for writing -- 'The process cannot access the file 'c:\code\xamarin-android\external\Java.Interop\tools\generat
or\obj\Debug-net7.0\generator.dll' because it is being used by another process.' [c:\code\xamarin-android\external\Java
.Interop\tools\generator\generator.csproj]
```
This is caused by our usage of `AdditionalProperties` in our `<ProjectReference>`.  This was needed as a result of trying to reference a `net472;net7.0` `generator` project in a `MonoAndroid1.0;net7.0` `Mono.Android` project. …
=> [Mono.Android] Remove `AdditionalProperties` from Java.Interop tools project references.

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 8789978

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
Context: https://github.com/dotnet/sdk/commit/d21e6bf5c5a239892d771f409841ce856bddcd89
Context: https://github.com/xamarin/xamarin-android/commit/8fa5d99341b868795b54bfa9d087bda38151a4d2
Context: https://github.com/xamarin/xamarin-android/commit/0cd963ac03fbd3d7370221adbc65b099e18f6565
Building a `net8.0-android` project with a .NET 9 SDK will fail when using specific arguments:
> dotnet publish -r android-arm64
MSBuild version 17.9.0-preview-23577-01+31108edc1 for .NET
...
bin\Debug\dotnet\sdk\9.0.100-alpha.1.23603.1\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(494,5): error NETSDK1112: The runtime pack for Microsoft.Android.Runtime.34.android-arm64 was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'android-arm64'.
Our …
=> [Xamarin.Android.Build.Tasks] don't set $(PublishSelfContained) for .NET 9

Makefile
Commit 60fd55e2 likely should have broken the release/7.0.4xx
build in the same way that it is currently failing:
"/Users/builder/azdo/_work/4/s/xamarin-android/tests/Mono.Android-Tests/Runtime-MultiDex/Mono.Android-TestsMultiDex.csproj" (default target) (32:6) ->
(_CompileToDalvik target) ->
MSBUILD : java error JAVA0000: Error in /Users/builder/android-toolchain/sdk/build-tools/34.0.0/mainDexClasses.rules [/Users/builder/azdo/_work/4/s/xamarin-android/tests/Mono.Android-Tests/Runtime-MultiDex/Mono.Android-TestsMultiDex.csproj]
MSBUILD : java error JAVA0000: Failed to read file: /Users/builder/android-toolchain/sdk/build-tools/34.0.0/mainDexClasses.rules [/Users/builder/azdo/_work/4/s/xamarin-android/tests/Mono.Android-Tests/Runtime-MultiDex/Mono.Android-TestsMultiDex.csproj]
MSBUILD : …
=> Build classic tests with build-tools 30.0.3

Makefile
Context: https://github.com/xamarin/xamarin-android/pull/8580
Does It Build™?
It *should* build, it *used* to build (on 2023-09-02), but #8580 *doesn't* build, as it's trying to reference
`android-toolchain/sdk/build-tools/34.0.0/mainDexClasses.rules`, which doesn't exist.
Furthermore, AFAICT `xaprepare` uses `$(XABuildToolsVersion)` to specify which build-tools package is installed, which has been `34` since 326ac889d5, so… how did it build then and why is it failing to build now?  What am I missing?
=> Empty commit

build-tools/automation/yaml-templates/install-microbuild-tooling.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs
Authenticode signing attempts started failing recently with:
ERROR: 'xsign' is misspelled or not recognized by the system.
Updating to Python 3.11 is the suggested fix for this issue.
=> [ci] Use python 3.11 for signing tasks

src/Mono.Android/Xamarin.Android.Net/ServerCertificateCustomValidator.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
Fixes https://github.com/dotnet/runtime/issues/95506
In Release configuration the `X509ExtendedTrustManagerInvoker` class is trimmed and so the `trustManager is IX509TrustManager tm` pattern matching doesn't work. This PR addresses the problem in two ways:
- an internal X509 trust manager is now required - it can't silently work with a `null` internal trust manager anymore
- `[DynamicDependency]` attribute to prevent trimming of the invoker classes for the `IX509TrustManager` interface and for the `X509ExtendedTrustManager` abstract class
/cc @grendello
=> [Mono.Android] Fix ServerCertificateCustomValidator

build-tools/automation/azure-pipelines-nightly.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/25351/APIScan-step-by-step-guide-to-setting-up-a-Pipeline
The ApiScan task has been added to the nightly build and test run.  This
task should help us identify related issues earlier, rather than having
to wait for a full scan of VS.  The task can take a long time to execute
so it has been added to the nightly job rather than the PR or CI jobs.
=> Add ApiScan to nightly build

build-tools/automation/azure-pipelines.yaml
The `MAUI Integration` test lane is currently failing with:
Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Could not find workload 'microsoft-net-runtime-android-net8' extended by workload 'android' in manifest 'microsoft.net.sdk.android' [C:\a\_work\1\s\maui\bin\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\WorkloadManifest.json]
at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.<>c__DisplayClass26_0.<<EnumerateWorkloadWithExtends>g__EnumerateWorkloadWithExtendsRec|0>d.MoveNext()
at System.Linq.Enumerable.AppendPrependIterator`1.LoadFromEnumerator()
at System.Linq.Enumerable.AppendPrepend1Iterator`1.MoveNext()
at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
at …
=> [tests] use `dotnet/maui/net9.0` branch

src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/xamarin-android/issues/8421
Reviewing the build log from:
dotnet new maui
dotnet build -f net8.0-android -bl
I noticed:
LinkAssembliesNoShrink 3.410s
...
Failed to read 'C:\Program Files\dotnet\packs\Microsoft.Android.Runtime.34.android-arm64\34.0.52\runtimes\android-arm64\lib\net8.0\Mono.Android.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
Failed to read 'C:\Program Files\dotnet\packs\Microsoft.Android.Runtime.34.android-arm64\34.0.52\runtimes\android-arm64\lib\net8.0\Java.Interop.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
Failed to read 'D:\.nuget\packages\microsoft.maui.controls.compatibility\8.0.3\lib\net8.0-android34.0\Microsoft.Maui.Controls.Compatibil …
=> [Xamarin.Android.Build.Tasks] <LinkAssembliesNoShrink/> skips symbols

build-tools/automation/azure-pipelines-nightly.yaml, src/Mono.Android/Android.Runtime/AndroidRuntimeInternal.cs, src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android.Runtime/JNINativeWrapper.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
We can simplify `JNIEnv.PropagateUncaughtException` by removing the
fallback case that would attempt to look for
`System.Diagnostics.Debugger.Mono_UnhandledException`.  In .NET the
`MonodroidRuntime::monodroid_debugger_unhandled_exception` function will
always be defined, and `Mono_UnhandledException` appears to no longer
exist in .NET.  This simplification should also appease our latest set
of API scan results that were complaining about missing documentation
for `Mono_UnhandledException`.
=> [Mono.Android] Remove Mono_UnhandledException lookup

src/Microsoft.Android.Templates/android-activity/.template.config/template.json, src/Microsoft.Android.Templates/android-layout/.template.config/template.json
Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1918037
Context: https://github.com/dotnet/templating/wiki/Reference-for-template.json
Context: https://github.com/dotnet/templating/wiki/Post-Action-Registry#open-a-file-in-the-editor
Within Visual Studio, if you:
1. Create a new .NET MAUI or .NET Android app, then
2. Go to the Solution Explorer, then
3. Right-click a folder, then click Add > New Item > Android, then
4. Double-click the **Android Activity** template.
The expected result is that a new Android Activity based on the Android Activity template will be added to your solution *and opened in the editor*.
Instead, a new Android Activity is added, but it is *not* opened.
Update the `.template.config/template.json` files to contain a `postActions` section with a …
=> [Microsoft.Android.Templates] New files should open editor

build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/yaml-templates/build-macos.yaml, build-tools/automation/yaml-templates/commercial-build.yaml
The API Scan job added in commit a10aa383cb accidentally excluded some
of our xamarin-android-binutils artifacts.  The job has been fixed to
scan the EXE files (and corresponding symbols) that were previously
skipped.  The latest scan results appear to be consistent with what was
being reported through VS scans, and we can continue working through
these issues: 
1. ApiScan Error missingsymbols - File: aapt2.exe.
Tool: ApiScan: Rule: missingsymbols (Missing Symbols)
2. ApiScan Error documentationnotfound - File: aapt2.exe.
Tool: ApiScan: Rule: documentationnotfound (Documentation Not Found).
3. ApiScan Error improperfileformat - File: as.exe.
Tool: ApiScan: Rule: improperfileformat (Improper File Format).
4. ApiScan Error missingsymbols - File: ld.exe.
Tool: ApiScan: Rule: missingsymbols …
=> [ci] Add exe files to API Scan

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
To keep app sizes down in the .NET 6 timeframe, we special-cased existing AndroidX and GPS packages so they were always trimmed.
Modern packages mark themselves trimmable with `$(IsTrimmable)` or the assembly-level attribute.
For nearly 2 years, we've applied the appropriate trimming setting in these packages:
* https://github.com/xamarin/AndroidX/pull/520
* https://github.com/xamarin/GooglePlayServicesComponents/pull/597
We should be able to remove this now in .NET 9.
=> [Xamarin.Android.Build.Tasks] remove `%(TrimMode)=link` metadata

Configuration.props, Directory.Build.props, build-tools/automation/yaml-templates/install-microbuild-tooling.yaml, build-tools/scripts/RunTests.targets, build-tools/xaprepare/xaprepare/Application/Context.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs, build-tools/xaprepare/xaprepare/Steps/Step_ThirdPartyNotices.cs, tests/api-compatibility/api-compatibility.targets
Fixes various CI warnings.
```
Specifying an exact version is not recommended on Microsoft-Hosted agents. Patch versions of Python can 
be replaced by new ones on Hosted agents without notice, which will cause builds to fail unexpectedly. It is 
recommended to specify only major or major and minor version (Example: `3` or `3.9`)
```
Fix: only specify `major.minor` as requested.
```
build-tools\scripts\RunTests.targets(3,3): Warning MSB4011: "C:\a\_work\1\s\Directory.Build.props" 
cannot be imported again. It was already imported at "C:\a\_work\1\s\build-tools\scripts\PrepareWindows.targets 
(3,3)". This is most likely a build authoring error. This subsequent import will be ignored. 
build-tools\scripts\RunTests.targets(7,3): Warning MSB4011: "C:\a\_work\1\s\Configuration.props" 
cannot be …
```
=> [ci] Fix remaining permanent CI warnings.

src/Mono.Android/Xamarin.Android.Net/ServerCertificateCustomValidator.cs
Follow-up to #8594 to fix https://github.com/dotnet/runtime/issues/95506 on Android API 21-23
=> [Mono.Android] Fix ServerCertificateCustomValidator on API 21-23

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
We are seeing numerous test failures because of this warning.
```
C:\Android\android-sdk\tools\proguard\proguard-android.txt : warning XA4304: ProGuard configuration file 'C:\Android\android-sdk\tools\proguard\proguard-android.txt' was not found.
```
This is because the proguard-android.txt file no longer ships with the android sdk. We should check this file exists before adding it to the list of `_ProguardConfiguration` files. This way if a user still does have it, it will be included.
=> Fix Proguard warning when missing Android Sdk proguard-android.txt

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1922983
Our error matching in Aapt2.cs did not include a new error message which has been introduced. As a result we got a APT2000 error instead of an actual error message which we get for other errors.
The error message in question is 
```
error: attribute ‘android:path’ in <data> tag has value of ‘code/fooauth://com.foo.foo, it must start with a leading slash ‘/’.
```
=> [Xamarin.Android.Build.Tasks] Add check for aapt2 invalid data path error

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.AvailableItems.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs, src/Xamarin.Android.Build.Tasks/Utilities/EnvironmentFilesParser.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Tooling.targets
In .NET 6+, `$(UsingAndroidNETSdk)` is always `true` as the general identifier that this project is .NET and not Xamarin.Android. We used this flag as a way to share code between .NET Android and Xamarin.Android.
* Remove checks for `$(UsingAndroidNETSdk)`
* No longer need to pass in this value to MSBuilds tasks or other C# classes
* Checks if `true` leave in place, and remove the condition
* Checks if `false` can just be completely removed now
In a future PR, we may also be able to remove `$(_AndroidIsBindingProject)`, which is slightly related. We removed the "binding project" as a concept in .NET 6+.
I left the `$(UsingAndroidNETSdk)` property in place, even though it is not used in these targets. Other general MSBuild targets may continue to use it in perpetuity.
=> [Xamarin.Android.Build.Tasks] remove checks for `$(UsingAndroidNETSdk)`

.github/workflows/locker.yml
Context: https://github.com/xamarin/xamarin-android/pull/8173
Context: https://github.com/dotnet/maui/pull/19145
When we [accepted migration](https://github.com/xamarin/xamarin-android/pull/8173) from `FabricBot` to `GitOps.ResourceManagement` due to `FabricBot` being decommissioned, one rule we lost was `[Closed Issue Management] Lock issues closed without activity for over 30 days`.  This rule is useful because comments on old, closed issues rarely will be seen or responded to, making us seem unresponsive to users.
MAUI has [replaced this rule](https://github.com/dotnet/maui/pull/19145) with a GitHub action written by the VSCode team that runs daily and performs the locking. We should ~~steal~~ borrow this for our own.
Unfortunately I'm not aware of a way to test a GitHub Action without …
=> [.github] Re-enable locking closed issues after 30 days of inactivity.

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Tooling.targets, src/Xamarin.Android.Build.Tasks/Tasks/ValidateJavaVersion.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ValidateJavaVersionTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/8369
During Android project builds, the `<ValidateJavaVersion/>` MSBuild task currently shells out to `java -version` and `javac -version` to determine if we have a *valid* & usable JDK.
Unfortunately, some customer logs have reported build times that are completely bananas:
Task ValidateJavaVersion 23.469s
...
Top 10 most expensive tasks
...
ValidateJavaVersion = 3:46.740, 35 calls
`java -version` and/or `javac -version` must be quite slow! Reading the source for OpenJDK, it appears that `java -version` actually starts a JVM to call a single method:
* https://github.com/openjdk/jdk/blob/df370d725e5ae55a05479e8375bf665233ac3e44/src/java.base/share/native/libjli/java.c#L1895-L1913
* …
=> [Xamarin.Android.Build.Tasks] parse JDK `release` file directly

Documentation/guides/messages/xa1039.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/xamarin/xamarin-android/pull/8629
This partially backports 2f192386 to .NET 8, but reduces XA1039 to a warning.
Also introduce `$(_AndroidIgnoreAndroidSupportWarning)` as an escape hatch if someone needs to completely disable the warning:
<_AndroidIgnoreAndroidSupportWarning>true</_AndroidIgnoreAndroidSupportWarning>
=> [release/8.0.1xx] [Xamarin.Android.Build.Tasks] XA1039 warning for Android.Support

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml, build-tools/automation/yaml-templates/variables.yaml
Now that API-34 is our baseline, we no longer need to install the API-33 Android SDK on our test agents, saving a little bit of space and time.
=> [ci] Only install Android SDK API-34 on test agents.

build-tools/automation/azure-pipelines-apidocs.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/build-linux.yaml, build-tools/automation/yaml-templates/commercial-build.yaml, build-tools/automation/yaml-templates/install-microbuild-tooling.yaml
The `NuGetAuthenticate@0` task is deprecated and will soon be removed:
Task 'NuGet authenticate' version 0 (NuGetAuthenticate@0) is deprecated.
This task will be removed. From January 31, 2024, onwards it may no longer be available.
Use the updated `NuGetAuthenticate@1` instead.
=> [ci] Use NuGetAuthenticate@1

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/Eol.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/InvalidConfigTests.cs
When .NET 9 ships, the .NET 7 Android workload will be out of support. We already have this behavior setup, but unfortunately the error message is wrong:
Microsoft.NET.EolTargetFrameworks.targets(38,5):
error NETSDK1202: The workload 'net6.0-android' is out of support and will not receive security updates in the future. Please refer to
https://aka.ms/maui-support-policy for more information about the support policy.
[MauiTest.csproj::TargetFramework=net7.0-android]
It says `net6.0-android`!
In a48a9c56, we hardcoded `net6.0` to align with the iOS team, but we can use the `$(TargetFrameworkVersion)` property (removing `v`) so we don't have to update this line every year.
I updated a test for this scenario.
=> [Xamarin.Android.Build.Tasks] fix net7.0 "out of support" message

Directory.Build.props
Context: https://github.com/xamarin/xamarin-android/tree/release/9.0.1xx-preview1
We branched for .NET 9 Preview 1 from cf1418d0 into 9.0.1xx-preview1; the main branch is now .NET 9 Preview 2.
Update xamarin-android/main's version number to 34.99.0-preview.2.
=> $(AndroidPackVersionSuffix)=preview.2; net9 is 34.99.0.preview.2

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/Linux.Debian.cs
SparkyLinux is a Debian-based distribution that's 100% compatible with its upstream, 
but it is rebranded and follows its own versioning scheme.  Add support for SparkyLinux 
detection so that `xaprepare` can properly detect the required packages.
TODO: the whole Debian detection code has to be refreshed at some point.
=> [xaprepare] Add support for newer SparkyLinux

.gitmodules, build-tools/automation/yaml-templates/apk-instrumentation.yaml, src/Mono.Android/Java.Interop/TypeManager.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateCompressedAssembliesNativeSourceFiles.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJniRemappingNativeCode.cs, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Tasks/JavaCompileToolTask.cs, src/Xamarin.Android.Build.Tasks/Tasks/R8.cs, src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/CompressedAssembliesNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/JniRemappingAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrComposer.cs, src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodsNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/NativeTypeMappingData.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingDebugNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingReleaseNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/XAJavaTypeScanner.cs
Context: https://github.com/xamarin/java.interop/pull/1181
Context: https://github.com/xamarin/xamarin-android/pull/8625
Context: https://github.com/xamarin/java.interop/commit/005c914170a0af9069ff18fd4dd9d45463dd5dc6
Does It Build™?
PR #8625 has turned into a cluster, *probably* because of xamarin/java.interop@005c9141, which implicitly requires typemap support for *non*-`Java.Lang.Object` subclasses such as the `CallVirtualFromConstructorDerived` test type.
Java.Interop#1181 updates typemap and JCW generation to support `Java.Interop.JavaObject` and `Java.Interop.JavaException` subclasses, which will *hopefully* allow the
`CallVirtualFromConstructorDerived`-using tests to work.
=> Bump to xamarin/java.interop/main@07c73009

Configuration.props
Changes: https://github.com/xamarin/xamarin-android/compare/d12da3a1...87e4a6d8
These changes are going out in a future servicing release.
=> Bump to 34.0.79 $(AndroidNetPreviousVersion)

Configuration.props, Documentation/workflow/HowToAddNewApiLevel.md, build-tools/automation/azure-pipelines.yaml, build-tools/create-android-api/create-android-api.csproj, build-tools/xaprepare/xaprepare/Application/AndroidToolchainComponent.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, build-tools/xaprepare/xaprepare/Main.cs, build-tools/xaprepare/xaprepare/Steps/Step_Android_SDK_NDK.cs, src/Mono.Android/Mono.Android.targets
Today, we recalculate the `api.xml` for `Mono.Android` API-34 on every build.
This involves:
- Installing Android SDK platforms 23 - 34 (2.2 GB)
- Running `class-parse` on every API level
- Running `api-xml-adjuster` on every API level
- Running `api-merge` to merge every level into a single `api.xml`
However, the output ~never changes, as the Android API should not change once it has shipped.  Thus, we can save disk space and build time by committing a completed `api.xml` instead of rebuilding it.
Additionally, `xaprepare` no longer installs all Android SDK Platforms by default.  Instead it defaults to only installing the latest stable version and any unstable preview version(s).  New value `all` has been added to the supported `-android-sdk-platforms=` command line argument to request …
=> [Mono.Android] Commit `api-34.xml` instead of generating it on every build.

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs
Context: https://github.com/xamarin/xamarin-android/issues/8421
Working a bit on build performance, I tested:
* `dotnet new maui`
* `dotnet build -bl`
The `.binlog` shows:
LinkAssembliesNoShrink 3.797s
Attaching `dotnet-trace` as mentioned on:
https://github.com/xamarin/xamarin-android/blob/2f192386e8072f8e0ecaf0de2fe48654f3ade423/Documentation/guides/tracing.md#how-to-dotnet-trace-our-build
I see time broken down such as:
FixAbstractMethods: 37%
AssemblyDefinition.Write: 27%
ProcessAssemblyDesigner: 20%
CopyIfChanged: 13%
DirectoryAssemblyResolver.GetAssembly: 4.4%
This made me focus in on `FixAbstractMethodsStep` and make the following changes:
* All calls for `TypeReference.Resolve()` and `MethodReference.Resolve()` should go through the `TypeDefinitionCache` to avoid repeated lookups. …
=> [Xamarin.Android.Build.Tasks] `FixAbstractMethodsStep` performance

.external
Changes: https://github.com/xamarin/monodroid/compare/66a65e3b3e5fa4314d8e8d4f1b8ad578a4a56ab0...848d1277b76a599d8a280d58ec06e95477b4a7e5
The `<_InstallAndroidJdk/>` target has been removed from the
`<InstallAndroidDependencies/>` target, as Java SDK installation support
has been added to `Xamarin.Installer.Build.Tasks`.
=> Bump to xamarin/monodroid@848d1277b7

Documentation/previous-releases.md, README.md
Fixes: https://github.com/xamarin/xamarin-android/issues/8708
Add README links to Android SDK 13.2.2 packages. (The most recent available.)
Also, remove mention of OSS packages, as the pipeline has not run in 2 years.
=> [readme] Add `d17-8` download links.

.external
Changes: https://github.com/xamarin/monodroid/compare/7b6faa34...7edfb4a9
* [ci] Fix monodroid component inclusion
* [release/8.0.1xx] Bump xamarin-android and yaml ref
* [release/8.0.1xx] Bump to xamarin/androidtools@6993959a
=> Bump to xamarin/monodroid/release/8.0.1xx@7edfb4a9

Configuration.props, build-tools/create-packs/Microsoft.Android.Ref.proj, src/Mono.Android/Mono.Android.csproj
Changes: https://github.com/xamarin/Java.Interop/compare/7f08b77f3464f2b276ec5edd2e4836b1915f86dd...dfcbd670304bb3d4becc6c76a3c16f10a158efae
* xamarin/Java.Interop@dfcbd670: Bump to xamarin/xamarin-android-tools/main@a698a33 (xamarin/Java.Interop#1189)
* xamarin/Java.Interop@6182baff: [build] Target `net8.0` (xamarin/Java.Interop#1186)
xamarin/java.interop@6182baff updated Java.Interop to target .NET 8 instead of .NET 7.  This introduced a build break:
…/xamarin-android/src/Mono.Android/Mono.Android.csproj(402,5):
error MSB3030: Could not copy the file
"…/xamarin-android/external/Java.Interop/bin/Debug-net7.0/ref/Java.Interop.dll"
because it was not found.
Introduce a new `$(JavaInteropTargetFrameworkVersion)` MSBuild property within `Configuration.props` which contains the .NET version …
=> Bump to xamarin/Java.Interop/main@dfcbd670

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://developercommunity.visualstudio.com/t/Visual-Studio-2022-Community-1785-ver/10577484
Related: https://github.com/xamarin/xamarin-android/issues/8662
I found the following build performance issue using a .NET Android project template inside VS Windows:
1. Create a new .NET Android project
2. Open some `AndroidResource` `.xml` file in the Android designer
3. *Every* incremental build appears to rebuild everything!
`obj\Debug\net8.0-android\build.props` appears to be changing between builds with the change:
```diff
--androidsupportedabis=armeabi-v7a;arm64-v8a;x86;x86_64
++androidsupportedabis=arm64-v8a
```
I narrowed this down to the designer running two targets, `PrepareResources;_GenerateCompileInputs`:
https://github.com/xamarin/UITools/blob/7b167eae94ae018ab19344d6bfb45a925 …
=> [Xamarin.Android.Build.Tasks] remove `$(AndroidSupportedAbis)` from `build.props`

src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj
It appears this is not needed?
=> [Microsoft.Android.Sdk.ILLink] remove Java.Interop.Export reference

Directory.Build.props
Update LibZipSharp to version 3.1.1.
Changes https://github.com/xamarin/LibZipSharp/compare/3.0.0...3.1.1
=> Bump LibZipSharp to 3.1.1

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
Changes: https://github.com/android/ndk/wiki/Changelog-r26#r26c
* Updated LLVM to clang-r487747e. See AndroidVersion.txt and clang_source_info.md 
in the toolchain directory for version information.
* [Issue 1928](https://github.com/android/ndk/issues/1928): Fixed Clang crash in 
instruction selection for 32-bit armv8 floating point.
* [Issue 1953](https://github.com/android/ndk/issues/1953): armeabi-v7a libc++ 
libraries are once again built as thumb.
`AndroidVersion.txt` contains:
```
17.0.2
based on r487747e
```
=> Bump NDK to r26c

build-tools/xaprepare/xaprepare/Application/RegexProgramVersionParser.cs, build-tools/xaprepare/xaprepare/Application/SevenZipVersionParser.cs, build-tools/xaprepare/xaprepare/Application/VersionFetchers.cs, build-tools/xaprepare/xaprepare/ToolRunners/SevenZipRunner.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj
From time to time, `7zip` invoked by `xaprepare` with an error similar to:
ERROR: Dangerous symbolic link path was ignored : android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/lib/python3.10/site-packages/lldb/lldb-argdumper : ../../../../bin/lldb-argdumper
ERROR: Dangerous symbolic link path was ignored : android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/lib/python3.10/site-packages/lldb/_lldb.cpython-310-x86_64-linux-gnu.so : ../../../liblldb.so
The problem is that this symlink is **not** a dangerous one, as it doesn't 
point outside the archived directory tree.
This happened on mac, Windows and Linux alike.
Try to work around the issue by using an undocumented `-snld` 7zip option 
when extracting ZIP archives.  Since the option is understood only from
`7-Zip` 20.x, check the …
=> [xaprepare] Make 7zip work with "dangerous" symlinks in ZIPs

.external
Changes: https://github.com/xamarin/monodroid/compare/848d1277b76a599d8a280d58ec06e95477b4a7e5...cb01503327f7723ec138ec4cc051610fecee1bf7
* xamarin/monodroid@cb0150332: Bump external/xamarin-android from `0c0f1fe` to `7368487`
* xamarin/monodroid@52e7c4c09: Bump external/android-sdk-installer from `4127490` to `13b2fb3`
* xamarin/monodroid@5003ccb4d: Bump external/android-sdk-installer from `9e143d7` to `4127490`
* xamarin/monodroid@d7ff10afb: Bump tools/msbuild/external/androidtools from `15350e7` to `8aeb717`
* xamarin/monodroid@ae8c39d59: Bump external/xamarin-android from `80ee320` to `0c0f1fe`
* xamarin/monodroid@d76e18694: [tools/msbuild] introduce $(_AndroidAllowJavaDebugging) feature switch
=> Bump to xamarin/monodroid@cb01503327

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
Context: https://github.com/xamarin/java.interop/pull/1174
In https://github.com/xamarin/java.interop/pull/1174, we refactored `Java.Interop.Tools.JavaCallableWrappers` to be more maintainable.  This resulted in a changed public API for consuming the library.
Update `Xamarin.Android.Build.Tasks.GenerateJavaStubs` to consume the updated API.
=> Track `Java.Interop.Tools.JavaCallableWrappers` changes

external/xamarin-android-tools.override.props
Somewhere in the dotnet/maui repo, it encountered the error:
XARLP7028
System.IO.FileNotFoundException: Could not load file or assembly 'libZipSharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=276db85bc4e20efc' or one of its dependencies. The system cannot find the file specified.File name: 'libZipSharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=276db85bc4e20efc'   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(IDictionary`2 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments, ICollection`1 proguardConfigFiles)   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.RunTask()   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in …
=> [xamarin-android-tools] import $(LibZipSharpVersion) value

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
Context: https://github.com/xamarin/xamarin-android/pull/8478
Context: https://github.com/xamarin/monodroid/pull/1393
Merging this no-op change will make it easier to orchestrate 
merging of the two PRs above.  
It allows us to merge the `monodroid` one before merging #8478 
and prevents breaking of any other builds or PRs in between 
merging of the two PRs.
=> Add a property required by #8478

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/variables.yaml
A new $(RunMAUITestJob) variable has been added to control execution of
the MAUI integration test job.  The value of this variable defaults to
true and it provides an easy way to disable the job on servicing/older
branches if needed.
=> [ci] Always run the MAUI test job

src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs, tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidMessageHandlerTests.cs
Fixes #7086
Neither the SocketsHttpHandler nor the ios/mac NSUrlSessionHandler dispose the content stream.
/cc @grendello
=> [Mono.Android] Do not dispose request content stream in AndroidMessageHandler

Directory.Build.props
Context: https://github.com/xamarin/xamarin-android/tree/release/9.0.1xx-preview2
We branched for .NET 9 Preview 2 from 8c7cf91f into release/9.0.1xx-preview2; the main branch is now .NET 9 Preview 3.
Update xamarin-android/main's version number to 34.99.0-preview.3.
=> $(AndroidPackVersionSuffix)=preview.3; net9 is 34.99.0.preview.3

.external
Changes: https://github.com/xamarin/monodroid/compare/cb01503327f7723ec138ec4cc051610fecee1bf7...e13723e701307f9f6966d4b309c3eba10a741694
* xamarin/monodroid@e13723e70: Bump external/xamarin-android from `87d8914` to `8c7cf91`
* xamarin/monodroid@905441a99: Pass the required parameters to BuildApk
* xamarin/monodroid@59a052933: [ci] Add guardian supression file
=> Bump to xamarin/monodroid@e13723e701

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Context: https://github.com/NuGet/Home/issues/13269#issuecomment-1969883700
In 2f4e01ec, we saw a problem with no-op NuGet restore, no longer being a no-op. So we temporarily disabled the failing `IncrementalFastDeployment` test.
It turns out, it might be related to a duplicate source listed in our `NuGet.config` during MSBuild tests:
<add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
<add key="testsource2" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
This might have surfaced a bug in NuGet, but for now let's stop emitting duplicate sources?
=> [tests] fix duplicate sources in `NuGet.config`

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/GenerateSupportedPlatforms.cs, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/in/Microsoft.Android.Sdk.BundledVersions.in.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/8331
Context: https://github.com/xamarin/xamarin-android/pull/8569
Context: https://github.com/dotnet/sdk/commit/25b360d5799b022ea538a13bac52246f1a1b936a
Building for `net9.0-android33` would give a poor error message:
error NETSDK1181: Error getting pack version: Pack 'Microsoft.Android.Ref.33' was not present in workload manifests.
C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets
To solve this, you would either change 33 to 34, or just remove the number to rely on the default value.
To make this easier:
* Automatically switch to 34 if the user specifies 33 or less.
* Opt into `%(DefineConstantsOnly)=true` for API levels 21-33 (and not the …
=> [Xamarin.Android.Build.Tasks] set `%(DefineConstantsOnly)` for older API levels

src/Mono.Android/Android.App/Activity.cs, src/Mono.Android/Android.App/Dialog.cs, src/Mono.Android/Android.App/FragmentManager.cs, src/Mono.Android/Android.Runtime/AndroidRuntime.cs, src/Mono.Android/Android.Runtime/Extensions.cs, src/Mono.Android/Android.Runtime/JNINativeWrapper.cs, src/Mono.Android/Android.Runtime/JavaProxyThrowable.cs, src/Mono.Android/Android.Runtime/ResourceDesignerAttribute.cs, src/Mono.Android/Android.Runtime/ResourceIdManager.cs, src/Mono.Android/Android.Views/View.cs, src/Mono.Android/Android.Views/Window.cs, src/Mono.Android/Java.Interop/JavaObjectExtensions.cs, src/Mono.Android/Java.Interop/TypeManager.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
This fixes the next set of trimmer warnings found via:
<IsTrimmable>true</IsTrimmable>
<EnableAotAnalyzer>true</EnableAotAnalyzer>
`JavaCast<T>()` now requires `PublicConstructors` and `NonPublicConstructors` because of `Activator.CreateInstance<T>()`. This change bubbles up to various other types that have a `Find*ById<T>()` method:
* `Activity`
* `Dialog`
* `FragmentManager`
* `View`
* `Window`
`GetInvokerType()` also has suppressions around `Assembly.GetType()` and `Type.MakeGenericType()`. We track this for the future at:
https://github.com/xamarin/xamarin-android/issues/8724
Update `[DynamicallyAccessedMembers]` based on changes to `RegisterNativeMembers` in:
https://github.com/xamarin/java.interop/commit/b8f6f8884ac11775107cbb55a9f57a38cbd53240
`$(EnableAotAnalyzer)` found usage of …
=> [Mono.Android] fix trimming warnings, part 2

build-tools/automation/yaml-templates/apk-instrumentation.yaml, build-tools/automation/yaml-templates/build-linux.yaml, build-tools/automation/yaml-templates/build-macos.yaml, build-tools/automation/yaml-templates/build-windows.yaml, build-tools/automation/yaml-templates/commercial-build.yaml, build-tools/automation/yaml-templates/run-emulator-tests.yaml, build-tools/automation/yaml-templates/run-msbuild-tests.yaml, build-tools/automation/yaml-templates/run-nunit-tests.yaml, build-tools/automation/yaml-templates/run-sliced-nunit-tests.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml, build-tools/automation/yaml-templates/stage-msbuild-tests.yaml, build-tools/automation/yaml-templates/upload-results.yaml
The `@self` yaml template annotation only appears to be needed in the
pipeline file, and not in nested templates.  This should fix potential
issues with other repos that use these templates.
=> [ci] Do not use self annotation for yaml-templates

build-tools/automation/yaml-templates/run-msbuild-tests.yaml, build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml, build-tools/automation/yaml-templates/stage-msbuild-tests.yaml
The mega pipeline extends our msbuild stages and does not yet support
using the 1ES pipeline template.
=> [ci] Add 1ESPT override to MSBuild test stages

build-tools/automation/azure-pipelines.yaml
The recent 1ES pipeline template migration added a new source code
analysis stage that is failing on PR builds from forks.  We should be
able to fix this by skipping AzDO build tagging and monodroid scanning
for such builds.
=> [ci] Fix SDL Sources Analysis for PRs from forks

src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs
Fixes #8740 
There is a race condition in `AndroidMessageHandler` (see https://github.com/xamarin/xamarin-android/issues/8740#issuecomment-1960331579 for more information). The solution is fairly simple: we should determine the decompression strategy only during the setup, when `AutomaticDecompression` is set. We don't need to do any more work during the request.
To prevent changing the decompression strategy while there are requests mid-flight, the setter will only accept values until the first request is sent. This is exactly what the `SocketsHttpHandler` does. I didn't want to touch any code unrelated to the race condition in this PR so if we want to prevent other properties from being mutated while HTTP requests are being sent, we should do it in a follow-up PR.
/cc @grendello
=> [Mono.Android] Fix race condition in AndroidMessageHandler

Documentation/guides/tracing.md
* Mention `dotnet-dsrouter android`
https://github.com/dotnet/diagnostics/issues/4337
Was fixed by .NET 8 GA, so we can remove the section mentioning it.
* Mention the relationship between the `debug.mono.profile` Android system property and `$DOTNET_DiagnosticPorts`.
* Mention `suspend` vs `nosuspend`.
* Mention `libmono-component-diagnostics_tracing.so` and the Mono diagnostic component.
These all came up from conversations with customers, so I think it will be useful for anyone.
=> [docs] update notes about `dotnet-trace` and `dotnet-gcdump`

src/Microsoft.Android.Templates/android-activity/.template.config/template.json, src/Microsoft.Android.Templates/android-layout/.template.config/template.json
Fixes: https://github.com/xamarin/xamarin-android/issues/8626
Removes the word "template" that shows up in the New Item dialog box, as it is unnecessary.
The original issue also mentions not having a custom icon, but as we don't have any of those available, the default icon seems good enough.
=> [templates] Remove redundant "template" from display name.

.gitmodules
Changes: https://github.com/xamarin/java.interop/compare/bec0326a925ff888d96cb433f5049000a6d32a33...3c5cf34b0e3cc9427521530db9aa4b4abe39d20d
* xamarin/java.interop@3c5cf34b: [generator] Extend `skipInvokerMethods` support to interfaces. (xamarin/java.interop#1203)
=> Bump to xamarin/java.interop/release/8.0.1xx@3c5cf34b

.external
Changes: https://github.com/xamarin/monodroid/compare/e13723e701307f9f6966d4b309c3eba10a741694...77124dc16985a92077e62b0cfeaeb007c4d4fd2a
* xamarin/monodroid@77124dc16: Bump to xamarin/xamarin-android/main@4d1fca7 (xamarin/monodroid#1447)
* xamarin/monodroid@9caae8213: Bump to xamarin/androidtools/main@7818dc5 (xamarin/monodroid#1446)
* xamarin/monodroid@84a7fcd54: Bump to xamarin/android-sdk-installer/main@438cf89 (xamarin/monodroid#1448)
* xamarin/monodroid@cdb452cf0: [tools/fastdev] Use chmod to set files as readonly (xamarin/monodroid#1425)
* xamarin/monodroid@b99fa9086: Bump to xamarin/xamarin-android@5cd9a267e2 (xamarin/monodroid#1444)
=> Bump to xamarin/monodroid/main@77124dc1

build-tools/trim-analyzers/trim-analyzers.props, src/Mono.Android/Android.OS/AsyncTask.cs, src/Mono.Android/Android.Runtime/AndroidEnvironment.cs, src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android.Runtime/JavaCollection.cs, src/Mono.Android/Android.Runtime/JavaDictionary.cs, src/Mono.Android/Android.Runtime/JavaList.cs, src/Mono.Android/Android.Runtime/JavaSet.cs, src/Mono.Android/Android.Util/SparseArray.cs, src/Mono.Android/Android.Widget/AdapterView.cs, src/Mono.Android/Android.Widget/ArrayAdapter.cs, src/Mono.Android/Java.Interop/JavaConvert.cs, src/Mono.Android/Java.Interop/JavaObjectExtensions.cs, src/Mono.Android/Mono.Android.csproj, src/Mono.Android/System.Linq/Extensions.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5652
Each trimming problem listed below.
src\Mono.Android\Android.Runtime\AndroidEnvironment.cs(373,19): error IL2057: Unrecognized value passed to the parameter 'typeName' of method 'System.Type.GetType(String, Boolean)'. It's not possible to guarantee the availability of the target type.
src\Mono.Android\Android.Runtime\AndroidEnvironment.cs(379,22): error IL2057: Unrecognized value passed to the parameter 'typeName' of method 'System.Type.GetType(String, Boolean)'. It's not possible to guarantee the availability of the target type.
src\Mono.Android\Android.Runtime\AndroidEnvironment.cs(342,20): error IL2057: Unrecognized value passed to the parameter 'typeName' of method 'System.Type.GetType(String, Boolean)'. It's not possible …
=> [Mono.Android] is now "trimming safe"

src/Microsoft.Android.Templates/android-activity/.template.config/localize/templatestrings.en.json, src/Microsoft.Android.Templates/android-layout/.template.config/localize/templatestrings.en.json
Context: https://github.com/xamarin/xamarin-android/pull/8773
In https://github.com/xamarin/xamarin-android/pull/8773 we removed some redundant verbiage from our Android item templates.  Now a complete XA build produces generated file changes, leaving us with a dirty local tree.
Commit the updated generated EN localization string files.
=> [Microsoft.Android.Templates] Update EN localization templatestrings.

build-tools/automation/yaml-templates/apk-instrumentation.yaml
Context: https://github.com/xamarin/xamarin-android/issues/8687
In https://github.com/xamarin/xamarin-android/pull/7963, we added an automatic retry mechanism to the APK test suites.  However this mechanism does not give us a chance to run any tasks between the retry.  
This means that when the tests are run a second time the output directories have not been cleaned and thus we are running incremental builds instead of full builds.  We could unknowingly have tests that always fail on a clean build and succeed on an incremental build.
Thus we are going to remove the automatic retries.  The good news is these test suites seem to be much more stable now than when we implemented the retries, so hopefully this will not result in too many flaky CI builds.
=> [ci] Don't auto-retry APK test suites.

src/monodroid/CMakeLists.txt
Clean up `src/monodroid/CMakeLists.txt` by removing all the 
options to handle builds for macOS, Linux and Windows desktops.
Also, bump C standard to C11
=> [runtime] Remove the last vestiges of desktop builds

Documentation/guides/AndroidAssetPacks.md, Documentation/guides/building-apps/build-items.md, Documentation/guides/building-apps/build-process.md, Documentation/guides/building-apps/build-properties.md, Documentation/guides/messages/README.md, Documentation/guides/messages/xa0138.md, Documentation/guides/messages/xa0139.md, Documentation/guides/messages/xa0140.md, build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Assets.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2LinkAssetPack.cs, src/Xamarin.Android.Build.Tasks/Tasks/AndroidComputeResPaths.cs, src/Xamarin.Android.Build.Tasks/Tasks/CreateDynamicFeatureManifest.cs, src/Xamarin.Android.Build.Tasks/Tasks/GetAssetPacks.cs, src/Xamarin.Android.Build.Tasks/Tasks/RemoveUnknownFiles.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AssetPackTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/ZipArchiveEx.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context https://github.com/xamarin/xamarin-android/issues/4810
Google Android began supporting splitting up the app package into multiple
packs with the introduction of the `aab` package format. This format allows
the developer to split the app up into multiple `packs`. Each `pack` can be
downloaded to the device either at install time or on demand. This allows
application developers to save space and install time by only installing
the required parts of the app initially. Then installing other `packs`
as required.
There are two types of `pack`. The first is a `Feature` pack, this type
of pack contains code and other resources. Code in these types of `pack`
can be launched via the `StartActivity` API call. At this time due to
various constraints .NET Android cannot support `Feature` …
=> AssetPack Support

src/Microsoft.Android.Templates/android-bindinglib/AndroidBinding1.csproj, src/Microsoft.Android.Templates/android-wear/AndroidApp1.csproj, src/Microsoft.Android.Templates/android/AndroidApp1.csproj, src/Microsoft.Android.Templates/androidlib/AndroidLib1.csproj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Resources/LayoutBinding.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidLinkMode.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownProperties.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs, tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/BindingTests.cs, tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj, tests/Mono.Android-Tests/Android.Graphics/NinePatchTests.cs, tests/Mono.Android-Tests/Android.Widget/CustomWidgetTests.cs, tests/Mono.Android-Tests/Java.Lang/ObjectTest.cs, tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj, tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/System/AppContextTests.cs, tests/Mono.Android-Tests/System.Drawing/TypeConverterTest.cs, tests/Mono.Android-Tests/System.Text.Json/JsonSerializerTest.cs, tests/Mono.Android-Tests/System/AppDomainTest.cs, tests/Mono.Android-Tests/System/ExceptionTest.cs, tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidClientHandlerTests.cs
As we have solved all trimming warnings in the Android workload, we
can now go "all in" on trimming.
Early in .NET 6 (maybe even 5?) we "hid" many trimming warnings as we
did not yet plan to solve them:
<SuppressTrimAnalysisWarnings Condition=" '$(SuppressTrimAnalysisWarnings)' == '' ">true</SuppressTrimAnalysisWarnings>
These warnings were not *actionable* at the time for customers, as
many warnings were in `Mono.Android.dll`, `Java.Interop.dll`, etc.
Going forward, let's stop suppressing these warnings if `TrimMode=full`.
We can also enable trimming for new projects:
* `dotnet new android`
* `dotnet new android-wear`
These will have the `TrimMode` property set to `Full` by default:
```xml
<PropertyGroup Condition="'$(Configuration)' == 'Release'">
<TrimMode>full</TrimMode> …
```
=> [One .NET] "greenfield" projects opt into trimming

src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
Context: https://github.com/xamarin/xamarin-android/pull/8790
The old method of satellite assembly counting relied on the 
`RelativePath` MSBuild item metadata, which appears to have gone
missing somewhere in .NET8+.  Update the code to check for presence
of the following metadata, in order given, to determine assembly's
culture, if any:
* `Culture`
* `RelativePath`
* `DestinationSubDirectory`
Failure to count satellite assemblies can, and sometimes will,
result in a segfault since we generate a number of native code
arrays based on the assembly count and the runtime assumes that
what the build told it is true.
=> [NET8] Fix assembly count when satellite assemblies are present

Directory.Build.props
Context: https://github.com/xamarin/xamarin-android/tree/release/9.0.1xx-preview3
We branched for .NET 9 Preview 3 from 4696bf3e into release/9.0.1xx-preview3; the main branch is now .NET 9 Preview 4.
Update xamarin-android/main's version number to 34.99.0-preview.4.
=> $(AndroidPackVersionSuffix)=preview.4; net9 is 34.99.0.preview.4

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Context: https://github.com/xamarin/xamarin-android/security/dependabot/1
Bumps NuGet.Packaging and related packages from version 6.7.0 to 6.7.1
to address a security issue.
=> [Xamarin.Android.Build.Tasks] Bump to NuGet 6.7.1

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Javac.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Tasks/Generator.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildOutput.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetXamarinProject.cs, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Fixes https://github.com/xamarin/xamarin-android/issues/8658
Fixes https://github.com/xamarin/xamarin-android/issues/8698
The PR fixes an issue where the bindings files in intermediate `generated` folder get deleted on subsequent builds. This causes the entire binding process to run again, slowing down builds. 
The root fo the problem is the `_ClearGeneratedManagedBindings` target. It was designed to clean out the `generated` folder in the case where no binding libraries were present. However it turns out if was running during a design time build! During design time builds the binding library item groups are not evaludated, so the `_ClearGeneratedManagedBindings` would run.. deleting everything. 
To fix this issue we only run the `_ClearGeneratedManagedBindings` in a standard build. The …
=> Add test for Binding Projects Incremental Build

build-tools/automation/azure-pipelines-nightly.yaml
I've configured a new [managed identity][0] (MSI) for API Scan, which
allows us to enable a more modern authentication approach when running
API Scan on the `MAUI-1ESPT` agent pool.
A new `$(ApiScanMAUI1ESPTManagedId)` variable has been configured in the
pipeline settings to pass the app ID for this MSI to the API Scan task.
[0]: https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/cd4829e2-e38b-43d2-8316-2f2009f36f97/resourcegroups/1esobjects/providers/microsoft.managedidentity/userassignedidentities/maui1esptapiscanidentity/overview
=> [ci] Use managed identity for ApiScan

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Javac.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Tasks/Generator.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildOutput.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetXamarinProject.cs, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Backport of: https://github.com/xamarin/xamarin-android/pull/8706
Fixes: https://github.com/xamarin/xamarin-android/issues/8658
Fixes: https://github.com/xamarin/xamarin-android/issues/8698
Design-time builds don't play nicely with binding project builds:
% dotnet new androidlib
% cat > Example.java <<EOF
package e;
public class Example {
public static void e() {
}
}
EOF
% dotnet build -p:DesignTimeBuild=true -v:diag
After this initial Design-Time build, we have the following generated source code for the binding:
% find obj -iname \*.cs | xargs ls -l
-rw-r--r--  1 user staff   197 Mar 25 19:22 obj/Debug/net8.0-android/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
-rw-r--r--  1 user staff   441 Mar 25 19:22 obj/Debug/net8.0-android/__Microsoft.Android.Resource.Designer.cs
-rw-r--r--  1 …
=> [release/8.0.2xx] [Xamarin.Android.Build.Tasks] DTBs should not rm generator output

eng/Versions.props
Context: https://github.com/xamarin/xamarin-android/blob/2ff1a5f67d6da4ebac507a1b248809388f23e7c7/eng/Versions.props#L15
As we moved to the .NET 8.0.200 SDK, we inadvertently changed the version band of the Android workload:
Microsoft.NET.Sdk.Android.Manifest-8.0.200
This would prevent 8.0.100 .NET SDKs from using the latest Android workload.
Pin `$(DotNetAndroidManifestVersionBand)` to 8.0.100 to fix this.
=> [release/8.0.2xx] [build] keep $(DotNetAndroidManifestVersionBand) on 8.0.100

Directory.Build.props, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Update `NuGet.ProjectModel` to the latest version.  This new version requires a newer version of `Newtonsoft.Json`, so update to the latest of it as well.
Remove unneeded NuGet PackageReferences.
=> Bump 'NuGet.*' and 'Newtonsoft.Json' NuGet versions.

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
`ILRepack` has a new (Microsoft) maintainer who is working on modernizing it.  This includes updating to a newer version of `Mono.Cecil` which supports `portable` and `embedded` debug symbols:
https://github.com/gluck/il-repack/pull/333
Updating to the latest version should fix our issue about being unable to debug `Xamarin.Android.Build.Tasks` or get full stack traces.
=> [Xamarin.Android.Build.Tasks] Update to newer ILRepack which supports debug files.

.external
Changes: https://github.com/xamarin/monodroid/compare/77124dc16985a92077e62b0cfeaeb007c4d4fd2a...fefc158ef36d056249e8775df4e5d409a70119e2
* xamarin/monodroid@fefc158ef: Bump external/android-sdk-installer from `c3daec9` to `852ad3f`
* xamarin/monodroid@809228010: Bump tools/msbuild/external/androidtools from `863a2cb` to `683b844`
* xamarin/monodroid@3f9d1b502: Bump external/xamarin-android from `9f548d5` to `378b492`
* xamarin/monodroid@20cacb191: Bump external/xamarin-android from `4d1fca7` to `9f548d5`
* xamarin/monodroid@db24ae03d: Bump tools/msbuild/external/androidtools from `7818dc5` to `863a2cb`
* xamarin/monodroid@98cf75626: Bump external/android-sdk-installer from `438cf89` to `c3daec9`
=> Bump to xamarin/monodroid@fefc158ef3

THIRD-PARTY-NOTICES.TXT, build-tools/xaprepare/xaprepare/ThirdPartyNotices/xxHash.cs
Context: 0db28d3ff2f9852005eddbfc6ff8c9227f1a5474
0db28d3 added two new submodules and included their licenses directly in the `THIRD-PARTY-NOTICES.txt` file, but it failed to update the relevant `xaprepare` TPN generation code.  In effect, each local build would produce changes to `THIRD-PARTY-NOTICES.txt` file.
Update `xaprepare` to include licenses for the submodules added by 0db28d3
=> Update THIRD-PARTY-NOTICES.txt generation code

build-tools/installers/unix-binutils.projitems, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
Bumps LLVM to v18.1.3 and XA utils version to 8.0.0
Changes: https://discourse.llvm.org/t/llvm-18-1-0-released/77448
Changes: https://discourse.llvm.org/t/llvm-18-1-1-released/77540
Changes: https://discourse.llvm.org/t/18-1-2-released/77821
Changes: https://discourse.llvm.org/t/18-1-3-released/78136
Changes interesting for us:
* AArch64 backend
* Added support for Cortex-A520, Cortex-A720 and Cortex-X4 CPUs.
* Assembler/disassembler support has been added for 2023 architecture extensions.
* Support has been added for Stack Clash Protection. During function frame creation
and dynamic stack allocations, the compiler will issue memory accesses at regular
intervals so that a guard area at the top of the stack can’t be skipped over.
* x86 backend
* The i128 type now matches GCC and clang’s …
=> Bumps LLVM to v18.1.3 and XA utils version to 8.0.0

.external
Changes: https://github.com/xamarin/monodroid/compare/7edfb4a9c1daa49216d193db6aa8b986483cf5fa...d627218f1e1d0c1e501e2cc36609deb0b09d30aa
* xamarin/monodroid@d627218f1: Bump to xamarin/android-sdk-installer/release/8.0.1xx@a6a2702a (xamarin/monodroid#1453)
Update the `InstallAndroidDependencies` target to use the `ANDROID_HOME` environment variable by default, if set:
% export ANDROID_HOME=path/to/android/sdk
% dotnet build -t:InstallAndroidDependencies -f:net8.0-android \
-p:JavaSdkDirectory="<JavaSdkPath>" \
-p:AcceptAndroidSDKLicenses=True
=> Bump to xamarin/monodroid/release/8.0.1xx@d627218f1

.github/dependabot.yml
Updates the list of submodules that dependabot ignores when checking for updates.  Repos which are no longer valid have been removed and recently added xxhash repos have been added to this list.
=> [ci] Update dependabot ignore list

src/Mono.Android/PublicAPI/API-35/PublicAPI.Unshipped.txt
Create a copy of the API-34 `PublicAPI.*` comparison files for API-35.  Doing this before we commit API-35 ensures that we will have a "shipped" baseline to compare against, so that any potential changes caused by API-35 will be surfaced in the PR diff.
Note these files are not consumed yet.  They will be consumed when API-35 is committed.
=> [Mono.Android] Commit baseline PublicAPI files for API-35.

build-tools/automation/azure-pipelines-apidocs.yaml, build-tools/automation/yaml-templates/build-linux.yaml, build-tools/automation/yaml-templates/commercial-build.yaml, build-tools/automation/yaml-templates/install-microbuild-tooling.yaml
The `NuGetAuthenticate@0` task is deprecated and will soon be removed:
Task 'NuGet authenticate' version 0 (NuGetAuthenticate@0) is deprecated.
This task will be removed. From January 31, 2024, onwards it may no longer be available.
Use the updated `NuGetAuthenticate@1` task instead.
=> [ci] Use NuGetAuthenticate@1 (#8676)

src/Microsoft.Android.Sdk.ILLink/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx
Context: https://dotnet.microsoft.com/platform/support/policy/xamarin
Context: ab3773cf439ab620934b04e1bd01f0d9cf61a6ae
Support for Xamarin.Android ends on 2024-May-1.
Update error and warning messages to minimize use of "Xamarin".
Remaining messages which contain "xamarin" are:
* XA0030: Building with JDK version `{0}` is not supported. Please install JDK version `{1}`. See https://aka.ms/xamarin/jdk9-errors
* XA1005: If basic type name matching fails, please add a `xamarin:managedType` attribute to the element to specify the fully qualified managed type name of the element
XA0030 Should Not Happen with .NET 6+, as JDK 11+ is required. XA0030 is thus moot.
XA1005 is related to Layout Code Behind (ab3773cf), and replacing `xamarin` would (1) be a source breaking change (so we can't …
=> [Xamarin.Android.Build.Tasks] Remove "Xamarin" from messages

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, src/Mono.Android/Profiles/api-VanillaIceCream.params.txt, src/Mono.Android/PublicAPI/API-35/PublicAPI.Unshipped.txt
Context: https://developer.android.com/about/versions/15
Context: https://android-developers.googleblog.com/2024/04/the-first-beta-of-android-15.html
Android 15 Beta 1 has been released.  The Android 15
* Feb/Mar: Developer Previews
* April/May: Unstable Betas
* June/July: Stable Betas
* ???: Final
This will be usable in its preview form to .NET 9 Preview users who explicitly target `net9.0-android35`.
`PublicApiAnalyzers` reports 1 API change (`PublicAPI.Shipped.txt`):
- NRT attribute changes (`!` -> `?`)
[0]: https://developer.android.com/about/versions/15/overview
=> [Mono.Android] Bind API-35 Beta 1.

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
Changes: https://discourse.llvm.org/t/18-1-4-released/78430
There isn't anything directly interesting for us in this release. 
Simply tracking the current version of the toolchain.
=> Bump to binutils based on LLVM 18.1.4

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
=> Remove MonoArchive_BaseUri from Configurables.cs

Directory.Build.props
Context: https://github.com/xamarin/xamarin-android/tree/release/9.0.1xx-preview4
We branched for .NET 9 Preview 4 from b30285f2 into release/9.0.1xx-preview4; the main branch is now .NET 9 Preview 5.
Update xamarin-android/main's version number to 34.99.0-preview.5.
=> $(AndroidPackVersionSuffix)=preview.5; net9 is 34.99.0.preview.5

.gitmodules
Changes: https://github.com/xamarin/xamarin-android-tools/compare/d3e7284851da69d0aef293614e7b2dfc5f43b3b8...d50747cbddf6ab3e2151fc2ae3e3af76edb4fd72
* xamarin/xamarin-android-tools@d50747c: Check for ANDROID_HOME Sdk location on Windows. (xamarin/xamarin-android-tools#230)
=> Bump to xamarin/xamarin-android-tools/release/8.0.1xx@d50747cb

Configuration.props
Context: https://github.com/xamarin/xamarin-android/releases/tag/34.0.95
Changes: https://github.com/xamarin/xamarin-android/compare/87e4a6d890397c13b2572ce01d4b57874ecef9b0...0d97e20b84d8e87c3502469ee395805907905fe3
=> Bump $(AndroidNetPreviousVersion) to 34.0.95

src/Mono.Android/Java.Lang/Thread.cs
Fixes: https://github.com/dotnet/maui/issues/18757
Context: https://github.com/dotnet/maui/pull/22007
Context: https://cs.android.com/android/platform/superproject/+/main:frameworks/base/core/java/android/view/View.java;l=19612
If you do something like:
new View(myContext).Post(() => {
// do something
});
If the `View` is never added to the `Window` (`IsAttachedToWindow` is false), the `Runnable` will never be executed, with data stored in this dictionary:
static Dictionary<Action, RunnableImplementor> instances = new Dictionary<Action, RunnableImplementor> ();
This is a problem if the `Action`:
* Is an instance method, will cause the `Action.Target` to live forever
* Is an anonymous method with captured variables, will cause the captured variables to live forever
I could observe this …
=> [Mono.Android] fix potential leak in Java.Lang.Thread

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildWithLibraryTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
Fixes: https://github.com/dotnet/maui/issues/18819
The sample creates a problem such as:
* Create a .NET Maui 8 class library with a base class inheriting from Java.Lang.Object: `MauiLib1`
* `BaseClass` * `DerivedClass1` : No error when creating an instance
* Create a .NET Maui 8 mobile app with a derived class of the base class in step 1: `MauiApp1`
* `DerivedClass2` : No error when creating an instance
* Create a .Net Maui 8 class library with a derived class of the base class in step 1: `MauiLib2` * `DerivedClass3` * Create an instance of all 3 derived class in mobile app in step 2. * `NotSupportedException` creating `DerivedClass3`
```
Only System.NotSupportedException Message=Cannot create instance of type 'MauiLib2.DerivedClass3': no Java peer type found.
at …
```
=> [Xamarin.Android.Build.Tasks] fix detection of "Android libraries"

.external, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Changes https://github.com/xamarin/monodroid/compare/a5742221b314864636f4356173a2535a539c7b2c...9ca6d9f64fce11f04d668ece50ada36de1d7efce.
Context: http://github.com/xamarin/xamarin-android/commit/86260ed36dfe1a90c8ed6a2bb1cd0607d637f403
Context: https://github.com/xamarin/xamarin-android/pull/8478
Context: https://github.com/xamarin/xamarin-android/pull/8895
Commit https://github.com/xamarin/xamarin-android/commit/86260ed3 altered packaging so that
*all* assemblies were considered to be ABI-specific, removing even
the *idea* of "CPU-agnostic assemblies".
This had unforeseen breakage: localization-specific `.resx` & related
files were no longer fast deployed to the correct location, breaking
*all* of our localization unit tests.
This wasn't found in …
=> Test fixlocalizationtests branch

.external
Changes: https://github.com/xamarin/monodroid/compare/d627218f1e1d0c1e501e2cc36609deb0b09d30aa...21aed734165ab0ea8bcaa1f4151bf13654153327
* xamarin/monodroid@21aed7341: Bump to xamarin/androidtools/release/8.0.1xx@5b93b9e7 (xamarin/monodroid#1470)
* xamarin/monodroid@cb085d420: Bump to xamarin-android/release/8.0.2xx@183b7f76 (xamarin/monodroid#1471)
* xamarin/monodroid@792168d45: Remove "Xamarin" from messages (#1468) (xamarin/monodroid#1469)
=> Bump to xamarin/monodroid/release/8.0.1xx@21aed734

build-tools/api-merge/ApiDescription.cs
Our process of building `Mono.Android.dll`'s `api.xml` using `api-merge` does not take into account that API could be removed from `android.jar`.
Track API removals by adding a `removed-since="XX"` attribute to API that no longer exists.
Note this information is not currently consumed anywhere, but having this data will allow us to determine if we want to make modifications to handle it in future PRs.  Potentially [`[UnsupportedOSPlatformAttribute]`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.versioning.unsupportedosplatformattribute?view=net-8.0) is a good solution for this.
=> [api-merge] Add `removed-since` info.

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
Changes: https://github.com/android/ndk/wiki/Changelog-r26#r26d
The release appears to contain a single bugfix for ndk-gdb/ndk-lldb
which doesn't affect us.  Toolchain version is unchanged.
=> Bump NDK to r26d

src/Mono.Android/Android.OS/Handler.cs, src/Mono.Android/Android.Views/View.cs
Context: 3ce27c9f507cbc96cfeeae76b29cf83b1e5e6e25
Commit 3ce27c9f had a TODO:
> TODO: Address [^0] and dispose of the `RunnableImplementor` instance
> when `View.Post()` returns `false`.
>
> [^0]: we leak if `View.post(Runnable)` returns *false*.
The time is now!  Review all `new RunnableImplementor(…, true)` calls, and if a "removable" `RunnableImplementor` is passed to a method which can return an error such as [`Handler.post()`][0] or [`View.post()`][1], dispose of the `RunnableImplementor` instance on error.
[0]: https://developer.android.com/reference/android/os/Handler#post(java.lang.Runnable)
[1]: https://developer.android.com/reference/android/view/View#post(java.lang.Runnable)
=> [Mono.Android] Dispose of the `RunnableImplementor` on error

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
On 2024-May-01, xamarin/monodroid-samples was updated so that the `main` branch no longer contained samples for Classic Xamarin.Android. This in turn meant the removal of the ActionBarSherlock sample.
This change in turn broke xamarin-android unit tests, which attempt to download this URL, which no longer exists:
* <https://github.com/xamarin/monodroid-samples/blob/main/ActionBarSherlock/ActionBarSherlock/Jars/ActionBarSherlock-4.3.1.zip?raw=true>
Oops.
As part of the removal of Classic Xamarin.Android samples, a new `monodroid-samples/archived-xamarin` branch was created, which is the state of the `main` branch before all old samples were removed.
Update the `BindingBuildTest.RemoveEventHandlerResolution()` integration test to use the correct URL for ActionBarSherlock.
=> [Xamarin.Android.Build.Tests] Fix ActionBarSherlock URL

src/Microsoft.Android.Sdk.ILLink/PreserveApplications.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocumentElement.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/8914
Fixes: https://github.com/xamarin/xamarin-android/issues/7301
Using a custom application with `TrimMode=full`:
[Application]
public class CustomApp : Application
{
public CustomApp(IntPtr h, JniHandleOwnership o) : base(h, o) { }
}
Fails with:
ILLink : error IL1012: IL Trimmer has encountered an unexpected error. Please report the issue at https://aka.ms/report-illink
Fatal error in IL Linker
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
at System.Linq.ThrowHelper.ThrowNoMatchException()
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
at MonoDroid.Tuner.PreserveApplications.PreserveTypeProperty(CustomAttribute attribute, String property) in …
=> [trimming] fix custom applications for `TrimMode=full`

Configuration.props
Changes: https://github.com/xamarin/xamarin-android/compare/34.0.95...96b6bb65e8736e45180905177aa343f0e1854ea3
* Bump to dotnet/runtime@fd8f5b5af7 8.0.4
* Bump to dotnet/installer@5b9983e91a 8.0.204-servicing.24169.39
* [ci] Migrate to the 1ES template
* [Xamarin.Android.Build.Tasks] Remove "Xamarin" from messages
* [Xamarin.Android.Build.Tasks] fix detection of "Android libraries"
* [Mono.Android] fix potential leak of RunnableImplementors
* Bump binutils to 17.0.6-7.2.2
* [Xamarin.Android.Build.Tasks] set %(DefineConstantsOnly) for older API levels
=> [build] bump to `$(AndroidNetPreviousVersion)` 34.0.113

build-tools/automation/azure-pipelines.yaml, build-tools/create-packs/Directory.Build.targets, eng/Version.Details.xml, eng/Versions.props
Context: https://github.com/dotnet/arcade/blob/efc3da96e5ac110513e92ebd9ef87c73f44d8540/Documentation/DependencyFlowOnboardingWithoutArcade.md
The steps used to publish build asset information to maestro have been
updated.
With the new `PushToAzureDevOpsArtifacts` task the build pipeline should
now create all of the artifacts required for maestro artifact publishing.
The `add-build-to-channel` darc command will now trigger a
[Build Promotion Pipeline][0] that pushes build assets to the feed that
corresponds to the maestro channel that is being updated.  We should 
no longer need to push assets to various NuGet feeds in a separate step. 
[0]: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=9577012&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=c7a8693b-2f9c-5ea8-c909-cde9405a …
=> [ci] Improve maestro artifact publishing

build-tools/automation/azure-pipelines.yaml
Commit bbac9fe4ce hit some issues when attempting to publish to maestro via the [Build Promotion Pipeline][0]:
error : Asset 'D:\a\_work\1\a\7dc04dfe-406a-4fa3-aea0-199acc2763fa\MergedManifest.xml' already exists with different contents
We can continue to push to the dotnet feeds ourselves for now while this issue is fixed.
[0]: https://dev.azure.com/devdiv/DevDiv/_build?definitionId=12603&_a=summary
=> [ci] Re-enable to push to dotnet9 feed

eng/Version.Details.xml, eng/Versions.props
Context: https://github.com/dotnet/installer/pull/19707
Changes: https://github.com/dotnet/installer/compare/fa261b95...1741345c
Changes: https://github.com/dotnet/runtime/compare/4326eb7e...84b33395
Changes: https://github.com/dotnet/cecil/compare/4abe3e63...7a4a59f9
dotnet/installer is no longer producing a `Microsoft.Dotnet.Sdk.Internal` "package" for the SDK. This is causing the maestro code-flow to fail, such as:
> darc update-dependencies --id 225276
Looking up build with BAR id 225276
Using 'Strict' coherency mode. If this fails, a second attempt utilizing 'Legacy' Coherency mode will be made.
Found no dependencies to update.
We use `Microsoft.Dotnet.Sdk.Internal` to provision the .NET SDK, similar to:
./dotnet-install.sh --version …
=> [build] fix code-flow from dotnet/installer, .NET 9.0.100-preview.5.24262.2

src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs, tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidMessageHandlerTests.cs
For some reason we skipped 308 (https://learn.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=net-8.0#system-net-httpstatuscode-permanentredirect) in AndroidMessageHandler. This PR adds support for this redirect status code.
Fixes #8946 
/cc @grendello
=> [Mono.Android] AndroidMessageHandler should follow 308: permanent redirect

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
Changes: https://discourse.llvm.org/t/18-1-5-released/78740
Changes: https://discourse.llvm.org/t/18-1-6-released/79068
There are no changes in the above announcements that are important to us. Simply tracking the latest LLVM 18 version.
There are no more planned 18.1.x releases, but there could be one if a critical issue is found.
=> Bump LLVM to 18.1.6

src/Microsoft.Android.Templates/android-bindinglib/.template.config/localize/templatestrings.tr.json, src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.tr.json, src/Microsoft.Android.Templates/android/.template.config/localize/templatestrings.tr.json, src/Microsoft.Android.Templates/androidlib/.template.config/localize/templatestrings.tr.json, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 9615978

.external, Documentation/docs-mobile/building-apps/build-properties.md, build-tools/automation/azure-pipelines.yaml, src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildWithLibraryTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownProperties.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs, tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs, tests/MSBuildDeviceIntegration/Tests/MonoAndroidExportTest.cs
Context https://github.com/xamarin/monodroid/pull/1481
Context https://github.com/xamarin/xamarin-android/issues/2730
Bump monodroid to bring in the following changes. 
Changes https://github.com/xamarin/monodroid/compare/9ca6d9f64fce11f04d668ece50ada36de1d7efce...93ab95e18077d56d9d55ce7b4069a534e2dea35e.
The biggest of these changes is the removal of Enhanced Fast Deplyment. This change removes the ability to side load `.dex`, `.so` and resources in the same directory as we sideload assemblies. This feature was always hard to maintain as it used a bunch of android API's which are deprecated or have very little documentation. It also did not work for `Application` subcalsses. This restriction alone makes it impossible to use this feature with Maui. 
Given its maintainance issues and the …
=> Remove Enhanced Fast Deployment

build-tools/xaprepare/xaprepare/Steps/Step_CopyExtraResultFilesForCI.cs
Context: a7b576885624d09c4cc9d65412da2a7558fd3b36
Context: a0b7aadec4fbcc6e7d6463f8a3982963db03ed17
Ever since commit a0b7aade, the **Prepare .NET Release** > **Push Internal** job has been failing:
Step Xamarin.Android.Prepare.Step_CopyExtraResultFilesForCI failed: Could not find a part of the path 'D:\a\_work\1\s\src\monodroid\jni'.
System.InvalidOperationException: Step Xamarin.Android.Prepare.Step_CopyExtraResultFilesForCI failed: Could not find a part of the path 'D:\a\_work\1\s\src\monodroid\jni'.
---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\a\_work\1\s\src\monodroid\jni'.
at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
at System.IO.Enumeration.FileSystemEnumerator`1.Init()
at …
=> [ci] Update path for generated `*.include.*` files

Directory.Build.props
Context: https://github.com/xamarin/xamarin-android/tree/release/9.0.1xx-preview5
We branched for .NET 9 Preview 5 from https://github.com/xamarin/xamarin-android/commit/c61174316fcb69959fc8731964edbf2e7df7d726 into release/9.0.1xx-preview5;
the main branch is now .NET 9 Preview 6.
Update xamarin-android/main's version number to 34.99.0-preview.6.
=> $(AndroidPackVersionSuffix)=preview.6; net9 is 34.99.0.preview.6

build-tools/automation/azure-pipelines.yaml
We've been running into issues with the `AzureFileCopy` task on the
MicroBuild pool, which will hopefully be resolved by using a different
image:
Failed to perform Auto-login: 'Get-AzAccessToken' command was found in the module 'Az.Accounts', but the module could not be loaded.
=> [ci] Run "Push Internal" job on AzurePipelines-EO pool

.github/ISSUE_TEMPLATE/01-building-an-application.yml, .github/ISSUE_TEMPLATE/02-running-an-application.yml, .github/ISSUE_TEMPLATE/03-mono-android-api.yml, .github/ISSUE_TEMPLATE/04-binding-a-java-library.yml, .github/ISSUE_TEMPLATE/05-other.yml
Update GH issue templates, removing EOL Classic and .NET 7.
=> [GitHub] Keep GH issue templates up to date.

Configuration.props, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.MacOS.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_AndroidTestDependencies.cs, build-tools/xaprepare/xaprepare/Scenarios/Scenario_Standard.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallAdoptOpenJDK.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Directory.Build.targets, src/manifestmerger/manifestmerger.targets, src/r8/r8.targets
Removes JDK 8 provisioning logic as it appears to not be needed.
The version of JDK 17 that is installed has been bumped to 17.0.11, and
aarch64 packages will now be used on macOS when applicable.
=> [build] Do not provision JDK 8

src/Microsoft.Android.Templates/android-wear/.template.config/localize/templatestrings.en.json
Context: https://github.com/xamarin/xamarin-android/commit/328644ac84170d4fb1e3ac2be6a42509170047f3
Adds the updated english templatestrings.json produced when building
locally, to ensure the latest strings are available for translation.
=> [templates] Update Wear OS en template string

src/Mono.Android/map.csv, tests/api-compatibility/acceptable-breakages-vReference-net9.0.txt
Fixes: https://github.com/xamarin/xamarin-android/issues/9000
Context: https://github.com/xamarin/xamarin-android/commit/3ca2a07ae859aa68cd97ea2c310a2ce62f952e24
The constant `android/app/ApplicationExitInfo.REASON_OTHER` was enumified against API-30 DP2 with a value of `10`.  Android developer previews are not stable and this value was [changed](https://developer.android.com/sdk/api_diff/r-dp3-incr/changes/android.app.ApplicationExitInfo) to `13` in API-30 DP3.  However, we did not update the enum value.
This process has been mitigated since, as we no longer enumify unstable API levels.  We wait until Google marks the API as "stable" before we perform enumification.
Update the enum to the correct value so it will be correct in .NET 9+.
=> [Mono.Android] Fix incorrect value for enum `ApplicationExitInfoReason.Other`.

build-tools/api-merge/ApiDescription.cs, src/Mono.Android/metadata
Context: https://github.com/xamarin/xamarin-android/issues/9000
In https://github.com/xamarin/xamarin-android/issues/9000, we learned that:
- Constant values can change between Android API levels
- `api-merge` does not update constant values in the final `api.xml` if they do change
Update `api-merge` to update constant values if they change, and update `api-VanillaIceCream.xml` with the new `api-merge` logic.
=> [api-merge] Update "constant" values if they change between API levels.

.external, Xamarin.Android.code-workspace, build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml, build-tools/automation/yaml-templates/stage-msbuild-tests.yaml, src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/DeviceTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Commit https://github.com/xamarin/monodroid/commit/c6aae9e5a154cfbf2c3a94e046fa2c747c3b82e2 removed the restriction for using .aab files during fast deployment. 
While using an .aab will still be slower that using an .apk it should still speed up the development process for those using things like asset packs. 
The reason it is slower is becasue the .aab file has to go through `bundle-tool` to be packaged and installed. This is a slow process. The .apk is much faster as we work with it directly. 
Numerous unit tests have been updated to test fast deployment when using .aab files. As a result we have had to increase the number of CI bots we use so we can spread out the new tests amonst more machines.
=> Make fast deployment work with aab files

.github/workflows/sdk-insertion-bump.yml
Fixes the sdk-insertion-bump workflow to pass updated repo information.
The trigger has also been disabled for now, though it can still be ran
manually via the workflow_dispatch event.
=> [ci] Update sdk-insertions trigger

build-tools/automation/azure-pipelines.yaml
Other test jobs use `s/` or `s/xamarin-android` as a checkout path.
=> [ci] Fix android source path for MAUI test job

build-tools/automation/azure-pipelines-nightly.yaml
The main build scripts prefer a checkout path of `s/xamarin-android`,
and the nightly job should do the same (at least for now).
=> [ci] Update checkout path for nightly build

tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidClientHandlerTests.cs
A handful of tests started failing after the org move:
Xamarin.Android.NetTests.AndroidHandlerTestBase.Redirect_POST_With_Content_Works
Invalid redirected URI
Expected: https://github.com/xamarin/xamarin-android
But was:  https://github.com/dotnet/android
Fix these by using the new repo URL.
=> [Mono.Android-Tests] Fix repo URL in redirect tests

src/Xamarin.Android.Build.Tasks/Tasks/LinkApplicationSharedLibraries.cs
This is just for parity with what `clang` uses, it will align the `libxamarin-app.so` 
library to a more natural boundary of 4k bytes (size of a memory page on Android)
Without the flag, the shared library is aligned to 64k bytes, which is wasteful with
regards to consumed memory (not much, but still) and may also make memory access slightly
slower than necessary.
=> [runtime] Explicitly align application shared library to page size

src/Xamarin.Android.Build.Tasks/Resources/proguard_xamarin.cfg
In dotnet/runtime we are adding a few more Java classes to assist with .NET crypto. One was added in https://github.com/dotnet/runtime/pull/103016, and another may be added in https://github.com/dotnet/runtime/pull/103337.
This PR changes ProGuard to keep all of the classes in this package rather than individually adding them. If we prefer to keep them individually, I can change the PR to do that, too.
/cc @simonrozsival
=> Keep all .NET runtime classes

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Tasks/AndroidZipAlign.cs, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkApplicationSharedLibraries.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/EnvironmentHelper.cs, src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfig.cs, src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/native/CMakeLists.txt, src/native/monodroid/embedded-assemblies-zip.cc, src/native/xamarin-app-stub/application_dso_stub.cc, src/native/xamarin-app-stub/xamarin-app.hh
Context: https://github.com/dotnet/android/wiki/Android-support-for-devices-with-16k-pages
Context: https://github.com/dotnet/android/pull/9020
Starting sometime next year Google will require all packages submitted
to the Play Store to be aligned to 16 bytes, in order to support Android
devices which use 16kb pages instead of the currently supported 4kb
ones.  The requirement also applies to native shared libaries (`.so`),
which need to be linked so that their loaded sections are aligned to
16kb as well.
This commit implements changes which make the alignment configurable,
while still defaulting to 4kb alignment.  The #9020 PR will enable (when
NDK r27 is released) building of our runtime shared libraries with 16kb
alignment.  While strictly speaking NDK r27 is not necessary to enable …
=> Make APK and shared library alignment configurable

Directory.Build.props
Context: https://github.com/xamarin/xamarin-android/tree/release/9.0.1xx-preview6
We branched for .NET 9 Preview 6 from ddb215b into release/9.0.1xx-preview6; the main branch is now .NET 9 Preview 7.
Update xamarin-android/main's version number to 34.99.0-preview.7.
=> $(AndroidPackVersionSuffix)=preview.7; net9 is 34.99.0.preview.7

build-tools/create-packs/License.targets, build-tools/debian-metadata/control, build-tools/scripts/XAVersionInfo.targets, build-tools/xaprepare/xaprepare/Application/GeneratedSourceLinkJsonFile.cs, tools/relnote-gen/App.cs, tools/relnote-gen/README.md
I tried to fix places that would show up in user-facing places like the `Version.commit`, SourceLink, etc. Or places that make web requests using this URL.
There are still many links in `.md` files or code comments, but those should redirect appropriately.
=> Fix places still pointing to xamarin/xamarin-android

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Resource.Designer.targets
Fixes #8581
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2051915
Context
* https://github.com/dotnet/project-system/blob/dd9431b535a6158060d7ab64597276eb2c354aab/docs/design-time-builds.md#targets-that-run-during-design-time-builds
* https://github.com/dotnet/project-system/blob/dd9431b535a6158060d7ab64597276eb2c354aab/docs/up-to-date-check.md#default-inputs-and-outputs
* https://github.com/dotnet/project-system/blob/dd9431b535a6158060d7ab64597276eb2c354aab/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets#L448-L449
The Visual Studio FastUpdate check flags the Resource Designer assembly as
newer than the output assembly (which it is). But it causes it to incorrectly
think the build is out of date.
``` …
```
=> Support Visual Studio "Build Acceleration"

.external, Directory.Build.props
Changes: https://github.com/dotnet/android-libzipsharp/compare/3.1.1...3.3.0
* https://github.com/dotnet/android-libzipsharp/commit/de57dcc: Add xml comments. Centralize the dotnet target framework (https://github.com/dotnet/android-libzipsharp/pull/143)
* https://github.com/dotnet/android-libzipsharp/commit/b541b87: Fix the elusive invalid zip archive issue that has been a problem for ages! (https://github.com/dotnet/android-libzipsharp/pull/142)
* https://github.com/dotnet/android-libzipsharp/commit/c2ae332: Update OneLocBuildToken (https://github.com/dotnet/android-libzipsharp/pull/141)
* https://github.com/dotnet/android-libzipsharp/commit/4fef46a: Bump library versions for the latest upstream releases (https://github.com/dotnet/android-libzipsharp/pull/140)
* …
=> Bump LibZipSharp to 3.3.0

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
Fixes: https://github.com/dotnet/android/issues/9060
This was introduced in 60e983c6 (.NET 6 timeframe).
It is a "private" switch that is no longer recommended.
=> [trimming] remove `$(_AggressiveAttributeTrimming)` by default

.github/policies/resourceManagement.yml
Events declared in this file have not been firing since the dotnet org
migration.  Updating the file should hopefully get things moving again.
=> [ci] Update resourceManagement.yml

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.RuntimeConfig.targets
Context: https://github.com/dotnet/android/issues/9060#issuecomment-2199309388
Context: https://github.com/dotnet/sdk/blob/e18cfb7a09d74952d5e9c2448d31dee313e059bb/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L522-L525
In eb6397d4, we introduced `$(_SystemDiagnosticsMetricsMeterIsSupported)` to avoid a startup time regression with `HttpClient`-related code. At the time, the public property `$(MetricsSupport)` had not been introduced yet in the .NET SDK.
Let's use `$(MetricsSupport)` instead of the private `$(_SystemDiagnosticsMetricsMeterIsSupported)` property.
=> [trimming] use public `$(MetricsSupport)` property

.external, Documentation/guides/MSBuildBestPractices.md, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks.csproj, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunParallelCmds.cs, build-tools/installers/create-installers.targets, build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/Sleep.cs, src-ThirdParty/android-platform-tools-base/SymbolWriter.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs, src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs, src/Xamarin.Android.Build.Tasks/Tasks/CalculateLayoutCodeBehind.cs, src/Xamarin.Android.Build.Tasks/Tasks/CompileNativeAssembly.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateLayoutBindings.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateLibraryResources.cs, src/Xamarin.Android.Build.Tasks/Tasks/GetAotArguments.cs, src/Xamarin.Android.Build.Tasks/Tasks/GetMicrosoftNuGetPackagesMap.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkApplicationSharedLibraries.cs, src/Xamarin.Android.Build.Tasks/Tasks/MavenDownload.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
We've decided to move https://github.com/xamarin/Xamarin.Build.AsyncTask
into xamarin-android-tools as part of dotnet org migration efforts.
Changes: https://github.com/dotnet/android-tools/compare/96745904ec3eeb71ccd178eeeab9a14afebfeb80...3debf8e07ce4a9dd4435d52913203eb93cc9df79
Changes: https://github.com/xamarin/monodroid/compare/e11d9a5af8f00a88d15bd87c777608f17c4ece78...038240c52a7dc2e66b9ad2ddb20b9886836eaec9
=> Use AsyncTask from xamarin-android-tools

Configuration.props, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, build-tools/xaprepare/xaprepare/Steps/Step_Get_Android_BuildTools.cs, src/aapt2/aapt2.targets
Context: https://developer.android.com/tools/releases/build-tools
Update `$(XABuildToolsVersion)` to 35, which is the latest version of the Android SDK Build Tools.
Does it build™?
=> [build] Bump `$(XABuildToolsVersion)`=35

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
Context: https://github.com/dotnet/runtime/pull/103970
Context: https://github.com/dotnet/android/pull/9062#discussion_r1659183391
This setting was removed in dotnet/runtime#103970, so it doesn't do anything.
=> [trimming] remove `$(NullabilityInfoContextSupport)`

Directory.Build.props, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
Context: https://github.com/dotnet/android/pull/9043
While attempting to mark API-35 stable, we hit this error running all of the in-tree Windows smoke tests on CI:
```
D:\a\_work\1\s\bin\Release\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.0-ci.pr.gh9043.6\tools\
Xamarin.Android.Bindings.JavaDependencyVerification.targets(22,5): error MSB4062: The 
"Xamarin.Android.Tasks.GetMicrosoftNuGetPackagesMap" task could not be loaded from the assembly 
D:\a\_work\1\s\bin\Release\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.0-
ci.pr.gh9043.6\tools\Xamarin.Android.Build.Tasks.dll. Could not load file or assembly 'Mono.Cecil, Version=0.11.4.0, 
Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'. The system cannot find the file specified. Confirm that the 
<UsingTask> declaration is correct, …
```
=> Bump `Mono.Cecil.dll` to `0.11.5`.

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/MainActivity.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/DotNet/MainActivity.cs
One change we need in the Android workload is to make sure that
trimmer warnings are displayed if a project sets `$(IsAotCompatible)`.
Customers would likely want this set for all platforms if they are
using NativeAOT on iOS or MacCatalyst.
I also wrote a test with somewhat complicated parameters to verify
we get warnings.
First, I can create a warning for both `IL2055` and `IL3050`:
// Member field
Type type = typeof (List<>);
// ...
// Later in OnCreate
Console.WriteLine (type.MakeGenericType (typeof (object)));
The combinations of tests are:
| Configuration | Property                           | Warning(s)        |
| ------------- | ---------------------------------- | ----------------- |
| Debug         | (defaults)                         | None              |
| Release       | …
=> [tests] verify trimmer warnings where appropriate

src/Xamarin.Android.Build.Tasks/Utilities/XAJavaTypeScanner.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9842772&view=logs&j=9a1c0345-5071-55ee-c0f3-a2911782c698&t=1e33272b-48f7-5132-3788-3179300312b4
We saw an NRE in `XAJavaTypeScanner` in the build linked above:
Microsoft.Android.Sdk.Darwin/34.0.95/tools/Xamarin.Android.Common.targets(1536,3): error XAGJS7001: System.NullReferenceException: Object reference not set to an instance of an object.
Microsoft.Android.Sdk.Darwin/34.0.95/tools/Xamarin.Android.Common.targets(1536,3): error XAGJS7001:    at Xamarin.Android.Tasks.XAJavaTypeScanner.GetJavaTypes(ICollection`1 inputAssemblies, XAAssemblyResolver resolver)
Microsoft.Android.Sdk.Darwin/34.0.95/tools/Xamarin.Android.Common.targets(1536,3): error XAGJS7001:    at …
=> [Xamarin.Android.Build.Tasks] fix NRE in XAJavaTypeScanner

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props
In an email thread, a customer was having trouble using a proguard rule file named `proguard-rules.pro`.
This seems to be a common name for the file, with ~96k results on GitHub:
* https://github.com/search?q=path%3A*proguard-rules.pro&type=Code
=> [Xamarin.Android.Build.Tasks] default wildcard for `proguard-rules.pro`

.gitmodules, src/Mono.Android/Android.Runtime/JNIEnvInit.cs, src/Mono.Android/Java.Interop/TypeManager.cs, tests/Mono.Android-Tests/Java.Interop/JavaObjectExtensionsTests.cs
Fixes: https://github.com/dotnet/android/issues/9038
Changes: https://github.com/dotnet/java-interop/compare/ccafbe6a102a85efe84ceb210b3b8b93e49edbcb...7a058c0ee50d39dc5783d2b2770ea5e0f1001a56
* dotnet/java-interop@7a058c0e: [Java.Interop] Add `IJavaPeerable.JavaAs()` extension method (dotnet/java-interop#1234)
* dotnet/java-interop@6f9defa5: Bump to dotnet/android-tools/main@3debf8e0 (dotnet/java-interop#1236)
* dotnet/java-interop@6923fb89: [ci] Add dependabot branches to build triggers (dotnet/java-interop#1233)
* dotnet/java-interop@573028f3: [ci] Use macOS 13 Ventura build agents (dotnet/java-interop#1235)
dotnet/java-interop@7a058c0e adds a new `IJavaPeerable.JavaAs<T>()`
extension method, to perform type casts which return `null` when
the cast will not succeed instead of throwing …
=> Bump to dotnet/java-interop/main@7a058c0e

src/Mono.Android/Android.Runtime/InputStreamInvoker.cs, src/Mono.Android/Android.Runtime/OutputStreamInvoker.cs, tests/Mono.Android-Tests/Android.Runtime/InputStreamInvokerTest.cs
Context: https://github.com/dotnet/android/issues/9039
Context: https://github.com/dotnet/android/issues/9039#issuecomment-2222830427
Context: 0315e8955cb93190832dc227aafaa90dda57a91a
In dotnet/android#9039, a customer reports that starting with the .NET for Android workload 34.0.113, their app would start crashing with an `ObjectDisposedException`:
ObjectDisposed_ObjectName_Name, Java.IO.InputStreamInvoker
at Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable )
at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
at Java.IO.InputStream.Close()
at Android.Runtime.InputStreamInvoker.Close()
at System.IO.Stream.Dispose()
at System.IO.BufferedStream.Dispose(Boolean )
at System.IO.Stream.Close()
at System.IO.Stream.Dispose() …
=> [Mono.Android] Data sharing and Close() overrides

src/Microsoft.Android.Sdk.ILLink/MarkJavaObjects.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc
Fixes: https://github.com/dotnet/android/issues/8940
Context: https://github.com/TobiasBuchholz/Plugin.Firebase/issues/144
Using the NuGet package:
<PackageReference Include="Plugin.Firebase.CloudMessaging" Version="3.0.0" />
Includes a service:
namespace Plugin.Firebase.CloudMessaging.Platforms.Android;
[Service(Exported = true)]
[IntentFilter(new[] { "com.google.firebase.MESSAGING_EVENT" })]
public class MyFirebaseMessagingService : FirebaseMessagingService
Unfortunately, using `TrimMode=full` completely trims away the above service, which is required for push notifications to work.
I could reproduce this problem in a test using the above NuGet package.
To fix this, we can modify `MarkJavaObjects` to preserve types with attributes that implement `Java.Interop.IJniNameProviderAttribute`, …
=> [Microsoft.Android.Sdk.ILLink] preserve types with `IJniNameProviderAttribute`

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs
The "debug" version of the mono archive appears to no longer exist due
to recent storage account changes.  The release bundles are still live,
so we should default to using those even for debug builds.
=> [xaprepare] Always use release mono bundle

tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/BindingTests.cs
Context: https://github.com/dotnet/runtime/issues/103987
dotnet/runtime#103987 was fixed, and we should have the changes in 094bf612.
Let's enable the test again.
=> [tests] re-enable `JavaAbstractMethodTest`

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/commercial-build.yaml
We've been having issues with the signing steps that run doing the macOS
build.  Migration to a new post-build workflow is in progress, however
this will hopefully fix things more quickly and be safer to backport.
=> [ci] Use DotNetCoreCLI to sign macOS files

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
When 60dbcc9f was backported to .NET 8, the accompanying unit test was accidentally targeting .NET 9.
=> [release/8.0.2xx] [tests] fix `InvalidTargetPlatformVersion` for `net8.0`

src/Xamarin.Android.Build.Tasks/Tasks/ReadAndroidManifest.cs
Fixes #6809
We have an issues where if a library manifest contains the following element and the file dos NOT exist in `android-sdk\platforms\android-XX\optional` we get an XA4218 warning.
```xml
<uses-library
android:name="androidx.window.sidecar"
android:required="false" />
```
This is the warning.
```
Warning XA4218: Unable to find //manifest/application/uses-library at path: android-sdk\platforms\android-31\optional\androidx.window.sidecar.jar	obj\Release\120\android\AndroidManifest.xml
```
So the work around this issue if the `required` attribute is NOT `true` we should ignore the warning. If the library is `required` or the `required` attribute is NOT specified we should revert to to the current behavior.
This warnings can come up if people use vendor specific .aar files. The …
=> Missing androidx.window.[extensions|sidecar] warnings

Directory.Build.props, build-tools/automation/azure-pipelines.yaml, build-tools/create-packs/Directory.Build.targets
We've seen the build promotion pipeline fail when trying to publish
stable package versions:
error : Package 'Microsoft.iOS.Ref.net8.0_17.5' has stable version '17.5.8001' but is targeted at a non-isolated feed 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json'
This is because we were not declaring these packages as stable when
building the build asset registry manifest.
Fix this by passing the `$(IsStableBuild)` property to the build asset
manifest creation task. This property needs to be updated manually when
switching to stable package versioning (see commit 4ea5dbb921).
When `$(IsStableBuild)` is set to true, packages will be pushed to an
isolated feed during publishing, such as:
Package Microsoft.Android.Ref.34@34.0.125 (Shipping) should go to …
=> [ci] Fix maestro publishing for stable packages

src/Xamarin.Android.Build.Tasks/Tasks/JavaToolTask.cs
Fixes #9089
Improve the error reporting so we emit mapping information for all the `lp` directories in an error message. 
The previous code only handled the first one, so lets get all of them.
So we go from 
```
Directory 'obj/Debug/net8.0-android/lp/548' is from 'protolitewellknowntypes-18.0.0.aar'.`
```
to 
```
Directory 'obj/Debug/net8.0-android/lp/548' is from 'foo1-18.0.0.aar'.
Directory 'obj/Debug/net8.0-android/lp/59' is from 'foo2-18.0.0.aar'.
```
=> Expand Java directory mapping message to support multiple directories

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs, src-ThirdParty/llvm/verbose_abort.cpp, src/native/CMakePresets.json.in, src/native/monodroid/CMakeLists.txt, src/native/monodroid/embedded-assemblies.hh, src/native/monodroid/monodroid-glue-internal.hh, src/native/monodroid/monodroid-glue.cc, src/native/monodroid/monodroid-tracing.cc, src/native/monodroid/startup-aware-lock.hh, src/native/monodroid/timing-internal.hh, src/native/monodroid/timing.hh, src/native/monodroid/xamarin_getifaddrs.cc, src/native/shared/CMakeLists.txt, src/native/shared/cppcompat.hh, src/native/tracing/native-tracing.cc
Changes: https://github.com/android/ndk/wiki/Changelog-r27
NDK r27 has been released.  The most important change affecting us is that we should start building
all our native libraries with [16k page alignment](https://github.com/android/ndk/wiki/Changelog-r27#announcements),
support for which is already in `main` and will be refined once #9075 is merged.
Notable changes:
* NDK switched to LLVM 18.0.1 as its toolchain
* A RISC-V sysroot (AKA riscv64, or rv64) has been added. It is not supported. It is present to aid bringup for
OS vendors, but it's not yet a supported Android ABI. It will not be built by default.
* Added APP_SUPPORT_FLEXIBLE_PAGE_SIZES for ndk-build and ANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES for CMake. 
* The unsupported libclang, libclang-cpp, libLLVM, and libLTO libraries …
=> Bump to NDK r27

build-tools/create-packs/Directory.Build.targets
After 580166e6 was merged, the `ConfigureLocalWorkload` target was no longer working as some of the structure of the `sdk-manifests` folder has changed.
* We should run the `DeleteExtractedWorkloadPacks` target, as it will delete the `sdk-manifests/workloadset` folder.
Without doing this, the .NET SDK will *always* attempt to use the 34.99.0-preview.6.340 version in the "baseline" manifest.
* We also should put a versioned folder after each manifest directory.
So, for example:
bin\Debug\lib\sdk-manifests\microsoft.net.sdk.android\ -> bin\Debug\lib\sdk-manifests\microsoft.net.sdk.android\35.0.0-preview.x.x\
bin\Debug\lib\sdk-manifests\android.deps.workload\ -> bin\Debug\lib\sdk-manifests\android.deps.workload\0.0.1\
Now with a fresh checkout:
dotnet msbuild -t:Prepare Xamarin.Android.sln …
=> [build] fix `ConfigureLocalWorkload` target

Configuration.props, Directory.Build.props, Documentation/docs-mobile/messages/index.md, Documentation/docs-mobile/messages/xa0141.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Aot.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Tasks/AndroidZipAlign.cs, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Tasks/GetAotArguments.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkApplicationSharedLibraries.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/EnvironmentHelper.cs, src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfig.cs, src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/ELFHelper.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/native/monodroid/embedded-assemblies-zip.cc, src/native/xamarin-app-stub/application_dso_stub.cc, src/native/xamarin-app-stub/xamarin-app.hh
Context: ddb215b762d94801b61b72acc879b2eefe3e9e46
Context: https://github.com/google/bundletool/releases/tag/1.17.0
* ddb215b7 added an field to the `application_config` structure which
specified the mask required to check whether entries in the APK that
we read at run time are properly alignment at the 4k or 16k page
boundary.  This PR removes that code because it's possible that
`bundletool` will change the package alignment **after** our code is
already built.  This would cause a false negative and an abort during
application execution.
Instead, we simply check whether the entry is 4k **or** 16k aligned.
* Bump `bundletool` to 1.17.0, which now defaults to producing
16k-aligned archives.
* Pass required alignment flags to Mono AOT compiler to produce
properly aligned shared libraries. …
=> Refine 16k page alignment support

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/build-linux.yaml, build-tools/automation/yaml-templates/build-macos.yaml, build-tools/automation/yaml-templates/build-windows.yaml
The conditions to disable CodeQL across different jobs and branches do
not appear be working as expected. The 'make prepare-update-mono' step
has been hanging intermittently on macOS, which appears to be due to
CodeQL.
Fix this by disabling CodeQL on this pipeline and only running it against
the nightly build.
=> [ci] Disable CodeQL on CI/PR pipelines

src/Microsoft.Android.Sdk.ILLink/PreserveLists/Mono.Android.xml, src/Mono.Android/Android.OS/AsyncTask.cs, src/Mono.Android/Android.Runtime/XmlPullParserReader.cs, src/Mono.Android/Android.Runtime/XmlReaderPullParser.cs, src/Mono.Android/Java.Lang/Object.cs, src/Mono.Android/metadata
Fixes: https://github.com/dotnet/android/issues/5197
`[Preserve]` still works in some form, as the `ApplyPreserveAttribute` trimmer step will "mark" types it encounters. It unfortuantely, *does not* work if an assembly is deemed to be fully removed, as the `ApplyPreserveAttribute` will not be called for these types.
To better align with the future of .NET, we should remove *our* usage of `[Preserve]`. The only failing result is `Java.Lang.Object.SetHandleOnDeserialized` which can be preserved in `Mono.Android.xml` instead.
In a future PR, we can consider emitting warnings in customer code with `[Preserve]` usage.
=> [trimming] remove our usage of `[Preserve]`

src/native/CMakeLists.txt, src/native/java-interop/CMakeLists.txt, src/native/monodroid/CMakeLists.txt, src/native/pinvoke-override/CMakeLists.txt, src/native/runtime-base/CMakeLists.txt, src/native/shared/CMakeLists.txt, src/native/tracing/CMakeLists.txt
The native runtime is subdivided into a collection of static libraries,
linked into the target shared library based on a set of conditions.
Some static libraries are "private" and aren't copied to packages, but
some are "public" in that they can be shipped in our nugets (when
dynamic runtime linking at app build time is implemented).  At the same
time, we have several build configurations which differ in their build
and link configurations, and especially in whether or not they link
against the shared C++ standard library or not.  In particular, the ASAN
and UBSAN builds require enabling of exceptions, RTTI and linking
against the shared C++ library.
Static component libraries will be built with the same set of
compilation and linking flags, and without modifying their output names
in …
=> [native] Change name of static libraries in some cases

.external, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs
Changes: https://github.com/xamarin/monodroid/compare/038240c52a7dc2e66b9ad2ddb20b9886836eaec9...d1d43ab161bfd493d982f40fd3e49ebfb274a110
=> Bump to xamarin/monodroid@d1d43ab161

src/Xamarin.Android.NUnitLite/Xamarin.Android.NUnitLite.NET.csproj, tests/Mono.Android-Tests/Java.Interop-Tests/Java.Interop-Tests.NET.csproj, tests/Mono.Android-Tests/Mono.Android-Test.Library/Mono.Android-Test.Library.NET.csproj, tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj, tests/TestRunner.Core/TestRunner.Core.NET.csproj, tests/TestRunner.NUnit/TestRunner.NUnit.NET.csproj
There are lots of warnings like:
.\dotnet-local.cmd build .\tests\Mono.Android-Tests\Runtime-Microsoft.Android.Sdk\Mono.Android.NET-Tests.csproj
...
.\tests\Mono.Android-Tests\Java.Interop\JavaConvertTest.cs(134,20):
warning CA1416: This call site is reachable on all platforms. 'Object' is only supported on: 'Android' 21.0 and later.
(https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1416)
...
Build succeeded with 1192 warning(s) in 44.4s
Several APK test projects need to set:
<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
In order to keep the .NET analyzer happy.
After these changes:
Build succeeded with 22 warning(s) in 38.4s
=> [tests] fix 1,170 build warnings

src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android.Runtime/JNIEnvInit.cs, src/native/monodroid/monodroid-glue-internal.hh, src/native/monodroid/monodroid-glue.cc
There is an API < 14 code path, that seems like we can just *remove* and tread all local refs as indirect.
This might speed up `JNIEnv.IdentityHash` a very small amount, as it no longer checks a `static bool` on each call.
=> [monodroid] treat `LocalRefsAreIndirect` as always true

Directory.Build.props
We branched for .NET 9 Preview 7 from ab412a56 into release/9.0.1xx-preview7; the main branch is now .NET 9 RC 1.
Update dotnet/android/main's version number to 35.0.0-rc.1.
=> $(AndroidPackVersionSuffix)=rc.1; net9 is 35.0.0-rc.1

src/native/CMakeLists.txt, src/native/tracing/CMakeLists.txt
Context: a7b576885624d09c4cc9d65412da2a7558fd3b36
Context: 2ec6f548de8e79c52ed2e61f7181cdf3d0324c20
a7b5768856, among other things, reorganized the way we build our native runtime.
One of the changes was subdivision of source code into separate subdirectories,
each of them a separate static library.  One of reasons behind it was preparation
for the future work where we will be linking the application native runtime dynamically
at application build time, mixing and matching various libraries as necessary.
For the last reason, some of the `.a` archives are output to the location where we store
files to be packaged and distributed to end users.  However, what a7b5768856 missed was
the fact that this mode operation causes later builds to overwrite the earlier ones, since
archive names are the …
=> Make sure debug and release builds of .a files are separate

build-tools/installers/create-installers.targets
Fixes: https://github.com/dotnet/android/issues/9037
Attempting to use `<AndroidMavenLibrary>` in Visual Studio 17.11 P3, which ships .NET 9 P5, like this:
```xml
<ItemGroup>
<AndroidMavenLibrary Include="com.squareup.okhttp3:okhttp" Version="4.9.3" />
</ItemGroup>
```
gives you the error:
```
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.99.0-preview.5.308\tools\Xamarin.Android.Bindings.JavaDependencyVerification.targets(27,5): error XAJDV7028: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.ProjectModel, Version=6.9.1.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The specified file cannot be found.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.99.0-preview.5.308\tools\Xamarin.Android.Bindings …
```
=> [installers] Ship `NuGet*` assemblies needed by `<AndroidMavenLibrary>`.

build-tools/manifest-attribute-codegen/metadata.xml, src/Mono.Android/Android.App/RequiredContentUriPermission.cs, src/Mono.Android/Mono.Android.csproj, src/Mono.Android/PublicAPI/API-35/PublicAPI.Unshipped.txt, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocumentElement.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.NamingCustomAttributes/Android.App/ActivityAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Android.App/ApplicationAttribute.cs, src/Xamarin.Android.NamingCustomAttributes/Android.App/ServiceAttribute.cs
Fixes: https://github.com/dotnet/android/issues/9092
[Previously](https://github.com/dotnet/android/issues/8272), we created a process for automatically determining the possible attributes for elements in `AndroidManifest.xml` and generating the `Mono.Android` `[Application]`, `[Activity]`, etc. attributes for users to consume.  At the time, we merely created the process, but did not use it to expose any new attributes that have been added in previous Android API levels that we never exposed.
This commit exposes all Google-documented manifest attributes for the elements we support.  The undocumented manifest attributes were moved around in the file to a section denoted as "undocumented".
=> [Mono.Android] Add properties for all documented AndroidManifest.xml attributes to `[Activity]`, `[Application]`, etc.

.external
Changes: https://github.com/xamarin/monodroid/compare/d1d43ab1...e68da1e8
* Bump external/xamarin-android from 35f41dc to cb23f7e
* [s360] Ignore irrelevant lz4 warnings
* Bump to dotnet/android@c157aed
* Bump to xamarin/android-sdk-installer@05e4d62
* [tools/msbuild] fix <FastDeploy/> creation of subdirectories
=> Bump to xamarin/monodroid/main@e68da1e8

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/dotnet/android/issues/8967
Context: https://github.com/dotnet/android/pull/9001
You can cause a build error in .NET 8 by doing:
* Start an x86 or x86_64 emulator
* `dotnet build -t:Run`
* Close the emulator, attach an arm or arm64 device
* `dotnet build -t:Run`
Emits the error:
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.113\tools\Xamarin.Android.Common.targets(2063,3): error XA3006: Could not compile native assembly file: typemaps.x86_64.ll
stderr | C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.113\tools\binutils\bin\llc.exe: error: C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.113\tools\binutils\bin\llc.exe: typemaps.x86_64.ll: error: Could not open input file: no such file or directory
This works fine …
=> [Xamarin.Android.Build.Tasks] fix `Inputs` for `_Generate*Java*` targets

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
When we build first to emulator and then change to device. Or we build to device and then change to emulator.
We were adding files in `existingEntries` with paths like this:
lib/armeabi-v7a/lib_Mono.Android.pdb.so
lib/arm64-v8a/lib_Mono.Android.pdb.so
lib/x86/lib_Mono.Android.pdb.so
lib/x86_64/lib_Mono.Android.pdb.so
And removing like this:
lib\armeabi-v7a/lib_Mono.Android.pdb.so
lib\arm64-v8a/lib_Mono.Android.pdb.so
lib\x86/lib_Mono.Android.pdb.so
lib\x86_64/lib_Mono.Android.pdb.so
Doing this all the pdb's were removed in the apk.
I saw this message when I build it locally:
`Removing lib/x86_64/lib_Mono.Android.pdb.so as it is not longer required.`
And then the runtime doesn't have the pdb information to load it and debug the app correctly.
In this PR I'm using the same workaround that …
=> Fixing adding pdb with one slash type and trying to remove another slash

build-tools/create-packs/SignVerifyIgnore.txt, src/bundletool/bundletool.targets
Context: https://github.com/dotnet/android/commit/c89de29a69eaa913255a6971d5305529bc085ebe
Various symbol and signing checks have been failing after bumping
bundletool.jar to version 1.17.0. We can fix these by stripping out the
offending content from bundletool.jar.
=> [bundletool] Remove com/sun/jna content

build-tools/automation/azure-pipelines.yaml
Using the $(System.JobAttempt) variable in the drop metadata artifact
name is problematic. In some cases the drop artifacts created by the
nuget-msi-convert job will be used by a different job, and the job
attempt number will not necessarily match if any jobs are re-ran.
=> [ci] Simplify shipping drop metadata names

src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs, tests/MSBuildDeviceIntegration/Tests/InstantRunTest.cs
I noticed in a `.binlog` in .NET 9:
ProcessAssemblies
...
OutputItems
...
D:\.nuget\packages\microsoft.maui.controls.core\9.0.0-preview.7.24407.4\lib\net9.0-android35.0\ar\Microsoft.Maui.Controls.resources.dll
DestinationSubDirectory = arm64-v8a\ar\\
I believe this causes an issue, later down the line:
FastDeploy
...
Remove redundant file files/.__override__/arm64-v8a/ar/Microsoft.Maui.Controls.resources.dll
So, `<FastDeploy/>` seems to delete every `Microsoft.Maui.Controls.resources.dll` file, because it is passed in:
obj\Debug\net9.0-android\android\assets\arm64-v8a\ar\Microsoft.Maui.Controls.resources.dll
TargetPath = arm64-v8a\ar\\Microsoft.Maui.Controls.resources.dll
I think this was introduced in 86260ed3, we can fix it by only appending to `%(DestinationSubDirectory)` if it …
=> [Xamarin.Android.Build.Tasks] fix `$(DestinationSubDirectory)` double slash

.external
Changes: https://github.com/xamarin/monodroid/compare/21aed734165ab0ea8bcaa1f4151bf13654153327...e6a7cf474abe406f85aac55531fc46ead8f3f7d8
Changes: https://github.com/xamarin/android-sdk-installer/compare/a6a2702acd629e35a4f486a45ff456f7396e26fb...21a3cbfbfde44de1fd39d7f09f277a4bc668bd55
Changes: https://github.com/xamarin/androidtools/compare/5b93b9e70e160d4919f39fd054bbeea80a645568...6ba69ad1c817a4d4bd5004339f4440dd9885ee4b
=> [release/8.0.4xx] Bump to xamarin/monodroid@e6a7cf474a

build-tools/automation/azure-pipelines.yaml, build-tools/create-packs/Directory.Build.targets, eng/Version.Details.xml, eng/Versions.props
Fixes: https://github.com/dotnet/android/issues/9164
Migrates darc/maestro commands to use a passwordless auth flow, as token
based authentication is deprecated and will be removed in the future.
=> [ci] Use passwordless auth for darc/maestro

src/Xamarin.Android.Build.Tasks/Utilities/JCWGenerator.cs
`JCWGenerator.EnsureIdenticalCollections` ensures that every architecture being built contains the same Java derived types. Because this includes `Mono.Android.dll`, even the `dotnet new android` template has ~8500 Java types found. The current implementation uses nested loops and is O(N²). By first sorting the items into `SortedSet` types and then using `SetEquals` we can significantly speed up this operation.
Fresh `dotnet build` of Android template (defaults to 4 architectures), `EnsureIdenticalCollections` takes:
| | |
|-|-|
| `main` | 3081 ms |
| PR | 29 ms |
=> [XABT] Use SortedSets in `JCWGenerator.EnsureIdenticalCollections` for better performance.

Directory.Build.props, build-tools/automation/azure-pipelines.yaml, build-tools/create-packs/Directory.Build.targets, eng/Version.Details.xml, eng/Versions.props
Backports the following maestro and artifact storage changes:
https://github.com/dotnet/android/commit/bbac9fe4ce1014f02c6f9933a13485dc20089a9d
https://github.com/dotnet/android/commit/f834b5531a8c2d4ef02084f553712392ff2c48a5
https://github.com/dotnet/android/commit/9ba9efa964ddf358d48fd27e188e508b2b3c836e
https://github.com/dotnet/android/commit/55c2dd8b275485905b18360fb3aca622411f5ee6
https://github.com/dotnet/android/commit/d050fda83a61bb7cd31e0a0686e9047cb01f924d
https://github.com/dotnet/android/commit/8a85c109d0d0a56a4a36cc1be2e645579ca9b5fe
=> [release/8.0.4xx] Backport maestro and artifact drop infra improvements

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildWithLibraryTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
We currently build for all 4 Android architectures by default. While modern apps are more likely to run on `android-arm64` modern devices or `android-x64` default emulator on x64 machines.
Let's drop 32-bit targets by default, and let customers opt into them. This could significatly help `Release` build times, etc.
Customers could opt into all 4 by adding in their `.csproj`:
<RuntimeIdentifiers>android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
Or in the case of a multi-targeted .NET MAUI project:
<RuntimeIdentifiers Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
=> [Xamarin.Android.Build.Tasks] default to only 64-bit targets

.external
Changes: https://github.com/xamarin/monodroid/compare/e68da1e8...12b1ae70
* Bump to dotnet/android/main@d01a564
* Bump to xamarin/androidtools/main@bea0d3e
* [tools/msbuild] make `_GetPrimaryCpuAbi` run again
* Bump to xamarin/android-sdk-installer/main@035c8a8
* Bump to dotnet/android/main@b69ad9e
I'm mainly doing this to test a build with the `_GetPrimaryCpuAbi` fix.
=> Bump to xamarin/monodroid/main@12b1ae70

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Bumps NuGet.ProjectModel and dependencies to v6.11.0.
Changes: https://github.com/NuGet/NuGet.Client/compare/623fde83a3cd73cb479ec7fa03866c6116894dbf...324d7272b8526a3826ef1f12fa6fc3a362b5bb79
AssemblyFileVersion:6.11.0.119
AssemblyInformationalVersion:6.11.0+324d7272b8526a3826ef1f12fa6fc3a362b5bb79.324d7272b8526a3826ef1f12fa6fc3a362b5bb79
Context: https://github.com/dotnet/android/pull/9098#issuecomment-2291293496
We believe this latest version contains published symbols that will
appease the VS symbol check.
=> [Build.Tasks] Bump to NuGet/Nuget.Client@324d7272

src/Mono.Android/Mono.Android.targets
Fixes: https://github.com/dotnet/android/issues/7974
We've been intermittently running into issues when building Mono.Android
on our PR build pool ever since commit 41b0124 which made mono an
optional build dependency.  Update mdoc invocations to use the .NET
version of the tool to remove one of the last parts of the build that
still depends on mono.
=> [Mono.Android] Use .NET version of mdoc

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Designer.targets, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/EnvironmentFilesParser.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes: https://github.com/dotnet/android/issues/9212
`$XAMARIN_BUILD_ID` was a value that was only used by the `mono-symbolicate` feature from Xamarin. In .NET 6+, `mono-symbolicate` is not supported (and unfortunately, no replacement yet):
* https://github.com/dotnet/runtime/issues/106395
Likely, a new solution would use some new tool like `dotnet-symbol`, which is able to locate symbol information based on existing information inside managed `.dll`'s or even native libraries.
Remove `$XAMARIN_BUILD_ID`, in order to delete unused code, and improve incremental build times mentioned in #9212.
=> [Xamarin.Android.Build.Tasks] remove `$XAMARIN_BUILD_ID`

Documentation/guides/MSBuildBestPractices.md, build-tools/create-packs/SignList.xml, build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
The historical reasons for needing to ILRepack assemblies should no
longer be a concern in a .NET world without VS for Mac.
The ILRepacker target has been removed, and the remaining assemblies
that were being repacked have been added to the workload SDK packs.
=> [Xamarin.Android.Build.Tasks] Remove ILRepack

src/native/monodroid/embedded-assemblies.hh
When assemblies are packaged in the APK archive, their names are
"mangled" so that we don't create clashes with "real" shared libraries,
which are placed in the same directory.  Additionally, since the `lib/`
directory in the APK archive supports only single level of directories,
we must encode satellite assembly culture in the file name, instead of
putting it in a subdirectory.
Unfortunately, when the code was committed, an off-by-one error crept
in, when converting satellite assembly names to their `culture/name`
for.  As the result, the first character of the culture was omitted
which would cause the satellite assemblies not to be loaded properly.
Fix the issue by using the correct mangled name prefix length.
=> Fix an off-by-one error demangling satellite assembly names

src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Tasks/JavaDependencyVerification.cs, src/Xamarin.Android.Build.Tasks/Tasks/MavenDownload.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/JavaDependencyVerificationTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/MavenDownloadTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/MavenExtensions.cs
Fixes: https://github.com/dotnet/android/issues/9013
Today, our Java Dependency Verification feature is built around our recommended practice of 1 binding library per project.  This is reflected in the fact that `JavaArtifact` and `JavaVersion` only support a single library:
```xml
<PackageReference 
Include="Xamarin.Kotlin.StdLib" 
Version="1.7.10" 
JavaArtifact="org.jetbrains.kotlin:kotlin-stdlib" 
JavaVersion="1.7.10" />
```
However a user may choose to place multiple Java libraries in a single package (or project), and we have no way to express that.  Instead of using `JavaArtifact`/`JavaVersion` to specify a Java dependency, we will only use `JavaArtifact` and we will update the specification to include the artifact version: `org.jetbrains.kotlin:kotlin-stdlib:1.7.10`.  Additionally, …
=> [XABT] Allow deployment artifacts to specify multiple JavaDependencyVerification JavaArtifact libraries.

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Utilities/JCWGenerator.cs
In order to ensure that all of our per-arch assemblies contain the same JCW types, we scan them all. We can parallelize this operation per-ABI to save time.  It is ok to parallelize Cecil here, as each "set" contains completely different assemblies coming from completely different assembly resolvers.
Fresh `dotnet build` of Android template (defaults to 4 architectures), total `GenerateJavaSourcesAndMaybeClassifyMarshalMethods` takes:
| | |
|-|-|
| `main` | 11835 ms |
| PR | 4548 ms |
=> [XABT] Scan for JCWs for each ABI in parallel.

Directory.Build.props
We branched for .NET 9 RC 1 from 79aab5c6 into release/9.0.1xx-rc1; the main branch is now .NET 9 RC 2.
Update dotnet/android/main's version number to 35.0.0-rc.2.
=> $(AndroidPackVersionSuffix)=rc.2; net9 is 35.0.0-rc.2

external/debugger-libs.override.props
Changes: https://github.com/mono/debugger-libs/compare/84c5c67f...d5664344
Context: https://github.com/dotnet/android/pull/9237
Updating this submodule in main, to align with changes on the `release/9.0.1xx-rc1` branch.
Notably, this sets `$(DisableTransitiveFrameworkReferenceDownloads)` for mono/debugger-libs to avoid restoring ASP.NET and Windows desktop packages for downlevel .NET versions.
Changes in mono/debugger-libs:
* Fix Policheck errors
* Adding AddExplicitInterfaceImplementation
* Fix add breakpoint and viewing locals from a pdb loaded on debugges
* Synchronize access to symbols dictionary
* [build] add extension point for consuming repositories
=> Bump to mono/debugger-libs/main@d5664344

eng/Version.Details.xml, eng/Versions.props
Changes: https://github.com/dotnet/runtime/compare/fe0cfd55...c4a79875
.NET 9 RC 1 will include security fixes, so the very latest builds will be internal. As a way for us to test the newest possible *public* builds, we can update dotnet/runtime *ahead* of dotnet/sdk.
To do this:
* Remove `CoherentParentDependency="Microsoft.NET.Sdk"` from `eng/Version.Details.xml`.
* Find a commit at: https://github.com/dotnet/runtime/commits/release/9.0-rc1
* Get the BAR build id for the commit:
```
> darc get-build --repo dotnet/runtime --commit c4a79875fcb2c76b2e92ff50940d4ea9264e2eeb
Repository:    https://github.com/dotnet/runtime
Branch:        release/9.0-rc1
Commit:        c4a79875fcb2c76b2e92ff50940d4ea9264e2eeb
Build Number:  20240821.1
Date Produced: 8/21/2024 7:33 AM
AzDO Build Id: 2520584 …
```
=> [release/9.0.1xx-rc1] [maestro] setup direct subscription for dotnet/runtime

Configuration.props, NuGet.config, build-tools/create-packs/Directory.Build.targets, build-tools/scripts/DotNet.targets, eng/Version.Details.xml, eng/Versions.props
Changes: https://github.com/dotnet/android/compare/34.0.113...b0fd011
.NET 8 changelog:
* [Mono.Android] AndroidMessageHandler should follow HTTP-308 redirects
* [ci] Fix android source path for MAUI test job
* [ci] Update checkout path for nightly build
* [Mono.Android-Tests] Fix repo URL in redirect tests
* [Xamarin.Android.Build.Tasks] Support VS "Build Acceleration"
* [xaprepare] Always use release mono bundle
* [ci] Update sdk-insertions trigger to manual only
* Bump to dotnet/runtime/release/8.0@4a37e7305c 8.0.8
* Bump to dotnet/installer/release/8.0.2xx@b638a84fba 8.0.205-servicing.24212.27
* [ci] Disable CodeQL on macOS, Linux, non-main jobs
* [ci] Use DotNetCoreCLI to sign macOS files
* [tests] fix `InvalidTargetPlatformVersion` for `net8.0`
* [ci] Run "Push Internal" job on …
=> Bump to 34.0.137 of the .NET 8 Android workload

src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrComposer.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrInstructions.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrMetadataManager.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrModule.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrTypeCache.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/MemberInfoUtilities.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/StructureInfo.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/StructureMemberInfo.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/TypeUtilities.cs
Context: https://github.com/dotnet/android/blob/main/Documentation/guides/tracing.md#how-to-dotnet-trace-a-build
Making a XAML or small C# change in a .NET MAUI project and running an incremental build, shows a reasonable amount of time spent in `<GenerateJavaStubs />` -- even with a device attached.
If I attach `dotnet trace` to `dotnet build`, I can see time spent in:
117.08ms (2.20%) xamarin.android.build.tasks!Xamarin.Android.Tasks.LLVMIR.MemberInfoUtilities.GetNumberFormat(class System.Reflection.MemberInfo)
82.33ms (1.60%) xamarin.android.build.tasks!Xamarin.Android.Tasks.LLVMIR.MemberInfoUtilities.IsNativePointerToPreallocatedBuffer(class System.Reflection.MemberInfo,unsigned int64&)
29.30ms (0.56%) xamarin.android.build.tasks!Xamarin.Android.Tasks.LLVMIR.MemberInfoUtilities.UsesDat …
=> [Xamarin.Android.Build.Tasks] introduce `LlvmIrTypeCache`

Configuration.props, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs, tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidClientHandlerTests.cs
Fixes: https://github.com/dotnet/android/issues/9253
Fixes: https://github.com/dotnet/android/issues/9048
Multiple reports that `make prepare` now errors out:
% make prepare
…
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Downloading Mono archive
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Checking if all runtime files are present
• some files are missing, download and extraction required
Downloading Mono archive from https://xamjenkinsartifact.azureedge.net/mono-sdks/android-debug-Darwin-d9a6e8710b37cd7f16cf52eff4f772556e57cc41.7z
Failed to obtain Mono archive size. HTTP status code: BadRequest (400). Mono runtimes will be rebuilt
Downloading Mono archive from https://xamjenkinsartifact.azureedge.net/mono-sdks/android-debug-Darwin-d9a6e8710b37cd7f16cf52ef …
=> [build] Fix the Legacy Xamarin.Android build

build-tools/xaprepare/xaprepare/Resources/Configuration.OperatingSystem.props.in, build-tools/xaprepare/xaprepare/Steps/Step_GenerateFiles.cs, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
Context: https://github.com/dotnet/android/issues/9159#issuecomment-2317390991
Bump `$(MinimumSupportedJavaVersion)` to 17.0, and base this value on the `Configurables.Defaults.MicrosoftOpenJDK17Version` value so that if (when) we bump the JDK we build against, the major version value of `$(MinimumSupportedJavaVersion)` follows suit.
Additionally, remove the `$(MinimumSupportedJavaVersion)` definition in `Microsoft.Android.Sdk.DefaultProperties.targets` so that it's only defined in one location.
=> [Xamarin.Android.Build.Tasks] Bump MinimumSupportedJavaVersion=17

tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs, tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
It's been a while, since I went through and refactored these tests. After seeing a couple build-time regressions in .NET 9, I think it's overdue.
Removing test cases that likely won't catch an issue:
* `Build_Designer_Change` (less concerned about designer now)
* `Build_CSProj_Change`
`Build_From_Clean_DontIncludeRestore` would likely catch similar issues as these two, anyway.
`Build_XAML_Change_RefAssembly` now uses a `net8.0` class library where `$(ProduceReferenceAssembly)` defaults to `true`.
Removed a 500ms addition, that only made sense when we supported both "classic" Xamarin.Android and .NET 6+ projects.
Update the time thresholds to be a bit shorter, in general.
=> [tests] update MSBuild performance tests

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Assets.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
I was looking to extend the `BuildDependsOn` target ordering used to
structure application and library builds and noticed a fair amount of
target duplication that may benefit from some consolidation.
A new `_AndroidBuildDependsOn` property has been added to include the
core targets that builds of both project types depend on.
The  `_CheckNonIdealBindingConfigurations` target has been merged with
`_CheckNonIdealConfigurations`.
The `_CheckProjectItems` target will now run for both app and library
projects, as the corresponding `CheckProjectItems` task is already
conditional based on the value of `$(AndroidApplication)`.
The `_AddAndroidDefines` target has been removed in favor of the more
widely used `AndroidPrepareForBuild` target, both of which are empty
targets that depend on …
=> [Xamarin.Android.Build.Tasks] Reduce BuildDependsOn duplication

src/Xamarin.Android.Build.Tasks/Mono.Android/GrantUriPermissionAttribute.Partial.cs, src/Xamarin.Android.Build.Tasks/Mono.Android/IntentFilterAttribute.Partial.cs, src/Xamarin.Android.Build.Tasks/Mono.Android/MetaDataAttribute.Partial.cs, src/Xamarin.Android.Build.Tasks/Mono.Android/PropertyAttribute.Partial.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
Profiling an incremental build of a `dotnet new maui` project with a XAML change, one thing I saw was time spent in `<GenerateJavaStubs/>` MSBuild task, and the `ManifestDocument` class:
67.57ms (1.80%) xamarin.android.build.tasks!Xamarin.Android.Tasks.ManifestDocument.Merge(class Microsoft.Build.Utilities.TaskLoggingHel
19.99ms (0.53%) xamarin.android.build.tasks!Xamarin.Android.Tasks.ManifestDocument.CreateApplicationElement(class System.Xml.Linq.XEleme...
Reviewing the code, there was a decent amount of LINQ usage that would create extra allocations for closures, such as:
var properties =
Assemblies.SelectMany (path => PropertyAttribute.FromCustomAttributeProvider (Resolver.GetAssembly (path), cache))
I unrolled the System.Linq usage, and just used plain `foreach` loops instead.
I also …
=> [Xamarin.Android.Build.Tasks] reduce System.Linq usage in ManifestDocument

src/Xamarin.Android.Build.Tasks/Utilities/JCWGenerator.cs
One question that came up with https://github.com/dotnet/android/pull/9208 was "why `SortedSet` instead of `HashSet`"?
Indeed a `HashSet` seems to be 10ms - 15ms faster to construct than the `SortedSet` while taking the same ~1ms to perform the `SetEquals` operation.
=> [XABT] Replace SortedSet with HashSet.

.editorconfig, src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesignerAssembly.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/GenerateResourceCaseMapTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ManagedResourceParserTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/ResourceData.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidCommonProject.cs, src/Xamarin.Android.Build.Tasks/Utilities/AssemblyCompression.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
I was building Xamarin.Android.Build.Tasks and noticed some CA2022 warnings that scared me:
src\Xamarin.Android.Build.Tasks\Utilities\AssemblyCompression.cs(77,6):
warning CA2022: Avoid inexact read with 'System.IO.FileStream.Read(byte[], int, int)' (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2022)
src\Xamarin.Android.Build.Tasks\Utilities\MonoAndroidHelper.cs(186,8):
warning CA2022: Avoid inexact read with 'System.IO.FileStream.Read(byte[], int, int)' (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2022)
Some cases like this were actually ok:
byte[] publicKey = new byte[stream.Length];
stream.Read (publicKey, 0, publicKey.Length);
// ...
name.PublicKey = SigningHelper.GetPublicKey (publicKey);
Because it uses …
=> [Xamarin.Android.Build.Tasks] make CA2022 an error

src/Xamarin.Android.Build.Tasks/Tasks/GenerateRtxt.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Utilities/FileResourceParser.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
Fixes: https://github.com/dotnet/android/issues/9285
Building a .NET 9 project without API 35 installed would fail with:
MSB4044: The "GenerateRtxt" task was not given a value for the required parameter "JavaPlatformJarPath"
I was able to reproduce this in an MSBuild test that uses:
var androidSdkPath = CreateFauxAndroidSdkDirectory (Path.Combine (path, "android-sdk"), "35.0.0", []);
To fix this:
* Remove `[Required]` from the `JavaPlatformJarPath` property
* Add some extra checks if the value is `null` or empty
I also did some other cleanup:
* `MonoAndroidHelper` now logs during the `<GetJavaPlatformJar/>`
task, even during a design-time build.
* Removed what looked like an unused, extra line in `FileResourceParser`:
string publicXmlPath = Path.Combine (JavaPlatformDirectory, "data", …
=> [Xamarin.Android.Build.Tasks] fix `<GenerateRtxt/>` during design-time builds

.external, Configuration.props, build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs
Context: https://github.com/dotnet/android/commit/51151d727a0438dd049ad2678f9039d8f255d7b2
Introduces a Xamarin.Installer.Common.props file which replaces
Xamarin.Android.Tools.Versions.props, and includes the latest
set of recommended Android SDK components for API 35.
=> Bump recommended Android SDK versions for API 35

Documentation/docs-mobile/building-apps/build-properties.md
This doc just looks a bit out of date.
=> [docs] mention `AndroidDexTool=d8` is default now

src/Xamarin.Android.Build.Tasks/Tasks/DetermineJavaLibrariesToCompile.cs
Context: https://github.com/dotnet/android/pull/2882
During an incremental build + deploy of a `dotnet new maui` project, I noticed time spent in:
62.52ms (1.8%) xamarin.android.build.tasks!Xamarin.Android.Tasks.DetermineJavaLibrariesToCompile.HasClassFiles(class System.String)
What's worse, is this happens once for build and again for deploy. Because there are 100+ `.jar` files, we are actively opening each one with libZipSharp to determine if there are any `.class` files.
In e6326dcb, we added the `HasClassFiles()` call to fix a problem with "Enhanced Fast Deployment". However, we have since completely removed this feature in:
* https://github.com/xamarin/monodroid/commit/93ab95e18077d56d9d55ce7b4069a534e2dea35e
* https://github.com/xamarin/monodroid/commit/2c64cd5f533616ff4751fb1df6bbfc …
=> [Xamarin.Android.Build.Tasks] remove `HasClassFiles` checks

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/EnvironmentHelper.cs, src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfig.cs, src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGenerator.cs, src/native/monodroid/embedded-assemblies.cc, src/native/monodroid/embedded-assemblies.hh, src/native/monodroid/monodroid-glue.cc, src/native/xamarin-app-stub/application_dso_stub.cc, src/native/xamarin-app-stub/xamarin-app.hh
Context: https://github.com/dotnet/android/pull/9292
With "Enhanced Fast Deployment" no longer part of .NET for Android, 
remove the native runtime side of its support.
=> Remove native runtime support for instant run

src/Mono.Android/Android.Runtime/AndroidRuntime.cs, src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android.Runtime/JNIEnvInit.cs, src/java-runtime/java/mono/android/MonoPackageManager.java, src/java-runtime/java/mono/android/Runtime.java, src/native/monodroid/internal-pinvokes.cc, src/native/monodroid/mono_android_Runtime.h, src/native/monodroid/monodroid-glue-internal.hh, src/native/monodroid/monodroid-glue.cc, src/native/pinvoke-override/generate-pinvoke-tables.cc, src/native/pinvoke-override/pinvoke-tables.include, src/native/runtime-base/internal-pinvokes.hh
This removes an API < 10 code path, which should speed up all `JNIEnv.StartCreateInstance` / `FinishCreateInstance` calls by a very small amount. They no longer check a `AllocObjectSupported` field, which is now always `true`.
This also removes the need to pass in `androidSdkVersion` / `android_api_level` from the native side at startup.
We can also remove the `_monodroid_get_android_api_level()` p/invoke, which is unused.
=> [Mono.Android] treat `AllocObjectSupported` as always true

src/Mono.Android/Xamarin.Android.Net/ServerCertificateCustomValidator.cs
Related to https://github.com/dotnet/runtime/issues/107695
When `<domain-config ...>` is used in `network_security_config.xml` then all calls to `_internalTrustManager.CheckServerTrusted (javaChain, authType);` will throw an exception and we will always pass `SslPolicyErrors.RemoteCertificateChainErrors` to the custom server certificate validation callback. To fix this, it is necessary to use hostname-specific certificate check via `X509TrustManagerExtensions`.
=> [Mono.Android] Use X509TrustManagerExtensions to allow using domain-config in network_security_config.xml

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10234371&view=ms.vss-test-web.build-test-results-tab&runId=110872727&resultId=100056&paneView=debug
The `Xamarin.Legacy.Sdk` GitHub repo is archived, and no longer supported.
We still have a few tests using `Xamarin.Legacy.Sdk` that fail with:
error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project.
It's probably related to Mono now longer installed on CI agents.
Let's remove usage of `Xamarin.Legacy.Sdk` from our tests.
=> [tests] remove Xamarin.Legacy.Sdk

build-tools/scripts/TestApks.targets
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10233028&view=logs&j=16e8a400-d09b-57ea-d2d5-3b6e79259973&t=469522d3-478a-58c1-dd99-cef151b877ac&l=4872
The APK tests on API 21 & 23 (maybe more) emulators fail with:
[BT The app doesn't support ABI architectures of the device. Device ABIs: [x86], app ABIs: [arm64-v8a, x86_64].
Let's build `android-x86` as well for all APK tests, to fix this issue.
=> [tests] fix nightly APK tests for 32-bit emulators

src/Xamarin.Android.Build.Tasks/Tasks/D8.cs, src/Xamarin.Android.Build.Tasks/Tasks/JavaToolTask.cs, src/Xamarin.Android.Build.Tasks/Tasks/R8.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
Context https://github.com/dotnet/android/issues/7008#issuecomment-2343312847
When building with certain libraries we are seeing the following errors
```
4>  Invalid signature '(TT;)TV;' for method java.lang.Object kotlin.jvm.internal.PropertyReference1.get(java.lang.Object). (TaskId:792)
4>R8 : Validation error : A type variable is not in scope.
4>  Signature is ignored and will not be present in the output. (TaskId:792)
4>  Info in ...\.nuget\packages\xamarin.kotlin.stdlib\1.6.20.1\buildTransitive\monoandroid12.0\..\..\jar\org.jetbrains.kotlin.kotlin-stdlib-1.6.20.jar:kotlin/jvm/internal/PropertyReference0.class: (TaskId:792)
4>  Invalid signature '()TV;' for method java.lang.Object kotlin.jvm.internal.PropertyReference0.get(). (TaskId:792)
4>R8 : Validation error : A type variable is …
```
=> Fix R8 Message processing to remove false positives.

src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodsNativeAssemblyGenerator.cs
Fixes: https://github.com/dotnet/android/issues/9200
@jonpryor found that on Windows, shared library name hashes are
generated using the Windows path separator character, while the
runtime expects a Unix one.  This discrepancy leads to different
hashes for the same satellite assembly on Linux/macOS and Windows.
Fix by explicitly converting any `\` characters in the satellite
assembly name to `/` prior to hash generation.
=> Fix DSO name hash generation on Windows

.external, tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
Context: https://github.com/dotnet/android/issues/8662
Context: https://github.com/xamarin/monodroid/pull/1537
* Bump to xamarin/monodroid/release/8.0.4xx@352bcbe8
Changes: https://github.com/xamarin/monodroid/compare/1a9ee373...352bcbe8
* [tools/msbuild] implement $(AdbTargetArchitecture) for IDEs
* Bump to dotnet/android/release/8.0.4xx@c158adfd6f
=> [release/8.0.4xx] [tests] add test for `$(AdbTargetArchitecture)` (#9227)

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
Changes: https://github.com/android/ndk/wiki/Changelog-r27#r27b
Contains a handful of toolchain fixes which don't affect us.  Updating
the version to track the latest LTS release.
=> Bump to Android NDK r27b

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10272296&view=ms.vss-test-web.build-test-results-tab&runId=111431847&resultId=100127&paneView=debug
With Fast Dev disabled, this test fails with:
```
'assemblies/arm64-v8a/App1.pdb' and 'D:\a_work\1\a\TestRelease\09-24_17.47.53\temp\BuildAppCheckDebugSymbols\App1\obj\Debug\android\assets\arm64-v8a\App1.pdb' should not differ
Expected Stream length 13136 but was 12432.
```
We can eventually fix the test, but we'd have to shell out to:
llvm-objcopy --dump-section=payload=payload.bin libassemblies.arm64-v8a.blob.so
=> [tests] ignore `BuildAppCheckDebugSymbols()` test on non-commercial builds

build-tools/create-packs/ConfigureLocalWorkload.targets
In 5ebcb1dd1, a new `libarchive-dso-stub.so` file was added to `Microsoft.Android.Runtime.proj` and runtime packs, but I started getting build failures for any app, such as:
bin\Debug\lib\packs\Microsoft.Android.Sdk.Windows\35.0.0\tools\Xamarin.Android.Common.Debugging.targets(139,2): error XABLD7009: System.InvalidOperationException: Internal error: archive DSO stub location not known for architecture 'Arm64'
at Xamarin.Android.Tasks.DSOWrapperGenerator.WrapIt(AndroidTargetArch targetArch, String payloadFilePath, String outputFileName, IBuildEngine4 buildEngine, TaskLoggingHelper log) in src\Xamarin.Android.Build.Tasks\Utilities\DSOWrapperGenerator.cs:line 86
at Xamarin.Android.Tasks.BuildApk.AddRuntimeConfigBlob(ZipArchiveEx apk) in src\Xamarin.Android.Build.Tasks\Tasks\BuildApk.cs:line …
=> [build] fix incremental build for `RuntimeLists.xml`

Configuration.props
Changes: https://cmake.org/cmake/help/latest/release/index.html
Android SDK recently added cmake v3.30.3.  Bridge the gap of 60+ releases
between 3.21.1 and the 3.30.3 and use the latest and the greatest.
This PR doesn't contain any changes to script files.  A review of changes 
in cmake is required in order to modify our scripts accordingly.
=> Bump cmake to version 3.30.3

src/Microsoft.Android.Templates/android-wear/AndroidApp1.csproj
Context: https://github.com/dotnet/android/issues/9161
Update our `android-wear` template to reference the latest NuGet of `Xamarin.AndroidX.Wear` (`1.3.0.10`).
=> [templates] Update to latest NuGet version of `Xamarin.AndroidX.Wear`

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hant.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10286032

src/Microsoft.Android.Templates/android-wear/AndroidApp1.csproj, src/Microsoft.Android.Templates/android/AndroidApp1.csproj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
For NativeAOT scenarios, projects would set:
<PublishAot>true</PublishAot>
For both `Debug` and `Release`, this allows you to get the same set of analyzers in both configurations. You'd want to see the same warnings for both.
For Android, the project template is currently doing:
<PropertyGroup Condition="'$(Configuration)' == 'Release'">
<TrimMode>Full</TrimMode>
But this would result in a *different* set of warnings between `Debug` and `Release` mode!
Instead, we can do:
<TrimMode>Full</TrimMode>
And then add a new default, such as:
<EnableTrimAnalyzer Condition="'$(EnableTrimAnalyzer)' == '' and '$(TrimMode)' == 'full'">true</EnableTrimAnalyzer>
`TrimMode=Full` does *not* enable the trimmer, so other defaults in `Debug` should remain …
=> [trimming] `TrimMode=full` in debug mode, should enable analyzers

Documentation/docs-mobile/TOC.yml, Documentation/docs-mobile/messages/index.md, Documentation/docs-mobile/messages/xa4315.md, samples/HelloWorld/HelloLibrary/AndroidManifest.xml, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AndroidLibraries.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Tasks/CreateAar.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateLibraryResources.cs, src/Xamarin.Android.Build.Tasks/Tasks/GetImportedLibraries.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildWithLibraryTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/8262
Context: https://developer.android.com/studio/projects/android-library#aar-contents
Context: fcd7cf8f4200ccae92e333c920613bfec260973b
In fcd7cf8f, we stopped using `@(EmbeddedResource)` within assemblies
to contain Android Resource, Assets, Libraries, etc., and instead
began a `.aar` file.
One of the things never supported in the Classic system was to allow
Library projects to contain `AndroidManifest.xml` files, and package
`AndroidManifest.xml` files into the library `.aar` file for inclusion
in NuGet packages.
Add `$(AndroidManifest)` to `@(_CreateAarInputs)`, so that Library
projects can now specify an `AndroidManifest.xml` file for inclusion
in the library `.aar` file (which in turn should be included in NuGet
packages). …
=> [Xamarin.Android,Build.Tasks] Library .aar includes $(AndroidManifest) (#8273)

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Microsoft.Android.Sdk.Bindings.Gradle.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidGradleProjectTests.cs
Context: https://github.com/dotnet/android/commit/dbdc5fadca60b79518739fea49bdfee58a748bf0
Updates the default values of the `%(Bind)` and `%(Pack)` metadata
forwarded to the created `@(AndroidLibrary)` item to better match the
defaults on that item. Leaving these empty did not allow the defaults
declared in the `AndroidLibrary` ItemDefinitionGroup to be used as
expected in commit https://github.com/dotnet/android/commit/dbdc5fadca60b79518739fea49bdfee58a748bf0.
=> [XABT] Update AndroidGradleProject Bind and Pack defaults

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildWithLibraryTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/native/monodroid/monodroid-glue.cc, src/native/runtime-base/android-system.cc, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
This commit updates the inputs for `_GenerateJavaStubs` and `_GeneratePackageManagerJava` so that the `@(AndroidEnvironment)` and `@(LibraryEnvironments)` items are only included if we are building a release build. Or a build which embeds the assemblies into the apk. 
This is so that we can evantually fast deploy these files to the device via https://github.com/xamarin/monodroid/pull/1547. 
A new unit test has been added to make sure that the environment values can be used correctly on device.
=> Add Conditional Inputs for _GeneratePackageManagerJava and _GenerateJavaStubs

NuGet.config, build-tools/scripts/DotNet.targets
Trying to fix the error:
##[error]build-tools\scripts\DotNet.targets(115,5): Error MSB3073: The command ""bin\Release\dotnet\dotnet" workload install maui --skip-manifest-update --skip-sign-check --verbosity diag --source "build-tools\scripts\..\..\..\maui\artifacts" --source "D:\a\_work\1\a\android-packs" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/benchmark-dotnet-prerelease/nuget/v3/index.json" --source "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" …
=> [build] add feeds to fix `MAUI Integration`

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tasks/PrepareDSOWrapperState.cs, src/Xamarin.Android.Build.Tasks/Utilities/DSOWrapperGenerator.cs
Context: https://github.com/dotnet/maui/pull/24539#issuecomment-2377671832
In .NET MAUI's build, they failed to bump .NET for Android because of the following error:
dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.0-rc.2.130\tools\Xamarin.Android.Common.Debugging.targets(139,2): error XABLD7009: System.InvalidOperationException: Internal error: archive DSO stub location not known for architecture 'X86'
at Xamarin.Android.Tasks.DSOWrapperGenerator.WrapIt(AndroidTargetArch targetArch, String payloadFilePath, String outputFileName, IBuildEngine4 buildEngine, TaskLoggingHelper log) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Utilities/DSOWrapperGenerator.cs:line 86
at Xamarin.Android.Tasks.BuildApk.AddRuntimeConfigBlob(ZipArchiveEx apk) in …
=> [Xamarin.Android.Build.Tasks] use `ProjectSpecificTaskObjectKey` in `<PrepareDSOWrapperState/>`

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/dotnet/android/issues/8253
Context: https://github.com/dotnet/android/pull/9343
We've had a number of reports about *hangs* when LLVM Marshal Methods are enabled (see also dotnet/android#8253), but we had been willing to accept having LLVM Marshal Methods enabled by default as it helps improve app startup time.
However, [a customer reported a native crash][0] when LLVM Marshal Methods are enabled:
> ![Thread Stack Trace][1]
syscall at line 28 within libc
__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) at line 144 within libc
sem_wait at line 108 within libc
within libmonosgen-2.0.so (Build Id: …)
within <anonymous:…>
This native crash suggests "something going wrong" within MonoVM. We find this "scary" enough that we feel it is once again …
=> [release/9.0.1xx-rc2] [Xamarin.Android.Build.Tasks] Disable LLVM marshal methods (#9336)

src/native/monodroid/xamarin-android-app-context.cc
`get_function_pointer` can be called from any thread. In particular, it can be called from Android thread pool thread when method marshaling is used. We need to ensure those threads stay in the GC safe mode from the runtime perspective once we stop executing user code on those threads. `mono_thread_attach` switches the thread to GC unsafe mode and it stays there after we stop executing user code. The next GC will try to suspend the thread which cannot succeed since there's no cooperative runtime code running on that thread anymore.
The fix is to use `mono_jit_thread_attach` which mimics what the iOS/macOS interop does. It creates the necessary MonoVM thread structures for JIT to work but doesn't transition the thread state.
Fixes #8253
=> Fix thread state transition in get_function_pointer

eng/Version.Details.xml, eng/Versions.props
Context: https://github.com/dotnet/android/commit/b5e7598e50f22a63b6e540c0c16559e86a70c119
Changes: https://github.com/dotnet/runtime/compare/46cfb747...200d05e4
.NET 9 RC 2 will include security fixes, so the very latest builds will be internal. As a way for us to test the newest possible *public* builds, we can update dotnet/runtime *ahead* of dotnet/sdk.
Following the instructions at b5e7598e, I ran the following command for the latest build on the `release/9.0-rc2` branch:
> darc get-build --repo dotnet/runtime --commit 200d05e41fc2212ff8c98ed79ebe9043bfed58aa
Repository:    https://github.com/dotnet/runtime
Branch:        release/9.0-rc2
Commit:        200d05e41fc2212ff8c98ed79ebe9043bfed58aa
Build Number:  20240923.4
Date Produced: 9/23/2024 8:50 PM
Build Link: …
=> [maestro] setup direct subscription for dotnet/runtime

Configuration.props, Xamarin.Android.Build.Tasks.sln, Xamarin.Android.sln, build-tools/create-packs/ConfigureLocalWorkload.targets, build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/Microsoft.Android.Ref.proj, build-tools/installers/create-installers.targets, eng/Versions.props, src/Microsoft.Android.Sdk.Analysis/Microsoft.Android.Sdk.Analysis.csproj, src/Microsoft.Android.Sdk.Analysis/ResourceDesignerDiagnosticSuppressor.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesignerAssembly.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesignerIntermediateClass.cs
Context #8381
Add a `DiagnosticSuppressor` to "turn off" the `IDE0002` style diagnostic message which incorrectly tells users to use the `_Microsoft.Android.Resource.Designer.ResourceConstant` type directly. This can cause allot of annoyance with our users because it appears on EVERY single usage of `Resource.*`. So you end up with what looks like code spagetti. 
So we need to start shipping an `Analyzer` assembly along with the `Ref` framework pack. This is the place these things need to go. Unfortunately it means that the older frameworks will not get this analyzer. Only the current one. 
On the packaging side, the Analyzer assembly has to go in a `analyzers/dotnet/<language>` folder in the .Ref Nuget Package. There also needs to be an entry in the `FrameworkList.xml` file which has a …
=> Add DiagnosticSuppressor to suppress the IDE0002 Style Hint in the IDE

tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs, tests/MSBuildDeviceIntegration/Tests/MarshalMethodsGCHangTests.cs
Context: https://github.com/dotnet/android/pull/9343
Context: https://github.com/dotnet/android/issues/8253#issuecomment-2380714158
Test is based on the original repro from https://github.com/filipnavara/mm-deadlock-repro/
=> Add test for marshal methods hang

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10317670

tests/MSBuildDeviceIntegration/Tests/MarshalMethodsGCHangTests.cs
Context: https://github.com/dotnet/android/pull/9352
Remove a misleading copy pasta comment and change the location
of message we use to test whether the app actually ran.
=> Cosmetic changes to the marshal methods hang test

src/Xamarin.Android.Build.Tasks/Utilities/AssemblyStoreGenerator.cs
When running builds at the command-line (with the default, new "MSBuild Terminal Logger"), `Console.WriteLine()` output can make the text not look so great:
> dotnet build -c Release -bl
Restore complete (0.6s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
hellomaui                                                                                      _BuildApkEmbed (18.9s)
Number of descriptors: 116; index entries: 232
hellomaui succeeded (33.3s) → bin\Release\net9.0-android\android-arm64\hellomaui.dll
Build succeeded in 46.8s
The message `Number of descriptors: 116; index entries: 232` appears, but so does another one. You can watch the terminal logger clear and rewrite messages, which is not ideal.
Let's move these to the MSBuild logger, so they will …
=> [Xamarin.Android.Build.Tasks] move `Console.WriteLine()` messages to MSBuild log

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Try moving the `_BuildApkFastDev` target to this repo. This will allow us to keep this target up to date easily when we change the underlying `BuildApk` task.
=> Move the _BuildApkFastDev Target to this repo

build-tools/automation/yaml-templates/run-msbuild-tests.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10326490&view=logs&j=293e774d-1b3c-56a2-2db1-26d172f04ddd&t=b180d07a-099b-5dc9-8d17-5c88abaf95ba&l=11
The attempt to install Xamarin.Android is failing on macOS anyway, as it relies on a VS Mac updater service:
Querying https://software.xamarin.com/Service/Updates?v=2&pv964ebddd-1ffe-47e7-8128-5ce17ffffb05=0&pv4569c276-1397-4adb-9485-82a7696df22e=0&pvd1ec039f-f3db-468b-a508-896d7c382999=0&pv0ab364ff-c0e9-43a8-8747-3afb02dc7731=0&level=Stable
Retry attempt 1: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
at Boots.Core.HttpClientWithPolicy.DoGetXmlDocumentAsync(Uri uri, CancellationToken token) in …
=> [build] stop installing Xamarin.Android

samples/HelloWorld/HelloLibrary/LibraryActivity.cs, src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Utilities/MetadataExtensions.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Utilities/ResourceDesignerImportGenerator.cs
Fixes #9369
When System.Reflection.Metadata comes across an Attribute which has a generic, it does NOT return a `TypeReferenceHandle`. It returns a `TypeSpecificationHandle`.
Tying to cast the type results in the following error
```
System.InvalidCastException: Die angegebene Umwandlung ist ungültig.
error XAFLT7007:    bei System.Reflection.Throw.InvalidCast()
error XAFLT7007:    bei System.Reflection.Metadata.TypeReferenceHandle.op_Explicit(EntityHandle handle)
error XAFLT7007:    bei Xamarin.Android.Tasks.MetadataExtensions.GetCustomAttributeFullName(MetadataReader reader, CustomAttribute attribute)
error XAFLT7007:    bei Xamarin.Android.Tasks.FilterAssemblies.IsAndroidAssembly(AssemblyDefinition assembly, MetadataReader reader)
error XAFLT7007:    bei …
```
=> Handle more Attribute Types when Filtering Assemblies

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/apk-instrumentation.yaml
There is some odd build issue were Release artifacts are making into a Debug build of `tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj`. This only happens in this test project.
I suspect it is because we are overriding the `$(Configuration)` in the project, but not always since we are also building in a `Release` environment. Both the top level `Configuration.props` is using `$(Configuration)` as well as the test project, but the test project gets a value of `Debug` from the build yaml. I think it is confusing things, but I have not been able to track it down.
So lets try to clean up the `tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj` test project after it has been built and run. To make sure any old outputs are …
=> Move Debug Test first and Clean after runs

build-tools/automation/yaml-templates/apk-instrumentation.yaml
Context: https://github.com/dotnet/android/commit/5cd9a267e20a19d796d521d67867a00fd67328ba
Context: https://github.com/dotnet/android/commit/e55c38f8eec2992899fc96528b9dcbc174aad585
The monodroid pipeline recently started failing to build with:
/build-tools/automation/yaml-templates/apk-instrumentation.yaml@xa-yaml: Could not find /build-tools/automation/yaml-templates/run-dotnet-preview.yaml in repository self hosted on https://github.com/ using commit 0f5fd98ec70af48f03a67577e5ef9a360c2f0650. GitHub reported the error, "Not Found"
The @ self yaml template annotation should only be used in the pipeline
file, and not in nested templates.  This should fix potential issues
with other repos that use these templates.
=> [CI] Remove self annotation from apk-instrumentation.yaml

build-tools/automation/yaml-templates/variables.yaml
Context: https://github.com/actions/runner-images/blob/768c45609155f3d115ea5c2c23ce129af4d17a9e/images/macos/macos-14-Readme.md
Updates the hosted macOS pool used for build and test stages to the
latest macOS 14 Sonoma images.
=> [ci] Use latest macOS-14 image

build-tools/automation/yaml-templates/apk-instrumentation.yaml
The apk-instrumentation template is also used by the monodroid repo,
where the xaSourcePath template parameter is set to the custom android
source path used there. This path (and other parameters) need to be
forwarded to the new clean step that was recently added.
=> [ci] Use xaSourcePath and other parameters in apk clean step

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Utilities/AssemblyPackagingHelper.cs, src/Xamarin.Android.Build.Tasks/Utilities/AssemblyStoreBuilder.cs
Simplify the task of constructing assembly stores by moving all the code
which actually stashes assemblies (and their config and debug files, if found
and required) in the assembly store to a separate utility class, `AssemblyStoreBuilder`.  
Additionally, move a portion of assembly packaging code from `BuildApk` to a helper class.
This makes it easier to build the stores outside of the `BuildApk` task and further 
simplifies `BuildApk` code.
=> Move all of assembly store building code to a separate class

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs, src/Xamarin.Android.Build.Tasks/Utilities/AssemblyCompression.cs
To further simplify `BuildApk`, move assembly compression code
to a separate utility class.  This also lets us compress assemblies
from tasks other than `BuildApk`.
=> Move compression code from BuildApk to utility class

build-tools/automation/azure-pipelines.yaml, build-tools/create-packs/vs-workload.in.props
Context: https://github.com/dotnet/arcade/commit/b2d3a3a35526b529490e8f7e410b3777b3f20bd6
Context: https://github.com/xamarin/yaml-templates/pull/339
The VS insertion manifest generation has been updated to use new VS
component IDs required for .NET 9+.
=> [nuget-msi-convert] Support improved VS component IDs

src/native/monodroid/debug.cc, src/native/monodroid/embedded-assemblies-zip.cc, src/native/monodroid/embedded-assemblies.cc, src/native/monodroid/mono-image-loader.hh, src/native/monodroid/mono-log-adapter.cc, src/native/monodroid/monodroid-glue.cc, src/native/monodroid/timezones.cc, src/native/monodroid/xamarin-android-app-context.cc, src/native/pinvoke-override/precompiled.cc, src/native/runtime-base/strings.hh, src/native/runtime-base/util.cc, src/native/shared/cpp-util.hh, src/native/shared/cxx-abi/terminate.cc, src/native/shared/helpers.cc, src/native/shared/helpers.hh, src/native/shared/new_delete.cc, src/native/tracing/native-tracing.cc, src/native/xamarin-debug-app-helper/debug-app-helper.cc
Android C API includes a function which allows the caller to set a
text message indicating the reason why the application is aborting
its execution using the `abort(3)` function, since the call doesn't
accept any parameters.  The message is then used in the native stack
trace (as well as in the application tombstone), which may be helpful
for us when reading crash reports which contain just the stack trace
and no context information.
Given the following code:
Helpers::abort_application (LOG_ASSEMBLY, "Testing abort stuff");
We will see the following logged in logcat:
F monodroid-assembly: Testing abort stuff
F monodroid-assembly: Abort at monodroid-glue.cc:825:2 ('void xamarin::android::internal::MonodroidRuntime::init_android_runtime(JNIEnv *, jclass, jobject)')
F libc    : Fatal signal …
=> [native] Let Android know what is our reason to abort()

Documentation/docs-mobile/TOC.yml, Documentation/docs-mobile/building-apps/build-properties.md, Documentation/docs-mobile/messages/index.md, Documentation/docs-mobile/messages/xa1038.md, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Resource.Designer.targets, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesignerIntermediateClass.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/InlineData.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Utilities/XmlUtils.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes https://github.com/dotnet/android/issues/9163
With the release of the new Resource Designer assembly we purposely removed the existing legacy `Resource.designer.cs` file from the `@(Compile)` ItemGroup. This is so that we did not get any clashes with the new system.
Unfortunately the name `Resource.designer.cs` is also used by developers as the name for the generated class when using `.resx` files. As a result we got the above bug report because the class was disappearing.
```
error CS0234: The type or namespace name 'Resources' does not exist in the namespace 'StringResourcesBug' (are you missing an assembly reference?)
```
It turns out that the `_RemoveLegacyDesigner` was being a bit too aggressive with its removal of files. Because it was matching on filename only it was removing …
=> .net8 Android not building because Resources from resx not found.

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
Some tests on the release/8.0.4xx branch have recently started failing
due to the following warning:
warning NU1903: Package 'System.Text.Json' 6.0.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-8g4q-xg66-9fp4
We've bumped these packages to 8.0.x in main, and should do the same
here to get the latest versions.
=> [tests] Bump System.Text.Json test package to 8.0.*

build-tools/create-packs/vs-workload.in.props
Context: https://github.com/dotnet/android/commit/ab079718118e2b84d7b529a1155138cd7c855e19
We've decided hold off on this change until .NET 10.
=> [nuget-msi-convert] Do not use new VS component IDs

.external
Changes: https://github.com/xamarin/monodroid/compare/352bcbe8cc06aeba358450f57846218ef274bf01...b753d75f846b76cabb3b65b52ac12c4a83c07a13
Updates the recommended Android SDK component feed to the latest d17-12 version.
=> Bump to xamarin/monodroid@b753d75f

src/native/monodroid/embedded-assemblies-zip.cc
Hash is always 64-bit, even on 32-bit platforms, use the correct
format (`%llx`) to fix incorrect value conversion on 32-bit targets.
=> Fix printf format for the library name hash

Directory.Build.props, build-tools/create-packs/Directory.Build.targets, build-tools/scripts/XAVersionInfo.targets
Context: https://github.com/dotnet/android/commit/0f2a3231c564b47acbbd4857c17ed9efe4bafcdc
Context: https://github.com/dotnet/android/commit/4ea5dbb921ccebb93f2a03d33169d2ebb6248936
Brings in stable versioning changes from previous .NET 8 and .NET 7
release branches.  We've historically added a few new version properties
to represent the stable version and calculate the patch delta.
`$(AndroidPackVersion)` has been updated to "reset" the commit distance.
=> [release/9.0.1xx] Use stable 35.0.x branding

Directory.Build.props
We branched for .NET 9 GA from b90c5590 into `release/9.0.1xx`; the main branch is now .NET 10 Preview 1.
Using 35.99.x for now, until we know that API 36 is a stable API.
=> $(AndroidPackVersionSuffix)=preview.1; main is 35.99.x

src/Xamarin.Android.Build.Tasks/Tasks/RemoveDirFixed.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/RemoveDirTests.cs
Fixes https://github.com/dotnet/android/issues/9133
Context: https://learn.microsoft.com/visualstudio/msbuild/copy-task?view=vs-2022
The Design Time Build (DTB) seems to lock files and directories during its build process. 
This is not by design it is just that sometimes a build will try to do something with a 
file that the DTB already has open.
Users will sometimes see this error.
```
Error (active)	XARDF7019	System.UnauthorizedAccessException: Access to the path 'GoogleGson.dll' is denied.
at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
at …
```
=> Add retry ability to RemoveDirFixed

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10431207&view=ms.vss-test-web.build-test-results-tab&runId=114098346&resultId=100000&paneView=debug
The `FastDeployEnvironmentFiles(false)` test fails on PRs from forks, because the "Fast Deployment" feature is not included in OSS builds.
The problem appears to be related to target ordering:
* `_GetGenerateJavaStubsInputs` : uses `@(AndroidEnvironment)` to set `@(_EnvironmentFiles)`
* `_GetGenerateJavaStubs` : must have same `Inputs` as `_GeneratePackageManagerJava`
* `_GeneratePackageManagerJava`: actually uses `@(_EnvironmentFiles)`
* `_GenerateEnvironmentFiles` : creates a new `@(AndroidEnvironment)` file, that won't be used!
But when using either a `Release` build or `Debug` build with `FastDev` enabled, everything …
=> [Xamarin.Android.Build.Tasks] fix $DOTNET_MODIFIABLE_ASSEMBLIES when FastDev is off

src/Microsoft.Android.Sdk.ILLink/PreserveLists/Java.Interop.xml, src/Microsoft.Android.Sdk.ILLink/PreserveLists/Mono.Android.xml, src/Mono.Android/Java.Lang/Object.cs, src/Mono.Android/Java.Lang/Throwable.cs, src/native/monodroid/monodroid-glue.cc, src/native/monodroid/osbridge.cc, src/native/monodroid/osbridge.hh
Context: https://github.com/dotnet/java-interop/issues/1255
Context: https://github.com/xamarin/monodroid/commit/a5c52905293d7eecdb3c078da62100081b338045
Context: https://issuetracker.google.com/issues/36986478
Context: https://github.com/dotnet/android/blob/b56d68fe2a2c2dffa47eb7e41ae08a00fda86367/Documentation/workflow/SystemProperties.md#debugmonowref
Android did not support [JNI Weak Global References][0] until API-8 (Android 2.2).  To allow Mono for Android applications to run on API-7 and earlier devices, while using JNI Weak Global References when possible (fewer GC allocations, better performance), the GC bridge supported two modes of operation:
* `debug.mono.wref=jni`: Use JNI Weak Global References.
* `debug.mono.wref=java`: Use [`java.lang.ref.WeakReference`][1].
With the …
=> [native, Mono.Android] Remove WeakReference support

src/Xamarin.Android.Build.Tasks/Resources/MonoRuntimeProvider.Bundled.java, src/java-runtime/java/mono/android/MonoPackageManager.java
We use [`ApplicationInfo.splitSourceDirs`](https://developer.android.com/reference/android/content/pm/ApplicationInfo#splitSourceDirs) to detect whether the application uses split config files.
Those files are created by Android when an AAB is used to deploy application (e.g. via Google Play Store).
When they are present, the base APK file doesn't contain any `lib/` directories and we can simply skip
scanning it for those entries, thus saving on startup time.  We used to check whether there are more than
one entry in `splitSourceDirs`, which used to be the case, but it seems that the recent Android versions
(at least API 33 and newer) can have just a single entry in the array.  Because of that, we were scanning
all the APK files on those Android versions, wasting time at startup.
Fix the …
=> Simplify and fix split configs detection

build-tools/scripts/DotNet.targets
Our MAUI integration lane currently fails with:
Workload installation failed: Version 34.0.145 of package microsoft.android.sdk.windows is not found in NuGet feeds...
They are missing the `darc-pub-dotnet-android-df9aaf2-1` feed containing our .NET 8 package on the dotnet/maui/net9.0 branch.
To fix this, let's read our `NuGet.config` and add any sources that start with `darc-pub-dotnet-android-*` into their `NuGet.config`.
Going forward, the lane should work without issue.
=> [build] fix missing `darc-pub-dotnet-android-*` feed for MAUI

Documentation/docs-mobile/TOC.yml, Documentation/docs-mobile/binding-libs/advanced-concepts/native-library-interop.md, Documentation/docs-mobile/building-apps/build-items.md, Documentation/docs-mobile/building-apps/build-process.md, Documentation/docs-mobile/building-apps/build-properties.md, Documentation/docs-mobile/building-apps/build-targets.md, Documentation/docs-mobile/messages/index.md, Documentation/docs-mobile/messages/xa0141.md, build-tools/scripts/sync-mobile-docs.ps1
The `docs-mobile` content has been synced with https://github.com/dotnet/docs-mobile/commit/9ccd7291ce358a14b3c027a54be8726956372501.
A `build-tools/scripts/sync-mobile-docs.ps1` script has been added to improve this workflow in the future. The default sync direction is from dotnet/android to dotnet/docs-mobile as content is typically authored in this repo first.
To sync, run the following:
pwsh build-tools/scripts/sync-mobile-docs.ps1 -DocsMobilePath ~/source/docs-mobile
To sync content back from docs-mobile to android, run the following:
pwsh build-tools/scripts/sync-mobile-docs.ps1 -DocsMobilePath ~/source/docs-mobile -SyncToAndroid
=> [docs] Sync docs with dotnet/docs-mobile@9ccd7291

build-tools/automation/azure-pipelines-apidocs.yaml, build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/yaml-templates/build-macos.yaml
Removes our dependency on the Android specific build pool, which should
reduce overall pool maintenance effort and cost.
The `VSEng-VSMac-Xamarin-Shared` pool is used by a handful of teams and
also consists of physical macOS machines that should be more performant
than the hosted options.
=> [release/8.0.4xx ][ci] Move PR build to shared pool

Xamarin.Android.sln
Fixes: #9487 
We removed the `Java.Interop.NamingCustomAttributes.shproj` project in https://github.com/dotnet/java-interop/pull/787, however it still exists in the `Xamarin.Android.sln` file.
Remove the `Java.Interop.NamingCustomAttributes.shproj` project from the `Xamarin.Android.sln` file.
=> [Xamarin.Android.sln] Remove `Java.Interop.NamingCustomAttributes.shproj`.

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Microsoft.Android.Sdk.Bindings.Gradle.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidGradleProjectTests.cs
The AndroidGradleProject targets have been updated to fix some issues we
ran into when trying to use this new build action in the MAUI build.
The default output path property will now check to see if it is rooted
before adding a `$(MSBuildProjectDirectory)` prefix to make it an
absolute path. The property name has also been shortened. This fixes
projects/builds that set `$(BaseIntermediateOutputPath)` or
`$(IntermediateOutputPath)` to an absolute path that would hit an error
along the lines of:
D:\a\_work\1\s\.dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.0-rc.2.152\tools\Microsoft.Android.Sdk.Bindings.Gradle.targets(73,5): error XACPR7024: System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : …
=> [Build.Tasks] Better handle gradle project custom output paths

src/Mono.Android/Android.Runtime/AndroidRuntime.cs, src/native/monodroid/monodroid-glue.cc, src/native/monodroid/osbridge.cc, src/native/monodroid/osbridge.hh, src/native/runtime-base/logger.cc, src/native/runtime-base/logger.hh
[native, Mono.Android] GC bridge logging improvements
Context: https://github.com/dotnet/android/issues/9039
While trying to further diagnose #9039, @jonpryor started fearing
that a GC bridge issue might be at play, but the current GC bridge
logging could use some improvements.
Update `OSBridge::take_weak_global_ref_jni()` to do two things:
1. Set the `handle` and `handle_type` fields *before* deleting the
original GREF.  This is for a hypothetical thread-safety issue
wherein the `handle` field and the `Handle` property could return
a *deleted* GREF before being updated to the "new" Weak GREF.
We have not seen this as being an issue in practice, but it's
something we noticed.  If it did happen, the app would crash and
a JNI error message would be present in `adb logcat`, a'la:
JNI …
=> [native, Mono.Android] GC bridge logging improvements

src/Mono.Android/Android.Runtime/AndroidEnvironment.cs, src/Mono.Android/Android.Runtime/Logger.cs, src/Mono.Android/ILLink/ILLink.Substitutions.xml, src/Mono.Android/Java.Interop/TypeManager.cs, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs
Context: https://developercommunity.visualstudio.com/t/XamarinAndroid-Designer---Replacement/10728132
Context: 363935b4
As the Android designer is no longer supported in Visual Studio, we are removing the `Xamarin.Android.VSAndroidDesigner.IsSupported` feature switch and `$(VSAndroidDesigner)` MSBuild property.
This removes the codepath for Java types at runtime (on desktop) via `TypeManager.TypeRegistrationFallback()`. This also removes a `Console.WriteLine()` call when `liblog` and `__android_log_print` cannot be found.
=> [Mono.Android] remove `Xamarin.Android.VSAndroidDesigner.IsSupported` feature switch

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props
One of the "gotchas" with `AutoImport.props`, is the file is imported by literally *all* .NET projects. Even .NET 8 and .NET 9 Android projects import their files on top of each other...
This means every `<ItemGroup>` needs a `Condition` that checks:
* is this Android?
* is this the expected .NET framework version?
`<ItemGroup>`s in `AutoImport.props` should have, something like:
<ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'android' and $([MSBuild]::VersionEquals($(TargetFrameworkVersion), '9.0')) ">
`$(EnableDefaultAndroidItems)` checks also work for some cases, but .NET MAUI turns this off in favor of their own wildcards:
https://github.com/dotnet/maui/blob/f269ef3de701043910c941bbbfcbdb7422cc245c/src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Mau …
=> [Xamarin.Android.Build.Tasks] add missing `Condition` in `AutoImport.props`

build-tools/automation/azure-pipelines.yaml, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, tests/Mono.Android-Tests/Mono.Android-Test.Shared.projitems, tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj, tests/Mono.Android-Tests/System.Xml/XmlSerializer.cs
Currently, users can experience runtime crashes related to the use of `DefaultValue` attributes (taking type and string) without any trim warnings (see https://github.com/dotnet/runtime/issues/109724). This is because the trim warnings are disable in partial trim mode and this use-case of `DefaultValue` attributes is not trim compatible.
Workaround around this is to enable `_DefaultValueAttributeSupport` to prevent customer apps from crashing without trim warnings. App will still crash in `TrimMode="full"` but user would get warned during compile time.
=> Enable `DefaultValueAttributeSupport` in partial trim mode.

src/manifestmerger/build.gradle, src/manifestmerger/manifestmerger.targets
Bumps com.android.tools.build:manifest-merger from 30.3.1 to 31.7.2.
This is a new version of #9500 with a shorter branch name.
=> Bump com.android.tools.build:manifest-merger from 30.3.1 to 31.7.2

THIRD-PARTY-NOTICES.TXT, Xamarin.Android.sln, build-tools/installers/create-installers.targets, build-tools/xaprepare/xaprepare/ThirdPartyNotices/Xamarin.Android.Build.Tasks.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/proguard-android/.gitignore, src/proguard-android/build.gradle, src/proguard-android/proguard-android.csproj, src/proguard-android/proguard-android.targets, src/proguard-android/settings.gradle
Context: https://discord.com/channels/732297728826277939/732297837953679412/1303383272918618163
A customer found their app grew in size when building on Windows
versus macOS.
The difference being a file that was passed to the `<R8/>` task on
Windows, but not on macOS:
C:\Users\[username]\AppData\Local\Android\Sdk\tools\proguard\proguard-android.txt
`tools` is *ancient*, as any Android SDK should be using
`cmdline-tools` now.
Let's stop using this file as a default set of proguard rules.
But we need to use the *right* set of proguard rules, reading
the text of the old one:
> This file is no longer maintained and is not used by new (2.2+)
> versions of the # Android plugin for Gradle. Instead, the Android
> plugin for Gradle generates the # default rules at build time and
> stores them in …
=> [Xamarin.Android.Build.Tasks] redistribute `proguard-android.txt` from Android gradle plugin

src/Mono.Android/Java.Interop/TypeManager.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs, tests/Mono.Android-Tests/Java.Interop/JavaObjectExtensionsTests.cs, tests/Mono.Android-Tests/Mono.Android-Test.Shared.projitems, tests/Mono.Android-Tests/java/net/dot/android/test/Example.java, tests/Mono.Android-Tests/java/net/dot/android/test/ValueProvider.java
Fixes: https://github.com/dotnet/android/issues/9535
Context: a017561b1e44c51a9af79fae0baaa50fe01c4123
Context: 35f41dcc7cf5eb65dc12d7c0a3421e67c2bdb6d6
Create a new .NET for Android project (`dotnet new android`), add
a `@(PackageReference)` to [Xamarin.AndroidX.Media3.ExoPlayer][0],
and add the following code:
var builder = new AndroidX.Media3.ExoPlayer.ExoPlayerBuilder(this);
var player = builder.Build();
Build and run in *Debug* configuration, and it crashes:
System.ArgumentException: Could not determine Java type corresponding to `AndroidX.Media3.ExoPlayer.IExoPlayerInvoker, Xamarin.AndroidX.Media3.ExoPlayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null`. (Parameter 'targetType')
at Java.Interop.TypeManager.CreateInstance(IntPtr handle, JniHandleOwnership transfer, Type …
=> [Xamarin.Android.Build.Tasks] Invokers after abstracts in typemaps

.external, .gitignore, build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/build-linux.yaml, build-tools/automation/yaml-templates/commercial-build.yaml, build-tools/installers/create-installers.targets, build-tools/scripts/BuildEverything.mk, build-tools/scripts/DotNet.targets, build-tools/scripts/msbuild.mk, build-tools/xaprepare/xaprepare/Steps/Step_PrepareExternalGitDependencies.cs
Bumps external components to https://devdiv.visualstudio.com/DevDiv/_git/android-platform-support/commit/cdef164e7eef35128f74fa1f3ecbd7a878953a43
A new android-platform-support Azure Repo has been created in the DevDiv
project containing library code from the xamarin/androidtools,
xamarin/monodroid, and xamarin/android-sdk-installer repos.
The build has been updated to build and package all required closed
source components from the new Azure Repo.
=> [ci] Use new DevDiv/android-platform-support repo

.external
Changes: https://devdiv.visualstudio.com/DevDiv/_git/android-platform-support/branchCompare?baseVersion=GCc22e86517918f75cdf147b12252361d90c6577bd&targetVersion=GC457de82bb5f8b7a8ee072177fde885e2e391b3bb
* Merged PR 594791: Ensures JavaSDK is installed previous to AndroidSDK
=> Bump to DevDiv/android-platform-support@457de82b

Documentation/guides/MSBuildBestPractices.md
This otherwise great article is a bit out-dated.  I kept the work-around as I thought it was fairly elegant knowledge on how MSBuild can be customized that is not quite explained well elsewhere.
=> Add $(IncrementalCleanDependsOn) property tip

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64SimpleDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/BuildReleaseArm64XFormsDotNet.apkdesc, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: 27b5d2e5da2c0083bd80b9e621029fefb49d2e1e
This reverts commit afb5f7ebfba33aa7f8b69848bb2f87a4c2c1f866 which disabled them.
The problem which caused Blazer (and some other) applications to fail was fixed 
in 27b5d2e5da2c0083bd80b9e621029fefb49d2e1e
=> Enable marshal methods by default

Configuration.props, build-tools/create-packs/ConfigureLocalWorkload.targets, build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/Microsoft.Android.Runtime.proj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/in/Microsoft.Android.Sdk.BundledVersions.in.targets, src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs
Right now our runtime packs are all identical for each .NET "runtime", but we want to be able to produce different packs, such as:
Microsoft.Android.Runtime.Mono.35.android-arm
Microsoft.Android.Runtime.Mono.35.android-arm64
Microsoft.Android.Runtime.Mono.35.android-x86
Microsoft.Android.Runtime.Mono.35.android-x64
Microsoft.Android.Runtime.NativeAOT.35.android-arm
Microsoft.Android.Runtime.NativeAOT.35.android-arm64
Microsoft.Android.Runtime.NativeAOT.35.android-x86
Microsoft.Android.Runtime.NativeAOT.35.android-x64
Currently, the contents of all these packs are identical, but this is an initial step to build multiple packs.
The plan is for the workload to only install the "Mono" packs, and the "NativeAOT" packs can be restored via NuGet.
=> [build] produce multiple "flavors" of runtime packs

src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Tasks/MavenDownload.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/MavenDownloadTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/ITaskItemExtensions.cs, src/Xamarin.Android.Build.Tasks/Utilities/MavenExtensions.cs
Fixes: https://github.com/dotnet/android/issues/9465
In all of the examples we used when developing and testing `@(AndroidMavenLibrary)` the Maven artifact filename followed the pattern `{artifact.Id}-{artifact.Version}.[jar|aar]`, so this is the default filename we construct for the user.  
However, there exists some packages like React that do not follow this pattern and instead do eg: `react-android-0.76.0-release.aar`. Attempting to use `@(AndroidMavenLibrary)` for React produces the following error:
```
error XA4236: Cannot download Maven artifact 'com.facebook.react:react-android'.
error XA4236: - react-android-0.76.0.jar: Response status code does not indicate success: 404 (Not Found).
error XA4236: - react-android-0.76.0.aar: Response status code does not indicate success: 404 …
```
=> [XABT] Add `ArtifactFilename` metadata for `@(AndroidMavenLibrary)` item.

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
I've noticed we are randomly seeing a test failure like:
Build_AndroidResource_Change
Exceeded expected time of 2250ms, actual 2992.086ms
Sometimes, it passes and sometimes not.
Reviewing the `.binlog` I noticed under the top 10 expensive tasks:
GenerateJniRemappingNativeCode = 97 ms, 1 calls.
Which I found by the target:
_GenerateEmptyAndroidRemapNativeCode
Building target "_GenerateEmptyAndroidRemapNativeCode" completely.
Input file "/Users/runner/work/1/a/TestRelease/11-21_21.07.33/temp/BuildAndroidResourceChange/UnnamedProject.csproj" is newer than output file "obj/Debug/android/jni_remap.x86_64.ll".
Which has the `Inputs/Outputs`:
Inputs="$(MSBuildProjectFullPath)"
Outputs="@(_AndroidRemapAssemblySource)"
Reviewing the target, it feels like we should fix the `Inputs` and `Outputs`, …
=> [Xamarin.Android.Build.Tasks] fix incremental builds for `_GenerateAndroidRemapNativeCode`

build-tools/automation/azure-pipelines.yaml, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
We've been seeing some strange output in the Azure Pipelines test output
pane when apkdiff fails. This change should hopefully clean that up and
instead upload an apkdiff.log file with the tools output when a related
test fails.
An issue with Mono.Android.NET_Tests Debug apk uploading has also been fixed.
=> [tests] Add apkdiff output to test attachment file

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Application.targets, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
Context: https://github.com/dotnet/sdk/issues/42155
Context: https://github.com/dotnet/sdk/pull/42240
Fixes: https://github.com/dotnet/sdk/issues/31253
The .NET SDK has introduced a new `ComputeRunArguments` MSBuild target that allows you to set `$(RunCommand)` and `$(RunArguments)` in a more dynamic way.
So, on Android:
* `ComputeRunArguments` depends on `Install`, so the app is deployed, the `<FastDeploy/>` MSBuild target runs, etc.
* `$(RunCommand)` is a path to `adb`
* `$(RunArguments)` is an `shell am start` command to launch the main activity.
The new implementation also allows us to use the `-p` parameter with `dotnet run`, such as:
dotnet run -bl -p:AdbTarget=-d
This will pass `-d` to `adb`, which allows you to select an attached device if an emulator is running.
Previously, we …
=> [Xamarin.Android.Build.Tasks] implement `dotnet run` with an MSBuild target

src/Xamarin.Android.Build.Tasks/Properties/Resources.cs.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.de.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.es.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.fr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.it.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ja.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ko.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pl.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.pt-BR.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.ru.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.tr.resx, src/Xamarin.Android.Build.Tasks/Properties/Resources.zh-Hans.resx
=> Localized file check-in by OneLocBuild Task: Build definition ID 17928: Build ID 10645592

.external
Changes: https://devdiv.visualstudio.com/DevDiv/_git/android-platform-support/branchCompare?baseVersion=GCc22e86517918f75cdf147b12252361d90c6577bd&targetVersion=GC52dd010acff1fa00d172609c231b7ee7b56b94a3
* Merged PR 594914: [InstallAndroidDependencies] Correctly init CommonUtilities.Helpers
* Merged PR 595751: [build] Use flexible cmake path
* Merged PR 595711: [oneloc] Fix lcl file paths
* Merged PR 594792: Ensures JavaSDK is installed previous to AndroidSDK
* Merged PR 594160: [OneLoc] Fix LocProject and OneLoc build pipeline
=> Bump to DevDiv/android-platform-support@52dd010a

Localize/loc/zh-Hant/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx.lcl
LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241203113739719 to main with localized lcls
=> LEGO: Pull request from juno/hb_6dddf33b-c6da-43d8-ac04-14d2c339cb00_20241203113739719 to main

.external, .gitmodules
Changes: https://devdiv.visualstudio.com/DevDiv/_git/android-platform-support/branchCompare?baseVersion=GC457de82bb5f8b7a8ee072177fde885e2e391b3bb&targetVersion=GCdf3620a12d632d018211985921374a88303ce4cd
* Merged PR 596023: [release/9.0.1xx] Bump to dotnet/android-tools@f742b155
* Merged PR 595816: Merged PR 595751: [build] Use flexible cmake path
* Merged PR 595817: Merged PR 594914: [InstallAndroidDependencies] Correctly init CommonUtilities.Helpers
Changes: https://github.com/dotnet/android-tools/compare/60fae1924e2d71f31dc1ed05f7346fd7874d6636...f742b1555fc78b6a7c105e38dd3efe3bea6ab138
* dotnet/android-tools@f742b15: Add support to discovering activity-alias activity elements
=> [release/9.0.1xx] Bump android-platform-support, android-tools

build-tools/xaprepare/xaprepare/Scenarios/Scenario_AndroidTestDependencies.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallAdoptOpenJDK.cs
The JDK install step has been updated to optionally skip installation
if a close enough match is found in the $(JI_JAVA_HOME) directory. This
should allow us to skip JDK provisioning on our test lanes.
=> [ci] Skip JDK install if near match is found in $(JI_JAVA_HOME)

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
***Note this PR is against the `release/9.0.1xx` branch.***
The MSBuild property `$(AndroidCreatePackagePerAbi)` is likely not used much anymore due to Google Play and Amazon stores both moving to the `.aab` format.  Removing it in .NET 10 will allow us to simplify our `BuildApk` MSBuild code.
Add a deprecation warning to .NET 9 for `$(AndroidCreatePackagePerAbi)` to inform users that it will be removed in .NET 10.
The workaround is to use the `-r` specifier when calling `dotnet build` if you still need to create individual `.apk` files per ABI:
```
dotnet build -c Release -r android-arm64
dotnet build -c Release -r android-x64
```
=> [XABT] Add deprecation warning for `$(AndroidCreatePackagePerAbi)`.

src/native/monodroid/debug.cc, src/native/monodroid/embedded-assemblies-zip.cc, src/native/monodroid/embedded-assemblies.cc, src/native/monodroid/embedded-assemblies.hh, src/native/monodroid/globals.cc, src/native/monodroid/globals.hh, src/native/monodroid/internal-pinvokes.cc, src/native/monodroid/monodroid-glue-internal.hh, src/native/monodroid/monodroid-glue.cc, src/native/monodroid/osbridge.cc, src/native/monodroid/xamarin_getifaddrs.cc, src/native/runtime-base/android-system.cc, src/native/runtime-base/android-system.hh, src/native/runtime-base/cpu-arch-detect.cc, src/native/runtime-base/jni-wrappers.hh, src/native/runtime-base/shared-constants.hh, src/native/runtime-base/util.hh, src/native/shared/cpp-util.hh
Continued effort to restructure our native C++ runtime, introducing
C++23 features as well as turning as many classes into static ones since
we don't really have objects that need to be created and destroyed during
lifetime of the application:
* Replace `abort_if*` preprocessor macros with templated functions. This
gives us better type safety.  Instead using variadic arguments, we now
provide overloads which take either a plain string without placeholders
or a lambda function to format the message string on demand.
* More `std::string_view` for literal strings
* More functions decorated with `noexcept` (this is going to be important
once exceptions are enabled in the future)
* Remove some unused code.
=> More C++ tweaks and changes

NuGet.config, eng/Version.Details.xml, eng/Versions.props
Changes: https://github.com/dotnet/android/compare/df9aaf29a52042a4fbf800daf2f3a38964b9e958...a8cd27e430e55df3e3c1e3a43d35c11d9512a2db
=> Bump .NET 8 SDK to a8cd27e4 34.0.147

src/Xamarin.Android.Build.Tasks/Tasks/AndroidComputeResPaths.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Fixes #9588 
Adding a new Android resource to a project causes the incremental build to error with:
```Resources\layout\activity_two.xml error APT2126: file not found.```
This error comes from the Aapt2Compile task. It is looking for \obj\Debug\net9.0-android\res\layout\activity_two.xml but that file doesn't exist. 
What was happening is the new file had the same modified date as the flag/stamp file that was used to generate it. 
The user was using `copy Resources\layout\activity_main.xml Resources\layout\activity_two.xml`. So the modified date was not "new". This caused the `_GenerateAndroidResourceDir` target to get skipped. 
What we should do is copy what we do in other places, and hash all the input files (and their destinations) into one hash. 
We can then use that hash file as an …
=> Fix AndroidResource Incremental build issue

src/manifestmerger/build.gradle
Context: https://github.com/dotnet/android/pull/9581
Bumps com.android.tools.build:manifest-merger from 31.7.2 to 31.7.3.
---
updated-dependencies:
- dependency-name: com.android.tools.build:manifest-merger dependency-type: direct:production update-type: version-update:semver-patch ...
=> Bump com.android.tools.build:manifest-merger in /src/manifestmerger

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/CodeBehind/BuildTests/CodeBehindBuildTests.NET.csproj
Eventually we want user to migrate to the Resource Designer Assembly. So we should deprecate these properties.
=> Deprecate `AndroidResgenFile` and `AndroidUseIntermediateDesignerFile`

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NativeAOT.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
This is an initial step to get the NativeAOT build working the same as
iOS does. At a high level, the changes are:
* Run `ILLink` with our existing trimmer/linker pipeline.
* Temporarily change our RID to `linux-bionic-arm64`.
* Pass the output to `ILC`, the NativeAOT compiler.
* Turn the RID back to `android-arm64`.
A list of MSBuild/workload changes required so far:
* `$(UseMonoRuntime)` is false when `$(PublishAot)` is true
* Set `$(_IsPublishing)` as NativeAOT expects `dotnet publish` to be
the only way NativeAOT is used. Setting this in our targets allows
the proper `*.NativeAOT.*` packs to restore inside of a `dotnet
build`.
* `$(SelfContained)=true`, seems to be required for the
`linux-bionic-arm64` runtime packs to restore. All Android apps are
self-contained, so this might be …
=> [NativeAOT] MSBuild-related logic to get projects to build

src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android.Runtime/RuntimeNativeMethods.cs, src/native/monodroid/internal-pinvokes.cc, src/native/pinvoke-override/generate-pinvoke-tables.cc, src/native/pinvoke-override/pinvoke-tables.include, src/native/runtime-base/internal-pinvokes.hh
In a NativeAOT context, we don't have `libmonodroid.so` *at all*. This makes methods like `JNIEnv.GetIdentityHashCode()` non-functional, as it p/invokes into `_monodroid_get_identity_hash_code`.
Remove `_monodroid_get_identity_hash_code`, in favor of:
return JniEnvironment.References.GetIdentityHashCode (new JniObjectReference (v));
Which should have negligible performance impact and works without `libmonodroid.so`.
=> [monodroid] remove `_monodroid_get_identity_hash_code`

src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android.Runtime/JNIEnvInit.cs, src/Mono.Android/Android.Runtime/JNINativeWrapper.cs, src/Mono.Android/Android.Runtime/Logger.cs, src/Mono.Android/Java.Interop/TypeManager.cs, src/native/monodroid/internal-pinvokes.cc, src/native/pinvoke-override/generate-pinvoke-tables.cc, src/native/pinvoke-override/pinvoke-tables.include, src/native/runtime-base/internal-pinvokes.hh
In a NativeAOT context, we don't have `libmonodroid.so` *at all*.
Let's remove the `monodroid_get_log_categories()` function, as we
already pass in `args->logCategories` at startup. We can use a new
`Logger.SetLogCategories()` method to pass the value in.
I also removed `JNIEnvInit.LogAssemblyCategory`, as we can just use
the `Logger` class instead.
The startup sequence in C++ seems OK, so doesn't seem like this
changes any behavior:
* `Java_mono_android_Runtime_initInternal()` sets up logging
categories very early in startup.
* `create_and_initialize_domain()` calls...
* `init_android_runtime()` calls...
* Calls managed code, `JNIEnvInit.Initialize()` using the correct
logging categories.
=> [monodroid] remove `monodroid_get_log_categories()`

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/in/Microsoft.Android.Sdk.BundledVersions.in.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NativeAOT.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
* Introduce `$(_AndroidNativeAot)` to be used throughout a build to know if it is a NativeAOT build. The logic for detecting a NativeAOT build will likely change for Debug vs Release in the future.
* Skip generation of `mono.MonoRuntimeProvider` for NativeAOT and don't emit the value in `AndroidManifest.xml`.
* For a project, `Hello.csproj` ensure that a native library, `libHello.so` is created. Use `@(LinkerArg)` and `%(ArchiveFileName)` to ensure that the native library is renamed with a `lib` prefix.
* Update the `NativeAOT` MSBuild test to verify these changes.
=> [NativeAOT] improve build logic, part 1

src/Mono.Android/Android.Graphics/Color.cs, src/Mono.Android/Android.Runtime/IJavaObjectValueMarshaler.cs, tests/api-compatibility/acceptable-breakages-vReference-net9.0.txt
Changes: https://github.com/dotnet/java-interop/compare/f800ea52dce62f126926d4b96121681508d506a1...2c06b3c2a11833aea0e9b51aac2a72195bd64539
* dotnet/java-interop@2c06b3c2: [Java.Interop] remove `DynamicallyAccessedMemberTypes.Interfaces` (dotnet/java-interop#1285)
=> Bump to dotnet/java-interop/main@2c06b3c2

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NativeAOT.targets, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Utilities/JCWGenerator.cs
This is another set of changes to Android apps to *run* under NativeAOT:
* Default to `$(TrimMode)=Full` for NativeAOT, this enables trimmer warnings and should be the default mode for NativeAOT.
* Ensure `_PrepareLinking` MSBuild target runs at the appropriate time. This was causing `Android.App.Activity`'s `GetOnCreate_Landroid_os_Bundle_Handler()` to get trimmed away.
* Default to `$(LinkerFlavor)=lld` to avoid a `java.lang.UnsatisfiedLinkError` at runtime.
* Include `libc++_shared.so` to avoid a `java.lang.UnsatisfiedLinkError` at runtime.
* Emit `JavaPeerStyle.JavaInterop1` java stubs for NativeAOT, as it is easier to get working in place of `JavaPeerStyle.XAJavaInterop1`.
I updated our existing `NativeAOT()` test to assert for these changes where possible.
=> [NativeAOT] improve build logic, part 2

build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml
The "WearOS Test" job regularly takes over an hour to complete.  Split the tests it runs into 2 parallel jobs to reduce the time taken to complete the stage.
=> [CI] Set "WearOS Tests" parallelization to 2 agents.

tools/workload-dependencies/WorkloadDependencies.proj
Commit b716173a added the ability to generate the workload.json file. However there was a bug where the `$(DotNetStableTargetFramework)` was not being defined for the workload-dependencies.csproj. This would resolve in the following error
```
bin/Release/dotnet/sdk/9.0.100-rtm.24512.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(96,5): error NETSDK1013: The TargetFramework value '' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.
```
The problem was that the `DotNetStableTargetFramework` property was not being passed on to the `dotnet run` call in WorkloadDependencies.proj. The CI build was working because we define the `DotNetStableTargetFramework` …
=> Fix WorkloadDependencies.proj build.

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/stage-linux-tests.yaml, build-tools/automation/yaml-templates/stage-package-tests.yaml
The "Linux Tests" stage/job regularly approaches an hour runtime, after a ~17 minute Linux build.  This puts it beyond our "ideal" 1 hour PR CI build.
Manually split the job up into 2 jobs that each run in parallel to reduce the overall runtime.
=> [CI] Break "Linux Tests" into 2 parallel jobs.

build-tools/xaprepare/xaprepare/Steps/Step_InstallAdoptOpenJDK.MacOS.cs
Context: https://github.com/dotnet/android/pull/9651
Recent versions of macOS, Safari, and **tar**(1) [^0] interact such that if you manually download a tarball and extract it, *all the extracted files* contain the `com.apple.quarantine` extended attribute.  This is a security feature, but it also means that the provisioned JDK *cannot be used*:
% $HOME/android-toolchain/jdk-21/bin/javac
zsh: operation not permitted: ./jdk-21/bin/javac
Which in turn means if you do something "reasonable" like download Microsoft OpenJDK and place it into `$HOME/android-archives` -- so that `xaprepare` doesn't need to download it *again* -- then the provisioned JDK will be *unusable*.  Which makes @jonpryor sad.
Update `Step_InstallAdoptOpenJDK.MacOS.cs` to run
`xattr -d -r com.apple.quarantine …
=> [build+macOS] Remove quarantine from OpenJDK installations

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, src/Mono.Android/Profiles/api-Baklava.params.txt, src/Mono.Android/PublicAPI/API-36/PublicAPI.Unshipped.txt, src/Mono.Android/metadata
Context: https://developer.android.com/about/versions/16
Context: https://android-developers.googleblog.com/2024/12/second-developer-preview-android16.html
Android 16 Developer Preview 2 has been released.  The Android 16
* Nov/Dec: Developer Previews
* Jan/Feb: Unstable Betas
* Mar/Apr: Stable Betas
* ???: Final
Currently, this will be usable in its preview form to `main` users who explicitly target `net9.0-android36`.  Once we are shipping .NET 10 previews, it will be usable for users who explicitly target `net10.0-android36`.  We will need to decide on our strategy for backporting this to .NET 9 service releases.
`PublicApiAnalyzers` reports 2 categories of API changes …
=> [Mono.Android] Bind Android 16 DP2.

src/Xamarin.Android.Build.Tasks/Resources/MonoRuntimeProvider.Bundled.java, src/Xamarin.Android.Build.Tasks/Utilities/JCWGenerator.cs, src/java-runtime/java/mono/android/MonoPackageManager.java
We currently have code that loads `MonoRuntimeProvider.Bundled.java` and parses Java code comments between:
// Mono Runtime Initialization {{{
android.content.pm.ApplicationInfo applicationInfo = context.getApplicationInfo ();
String[] apks = null;
String[] splitApks = applicationInfo.splitSourceDirs;
if (splitApks != null && splitApks.length > 0) {
apks = new String[splitApks.length + 1];
apks [0] = applicationInfo.sourceDir;
System.arraycopy (splitApks, 0, apks, 1, splitApks.length);
} else {
apks = new String[] { applicationInfo.sourceDir };
}
mono.MonoPackageManager.LoadApplication (context, applicationInfo, apks);
// }}}
These lines are used for any `Instrumentation` type, such as:
https://github.com/dotnet/java-interop/blob/2c06b3c2a11833aea0e9b51aac2a72195bd64539/src/Java.Interop.To …
=> [java-runtime] simplify `mono.MonoPackageManager.LoadApplication()`

build-tools/automation/azure-pipelines-apidocs.yaml, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, src/Mono.Android/Mono.Android.targets
Updates xaprepare and Mono.Android to generate API Docs against API level 35 sources.
The azure-pipelines-apidocs.yaml pipeline has been updated to use the 1ES pipeline template to improve compatibility with existing yaml templates.
The semi-automated API docs build and update workflow uses the .NET framework version of Mdoc and the <RunMdoc/> target has been updated to continue to mirror that workflow. 
Bumps to dotnet/java-interop@fe00cef5:
https://github.com/dotnet/java-interop/compare/2c06b3c2a11833aea0e9b51aac2a72195bd64539...fe00cef5290a7e75b8e73e3044966a14e6c312c9
=> [Mono.Android] Generate API docs for API level 35

src/Xamarin.Android.Build.Tasks/Tasks/CollectAssemblyFilesForArchive.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Commit 6b91b042 split up the BuildApk task into their own Tasks to improve build performance. In that change the call to `CollectAssemblyFilesForArchive` was a no-op if `EmbedAssembliesIntoApk` was set to `False`. However it was still being called in the `_BuildApkFastDev` target, even though it had a condition which would skip the target entirely if `EmbedAssembliesIntoApk` was `False`.
So lets remove the call to `CollectAssemblyFilesForArchive` from `_BuildApkFastDev` completely. We can also remove the `EmbedAssemblies` property from the `CollectAssemblyFilesForArchive` task as it is no longer needed.
=> Remove call to CollectAssemblyFilesForArchive for Fast Deployment.

Documentation/docs-mobile/messages/xa0141.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AndroidLibraries.targets, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Tasks/GetImportedLibraries.cs, src/Xamarin.Android.Build.Tasks/Tasks/ReadLibraryProjectImportsCache.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Utilities/ELFHelper.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.EmbeddedResource.targets
Figuring out how to fix a `XA0141` error is almost impossible for an end user at this time. The default error message is
```
NuGet package '' version '' contains a shared library 'foo.so' which is not correctly aligned. See https://developer.android.com/guide/practices/page-sizes for more details
```
the assumption was that the NuGet package and Version would be available as metadata items on the 
MSBuild Items. Unfortunately that was not the case, so the data the user gets is empty. 
This commit adds the required Metadata to all NuGet Package references resolved by the project. This will allow us to propagate that data throughout the build Items as they are transformed. This will in the end mean we can provide a decent error message to the user. 
```
Shared library 'foo.so' must use 16 …
```
=> Add NugetPackageId Metadata to TaskItems

src/Microsoft.Android.Sdk.ILLink/Microsoft.Android.Sdk.ILLink.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj, tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj
Several of our projects that have not been NRT enabled import `.cs` files from other projects that do have NRT annotations.
This results in warning CS8632:
```
warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
```
We can allow NRT annotations without enabling NRT by adding `<Nullable>annotations</Nullable>` to these projects, fixing ~100 build warnings.
=> Add `$(Nullable)` = `annotations` to projects using NRT annotations without NRT enabled.

build-tools/automation/yaml-templates/build-linux.yaml, build-tools/automation/yaml-templates/build-macos.yaml, build-tools/automation/yaml-templates/build-windows.yaml, build-tools/automation/yaml-templates/fail-on-dirty-tree.yaml, build-tools/xaprepare/xaprepare/Steps/Step_ThirdPartyNotices.cs
When running `xaprepare` on Windows, your local `git` tree ends up dirty due to line ending changes in `THIRD-PARTY-NOTICES.txt`.
Update `xaprepare` to always normalize line endings to `Environment.NewLine` in `THIRD-PARTY-NOTICES.txt` to prevent this issue.
Additionally, these scenarios where the build unintentionally modifies git tracked files on some platforms are frustrating, so let's prevent them from happening in the first place.
Add a CI check to fail a build if any git tracked files were modified.
Example:
Clicking the error will show the modified file(s):
Source: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10799472&view=results
=> [ci] Fail build if any git tracked files were modified.

build-tools/gradle/gradle/wrapper/gradle-wrapper.properties, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Javac.targets, src/Xamarin.Android.Build.Tasks/Tasks/Javac.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in, tools/workload-dependencies/Program.cs, tools/workload-dependencies/WorkloadDependencies.proj
Context: https://github.com/dotnet/android/pull/9651
PR #9651 demonstrated that it was fairly straightforward to use JDK-21 on CI.  We don't want to fully bump to JDK-21, because we still support building with JDK-17, so we *at minimum* need to run tests on both JDK-17 and JDK-21.
As a "minimal introductory step", add support for JDK-21:
* Update to Gradle 8.12, for harmony with dotnet/java-interop.
* Update the `<Javac/>` task to use `javac --release N` when using JDK-17 and later.  JDK-11 doesn't support `javac --release`. (Why care about JDK-11?  Because .NET 8 still supports it, and this will make future cherry-picking easier.)
* Set `$(LatestSupportedJavaVersion)`=21.0.99, which removes the XA0030 error which would result from using JDK-21.
* Update `tools/workload-dependencies` to …
=> [build] Support JDK-21

build-tools/automation/azure-pipelines-apidocs.yaml, build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/build-windows.yaml, build-tools/automation/yaml-templates/commercial-build.yaml, build-tools/automation/yaml-templates/run-emulator-tests.yaml, build-tools/automation/yaml-templates/setup-jdk-variables.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/automation/yaml-templates/variables.yaml, build-tools/scripts/TestApks.targets, build-tools/xaprepare/xaprepare/Steps/Step_InstallAdoptOpenJDK.cs
Adds a `setup-jdk-variables.yaml` template to set the `JAVA_HOME` and 
`JI_JAVA_HOME` variables from a single script location.
A new `JI_JAVA_HOME_DEFAULT` variable will also be set to point to a
current JDK that can be used to run various Android SDK tools as needed.
Consolidating this logic should make it easier to update the default
JDK version we install and/or test against in the future.
Build jobs and some test jobs that run on custom agents will use the
default android-toolchain path that xaprepare installs into.
Most other test jobs will attempt to use the value of a preinstalled JDK
found at `$JAVA_HOME_$(JAVA_VERSION)_$(OS_ARCH)` if it is defined.
=> [ci] Add template for setting *JAVA_HOME vars

src/Microsoft.Android.Sdk.Analysis/Analyzers/CustomApplicationAnalyzer.cs, src/Microsoft.Android.Sdk.Analysis/Tests/DNAA0001Tests.cs, src/Microsoft.Android.Sdk.Analysis/Utilities/Utilities.cs
We are seeing the following error in maui apps.
```
error DNAA0001: Application class 'MainApplication' does not have an Activation Constructor 'MainApplication(IntPtr handle, JniHandleOwnership transfer)'. 
```
this is because they are using `global::Android.Runtime.JniHandleOwnership` rather than `Android.Runtime.JniHandleOwnership`. This causes our string comparisons to fail to we report a false error message.
Rather than using `.ToString()` we should switch over to using `QualifiedNameSyntax` and `IdentifierNameSyntax` to get the name of the class. This allows us to remove some string comparisons as we can now get the name of the class without the full namespace if it has a `global::` prefix.
=> Fix Analyser to work with global types

build-tools/automation/yaml-templates/setup-jdk-variables.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml, build-tools/automation/yaml-templates/stage-msbuild-tests.yaml, build-tools/automation/yaml-templates/stage-package-tests.yaml, build-tools/automation/yaml-templates/variables.yaml
Azure Pipelines now provides the `macos-14-arm64` image.  We can use this image to run our MSBuild tests on.  This is a benefit because it's nearly twice as fast and nowadays our Mac users are probably more likely to be running arm64.
Unfortunately it [does not support nested virtualization](https://github.com/actions/runner-images/issues/9460), so we can't run our emulator tests on this image.  Supposedly Apple added nested virtualization in MacOS 15, but Azure does not have `macos-15-arm64` images yet.  Hopefully we will be able to use those for emulator tests in the future.
Additionally:
- Update `apkdiff` to a [newer version with Apple Silicon support](https://github.com/radekdoulik/apkdiff/pull/8).
- Tweak agent count since we now need fewer Mac agents, but could use a couple more …
=> [ci] Run Mac MSBuild tests on `macos-14-arm64`

tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidClientHandlerTests.cs
Building on https://github.com/dotnet/android/pull/2279, the network tests in our "Packaging Tests" very frequently fail with `BadGateway`, indicating a server side problem.  
Our "fix" has been to rerun the tests until they pass.  This wastes a considerable amount of developer and CI resources.
Instead, let's detect this case and ignore the test so that it isn't reported as "failed".
=> [Mono.Android-Tests] Ignore "BadGateway" test failures.

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Utilities/AndroidRuntime.cs, src/Xamarin.Android.Build.Tasks/Utilities/JCWGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/dotnet/android/pull/9572#issuecomment-2593419505
Context: https://github.com/xamarin/xamarin-macios/blob/2009c571aa8a975ab0e0b1785e5484dbd64d6f9b/dotnet/targets/Xamarin.Shared.Sdk.targets#L1004-L1006
To align with xamarin/xamarin-macios, the following public MSBuild properties can be used to select a runtime for iOS, macOS, etc.:
* `$(UseMonoRuntime)=true`: MonoVM
* `$(UseMonoRuntime)=false`: CoreCLR
* `$(PublishAot)=true`: NativeAOT
* Defaults if blank, select MonoVM
Introduce a private `$(_AndroidRuntime)` property we can use throughout our build to know which runtime is being targetted.
This way, if a new property is designed in the future, we can keep using `$(_AndroidRuntime)` and simply update the defaults.
=> [Xamarin.Android.Build.Tasks] introduce `$(_AndroidRuntime)` property

build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Unix.cs
Our CI builds are frequently failing to download the `dotnet-install.sh` script from the official .NET website due to an `AuthenticationException`.
Instead, grab the `dotnet-install.sh` script directly from GitHub to avoid the issue.
=> [CI] Grab 'dotnet-install.sh' script directly from GitHub.

.external, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Base/MainActivity.cs, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
Context 
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2305723
https://github.com/mattleibow/MauiAppWithMultipleIcons
Apparently launching an activity-alias was not supported at all. That probably means very few people use it, however we really should be able to launch them.
The changes to `android-platform-support` include the ability for `GetAndroidActivityName` to find `activity-alias` elements which have the correct metadata. This allows us to launch them via the typical `Run` command to launch them. 
Added a unit test.
=> Add activity-alias support

build-tools/xaprepare/xaprepare/Steps/Step_CopyExtraResultFilesForCI.cs, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Aapt2.targets, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Resource.Designer.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AndroidLibraries.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.BuildOrder.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceCaseMap.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateRtxt.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs, src/Xamarin.Android.Build.Tasks/Utilities/FileResourceParser.cs, src/Xamarin.Android.Build.Tasks/Utilities/ZipArchiveEntryExtensions.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.EmbeddedResource.targets, tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs, tests/msbuild-times-reference/MSBuildDeviceIntegration.csv
So one of the big issues we have with design time builds is the shear amount of time they take. 
This is principally because we have to discover and extract ALL the .aar/.zip files which we need before we can do a build. 
This used to be because we embedded the data into the assemblies, but we ship these resources as .aar file these days. 
So lets take advantage of that. 
Rather then extracting to disk and then reading the files from disk, we instead read the .aar directly for a design time build. We extract the required data into memory which will allow us to generate the required R.txt file. Note that only a small amount of data is needed from the .aar , its mostly entry filenames and the contents of any .xml/.axml file which we find in the `res` folder. So this will cut down the amount …
=> Rework Design Time Build to use .aar files directly.

build-tools/automation/azure-pipelines.yaml
Context: https://github.com/dotnet/maui/tree/net10.0
Context: https://github.com/dotnet/maui/pull/27040
dotnet/maui is using the `net10.0` branch for .NET 10.
=> [build] fix `MAUI Integration` lane

src/Xamarin.Android.Build.Tasks/Mono.Android/ApplicationAttribute.Partial.cs
Fixes: https://github.com/dotnet/android/issues/9705
When [converting the AndroidManifest attribute mappings system in .NET 9](https://github.com/dotnet/android/pull/8781), `ApplicationAttribute.ManageSpaceActivity` was not correctly mapped in the manual mapping.  It needs to follow the pattern other attributes of type `Type` follow, like `ActivityAttribute.ParentActivity`:
https://github.com/dotnet/android/blob/7454deb40ce06501831973e5186e2f71d0ecf804/src/Xamarin.Android.Build.Tasks/Mono.Android/ActivityAttribute.Partial.cs#L31-L37
With this change, the reported case in #9705 generates the proper AndroidManifest value:
```xml
<application ... android:manageSpaceActivity="crc64fe9411caa440e724.ManageSpaceActivity" ... >
```
=> [XABT] Fix `ApplicationAttribute.ManageSpaceActivity` manual mapping

Directory.Build.props, samples/HelloWorld/HelloLibrary/LibraryActivity.cs
Modern best practices for software development recommend treating warnings as errors. Although the majority of warnings are benign, warnings for any potential actual issues will be lost in the sea of benign warnings and will not be caught.
However, having to fix warnings during the development process can be annoying as code is often in a temporary state.  As a balance, we only error on warnings when building on CI.  This way local development isn't hindered, but CI will protect us from committing new warnings.
Developers can opt-in to the errors locally by setting `$(_AndroidTreatWarningsAsErrors)` to `true`.
There are several projects that have warnings today.  For now, we will simply grandfather those projects in, allowing us to move forward with protecting the rest of the projects …
=> Set `$(TreatWarningsAsErrors)` = `true` for CI builds.

src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceCaseMap.cs
We got a bug report that a DTB in VS results in the following error.
```
System.ArgumentOutOfRangeException: Positive number required.
Parameter name: bufferSize
at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
at Xamarin.Android.Tasks.GenerateResourceCaseMap.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceCaseMap.cs:line 94
at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25
```
We were passing `-1` as the bufferSize. While this is fine under .net 9/10. It seems the full .net framework does not like …
=> Fix an bug in the Design Time Build

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/install-dotnet-tool.yaml
A couple of scripts that added various tools to $PATH have been removed.
These were added when we were onboarding to the 1ES pipeline template
and testing new machine pool/image requirements. The Windows images
we're using have received many updates since then, and these workarounds
that updated $PATH are no longer necessary.
=> [ci] Remove test environment PATH additions

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NativeAOT.targets, src/Xamarin.Android.Build.Tasks/Tasks/SetNdkPathForIlc.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
In 2fa79549, we got Android projects *building* for NativeAOT. However, this didn't work at all on Windows.
Reviewing how NativeAOT's MSBuild targets are setup, they expect various tooling to be available in `%PATH%`.
To fix this:
* Create a new `<SetNdkPathForIlc/>` MSBuild task.
* That simply sets the Android NDK "bin" directory to `%PATH%`.
NativeAOT apps now successfully build (and run) on Windows. I also updated an integration test to verify this.
Unfortunately, we still have to set `$(DisableUnsupportedError)` or we will get the message:
D:\.nuget\packages\microsoft.dotnet.ilcompiler\10.0.0-alpha.1.25067.10\build\Microsoft.NETCore.Native.Publish.targets(61,5):
error : Cross-OS native compilation is not supported. Please use the appropriate OS-specific target.
A future change might …
=> [nativeaot] fix project builds on Windows

build-tools/gradle/gradle/wrapper/gradle-wrapper.properties, src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Javac.targets, src/Xamarin.Android.Build.Tasks/Tasks/Javac.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
Context: https://github.com/dotnet/android/pull/9651
PR #9651 demonstrated that it was fairly straightforward to use JDK-21 on CI.  We don't want to fully bump to JDK-21, because we still support building with JDK-17, so we *at minimum* need to run tests on both JDK-17 and JDK-21.
As a "minimal introductory step", add support for JDK-21:
* Update to Gradle 8.12, for harmony with dotnet/java-interop.
* Update the `<Javac/>` task to use `javac --release N` when using JDK-17 and later.  JDK-11 doesn't support `javac --release`. (Why care about JDK-11?  Because .NET 8 still supports it, and this will make future cherry-picking easier.)
* Set `$(LatestSupportedJavaVersion)`=21.0.99, which removes the XA0030 error which would result from using JDK-21.
=> [build] Support JDK-21 (#9672)

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, src/Mono.Android/Mono.Android.csproj, src/Mono.Android/Profiles/api-Baklava.params.txt
Context: https://developer.android.com/about/versions/16
Context: https://android-developers.googleblog.com/2025/01/first-beta-android16.html
Android 16 Beta 1 has been released.  The Android 16
* Nov/Dec: Developer Previews
* Jan/Feb: Unstable Betas
* Mar/Apr: Stable Betas
* ???: Final
Currently, this will be usable in its preview form to `main` users who explicitly target `net10.0-android36`.  Once we are shipping .NET 10 previews, it will be usable for users who explicitly target `net10.0-android36`.  We will need to decide on our strategy for backporting this to .NET 9 service releases.
Additional note(s):
- We cannot generate an updated `PublicAPI.Unshipped.txt` because this is done …
=> [Mono.Android] Bind Android 16 Beta 1.

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
Sets the default for switch added in https://github.com/dotnet/sdk/pull/46375.
(Should merge before we start consuming the SDK/runtime that has this.)
=> Set default for UseSizeOptimizedLinq

.gitmodules, tests/Mono.Android-Tests/Java.Interop-Tests/Java.InteropTests/AndroidValueManagerContractTests.cs
Changes: https://github.com/dotnet/java-interop/compare/9b1d8781e8e322849d05efac32119c913b21c192...e288589d92afc9edd9070638ebed72f67e310117
* dotnet/java-interop@e288589d: [Java.Interop] Add JniRuntime.JniValueManager.GetPeer() (dotnet/java-interop#1295)
* dotnet/java-interop@bbb15b71: [ci] Add dev/* branches to CI trigger (dotnet/java-interop#1297)
=> Bump to dotnet/java-interop/main@e288589d

src/Mono.Android/Android.App/Activity.cs, src/Mono.Android/Android.App/Dialog.cs, src/Mono.Android/Android.App/FragmentManager.cs, src/Mono.Android/Android.OS/AsyncTask.cs, src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android.Runtime/JavaArray.cs, src/Mono.Android/Android.Runtime/JavaCollection.cs, src/Mono.Android/Android.Runtime/JavaDictionary.cs, src/Mono.Android/Android.Runtime/JavaList.cs, src/Mono.Android/Android.Runtime/JavaSet.cs, src/Mono.Android/Android.Util/SparseArray.cs, src/Mono.Android/Android.Views/View.cs, src/Mono.Android/Android.Views/Window.cs, src/Mono.Android/Android.Widget/AdapterView.cs, src/Mono.Android/Android.Widget/ArrayAdapter.cs, src/Mono.Android/Java.Lang/Object.cs
Context: https://github.com/dotnet/android/pull/9630
Context: https://github.com/dotnet/java-interop/pull/1295
As an alternative to #9630...
For NativeAOT support, implement `Java.Lang.Object.GetObject()` using the new `JniRuntime.JniValueManager.GetPeer()` method.
This also cleans up a few things if `Java.Lang.Object` introduces an internal `DynamicallyAccessedMemberTypes Constructors` field.
=> [Mono.Android] Java.Lang.Object.GetObject<T>() implementation

Directory.Build.props
Context: https://github.com/dotnet/android/tree/release/10.0.1xx-preview1
We branched for .NET 10 Preview 1 from 3856e621 into `release/10.0.1xx-preview1`; the main branch is now .NET 10 Preview 2.
=> `$(AndroidPackVersionSuffix)`=preview.2

src/Xamarin.Android.Build.Tasks/Utilities/FileResourceParser.cs
Fixes #9735 
Building a Maui app we end up with the following error
```
System.IO.IOException: The process cannot access the file 'C:\Users\rumar\AppData\Local\Temp\Microsoft.Maui.Cache\NuGet\packages\xamarin.androidx.core\1.15.0.2\aar\androidx.core.core.aar' because it is being used by another process.
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Xamarin.Android.Tasks.FileResourceParser.Parse(String …
```
=> Don't Open .aar files with ReadWrite FileAccess

src/Xamarin.Android.Build.Tasks/Mono.Android/ApplicationAttribute.Partial.cs
Fixes: https://github.com/dotnet/android/issues/9705
Context: 3ab74db2c669fc234c6d60ed9884aecec8dfe61a
When converting `AndroidManifest.xml` attribute mappings in 3ab74db2, `ApplicationAttribute.ManageSpaceActivity` was not correctly mapped in the manual mapping.
The result is that if the property is used:
[assembly: Application(ManageSpaceActivity=typeof(MyManageSpaceActivity))]
the build will fail:
error XAGJS7007: System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Type'.
error XAGJS7007:    at Android.App.ApplicationAttribute.<>c.<AddManualMapping>b__189_3(ApplicationAttribute self, Object value) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Mono.Android/ApplicationAttribute.Partial.cs:line 47
error XAGJS7007:    at …
=> [XABT] Fix ApplicationAttribute.ManageSpaceActivity manual mapping (#9708)

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/GitBranch.cs
Context: https://github.com/dotnet/android/pull/9732
PR #9732 failed with:
NuGet.Build.Tasks.Pack.targets(221,5): error NU5123: Warning As Error: The file 'package/services/metadata/core-properties/027a96e260344b159133798c830dab61.psmdcp' path, name, or both are too long.
Your package might not work without long file path support. Please shorten the file path or file name.
The branch name is 68 characters long:
darc-release/10.0.1xx-preview1-94740166-a85b-4349-9dd7-c8274168049c
Update the `<GitBranch/>` MSBuild task to substring long `darc-` branch names to avoid this problem. I found even 50 characters was causing the issue, so I chose 32.
=> [xa-prep-tasks] fix build errors for long `darc-` branch names

samples/NativeAOT/NativeAotTypeManager.cs, samples/NativeAOT/NativeAotValueManager.cs
Context: dbb0b92035d4ebb40dd3fb2768e20ac7cbef43c4
Context: https://github.com/dotnet/java-interop/commit/dd3c1d0514addfe379f050627b3e97493e985da6
Commit dbb0b920 had to copy significant parts of
`JniRuntime.JniValueManager.CreatePeer()` in order to get the desired semantics.  dotnet/java-interop@dd3c1d05 added a `TryCreatePeer()` virtual method in an effort to reduce the amount of copied code required.
Update `NativeAotValueManager` to override the new method, allowing us to remove most of the `CreatePeer()` code added in dbb0b920. Additionally, override `GetInvokerTypeCOre()` within `NativeAotTypeManager` so that .NET for Android -style `Invoker` types can be appropriately resolved.
=> [NativeAOT] Integrate TryCreatePeer

src/Xamarin.Android.Build.Tasks/Tasks/CollectAssemblyFilesForArchive.cs, src/Xamarin.Android.Build.Tasks/Tasks/CompressAssemblies.cs, src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblyCompressionFailures.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs, src/Xamarin.Android.Build.Tasks/Utilities/AssemblyCompression.cs, src/Xamarin.Android.Build.Tasks/Utilities/ITaskItemExtensions.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
If using `$(AndroidEnableAssemblyCompression)` today, we do not compress assemblies incrementally.  That is, we always compress every assembly even if they haven't changed since the previous build.
Update the `CompressAssemblies` task to check if the input is newer than the output, and skip recompressing if the input has not changed.
This is most visible with the following test case:
```
dotnet build -p:EmbedAssembliesIntoApk=true -p:AndroidIncludeDebugSymbols=false
```
| Scenario (`CompressAssemblies` tasks)        | main     | This PR  |
| --------------- | -------- | -------- |
| Full            | 44.26 s | 44.2 s  |
| NoChanges       | not run | 34 ms   |
| ChangeResource  | 27.8 s  | 9 ms    |
| AddResource     | 25.81 s | 25 ms   |
| ChangeCSharp    | 25.87 s | 30 …
=> [XABT] Make assembly compression incremental.

.github/ISSUE_TEMPLATE/01-building-an-application.yml, .github/ISSUE_TEMPLATE/02-running-an-application.yml, .github/ISSUE_TEMPLATE/03-mono-android-api.yml, .github/ISSUE_TEMPLATE/04-binding-a-java-library.yml, .github/ISSUE_TEMPLATE/05-other.yml
Users will (hopefully!) be testing the forthcoming .NET 10 for Android preview bits and providing feedback.  Or even providing feedback today on `main` builds!
Update our issue templates to include `net10.0-android (Preview)` as an option.
=> [.github] Update issue templates to include `net10.0-android`.

Configuration.props, build-tools/create-packs/Directory.Build.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.CoreCLR.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.targets, src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
This is a step towards Android projects using `UseMonoRuntime=false` successfully:
1. Create new packs such as `Microsoft.Android.Runtime.CoreCLR.[api].[rid]`
2. Ensure a project *builds* with `UseMonoRuntime=false` in both `Debug` and `Release` configurations.
3. The project will not be able to run successfully yet.
(Significant work required for no. 3)
=> [coreclr] projects with `UseMonoRuntime=false` successfully build

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.Core.targets
Fixes: https://github.com/dotnet/android/issues/9645
If a user specifies `$(OutputPath)` on the command line, it won't automatically get a trailing slash added to it because global properties can't be overwritten.  Ensure we add a trailing slash to `$(OutputPath)` when constructing `$(DocumentationFile)`.
This probably doesn't warrant a test case.
Tested locally with:
```
dotnet build -bl -p:OutputPath=C:\Users\jopobst\Desktop\maven_messaging\foo
```
`main`:
This PR:
=> [XABT] Ensure `$(DocumentationFile)` correctly uses `$(OutputPath)`.

.gitmodules, build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CheckApiCompatibility.cs, build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs, src/Mono.Android/Mono.Android.targets
Context: https://github.com/dotnet/android/pull/9747
Changes: https://github.com/dotnet/java-interop/compare/dd3c1d0514addfe379f050627b3e97493e985da6...6bc87e8b55bc00ae1423a5ae92cf5db573fc76ed
* dotnet/java-interop@6bc87e8b: [jcw-gen] Use `+` for nested types, not `/` (dotnet/java-interop#1304)
dotnet/java-interop@6bc87e8b is needed to unblock parts of #9747.
Additionally, two "quality of life" changes:
Firstly, update the `src/Mono.Android` build so that if there are
API breaks reported, the breakage is collated into 
`src/Mono.Android/ApiCompatLinesToAdd.txt` in a format that can be
directly copied into 
`tests/api-compatibility/acceptable-breakages-vReference-*.txt` if
deemed useful.
Previously, *all* changes were printed to the build log, which was
annoying to deal with because (1) …
=> Bump to dotnet/java-interop/main@6bc87e8b

src/Mono.Android/Android.Runtime/JavaList.cs, tests/Mono.Android-Tests/Java.Interop/JavaListTest.cs
Fixes: https://github.com/dotnet/android/issues/9675
Remove the check for duplicates in `JavaList.Add` to allow duplicates.
=> [Mono.Android] `JavaList.Add` should allow duplicates.

src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android.Runtime/JNIEnvInit.cs, src/native/mono/monodroid/monodroid-glue-internal.hh, src/native/mono/monodroid/monodroid-glue.cc
This avoids the problem of `JNIEnvInit.mid_Class_forName` being `null` in a NativeAOT context:
02-07 14:05:25.954 30744 30744 E AndroidRuntime: Process: net.dot.hellonativeaot, PID: 30744
02-07 14:05:25.954 30744 30744 E AndroidRuntime: net.dot.jni.internal.JavaProxyThrowable: System.TypeInitializationException: TypeInitialization_Type_NoTypeAvailable
02-07 14:05:25.954 30744 30744 E AndroidRuntime:  ---> System.ArgumentNullException: ArgumentNull_Generic Arg_ParamName_Name, method
02-07 14:05:25.954 30744 30744 E AndroidRuntime:    at Java.Interop.JniEnvironment.StaticMethods.CallStaticObjectMethod(JniObjectReference, JniMethodInfo, JniArgumentValue*) + 0x1c8
02-07 14:05:25.954 30744 30744 E AndroidRuntime:    at Android.Runtime.JNIEnv.FindClass(String) + 0xb4
02-07 14:05:25.954 30744 …
=> [Mono.Android] update `JNIEnv.FindClass()` to use `JniEnvironment.Types.FindClass()`

build-tools/create-packs/Microsoft.NET.Sdk.Android.proj, eng/Versions.props, src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json, src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
Context: https://github.com/dotnet/android-libraries/issues/1084#issuecomment-2627870179
Context: https://aka.ms/maui-support-policy
dotnet/android-libraries needs to build with:
<TargetFrameworks>net8.0-android;net10.0-android</TargetFrameworks>
Typically each .NET release, we only support N-1 `$(TargetFrameworks)` and import `Eol.targets` to emit an error message on older versions.
We can make some .NET workload changes to support .NET 8 in a .NET 10 SDK until .NET 8 goes out of support in May.
I also updated some MSBuild tests to ensure .NET 8 projects build & run.
=> [Xamarin.Android.Build.Tasks] temporarily support .NET 8 in .NET 10

src/Mono.Android/Android.Runtime/ExtraDelegates.cs, src/Mono.Android/Mono.Android.csproj, src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodsClassifier.cs
Context: https://github.com/dotnet/java-interop/pull/1296
Context: https://github.com/dotnet/java-interop/issues/1027
Changing callback methods to blittable types (`bool` -> `sbyte` and `char` -> `ushort`) causes warnings when the marshal method classifier verifies that the marshal types match the native types:
```
Xamarin.Android.Common.targets(1502,3): Method 'System.SByte Java.Lang.Object::n_Equals_Ljava_lang_Object_(System.IntPtr,System.IntPtr,System.IntPtr)' doesn't match native callback signature (invalid return type: expected 'System.Boolean', found 'System.SByte')
Xamarin.Android.Common.targets(1502,3): Unable to find native callback method 'n_Equals_Ljava_lang_Object_' in type 'Java.Lang.Object', matching the 'System.Boolean Java.Lang.Object::Equals(Java.Lang.Object)' signature …
```
=> [XABT] Avoid non-blittable types in native callback methods

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
Context: https://github.com/advisories/GHSA-8g4q-xg66-9fp4
Address CVE-2024-43485 by updating NuGet.ProjectModel to v6.13.1, which
brings in System.Text.Json v8.0.5.
=> [build] Address CVE-2024-43485

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
Context: https://github.com/dotnet/roslyn-analyzers/issues/7525
Context: https://github.com/dotnet/msbuild/issues/11237
The two above issues are fixed, so we can restore the impacted tests by partially reverting 37014d10.
=> [tests] restore ignored tests from .NET 10 issues

tests/Mono.Android-Tests/Mono.Android-Tests/Android.OS/HandlerTest.cs, tests/Mono.Android-Tests/Mono.Android-Tests/Localization/LocalizationTests.cs
Context: https://github.com/dotnet/android/pull/9758
While enabling new tests for `Mono.Android-Tests`, git somehow ate my files and made them all empty.  I fixed the ones that CI found but didn't notice the other empty files.
Add the content of these files back.
Verified on CI run that the 2 new tests are indeed being run and succeed.
=> [Mono.Android-Tests] Fix empty files issue.

src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/CompressedAssembliesNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/JniRemappingAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrComposer.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrInstructions.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrModule.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrStringEncoding.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrStringManager.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrVariable.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/MemberInfoUtilities.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/NativeAssemblerAttribute.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/StringHolder.cs, src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodsNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingDebugNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingReleaseNativeAssemblyGenerator.cs
Another portion of code taken from https://github.com/dotnet/android/pull/9572 to make it smaller.
This adds support for Unicode strings to the LLVM IR generator, together with de-duplication and
support for outputting the same string encoded both as UTF-8 and Unicode.
=> [LLVM IR] Add support for Unicode strings

build-tools/create-packs/Directory.Build.targets, src/Xamarin.Android.Build.Tasks/Microsoft.NET.Sdk.Android/WorkloadManifest.in.json
Context: https://github.com/dotnet/android/pull/9777
The problem with #9777, is it increases our install size by something like ~700MB with the following packs:
* Microsoft.Android.Sdk.[platform] x 1 (current platform)
* Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.[RID] x 4 RIDs
* Microsoft.NETCore.App.Runtime.Mono.[RID] x 4 RIDs
Some of .NET MAUI's CI machines are extremely tight on disk space, and we promptly filled the disk!
Let's move these packs to a new `android-net8` workload, which can be installed separately.
dotnet/android-libraries could simply install:
dotnet workload install android-net8
Which would provision both `android` and `android-net8` workloads.
=> [Xamarin.Android.Build.Tasks] move .NET 8 support to `android-net8` workload

src/Microsoft.Android.Sdk.ILLink/TypeMappingStep.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
70bd636b introduced an "MVP" for a managed typemap for NativeAOT.
Unfortunately, a `dotnet new maui` project template still crashes with:
AndroidRuntime: Process: net.dot.hellonativeaot, PID: 16075
AndroidRuntime: net.dot.jni.internal.JavaProxyThrowable: System.InvalidCastException: Arg_InvalidCastException
AndroidRuntime:    at Java.Lang.Object._GetObject[T](IntPtr, JniHandleOwnership) + 0x64
AndroidRuntime:    at Microsoft.Maui.WindowOverlay.Initialize() + 0x168
AndroidRuntime:    at Microsoft.Maui.Handlers.WindowHandler.OnRootViewChanged(Object sender, EventArgs e) + 0x8c
AndroidRuntime:    at Microsoft.Maui.Platform.NavigationRootManager.SetContentView(IView) + 0x17c
AndroidRuntime:    at Microsoft.Maui.Platform.NavigationRootManager.Connect(IView, IMauiContext) + 0xf0
AndroidRuntime: …
=> [nativeaot] fix typemap logic involving duplicates

Documentation/docs-mobile/building-apps/build-properties.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NativeAOT.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
dbb0b920 introduced `$(_AndroidCodeGenerationTarget)`, but I didn't notice that `$(AndroidCodegenTarget)` already exists!
Unify on `$(AndroidCodegenTarget)`, making the defaults:
* `$(AndroidCodegenTarget)=XAJavaInterop1` if blank, when not using NativeAOT
* `$(AndroidCodegenTarget)=JavaInterop1` if blank, when using NativeAOT
=> [Xamarin.Android.Build.Tasks] unify `$(AndroidCodegenTarget)`

src/Xamarin.Android.Build.Tasks/Tasks/RemoveRegisterAttribute.cs
Fixes #9629
Add the use of the `DirectoryAssemblyResolver` to make sure we can handle issues such as 
```
XARRA7028: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'
bei Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
bei Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
bei Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
bei Mono.Cecil.TypeReference.Resolve()
bei Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
bei Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
bei Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
bei …
```
=> XARRA7028 AssemblyResolutionException in Android App Release Build

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
`mono.android.jar/dex` are compiled with `$(AndroidCodegenTarget)=XAJavaInterop1`, and so this causes a problem if you build a project with `$(AndroidCodegenTarget)=JavaInterop1` as incorrect Java stubs will be used.
For example, `dotnet new maui` using NativeAOT we can get a crash such as:
02-14 16:23:29.884 19260 19260 E .hellonativeaot: No implementation found for void mono.android.Runtime.register(java.lang.String, java.lang.Class, java.lang.String) (tried Java_mono_android_Runtime_register and Java_mono_android_Runtime_register__Ljava_lang_String_2Ljava_lang_Class_2Ljava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?
Which is caused by `mono.android.Runtime.register` being called by `mono/android/view/View_OnClickListenerImplementor.java` which is compiled with …
=> [Xamarin.Android.Build.Tasks] use `mono.android.jar` only for `$(AndroidCodegenTarget)=XAJavaInterop1`

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, src/Mono.Android/Profiles/api-Baklava.params.txt, src/Mono.Android/metadata
Context: https://developer.android.com/about/versions/16
Context: https://android-developers.googleblog.com/2025/02/second-beta-android16.html
Android 16 Beta 2 has been released.  The Android 16
* Nov/Dec: Developer Previews
* Jan/Feb: Unstable Betas
* Mar/Apr: Stable Betas
* ???: Final
Currently, this will be usable in its preview form to `main` users who explicitly target `net10.0-android36`.  Once we are shipping .NET 10 previews, it will be usable for users who explicitly target `net10.0-android36`.  We will need to decide on our strategy for backporting this to .NET 9 service releases.
Additional note(s):
- We cannot generate an updated `PublicAPI.Unshipped.txt` because this is done …
=> [Mono.Android] Bind Android API-36 Beta 2.

.gitmodules, samples/NativeAOT/MainActivity.cs, src/Mono.Android/Android.Runtime/JNIEnv.cs
Context: https://github.com/dotnet/android/pull/9811
The .NET MAUI template + NativeAOT currently crashes with:
02-18 15:59:24.575 12907 12907 E AndroidRuntime: net.dot.jni.internal.JavaProxyThrowable: System.InvalidProgramException: InvalidProgram_Specific, IntPtr Android.Runtime.JNIEnv.monodroid_typemap_managed_to_java(System.Type, Byte*)
02-18 15:59:24.575 12907 12907 E AndroidRuntime:    at Internal.Runtime.TypeLoaderExceptionHelper.CreateInvalidProgramException(ExceptionStringID, String) + 0x4c
02-18 15:59:24.575 12907 12907 E AndroidRuntime:    at Android.Runtime.JNIEnv.monodroid_typemap_managed_to_java(Type, Byte*) + 0x18
02-18 15:59:24.575 12907 12907 E AndroidRuntime:    at Android.Runtime.JNIEnv.TypemapManagedToJava(Type) + 0x104
02-18 15:59:24.575 12907 12907 E AndroidRuntime: …
=> [Mono.Android] `JNIEnv.FindClass(Type)` now uses `TypeManager`

.github/copilot-instructions.md, src/Xamarin.Android.Build.Tasks/Tasks/D8.cs, src/Xamarin.Android.Build.Tasks/Tasks/R8.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs, src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs, src/Xamarin.Android.Build.Tasks/Tasks/RuntimeIdentifierToAbi.cs, src/Xamarin.Android.Build.Tasks/Tasks/SetNdkPathForIlc.cs, src/Xamarin.Android.Build.Tasks/Tasks/ValidateJavaVersion.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.Nullable.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
Context: https://code.visualstudio.com/docs/copilot/copilot-customization
We have various MSBuild tasks that have not enabled C# nullable reference types. This is a bit tedious to do, so I tried VS Code Insiders and GitHub Copilot "Edits" to do this work. I did this for just a few files for now.
I introduced a new file `.github/copilot-instructions.md` to keep copilot from going off the rails! I mostly had to fight it to respect our code formatting, not delete comments, etc.
I would recommend the settings:
"github.copilot.chat.codeGeneration.useInstructionFiles": true,
"github.copilot.chat.codeGeneration.instructions": [
{
"file": ".editorconfig"
},
{
"file": "README.md"
}
],
* `github.copilot.chat.codeGeneration.useInstructionFiles`: enables the use of `.github/copilot-instructions.md`
* …
=> [Xamarin.Android.Build.Tasks] use copilot to opt into NRT

samples/NativeAOT/NativeAOT.csproj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
Context: https://github.com/xamarin/xamarin-macios/blob/d4baff4c6847a413e6a9c60089edfff50611ea9b/dotnet/targets/Xamarin.Shared.Sdk.props#L192
`$(PublishAotUsingRuntimePack)` needs to be `true` for any NativeAOT scenario on mobile. This setting is more useful for desktop platforms, as you aren't cross-compiling anything. Desktop builds can potentially use the packs from the .NET SDK as the host and target match.
xamarin/xamarin-macios also defaults `$(PublishAotUsingRuntimePack)=true` when `$(PublishAot)=true`, so we should be safe to follow suit.
=> [nativeaot] default to `$(PublishAotUsingRuntimePack)=true`

samples/HelloWorld/HelloWorld/Properties/AndroidManifest.xml
When I try installing `samples/HelloWorld`, installation fails:
./dotnet-local.sh build -t:Install samples/HelloWorld/HelloWorld/HelloWorld.DotNet.csproj
HelloWorld.DotNet failed with 2 error(s) (139.4s) → samples/HelloWorld/HelloWorld/bin/Debug/net10.0-android/HelloWorld.DotNet.dll
/Users/jon/Developer/src/dotnet/android/bin/Debug/lib/packs/Microsoft.Android.Sdk.Darwin/35.99.0/tools/Xamarin.Android.Common.targets(2824,3): error MSB6006: "adb" exited with code 1.
/Users/jon/Developer/src/dotnet/android/bin/Debug/lib/packs/Microsoft.Android.Sdk.Darwin/35.99.0/tools/Xamarin.Android.Common.targets(2824,3): error XAAADB0000:
Serving...
All files should be loaded. Notifying the device.
adb: failed to install bin/Debug/net10.0-android/com.xamarin.android.helloworld-Signed.apk: Failure …
=> [HelloWorld] Fix app install

src/Mono.Android/Android.Runtime/JNIEnv.cs
A .NET MAUI + NativeAOT project fails with:
02-21 10:24:09.913 21462 21462 E AndroidRuntime: net.dot.jni.internal.JavaProxyThrowable: System.DllNotFoundException: DllNotFound_Linux, xa-internal-api,
02-21 10:24:09.913 21462 21462 E AndroidRuntime: dlopen failed: library "xa-internal-api.so" not found
02-21 10:24:09.913 21462 21462 E AndroidRuntime: dlopen failed: library "libxa-internal-api.so" not found
02-21 10:24:09.913 21462 21462 E AndroidRuntime: dlopen failed: library "xa-internal-api" not found
02-21 10:24:09.913 21462 21462 E AndroidRuntime: dlopen failed: library "libxa-internal-api" not found
02-21 10:24:09.913 21462 21462 E AndroidRuntime:
02-21 10:24:09.913 21462 21462 E AndroidRuntime:    at System.Runtime.InteropServices.NativeLibrary.LoadLibErrorTracker.Throw(String) + …
=> [Mono.Android] use `GetJniTypeNameFromInstance()`

src/Microsoft.Android.Runtime.NativeAOT/Android.Runtime.NativeAOT/DiagnosticSettings.cs, src/Microsoft.Android.Runtime.NativeAOT/Android.Runtime.NativeAOT/JavaInteropRuntime.cs, src/Microsoft.Android.Runtime.NativeAOT/Microsoft.Android.Runtime.NativeAOT.csproj
Context: https://github.com/dotnet/java-interop/blob/9dea87dc1f3052ed0f9499c9858b27c83e7d139e/samples/Hello-NativeAOTFromAndroid/README.md
The NativeAOT sample and related `Microsoft.Android.Runtime.NativeAOT` assembly is based in part on the `Hello-NativeAOTFromAndroid` sample in dotnet/java-interop, which contains this comment about Logging:
> The (very!) extensive logging around JNI Global and Local
> references mean that this sample should not be used as-is for
> startup timing comparison.
…because `adb logcat` is absolutely *spammed* by LREF and GREF logs.
The "solution" in .NET for Android "proper" is to use the `debug.mono.log` system property to control logging.  By default, LREF and GREF logs are disabled, but can be enabled by setting the `debug.mono.log` system property …
=> [Microsoft.Android.Runtime.NativeAOT] Parse debug.mono.log

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/AddKeepAlivesStep.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/LinkerTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.Linker.cs
Fixes: https://github.com/dotnet/android/issues/8421
Context: https://github.com/dotnet/java-interop/issues/719
Context: https://github.com/dotnet/android/pull/5278
In https://github.com/dotnet/java-interop/issues/719, we realized we needed to call `GC.KeepAlive ()` on objects that are passed to native code to prevent the GC from collecting them prematurely.
However, this only solved the issue for newly compiled binding libraries and not the existing ecosystem of binding libraries.  Thus we added https://github.com/dotnet/android/pull/5278, a "linker" step that would add `GC.KeepAlive ()` calls to existing binding libraries.
The `AddKeepAlivesStep` runs on all assemblies the contain a reference to `Java.Lang.Object`, including ones that already have the keep-alives compiled in.  Modify …
=> [XABT] Don't run `AddKeepAlivesStep` on .NET for Android assemblies.

samples/NativeAOT/NativeAOT.csproj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NativeAOT.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownProperties.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs
Context: https://github.com/dotnet/sdk/blob/68bf4cbabc023e5c2752ee4d5ce7e4a40929e748/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets#L227-L229
The only blocker for supporting `$(RuntimeIdentifiers)=android-arm64;android-x64` is the error message:
error NETSDK1191: A runtime identifier for the property 'PublishAot' couldn't be inferred. Specify a rid explicitly.
We can set `$(AllowPublishAotWithoutRuntimeIdentifier)` by default, as this is not an error we'd ever want to show on Android.
After this change I can see the MSBuild terminal logger shows the two RIDs building in parallel:
MyApp     IlcCompile (8.7s)
MyApp     IlcCompile (8.6s)
And then the resulting `.apk` has both `lib/arm64-v8a` and `lib/x86_64`.
I also updated some of our MSBuild …
=> [nativeaot] support multi-RID builds

src/Mono.Android/Android.Animation/AnimatorSet.cs, src/Mono.Android/Android.Animation/ValueAnimator.cs, src/Mono.Android/Android.Bluetooth/BluetoothGattServerCallback.cs, src/Mono.Android/Android.Telephony/CellInfo.cs, src/Mono.Android/Android.Widget/AbsListView.cs, src/Mono.Android/Java.Interop/TypeManager.cs, src/Mono.Android/Java.Util/IList.cs, src/Mono.Android/Java.Util/ISortedMap.cs
Context: https://github.com/dotnet/java-interop/pull/1275
Throughout the years of binding `Mono.Android` there have been instances where we need to write manual binding code to work around issues in `generator`.  These instances need to be manually updated to mirror the latest `generator` output by removing calls to `JNINativeWrapper.CreateDelegate` that would prevent NativeAOT from functioning.
It is recommended to review this PR with "Hide Whitespace Changes", as adding try/catch blocks affected indentation.
=> [Mono.Android] Remove usages of `JNINativeWrapper.CreateDelegate`.

src/Microsoft.Android.Runtime.NativeAOT/Android.Runtime.NativeAOT/NativeAotTypeManager.cs
Context: https://github.com/dotnet/android/pull/9824
With `debug.dotnet.log` support implemented, the lref/gref logging seems sufficient for debugging Java interop (or GC)-related issues.
Remove other logging in `NativeAotTypeManager` that seems unnecessary and will yield better startup performance.
=> [nativeaot] remove extraneous log messages

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
A `dotnet new maui` project template fails to build with:
obj\Release\net10.0-android\android-arm64\android\src\mono\android\runtime\InputStreamAdapter.java:4: error: InputStreamAdapter is not abstract and does not override abstract method read() in InputStream
obj\Release\net10.0-android\android-arm64\android\src\mono\android\runtime\OutputStreamAdapter.java:4: error: OutputStreamAdapter is not abstract and does not override abstract method write(int) in OutputStream
I found I could also reproduce this issue with the `BuildBasicApplicationAppCompat()` MSBuild test.
After reviewing `.binlog` files, I found we weren't including `PreserveLists\*.xml` files *at all* in NativeAOT, as the `Condition` was false:
<_PreserveLists Include="$(MSBuildThisFileDirectory)..\PreserveLists\*.xml" /> …
=> [nativeaot] fix missing `PreserveLists\*.xml` files

src/Microsoft.Android.Runtime.NativeAOT/Microsoft.Android.Runtime.NativeAOT.csproj
Various folks building dotnet/android/main have been running into:
Microsoft.Common.CurrentVersion.targets(5064,5): error MSB3030: Could not copy the file
"…/dotnet/android/bin/Release/lib/packs/Microsoft.Android.Runtime.NativeAOT.35.android-arm64/35.99.0/runtimes/android-arm64/lib/net10.0/Microsoft.Android.Runtime.NativeAOT.dll" because it was not found.
And then were able to fix this by manually copying the file. It also somehow works fine on CI?!?
Reviewing a clean build, I noticed the `_CopyToPackDirs` target was *not* running for this project when doing a build.
Comparing against another project that *does* work, `Mono.Android.Export.csproj`, I remembered something that is missing and important...
If you want to replace `$(BuildDependsOn)`, then you need to do:
<Project>
<Import …
=> [build] fix local `Microsoft.Android.Runtime.NativeAOT.csproj` builds

Directory.Build.props, Documentation/guides/HowToBranch.md
Context: https://github.com/dotnet/android/tree/release/10.0.1xx-preview2
We branched for .NET 10 Preview 2 from ea8d2a7a into `release/10.0.1xx-preview2`; the main branch is now .NET 10 Preview 3.
I also updated `HowToBranch.md` as it was out of date.
=> $(AndroidPackVersionSuffix)=preview.3

src/Xamarin.Android.Build.Tasks/Tasks/GenerateACWMap.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateMainAndroidManifest.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateMergedAndroidManifest.cs, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Begin breaking down the `<GenerateJavaStubs>` task into smaller, more manageable pieces by moving the manifest merging and ACW map generation into separate tasks.  Once this is complete, we should be able to start moving these steps that require Cecil assembly scanning into linker steps (or equivalent), eventually saving a Cecil assembly scan per build.
Additionally, create a new `GetProjectBuildSpecificTaskObjectKey` to be used with `GetRegisteredTaskObject`. This version additional uses `$(IntermediateOutpuPath)` in the key to help ensure data from multi-targeted builds (`net8.0-android,net9.0-android`) is not overwritten.
=> [XABT] Refactor manifest merging and ACW map generation out of `GenerateJavaStubs`.

build-tools/installers/create-installers.targets, src/Xamarin.Android.Build.Tasks/Tasks/BuildAppBundle.cs, src/Xamarin.Android.Build.Tasks/Tasks/JavaDependencyVerification.cs, src/Xamarin.Android.Build.Tasks/Utilities/JsonExtensions.cs, src/Xamarin.Android.Build.Tasks/Utilities/MamJsonParser.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
* JsonElement is read only. This is why we convert them to JsonNode. 
* JsonNode.Parse does NOT have the same features as JsonDocument.Parse. e.g you CANNOT tell it to ignore trailing comma's. It will just throw an exception. This is the reason why we have to load the .json via JsonDocument and then call the extension method `.ToNode ()` on the Root JsonElement to convert it to a JsonNode.  (We use JsonNode to do the merging).
=> Switch more over to System.Text.Json

src-ThirdParty/NUnitLite/Internal/AssemblyHelper.cs
Running `Mono.Android-Tests` on NativeAOT crashes with:
02-27 14:32:47.590  9008  9024 E NUnit   : Error: System.NotSupportedException: NotSupported_CodeBase (TaskId:30)
02-27 14:32:47.590  9008  9024 E NUnit   :    at System.Reflection.Runtime.Assemblies.RuntimeAssemblyInfo.get_CodeBase() + 0x34 (TaskId:30)
02-27 14:32:47.590  9008  9024 E NUnit   :    at NUnit.Framework.Internal.AssemblyHelper.GetAssemblyPath(Assembly) + 0x10 (TaskId:30)
02-27 14:32:47.590  9008  9024 E NUnit   :    at NUnit.Framework.Internal.NUnitLiteTestAssemblyBuilder.Build(Assembly, IDictionary) + 0x8c (TaskId:30)
02-27 14:32:47.590  9008  9024 E NUnit   :    at NUnit.Framework.Internal.NUnitLiteTestAssemblyRunner.Load(Assembly, IDictionary) + 0x28 (TaskId:30)
02-27 14:32:47.590  9008  9024 E NUnit   :    at …
=> [NUnitLite] remove `Assembly.CodeBase` usage

src/Mono.Android/Android.Runtime/InputStreamInvoker.cs, src/Mono.Android/Android.Runtime/OutputStreamInvoker.cs, src/Mono.Android/Android.Runtime/XmlPullParserReader.cs
f800c1a6 was a step toward making `Java.Lang.Object.GetObject<T>()` to not call the static `Java.Interop.TypeManager.CreateInstance()` and go through a `JniRuntime.JniValueManager` instead.
Unfortunately, there are still a few types that manually call `TypeManager.CreateInstance()`, these will error when running with NativeAOT such as `Mono.Android.NET-Tests`:
02-27 14:40:23.089  9462  9487 I NUnit   : AssetContents("asset1.txt","Asset1")
02-27 14:40:23.093  9462  9487 E NUnit   :      [FAIL]
02-27 14:40:23.093  9462  9487 E NUnit   :  : System.DllNotFoundException : DllNotFound_Linux, xa-internal-api,
02-27 14:40:23.093  9462  9487 E NUnit   : dlopen failed: library "xa-internal-api.so" not found
02-27 14:40:23.093  9462  9487 E NUnit   : dlopen failed: library "libxa-internal-api.so" …
=> [Mono.Android] use `Java.Lang.Object.GetObject<T>()`

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NativeAOT.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
d70db5b was *wrong* in that it merged two different things:
* Java stub generation's "codegen target" (once settable by an MSBuild property `$(_AndroidCodeGenerationTarget)`)
* C# generator's "codegen target" or `$(AndroidCodegenTarget)`
The problem was `$(_AndroidCodeGenerationTarget)` was just poorly named making me think it was the same as `$(AndroidCodegenTarget)`.
Partially revert d70db5b and use the name `$(_AndroidJcwCodegenTarget)` instead.
NativeAOT now defaults to `$(_AndroidJcwCodegenTarget)=JavaInterop1` and `$(AndroidCodegenTarget)=XAJavaInterop1`.
=> [Xamarin.Android.Build.Tasks] introduce `$(_AndroidJcwCodegenTarget)`

src/Mono.Android/Android.Runtime/JNIEnv.cs
`Mono.Android` has various test failures under NativeAOT such as:
02-28 16:35:29.583 18438 18456 I NUnit   : CastJavaLangObjectArrayToByteArrayThrows
02-28 16:35:29.586 18438 18456 E NUnit   :      [FAIL]
02-28 16:35:29.586 18438 18456 E NUnit   :  :   Expected: <System.InvalidCastException>
02-28 16:35:29.586 18438 18456 E NUnit   :   But was:  <System.DllNotFoundException> (DllNotFound_Linux, xa-internal-api,
02-28 16:35:29.586 18438 18456 E NUnit   : dlopen failed: library "xa-internal-api.so" not found
02-28 16:35:29.586 18438 18456 E NUnit   : dlopen failed: library "libxa-internal-api.so" not found
02-28 16:35:29.586 18438 18456 E NUnit   : dlopen failed: library "xa-internal-api" not found
02-28 16:35:29.586 18438 18456 E NUnit   : dlopen failed: library "libxa-internal-api" not …
=> [Mono.Android] update more `TypeManager.GetClassName()` calls

src/Mono.Android/Java.Interop/JavaConvert.cs
Mono.Android-Tests running on NativeAOT can have a failure such as:
02-28 14:33:38.949 12544 12567 I NUnit   : Indexer
02-28 14:33:38.952 12544 12567 E NUnit   :      [FAIL]
02-28 14:33:38.952 12544 12567 E NUnit   :  : System.DllNotFoundException : DllNotFound_Linux, xa-internal-api,
02-28 14:33:38.952 12544 12567 E NUnit   : dlopen failed: library "xa-internal-api.so" not found
02-28 14:33:38.952 12544 12567 E NUnit   : dlopen failed: library "libxa-internal-api.so" not found
02-28 14:33:38.952 12544 12567 E NUnit   : dlopen failed: library "xa-internal-api" not found
02-28 14:33:38.952 12544 12567 E NUnit   : dlopen failed: library "libxa-internal-api" not found
02-28 14:33:38.952 12544 12567 E NUnit   :    at System.Runtime.InteropServices.NativeLibrary.LoadLibErrorTracker.Throw(String …
=> [Mono.Android] fix `JavaConvert.GetTypeMapping()` for NativeAOT

build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/vs-workload.in.props
Context: https://github.com/xamarin/yaml-templates/commit/96d7858cce242c5eea76028f3f051bb9ffda793c
Adds the VS manifest zips needed by the workload versions VS insertion
pipeline to Maestro publishing.
The first update to VS that includes these changes will have to be done
manually, as the manifest names are also changing to work with the new
pipeline.
=> [ci] Publish VS workload zips

Documentation/docs-mobile/messages/xa1040.md, src/Xamarin.Android.Build.Tasks/Properties/Resources.Designer.cs, src/Xamarin.Android.Build.Tasks/Properties/Resources.resx, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
MonoVM is currently the default (and supported!) runtime for .NET for Android. Emit `XA1040` when the user opts into using the experimental runtimes, such as:
* `$(UseMonoRuntime)=false` CoreCLR
* `$(PublishAot)=true` NativeAOT
If desired, you can opt out of the warning completely with `$(AndroidAllowExperimentalRuntime)=true`, or use existing MSBuild mechanisms to suppress it.
=> [Xamarin.Android.Build.Tasks] emit XA1040 for experimental runtimes

src/native/mono/monodroid/monodroid-glue.cc
Fixes: https://github.com/dotnet/android/issues/9573
Context: 8e1c0e6e2f4c41c9a24904bb1cea943357d78ac4
A customer reports that they are unable to attach a debugger to
32-bit Android apps:
> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.companyname.exemploandroid/crc64358cda76bdc6f75f.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.companyname.exemploandroid/crc64358cda76bdc6f75f.MainActivity }
…
[monodroid-debug] Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=127.0.0.1:8805,server=y,embedding=1,timeout=8
…
[mono] Listening on 127.0.0.1:8805 (timeout=8 ms)...
[mono] debugger-agent: Timed out waiting to connect.
Of particular note …
=> Fix Debugger timeout on 32 bit devices.

tests/Mono.Android-Tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidClientHandlerTests.cs, tests/Mono.Android-Tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidMessageHandlerTests.cs
CI tests are failing with:
```
System.Net.Http.HttpRequestException : net_http_message_not_success_statuscode_reason, 503, Service Temporarily Unavailable
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
at Xamarin.Android.NetTests.AndroidHandlerTestBase.EnsureSuccessStatusCode(HttpResponseMessage response)
at Xamarin.Android.NetTests.AndroidHandlerTestBase.Redirect_POST_With_Content_Works()
at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object , BindingFlags )
```
Add several additional HTTP 50X codes that indicate temporary network/server failures to the list of status codes that should be ignored in `EnsureSuccessStatusCode`.
=> [Mono.Android-Tests] Ignore more types of temporary network/server failures.

build-tools/create-packs/Directory.Build.targets, build-tools/create-packs/vs-workload.in.props
Context: https://github.com/xamarin/yaml-templates/commit/96d7858cce242c5eea76028f3f051bb9ffda793c
Adds the VS manifest zips needed by the workload versions VS insertion
pipeline to Maestro publishing.
The first update to VS that includes these changes will have to be done
manually, as the manifest names are also changing to work with the new
pipeline.
=> [ci] Publish VS workload zips (#9870)

tests/Mono.Android-Tests/Mono.Android-Tests/Mono.Android.NET-Tests.csproj, tests/Mono.Android-Tests/Mono.Android-Tests/runtimeconfig.template.json
NativeAOT doesn't support `runtimeconfig.template.json` and it emits the build warning:
D:\.nuget\packages\microsoft.dotnet.ilcompiler\10.0.0-preview.3.25152.2\build\Microsoft.NETCore.Native.Publish.targets(46,5):
The published project has a runtimeconfig.template.json that is not supported by PublishAot. Move the configuration to the project file using RuntimeHostConfigurationOption.
So, instead of using `runtimeconfig.template.json` with contents:
{
"configProperties": {
"test_bool": true,
"test_integer": 42,
"test_string": "foo"
}
}
You can simply define them in your `.csproj` as:
<ItemGroup>
<RuntimeHostConfigurationOption Include="test_bool"    Value="true" />
<RuntimeHostConfigurationOption Include="test_integer" Value="42" />
<RuntimeHostConfigurationOption Include="test_string" …
=> [tests] remove `runtimeconfig.template.json` in favor of `@(RuntimeHostConfigurationOption)`

src/Xamarin.Android.Build.Tasks/Resources/NativeAotRuntimeProvider.java
Context: https://github.com/dotnet/runtime/blob/d09a42b9149e14a37c8ef8363cdb7e17bb922c37/src/libraries/System.Private.CoreLib/src/System/IO/Path.Unix.cs#L83
`System.IO.Path.GetTempPath()` doesn't work under NativeAOT as seen by the test failure:
Mono.Android.NET_Tests, Android.RuntimeTests.InputStreamInvokerTest.InputStreamTest / Release
System.IO.DirectoryNotFoundException : IO_PathNotFound_Path, /tmp/
at Interop.ThrowExceptionForIoErrno(Interop.ErrorInfo, String, Boolean) + 0x11
at Interop.CheckIo(Int64, String, Boolean) + 0x5d
at System.IO.Path.GetTempFileName() + 0x14d
at Android.RuntimeTests.InputStreamInvokerTest.InputStreamTest() + 0x18
at libMono.Android.NET-Tests!<BaseAddress>+0x1483023
at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) …
=> [nativeaot] set `$HOME` and `$TMPDIR`

src/native/monodroid/monodroid-glue.cc
Fixes: https://github.com/dotnet/android/issues/9573
Context: 8e1c0e6e2f4c41c9a24904bb1cea943357d78ac4
A customer reports that they are unable to attach a debugger to 32-bit Android apps:
> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.companyname.exemploandroid/crc64358cda76bdc6f75f.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.companyname.exemploandroid/crc64358cda76bdc6f75f.MainActivity }
…
[monodroid-debug] Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=127.0.0.1:8805,server=y,embedding=1,timeout=8
…
[mono] Listening on 127.0.0.1:8805 (timeout=8 ms)...
[mono] debugger-agent: Timed out waiting to connect.
Of particular note …
=> Fix Debugger timeout on 32 bit devices for .net 9

NuGet.config, eng/Version.Details.xml, eng/Versions.props
.NET 8 Changes: https://github.com/dotnet/android/compare/a8cd27e430e55df3e3c1e3a43d35c11d9512a2db...cdb777a0c306e3e0668f847433f82144d7ca745f
.NET 9 Changes: http://github.com/dotnet/android/compare/4b20432d95ea8965a41cc73997e459d7fa561233...1719a35b8a0348a4a8dd0061cfc4dd7fe6612a3c
Updates the previous .NET for Android SDK versions to the packages that
will be shipping in the upcoming VS 17.14 preview 2 release.
=> Update AndroidNetPreviousVersion to 35.0.50 and 34.0.148

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/dotnet/android/issues/9526
Today, we need to run *either* `ILLink` or `_LinkAssembliesNoShrink`, however they have different triggers:
- [`ILLink` - `$(PublishTrimmed)` = `true`](https://github.com/dotnet/runtime/blob/f63d96e434576ae81a105a7e52634a877058b978/src/tools/illink/src/ILLink.Tasks/build/Microsoft.NET.ILLink.targets#L92-L96)
- `_LinkAssembliesNoShrink` - `$(AndroidLinkMode)` = `None`
These can get out of sync, particularly when using global properties, causing both to be run.  
Update `_LinkAssembliesNoShrink` to trigger when `$(PublishTrimmed)` != `true` to ensure that we don't run it if `ILLink` is being run.
=> [XABT] Don't run `_LinkAssembliesNoShrink` when `$(PublishTrimmed)` = `true`.

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
Changes: https://github.com/android/ndk/wiki/Changelog-r28
Important changes:
* Toolchain switches to LLVM 19.0.0
* 16k page alignment is enabled by default
=> Bump NDK to r28

build-tools/automation/yaml-templates/variables.yaml
Attempt to fix package signature verification failures for apkdiff that we've seen on the release/8.0.4xx branch.
=> [release/8.0.4xx] Update apkdiff to 0.0.17

build-tools/automation/yaml-templates/run-msbuild-tests.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/automation/yaml-templates/stage-msbuild-emulator-tests.yaml, build-tools/automation/yaml-templates/variables.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10326490&view=logs&j=293e774d-1b3c-56a2-2db1-26d172f04ddd&t=b180d07a-099b-5dc9-8d17-5c88abaf95ba&l=11
The attempt to install Xamarin.Android is failing on macOS anyway, as it relies on a VS Mac updater service:
Querying https://software.xamarin.com/Service/Updates?v=2&pv964ebddd-1ffe-47e7-8128-5ce17ffffb05=0&pv4569c276-1397-4adb-9485-82a7696df22e=0&pvd1ec039f-f3db-468b-a508-896d7c382999=0&pv0ab364ff-c0e9-43a8-8747-3afb02dc7731=0&level=Stable
Retry attempt 1: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
at Boots.Core.HttpClientWithPolicy.DoGetXmlDocumentAsync(Uri uri, CancellationToken token) in …
=> [release/8.0.4xx] [build] stop installing Xamarin.Android

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
Updates `InstallAndroidDependencies` to install JDK 17.0.14 over 17.0.8.
We should be able to set the JDK version that is installed via the
`InstallAndroidDependencies` -> `_InstallAndroidJdk` target without
updating monodroid.
=> [release/8.0.4xx] Prefer JDK 17.0.14

src/monodroid/jni/monodroid-glue.cc
Fixes: https://github.com/dotnet/android/issues/9573
Context: 8e1c0e6e2f4c41c9a24904bb1cea943357d78ac4
A customer reports that they are unable to attach a debugger to 32-bit Android apps:
> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.companyname.exemploandroid/crc64358cda76bdc6f75f.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.companyname.exemploandroid/crc64358cda76bdc6f75f.MainActivity }
…
[monodroid-debug] Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=127.0.0.1:8805,server=y,embedding=1,timeout=8
…
[mono] Listening on 127.0.0.1:8805 (timeout=8 ms)...
[mono] debugger-agent: Timed out waiting to connect.
Of particular note …
=> Fix Debugger timeout on 32 bit devices for .net 8

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.AssemblyResolution.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NativeAOT.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidApplicationProject.cs
The `EmbeddedResources_ShouldBeLocalized()` test was failing under a NativeAOT context:
Embedded string resource did not contain expected value after changing CultureInfo.
String lengths are both 1. Strings differ at index 0.
Expected: "b"
But was:  "a"
-----------^
After reviewing a `.binlog`, it appears the `_ComputeIlcCompileInputs` MSBuild target was not working as expected:
https://github.com/dotnet/runtime/blob/cc803458ab4dabf020b462873be5bf56f1640b1e/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Publish.targets#L3-L11
`@(IntermediateSatelliteAssembliesWithTargetPath)` was blank!
The problem being the way Android has an "inner" build per RID:
* `@(IntermediateSatelliteAssembliesWithTargetPath)` is set in the "outer" build.
* …
=> [nativeaot] fix `.resx` files in apps

src/Mono.Android/Android.Runtime/JNIEnv.cs
`JNIEnv.GetJniName()` would fail under NativeAOT, as `TypemapManagedToJava()` will eventually call a p/invoke that doesn't exist.
Update this method to go through the `JniRuntime.JniTypeManager.GetTypeSignature()`, abstraction that should be used instead.
=> [Mono.Android] update `JNIEnv.GetJniName()`

tests/MSBuildDeviceIntegration/Resources/LinkDescTest/HttpClientTest.cs
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=11188869&view=ms.vss-test-web.build-test-results-tab&runId=124545813&resultId=100000&paneView=debug
This test can randomly fail with:
03-13 20:25:44.700  2623  2623 I XALINKERTESTS: [FAIL] HttpClientTest.Post FAILED: System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode_reason, 503, Service Temporarily Unavailable
03-13 20:25:44.700  2623  2623 I XALINKERTESTS:    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
03-13 20:25:44.700  2623  2623 I XALINKERTESTS:    at HttpClientTest.Post()
I made this test print an `[IGNORE]` result if this occurs, similar to what we did in 455ec0a4f.
=> [tests] ignore network errors in `CustomLinkDescriptionPreserve` test

NuGet.config, eng/Version.Details.xml, eng/Versions.props
Changes: https://github.com/dotnet/android/compare/cdb777a0c306e3e0668f847433f82144d7ca745f...fea9dcd5824c760485e39138b38999c303da8b56
* [release/8.0.4xx] Update apkdiff to 0.0.17 (#9894)
* [release/8.0.4xx] Prefer JDK 17.0.14
* [release/8.0.4xx] [build] stop installing Xamarin.Android (#9895)
* Fix Debugger timeout on 32 bit devices. (#9881)
=> Bump to 34.0.153 of the .NET 8 Android workload

tests/Mono.Android-Tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidClientHandlerTests.cs, tests/Mono.Android-Tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidMessageHandlerTests.cs
In the never-ending saga of trying to ignore temporary HTTP errors in `Mono.Android-Tests` test methods, our [latest attempt](https://github.com/dotnet/android/pull/9871) uses `Assert.Ignore`.  Behind the scenes, `Assert.Ignore` breaks out of a test by throwing `NUnit.Framework.IgnoreException`.  However our very dated test runner doesn't seem to handle this exception properly when in an `async` `Task` test method, resulting in this test failure:
```
System.AggregateException : AggregateException_ctor_DefaultMessage (Ignoring network/server failure: ServiceUnavailable)
----> NUnit.Framework.IgnoreException : Ignoring network/server failure: ServiceUnavailable
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
at …
```
=> [Mono.Android-Tests] Ignore temporary HTTP errors in async test methods.

build-tools/automation/yaml-templates/run-sliced-nunit-tests.yaml
Context: https://github.com/dotnet/android/commit/d00b779a5b5f405af967d85e28e570e873631a6b
Commit https://github.com/dotnet/android/commit/d00b779a5b5f405af967d85e28e570e873631a6b added a unit test retry mechanism to address flaky emulator tests.  
This works by:
- Running the unit tests via `dotnet test`
- Running `dotnet-test-slicer` to create a test filter that only contains the failed tests
- Rerunning `dotnet test` with the filtered test list
In the case where there are no failed tests, a "dummy" filter is created that does not match any tests.
Most of the time this is fine and the `dotnet test` invocation with the dummy filter takes a couple of seconds to determine it has nothing to do and exits.  However, this ***no-op*** can ***itself*** hang, causing the build to hang for ~3 …
=> [ci] Don't re-run `dotnet test` if there are no auto retry tests.

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
=> Set HttpActivityPropagationSupport=true for non-Release builds

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, tests/Mono.Android-Tests/Mono.Android-Tests/System/AppContextTests.cs
Primarily to light up the metrics when using .NET MAUI apps with .NET Aspire, but this will emit metrics for potential other purposes as well.
With this change the `MetricsSupport` property will only be set to `false` when the property has no value and the build is not a `Release` build.
That means, if the property is not explicitly set in the .NET MAUI project (or .NET for Android project) and the build is not a `Release` build, the property will be set to `true` (the default value) and emit metrics.
cc: @rolfbjarne I was informed you were going to disable this for iOS, so it might be good to keep this in mind as well for that!
=> Enable MetricsSupport by default for non-Release builds

.gitmodules
Fixes: https://github.com/dotnet/java-interop/issues/23
Changes: https://github.com/dotnet/java-interop/compare/bc44f085f6785abb2e3d2a9533a70b2f63d681b8...5852e6e398a6c96d42fff3ed4b8a5d4b5a0abf97
* dotnet/java-interop@5852e6e3: [Java.Interop] Use `Class.forName()` as fallback to load Java classes (dotnet/java-interop#1326)
=> Bump to dotnet/java-interop/main@5852e6e3

.external
Changes: https://github.com/dotnet/android-tools/compare/ac8d0ee46e6f3bc3833577eff9a2190fa1cc52bc...0658bc63ebbc5a7ec08f54f903c0ea2fe832c6aa
* dotnet/android-tools@0658bc6: [Xamarin.Android.Tools.AndroidSdk] OS-specific dirs are OS-specific (dotnet/android-tools#250)
=> Bump to dotnet/android-tools/main@0658bc63

.external
Changes: https://github.com/dotnet/android-tools/compare/ab657dfcebf2d80e422c25e91dd389ec4f2aa1bc...59cab872db5b9544d6e734120393f96be61940bf
* dotnet/android-tools@59cab87: [Xamarin.Android.Tools.AndroidSdk] OS-specific dirs are OS-specific (dotnet/android-tools#250)
* dotnet/android-tools@ab50990: [ci] Move PR build to dnceng public (dotnet/android-tools#249)
=> Bump to dotnet/android-tools/release/9.0.1xx@59cab872

Directory.Build.props
Context: https://github.com/dotnet/android/tree/release/10.0.1xx-preview3
We branched for .NET 10 Preview 3 from 2173aca1 into `release/10.0.1xx-preview3`; the main branch is now .NET 10 Preview 4.
=> $(AndroidPackVersionSuffix)=preview.4

build-tools/automation/yaml-templates/use-dot-net.yaml, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Unix.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.Windows.cs
The dot.net redirector has issues currently, using the CDN URL directly is more reliable anyway.
=> Use CDN URL for dotnet-install script

NuGet.config, eng/Version.Details.xml, eng/Versions.props
Bump previous Android SDK references for the upcoming April servicing release.
.NET 8 Changes: https://github.com/dotnet/android/compare/cdb777a0c306e3e0668f847433f82144d7ca745f...82d8938cf80f6d5fa6c28529ddfbdb753d805ab4
.NET 9 Changes: https://github.com/dotnet/android/compare/1719a35b8a0348a4a8dd0061cfc4dd7fe6612a3c...e7876a4f92d894b40c191a24c2b74f06d4bf4573
=>  Update Android workload versions to 35.0.61 and 34.0.154

build-tools/xaprepare/xaprepare/Application/Utilities.cs
Context: https://github.com/dotnet/arcade/pull/15546
Right now failures just print:
Downloading dotnet-install script...
-> https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.sh
Error: Download of dotnet-install from 'https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.sh' failed
Let's log the exception message, as it retries.
After this change, we get the intermittent error on macOS only:
Warning: Download of 'https://builds.dotnet.microsoft.com/dotnet/scripts/v1/dotnet-install.sh' failed: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown …
=> [xaprepare] log exceptions, and handle CRL check failures

src/Xamarin.Android.Build.Tasks/Utilities/ManagedMarshalMethodsLookupGenerator.cs
Contributes to https://github.com/dotnet/android/issues/9962
The `ManagedMarshalMethodsLookupGenerator` generates IL of a switch statement which looks like this:
```c#
.method public hidebysig static 
native int '<JI>GetFunctionPointer' (
int32 methodIndex
) cil managed 
{
// Method begins at RVA 0xac270
// Header size: 1
// Code size: 59 (0x3b)
.maxstack 8
IL_0000: ldarg methodIndex
IL_0004: switch (IL_001b, IL_0022, IL_0029, IL_0030)
IL_0019: br.s IL_0037
IL_001b: ldftn void Android.App.Application::n_OnCreate_mm_wrapper(native int, native int)
IL_0021: ret
IL_0022: ldftn void Android.App.Application::n_OnLowMemory_mm_wrapper(native int, native int)
IL_0028: ret
IL_0029: ldftn void Android.App.Application::n_OnTrimMemory_I_mm_wrapper(native int, native int, int32)
IL_002f: ret
IL_0030: …
```
=> Avoid using br.s when generating managed UCO lookup tables

src/Microsoft.Android.Runtime.NativeAOT/Android.Runtime.NativeAOT/JavaInteropRuntime.cs, src/Microsoft.Android.Runtime.NativeAOT/Java.Interop/JreRuntime.cs, src/Mono.Android/Android.Runtime/AndroidRuntime.cs, src/Mono.Android/Android.Runtime/JNIEnvInit.cs, src/Mono.Android/Microsoft.Android.Runtime/ManagedValueManager.cs, src/Mono.Android/Mono.Android.csproj
Context: https://github.com/dotnet/android/issues/9962
Context: https://github.com/dotnet/java-interop/commit/5852e6e398a6c96d42fff3ed4b8a5d4b5a0abf97
`dotnet new maui -sc` fails under CoreCLR:
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.companyname.dotnetnewmauisamplecontent, PID: 6548
E AndroidRuntime: android.runtime.JavaProxyThrowable: [System.InvalidOperationException]: InvalidOperation_HandleIsNotInitialized
E AndroidRuntime: 	at System.WeakReference`1.SetTarget + 0x18(Unknown Source)
E AndroidRuntime: 	at Microsoft.Maui.ApplicationModel.ActivityLifecycleContextListener.set_Activity + 0x0(Unknown Source)
E AndroidRuntime: 	at Microsoft.Maui.ApplicationModel.ActivityLifecycleContextListener.Android.App.Application.IActivity …
=> [Mono.Android] Add ManagedValueManager, use with CoreCLR

eng/Version.Details.xml, eng/Versions.props
Context: https://github.com/dotnet/maui/pull/28663
Previously we've been tracking:
<Dependency Name="Microsoft.Android.Sdk.Windows" Version="35.0.61">
<Uri>https://github.com/dotnet/android</Uri>
<Sha>e7876a4f92d894b40c191a24c2b74f06d4bf4573</Sha>
</Dependency>
And then for .NET 8, we just manually updated the
`$(AndroidNet8PreviousVersion)` property.
This makes it difficult for other repositories to *know* about the required NuGet feeds:
<add key="darc-pub-dotnet-android-82d8938" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-android-82d8938c/nuget/v3/index.json" />
<add key="darc-pub-dotnet-android-e7876a4" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-android-e7876a4f/nuget/v3/index.json" />
In dotnet/maui or dotnet/performance, …
=> [darc] track previous .NET Android manifests

src/Mono.Android/Android.Runtime/AndroidRuntime.cs
This is a follow-up to #9973
Replaces #9977 (CI was failing due to long branch name)
This PR fixes the following crash at the startup of `dotnet new maui -sc` when the `AndroidTypeManager` is used:
```
--------- beginning of crash
03-27 09:57:38.276 25497 25497 E AndroidRuntime: FATAL EXCEPTION: main
03-27 09:57:38.276 25497 25497 E AndroidRuntime: Process: com.companyname.testmaui, PID: 25497
03-27 09:57:38.276 25497 25497 E AndroidRuntime: android.runtime.JavaProxyThrowable: [System.MemberAccessException]: Acc_CreateAbstEx, Android.Views.LayoutInflater
03-27 09:57:38.276 25497 25497 E AndroidRuntime: at System.Reflection.RuntimeConstructorInfo.CheckCanCreateInstance + 0x3c(Unknown Source)
03-27 09:57:38.276 25497 25497 E AndroidRuntime: at …
```
=> [CoreCLR] Override GetInvokerTypeCore in AndroidTypeManager

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs
This test has started failing as soon as a `platform-tools` 36.0.0 appeared on Google's feed:
_AndroidSdkDirectory was not set to new SDK path C:\a\_work\1\a\TestRelease\03-28_03.15.36\temp\InstallAndroidDependenciesTestGoogleV2\android-sdk. Please check the task output in 'install-deps.log'
Expected: True
I'm guessing this is because it is still "preview":
<remotePackage path="platform-tools">
<type-details xsi:type="generic:genericDetailsType"/>
<revision>
<major>36</major>
<minor>0</minor>
<micro>0</micro>
</revision>
<display-name>Android SDK Platform-Tools</display-name>
<uses-license ref="android-sdk-preview-license"/>
As the `.binlog` shows:
Component Android SDK Platform-Tools r36.0.0 not present on the system
Component Android SDK Platform-Tools r35.0.2 not …
=> [tests] fix `InstallAndroidDependenciesTest("GoogleV2")`

src/native/clr/host/host-jni.cc, src/native/clr/host/typemap.cc
It seems that as part of refactoring and splitting the big CoreCLR host PR into pieces, the dumping of timing data got disabled for CoreCLR.
This PR reenables this feature so that we can measure startup performance of CoreCLR with https://github.com/grendello/XAPerfTestRunner/tree/master
=> [coreclr] Enable dumping `FastTiming` data with CoreCLR

build-tools/create-packs/Microsoft.Android.Runtime.proj, src/Microsoft.Android.Runtime.NativeAOT/Android.Runtime.NativeAOT/JavaInteropRuntime.cs, src/Microsoft.Android.Runtime.NativeAOT/Java.Interop/JreRuntime.cs, src/Microsoft.Android.Runtime.NativeAOT/Microsoft.Android.Runtime.NativeAOT.csproj, src/Microsoft.Android.Sdk.ILLink/TypeMappingStep.cs, src/Mono.Android/Android.Runtime/AndroidRuntime.cs, src/Mono.Android/Android.Runtime/JNIEnvInit.cs, src/Mono.Android/ILLink/ILLink.Substitutions.xml, src/Mono.Android/Microsoft.Android.Runtime/ManagedTypeManager.cs, src/Mono.Android/Microsoft.Android.Runtime/ManagedTypeMapping.cs, src/Mono.Android/Microsoft.Android.Runtime/RuntimeFeature.cs, src/Mono.Android/Mono.Android.csproj, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.ILLink.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NativeAOT.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.RuntimeConfig.targets, src/Xamarin.Android.Build.Tasks/Tasks/GenerateTypeMappings.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
For NativeAOT, we implemented a "managed" typemap that is trimmer-safe.
In order to test its performance characteristics, we can make this typemap useable for Mono and CoreCLR as well:
* Move `NativeAotTypeManager`, `NativeAotValueManager`, and `TypeMapping` types to `Mono.Android.dll`
* Rename `NativeAot*` to `Managed*`
* Add a new private `$(_AndroidTypeMapImplementation)` MSBuild property that can be set to `llvm-ir` or `managed`.
* Add a new trimmer feature flag `Microsoft.Android.Runtime.RuntimeFeature.ManagedTypeMap` that when `true` uses the managed typemap on any runtime.
I added a test that verifies `dotnet run` succeeds for all typemap implementations.
Note that NativeAOT will *only* support the managed typemap.
=> [Xamarin.Android.Build.Tasks] make "managed typemap" runtime agnostic

src/Xamarin.Android.Build.Tasks/Utilities/TypeMapCecilAdapter.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs
In preparation for future changes to the typemap generation process, this commit refactors the usage of `Mono.Cecil` out of the `TypeMapGenerator` class.  (Part of the "move `GenerateJavaStubs` to linker steps" effort.)
This facilitates a future state where:
- The `Module[Debug|Release]Data` entries are created from `Mono.Cecil` data in the `LinkAssembliesNoShrink`/`ILLink` step and persisted to disk.
- The `GenerateTypeMappings` task reads the persisted information to generate the typemap.
This refactor could be done as part of that future change, but seemed like a smaller change that could be more easily reviewed and committed separately.
=> [XABT] Refactor Cecil usage out of `TypeMapGenerator`.

build-tools/automation/yaml-templates/variables.yaml, build-tools/create-packs/Directory.Build.props, build-tools/create-packs/Directory.Build.targets, build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/GitBranch.cs
If you open a PR with a long branch name, it can error with:
NuGet.Build.Tasks.Pack.targets(221,5): error NU5123: Warning As Error: The file 'package/services/metadata/core-properties/d9cd2ffb8cfc41bdbfe90e7dbc7228fb.psmdcp' path, name, or both are too long. Your package might not work without long file path support. Please shorten the file path or file name.
Let's ignore `NU5123` for pull requests.
I think the warning, in general, is good to know if we create a path inside a `.nupkg` that is too long. But for PRs, we should ignore it.
This also reverts some commits that "shorten" branch names, which should no longer be needed:
* 7651b64895ecf2812e85cd570b61f3950b3db09c
* 6d9b295652ef5292427cb15b2afce469c6ed940f
While making this work, I noticed that the `CreateAllPacks` target did not …
=> [build] see if we can allow long branch names

src/Xamarin.Android.Build.Tasks/Tasks/GenerateTypeMappings.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMapCecilAdapter.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/dotnet/android/pull/9292
In https://github.com/dotnet/android/pull/9292, we removed support for the "instant run" feature.  This feature required the use of typemaps that existed outside of the "native" assemblies (`$(_AndroidGenerateNativeAssembly)` = `false`).  This support is no longer needed, and in fact causes a build error if it is used:
```
Xamarin.Android.Common.targets(2132,3): error XA3006: Could not compile native assembly file: typemaps.x86_64.ll
```
As such, clean up our codebase to remove support for this.
Additionally, unused fields in the `Module[Debug|Release]Data` and `TypeMap[Debug|Release]Entry` data classes were removed to help make it clearer what data is required to generate typemaps.
=> [XABT] Remove support for `$(_AndroidGenerateNativeAssembly)` = `false` (typemaps).

src/Microsoft.Android.Runtime.NativeAOT/Java.Interop/JreRuntime.cs
=> [NativeAOT] Remove unnecessary GetAssemblyLocation method

src/Xamarin.Android.Build.Tasks/Tasks/Generator.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/InlineData.cs, tools/assembly-store-reader/AssemblyStoreManifestEntry.cs, tools/assembly-store-reader/AssemblyStoreManifestReader.cs
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1852953
There was a problem with the generator arguments not allowing for assembly names with spaces in them. 
So lets fix that by adding quotes to make sure the assembly name is parsed correctly. Also add a unit test to make sure we don't regress in the future.
=> Test a project with a Space in the project Name

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FindJavaObjectsStep.cs, src/Xamarin.Android.Build.Tasks/Tasks/AssemblyModifierPipeline.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateACWMap.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaCallableWrappers.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Utilities/ACWMapGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/JavaObjectsXmlFile.cs, src/Xamarin.Android.Build.Tasks/Utilities/UtilityExtensions.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/dotnet/android/pull/9893
Building on https://github.com/dotnet/android/pull/9893, this moves the process of scanning for JLOs needed for the ACW map generation task to the `FindJavaObjectsStep` "linker step".
This process needs `interface` JLOs, which `JavaCallableWrappers` doesn't support.  Expanding the JCW serialization format to allow interfaces (and other ACW-needed data it didn't already support) resulted in a lot of extra processing and waste.
Instead, we expand the `.jlo.xml` file to have 2 sections, one for JCW needed data and one for ACW needed data:
```xml
<api>
<jcw-types>
<type name="MainActivity" package="crc645107ba1b8b6ee4d3" application_java_class="android.app.Application" mono_runtime_initialization="mono.MonoPackageManager.LoadApplication …
```
=> [XABT] Move scanning for ACW map JLOs to `FindJavaObjectsStep`.

build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/azure-pipelines.yaml
Updates the repo reference that provides common yaml templates from https://github.com/xamarin/yaml-templates
to
https://devdiv.visualstudio.com/DevDiv/_git/Xamarin.yaml-templates
=> [ci] Use templates from DevDiv/Xamarin.yaml-templates

samples/NativeAOT/runwithdebugger.ps1, samples/NativeAOT/runwithdebugger.sh
Make it able to detect the OS-specific path to the NDK toolchain binaries, 
as well as the path to the NDK root directory using a number of environment 
variables used at one time or another for this purpose.
Instead of hard-coding path to the `lldb-server` binary, which is located in 
a versioned directory, use `clang` itself to print full path to the binary, 
thus making the script LLVM version agnostic.
Additionally, detect the attached device's architecture and use the correct
`lldb-server` binary.
=> Make the NativeAOT debugger script more flexible

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, src/Mono.Android/Mono.Android.targets
Updates xaprepare and Mono.Android to generate API Docs against
API-36 sources.
=> [Mono.Android] Generate API docs for API level 36

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs, src/Mono.Android/Mono.Android.targets
Updates xaprepare and Mono.Android to generate API Docs against
API-36 sources.
=> [release/9.0.1xx] [Mono.Android] Generate API docs for API level 36

build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/yaml-templates/commercial-build.yaml, build-tools/automation/yaml-templates/start-stop-emulator.yaml
Commit dc089720 broke the nightly build because the symbol upload step
was not using a unique artifact name.
The nightly hosted test pool has been updated to use x64 images and the
tests that run on the shared pool will now prefer Sequoia images.
=> [ci] Fix nightly build symbol artifact upload

Documentation/guides/tracing.md
Context: https://github.com/dotnet/diagnostics/pull/5241
Context: https://www.nuget.org/packages/dotnet-trace/9.0.621003
Introduce documentation for the new `--dsrouter` switch in `dotnet-trace collect` command. This new switch eliminates the need to run `dotnet-dsrouter` as a separate process when profiling. Note that users need at least version 9.0.621003 of the diagnostic tools to use this new feature.
=> [docs] new `dotnet-trace collect --dsrouter` switch

build-tools/automation/azure-pipelines.yaml
The `Publish symbols and Push to Maestro` job and `generate and publish BAR manifest` step fail with:
C:\hostedtoolcache\windows\dotnet\sdk\9.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(166,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 10.0.  Either target .NET 9.0 or lower, or use a version of the .NET SDK that supports .NET 10.0. Download the .NET SDK from https://aka.ms/dotnet/download [D:\a\_work\1\s\build-tools\create-packs\Microsoft.Android.Sdk.proj]
0 Warning(s)
1 Error(s)
It looks like we were using .NET 9 previews in the past:
```yaml
- task: UseDotNet@2
displayName: Install .NET 9.x
inputs:
version: 9.x
includePreviewVersions: true
```
So, we can use .NET 10 previews for this during .NET 10 development.
=> [build] install .NET 10.x for BAR manifest

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/AddKeepAlivesStep.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FindJavaObjectsStep.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixAbstractMethodsStep.cs, src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FixLegacyResourceDesignerStep.cs, src/Xamarin.Android.Build.Tasks/Tasks/AssemblyModifierPipeline.cs, src/Xamarin.Android.Build.Tasks/Tasks/LinkAssembliesNoShrink.cs, src/Xamarin.Android.Build.Tasks/Utilities/AssemblyPipeline.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.Linker.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
In order to continue moving forward with moving tasks from the `<GenerateJavaStubs>` task to our "additional linker steps", we need a more flexible assembly scanning/modification pipeline.  
Specifically, we will need to run "RewriteMarshalMethods" in the `<AssemblyModifierPipeline>` task so that it happens for both linked and non-linked builds.  However, we want to run it:
- After the `FindJavaObjectsStep` step in the `<AssemblyModifierPipeline>` pipeline.
- In the same loop as the other assembly modification steps in the `<LinkAssembliesNoShrink>` task (which is before `<AssemblyModifierPipeline>` steps run) so that we do not need to write the assemblies twice.
Although we could achieve these goals with enough hacks, instead refactor the steps into a proper, flexible "pipeline".
This …
=> [XABT] Refactor `<LinkAssembliesNoShrink>`/`<AssemblyModifierPipeline>` tasks to use an actual pipeline.

build-tools/xaprepare/xaprepare/Steps/Step_InstallDotNetPreview.cs, build-tools/xaprepare/xaprepare/xaprepare.csproj
Fix warnings produced by building and running `xaprepare`:
```
warning NU1510: PackageReference System.Net.Http will not be pruned. Consider removing this package from your dependencies, as it is likely unnecessary.
warning NU1510: PackageReference System.Private.Uri will not be pruned. Consider removing this package from your dependencies, as it is likely unnecessary.
warning NU1510: PackageReference System.Text.Encoding.CodePages will not be pruned. Consider removing this package from your dependencies, as it is likely unnecessary.
EXEC : warning : Using cached installation script found in 'C:\Users\user\android-archives\dotnet-install.ps1'
```
- Remove referenced packages, these were likely required when `xaprepare` was multi-targeting with `net472`
- Convert cached script warning to a …
=> [xaprepare] Fix warnings produced by building and running.

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
Context: https://github.com/dotnet/runtime/issues/112017
Context: https://github.com/dotnet/runtime/pull/113306
In .NET 10 Preview 1, when using System.IO.Compression to create `.apk` files, `zipalign` was giving the error:
01-30 21:38:27.669 38611 159726 W zip     : WARNING: header mismatch
To workaround, we temporarily set `$(_AndroidUseLibZipSharp)=true`.
We think this is fixed now, so partially revert f3ef4fe0.
=> [XABT] remove `$(_AndroidUseLibZipSharp)=true` default value

build-tools/automation/azure-pipelines.yaml, build-tools/automation/yaml-templates/setup-test-environment.yaml, build-tools/automation/yaml-templates/variables.yaml, build-tools/xaprepare/xaprepare/OperatingSystems/OS.cs
This is a list of things I fixed...
The `MAUI Integration` job looks to be failing, because we are
building with a .NET 9 SDK:
C:\Users\cloudtest\.nuget\packages\microsoft.dotnet.arcade.sdk\10.0.0-beta.25212.1\tools\RepositoryValidation.proj(33,5): error MSB4018: The "Microsoft.DotNet.Arcade.Sdk.GetLicenseFilePath" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at Microsoft.DotNet.Arcade.Sdk.GetLicenseFilePath.ExecuteImpl()
at Microsoft.DotNet.Arcade.Sdk.GetLicenseFilePath.Execute() in …
=> [build] fix `MAUI Integration` job

build-tools/automation/azure-pipelines-nightly.yaml, build-tools/automation/yaml-templates/variables.yaml
Jobs running on the shared macOS pool will now use the latest Sequoia
images which should hopefully bring better performance and reliability.
=> [ci] Use Sequoia images for all shared mac jobs

Directory.Build.props, src/Xamarin.Android.Build.Tasks/Tasks/CollectNativeFilesForArchive.cs, src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.Basic.cs, tools/assembly-store-reader-mk2/AssemblyStore/AssemblyStoreExplorer.cs, tools/decompress-assemblies/main.cs
Fix all NRT warnings in `assembly-store-reader-mk2` and `decompress-assemblies` tools and removes them from the "allow warnings" allow-list in the `Directory.Build.props` file.
=> Fix NRT warnings in `assembly-store-reader-mk2` and `decompress-assemblies` tools.

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
ReadyToRun deployments are enabled when:
1. `<PublishReadyToRun>true</PublishReadyToRun>` is added to the project file
3. App is published via: `dotnet publish`
Once enabled, the SDK injects necessary build tasks to perform AOT compilation of assemblies after their trimming and creation of R2R images during app publish.
Currently, Android app build runs two assembly postprocessing build tasks (after R2R image generation): `RewriteMarshalMethods` and `RemoveRegisterAttribute` that are modifying assemblies with `Mono.Cecil`. However, altering R2R assemblies is not supported with Mono.Cecil and build fails via:
```
System.NotSupportedException: Writing mixed-mode assemblies is not supported
         at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, …
```
=> [coreclr] Initial support of R2R builds

.github/dependabot.yml
Our build has the `NU1510` warnings like:
external\debugger-libs\Mono.Debugging\Mono.Debugging.csproj warning NU1510: PackageReference System.Buffers will not be pruned. Consider removing this package from your dependencies, as it is likely unnecessary.
external\debugger-libs\Mono.Debugging\Mono.Debugging.csproj warning NU1510: PackageReference System.Collections.Immutable will not be pruned. Consider removing this package from your dependencies, as it is likely unnecessary.
external\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft.csproj warning NU1510: PackageReference System.Runtime will not be pruned. Consider removing this package from your dependencies, as it is likely unnecessary.
external\debugger-libs\Mono.Debugger.Soft\Mono.Debugger.Soft.csproj warning NU1510: …
=> [dependabot] allow mono/debugger-libs to update

Configuration.props, src/Mono.Android/Mono.Android.targets, src/Xamarin.Android.Build.Tasks/Tasks/Javac.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in, src/java-runtime/java-runtime.csproj
Fixes: https://github.com/dotnet/android/issues/9922
Fixes: https://github.com/dotnet/android/issues/9925
In 165cef7d, we started compiling with Java 17 by default. This causes warnings in #9922 such as:
"/Users/builder/android-toolchain/jdk-21/bin/java" -classpath "/Users/builder/azdo/_work/11/s/xamarin-android/bin/Release/lib/packs/Microsoft.Android.Sdk.Darwin/35.99.0/tools/r8.jar" com.android.tools.r8.D8 --release --no-desugaring --output "obj/Release/release" "/Users/builder/azdo/_work/11/s/xamarin-android/bin/Release/lib/packs/Microsoft.Android.Sdk.Darwin/35.99.0/tools/java_runtime.jar"
Warning in /Users/builder/azdo/_work/11/s/xamarin-android/bin/Release/lib/packs/Microsoft.Android.Sdk.Darwin/35.99.0/tools/java_runtime.jar:mono/MonoPackageManager.class at …
=> [build] default `$(JavacSource/TargetVersion)` to 1.8 for Android code

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateMainAndroidManifest.cs, src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs, src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodCecilAdapter.cs, src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodsNativeAssemblyGenerator.cs
Context: https://github.com/dotnet/android/issues/10062
_One_ issue with our desire to move around LLVM Marshal Method build code so that it can work with Ready2Run is that our current implementation relies on holding Cecil `AssemblyDefinition` objects open in global state across multiple targets.  While these objects are open, no other process can access our assemblies, making it harder to reorder targets and tasks.
As a first step towards refactoring this process, let's move the data into a DTO that does not require Cecil.  Additionally, this makes it clear _what_ data is actually consumed by `<GeneratePackageManagerJava>` rather than "entire assemblies" so we can focus on how to properly obtain and persist the data.
This still relies on `BuildEngine4.RegisterTaskObject` to store the …
=> [XABT] GeneratePackageManagerJava - Convert `NativeCodeGenState` to Cecil-less DTOs.

.gitignore, build-tools/automation/yaml-templates/fail-on-dirty-tree.yaml
Context: https://github.com/dotnet/android/pull/9661
Building on https://github.com/dotnet/android/pull/9661, we also shouldn't be writing build artifacts to the source tree.
Any files generated by the build should be placed in `/bin` or `/obj` folders rather than the source tree.
Violations fixed by putting the artifact in `.gitignore`.
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
src/native/CMakePresets.json
```
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
src/native/CMakePresets.json
src/native/clr/host/generate-pinvoke-tables
src/native/clr/host/pinvoke-tables.include.generated
src/native/mono/pinvoke-override/generate-pinvoke-tables
src/native/mono/pinvoke-override/pinvoke-tables.include.generated
```
``` …
```
=> [ci] Fail build if any untracked files written in git tree

build-tools/create-packs/Microsoft.Android.Sdk.proj
Context: https://github.com/dotnet/android/commit/dc089720b658de788990f1c3426d19c673ccfa20
Removes the extra `runtimes` folder that was inadvertently included in the symbols target path in the new symbols.nupkg files.
Before:
53652  01-24-2021 16:24   runtimes/tools/HtmlAgilityPack.pdb
42736  04-24-2025 21:55   runtimes/tools/Java.Interop.Tools.Maven.pdb
42940  06-06-2024 15:33   runtimes/tools/libZipSharp.pdb
....
After:
53652  01-24-2021 16:24   tools/HtmlAgilityPack.pdb
42736  04-24-2025 21:55   tools/Java.Interop.Tools.Maven.pdb
42940  06-06-2024 15:33   tools/libZipSharp.pdb
....
=> [workload] Fix symbols paths in Microsoft.Android.Sdk

build-tools/automation/yaml-templates/stage-package-tests.yaml, samples/NativeAOT/NativeAOT.csproj, tests/Mono.Android-Tests/Java.Interop-Tests/Java.InteropTests/AndroidValueManagerContractTests.cs, tests/Mono.Android-Tests/Mono.Android-Tests/Java.Interop/JnienvTest.cs, tests/Mono.Android-Tests/Mono.Android-Tests/Java.Lang/ObjectTest.cs, tests/Mono.Android-Tests/Mono.Android-Tests/Mono.Android.NET-Tests.csproj, tests/Mono.Android-Tests/Mono.Android-Tests/System/AppContextTests.cs, tests/Mono.Android-Tests/Mono.Android-Tests/System/ExceptionTest.cs, tests/Mono.Android-Tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidClientHandlerTests.cs, tests/Mono.Android-Tests/Mono.Android-Tests/Xamarin.Android.Net/HttpClientIntegrationTests.cs
Context: https://github.com/dotnet/android/issues/10079
This runs Mono.Android-Tests with `-p:PublishAot=true`.
I temporarily disabled the following tests:
* The `Java.Interop-Tests.dll` test assembly
* `GCBridge` category, related to a missing "GC Bridge"
* `SSL` and `NTLM` categories related to some http tests
* Some individual tests
These categories will probably *never need to* work on NativeAOT:
* `Export`: use of `Mono.Android.Export.dll`
* `AndroidClientHandler`: legacy `HttpClientHandler` implementation
* `NativeTypeMap`: as the managed typemap is trimmer safe
* `AppContextTests.TestPrivateSwitches` may not be relevant for NativeAOT
I left a `TODO` comment for each ignored test, to investigate in the future.
=> [nativeaot] run Mono.Android-Tests

build-tools/create-packs/Directory.Build.targets
Context: https://github.com/dotnet/arcade/blob/79ecdf3ef50e5e8e9d2b02e7113ec37c4219eeb5/src/Microsoft.DotNet.Build.Manifest/BuildModelFactory.cs#L95
Builds on main/release branches fail with:
build-tools\create-packs\Directory.Build.targets(175,5): error : Missing 'Kind' property on artifact D:\a\_work\1\a\nuget-signed\Microsoft.Android.Ref.36.36.0.0-ci.main.72.nupkg.
Possible values are 'Blob', 'PDB', 'Package'.
Set `%(Kind)=Package` for `.nupkg` files and `%(Kind)=Blob` for everything else.
=> [build] set `%(Kind)` for `PushManifestToBuildAssetRegistry`

Directory.Build.props
Context: https://github.com/dotnet/android/tree/release/10.0.1xx-preview4
We branched for .NET 10 Preview 4 from 5c5745c into `release/10.0.1xx-preview4`; the main branch is now .NET 10 Preview 5.
=> $(AndroidPackVersionSuffix)=preview.5

src/Xamarin.Android.Build.Tasks/Tasks/Javac.cs
Fixes: https://github.com/dotnet/android/issues/9925
Partial backport of: https://github.com/dotnet/android/pull/10050
For backporting to .NET 9, we just need to suppress a warning that JDK 21 will show when using `javac -source 1.8 -target 1.8`.
=> [release/9.0.1xx] pass `-Xlint:-options` for `javac` -target/source 1.8

samples/NativeAOT/MainApplication.cs, src/Microsoft.Android.Runtime.NativeAOT/UncaughtExceptionMarshaler.cs
Context: 9ad492a42b384519a8b1f1987adae82335536d9c
Context: https://github.com/dotnet/runtime/issues/102730
Commit 9ad492a4 had a TODO:
> TODO: once dotnet/runtime#102730 is fixed, update
> `UncaughtExceptionMarshaler` to do whatever it needs to do to cause
> the `AppDomain.UnhandledException` event to be raised.
dotnet/runtime#102730 *has* been fixed.
Update `UncaughtExceptionMarshaler` to call
`ExceptionHandling.RaiseAppDomainUnhandledExceptionEvent(object)` with the unhandled exception, so that the
`AppDomain.UnhandledException` event is raised.
Update `samples/NativeAOT` to subscribe to the
`AppDomain.UnhandledException` event.
Install the app:
./dotnet-local.sh build -t:Install samples/NativeAOT/NativeAOT.csproj
and run the sample so that it throws an unhandled exception:
adb shell am …
=> [NativeAOT] Raise `AppDomain.UnhandledException` event

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NativeAOT.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AssetPackTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.TestCaseSource.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/ProjectExtensions.cs
For each "smoke test" that build an Android application project (libraries not really relevant), we run the test on all runtimes.
For each test, I generally added two more test cases for NativeAOT and CoreCLR.
This is a first step to ensure that we don't break CoreCLR or NativeAOT support at build time.
This also discovered a bug on NativeAOT, in a project with spaces:
clang no such file or directory: 'Me.so'
C:\Users\cloudtest\.nuget\packages\microsoft.dotnet.ilcompiler\10.0.0-preview.5.25227.101\build\Microsoft.NETCore.Native.targets(391,5): error MSB3073: The command ""clang" "obj\Release\android-arm64\native\Test Me.o" -o "bin\Release\android-arm64\native\Test Me.so" -Wl,--version-script="obj\Release\android-arm64\native\Test Me.exports" -Wl,--export-dynamic -gz=zlib -fuse-ld=lld …
=> [ci] run MSBuild "SmokeTests" category on all runtimes

Documentation/docs-mobile/building-apps/build-properties.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
Context: https://github.com/dotnet/macios/pull/22685
Context: https://github.com/dotnet/macios/issues/19370
To simplify inclusion of the Mono diagnostics component, the iOS/macOS/etc. workloads are introducing a new `$(EnableProfiler)` property.
To align with Android, we can make `$(EnableProfiler)` available and work the same way as the existing `$(AndroidEnableProfiler)` property.
I documented `$(AndroidEnableProfiler)` (which was missing!), and also added an entry about the new, `$(EnableProfiler)` property.
=> [XABT] introduce `$(EnableProfiler)` property

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FindJavaObjectsStep.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateMainAndroidManifest.cs, src/Xamarin.Android.Build.Tasks/Tasks/RewriteMarshalMethods.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/MarshalMethodTests.cs, src/Xamarin.Android.Build.Tasks/Utilities/CecilExtensions.cs, src/Xamarin.Android.Build.Tasks/Utilities/JCWGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodsAssemblyRewriter.cs, src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodsClassifier.cs, src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodsCollection.cs, src/Xamarin.Android.Build.Tasks/Utilities/NativeCodeGenState.cs, src/Xamarin.Android.Build.Tasks/Utilities/XAJavaTypeScanner.cs, src/Xamarin.Android.NamingCustomAttributes/Android.Runtime/RegisterAttribute.cs
Today the marshal method scanning process is tightly coupled to scanning for JavaCallableWrappers. That is, when building `CallableWrapperType` objects, the `MarshalMethodsClassifier` is used to classify methods as marshal methods by calling `ShouldBeDynamicallyRegistered (...)`.
However `ShouldBeDynamicallyRegistered` doesn't just return a simple `bool`, it has the side effect of building a list of `MarshalMethodEntry` objects that are used extensively throughout the build process.
We are likely going to need to build this list in places other than JavaCallableWrappers scanning: assembly rewriting will likely be before JCWs, and `GenerateNativeMarshalMethodSources` will likely be after JCWs.
As such:
- Rework `MarshalMethodsClassifier` to simply classify methods as LLVM marshal method …
=> [XABT] Separate marshal method storage from `MarshalMethodClassifier` to `MarshalMethodsCollection`.

src/Mono.Android/Microsoft.Android.Runtime/ManagedValueManager.cs, tests/Mono.Android-Tests/Mono.Android-Tests/Java.Lang/ObjectTest.cs
The following test is failing on NativeAOT as well as any case we'd use `ManagedValueManager`:
[Test]
public void JnienvCreateInstance_RegistersMultipleInstances ()
{
using (var adapter = new CreateInstance_OverrideAbsListView_Adapter (Application.Context)) {
var intermediate  = CreateInstance_OverrideAbsListView_Adapter.Intermediate;
var registered    = Java.Lang.Object.GetObject<CreateInstance_OverrideAbsListView_Adapter>(adapter.Handle, JniHandleOwnership.DoNotTransfer);
Assert.AreNotSame (adapter, intermediate); // Passes
Assert.AreSame (adapter, registered);      // Fails!
}
}
With the assertion:
Expected: same as <com.xamarin.android.runtimetests.CreateInstance_OverrideAbsListView_Adapter{cbd0e5a V.ED.VC.. ......I. 0,0-0,0}>
But was: …
=> [Mono.Android] fix "replaceable" objects in `ManagedValueManager`

src/Xamarin.Android.Build.Tasks/Tasks/AndroidComputeResPaths.cs, src/Xamarin.Android.Build.Tasks/Tasks/CreateAar.cs
Context: https://github.com/dotnet/android/pull/10099
Context: https://github.com/dotnet/android/pull/9918
#10099 enabled NRT checks for a number of XABT Tasks and was merged because all the tests passed.  However, #10099 was not rebased on the tip of `main` which, in the meantime, contained code from the recently merged #9918 PR. #9918 introduced a couple of `string` properties to the `AndroidComputeResPaths` and `CreateAar` tasks, which were not nullable annotated.
This resulted in the following build errors once #10099 was merged:
```
src/Xamarin.Android.Build.Tasks/Tasks/AndroidComputeResPaths.cs(52,17): error CS8618: Non-nullable property 'PrefixProperty' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as …
```
=> [XABT] Fix build errors caused by enabling nullable checks in the tasks

tests/Mono.Android-Tests/Java.Interop-Tests/Java.Interop-Tests.NET.csproj, tests/Mono.Android-Tests/Mono.Android-Tests/Xamarin.Android.RuntimeTests/NUnitInstrumentation.cs
Until a "GC Bridge" exists, for `Java.Interop-Tests` to work on the new runtimes, we need to set:
```xml
<DefineConstants Condition=" '$(UseMonoRuntime)' == 'false' or '$(PublishAot)' == 'true' ">$(DefineConstants);NO_GC_BRIDGE_SUPPORT</DefineConstants>
```
=> [tests] enable Java.Interop-Tests for CoreCLR

eng/Version.Details.xml
Fixes: https://github.com/dotnet/android/issues/10074
Context: https://github.com/dotnet/sdk/issues/39892
`Microsoft.DotNet.ApiCompat` was moved to dotnet/sdk in later versions than 7.x, so we really can't track it with darc/maestro unless we move to the new version.
Let's remove the entry from `eng/Version.Details.xml` to prevent confusion.
The version number remains in `eng/Versions.props`, so this should not affect our build to remove this.
=> [darc] stop tracking `Microsoft.DotNet.ApiCompat` from dotnet/arcade

build-tools/create-packs/Microsoft.NET.Sdk.Android.proj, build-tools/scripts/DotNet.targets, eng/Versions.props
In fc72bb40, we migrated to a 9.0.300 .NET SDK, which unfortunately resulted in an Android workload manifest with a 9.0.300 version band:
Microsoft.NET.Sdk.Android.Manifest-9.0.300.35.0.73.nupkg
To stay on 9.0.100, we need to also set `$(DotNetSdkManifestsFolder)` in `eng/Versions.props` in addition to the other properties we set in fc72bb40.
=> [release/9.0.1xx] fix `Microsoft.NET.Sdk.Android.Manifest-9.0.100` version band

src/Microsoft.Android.Runtime.NativeAOT/Android.Runtime.NativeAOT/JavaInteropRuntime.cs, src/Xamarin.Android.Build.Tasks/Resources/JavaInteropRuntime.java, src/Xamarin.Android.Build.Tasks/Resources/NativeAotRuntimeProvider.java, tests/Mono.Android-Tests/Mono.Android-Tests/Java.Interop/JnienvTest.cs
Fixes: https://github.com/dotnet/android/issues/10081
Fixes: https://github.com/dotnet/android/issues/10118
Context: 18ca52896f36bd756f6b9df801758ab4fe3dc31a
Context: https://github.com/dotnet/java-interop/commit/5852e6e398a6c96d42fff3ed4b8a5d4b5a0abf97
dotnet/java-interop@5852e6e3 updated `JniEnviroment.Types.FindClass()` to begin using [`Class.forName(String, bool, ClassLoader)`][0] to load Java types instead of `ClassLoader.loadClass()`.
This broke type registration on non-Java threads under NativeAOT; attempting to load a non-Android Java type from a managed thread:
var t = new System.Threading.Thread(() => {
using var c = new ClassFromThisAssembly();
});
t.Start();
t.Join();
would fail with a `ClassNotFoundException`:
E NUnit   : Java.Lang.ClassNotFoundException: Didn't find class …
=> [NativeAOT] Provide the Android ClassLoader

src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs, src/Mono.Android/Android.Runtime/JNINativeWrapper.g.tt
Fixes: https://github.com/dotnet/android/issues/10126
Context: 4b158cee17f01abc792383169ba6eb026c99bbd4
Context: https://github.com/dotnet/java-interop/commit/356485ee41fb61570e84c11ba120d6f8cf81ae09
Context: 32cff4383232d5de156bd6c5d10292fcffa66d50
NativeAOT currently requires new binding assemblies, bindings which do not use `JNINativeWrapper.CreateDelegate()`, as one of the code paths within `JNINativeWrapper.CreateDelegate()` uses `System.Reflection.Emit`, which does not exist in NativeAOT. dotnet/java-interop@356485ee contains the `generator` changes needed to avoid `JNINativeWrapper.CreateDelegate()`.
However, there is one situation in which that "requirement" is (kinda) *conditional*: commit 32cff438 added "builtin" JNI wrapper methods, avoiding the need for System.Reflection.Emit …
=> [NativeAOT] "Fix" AndroidRuntimeInternal.WaitForBridgeProcessing()

src/Xamarin.Android.Build.Tasks/Tasks/GenerateAdditionalProviderSources.cs, src/Xamarin.Android.Build.Tasks/Tasks/GenerateMainAndroidManifest.cs, src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodCecilAdapter.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Move the process of generating additional provider source code out of the `<GenerateMainAndroidManifest>` task into a new `<GenerateAdditionalProviderSources>` task.
Additionally, move the Cecil data needed for this task into the Cecil-less `NativeCodeGenStateObject` class to help facilitate a future where we aren't using Cecil in the `_GenerateJavaStubs` target.
=> [XABT] Move additional provider source code generation out of `<GenerateMainAndroidManifest>` task.

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/FindTypeMapObjectsStep.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AssetPackTests.cs, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.TestCaseSource.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMapCecilAdapter.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMapGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMapObjectsXmlFile.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingDebugNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/TypeMappingDebugNativeAssemblyGeneratorCLR.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/native/clr/host/assembly-store.cc, src/native/clr/host/internal-pinvokes.cc, src/native/clr/host/typemap.cc, src/native/clr/include/host/typemap.hh, src/native/clr/include/xamarin-app.hh, src/native/clr/xamarin-app-stub/application_dso_stub.cc, src/native/common/include/shared/xxhash.hh, src/native/common/runtime-base/timing-internal.cc, src/native/native.targets
Implements support for Debug configuration typemaps in CoreCLR apps.
This PR is limited to the managed-to-java lookup, as the java-to-managed one isn't
currently used in CoreCLR apps (that lookup is done in managed code, I will open a
new PR to experiment in this area). 
This PR also doesn't implement support for fastdev, it will be addressed in a separate PR.
CoreCLR doesn't provide us with a way to translate a `System.Type` instance to a type name in
native code, and therefore the managed code calls into the native runtime to perform the lookup using the type name and the assembly MVID.  However, the managed-to-java lookup tables use the assembly-qualified managed type name, so this PR introduces a step to "fix up" the 
passed managed type name by appending the assembly name, which is …
=> [CoreCLR] support for debug build typemaps

Directory.Build.props, Documentation/guides/HowToBranch.md
Context: https://github.com/dotnet/android/tree/release/10.0.1xx-preview5
We branched for .NET 10 Preview 5 from 7486928c into `release/10.0.1xx-preview5`; the main branch is now .NET 10 Preview 6.
I also updated `HowToBranch.md`.
=> $(AndroidPackVersionSuffix)=preview.6

Documentation/docs-mobile/building-apps/build-properties.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
Context: https://github.com/dotnet/macios/pull/22982
Context: https://github.com/dotnet/runtime/issues/115473#issuecomment-2933946678
We are aligning WASM, iOS, Android to all use the same property name for this.
=> [xabt] rename `$(EnableProfiler)` to `$(EnableDiagnostics)`

src/Mono.Android/Java.Interop/TypeManager.cs
I noticed there were _thousands_ of log messages such as `I monodroid: Loaded type: Java.Lang.Object` printed in logcat while running unit tests. It turns out we aren't caching the resolved type mappings when the `GetJavaToManagedType` method is called from `AndroidRuntime.GetTypesForSimpleReference`. This hurts performance because the call to `clr_typemap_java_to_managed` is fairly expensive.
This PR makes sure we're using the `TypeManagerMapDictionaries.JniToManaged` cache in this codepath.
=> [CoreCLR] Cache JNI to Managed type mappings

.external, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs
Fixes: https://github.com/dotnet/android/issues/10167
FastDev binary utilities are rebuilt with 16k page alignment for arm64, 
which causes them not to segfault on devices or emulators which enabled 
16k page support.
At the same time, the 16k-aligned binaries work fine on 4k-page devices/emulators.
Tested both on Android 16.
=> Bump android-platform-support submodule

src/Xamarin.Android.Build.Tasks/Tasks/GenerateNativeMarshalMethodSources.cs, src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodsNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodsNativeAssemblyGeneratorCoreCLR.cs, src/Xamarin.Android.Build.Tasks/Utilities/MarshalMethodsNativeAssemblyGeneratorMonoVM.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/native/clr/include/xamarin-app.hh, src/native/clr/xamarin-app-stub/application_dso_stub.cc, src/native/common/include/runtime-base/timing-internal.hh
Our build process targetting CoreCLR generated marshal methods code that is
only used by our MonoVM runtime. The native code included marshal methods and 
class names, as well as assembly image cache which is not supported on CoreCLR.
All of the above data were stored as pointers in the resulting `libxamarin-app.so`,
each pointer being a relocation that has to be fixed up by the system dynamic linker
at application load time. The more relocations exist across the `.so` file, the more
of it the linker has to actually read into memory (instead of just mmapping it and 
lazily loading whenever/if the code/data in that section is used).
This PR removes all of that code from the CoreCLR version of `libxamarin-app.so`,
together with a number of native structs supporting the data.
Testing the …
=> [CoreCLR] Remove unused marshal methods code

Documentation/docs-mobile/building-apps/build-properties.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.Aot.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, tests/MSBuildDeviceIntegration/Tests/InstallAndRunTests.cs
Fixes: https://github.com/dotnet/android/issues/9577
Partially reverts 82a40927.
We introduced an "experimental" property `$(AndroidStripILAfterAOT)` in .NET 8, which has a few flaws as mentioned in #9577. I've seen this come up on a couple customer issues, and the solution was to stop using the feature...
Since, this feature is only available for Mono (not CoreCLR or NativeAOT), it feels like we should remove it from the codebase for now. We could bring it back in the future, if we also solved #9577.
=> [xabt] remove `$(AndroidStripILAfterAOT)`

src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGeneratorCLR.cs, src/Xamarin.Android.Build.Tasks/Utilities/CompressedAssembliesNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/LlvmIrGenerator/LlvmIrStringBlob.cs, src/native/clr/host/assembly-store.cc, src/native/clr/host/host.cc, src/native/clr/include/runtime-base/monodroid-dl.hh, src/native/clr/include/xamarin-app.hh, src/native/clr/runtime-base/android-system.cc, src/native/clr/xamarin-app-stub/application_dso_stub.cc, src/native/mono/monodroid/embedded-assemblies.cc, src/native/mono/xamarin-app-stub/application_dso_stub.cc, src/native/mono/xamarin-app-stub/xamarin-app.hh
Another in series of PRs which reduces the number of relocations in
`libxamarin-app.so`.
This PR changes the way compressed assemblies (CoreCLR and MonoVM),
environment variables (CoreCLR) and runtime properties (CoreCLR)
are stored.
Compressed assemblies no longer use one target buffer per assembly,
but instead allocate a single big buffer for all the decompressed
assemblies, addressing the data using indexes into the buffer instead
of pointers.
Environment variables and runtime properties now use string blobs
instead of string pointers.
For the `dotnet new maui -sc` sample, this PR reduces the number of 
relocations in `libxamarin-app.so` from 394 (in the `main` branch)
to 136 entries.
Size of `libxamarin-app.so` is slightly reduced:
* arm64: from 370936 to 365800 bytes (1.4%)
* x64: …
=> [native] Generate less relocations in libxamarin-app.so

src/Microsoft.Android.Runtime.NativeAOT/Android.Runtime.NativeAOT/JavaInteropRuntime.cs, src/Microsoft.Android.Runtime.NativeAOT/Java.Interop/JreRuntime.cs, src/Mono.Android/Android.Runtime/AndroidRuntime.cs, src/Mono.Android/Android.Runtime/JNIEnv.cs, src/Mono.Android/Android.Runtime/JNIEnvInit.cs, src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs, src/Mono.Android/Android.Runtime/JNINativeWrapper.g.tt, src/Mono.Android/Java.Interop/Runtime.cs, src/Mono.Android/Java.Lang/Object.cs, src/Mono.Android/Microsoft.Android.Runtime/ManagedValueManager.cs, src/Mono.Android/Microsoft.Android.Runtime/SimpleValueManager.cs, src/Mono.Android/Mono.Android.csproj
This PR contains bits from #10198 which don't depend on new APIs in dotnet/runtime changes.
/cc @jonathanpeppers
=> [GC Bridge] Split ManagedValueManager and SimpleValueManager

.gdn/tsaoptions-v2.json, build-tools/automation/azure-pipelines.yaml
by changing the area path in AzDO, I accidentally broke the integration with TSA. This PR fixes the area path to point to the correct location.
=> Update TSA Area Path to DevDiv\.NET MAUI\Android

src/Xamarin.Android.Build.Tasks/Tasks/BuildArchive.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2510554
In testing .NET 10, we found the issue:
ADB0010: Mono.AndroidTools.InstallFailedException: Unexpected install
output: Failure [-124: Failed parse during installPackageLI: Targeting
R+ (version 30 and above) requires the resources.arsc of installed
APKs to be stored uncompressed and aligned on a 4-byte boundary] ...
1. Create a new .NET MAUI/MAUI Blazor app.
2. Change the value for the Color attribute to #FF0000 or any color.
```xml
<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#FF0000" BaseSize="128,128" />
```
3. Deploy to android.
4. The splash screen color should change according to the chosen color.
5. Stop Debugging and change the splash screen color again.
6. If you do it enough times, you would …
=> [xabt] fall back to libZipSharp on .NET framework

.external, Configuration.props, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.Linux.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.MacOS.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.Windows.cs, build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/AndroidToolchain.cs
Updates:
* `build-tools`: 35.0.0 -> 36.0.0
* `platform-tools`: 34.0.5 -> 36.0.0
* `cmdline-tools`: 12.0 -> 19.0
Specifically wanting a newer `platform-tools` to hopefully fix test failures in:
InstallAndroidDependenciesTest("GoogleV2")
_AndroidSdkDirectory was not set to new SDK path C:\a\_work\1\a\TestRelease\06-24_17.18.26\temp\InstallAndroidDependenciesTestGoogleV2\android-sdk. Please check the task output in 'install-deps.log'
Expected: True
It appears that `-t:InstallAndroidDependencies -p:AndroidManifestType=GoogleV2` is not installing `platform-tools` as the `34.0.5` version is not found in Google's manifest.
=> [build] update Android SDK components

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
Control over this is moving from dotnet/runtime repo build time to publish time so we need to set a default that matches the old build-time setting.
Ref https://github.com/dotnet/runtime/pull/117012
Ref https://github.com/dotnet/sdk/pull/49564
=> Set a default for the Http3Support feature switch

src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.CoreCLR.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NativeAOT.targets, src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs
Context: https://github.com/dotnet/android/pull/10007
Just like we enable `$(RunAOTCompilation)` and `$(AndroidEnableProfiledAot)` in `Release` mode by default for Mono, we should enable R2R composite for CoreCLR.
"One weird trick" we're doing is to set `$(_IsPublishing)` by default, so the correct packs can be restored & ran during a `dotnet build`. We were already doing this for NativeAOT, so hoping the same trick will work for CoreCLR.
I also updated the `BasicApplicationPublishReadyToRun()` test to verify these defaults are working as expected.
=> [xabt] enable R2R Composite by default for CoreCLR in Release

src/Mono.Android/Java.Interop/TypeManager.cs, src/Xamarin.Android.Build.Tasks/Tasks/CreateAssemblyStore.cs, src/Xamarin.Android.Build.Tasks/Utilities/AssemblyStoreAssemblyInfo.cs, src/Xamarin.Android.Build.Tasks/Utilities/AssemblyStoreBuilder.cs, src/Xamarin.Android.Build.Tasks/Utilities/AssemblyStoreGenerator.Classes.cs, src/Xamarin.Android.Build.Tasks/Utilities/AssemblyStoreGenerator.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets, src/native/clr/host/assembly-store.cc, src/native/clr/include/constants.hh, src/native/clr/include/host/assembly-store.hh, src/native/clr/include/xamarin-app.hh, src/native/mono/monodroid/embedded-assemblies.cc, src/native/mono/xamarin-app-stub/xamarin-app.hh, tools/assembly-store-reader-mk2/AssemblyStore/AssemblyStoreItem.cs, tools/assembly-store-reader-mk2/AssemblyStore/StoreReader_V2.Classes.cs, tools/assembly-store-reader-mk2/AssemblyStore/StoreReader_V2.cs, tools/assembly-store-reader-mk2/StorePrettyPrinter.cs
Ignore assemblies whose names end in `.ni` and `.ni.dll`, when 
a load request is made via the CoreCLR host contract callback.
For each CoreCLR will ask to first load `Assembly.ni.dll`, NI
standing for Native Image. This is something that was used on
Windows long ago and it never was, nor will it be, supported on
Unix.
This is mostly a cosmetic change in that it prevents a false
warning about a missing assembly from being logged in logcat.
This, in itself, is a startup time improvement since those
warnings would always be logged during every application launch,
with logcat logging being very expensive (and unpredictable).
The message about a missing `.ni.dll` is still logged, but with
the Debug severity, which will cause it to show up only if the
`assembly` logging category is enabled (it …
=> [CoreCLR] Ignore some assemblies when asked to load them

NuGet.config
I also moved the `dotnet-tools` feed down, as we've seen it timeout occasionally:
Determining projects to restore...
Retrying 'FindPackagesByIdAsync' for source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/4828dfac-e9f8-49bc-acb6-319be99331fc/nuget/v3/flat2/xamarin.androidx.lifecycle.livedata.core.ktx/index.json'.
The HTTP request to 'GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/4828dfac-e9f8-49bc-acb6-319be99331fc/nuget/v3/flat2/xamarin.androidx.lifecycle.livedata.core.ktx/index.json' has timed out after 100000ms.
=> [nuget.config] see if we can remove `dotnet9` feeds

src/native/mono/shared/helpers.cc
Context: https://github.com/dotnet/runtime/issues/117733
When a .NET for Android app aborts, the abort message should contain the file name, line number, column, and function name of the function which triggered the abort.
Insteda, we get the filename, line number, and column, but we get `%s` for the function name:
F monodroid: Abort at mono-log-adapter.cc:46:3 ('%s')
Update the `log_fatal()` invocation within `mono-log-adapter.cc` to use `{}` instead of `%s`, in accordance with C++ `std::format`. This should cause `sloc.function_name()` to be properly part of the abort message.
=> [native] Ensure function_name() is part of log message

Directory.Build.props
Context: https://github.com/dotnet/android/tree/release/10.0.1xx-preview7
We branched for .NET 10 Preview 7 from 510fc086 into `release/10.0.1xx-preview7`; the main branch is now .NET 10 RC 1.
=> `$(AndroidPackVersionSuffix)=rc.1`

build-tools/create-packs/Directory.Build.targets, external/xamarin-android-tools.override.props
In order to consume `Xamarin.Android.Tools.AndroidSdk` more easily by other projects, let's build and redistribute it as a "transport pack".
=> [build] pack `Xamarin.Android.Tools.AndroidSdk`

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildWithLibraryTests.cs, src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
Context: https://github.com/dotnet/sdk/blob/1ed2f8e9751753a1d249d129884a669363c1b832/src/StaticWebAssetsSdk/Sdk/Sdk.StaticWebAssets.StaticAssets.ProjectSystem.props#L30-L31
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2533207
1. Create a `dotnet new maui-blazor-web` project.
2. Open the `*.Shared.csproj`, the Razor class library project.
3. Change the `$(TargetFramework)` from `net9.0` to `net9.0-android`.
4. Build the project.
Get the warnings:
hellomauiblazor.Shared net9.0-android succeeded with 11 warning(s) (0.4s) → hellomauiblazor.Shared\bin\Debug\net9.0-android\hellomauiblazor.Shared.dll
wwwroot\app.css : warning XA0101: @(Content) build action is not supported
wwwroot\bootstrap\bootstrap.min.css : warning XA0101: @(Content) build action is not supported …
=> [xabt] suppress `XA0101` for Razor class libraries

Documentation/workflow/UnitTests.md, tests/Mono.Android-Tests/Java.Interop-Tests/Java.Interop-Tests.NET.csproj, tests/Mono.Android-Tests/Mono.Android-Tests/Mono.Android.NET-Tests.csproj
Context: https://github.com/dotnet/android/pull/10198
We added CoreCLR "GC Bridge" support in 1f8f7195, but there are still some tests we can enable. Hopefully they pass! 🤞
I also did some cleanup of a `DotNetIgnore` category that is no longer used since Xamarin.Android was removed from this repo.
=> [tests] enable `GCBridge` category for CoreCLR

.vscode/extensions.json
For C# development, you should use:
* https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit
* https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-maui
So we should remove older extensions like:
* `ms-vscode.mono-debug`
* `visualstudioexptteam.vscodeintellicode`
* `wghats.vscode-nxunit-test-adapter`
* `derivitec-ltd.vscode-dotnet-adapter`
These are also sorted alphabetical now.
=> [vscode] update recommended VS Code extensions

build-tools/trim-analyzers/trim-analyzers.props
Context: https://github.com/dotnet/runtime/pull/118180
The new warnings are opt-in under the following settings:
* `<VerifyReferenceTrimCompatibility>true</VerifyReferenceTrimCompatibility>`
* `<VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>`
=> [build] enable transitive trimmer warnings

src/manifestmerger/build.gradle
Context: https://maven.google.com/web/index.html?q=com.android.tools.build#com.android.tools.build:manifest-merger:31.12.0
Context: https://android.googlesource.com/platform/tools/base/+/master/build-system/manifest-merger
Bumps com.android.tools.build:manifest-merger from 31.11.1 to 31.12.0.
Note that I was unable to locate a specific git tag for this release.
=> Bumps com.android.tools.build:manifest-merger from 31.11.1 to 31.12.0

Directory.Build.props
Context: https://github.com/dotnet/maui/issues/30948
I don't think this will solve dotnet/maui#30948, but it will at least reduce confusion if we put a 15.x version number on our .NET 9 MSBuild task assemblies.
=> [release/9.0.1xx] [build] update `$(ProductVersion)` to align with Android 15

build-tools/xaprepare/xaprepare/ConfigAndData/BuildAndroidPlatforms.cs
Changes: https://github.com/android/ndk/wiki/Changelog-r28#r28c
Nothing stands out in the upstream changes as affecting us.
=> [build] Bump NDK to r28c

tests/MSBuildDeviceIntegration/Tests/InstallTests.cs
7b62f35c updated various MSBuild tests to pass `defaultIfNotUsed: true`, when asserting if an MSBuild target is skipped.
It looks like we missed one place this is needed.
=> [tests] fix `AppWithAndroidJavaSource` test

src/native/clr/runtime-base/android-system.cc
Fixes: #10382
Context: f37158eae0111a6cdd25e870e412fcc74997d529
f37158eae switched to string blobs when storing environment variables
in `libxamarin-app.so`.
In case of an odd count of envvars, we'd fail to set them because
of a check that should have been removed in f37158eae
Remove verification that there's an even number of elements in the
environment variable array, it is no longer necessary.
=> [clr] fix environment variable setting

Documentation/docs-mobile/building-apps/build-properties.md, src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets
Context: https://github.com/jonathanpeppers/MauiAspireWithTelemetry/tree/peppers
Context: https://github.com/dotnet/maui/pull/31058
We are in the process of adding `Metrics` to .NET MAUI to enable `dotnet-counters` such as:
> dotnet-counters monitor --dsrouter android --counters Microsoft.Maui
Press p to pause, r to resume, q to quit.
Status: Running
Name                                      Current Value
[Microsoft.Maui]
maui.layout.arrange_count ({times})               6
maui.layout.arrange_duration (ns)
Percentile
50                                      518,656
95                                    2,367,488
99                                    2,367,488
maui.layout.measure_count ({times})              11
maui.layout.measure_duration (ns)
Percentile
50 …
=> [xabt] fix default trimmer switches for `Metrics`

build-tools/xaprepare/xaprepare/ConfigAndData/Dependencies/Linux.Debian.cs
Debian 13 (trixy) has just been released and, as of now, 
the "unstable" Debian distribution (always code-named `sid`) 
has no numeric version and `xaprepare` fails to detect it.
Fix this by adding information about `forky`, the next release
code name, and pretending it's version 14 (which it will be, eventually)
=> [xaprepare] Fix detection of the new Debian/sid version

src/Mono.Android/java/mono/android/TypeManager.java
Comparing performance of .NET 9 vs .NET 10, I noticed something very odd stand out!
.NET 9:
14.94ms System.Private.CoreLib!System.Type.GetType(string...
.NET 10:
53.57ms System.Private.CoreLib!System.Type.GetType(string...
Was `Type.GetType()` really that much slower in .NET 10?
After some testing, my tests found that this was not the case when I tested `Type.GetType()` in isolation.
So I added some logging to `JNIEnvInit` to see what was going on:
```csharp
var sw = new System.Diagnostics.Stopwatch ();
sw.Start ();
var type = TypeGetType (typeName);
sw.Stop ();
Logger.Log (LogLevel.Debug, "monodroid", FormattableString.Invariant ($"foo: Type.GetType() took {sw.ElapsedMilliseconds} ms, with type '{typeName}'."));
```
And got this result!
08-14 10:57:28.998  8435  8435 D monodroid: foo: …
=> [Mono.Android] fix `Type.GetType()` performance issue

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs, tests/MSBuildDeviceIntegration/Tests/PerformanceTest.cs
Context: https://github.com/dotnet/android/pull/10438
We can always call `Assert.Inconclusive()`, to prevent failing tests from contributors.
=> [tests] builds from forks skip `AssertCommercialBuild()` tests

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/MainActivity.cs, src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGenerator.cs, src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGeneratorCLR.cs, src/native/clr/host/host.cc, src/native/clr/include/host/host.hh, src/native/clr/include/xamarin-app.hh, src/native/clr/xamarin-app-stub/application_dso_stub.cc, src/native/mono/monodroid/monodroid-glue-internal.hh, src/native/mono/monodroid/monodroid-glue.cc, src/native/mono/runtime-base/monodroid-dl.hh, src/native/mono/xamarin-app-stub/application_dso_stub.cc, src/native/mono/xamarin-app-stub/xamarin-app.hh, tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs
Context: cba39dcf72
Context: #10376
Context: #10324
cba39dcf72 implemented preloading of JNI-using native libraries but it missed to update
alias entries for each preloaded library.
During application build we generate native code that contains cache for each native
library packaged with the managed application code. Each library follows the same
naming pattern: `lib<NAME>.so`. However, the managed code can refer to those libraries
(when e.g. declaring a p/invoke with the `[DllImporrt]` attribute) using different forms
of names. The request may have a form of `lib<NAME>` or `<NAME>` etc. 
When the runtime tries to resolve the p/invoke symbol, it first needs to load the shared
library. This is done (in our case) by using a callback into our runtime which then tries
to find the library and …
=> [native] When preloading shared JNI libraries, update alias entries too

src/Xamarin.Android.Build.Tasks/Utilities/ApplicationConfigNativeAssemblyGeneratorCLR.cs, src/native/clr/host/host.cc, src/native/clr/include/runtime-base/monodroid-dl.hh, src/native/clr/include/startup/zip.hh, src/native/common/include/runtime-base/strings.hh, src/native/mono/monodroid/embedded-assemblies-zip.cc
Fixes: #10383
This is an optimization for when shared libraries aren't extracted from the APK.
In this case, we can load them faster by using extended dlopen API provided by
Android, which allows us to skip path scanning by `dlopen`.
This is done by recording file offset of any .so library inside the APK at
application startup and then using it, together with the APK file descriptor
that we keep around, to load the library using Android extended version of
`dlopen`.
This does not apply to any libraries using JNI, as they have to be loaded
using the Java `System.loadLibrary` API (see cba39dcf72 and 1a62af3814)
=> [native] Fix loading of shared libraries directly from the APK

src/Microsoft.Android.Runtime.NativeAOT/Android.Runtime.NativeAOT/JavaInteropRuntime.cs, src/Mono.Android/Android.Runtime/JNIEnvInit.cs
The threshold value is used by the global reference creation routine to determine whether to [start GC collection][0]:
```csharp
if (gc >= JNIEnvInit.gref_gc_threshold) {
Logger.Log (LogLevel.Debug, "monodroid-gc", gc + " outstanding GREFs. Performing a full GC!");
System.GC.Collect ();
}
```
However, the threshold value was being initialized after we've already invoked some non-trivial managed code in the managed [NativeAOT runtime][1], too late to avoid at least a handful of `System.GC.Collect ()` calls:
09-15 14:37:25.923 10761 10761 D monodroid-gc: 1 outstanding GREFs. Performing a full GC!
09-15 14:37:25.923 10761 10761 D monodroid-gc: 2 outstanding GREFs. Performing a full GC!
09-15 14:37:25.923 10761 10761 D monodroid-gc: 3 outstanding GREFs. Performing a full GC!
09-15 …
=> [NativeAOT] Initialize GC threshold much earlier

src/native/clr/host/internal-pinvokes-clr.cc, src/native/clr/host/internal-pinvokes-shared.cc, src/native/nativeaot/host/internal-pinvoke-stubs.cc
Context: https://github.com/dotnet/android/pull/10496#issuecomment-3307541946
Context: 869b0e03937e0c17a4cf3fbc85f50d80350b2576
The `_monodroid_weak_gref_delete` p/invoke wasn't implemented 
in 869b0e0393 as it was thought to be unused. However, the test
failure in #10496 shows that it's not true.
Bring the `_monodroid_weak_gref_delete` implementation to NativeAOT
host from the CoreCLR host.
=> [nativeaot] Implement _monodroid_weak_gref_delete

Directory.Build.props
Context: https://github.com/dotnet/android/tree/release/10.0.1xx
We branched for .NET 10 from 78f5f8cd4 into `release/10.0.1xx`; the main branch is now .NET 11.
=> $(AndroidPackVersionSuffix)=preview.1; main is 36.1.99
