dotnet/android

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

The Builder was not checking for the xabuild script in the
`out` directory for the monodroid tree.

[Xamarin.ProjectTools] Fix path to xabuild for monodroid.

---

Makefile

When working with the `Makefile` I noticed this command doesn’t run the
tests:
```
$ make run-nunit-tests
make: Nothing to be done for `run-nunit-tests’.
```
And this command runs the tests:
```
$ make run-nunit-tests SKIP_NUNIT_TESTS=1
```
I suspect the intention is that `ifneq` needs to be `ifeq`.
I believe this was introduced in https://github.com/xamarin/xamarin-android/commit/385699a58635d87a1cc65b60995d3420995f21d7.

[build] SKIP_NUNIT_TESTS check is reversed

---

src/Mono.Android/Test/apk-sizes-definitions.txt

The https://github.com/xamarin/xamarin-android/commit/2dc5689a5d823fc91b04791d5354254e5ed2d31d fixed the files location, but new size measurements definition
didn't include the AOT'ed assemblies sizes.

[performance measurements] Added AOT'ed assemblies sizes again

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60080
Context: 1cd582ec
It appears that the `<GetAdditionalResourcesFromAssemblies/>` task is
causing Visual Studio 2015 to hang when loading projects.
In the interests of expediency, "revert" to d15-3 behavior and make
the `<GetAdditionalResourcesFromAssemblies/>` task invocation
conditional on `$(DesignTimeBuild)` being False, i.e. only execute
`<GetAdditionalResourcesFromAssemblies/>` when performing *normal*
builds, *not* Design-Time builds.

[Xamarin.Android.Build.Tasks] Don't get resources in DTB

---

tools/scripts/xabuild

Otherwise we'd continue in the script and all sorts of weirdness would occur since TARGETS_DIR is empty.

xabuild: exit if TARGETS_DIR can't be found

---

src/Xamarin.Android.Build.Tasks/Tasks/Lint.cs

We need to output the Lint tool Path we use and the Lint Tool
version for diagnostic purposes. So if it does fail we have
the information we need to correct the issue.

[Xamarin.Android.Build.Tasks] Add Debug info for Lint Task

---

Configuration.props
README.md
build-tools/dependencies/dependencies.projitems

There are circumstances when we don't want to use the latest
and greatest version of mono. On the CI servers we will want
to keep to certain versions so that we have a stable build.
But on developer machines we will want to allow the developer
to ignore such checks.
This commit adds support for a Max mono version. By default
this proeprty is ignored. But on build systems we should pass
/p:IgnoreMaxMonoVersion=False
to ensure that the max version is applied and we run against
a stable version of mono.

[Makefile] Add support for a Max Mono Version.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs

There was a spelling mistake in the DesignTime build timing test.
Also it was reporting the wrong time! So this commit fixes that.
It also makes the test `NonParallelizable`, this is because when
its run in parallel with a bunch of other tests the timing is usually
off and the test fails.

[Xamarin.Android.Build.Tests] Fix up message for the DesignTime timing test.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

Sometimes out TimeOut tests fail if the build is a bit slow.
This is because we time the entire process of starting a new
process to bringing in ALL the output data.
So lets parse the build.log and pull our the reported MSBuild
"Time Elapsed" if we can.

[Xamarin.ProjectTools] Get the actual Time Elapsed from the build.log

---

tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Properties/AndroidManifest.xml
tests/locales/Xamarin.Android.Locale-Tests/Properties/AndroidManifest.xml

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60185
Newer versions of NDK don't include API 4 anymore but two of our tests specified
that they required that particular version to build. This caused the tests to
fail because the android-4 platform path was nowhere to be found.
Bump the minimum SDK version to 9 (which is the lowest platform included in the NDK
as of now)

[tests] Don't use obsolete NDK API levels

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs

The test failed locally for me with:
```
/Users/alexander/dev/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: 
error : '/Users/alexander/Library/Developer/Xamarin/android-sdk-macosx/build-tools/23.0.0/apksigner' does not exist.
You need to install android-sdk build-tools 26.0.1 or above.
```
which is weird since it's looking into the 23.0.0 build tools which doesn't have apksigner even though the test specifies build tools 26.0.1.
Turns out the test had a typo, it used AndroidBuildToolsVersion instead of AndroidSdkBuildToolsVersion so it fell back to 23.0.0 :)

[Xamarin.Android.Build.Tasks] Correctly set build tools version in CheckSignApk test

---

Makefile

Context: 286b9c28
Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/700/testReport/
`Xamarin.ProjectTools` was updated in commit 286b9c28 to use `msbuild`
(via `xabuild`) when `$USE_MSBUILD` is *not* `0`, and to continue
using `xbuild` (the historical default!) when `$USE_MSBUILD` is `0`.
Unfortunately, *nothing exports `$USE_MSBUILD`*. Consequently, we
*always* use `msbuild`/`xabuild`, unless the calling environment
explicitly exports it (which isn't the case on Jenkins).
Update the `RUN_NUNIT_TEST` make `define` so that the `$USE_MSBUILD`
environment variable is exported to the *value of* the
`$(USE_MSBUILD)` make variable, IFF it's not the empty string.
If `$(USE_MSBUILD)` *is* the empty string, export `USE_MSBUILD=0`,
which will cause `xbuild` to be …

[tests] Export `$USE_MSBUILD=$(USE_MSBUILD)`

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Xamarin.Android.Windows.targets

Commit 286b9c28 added extra items to the IncrementalClean ItemGroups.
But one of them omited the `$`. This commit fixes that issue.

[Xamarin.Android.Build.Tasks] Fix Type in the Xamarin.Android.Windows.targets

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
tools/xabuild/XABuild.cs
tools/xabuild/XABuildPaths.cs

Context in #954 #964 #967
The Xamarin.Android.Build.Tests run xabuild.exe in parallel, which
brings up some interesting issues. xabuild.exe needs to overwrite a
config file that is used by the `MSBuildApp` class. Several PRs
were made to try to address this issue.
This solution uses the `MSBUILD_EXE_PATH` environment variable, that
gets MSBuild to load a temporary file for the config file. This allows
multiple xabuild.exe's to run in parallel without issue.
Past attempts:
- In #954, `EventWaitHandle` was used, which does not work when running
under Mono.
- In #964, `FileStream` was used as an interprocess lock and `MSBuildApp`'s
static ctor was forced to run during the lock. It wasn't ideal.
- In #967, the config file was created before the tests run, and uses a
`File.Exists` check. This …

[xabuild] use a temp file for xabuild's config

---

tools/xabuild/XABuild.cs

There are cases in which diagnostic MSBuild output is not including
important information such as `$(MSBuildExtensionsPath)`.
To help debug situations like this, if `MSBuildApp.Main` returns a
non-zero exit code, we can print the contents of xabuild.exe's config
file to the console.

[xabuild] print config file to console on error

---

Makefile

The Xamarin.Android.Build.Tests msbuild tests recently started hanging after the tests were done.
Run tests with a single worker as a workaround until we figure out why to unblock Jenkins.

[tests] Use single NUnit worker to prevent hanging msbuild tests

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
tools/xabuild/XABuild.cs
tools/xabuild/XABuildPaths.cs

Context in #910
When switching to `xabuild.exe`, two mistakes were made:
- `xabuild.exe` shouldn’t set `AndroidSdkDirectory` or
`AndroidNdkDirectory`
- Xamarin.Android.Build.Tests should pass these values to xabuild
This restores some of the code in `Builder.cs` removed in f9d15dd

[tests] fix failures related to AndroidSdkDirectory property

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs

Commit 8643ded9 added support for running the tests in msbuild.
Part of that change was altering the behaviour of `xbuild to
match that of msbuild. This was regarding the way they hande
the `$(DebugType) == "None"`.
The commit altered the .targets file to reset `$(DebugType)` to
`portable` if `None` is detected. It also resets `$(DebugSymbols)`
to `false` in the same senario.
As a result the the in these two tests which do the same thing
should not longer be required.

[Xamarin.Android.Build.Tests] Clean up DebugType = "None" test changes.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

Commit 029c86fb kinda caused a perforanace problem because it
was regex'ing the entire build log. Some of those logs can
grow to 300+ meg in size.
This commit reworks the build log processing to
1) Use a StringBuilder rather than concat strings.
2) Search for the build time from the end of the file first.
Hopefully this will improve things.

[Xamarin.Android.Build.Tests] Fix the processing of the build.log files.

---

Makefile
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/packages.config

Context: https://github.com/nunit/nunit/releases/tag/3.7.1
The release notes for NUnit 3.7.1 mention a hang with parallelized
tests, so it is worth a try to see if updating fixes it.
Reverting 6687dac as well to see if we get a green build.

[tests] update NUnit to 3.7.1

---

build-tools/android-toolchain/android-toolchain.projitems

The `dl.` CDN has more backends than `dl-ssl.` and is generally faster.
Also, change ant download to use HTTPS (in preparation for the world where plain
http is gone :P)

Change Android repository base URL to https://dl.google.com

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

On jenkins is appears we are getting a situation where we
are picking up an empty directory for the FrameworkPath.
As a result we always get 0 when trying to pick up the
runtime that are available. So tests which check the runtimes
fail.
This commit adds a check for a 'libmono-android.release.so' file
so can ensure the required files exist in the folder. Also added
code to pick up the `CONFIGURATION` environment variable from
the Makefile.

[Xamarin.Android.Build.Tests] Fix Framework Path Detection.

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.CSharp.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.FSharp.targets

Commit 8643ded9 tried to make sure xbuild worked like msbuild
when it came to `'$(DebugType)' == 'None'`. The "fix" however
was not correct.
When DebugType is None under msbuild, it changes to `portable`
and DebugSymbols get set to 'true'. Also when DebugType is empty
it gets set to `portable` but the DebugSymbols is left alone.
So we need to get xbuild to do the same. Otherwise we get the
wrong runtimes. But by the time we get the the .Common.targets
it is too late to change the `DebugSymbols` value. xbuild does
not take the change. So we need to do this before xbuild gets
a chance to set the value of `DebugSymbols`.
The trick is to alter the properties in the CSharp and Fsharp
targets BEFORE we import the Microsoft targets.

[Xamarin.Android.Build.Tasks] Force xbuild to behave like msbuild.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=60080
In a previus attempt to fix an intellisense build (1cd582ec) we
caused this issue. The DesignTime build does NOT like our AsyncTask
as it locks the IDE.
This commit puts the old code back in place which skips the task
if we are in DesignTime mode. But so we can easily test it, we
emit an message that our test can pick up to ensure we are doing
the correct thing. Without the message we have no way of knowing
if the task is skipped.

[Xamarin.Android.Build.Tasks] Fix a Hang in Visual Studio DesignTime Build.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

The DesignTime build is generally run before any nuget packages
have been restore. As a result we end up with empty cache files.
Because those files exist and are considered uptodate, when the
main build finally happens they are not re-generated.
This causes errors like
error: Error: No resource found that matches the given name: attr 'colorAccent'.
on a new default template.
So the DesignTime build should have its own set of cache files which
do not conflict with the main build. This way when the main build
runs the cache files will not be in place.

[Xamarin.Android.Build.Tasks] Move DesignTime Cache files to designtime folder.

---

Makefile
build-tools/scripts/PrepareImageDependencies.targets
build-tools/scripts/prepare-image-dependencies.sh.in

We are investigating building Xamarin.Android atop
Visual Studio Team System (VSTS) in addition to our current Jenkins
setup, and one of the issues we're running into is "bootstrapping":
VSTS is configured to create a "fresh" VM for each build.
**Pro**: It should allow builds to be more reliable, as previous build
artifacts won't be present, and thus won't cause/hide errors.
**Con**: *Previous build artifacts are not present*. Previous build
artifacts such as *downloading and extracting* the Android NDK & SDK,
using `brew` to install dependencies, building MXE...
Ensuring that the dependencies are installed through `make prepare`
can be quite time consuming. What we want is a way to ensure that the
"build image" -- *what's already installed* when the VM boots --
contains all of our …

[build] Add `make prepare-image-dependencies` target.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

The BuildAppCheckDebugSymbols test does not take into account
that when building in debug mode on monodroid the assemblies
are not embedded in the apk. As a result when trying to get
`Library1.pdb` from the apk we get a null back. This causes
a Null Ref exception when we try to get a length.
The fix is to look in the `assets` directory if we can't get
the file from the zip. This will allow the test to work in
both xamarin-android and monodroid.

[Xamarin.Android.Build.Tests] Fix BuildAppCheckDebugSymbols for monodroid

---

tools/xabuild/XABuild.cs
tools/xabuild/XABuildPaths.cs

Context:
https://github.com/xamarin/xamarin-android/blob/master/tools/scripts/xabuild#L105
`xabuild`, the shell script, has some logic to set MSBuild properties
for `AndroidSdkDirectory` and `AndroidNdkDirectory`. The issue here is
on Windows, `xabuild.exe` is not invoked from this shell script. So we
need to replicate the logic in C# in `xabuild.exe`, but not break what
was fixed in #977.
Changes:
- check for `ANDROID_SDK_PATH` or `ANDROID_NDK_PATH` environment
variables
- Run `Paths.targets` via a new MSBuild process, the same way as
`xabuild`, the script
- Set the `AndroidSdkDirectory` and `AndroidNdkDirectory` values in the
config file if they are not blank
- `AndroidSdkDirectory` and `AndroidNdkDirectory` can still be
overridden by a user, because incoming values supersede what is …

[xabuild.exe] handle AndroidSdkDirectory like the script

---

build-tools/scripts/PrepareWindows.targets

On Windows after formatting my machine (don't ask), `PrepareWindows.targets` was failing with:
System.InvalidOperationException: Could not determine Android SDK location.
Looking into it, there appear to be two things wrong:
- `PrepareWindows.targets` should import `Configuration.props`
- The incoming variables are `AndroidSdkDirectory` and `AndroidNdkDirectory` not `AndroidSdkPath` and `AndroidNdkPath`
I'm not quite sure how this _ever_ worked, unless `AndroidSdkInfo` was able to find _some_ Android SDK on your machine.

[build] fix for JdkInfo task in PrepareWindows.targets

---

src/Xamarin.Android.Build.Tasks/Tasks/Dx.cs

Otherwise debugging won't work with d8/r8.

[msbuild] remove --dex argument and add DxExtraArguments from Dx task.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/FailedBuildException.cs

If the build fails we get a generic message to look at the build.log.
This is a pain because the build log is HUGE! and takes ages to find the
problem.
It seems NUnit does not include the BuildLog property from the
`FailedBuildException`. So lets override the ToString method to
include the data.

[Xamarin.Android.Build.Tests] Add Build Log to the Exception data.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

We get a few probems when building with mono/xbuild. We get
the occasional crash :(
at <unknown> <0xffffffff>
at (wrapper managed-to-native) object.__icall_wrapper_mono_gc_alloc_obj (intptr,intptr) [0x00000] in <4fdc5ed61a074cafb49fa42deb20d521>:0
at (wrapper alloc) object.AllocSmall (intptr,intptr) <0x000fa>
So what we might want to do is to retry the build if we get this.
It usually doesn't happen twice in a row.

[Xamarin.Android.Build.Tests] Lets retry a build if we get a native crash

---

.gitmodules
Configuration.props

Instead of having own submodule. This way we unify with xamarin-macios
as it also uses mono's linker submodule.

[linker] Use mono's linker submodule

---

src/Xamarin.Android.Build.Tasks/Tasks/GetJavaPlatformJar.cs
src/Xamarin.Android.Build.Tasks/Tasks/JarToXml.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs

Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=60324
If a android.jar file does NOT exist for a target platform we should
raise a normal error. But we currently throw a null reference
exception.
`TryGetPlatformDirectoryFromApiLevel` can return null, this is by
design. So we need to handle that in the places where its used.
And return a reasonable error message if we do get a null back.

[Xamarin.Android.Build.Tasks] Null Reference Exceoption when getting android.jar

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs

Rather than trying to ALWAYS unset the ReadOnly flag, lets only
do it if the directory is read only. Also use EnumerateFiles
rather than GetFiles to get the .jar files. EnumerateFiles is
more efficient.

[Xamarin.Android.Build.Tasks] Speed up ResolveLibraryProjectImports

---

src/Xamarin.Android.Build.Tasks/Tasks/Lint.cs

Turns out lint.bat does not always return a version number. It
returns stuff like
lint: version unknown
lint: unknown version
not very helpful. So we need to handle that case and return a
empty verison.

[Xamarin.Android.Build.Tasks] Handle lint.bat not returning version info.

---

src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60473
In the case when the URL doesn't contain any query elements we
optimized for speed and memory by not using UrlBuilder to do the
encoding work on the URL. However, it causes problems with URLs
that are sent pre-encoded.
Remove the optimization and rely on UrlBuilder in all cases.

Don't optimize URL encoding

---

tests/Xamarin.Forms-Performance-Integration/Droid/Xamarin.Forms.Performance.Integration.Droid.csproj

Other Android projects (such as test APKs), set `TargetFrameworkVersion`
by importing `Configuration.props` and using `$(AndroidFrameworkVersion)`.
`AndroidUseLatestPlatformSdk` should also be set to `false`.
Not sure why this hasn't caused any issues yet, I first noticed this
causing a failure on PR #997.

[tests] fixed Forms project TargetFrameworkVersion

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

Commit 855ad009 added logic to detect if a test had a native crash and to
retry the test. There was a flaw in the logic such that it would
run every test twice...
This fixes that.

[Xamarin.Android.ProjectTools] Fix logic error in native crash detection.

---

src/Xamarin.Android.Build.Tasks/Tasks/AndroidApkSigner.cs

Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=60444
We should NOT ever pass a minSdk value that is greater than
the maxSdk. It results in the following error
Min API Level (10) > max API Level (8)
So we should check the values and use the minimum value
for the minSdk.

[Xamarin.Android.Build.Tasks] ApkSigner Failed if minsdk > maxSdk

---

build-tools/scripts/TimingDefinitions.txt

Added NUnit.results label to the default time performance definition
file. It matches NUnit line with results, which is printed out at the
end of the NUnit driven test.

[tests] Measure end time of NUnit tests

---

src/Xamarin.Android.Build.Tasks/Tasks/ClassParse.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets

Adds support to binding projects to make use of ApiXmlDocPaths as a project property for including api.xml style java docs to be used by ClassParse for resolving parameter names.
This format is used by Android Support libraries (and eventually Google Play Services / Firebase).
This requires xamarin/java.interop@61c70ece24e5e59118fe4b093c60ef2898eb2748
This PR supercedes and closes #916.

Generator support for api.xml style java docs for parameter names

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs

This method was not using the full path to the project directory, and so
it wasn't actually deleting anything. This caused test failures on
Windows in tests such as `ManifestTest.Bug12935`. This particular test
was modifying the contents of `AndroidManifest.xml`, and checking the
results of the build afterward. Since the project files were not
deleted, changes to the `AndroidManifest.xml` were not getting written
to disk during the test.

[tests] Fix issue in ProjectBuilder.Cleanup

---

tests/Xamarin.Android.Bcl-Tests/Resources/LinkerDescription.xml

I added tests for the *Attributes which were linked away in https://github.com/mono/mono/commit/5a5ab38c9e39c64b23b2071c195400b743a38455 so we should be able to remove the linker exclusions now.

Bump to mono/2017-10/56195c0c and remove linker exclusions in corlib tests

---

tests/Xamarin.Android.Bcl-Tests/App.cs

The tests were fixed in Mono by:
- https://github.com/mono/mono/pull/5720
- https://github.com/mono/mono/pull/5942

Bump to mono/2017-10/dcbdec80; reenable tests

---

build-tools/mono-runtimes/mono-runtimes.props

it's going to be default in mono once
https://github.com/mono/mono/pull/5925 is merged

[runtime] disable interpreter

---

tools/xabuild/XABuild.cs
tools/xabuild/XABuildPaths.cs

Context: https://github.com/Microsoft/msbuild/blob/master/src/Shared/BuildEnvironmentHelper.cs#L511
`xabuild.exe` did not support building .NET standard projects. It turns
out a `MSBuildSDKPaths` environment variable needed to be set for locating
the `Sdks` directory. On Windows, this path is relative to Visual Studio /
MSBuild, but on Mac I had to hardcode the path to .NET Core. It seems to
use the same path on Linux as well.

[xabuild.exe] fix for .NET standard projects

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Context in #992
The lint.bat tool installed to ~\android-toolchain\sdk\tools\bin
appears to be broken on Windows, so a few tests are failing that use it.
There is a workaround to set the `JAVA_OPTS` environment variable
that gets these tests passing on Windows. Hopefully, this is a temporary
workaround until a new version of the SDK tools comes out that fixes
this issue.
One other thing to note here is that the Android SDK installed by Visual
Studio uses the SDK tools version 25.x, which does not appear to have
this issue on windows.

[tests] workaround broken lint.bat on Windows

---

src/Xamarin.Android.Build.Tasks/Tasks/Lint.cs

If a user provides lint checks which are not supported by
the current lint version it will error.
Invalid id or ategory "StatckFieldLeak"
This is normally ok. But in our build system we sometimes end up
on a bot which has an older version of lint. And in this case
the test fails, which in reality it should ignore the id we
are trying to use.
So this commit addds some validation to the Disabled and Enabled
checks. If its not supported we will remove the check and issue
a warning.

[Xamarin.Android.Build.Tasks] Remove Unsupported Lint Checks

---

Configuration.props

To be able to run tests against your system's setup of the Android SDK,
we need `$(AndroidSdkDirectory)` and `$(AndroidNdkDirectory)` to be able to
be overidden.

[build] AndroidSdkDirectory and AndroidNdkDirectory can be overridden

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.Darwin.projitems
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.Linux.projitems
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.Windows.projitems
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj

Context https://bugzilla.xamarin.com/show_bug.cgi?id=58994
There is a bug in VSForMac which does not like Conditionals on things
like `Content` or `ProjectReference`. This commit moves those itms
into `projitems` files which then allows us to use the `Import`
with the required Conditional. This works around the issue.

[Xamarin.Android.Project.Tools] Fix the Xamarin.ProjectTools so it compiles in VSForMac

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

We want to be able to run the msbuild tests against a system
installed xamarin-android. So we need to fallback to using
`msbuild` or `xbuild` if the required `xabuild` is NOT in place.
So if we do a full build `xabuild` will be in `bin\$(Configuration)\bin`
and the tests will run under the local environment. But if we just build
the tests `xabuild` will not exist since its copied as part of the
XABuild project build process.

[Xamarin.ProjectTools] Allow msbuild tests to run against system x-a.

---

.gitignore
Before.Xamarin.Android.sln.targets
Makefile
build-tools/scripts/PrepareWindows.targets
build-tools/scripts/RunTests.targets
build-tools/scripts/TestApks.targets
build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/SetEnvironmentVariable.cs
build-tools/xa-prep-tasks/xa-prep-tasks.csproj
src/Mono.Android/Test/Mono.Android-Tests.csproj

The end goal here is to enable Windows users to easily run the various
types of tests. Commands have been migrated to MSBuild, keeping `make`
commands the same for macOS and linux.
Windows:
```
msbuild Xamarin.Android.sln /t:RunAllTests
msbuild Xamarin.Android.sln /t:RunNUnitTests
msbuild Xamarin.Android.sln /t:RunJavaInteropTests
msbuild Xamarin.Android.sln /t:RunApkTests
```
macOS/linux should remain unchanged:
```
make run-all-tests
make run-nunit-tests
make run-ji-tests
make run-apk-tests
```
- Added a new build-tools/scripts/RunTests.targets
- Before.Xamarin.Android.sln.targets includes these test targets
- A new `SetEnvironmentVariable` task is needed, added to xa-prep-tasks
- Mono.Android-Tests.csproj needs to remove the `<ProjectReference />` android-toolchain
- Otherwise …

[tests] migrate test targets to MSBuild

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

The VS team have asked if there is a way to know which runtime
is being used by a particular build configuration.
Since we calculate the `AndroidIncludeDebugSymbols` when the project
is loaded is makes sense to store that in the `build.props` file.
It should not change very often unless the user constantly
updated the project. This way the VS team can read the `build.props`
file and look for the value.
We could have added a new target, but at the point this is needed
VS can not call MSBuild targets or read properties.

[Xamarin.Android.Build.Tasks] Cache if we are using Release or Debug

---

Configuration.props
build-tools/scripts/RunTests.targets
src/Mono.Android/Test/Mono.Android-Tests.csproj

`Mono.Android-Tests.csproj` needed to use `$(MSBuildExtensionsPath)` as
part of locating `Xamarin.Android.CSharp.targets`. The other test APK
projects were already doing this.
The other change here is to set `XAIntegratedTests` to False by default,
so that it is not required to be set when building the test APKs with
your system Xamarin.Android installation.

[tests] changes to build test APKs with system Xamarin.Android

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs
src/Xamarin.Android.Build.Tasks/Tasks/AndroidToolTask.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidRegExTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildActions.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildItem.cs

Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=60445
The regex is picking up the warning in
warning: string 'app_name1' has no default translation.
but the "warning" part is being picked up by the very first
capture group so the current code does not detect its a warning.
So in addition to checking the capture group, we should look at
the entire line and check for "warning"

[Xamarin.Android.Build.Tasks] Aapt MSBuild Task treats no default translation warnings as MSBuild errors

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs
src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs
src/Xamarin.Android.Build.Tasks/Tasks/Crunch.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetAdditionalResourcesFromAssemblies.cs

We should also provide the Cancelation Token and the
TaskScheduler for the `Parallel.ForEach` calls.
Removed a call to Log.LogErrorFromException as the continuation does/will NOT run on the UI thread.

[Xamarin.Android.Build.Tasks] Rework Parellel.ForEach

---

src/Mono.Android/Test/Mono.Android-Tests.projitems

This target is using `unzip` and `stat` Unix commands. There is not
currently a simple way to implement this cross-platform, so it is
simpler to just skip this target on Windows.
I also fixed the code formatting.

[tests] skip _RecordApkSizes on Windows

---

build-tools/scripts/RunTests.targets

On Windows, under MSBuild, I noticed a clean build was not copying the
test results from `external/Java.Interop` to the root directory. Two
things were causing this to be overlooked: the `<Copy />` task left the
original files from past test runs, and the `@(_JavaInteropTestResults)`
`ItemGroup` was calculated at the top of the file. I *think* this is
somehow working on xbuild.
To fix this, I moved the location of the `@(_JavaInteropTestResults)`
`ItemGroup` to happen during the target, instead of at the top of the
file. I also added a `<Delete />` task after the `<Copy />` to keep a clean
`external/Java.Interop` directory. It doesn't look like xbuild supports
`<Move />`.

[tests] fix Java.Interop test results copying

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Commit 70d9e2ff added a "rudimentary `Install` target". This worked in
that it would install a package, but was less than ideal because it
would *fail* on multiple installs:
$ msbuild /t:Install App.csproj
$ msbuild /t:Install App.csproj
Failed to install App-Signed.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install App without first uninstalling.]
Use `adb install -r` instead of `adb install` so that we *replace*
existing packages, should there be an existing package.
This should remove a potential headache from using the OSS bits with
Visual Studio for Mac/etc.

[Xamarin.Android.Build.Tasks] Use `adb install -r`

---

Documentation/DevelopmentTips.md
build-tools/scripts/TestApks.targets
src/Mono.Android/Test/System.Net/ProxyTest.cs
src/Mono.Android/Test/System.Net/SslTest.cs
src/Mono.Android/Test/Xamarin.Android.Net/AndroidClientHandlerTests.cs
src/Mono.Android/Test/Xamarin.Android.Net/HttpClientIntegrationTests.cs
src/Xamarin.Android.NUnitLite/Gui/Activities/TestSuiteActivity.cs
src/Xamarin.Android.NUnitLite/Gui/AndroidRunner.cs
src/Xamarin.Android.NUnitLite/Gui/Instrumentations/TestSuiteInstrumentation.cs
tests/Xamarin.Android.Bcl-Tests/TestInstrumentation.cs

In some QA needs to run tests on devices without a network connection,
so an option to disable tests that rely on the network in Mono.Android-Tests
is needed.
NUnit has the option to include or exclude tests based on the
`CategoryAttribute`. Various tests were decorated with
`[Category("InetAccess")]` that appeared to use the internet. To verify
this works, I ran the tests with my internet disabled. The test run for
Mono.Android-Tests went down from 106 to 84 tests, with no failures.
To exclude a category, on Windows:
```
msbuild Xamarin.Android.sln /t:RunApkTests /p:ExcludeCategories=InetAccess
```
On MacOS/Linux:
```
make run-apk-tests EXCLUDECATEGORIES=InetAccess
```
If you want to specify multiple categories, use `:` (colon) to delimit
each category. This delimiter is used for various …

[tests] option to include/exclude categories from Test APKs

---

build-tools/android-toolchain/android-toolchain.targets

Context: https://devdiv.visualstudio.com/DevDiv/Default/_build/index?buildId=1138882&_a=summary
Context: https://github.com/xamarin/xamarin-android/pull/606#issuecomment-304171702
We [discovered 6 months ago][0] that a mono bump was failing to build
because:
[0]: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/966
1. The Jenkins machine building the PR has Homebrew 1.2.1 installed.
2. The Jenkins machine attempting to build the PR has never built
MXE before, as MXE is only required for *full* builds in which the
mono runtime has changed.
3. The MXE build failed, because `autopoint` wasn't in `$PATH`:
Executing: make MXE_TARGETS="i686-w64-mingw32.static" gcc cmake zlib pthreads dlfcn-win32 mman-win32 PREFIX="/Users/builder/android-toolchain /mxe"
Missing requirement: …

[android-toolchain] Provide path to `autopoint`

---

build-tools/scripts/RunTests.targets

Recently the migration of running the apk tests to msbuild
(https://github.com/xamarin/xamarin-android/commit/cdf3bcc11aaf036b68daaec504f6ffa4dbbc120a)
stopped running runtime test with Aot and thus we are missing
performance measurements for Release/Aot.
The reason of it is that `_AotName` property is not set, when calling
MSBuild task to run the apk tests. This patch sets the `AotAssemblies`
property when calling `RunApkTests.targets`

[Tests] Run runtime test in Release/Aot configuration again

---

Documentation/DevelopmentTips.md
Makefile
build-tools/scripts/runtime-helpers.mk

This basically implements the steps described in
Documentation/DevelopmentTips.md for the runtime and BCL assembles. Short help
is available by running
make rebuild-help

Add a bunch of Make targets to help rebuilding Mono runtime and BCL

---

src/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/StartAndroidEmulator.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1145123&tab=details&_a=summary
We want to check for `emulator` errors early, so that we don't have a
"hung build" that sticks around until we hit a timeout; see db668ba0.
A new error condition arose while attempting to run the
`emulator`-based tests on VSTS:
[emulator stdout] emulator: ERROR: This AVD's configuration is missing a kernel file! Please ensure the file "kernel-ranchu" is in the same location as your system image.
[emulator stdout] emulator: ERROR: ANDROID_SDK_ROOT is undefined
These weren't otherwise handled, and thus the error wasn't treated as
an actual error. The result is that *nothing happened*, and the
subsequent `adb wait-for-device` hung until the build timed out.
Check for a message containing …

[tests] Check for "ERROR:" emulator message

---

Configuration.props
build-tools/scripts/TestApks.targets
src/Mono.Android/Test/Mono.Android-Tests.projitems
tests/RunApkTests.targets

One more fix after the migration of running the apk tests to msbuild
(https://github.com/xamarin/xamarin-android/commit/cdf3bcc11aaf036b68daaec504f6ffa4dbbc120a).
The reason of it is that `_AotName` property is not set, when building
the test. This patch moves the property to `Configuration.props` and
renames it to `TestsAotName`, so that it is set in the test project.
I also have to move _RecordApkSizes target to `TestApks.targets` as I
was experiencing troubles with `AfterTargets` dependency. It looks
like `xbuild` didn't run it the second time, even when the target was
called from project called by MSBuild task.
So to overcome this dependency issue, I moved the target to avoid
using `AfterTargets`. This also means that we can now easily measure
the sizes of the other tests as well (on …

[Tests] Measure test sizes in Release/Aot configuration again

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1137183
(search for APT0000 in Xamarin.Android-Tests.sln output)
Our Windows builds on VSTS are randomly failing with:
```
2017-11-14T00:49:35.1654201Z   Executing package -f -m -M
E:\A\_work\_temp\lrwwmk1i.il2\manifest\AndroidManifest.xml -J
E:\A\_work\_temp\lrwwmk1i.il2 --custom-package mono.android_tests -F
E:\A\_work\_temp\lrwwmk1i.il2\resources.apk.bk -S obj\Debug\res -S
E:\A\_work\2\s\src\Mono.Android\Test\obj\Debug\lp\1\jl\res -I
C:\Users\dlab\android-toolchain\sdk\platforms\android-26\android.jar
--auto-add-overlay --max-res-version 26 (TaskId:87)
2017-11-14T00:49:35.2324246Z
E:\A\_work\2\s\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\Xamarin.Android.Common.targets(1373,2):
error APT0000: …
```

[Xamarin.Android.Build.Tasks] Aapt task needs to ignore fakeLogOpen

---

tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.targets

This is required for "system" execution on Windows, as there is no 'xbuild-frameworks' folder installed by the XA .vsix. An example framework installation location in VS2017 is shown below:
'C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0'.

[Xamarin.Android.Bcl-Tests] Allow Xamarin.Android.NUnitLite.dll path to be overridden

---

src/Xamarin.Android.Build.Tasks/Tasks/AndroidApkSigner.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems?id=525752
Older `apksigner` versions did not have an `--in` parameter. Instead
they expected the last item to be passed to be the .apk to sign.
So to make this work on older `apksigner` versions we should rework
the Task to pass the apk last.

[Xamarin.Android.Build.Tasks] Apksigner invocation fails on build-tools 25 and lower

---

src/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/StartAndroidEmulator.cs

It appears the installation of Android Studio has exported `ANDROID_HOME`
on my system. This is problematic for our build, since it installs a
specific version of the Android SDK into ~/android-toolchain/sdk.
The fix is to set `ANDROID_HOME` for the `emulator` command using the
existing value for `AndroidSdkHome` from our build. This allows the emulator
to locate the proper system image in ~/android-toolchain/sdk/system-images.
I suspect a similar problem is happening on VSTS, in our monodroid build.
I also added the `-verbose` flag to the `emulator` command so we will have
more information if the emulator fails to launch during a build.

[tests] fix emulator launch when ANDROID_HOME is set

---

build-tools/scripts/RunTests.targets

Context: https://github.com/xamarin/java.interop/pull/211
For Windows to set `ANDROID_SDK_PATH` for the Java.Interop unit tests,
we need to pass `$(AndroidSdkDirectory)` through.
Otherwise a few tests get skipped in
Xamarin.Android.Tools.Bytecode-Tests.dll.

[tests] set $(AndroidSdkDirectory) for JI tests

---

build-tools/android-toolchain/android-toolchain.projitems

Context:
https://developer.android.com/studio/releases/emulator.html#26-1-3
Google has added support for `hypervisor.framework` on Mac instead of
using HAXM. It appears all we need to do to enable this is use a newer
version of the emulator. Thanks to @JonDouglas for the info about this.
To check that `hypervisor.framework` is enabled, run `make
run-apk-tests V=1`, and you should see the following output when the emulator starts:
`emulator: CPU Acceleration status: Hypervisor.Framework OS X Version 10.12`
On my machine, I also had to uninstall HAXM, which you can either do by
running the silent uninstaller or the following command:
`sudo kextunload -b com.intel.kext.intelhaxm`

[android-toolchain] update emulator to 26.1.4.0

---

tools/xabuild/XABuild.cs

This is a minor fix, but it is possible the system running `xabuild.exe`
will not have .NET Core installed. So we shouldn't set this environment
variable if the directory does not exist.

[xabuild] check if MSBuildSDKsPath exists

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

We should check StdOut for SIGSEGV as well as StdError,
just in case mono prints it there instead.

[Xamarin.ProjectTools] Check StdOut for SIGSEGV.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildActions.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildItem.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetStandard.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetXamarinProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinPCLProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj

This adds Netstandard support to our msbuild unit test system. You can now create a new `DotNetStandard` project and add that as a reference. The builder also has a new property `RequiresMSBuild` which is used to force the system to use `msbuild` for its build process.

Netstandard Support

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=60878
The Managed Resource Parsing system was not including items downloaded
into the global resource cache. As a result intellisense for those
items did not work.
This commit fixes that by adding `_CreateAdditionalResourceCache` to the
`_ManagedUpdateAndroidResgen` target. This will ensure that those
items are included. Note that we still DO NOT download files during
the designtime build. So if the required items have not been downloaded
the intellisense will still not show those items. The user will
need to do a full build to ensure those items are in place.

[Xamarin.Android.Build.Tasks] Android design-time intellisense doesn't process global cache AARs

---

tests/Xamarin.Android.Bcl-Tests/App.cs

This commit fixes one of the subtle pitfalls of the null conditional
operator (and the biggest issue with it, IMO, as it introduces subtle
*runtime* bugs which may be hard to find, depending on where and how
the code is used)
It is tempting to use the null conditional operator as follows:
string[] arr = null;
if (arr?.Length == 0)
Console.WriteLine ("Array has no elements or is null");
Console.WriteLine ($"Array contains {arr.Length} elements");
However, the above code will throw a NullReferenceException in the last
line. The reason is that the conditional expression preceeding it will
yield `false` because the ?. operator returns a nullable type which, in
this case, will have a value of `null` - and that value is not equal to
`0` obviously. Yet since the conditional expression type is …

Fix a subtle logic bug with null conditional operator

---

src/Xamarin.Android.Build.Tasks/Tasks/CreateMultiDexMainDexClassList.cs
src/Xamarin.Android.Build.Tasks/Tasks/Proguard.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://bugzilla.xamarin.com/show_bug.cgi?id=56834
A default multi-dex application will print a warning to the console
such as:
```
Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [android-support-multidex.jar:META-INF/MANIFEST.MF])
```
This is due to most jar files containing a `META-INF/MANIFEST.MF`,
which really just needs to be excluded from the proguard command.
We can do this by adding a filter to the end of each jar file passed
via the `-injars` command line option.
Changes:
- Added a `$(_AndroidProguardInputJarFilter)` internal property, which
defaults to `(!META-INF/MANIFEST.MF)` so we ignore the most common warning
by default
- Added a `ProguardInputJarFilter` property to the `<Proguard />` and
`<CreateMultiDexMainDexClassList />` tasks
- Added …

[Xamarin.Android.Build.Tasks] added filter to proguard commands

---

tools/xabuild/XABuild.cs
tools/xabuild/XABuildPaths.cs

This solves two problems with `xabuild.exe`:
- `xabuild.exe /t:Restore` did not work on Windows
- `xabuild.exe` only supported .NET Core 2.0.0
To fix these issues:
- Set `NuGetRestoreTargets` property, this allows Windows to properly
import `NuGet.targets`, which fixes the `Restore` target
- I found this property in
`%VsInstallDir%\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets`
- Note that on Windows I had to use the `ProgramW6432` environment
variable, so that a 32-bit process on a 64-bit machine could find the
path to `C:\Program Files\`
- Added logic to locate the newest version of .NET Core within the
`dotnet/sdk` directory. This allows `xabuild.exe` to function on
machines that have .NET Core 2.0.3, 1.0.0, etc.

[xabuild] better NetStandard support

---

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs
src/Xamarin.Android.Build.Tasks/Linker/PreserveLists/System.xml

Do not always preserve System.dll parts. The ProcessSystem method was
ported from Xamarin.MaciOS.
I run across this when testing linker-analyzer tool. The
`System.Net.Sockets.Socket` looked like a good candidate to check as
it was big and had only few dependencies. It turned out we preserve
the whole type unconditionaly.
```
Distance | TypeDef:System.Net.Sockets.Socket [total deps: 4][size: 16927 total size: 16927]
------------------------------------------------------------------------
1 | Other:ResolveFromXmlStep: descriptor System.xml from Xamarin.Android.Build.Tasks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
1 | Assembly:System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
2 | Other:MonoDroid.Tuner.MonoDroidMarkStep
```
I have also found out that …

[linker] Preserve System.dll parts conditionaly

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=60880
For some weird reason, writing the designer.cs location to the
FileWrites file was not working. It was getting deleted still.
So lets add it to the Xamarin.Android.Windows.targets. This is what
we use to make sure files are NOT deleted by the IncrementalClean.
Again no idea why writing the data to the FileWrites file as NOT
working.
A unit test has also been updated to make sure the designtime
file is NOT removed on the next full build after the designtime
one.

[Xamarin.Android.Build.Tasks] Android design-time intellisense gets deleted by IncrementalClean

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

Context: https://devdiv.visualstudio.com/DevDiv/Default/_build/index?buildId=1180513
The Xamarin.Android.Build.Tests aren't creating binary logs on Windows
at the moment, due to `RunningMSBuild` not being set. This flag is
probably supposed to be set on Windows, it may fix some tests as well as
enable binary logs.

[tests] RunningMSBuild likely should be set on Windows

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

If we hit a native crash in both of the attempts to run an
msbuild test we get an IO exception when trying to append the
'process.log' to the build output.
`System.IO.FileNotFoundException: Could not find file process.log`
This is because `process.log` was moved to `process.log.bak` when
we get a nartive crash.
What we want is to ignore any native crashes on the first run of
the test. If we still get a native crash on the next run we should
log it.
So on the first crash we Move the file over to the `process.log.bak`.
But we only do this on the first crash (attempt == 0). Otherwise we
end up moving the file again and we hit an error when trying to
append the process.log to the build output.

[Xamarin.ProjectTools] Fix an IO error when reading process.log

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs
src/Xamarin.Android.Build.Tasks/Tasks/AndroidToolTask.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidRegExTests.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems?id=528572
The current RegEx was capturing output which was not and error
or warning. It turns out that aapt is not very consistent with
its error messaging. Sometimes they use `error`, sometimes then
use `Error` or `ERROR`. Or in the worse case, they don't flag it
as anything.
This commit adds a few more tests to AndroidRegExTests as well
as alters the logic in `Aapt` a bit as well. This logic will
only log as an error if we have an error `level` or we have
a `file` and `line`. This seems to be fairly consistent when
looking at the `aapt` source code.
We also added a few extra `Known` errors which the regex might not
pick. This is because they do not contain a `level` or a `file`
and `line` number.

[Xamarin.Android.Build.Tasks] New APT0000 msbuild errors are being reported from aapt output parsing

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs

We shouldn't wait forever for the process to finish. We should
timeout after a short period to make sure we don't hang on the
CI system.

[Xamarin.Android.Build.Tests] Timeout when calling adb or a process.

---

Makefile
build-tools/libzip/libzip.props
build-tools/scripts/dependencies/debian-common.sh
build-tools/scripts/dependencies/linux-prepare-Debian.sh
build-tools/scripts/dependencies/linux-prepare-Ubuntu.sh
build-tools/scripts/generate-os-info

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60901
The root cause of the bug is the condition in build-tools/libzip/libzip.props
which checks whether to build libzip or not and, currently, does NOT build the
library only on Ubuntu machines. The reason for this was that, so far, none of
us tested the build on Debian and it wasn't certain what, if any, changes would
be required (despite Ubuntu being based on Debian) in order for the build to
work on Debian proper and, possibly, other related distros.
This commit introduces a new msbuild property, `$(HostOsFlavor)` which can be
used to cluster related distros/operating systems into groups with the purpose
of sharing certain behaviors or operations - like building, or not, of libzip.
This commit also introduces a `make prepare` script …

Fix build on Debian

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

If we detected a native crash on the first run of the
test we did NOT reset it.. We really should otherwise we
get incorrect log messasges on the next build.

[Xamarin.ProjectTools] Reset the native crash flag.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

The DesignTime build does not include the required Android
Defines. As a result we can get into a situation where shared
code is not compiled correctly. The Intellisense will therefore
be inaccurate or worse the design time build fails and we get
no intellisense at all.

[Xamarin.Android.Build.Tasks] Android Defines are not available in DesignTime Builds.

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Xamarin.Android.Windows.targets

Context: https://bugzilla.xamarin.com/show_bug.cgi?id=60880
Commit 552ad5d7 added code to make sure the `designtime` build
files are NOT deleted by the `IncrementalClean` target.
While it fixed the issue for `xbuild` it did NOT fix it for
`msbuild`. As a result the file was still deleted.
So we need to add the file to the target in the
Xamarin.Android.Windows.targets to ensure that it is NOT
removed (just like the mdb files).

[Xamarin.Android.Build.Tasks] Fix IncrementalClean on msbuild.

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Xamarin.Android.Windows.targets

Context: https://bugzilla.xamarin.com/show_bug.cgi?id=60880
Commit 552ad5d7 added code to make sure the `designtime` build
files are NOT deleted by the `IncrementalClean` target.
While it fixed the issue for `xbuild` it did NOT fix it for
`msbuild`. As a result the file was still deleted.
So we need to add the file to the target in the
Xamarin.Android.Windows.targets to ensure that it is NOT
removed (just like the mdb files).

[Xamarin.Android.Build.Tasks] Fix IncrementalClean on msbuild. (#1063)

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.FSharp.targets

Context: https://devdiv.visualstudio.com/DevDiv/Default/_build/index?buildId=1188880&_a=summary&tab=ms.vss-test-web.test-result-details
Our FSharp tests are failing on Windows due to the way we are having to
import `Microsoft.FSharp.targets`:
```
<Import
Condition="'$(Language)' != 'F#' And Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets')"
Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets"
/>
```
Since `xabuild.exe` is modifying `$(MSBuildExtensionsPath)` to a path in
XA's build tree, the `Condition` always evaluates to `False`--even though
the search path fallbacks would have located it. Since we are having to
use `Condition` and check for multiple paths for …

[tests] fix for FSharp targets on Windows

---

src/Xamarin.Android.Build.Tasks/Tasks/AsyncTask.cs

There is a possilility that we might be locking up the UI thread
when logging CustomBuildEvents.. This happens in the
`InstallPackageAssemblies` task. Currently we only use
BuildEngine.LogCustomEvent
Which may well cause problems when called from a non UI thread.
So in keeping with the other Log methods available we should add
a new LogCustomBuildEvent. This will queue and marshall the data
to the UI Thread just like the other methods do.

[Xamarin.Android.Build.Tasks] Add LogCustomBuildEvent method to AsyncTask

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

This commit adds an additional check to only process the
process.log if the file exists. We might be in a situation
where nothing is written to StdOut or StdErr as a result we
might not get a log file. So lets not crash the test if it
does not exist.

[Xamarin.ProjectTools] Only add the process.log if it exists.

---

README.md

Added a quick note for people who browse the repository on the proper place to report issues. We can extend this out further as well with a contribution/how to report guide.

Change "Reporting Bugs" section to Github Issues

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs

If the `adb` command times out it will probably return
an empty string. In that case we should NOT run the
tests which need devices.
So instead of checking for an error, lets try to parse
the output to an int. We should be getting a valid
integer value back for the sdk version. If we do not then
we should not run those tests.

[Xamarin.Android.Build.Tests] Fix detection of Emulators.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context https://bugzilla.xamarin.com/show_bug.cgi?id=60880
Turns out the design time build in Visual Studio does not
clean up after itself.. ever. So we really should not be
deleting the directory on a `Clean`.
This commit move that code into is own internal target
and updates the tests to reflect the changes.

[Xamarin.Android.Build.Tasks] Dont clean the designtime folder

---

src/Xamarin.Android.Build.Tasks/Tasks/Lint.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://devdiv.visualstudio.com/DevDiv/Default/_build/index?buildId=1196396&_a=summary&tab=ms.vss-test-web.test-result-details
I am not sure how I missed this, but the `<Lint />` task was always
failing on Windows unless `JAVA_HOME` is set.
The error is:
```
LINT JAVA_HOME is not set and no 'java' command could be found in your PATH.
```
To fix this:
- Pass `$(JavaSdkDirectory)` to the `<Lint />` task
- Set `JAVA_HOME` for `ToolTask`'s `EnvironmentVariables` property
- Set `JAVA_HOME` when running `lint.bat --version`, I had to add an
optional parameter for environment variables to
`MonoAndroidHelper.RunProcess`

[lint] JAVA_HOME must be set on Windows

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs

When I originally setup `FrameworkLibDirectory` on Windows,
`setup-windows.exe` was the method for running these tests. Now that
`xabuild.exe` is used instead, we need this directory to also possibly
be used from within the build tree as when `IsUnix` is true.
Changes:
- `FrameworkLibDirectory` will return locations within the build tree on
windows
- A few places that used to have an `IsUnix` check such as
`AndroidMSBuildDirectory`, it made more sense to do a `Directory.Exists`,
and then fallback to using `FrameworkLibDirectory`
- Fixed the `CrossCompilerAvailable` method on Windows
- The `BuildAotApplication` test has a `Regex` that won't work on
Windows due to shortened paths. It looked best to skip this assertion.
This short fix a variety of tests on Windows, and hopefully un-ignore …

[tests] fixed FrameworkLibDirectory on Windows

---

src/Xamarin.Android.Build.Tasks/Mono.Android/BroadcastReceiverAttribute.Partial.cs
src/Xamarin.Android.NamingCustomAttributes/Android.Content/BroadcastReceiverAttribute.cs

There is some grand idea to generate all those attributes code, but it's
going to take long time and this bug shouldn't need to wait for that.
This bug can be fixed with just a few lines of changes.

add BroadcastReceiverAttribute.Description property. (fix bug #60940)

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

We have an occasional issue with xbuild throwing an error.
Unhandled Exception:
System.ArgumentException: is negative
Parameter name: count
at (wrapper managed-to-native) System.Buffer.InternalBlockCopy(System.Array,int,System.Array,int,int)
at System.IO.StreamWriter.Write (System.Char[] buffer, System.Int32 index, System.Int32 count) [0x00094] in /Users/builder/data/lanes/5533/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/streamwriter.cs:415
at System.IO.TextWriter.WriteLine (System.String value) [0x00070] in /Users/builder/data/lanes/5533/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/io/textwriter.cs:490
at Microsoft.Build.BuildEngine.ConsoleLogger+BuildRecord.WriteLine (System.String message) …

[Xamarin.ProjectTools] Handle xbuilds negative index error.

---

src/Xamarin.Android.NamingCustomAttributes/Android.App/ActivityAttribute.cs
src/Xamarin.Android.NamingCustomAttributes/Android.App/ApplicationAttribute.cs
src/Xamarin.Android.NamingCustomAttributes/Android.App/InstrumentationAttribute.cs
src/Xamarin.Android.NamingCustomAttributes/Android.App/ServiceAttribute.cs
src/Xamarin.Android.NamingCustomAttributes/Android.Content/BroadcastReceiverAttribute.cs
src/Xamarin.Android.NamingCustomAttributes/Android.Content/ContentProviderAttribute.cs
src/Xamarin.Android.NamingCustomAttributes/Android.Runtime/RegisterAttribute.cs
src/Xamarin.Android.NamingCustomAttributes/Java.Interop/IJniNameProviderAttribute.cs
src/Xamarin.Android.NamingCustomAttributes/Xamarin.Android.NamingCustomAttributes.projitems

Those Attributes are specific to Android, but they have been part of
Java.Interop codebase because things were not that well separate.
Add a simple interface to avoid concrete dependencies to Android.*
attributes and make things simpler.

Reduce Android.* dependency from Java.Interop repo.

---

src/Xamarin.Android.Build.Tasks/Tasks/CreateMultiDexMainDexClassList.cs
src/Xamarin.Android.Build.Tasks/Tasks/Proguard.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

I noticed on Windows, the `Desugar(True, True, True)` test was failing
with:
```
java.io.IOException: Can't read
[E:\A\_work\1\s\bin\TestDebug\temp\Desugar(True,True,True)\obj\Release\android\bin\classes\classes.zip(!META-INF\MANIFEST.MF)]
(No such file or directory)
```
However, running locally proved the file does exist.
Somehow #1049 introduced a case where proguard is failing due to the
combination the new `(!META-INF/MANIFEST.MF)` filter and the parameters
passed to proguard in this test.
Looking into it, we had an odd form of how the paths were being passed
on Windows using a combination of single and double-quotes:
```
-injars "'path1(!META-INF/MANIFEST.MF)';'path2(!META-INF/MANIFEST.MF)'"
```
The way these paths were passed was not working on Windows after adding
this new …

[Xamarin.Android.Build.Tasks] fix for proguard enclosing char on windows

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildItem.cs

Changes:
- `CheckResourceDesigner*` for F# can't pass on Windows due to the
MSBuild project API sorting. F# relies on files in the `fsproj` in a
certain order, which cannot be achieved if the MSBuild API always does
its own sorting. I feel it is best to skip these tests on Windows for
now.
- `BuildExternalJavaLibrary` should just use `$(MSBuildExtensionsPath)`
since `$(MonoDroidInstallDirectory)` is not set on Windows. It also
needed to apply a timestamp to the new reference, or the project file
wasn't saving on Windows. The last fix is using `Path.Combine`.
- `BuildAppCheckDebugSymbols` needs to set `DebugType` to `portable` on
Windows in order to produce pdb files
- `BuildAppWithManagedResourceParserAndLibraries` was consistently
taking ~9 seconds on the VSTS build agent. I was also …

[tests] fixed several tests on Windows

---

tools/xabuild/XABuild.cs
tools/xabuild/XABuildPaths.cs

The `NetStandardReferenceTest` has been failing on Windows due to its
use of `<PackageReference />`.
Windows appears to need to import two files:
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.props
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets
Luckily we can set two properties to specify these paths:
`$(NuGetProps)` and `$(NuGetTargets)`. I think this is only a problem on
Windows, as these files aren't present on macOS.

[xabuild] support <PackageReference />

---

build-tools/enumification-helpers/enum-conversion-mappings.xml
build-tools/enumification-helpers/generate-const-mapping.cs
build-tools/enumification-helpers/methodmap.ext.csv
src/Mono.Android/map.csv
src/Mono.Android/methodmap.csv

See the github comments on the issue details.
To solve the issue, we introduce a "fake" mapping fixup in enumification-helpers.
Use "force-api-level" mapping information to override the correct API Level
information to generate modified map(.ext).csv.
methodmap.csv is also fixed to (1) remove old mapping for 24 and (2) change
the mapping for 25 down to 24 too.

[enumification] fix RemoteConference.ConnectionProperties (issue #1087)

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Context: https://devdiv.visualstudio.com/DevDiv/Default/_build/index?buildId=1206705&tab=ms.vss-test-web.test-result-details
`BuildAMassiveApp` has been failing under MSBuild with:
```
E:\A\_work\1\s\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\Xamarin.Android.Common.targets(1167,2):
error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'Lib0,
Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Lib0.dll'
```
It turns out that setting `BuildingInsideVisualStudio` signals MSBuild
that it doesn't need to figure out project dependencies. So
`Lib0.csproj` isn't built at the time `ResolveLibraryProjectImports`
runs.
For now, it seems …

[tests] fix BuildAMassiveApp under MSBuild

---

src/Xamarin.Android.Build.Tasks/Utilities/ZipArchiveEx.cs

Fixes: https://devdiv.visualstudio.com/DevDiv/Release%20Dashboard/_workitems?id=534477&_a=edit
On Xamarin.Android 8.1 on Windows, we are experiencing problems with
file sharing causing build errors:
error while writing anim: obj\Debug\android\bin\classes\android\support\design\R$anim.class (The process cannot access the file because it is being used by another process)
Bump to LibZipSharp/b7aab1e2 so that we don't need to rely on the GC
finalizing object instances to close `FileStream` instances.
This deterministic closing of files in turn means that
`ZipArchiveEx.Flush()` no longer needs to call `GC.Collect()`, which
wasn't a reliable fix anyway...

Bump to LibZipSharp/master/b7aab1e26

---

build-tools/enumification-helpers/generate-const-list-2.cs

There were final fields that actually didn't give value in the API XML.

[enumification] filter final ints without explicit constant value.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1223975
A recent Windows test run failed with:
```
E:\A\_work\1\s\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\Xamarin.Android.Common.targets(2191,3):
error XA5213:
java.lang.OutOfMemoryError. Consider increasing the value of $(JavaMaximumHeapSize).
Java ran out of memory while executing 'java.exe -jar
C:\Users\dlab\android-toolchain\sdk\build-tools\26.0.1\\lib\dx.jar
--dex --no-strict --output obj\Release\android\bin
E:\A\_work\1\s\bin\TestDebug\temp\BuildAMassiveApp\App1\obj\Release\android\bin\classes\classes.zip
E:\A\_work\1\s\bin\Debug\lib\xamarin.android\xbuild-frameworks\MonoAndroid\v8.1\mono.android.jar
C:\Users\dlab\AppData\Local\Xamarin\GooglePlayServicesLib\22.0.0\embedded\classes.jar …
```

[tests] BuildAMassiveApp needs JavaMaximumHeapSize

---

src/Mono.Android/Java.Interop/JavaObjectExtensions.cs
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Extensions.cs
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MarkJavaObjects.cs
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs

Currently, interfaces generate `Invoker` classes such as:
```
// src/Mono.Android/obj/Debug/android-26/mcw/Java.Lang.IAppendable.cs
partial class IAppendableInvoker {
public static IAppendable GetObject (IntPtr handle, JniHandleOwnership transfer)
{
return global::Java.Lang.Object.GetObject<IAppendable>(handle, transfer);
}
}
```
`JavaCast` was previously looking up these `Invoker` types and calling
the `GetObject` method via reflection. We can simplify this by just calling
`Java.Lang.Object.GetObject()` directly—bypassing all the reflection.
One day we might be able to drop the generated `Invoker` method from
generator, but compiled bindings would break on older versions of
Xamarin.Android. It might be *instead* worthwhile look into allowing
the linker to strip the `*Invoker.GetObject()` …

[java.interop] improve JavaCast() for interfaces

---

src/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/StartAndroidEmulator.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build/index?definitionId=8113
In cases where HAXM is installed/not working, an `ERROR:` message can be
displayed via stdout. We should check both stdout and stderr for
`ERROR:` messages.
This caused builds to hang on VSTS, since the VMs on VSTS do not
currently support HAXM.

[tests] StartAndroidEmulator should check stdout for "ERROR:"

---

src/Mono.Android/Test/Mono.Android-Tests.projitems
tests/Xamarin.Forms-Performance-Integration/Droid/Xamarin.Forms.Performance.Integration.Droid.projitems

Previous commit
https://github.com/xamarin/xamarin-android/commit/dd42c9a41fac43a96b001e374c7a691aff3284c8
tried to fix apk sizes input filename, as it was broken for some
time. I overlooked that `Package` is part of the item group though and
not a property group as I thought. Thus we got all measurement mixed,
so last one won and thus we have wrong numbers for Mono.Android
test. This patch fixes that.

[tests] Fix apk sizes input filename

---

src/Mono.Android/Java.Interop/AndroidEventHelper.cs
src/Mono.Android/Java.Interop/EventHelper.cs

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=59804
Context: https://gist.github.com/jonpryor/d0e7bda3107913d0ab8ad46e8ae26419
Context: http://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/
(Would you believe a 5.5+ year old bug? Of course you would!)
Assume a *multithreaded* event registration and dispatch Java app,
such as that in the JavaBeans 1.0.1 spec §6.5.1, in which one thread
(un-)subscribes to events via `Model.addModelChangedListener()` and
`Model.removeModelChangedListener()`, while *another thread* is
responsible for calling `Model.notifyModelChanged()`.
This is fine, *so long as* a Listener doesn't "invalidate" itself
while still accessible from `Model.listeners`:
// This is fine and normal
MyModelChangedListener l = new …

[Mono.Android] Don't dispose of event handler implementors

---

build-tools/android-toolchain/android-toolchain.projitems
build-tools/scripts/RunTests.targets
src/Xamarin.Android.Build.Tasks/Tasks/MakeBundleNativeCodeExternal.cs
src/Xamarin.Android.Build.Tasks/Tasks/NdkUtils.cs

Context: https://developercommunity.visualstudio.com/content/problem/166029/building-xamarinandroid-application-with-bundleass.html
NDK 14r introduced experimental support for so-called "unified headers" which
replace the per-platform C header files, NDK 15 deprecated the old headers and
NDK 16 removed them completely. Xamarin.Android has been building itself with
NDK configured to use unified headers for a while now, but we missed one piece
of code which is affected by the change - mkbundle.
This commit adds code to MakeBundleNativeCodeExternal task to make it possible
to build code generated by mkbundle on systems with NDK that lacks the
per-platform header files. This is done in a backward-compatible way but if your
NDK has both the old and the new headers, the latter will be used. …

Fix bundling of assemblies in NDK with unified headers

---

build-tools/create-vsix/create-vsix.targets
build-tools/scripts/BuildEverything.mk

Context: https://developer.xamarin.com/releases/android/xamarin.android_7/xamarin.android_7.4/#API-10_is_Obsolete
Context: https://github.com/xamarin/xamarin-android/pull/1105
Context: https://github.com/xamarin/xamarin-android/pull/1032
In Xamarin.Android 7.4, we announced that API-10 was obsolete and
would be removed in a future release.
PR #1032 attempted to do so, but does not yet work, so until now we
have continued shipping API-10 assemblies, even though
Xamarin.Android 7.4 hit stable on 2017-Aug-11.
Meanwhile, PR #1105 includes an NDK bump, which in turn means that the
lowest API level we can compile for will be *API-14*.
Attempt to split the difference, assuming PR #1105 lands before
PR #1032: Keep the supporting files for API-10, but don't build them,
and explicitly remove `v2.3` …

[create-vsix, build] Don't package API-10 assemblies

---

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Linker.cs

Bumps to cecil/mono-2017-10/76ffcdab.
This is consistent with cba77e9d, which *hopefully* means we won't get
the unit test failures seen in PR #1101.

Bump to mono/2017-10/63e8dc6e

---

build-tools/scripts/PrepareWindows.targets

We discovered the build fails on Windows if you:
- wipe out `~\android-toolchain`
- `git clean -dxf`
- `msbuild Xamarin.Android.sln /t:Prepare`
- Or just have a fresh machine
We need to reorder the steps of what happens in `PrepareWindows.targets`:
1. `git submodule update`
2. build `xa-prep-tasks`, which gets `.nuget\NuGet.exe`
2. `nuget restore`
3. build `android-toolchain` , which is the missing step that installs the Android SDK
4. proceed with everything else
Without step no. 3, the missing Android SDK that gets installed to
`~\android-toolchain` causes the `<JdkInfo />` task to fail.

[build] fix Windows build on a fresh machine

---

src/Mono.Android/Android.Runtime/JNIEnv.cs
src/Mono.Android/Test/Java.Interop/JnienvTest.cs
src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=61073
Context: xamarin/java.interop#227
The Java-to-Managed typemaps list types such as:
```
android/app/Activity
Android.App.Activity, Mono.Android, Version=0.0.0.0, Culture=neutral,
PublicKeyToken=84e04ff9cfb79065
```
This is found in the intermediate dir after a  build in `acw-map.txt`,
or `$(_AcwMapFile)`.
Let’s assume you have an Android project with the following
assembly-level attribute:
```
[assembly:AssemblyVersion("1.0.0.*")]
```
Then on *every* build, the typemap is invalidated because your version
number has been incremented.
Changes:
- Bumped Java.Interop to master/429dc2a
- `JNIEnv` needs to use the shorter type name when calling
`monodroid_typemap_managed_to_java`
- `GenerateJavaStubs` should not be writing lines for …

[Xamarin.Android.Build.Tasks] <GenerateJavaStubs /> generates a shorter acw-map.txt

---

src/Xamarin.Android.Build.Tasks/Tasks/CreateMultiDexMainDexClassList.cs
src/Xamarin.Android.Build.Tasks/Tasks/Proguard.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Fixes: #1135
Context: #1068
When making changes in #1068, I added a unit test that builds an
application with both spaces and parentheses in its path. However, this
was not enough to test everything; the test also needed an
`AndroidJavaLibrary` build item with spaces and parentheses in its name!
Changes:
- Made a `Hello (World).jar` file, that has a single class in it
- Added the jar file as a `AndroidJavaLibrary`, in
the `BuildApplicationWithSpacesInPath` test
- Reverted `Proguard.cs` and `CreateMultiDexMainDexClassList.cs` from
what I did in #1068 -- Dean tried to warn me
- Move the `(!META-INF/MANIFEST.MF)` filter expression outside the
single quotes
- For the `-injars` expression to work on *both* macOS and Windows,
I had to enclose the entire expression in double-quotes
PR #1068 was …

[Xamarin.Android.Build.Tasks] ProGuard/MultiDex fix parentheses in path

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Commit fd969980 added support for reading and parsing R.txt
files. This commit adds support for generating the file as
part of the `_UpdateAndroidResgen` target.
The idea is that if the R.txt file is present we should use
that for our design time build Resource.Designer.cs.

[Xamarin.Android.Build.Tasks] Generate an R.txt for DesignTime Builds.

---

src/Mono.Android/Android.Runtime/UncaughtExceptionHandler.cs

Fixes https://github.com/xamarin/xamarin-android/issues/1144
User code cannot easily unwrap the inner exception itself unless
it uses reflection to read the `JavaProxyThrowable.InnerException`
property which is unacceptable.
Add code to unwrap the exception before calling the AppDomain
unhandled exception handler.

Unwrap JavaProxyThrowable in unhandled exception handler

---

src/Xamarin.Android.Build.Tasks/Tasks/CompileToDalvik.cs
src/Xamarin.Android.Build.Tasks/Tasks/CreateMultiDexMainDexClassList.cs
src/Xamarin.Android.Build.Tasks/Tasks/Javac.cs
src/Xamarin.Android.Build.Tasks/Tasks/Proguard.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=61073
Context: a296784
When we added the new `classes.zip` functionality, there was one oddity
present. On the first build, everything appears to be normal. On the
second build, `classes.zip` appeared to contain itself inside itself???
To make things even stranger, I wrote a unit test that contains a
`Java.Lang.Object` subclass in which its type and namespace names change
on each write. This worked fine on macOS, even with the oddity of
`classes.zip` continually zipping itself inside itself... The new java
sources would appear at the bottom of the list within the zip file.
Everything broke down when I tried my unit test on Windows, the case of
`classes.zip` trying to compress itself inside itself was silently
failing. It was not …

[Xamarin.Android.Build.Tasks] fix classes-zip inception

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs

Fixes #1136
Commit 7f45a6d reworked the GetJavaPlatformJar Task (and others)
to handle a NRE exception. However the error logging code in
MonoAndroidHelper.cs was not formatted correctly. As a result
the XA5207 error would be logged without any message.
This commit fixes up the LogError call to make sure the error
has a decent message. It also adds a unit test so that we can
catch this issue if it regresses in the future.

[Xamarin.Android.Build.Tasks] Fix message for missing Platform error XA5207

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidRegExTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs

Context #1134 
Aapt is pretty inconsistent with how it reports errors and
warnings. Warnings are written to stderr..
So we are reworking the output processing for aapt to hopefully
handle errors are warnings in a more consistent way. Rather than
process the output in realtime we will buffer it and process the
output once aapt has completed. This will allow us to check to
see if the required output file (R.java) was created. If it
wasn't then we can assume that the process failed.
We can then process the output knowing that we are expecting
and error. In the case where R.java does exist, we can assume
if we do find anything which looks like an error it is more
than likely a warning.

[Xamarin.Android.Build.Tasks] Rework Aapt log processing.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=61065
If a user sets the `$(AndroidKeyStore)` to `True` for a
debug configuration they will get the following error.
[MESSAGE] jarsigner error: java.lang.RuntimeException: keystore load: /Users/$(user)/.local/share/Xamarin/Mono for Android/debug.keystore (No such file or directory)
Note this will only happen if they have NEVER build with
`$(AndroidKeyStore)` set to `False`. This is because we
don't always generate the `debug.keystore`.
So rather than hitting this issue we should always generate the
`debug.keystore` regardless of what the setting for `$(AndroidKeyStore)`
is. This commit splits out the keystore generation into its own
target. This target will check the existance of the file and
generate it if required. We also move all the …

[Xamarin.Android.Build.Tasks] Always create the debug.keystore

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildAssetsTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context #1150
The way the current system works is that the `UpdateAndroidAssets`
target is called as part of the `ResolveReferencesDependsOn`. This
makes it impossible to do any kind of processing of assets after
the project has already built. It also menas that a straight up
call to `Build` will result in all the assets being copied into
the intermediate directory. If your project has a large number
of assets that is going to take time. Note this might also be
called as part of a designtime build at the moment... not good.
So is there a reason why we call `UpdateAndroidAssets` before
`Compile`? We don't generate any entries in the Designer.cs files
for them.. We don't clean them up.. we dont appear to do anything
except package them! So the anser looks to be a resounding NO!
So we shall …

[Xamarin.Android.Build.Tasks] ReOrder when Assets are Processed.

---

build-tools/mono-runtimes/ProfileAssemblies.projitems
build-tools/mono-runtimes/mono-runtimes.targets
tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.targets

PR https://github.com/xamarin/xamarin-android/pull/1075 keeps rebuilding all the
Mono runtimes because the two files in this commit are part of the logic to
determine whether to use cached Mono or not. The result isn't cached, because
it's a PR builder, and so we keep waiting for 7h+ each time a smallest change is
made. This commit will cause Mono to be rebuilt and cached and, in turn, speed
up round-trip time for PR 1075

Preparation for the new test runner

---

Makefile

Update the `make prepare` step so that we pass `JI_MAX_JDK=8` to
Java.Interop's `make prepare` step. This prevents us from using JDK 9
if it is installed on the machine.
Internal VSTS builds are failing *seemingly* because JDK 9 is
installed and used by default on the build machine, with `gradelw`
bailing out with:
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
This previously worked with JDK 8, so we're hoping that the use of
JDK 9 is the cause, and by *excluding* JDK 9 from being used we'll be
able to build on VSTS again.

[build] Set `$(JI_MAX_JDK)` for Java.Interop

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

Context #1134
Commit 23c5801 reworked Aapt to emit warnings if the required
output file did exist. If it didn't we should emit errors.
There was one slight problem with this, we were checking the
wrong file. We should have been checking for the temp
packaged_resources file rather than the R.txt (which will
always exist after an initial build).
This commit fixes that amd adds a unit test. Note the in order
to create the senario we need to have a `$(TargetFrameworkVersion)`
which is `v8.0`. We currently only build `v1.0` and `v8.1` for
PR builds. So the test checks to see if that target framework is
available. If not the test will be ignored.

[Xamarin.Android.Build.Tasks] Fix Aapt task to emit warnings

---

src/Xamarin.Android.Build.Tasks/Tasks/Lint.cs

Context #1171
There is a new test [ObsoleteSdkInt] which produces a warning
such as
obj/Debug/android/src/mono/MonoPackageManager.java(85,6): warning XA0102:  Unnecessary; SDK_INT is always >= 10 [ObsoleteSdkInt]
So our MonoPackageManager.java file is the cause of this
particular warning [1]. I am not sure we can remove that
line of code yet, since our apps can run on older devices.
That said once the % share of devices for API's < 8 is 0,
we can probably remove that line of code completely and
re-enable this check.
[1] https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Resources/MonoPackageManager.java#L85

[Xamarin.Android.Build.Tasks] Ignore the ObsoleteSdkInt Lint Check

---

src/Xamarin.Android.Build.Tasks/Tasks/CompileToDalvik.cs
src/Xamarin.Android.Build.Tasks/Tasks/CreateMultiDexMainDexClassList.cs
src/Xamarin.Android.Build.Tasks/Tasks/Javac.cs
src/Xamarin.Android.Build.Tasks/Tasks/Proguard.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=61073
Context: a296784
When we added the new `classes.zip` functionality, there was one oddity
present. On the first build, everything appears to be normal. On the
second build, `classes.zip` appeared to contain itself inside itself???
To make things even stranger, I wrote a unit test that contains a
`Java.Lang.Object` subclass in which its type and namespace names change
on each write. This worked fine on macOS, even with the oddity of
`classes.zip` continually zipping itself inside itself... The new java
sources would appear at the bottom of the list within the zip file.
Everything broke down when I tried my unit test on Windows, the case of
`classes.zip` trying to compress itself inside itself was silently
failing. It was not …

[Xamarin.Android.Build.Tasks] fix classes-zip inception (#1142)

---

src/Xamarin.Android.Build.Tasks/Tasks/AndroidUpdateResDir.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildAssetsTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/Files.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.csproj

When adding a new subfolder in the IDE (VSForMac) we end up
with a folder which has a build action of AndroidAsset.
This causes the copy task to fail with
Cannot copy <folder> to <destfolder>, as the source file doesn't exist",
This is because we assume that all items in AndroidAsset (and
AndroidResource) and files. It looks like this is not the case.
While a work around is easy .. simply remove the item. It does
require that the user manually update the csproj.
So this commit uses `Directory.Exists` to check to see if the
item is a directory or not. If it is we skip over it. Otherwise
its a file so we should copy.
We do this in `Files.cs` but also in `AndroidUpdateResDir.cs`.
The latter has been changed to output a list of the "Resolved"
files which will not include any folders.

[Xamarin.Android.Build.Tasks] Ignore AndroidAsset items which are folders.

---

src/Mono.Android/Mono.Android.projitems

The API-27 binding has been considered stable (-ish) since commit
914f95fc, give or take a few problems (c2811327, 9cc80d7a, etc.).
Ensure that the generated `AndroidApiInfo.xml` files (8942eca0)
state that API-27 is stable.

[Mono.Android] API-27/v8.1 is stable

---

build-tools/enumification-helpers/enum-conversion-mappings.xml
src/Mono.Android/map.csv

After the last API XML generation sanitization, ChoiceMode was removed
because they were generated from AbsListView fields which DOES NOT EXIST
in API Level 10.
And getChoiceMode() and setChoiceMode are removed because they expect
that nonexistent enum.
Fortunately they are in ListView in API Level 10, so they can be generated
from there.

[enumification][Mono.Android] fix ChoiceMode enum generation.

---

build-tools/enumification-helpers/enum-conversion-mappings.xml
src/Mono.Android/map.csv

After the last API XML generation sanitization, ChoiceMode was removed
because they were generated from AbsListView fields which DOES NOT EXIST
in API Level 10.
And getChoiceMode() and setChoiceMode are removed because they expect
that nonexistent enum.
Fortunately they are in ListView in API Level 10, so they can be generated
from there.

[d15-6][enumification][Mono.Android] fix ChoiceMode enum generation.

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #1165
We need to provide default values for `platform-tools` and
`tools` so that our SDK Manager can correctly download
the required versions.

[Xamarin.Android.Build.Tools] Add $(AndroidSdkPlatformToolsVersion)

---

tests/BCL-Tests/LocalTests.NUnit/System.Net.Http/HttpClientTest.cs

The server used in the test sometimes cannot be reached, there's no need to
treat it as a failure. Ignore the timeout with Assert.Ignore instead.

[Tests] Make the HttpClientTest.TestEscapedURI test ignore timeout

---

src/Xamarin.Android.Build.Tasks/Tasks/CheckTargetFrameworks.cs

Removes an additional "v" that was being included in a warning message when the `$(TargetFrameworkVersion)` is lower than what other assemblies expect in a `XA0105` warning.
Example Warnings on 15.6:
```
2>C:\Users\dougl\source\repos\App75\App75\App75.Android\App75.Android.csproj : warning XA0105: The $(TargetFrameworkVersion) for FormsViewGroup.dll (vv8.0) is greater than the $(TargetFrameworkVersion) for your project (v7.1). You need to increase the $(TargetFrameworkVersion) for your project.
2>C:\Users\dougl\source\repos\App75\App75\App75.Android\App75.Android.csproj : warning XA0105: The $(TargetFrameworkVersion) for Xamarin.Forms.Platform.Android.dll (vv8.0) is greater than the $(TargetFrameworkVersion) for your project (v7.1). You need to increase the $(TargetFrameworkVersion) for …
```

Remove extra "v" from $(TargetFrameworkVersion) XA0105 warning

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

We need to add an additional conditional Import for the
Installer target. This will allow commercial users to use
the following targets.
`GetAndroidDependencies`
`InstallAndroidDependencies`

[Xamarin.Android.Build.Tasks] Add Installer target Import.

---

build-tools/scripts/Jar.targets
src/Xamarin.Android.Build.Tasks/Tasks/AdjustJavacVersionArguments.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
tests/CodeGen-Binding/Xamarin.Android.FixJavaAbstractMethod-APIv1Binding/Xamarin.Android.FixJavaAbstractMethod-APIv1Binding.csproj
tests/CodeGen-Binding/Xamarin.Android.FixJavaAbstractMethod-APIv1Binding/Xamarin.Android.FixJavaAbstractMethod-APIv1Binding.targets
tests/CodeGen-Binding/Xamarin.Android.FixJavaAbstractMethod-APIv2Binding/Xamarin.Android.FixJavaAbstractMethod-APIv2Binding.csproj
tests/CodeGen-Binding/Xamarin.Android.FixJavaAbstractMethod-APIv2Binding/Xamarin.Android.FixJavaAbstractMethod-APIv2Binding.targets
tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding/Xamarin.Android.LibraryProjectZip-LibBinding.targets
tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/Xamarin.Android.McwGen-Tests.csproj
tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests/Xamarin.Android.McwGen-Tests.targets
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib1/Xamarin.Android.BindingResolveImportLib1.csproj
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib1/Xamarin.Android.BindingResolveImportLib1.targets
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib2/Xamarin.Android.BindingResolveImportLib2.csproj
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib2/Xamarin.Android.BindingResolveImportLib2.targets
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib3/Xamarin.Android.BindingResolveImportLib3.csproj
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib3/Xamarin.Android.BindingResolveImportLib3.targets
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib4/Xamarin.Android.BindingResolveImportLib4.csproj
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib4/Xamarin.Android.BindingResolveImportLib4.targets

We have a VSTS+macOS build machine which has JDK 9 as the default JDK,
thus causing *all* xamarin-android builds to fail, as `gradlew` and
JDK 9 don't *directly* mix:
Executing: ./gradlew assembleDebug --stacktrace
...
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':library'.
...
Caused by: org.gradle.internal.event.ListenerNotificationException:
Failed to notify project evaluation listener.
...
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
...
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
When using JDK 9, `gradlew` fails because *something* within it
attempts to use the deprecated type
`javax.xml.bind.annotation.XmlSchema`, and JDK 9 doesn't provide
deprecated modules in the …

[build] Cursory JDK 9 support

---

src/Xamarin.Android.Build.Tasks/Tasks/AndroidApkSigner.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Once again we hit an issue where the `apksigner.bat` file provided
with android build-tools was not functioning correctly. So like
we did with `dx.bat` and other tooling we should switch to using
the `apksigner.jar` file directly.
Additionally JDK 9 has removed support for the `java.ext.dirs`, which
all versions of the `apksigner.bat` use. As a result this tool will
not work with JDK 9. So its best to remove it now.
We have existing unit tests which check that the Apk is being
signed correctly. So not additional tests are required.

[Xamarin.Android.Build.Tasks] Rework AndroidApkSigner to use .jar directly.

---

build-tools/scripts/ApkSizesDefinitions.txt

This way we will see changes in Java.Interop.dll size when we switch
to complete Java.Interop.dll instead of XAIntegration's one.

[Plots] Measure Java.Interop.dll size as well

---

Makefile

The [`msbuild`-based Jenkins job][jenkins-msbuild] job has been
failing a lot recently:
[jenkins-msbuild]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-msbuild/
error MSB3644: The reference assemblies for framework "MonoAndroid,Version=v1.0" were not found.
The cause of the error is that *when there is no prebuilt mono runtime
to download*, this file does not exist:
bin/Debug/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v1.0/RedistList/FrameworkList.xml
The above file is created by the
`build-tools/scripts/mono-runtimes.mdproj` build, and
`mono-runtimes.mdproj` *is not being built*. Without a mono build,
there is no `MonoAndroid/v1.0` framework, and everything fails.
I don't know when this actually broke, or what change is responsible.
(It works with …

[build] Fix the MSBuild build

---

build-tools/api-merge/ApiDescription.cs

When merging we process several API description files, each for a separate
platform. The resulting file currently carries the *first* platform level in its
`<api platform="">` root element attribute. This is a subtle issue that may
cause problems when applying fixups from metadata (for instance) as the
`api-since` and `api-until` attributes in fixups may apply to incorrect sets of
API members.
Fix the issue by putting the latest API description platform level as obtained
from the files provided to api-merge (the files are sorted in platform level
ascending order)

Make sure merged api description has the latest platform level

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in

Fixes #1248
JDK 9 doesn't currently provide a robust and reliable user
experience. Until we can provide a reliable experience, we
should "fail early".
We already have a property for `$(LatestSupportedJavaVersion)`
which currently cannot be overridden. We also currently emit
a warning when the java version is greater than this property.
However with JDK 9 it seems a warning is not enough. So we
should change the warning to an error. We also need to make
`$(LatestSupportedJavaVersion)` writable so that it can be
overridden from the command line via.
msbuild /p:LatestSupportedJavaVersion=9.0.0 /t:SignAndroidPackage TheApp.csproj

[Xamarin.Android.Build.Tasks] Generate error when JDK 9 is used

---

build-tools/scripts/generate-os-info

GCC has recently added flags to mitigate effects of the Spectre CPU bug. The
flags enable compiler to replace certain processor instructions vulnerable to
the attack (function return, indirect branches - function calls, conditional
branching etc) by instructions which invalidate CPU's branch prediction cache
and thus mitigate the threat.

Detect whether host compiler supports Spectre mitigation flags

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Xamarin.Android.Windows.targets

Fixes #1164
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=61108
The IncrementalClean target basically deletes a ton of stuff
if its not in the FileWrites group. Under certain conditons
this include assemblies in the `$(OutDir)`.
It mainly effects projects which use a shared `$(OutDir)`.
So it a third level dependency is copied to the `$(OutDir)`
but is not referenced by the main app project we end up with
IncrementalClean deleting the file. This then breaks packaging
since we expect the file to exist.
This causes problems with TFS because it seems to ALWAYS use
a shared `$(OutDir)`.
To work around this problem we just need to tell IncrementalClean
to ignore any dll in the `$(OutDir)`. Since we already have a
target in place to handle this we can just expand the list of
files it …

[Xamarin.Android.Build.Tasks] Stop IncrementalClean removing assemblies.

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Xamarin.Android.Windows.targets

Commit 20123b5 broke the build system on windows. The
condition on `_RegisterAndroidFilesWithFileWrites` was
incorrect. `_IsRunningXBuild` can be empty when running
under MSbuild. As a result the condition will always
result in the target being skipped.
This commit fixes the condition to that it will run
correctly under msbuild and is skipped on xbuild.

[Xamarin.Android.Build.Tasks] Fix Conditon on _RegisterAndroidFilesWithFileWrites

---

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs

With this change it is possible to build an apk containing `aot`
profiler module (libmono-profiler-aot.so shared library) and profile
the app with it. It can enabled by setting `mono.debug.profile`
property to `aot` on the device or emulator.
Note that the `aot` profiler saves the data during the mono
runtime shutdown. So one way (only way?) to get the data is to call
`System.Environment.Exit` to end the XA app. Currently  there is
an issue with Java.Interop, where during the shutdown we get
an unhandled exception and thus the shutdown process doesn't
finish, which means the profile output is not written to the file.
Hopefully I can fix that soon.

[Tasks] Add aot to the list of valid profilers

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #1235
There seems to be a bug in msbuild [1] where if you create
an item inside a task and the task is skipped, the metadata
is not created for the item.
So we get into a situation where our `__AndroidLibraryProjects__.zip`
does not contain the correct LogicalName. As a result our
extraction process cannot find the resource, and builds fail.
This commit spits out the code that created the zip file into
its own target `_CreateManagedLibraryResourceArchive`. This means
we can skip this new target it needed. However the target
which creates the item `_AddLibraryProjectsEmbeddedResourceToProject`
can now run for every build. This will ensure that the metadata is
always created.
Also added a unit test.
[1] https://social.msdn.microsoft.com/Forums/netframework/en-US/259271d8-a3fc-4a9b-9e3a …

[Xamarin.Android.Build.Tasks] missing EmbeddedResource.LogicalName for __AndroidLibraryProjects__

---

Makefile
build-tools/scripts/BuildEverything.mk
build-tools/scripts/msbuild.mk
build-tools/scripts/runtime-helpers.mk

XA's Makefile exports the OS environment variable set to output of the `uname -s` 
command which returns the operating system's name. On macOS it will return
`Darwin`, on Linux `Linux` etc. MSBuild (the build system, not the command)
defines a standard property `$(OS)` which names the operating system kind -
`Windows_NT` on Windows and `Unix` on *nix systems.
Our project and target files (also a large set of them from e.g. Mono) use the
property to check whether they are running on Unix or Windows and they rely on
the property's value to be set correctly to make the right decisions.
MSBuild (the system) supports setting of properties from the command line but it
also takes their values from the process environment. However, it appears
there's a major difference between Mono's xbuild …

Fix build with msbuild on Linux

---

build-tools/api-merge/api-merge.cs

Depending on whether api-merge is invoked by xbuild or msbuild, the paths passed
to the app can be relative, full or mixed. However, the code assumes that
they're all equal and compares them to know when to stop processing the passed
sources.
Since the assumption is wrong and it breaks our builds, this patch makes sure
that all paths are normalized before they are compared.

Normalize paths passed to api-merge

---

build-tools/scripts/dependencies/debian-common.sh

The `sqlite3` command is used by build-tools/mono-runtimes/mono-runtimes.targets
during the build and is thus a hard dependency.

Add sqlite3 package to Debian/Ubuntu dependencies

---

build-tools/api-xml-adjuster/api-xml-adjuster.csproj

Part of the XA build process is download and installation of Android SDK, NDK as
well as creation of native compilation toolchains. However, it appears that at
some point we regressed and stopped performing those tasks and, thus, the builds
fail when adjusting API description files with api-xml-adjuster since at this
point no SDK, NDK or toolchains are found. The download and installation of
those components is handled by the android-toolchain project which is dependent
upon by several other projects in XA that require the SDK and the NDK to be
present. android-xml-adjuster needs them as well but it hasn't dependent on
android-toolchain until this commit which adds a reference to the toolchain
project and fixes the build.

Fix builds when there Android toolchain directory doesn't exist yet

---

Documentation/build_process.md
src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidBuildActions.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/AndroidItem.cs
src/Xamarin.Android.Build.Tasks/Utilities/Files.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Our components team currently have to go through a ton
of hoops to include .aar files in the build system.
Because we are not allowed to ship some of the google .aar
files with the Nuget packasges they need to be downloaded
on demand. To work within the current build system these
.aar files then need to be unpacked, restructured,
compressed and included in the Nuget assembly as an
EmbeddedResource. This requires updating the assembly
after it has been downloaded from nuget.
With the introduction of the `AndroidAarLibrary` build
action we can remove the rebuilding of the Nuget assembly
completely. The new system will still download the required
.aar files on demand. But instead of repacking them into
the .dll, the Nuget .targets file will simply add these
.aar files to the …

[Xamarin.Android.Build.Tasks] Add `AndroidAarLibrary` Build Action

---

Documentation/LayoutCodeBehind.md
src/Xamarin.Android.Build.Tasks/Tasks/CalculateLayoutCodeBehind.cs
src/Xamarin.Android.Build.Tasks/Tasks/GenerateLayoutCodeBehind.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

This commit is based on work done by @grendello. It adds support
for the generation of code behind for layout files. This will
make it easier for users to write code since they will no longer
need to use `FindViewbyId` manually. The generated code will
automatically provide properties for the various UI elements
in the layout file.
For example if you have a Button with an id of `@id/myButton` you
will see a property is available on your activity `myButton`. You
can then replace code like
var button = FindViewById<Button> (Resource.Id.myButton);
button.Click += delegate {
};
with
myButton.Click += delegate {
};
much nicer eh :).
There are a couple of caviats. The main one is your layout class
MUST be a `partial` class. So
public class MainActivity : Activity {
}
becomes
public partial …

[Xamarin.Android.Build.Tasks] Add Support for CodeBehind for layout files

---

build-tools/api-xml-adjuster/api-xml-adjuster.targets

Since 7d705bf, the Windows builds on VSTS have seemed to be failing. I
tested this locally, and noticed the use of command line arguments such
as:
-parameter-names='%(SomeVariable)'
Unfortunately, this isn't working on Windows due to the single quote. It
is more appropriately expressed as:
-parameter-names=&quot;%(SomeVariable)&quot;
This isn't very pretty, but it should work on all platforms.
I also fixed all the tabs I saw in this file--in favor of spaces, and
fixed other XML code conventions.
I will now return to my regularly scheduled baby duty.

[build] fix api-xml-adjuster.targets on Windows

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs

The [Ubuntu build][0] is [failing][1]:
warning : Failed to get the Java SDK version as it does not appear to contain a valid version number.
`javac -version` returned:
```openjdk version "1.8.0_03-Ubuntu"
OpenJDK Runtime Environment (build 1.8.0_03-Ubuntu-8u77-b03-3ubuntu3-b03)
OpenJDK 64-Bit Server VM (build 25.03-b03, mixed mode)
```
...
Task "AdjustJavacVersionArguments"
…/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets:
error : Error executing task AdjustJavacVersionArguments: Required property 'JdkVersion' not set.
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/779/
[1]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/779/consoleText
This was introduced/broken by commit 0e1d1c8a, …

[Xamarin.Android.Build.Tasks] Improve `javac -version` parsing

---

src/Xamarin.Android.Build.Tasks/Tasks/CalculateProjectDependencies.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/GetDependenciesTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/MockBuildEngine.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.Shared.projitems
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #1269
This commit adds the `GetAndroidDependencies` target to the
`Xamarin.Android.Common.targets`. Its purpose is to examine
the various settings in the project and report which android
sdk build-tools, platform-tools etc are required.
`GetAndroidDependencies` will output an @(AndroidDependency)
with Version metadata Valid component names are platform,
build-tool, platform-tool and tool.

[Xamarin.Android.Build.Tasks] Add GetAndroidDependencies Target

---

src/Xamarin.Android.Build.Tasks/Tasks/CalculateProjectDependencies.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/GetDependenciesTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

We should only list `ndk-bundle` in the AndroidDependencies if
the user is using Aot or MkBundle. Otherwise we will end up
downloading a ton of stuff we don't need.
This commit fixes the `CalculateProjectDependencies` to report
`ndk-bundle` if needed. It also adds a unit test to make sure
it is not included when it shouldn't be.

[Xamarin.Android.Build.Tasks] Only report `ndk-bundle` if required.

---

tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.csproj

This argument is required for the majority of 'AdbTarget' usage already, and should be passed as part of 'AdbTarget'.

[BCL-Tests] Remove '-s' from _GrantPermissions

---

build-tools/api-xml-adjuster/api-xml-adjuster.targets

Ideally, project rebuilds when nothing has changed should be *fast*.
`api-xml-adjuster` isn't:
$ time (cd build-tools/api-xml-adjuster ; xbuild)
real	2m1.084s
user	1m55.916s
sys	0m8.853s
$ time (cd build-tools/api-xml-adjuster ; xbuild)
real	2m0.824s
user	1m56.140s
sys	0m8.600s
A *minimum* two minute+ rebuild -- when *nothing* has changed -- is a
surefire way to get really annoyed.
With diagnostic logging, we start to see the culprit:
Target _ClassParse needs to be built as input file '@(ApiFileDefinition -> /Volumes/Seagate4TB/work/xamarin-android/build-tools/api-xml-adjuster/../../src/Mono.Android/Profiles/api-27.params.txt)' does not exist.
This in turn causes `class-parse.exe` and `api-xml-adjuster.exe` to be
*re-executed* on *every* `android.jar` on *every* build.
Fix this by …

[api-xml-adjuster] Fix rebuilds

---

src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/1296
Xamarin.Android attempts to expose the Java-based Android API as a
".NET feeling" API. This takes many forms, such as prefixing interface
names with `I`, mapping `get` and `set` methods to properties, mapping
listener interfaces to events, and PascalCasing method names.
This also affects Java package names and C# namespaces.
When creating the `.apk` file, we philosophically need to go the
opposite direction: PascalCased members need to be mapped to
"something appropriate" within Java. For example, many Android
Resource ids *must* be all lowercase, and Android doesn't support
package names starting with an uppercase letter in all circumstances.
At one point, we tried mapping C# PascalCased namespaces to camelCased
namespaces, so …

[Xamarin.Android.Build.Tasks] Fragments & Shorter acw-map

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

This is a bug in the `<GetAndroidDependencies/>` target. It does
not call `MonoAndroidHelper.RefreshSupportedVersions`. As a result
if called directly it will generate a Null Reference exception because
`MonoAndroidHelper.SupportedVersions` will be null.
So we should be dependent on `<_SetLatestTargetFrameworkVersion/>`.
This will initialize the `MonoAndroidHelper.SupportedVersions`. But
it will also resolve the correct `TargetFrameworkVersion` if the
user is using `AndroidUseLatestPlatformSdk`.

[Xamarin.Android.Build.Tasks] GetAndroidDependencies should call _SetLatestTargetFrameworkVersion

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Xamarin.Android.Windows.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #1286
We have a number of problems with our DesignTime build system. The
main one which this PR addresses is the designer file is deleted
by `IncrementalClean` AND `CoreClean`. This them completely messes
up the DesignTime system since it can no longer find the file.
So what we should be doing is making sure we don't tell the build
system about the designer file ;). We do this by not writing the
path to the `$(CleanFile)`.

[Xamarin.Android.Build.Tasks] Stop designtime designer being deleted.

---

.gitmodules

Context: 34f437d97d6d5f56d684af99449de49b870b32cc
Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/873/
The bump to mono/2017-12 in commit 34f437d9 included ABI "breakage" in
`System.Data.dll` which wasn't *actual* breakage.
Update xamarin-android-api-compatibility to so that we don't report
warnings for this "breakage."

Bump to xamarin-android-api-compatibility/d15-7/10df9b67

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets

There is a trivial difference between `msbuild` and `xbuild` - `msbuild`
seems to respect (or ignorant of) the fact that filenames that are different
in case are actually different on case-sensitive filesystem.
Thus with `msbuild`, our binding projects don't build due to "missing"
Microsoft.CSharp.Targets (there are only Microsoft.CSharp.targets even in
`xbuild` support files in mono).
This trivial fix should make it work.

[msbuild] Fix <Import>-ed filename, for case sensitivity.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ResolveSdksTaskTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj

This commit adds a basic unit test for ResolveSdks.

[Xamarin.Android.Build.Tests] Add test for ResolveSdks.

---

src/Xamarin.Android.Build.Tasks/Tasks/CalculateProjectDependencies.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/GetDependenciesTests.cs

The path separator for the android manifest change from
a `;` to a '/'. This commit updates the `CalculateProjectDependencies`
task to use the new format. It also updates the tests.
The current manifest [1] has been updated to [2]. It seems the general reasoning was to make the way the components are queried via the Sdk Manager and the MsBuild tasks consistent. It also makes the output of the `CalculateProjectDependencies` more `msbuild` friendly. 
The new manifest [2] now has a `filesystem-path` in addition to the `path`
`path="build-tools;27.0.3" filesystem-path="build-tools/27.0.3"`
Note that the `filesystem-path` includes `/` rather than `;`. Prior to this change the `InstallAndroidDependencies` needed to fix up the output of `CalculateProjectDependencies` to correctly query the SDK …

[Xamarin.Android.Build.Tasks] Update `CalculateProjectDependencies` to match new spec.

---

src/monodroid/jni/monodroid-glue.c

When the profiler output filename is not set, we set our own, which is
written in the `.__override__` directory. It is now set to
`profile.aot` for the `aot` profiler and `.mlpd` for the `log`
profiler.

[monodroid] Use .aot extension for default aot profiler output

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context https://bugzilla.xamarin.com/show_bug.cgi?id=5870
One of the issues with the current resource designer implementation
is that it is not in the intermediate directory. As a result it is
always causing problems for Source control systems.
Additionally normal .net apps create generated files in the
intermediate directory and make use of the a target and make use
of "build time code generation" [1] by making use of the Generator
metadata in MSBuild. Visual studio already has support for this
however VSForMac did not.
The issue with VSForMac is now being solved. With this commit
we will introduce a new target UpdateGeneratedFiles which can be
used by both VS and XS to generate the Resource.Designer.xx file
in the intermediate directory.
All of this is current protected by the …

[Xamarin.Android.Build.Tasks] Add support for Generated Resources via VSForMac

---

.gitmodules
tests/api-compatibility/api-compatibility.mk

Fixes: https://github.com/xamarin/xamarin-android/issues/1089
We found that xamarin-android-api-compatibility wasn't *actually*
performing the inter-API-level checks, meaning an important API
compatibility check wasn't being performed.
Bump to xamarin-android-api-compatibility/2c689ef2 so that
inter-API-level checks are properly performed.
Additionally, set `$(HTML_OUTPUT_DIR)` so that `mono-api-html` output
files are written into `bin/Build$(CONFIGURATION)/compatibility`.
This will (hopefully) allow us to use the Jenkins
**Publish HTML reports** Post-build Action to nicely display API
compatibility breakage, without requiring that we read the actual
build log output.

Bump to xamarin-android-api-compatibility/master/2c689ef2

---

src/Mono.Android/Android.App/UsesConfigurationAttribute.cs
src/Mono.Android/Android.App/UsesFeatureAttribute.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/ActivityAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/ApplicationAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/InstrumentationAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/UsesConfigurationAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Mono.Android/UsesFeatureAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
src/Xamarin.Android.NamingCustomAttributes/Android.App/ActivityAttribute.cs
src/Xamarin.Android.NamingCustomAttributes/Android.App/ApplicationAttribute.cs
src/Xamarin.Android.NamingCustomAttributes/Android.App/InstrumentationAttribute.cs

This should fix https://github.com/xamarin/xamarin-android/issues/1224.
Those attributes were based on build-tools/manifest-attribute-codegen.exe
(which is not really codegen yet, but lists up all the manifest attributes
that are found from Android SDK resources).
However not all the attributes were documented. For those undocumented
attributes, the issue https://github.com/xamarin/xamarin-android/issues/1336
was created to track.

[msbuild][Mono.Android] add a bunch of "missing" manifest attributes.

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in

Fixes #1287
One of the problems we have encountered is that the logic behind
how and when the design time build (DTB) is run is unclear. Specifically
what events/changes trigger a DTB. After lenghty conversations with
the Visual Studio team it seems that their prefered solution is to
use the `Generator` metadata.
The idea behind this is that an Item can include
<Generator>MSBuild:Target</Generator>
metadata which specify the MSBuild `Target` to run if that file
is modified. If these data is present Visual Studio will run the
target, which then modifies the required files which then triggers
an DTB update. Other ideas included adding a FileSystemWatcher to
the Visual Studio Addin to detect these changes and run targets.
That said the Generator metadata is built in and should work for
this …

[Xamarin.Android.Build.Tasks] Add Default Metadata for `@(AndroidResource)` Items.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.PCLSupport.targets

Context #1154 
This PR brings in changes from xamarin/xamarin-macios#2643 and xamarin/xamarin-macios#2731 to improve our net standard support. While it does not fix the packaging problem in #1154 it will give us parity with the iOS code base.

Better NetStandard Support

---

src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs

Fixes https://github.com/xamarin/xamarin-android/issues/1334
As per https://tools.ietf.org/html/rfc7231#section-6.4.1 the reponse isn't
required to contain the Location header and the client should act accordingly.
Since it is not documented what the action in this case should be, we're
following what Xamarin.iOS does and simply return the content of the request
as if it wasn't a redirect.

Don't throw exception on HTTP status 300 and no Location header

---

src/Xamarin.Android.Build.Tasks/Resources/proguard_xamarin.cfg

After XA stopped using Java.Interop built in XAIntegration
configuration, we need com.xamarin.java_interop.ManagedPeer to be
present in the mono.android.jar file, as managed ManagedPeer type
requires it.
Thus we need to preserve that class when using proguard.
Fixes https://github.com/xamarin/xamarin-android/issues/1331

[proguard] Preserve ManagedPeer class

---

tools/xabuild/SymbolicLink.cs
tools/xabuild/packages.config
tools/xabuild/xabuild.csproj

We would like to migrate to using `msbuild` to build everything on
Jenkins, instead of `xbuild`.
Before doing so, we updated the [xamarin-android-msbuild][0] job so
that it mirrored the [xamarin-android][1] job, updating it to build
and run unit tests. (Unit tests were previously skipped on the
`xamarin-android-msbuild` job because unit test execution takes
awhile, and behavior under MSBuild *should* be identical to that under
`xbuild`, so there wasn't a perceived need to spend time on them.)
It is at that point that [everything stopped working][2]:
/Users/builder/jenkins/workspace/xamarin-android-msbuild/tools/scripts/../../bin/Debug/bin/xabuild.exe.dll /p:Configuration=Debug /p:MonoDroidInstallDirectory=/Users/builder/jenkins/workspace/xamarin-android-msbuild/tools/scripts/../../bin/Debu …

[xabuild] Remove Mono.Posix use

---

Documentation/DevelopmentTips.md
Makefile

This commits adds the `ANDROID_API` makefile variable which, when set, will
build XA for the specified platform. It takes advantage of the variables found
in BuildEverything.mk by indexing the ALL_FRAMEWORKS variable with the API level
number and setting the msbuild properties accordingly.

Make it easier to build for an API platform other than default

---

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

What do we want? TLS 1.2+ support by default!
The question has been, how "best" to do that? See also: 908f56d6.
If you need TLS 1.2 support via `System.Net.Http.HttpClient`, *and* you
don't need TLS 1.2 support via `System.Net.WebClient`, *and* you
*only* run on Android 5.0 or later (API-21+), you can use
`Xamarin.Android.Net.AndroidClientHandler`.
That is, admittedly, a lot of "and"s. Pre-Android 4.4 devices make up
approximately 17% of devices [accessing the Google Play Store][0]
(as of 2018-Feb-28). `AndroidClientHandler` will *work* on those
devices, but it uses the underlying Android APIs to provide TLS
access, and Android itself didn't support TLS 1.2 until 5.0.
`AndroidClientHandler` can be enabled by building with
`$(AndroidHttpClientHandlerType)` set to …

[Xamarin.Android.Build.Tasks] Default to XA_TLS_PROVIDER=btls

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Analysis.targets

Visual Studio allows "project analysis rules" to be run against a
project, so that problems which shouldn't be build errors or warnigns
can still be reported to the developer.
In Visual Studio for Mac, the analysis rules can be executed via the
**Project** > **Run Code Analysis On *Project Name*** menu item.
However, when I do this in a project which should elicit an analysis
error, *nothing* is reported. :-/
The `xamarin-analysis` documentation states that the analysis rules
should emit errors into the `@(XamarinProjectAnalysisResult)`
item group.
We were inadvertently placing these into
`@(XamarinPackageAnalysisTargets)`, which is actually used to
determine which targets should be executed. As such, no errors are
actually displayed to the developer within the IDE.

[Xamarin.Android.Build.Tasks] Emit @(XamarinProjectAnalysisResult)

---

build-tools/scripts/BuildEverything.mk

Commit 2bd13c4a [broke the Linux build][0]:
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/817/
cp: will not overwrite just-created 'xamarin.android-oss_v8.3.99.20_Linux-x86_64_HEAD_2bd13c4/ThirdPartyNotices.txt' with 'bin/Release/lib/xamarin.android/ThirdPartyNotices.txt'
build-tools/scripts/BuildEverything.mk:165: recipe for target 'xamarin.android-oss_v8.3.99.20_Linux-x86_64_HEAD_2bd13c4.tar.bz2' failed
I don't care if the Debug or Release file is used; they should be
identical.
Replace `cp` with `cp -f` so that `make package-oss` doesn't fail.

[build] Use `cp -f` in `make package-oss`

---

build-tools/scripts/BuildEverything.mk

`make package-oss` fails on Linux with the following error:
if [ ! -f xamarin.android-oss_v8.3.99.23_Linux-x86_64_master_3f587f51/ThirdPartyNotices.txt ] ; then cp -f bin/*/lib/xamarin.android/ThirdPartyNotices.txt xamarin.android-oss_v8.3.99.23_Linux-x86_64_master_3f587f51 ; fi
cp: will not overwrite just-created 'xamarin.android-oss_v8.3.99.23_Linux-x86_64_master_3f587f51/ThirdPartyNotices.txt' with 'bin/Release/lib/xamarin.android/ThirdPartyNotices.txt'
which is due to some weird decisions GNU cp makes when copying files with the
same names from different source directories to the same destination. The fix is
to use `-a` (archive), however, it's not portable as macOS (BSD) version of cp
doesn't support it. Thus, this patch

Fix package creation on oss

---

build-tools/scripts/BuildEverything.mk

Sometimes a PR build will [fail][0]. That's to be expected! ;-)
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-pr-builder/2600/
However, sometimes the error message is [largely useless][1]:
[1]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-pr-builder/2600/testReport/junit/Xamarin.Android.Build.Tests.BuildTest/BuildAotApplicationAndBundle/Xamarin_Android_Build_Tests_BuildTest_BuildAotApplicationAndBundle__armeabi_v7a__False_True____Debug/
MESSAGE:
Build should have succeeded.
Expected: True
STACK TRACE:
at Xamarin.Android.Build.Tests.BuildTest.BuildAotApplicationAndBundle (System.String supportedAbis, System.Boolean enableLLVM, System.Boolean expectedResult)
That's not helpful at all.
In such circumstanes, the …

[build] Add `make package-test-errors` target

---

Makefile
build-tools/scripts/BuildEverything.mk

An unanticipated side-effect of commit 2bd13c4a was that
`make prepare` was downloading `bundle-v*.zip` for *both*
[Debug and Release][0] configurations, even on the PR builder (which
only builds Debug by default):
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-pr-builder/2610/console
Downloading `https://xamjenkinsartifact.azureedge.net/xamarin-android/xamarin-android/bin/Debug/bundle-v21-h86de098f-Debug-Darwin-libzip=1d8b1ac,llvm=bdb3a11,mono=607cbde.zip` to `/Users/builder/android-archives/.bundle-v21-h86de098f-Debug-Darwin-libzip=1d8b1ac,llvm=bdb3a11,mono=607cbde.zip.download`
...
Downloading `https://xamjenkinsartifact.azureedge.net/xamarin-android/xamarin-android/bin/Release/bundle-v21-h86de098f-Release-Darwin-libzip=1d8b1ac,llvm=bdb3a11,mono=607cbde.z …

[build] ThirdPartyNotices.txt and $(CONFIGURATIONS)

---

Documentation/guides/BuildProcess.md
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context #1361
This change will allow developers to override our defaults and pick stronger values if required.

[Xamarin.Android.Build.Tasks] Add Properties for the Debug Key

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Adding `@(AndroidAarLibrary)` to `@(AvailableItemName)` *should* have
been done as part of commit 6a8ea2bb, but was overlooked.
We want `@(AvailableItemName)` to be up-to-date so that you can have
conditional MSBuild behavior based on whether a particular item is
supported.
In particular, @Redth wants to ensure that the `@(AndroidAarLibrary)`
build action is available as part of his Components work, and ensuring
that `@(AvailableItemName)` contains `@(AndroidAarLibrary)` is the
most straightforward way to do so.
Additionally, sort and re-indent the `@(AvailableItemName)` entries.

[Xamarin.Android.Build.Tasks] Add @(AndroidAarLibrary)

---

src/Xamarin.Android.Build.Tasks/Properties/AssemblyInfo.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidResourceTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs

Our Resource Case converter `AndroidResource` did not handle
the `actionLayout` attribute for the `http://schemas.android.com/apk/res-auto`
namespace in menu xml files.
As a result the value for the `actionLayout` would not be
lowercased. This results in the following error
No resource found that matches the given name (at ‘actionLayout’ with value ‘@layout/ServingLayout’).
The fix is to add support for `actionLayout` to `AndroidResource`.
We also have added a unit test for this particular case and allowed
the `Xamarin.Android.Build.Tests` access to the internals of the
`Xamarin.Android.Build.Tasks` so it can unit test more of the
internal classes it has.

[Xamarin.Android.Build.Tasks] Fix an issue with `actionLayout`

---

src/Xamarin.Android.Build.Tasks/Tasks/ConvertResourcesCases.cs
src/Xamarin.Android.Build.Tasks/Tasks/CopyAndConvertResources.cs
src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs

DevDiv Issue 571365
We have a report that `ConvertResourcesCases` is failing with the follow
error.
error MSB4018: The "ConvertResourcesCases" task failed unexpectedly.
Android/Xamarin.Android.Common.targets(1334,2): error MSB4018: System.IO.FileNotFoundException: <some path>/design_layout_snackbar.xml.tmp does not exist
This is completely weird, especially as the Task is not called in
parallel. What I susepct is happening is VSForMac is running is
UpdateResources task at the same time the user is doing a build.
Because the name of the temp files we are just `foo.xml.tmp` it
is highly possible that one instance of the task is deleting the
file while the other instance is still running. This is difficult
to replicate.
This change uses
System.IO.Path.GetTempFileName ();
to generate a random …

[Xamarin.Android.Build.Tasks] The "ConvertResourcesCases" task failed unexpectedly.

---

Documentation/guides/LayoutCodeBehind.md
src/Mono.Android/Test/Mono.Android-Tests.csproj
src/Mono.Android/Test/Resources/layout/FragmentFixup.axml
src/Mono.Android/Test/Resources/layout/Main.axml
src/Mono.Android/Test/Xamarin.Android.RuntimeTests/MainActivity.cs
src/Xamarin.Android.Build.Tasks/Tasks/GenerateLayoutCodeBehind.cs

Fragment handling code partially taken from https://github.com/xamarin/xamarin-android/pull/1302/
Fragments are treated as normal widget, with the difference that they have to be
found using `FragmentManager.FindFragmentById` instead of the usual
`Activity.FindViewById` method.
Each generated class also gets a property named `Widget` which returns the
actual Android widget as found in the layout file. This allows us to keep
hierarchical nature of the XML code (thus handling nested widgets with duplicate
ids gracefully) while being able to access the parent widget itself.
The commit introduces a new attribute called `tools:managedType` which is used
to specify the element associated property's type. We cannot use `tools:class`
for this purpose since the layout root element already uses it …

Code-behind fragment and widget access fixes

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Xamarin.Android.Sdk.props

This is required to support the new "Visual Studio Build Tools" SKU (installs only build tools) where `devenv.isolation.ini` is not available (already confirmed this is intentional with the VS Setup team) and thus our build breaks. We are using InstallationID to support SxS at design-time so this isn't really needed in this case, it's safe to skip it.

Skip using InstallationID if it is not available

---

src/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/StartAndroidEmulator.cs

The Jenkins emulator-based tests are [hanging][0] -- again (see also
3294a50e) -- this time with new messages to `stderr`:
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/903/console
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
2018-03-08 11:26:32.097 qemu-system-i386[74190:5500464] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
PasteBoard: Error creating pasteboard: com.apple.pasteboard.clipboard [-4960]
2018-03-08 11:26:32.097 qemu-system-i386[74190:5500464] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, …

[tests] Check for " failed " emulator message

---

build-tools/create-vsix/create-vsix.targets
tools/xabuild/XABuild.cs

`xabuild.exe` execution involves the creation of symbolic links within
`bin/$(Configuration)/lib/xamarin.android/xbuild-frameworks`, pointing
into the `.NETFramework` and `.NETPortable` directories.
`build-tools/create-vsix` doesn't know anything about these symbolic
links, and *follows* them.
The result is that *if* you build with `xabuild.exe` then create a
`.vsix`, the resulting file will contain lots of "garbage":
$ make prepare all all-tests MSBUILD=msbuild
$ make create-vsix CONFIGURATIONS=Debug
$ unzip -l Xamarin.Android.Sdk-OSS*.vsix
...
135  03-08-2018 21:40   $ReferenceAssemblies/Microsoft/Framework/.NETFramework/v2.0/RedistList/FrameworkList.xml
...
22640  03-08-2018 21:40   $ReferenceAssemblies/Microsoft/Framework/.NETPortable/v4.0/Microsoft.CSharp.dll
...
All told, an extra …

[create-vsix] Don't package xabuild.exe symlinks

---

build-tools/scripts/BuildEverything.mk

`cp -f` (or `-af`) doesn't help on Linux when copying multiple files with
the same name to one target directory (as is the case here when building
both Debug and Release configurations). Using `cp -n` means the overwrite
is skipped, rather than fatal. macOS does not care about the overwrite
either way - passing `-n` to BSD `cp` is non-fatal, and fixes the build
failures on Linux.
```
directhex@flame:/tmp/dirtests$ mkdir a1
directhex@flame:/tmp/dirtests$ mkdir a2
directhex@flame:/tmp/dirtests$ touch a1/foo.txt a2/foo.txt
directhex@flame:/tmp/dirtests$ mkdir out
directhex@flame:/tmp/dirtests$ cp -af a*/*.txt out/
cp: will not overwrite just-created 'out/foo.txt' with 'a2/foo.txt'
directhex@flame:/tmp/dirtests$ cp -n a*/*.txt out/
directhex@flame:/tmp/dirtests$ 
```

Use `cp -n` during ThirdPartyNotices.txt copying.

---

build-tools/timing/timing.csproj
build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/ProcessLogcatTiming.cs
build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/ProcessPlotInput.cs

Adds timing.csproj and improves ProcessLogcatTiming task to ease
getting performance data of a XA app running on the emulator.
An example use:
```
msbuild /v:d build-tools/timing/timing.csproj /t:LogcatTiming /p:PID=7085
```
BTW, make sure the timing logging is enabled, before running the
app. It can be enabled by running:
```
adb shell setprop debug.mono.log timing
```

[build-tools] Process performance data from logcat

---

.gitmodules

Fixes https://github.com/mono/mono/issues/7472.
Commit list for mono/mono:
* mono/mono@145ca6391f8 [d15-6-2017-10] Only null check target for delegate if method is not static. (#7477)
* mono/mono@835a98d8559 Bump bockbuild to get curl error changes
* mono/mono@bbd88d02b2f Bump bockbuild for mono/bockbuild#62 (#7208)
* mono/mono@1eac626536b Pass TRUE for 'repeat' of send variants. This matches behavior of receive variants. Fixes blocking send call where Win32 returns WSAEWOULDBLOCK.
* mono/mono@33652b57ebb Bump bockbuild to get new gtk+ repo location
* mono/mono@3f39812cb9e [2017-10] [reference-assemblies] Fix public key for some newer v4.7.1 facades (#6864)
Diff: https://github.com/mono/mono/compare/da1e498884ddc56ac6ca82d3703096dc6370e1b2...145ca6391f80a71efc45530a989e33dacc9bfdf4

Bump mono to get fix for mono/mono#7472.

---

build-tools/create-vsix/create-vsix.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/1401
Commit 328286b7 had an unanticipated side-effect: the resulting
`.vsix` contained *no* `$ReferenceAssemblies` entries when running
`make create-vsix` with an xbuild-based build tree:
$ make prepare all # MSBUILD=msbuild NOT PROVIDED
$ make create-vsix CONFIGURATIONS=Debug
$ unzip -l bin/BuildDebug/Xamarin.Android.Sdk-OSS*.vsix
This is because when building only with `xbuild`,
`bin/$(Configuration)/lib/xamarin.android/xbuild-frameworks/.__sys_links.txt`
doesn't exist, and thus `@(_SymLinks)` is *empty*.
Consequently, the interpolation of
`$(LibDir)xbuild-frameworks\%(_SymLinks.Identity)\**\*.*` is
`$(LibDir)xbuild-frameworks\**\*.*`, which causes *all*
`@(ReferenceAssemblies)` entries to be removed.
Doh!
Fix this by making the …

[create-vsix] Don't exclude @(_Symlinks) when empty

---

Makefile
tools/scripts/xabuild

This is the common build failure, what we see after `make prepare` and `make`:
rm: cannot remove '/sources/monodroid/monodroid/external/xamarin-android/tools/scripts/../../bin/Debug/lib/xamarin.android/xbuild/Xamarin': Is a directory
This does not show up once you run `make` again, so it's a cosmetic problem.
But this should not happen. First-time contributors would get stuck at it
and may leave after seeing this. This should be fixed.

Ensure directory removal with rm `-rf`.

---

build-tools/mono-runtimes/mono-runtimes.props

Fixes: https://github.com/mono/mono/issues/6989
The AOT cross-compilers were being mis-`configure`d on Linux, as the
`configure --build` option wasn't actually specified, unlike macOS.
The result is executing the cross-compilers may result in an assert
failing:
[AOT] MONO_PATH="/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/obj/Release/android/assets" MONO_ENV_OPTIONS="" /mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Linux/cross-arm --aot=msym-dir=/mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/bin/TestDebug/temp/CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease/obj/Release/aot/armeabi-v7a,outfile=/mnt …

[mono-runtimes] Provide `configure --build` value for Linux

---

build-tools/ThirdPartyNotices/ThirdPartyNotices.csproj
build-tools/scripts/PrepareWindows.targets

Context: #464
Since the `ThirdPartyNotices.txt` functionality was implemented in
`Makefile`, this file was not getting generated on Windows. This commit
adds the same functionality to `PrepareWindows.targets`, which basically
just builds `ThirdPartyNotices.csproj` twice with different parameters.
The only workaround I had to add for Windows was to make the
`<ProjectReference />` for `xa-prep-tasks.csproj` condition on Windows.
Otherwise, I was getting into a file-locking issue where the nested
`<MSBuild />` task was trying to copy `xa-prep-tasks.dll` to the output
directory while it was in use.

 [build] Windows support for ThirdPartyNotices

---

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/ProcessLogcatTiming.cs

Add another regexp match for timing log start. So far I have been
using the logcat timing with logcat output from the emulator with API
version 21. Looks like the logcat format changed in newer Android
versions.
Here is an example of the relevant part of the logcat output on Pixel
2 device (API 27):
```
03-08 15:11:48.140  1128  4745 I ActivityManager: Start proc 18503:com.xamarin.xatemplateaot/u0a241 for activity com.xamarin.xatemplateaot/md58018c7d08c228c8e2a3e03723c59ca27.MainActivity
```
While on the emulator with API 21 we see:
```
03-07 20:53:48.816  1527  1869 I ActivityManager: Start proc com.xamarin.xatemplateaot for activity com.xamarin.xatemplateaot/md58018c7d08c228c8e2a3e03723c59ca27.MainActivity: pid=3080 uid=10057 gids={50057, 9997, 3003} abi=x86
```
The main difference here …

[build-tools] Improve logcat timing processing

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

If the `$(AdbTarget)` changes we currently do not invlaidate
the build. This can cause problems since we taylor the build
for the specific device which it attached. This happens for
FastDev builds.

[Xamarin.Android.Build.Tasks] Invalidate Build if $(AdbTarget) changes.

---

src/Mono.Android/Test/Android.App/ApplicationTest.cs
src/Mono.Android/Test/Mono.Android-Tests.csproj
src/Mono.Android/Test/Xamarin.Android.RuntimeTests/NUnitInstrumentation.cs
src/Mono.Android/Test/Xamarin.Android.RuntimeTests/TestInstrumentation.cs
tests/TestRunner.NUnit/NUnitTestRunner.cs

* Fixes #1191. The `Mcc` and `Mnc` values are now always present in ActivityInfo.ConfigChanges in Android 8.0+. The proposed fix is to ensure that `ConfigChanges` contains the `KeyboardHidden` flag , rather than requiring an exact match.
* Adds new instrumentation for new NUnit runner.
* Fixes possible NRE in new NUnit instrumentation/runner if test inclusion/exclusion data isn't provided.
Using the new NUnit runner is desirable as it is reliably producing test result xml files on device which can be pulled and published with ease. The previous runner had issues with certain devices when it came to providing the correct "on device" path to the test result xml. I've only marked the old instrumentation as obsolete (rather than deleting it) as I am not entirely familiar with how it is used …

[Mono.Android-Tests] Fix #1191, add new instrumentation class for new NUnit runner

---

Configuration.props
Documentation/building/configuration.md
build-tools/create-vsix/create-vsix.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/1267
The commercial Windows `Xamarin.Android.Sdk.*.vsix` file contains lots
of files that the macOS `xamarin.android*.pkg` file does not.
Update `build-tools/create-vsix` to remove some of the additional
files which are not necessary, including:
* `*.dylib`: macOS native libraries, not needed on Windows.
* `$MSBuild/Xamarin/Android/**/*.pdb`: Debug symbols.
* `$MSBuild/Xamarin/Android/lib/**/*.d.so`: Native libraries which
have not been `strip`d.
* `$ReferenceAssemblies/Microsoft/Framework/MonoAndroid/**/libZipSharp.*
`libZipSharp*` is only needed in `$MSBuild`.
* Distribute `Mono.Android.Export.*`, `OpenTK.*`, and `OpenTK-1.0.*`
for only *one* API level, not *every* API level.
`RedistList/FrameworkList.xml` ensures that previous …

[create-vsix] Remove unnecessary cruft

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

When building a MultiTarget netstandard project which includes
`monoandroidX.X` we get the following warning
System.ArgumentException: Specified resource directory was not found:
This is raised by the `ManagedResourceParser` because the
`$(MonoAndroidResourcePrefix)` does not exist. Its a netstandard
project so it won't have any (maybe).
This commit makes sure we only run the `GenerateResourceDesigner`
if that directory exists. This will stop the warning showing and
give us a clean Design Time build.

[Xamarin.Android.Build.Tasks] Fix Warning in Design Time Build.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets

Context #1091
The test `BindingBuildTest.JavaSourceJar` appears to pass under xbuild,
but fail under msbuild. This seems be true for macOS or Windows.
Under further inspection, I noticed the `BuildDocumentation` target was
never running under msbuild. It was being skipped due to the outputs
being up-to-date in comparison to the inputs. To fix the skipped target,
I was able to add an additional input in
`Xamarin.Android.Bindings.targets`.
The line:
```
<Copy
SourceFiles="@(IntermediateAssembly->'$(IntermediateOutputPath)%(filename).xml')"
DestinationFiles="@(IntermediateAssembly->'$(OutputPath)%(filename).xml')"
SkipUnchangedFiles="true" />
```
Implies that `@(IntermediateAssembly->'$(IntermediateOutputPath)%(filename).xml')`
also should be an input.
Additionally, there was some stuff in …

[msbuild] fix for JavaSourceJar and test

---

Documentation/guides/BuildProcess.md

Synchronize `BuildProcess.md` with changes made by the documentation
team at:
https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/building-apps/build-process.md
Update the documentation for the `$(AndroidHttpClientHandlerType)` and
`$(AndroidTlsProvider)` properties for clarity and commit edfa864b.

[docs] Synchronize and update BuildProcess.md

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1480184&tab=ms.vss-test-web.test-result-details&_a=summary
In the case of `Xamarin.Android.Build.Tests.BuildTest.ValidateUseLatestAndroid`,
there are points at which `UseLatestPlatformSdk` and `TargetFrameworkVersion`
are changed, but the `csproj` file is not re-saved on Windows.
So how does the test pass on macOS?
They pass on macOS due to `FileInfo.LastWriteTimeUtc` not containing
the millisecond information, which means files are likely to re-save
on macOS when not needed.
A simple fix for Windows, is to keep a reference to the last `csproj`
file contents. If the contents change, make the `Timestamp` of the
`csproj` null so it will always re-save.
After making this change, I was able to remove the following code from …

[tests] change to re-save project file if properties change

---

build-tools/libzip/libzip.targets
build-tools/mono-runtimes/mono-runtimes.targets
build-tools/unix-distribution-setup/unix-distribution-setup.csproj
build-tools/unix-distribution-setup/unix-distribution-setup.targets
src/System.Drawing.Primitives/System.Drawing.Primitives.targets
src/monodroid/monodroid.targets
src/netstandard/netstandard.targets
src/proguard/proguard.targets
src/sqlite-xamarin/sqlite-xamarin.targets

[Omnisharp-Roslyn](https://github.com/OmniSharp/omnisharp-roslyn/) uses an internal MSBuild loader which has a number of
demands/assumptions on the contents of .csproj+.targets files.
It assumes the following targets are present:
* Compile
* CoreCompile
It also assumes that the `TargetFrameworkMoniker` property is set.
This commit makes a number of changes to our non-managed projects to make sure
the above expectations are met. With those changes in place one can load
Xamarin.Android.sln into an editor that uses OmniSharp for .NET code completion
etc.

Fix loading of Xamarin.Android.sln for omnisharp-roslyn

---

src/Mono.Android/Test/Xamarin.Android.Net/AndroidClientHandlerTests.cs

This is a temporary step before we get our own server set up.

Use httpbin.org for AndroidClientHandler tests

---

src/Mono.Android/Test/Xamarin.Android.Net/AndroidClientHandlerTests.cs
src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/1282
When the original request uses the POST method and has a content payload, we
must discard the content when the server returns a redirection status as the
method changes to GET and the POST content cannot be used in this context.
This is not only the correct client behavior but it also prevents attempt to use
disposed content stream on the redirected request.

Discard POST content on request redirection

---

src/Xamarin.Android.Build.Tasks.tpnitems
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
src/Xamarin.Android.Build.Tasks/packages.config

Fixes: https://github.com/mono/mono/issues/7511
Fixes: https://github.com/xamarin/xamarin-android/issues/1438
Context: https://github.com/xamarin/xamarin-android/pull/1289
PR #1289 bumps xamarin-android to use the mono/2018-02 branch, and is
encountering an error when executing the
`Xamarin.Android.Build.Tests.AndroidUpdateResourcesTest.CheckResourceDesignerIsCreated()`
test, with the following error:
/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: error : Error executing task GenerateResourceDesigner: Could not load file or assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Error executing task …

[Xamarin.Android.Build.Tasks] Install FSharp.Core 4.3.1

---

Documentation/guides/BuildProcess.md
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #1415
Commonly Xamarin.Android apps on Windows require the `JavaMaximumHeapSize`
property to be set, in order to make it past the `CompileToDalvik`
MSBuild task that invokes `dx.jar`. Passing `java.exe` a value of
`-Xmx1G` mitigates the `java.lang.OutOfMemoryError`.
We have been getting reports of this happening for File->New Project
templates, so it seems to be time to default the value to `1G` if it
is not set.
Changes:
- Set `JavaMaximumHeapSize` in `Xamarin.Android.Common.targets` if unset
- Removed places `JavaMaximumHeapSize` was required to be set for
some unit tests to pass on Windows
- Update documentation
Concerns:
At one time, a default value for `JavaMaximumHeapSize` was attempted,
only to get reports of an error such as:
While trying to start a Java application with a …

[msbuild] default value for JavaMaximumHeapSize

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs
src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs
src/Xamarin.Android.Build.Tasks/Tasks/Crunch.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/578528
We are getting allot of reports of hangs in the aapt
task. While this might be down tot he aapt verson
itself, it did highlight a possible problem with our
implementation.
Firstly `Parallel.ForEach` is a BLOCKING call. So our
implementation in `Aapt.cs` and `Crunch.cs` was not
taking that into account. Also `Parellel.ForEach` will
use the current thread to run tasks. So if we run it
from the main MSBuild `Execute` method it will run
at least on of the items on that thread. Given one of
our goals was to not block the UI thread in VS this
might well cause a problem. Also the Local final action
in `Parallel.ForEach` is run for every task, not when all
have completed. As a result the `Complete` method was
being called many …

[Xamarin.Android.Build.Tasks] Rework Parallel.ForEach

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.PCLSupport.props
src/Xamarin.Android.Build.Tasks/Xamarin.Android.PCLSupport.targets

On a VS project which has an Android App referencing a NetStandard
library, making changes on the NetStandad library will not force a build
of either project. This change moves the redefinition of the task to
where it will not be hit when it shouldn't be. This can be easily tried
with https://github.com/Microsoft/SmartHotel360-mobile-desktop-apps.
Open the Android Solution and run, then change the Login.xaml and try
running again. Without this change, the deployed app will not be
affected. It works correctly with this change.

Fixed build on VS when using NetStandard libraries

---

build-tools/create-vsix/create-vsix.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/1454
Commit cdaa52b3 had a thinko: it updated `@(ReferenceAssemblies)` so
that e.g. `Mono.Android.Export.dll` and `OpenTK-1.0.dll` would only be
installed *once*, into `$(AndroidFirstFrameworkVersion)` -- instead of
having a copy in *each* framework version -- but
`%(ReferenceAssemblies.VSIXSubPath)` had the wrong value.
Consequently, the files were being installed into the wrong directory.
Fix `%(ReferenceAssemblies.VSIXSubPath)` so that instead of the
incorrect `Microsoft/Framework/$(AndroidFirstFrameworkVersion)/` it's
`Microsoft/Framework/MonoAndroid/$(AndroidFirstFrameworkVersion)/`.

[create-vsix] Properly install $(AndroidFirstFrameworkVersion)

---

src/Xamarin.Android.Build.Tasks.tpnitems
src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
src/Xamarin.Android.Build.Tasks/Utilities/NuGetLogger.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
src/Xamarin.Android.Build.Tasks/packages.config

Fixes #1154, #1162
Netstandard packages sometimes ship with both reference and
implementation assemblies. The Nuget build task `ResolveNuGetPackageAssets`
only resolves the `ref` version of the assemblies. There does
not seem to be away way to FORCE Nuget to resolve the lib one.
How .net Core manages to do this is still a mistery. That said
the Nuget `ResolveNuGetPackageAssets` does give us a hint as to
how to use the `project.assets.json` file to figure out what
`lib` version of the package we should be including.
This commit reworks `ResolveAssemblies` to attempt to map the
`ref` to a `lib` if we find a Referenece Assembly. Historically
we just issue a warning (which will probably be ignored), but
now we will use the `project.assets.json` file to find the
implementation version of the …

[Xamarin.Android.Build.Tasks] Better support for netstandard libraries.

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs

We got a bug report where Aapt crashes with the following
Unhandled Exception: System.ArgumentOutOfRangeException: capacity was less than the current size.
Parameter name: value
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
at System.Collections.Generic.List`1.set_Capacity(Int32 value)
at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
at System.Collections.Generic.List`1.Add(T item)
at Xamarin.Android.Tasks.Aapt.<>c__DisplayClass134_0.<RunAapt>b__0(Object sender, DataReceivedEventArgs e)
This looks like a problem were the StdOut and StdError message handlers
are being called a the same time. As a result they try to add and
item at the same time causing this problem when the collection tries
to grow.
So lets put …

[Xamarin.Android.Build.Tasks] Add Locking for processing aapt output.

---

build-tools/scripts/RunTests.targets

To get our desired behavior on VSTS, we have to:
- Make sure our call to NUnit returns a failing exit code
- Set the "Continue on Error" option in VSTS
- Add a step at the end of our build definition in VSTS to fail the
build if any issues ocurred
To make this work, we have to change our `<Exec />` task usage to
`ContinueOnError="ErrorAndContinue"`.
Example builds with a failing test can be found here:
- https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1502302&tab=ms.vss-test-web.test-result-details
- https://jenkins.mono-project.com/job/xamarin-android-pr-builder/2739/

[tests] support for running tests on VSTS

---

src/Xamarin.Android.Build.Tasks/Tasks/GetAdditionalResourcesFromAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetImportedLibraries.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/XDocumentExtensions.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

We had a report from @garuma that the `Resource.designer.cs` was not being updated correctly if the Nuget packages were not restored when opening the project. This is a user preference option apparently. This is due to when the Design Time Build (DTB) is run. The main DTB is run on project load. The `ManagedResourceParser` would then run on the available resources, which would NOT include those from the Nuget packages as they were not restored.
When the Nuget packages are finally restored the designer is not updated because none of the inputs changes. On a restore Nuget does not modify the csproj, or change any of the project build properties. As a result some of our targets a skipped. 
This commit adds the various .cache files we use to the inputs of `_UpdateAndroidResgen` and other …

[Xamarin.Android.Build.Tasks] DesignTimeBuild Improvements 

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs

Commit f7c942dd added support for replacing Reference
assemblies with runtime assemblies. However a member of
the Nuget team correctly pointed out that the Nuget does
not akways have the same name as the package its in...
So lets rework this code to do something else. We have the
full path to the reference assembly. We also have the Nuget
Project Model. This contains a list of the Paths for the
cache's being used. So we use that information to attempt to
figure out which package this reference came from. We can the
use the Nuget ProjectModel to look up the replacement runtime
assembly.
Again this should just skip over things if we can't find what
we want and issue the normal warning.

[Xamarin.Android.Build.Tasks] Rework how we resolve netstandard Nugets

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs

Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/585941
Commit 42a4b9be special-cased the `fakeLogOpen` messages to produce
warnings, instead of their earlier behavior of producing *errors*.
This was an improvement, in that builds were now able to finish, but
now developers are being "spammed" with lots of warnings about
`fakeLogOpen`, which cannot be easily ignored.
Further special-case the `fakeLogOpen` messages so that instead of
producing warnings, we instead produce "normal" messages.

[Xamarin.Android.Build.Tasks] `fakeLogOpen` is ignorable

---

build-tools/scripts/BuildEverything.mk
tests/api-compatibility/api-compatibility.mk

[xamarin-android build #915][0] reports various api-compatibility
failures, such as:
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/915/consoleText
<h1>### API BREAK BETWEEN v8.1 and v8.1.99</h1>
<div>
<h2>Namespace Android.Telephony</h2>
<div>
<h3>Type Changed: Android.Telephony.CellIdentityCdma</h3>
Modified base type: <span class='removed removed-inline removed-breaking-inline'>Java.Lang.Object</span> <span class='added '>Android.Telephony.CellIdentity</span>
We want to ignore these for now, as these changes are against an
*unstable* API level, and we don't want to have to ensure
intra-API-stability for unstable API levels. (In part becuase we
haven't enumified unstable API levels, because they're in flux.)
Update `$(STABLE_API_LEVELS)` so that it …

[api-compatibility] Only check stable API levels

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

The previous commit 029a8b49 fixed up some issues with resolving
the correct nuget. However on windows we get some weird pathing
issues because the project.assets.json file is using `/` as
path seperators. This is probably to be platform independent.
So in the project.assets.json we have a PackageName of
`System.IO.Packaging/4.4.0`
note the use of the `/`.
But our string comparision was using what ever path we had, on
windows that was `\`. 
`c:\pathtonuget\system.io.packaging\4.4.0\ref\netstandard1.3\System.IO.Packaging.dll`
So we never found the Library were we
looking for because `system.io.packaging/4.4.0` != `system.io.packaging\4.4.0`.
We just got lucky that it worked on Mac because the path separator is `/`.
We also need to normalize the resulting full path
to match the system path …

[Xamarin.Android.Build.Tasks] Fix an issue where the 'ref' nuget is not found on windows.

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs
src/Xamarin.Android.Build.Tasks/Tasks/Aot.cs
src/Xamarin.Android.Build.Tasks/Tasks/AsyncTask.cs
src/Xamarin.Android.Build.Tasks/Tasks/Crunch.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetAdditionalResourcesFromAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs

Some of our task continuations were not logging any
exceptions if they failed. This commit adds code to
ensure that if the task fails we get the log information
and stacktrace.

[Xamarin.Android.Build.Tasks] Add Logging if the task fails.

---

src/Mono.Android/Test/System.Net/SslTest.cs
src/Mono.Android/Test/Xamarin.Android.Net/AndroidClientHandlerTests.cs

A recent certificate expiration on the old 'xamdev' test servers caused a number of failures in existing tests. We have since stood up new test servers which can be used instead.
This is a version of #1476 for d15-7.

[Mono.Android-Tests] Use new internalx TLS test servers

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Xamarin.Android.Sdk.props

With this fix, `msbuild` will just work if xamarin-android is installed
to the same installation prefix directory as mono and msbuild, to the
right target framework path.
The fix is to NOT alter the TargetFrameworkRootPath location for
Windows-specific path.

[msbuild] Fix TargetFrameworkRootPath for non-Windows environment.

---

src/Mono.Android/Android.Runtime/JNINativeWrapper.cs

A LINQ expression was used for succinctness in the `CreateDelegate`
method.
It turns out that this method could get called alot in a Xamarin.Android
application, so it seems it could be worthwhile to port the LINQ code to
an equivalent for-loop.
This change should slightly decrease the number of allocations during
startup.

[Mono.Android] remove LINQ usage in Android.Runtime.JNINativeWrapper

---

build-tools/api-xml-adjuster/api-xml-adjuster.targets
src/libzip/libzip.targets
src/mono-runtimes/mono-runtimes.targets

Whenever `external/mono` is bumped, the
[`xamarin-android-msbuild` job breaks][0]:
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-msbuild/838/
Building target "_Make" completely.
...
Task "Touch" (TaskId:1642)
Task Parameter:
Files=
…/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/x64/libzip.dll
CMake=/Users/builder/android-toolchain/mxe-b9cbb53/bin/x86_64-w64-mingw32.static-cmake
CMakeFlags=
CopyToOutputDirectory=Always
OutputLibrary=x64/libzip.dll
OutputLibraryPath=lib/libzip.dll
…/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/libzip.dll
CMake=/Users/builder/android-toolchain/mxe-b9cbb53/bin/i686-w64-mingw32.static-cmake
CMakeFlags=
CopyToOutputDirectory=Always
OutputLibrary=libzip.dll
OutputLibraryPath=lib/libzip.dll (TaskId:1642)
Touching …

[libzip-windows] Fix building with `msbuild`

---

src/Xamarin.Android.Build.Tasks/Tasks/GetJavaPlatformJar.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs
tests/locales/LibraryResources/LibraryResources.csproj

Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/592736
Fixes: https://github.com/xamarin/xamarin-android/issues/1498
Context: 0780e274f1a301b709ba8eeb82ed83d6d77cfa7e
Context: https://github.com/xamarin/xamarin-android/pull/1439
What does it take to *use* a new (and unstable!) API level?
Commit 8942eca0 tried to lay some of this out, but *in principal* the
current process should be:
1. Bind the new API level.
2. Add a new `@(AndroidApiInfo)` entry for the new API level.
3. Specify the `$(TargetFrameworkVersion)` of the new API level when
building a project.
Commit 8ce25376 bound API-P as v8.1.99, finishing steps (1) and (2).
Therefore, step (3) should just work, right?
$ cd samples/HelloWorld
$ ../../bin/Debug/bin/xabuild /p:TargetFrameworkVersion=v8.1.99
Success!
Except, …

[Xamarin.Android.Build.Tasks] %(AndroidApiInfo.Stable)=False

---

build-tools/scripts/TestApks.targets
src/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunInstrumentationTests.cs
src/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunUITests.cs

Lately the BCL tests started to produce a lot of logcat output, way
over the 4M limit of the buffer.
Thus we need to get the logcat output after every apk test run.
I have considered to batch the `RunTestApks` target. That would not
work very well though, as we are already batching the tasks in this
target with two related different item groups. So I moved the
collection of the logcat output to the `RunInstrumentationTests` and
`RunUITests` tasks.

[plots] Get logcat output for timing in the tasks

---

src/Xamarin.Android.Build.Tasks/Linker/Mobile.Tuner/MobileProfile.cs
src/mono-runtimes/ProfileAssemblies.projitems

It was part of the 2017-12 mono bump from https://github.com/xamarin/xamarin-android/pull/1508

Add new System.Memory facade

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #1501 
If we have valid live cache files for the additional resources, the design time build should make use of them. However it should not create them since it would cause build problems for the live builds.

[Xamarin.Android.Build.Tasks] DesignTimeBuild should use live build cache's if they exist.

---

src/proguard/proguard.targets

You are generating such extraneous build log lines:
proguard:
[javac] proguard/ProGuard.java omitted as /sources/xamarin-android/external/proguard/classes/proguard/ProGuard.class is up to date.
[copy] No sources found.
[copy] No sources found.
[jar] proguard/ArgumentWordReader.class omitted as /sources/xamarin-android/external/proguard/lib/proguard.jar:proguard/ArgumentWordReader.class is up to date.
[jar] proguard/AssumeNoSideEffectsChecker.class omitted as /sources/xamarin-android/external/proguard/lib/proguard.jar:proguard/AssumeNoSideEffectsChecker.class is up to date.
[jar] proguard/ClassMemberChecker.class omitted as /sources/xamarin-android/external/proguard/lib/proguard.jar:proguard/ClassMemberChecker.class is up to date.
[jar] proguard/ClassPath.class omitted as …

Sanitize (eliminate) proguard build log outputs.

---

build-tools/xa-prep-tasks/xa-prep-tasks.targets

One of my biggest nightmares when developing for `xamarin-android` on
Windows, is noticing when I inadventently modified the hash for the
downloaded bundle, or check out a newer commit where the bundle is not
available yet. In cases where the bundle gets a 404, this is merely a
warning and the build continues on. This is a problem on Windows, since
it completely depends on the bundle download.
Depending on the state of your build tree, one of the following could
happen on Windows due to a failed bundle download:
- an `<Exec />` task fails, due to it trying to run `make`
- thousands of build errors on `Mono.Android.csproj` complaining about
missing `mscorlib` types
Explicitly failing the build on Windows, makes it a lot more clear what
is wrong. It also fails the build faster, freeing up …

[windows] fail the build if bundle download fails

---

src/Xamarin.Android.Build.Tasks/Tasks/ConvertResourcesCases.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

We currently call `ConvertResourcesCases` in three different places. [1], [2], [3]. For the most part they process the same files , over and over and over again. On a large project this is totally a waste of time. If the file has been processed once and not updated then we should not need to process it again.
So the only exception here is `GenerateJavaStubs`. The case here is this needs to be done AFTER we have compiled the app.. but we need to replace any instances of `Foo.MyClass` with `<md5hash>.MyClass` which is generated in the java code. So we do still need to process the resource files for the app after the main assembly has been built. 
That said if we know `UpdateAndroidResgen` has run, then we DONT need to run this again in `_CreateBaseApk`.
So this is an attempt to see if we …

[Xamarin.Android.Build.Tasks] Try to speed up ConvertResourcesCases

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs

Context: https://github.com/xamarin/xamarin-android/pull/1490
Since aee709d, the `ReportAaptErrorsInOriginalFileName` test has been
failing on Windows.
Looking into it, there really was a problem. The error message was
reporting the path as `\layout\main.xml`, which will not map back to
file within the user's project in an IDE.
It appears the change of the use of a `WorkingDirectory` caused the
following:
- `file` starts out as a full path such as
`C:\Users\myuser\Desktop\Git\xamarin-android\bin\TestDebug\temp\ErroneousResource\obj\Debug\res\layout\main.xml`
- `resourceDirectory` is a full path such as
`C:\Users\myuser\Desktop\Git\xamarin-android\bin\TestDebug\temp\ErroneousResource\obj\Debug\res`
- After the `Substring` the result is `\layout\main.xml`, so we need to
trim the leading `\` …

[Aapt] fix original file name in error message

---

src/Xamarin.Android.Build.Tasks/Tasks/GetAdditionalResourcesFromAssemblies.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597577
Commit aee709d made some changes which effect the working directory
if a task. Now it seems we now need to provide a full path for
the resource.cache file when we try to save it similar to what
we did for [1].
[1] https://github.com/xamarin/xamarin-android/commit/aee709d2ec98ddeb9a0cec9604e4fefa7321196e#diff-97e1ab3c8027acfecf85b8bb5a88dd9aR269

[Xamarin.Android.Build.Tasks] Fix issue with pathing to resource.cache

---

build-tools/api-xml-adjuster/api-xml-adjuster.targets

Commit e3abe4b8 broke caching of the
`bin/Build$(Configuration)/api/api-*.xml.*` files, reintroducing the
scenario that commit 5c46ee39 fixed. The result is that *minutes* may
be spent needlessly re-generating API XML.
The cause of the breakage is that `@(_ApiParameterDescription)`
(introduced in e3abe4b8) will contain entries that we don't care
about, e.g. API-4, for which no longer generate bindings. As such, the
`_ClassParse` target Inputs were looking for files which will never
exist, thus causing the `_ClassParse` target to always execute.
This *could* be fixed by making `@(_ApiParameterDescription)`/etc.
entries conditional on on the file
`%(_ApiParameterDescription.ParameterDescription)` refers to actually
existing, a'la:
<ItemGroup>
<_ApiParameterDescription …

[api-xml-adjuster] Don't needlessly rebuild XML

---

tests/locales/Xamarin.Android.Locale-Tests/Xamarin.Android.Locale-Tests.projitems

Looks like https://github.com/xamarin/xamarin-android/commit/c4e81655a
omitted the locale test and thus we didn't run it anymore.
Added `TestApkInstrumentation` item, so that the test is run again.

[tests] Run locale test again

---

src/Xamarin.Android.Build.Tasks/Tasks/GetAdditionalResourcesFromAssemblies.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597577
Commit aee709d made some changes which effect the working directory
if a task. Now it seems we now need to provide a full path for
the resource.cache file when we try to save it similar to what
we did for [1].
[1] https://github.com/xamarin/xamarin-android/commit/aee709d2ec98ddeb9a0cec9604e4fefa7321196e#diff-97e1ab3c8027acfecf85b8bb5a88dd9aR269

[Xamarin.Android.Build.Tasks] Fix issue with pathing to resource.cache (#1533)

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs

Fixes https://github.com/xamarin/xamarin-android/issues/1541
We missed one area in the changes where we worked around
the WorkingDirectory issues. We were not using the full path
to create the directory where the java R.java files are output.
As a result we ended up with the following error
```
Error        Access to the path 'obj\Debug\monoandroid81\android\src' is denied.
at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
at System.IO.Directory.CreateDirectory(String path)
at Xamarin.Android.Tasks.Aapt.GenerateCommandLineCommands(String ManifestFile, String …
```

[Xamarin.Android.Build.Tasks] Use full path to create designer output directory.

---

src/libzip/libzip.targets
src/mono-runtimes/mono-runtimes.targets
src/monodroid/monodroid.targets

Like e3abe4b8, but different: we had another `xbuild`-ism that
`msbuild` doesn't like: the "intermixing" of "strings" and item
metdata within *top-level* item groups.
For example:
<_MonoCrossRuntimeIntermediateOutput Include="$(IntermediateOutputPath)\%(_MonoCrossRuntime.Identity)\mono\mini\mono-sgen%(_MonoCrossRuntime.ExeSuffix)" />
The above uses item metadata, e.g. `%(_MonoCrossRuntime.Identity)`,
*outside* of a `@(_MonoCrossRuntime->'...')` context, at top-level
scope. The result is a [build break][0]
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-msbuild/857/
src/mono-runtimes/mono-runtimes.targets(818,5): error MSB3375:
The file "obj/Debug//%(_MonoCrossRuntime.Identity)/mono/mini/mono-sgen%(_MonoCrossRuntime.ExeSuffix)" does not exist.
Note that the …

[libzip, mono-runtimes, monodroid] Build with msbuild

---

src/Mono.Android/Java.Interop/TypeManager.cs
src/Mono.Android/java/mono/android/TypeManager.java

And use it from Java side in place of the old
`Java.Interop.TypeManager` and its `Activate` method. As it is based
on `JavaObject`, it will work nicely with the *jnimarshalmethod-gen*.

[Java.Interop] Add JavaTypeManager class based on JavaObject

---

tools/xabuild/SymbolicLink.cs
tools/xabuild/XABuild.cs

Context: d82c97c
Context: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1550431
For a while, my previous changes to `xabuild.exe` seemed to be working.
It still failed sometimes after reviewing past builds on VSTS:
- `RunXABuildInParallel` test failed randomly with non-zero exit code
when running `xabuild /version`
- Any test in `Xamarin.Android.Build.Tests`
The exception is something like:
Unhandled Exception: System.IO.IOException: The process cannot access the file 'bin\Debug\lib\xamarin.android\xbuild-frameworks\.__sys_links.txt' because it is being used by another process.
I think one more change might finally fix this. Before this change,
`xabuild.exe` was opening the `.__sys_links.txt` every time. It should
first check and see if the symbolic links already exist …

[xabuild.exe] another fix for multi-process file access

---

build-tools/bundle/bundle-path.targets
build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/SystemUnzip.cs
build-tools/xa-prep-tasks/xa-prep-tasks.targets

The intent here is to make it easier to fetch bcl-test artifacts for PR builds. QA's current bcl-test harness relies on the `_DownloadAndExtractBundle` target to download and extract the bcl-test
assemblies to the correct location. However, this falls apart when attempting to test a PR build as the mono bundle is not uploaded. One solution to this problem is to allow us to override the file "bundle" that is downloaded, as PR builds do upload a zipped up build output which contains the relevant test assemblies.
Now that the bundle download URI properties can be overridden, we quickly run in to max path length limitations when attempting to `SystemUnzip` the entirety of the XA build on Windows. A new property for a temporary bundle extraction location has been added to address this.
Example …

 [build-tools] Allow various bundle download and unzip properties to be overridden

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BuildHelper.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetXamarinProject.cs
tools/xabuild/XABuildPaths.cs

Context: https://github.com/xamarin/xamarin-android/issues/1532
In discussion around this issue, we realized the error message given by
the `<ResolveAssemblies />` MSBuild task is confusing for developers.
Currently users are getting:
Could not load assembly A. Perhaps it doesn't exist in the Mono for Android profile?
This message makes sense for `System.*` or framework assemblies.
We were thinking in some cases we could give an error such as:
Could not find assembly A, referenced by B. Please add a NuGet package or assembly reference for A, or remove the reference to B.
Additionally we should list an assembly "resolution path", so we can
easily figure out where the missing assembly came from.
In order to make this work:
- Keep a `List<string>` to store the name of each assembly
- Catch …

[Xamarin.Android.Build.Tasks] better ResolveAssemblies errors

---

tests/Xamarin.Forms-Performance-Integration/Droid/MainActivity.cs
tests/Xamarin.Forms-Performance-Integration/Droid/Xamarin.Forms.Performance.Integration.Droid.projitems

Looks like the hash in the `MainActivity` activity name is changing, so
give the activity an explicit name.
This fixes the performance measurements for XF test.

[tests] Use explicit Activity name in XF test

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #1519
The change to introduce `apksigner` had a slight flaw in its
signing logic. It only ever deleted `$(ApkFileSigned)` when
rebuilding the apk. So in the case where we are splitting the
apk by abi.. we didn't delete the other abi specific apks..
This commit fixes up the targets so that we correctly remove
the abi specific apks if they are being used when `$(AndroidUseApkSigner)`
is `true`.

[Xamarin.Android.Build.Tasks] Deploying to Android fails with zipalign error

---

build-tools/android-toolchain/android-toolchain-windows.targets
build-tools/android-toolchain/android-toolchain.csproj
build-tools/android-toolchain/android-toolchain.targets

Context fef4541
Since the `mono-sdks` took over the installation of `android-toolchain`,
these dependencies are now installed by `make` scripts. This
unfortunately, will not work on Windows since we allow builds with
a vanilla install of Visual Studio 2017 and a simple:
`msbuild Xamarin.Android.sln /t:Prepare` then `/t:Build`.
To fix this, I brought back the old MSBuild code in a
`android-toolchain-windows.targets` file to be used only on Windows. I
had to rearrange how things are imported a bit to get this to work
properly.
This should give us what we want:
- The `mono-sdks` install the Android toolchain on macOS/linux
- Windows still functions as it did before

[android-toolchain] support Windows again

---

Makefile
build-tools/scripts/PrepareWindows.targets
build-tools/scripts/XABuildPaths.cs.in
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj

The generated file contains paths to the top source directory, `xabuild`,
`xabuild.exe`, current `bin` directory, current test output directory and a
constant with the current configuration name. The paths can be useful in test
projects to find various bits and pieces which are currently referred to using
paths relative to a specific location and thus not really "portable" between
various test projects.

Generate source file with XA build paths

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1605061&tab=ms.vss-test-web.test-result-details&_a=summary
Noticed these are probably failing since 41bc8ff, but the build was
not working overall on Windows at the time--so we didn't catch it.
The `CheckSignApk` test had a couple issues:
- `C:\Users\myuser\Documents\android-toolchain\sdk` was being used as
the location of the Android SDK on Windows. `BaseTest` needed to use
`Environment.SpecialFolder.UserProfile` instead of `Personal`.
- `apksigner` is `apksigner.bat` instead of `apksigner.exe` on Windows

[tests] fix Windows test failures

---

Makefile

Commit e937f9b4 broke `make prepare` for the Release configuration.
Jenkins assumes that `make prepare` is a single invocation for *both*
Debug & Release builds; see e.g. `make prepare-external`:
$(foreach conf, $(CONFIGURATIONS), ...)
Commit e937f9b4 didn't abide by this requirement, and thus only
generated `XABuildPaths.cs` for the Debug configuration. As such, when
attempting to build in the Release configuration, [things broke][0]:
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/958/
CSC: error CS2001: Source file '…/xamarin-android/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/../../../../bin/TestRelease/XABuildPaths.cs' could not be found.
The fix is to update `make prepare-paths` so that it generates …

[build] Generate XABuildPaths.cs for all $(CONFIGURATIONS)

---

Documentation/guides/messages/apt0000.md
src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs
src/Xamarin.Android.Build.Tasks/Tasks/AsyncTask.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/MSBuildExtensions.cs

To get started in fixing #1560, some of our helper methods need updating
in order to completely support coded warnings in MSBuild tasks.
- `AsyncTask` needs "background-thread-safe" versions of `LogWarning`
that allow us to specify error codes. The `WaitForCompletion` method
also needed to call `LogCodedWarning` internally.
- Overloads of `LogError` and `LogWarning` that specify an error code
are renamed to `LogCodedError` and `LogCodedWarning`. This will help us
identify log messages that need error codes by searching for `LogError`
- `MSBuildExtensions` need proper method overloads for
`LogCodedWarning`, I copied what we have for `LogCodedError` so
`LogCodedWarning` will match it exactly
Changes to `<Aapt />`, as a guinea …

[Xamarin.Android.Build.Tasks] plumbing for coded warnings

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ResolveSdksTaskTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs

Context #1511
For most tests we already define an ApiInfo[] to contain
apis we want to test against. This commit cleans up the helper
methods to make use of the same ApiInfo[] arrays to create
the `android-{Id}` directories.
It also adds unit tests to conver the fix made for #1511.

[Xamarin.Android.Build.Test] Rework CreateFauxAndroidSdkDirectory to take ApiInfo[].

---

Documentation/building/unix-instructions.md
build-tools/api-xml-adjuster/Makefile
build-tools/debian-metadata/control
build-tools/scripts/RunTests.targets
build-tools/scripts/msbuild.mk
tools/scripts/xabuild

`xbuild` is "wonky" in all manner of ways -- for better or worse
(648aff99, e3abe4b8, 069c65ae).
Worse, our unit tests has a tendency to throw
`ArgumentOutOfRangeException` when running under `xbuild`, e.g. this
recent [`BuildAotApplicationAndBundle("armeabi",True,True)` error][0]
which produces a (temporary, Workspace-local) [log file][1] with:
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/955/testReport/Xamarin.Android.Build.Tests/BuildTest/BuildAotApplicationAndBundle__armeabi__True_True_/
[1]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/ws/xamarin-android/bin/TestRelease/temp/BuildAotApplicationAndBundle_armeabi_True_True/build.log
…/xamarin-android/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Comm …

[build] Use `msbuild` by default to build xamarin-android

---

build-tools/scripts/RunTests.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs

Previously if you ran the NUnit tests you would get nuget output such as:
```
Restoring NuGet package Xamarin.Android.Support.v7.Cardview.24.2.1.
Adding package 'Xamarin.Android.Support.v7.Cardview.24.2.1' to folder 'C:\Users\myuser\Desktop\Git\xamarin-android\bin\TestDebug\temp\packages'
Added package 'Xamarin.Android.Support.v7.Cardview.24.2.1' to folder 'C:\Users\myuser\Desktop\Git\xamarin-android\bin\TestDebug\temp\packages'
NuGet Config files used:
C:\Users\myuser\AppData\Roaming\NuGet\NuGet.Config
C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.Fallback.config
Feeds used:
C:\Users\myuser\.nuget\packages\
https://api.nuget.org/v3/index.json
C:\Users\myuser\Desktop\NuGet …
```

[tests] nuget output and test names go to output file

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks.csproj
build-tools/scripts/MSBuildReferences.projitems
build-tools/xa-prep-tasks/xa-prep-tasks.csproj
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
tools/xabuild/xabuild.csproj

Context: https://github.com/xamarin/xamarin-android/pull/1465
In grendel's PR, he added `Xamarin.ProjectTools` and a new test project
to `Xamarin.Android-Tests.sln`. The problem with this is that
`xabuild.exe` builds the test solution, and if there is a project
referencing `Microsoft.Build.Framework` it will use a *different*
`Microsoft.Build.Framework.dll` than if you built the projects with
plain `msbuild`.
An example of failing commands when `Xamarin.ProjectTools` is in
`Xamarin.Android-Tests.sln`:
```
make prepare all all-tests
make run-nunit-tests TEST=Xamarin.Android.Build.Tests.BuildTest.ValidateJavaVersion
```
Results with the exception:
```
System.MissingMethodException : void Xamarin.ProjectTools.Builder.set_Verbosity(Microsoft.Build.Framework.LoggerVerbosity)
at …
```

[build] standardize references to Microsoft.Build.*.dll

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

This has been a long standing issue that we never caught...
The `Output` on the `_LinkAssembliesNoShrink` target was
incorrect. It was using `$(MonoAndroidIntermediateDir)`
rather than `$(MonoAndroidIntermediateAssemblyDir)`.
As a result it was always looking for the output files in the
project root directory.. They never existed so the target
ALWAYS ran!.

[Xamarin.Android.Build.Tasks] Stop `_LinkAssembliesNoShrink` running all the time.

---

src/Xamarin.Android.Build.Tasks/Tasks/ConvertResourcesCases.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/GetDependenciesTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Commit a50e00bb broke the build in such that `_UpdateAndroidResgen`
always runs. This is because the resource file last modified date
was always newer than the `R.cs.flag`.
As a result of reading the fix to set the last write, this then broke `_GenerateAndroidResourceDir`. 
This is because the `build.props` ended up being newer than the resource files in `@(_AndroidResourceDest)` causing the target to run when it shouldn't. So we also introduce an `_AndroidResFlagFile` to control when we need to generate the resource directory in the `$(IntermediateOutputPath)`.
Unit tests have been updated to make sure these target do not run when they are no supposed to.

[Xamarin.Android.Build.Tasks] _UpdateAndroidResgen always runs.

---

src/Mono.Android/Android.App/Activity.cs
src/Mono.Android/Android.Views/View.cs
src/Mono.Android/Xamarin.Android.Design/ILayoutBindingClient.cs
src/Mono.Android/Xamarin.Android.Design/LayoutBinding.cs

Commit ab3773cf [broke the build][0]:
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/972/
Xamarin.Android.Design/ILayoutBindingClient.cs(15,79): error CS0246: The type or namespace name 'Fragment' could not be found (are you missing a using directive or an assembly reference?)
Xamarin.Android.Design/LayoutBinding.cs(35,77): error CS0246: The type or namespace name 'Fragment' could not be found (are you missing a using directive or an assembly reference?)
Android.App/Activity.cs(49,94): error CS0246: The type or namespace name 'Fragment' could not be found (are you missing a using directive or an assembly reference?)
Android.Views/View.cs(87,114): error CS0234: The type or namespace name 'Fragment' does not exist in the namespace 'Android.App' (are you …

[Mono.Android] Support building with API-10

---

src/Xamarin.Android.Build.Tasks/Tasks/GenerateLayoutBindings.cs

Commit ab3773cf added support for a new Binding system. It
broke on of our updated unit tests though. If a resource is
updated but not changed the resulting binding generator should
NOT produce an updated binding cs file. If it does the result
is the `CoreCompile` target ends up running and a whole host
of other targets then run as a result including `_LinkAssembliesNoShrink`.
What we should be doing is generating to a temp file and then
only update the binding if there has been a change.

[Xamarin.Android.Build.Tasks] Fix test broken by new Binding system

---

build-tools/scripts/Packaging.mk

The [xamarin-android-linux][0] job has long been broken, and I had
hoped that commit 3b904c20 would allow it to build once more.
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/
Commit 3b904c20 *does* appear to have improved matters; build times
went from ~1h to ~4h, so it was certainly building more. :-)
Unfortunately, the build [fails within `make package-oss`][1]:
[1]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/956/
if [ ! -f xamarin.android-oss_v8.3.99.151_Linux-x86_64_HEAD_3b904c2/ThirdPartyNotices.txt ] ; then \
cp -n  xamarin.android-oss_v8.3.99.151_Linux-x86_64_HEAD_3b904c2 ; \
fi
cp: missing destination file operand after 'xamarin.android-oss_v8.3.99.151_Linux-x86_64_HEAD_3b904c2'
Try 'cp --help' for more …

[build] Fix Linux `make package-oss`

---

build-tools/scripts/RunTests.targets
build-tools/scripts/TestApks.targets
tests/RunApkTests.targets

Context: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/2963/testReport/
A build for PR #1489 ran 1110 tests; it *should* have run over 35,000.
Where are the missing tests?
What's missing are the `.apk` on-device tests; BCL tests make up
*most* of our expected test count.
Analysis of the build log shows that the on-device tests *are*
running, with test results being downloaded:
…/android-toolchain/sdk/platform-tools/adb -s emulator-5570  pull "/data/data/Xamarin.Android.Bcl_Tests/files/.__override__/TestResults.xUnit.xml" "…/xamarin-android/tests/../bin/TestDebug/TestResult-Xamarin.Android.Bcl_Tests.xunit.xml"
...
/data/data/Xamarin.Android.Bcl_Tests/files/.__override__/TestResults.xUnit.xml: 1 file pulled. 53.5 MB/s (3273412 bytes in 0.058s)
but those results don't …

[tests] Report errors last in `RunApkTests` (Take 2!)

---

src/Xamarin.Android.Build.Tasks/Tasks/FindLayoutsToBind.cs

Since ab3773cf, `Xamarin.Android-Tests.sln` hasn't been building on
Windows, with the following errors:
"Mono.Android-Tests.csproj" (default target) (2) ->
Xamarin.Android.RuntimeTests\MainActivity.cs(19,4): error CS0103: The name 'first_text_view' does not exist in the current context
Xamarin.Android.RuntimeTests\MainActivity.cs(23,4): error CS0103: The name 'second_text_view' does not exist in the current context
Xamarin.Android.RuntimeTests\MainActivity.cs(27,4): error CS0103: The name 'my_scroll_view' does not exist in the current context
Xamarin.Android.RuntimeTests\MainActivity.cs(29,4): error CS0103: The name 'first_text_view' does not exist in the current context
Xamarin.Android.RuntimeTests\MainActivity.cs(33,4): error CS0103: The name 'second_text_view' does not exist in the …

[codebehind] fix for FindLayoutsToBind on Windows

---

tests/BCL-Tests/Xamarin.Android.Bcl-Tests/XUnitInstrumentation.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/1400
Related: https://github.com/xamarin/xamarin-android/pull/1421
The mono/corefx xUnit test
[`TaskSchedulerTests.GetTaskSchedulersForDebugger_ReturnsDefaultScheduler()`][0]
[fails when built in Release mode][1]:
[0]: https://github.com/dotnet/corefx/blob/893708a4c46047af6fb14bc0f2c33b3ca6adc527/src/System.Threading.Tasks/tests/TaskScheduler/TaskSchedulerTests.cs#L293-L301
[1]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/980/testReport/junit/Test%20collection%20for%20System.Threading.Tasks.Tests/TaskSchedulerTests/System_Threading_Tasks_Tests_TaskSchedulerTests_GetTaskSchedulersForDebugger_ReturnsDefaultScheduler___Release/
System.NullReferenceException : Object reference not set to an instance of an …

[tests] Ignore XUnit `nonuapaottests` category

---

build-tools/scripts/Packaging.mk

Commit 7f56c949 attempted to fix `make package-oss` on Linux, noting:
> In the absense of actually understanding what's wrong and fixing the
> real problem, instead print out some debug spew if the `cp` operation
> *would* fail -- because `$(firstword $(wildcard ...))` returns "" --
> and fallback to an attempted "hardcoded" `cp` operation.
We now have a plausible explanation which matches the facts on hand:
[`$(wildcard)` should be used with care][wildcard], because it's
behavior is dependant upon filesystem caching done by **make**.
[wildcard]: https://www.cmcrossroads.com/article/trouble-wildcard
> The unexpected, and apparently inconsistent, results above are
> because GNU Make contains its own cache of directory entries.
> `$(wildcard)` reads from that cache (and not directly from …

[build] Avoid using `$(wildcard) on generated files

---

Documentation/guides/messages/xa0105.md
src/Xamarin.Android.Build.Tasks/Tasks/CheckTargetFrameworks.cs

As part of our Error/Warning clean up we are changing
`CheckTargetFrameworks` to use LogCodedWarning and adding
docs for `XA0105`.

[Xamarin.Android.Build.Tasks] Fix CheckTargetFrameworks to use LogCodedWarning

---

Documentation/guides/messages/xa0109.md
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

The `<Warning/>` which was being raised if the user used a
`$(TargetFrameworkVersion)` of `v4.5` did not have a code.
This adds a code and a document for it.

[Xamarin.Android.Build.Tasks] Add Coded Error for TargetFramework v4.5

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/ProcessMSBuildTiming.cs
build-tools/timing/timing.targets

Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/plot/Build%20times/
The first issue with the new plots is I am storing `TimeSpan` data in
the CSV file. The Jenkins plugin for plots, doesn't seem to be able to
render this. I have converted the data to milliseconds instead.
The second issue is all of the `Install` targets for
`HelloWorld.csproj` are getting `[INSTALL_FAILED_NO_MATCHING_ABIS]`.
The fix for this is to pass `/p:AndroidSupportedAbis=x86` for each
build.

[build] fixes for MSBuild project timing

---

build-tools/scripts/RunTests.targets

The [xamarin-android Jenkins job][0] isn't green, but it's not because
of any failing unit tests; 81ef825a fixed the last known unit test
failure.
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/
This leaves us wondering: what's broken *now*?
Fortunately we have logs, e.g. [build #987][1]:
[1]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/987/
Resources/drawable/android_button.xml(4): error APT0000: No resource found that matches the given name (at 'drawable' with value '@drawable/AndroidPressed'). […/xamarin-android/src/Mono.Android/Test/Mono.Android-Tests.csproj]
Resources/drawable/android_button.xml(4): error APT0000: No resource found that matches the given name (at 'drawable' with value '@drawable/AndroidPressed'). …

[tests] Enable diagnostic logging for `make V=1`

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ResolveSdksTaskTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

@directhex notes:
> Jdk and jre aren't the same thing.
> If jre (java) is 8 but Jdk (javac) is 9, javac throws exit 2
> Yes I know it's an edge case
> But we should check both java and javac version for XA0030
Update `<ResolveSdks/>` to validate versions from *both*
`java -version` *and* `javac -version`, to ensure that we don't
inadvertently use JDK 9 tooling (see also 9c9e5e53).

[Xamarin.Android.Build.Tasks] Check `javac -version`

---

src/Xamarin.Android.Build.Tasks/Tasks/GenerateLayoutBindings.CSharpBindingGenerator.cs

When the application with generated code-behind bindings is built in the Release
configuration with binding enabled (the default), the binding classes might be
linked out as they are instantiated using `Activator.CreateInstance` and not
directly. Prevent this from happening by decorating the binding constructor with
the `[Preserve]` custom attribute which tells the linker to keep the method in
the application.

[CodeBehind] Make sure the generated binding is not linked out

---

src/mono-runtimes/mono-runtimes.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/1652
Xamarin.Android doesn't ship `Mono.Cecil.dll`, as it is not fully
API-stable, and there have been historical problems when multiple
different versions of `Mono.Cecil.dll` were being used within the same
process at the same time.
Our solution to this was to "vendorize" `Mono.Cecil` into
`Xamarin.Android.Cecil.dll`, and update any utilities which reference
`Mono.Cecil.dll` to instead reference `Xamarin.Android.Cecil.dll` by
using `remap-assembly-ref.exe`; see also e814528c.
Unfortunately we overlooked some utilities.
Update `mono-runtimes.targets` so that `illinkanalyzer.exe`,
`mono-symbolicate.exe`, and `mkbundle.exe` have any assembly
references to `Mono.Cecil` remap'd to target `Xamarin.Android.Cecil`.

[mono-runtime] Remap Mono.Cecil for utilities

---

src/Xamarin.Android.Build.Tasks/Tasks/CopyIfChanged.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

For a long time it seems we have not been correctly updating the
`$(Intermediate)res` in the `_GenerateAndroidResourcesDir` target.
This has recently come to light with our switch over to msbuild
as our main way to compile (rather than xbuild).
For Target `Inputs` and `Outputs` msbuild only checks the timestamps
of files to decide if they have changed. However the Copy task checks
both the timestamps AND the contents. It seems to do this even if
the timestamps are the same or the destination file is newer. 
If the contents change the file is copied.
This causes us a problem, since we fixup the destination files
by changing the cases of Resources. Also we replace references to
managed class names with the md5 hashes Java class. As a result if
we run the `_GenerateAndroidResourcesDir` for …

[Xamarin.Android.Build.Tasks] Intelligently update the `$(Intermediate)res` directory.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileExpected.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs

The `ManagedResourceParser` was not taking into account the fact
that the app should be using `const` not `static` for the
resource fields.

[Xamarin.Android.Build.Tasks] Designer items should be const for apps.

---

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs

There was still a use of `LogWarning` in `BuildApk`. This was
an `XA0107` warning to do with reference assemblies. It should
be using the same code as the earlier `LogCodedWarning`

[Xamarin.Android.Build.Tasks] Fix up `BuildApk` task LogWarning.

---

Xamarin.Android.sln
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Extensions.cs
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj

Let linker preserve the jni marshal methods and also update the
registration methods we generate with `jnimarshalmethod-gen`.
We want the linker to preserve only jni marshal methods for methods
which are not linked away. Thus we also need to update the
`__<$>_jni_marshal_methods::__RegisterNativeMembers` method to only
register the remaining methods.
For example in our XA template application, the number of registered
methods for `Android.App.Activity` class goes down to 31 from 241.
This commit still keeps the `Get*Handler` methods in the linked
assembly. Once we have the marshal methods for all the code, we can
remove these easily in `DoAdditionalMethodProcessing` by returning
early, before `PreserveRegisteredMethod` is called or even remove that
call.

[linker] Update linker to be aware of jni marshal methods

---

src/Mono.Android/Test/Mono.Android-Tests.csproj
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
tests/CodeBehind/BuildTests/CodeBehindBuildTests.csproj

Context: https://github.com/xamarin/xamarin-android/issues/1669
The layout bindings and associated Code-Behind (ab3773cf)
infrastructure is breaking existing projects, e.g. the
[Cheesesquare sample][0] [fails to build][1] with:
[0]: http://github.com/xamarin/monodroid-samples/tree/master/android5.0/Cheesesquare
[1]: https://github.com/xamarin/xamarin-android/issues/1669#issuecomment-388163599
error CS0234: The type or namespace name 'Android' does not exist in the namespace 'Cheesesquare'
This is apparently happening because the wrong namespace is used for
the generated `Resource` type, with generated code containing:
public TextView Text1 => FindView (global::Cheesesquare.Android.Resource.Id.Text1, ref __Text1);
There is no `Cheesesquare.Android.Resource` type; the generated …

[Xamarin.Android.Build.Tasks] Disable layout bindings

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.DefaultOutputPaths.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidProject.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.CSharp.targets

We only can do this when AndroidUseLatestPlatformSdk is false due to the
need of evaluating the MsBuild properties before calculating the latest SDK
using the _SetLatestTargetFrameworkVersion target (Xamarin.Android.Common.targets)
XA heavily leverages generated files in the intermediate output directory to achieve incremental build,
which is key since a lot of the Android/Java SDK tools are slow.
In XA, targeting different API levels is done by changing the TargetFramework property in the project.
This effectively invalidates all previous intermediate artifacts. Since this is not an uncommon
action (i.e. user is trying out various target API levels to see which one works best for their needs),
we'd like to preserve whatever artifacts were generated in a previous run for a given …

Appending target framework to the OutputPath/IntermediateOutputPath

---

tools/xabuild/XABuildPaths.cs

When looking at my Mono 5.12 installation, I noticed a few files we
should be using with `xabuild.exe`:
- `/Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/NuGet.targets`
- `/Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks` directory
`NuGet.targets` is needed for `XABuildPaths.NuGetRestoreTargets`, and
the `Sdks` directory can be used for `MSBuildSdksPath`.
Both of these values can still fall back to .NET Core, if they are not
found.
After these changes, it more closely matches the Windows code. We
should be able to build a wider range of .NET standard projects with
`xabuild.exe` now on macOS.

[xabuild.exe] fixes for paths/settings on macOS

---

src/OpenTK-1.0/OpenTK.csproj

Commit 13d216fd [broke the build][0], within the `make opentk-jcw`
build target:
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1003/
$ msbuild /p:Configuration=Debug /p:AndroidApiLevel=15 /p:AndroidPlatformId=15 /p:AndroidFrameworkVersion=v4.0.3 /t:GenerateJavaCallableWrappers /v:diag src/OpenTK-1.0/OpenTK.csproj
...
Target "GenerateJavaCallableWrappers: (TargetId:2)" in file "…/xamarin-android/build-tools/scripts/JavaCallableWrappers.targets" from project "…/xamarin-android/src/OpenTK-1.0/OpenTK.csproj" (entry point):
Building target "GenerateJavaCallableWrappers" completely.
Input file "…/xamarin-android/src/OpenTK-1.0/obj/Debug/MonoAndroid403/OpenTK-1.0.dll" does not exist.
...
mono --debug=casts …

[OpenTK-1.0] Disable per-TFN IntermediateOutputPath

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs

There are build failures on the monodroid where we are
trying to open the `UnSigned` file when it no longer
exists.
Xamarin.Tools.Zip.ZipIOException : <file> does not exist and file creation was not requested
This is since our switch to `apksigner`.

[Xamarin.Android.Build.Tests] Lets check the Signed apks.

---

build-tools/debian-metadata/control
build-tools/debian-metadata/rules

Instead of needing to guess dependencies and hand-encode them, this uses the automatic dependency generator (with a big pile of excludes)

[linux] Accurate dependency tracking for package

---

build-tools/scripts/RunTests.targets
src/Xamarin.Android.Build.Tasks/Tasks/MakeBundleNativeCodeExternal.cs
src/monodroid/jni/monodroid-glue.c

Fixes: https://github.com/xamarin/xamarin-android/issues/1651
Recent update to mono brought in changes in the code generated by `mkbundle`
when dealing with AOT. Unfortunately, the changes require the bundle to be able
to find the `mono_jit_set_aot_mode` runtime function which isn't exported in the
Xamarin.Android up and thus the loading of the bundle crashes on startup with
the following message:
dlopen failed: cannot locate symbol "mono_jit_set_aot_mode" referenced by libmonodroid_bundle_app.so
To fix this we need to augment the bundle's `mono_mkbundle_init` function in
generated code to take a third parameter - pointer to the abovementioned
function. With the current code this requires a set of rather ugly changes, as
seen in this commit, but it makes the application not crash on start …

Fix bundled app crash on startup

---

src/monodroid/jni/dylib-mono.c
src/monodroid/jni/dylib-mono.h
src/monodroid/monodroid.props
src/monodroid/monodroid.targets

Also add `MonoThread` and `mono_thread_current` to *dylib*.
Fixed `monodroid_mono_class_get_field_from_name_fptr` signature, where
we were missing *const* for 2nd argument.
Used relevant types in the `monodroid_mono_class_from_mono_type_fptr`
signature.

[monodroid] Add libjava-interop sources to runtime sources

---

src/Xamarin.Android.Build.Tasks/ILRepack.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
src/Xamarin.Android.Build.Tasks/packages.config

`ResolveAssemblies` is throwing the following error on
a newer mono (2018-04).
error : Could not load file or assembly 'NuGet.ProjectModel, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
This is because we took a dependency on NuGet.ProjectModel 4.6 and
the newer mono has 4.7. This results in the error above.
Now we cannot always be sure which version of the NuGet assemblies
will be installed since users are able to upgrade mono independently.
So this PR will use the `ILRepack` NuGet to package up the dependencies
we need so that `Xamarin.Android.Build.Tasks` contains all the
correct assemblies it needs.

[Xamarin.Android.Build.Tasks] ILRepack the NuGet.* Tasks Dependencies.

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.CSharp.targets

xbuild is not being compatible with the property evaluations
we're doing in the .targets => so we're only offering the output
paths improvements to the users that are using MsBuild.
It also prevents that CI builds don't fail because of this change.
And also adding the ability to disable it by setting the
EnableDefaultOutputPaths property to false.

Enabled DefaultOutputPaths targets for msbuild only

---

src/Xamarin.Android.Build.Tasks/ILRepack.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj

When building via monodroid we get a build error
Error initializing task ILRepack: System.IO.FileNotFoundException:
File name: '[path]/monodroid/external/xamarin-android/src/Xamarin.Android.Build.Tasks/ILRepack.Lib.MSBuild.Task.dll'
which it really really weird because the .targets in the NuGet is using
$(MSBuildThisFileDirectory)ILRepack.Lib.MSBuild.Task.dll
and that is somehow resolving to a path outside of the the `packages`
folder....
So lets load the assembly in the `ILRepack.targets` manually
from the location we know it will be.

[Xamarin.Android.Build.Tasks] Failed to load ILRepack.Lib.MSBuild.Task.dll

---

src/Xamarin.Android.Build.Tasks/Tasks/LinkAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ResolveSdksTaskTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

When taking an audit of our build times, I was testing the following
scenario:
- `msbuild Droid.csproj /t:Install /bl:first.binlog`
- `msbuild Droid.csproj /t:Install /bl:second.binlog`
In theory, the "second" build should be very fast and basically not do
anything. Unfortunately that was not the case.
In my example, I saw build logs such as:
Target _LinkAssembliesNoShrink
Building target "_LinkAssembliesNoShrink" partially, because some output files are out of date with respect to their input files.
[ResolvedUserAssemblies: Input=C:\Users\myuser\.nuget\packages\xamarin.forms\3.0.0.482510\lib\MonoAndroid10\FormsViewGroup.dll, Output=obj\Debug\android\assets\FormsViewGroup.dll] Input file is newer than output file.
[ResolvedUserAssemblies: …

[Xamarin.Android.Build.Tasks] fix timestamps in various intermediate folders

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs

The `ResolveNativeLibrariesInManagedReferences` test fails when run
in Debug mode when we are using the `_BuildApkForFastDev`. This is
because the updated `libfoo.so` is not being updated in the apk.
Now this is probably a bug in the system. This is because the native
libraries are embedded into the apk even in fast dev. However to we
do not update the apk in fast dev mode if an assembly changes. This
is because we don't want to rebuild the apk every time a bit of
code is changed.
So this behaviour needs to be redone. This is will be handled
in the new instant run support in PR #609. This new system will
fast deploy native libraries to the device.
So for now so we can get a xamarin-adroid bump in monodroid we
should restrict this test to Release only.

[Xamarin.Android.Build.Tasks] Run `ResolveNativeLibrariesInManagedReferences` Test in Release

---

build-tools/android-toolchain/android-toolchain.targets

Mono SDK build currently checks for presence of Xcode when building on macOS.
However, Xcode isn't required to build neither Mono (for desktop or Android) nor
Xamarin.Android itself. This commit drops the dependency when building the
Android toolchains. The only build requirement, as far as tools are concerned,
on macOS are the command line tools from Apple.

[macOS] Drop requirement for Xcode when building Mono runtime

---

Xamarin.Android.sln

(You should not use MSBuild solution format unless everything can be
handled from within the IDEs or you understand what you are editing.)
Those ProjectTypeGuids were wrong; whoever made changes to the guids
should also fix Xamarin.Android.sln otherwise IDEs will fix them next
time someone with sanity makes changes on the file from IDEs and they
result in messy extraneous changes (and whoever used IDEs should not be
blamed; it is whoever didn't make required changes to blame).
Next, Java.Interop.Export was not appropriately added to configuration
mappings and therefore it was not built as part of dependencies when
it was built on the IDEs. `msbuild.exe` may build that but that's only
because build configuration is not taken into consideration.
This would not have happened if we have used …

Fix build config mappings and project type guids.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs

Our wrench build if timing out because its not getting
any console output from Nunit. This is because Nunit
is buffering the output.
So lets Flush the Output so we get decent progress messages.

[Xamarin.Android.Build.Tests] Flush our test output.

---

src/monodroid/monodroid.targets

Make sure the `Java.Interop.dll` has `java_interop_jnienv_get_java_vm`
function available, through the *DllMap* in the config file. The function is called from [JniEnvironment.cs](https://github.com/xamarin/java.interop/blob/master/src/Java.Interop/Java.Interop/JniEnvironment.cs#L168).
This code path is reached during `jnimarshalmethod-gen.exe` run.

[monodroid] Add Java.Interop.dll.config for host JI assembly

---

src/mono-runtimes/mono-runtimes.targets

A follow up to 9178d614ae881862623ca07b71c16fab8b164cdb, add `DISABLE_IOS=1`
to a handful more locations so that Mono can be built without Xcode installed
on the system.

[build, macOS] More changes to not require Xcode for building

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.DefaultOutputPaths.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/620311
Defaulting `$(AppendTargetFrameworkToIntermediateOutputPath)` to True
is breaking QA unit tests, and we still have no good idea how much
havoc this will wreak upon our customers.
Default `$(AppendTargetFrameworkToIntermediateOutputPath)` to False so
that the new `$(IntermediateOutputPath)` mechanism it implies
(13d216fd) can be opted-in to instead of out of.

[Xamarin.Android.Build.Tasks] Disable per-TFN IntermediateOutputPath

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileExpected.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs

We got a report on slack that intellisense is showing errors on switch
statements for android resources. This might be because ALL of
the resource ids are 0 when using the managed parser.
This commit mimics the algorithm used by aapt as decribed at [1].
As a result most of the ids will be unique, which should fix
the intellisense errors.
[1] https://stackoverflow.com/questions/6517151/how-does-the-mapping-between-android-resources-and-resources-id-work

[Xamarin.Android.Build.Tasks] Fix Intellisense errors for switch statements

---

build-tools/timing/timing.projitems
build-tools/timing/timing.targets

In our private `monodroid` repo, a few features are needed in order to
setup timing:
- `xabuild` needs to be supported for `Release` configuration
- Need to be able to clone a project not in our repo
- Need to be able to run NuGet restore
Changes:
- Use `bin\$(Configuration)\bin\xabuild`
- Added `Restore` metadata to `XACaptureBuildTimingProject`, which
defaults to empty. If specified, `.nuget\NuGet.exe restore` will be
called on the value, which should generally be a path to a `*.sln`
file.
- Added `Repo` metadata to `XACaptureBuildTimingProject`, which
defaults to empty. If enabled, this script will use git commands to
clone the repo (with a depth of 1) and move to a specified commit
- Added `Commit` metadata to `XACaptureBuildTimingProject`, which
defaults to empty. If enabled, a `git …

[timing] more configuration options for MSBuild timing

---

build-tools/scripts/TestApks.targets

Set `Timeout` parameters for `Adb` task calls (and tasks based on
Adb).
We are still experiencing issues where `adb` get stuck for unknown
reason. Like in this case where it locked for nearly 7 hours.
```
01:39:56   adb I 05-25 01:39:56 71573 6448255 adb_io.cpp:75] readx: fd=3 wanted=4 (TaskId:88)
08:18:29 Build timed out (after 600 minutes). Marking the build as aborted.
```
We set the timeout in most cases to 1 or 2 minutes, plus these cases
with longer timeouts:
* RunInstrumentationTests 30 minutes
* RunUITests 5 minutes

[tests] Set timeouts for Adb tasks

---

.gitmodules
Makefile
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.Darwin.projitems
src/libzip-windows/libzip-windows.csproj
src/libzip-windows/libzip-windows.projitems
src/libzip-windows/mingw-linux-32.cmake
src/libzip-windows/mingw-linux-64.cmake
src/libzip/CMakeCacheInitialOSX.txt
src/libzip/libzip.projitems
src/libzip/libzip.targets

Bump to lipzip/rel-1-5-1/b95cf3fdd4c1271f922017f092d02a878873425c (#863)
Main reason is to include fixes for a couple CVEs. Changes:
* 1.3.0
* Support bzip2 compressed zip archives
* Improve file progress callback code
* Fix zip_fdopen()
* CVE-2017-12858: Fix double free().
* CVE-2017-14107: Improve EOCD64 parsing.
* 1.3.1
* Install zipconf.h into ${PREFIX}/include
* Add zip_libzip_version()
* Fix AES tests on Linux
* 1.3.2
* Fix bug introduced in last: zip_t was erroneously freed if zip_close()
failed.
* 1.4.0
* Improve build with cmake
* Retire autoconf/automake build system
* Add zip_source_buffer_fragment().
* Add support to clone unchanged beginning of archive (instead of
rewriting it). Supported for buffer sources and on Apple File System.
* Add support for Microsoft Universal …

Bump to lipzip/rel-1-5-1/b95cf3fdd4c1271f922017f092d02a878873425c (#863)

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Aapt2Tests.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build?buildId=1722717&tab=ms.vss-test-web.test-result-details
I noticed one of the new aapt2 tests is failing on Windows with:
System.IO.IOException :
The process cannot access the file 'E:\A\_work\1\s\bin\TestDebug\temp\Aapt2CompileFixesUpErrors' because it is being used by another process.
I also noticed usage of `Directory.SetCurrentDirectory` within the
test, that should be within a `try-finally` block.
The following fixes the test:
- Reset `$CWD` right after we run `Aapt2Compile.Execute`, as we should
no longer need it modified at that point
- Use a `try-finally` block, in case something `throws`

[tests] fix Aapt2Tests on Windows

---

Makefile
build-tools/scripts/Configuration.Java.Interop.Override.props

Fixes: https://github.com/xamarin/xamarin-android/issues/1493
Allows injection of `<dllmap/>` entries into
`Java.Runtime.Environment.dll.config`.
Use `<fileapi.h>`, not `<FileAPI.h>`, as Linux wants the former.
Add `$(CecilSourceDirectory)` support.

Bump to Java.Interop/master/bed29582

---

Documentation/guides/messages/README.md
Documentation/guides/messages/adb0000.md

Context: https://github.com/xamarin/monodroid/pull/780
Closes: https://github.com/xamarin/xamarin-android/issues/1727
I implemented `ADB0000` in the proprietary part of Xamarin.Android,
but need to document the error code in the open source
`xamarin-android` repository.
Looking at how the `Install` target is setup in `xamarin-android`, it
did not appear there was a good way to emit this error code for the
following target:
<Target Name="_Deploy">
<Exec Command="&quot;$(AdbToolPath)\adb&quot; install -r &quot;$(ApkFileSigned)&quot;" />
</Target>
Since proprietary Xamarin.Android overrides this target, it is
probably not worth the work to write a custom MSBuild task to add the
`ADB0000` error code for open source …

[docs] added ADB0000 error code

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

`AndroidUseAapt2="$(Aapt2Version)"` is wrong.
The commit message from 3395dbc says:
<AndroidUseAapt2>True</AndroidUseAapt2>
so use it. To make sure, specifying Aapt2Version didn't affect anything.

[msbuild] fix Aapt2 property reference.

---

Documentation/guides/BuildProcess.md
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/AndroidLinkContext.cs
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Linker.cs
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/LinkerOptions.cs
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs
src/Xamarin.Android.Build.Tasks/Tasks/LinkAssemblies.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

This option makes preserving new marshal methods, generated by
`jnimarshalmethod-gen.exe`, optional in the linker.
It also introduces new `JniMarshalMethods` property to toggle building
with generated marshal methods and will be used by following
patches too. It defaults to *False*.

[linker] Added PreserveJniMarshalMethods option

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Aapt2Tests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/1748
I was testing build times on master with a project in the
Xamarin.Forms repo.
I discovered the following scenario:
1. Build [Xamarin.Forms.ControlGallery.Android.csproj](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj)
2. Build it again, with no changes
The `_CreateAapt2VersionCache` target was always running, and it seems
to be a bit of a performance regression.
For example, in the log from building this project I saw the following
times from `_CreateAapt2VersionCache` in this project and other referenced
projects:
- 144ms
- 51ms
- 92ms
- 127ms
- 102ms
Total of 516ms added to a build with no changes.
To fix this I:
- Added a test with …

[aapt2] _CreateAapt2VersionCache target should not run when aapt2 is disabled

---

src/monodroid/jni/monodroid-glue.c
src/monodroid/jni/xamarin_getifaddrs.c
src/monodroid/monodroid.projitems

We've been building libmonodroid for Linux host incorrectly. While the shared
library built, it would never load properly, failing to resolve the
`pthread_threadid_np` and `print_ifla_name` functions.
The former is due the fact that we attempted to implement the `gettid`
function (returns current thread ID) which does not exist in glibc on Linux and
our implementation called `pthread_threadid_np` which caused a compiler warning
about missing declaration of the function - an error which would show up only at
runtime (but we practically don't use the Linux host libmonodroid currently and
so nobody noticed the issue). This commit fixes the implementation by calling
the `SYS_gettid` system call directly on Linux (but not on Android which has its
own implementation of the call in bionic)
The …

[Linux] Fix a few problems with host build of libmonodroid

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.DefaultOutputPaths.targets

Context: 13d216fd86b4419eee8029abecf2ef24115edf26
Context: 96b735273bb70b5ef40698d9ed4c287108792b9d
After internal deliberation, we have decided that it is sufficiently
"safe enough" to set
`$(AppendTargetFrameworkToIntermediateOutputPath)`=True on Windows,
so that `$(IntermediateOutputPath)` contains
`$(TargetFrameworkVersion)`.

[Xamarin.Android.Build.Tasks] Per-TFV IOP on Windows

---

build-tools/scripts/PrepareWindows.targets

Context: https://github.com/xamarin/xamarin-android/commit/9bc51aed62d6e00035496dc3c6a76fb303a5fa90#diff-b67911656ef5d18c4ae36cb6741b7965R114
Java.Interop was recently configured to use Mono's copy of
`Mono.Cecil`. This change was setup in the `Makefile`:
prepare-props: prepare-deps
cp $(call GetPath,JavaInterop)/external/Mono.Cecil* "$(call GetPath,MonoSource)/external"
cp "$(call GetPath,JavaInterop)/product.snk" "$(call GetPath,MonoSource)"
We have to run the equivalent of these `cp` commands in
`PrepareWindows.targets`.

[build] fix Java.Interop's Mono.Cecil usage on Windows

---

Makefile

They have been kept old in their directory, and updates have been prevented.
That resulted in incorrect TargetFrameworkRootPath setting in the previous
bogus property definition. Removing this file fixes it.

Make sure to remove previous Xamarin.Android.Sdk.(props|targets)

---

.gitignore
Xamarin.Android.Build.Tasks.sln

Currently working with Xamarin.Android.Build.Tasks in Visual Studio
for Windows requires several non-working projects to be unloaded.
Most of the development done on Windows involve the
Xamarin.Android.Build.Tasks MSBuild tasks and unit tests, so it makes
sense to just have a simple SLN file to work on this specific part of
the product.
This simplifies the workflow on Windows:
- Run `msbuild Xamarin.Android.sln /t:Prepare`
- Run `msbuild Xamarin.Android.sln`
- Open `Xamarin.Android.Build.Tasks.sln`, which only loads 4 relevant
projects, and work completely in the IDE from there. The solution
also loads very quickly, due to having less projects.
From here, the IDE's NUnit unit test runner works, and it is
straightforward to make changes to MSBuild tasks.
Other changes:
- Added a …

[Xamarin.Android.Build.Tasks] add a SLN to work on build tasks easier

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

The current Install (_Deploy) target will fail with 'error : more than one device/emulator' if multiple devices or emulators are attached. This change allows us to pass the -s argument to adb (e.g. '/p:AdbTarget=-s foo'), which allows us to specify an individual target if multiple are present.
Failure example:
```
"Tests.csproj" (Install target) (1) ->
(_Deploy target) -> 
EXEC : error : more than one device/emulator [/foo/bar/Tests.csproj]
EXEC : error : more than one device/emulator [/foo/bar/Tests.csproj]
adb : error : failed to get feature set: more than one device/emulator [/foo/bar/Tests.csproj]
/foo/bar/xamarin.android-oss_v8.4.99.3_Darwin-x86_64_HEAD_7ba040a/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3054,3): error MSB3073: The command …
```

[Xamarin.Android.Common.targets] Allow AdbTarget to be used for deployment

---

src/monodroid/jni/monodroid-glue.c

Noticed the following warning in the build
log. `enable_soft_breakpoints` function is called only when `DEBUG` is
defined. So make sure we don't compile it when `DEBUG` is not defined.
```
jni/monodroid-glue.c(2493,1): warning GF055929C: unused function 'enable_soft_breakpoints' [-Wunused-function] [/Users/rodo/git/xa2/src/monodroid/monodroid.csproj]
```

[monodroid] Include enable_soft_breakpoints conditionally

---

Configuration.props

Commit 01988e0 broke `ResolveSdks` because it forced
the system to build the v1.0 and v9.0 apis. v9.0 is
unstable, as a result the following exception occurs
The "ResolveSdks" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object
This is because there are NO stable api's available.
This commit resets the system to build the latest stable api.

[build] Build the latest stable platform.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileExpected.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManagedResourceParserTests.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs

Fixes https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/628467
Fixes #1784
We were not correctly processing `dimen` resource items when parsing
the actual resources. We did however do it correctly when processing
the `R.txt` file.

[Xamarin.Android.Build.Tasks] Intellisense can't recongize 'Resource Dimension' definition

---

src/Xamarin.Android.Build.Tasks/Tasks/GetImportedLibraries.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs

Fixes #1814
Both `GetImportedLibraries` and `ResolveLibraryProjectImports` have
a problem where the cache files they genereate are not always
consistent between builds.
In some cases additional entries are added/removed. As a result
targets like `_UpdateAndroidResgen` will run when they really
do not need to. Here are some examples of the changes
diff -u old.cache Bug15162/obj/Debug/libraryprojectimports.cache
--- old.cache	2018-06-14 11:12:10.000000000 +0100
+++ Bug15162/obj/Debug/libraryprojectimports.cache	2018-06-14 11:12:28.000000000 +0100
@@ -1,8 +1,6 @@
﻿<?xml version="1.0" encoding="utf-8"?>
<Paths>
<Jars>
-    <Jar>obj/Debug/lp/0/jl/formsviewgroup.jar</Jar>
-    <Jar>obj/Debug/lp/7/jl/support-annotations.jar</Jar>
<Jar>/Users/dean/Downloads/Bug15162-1/Bug15162/obj/Debug/lp/0/jl/fo …

[Xamarin.Android.Build.Tasks] Fix inconsistent library cache files.

---

src/Xamarin.Android.Build.Tasks/ILRepack.targets

We had a duplicate Nuget.Common when we need a
Nuget.Protocol.

[build] Fix the list of ILRepack assemblies.

---

Makefile
build-tools/scripts/BuildEverything.mk
build-tools/scripts/Packaging.mk
build-tools/scripts/msbuild.mk

Fixes: https://github.com/xamarin/xamarin-android/issues/1792
We have a bit of a conundrum: when things break, the diagnostic build
logs are *essential* to tracking down *why* something broke.
However, the sheer *verbosity* of those diagnostic logs makes it
difficult to determine *what* broke; it's very easy to get lost.
Additionally, the gigantic log files make the **Console Output**
Jenkins link nearly useless, as most web browsers will cease up when
attempting to download ~1GB log files.
Split the difference: introduce a new `$(call MSBUILD_BINLOG)` syntax
which creates an [MSBuild binary log][0] file, which is like
diagnostic output *but even moreso*, while *also* overriding the
console logging to `/v:normal`.
[0]: https://github.com/Microsoft/msbuild/wiki/Binary-Log
This should allow …

[build] Normal & Diagnostic Log Verbosity, at once!

---

src/Xamarin.Android.Build.Tasks/Tasks/CheckForInvalidResourceFileNames.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs

Fixes #1780
We forgot to include `-` as a valid character for the Resource
filenames when implementing the `CheckForInvalidResourceFileNames`
Task. As a result many working samples, when using `aapt2`, failed
with.
APT0000: Invalid file name: It must contain only [a-zA-Z0-9_.].
The fix is to allow `-` as a filename character.
This is only done for `values` filenames, since they
are the only ones which support `-`. For all other resource types `-` is invalid.

[Xamarin.Android.Build.Tasks] [Aapt2] Allow dashes in Resource file names

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.CSharp.targets

Context https://github.com/xamarin/xamarin-android/issues/1824
We seem to be getting some odd behaviour since commit 13d216f which
introduced the `DefaultOutputPaths` targets. For example we see
the following types of paths on MacOS
obj\/Debug\foo
The theory is that the new target is causing this weirdness. So
lets not import that target on MacOS at all. This is ok because
most of the code in the target is not used. This should fix these
weird path issues for 15.8. It will give us time to figure out how to
get this new functionality working on MacOS for the next release.

[Xamarin.Android.Build.Tasks] Dont Import `Xamarin.Android.DefaultOutputPaths.targets` on mac

---

src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #1822
Currently we only apply the `$(AndroidStoreUncompressedFileExtensions)` to
the resources added to the apk via `aapt2`. All the other resources added
by `BuildApk` are added as `Deflate`. As a result this means an  
Xamarin.Android apk cannot run on `Android.Things` since it requires the 
native libraries to be uncompressed.
We should we using the `$(AndroidStoreUncompressedFileExtensions)` property
as part of the `BuildApk` process to ensure that files which need to 
be left uncompressed are.

[Xamarin.Android.Buiild.Tasks] Allow uncompressed native libraries in apk

---

Documentation/guides/messages/xa4302.md
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/1698
In the project reproducing this issue, the Xamarin.Firebase.lid NuGet
produces an `AndroidManifest.xml` with the following line:
<permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />
Unfortunately our manifest merging code is throwing an exception and
producing a warning such as:
Xamarin.Android.Common.targets(1910,3): warning : Name cannot begin with the '$' character, hexadecimal value 0x24.
We also aren't getting the contents of this `AndroidManifest.xml`
merged, so this is definitely an issue!
The exception is coming from the following code:
var existing = (name != null) ?
doc.XPathSelectElement (string.Format ("/manifest/{0}[@android:name='{1}']", top.Name.LocalName, …

[Xamarin.Android.Build.Tasks] fix for android:name="$" in manifest

---

src/monodroid/monodroid.targets

Context: https://devdiv.visualstudio.com/DevDiv/_build?buildId=1778402
Since d18c45a, the build has been failing on Windows with:
src\monodroid\monodroid.targets (162, 5)
src\monodroid\monodroid.targets(162,5): Error MSB4018: The "ReplaceFileContents" task failed unexpectedly.
System.IO.FileNotFoundException: Could not find file 'E:\A\_work\2\s\external\Java.Interop\src\Java.Runtime.Environment\Java.Runtime.Environment.dll.config'.
File name: 'E:\A\_work\2\s\external\Java.Interop\src\Java.Runtime.Environment\Java.Runtime.Environment.dll.config'
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, …

[build] fix for monodroid.targets on Windows

---

build-tools/scripts/Packaging.mk
build-tools/scripts/msbuild.mk

Commit 987a05fa updated the build system to create MSBuild `binlog`
files, so that the "normal" build logs could be smaller.
There's just one problem with this arrangement: when something goes
wrong, we need the `*.binlog` files to determine what went wrong, but
*nothing was preserving the `.binlog` files*!
Oops.
Update the `make package-build-status` target so that it stores
generated `*.binlog` files into the `build-status-*` file.
Additionally, alter the `.binlog` filename format so that instead of
containing the Unix time_t/epoch value, it instead uses ISO 8601
notation of `<year><month><date>T<hour><minute><second>`.  This
results in more human readable values, and will allow for saner
integration in the future for when we migrate unit test execution over
to also produce `.binlog` …

[build] `make package-build-status` captures binlog files

---

src/Mono.Android/Android.Runtime/ResourceIdManager.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/1544
I was able to verify that my app's `Resource.UpdateIdValues` was
getting invoked multiple times with VS 15.7.4:
- Create a new Xamarin.Android app
- Create a new Xamarin.Android library, and reference it from the app
- (Optional) call `Android.Runtime.ResourceIdManager.UpdateIdValues`
directly
By placing a breakpoint, and/or `Log.Debug` messages, I can verify
that my app's `Resource.UpdateIdValues` was being called 5 times!
The issue lies in this code:
if (id_initialized)
return;
//System.Reflection code to call Resource.UpdateIdValues() in the app
id_initialized = true;
While `Resource.UpdateIdValues` is being invoked,
`ResourceIdManager.UpdateIdValues ()` is called recursively.
`id_initialized` will not be set until after the …

[Mono.Android] ResourceIdManager.UpdateIdValues called N times

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build?buildId=1768391
Context: https://devdiv.visualstudio.com/DevDiv/_build?buildId=1778620
There are a couple issues happening on VSTS:
1. If the build needs to delete/recreate `~\android-toolchain\sdk`,
sometimes `adb.exe` is running and so the directory cannot be
deleted.
2. Sometimes the `<Exec />` MSBuild task will hang indefinitely, even
though the NUnit tests have completed.
Our test run `adb.exe` here, to determine if a device/emulator is
connected:
https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs#L19-L21
It turns out the two issues are directly related. If you launch
`adb.exe`, and it is the first instance of `adb`, it will continue to …

[tests] kill adb when Xamarin.Android.Build.Tests complete

---

build-tools/android-toolchain/android-toolchain.projitems

If you are running Android O or above as the Android target to test
`run-apk-tests`, it will fail because of adb server version mismatch
(39 vs. 40). It is a typical adb issue e.g.:
https://sqa.stackexchange.com/questions/20524/how-to-resolve-adb-server-version-32-doesnt-match-this-client-36-killin
We need newer adb to fix this issue.

bump Android platform-tools to fix adb server version mismatch with P.

---

Configuration.props
build-tools/android-toolchain/android-toolchain-windows.targets
build-tools/android-toolchain/android-toolchain.projitems
src/monodroid/CMakeLists.txt
src/monodroid/monodroid.targets

Fixes for unzipping the cmake download:
- `android-toolchain.projitems` doesn't need to specify `.zip`, as the
targets append this extension automatically
- It appears that the zip of cmake doesn't have a subdirectory
- Added a `NoSubdirectory` item metadata
- Set `<UnzipDirectoryChildren NoSubdirectory="True" />` so that
cmake is extracted correctly
Issues with paths:
- cmake does not appear to like odd combinations of paths, such as
`\/` or `\\`. These are likely mistakes that *happen to work*, so we
should clean them up.
- `Configuration.props` had a double path separator in
`$(XAInstallPrefix)`, since `$(MSBuildThisFileDirectory)` contains a
trailing slash
- `monodroid.targets` had a path with `\/` on Windows, since
`$(OutputPath)` has a trailing slash
- `CMakeLists.txt` had two …

[build] cmake fixes for Windows

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build?buildId=1793969
Our VSTS builds on Windows have had one failing unit test for a while
(but the build was otherwise broken in general).
Xamarin.Android.Build.Tests.BuildTest.BuildMultiDexApplication(False,"v7.1")
multidex-ed classes.zip exists
Expected: True
But was: False
at Xamarin.Android.Build.Tests.BuildTest.BuildMultiDexApplication(Boolean useJackAndJill, String fxVersion)
in E:\A\_work\2\s\src\Xamarin.Android.Build.Tasks\Tests\Xamarin.Android.Build.Tests\BuildTest.cs:line 544
1589dff3 was a good attempt at handling our new
`AppendTargetFrameworkToIntermediateOutputPath` logic in this test.
However, it was using `TargetFrameworkMoniker` *before* this line:
proj.TargetFrameworkVersion = b.LatestTargetFrameworkVersion ();
And so, …

[tests] fix failing MultiDex test on Windows

---

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context https://devdiv.visualstudio.com/DevDiv/_workitems/edit/631540
The Cecil `DirectoryAssemblyResolver` is failing to resolve
`System.Runtime.dll` when loading assebmlies from the Intermediate
directory.
MSB4018: System.IO.FileNotFoundException: Could not load assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?
This seems to be becaue we have netstandard2.0 references in the
list of assemblies which reference `System.Runtime.dll`. However
in `GenerateJavaStubs` we are not including the `v1.0` or the
`Facades` directory in the search path. As a result the dependency
cannot be loaded. By default `DirectoryAssemblyResolver` only
uses the directories from the assemblies being loaded to …

[Xamarin.Android.Build.Tasks] Add `FrameworkDirectories` to `GenerateJavaStubs`.

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs

Fixes #1770
Turns out that `aapt2` does write warnings to `stderr` after
all. One example is [1]. This uses the `ALOGW` macro to write
a warning to `stderr`. These warnings are prefixed by a
`W/<type>`. So we can ue that to detect the warning in our
output logging code.
[1] https://github.com/aosp-mirror/platform_frameworks_base/blob/07735797a235ed98d182d0a40c8bdce4d92f9f0a/libs/androidfw/ResourceTypes.cpp#L6127

[Xamarin.Android.Build.Tasks] Ignore Aapt2 Warnings from StdErr

---

Documentation/guides/messages/xa4303.md
src/Xamarin.Android.Build.Tasks/Tasks/CreateManagedLibraryResourceArchive.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ZipArchiveExTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
src/Xamarin.Android.Build.Tasks/Utilities/Files.cs
src/Xamarin.Android.Build.Tasks/Utilities/ZipArchiveEx.cs

Context: https://developercommunity.visualstudio.com/content/problem/218603/msbuild-failure-in-resolvelibraryprojectimports-ta.html
Context: https://github.com/AArnott/PCLCrypto/issues/138
Fixes: http://work.devdiv.io/631267
Developers were reporting an error when consuming the PCLCrypto
`2.1.17-alpha-g5b1e8dff8c` NuGet package:
error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly.
error MSB4018: System.NotSupportedException: The given path's format is not supported.
error MSB4018: at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
error MSB4018: at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
error MSB4018: at System.IO.Directory.CreateDirectory(String path)
error MSB4018: at …

[Xamarin.Android.Build.Tasks] fixes for invalid __AndroidLibraryProjects__.zip

---

src/Mono.Android/Android.Runtime/ConstructorBuilder.cs

Reduce usage of slow `Guid.NewGuid ()` calls. All we need is method
unique name here and unique integer number should be all we need.
When looking further into
https://github.com/xamarin/xamarin-android/issues/1832 I noticed that
`ConstructorBuilder` uses `Guid.NewGuid ()` as well.
It also creates new assembly builder which is slow too and involves
call to `System.Guid:FastNewGuidArray ()` thrue
`System.Reflection.Emit.ModuleBuilder:.cctor ()`. I think we can avoid
creating new module as we already "pollute" `System.Object` in
`JNINativeWrapper` and thus we can put the constructors there as well.
After that change, together with
https://github.com/xamarin/xamarin-android/pull/1868, our
Xamarin.Android template app doesn't call the `Guid.NewGuid ()` during
the startup anymore.
In case of …

[Mono.Android] Avoid using Guid.NewGuid () for dynamic constructor names

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://github.com/xamarin/xamarin-android/pull/1741
Fixes: https://github.com/xamarin/xamarin-android/issues/1828
PR #1741 is a good attempt at fixing this, but...
- It is a little heavy handed and basically "nukes the world".
- It does not reproduce an issue in a test and "fix it", it fixes an
"unknown" #deletebinobj problem.
I also have a few nitpicks about PR #1741:
- It only comes into effect if `BuildingInsideVisualStudio` is `True`.
We should also fix command-line builds.
- The `$(ProjectLockFile).stamp` file isn't added to `FileWrites`.
So let's improve on #1741! As it had some good ideas, we just need to
narrow its focus.
First, I reproduced a real issue in a test with the following
scenario:
- Create a Xamarin.Forms 2.3.4 app that uses the 25.4.x support
libraries
- …

[Xamarin.Android.Build.Tasks] clean intermediates if NuGets change

---

src/Mono.Android/Java.Interop/TypeManager.cs

In https://github.com/xamarin/xamarin-android/issues/1830 we saw that
there are cases when `monodroid_typemap_java_to_managed` fails to get
us managed type name. These are internal and nested private
classes. We don't need to fallback in these cases.
So the fallback didn't get us anything as we don't have managed
bindings for these.
Avoiding the fallback saves us aprox. 9ms in
`TypeManager::GetJavaToManagedType ()`, which is about 90%
improvement. 10ms to 1ms. (measured on x86_64 emulator, XamlSamples
app)
Also the JIT *Compiled methods* number goes down from 5133 to 5107.

[Mono.Android] Do not fallback in GetJavaToManagedType

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

Context: http://build.devdiv.io/1806783
Commit messages can "accidentally" cause test failures on VSTS.
Consider if you added an error message in a commit message, then wrote
a test asserting the error no longer occurs.
Both Jenkins and VSTS have an environment variable containing the full
commit message, which will inexplicably cause your test to fail...
- Jenkins sets `ghprbPullLongDescription`
- VSTS sets `BUILD_SOURCEVERSIONMESSAGE`
In this case my build log had:
```
BUILD_SOURCEVERSIONAUTHOR = Jonathan Peppers
BUILD_SOURCEVERSIONMESSAGE = [Xamarin.Android.Build.Tasks] clean intermediates if NuGets change (#1878)
~~commit message text~~
Skipped resource lookup for C:\Users\myuser\.nuget\packages\xamarin.android.support.animated.vector.drawable\27.0.2.1\lib\MonoAndroid81\Xamarin.Android …
```

[Xamarin.ProjectTools] fix for VSTS and BUILD_SOURCEVERSIONMESSAGE

---

tests/CodeBehind/UnitTests/BuildTests.cs

Design time build works by invoking a different target than the normal build.
Add a couple of tests which invoke the same target.

Add Code-Behind tests for design-time build

---

src/Mono.Android/Java.Interop/TypeManager.cs

This fixes https://github.com/xamarin/xamarin-android/issues/1831
Make sure we use the code path, which uses the `typename.*` maps. It
is much faster than `JavaNativeTypeManager.ToJniName`.
Tested with x86 emulator again. It saves 17ms (from 18ms to 1ms) in XA
template and 26ms (from 28ms to 2ms) in XamlSamples app. So it scales
well.
It also decreases JIT usage. XA template: *Compiled methods* 1954 to
1880.

[Mono.Android] Use the faster java type name mapping

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/StartAndroidEmulator.cs

Context: https://developer.android.com/studio/run/emulator-commandline
When attempting to use the emulator created from our build, on Windows
I commonly get an error such as:
adb : error : failed to copy 'bin\TestDebug\Mono.Android_Tests-Signed.apk' to '/data/local/tmp/Mono.Android_Tests-Signed.apk': remote No space left on device [tests\RunApkTests.targets]
The issue seems to be there is not enough disk space allocated to
`/data/local/tmp/`.
When I look at the build log, where we start the emulator:
[emulator stdout]   disk.cachePartition.size = 66m
It appears that only 66MB is allocated by default. I'm not sure how we
aren't hitting the same problem on other platforms.
If I add the flag `-cache-size 512`, I now see:
[emulator stdout]   disk.cachePartition.size = 512m
And now I can …

[tests] fix for launching emulator on Windows

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs

Context: https://github.com/xamarin/xamarin-android/commit/77cf939df5e6d3bf657cb191db819abc99b6957b
Since 77cf939, we have been killing adb after tests complete.
This causes an issue if you are running a test in an IDE that uses
`BaseTest.HasDevices`. The first run will likely work, but the second
one fails saying `Test Skipped no devices or emulators found.`.
If you run a test, and adb is not already running, consider the
following code:
var result = RunAdbCommand ($"{adbTarget} shell getprop ro.build.version.sdk");
It will return with:
27* daemon not running; starting now at tcp:5037
* daemon started successfully
Since we pass the result to `int.TryParse`, we are treating the
command as if it had failed, meaning no devices were attached.
To make this more robust, we can split on the `*` …

[tests] fix for first launch of adb

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/XamarinProject.cs

Context: https://github.com/xamarin/xamarin-android/pull/1878
The way `Xamarin.ProjectTools` saves `packages.config`, it would
accidentally trigger `_CleanIntermediateIfNuGetsChange`. It saves the
file *every* time, regardless if the contents changed or not. This
would play havoc with `_CleanIntermediateIfNuGetsChange` and cause it
to run when it shouldn't.
So I modeled what we are currently doing for conditionally saving the
project file. I keep the last `packages.config` contents around, and
make sure it only saves to disk if it changes. Using
`DateTimeOffSet.MinValue` as a `Timestamp` will prevent the file from
being written to disk.
I updated two tests to validate this change, which also adds some
additional validation to the `_CleanIntermediateIfNuGetsChange`
target.

[Xamarin.ProjectTools] only save packages.config if it changes

---

Documentation/guides/LayoutCodeBehind.md
src/Xamarin.Android.Build.Tasks/Tasks/CalculateLayoutCodeBehind.cs
tests/CodeBehind/BuildTests/Resources/layout/Main.axml

If the Android layout file being processed has an XML node other than an
element (e.g. a comment) directly following the XML declaration node, the
generator fails to properly locate the root element and will miss any namespace
declarations on it, as well as the `xamarin:classes` attribute.
This results in failure to generate partial class code and will also cause an
error to parse any elements with the `xamarin:managedType` attribute further
down in the layout file.
The fix is to skip over non-element nodes until we find the first element one
and then attempt to read namespaces and other attributes.

[CodeBehind] Fix code generation for layouts with non-element root

---

src/Mono.Android/Android.Runtime/AndroidRuntime.cs

The jnimarshalmethod-gen build infrastructure is not ready yet, so
for now we don't need to look for the registration methods.
The `TryRegisterNativeMembers` is quite slow and needs an update. See
https://github.com/xamarin/xamarin-android/issues/1898.

[Mono.Android] Do not try to use new jni marshal methods yet

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://github.com/xamarin/xamarin-android/pull/1878
The initial `_CleanIntermediateIfNuGetsChange` target had a terrible
bug.
If you were building a project for the first time, due to the ordering
of targets:
<BuildDependsOn>
_ValidateLinkMode;
_SetupDesignTimeBuildForBuild;
_CreatePropertiesCache;
_AddAndroidDefines;
_AddNativeLibraryArchiveToCompile;
_CheckTargetFramework;
_RemoveLegacyDesigner;
_ValidateAndroidPackageProperties;
_CleanIntermediateIfNuGetsChange;
$(BuildDependsOn);
</BuildDependsOn>
`_CreatePropertiesCache` creates `build.props`, but then on a first
build `_CleanIntermediateIfNuGetsChange` runs and deletes it!
The fix here is to move `_CleanIntermediateIfNuGetsChange` ahead of
`_CreatePropertiesCache`--it does not appear that any other
intermediate files are …

[Xamarin.Android.Build.Tasks] _CleanIntermediateIfNuGetsChange deletes build.props

---

Documentation/guides/BuildProcess.md
src/Xamarin.Android.Build.Tasks/Tasks/CreateMultiDexMainDexClassList.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context #1888
The component team need the ability to pass additional arguments
to the `com.android.multidex.MainDexListBuilder`. Specifically
they need to pass `--disable-annotation-resolution-workaround`.
Since we don't want to do that on all apps, we should add the ability
for them to provide those values in the `csproj` of the binding.
This commit adds `$(AndroidMultiDexClassListExtraArgs)` which will be
appended to the `CreateMultiDexMainDexClassList` command line.
This will allow the team to pass any additional arguments they need.

[Xamarin.Android.Build.Tasks] Add ExtraArgs support to `CreateMultiDexMainDexClassList`.

---

Configuration.props

Context: http://build.devdiv.io/1820059
Since f9a7cfc, NuGet restore has been failing for `Xamarin.Android-Tests.sln`:
Error XA0000: Could not determine API level for $(TargetFrameworkVersion) of 'v9.0'. [E:\A\_work\2\s\src\Mono.Android\Test\Mono.Android-Tests.csproj]
When running:
.nuget\NuGet.exe restore Xamarin.Android-Tests.sln -Verbosity Detailed
There is a little more insight into how NuGet works:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\msbuild.exe
"C:\Users\myuser\AppData\Local\Temp\NuGetScratch\rh0oot0c.d22.nugetinputs.targets"
/t:GenerateRestoreGraphFile /nologo /nr:false /v:q
/p:NuGetRestoreTargets="C:\Users\myuser\AppData\Local\Temp\NuGetScratch\zzcd4yd1.a0q.nugetrestore.targets"
/p:RestoreUseCustomAfterTargets="True" …

[build] fix for *new* TargetFrameworkVersion during nuget restore

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs

When we are debugging tests we don't want to kill `adb` after
the tests. This is so we can re-run tests without having to
run
adb start-server
every time.

[Xamarin.Android.Build.Tests] Dont kill adb when debugging.

---

Documentation/guides/messages/README.md
Documentation/guides/messages/xa0113.md
Documentation/guides/messages/xa0114.md
src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/635168
Fixes https://github.com/xamarin/xamarin-android/issues/1766
Google as of August and November 2018 will required a minimum
of TargetFrameworkVersion v8.0 to publish/update apps.
This commit adds a new check to `ResolveSdksTask` which will
emit warnings when we hit those dates. This will only happen
if the `TargetFrameworkVersion` < `v8.0`
If you are not targeting the Google Play store and wish to hide these
warnings you can make use of the `/nowarn:XA0114,XA0113` command line switch. 
Alternatively add
<NoWarn>XA0114;XA0113</NoWarn>
to your .csproj.
[1] [Google Play's target API level requirement](https://developer.android.com/distribute/best-practices/develop/target-sdk)

[Xamarin.Android.Build.Tasks] Add Warnings for minimum Google Play requirements.

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

After a ton of debugging under VS2017 I finally nailed down
one of the problems which cause
error APT0000: No resource found that matches the given name (at 'resource_name' with value '@string/foo').
When a user modifies a layout file we now call `UpdatedGeneratedFiles`
automatically to regenerate the designer files. The problem is that
sometimes both `@(ReferencePath)` and `@(ReferenceDependencyPaths)`
are completely empty. But not all the time. It seems that `msbuild`
provides those items *most* of the time.. but not ALL of the time.
As a result what happens is we end up with a `libraryprojectimports.cache`
file which contains ONLY `.jar` files references. It has no values
for `ResolvedResourceDirectories`, `ResolvedAssetDirectories` or
`ResolvedResourceDirectoryStamps`. The result is …

[Xamarin.Android.Build.Tasks] Fix `UpdateGeneratedFiles` to depend on `ResolveAssemblyReferences`.

---

src/monodroid/CMakeLists.txt

Recently the commit 7c8b6e4 omitted
the java-interop-gc-bridge-mono.c from host runtime sources.
jnimarshalmethod-gen.exe depends on it, so include it in the
compilation again. (previously added in d18c45a)

[monodroid] Include JI GC bridge in host runtimes again

---

src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs

On AndroidClientHandler, the ConnectAsync method creates a temporary cancellation token callback to disconnect the connection, but it was not making sure the httpConnection.Disconnect() do not happen on the main thread - it can cause Android to throw an exception. For more information read https://github.com/xamarin/xamarin-android/issues/1588 
To fix it we changed the ct.Register callback in ConnectAsync to be just like the one in DoProcessRequest

Fix issue #1588

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs
src/Xamarin.Android.Build.Tasks/Tasks/ValidateJavaVersion.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ResolveSdksTaskTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: http://work.devdiv.io/639234
The `ResolveSdks` MSBuild task was quite large, and had lots of inputs
and outputs. Because of this, it is difficult to tell which parts of
it are slow.
As a first stab at refactoring, I split it into three tasks that are
more focused in their concerns:
- `ResolveSdks` - now focuses on resolving `AndroidSdkPath`,
`AndroidNdkPath` and `JavaSdkPath`. It also sets up any static
members of `MonoAndroidHelper`.
- `ValidateJavaVersion` - shells out to `java` and `javac`, sets
`MinimumRequiredJdkVersion` and `JdkVersion`.
- `ResolveAndroidTooling` - does all the other work: calculates
`TargetFrameworkVersion` and finds the paths of various Android
command line tooling
The goal here is to clean things up without really changing how
anything works. And in …

[Xamarin.Android.Build.Tasks] refactor/split up ResolveSdks

---

src/Xamarin.Android.Build.Tasks/Tasks/CalculateLayoutCodeBehind.cs
tests/CodeBehind/BuildTests/CodeBehindBuildTests.csproj
tests/CodeBehind/BuildTests/MainMergeActivity.cs
tests/CodeBehind/BuildTests/Resources/layout/MainMerge.axml
tests/CodeBehind/UnitTests/BuildTests.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/1929
`<merge>` is an element used by Android to avoid stacking too many view groups
when one layout is included into another. In such cases `<merge>` can be used as
a place-holder which is replaced by the enclosing view group of the layout that
includes another layout with `<merge>` as the root element. However, as much as
you can call `FindViewById` to find an instance of `<merge>` which was given the
`android:id` attribute, Android will always return `null` in such case, as the
element has no type counterpart in the `Android.Views` collection of views.
Therefore, we must ignore the element whenever we process a layout that contains
it decorated with `android:id` in order to avoid confusion in generated
code (i.e. the property …

Ignore <merge> when generating code-behind source

---

src/monodroid/CMakeLists.txt

Due to a mistake in `CMakeLists.txt` the `DEBUG` macro wasn't defined and, in
effect, no libmonodroid.so built after the switch to cmake included the soft
debugger code required for debugging on device or in the emulator.
This commit fixes the issue by properly defining `-DDEBUG` whenever necessary.
Additionally, it now properly adds other native debugging flags which were
previously mistakenly omitted.

Include soft debugger interface code in libmonodroid

---

src/Xamarin.Android.Build.Tasks/Tasks/CopyIfChanged.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/1933
There have been various reports of a scenario such as:
- Open a project in VS 2017, that uses uppercase letters when
referencing a resource, such as `@drawable/IMALLCAPS`
- A Design-Time Build occurs
- Some future build later, a *regular* build fails with an `APT0000`
error
```
Resources\layout\test.axml(3,0): error APT0000: No resource found that matches the given name (at 'src' with value '@drawable/IMALLCAPS')
```
Once you are in this state, you are basically hosed until you
`Rebuild` or delete `obj`...
After a lot of digging, I was able to reproduce the issue by
invalidating `build.props`. This happens in a lot of common
situations:
- `$(DesignTimeBuild)` changes, such as a DTB or a regular build
- `$(AdbTarget)` changes, …

[Xamarin.Android.Build.Tasks] build.props can cause ConvertResourceCases to skip

---

src/mono-runtimes/mono-runtimes.projitems
src/monodroid/jni/monodroid-glue.c

When the `DEBUG` macro is defined it causes the build to include code that's
specific to Unix systems and will not build when targetting Windows (mostly
related to sockets). This commit modifies the minimal set of lines (on purpose,
to reduce the noise) to make the Windows cross-builds work.
Additionally, the `--cache-file` configure parameter is removed from
`mono-runtimes.projitems` as it is a duplicate and incorrect, with the correct
one found in `mono-runtimes.targets` file, in the `_ConfigureCrossRuntimes`
target.

Minimal changes to fix libmonodroid build for Windows with DEBUG

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Context: https://github.com/xamarin/xamarin-android/pull/1916
These tests were never quite right, since they were just looking for
instances of `TargetFrameworkVersion` in the build log. This would
match for inputs and outputs, and wasn't actually testing anything
because it appeared to always pass.
In #1916 I improved them by looking for
`Output Property: TargetFrameworkVersion=v2.3`, but they were
not passing.
Two issues to fix:
- These tests should set `AndroidUseLatestPlatformSdk=False`
- These tests shouldn't use `StringAssertEx.Contains` because it calls
`Assert.Pass`, skipping any future assertions...
When testing on Windows, these tests get skipped, so I had to fix
things on Mac. The PR builder also skips them, so we did not see the
issue until it was merged into master.

[tests] fix CheckTargetFrameworkVersion tests

---

build-tools/timing/timing.targets

When timing builds, and plotting them on Jenkins, we should prefer to
use the `Release` build output of `xamarin-android` if it exists.
This also will fix a problem downstream in `monodroid`, where I'm not
able to profile `Debug` builds because `bin\Debug` *might* not exist.
`monodroid` seems to mostly use `Release` builds of `xamarin-android`.
We really need to profile `Debug` Xamarin.Android application builds
so that we can see how `Fast Deployment` is performing.

[timing] use Release build of xabuild/xamarin-android if possible

---

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
src/Xamarin.Android.Build.Tasks/Tasks/LinkAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Context: https://github.com/xamarin/Xamarin.Forms/blob/42c07d1ae5aa56eb574b7d169499f1a9af7ec080/Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
While working on build performance, I noticed two timestamp issues
that are preventing some targets in Xamarin.Android from building
incrementally. I spotted both of these while timing builds of the
`Xamarin.Forms.ControlGallery.Android` project. It is a good test
subject, because it builds PCLs, and seven (or so) Xamarin.Android
library projects.
While timing builds, I noticed the following when
`_LinkAssembliesNoShrink` runs:
Target Name=_LinkAssembliesNoShrink Project=PagesGallery.Droid.csproj
Building target "_LinkAssembliesNoShrink" partially, because some output files are out of date with respect to their …

[Xamarin.Android.Build.Tasks] timestamp fixes for incremental builds

---

build-tools/scripts/dependencies/debian-common.sh
build-tools/scripts/dependencies/linux-prepare-LinuxMint.sh
build-tools/scripts/dependencies/ubuntu-common.sh
build-tools/scripts/generate-os-info

Add detection and preparation script for the Linux Mint distribution. Since Mint
is based on Ubuntu, this patch reorganizes things a little bit to reuse as much
of Ubuntu specific code as possible.

Add Linux Mint to the fold

---

build-tools/create-vsix/create-vsix.csproj

While generating a VSIX, I noticed this in the build log:
CreateVsixContainer:
Creating VSIX Container...
Creating the package with the following compression level. "NotCompressed".
Changing the `ZipPackageCompressionLevel` property to `Normal`, seems
to change the VSIX so it is properly compressed.
The file size goes from 584991368 bytes to 172998318 bytes.
It's worth doing this, just to make the download smaller in the OSS
repo. I need to do some further research and make sure the VSIX we are
shipping commercially is compressed.

[build] set VSIX compression level to Normal

---

src/Xamarin.Android.Build.Tasks/Tasks/ValidateJavaVersion.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/KeyToolTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/ValidateJavaVersionTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/MockBuildEngine.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj

Context: https://github.com/Microsoft/msbuild/blob/f147a76a60bf9e516800f65f9614c914df0a4f15/src/Framework/IBuildEngine4.cs#L34-L84
Context: https://github.com/xamarin/Xamarin.Forms/blob/42c07d1ae5aa56eb574b7d169499f1a9af7ec080/Xamarin.Forms.ControlGallery.Android/Xamarin.Forms.ControlGallery.Android.csproj
The new `ValidateJavaVersion` MSBuild task gets invoked for *every*
project on *every* build, regardless if there are changes or not.
Unfortunately, this task also takes around 250ms to run, since it
shells out to `java -version` and `javac -version`.
We can use MSBuild's `GetRegisteredTaskObject` and
`RegisterTaskObject` to cache the output of running these command line
tools. If we key with the full path to `java` or `javac`, the cache
should be properly invalidated if a different …

[Xamarin.Android.Build.Tasks] cache java -version output

---

Documentation/guides/messages/README.md
Documentation/guides/messages/xa1000.md
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs

Fixes https://devdiv.visualstudio.com/DevDiv/Xamarin%20Project%20Mgrs/_workitems/edit/639674
If a user generates an invalid or incomplete xml file the
`ManagedResourceParser` should not crash with an exception.
> The "GenerateResourceDesigner" task failed unexpectedly.System.Xml.XmlException: Root element is missing.   at System.Xml.XmlTextReaderImpl.Throw(Exception e)   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()   at System.Xml.XmlTextReaderImpl.Read()   at Xamarin.Android.Tasks.ManagedResourceParser.ProcessXmlFile(String file)   at Xamarin.Android.Tasks.ManagedResourceParser.ProcessResourceFile(String file)   at Xamarin.Android.Tasks.ManagedResourceParser.Parse(String resourceDirectory, IEnumerable`1 additionalResourceDirectories, Boolean isApp, Dictionary`2 resourceMap) …

[Xamarin.Android.Build.Tasks] ManagedResourceParser should not throw

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://github.com/Microsoft/msbuild/blob/b3f9eeab651c92bade6e4f64d11b59aa39e149cb/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3305
Fixes: https://github.com/xamarin/xamarin-android/issues/1960
While reviewing build logs, I have noticed something very odd if you
are building for `TargetFrameworkVersion=v6.0` and it gets switched to
a different one such as `TargetFrameworkVersion=v9.0`.
Here is the `GenerateTargetFrameworkMonikerAttribute` target from
`Microsoft.Common.CurrentVersion.targets`:
WriteLinesToFile
Parameters
File = C:\Users\myuser\AppData\Local\Temp\MonoAndroid,Version=v6.0.AssemblyAttributes.cs
Lines
// <autogenerated />
using System;
using System.Reflection;
[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute("MonoAndroid,Version=v9.0", …

[Xamarin.Android.Build.Tasks] we should set TargetFrameworkMonikerAssemblyAttributesPath

---

src/Xamarin.Android.Build.Tasks/Tasks/CopyAndConvertResources.cs
src/Xamarin.Android.Build.Tasks/Tasks/CopyIfChanged.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/1962
Since 0adf1ae0, I believe that resource changes on macOS have been
flaky--sometimes working, sometimes not. They have been consistenly
working on Windows, however...
After writing the simplest test I could, I found that my machine on
High Sierra could *sometimes* reproduce what our QA team was seeing. I
had to add the `[Repeat]` NUnit attribute before I could get the
failure to occur regularly.
After debugging for quite some time, I noticed a mistake in the
`CopyIfChanged` task. When comparing timestamps, it looks like it is
using the last *access* time of the destination file instead of the
last *write* time!
I think this is likely a typo (unintended), since switching the call
to `GetLastWriteTimeUtc` fixes the problem. …

[Xamarin.Android.Build.Tasks] CopyIfChanged use last "write" time

---

tests/TestRunner.xUnit/TestRunner.xUnit.csproj
tests/TestRunner.xUnit/packages.config

Update the xUnit (upstream) runner. The tests completed properly, hopefully it means it now handles all the unhandled exceptions properly (or we were lucky this time not to hit the network issue which caused the unhandled exception previously).

Update xUnit packages to the latest versions

---

src/Xamarin.Android.Build.Tasks/Tasks/Desugar.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Utilities/DexUtils.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Looking into a customer's binding project, usage of
`$(AndroidEnableDesugar)` was causing a crash at runtime where
`mono.MonoRuntimeProvider` was completely missing from the APK.
Looking into it further, it seemed that our desugar support only
worked when used in combination with Proguard or MultiDex.
What was happening:
- The `<Desugar />` MSBuild task "desugars" the Xamarin.Android app
code into a `__app_classes__.jar` file
- However `__app_classes__.jar` was not added to the `OutputJars`
output property
- In `Xamarin.Android.Common.targets` a `@(_AlternativeJarForAppDx)`
item group is used for the input to `javac`, which does not contain
any of the Xamarin.Android app's Java code!
In fact, a workaround for the customer's project, was to add the
following to their Xamarin.Android app …

[Xamarin.Android.Build.Tasks] Desugar now works without Proguard/MultiDex

---

.gitignore
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/1958
Context: https://github.com/xamarin/xamarin-android/issues/1933
Context: https://github.com/xamarin/xamarin-android/pull/1943
One of the issues I noticed while debugging the issue with #1933 is
that `$(IntermediateOutputPath)build.props` gets invalidated if
`$(DesignTimeBuild)` changes. `build.props` triggers alot of targets
to build completely again, so this is pretty bad for our build times
in an IDE...
Design-Time Builds can run quite frequently in VS Windows, and we
don't want to rebuild a bunch of things unnecessarily when the user
switches back to a regular build.
So a solution, is to use a `obj/Debug/designtime/build.props` that
works independantly of `build.props`. This prevents some slower
targets from running when …

[Xamarin.Android.Build.Tasks] use designtime/build.props

---

src/Xamarin.Android.Build.Tasks/ILRepack.targets

Xamarin.Android uses the ILRepack
task (https://www.nuget.org/packages/ILRepack.Lib.MSBuild.Task/) to repack/merge
the `Xamarin.Android.Build.Tasks` assembly, a step that is performed after the
`Xamarin.Android.Build.Tasks` project build completes. The step takes the
project's output assembly and several other dependencies and merges them into
one, replacing the original output assembly. For the majority of time it works
flawlessly, however the scenario described below causes a Mono runtime
crash (similar to this one https://github.com/mono/mono/issues/9613, although
not identical).
The crash causes aren't yet know in every detail, but the high level overview of
the issue is as follows. Mono runtime uses the `mmap(2)` system call on Unix to
map the on-disk image of the assembly into …

Fix ILRepack target on Linux

---

Configuration.props
build-tools/android-toolchain/android-toolchain.targets

Context: https://github.com/mono/mono/pull/9473#issue-200303674

Make platform-tools setup customizible and tell it to mono/sdks setup.

---

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Context: https://github.com/xamarin/xamarin-android/pull/1930
Since 3d999d3, `Fast Deployment` has been rebuilding the APK when it
shouldn't. Apparently the `typemap.mj` and `typemap.jm` files'
timestamps are used when deciding to repack/deploy the APK or not.
After looking at my `CheckTimestamps` test, I don't think it was quite
right. It should modify `MainActivity`'s type name so that these files
will be updated. Just modifying code won't invalidate these files.
Then the `GenerateJavaStubs` task should only update the timestamps if
the file was actually changed, which should fix `Fast Deployment`.

[Xamarin.Android.Build.Tasks] only update typemap timestamps if changes occur

---

build-tools/scripts/Packaging.mk
build-tools/scripts/ln-to.sh

The "log pakages" produced by `make package-build-status` (a2a970f5)
and `make package-test-errors` (0435a91f) have one usability problem:
they aren't compatible with [`make dist`][make-dist].
Specifically, `make dist`-style packages are packages which have a
root directory that is the same as the basename of the package name.
For example, if a package is named `foo.zip`, then the contents of
`foo.zip` would all be within a `foo` directory.
Addiotionally, `make dist`-style files usually have a "version number"
of some form encoded in the filename, with `foo-1.zip` having all
files within it nested under the `foo-1` directory.
This has two wonderful benefits:
1. When downloading such files, they won't "collide" with each other,
because they have unique values within the filename.
2. When …

[build] `make dist`-compatible log packages

---

Xamarin.Android.sln

The `build-tools/download-bundle` project was flagged with an
"Invalid configuration mapping" error when `Xamarin.Android.sln` was
loaded into Visual Studio for Mac.

[VSfM] Fix "Invalid configuration mapping" error

---

src/Mono.Android/Test/System.Net/NetworkInterfaces.cs
tests/TestRunner.Core/TestInstrumentation.cs
tests/TestRunner.NUnit/NUnitTestInstrumentation.cs

This test is failing rather consistently on many physical devices. See https://github.com/xamarin/xamarin-android/issues/1534 for more info.
I'd like to add a way to ignore this test conditionally, and we can do so with categories. However, the new NUnit test runner currently only allows included or excluded categories to be set in code when inheriting from `Xamarin.Android.UnitTests.NUnit.NUnitTestInstrumentation`. To address this, `NUnitTestInstrumentation` will now attempt to process certain instrumentation extras provided from the command line.
Usage:
`adb shell am instrument -e include InetAccess:NetworkInterfaces -w (PackageName)/(InstrumentationName)`
or
`adb shell am instrument -e exclude NetworkInterfaces -w (PackageName)/(InstrumentationName)`

[tests] Add category support to the new NUnit runner, and a category to the DotNetInterfacesShouldEqualJavaInterfaces test

---

build-tools/scripts/BuildEverything.mk
src/Mono.Android/Test/Mono.Android-Tests.targets
src/Mono.Android/Test/jni/Application.mk
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
src/sqlite-xamarin/src/main/jni/Application.mk
tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj
tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/jni/Application.mk
tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding/Properties/AssemblyInfo.cs
tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding/Xamarin.Android.LibraryProjectZip-LibBinding.csproj
tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding/Xamarin.Android.LibraryProjectZip-LibBinding.targets
tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding/jni/Application.mk
tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding/simple2/jni/Application.mk
tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-Tests/Xamarin.Android.MakeBundle-Tests.csproj
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib2/Xamarin.Android.BindingResolveImportLib2.csproj
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib2/jni/Application.mk
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib4/Xamarin.Android.BindingResolveImportLib4.csproj
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib4/jni/Application.mk

Starting with Android NDK r17, armeabi is *removed*, meaning that we
cannot build anything with armeabi anymore.
seealso: https://github.com/xamarin/java.interop/pull/346

Remove armeabi from build.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs

Our tests were not all using the same root path. While this
does not cause a problem in this repo. It does cause a
problem in monodroid. This is because the Root for the
base test is looking in the wrong directory. The result
is file checks fail.

[Xamarin.Android.Build.Tests] Fix BaseTest to use the same Root path.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BaseTest.cs

Context: http://build.devdiv.io/1901382
Since 8b244a1, the use of relative paths in the `BaseTest.Root` is
causing a test failure such as:
Xamarin.Android.Build.Tests.ResolveSdksTaskTests.ResolveSdkTiming
MonoAndroidToolsPath should be E:\A\_work\13\s\build-tools\scripts\..\..\bin\TestDebug
Expected string length 29 but was 55. Strings differ at index 17.
Expected: "E:\\A\\_work\\13\\s\\bin\\TestDebug"
But was: "E:\\A\\_work\\13\\s\\build-tools\\scripts\\..\\..\\bin\\TestDebug"
---------------------------------^
To restore the old behavior of the path returned, using
`Path.GetFullPath` in the `Root` property seems to fix the failures.
The old code was returning the full path, so this puts things back the
way it was:
public string Root {
get {
return Path.GetDirectoryName (new Uri (typeof …

[tests] fix for ResolveSdksTaskTests on Windows

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileExpected.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManagedResourceParserTests.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs

Fixes https://github.com/xamarin/xamarin-android/issues/1983
The ManagedResourceParser did not support `transition`
resource types. This commit adds support for that missing
type.
It was also missing 'array' support when parsing the `R.txt` file.
This has also been added.

[Xamarin.Android.Build.Tasks] Add 'transition' and 'array' support

---

Documentation/guides/messages/xa4304.md
src/Xamarin.Android.Build.Tasks/Tasks/Proguard.cs

Added a warning code for the `Proguard` MSBuild task along with
documentation. There was only one warning to fix here.
Additionally, I removed the extraneous log messages from the
`Proguard` task, since diagnostic MSBuild output will include all the
information we need.

[Xamarin.Android.Build.Tasks] proguard warning code

---

Documentation/guides/BuildProcess.md
Documentation/guides/messages/README.md
Documentation/guides/messages/apt0001.md
src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs
src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Compile.cs
src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Aapt2Tests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #1985
We currently use the same `AndroidResgenExtraArgs` property for
both `aapt` and `aapt2`. As a result when passing `--no-crunch`
to the `aapt2 link` command the following error is raised.
error APT0000: unknown option '--no-crunch'. "unknown option '--no-crunch'.".
Even worse.. you get 70 errors as `aapt2` dumps the contents of
the help output to stdout. This is not idea and does not allow
the user to act on the error.
So this commit does a couple of things
1) Add two new properties for passing arguments for `aapt2`
```
<AndroidAapt2LinkExtraArgs/>
<AndroidAapt2CompileExtraArgs/>
```
These will be used for `aapt2` instead of `AndroidResgenExtraArgs`.
2) Update the `Aapt2` to handle the unknown option error by emiting
and more descriptive error message. Also make sure we ignore …

[Xamarin.Android.Build.Tasks] Fix issues with `ExtraArgs` for Aapt2.

---

src/monodroid/jni/monodroid-glue.c

The following scenario using `Fast Deployment` causes an issue:
- Build and run a `Debug` mode Xamarin.Android app
- Update Xamarin.Android
- Build and run again
On the second deployment, a *new* shared Mono runtime will be
installed on the device.
And so, the symlink pointing to the shared Mono runtime was pointing
to a location that does not exist:
$ run-as com.xamarin.myapp ls -la /data/user/0/com.xamarin.myapp/files/.__override__/links
lrwxrwxrwx 1 u0_a132 u0_a132   93 2018-07-19 16:57 libmonosgen-2.0.so -> /data/app/Mono.Android.DebugRuntime-Y2eHYda6s0hMKJmiCfcYlA==/lib/x86/libmonosgen-32bit-2.0.so
$ ls /data/app/Mono.Android.DebugRuntime-Y2eHYda6s0hMKJmiCfcYlA==/lib/x86/
ls: /data/app/Mono.Android.DebugRuntime-Y2eHYda6s0hMKJmiCfcYlA==/lib/x86/: No such file or directory
This caused …

[monodroid] recreate shared runtime symlink if it points to an invalid location

---

tools/xabuild/xabuild.csproj

Context: https://github.com/xamarin/xamarin-android/pull/1975
In newer versions of Mono, `xabuild` is failing with:
/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(2126,5): error MSB3248:
Parameter "AssemblyFiles" has invalid value "xamarin-android/bin/Debug/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v1.0/mscorlib.dll".
Could not load file or assembly 'System.Reflection.Metadata, Version=1.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Or another example:
Mono: The following assembly referenced from monodroid/external/xamarin-android/bin/Debug/bin/Microsoft.Build.Tasks.Core.dll could not be loaded:
Assembly:   System.Reflection.Metadata    (assemblyref_index=7)
Version: …

[xabuild] reference missing assembly on newer Mono versions

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CheckAdbTarget.cs

Many of our PR builds recently have been failing, e.g. [3697][3697]:
CHECKADBTARGET : error : no devices/emulators found [/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/build-tools/timing/timing.csproj]
What's "funny" about this error message is that the
`<CheckAdbTarget/>` task *shouldn't ever fail*: the `Execute()` always
returns `true` (no error), and *itself* never calls `LogError()`.
However, it *did* call `ToolTask.LogEventsFromTextOutput()`, which
*can* call `LogError()` if it runs across an error in a "canonical"
format, complete with uppercasing the task name when it does so.
Remove the `base.LogEventsFromTextOutput()` invocation so that we
don't inadvertently log an error message.  With luck, this will remove
`<CheckAdbTarget/>` as a possible source …

[Xamarin.Android.Tools.BootstrapTasks] Remove adb errors

---

Documentation/guides/messages/README.md
Documentation/guides/messages/xa1001.md
Documentation/guides/messages/xa1002.md
src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs
src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs
src/Xamarin.Android.Build.Tasks/Tasks/ConvertResourcesCases.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ConvertResourcesCasesTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context https://github.com/xamarin/xamarin-android/issues/1711
When using a custom view within a layout file we replace the
`namespace.classname` with an `md5hash.classname`. We do this
by using the `acwmap.txt` file to make known types onto the
`md5` hashed ones. We do this in a case sensitive manner. We
also only support Camel case and lower case type names.
ClassLibrary1.CustomView=md5d6f7135293df7527c983d45d07471c5e.CustomTextView
classlibrary1.CustomView=md5d6f7135293df7527c983d45d07471c5e.CustomTextView
Given that a user is able to type these manually it is highly
probable that typo's will occur. If for example a user types
Classlibrary1.CustomView
(Note the lower case `L`) this will NOT be fixed up. Instead the user will recieve the
following error at runtime.
FATAL UNHANDLED …

[Xamarin.Android.Build.Tasks] Emit an Error if a custom view cannot be fixed up.

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt.cs
src/Xamarin.Android.Build.Tasks/Tasks/Aapt2.cs
src/Xamarin.Android.Build.Tasks/Tasks/AndroidToolTask.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidRegExTests.cs

Fixes (again) #1770
On windows we are hitting the same issue where the warnings
`aapt2` is producing are being logged as errors.
The weird part is that the "file" group was not being populated
with the right informaton.. This turns out to be down to how
`aapt2` is reporting the warnings..
W/ResourceType(23681): For resource 0x0101053d, entry index(1341) is beyond type entryCount(733)
W/ResourceType( 5536): For resource 0x0101053d, entry index(1341) is beyond type entryCount(1155)
^
Hmmmmm.
This space throws off our regex and results in the entire line
ending up in the `message` property.
So the fix is to update the regex to allow spaces for the `line`
capture group. We then also need to Trim that value before passing
it into `int.Parse` to ensure we don't get an error.

[Xamarin.Android.Build.Tasks] Fix Aapt2 warnings showing as errors

---

src/Xamarin.Android.Build.Tasks/Tasks/LinkAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://github.com/xamarin/xamarin-android/commit/3d999d32c3dcd78f687f0976f0b5a6a985736a75#diff-42a9402e6466c65d49d0ee7caf21f327R164
Since 3d999d32, a test is failing downstream in monodroid that is
testing the following scenario:
- With `Fast Deployment` enabled, run `/t:Install`
- Make a small code change
- Run `/t:Install` again
- Assemblies are getting uploaded to the device that should already be
up to date!
3d999d32 was addressing a symptom of the problem, but not the root
cause. The `OutputStep` of the linker has various uses of `File.Copy`,
which *preserves* the timestamp of the source file.
https://github.com/mono/linker/blob/615f62c32705322aeb0f3f15212a3dbb94b7f0aa/linker/Linker.Steps/OutputStep.cs#L187
The solution, then, is to run the `<Touch />` MSBuild task on the …

[Xamarin.Android.Build.Tasks] _LinkAssembliesNoShrink timestamps

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs

Context: https://paper.dropbox.com/doc/OpenJDK-and-You--AH1yWKdVXgno~uXYfmcUAZTwAg-NoECAe2XkBQeoxFfGL6ea
Context: https://github.com/xamarin/xamarin-android-tools/pull/29#issuecomment-400048306
Context: https://github.com/xamarin/xamarin-android/pull/2004#issuecomment-409924069
Context: https://github.com/xamarin/xamarin-android-tools/blob/917d3b3ce455eed6a4a0e4271d34661bdf0b261d/src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs#L256
Fixes: http://work.devdiv.io/646086
Fixes: http://work.devdiv.io/652760
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597752
Fixes: https://github.com/xamarin/xamarin-android-tools/issues/26
Fixes: https://github.com/xamarin/xamarin-android-tools/issues/39
Update & export `%JAVA_HOME%`, `%PATH%` on Windows.
We are [observing some unit test …

Bump to xamarin/xamarin-android-tools:master@917d3b3c

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #2029
The Xamarin.Android.Support.Vector.Drawable [1] NuGet package
overrides `$(AndroidResgenExtraArgs)` with `--no-version-vectors`.
Since 77d603a2 `aapt2` now has its own properties for `link` and
`compile`. As a result people using `aapt2` are likely to encounter
issues when using the above Nuget Package.
To help our users we can auto detect if the `--no-version-vectors`
is set in the `$(AndroidResgenExtraArgs)` property and auto
include that into the new `$(AndroidAap2LinkExtraArgs)` property
(if it does not contain it already). This will hopefully provide
a smooth transiton for users using `aapt2`.
Note `$(AndroidAap2CompileExtraArgs)` does NOT need the same argument
since is it not a valid argument for the `compile` task.
[1] …

[Xamarin.Android.Build.Tasks] Aapt2 & AndroidResgenExtraArgs compatibility

---

Documentation/guides/BuildProcess.md
src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ResolveSdksTaskTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #2007
Apparently there is a situation we aren't doing the right thing for:
- `TargetFrameworkVersion` is set to `v9.0`
- `AndroidUseLatestPlatformSdk`=`True`
- API 28 is not installed
In this case, we *should* be downgrading `TargetFrameworkVersion` to `v8.1`. Instead we get:
ResolveSdksTask Outputs:
AndroidApiLevel: 27
AndroidApiLevelName: 27
TargetFrameworkVersion: v9.0
This puts us in a weird state, since we would use JAR files for
different API levels:
- `platforms/android-27/android.jar`
- `xbuild-frameworks/MonoAndroid/v9.0/mono.android.jar`
This causes `proguard` (and likely other things) to fail:
PROGUARD : warning : there were 38 unresolved references to classes or interfaces.
You may need to add missing library jars or update their versions.
If your code works fine without …

[Xamarin.Android.Build.Tasks] fix for UseLatest when API level not installed

---

src/Mono.Android/Android.Runtime/ConstructorBuilder.cs
src/Mono.Android/Android.Runtime/DynamicMethodNameCounter.cs
src/Mono.Android/Android.Runtime/JNINativeWrapper.cs
src/Mono.Android/Mono.Android.csproj

Put the dynamic method name logic in one place. It also removes the
formatted string use and uses `InvariantCulture`.
It hopefully improves the performance (simpler string operations,
`InvariantCulture`). The change in performance is so small though, that
I wasn't able to measure it.
We use `long` counter, because `ConstructorBuilder` can, in some
cases, create a new constructor per java object instance. This should
be addressed in the future. After that we can probably get back to
`int` counter.
Also associate the created dynamic methods with
`DynamicMethodNameCounter` class instead of `System.Object`

Refactor dynamic method names creation

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

I got report from a customer (over email) of an error such as:
Java.Lang.ClassNotFoundException: Didn't find class "com.google.android.gms.R$string" on path: DexPathList
The build log showed the app was using a combination of Firebase with
MultiDex enabled, so I tried the Firebase sample from the docs team:
https://github.com/xamarin/monodroid-samples/tree/master/Firebase/FCMNotifications
Things appeared to work fine, but something seemed strange: my "spider
sense" was going off.
My initial thought was that the customer recently enabled MultiDex,
and toggling MultiDex on/off was breaking the build.
Oh, it was much worse than that.
I wrote a simple test with the following scenario:
- Build an app that *requires* MultiDex, w/ many methods
- Check we have `classes.dex`, `classes2.dex`, …

[Xamarin.Android.Build.Tasks] 3 tales of #deletebinobj

---

src/Xamarin.Android.Build.Tasks/Tasks/ConvertResourcesCases.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs

Context: https://github.com/xamarin/xamarin-android/issues/2043
When parallel builds occur, we can get `obj/Debug/lp` into a broken
state:
Resources/layout/abc_action_menu_layout.xml warning XA1001:
AndroidResgen: Warning while updating Resource XML '/var/folders/nx/rzr6lcqj6j3_vp7vtp28v2cw0000gn/T/tmp6bafd8e4.tmp': Root element is missing.
Then later, `<Aapt />` fails on the empty file:
obj/Debug/lp/11/jl/res/layout/abc_action_menu_layout.xml(2,0): error APT0000: Error parsing XML: no element found
It appears that `ConvertResourcesCases` still copies the file, even if
`AndroidResource.UpdateXmlResource` fails. Subsequent builds will
continue to fail, because an empty file has been copied with a newer
timestamp. Once in this state, developers would have to `Rebuild` the
project or delete …

[Xamarin.Android.Build.Tasks] fix for parallel builds

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileExpected.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManagedResourceParserTests.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs

Our `ManagedResourceParser` was not processing `raw` items
when processing an `R.txt` file. As a result you get the
following error
Resource' does not contain a definition for 'Raw'
This commit adds code to ensure we process the items.

[Xamarin.Android.Build.Tasks] Process 'raw' items from R.txt

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/Files.cs

Context: https://github.com/xamarin/xamarin-android/issues/2043
Another issue that could crop up from #2043 is:
- Two instances of `ResolveLibraryProjectImports` are run in parallel
- A file is written to at the same time, causing invalid zip files in
`obj/Debug/lp`, such as a `classes.jar` file
An example error message would be:
error APT0000: ERROR: unable to open 'obj/Debug/lp/7/jl/bin/classes.jar' as a zip file: -78 "classes.jar' as a zip file: -78".
Checking the zip file indicates it is corrupted:
$ zipinfo bin/TestDebug/temp/BuildInParallel/obj/Debug/lp/7/jl/bin/classes.jar
Archive:  bin/TestDebug/temp/BuildInParallel/obj/Debug/lp/7/jl/bin/classes.jar
[bin/TestDebug/temp/BuildInParallel/obj/Debug/lp/7/jl/bin/classes.jar]
End-of-central-directory signature not found.  Either this …

[Xamarin.Android.Build.Tasks] more fixes for parallel builds

---

src/Xamarin.Android.Build.Tasks/Tasks/AsyncTask.cs
src/Xamarin.Android.Build.Tasks/Tasks/CancelableTask.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj

The `ICancelableTask` is implemented by the AsyncTask
so that long background processes can respond to a `Cancel`
requrest from MSBuild.
The problem here is that many of our tasks which we might
want to cancel, do not derive from `AsyncTask`. Given that
allot of the time a task wont be using the features of
`AsyncTask`, it makes sense to introduce a new bass class.
This new class implements `ICancelableTask` and will allow
normal `Tasks` to use those features. This can be done by
overriding the `Cancel` method. Or alternatively using the
`CancellationToken` property `Token` to `Register` callbacks
or simply check `Token.IsCancellationRequested`.
`AsyncTask` has been updated to use the new base class.

[Xamarin.Android.Build.Tasks] Add CancelableTask.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: http://work.devdiv.io/663415
Fixes: https://github.com/xamarin/xamarin-android/issues/2060
Context: https://github.com/xamarin/xamarin-android/pull/2064
Context: https://github.com/xamarin/xamarin-android/commit/41bc8ffa0b8f21c4b41cc33fb629b433cfc5b3fd
Since 41bc8ff, I believe we have had the following problem:
- `$(AndroidUseApkSigner)` is `True`, this is the default now
- `$(AndroidCreatePackagePerAbi)` is `True`
- The per-abi APKs are not signed!
I think this bug surfaced in the 15.7 timeframe.
Looking at the existing code, an `ApkAbiFilesSigned` item group is
computed at a time at which the files may not exist yet: making the
`ApkAbiFilesSigned` item group empty on a first build. We used this
item group to delete existing APK files if they exist, but we also
need it sign them! …

[Xamarin.Android.Build.Tasks] AndroidCreatePackagePerAbi APKs should be signed

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.DefaultOutputPaths.targets
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidProject.cs

Context: https://github.com/xamarin/xamarin-android/pull/1628
Fixes: http://work.devdiv.io/667203
Customers are reporting MAX_PATH (or PathTooLongException) related
failures when upgrading Visual Studio from 15.7 to 15.8. This appears
to be due to the change of moving `$(IntermediateOutputPath)` from
`obj\Debug\` to `obj\\Debug\MonoAndroid81`.
Note we have two things we can do here to improve this:
- Rename `MonoAndroid81` to just `81`
- Fix the double slash `\\`
There was also the comment of using `$(AndroidApiLevel)`, but it feels
a bit safer to use what we have currently and shorten it. In the long
run, we should revisit the current approach entirely.
It appears during MSBuild evaluation, the `$(PlatformName)` is empty
(and not equal to `AnyCPU`). So we should just drop this extra …

[Xamarin.Android.Build.Tasks] shorten $(IntermediateOutputPath) for MAX_PATH

---

build-tools/scripts/PrepareWindows.targets

Add an error early in the preparation targets to let contributors know that having spaces in the Android NDK path will cause an error later in the build.  For example, before this change, a build run under a user named "Windows User" would hit the following error:
'C:\Users\Windows' is not recognized as an internal or external
command, operable program or batch file.
C:\source\xamarin-android\src\sqlite-xamarin\sqlite-xamarin.targets
(27,5): error MSB3073: The command "
"C:\Users\Windows User\android-toolchain\ndk\ndk-build.cmd"
SQLITE_SOURCE_DIR="C:\source\xamarin-android\external\sqlite"
APP_ABI="armeabi-v7a x86""
exited with code 1.
As a follow-up to the related conversation in https://github.com/xamarin/xamarin-android/pull/2075, I tried a few steps to resolve this issue. …

[build] Add error for spaces in Android NDK path

---

src/Xamarin.Android.NUnitLite/NUnitLite/Runner/OutputWriters/NUnit2XmlOutputWriter.cs
tests/TestRunner.xUnit/NUnitXml.xslt

Context: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3806
Context: https://github.com/mono/NUnitLite/pull/12
Our on-device tests don't appear to be reporting properly in Jenkins:
INFO: Starting to record.
INFO: Processing NUnit-2.x (default)
INFO: [NUnit-2.x (default)] - 16 test report file(s) were found with the pattern 'xamarin-android/TestResult-*.xml' relative to '/Users/builder/jenkins/workspace/xamarin-android-pr-builder' for the testing framework 'NUnit-2.x (default)'.
WARNING: The file '/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/TestResult-Xamarin.Android.Bcl_Tests.nunit-Debug.xml' is an invalid file.
WARNING: At line 7 of file:/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/TestResult-Xamarin.Android. …

[bcl-tests] fix NUnit test result files for Jenkins

---

src/Xamarin.Android.Build.Tasks/Tasks/ConvertResourcesCases.cs

This commit does 3 changes to ConvertResourceCase, in order to
drastically reduces execution times. On my sample, execution times are
less than half of the original times:
- simplify the linq query used to get the `xmls` files (thx @jonathanpeppers)
- compute `reosurcedictionaries` out of the loop
- do not create a temp file as UpdateXmlResource already creates a temp
file. Change the return value of UpdateXmlResource to indicate if the
file has been changed or not.

[Xamarin.Android.Build.Tasks] reduce task time

---

Makefile

[The build][0] is [broken][1]!
msbuild /p:Configuration=Debug /p:AutoProvision=True /p:AutoProvisionUsesSudo=True /p:IgnoreMaxMonoVersion=False /v:diag /v:normal /binaryLogger:"…/xamarin-android//bin/BuildDebug/msbuild-`date +%Y%m%dT%H%M%S`-prepare-deps.binlog" build-tools/dependencies/dependencies.csproj
Microsoft (R) Build Engine version 15.3.0.0 (d15.3/e5db6a9 Wed May 10 05:29:34 EDT 2017)
Copyright (C) Microsoft Corporation. All rights reserved.
/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/MSBuild.dll /binaryLogger:…/xamarin-android/bin/BuildDebug/msbuild-20180824T102507-prepare-deps.binlog /p:Configuration=Debug /p:AutoProvision=True /p:AutoProvisionUsesSudo=True /p:IgnoreMaxMonoVersion=False /v:diag /v:normal …

[build] Explicitly create `bin/Build$(Configuration)`

---

src/Mono.Android/Mono.Android.targets

Fixes: http://work.devdiv.io/667174
Context: https://github.com/xamarin/java.interop/pull/360
Building `Java.Interop` in a similar fashion as `Mono.Android.dll`:
<NoStdLib>true</NoStdLib>
<TargetFrameworkIdentifier>MonoAndroid</TargetFrameworkIdentifier>
<TargetFrameworkVersion>v1.0</TargetFrameworkVersion>
<TargetFrameworkRootPath>$(XAInstallPrefix)xbuild-framework</TargetFrameworkRootPath>
<ItemGroup>
<Reference Include="mscorlib">
<HintPath>$(XAInstallPrefix)xbuild-frameworks\MonoAndroid\v1.0\mscorlib.dll</HintPath>
<Private>False</Private>
</Reference>
<Reference Include="System">
<HintPath>$(XAInstallPrefix)xbuild-frameworks\MonoAndroid\v1.0\System.dll</HintPath>
<Private>False</Private>
</Reference>
<Reference Include="System.Core"> …

[Mono.Android] build and reference non-PCL Java.Interop

---

Documentation/guides/messages/xa5300.md
src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs

In a0d4317b4 we added the `XA5300` error code, but there were a few
loose ends:
- The `*Handler` methods in `ResolveSdks` are completely unused. We
should remove them.
- `MonoAndroidHelper.RefreshAndroidSdk` should use the `XA5300` error
code.
I also expanded upon the `xa5300.md` documentation a bit.

[Xamarin.Android.Build.Tasks] missing error code in ResolveSdks

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunInstrumentationTests.cs
build-tools/scripts/TestApks.targets
tests/TestRunner.Core/LogWriter.cs
tests/TestRunner.Core/TestInstrumentation.cs

The LogWriter class used by both xUnit and NUnit test runners has configurable
minimum logging level which defaults to `Info`. It is not possible to configure
the level from command line, e.g. when starting the instrumentation. This commit
fixes the problem by introducing the `loglevel` parameter which can be sent to
the instrumentation using this syntax:
-e "loglevel info"
The acceptable log level values are (the strings are case-insensitive):
* Wtf
* Error
* Warning
* Info
* Debug
* Verbose
The default in the logger class is reasonable `Info`, however this commit
changes the value used by the `RunTestApks` target to `Verbose` in order to try
to figure out why the tests are failing on us when run on PR builders.

Make {x,n}unit runner logging level configurable from command line

---

Configuration.props
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/Adb.cs
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CreateAndroidEmulator.cs
build-tools/android-toolchain/android-toolchain.projitems
build-tools/scripts/TestApks.targets

This commit updates the Android emulator to the latest version
available (`4969155` a.k.a. v27.3.10), switches its system image to API 28,
makes sure that the emulator is started from the `emulator` subdir of the
Android SDK root (the binary in `tools` won't work anymore) and makes sure we
don't error out when we attempt to uninstall packages that don't exist in the
AVD.

Update emulator to the latest version, switch to API 28

---

src/Mono.Android/Test/Xamarin.Android.Net/HttpClientIntegrationTests.cs
src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs

HTTP headers `Server` and `User-Agent` must use space symbol as a separator instead of comma as defined in [RFC 7231](https://tools.ietf.org/html/rfc7231). Implemented this requirement similar to what have been done for NSUrlSessionHandler.cs in Xamarin.iOS.
See the issue #1931

Fixed the issue #1931

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/Files.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

[Xamarin.Android.Build.Tasks] fix incremental builds for Xamarin.Forms projects
@StephaneDelcroix noticed a build performance problem in Xamarin.Forms
projects:
- Build
- Build again with no changes
- Slow targets such as `_UpdateAndroidResgen` and `_GenerateJavaStubs`
run again!
The cause appeared to be this:
Building target "_UpdateAndroidResgen" completely.
Input file "obj/Debug/res/layout/tabbar.xml" is newer than output file "obj/Debug/R.cs.flag".
I modified the `CheckTimestamps` test to replicate this issue:
- Added Xamarin.Forms NuGet packages
- Added `Tabbar.axml` from the Xamarin.Forms template
This surfaced several problems with timestamps and Xamarin.Android
building incrementally...
In the `_GenerateJavaStubs` target, the `ConvertResourcesCases`
MSBuild task is not supplied a …

[Xamarin.Android.Build.Tasks] fix incremental builds for Xamarin.Forms projects

---

src/monodroid/CMakeLists.txt

So that `jnimarshalmethod-gen.exe` (and possible future desktop
utilities, which would use JVM) work.

[monodroid] Add java-interop-jvm.c to desktop libmonodroid

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://github.com/xamarin/xamarin-android/pull/2088
970da9ef was a good step towards "correctness" in building
incrementally in the following scenario:
- File | New Xamarin.Forms project | NetStandard library
- Build
- Change XAML
- Build
In this scenario, there is now a new target rising to the surface we
can improve:
276 ms  _CopyIntermediateAssemblies                1 calls
Looking at the target, it seems we could use the `CopyIfChanged` task
here more effectively. This task will automaticaly set the timestamps
of files that have been copied, and so we don't need any subsequent
`<ItemGroup />` or `<Touch />` elements. It was also touching *all*
files instead of just the ones that were changed.
After this change:
33 ms  _CopyIntermediateAssemblies                1 calls
The …

[Xamarin.Android.Build.Tasks] _CopyIntermediateAssemblies uses CopyIfChanged

---

src/Xamarin.Android.Build.Tasks/Tasks/Javac.cs
src/Xamarin.Android.Build.Tasks/Utilities/ZipArchiveEx.cs

I was thinking about a couple of the slower MSBuild tasks:
- `Javac`
- `CompileToDalvik`
One thing I noticed here was that `Javac` outputs a `classes.zip`
file, and `CompileToDalvik` consumes it. It also looked like we are
using `CompressionMethod.Default` as you would expect.
So why should we compress this file at all? It seemed that was work we
could just skip and things would work fine? Presumably `dx.jar` can
work with an uncompressed `classes.zip` file faster than a compressed
one?
So I made the following changes:
- Added an option to pass in the `CompressionMethod` in `ZipArchiveEx`
- Used `CompressionMethod.Store` for creating `classes.zip`
The results on a File | New Xamarin.Forms app looked great!
Before:
3443 ms  Javac                                      1 calls
11545 ms …

[Xamarin.Android.Build.Tasks] leave classes.zip uncompressed

---

tests/CodeBehind/UnitTests/BuildTests.cs

Each test now creates a copy of the test projects so that no two builds use the
same `bin` and `obj` subdirectories. This makes it possible to run all the tests
in parallel.

[Tests] Make CodeBehind tests parallelizable

---

src/Mono.Android/Android.Runtime/AndroidRuntime.cs
src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MonoDroidMarkStep.cs

Initialize the types map in `Prefill` method, updated by the
linker. Also pass the types count to the dictionary constructor to
improve performance and optimize memory allocation.
An example of `MagicRegistrationMap::Prefill` method, updated by the
linker, with the new code:
using System.Collections.Generic;
private static void Prefill ()
{
MagicRegistrationMap.typesMap = new Dictionary<string, int> (5);
MagicRegistrationMap.typesMap ["xatemplateaot.MainActivity"] = 0;
MagicRegistrationMap.typesMap ["Android.Runtime.UncaughtExceptionHandler"] = 1;
MagicRegistrationMap.typesMap ["Android.Views.View+IOnClickListenerImplementor"] = 2;
MagicRegistrationMap.typesMap ["Java.Lang.Thread+RunnableImplementor"] = 3;
MagicRegistrationMap.typesMap ["Java.Interop.TypeManager+JavaTypeManager"] = 4;
}

Lazy magic marshaling types map initialization

---

src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Xamarin.Android.Sdk.props
src/Xamarin.Android.Build.Tasks/Tasks/SetVsMonoAndroidRegistryKey.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj

In `Xamarin.Android.Sdk.props` we have some inline C# code for a
MSBuild task named `SetVsMonoAndroidRegistryKey`. Which is
understandable, since the code needed is so simple. But thinking about
it, MSBuild has to *compile* this code to run it. Which seems
inherently slower than if we compiled the code during our build.
Currently its entire parent target, `RedirectMonoAndroidSdkPaths`,
takes:
157 ms  RedirectMonoAndroidSdkPaths                1 calls
I moved this task inside `Xamarin.Android.Build.Tasks.dll`, and we
appear to get some improvements "for free":
76 ms  RedirectMonoAndroidSdkPaths                1 calls
I looked at some past logs, and there are some times where the
`RedirectMonoAndroidSdkPaths` target was taking over 200ms. I suspect
MSBuild might also have some caching …

[Xamarin.Android.Build.Tasks] precompile SetVsMonoAndroidRegistryKey

---

src/Xamarin.Android.Build.Tasks/Tasks/ConvertCustomView.cs
src/Xamarin.Android.Build.Tasks/Tasks/ConvertResourcesCases.cs
src/Xamarin.Android.Build.Tasks/Tasks/CopyAndConvertResources.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ConvertResourcesCasesTests.cs
src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs
src/Xamarin.Android.Build.Tasks/Utilities/MSBuildExtensions.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixed #2100
Currently `ConvertResourcesCases` is called twice on ALL
resources referenced by the project. This is terribly inefficient.
However it is required. The first pass is done before a `Compile`,
this fixes up the casing for things like drawables etc ready to
be processed by aapt. The second is done after `GenerateJavaStubs`
which happens AFTER the `Compile` step. This is to replace any
custom view references with the correct `{md5}.View` style references.
This is because we replace the normal readable namespace with an md5 hash.
The problem was that `ConvertResourcesCases` is doing a TON of
work it doesn't really need to do the second time around. For example
checking if it needs to lower case names of items. The second pass
really only needs to worry about custom views. In …

[Xamarin.Android.Build.Tasks] Add ConvertCustomView Task

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #2121
There were a number of performace issues with `_CreateAapt2VersionCache`.
First the wildcards were processing the ENTIRE `$(IntermediateOutputPath)`!
What they should have been doing was targeting specific
directories. I.e the root of `$(IntermediateOutputPath)` and
the directories under `$(IntermediateOutputPath)\lp`.
Second the target did not have a Condition to stop it running if
the versions matched, so that has been added.
However, even if a target is NOT run. MSbuild will still evaluate
the `PropertyGroups` and `ItemGroups` within the targets. So we
need to add `Conditon` on the `_CompiledFlataArchive` and
`_CompiledFlataStamp` items as well.
With these in place the time when this target is skipped is down
to 1ms.

[Xamarin.Android.Build.Tasks] `_CreateAapt2VersionCache` slow due to wildcard usage

---

src/Mono.Android/Java.Interop/TypeManager.cs

This partially reverts commit 6418edce
Context: http://work.devdiv.io/675738
Commit 6418edce breaks the Android Designer, because the
Android Designer doesn't generate `typemap.jm` and `typemap.mj` files,
which `monodroid_typemap_java_to_managed()` uses in order to perform
the Java->managed type mapping.  Without an appropriate `typemap.jm`
file, and with the removal of the Reflection (-ish)-based fallback
code in commit 6418edce, there is no way within the Android Designer
to associate a Java type with a corresponding C# type, for e.g. custom
("new") `View` subclasses written in C# or outside of `android.jar`.
The d15-9 branch hit the same problem, and likewise reverted this
change in commit 91a3fe52.
Instead of *fully* reverting 6418edce, "revert" it *on Desktop*.
When running on an …

[Mono.Android] Use package fallback in GetJavaToManagedType on desktop

---

src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs

Reviewing our codebase, we found a place where the `BuildApk` task was
calling an overload for `MonoAndroidHelper.IsReferenceAssembly`.
This presented two problems:
1. It was using the `InMemory` option
2. We were not calling `Dispose()`!
Case No.1 was bad, since we basically load every assembly into memory!
foreach (ITaskItem assembly in ResolvedUserAssemblies) {
if (MonoAndroidHelper.IsReferenceAssembly (assembly.ItemSpec)) {
//...
foreach (ITaskItem assembly in ResolvedFrameworkAssemblies) {
if (MonoAndroidHelper.IsReferenceAssembly (assembly.ItemSpec)) {
Likewise, we need to call `Dispose` here, since a lock could be held
on the file here on Windows.
The changes here made `BuildApk` slower (and more correct!), but the
overall build time better.
Before:
5890 ms  BuildApk …

[Xamarin.Android.Build.Tasks] should Dispose AssemblyDefinition

---

README.md

Updates the https://github.com/xamarin/xamarin-android#downloads section to include our most recent released OSS builds and updates the version on the current master builds.

Add 15.8, 15.9, and update master version number to downloads section.

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/Adb.cs
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CheckAdbTarget.cs
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunInstrumentationTests.cs
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunUITests.cs
build-tools/scripts/BuildEverything.mk
build-tools/scripts/TestApks.targets
src/Mono.Android/Test/Mono.Android-Tests.csproj
src/Mono.Android/Test/Mono.Android-Tests.projitems
src/Mono.Android/Test/Properties/AndroidManifest.xml
tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Properties/AndroidManifest.xml
tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj
tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.projitems
tests/locales/Xamarin.Android.Locale-Tests/Properties/AndroidManifest.xml
tests/locales/Xamarin.Android.Locale-Tests/Xamarin.Android.Locale-Tests.csproj
tests/locales/Xamarin.Android.Locale-Tests/Xamarin.Android.Locale-Tests.projitems

The `leeroy` make target failed with a "file not found" exception while
attempting to invoke the `cross-arm` crosscompiler and the reason for this was
that `cross-arm` was never built because of the `armeabi-v7a` target missing in
the `ALL_AOT_ABIS` make variable in the `build-tools/scripts/BuildEverything.mk`
file.
This commit adds the missing target architecture and fixes the build.

Fix AOT build

---

src/Xamarin.Android.Build.Tasks/Tasks/ConvertResourcesCases.cs
src/Xamarin.Android.Build.Tasks/Tasks/CopyAndConvertResources.cs

Commit 1886e6f1 added new methods to log warnings and errors for
resource files. However the warning changes were calling the
`FixupResourceFilenameAndLogCodedError` method.
Lets call `FixupResourceFilenameAndLogCodedWarning` where it should
be called instead.

[Xamarin.Android.Build.Tasks] Fix usage of wrong method to log warning.

---

build-tools/download-bundle/download-bundle.targets

Around 2018-Aug-15, the Jenkins config for xamarin-android was changed
in a way which [altered the URL for where files are uploaded][0] so
that it contained `${BUILD_NUMBER}`, which is a value which increments
on every build.  A consequence of this change is that the bundle could
no longer used, as it could no longer be *found*, as there is no way
of knowing what `${BUILD_NUMBER}` could possibly be, which in turn
caused increased build times for PRs and master builds, as mono would
now always need to be rebuilt.
On 2018-Sep-7, the [Jenkins config was updated][1] to remove
`${BUILD_NUMBER}` from the URL, allowing for "static" URLs which works
with our bundle mechansism.
With the removal of `${BUILD_NUMBER}`, we're good, right?  The bundle
should now be used?
Not so much.  One other part …

[download-bundle] Update mono bundle download URL

---

Documentation/guides/BuildProcess.md
Documentation/guides/LayoutCodeBehind.md

Context: https://github.com/xamarin/xamarin-android/pull/1671
Context: https://github.com/xamarin/xamarin-android/issues/1669
The new Bindings and Code-Behind features were breaking some existing
projects, so the default value of `$(AndroidGenerateLayoutBindings)` was
changed from `True` to `False`.  This commit adjusts the documentation
accordingly so that users will know how to enable those features if they
want to try them.  This new wording can be changed back once the default
value of `$(AndroidGenerateLayoutBindings)` is switched back to `True`.

[docs] Update $(AndroidGenerateLayoutBindings) info

---

build-tools/scripts/TestApks.targets

We currently fail to kill the emulator if any of the steps executing APK tests
fail. This is because the failed task stops execution of all the other targets
defined in that file. In effect we leave running instances of the emulator on
the build bots, should such a failure happen.
This diff adds `ContinueOnError="ErrorAndContinue" to each task in the target
file so that we are sure to hit the `ReleaseAndroidTarget` target no matter what.

[Tests] Make sure emulator is killed after tests fail

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs

Looking at `ResolveAssemblies`, I noticed a lot of LINQ usage that
could be simplified.
We were using `HashSet<string>` that contains a list of all
assemblies, and the following code:
if (!topLevel && assemblies.All (a => new AssemblyNameDefinition (a, null).Name != assembly.Name.Name))
assemblies.Add (fullPath);
This was called from a *recursive* function and needlessly calls
`new AssemblyNameDefinition ().Name` for every other assembly...
Roughly a O(N^2) operation.
So I changed the `HashSet<string>` to be a `Dictionary<string,
string>`, where the "key" is the `assembly.Name.Name` and the value
the full path to the assembly.
I also fixed up usage of `assembly.MainModule.FullyQualifiedName`,
which was deprecated mentioning to use `FileName` instead.
Lastly, I fixed up several LINQ …

[Xamarin.Android.Build.Tasks] simplify LINQ in ResolveAssemblies

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/CreateAndroidEmulator.cs
build-tools/scripts/TestApks.targets

The `CreateAndroidEmulator` task calls the Android SDK utility
`avdmanager` (which replaced the former `android` tool in creation of AVDs) in
order to create an instance of AVD used by our APK tests. The tool has the habit
of asking a question whether or not the user wants to create a custom hardware
profile for the emulator and it cannot be persuaded to not ask that question.
So, in order to be polite and answer it, we loop after the process has started
and keep sending it newline characters which, at some point, answer the question
and everybody is happy.
The process works most of the time but, unfortunately, it requires us to rely on
`System.Diagnostics.Process.HasExited` property which is *not* a reliable way to
test whether the process went away, *especially* right after it quit. And …

Make Android emulator creation task slightly less racy

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunInstrumentationTests.cs
build-tools/scripts/BuildEverything.mk

We've been dealing with a head-scratching annoyance: `.apk` test would
execute, pass, and have their `TestResults.xml` files extractable when
the PR builds run the `.apk` tests, but *not* when `master` does.
This makes it difficult to know whether or not we've broken anything.
One "interesting" observation we've had is that the paths *differ* on
the "downloadable" vs. "undownloadable" builds.  For example,
[master build #1166][0] uses an internal storage path:
RunTestApks
...
Executing: /Users/builder/android-toolchain/sdk/platform-tools/adb   shell run-as Mono.Android_Tests cat "/data/user/0/Mono.Android_Tests/files/.__override__/TestResults.xml"
writing stdout to file: /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/tests/../bin/TestRelease/TestResult-Mono.Android_Tests. …

[build] Build Xamarin.Android.NUnitLite.dll for API-28

---

Documentation/guides/messages/README.md
Documentation/guides/messages/xa0115.md
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://github.com/xamarin/xamarin-android/issues/2173
Context: https://github.com/xamarin/xamarin-android/pull/2106
This commit checks for the presence of the now unsupported armeabi architecture in the `$(AndroidSupportedAbis)` property by using a conditional error in a new target.  Another option could be to to change the error to a warning and *ignore* the ";armeabi;" substring in the
property.  But that seems a little risky for cases where users might not notice the warning.  They would probably be surprised later when they discovered that their APKs did not contain armeabi support.
I also debated on whether it would be better to move this check into the `BuildApk` task.  I decided that since it is just a small test to look for a substring in an MSBuild property, using a …

[Xamarin.Android.Build.Tasks] Add coded error for armeabi

---

build-tools/scripts/BuildEverything.mk

We've been dealing with a head-scratching annoyance: `.apk` test would
execute, pass, and have their `TestResults.xml` files extractable when
the PR builds run the `.apk` tests, but *not* when `master` does.
This makes it difficult to know whether or not we've broken anything.
One "interesting" observation we've had is that the paths *differ* on
the "downloadable" vs. "undownloadable" builds.  For example,
[master build #1166][0] uses an internal storage path:
RunTestApks
...
Executing: /Users/builder/android-toolchain/sdk/platform-tools/adb   shell run-as Mono.Android_Tests cat "/data/user/0/Mono.Android_Tests/files/.__override__/TestResults.xml"
writing stdout to file: /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/tests/../bin/TestRelease/TestResult-Mono.Android_Tests. …

[build] Build Xamarin.Android.NUnitLite.dll for API-28 (#2182)

---

src/Mono.Android/Mono.Android.csproj
src/Mono.Android/Test/Xamarin.Android.Net/AndroidClientHandlerTests.cs
src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs
src/Mono.Android/Xamarin.Android.Net/OldAndroidSSLSocketFactory.cs

Context: https://github.com/xamarin/xamarin-android/issues/1615
It turns out that the older platforms do support TLS 1.1 and 1.2 protocols but
that they don't enable it by default. Thanks to code provided by
https://github.com/gameleon-dev in the issue linked to above we now support it
too.
Updated the TLS 1.2 tests to enable them on platforms >= 16

Enabled TLS 1.1 and 1.2 support on platforms >= 16 and <= 20

---

build-tools/scripts/BuildEverything.mk
src/Xamarin.Android.NUnitLite/Gui/Instrumentations/TestSuiteInstrumentation.cs

Context: 24158d08be1db5a45dfd2ebfe8c05a85bfa8af00
Fixes: https://github.com/xamarin/xamarin-android/issues/2189
What do we want?  A reliable way to get `TestResults.xml` files off of
the Android target device, so that we can get unit test results.
A reliable way that works on a variety of Android API levels and their
corresponding emulators.
(What do we want?  ***GREEN BUILDS***.)
The problem with 24158d08 is twofold:
1. When building an app with a `$(TargetFrameworkVersion)` less than
`v9.0` (`$(lastword $(API_LEVELS))`), there is a build warning:
warning XA0105: The $(TargetFrameworkVersion) for 'Foo' (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v5.0). You need to increase the $(TargetFrameworkVersion) for your project.
2. When *running*/using …

[build] Build Xamarin.Android.NUnitLite.dll for API-10

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/2183
Context: https://github.com/xamarin/xamarin-android/issues/2177
Context: https://github.com/xamarin/xamarin-android/pull/1878
Context: http://work.devdiv.io/661455
We are seeing reports of issues related to VS for Mac displaying
`Updating Android Resources...` in the title bar, and a build running
at the same time.
This is effectively running two commands at the same time:
msbuild YourAndroid.csproj /t:UpdateAndroidResources
msbuild YourAndroid.csproj /t:Build
In the case such as #2183, we get the failure:
Task "RemoveDirFixed"
Xamarin.Android.Common.targets(3042,2): error : Directory /Users/builder/agent/_work/r1/a/XQA.VSMac/XQA.VisualStudioMac/TestResults/26ff4d25/TestAndroidEnableAOTEnterprise/Temp/DroidApp/DroidApp/obj/Relea …

[Xamarin.Android.Build.Tasks] skip _CleanIntermediateIfNuGetsChange on first build

---

tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/Config.cs.in
tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/EmbeddedDSO-UnitTests.csproj

Getting a compiler error on Windows for `obj\Debug\Config.cs`, the
generated code is:
public static readonly string ZipAlignPath = Path.Combine ("C:\Users\myuser\android-toolchain\sdk", "build-tools", "28.0.0", "zipalign.exe");
Fixes include:
- Use the `@` symbol before the base path in `Config.cs.in`
- Use `Inputs` and `Outputs` on the `Prepare` target so it doesn't run
all the time
- Fix the double slash, since `$(IntermediateOutputPath)` always has a
trailing slash after the core MSBuild targets are imported
- Fixed a tab character

[tests] fix the Windows build for DSO tests

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
src/Xamarin.Android.Build.Tasks/Utilities/Files.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/2198
In 970da9efb, I fixed various issues with incremental builds.
But one scenario has a regression on MacOS:
- Add the `Xamarin.Android.Wear` NuGet to a new project
- Build
Encounter an error such as:
error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly.
error MSB4018: System.UnauthorizedAccessException: Access to the path "/Users/peter/Projects/TestWearab/TestWearab/obj/Debug/lp/15/jl/proguard.txt" is denied.
error MSB4018:   at System.IO.File.SetLastWriteTime (System.String path, System.DateTime lastWriteTime) [0x0002b] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/File.cs:488
error MSB4018:   at …

[Xamarin.Android.Build.Tasks] fix for readonly files on MacOS

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/2193
I have been able to reproduce a #deletebinobj bug with the following
steps:
1. `File | New Project | Android App (Xamarin) | Tabbed App`, set
`Minimum Android Version` to `Android 5.0 (Lollipop)`
2. Build
3. Add a new `TextView` to `Resources\layout\activity_main.axml`, with
an id of `textView1`
4. Build and Deploy
Get a crash at runtime:
Android.Views.InflateException: Binary XML file line #1: Error inflating class android.support.design.widget.BottomNavigationView occurred
A `Rebuild` fixes the problem, and the app starts correctly again.
After comparing `obj` directories from before and after, I noticed
`obj\Debug\android\src\android\support\compat\R.java` was missing the
field for `R.id.textView1`!
public static int …

[Xamarin.Android.Build.Tasks] deletebinobj fix for resources

---

build-tools/scripts/Configuration.Java.Interop.Override.props

Adds xamarin/xamarin-android-tools to xamarin/Java.Interop.
Override `$(XamarinAndroidToolsDirectory)` so that the Java.Interop
build will use xamarin-android's `external/xamarin-android-tools` in
precedence/priority over the commit that Java.Interop uses, in a
similar fashion as 9bc51aed and Cecil.

Bump to xamarin/Java.Interop:master@32f0c9cf

---

src/Xamarin.Android.Build.Tasks/Tasks/Desugar.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/2143
Context: https://github.com/xamarin/xamarin-android/issues/1639
Xamarin.Android's current implementation of desugar runs a command
such as:
java -jar desugar_deploy.jar 
--bootclasspath_entry ~\android-toolchain\sdk\platforms\android-28\android.jar 
--min_sdk_version 11 
--classpath_entry xamarin-android\bin\Debug\lib\xamarin.android\xbuild-frameworks\MonoAndroid\v9.0\mono.android.jar 
--input Lambda.jar 
--output obj\Debug\android\bin\desugared\14-57-25-90-94-EE-16-09-B8-68-88-BC-9D-FC-6C-89Lambda.jar
However, certain jars are failing with messages such as:
Exception in thread "main" java.lang.TypeNotPresentException: Type okhttp3.Interceptor not present
Or another example:
Error: java.lang.TypeNotPresentException : Type …

Added --classpath_entry for Desugar

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://github.com/xamarin/xamarin-android/pull/2088
Context: https://github.com/xamarin/xamarin-android/pull/2129
Context: https://github.com/xamarin/xamarin-android/pull/2199
In 4deec52e, I fixed the #deletebinobj problem we discovered.
However...
I introduced a regression to incremental builds, I noticed that the
`_CompileJava` target is now running on a second build with no
changes. Third build? oddly it gets skipped...
It seems to be due to our use of flag files:
1. `_UpdateAndroidResgen` updates `R.cs.flag` and uses the file as an
output
2. `_GenerateJavaDesignerForComponent` now uses `R.cs.flag` as an
input
3. `_GenerateJavaStubs` *also* updates the timestamp on `R.cs.flag`.
This was added in 970da9ef, as a workaround for our two instances
of `ConvertResourcesCases`.
4. …

[Xamarin.Android.Build.Tasks] fix _CompileJava running too often

---

src/Mono.Android/Test/Xamarin.Android.Net/AndroidClientHandlerTests.cs
src/Mono.Android/Test/Xamarin.Android.Net/HttpClientIntegrationTests.cs

Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1180/testReport/junit/(root)/AndroidClientHandlerTests/Mono_Android_Tests__Xamarin_Android_NetTests_AndroidClientHandlerTests_Sanity_Tls_1_2_Url_WithMonoClientHandlerFails___Release/
`AggregateException`, like `Exception`, can be ~anything, and
represent an *actual failure* that needs to be fixed...or a
(hopefully) transient network failure that will disappear the next
time the test is run.
Which brings us to
`AndroidClientHandlerTests.Sanity_Tls_1_2_Url_WithMonoClientHandlerFails()`:
this test has been failing more often of late, but *we don't know
why*.  Our *guess* is that it's a transient network failure, as
*sometimes* the test works, but even if we assume that's the case,
we're still getting these …

[Mono.Android-Tests] Improve AggregateException logging

---

tools/xabuild/XABuild.cs

When we first implemented `xabuild.exe`, we though it was helpful to
see the configuration file that was used if the build failed.
However, it mostly seems unnecessary now, since:
- All variables used are printed in diagnostic or binary log files.
They show up as properties at the beginning of the build.
- We are all much more accustomed to looking through binary log files
now anyway. Our build even saves them!
I very much dislike having to scroll *way* up my console window when a
build fails!
Here is an example of what the output *used* to look like:
> .\bin\Debug\bin\xabuild /asdfsadfsdadf
Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
MSBUILD : error MSB1001: Unknown switch.
Switch: /asdfsadfsdadf
For …

[xabuild] we don't need config file in stdout

---

src/Xamarin.Android.Build.Tasks/Tasks/GetJavaPlatformJar.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ResolveSdksTaskTests.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/2200
In 93ddf96f, I split up the `ResolveSdks` MSBuild task.
In doing that I broke a situation:
- `msbuild /p:AndroidUseLatestPlatformSdk=true /p:AndroidSdkDirectory="C:\DoesNotExist" MyApp.csproj`
- This works in 15.8 stable, but not 15.9 or master where 93ddf96f is
applied
The error message is also rather unpleasant, due to an unhandled
exception:
(_SetLatestTargetFrameworkVersion target) ->
error MSB4018: The "ResolveAndroidTooling" task failed unexpectedly.
error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\DoesNotExist\platforms'.
The cause, is how `$(AndroidSdkDirectory)` is handled as an output:
<Output TaskParameter="AndroidSdkPath" PropertyName="AndroidSdkDirectory" …

[Xamarin.Android.Build.Tasks] restore behavior for custom $(AndroidSdkDirectory)

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #2218
There was a typo in the property group definition for
`AndroidAapt2LinkExtraArgs`. It was `AndroidAap2LinkExtraArgs`.
As a result the extra args would never be picked up.

[Xamarin.Android.Build.Tasks] Fix typo for `AndroidAapt2LinkExtraArgs`

---

src/Xamarin.Android.Build.Tasks/Resources/MonkeyPatcher.java

Commit 3f360c09 introduced the `MonkeyPatcher` but it seems
there was a typo in it. This commit fixes that issue.

[Xamarin.Android.Build.Tasks] Fix typo in MonkeyPatcher.

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://docs.microsoft.com/en-us/visualstudio/msbuild/resolveassemblyreference-task?view=vs-2017
Context: https://twitter.com/KirillOsenkov/status/1043725067081764865
Kirill added a new analyzer to the Windows binlog viewer, noting
`$(AssemblySearchPaths)` that are unused during a build.
Looking at what we are using currently, it reports:
Unused AssemblySearchPaths locations
{AssemblyFolders}
{AssemblyFoldersFromConfig:C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\AssemblyFolders.config,v9.0}
{CandidateAssemblyFiles}
{Registry:Software\Microsoft\MonoAndroid,v9.0,AssemblyFoldersEx}
bin\Debug\
Luckily, we already had MSBuild logic in place to remove `{GAC}` from
this list.
But we certainly are probing search paths that are nonsensical for …

[Xamarin.Android.Build.Tasks] optimize $(AssemblySearchPaths)

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://github.com/xamarin/xamarin-android/pull/2204
In d6009efa, I fixed the issue if `$(AndroidSdkDirectory)` is set to a
non-existent directory.
However, downstream in `monodroid`, there is a test project with an MSBuild target such as:
<Exec Command="&quot;$(JavaSdkDirectory)\bin\javac&quot; -etc" />
`/p:JavaSdkDirectory` is not passed in here at the command line or
imported, and so `/bin/javac` is attempted to be used--which won't
quite work...
This brings up an important point.
`$(AndroidSdkDirectory)`, `$(AndroidNdkDirectory)` and
`$(JavaSdkDirectory)` were public properties that were set if blank.
So we can't just remove them! There could be unknown projects, NuGet
packages, etc. relying on them.
So I think the fix here, is to set these properties if they are blank. …

[Xamarin.Android.Build.Tasks] set $(AndroidSdkDirectory) if blank

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

This commit adds a custom view to the `SwitchBetweenDesignTimeBuild`
test. This is so we can make sure that we are not running targets
like `_UpdateAndroidResgen` even if the custom view is updated
as part of `_GenerateJavaStubs`.

[Xamarin.Android.Build.Tests] Add CustomView to SwitchBetweenDesignTimeBuild

---

.gitmodules

Context: https://github.com/xamarin/xamarin-android/commit/2b863c31064ded67bb5fb00cbcf3f5911d158514
Context: https://github.com/xamarin/xamarin-android/commit/7f9a3657b673c6b78797e7c75ba927922c6e10b1
Context: https://github.com/xamarin/xamarin-android/commit/acdbe90fd84d08e94f263ffbb5613cf1644c07a2
Context: https://github.com/xamarin/xamarin-android/commit/29d778a8db91c759eb6ea9b7867434b263a15789
Context: ...
Every time @MSylvia branches our products for release, we get a
unnecessarily large change to `.gitmodules`, for two reasons:
1. @MSylvia's tooling uses spaces `    ` instead of tabs for
indentation, and
2. @MSylvia's tooling *sorts submodules*.
This turns a conceptually simple change -- update branch names -- into
a very *noisy* change, as the `.gitmodules` contents are re-ordered …

[git] Re-format `.gitmodules`

---

src/monodroid/jni/monodroid-glue.c

The `d_name` property on the directory structture is not
a `char*` on windows but a `wchar_t`. As a result it might
not behave as expected when running on the desktop.
we should use `utils.utf16_to_utf8` to convert the values
over to a format which `copy_file_to_internal_location` can
take.

[monodroid] Convert path to utf8 on windows.

---

Xamarin.Android-Tests.sln
build-tools/scripts/RunTests.targets
src/Xamarin.Android.Build.Tasks/Tasks/MakeBundleNativeCodeExternal.cs
tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-Tests/Xamarin.Android.MakeBundle-Tests.csproj
tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/BuildTests.cs
tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/Config.cs.in
tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/Properties/AssemblyInfo.cs
tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/Xamarin.Android.MakeBundle-UnitTests.csproj
tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/Xamarin.Android.MakeBundle-UnitTests.targets
tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/packages.config

Android API23 and newer requires that any shared library used by an application
which targets API23 or newer has its soname set in the ELF header or otherwise
the OS will refuse to load it:
09-18 08:07:27.687 10698 10698 W linker  : Warning: "/data/app/Mono.Android_Tests-O9bT_-xHyd26brpmOI9RNg==/lib/x86/libmonodroid_bundle_app.so" has no DT_SONAME (will use libmonodroid_bundle_app.so instead) and will not work when the app moves to API level 23 or later (https://android.googlesource.
com/platform/bionic/+/master/missing-soname-enforced-for-api-level-23) (allowing for now because this app's target API level is still 22) (TaskId:201)
This commit fixes the problem by passing `-soname libmonodroid_bundle_app.so` to
the linker when building the bundle.

Make sure app bundle has soname set

---

build-tools/scripts/dependencies/debian-common.sh

Linux PR builders run on Debian instead of Ubuntu and because of an omission in
the Mono SDKs makefiles the bots tried to use MXE instead of the mingw
environment provided by the distribution. The Mono bump includes a fix for this.

Bump Mono to fix builds on the Linux PR builders

---

src/Xamarin.Android.Build.Tasks/Tasks/ConvertCustomView.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ConvertResourcesCasesTests.cs
src/Xamarin.Android.Build.Tasks/Utilities/XDocumentExtensions.cs

While investigating a Designer Build breakage in monodroid we
hit an issue where the `ConvertCustomView` task was updating
a file even if nothing had changed in it.
As a result this causes a problem because we end up in a loop
where `_GenerateJavaStubs` and `_UpdateAndroidResgen` and the
designer target all update the same files over and over.
So lets try to avoid that by only updating the custom view
if the file actaually changes. However lets also keep the
modified date for the file which was written by
`_UpdateAndroidResgen`. This will ensure we dont keep running
the same targets over and over.

[Xamarin.Android.Build.Tasks] Only update the CustomView if the document changed.

---

src/mono-runtimes/mono-runtimes.targets

If one tries to build a release version of XA (`make CONFIGURATION=Release`) but
the tree is not configured to build any of the cross compilers, the build will
fail when trying to strip the non-existing runtime with an error similar to:
Copying file from ".../external/mono/sdks/out/android-host-Linux-release/bin/mono" to ".../bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/Linux/mono".
Touching ".../bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/Linux/mono".
""  ".../bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/"
/bin/sh: 2: /tmp/tmp755872b2be394779865a2aa8606e7deb.exec.cmd: : Permission denied
This is because the condition on the `Exec` task doesn't take into account the
possibility that there are no cross runtimes built.

Fix release build when no cross runtimes are present

---

src/libzip/libzip.projitems

Xcode 10.0 deprecates compiling of 32bit applications.
The macOS 10.14 SDK no longer contains support for compiling
32-bit applications. If developers need to compile for i386, Xcode
9.4 or earlier is required. (39858111)
So just build 64bit everywhere.

[libzip] Remove building of i386 on MacOS.

---

Documentation/guides/messages/xa0116.md
src/Xamarin.Android.Build.Tasks/Tasks/CopyResource.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/CopyResourceTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj

Context: https://github.com/xamarin/xamarin-android/pull/609
In a recent change, we removed `StubApplication.java`, but downstream
in `monodroid` we had MSBuild tasks that still expected the file to
exist.
We got an error such as:
Xamarin.Android.Common.Debugging.targets(319,2): error MSB4018: The "CopyResource" task failed unexpectedly.
Xamarin.Android.Common.Debugging.targets(319,2): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object
Xamarin.Android.Common.Debugging.targets(319,2): error MSB4018: at Xamarin.Android.Tasks.CopyResource.Run (System.Reflection.Assembly assm, System.String ResourceName, System.String OutputPath, Microsoft.Build.Utilities.TaskLoggingHelper Log) [0x00058] in <5782345e71104ee895a29d54bde93c43>:0 …

[Xamarin.Android.Build.Tasks] CopyResource should fail with an error code

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BuildHelper.cs

Some of the tests in monodroid are failing because
it was assumed that the test `Root` folder would be
in the project output directory.
However with the new `XAConfig` file changes in XA that
is no longer the case. As a result some of the unit tests
fail because it is looking for files in the wrong place.
This commit changes the `Root` property of the `ProjectBuilder`
to use the one from `XAConfig`.

[Xamarin.Android.Build.Tests] Fix BuildHelper Root

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RenameTestCases.cs

Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1193/
The hope (dream?) behind 0ec00e12 was that if (when) a `.apk` test had
some unspeakable error occur -- one in which the `TestResults*.xml`
file wasn't generated -- then `<RenameTestCases/>` would generate a
"stub" error XML file so that we'd see an *actual* error in the
Jenkins job status page.
How'd we do?
Not good: [Job #1193][0] had a failure when running
`Xamarin.Android.Locale_Tests-Signed.apk` (currently unexplored),
which caused our "stub error XML file" to be generated.  The result is
that Jenkins *did not report any errors*.
Doh!
Why?  Cast our memory back to 23b2642e, and we can see why:
$ xsltproc nunit-1.0-to-junit-2.xsl TestResult-Xamarin.Android.Locale_Tests-Debug.xml
<?xml …

[Xamarin.Android.Tools.BootstrapTasks] Emit proper error XML

---

build-tools/create-vsix/source.extension.vsixmanifest

The valid ranges will be controlled by Willow, rather than the VSIXes themselves.

Remove top version range from prerequisites

---

Documentation/guides/messages/README.md
Documentation/guides/messages/xa0117.md
src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs

Add a new Warning XA0117 which will inform users if they are
using a `$(TargetFrameworkVersion)` which is going to be
deprecated in the future.
In d16 out minimum supported version will be v4.4 (19).
v2.3 (10) will be removed.

[Xamarin.Android.Build.Tasks] Add XA0117 TargetFrameworkVersion is deprecated.

---

Documentation/guides/messages/README.md
Documentation/guides/messages/xa0115.md
Documentation/guides/messages/xa0116.md
Documentation/guides/messages/xa0117.md
src/Xamarin.Android.Build.Tasks/Tasks/ResolveAndroidTooling.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Commit b1d81460 introduced a new error XA0115. This error is raised
if the user has `armeabi` in their `$(AndroidSupportedAbis)`.
We need to do a similar thing in the d15-9 release. However it should
not be an error but a warning. It will turn into an error for the next
release.
This commit also introduces a warning if the user is using a
`$(TargetFrameworkVersion)` less than 19. These platforms have
a very low market share and will be slowly removed from our
build system going forward. This warning is to make sure that users
get a heads up before their application starts failing to build.

[Xamarin.Android.Build.Tasks] Backport XA0115 error but make it a warning.

---

.gitmodules
Configuration.props
build-tools/scripts/cmake-common.props
src/sqlite-xamarin/CMakeLists.txt

The full list of changes since our previous release 3.9.2 can be found here:
https://sqlite.org/changes.html
Additionally, bump the base NDK API platform we use to build native code to 14.
This is in line with the API level Mono runtime is built with as well as with
the minimum supported API in newer NDKs. Making the change part of this commit
because it also affects the way SQLite is built.

Update SQLite to version 3.52.2

---

src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/2202
Context: https://forums.xamarin.com/discussion/96028/android-documentsprovider-intent-filter
When generating `AndroidManifest.xml` we currently fail to take into account any
instances of the `IntentFilterAttribute` custom attribute decorating all the
content provider classes (that is ones with another custom attribute -
`ContentProviderAttribute`). This forces the developer to manually edit the
manifest to add appropriate entry for the provider and its intent filters.
This commit removes the limitation by making sure our manifest generator looks
for and processes the `IntentFilter` custom attribute.

Don't ignore IntentFilter attribute on content provider classes

---

Documentation/guides/messages/README.md
src/Xamarin.Android.Build.Tasks/Tasks/CalculateLayoutCodeBehind.cs
src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs
src/Xamarin.Android.Build.Tasks/Tasks/GetAdditionalResourcesFromAssemblies.cs
src/Xamarin.Android.Build.Tasks/Tasks/ReadAdditionalResourcesFromAssemblyCache.cs
src/Xamarin.Android.Build.Tasks/Tasks/ReadImportedLibrariesCache.cs
src/Xamarin.Android.Build.Tasks/Tasks/ReadLibraryProjectImportsCache.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs

* I investigated the code paths that led into the `LogWarning()` in
`GenerateResourceDesigner.AddRename()`.  I could not find any way to
hit that message with the current code.  Moreover, the only reports of
the message I could find on the web were from capitalization
mismatches, and those are now explicitly ignored by the use of the
`StringComparison.OrdinalIgnoreCase` argument in the call to
`string.Compare()`.  Since this message does not currently indicate an
actionable problem, I changed it from a warning to a debug message.
* Neither of the warnings in
`GetAdditionalResourcesFromAssemblies.AddAttributeValue()` is
actionable for Xamarin.Android app developers.  The first warning can
only arise if a new attribute name has …

[Xamarin.Android.Build.Tasks] Add more warning codes

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/CopyResourceTests.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs

The instant run fast deployment modifications are only enabled if the developer is targeting API 19 or above. So we should only include the `ResourcePatcher` and `MonkeyPatcher` files if the same conditions are met.

[Xamarin.Android.Build.Tasks] `ResourcePatcher` for API 19+.

---

src/monodroid/jni/dylib-mono.cc
src/monodroid/jni/monodroid-glue.cc

Recent move of libmonodroid to C++ broke the
`monodroid_dylib_mono_init` usage with *NULL* libmono_path parameter,
which is needed at
https://github.com/xamarin/java.interop/blob/master/src/java-interop/java-interop-gc-bridge-mono.c#L266
That led to the following crash:
Assertion failed: (directories), function load_dso_from_specified_dirs, file /Users/rodo/git/xa5/src/monodroid/jni/monodroid-glue.cc, line 761.
Stacktrace:
at <unknown> <0xffffffff>
at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_gc_bridge_new (intptr) [0x00002] in <fe331788190c4039ae28220ef452fac0>:0
at Java.Interop.MonoRuntimeValueManager.OnSetRuntime (Java.Interop.JniRuntime) [0x0002c] in <fe331788190c4039ae28220ef452fac0>:0
at Java.Interop.JniRuntime.SetRuntime<T_REF> (T_REF) [0x00012] in …

[monodroid] Fix regression in monodroid_dylib_mono_init

---

src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Compile.cs
src/Xamarin.Android.Build.Tasks/Tasks/Aapt2Link.cs
src/Xamarin.Android.Build.Tasks/Tasks/ComputeHash.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Aapt2Tests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #2205
The problem here is on the first build the compiled.flata archive only contains
```
Archive:  compiled.flata
Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
400  Stored      400   0% 01-01-1980 01:00 8ade13a7  values_goog_svcs_json.arsc.flat
--------          -------  ---                            -------
400              400   0%                            1 file
```
which suggested that something is overwriting the compiled.flata archive created by `_CompileResources`.
The actual problem. The `_CompileAndroidLibraryResources` target is processing the directory for the `GooglePlayServicesJson` items. And as a result its creating a compiled.flata archive in the same place as the main Resource …

[Xamarin.Android.Build.Tasks] Merge local and dependencies Resources conflicting

---

src/sqlite-xamarin/CMakeLists.txt

Fixes: https://github.com/xamarin/xamarin-android/issues/2271
Context: https://github.com/xamarin/xamarin-android/commit/673757d85ce9d3d14745f01d3c34a6c24e00126e
Context: https://cmake.org/cmake/help/v3.3/command/file.html
`cmake` mandates a uniform way of presenting filesystem paths across
all the operating systems it supports - it requires that path segments
are separated with the `/` character.
In 673757d8, we faced a similar problem, but used a string replace as
a fix:
string(REPLACE "\\" "/" MY_PATH ${MY_PATH})
There is a proper, more "portable" way to do this, such as:
file(TO_CMAKE_PATH "${MY_PATH}" MY_PATH)
Using this for `SQLITE_XAMARIN_SOURCES` fixes the sqlite build on
Windows.

[build] CMakeLists.txt fixes for sqlite on Windows

---

build-tools/scripts/dependencies/debian-common.sh

Those packages aren't necessary to build Xamarin.Android but their installation
may cause removal of other compilers, for instance gcc/g++ cross-compilers for
architectures different than the host one.

[Linux build] Remove {gcc,g++}-multilib packages from dependencies

---

src/monodroid/CMakeLists.txt
src/monodroid/jni/android-system.cc
src/monodroid/jni/android-system.h
src/monodroid/jni/dylib-mono.cc
src/monodroid/jni/globals.cc
src/monodroid/jni/globals.h
src/monodroid/jni/monodroid-glue-internal.h
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/osbridge.cc
src/monodroid/jni/osbridge.h

The `AndroidSystem` class now lives in separate source files. No functional changes made.
The `OSBridge` class now lives in separate source files. No functional changes made.

Monodroid refactor

---

build-tools/scripts/RunTests.targets
build-tools/scripts/msbuild.mk

Context: https://github.com/xamarin/xamarin-android/issues/1792
Context: 987a05fa890b8a24513820942f2c134099273950
Commit 987a05fa updated the "normal" build log process, as used by
Jenkins/etc., so that Console output received "normal" build verbosity
messages, while MSBuild `.binlog` files would be generated so that
"diagnostic" build logs could be produced "later," as necessary.
Unfortunately, commit 987a05fa didn't update unit test builds.
Consequently, `make run-apk-tests`/etc. would emit *diagnostic* build
logs to the Console, meaning instead of the previous ~1GB log file, we
instead had a "mere" ~400MB instead.
Update test execution so that they follow the spirit of 987a05fa:
`.binlog` files for diagnostic output, with "normal" output printed to
the console, resulting in smaller …

[build] Generate separate .binlog files for tests.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildOutput.cs

Context: https://github.com/xamarin/xamarin-android/pull/2285
The `IsTargetSkipped` method has a slight bug, it doesn't account for:
Skipping target "_GenerateJavaDesignerForComponent" because it has no inputs.
Minor change here to account for either `inputs` or `outputs` in the
message. There are no test failures caused by this on master; this was
discoverd in #2285 on d15-9.
Switched to using C# string interpolation.

[tests] Xamarin.ProjectTools fix for IsTargetSkipped

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildOutput.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://github.com/xamarin/xamarin-android/issues/2216#issuecomment-428731234
This reverts commit fab260dfab1e2b7837e9c9e0e665007cb3156374.
This commit relies on other commits in master, which otherwise causes a regression as mentioned in #2216:
```
Building target "_GenerateJavaDesignerForComponent" completely.
Input file "obj\Debug\81\R.cs.flag" is newer than output file "obj\Debug\81\Component.R.cs.flag".
```
This target shouldn't be running in a build with no changes.
I also incorporated test changes from master @ 647659e8, which catches the regression in #2216. It will be helpful to add this test in d15-9 going forward.

 Revert "[Xamarin.Android.Build.Tasks] deletebinobj fix for resources

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #2289
When doing debug shared runtime builds the user generally does
not care what abi is used. As a result we should only be showing
the `XA0115` warning when they are NOT using the shared runtime.

[Xamarin.Android.Build.Tasks] Ignore XA0115 for Shared Runtime builds.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsAndroidApplicationProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Not quite sure how we ever got away with this. As part
of the build process we extract from `EmbeddedResource`
a bunch of `.java` files into the intermediate directory.
These are used for a number of things like multidex and
bootstrapping mono. For some reason we NEVER added those
to the `FileWrites` group. So there is a good chance these
files will get deleted by an incremental clean.
This was picked up by a unit test in monodroid which
deals with fast deployment.

[Xamarin.Android.Build.Tasks] Add `CopyResource` items to `FileWrites`.

---

build-tools/scripts/RunTests.targets

What do we want?  Faster unit test execution!
How do we do that?  By running things in parallel!
Some of our existing tests are already run in parallel, such as the
`src/Xamarin.Android.Build.Tasks/Tests` tests which use NUnit's
`[Parallelizable (ParallelScope.Children)]`, but there is currently no
way to run the `Xamarin.Android.Build.Tasks` NUnit tests
*concurrently* with the on-device `.apk` tests concurrently with the
Java.Interop unit tests concurrently with...
We *think* there might be a "win" here, as the
`Xamarin.Android.Build.Tasks` unit tests are heavily I/O bound, while
the `.apk` BCL tests are -- presumably -- CPU bound, so executing
these at the same time might net some nice time savings.
Spike the idea by updating the `RunAllTests` target to *generate a
shell script* which …

[tests] Run tests in parallel on non-Windows

---

src/monodroid/jni/android-system.cc

Fixes: https://github.com/xamarin/xamarin-android/issues/2300
Commit e99b02b7 [broke the Android Designer][0]:
[monodroid] Cannot find 'libmonosgen-2.0.dll'. Looked in the following locations:
[monodroid]   C:\Users\VssAdministrator\AppData\Local\Temp\tmpC7EC.tmp\.__override__
[monodroid]   C:\Users\VssAdministrator\AppData\Local\Temp\tmpC7EC.tmp
[monodroid]   C:\Users\VssAdministrator\AppData\Local\Temp\tmpC7EC.tmp
[monodroid]   C:\Users\VSSADM~1\AppData\Local\Temp\data
[monodroid] Do you have a shared runtime build of your app with AndroidManifest.xml android:minSdkVersion < 10 while running on a 64-bit Android 5.0 target? This combination is not supported.
[monodroid] Please either set android:minSdkVersion >= 10 or use a build without the shared runtime (like default Release …

[monodroid] Provide proper in-module address on Windows

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets

Fixes: http://feedback.devdiv.io/335298
Context: https://github.com/xamarin/XamarinComponents/tree/master/Android/ARCore/samples
The linked example was failing a design-time build with:
"XamarinComponents\Android\ARCore\source\Google.ARCore.csproj" ->
Additions\Additions.cs(63,101,63,107): error CS0234: The type or namespace name 'Anchor' does not exist in the namespace 'Google.AR.Core' (are you missing an assembly reference?)
Usage of the `Anchor` type had sqiggly Intellisense errors in Visual
Studio. Building the project was successful, however.
Looking further, the contents of `obj\Debug\api.xml` seemed _wrong_
after a design-time build:
<api></api>
Reviewing the log, the `<ClassParse />` MSBuild task had no inputs:
ClassParse
ClassParse Task
OutputFile: …

[Xamarin.Android.Build.Tasks] fix DTBs for binding projects with aar files

---

src/monodroid/jni/android-system.cc

https://github.com/xamarin/xamarin-android/commit/9621be1db9e5b38b503c658df0c61c5dc49796e8 reverted previous change to send a real path to `GetModuleHandlExW` but the
reversal wasn't complete :( The call to free memory allocated for that path was
left, but with the current code `dir_path` is a pointer to a class field and
freeing it may have unknown effects.
Additionally, change some `NULL`s to C++ `nullptr`s

Do not free memory that wasn't dynamically allocated

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

This reverts commit dfd695ece835a179dfef4bb276a5a3a6133af586.
This is because on master we have removed `armeabi` completely.
As a result we WANT to raise an error is this is used anywhere.
Its not used in the shared runtime anymore so this "fix" is
not needed.

Revert "[Xamarin.Android.Build.Tasks] Ignore XA0115 for Shared Runtime builds. (#2293)"

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsAndroidApplicationProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/App.xaml
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/App.xaml.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/MainActivity.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/MainPage.xaml
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/MainPage.xaml.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/Tabbar.axml
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/Toolbar.axml
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/colors.xml
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Resources/Forms/styles.xml
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Xamarin.ProjectTools.csproj

In the past `XamarinFormsAndroidApplicationProject` was incomplete:
1. It was not a "real app", but the resemblance of one that merely
_compiled_.
2. It did not have XAML or import/run Xamarin.Forms MSBuild tasks.
3. It was not an app that could startup, and render Xamarin.Forms
content.
So I took the simplest Xamarin.Forms template from Visual Studio 2017
15.8.7, a `Blank App`:
- Added various new files as `EmbeddedResource` in
`Xamarin.ProjectTools`.
- Used most files as-is, adding `${ROOT_NAMESPACE}` where appropriate.
- Included `Tabbar.axml`, which has a "custom view".
- Included proper XAML files.
- Imported `Xamarin.Forms.targets`, and verified that `XamlG` and
`XamlC` are now both running.
- Added `Xamarin.Android.Support.Vector.Drawable`, which avoids a
crash at runtime.
- …

[tests] use a "real" Xamarin.Forms app

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

While reviewing our MSBuild targets, I noticed three targets that
declared `Inputs` and `Outputs`, but did not actually update any
files:
- `_CollectConfigFiles`
- `_CollectMdbFiles`
- `_CollectPdbFiles`
This means that MSBuild was unnecessarily looking at files to see if
they exist, and might be comparing timestamps as well. The targets
would also _always_ run, so it doesn't matter to have `Inputs` and
`Outputs` in these targets at all!
I basically removed these `Inputs` and `Outputs`, and saw a
performance gain with just doing that. I also saw performance gains to
targets that depend on these three targets. Since `Inputs` and
`Outputs` timing is internal to MSBuild, I am not sure where the
actual time is being tallied here.
Before:
1 ms  _CopyConfigFiles                           1 …

[Xamarin.Android.Build.Tasks] remove unused Inputs/Outputs

---

src/monodroid/jni/monodroid-glue.cc

Should fix https://github.com/xamarin/xamarin-android/issues/2257
We should release local ref earlier in these cases, because with
higher number of assemblies we can overflow the local reference table
soon enough, before returning from native code.
In case of apks it is not as much probable, but why not release it and
not take a chance.

[monodroid] Release local refs earlier

---

Documentation/guides/messages/README.md
Documentation/guides/messages/xa1004.md
src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/626304
If `ResolveLibraryProjectImports` encounters a corrupt zip or
aar file during the extraction process we get the following
error.
Xamarin.Tools.Zip.ZipIOException: Unexpected libzip error: EOF
at Xamarin.Tools.Zip.ZipArchive.Open (System.String path, System.IO.FileMode mode, System.String defaultExtractionDir, System.Boolean strictConsistencyChecks, Xamarin.Tools.Zip.IPlatformOptions options) [0x00141] in <9421129374314790afd60f8c0021d3d4>:0
at Xamarin.Android.Tools.Files.ReadZipFile (System.String filename, System.Boolean strictConsistencyChecks) [0x00000] in <c304dcc9c82e4174bfeded58a523ee7b>:0
at Xamarin.Android.Tasks.MonoAndroidHelper.ReadZipFile (System.String filename) [0x00000] in …

[Xamarin.Android.Build.Tasks] error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly while building Android App

---

tests/CodeGen-Binding/Xamarin.Android.FixJavaAbstractMethod-APIv1Binding/Transforms/EnumFields.xml
tests/CodeGen-Binding/Xamarin.Android.FixJavaAbstractMethod-APIv2Binding/Transforms/EnumFields.xml
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib1/Transforms/EnumFields.xml
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib2/Transforms/EnumFields.xml
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib3/Transforms/EnumFields.xml
tests/ResolveImports/Xamarin.Android.BindingResolveImportLib4/Transforms/EnumFields.xml

Some binding template file contains invalid closing tag.
These tags are in comment-out filed, so this PR will not affect other codes.
The fundamental solution is to fix following file, but I do not have access to repository that contains that file...
```
cat /Applications/Visual\ Studio.app/Contents/Resources/lib/monodevelop/AddIns/MonoDevelop.MonoDroid/templates/Project/BindingProject/EnumFields.xml
<enum-field-mappings>
</enum-field-mappings>
%
```
Although the format of following files are different from the current one, the closing tag is correct so I did not modify it.
https://github.com/xamarin/xamarin-android/blob/master/tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding/Transforms/EnumFields.xml
https://github.com/xamarin/xamarin-android/blob/master/tests/CodeGen-Bi …

Typo Fix in EnumFields.xml

---

Documentation/README.md
Documentation/guides/MSBuildBestPractices.md
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/2247
We currently have two targets that fail to build incrementally:
- `_ResolveLibraryProjectImports`
- `_GeneratePackageManagerJava`
Both of these targets declare `Outputs`, but don't always update the
timestamp of the output file. They used `CopyIfChanged` logic, so they
won't write to the file if nothing changed.
However...
We can't just add `<Touch/>` calls here either, as the `Outputs` of
these targets are `Inputs` to other *slow* targets (`_CompileJava`,
`_UpdateAndroidResgen`, and friends). If we used `<Touch/>` here,
things would be worse and trigger the *slow* targets to run.
So the only option here is to use a "stamp" file, this allows these
targets to properly build incrementally and not trigger other targets.
I updated …

[Xamarin.Android.Build.Tasks] incremental build improvements

---

src/Xamarin.Android.Build.Tasks/Tasks/CompileToDalvik.cs

When using the InstantRun feature we are seeing the following
error.
error MSB6003: The specified task executable "java" could not be run. '{path}obj/Debug/lp/2/classes.zip' does not exist. Please rebuild the project.
This is because `_CompileToDalvikLibraryJars` runs to compile
the various `.jar` files into `.dex` files for each library.
This helps to speed up incremental builds.
However the `classes.zip` will NOT exist
in these `lp` directories and nor should it.
So rather than throwing an error lets just not include
the file if it does not exist.

[Xamarin.Android.Build.Tasks] Fix Error in `CompileToDalvik`.

---

src/Xamarin.Android.Build.Tasks/ILRepack.targets

When building the `Xamarin.Android.Build.Tasks.dll` assembly we merge it with a
number of assemblies in order to avoid problems when the IDE loads a different
version of any of those assemblies, which can potentially break XA.
Unfortunately, the merging process crashes the build on Linux:
```
Stacktrace:
at <unknown> <0xffffffff>
at (wrapper managed-to-native) System.MonoCustomAttrs.IsDefinedInternal (System.Reflection.ICustomAttributeProvider,System.Type) [0x00021] in <fb4ca01ee4cf488c95b864932a850791>:0
at System.MonoCustomAttrs.IsDefined (System.Reflection.ICustomAttributeProvider,System.Type,bool) [0x00027] in <fb4ca01ee4cf488c95b864932a850791>:0
at System.RuntimeType.IsDefined (System.Type,bool) [0x00038] in <fb4ca01ee4cf488c95b864932a850791>:0
at …
```

Disable ILRepack target on Linux

---

build-tools/android-toolchain/android-toolchain.targets
src/Mono.Android/Mono.Android.csproj
src/Mono.Android/Mono.Android.targets

We have something weird going when building Xamarin.Android itself:
msbuild Xamarin.Android.sln
msbuild Xamarin.Android.sln
You would assume that the second command would be a no-op, but it's
not...
`xa-prep-tasks.csproj` and `Xamarin.Android.Tools.BootstrapTasks`
seems to build *every* time. You can see the `CoreCompile` target
running, which is even worse on Windows, where the output assembly
file might be locked!
I found two cases where we are calling the `<MSBuild/>` MSBuild task,
where `<ProjectReference/>` would be more appropriate:
- `android-toolchain.targets` - had an `<MSBuild />` call to build
`Xamarin.Android.Tools.BootstrapTasks`, but it *also* had a
`<ProjectReference/>`. Removing it worked fine, and solved the
problem.
- `Mono.Android.targets` - was manually building …

 [build] use <ProjectReference /> instead of <MSBuild />

---

src/mono-runtimes/mono-runtimes.targets

If we, for some reasons, built Mono from sources, we do not want to try to download it later on. This may happen if you bump `external/mono` to the `HEAD` of a release branch, build locally *before* the Mono Archive is created on CI, then try to rebuild locally *after* the Mono Archive has been created on CI.

[mono] Make sure we either download *or* build mono

---

build-tools/android-toolchain/android-toolchain.targets

On my machine, `<AcceptAndroidSdkLicense/>` is taking about ~1.5 sec
and runs even in a build with no changes.
We can run it as part of the `_UnzipFiles` target, removing the
`_AcceptAndroidSdkLicenses` target completely. We only need to
re-accept the licenses after new zip files are extracted.
This should save us about 1.5 seconds on any incremental build of
Xamarin.Android itself.

[build] <AcceptAndroidSdkLicense/> should not always run

---

src/Xamarin.Android.Build.Tasks/Utilities/AndroidResource.cs

Context: http://www.getcodetrack.com/
I used a "freeware" .NET profiler to see what it would turn up.
Using the tool, I profiled the following .NET process:
.\bin\Debug\bin\xabuild.exe .\tests\Xamarin.Forms-Performance-Integration\Droid\Xamarin.Forms.Performance.Integration.Droid.csproj /v:quiet
This seemed to have a lot of useful information, and I quickly noticed:
Monodroid.AndroidResource.UpdateXmlResource -> 3683 calls -> 2.13s
..
Monodroid.AndroidResource.ResourceNeedsToBeLowerCased -> 2384 calls - 319.53ms
This is a known codepath, the `ConvertResourcesCases` MSBuild task,
that we know takes a bit of time.
Looking through the call stack, I saw two points we could make easy
fixes for:
- A `Regex` in `AndroidResource` was not using `RegexOptions.Compiled`
- There was a string append …

[Xamarin.Android.Build.Tasks] more ConvertResourcesCases improvements

---

src/Mono.Android/metadata

Fixes: http://work.devdiv.io/712427
For the next major release of Visual Studio, Xamarin.Android will stop
building and distributing `Mono.Android.dll` for:
* v2.3 (API-10)
* v4.0.3 (API-15)
* v4.1 (API-16)
* v4.2 (API-17)
* v4.3 (API-18)
This will be done for the following reasons:
1. Support for API-10 and API-15 will be dropped from the
[Android NDK][0]:
> Support for ICS (android-14 and android-15) will be removed from r18
2. The [Android Support Library][1], as of release 26.0.0
(July 2017), requires API-14 or higher:
> Starting with Support Library version 26.0.0 (released in July 2017),
> the minimum supported API level has changed to Android 4.0 (API level 14)
> for all support library packages.
3. The Android Support Library replacement, [AndroidX][2], requires
a …

[Mono.Android] Obsolete Mono.Android.dll for < API-19

---

build-tools/debian-metadata/rules

Augment https://github.com/xamarin/xamarin-android/commit/01578999d04d5510a2e2680f805e803e65c76467 to ignore a couple more native Windows binaries when building a Debian package.

[Linux, build] Ignore more native Windows binaries on packaging

---

build-tools/scripts/Packaging.mk

Debian packaging uses "native" packaging scheme (that is Xamarin.Android is
treated as a Debian native package as opposed to a 3rd party one) and so the
.orig.tar.bz2 file is not needed.

[Debian] Save uploading lots of data

---

build-tools/scripts/BuildEverything.mk
build-tools/scripts/Packaging.mk

Context: ae093bf0a103863e9325afd7e2fedbff1b78648e
The Jenkins changes around ae093bf0 broke the
[xamarin-android-linux-release][0] build, because
`make jenkins CONFIGURATION=Debug` builds the `$(ZIP_OUTPUT)` file,
which then *only* contains the Debug-configuration artifacts, and
because `$(ZIP_OUTPUT)` already exists, it is not recreated when
`make jenkins CONFIGURATION=Release` is executedd.
Consequently, when `make package-deb CONFIGURATION=Release` is
executed, *there are no Release artifacts*, and packaging fails.
The fix?  If the intention behind ae093bf0 is to eventually build both
Debug and Release configuration artifacts on separate Jenkins jobs,
then they should likewise produce different `$(ZIP_OUTPUT)` filenames.
Include `$(CONFIGURATION)` in the `$(ZIP_OUTPUT)` filename. …

[build] $(ZIP_OUTPUT) contains $(CONFIGURATION)

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/BuildItem.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DownloadedCache.cs

Context: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4408/testReport/junit/Xamarin.Android.Build.Tests/BuildTest/BuildBasicApplicationCheckPdb___Debug/
A random test failure has occurred such as:
Xamarin.Android.Build.Tests.BuildTest.BuildBasicApplicationCheckPdb
System.IO.IOException : Sharing violation on path /Users/builder/.local/share/Xamarin.ProjectTools/PdbTestLibrary.pdb
at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <9e4df56871b74651838be0f6a9e1bc80>:0
at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) …

[tests] NO dropbox, fix locking in Xamarin.ProjectTools

---

Documentation/guides/MSBuildBestPractices.md
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

In our "MSBuild Best Practices" guide, the convention for using a
"stamp" file has a bit of boilerplate...
<Target Name="_MyTarget"
Inputs="..."
Outputs="$(_AndroidStampDirectory)_MyTarget.stamp">
<Touch Files="$(_AndroidStampDirectory)_MyTarget.stamp" AlwaysCreate="True" />
<ItemGroup>
<FileWrites Include="$(_AndroidStampDirectory)_MyTarget.stamp" />
</ItemGroup>
</Target>
It would be reasonably easy to mess this up.
If we add a new `_AddFilesToFileWrites` target that automatically adds
`$(_AndroidStampDirectory)*.stamp` to `FileWrites`, we can simplify
things:
<Target Name="_MyTarget"
Inputs="..."
Outputs="$(_AndroidStampDirectory)_MyTarget.stamp">
<Touch Files="$(_AndroidStampDirectory)_MyTarget.stamp" AlwaysCreate="True" />
</Target>
This should be less prone to mistakes.

[Xamarin.Android.Build.Tasks] target to simplify @(FileWrites)

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidCommonProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinAndroidWearApplicationProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/XamarinFormsAndroidApplicationProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs

WIP. 
In a effort to reduce our dependency on external resources we should not be relying on `Nuget.exe` to restore packages. We should instead be using `msbuild /t:Restore`. 
That only works with `PackageReference` though. So lets move all of our Nuget references in the MSBuild tests over to use that system. We can then hopefully remove the dependency on `Nuget.exe`

Move all MSBuild tests over to use `PackageReference`.

---

Makefile
build-tools/scripts/BuildEverything.mk
build-tools/scripts/msbuild.mk

There were some leftovers of useless $(CONFIGURATION)

[build] Expunge use of CONFIGURATIONS (Continuation)

---

src/mono-runtimes/ProfileAssemblies.projitems
src/mono-runtimes/mono-runtimes.targets
tests/BCL-Tests/Xamarin.Android.Bcl-Tests/NUnitInstrumentation.cs
tests/BCL-Tests/Xamarin.Android.Bcl-Tests/XUnitInstrumentation.cs
tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.csproj
tests/BCL-Tests/Xamarin.Android.Bcl-Tests/Xamarin.Android.Bcl-Tests.targets
tests/TestRunner.Core/TestInstrumentation.cs
tests/TestRunner.NUnit/NUnitTestInstrumentation.cs

Context: https://github.com/mono/mono/blob/8e0cbf1044fb86f40c41f4317ef9154f82a94bb4/scripts/ci/pipeline/sdks-archive.groovy#L84
Context: https://jenkins.mono-project.com/view/Per-commit%20packages/job/archive-mono/
The mono archives have a different filename format than that used in
commit f970cd50.  As per [`sdks-archive.groovy`][0], the filename to
download *should* be:
${product}-${configuration}-${platform}-${commitHash}.zip
Update `$(_MonoArchiveName)` accordingly, and fix the output paths so
that the mono archive can actually be used.  (As noted in f970cd50,
*actual* support for building with the mono archive hadn't been
tested, as one didn't exist for the mono xamarin-android uses.)
[0]: https://github.com/mono/mono/blob/8e0cbf1044fb86f40c41f4317ef9154f82a94bb4/scripts/ci/pipeline/s …

[mono-2018-10] [build] Download correct mono archive URL

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/2356
When `$(AndroidUseAapt2)=True`, if you look for a log entry of a file
that is processed:
Processing: C:\Users\myuser\Desktop\Git\xamarin-android\tests\Xamarin.Forms-Performance-Integration\Droid\obj\Debug\90\lp\22\jl\res\values\values.xml   10/30/2018 4:28:18 PM > 1/1/0001 12:00:00 AM
You will see this repeated several times (9 in case of a Xamarin.Forms
project).
It turns out, since the `_CompileAndroidLibraryResources` target is
batched, it is called once per item of
`@(_LibraryResourceHashDirectories)`:
<Target Name="_CompileAndroidLibraryResources" DependsOnTargets="_CollectLibraryResourceDirectories"
Condition="'$(_AndroidUseAapt2)' == 'True'"
Inputs="%(_LibraryResourceHashDirectories.FileFound)" …

[Xamarin.Android.Build.Tasks] aapt2, move ConvertResourcesCases to a new target

---

src/r8/r8.targets
tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding/Xamarin.Android.LibraryProjectZip-LibBinding.targets
tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding/java/JavaLib/library/.gitignore
tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding/java/JavaLib/library/build.gradle.in

Context: https://github.com/xamarin/xamarin-android/pull/2019
Context: http://build.devdiv.io/2168276
Context: http://build.devdiv.io/2169681
Since 4bb4b2e, our builds have been failing on VSTS on Windows.
Jenkins is green, however.
Currently getting a failure in
`Xamarin.Android.LibraryProjectZip-LibBinding.csproj` such as:
2018-10-31T14:02:28.8336608Z    .\gradlew assembleDebug --stacktrace --no-daemon
2018-10-31T14:02:40.7122197Z   NDK is missing a "platforms" directory.
2018-10-31T14:02:40.7122937Z   If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Users\dlab14\android-toolchain\sdk\ndk-bundle.
2018-10-31T14:02:40.7124870Z   If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this …

[build] fixes for failing Windows build

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Android/KnownPackages.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes #2360, #2361, #2362, #2363
When running the `Lint` checks on an application we
provide a path to a `project` directory. This is
currently the `$(IntermediateOutputPath)`. The problem
with this is that it also includes the `lp` directory.
The `lp` directory contains ALL the resources and
Manifest files for the library projects. As a result
if you are referencing support packages ALL of those
items are checked too.
It turns out that most of the Manifest files shipped
with the libraries are not complete or will cause
`lint` errors or warnings.
So what we need to do is point the `lint` check at
the `$(IntermediateOutputPath)android`. This will restrict
the checks to the files which the Build system
produces (the java code, and the final app manifest).
This PR includes an updated unit …

[Xamarin.Android.Build.Tasks] Fix Various `Lint` Issues

---

src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/StripEmbeddedLibraries.cs
src/Xamarin.Android.Build.Tasks/Tasks/BuildApk.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

To improve fast deployment even further we need to alter
the way we deal with native libraries in refernced
assemblies.
Currently these libraries are extracted as part of the
`BuildApk` task. As a result if a native library is
updated we need to build the whole `.apk` again.
We should extract the `__AndroidNativeLibraries__.zip` contents
into the `$(IntermediateOutputDir)\lp\{assmelby}\nl` directory
as part of the `ResolveLibraryProjectImports` task.
This way the existing `GetImportedLibraries` task will
then pick those `.so` files up and add them to the
`@(NativeLibraries)` Item Group. This will then be picked up
by `BuildApk` as normal in a release build.
However for a debug build we can skip putting these files
in the `.apk` and Fast deploy them instead.

[Xamarin.Android.Build.Tasks] Extract .so files to the `lp` directory

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs

Implements https://github.com/xamarin/xamarin-android/issues/2374
As the `ResolveSdks` task is used in every build, try to make it faster.
I tried to measure few builds and the time went from ~540ms to ~240ms
per 3 calls. (there were also some longer builds with cached value as
well. I think it is just a fluctuation I see on my old notebook)

[ResolveSdksTask] cache JdkJvmPath value

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetXamarinProject.cs

Downstream in `monodroid` we are getting a random test failure with a
test case such as:
proj.Touch ("SomeFile");
Assert.IsTrue (b.Build (proj, true, null, false));
It seems from the build log that `SomeFile` was not actually updated.
So looking at `Touch`, it uses `Now` instead of `UtcNow`:
foreach (var item in itemPaths)
GetItem (item).Timestamp = DateTimeOffset.Now;
But the code deciding to save a file or not uses `LastWriteTimeUtc`:
var needsUpdate = (!File.Exists (path) || p.Timestamp == null || p.Timestamp.Value > new DateTimeOffset (new FileInfo (path).LastWriteTimeUtc));
We should be using `Utc` everywhere. I've gone through
Xamarin.ProjectTools and the MSBuild tests to use `UtcNow` where
needed. Some places I also changed to use `DateTimeOffset` instead of
`DateTime` for …

[Xamarin.ProjectTools] change Now to UtcNow

---

Documentation/guides/messages/xa0118.md
Documentation/guides/messages/xa1005.md

This documentation was meant to be part of:
https://github.com/xamarin/xamarin-android/pull/2258
I accidentally removed these pages from that pull request when I was
updating it to exclude the changes for XA4214 and XA4215.
* * *
These are documentation only changes, and I'm curious to check for reference if this PR trigger is enabled in this repo, so I'll try skipping the PR build:
@monojenkins skip

[docs] Add docs for warnings XA0118 and XA1005

---

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Using a commercial master build of Xamarin.Android, I get the
following crash at runtime:
java.lang.RuntimeException: Unable to get provider mono.android.ResourcePatcher: java.lang.ClassNotFoundException: Didn't find class "mono.android.ResourcePatcher" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/HelloForms.HelloForms-g8b7mdSG3CF6lxWgPVIURg==/base.apk"],nativeLibraryDirectories=[/data/app/HelloForms.HelloForms-g8b7mdSG3CF6lxWgPVIURg==/lib/arm64, /data/app/HelloForms.HelloForms-g8b7mdSG3CF6lxWgPVIURg==/base.apk!/lib/arm64-v8a, /system/lib64]]
at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
at …

[Xamarin.Android.Build.Tasks] fix for missing content provider

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunInstrumentationTests.cs
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunUITests.cs

Fixes https://github.com/xamarin/xamarin-android/issues/2371
After https://github.com/xamarin/xamarin-android/pull/2125, the
`RunInstrumentationTests` task stopped writing the logcat output to
the `LogcatFilename` specified as parameter.
That resulted in missing input files for the `ProcessLogcatTiming`
task.

[build-tools] Write the intrumentation timing output again

---

Configuration.props
build-tools/scripts/TestApks.targets
src/Mono.Android/Test/Mono.Android-Tests.projitems
tests/Runtime-MultiDex/Mono.Android-TestsMultiDex.projitems
tests/Xamarin.Forms-Performance-Integration/Droid/Xamarin.Forms.Performance.Integration.Droid.projitems

Fixes https://github.com/xamarin/xamarin-android/issues/2400
With https://github.com/xamarin/xamarin-android/pull/1683 we started
to run and measure the apk tests with `BundleAssemblies=True` as
well. To not mix and repeat these measurements with other ones,
introduce `TestsFlavor` property in place of `TestsAotName` to
distinguish the apk tests runs when collecting and processing
measurements data.
It is similar to what we did with AOT before.
Example content of TestResult-Mono.Android_Tests-times.csv after the
fix:
last-Release,JNI.init-Release,init-Release,NUnit.results-Release,last-Release-Aot,JNI.init-Release-Aot,init-Release-Aot,NUnit.results-Release-Aot,last-Release-Bundle,JNI.init-Release-Bundle,init-Release-Bundle,NUnit.results-Release-Bundle …

[plots] Do not mix Release and Release/Bundle measurements

---

build-tools/android-toolchain/android-toolchain.projitems

In 4bb4b2e, we added a `%(HashHeader)` value for invalidating cached
downloads in `android-toolchain.csproj`. It's primary use was for a
`depot_tools.zip` file, which is a dependency of building r8.
However...
Quite frequently we are seeing `depot_tools.zip` *change* and it gets
re-downloaded:
Hash found using 'x-goog-hash', destination file changing to 'C:\Users\myuser\android-archives\depot_tools-crc32c=JBYDJw==.zip'.
Downloading `https://storage.googleapis.com/chrome-infra/depot_tools.zip` to `C:\Users\myuser\android-archives\.depot_tools-crc32c=JBYDJw==.zip.download`.
Since we can't really count on a "version" of this file we are
downloading, I have mirrored it to the Azure storage account we are
already using for tests:
https://xamjenkinsartifact.azureedge.net/mono-jenkins/xamarin-and …

[android-toolchain] mirror depot_tools in Azure storage

---

src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/1924
The `Authorization` HTTP header should not be passed on to the next location
when redirecting. Make sure it is removed before following the redirect.

Don't propagate the Authorization header on redirect

---

tests/Xamarin.Forms-Performance-Integration/Droid/proguard.cfg

https://github.com/xamarin/xamarin-android/pull/2019/files introduced a crash in our
XForms test, it crashes in the middle of the startup.
It looks like we need to preserve also `android.support.v7.view.**`
classes as well.
This is the logcat output of the crash:
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: Xamarin.Forms_Performance_Integration, PID: 8563
E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{Xamarin.Forms_Performance_Integration/xamarin.forms.performance.integration.MainActivity}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class android.support.v7.view.menu.ActionMenuItemView
E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread …

[tests] Preserve more java classes in XForms sample

---

build-tools/scripts/Packaging.mk

Context: ae093bf0a103863e9325afd7e2fedbff1b78648e
Context: faaa908b2f0fcdae907bd12233efb0febb04fe91
Update the `make package-build-status` output so that
`xa-build-status*.zip` becomes
`xa-build-status*-$(CONFIGURATION).zip`, ensuring that Debug and
Release build outputs go to separate filenames.
The current plan is to eventually alter the [xamarin-android][0] job
so that it builds *only Release artifacts* by default, and add a new
`xamarin-android-debug` job which builds Debug configuration
artifacts.  Both jobs will still upload their artifacts to the same
URL -- which doesn't contain a JOB number; see ea89a667 -- thus the
`xa-build-status*.zip` file needs to contain `$(CONFIGURATION)` so
that the two jobs don't overwrite each other's outputs.
[0]: …

[build] Add `$(CONFIGURATION)` to package-build-status output

---

src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/2123
Implement proxy support for the Java HTTP client by "translating" the proxy
information specified in `HttpClientHandler.Proxy` to the format accepted and
expected by the Java client. Since the translation may involve a DNS lookup, it
is performed in a separate task. No caching is attempted in our client code.

Use a proxy server if specified

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs

Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1252/testReport/
There are currently some test failures on xamarin-android/master:
Xamarin.Android.Build.Tests.BuildTest.CheckLintErrorsAndWarnings
...
(Restore target) -> 
/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/msbuild/15.0/bin/NuGet.targets : error : Package 
Xamarin.Android.Support.v4 27.0.2.1 is not compatible with monoandroid43 (MonoAndroid,Version=v4.3).
The problem is that somehow `TargetFrameworkVersion` is getting set to `v4.3`?
Reviewing this code:
if (latest.Major < version.Major && latest.Minor <= version.Minor)
We should just use the `<` operator on `System.Version` instead.

[Xamarin.ProjectTools] fix LatestTargetFrameworkVersion

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/2410
One of the key metrics tracked in Visual Studio is the time it takes
for "solution create" to complete. Xamarin.Android would contribute to
this time from the duration of an initial design-time build.
`ValidateJavaVersion` is one of the slower tasks during a DTB:
ValidateJavaVersion = 280 ms
I have seen reports of this taking 500ms sometimes. Subsequent calls
of `<ValidateJavaVersion/>` are cached, but that does not help the
first DTB on "solution create".
Looking at the task, it's main job is to emit errors/warnings, and
then it sets two properties:
- `_JdkVersion`
- `_DefaultJdkVersion`
These are only used by the `_AdjustJavacVersionArguments` target,
which doesn't run during DTB.
We can just skip `<ValidateJavaVersion/>` on …

[Xamarin.Android.Build.Tasks] skip ValidateJavaVersion on DTB

---

build-tools/scripts/TestApks.targets
build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/ProcessLogcatTiming.cs
build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/ProcessPlotInput.cs

Fixes https://github.com/xamarin/xamarin-android/issues/2397
Make sure that we don't break the timing measurements again, when the *logcat*
output is not collected. The PR build should fail in such case.

[tests] Emit error when timing input is missing

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveJdkJvmPath.cs
src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/2409
Context: https://github.com/xamarin/xamarin-android/wiki/Build-Performance-Results
When doing the latest performance comparison, I noticed the
`<ResolveSdks/>` MSBuild task is a bit slower:
* VS 15.9
80 ms  ResolveSdks                                7 calls
* VS 16.0 p2 (master)
127 ms  ResolveSdks                                7 calls
For `$(AndroidGenerateJniMarshalMethods)` support, we needed to locate
a new `$(JdkJvmPath)` location.
Since `<ResolveSdks/>` finds `$(JdkJvmPath)` on first build, and
design-time builds, it is worth making sure this task doesn't get any
slower. The initial design-time build happens on "solution create",
which is one of the more important metrics the VS team measures.
So I split out the logic …

[Xamarin.Android.Build.Tasks] locate $(JdkJvmPath) only when needed

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Context: https://github.com/xamarin/xamarin-android/issues/2410
In 3eb41a0, I added a good performance improvement for the initial
design-time build (solution create).
However, we have tests downstream in monodroid that check if MSBuild
targets called by the Android designer are working. Apparently, these
targets need `$(_JdkVersion)`, whoops! Glad we have that test!
The Android designer also sets
`$(AndroidUseManagedDesignTimeResourceGenerator)` to `False`. We can
check for this and allow the `<ValidateJavaVersion/>` MSBuild task to
run in this case.

[Xamarin.Android.Build.Tasks] <ValidateJavaVersion/> needed for designer

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Fixed #2408
As part of the speed up process when extracting resources
from assemblies and Aar files, we dont re-extract if
the stamp file is newer than the assembly.
The problem with that was in the case of Aar files we
were NOT adding the `res` or `asset` directories to
the list of resolved directories when we skipped extraction.
As a result we got less `res` directories on a second
build.
This commit fixes that.

[Xamarin.Android.Build.Tasks] Fix Aar directory resolution.

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

`$(IntermediateOutputPath)build.props`, or
`$(_AndroidBuildPropertiesCache)` is a file used as an `Input` to many
MSBuild targets. We write many *important* properties in this file as
a mechanism to trigger most of the build to rerun. So for example, if
you enabled proguard, the `$(AndroidEnableProguard)` MSBuild property
would re-run a lot of the build, such as `_CompileJava`,
`_CompileDex`, etc.
Right now there are two problematic properties in this file:
- `$(AdbTarget)`
- `$(AdbOptions)`
This means if you switched from a different Android deploy target:
emulator to device, or just a different device--it would run a full
build! `$(AdbTarget)` and `$(AdbOptions)` need to trigger MSBuild
targets related to "Fast Deployment" to re-run, but not everything.
What makes matters even worse, is …

[Xamarin.Android.Build.Tasks] move $(AdbTarget) out of build.props

---

Configuration.props

(Commercial) Xamarin.Android v9.1.102 is being tracked in the
[xamarin-android/d16-0-p2](https://github.com/xamarin/xamarin-android/tree/d16-0-p2) branch.
Bump $(ProductVersion) to 9.1.199 to track development progress of
the next version of Xamarin.Android.

Bump $(ProductVersion) to 9.1.199

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RenameTestCases.cs
build-tools/scripts/TestApks.targets

Context: https://gitter.im/xamarin/xamarin-android?at=5be467157326df140ed4fe2b
Context: https://gitter.im/xamarin/xamarin-android?at=5be46a0c7326df140ed51325
Context: https://gitter.im/xamarin/xamarin-android?at=5be46dd37326df140ed527d1
The `<RenameTestCases/>` task was added in 385699a5 to update the
`//test-case/@name` attribute value to contain the Configuration from
which the test came from.
As part of its operation, it would occasionally encounter NUnit XML
files which were *invalid*, usually because `nunit-console` crashed;
see also 0ec00e12, which updated `<RenameTestCases/>` semantics so
that *if* an NUnit file were invalid, it would generate a "new" NUnit
XML file containing a generic error message.
The problem is, this attempt at reporting *any* error message is still
failing. …

[Xamarin.Android.Tools.BootstrapTasks] RenameTestCases errors

---

tests/RunApkTests.targets

I think we want to run and measure this test in all configurations,
the same as we do for Mono.Android-Tests.

[tests] Run the XForms test also in Debug and Release/AOT

---

src/Xamarin.Android.Build.Tasks/Tasks/CreateManagedLibraryResourceArchive.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Commit 960f32c5 changed the location where libraries compile
their `compiled.flata` archive. As a result this file
was NOT being included in the `ManagedLibraryResourceArchive`.
This PR fixes up the `CreateManagedLibraryResourceArchive` to
use the new location for storing the `flata` archives.

[Xamarin.Android.Build.Tasks] Include compiled.flata in archive

---

src/mono-runtimes/mono-runtimes.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/2350
Most of the logic in `mono-runtimes.csproj` was happening during
`CoreCompile`. The problem with this is that design-time builds in
Visual Studio runs `CoreCompile`. The `Task.Wait` in `<DownloadUri/>`
causes a hang.
It turns out we could just completely remove the following target:
<Target Name="CoreCompile"
DependsOnTargets="_Build">
</Target>
`_Build` still runs appropriately. `_BuildUnlessCached` will call
`ForceBuild` or `_Build` depending if things are cached.

[mono-sdks] <DownloadUri/> should not run during design-time builds

---

build-tools/scripts/PrepareWindows.targets
build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/JdkInfo.cs

On Windows, if you have Microsoft OpenJDK installed, you currently
needed a `Configuration.Override.props` such as:
<Project>
<JavaSdkDirectory>C:\Program Files (x86)\Java\jdk1.8.0_161</JavaSdkDirectory>
</Project>
The Xamarin.Android build can't currently work with Microsoft OpenJDK,
because it is missing header files.
I've updated the `JdkInfo` MSBuild task to match a similar task in
Java.Interop. It now validates that JDKs are < `$(MaxJdkVersion)`, and
contain valid header files. `$(MaxJdkVersion)` defaults to 8.0 if it
is blank.
Now I am able to build Xamarin.Android on a Windows machine with
multiple JDKs and it picks the correct one.

[xa-prep-tasks] use JdkInfo to find JavaSdkDirectory

---

src/monodroid/jni/monodroid-glue.cc

The primary reason is to get a logging API initialization
change (https://github.com/xamarin/java.interop/commit/6dd6f166238e59e59c987bc939e0ce5914003a59)
in so that we can initialize logging earlier during the init process.

Bump Java.Interop

---

Documentation/workflow/HowToBumpMono.md
src/mono-runtimes/ProfileAssemblies.projitems

Fixes: https://github.com/xamarin/xamarin-android/issues/1879
Add the following Facade assemblies to `@(MonoFacadeAssembly)`:
* `System.Buffers.dll`
* `System.Memory.dll`
* `System.Net.Http.Rtc.dll`
* `System.Threading.Tasks.Extensions.dll`
Note: list was reordered to be sorted as per **sort**(1), and
generated with the following shell code on macOS:
$ cd external/mono/mcs/class/Facades
$ for d in `find . -depth 1 -type d | grep -v 'netstandard\|System.Drawing.Primitives' | sort -f` ; do
n=`basename "$d"`;
echo "    <MonoFacadeAssembly Include=\"$n.dll\" />";
done | pbcopy
The `netstandard` and `System.Drawing.Primitives` directory are
excluded so that the comment and following `@(MonoFacadeAssembly)`
entries in `ProfileAssemblies.projitems` are still relevant.

[mono-runtimes] Update @(MonoFacadeAssembly)

---

build-tools/download-bundle/download-bundle.targets

Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-debug/
To speed up build times, Xamarin.Android now builds Debug and Release
builds on different jobs on Jenkins.
The issue with this is that the Azure upload url will be of the form:
https://xamjenkinsartifact.azureedge.net/mono-jenkins/${JOB_NAME}/bin/
So we need to check for `Debug` `$(Configuration)` and use
`xamarin-android-debug` in that case.

[download-bundle] updated URL for Debug bundle

---

build-tools/download-bundle/download-bundle.targets

Context: https://www.nuget.org/downloads
Context: http://build.devdiv.io/2236305
Currently we download NuGet.exe from:
https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
However, it seems that the NuGet 4.8.1 release breaks our build on
Windows...
src\monodroid\monodroid.targets(3,3): Error MSB4019: The imported project "E:\A\_work\14\s\external\Java.Interop\bin\BuildDebug\JdkInfo.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [E:\A\_work\14\s\src\monodroid\monodroid.csproj]
src\Xamarin.Android.NUnitLite\Xamarin.Android.NUnitLite.csproj(349,3): Error MSB4019: The imported project "E:\A\_work\14\s\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\Xamarin.Android.CSharp.targets" was not found. Confirm that …

[build] pin NuGet.exe to a specific version

---

build-tools/download-bundle/download-bundle.targets

Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android
Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-debug
Context: https://github.com/xamarin/xamarin-android/pull/2457
dd498d2 was an attempt to fix our Jenkins configuration + bundle
downloads. However, when I tested the latest bundle I found a new
problem...
The current URLs are of the form:
Debug:   https://xamjenkinsartifact.azureedge.net/mono-jenkins/xamarin-android-debug/xamarin-android/bin/Debug/...-Debug-...zip
Release: https://xamjenkinsartifact.azureedge.net/mono-jenkins/xamarin-android/bin/Release/...-Release-...zip
The `xamarin-android-debug` job is using `${JOB_NAME}` as the "virtual
directory" to upload to. The `xamarin-android` Release job is not... …

[download-bundle] updated URLs, take 2!

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BindingBuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/2452
Some of our Xamarin components on NuGet need to take advantage of the
`$(AndroidSdkBuildToolsVersion)` property. However, this property does
not exist in a binding project.
It appears we need to move some important properties:
* `$(AndroidSdkBuildToolsVersion)`
* `$(AndroidSdkPlatformToolsVersion)`
* `$(AndroidSdkToolsVersion)`
* `$(AndroidNdkVersion)`
From `Xamarin.Android.Common.targets` to
`Xamarin.Android.Common.props`, since binding projects only import the
`*.props` file.
Other changes:
* I updated a binding project test, to verify these properties are
set.
* `Xamarin.Android.Build.Tasks.targets`, which generates
`Xamarin.Android.Common.props` was using a space character as a
delimiter? I wasn't aware this even worked, so …

[Xamarin.Android.Build.Tasks] move properties so they exist in binding projects

---

src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/1923
When a Location header contains an URL that is relative or lacks schema/host, we
now use the original request URL to construct the destination URL. Additionally,
if the original URL contains a fragment but the destination does not, we append
the fragment to the destination.

Follow redirections to relative URLs

---

src/Xamarin.Android.Build.Tasks/Tasks/CollectNonEmptyDirectories.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileExpected.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

This Commit enables `aapt2` as the default resource processor. 
It can be disabled by setting the `AndroidUseAapt2` to false in your csproj.
This Commit also fixes a small issue with compiling library resources. The scenario is as follows.
The main app project references a library which contains resources. 
`Resource\drawable\foo.png`
`Resource\layout\foo.xml`
On first build this works as expected. Then the user updates `foo.xml`. The next build will NOT refresh the `flata` file for the library. This is because `CollectNonEmptyDirectories` only looks for the first file in the library `res` directory. This file was then used as an input to the targets `_ConvertLibraryResourcesCases` and `_CompileAndroidLibraryResources`. The problem is that first file probably didn't change. And in this …

Enable Aapt2 by default

---

Configuration.props
Documentation/building/configuration.md
build-tools/scripts/BuildEverything.mk
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Bindings.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.CSharp.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.FSharp.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.VisualBasic.targets

Context: https://github.com/xamarin/xamarin-android/pull/1032
We previously obsoleted support for API levels earlier than API-19;
see commit 66e1b655.
Next up: stop *building* `Mono.Android.dll` and related assemblies for
API levels earlier than API-19, and stop *shipping* `Mono.Android.dll`
assemblies for `$(TargetFrameworkVersion)` values before `v4.4` (19).
PR #1032 previously tried to do this, and failed, because it attempted
to do "too much," removing code from `Mono.Android.dll` *as well as*
removing support for *building* the obsolete API levels.
Simplify things by *just* altering the build system and *not* the
source code within `Mono.Android.dll`.

[build] Do not build obsolete Mono.Android assemblies

---

src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/util.cc
src/monodroid/jni/util.h

Current timing code in monodroid-glue.cc uses the `gettimeofday` which provides
a most a microsecond accuracy, not enough for certain measurements.
Additionally, current code rounds it up to the millisecond boundery, making the
measurements very inaccurate. Also, `gettimeofday` is quite heavy in terms of
time spent in the syscall.
Replace `gettimeofday` with a call to `clock_gettime` when targetting Android or
Linux. This allows us to specify an alternative lock source, `CLOCK_MONOTONIC`,
which is very accurate and fast (not as fast as `CLOCK_MONOTONIC_COARSE` but
with higher resolution, thus better suited for our needs).
In addition, introduce a small collection of structures to be used for timing
instead of the currently used `long long` variables. Also introduced are the
`Util` class …

Improve timing accuracy and efficiency

---

build-tools/scripts/dependencies/debian-common.sh

libncurses5 is needed for clang 3.8 from the NDK and zlib is needed for Mono.

Update Debian dependencies

---

src/Xamarin.Android.Build.Tasks/Tasks/LinkAssemblies.cs

Context: https://github.com/Microsoft/perfview
When reviewing the .NET exception report in PerfView, I noticed a
`FileNotFoundException` thrown for every assembly such as:
Throw(System.IO.FileNotFoundException) Could not find file 'samples\HelloWorld\bin\Debug\HelloWorld.dll.mdb'.
All coming from the `LinkAssemblies` MSBuild task.
Reviewing the code, it appears we were affectively causing a `throw
new FileNotFoundException` + `catch` for every instance where an mdb
file was missing!
I reworked the mdb code in `LinkAssemblies` to match what we are doing
for pdb files. It is an order of magnitude faster to check
`File.Exists` over `throw` + `catch`, especially when the file will
most likely not exist.
The results seem to be a ~29ms improvement:
Before:
445 ms  LinkAssemblies …

[Xamarin.Android.Build.Tasks] avoid FileNotFoundException in LinkAssemblies

---

samples/HelloWorld/HelloLibrary/HelloLibrary.csproj
samples/HelloWorld/HelloWorld.csproj

In 1fb7983, a new `HelloLibrary.csproj` was added, but it had some
settings that cause `pdb2mdb` to run:
<DebugType>full</DebugType>
...
<DebugType>pdbonly</DebugType>
I switched the "Hello World" projects to use `$(DebugType)` `portable`,
so that portable pdb files are always generated as part of their
build.
This way when profiling builds on Windows, I don't have to account for
the `<ConvertDebuggingFiles/>` MSBuild task taking time.

[samples] use $(DebugType) portable

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Downstream in monodroid, we are seeing an issue with "Fast Deployment":
1. An incremental build occurs; one or more assemblies change.
2. We still seem to deploy *every* assembly.
This started happening in 539954c, since I corrected the directory
that `_LinkAssembliesNoShrink` was touching files in.
`_LinkAssembliesNoShrink` was setup to:
1. Its `Outputs` were assemblies produced by the linker.
2. A `<Touch/>` command was updating timestamps of these assemblies.
Refactoring this target to more closely match `_LinkAssembliesShrink`
actually seems more correct here:
1. `Inputs` should include `$(_AndroidBuildPropertiesCache)`. Whoops!
2. `Outputs` should be the `$(_AndroidLinkFlag)` file.
3. We can do away with the `@(_LinkAssembliesNoShrinkFiles)` item
group, and just directly add to …

[Xamarin.Android.Build.Tasks] fix Inputs/Outputs for _LinkAssemblies*

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunInstrumentationTests.cs
build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RunUITests.cs

That way it is easier to find a problem in the logcat output as it
will only contain the information relevant to the particular test run.
As we clear it after the run, the first test logcat on a freshly
started emulator will also contain the startup info in case it is
needed.

[tests] Clear the adb log ater we collect the logcat output

---

src/Mono.Android/Android.Runtime/AndroidRuntime.cs

Adds a
`Java.Interop.JniRuntime.CreationOptions.UseMarshalMemberBuilder`
property which controls whether or not `Java.Interop.Export.dll` is
loaded during `JniRuntime` creation.
Xamarin.Android currently doesn't build, bundle, or otherwise include
`Java.Interop.Export.dll`, and thus the attempted assembly load
*always fails*, which is "fine" -- the exception is handled
appropriately -- but attempted load and corresponding exception
appears to add about ~100ms to process startup, which is insane.
Set `JniRuntime.CreationOptions.UseMarshalMemberBuilder=false` so that
we don't attempt to load this assembly, which should help our process
startup times.

Bump to xamarin/Java.Interop/master@706e4cc4

---

Makefile

We want the Mono upgrade to run *before* we run `/t:Restore`.
In one case downstream in monodroid, we encountered:
error MSB4244: The SDK resolver assembly "/Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/SdkResolvers/Microsoft.Build.NuGetSdkResolver/..\..\Microsoft.Build.NuGetSdkResolver.dll" could not be loaded. Invalid Image
This error normally means the file didn't exist, although it *should*.
That file was present in my Mono 5.16 installation.

[build] Makefile should run /t:Restore after dependencies.csproj

---

src/Xamarin.Android.Build.Tasks/Mono.Android/ActivityAttribute.Partial.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocumentElement.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
src/Xamarin.Android.NamingCustomAttributes/Android.App/ActivityAttribute.cs

Adds a number of attributes for an Activity that are supported in android
autoRemoveFromRecents
banner
colorMode
description(NOT FOUND IN DOCS, ONLY SOURCE)
enableVrMode
finishOnCloseSystemDiaglogs(NOT FOUND IN DOCS, ONLY SOURCE)
lockTaskMode(NOT FOUND IN DOCS, ONLY SOURCE)
logo(NOT FOUND IN DOCS, ONLY SOURCE)
maxAspectRatio
maxRecents
persistableMode
recreateOnConfigChanges(NOT FOUND IN DOCS, ONLY SOURCE)
relinquishTaskIdentity
resumeWhilePausing(NOT FOUND IN DOCS, ONLY SOURCE)
rotationAnimation(NOT FOUND IN DOCS, ONLY SOURCE)
showForAllUsers
showOnLockScreen(NOT FOUND IN DOCS, ONLY SOURCE)
singleUser
splitName
visibleToInstantApps(NOT FOUND IN DOCS, ONLY SOURCE)
see #1891

Add Missing Activity Attributes #1891

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs

Downstream in monodroid (commerical product), this test is failing:
Failed : Xamarin.Android.Build.Tests.IncrementalBuildTest.ProduceReferenceAssembly
`_BuildApkEmbed` should *not* be skipped!
When "Fast Deployment" is enabled, the `_BuildApkFastDev` MSBuild
target runs instead of `_BuildApkEmbed`.
To workaround it, we can just disable "Fast Deployment". We are really
just wanting to make sure `CoreCompile` is skipped in this test.

[tests] fix for ProduceReferenceAssembly test

---

src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/MonoAndroidHelperTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.Shared.projitems
src/Xamarin.Android.Build.Tasks/Utilities/Files.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs

In many places throughout the Xamarin.Android build, we have a pattern
of:
- Generate a temp file.
- Use `MonoAndroidHelper.CopyIfChanged` to put the file in the
destination. This reads both files, doing a hash comparison before
deciding to write or not.
- Delete the temp file.
Sometimes the temp file is actually in `%TEMP%`, but other times we
append `.new` to the destination file. The case of `.new` can collide
if two builds are running at once (example caused by a known VS for
Mac issue).
Thinking about this, in cases with small files, we can make a simple
optimization:
- Generate the file in-memory.
- Use a new `MonoAndroidHelper.CopyStreamIfChanged` method`.
This has several benefits:
- We never write a file to disk when there are no changes.
- We don't have to *remember* to delete …

[Xamarin.Android.Build.Tasks] don't use so many temp files

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

If the `_ValidateResourceCache` MSBuild target deems the cache file
invalid:
<Delete Files="$(_AndroidResourcePathsCache)" Condition=" '$(_IsResourceCacheValid)' == 'False' " />
The problem is that the `_BuildAdditionalResourcesCache` will be
skipped!
<Target Name="_BuildAdditionalResourcesCache"
Inputs="@(ReferencePath);@(ReferenceDependencyPaths);$(MSBuildProjectFullPath);$(NugetPackagesConfig);$(_AndroidBuildPropertiesCache)"
Outputs="$(_AndroidStampDirectory)_BuildAdditionalResourcesCache.stamp"
In eca09c89, I fixed a problem with `_BuildAdditionalResourcesCache`
running on every build by introducing a stamp file.
Since the `Outputs` are now the stamp file, we need to *also* delete
the stamp file when `'$(_IsResourceCacheValid)' == 'False'`. We had a
test checking this exact problem, …

[Xamarin.Android.Build.Tasks] _ValidateResourceCache incremental build issue

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/2507
Fixes: https://developercommunity.visualstudio.com/content/problem/400751/xamarin-android-build-failed-due-to-missing-folder.html
Context: https://github.com/xamarin/xamarin-android/issues/2173
Context: https://github.com/xamarin/xamarin-android/pull/2180

[Xamarin.Android.Build.Tasks] Support comma separators for armeabi error

---

src/monodroid/CMakeLists.txt
src/monodroid/jni/win32/jni_md.h

Context: https://github.com/xamarin/java.interop/issues/403
Make sure we use `__stdcall` when crosscompiling for mxe/win.
This allows us to crosscompile for Windows without installing Java SDK
for Windows.
The include path is put BEFORE other includes, so that the `jni_md.h`
is found before the one in Mac JDK, in `darwin` SDK subdirectory (like
`/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/include/darwin`).

[monodroid] Use right calling convention on Windows

---

build-tools/api-xml-adjuster/api-xml-adjuster.csproj

Since c93a8af changed some projects to netstandard 2.0, we also need
this project to be 4.6.1:
Microsoft.Common.CurrentVersion.targets(2110,5): Warning MSB3274: The primary reference "E:\A\_work\34\s\external\Java.Interop\bin\Debug\Xamarin.Android.Tools.ApiXmlAdjuster.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".
Which causes the error:
build-tools\api-xml-adjuster\Program.cs(12,18): Error CS0246: The type or namespace name 'JavaApi' could not be found (are you missing a using directive or an assembly reference?)
This doesn't seem to be a problem on Mono, just .NET framework.

[build] api-xml-adjuster needs TFV 4.6.1 on Windows

---

build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/DownloadUri.cs

Context: http://build.devdiv.io/2271113
Context: http://www.tugberkugurlu.com/archive/efficiently-streaming-large-http-responses-with-httpclient
We are still getting random OOM errors on Windows/VSTS:
android-toolchain.targets(52,5): Error : Unable to download URL `https://dl.google.com/android/repository/android-ndk-r14b-windows-x86_64.zip` to `C:\Users\dlab14\android-archives\android-ndk-r14b-windows-x86_64.zip`: Exception of type 'System.OutOfMemoryException' was thrown.
It turns out that if you don't specify
`HttpCompletionOption.ResponseHeadersRead`, then the entire request
body is buffered into a `MemoryStream`! This setting is what signals
the `HttpClient` to *NOT* buffer anything, so you can stream the file
to disk.
Since several of our Android SDK/NDK files are ~500MB, we could …

[xa-prep-tasks] "stream" http requests

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.CSharp.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
src/Xamarin.Android.Build.Tasks/Xamarin.Android.FSharp.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.VisualBasic.targets

Fixes https://github.com/mono/mono/issues/10602 .
From the issue:
```
We need to enable this to support the system assemblies conflict
resolution which we now rely on for any new packages to enhance
developers experience and get us out of dependency on specific package
versions.
```

[msbuild] Enable nuget package resolution

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.CSharp.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.props.in
src/Xamarin.Android.Build.Tasks/Xamarin.Android.FSharp.targets
src/Xamarin.Android.Build.Tasks/Xamarin.Android.VisualBasic.targets

Fixes https://github.com/mono/mono/issues/10602 .
From the issue:
```
We need to enable this to support the system assemblies conflict
resolution which we now rely on for any new packages to enhance
developers experience and get us out of dependency on specific package
versions.
```
Backport of #2481.
/cc @marek-safar @radical

[d16-0] [msbuild] Enable nuget package resolution

---

src/Xamarin.Android.Build.Tasks/Generator/Generator.cs
src/Xamarin.Android.Build.Tasks/Tasks/GenerateJavaStubs.cs
src/Xamarin.Android.Build.Tasks/Tasks/GenerateResourceDesigner.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/MonoAndroidHelperTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.Shared.projitems
src/Xamarin.Android.Build.Tasks/Utilities/Files.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs

Context: https://github.com/xamarin/xamarin-android/pull/2505
This is based on #2505, but I incorporated the java.interop changes so
`GenerateJavaStubs` uses no temp files at all.
In many places throughout the Xamarin.Android build, we have a pattern
of:
- Generate a temp file.
- Use `MonoAndroidHelper.CopyIfChanged` to put the file in the
destination. This reads both files, doing a hash comparison before
deciding to write or not.
- Delete the temp file.
Sometimes the temp file is actually in `%TEMP%`, but other times we
append `.new` to the destination file. The case of `.new` can collide
if two builds are running at once (example caused by a known VS for
Mac issue).
Thinking about this, in cases with small files, we can make a simple
optimization:
- Generate the file in-memory.
- Use a …

[Xamarin.Android.Build.Tasks] no temp files in GenerateJavaStubs

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Context: http://build.devdiv.io/2279876&view=ms.vss-test-web.test-result-details
There are about 5 tests that seem to fail a lot on new build machines.
The errors are generally related to file sharing:
The last access/last write time on file "C:\Users\dlab14\.nuget\packages\xamarin.forms\3.1.0.697729\lib\MonoAndroid10\FormsViewGroup.dll.mdb" cannot be set.
Access to the path 'C:\Users\dlab14\.nuget\packages\xamarin.forms\3.1.0.697729\lib\MonoAndroid10\FormsViewGroup.dll.mdb' is denied.
Or another example:
C:\Users\dlab14\.nuget\packages\xamarin.build.download\0.4.9\build\Xamarin.Build.Download.targets(114,3): The process cannot access the file 'C:\Users\dlab14\.nuget\packages\xamarin.googleplayservices.gcm\60.1142.1\lib\MonoAndroid80\Xamarin.GooglePlayServices.Gcm.dll' because it is being …

[tests] mark flaky tests NonParallelizable

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs

When reviewing `ResolveLibraryProjectImports`, I noticed a few things
we could improve:
1. We are using `GetResourceData` to get the entire contents of a file
as a `byte[]` and then writing to disk.
2. We are writing temporary zip files to disk, reading them to extract,
then deleting them.
The first thing I did was take advantage of the `GetResourceStream`
method, so we could just do `stream.CopyTo(file)`. This prevents us
from allocating big `byte[]` the size of each file.
Next, I took advantage of `ZipArchive.Open (stream)` and
`GetResourceStream` to avoid the need for creating temporary zip
files. We can unzip directly from the `Stream` in memory.
When timing these changes, I used the Xamarin.Forms integration
project in this repo:
Before
1. 1793 ms  ResolveLibraryProjectImports …

[Xamarin.Android.Build.Tasks] ResolveLibraryProjectImports temp files

---

build-tools/Xamarin.Android.Tools.BootstrapTasks/Xamarin.Android.Tools.BootstrapTasks/RenameTestCases.cs

Context: https://jenkins.mono-project.com/job/xamarin-android-pr-builder-release/189/
Commit c38c58e9 updated the `<RenameTestCases/>` task so that if the
NUnit XML output file couldn't be found, we would instead *generate* a
"reasonable" NUnit XML file containing an error, so that Jenkins would
nicely show that *something* went wrong.
The result is that it works, but isn't "nice": the Test Result failure
is a *filesystem path*, e.g.
/Users/builder/jenkins/workspace/xamarin-android-pr-builder-release/xamarin-android/build-tools/scripts/../../TestResult-Xamarin.Android.EmbeddedDSO_Test.nunit-Release-Aot.xml.TestResult-Xamarin.Android.EmbeddedDSO_Test.nunit-Release-Aot.xml
(That's *literally* the name of a "failing test.")
Additionally, the [*contents* of the generated file][0] aren't …

[Xamarin.Android.Tools.BootstrapTasks] Include Logcat in errors

---

Xamarin.Android.sln
build-tools/scripts/RunTests.targets
build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/RunParallelTargets.cs
build-tools/xa-prep-tasks/xa-prep-tasks.csproj

Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1331/
Context: https://github.com/xamarin/xamarin-android/issues/2397
Context: 5eae6e55190e3c30d3844c92d557128f872caa22
Commit 91a39725 updated `make run-all-tests` so that certain MSBuild
unit test targets would be run in parallel, but had two flaws:
1. It only worked on non-Windows platforms.
2. It ignored many errors.
Commit 91a39725 only worked on non-Windows platforms because it worked
by generating a **bash**(1)-compatible shell script which
*backgrounded* the target invocations.  Errors were ignored because
the generated script always exited with an error code of 0:
msbuild RunTests.targets /t:RunNUnitTests &
msbuild RunTests.targets /t:RunApkTests &
exit 0
Such a script won't easily run on Windows, …

[tests] Run tests in parallel

---

src/monodroid/jni/monodroid-glue.c

Fixes: https://github.com/xamarin/xamarin-android/issues/2257
We should release local ref earlier in these cases, because with
higher number of assemblies we can overflow the local reference table
soon enough, before returning from native code.
In case of apks it is not as much probable, but why not release it and
not take a chance.

[monodroid] Release local refs earlier (#2312)

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

* [Xamarin.Android.Build.Tasks] Fix Aar directory resolution.
Fixed #2408
As part of the speed up process when extracting resources
from assemblies and Aar files, we dont re-extract if
the stamp file is newer than the assembly.
The problem with that was in the case of Aar files we
were NOT adding the `res` or `asset` directories to
the list of resolved directories when we skipped extraction.
As a result we got less `res` directories on a second
build.
This commit fixes that.
* Add Unit Test
* Fix Compile Error

[Xamarin.Android.Build.Tasks] Fix Aar directory resolution. (#2424)

---

build-tools/create-vsix/create-vsix.csproj

Downstream in monodroid, we are getting a build error during a
`Release` build:
xamarin-android/src/libzip/libzip.targets(16,5): error MSB4062: The "Xamarin.Android.BuildTools.PrepTasks.GitCommitTime" task could not be loaded from the assembly xamarin-android/build-tools/scripts/../../bin/BuildDebug/xa-prep-tasks.dll. Invalid Image Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
The path here is wrong, we should not be looking in `BuildDebug`
during a `Release` build.
I opened Xamarin.Android.sln in Visual Studio (on Windows), and in the
`Configuration Manager` `create-vsix.csproj` was listed as building
`Debug` for `Release` builds! The …

[build] create-vsix.csproj should have Release configuration

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Expected/GenerateDesignerFileExpected.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManagedResourceParser.cs

Context: https://github.com/xamarin/xamarin-android/pull/2546
Changes: https://github.com/xamarin/xamarin-android-api-compatibility/compare/ec562e9...3fe4561
Bumps to xamarin/xamarin-android-api-compatibility/master@3fe4561
This partially reverts 0f91aea.
In #2546, we experienced a bit of API breakage when disabling
`$(AndroidUseAapt2)`. We want to fix the breakage in master, but keep
`$(AndroidUseAapt2)` turned on by default.
We need to put the `ManagedResourceParser` back the way it was before
0f91aea, except for `Resource.Attribute`.
Since `aapt`(1) always emits this class, we should replicate that.

[Xamarin.Android.Build.Tasks] fix ManagedResourceParser API breakage

---

Documentation/building/unix-instructions.md
Makefile
tests/RunApkTests.targets

Make it possible to run selected apk tests by passing `TESTS` variable
to `make`.
Example usage:
make run-apk-tests TESTS="Xamarin.Forms_Performance_Integration;Xamarin.Android.Locale_Tests"
Or msbuild equivalent:
msbuild /t:RunApkTests tests/RunApkTests.targets /p:ApkTests='"Xamarin.Forms_Performance_Integration;Xamarin.Android.Locale_Tests"'
The relevant part of the output of the msbuild example above looks like:
UndeployTestApks:
Executing: /Users/rodo/android-toolchain/sdk/platform-tools/adb   uninstall "Xamarin.Android.Locale_Tests"
Executing: /Users/rodo/android-toolchain/sdk/platform-tools/adb   uninstall "Xamarin.Forms_Performance_Integration"
DeployTestApks:
Executing: /Users/rodo/android-toolchain/sdk/platform-tools/adb   install …

[tests] Allow running only selected apk tests

---

.gitmodules

Context: https://blade.tencent.com/magellan/index_en.html
Context: https://worthdoingbadly.com/sqlitebug/
Includes SQLite fixes between 2018-09-25 and 2018-12-01, bringing us
to SQLite 3.26.0.

Update SQLite to 3.26.0

---

src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

We had an issue where the `_CopyPackageInputs` was occasionally
NOT including a changed apk! It was really weird.
So lets rework this to define the `_CopyPackageInputs`
Property within a Target. This should allow it to pick
up and dynamically added Items.

[Xamarin.Android.Build.Tasks] Fix a weird error with `_CopyPackage`

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs

PR #2515 highlighted an issue with a few of our
repeat build tests. Tests were failing because
the `_Sign` target was being skipped. Looking
at the build logs, `BuildApk` was being called.
As was `_CreateBaseApk`, so what is going on?
So it turns out that in `BuildApk` we use the
`CopyZipIfChanged` method to move the temp
zip file over to the actual one. In this case
... the zip was identical! So the "new" zip
was not copied.. and so the `_Sign` task did
not need to run.
How can the zip be the same? It had an updated
file? Well wrong.. we just touched the timestamp.
In which case the zip ends up with the exact same
CRC values for each file. We use the CRC to detect
changes.. so no changes. So it turns out our build
system was behaving as expected.. it was just our
test was invalid.
So the …

[Xamarin.Android.Build.Tests] Fix Repeat Build Tests

---

src/Mono.Android/Mono.Android.targets
src/Mono.Android/Test/Mono.Android-Test.Shared.projitems
src/Mono.Android/Test/Mono.Android-Tests.csproj

There are two scenarios of consequence when building
`src/Mono.Android/Mono.Android.csproj`:
1. When it hasn't previously built, e.g. a fresh checkout or
`git clean`'d tree.
2. When it *has* been previously built.
When building `Mono.Android.csproj` for the first time, there are 38
warnings produced.
When building `Mono.Android.csproj` afterward, there are *4400*
warnings, 3862 of which are CS2002 warnings:
warning CS2002: Source file 'obj/Debug/android-28/mcw/Android.AccessibilityServices.AccessibilityButtonController.cs' specified multiple times
...
What's going on here?
The cause is twofold: commit 98880bd5, and MSBuild's behavior of
evaluating `<ItemGroup/>` and `<PropertyGroup/>`s for Targets which
are *not executed*.
Prior to commit 98880bd5, initial builds would *fail*, as per …

[Mono.Android] Remove CS2002 build warnings

---

src/Xamarin.Android.Build.Tasks/Tasks/CopyResource.cs
src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
src/Xamarin.Android.Build.Tasks/Utilities/XDocumentExtensions.cs

In various places throughout our build, we are still using a pattern
such as:
try {
var temp = Path.GetTempFileName ();
//Write to the file
MonoAndroidHelper.CopyIfChanged (temp, dest);
} finally {
File.Delete (temp);
}
Or sometimes variations that aren't even as nice as this...
We can instead use the new `MonoAndroidHelper.CopyIfStreamChanged`
method and not use any temp files.
This MSBuild task had its own `CopyIfStreamChanged` behavior, and it
has been around a while. I was able to remove a lot of code from this
MSBuild task; it is much simpler now.
Other changes:
- We don't really need an extra `Run` method here.
- If we are putting `Assembly.GetExecutingAssembly ()` in a static
variable, let's put the jcwgen assembly in one as well.
- Use string interpolation: `$`
Each had a simple …

[Xamarin.Android.Build.Tasks] remove more %temp% file usage

---

CODEOWNERS
src/monodroid/jni/android-system.cc
src/monodroid/jni/cpu-arch-detect.cc
src/monodroid/jni/debug.cc
src/monodroid/jni/dylib-mono.cc
src/monodroid/jni/embedded-assemblies.cc
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/monodroid-networkinfo.cc
src/monodroid/jni/osbridge.cc
src/monodroid/jni/timezones.cc
src/monodroid/jni/util.cc
src/monodroid/jni/xamarin_getifaddrs.cc

In effort to morph our current code to modern C++, this commit replaces all the
`NULL` macro instances with the C++ standard `nullptr` type. No functional
changes are present in this commit.
The only exception here is the `xamarin_getifaddrs.cc` file in which the reverse
operation is done - replacement of `nullptr` with `NULL`. The reason for this is
that the file is destined to be moved to the Mono codebase at some point and so,
at least for now, it should remain standard C99

[C++] Cosmetic changes to the code: NULL -> nullptr

---

build-tools/scripts/XAVersionInfo.targets
build-tools/xa-prep-tasks/Xamarin.Android.BuildTools.PrepTasks/GitBlame.cs

Downstream in monodroid, I'm getting a build failure such as:
/usr/bin/git blame "/full/path/to/external/xamarin-android/Configuration.props"
XAVersionInfo.targets(53,5): error MSB6006: "git" exited with code 128.
XAVersionInfo.targets(61,5): error MSB4044: The "GitCommitsInRange" task was not given a value for the required parameter "StartCommit".
If I run the git command manually:
fatal: not a git repository (or any of the parent directories): .git
It seems we shouldn't be using a full path here, but use
`WorkingDirectory` instead? Maybe it will not work if
`xamarin-android` is a submodule?
This has somehow been working in the past, so perhaps my version of
git is the cause?
$ git --version
git version 2.17.1 (Apple Git-112)

[build] use WorkingDirectory for <GitBlame/>

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveLibraryProjectImports.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

The Xamarin.Android designer uses the paths found in
`libraryprojectimports.cache`, and recently was coming up with some
odd paths in test failures:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\obj\Debug\90\lp\2\jl\res
Looking at the contents of `libraryprojectimports.cache`, some of the
paths were no longer full paths:
<Paths>
...
<ResolvedResourceDirectories>
<ResolvedResourceDirectory>obj\Debug\81\lp\6\jl\res</ResolvedResourceDirectory>
<ResolvedResourceDirectory>obj\Debug\81\lp\9\jl\res</ResolvedResourceDirectory>
<ResolvedResourceDirectory>obj\Debug\81\lp\11\jl\res</ResolvedResourceDirectory>
<ResolvedResourceDirectory>obj\Debug\81\lp\12\jl\res</ResolvedResourceDirectory>
<ResolvedResourceDirectory>obj\Debug\81\lp\13\jl\res</ResolvedResourceDirectory> …

[Xamarin.Android.Build.Tasks] designer needs full paths in libraryprojectimports.cache

---

src/monodroid/jni/embedded-assemblies.cc
src/monodroid/jni/embedded-assemblies.h
src/monodroid/jni/globals.cc
src/monodroid/jni/globals.h
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/util.h

* removed a number of `MONO_API` functions, they don't appear to be used anywhere (were supposed to be used by Mono Unreal Engine, but we're not sure if that's the case). We can restore them if needed
* Simplified a lot of code
* Removed `printf` family calls

[C++-ification] Introducing EmbeddedAssemblies class

---

src/libzip/libzip.targets

Downstream in monodroid, we are getting a build failure such as:
"/Users/builder/jenkins/workspace/monodroid-pr/monodroid/tools/msbuild/Xamarin.Android.Build.Tasks.sln" (default target) (1) ->
"/Users/builder/jenkins/workspace/monodroid-pr/monodroid/tools/msbuild/Xamarin.Android.Build.Debugging.Tasks.csproj" (default target) (6) ->
(_CopyOutOfDateSourceItemsToOutputDirectoryAlways target) ->
/Library/Frameworks/Mono.framework/Versions/5.18.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(4584,5): error MSB3027: Could not copy "/Users/builder/jenkins/workspace/monodroid-pr/monodroid/external/xamarin-android/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/libzip.5.0.dylib" to "/Users/builder/jenkins/workspace/monodroid-pr/monodroid/out/lib/xamarin.android/xbuild/Xam …

[libzip] remove CopyToOutputDirectory

---

src/monodroid/jni/embedded-assemblies.cc
src/monodroid/jni/embedded-assemblies.h
src/monodroid/jni/monodroid-glue.cc
src/monodroid/jni/util.cc
src/monodroid/jni/util.h

* Use `new/delete/delete[]` more
* Avoid calling the `printf` family of functions in favor of new, template, `string_concat` in the `Utils` class. When `sprintf` is used to concatenate just strings we can do better by not calling the C varargs functions and generate very efficient code.
* Replace C `strdup` calls with our, based on `new`, strdup implementation

[C++ification] Glue and utilities code changes

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Fixes: https://github.com/xamarin/xamarin-android/issues/2548
Fixes: http://work.devdiv.io/753650
In the case of the Android designer, a `SetupDependenciesForDesigner`
target is run as a way to "build enough" things for the designer to
work.
The problem is if a `<ProjectReference/>` hasn't built yet, the
`_ResolveAssemblies` target can fail:
"HelloForms.Android.csproj" (SetupDependenciesForDesigner target) (1:7) ->
(_ResolveAssemblies target) ->
Xamarin.Android.Common.targets(1898,2): error : Exception while loading assemblies: System.InvalidOperationException: Failed to load assembly HelloForms\bin\Debug\netstandard2.0\HelloForms.dll
Xamarin.Android.Common.targets(1898,2): error :    at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)
In this case, I …

[Xamarin.Android.Build.Tasks] _ResolveAssemblies better handle missing assemblies

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
src/Xamarin.Android.Build.Tasks/Utilities/DummyCustomAttributeProvider.cs
src/Xamarin.Android.Build.Tasks/Utilities/MetadataExtensions.cs
src/Xamarin.Android.Build.Tasks/Utilities/MetadataResolver.cs
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj
src/Xamarin.Android.Build.Tasks/packages.config
tools/xabuild/xabuild.csproj

Context: https://github.com/dotnet/corefx/tree/master/src/System.Reflection.Metadata/src/System/Reflection/Metadata
Context: https://github.com/jonathanpeppers/Benchmarks
There is a new System.Reflection.Metadata library from corefx for
reading .NET assemblies. It is a bit more performant than Mono.Cecil
because it is a different library with different opinions.
Some notes about System.Reflection.Metadata:
- SRM has a forward "reader" style API
- SRM uses lots of structs, and you have to do an additional call to
lookup strings generally.
- SRM, as far as I have seen, doesn't have APIs to modify and write
out new assemblies.
- SRM only supports "portable" pdb files.
- SRM is not well documented yet. To discover usage, I read source
code and/or unit tests.
From my benchmark above, it seems …

[Xamarin.Android.Build.Tasks] use System.Reflection.Metadata in <ResolveAssemblies/>

---

src/monodroid/jni/logger.c
src/monodroid/jni/logger.h
src/monodroid/jni/monodroid-glue.cc

Implements https://github.com/xamarin/xamarin-android/issues/2610
It is possible to set log to timing=bare to avoid employing the
performance counters.
Example:
adb shell setprop debug.mono.log timing=bare
This way we can get closer to "normal" app run times.
Comparison of XF test on Pixel XL 2:
Before:
Time:    328ms Message: monodroid-timing: Runtime.init: end, total time; elapsed: 0s.18432517441218359126::16774850937603807740
Time:    329ms Message: monodroid-timing: Runtime.init: end, total time; elapsed: 0s.18432517441218787043::16774850937603807745
Time:    337ms Message: monodroid-timing: Runtime.init: end, total time; elapsed: 0s.18432517441219141783::16774850937603807750
Time:    320ms Message: monodroid-timing: Runtime.init: end, total time; elapsed: …

[monodroid] Add log timing categories

---

src/Xamarin.Android.Build.Tasks/Tasks/GeneratePackageManagerJava.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Commit b90d3ab7 altered where we generate the Guid for the
`XAMARIN_BUILD_ID`. This change resulted in the `_CompileJava`
target running on every build. This was because the Guid and
the resultng `AndroidEnvironment.java` file changed on every
build.
The `XAMARIN_BUILD_ID` should only change when an apk is
built. This is so the same id can be written to both the
apk and the msym archive.
There was also a problem on windows where the design time
build would trigger `_GeneratePackageManagerJava` to run.
This was down to the the following file being updated
<Project>.csproj.CoreCompileInputs.cache
This would cause a cascade because once `_GeneratePackageManagerJava`
ran, this would then trigger `_CompileJava` and then other
targets.
Looking at `GeneratePackageManagerJava` we don't actually …

[Xamarin.Android.Build.Tasks]  Fix problem with `_CompileJava` running always.

---

src/Xamarin.Android.Build.Tasks/Tasks/GetAdditionalResourcesFromAssemblies.cs

Just like in c22475d, we can use System.Reflection.Metadata in places
over Mono.Cecil for performance benefits.
On such case is the `<GetAdditionalResourcesFromAssemblies/>` MSBuild
task, which only looks at custom attributes in assemblies:
Before
1st:          98 ms  GetAdditionalResourcesFromAssemblies       1 calls
Incremental: 105 ms  GetAdditionalResourcesFromAssemblies       1 calls
After
1st:          54 ms  GetAdditionalResourcesFromAssemblies       1 calls
Incremental:  53 ms  GetAdditionalResourcesFromAssemblies       1 calls
This was a straightforward port to SRM, which seems to save ~50ms on
every build.

[Xamarin.Android.Build.Tasks] SRM in <GetAdditionalResourcesFromAssemblies/>

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
tests/EmbeddedDSOs/EmbeddedDSO/Properties/AndroidManifest.xml

Fixes #2081
If a user needs to use the `directBootAware` attribute on
an `application`, `activity` or `service` we also need
to include it on the `MonoRuntimeProvider` so that
native libraries can be resolved correctly. Not doing
so results in the following
java.lang.UnsatisfiedLinkError: No implementation found for void mono.android.Runtime.register
This commit looks to see if any elements in the manifest
contain `directBootAware`. If there are , then we also
include it in the `provider`.

[Xamarin.Android.Build.Tasks] Add `directBootAware` if needed.

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/ManifestTest.cs
src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs
tests/EmbeddedDSOs/EmbeddedDSO/Properties/AndroidManifest.xml

Fixes: https://github.com/xamarin/xamarin-android/issues/2081
Context? http://work.devdiv.io/727120
The [`//application/@android:directBootAware`][0] attribute *changes*
how process startup semantics work, in [non-obvious ways][1].
Consider the following:
1. Start with an Android v7.0 Nougat device.
2. Build, Install, & Run the [Direct Boot Sample][2]
3. Create an alarm within the Direct Boot Sample app.
4. Reboot the Android device.
5. Wait for the alarm to go off without unlocking the device.
Expected results: An alarm goes off.
Actual results: Nothing happens, and `adb logcat` contains:
java.lang.UnsatisfiedLinkError: No implementation found for void mono.android.Runtime.register(java.lang.String, java.lang.Class, java.lang.String) (tried Java_mono_android_Runtime_register and …

[Xamarin.Android.Build.Tasks] Add `directBootAware` if needed. (#2621)

---

src/Xamarin.Android.Build.Tasks/ILRepack.targets
tools/xabuild/XABuild.cs
tools/xabuild/xabuild.csproj

Downstream in monodroid, I attempted to use the final pkg file for the
Xamarin.Android commercial product.
Unfortunately, building a Xamarin.Android project fail with:
$ msbuild HelloForms/HelloForms.Android/HelloForms.Android.csproj /t:SignAndroidPackage /restore /bl
...
"HelloWorld/HelloForms/HelloForms.Android/HelloForms.Android.csproj" (SignAndroidPackage target) (1:7) ->
(_ResolveAssemblies target) ->
Xamarin.Android.Common.targets(1930,2): error : Exception while loading assemblies: System.MissingMethodException: Method not found: System.Reflection.AssemblyName System.Reflection.Metadata.AssemblyDefinition.GetAssemblyName() [HelloWorld/HelloForms/HelloForms.Android/HelloForms.Android.csproj]
Xamarin.Android.Common.targets(1930,2): error :   at …

[Xamarin.Android.Build.Tasks] ILRepack SRM

---

src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets

Currently the `<GenerateJavaStubs/>` MSBuild task will load and
iterate over NetStandard or PCL assemblies. It simply looks at all
items in `@(_ResolvedUserAssemblies)` and writes Java stubs if needed.
We could look at the `TargetFrameworkIdentifier` and *only* do this
work for `MonoAndroid` assemblies.
To make this work:
- The `<ResolveAssemblies/>` MSBuild task needs to parse the
`TargetFrameworkIdentifier` and add it to the item metadata for each
assembly.
- `<GenerateJavaStubs/>` should use a subset of
`@(_ResolvedUserAssemblies)` where `TargetFrameworkIdentifier` is
`MonoAndroid`.
Results:
Before
First:       1200 ms  GenerateJavaStubs                          1 calls
Incremental: 1047 ms  GenerateJavaStubs                          1 calls
After
First:       1084 ms …

[Xamarin.Android.Build.Tasks] <GenerateJavaStubs/> only for MonoAndroid assemblies

---

build-tools/cmake/xa_macros.cmake
src/monodroid/CMakeLists.txt
src/sqlite-xamarin/CMakeLists.txt

Move some macros to a CMake module file so that they can be shared by all the
native code we build with CMake:
* Macros to check for compiler+linker flags
* Add a macro to set common compiler+linker flags

[build] Small CMake reorganization

---

src/Xamarin.Android.Build.Tasks/ILRepack.targets

We saw the following error in the latest versions of monodroid.
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1928,2): error : Could not load file or assembly 'NuGet.ProjectModel, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
After investingating it turns out that the
`Xamarin.Android.Build.Tasks` project was being run
multiple times (as expected). However the
`CopyFilesToOutputDirectory` target was being run
on the second build. This was also running the
internal target `_CopyFilesMarkedCopyLocal`.
The result of both of these targets was to copy
over the old assembly over the ILRepacked version
and copy over ALL the NuGet assemblies from the
nuget packages cache.
This then turns into the …

[Xamarin.Android.Build.Tasks] Run ILRepack if `NuGet.ProjectModel` Exists

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidUpdateResourcesTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/IncrementalBuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/PackagingTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Utilities/BuildHelper.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/DotNetXamarinProject.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs
src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets
tests/CodeBehind/UnitTests/BuildTests.cs
tests/CodeGen-MkBundle/Xamarin.Android.MakeBundle-UnitTests/BuildTests.cs
tests/EmbeddedDSOs/EmbeddedDSO-UnitTests/BuildTests.cs

Context: https://github.com/xamarin/xamarin-android/wiki/IDE-Performance-Results
Context: https://github.com/jonathanpeppers/HelloWorld
When doing some performance measurements *inside* of Visual Studio, I
noticed we seem to have significant overhead in a build with no
changes.
In a "Hello World" Xamarin.Forms app:
Preparation Time: 00:03.9
Launch Time:      00:02.5
Where `Preparation Time` is everything MSBuild, and `Launch Time` is
the time it takes to start the Android application and attach the
debugger.
`Preparation Time` is effectively:
msbuild Foo.Android.csproj /p:BuildingInsideVisualStudio=True /t:Build
msbuild Foo.Android.csproj /p:BuildingInsideVisualStudio=True /t:Install
One concern here is that `Install` depends on `SignAndroidPackage`,
which depends on `Build`. We are doing …

[Xamarin.Android.Build.Tasks] Install should skip Build when inside the IDE

---

build-tools/dependencies/dependencies.projitems

Updates the minimum required MDK version to the same commit currently
referenced in external/mono. This brings in a bunch of fixes that have
since been applied to the mono/mono:2018-08 branch.
From recent testing, this also appears to resolve the Android SDK download failures
we've been seeing intermittently on machines which don't already have these
components fully cached:
```
2019-01-29T18:05:08.0179160Z (_DownloadItems target) -> 
2019-01-29T18:05:08.0180480Z   /Users/vsts/agent/2.144.2/work/1/s/external/xamarin-android/build-tools/android-toolchain/android-toolchain.targets(42,5): error : Unable to download URL `https://dl.google.com/android/repository/platform-26_r02.zip` to `/Users/vsts/android-archives/platform-26_r02.zip`: An error occurred while sending the request …
```

Bump `ManagedRuntime` dependency

---

src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/ProjectBuilder.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/SolutionBuilder.cs

Downstream in monodroid, we have the need to run some designer-related
tests agains projects that haven't restored NuGet packages yet.
Unfortunately, there wasn't a way to do this in our MSBuild tests.
To better support these tests:
- Added a `AutomaticNuGetRestore` property which defaults to `true`.
These tests could turn this off.
- Any calls to `project.NuGetRestore` now check
`AutomaticNuGetRestore`. These supported `packages.config` and call
`nuget.exe` directly.
- Made the `/restore` flag check `AutomaticNuGetRestore`, and also set
this up to check that `PackageReferences > 0`. This will help our
tests be a bit faster when there are no `PackageReferences`.

[Xamarin.ProjectTools] support for disabling automatic NuGet restore

---

Configuration.props
build-tools/dependencies/dependencies.projitems

Context: https://github.com/xamarin/xamarin-android/pull/2357
Context: https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1239/console
We are experiencing a number of hangs from mono while running our unit
tests, seemingly around process exit; see e.g. [Jenkins build 1442][0]
which is a hang from executing `EmbeddedDSOUnitTests.dll`, or
[Jenkins build 1436][1], which is a hang from executing
`Xamarin.Android.MakeBundle-UnitTests.dll`, or...
One theory (hope? desire?) is that some of our apparent deadlocks may
be fixed by [this deadlock fix in mono][2], the fix for which is
present in `MonoFramework-MDK-5.18.0.249.macos10.xamarin.universal.pkg`.
Update `$(_DarwinMonoFramework)` and
`$(MonoRequiredDarwinMinimumVersion)` so that Mono 5.18.0.249 is
installed on our …

[build+macOS] Build with MDK 5.18.0.249

---

build-tools/timing/timing.targets

Context: https://github.com/Microsoft/SmartHotel360-Mobile
Downstream in monodroid we building the SmartHotel360 app as part of
our MSBuild timings.
The problem is the following set of git commands:
git clone https://github.com/Microsoft/SmartHotel360-Mobile.git --depth=1
git checkout ad41901761df12802ab332d78b9eedb3248f3f1e
If ad41901761df12802ab332d78b9eedb3248f3f1e is not the latest commit,
this command will fail with:
fatal: reference is not a tree: ad41901761df12802ab332d78b9eedb3248f3f1e
I invadvertantly broke this by updating our fork to latest
Microsoft/SmartHotel360-Mobile/master. Whoops!
Some options to fix this would be:
1. Create a branch, then don't ever touch it! Use `--branch` during
the `git clone`.
2. Don't use `--depth=1` at all.
Looking into it `--depth=1` is not saving …

[timing] don't use --depth=1 for git clone

---

src/monodroid/jni/dylib-mono.cc
src/monodroid/jni/dylib-mono.h
src/monodroid/jni/monodroid-glue.cc

The callback functions definitions:
https://github.com/mono/mono/blob/2359cba40e94accdcf5ce526572bce834d53f3aa/mono/metadata/profiler-events.h#L50
https://github.com/mono/mono/blob/2359cba40e94accdcf5ce526572bce834d53f3aa/mono/metadata/profiler-events.h#L103
https://github.com/mono/mono/blob/2359cba40e94accdcf5ce526572bce834d53f3aa/mono/metadata/profiler-events.h#L105

[monodroid] Improve type safety of recently added functions

---

src/Xamarin.Android.Build.Tasks/Tasks/NdkUtils.cs
src/Xamarin.Android.Build.Tasks/Tasks/NdkUtilsOld.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/NdkUtilTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj
src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs

The r19 Ndk on windows does not use `.exe` files
for some of its compiler tools. It uses `.cmd`.
As a result our current setup will not find these
files and you end up with errors like
error XA5101: Toolchain utility 'armv7a-linux-androideabi16-clang.exe' for target Arm was not found. Tried in path: "C:\Users\dlab14\android-toolchain\ndk\toolchains\llvm\prebuilt\windows-x86_64"
This commit changes the code to use the
`MonoAndroidHelper.GetExecutablePath` method which
uses the `PATHEXT` environment variable to search
for various exe file extensions.

[Xamarin.Android.Build.Tasks] Fix Ndk .exe lookup.

---

src/monodroid/jni/embedded-assemblies.cc
src/monodroid/jni/embedded-assemblies.h

When using fastdev typemaps we get the following error
```
01-31 10:57:34.336  5802  5802 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 5802 (haredandroidios), pid 5802 (haredandroidios)
01-31 10:57:34.358  5829  5829 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-31 10:57:34.358  1685  1685 I /system/bin/tombstoned: received crash request for pid 5802
01-31 10:57:34.359  5829  5829 I crash_dump32: performing dump of process 5802 (target tid = 5802)
01-31 10:57:34.363  5829  5829 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-31 10:57:34.363  5829  5829 F DEBUG   : Build fingerprint: 'Android/sdk_phone_x86/generic_x86:9/PSR1.180720.012/4923214:userdebug/test-keys'
01-31 10:57:34.363 …
```

[monodroid] Fix runtime crash when using fastdev typemaps

---

Documentation/guides/messages/xa4216.md
src/Xamarin.Android.Build.Tasks/Tasks/GetJavaPlatformJar.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/2692
Xamarin.Android does not currently support devices less than API-9.
The resulting `.apk` file will reference the
[`ApplicationInfo.nativeLibraryDir` field][1], which was added in
API-9, and thus may prevent `classes.dex` from being loaded.
A XA4216 warning is now issued, stating that this configuration
is not supported. Added a test verifying this warning.
[1]: https://developer.android.com/reference/android/content/pm/ApplicationInfo#nativeLibraryDir

[Xamarin.Android.Build.Tasks] warning if minSdkVersion < 9

---

src/monodroid/jni/dylib-mono.cc
src/monodroid/jni/dylib-mono.h
src/monodroid/jni/monodroid-glue.cc

Get more information with `debug.mono.log` property set to `timing`.
It hooks up to the profiler's `jit_begin` and `jit_done` events and
prints the method JIT begin and done times to `methods.txt`
Example output:
JIT method begin: Android.Runtime.JNIEnv:Initialize (Android.Runtime.JnienvInitializeArgs*) elapsed: 0s:97::383916
JIT method begin: Android.Runtime.JNIEnv:.cctor () elapsed: 0s:99::500999
JIT method  done: Android.Runtime.JNIEnv:.cctor () elapsed: 0s:99::626468
JIT method begin: (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr) elapsed: 0s:99::695999
JIT method  done: (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr) elapsed: 0s:99::913551
JIT method begin: Android.Runtime.JNIEnv/<>c:.cctor () elapsed: …

[monodroid] Make it possible to measure jit times

---

src/Xamarin.Android.Build.Tasks/Tasks/AndroidUpdateResDir.cs
src/Xamarin.Android.Build.Tasks/Tasks/CompileToDalvik.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs

Fixes #2685
In commit 8571a7f we switched the `CompileToDalvik` task over
to use the `--input-list` argument. This helped reduce the
overall length of the command line arguments passed. It
had a side effect of causing a problem if the path
contained non-ASCII characters. We end up with the
following error
java.io.FileNotFoundException: C:\Temp\Scratch.├£ml├ñ├╝ts\Scratch.├£ml├ñ├╝ts\obj\Debug\90\android\bin\classes.zip (The system cannot find the path specified)
This is because while the `input-list` file is fine,
the paths within it might contain non-ASCII characters.
So we need to let java know that, we can do that via the
file.encoding=UTF8
argument. `CompileToDalvik` can be run in two modes, the first
is just invoking the `dx` executable. The second is invoking
the `dx.jar` via `java`. …

[Xamarin.Android.Build.Tasks] Provide file.encoding for dx tool

---

Documentation/guides/messages/xa4216.md
src/Xamarin.Android.Build.Tasks/Tasks/GetJavaPlatformJar.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj

Context: https://github.com/xamarin/xamarin-android/pull/2698
In #2698, we added a new build warning for projects using a
`//uses-sdk/@android:minSdkVersion` lower than Xamarin.Android
supports. This change checking for API-9 was appropriate for 16.0, but
not 16.1/master.
We should instead use `XABuildConfig.NDKMinimumApiAvailable` to decide
to show these warnings or not. I updated the relevant test &
warning code documentation about this as well.
While using `XABuildConfig` in `Xamarin.Android.Build.Tests`, I
noticed a compiler warning. It seems the type was found twice, since
it has a reference to `Xamarin.Android.Build.Tasks`. We can remove the
`<Compile/>` item for `XABuildConfig.cs` in this project.

[Xamarin.Android.Build.Tasks] use NDKMinimumApiAvailable for minSdkVersion warning

---

src/Mono.Android/Test/Mono.Android-Tests.csproj
tests/Xamarin.Forms-Performance-Integration/Droid/Xamarin.Forms.Performance.Integration.Droid.csproj

Context: https://devdiv.visualstudio.com/DevDiv/_build?definitionId=7212
Context: http://build.devdiv.io/2391004
We are in the process of switching the Windows build on Azure DevOps
to build in `Release` `$(Configuration)`. This will more closely match
what we are doing on Jenkins for other platforms.
Unfortunately we get the following build failure in `Release`:
>.\bin\Release\bin\xabuild Xamarin.Android-Tests.sln /p:Configuration=Release
...
bin\Release\lib\xamarin.android\xbuild\Xamarin\Android\Xamarin.Android.Common.targets(2193,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
at MonoDroid.Tuner.MonoDroidMarkStep.UpdateMarshalTypes()
at …

[tests] don't enable $(AndroidGenerateJniMarshalMethods) on Windows

---

src/Xamarin.Android.Build.Tasks/Tasks/MakeBundleNativeCodeExternal.cs
src/Xamarin.Android.Build.Tasks/Tasks/NdkUtils.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Tasks/MakeBundleNativeCodeExternalTests.cs
src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/Xamarin.Android.Build.Tests.csproj

Fixes: https://github.com/xamarin/xamarin-android/issues/2708
Move the check for a `null` or empty `AndroidNdkDirectory` from
`MakeBundleNativeCodeExternal.Execute()` into
`NdkUtil.ValidateNdkPlatform()`, and update the error message.  Make
`ValidateNdkPlatform()` fail with that same error if it cannot get the
version of the NDK.  That way, the `MakeBundleNativeCodeExternal` and
`Aot` tasks will both hit that new updated error first before they try
to call any other methods from `NdkUtil`.  This solves the problems from
the linked issue.  In short, the two tasks were each producing a
different error message when invoked with an invalid or missing
`AndroidNdkDirectory`, and neither message suggested how to resolve the
error.

[Xamarin.Android.Build.Tasks] Improve Android NDK validation errors
